### ISSUE TITLE
Corrupted JavaScript for class instances with point-free declarations

### ISSUE THREAD

**Issue by mrhania** [purescript/purescript#1000]
Consider following code:
```purescript
data Foo

instance eqFoo :: Eq Foo where
  (==) _ _ = false
  (/=) = (==)
```
The compiler will then produce
```javascript
var eqFoo = new Prelude.Eq(Prelude["=="](eqFoo), function (_0) {
    return function (_1) {
        return false;
    };
});
```
which will fail to load since `eqFoo` is `undefined` when defining `eqFoo`, thus `Prelude["=="](eqFoo)` will try to lookup `"=="` on `undefined`.

**Comment by garyb** [comment]
This is #365 again I think. Thanks for the simple example though.

**Comment by mrhania** [comment]
> This is #365 again I think.

Ouch, right. I have been looking only under *codegen* label so I missed that one.

**Comment by garyb** [comment]
Ah yep, I've added a `codegen` label for that one too.

**Comment by paf31** [comment]
Fixed
