### ISSUE TITLE
Function that appends a row

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript#1005]
I'd like a function of the form:
```purs
onClick :: forall a. a -> String -> {click :: String | a}
onClick b s = {click: s | b}
```

but I receive syntax errors.

This even produces "kind unification" errors:
```purs
onClick :: forall a. String -> (click :: String | a)
onClick s = {click: s}
```
```purs
  Cannot unify kind
    *
  with kind
    # *
```

This sort of makes sense, since the types of kind `# *` should be uninhabited, but how do I declare a function that takes a row type and returns a different row type parameterized by the input?

**Comment by garyb** [comment]
We can't do that at the moment as there is no "lacks constraint" for rows; in the example above we'd need to type `a` as not having `click`.

**Comment by garyb** [comment]
Related: #469

**Comment by paf31** [comment]
The original problem can be solved using

```purescript
onClick :: forall a. { | a } -> String -> { click :: String | a }
```

and the FFI, or


```purescript
onClick :: forall a. { click :: String | a } -> String -> { click :: String | a }
```

and a record update. The more general problem will be solvable via the FFI once #469 is implemented.
