### ISSUE TITLE
Control-D in psci should quit

### ISSUE THREAD

**Issue by enolan** [purescript/purescript#1013]
This is standard behavior in pretty much every repl. I'm using 0.6.9.3 from Hackage.

**Comment by puffnfresh** [comment]
:+1:

**Comment by paf31** [comment]
Control-D is used to signal end-of-statement in multi-line mode. Control-C can be used to kill the process.

**Comment by sharkdp** [comment]
:+1: I wanted to suggest this yesterday and just saw the bug report. I am also very much used to Control-D from all kinds of programs and usually think of it as the "safer" way to quit a program: end of input as compared to immediate (C)ancel. There's probably no difference for most REPLs, but anyway.

**Comment by paf31** [comment]
This behavior is inherited from `haskeline`. Changing it would require a patch there I think.

**Comment by joneshf** [comment]
There's a specific command to quit, namely `:quit`.

That said, it'd be nice to interact well with other unix programs. Least surprise and all that stuff. One thing to be aware of is the exit code the process sends. <kbd>CTRL</kbd>+<kbd>C</kbd> will give a non-zero exit code. Whereas <kbd>CTRL</kbd>+<kbd>D</kbd> should give a zero exit code.

Also, idris uses haskeline, and they catch <kbd>CTRL</kbd>+<kbd>D</kbd> and handle it properly. Maybe some insight can be gleaned from there.

**Comment by joneshf** [comment]
Also, doesn't windows use <kbd>CTRL</kbd>+<kbd>Z</kbd> as EOF?

**Comment by cdepillabout** [comment]
I would expect Ctrl-D to quit, where as Ctrl-C will just ignore the current command and go down to an empty prompt, like it does in bash.  Currently in psci, the functionality of Ctrl-D and Ctrl-C are opposite of bash.  It's confusing for a long-time shell user.

**Comment by zudov** [comment]
Same in `ghci`, Ctrl-C causes to cancel the current expression, Ctrl-D quits.

`ghci` also uses `haskelline`

**Comment by paf31** [comment]
Well if someone can figure out the right code to poach from `ghci`, I'll take a PR.

**Comment by zudov** [comment]
This looks useful https://hackage.haskell.org/package/haskeline-0.7.2.1/docs/System-Console-Haskeline.html#v:withInterrupt , at least it should allow not to quit on Ctrl-C.

I'll try to figure it out, after I wake up (if no one would fix it or start working on it it by that time)

**Comment by zudov** [comment]
IMO, in the repl it makes sense that:

- Ctrl-C -- Cancel current command
- Ctrl-D -- There would be no more input. If we are in multi-line mode, it means that the multiline input is over. If we are in single-line mode it means that there would be no more commands and repl may quit.

**Comment by jplatte** [comment]
> * Ctrl-C -- Cancel current command
> * Ctrl-D -- There would be no more input. If we are in multi-line mode, it means that the multiline input is over. If we are in single-line mode it means that there would be no more commands and repl may quit.

+1

**Comment by enolan** [comment]
Great!
