### ISSUE TITLE
Quantified constraints

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1015]
I would like things like:

```purescript
class (forall a. Show (f a)) => Show1 f
```

and maybe even

```purescript
instance showFix :: (forall a. (Show a) => Show (f a)) => Show (Fix f)
```

**Comment by LiamGoodacre** [comment]
At first glance this seems really cool.  Has the idea been abandoned?

**Comment by paf31** [comment]
I closed this because we can solve the problem in libraries once we have constraint kinds. See the `constraints` library in Haskell for examples.

**Comment by masaeedu** [comment]
@paf31 Is there an existing issue for constraint kinds then? Having neither quantified constraints or reified constraints creates certain conveniences and makes other nice patterns inexpressible in the language. The two examples I've run into over the past week are:

- Having to create a `class Lazy2 p where defer2 :: forall a b. (Unit -> p a b) -> p a b` clone of `Lazy` (FFI and all) so I can demand a constraint for a profunctor being lazy regardless of its type arguments
- Being unable to express any of the nice patterns from the `mmorph` Haskell package as classes

**Comment by JordanMartinez** [comment]
Thought I'd link to the Haskell library mentioned above: https://hackage.haskell.org/package/constraints-0.13.4/docs/Data-Constraint.html
