### ISSUE TITLE
Merge Semigroupoid and Category

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1019]
Just for discussion, while we're breaking things in Prelude.

The only use case I can imagine for `Semigroupoid` is `Kleisli (Map k)` (right now, that doesn't work because `semigroupoidKleisli` has a `Monad` constraint, and only needs `Bind`, but whatever).

However, I think the cognitive overhead is considerable for beginners. I think the name doesn't help (`Composable`, anyone?)

**Comment by paf31** [comment]
Oops, meant to /cc @joneshf @garyb @jdegoes

**Comment by garyb** [comment]
I don't really have a strong opinion on this, but: #776 and also #625 mentions a `Semigroupoid` instance without `Category`, but I don't know if that's just out of not needing it for the example.

But then on the other hand, I'm not sure how many beginners are going to be needing to make `Category` instances either :)

**Comment by garyb** [comment]
Actually I'm pretty sure a `Category` for #625 is not a problem at all having actually looked at it now.

**Comment by paf31** [comment]
Oops, I forgot I already asked this :) I think I would probably like to think about renaming `Semigroupoid` if we don't want to remove it. `Category` is off-putting enough for beginners who want to use the `id` function, but getting `No Semigroupoid instance found...` when using `<<<` without a type signature is just bizarre :)

**Comment by jdegoes** [comment]
I think the solution is better compiler errors / warnings. If the error said:

```purescript
You are using the <<< operator. In order to use this operator, you must implement the Semigroupoid instance for the Foobar type.

This instance contains the following functions:

   ...
```

Some errors produced by GHC are this good and they do make a real difference. Calling this `Compose` or something might be slightly less scary but it doesn't actually provide any more information, so ultimately it's no more helpful. Ultimately, the user should receive a message that makes "next steps" clear, i.e. provide an instance of XYZ interface by implementing the functions ABC. Etc.

That said, I realize that's NOT an easy problem for all the cases we have to deal with. If something should be done about it, I'd prefer renaming to eliminating it

**Comment by joneshf** [comment]
> I think the solution is better compiler errors / warnings

I agree completely. Any error is scary if you don't know how to fix it.
