### ISSUE TITLE
Quickcheck test suites for core libraries

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1021]
I don't think this is documented anywhere right now, but we discussed breaking `core-tests` into separate test suites for each core library repo.

**Comment by garyb** [comment]
I also intend to make some more law tests and have those live somewhere, convenient - especially given our recent prelude changes. Currently `Functor, Applicative, Monad` [live here](https://github.com/purescript/core-tests/blob/9cd196f6552a027ee679531de59f85cc0a3c60f6/src/Test/Classes.purs), which tells you how old that is.

**Comment by paf31** [comment]
Cool :) Those can probably benefit from scoped type variables now as well.

**Comment by paf31** [comment]
Actually, those along with some more tests, could make a really nice `purescript-laws` package in core.

**Comment by garyb** [comment]
Yeah, definitely! It was writing these originall that made me request the feature.

And yep, something like `purescript-quickcheck-laws` as a package is exactly what I had in mind. :+1:

**Comment by paf31** [comment]
Let's track this on the library repos.
