### ISSUE TITLE
fail to inference the most general type?

### ISSUE THREAD

**Issue by Javran** [purescript/purescript#1022]
Without explicit type signature, the following code failed to type check:

```purescript
module TyTests where

testTyInf :: [String]
testTyInf = [ f "", f 1 ]
  where
    -- f :: forall a. (Show a) => a -> String
    f x = show x
    -- however the following definition works fine
    -- f = show

testTyInf1 :: [String]
testTyInf1 = 
  let f x = show x 
      -- f = show
  in [f "", f 1 ]
```

**Comment by paf31** [comment]
Yes, PureScript doesn't infer general types with constraints yet:

https://github.com/purescript/purescript/wiki/Differences-from-Haskell#type-classes-and-type-inference

**Comment by Javran** [comment]
ah I see. sorry I missed that part of the document.

will this be a future work? feel free to make it wontfix or leave it open :)

**Comment by paf31** [comment]
It's on the roadmap, but it's not a priority right now. If anyone is interested in working on it, I'll happily take a PR of course :) I'll mark this as a duplicate, since there are other reports for this elsewhere.

**Comment by Javran** [comment]
okay, no problem.
