### ISSUE TITLE
Better "module defined multiple times" error

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1024]
from IRC - for the "module X has been defined multiple times" error, it would be nice to show every filename that defines a module X. Currently, if you get that error, you have to use grep or something and find it yourself, which is not catastrophic but also not the nicest user experience.

**Comment by mjgpy3** [comment]
I notice there's also a `RedefinedIdent` error type as well. Is showing files for that error also a desirable enhancement? If so, should it be done as part of this issue or a separate one?

**Comment by hdgarrood** [comment]
`RedefinedIdent` is only thrown during type checking, whereas `RedefinedModule` is thrown during desugaring. Type errors do have good information about where they arose from, so I don't think `RedefinedIdent` suffers from the same issue that this issue is about. Having said that, I was unable to work out how to write a program that actually failed with that type error. Either way I don't think it's the same issue.

**Comment by hdgarrood** [comment]
Do you think it would make sense to store a module's filename inside the AST? That is, adding an extra argument to the `Module` constructor?
