### ISSUE TITLE
Monorphism Restriction Is Not Enforced

### ISSUE THREAD

**Issue by xixixao** [purescript/purescript#1034]
This runs fine in PureScript but is prohibited in Haskell:
```purescript
module Main where

import Debug.Trace

class SomeClass a where
  some :: a

instance scNumber :: SomeClass Number where
  some = 0

instance scArray :: SomeClass [a] where
  some = []

other = some -- Haskell blows up here with monorphism restriction

main = do
  print $ (2 : other)
  print $ (2 + other)
```
This might be as expected, I just couldn't find any documentation on the issue of monorphism restriction apart from some mentions in issues which suggest PureScript enforces it.

**Comment by paf31** [comment]
The restriction is different in PureScript. We generally don't infer constrained types, but this case is slightly different, only because `some` is a simple name, so we give `other` the same type as `some`.

**Comment by xixixao** [comment]
:+1:
