### ISSUE TITLE
Remove Prelude

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1040]
On the `0.7-dev` branch:

- [x] Remove built-in prelude.
- [x] Add a detailed error if both Prelude and `--no-prelude` are missing.
- [x] Get tests working without Prelude
- [x] Extract `purescript-prelude`
- [x] Extract `purescript-eff`
- [x] Extract `purescript-console`
- [x] Extract `purescript-st`
- [x] Extract `purescript-functions`
- [ ] Fix `core-tests`.

**Comment by puffnfresh** [comment]
Awesome stuff :+1:

**Comment by markfarrell** [comment]
Yeah.
