### ISSUE TITLE
Better errors for kind mismatch in typed expressions

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1042]
For example:
```purescript
module Test where

data List a
  = Nil
  | Cons a (List a)

x = Nil :: List
```

Gives a type error:
```
Error in module Test:
Error in value declaration x:
Error at test.purs line 7, column 5 - line 7, column 12:
  Expected type of kind *, was * -> *
See https://github.com/purescript/purescript/wiki/Error-Code-ExpectedType for more information, or to contribute content related to this error.
```

We might improve this error by adding something like the following:

> In a type-annotated expression `x :: t`, the type `t` must have kind `*`. The error arises from the type  `List` having the kind `* -> *` instead.

We might even be able to go further for types of kind `* -> *`:

> Perhaps you meant `forall a. List a`?

**Comment by paf31** [comment]
I'd be wary of suggesting the use of `forall`, since people tend to get that wrong quite a lot, but I'm in favour of a better error message when we expect `*`.

**Comment by hdgarrood** [comment]
Sorry, I don't follow - what do people get wrong quite a lot?

**Comment by garyb** [comment]
They sometimes put `forall` in the wrong place, resulting in types that can have no inhabitants.
