### ISSUE TITLE
0.6.9.5 probably shouldn't have been released as that

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1054]
It has all the `Prelude` changes that are going into 0.7 - breaking stuff by introducing `Lattice`, removing `Bits`, etc.

**Comment by paf31** [comment]
0.6.9.5 was the 0.6.9.3 tag with two cherry picked fixes from master. It shouldn't have the Lattice stuff.

**Comment by paf31** [comment]
Closing this as I'm pretty sure it's right. We can reopen if not.

**Comment by garyb** [comment]
Oh, sorry, I think you are right. I was looking at the "Commits since release" list thinking it was the diff between that release and the previous.
