### ISSUE TITLE
Move Int and Char into Prim, and add Int and Char literals

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1061]
Should we do this as part of the 0.7 changes, or after?

/cc @garyb

**Comment by garyb** [comment]
I guess for the 0.7 release would be ideal.

Would we allow casting integer literals to `Number`?
``` purescript
four :: Number
four = 4
```
 Or will `Number`s strictly require the `x.0` ending?

**Comment by garyb** [comment]
:scream:

This will made importing `Data.Int (Int())` redundant, will have to go back and take it out everywhere, as `Int` will already be in scope.

**Comment by paf31** [comment]
I was thinking `1 :: Int` but `1.0 :: Number` with no implicit casting.

Yes, it would be quite a bit more work sadly, which is why I wanted to figure out when we wanted to do it.

**Comment by andyarvanitis** [comment]
Any plans for `Char` as well, including `''` literals?

**Comment by garyb** [comment]
@paf31 Yeah, that makes sense I think, at least that way it's never ambiguous.

It's unfortunate, but I'd rather not have to go through all the libraries yet again at a later date, so may as well get it done now.

**Comment by jdegoes** [comment]
> It's unfortunate, but I'd rather not have to go through all the libraries yet again at a later date, so may as well get it done now.

Agreed. Also changes this drastic will have a negative affect on the PureScript community, so it's best to Break All the Things now. With each point release comes increasing pressure to preserve backward compatibility.

**Comment by jdegoes** [comment]
> Any plans for Char as well, including 'c' literals?

Please oh please! :+1:

**Comment by garyb** [comment]
:+1: for Char literals also, I don't think they will interfere with prime'd identifiers?

**Comment by paf31** [comment]
I can get behind `Char` literals too.

**Comment by paf31** [comment]
Anyone care to take a look at this? It would be a good intro to the parser and code gen and bits of the type checker.

If not, I'll take care of it early next week.

**Comment by andyarvanitis** [comment]
Just FYI, I have them (`Char` / literals) in pure11, although they just end up as `Int`s.

**Comment by michaelficarra** [comment]
If we have chars, we should be careful to differentiate bytes and code points. See [golang's handling of char/byte/rune](https://blog.golang.org/strings#TOC_5.). For instance, we may want to destructure strings in the future, and I would prefer they destructure to code points instead of bytes. This is how for-of (the encouraged) iteration in ES6 works. Note that there are APIs for viewing a string as both a list of bytes (`charCodeAt` or numeric indices) and a list of code points (`codePointAt` or for-of).

**Comment by paf31** [comment]
I was thinking that `Char` would just be a single character string in the JS backend, just like in `Data.Char`.

**Comment by paf31** [comment]
Char literals are done. "Just" need to update the tests, and then the core libraries.

**Comment by jdegoes** [comment]
:smile: :smile: :smile:

**Comment by andyarvanitis** [comment]
:+1:
