### ISSUE TITLE
Syntax for virtual dom extensions

### ISSUE THREAD

**Issue by Ciantic** [purescript/purescript#1068]
This is inspired by thread in [TypeScript issues](https://github.com/Microsoft/TypeScript/issues/296). I think this is even more relevant to Purescript since this project is aimed at programming web and not "only typed extension of JS" like TS is.

Problem at the moment is this nonsense:

```
import Data.DOM.Free
 
doc :: Element
doc = div [ _class := "image" ] $ do
  elem $ img [ src := "logo.jpg"
             , width  := 100
             , height := 200
             ]
  text "Functional programming for the web!"
```

It might be completely clear for language purists but I gather this would be nicer:

```
doc :: Element
doc = 
    <div className="image">
        <img src="logo.jpg" width={100} height={200}>
        Functional programming for the web!
    </div>
```

It could compile to function calls, and in case of HTML elements perhaps factory function called with string. You can see type safe ideas from TS thread, I think my point is clear however.

P.S. I have also left out some important details like using `{some stuff}` syntax to call the native language again, I'm not too familiar with the syntax to make an example of that.

**Comment by paf31** [comment]
Adding XML syntax contradicts many of the design decisions in the language. I don't want to implement this, but it would be a good candidate for a Template PureScript library when that exists. See libraries like `hamlet` or `text-xml-qq` in Haskell.

**Comment by arrowd** [comment]
Has anything changed since then? I also find it uncomfortable to write large chunks of HTML in `Data.DOM` combinators.

**Comment by kRITZCREEK** [comment]
No, we don't have a good plan for template purescript yet, and it definitely won't happen as part of the language.
