### ISSUE TITLE
Deprecation of foreign string literals

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1069]
Since 0.7 is already getting pretty ["melty"](https://github.com/purescript/purescript/issues/937) in terms of breaking stuff, should we take this opportunity to start updating FFI code too?

Perhaps we could keep inline foreign strings working for now, but make them a warning. I suppose the same applies to operator aliases actually, or indeed any of the changes discussed in #937.

Basically I'd like to avoid having to make breaking changes to all the base libraries yet again when 0.8 rolls around, since we're already doing that in 0.7 - if we turn all those things into warnings and provide the alternative, at least it gives people a chance to update rather than breaking overnight.

- [ ] Add deprecation warning for inline JS
- [x] Combine external JS during compilation

**Comment by puffnfresh** [comment]
I think it's premature to worry about breaking people's PureScript code. I don't think it's a big problem.

**Comment by jdegoes** [comment]
> I think it's premature to worry about breaking people's PureScript code. I don't think it's a big problem.

I disagree. Of course we should break backward compatibility, because we need to improve the language before a 1.0 release, but breaking backward compatibility like this will make a lot of people upset and cause some to leave (or not join) the community (we're talking about literally breaking hundreds of PureScript libraries, and that's just on Github).

So ideally we minimize the number of *times* that breaking changes are required.

For that reason I'd be all in favor of making 0.7 the "meltdown" release. A lot of this is about fixing stuff (ints, chars, no prelude, operator aliases), future releases I think can be more about improving / adding rather than fixing and possibly less liable to break backward compatibility.

**Comment by SimonRichardson** [comment]
:+1: 

I agree about bringing "meltdown" to 0.7 as well, I'd rather have to deal with it once.

**Comment by paf31** [comment]
I'm in favor of breaking lots of stuff generally. I'd just like to make sure that whatever we break in 0.7 can be fixed mechanically and quickly if you know what you're doing. The reason is that I don't want to risk us getting into a situation where nobody can build anything (especially with LambdaConf around the corner).

So my list is:

- Deprecate inline JS
- Remove Array sugar (`[]` types, `:` matching and `:` constructor)

I don't know if I want to introduce operator aliases in 0.7, because it's quite a big change to the compiler, and I don't even think we've agreed on an approach yet. If we do anything at all, I'd like it to be very simple. It could even be just _allowing_ the syntax (and providing a deprecation warning), without doing anything with it.

**Comment by garyb** [comment]
Maybe for the operator stuff then, as indeed we haven't figured that out yet, we should update the core libraries to not use operators in class definitions? We started going that way with `inf` and `sup`, so could just apply it everywhere else - `bind`, `map`, etc.

At least then it means there will be no future updating-of-instances required, and as you can sort-of alias operators now: `(<$>) = fmap`, so usage of the classes needn't change, only the instances.

**Comment by paf31** [comment]
I like that idea, and as a bonus, it can be implemented without changes to the compiler now that we've removed the Prelude.

**Comment by paf31** [comment]
Ok, I'll update the original post.

**Comment by paf31** [comment]
Another thought on the FFI: if we're going to allow JS in external files, we're going to need a way to bundle it during compilation. It would probably be nice if we had a better convention for scoping than "the name exists in the global namespace".

**Comment by garyb** [comment]
I've also been thinking about how that might work. I think the bundling of external FFI has to mostly be left up to the backend for that particular target, as there's no way we can cover everything off.

My preference for the JS one would to be use something like a CommonJS exports object as a way of declaring the definitions, and then it can be bundled as Some.Module.$Foreign or something, and definitions can be referenced that way in the generated code when using the `foreign import`ed name.

**Comment by natefaubion** [comment]
Could you have a module `Foo.purs` and `Foo.ffi.js`:
In `Foo.ffi.js`:
```js
function ffiFn() {
}
```

In `Foo.purs`:
```purescript
module Foo (ffiFn) where
foreign import ffiFn :: Foo
```

and the ffi file gets included at the top?

**Comment by paf31** [comment]
That's what I've been leaning towards too - backends choose their own convention, and I think @natefaubion's convention makes good sense.

**Comment by paf31** [comment]
Oh, apart from the global namespacing thing. Would we rather have:

```js
Foo.ffiFn = function() { };
```

**Comment by garyb** [comment]
That's what I was getting at. Then you won't accidentally shadow names from the JS in the PS, or vice versa.

**Comment by garyb** [comment]
Although I'd prefer something like an implict exports value, so your FFI file would be like:

```
expors.ffiFn = function() {};
```

And then wrapped in this by codegen:

```
(function () {
  var exports = {};
  ... dump code here ...
  return exports;
}());
```

**Comment by paf31** [comment]
Sounds good to me.

**Comment by natefaubion** [comment]
I also still like https://github.com/purescript/purescript/issues/887#issuecomment-74991067 and you could add deprecations warnings to the current foreign import syntax

**Comment by paf31** [comment]
@natefaubion That's a neat idea. The only issues I see are 1) how to handle externs, and 2) what do you do with `Math` and `Globals`?

**Comment by garyb** [comment]
I guess you'd could make an FFI module that just re-exports them:

``` js
exports.abs = Math.abs;
exports.min = Math.min;
exports.max = Math.max;
...
```

**Comment by natefaubion** [comment]
For externs, if you re-export an ffi function, I'd assume it just gets a signature in the file like a normal function. Is that reasonable?

**Comment by joneshf** [comment]
Would this handle multiple ffi files?

**Comment by garyb** [comment]
That's down the the language's backend I guess.

**Comment by natefaubion** [comment]
Correct, each backend would choose how to handle the import https://github.com/purescript/purescript/issues/887#issuecomment-75132553

**Comment by paf31** [comment]
@natefaubion The issue with externs is that even regular functions become foreign imports in externs files, so you'd need an empty module name for those. Which isn't an awful thing, just needs to be considered.

**Comment by joneshf** [comment]
@garyb @natefaubion makes sense.

If this is where we're discussing breaking changes, then I'd like to suggest one more: create and use `Nat` where sensible. 

It doesn't make much sense to have functions like: 

* `take :: Int -> [a] -> [a]`
* `fromCharCode :: Int -> Char`
* `replicateM :: Int -> m a -> m [a]`
* `length :: [a] -> Int`
* etc

When what we really want (and mean in the implementations) are functions like

* `take :: Nat -> [a] -> [a]`
* `fromCharCode :: Nat -> Char`
* `replicateM :: Nat -> m a -> m [a]`
* `length :: [a] -> Nat`
* etc

`Nat` makes a `Semiring` and a `Ring` depending on how you define `(-)`. There are at least two instances

```purescript
-- As a metric on Nat:
instance ringNat :: Ring Nat where
  (-) m n
    | m < n     = n - m
    | otherwise = natSubtract m n

-- Or as truncated subtraction on Nat:

instance ringNat' :: Ring Nat where
  (-) m n
    | m < n     = zero
    | otherwise = natSubtract m n
```

Or just don't attempt to implement `Ring`, and the choice needn't be made.

**Comment by michaelficarra** [comment]
> I guess you could make an FFI module that just re-exports them

```js
exports = Math;
```

**Comment by paf31** [comment]
@michaelficarra I think that works, and it conveys the intent nicely too.

@joneshf I like the idea of defining a `Nat` type, if we can make it simple enough to use. I think the "not beginner friendly" argument isn't really appropriate any more given the recent changes we've made anyway :) and if people already understand `Semigroup`, `Semiring`, etc., it should be a simple change. As I say, I just want to make it easy to interoperate with `Int` code. We'd need `fromNat` and probably `Int -> Nat` as well.

**Comment by garyb** [comment]
The only thing with `Nat` is... doesn't that put us in the same position as we currently have with `Int`? A ton of code needing `fromNat`/`toNat`...

**Comment by paf31** [comment]
Yes, I think we need to distinguish between breaking some things which are convenient to break and trying to fix everything at once. I suspect `Nat` might be too much for 0.7 honestly, but I think I would probably want to do it eventually.

**Comment by jdegoes** [comment]
> The only thing with Nat is... doesn't that put us in the same position as we currently have with Int? A ton of code needing fromNat/toNat...

Not quite as bad since you would normally form `Nats` through `zero` and `succ` (`= \n -> n `plus` one`).

e.g. `length :: List a -> Nat` would be defined inductively from `zero` using `succ`. 

Doesn't really help for `Array` and such, since you wouldn't define those inductively for performance reasons...

**Comment by paf31** [comment]
Oh, I assumed `Nat` would just refine `Number` using the `FFI`, like `Int`. I don't think an inductive `Nat` is going to be practical for things like `length`.

**Comment by paf31** [comment]
...on arrays, to clarify.

**Comment by jdegoes** [comment]
Sure, but that doesn't prevent inductive creation of a `Nat` using `Semiring`'s zero / plus / one, which would probably be the case for `List` and similar structures.

**Comment by michaelficarra** [comment]
Would integer literals produce a Nat?

**Comment by paf31** [comment]
Should we deprecate inline FFI or just outright disallow it?

**Comment by garyb** [comment]
I'd prefer deprecate till the next major version, with a warning when compiling existing inline.

And update all core libs etc. to avoid inline.

**Comment by jdegoes** [comment]
Deprecate with *extremely clear* explanation of the successor method to FFI strings.

**Comment by garyb** [comment]
Current thinking for how this will work:

- New compiler flag to pass in source files for FFI files
- `psc` and `psc-make` load these files and look for a line like `// module X.Y.Z` to determine which module the FFI code is for
- Pass through map/tupled list of modules and FFI code to `Language.Purescript`
- Compiles PS modules as normal
- Codegen bundles FFI code within modules

**Comment by garyb** [comment]
Additionally

- For now we're going to stick to the existing `foreign import` syntax, just disallowing literals (and this will be an error rather than deprecation warning - people are going to have to update the code anyway with 0.7, so may as well get it out of the way, as we're breaking and not deprecating everything else)
- It will be an error to use `foreign import` if the module has no associated FFI file, except the case where the foreign import is for `data`.

**Comment by andyarvanitis** [comment]
So just for clarification: the FFI files will be source files (native backend language), with no PS syntax other than `// module X.Y.Z` comments, right?

**Comment by garyb** [comment]
I think that detail is left up to the backend - it's just how I see it working for the JS case. I guess the bit that affects all backends is that `Language.PureScript` will now be accepting a list of modules-with-associated-FFI-stuff, which will be handed off to the backend to deal with.

**Comment by andyarvanitis** [comment]
Ok, sounds good -- I was mainly wondering if the non-backend parts of the compiler would be looking for anything else in those files. For compiled-language backends, it would be nice for those to be natively compilable/checkable before being processed by the PS compiler, and it sounds like that will be the case.

Since comment syntax is language-specific (`//`, `/*`, `#`, etc), I guess the backend parts of `psc/psc-make` will handle that parsing?

**Comment by garyb** [comment]
Ah yep, the idea is to have the non-backends parts know absolutely nothing about the FFI code (I'll use a type variable throughout), and have it all handled in the executable and backend parts.

Although I've been discussing DCE with @paf31 on IRC, and that's raising some tricky issues. I guess DCE is irrelevant to pure11 though, so this could be considered part of the JS backend too.

**Comment by garyb** [comment]
@paf31: As we're now just going to bundle a bunch of JS in our generated code, it won't necessarily fit into any kind of nice box we make for it (the `exports` object could be generated dynamically for instance), so here's a few thoughts, although it does involve a little parsing (but not needing a full on JS AST):

1) We only use DCE for things that look like `exports.foo = ...`.
2) Any other code in the file is always included in the output.

As a consequence of this, we could actually look for dependencies between declarations just by looking for `exports.foo` references in the file, aside from the definition. This obviously doesn't work for `exports[...]` type dynamic access, but maybe we could emit a warning if that is seen in the file when DCE is enabled.

Doing things this way also allows us to `require` or whatever to bring variables into scope throughout the module without having to do so in each exported definition. So `var vtree = require("virtual-dom/vtree");` could go in the top of the file and then be used safely throughout, as it wouldn't be erased due to not following `exports.vtree = ...`.

I like this approach as it keeps things flexible on the JS side, allowing people to do whatever they want to construct the exports object (and actually the JS file is just a completely normal CommonJS module with just a single comment added somewhere at the top), while keeping DCE practical and predictable.

**Comment by paf31** [comment]
@garyb Sounds promising. Let's run through an example. Is this correct?

```purescript
module M where

foreign import data X

foreign import foo :: X -> X
```

```javascript
// module M

var m = require("blah");

exports.foo = function(x) {
  return m(x);
};
```

If so, how would you parse the file in the general case? How would you know where an export ended and the next bit of (possibly exported) code started?

I feel like a full JS parser might be a better way to go. It's not a bad thing necessarily.

**Comment by jdegoes** [comment]
> I feel like a full JS parser might be a better way to go.

Yes, please. A JVM backend would use bytecode analysis, and parsing Javascript is the equivalent of that in the world where Javascript is the target. Seems like there are a few JS parsers around.

Also, presumably if there are no module comments, the module is inferred from the name of the file???

**Comment by paf31** [comment]
> Also, presumably if there are no module comments, the module is inferred from the name of the file???

I think we decided it would be an error. How would you infer it when the source file could be in `src/` or `bower_components/` or any other directory?

**Comment by michaelficarra** [comment]
@paf31 Is it possible for us to use ES6 imports/exports?

```js
import * as m from "blah";
export function foo(x) { return m(x); };
```

**Comment by jdegoes** [comment]
Also I'm not expert in the various module wars, but it seems like AMD would be a better choice, e.g.

```javascript
define('blah', function () {
});
```

No comment necessary since you define the module right there, also seamlessly supports multiple modules per file, etc.

**Comment by paf31** [comment]
Both of those options require modifying the JS yes? In the original version, I think we'd just drop the JS file into the compiled file, verbatim.

**Comment by michaelficarra** [comment]
@paf31 The compilation from ES6 imports/exports to CommonJS imports/exports is straightforward: http://jsmodules.io/cjs.html
