### ISSUE TITLE
Remove array sugar

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1075]
- [x] Type syntax
- [x] Cons binders
- [ ] Move `cons` and `:` into `purescript-arrays`

**Comment by garyb** [comment]
- [ ] Move `unsafeIndex` out of `Prelude.Unsafe`

**Comment by jdegoes** [comment]
> Move cons and : into purescript-arrays

I think there's an argument for `purescript-consable`:

```purescript
class Consable f where
  cons :: a -> f a -> f a

(:) = cons

class Unconsable f where
  uncons :: f a -> Maybe (Tuple a (f a))
```

or something like that.

**Comment by paf31** [comment]
@jdegoes Both sound good, but I don't think we can keep cons-pattern syntax.

**Comment by michaelficarra** [comment]
:+1: @jdegoes 

We can still keep the cons-patterns if we take the route I suggested in #607.

**Comment by jdegoes** [comment]
I don't really care about cons patterns because it's so easy to write:

```purescript
case uncons a of
  Nothing ->
  Just (Tuple x xs) -> 
```

i.e. push the pattern into the expression level and use the `Maybe` / `Tuple` deconstruction.

**Comment by michaelficarra** [comment]
But @jdegoes,

```purescript
f [] = ...
f (a : []) = ...
f (a : b : rest) = ...
```

is much more clearly written using cons patterns.

**Comment by jdegoes** [comment]
True, but I think special casing this is probably not the right way (as opposed to adding something like view patterns in the future).

**Comment by joneshf** [comment]
> I think there's an argument for purescript-consable:

You mean like this: https://github.com/joneshf/purescript-cons :)

**Comment by jdegoes** [comment]
Figures there would be lenses / prisms involved. Dude, you're like the ed kmett of PureScript! ;-)

**Comment by paf31** [comment]
@michaelficarra I think in that case, we should use `List` anyway. Converting to `List` and then back would probably be just as fast anyway.

**Comment by andyarvanitis** [comment]
I think I will miss the patterns -- but maybe it will help encourage more careful selection of collection types by users (and library creators). For some backends there are lots of options for what's under-the-hood that affect performance, memory, and interop. E.g., for C++ there are std::vectors, std::deque, etc..

**Comment by flq** [comment]
So currently chapter 5 of the book doesn't compile, and it seems to be related to what happened here.
It is about this code:

```haskell
showPicture picture = "[" ++ go picture ++ "]"
  where
  go :: Picture -> String
  go [] = ""
  go [x] = showShape x
  go (x : xs) = showShape x ++ ", " ++ go xs
```

With the error stating that `Cons binders are no longer supported. Consider using purescript-lists or purescript-sequences instead.`

So, what is the canonical way to go about such code?

**Comment by adnelson** [comment]
I'm also running into the error that @flq mentioned. The error message "Cons binders are no longer supported" is very confusing: what does this even mean?

**Comment by garyb** [comment]
A cons binder is where you have `x : xs` or other similar patterns. So called because it refers to destructuring a "cons list", which is where the list is constructed `x1 : x2 : x3 : []`. The `:` is called "cons".

Since that's not how JavaScript arrays are represented, pretending they are results in poorly performing code.
