### ISSUE TITLE
Move instances for Prim types with classes

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1076]
For Pursuit (orphan instances not documented)

**Comment by puffnfresh** [comment]
:+1:

**Comment by paf31** [comment]
What instances still need to be moved?

**Comment by garyb** [comment]
Just those for `Monoid` I think, the `Prelude` classes are done now.

**Comment by garyb** [comment]
Closed by purescript/purescript-monoid@b05051d6a97febfbe234f811b91f287796ecdf4b
