### ISSUE TITLE
Improving doc-comment syntax

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1081]
I have a couple of minor gripes with the current doc-comment syntax:

1. Mixing docs with non-docs is too hard
2. Putting a pipe at the start of every line is too fiddly. This is particularly bad for non-{emacs,vim} users.

An example of the first problem - I want the documentation comments here to come through to the rendered psc-docs version, but not the TODO:

```purescript
-- | O(log(min(i,n-i))). Adjust the element at the specified index by
-- | applying the given function to it. If the index is out of range, the
-- | sequence is returned unchanged.
-- TODO: Investigate whether this can be optimized.
adjust :: forall a. (a -> a) -> Number -> Seq a -> Seq a
adjust f i xs = if inBounds xs i then unsafeAdjust f i xs else xs
```

This will currently result in no documentation appearing at all, because the code currently checks that every line starts with a pipe, and ignores the whole lot if the check fails.

I think we can solve both of these issues in one hit, while mostly maintaining backwards compatibility, by using block comments (since nobody seems to be using them for docs at the moment).

1. In the case where a declaration is accompanied by a documentation block comment, it makes sense to assume that it contains all of the documentation - all other comments can probably be ignored.
2. Relax the requirement for block comments that every line start with a pipe. Instead, just ensure that the whole comment starts with a pipe.

Example:

```purescript
{-| O(log(min(i,n-i))). Adjust the element at the specified index by applying
the given function to it. If the index is out of range, the sequence is
returned unchanged.
-}
-- TODO: Investigate whether this can be optimized.
adjust :: forall a. (a -> a) -> Number -> Seq a -> Seq a
adjust f i xs = if inBounds xs i then unsafeAdjust f i xs else xs
```

If we standardise on block comments (across core libraries, purescript book, etc) then other people will probably start writing code in the same way, which I think would mean less pain for everyone.

If there's agreement I will probably send a PR soon. This would be a tiny change, 20 lines or so maximum.

**Comment by garyb** [comment]
I personally rather like the `-- |` style, when you're reading down the code it clearly denotes where documentation is rather than "just comments", having the block comment that way obfuscates it a little more. Also it's just an aesthetic thing but I like having the consistent margin down the left side also.

I'd agree that the case you posted above should work though, and just keep the doc comment upto the TODO line.

**Comment by garyb** [comment]
I'm not sure I agree that putting a pipe in is all that fiddly either - aside from the most very basic of text editors I doubt there are many that don't support some form of multiline or column based editing.

**Comment by hdgarrood** [comment]
Fair enough if you prefer the single line style.

I'm a Vim user, and although Vim does support a kind of multiline / column based editing, it's painful when I'm trying to wrap at 79 characters. Take the above example - it turns out the lines are wrapped a bit early. I press `2gqj`, which means "wrap the following two lines", and this happens:

```purescript
-- | O(log(min(i,n-i))). Adjust the element at the specified index by -- |
applying the given function to it. If the index is out of range, the -- |
sequence is returned unchanged.
adjust :: forall a. (a -> a) -> Number -> Seq a -> Seq a
adjust f i xs = if inBounds xs i then unsafeAdjust f i xs else xs
```

There are lots of programmers who don't use fancy text editors, or who aren't aware of the fancy features of their own text editor - for example, I expect there is a good way of doing this in Vim, but it could take me hours to work out what it is. My proposed solution works out of the box.

How would you feel about only requiring a pipe on the first line of block comments only, but continuing to strip pipes on every other line? So the following two things end up the same:

```
{-| O(log(min(i,n-i))). Adjust the element at the specified index by applying
the given function to it. If the index is out of range, the sequence is
returned unchanged.
-}
``` 

```
{-| O(log(min(i,n-i))). Adjust the element at the specified index by applying
  | the given function to it. If the index is out of range, the sequence is
  | returned unchanged.
-}
```

**Comment by garyb** [comment]
Oh, I wasn't saying "no", just throwing my 2p in :smile:

**Comment by paf31** [comment]
I'm going to vote for the aligned `|`s too, since I think it makes it easier to format non-trivial Markdown.
