### ISSUE TITLE
Parallel builds

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1087]
I think `monad-par` would be a nice approach.

**Comment by puffnfresh** [comment]
Slow builds are killing me right now :+1:

**Comment by paf31** [comment]
Related: https://github.com/bitc/purescript/tree/psc-compile/psc-compile

This is probably a better approach: simplify the `psc` build when modules didn't change, and get parallelism by using multiple processes and make/Shake.

`psc` could even support a `--dump-make-file` option.
