### ISSUE TITLE
Conflicting import error seems to use the wrong module name

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1088]
If we have:

```purescript
module ConflictingImport where

id :: Number
id = 1
```

Then this will fail with:

```
>> Error in module ConflictingImport:
>> Declaration id conflicts with import ConflictingImport
```

I think a better error message could be:

```
Cannot declare a value `id` when another declaration with that name was
imported from Prelude.
Possible fix: hide `id` in the Prelude import:
   import Prelude hiding (id)
```

**Comment by hdgarrood** [comment]
See also https://github.com/purescript/purescript/wiki/Error-Code-ConflictingImport - this wiki page should probably be updated after this is fixed.

**Comment by mjgpy3** [comment]
I'd like to look at this when #1085 gets in. The suggestions mechanism could be useful here.
