### ISSUE TITLE
Move cons and : into purescript-arrays

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1089]

**Comment by michaelficarra** [comment]
I'd rather see purescript-arrays depend on [purescript-cons](https://github.com/joneshf/purescript-cons) and implement `Cons` and `Snoc`.

**Comment by jdegoes** [comment]
> I'd rather see purescript-arrays depend on purescript-cons and implement Cons and Snoc.

:+1:

**Comment by paf31** [comment]
Can't see how we can have a `lens` depedency from `arrays`.

**Comment by jdegoes** [comment]
It's a well-known fact that the whole physical universe as well as all of mathematics depends on lens, is it not? :smiling_imp:

**Comment by michaelficarra** [comment]
Well we can leave purescript-cons depending on purescript-arrays (I don't remember where we landed on this inversion of dependencies discussion), but it's pretty inevitable that you're going to have to use lenses in any non-trivial program.

**Comment by paf31** [comment]
> but it's pretty inevitable that you're going to have to use lenses in any non-trivial program.

Not sure I agree with that.

**Comment by michaelficarra** [comment]
Yeah, I knew that would be a controversial claim. How about the majority of programs that make use of arrays?

**Comment by paf31** [comment]
I think there is a good use case for `arrays` which replaces things like Underscore and lodash, which has a good chance of introducing beginners to PureScript. Forcing lenses on them at such an early stage seems a little much.

We can define these instances of course, just not in `arrays` itself.

**Comment by hdgarrood** [comment]
It looks like `Array` does already have instances for `Cons` and `Snoc`, defined in `purescript-cons` (which is the only place they could go anyway, if you want to avoid orphan instances). Re this particular issue: why not both?
