### ISSUE TITLE
Core library test suites

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1091]
I thought we could implement these as subprojects, so that we could use testing libraries without circular dependencies. @garyb I forget, but I feel like you said there might be an issue with that?

**Comment by garyb** [comment]
I'll get back to you on that. There is definitely an issue if we want to use Grunt to run the tests at the same time as building (which I would really like), but I think Gulp may not suffer from the same problem - as I've been switching all the core libraries over it might be fine now.

**Comment by paf31** [comment]
@garyb I'll close this, since at least Travis is running again for core libs (thanks!), and we can work on adding more tests gradually.
