### ISSUE TITLE
Move purescript-lists into core

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1092]
- [x] Move `ListT` into `transformers`
- [x] Remove lazy lists from `lazy`
- [x] Improve the lazy list implementation
- [x] Add `some`, `many`, `replicateM`, `foldM` and `filterM`

/cc @jdegoes

**Comment by jdegoes** [comment]
:+1:

**Comment by paf31** [comment]
- [ ] Add `some`, `many`, `replicateM`, `foldM` and `filterM`
