### ISSUE TITLE
Should Int literals be `|0`d?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1094]
It's currently possible to construct `Int` values outside the 32-bit range using literals:

```
> let y = 99999999999999999 :: Int
> y
100000000000000000

> y + 1
1569325056
```

Should `Int` literals come out as `x|0` to avoid this? Alternatively, should it be an error to write an `Int` literal outside the 32-bit range?

**Comment by garyb** [comment]
I think it should be an error to write literals that are too large :+1:

**Comment by michaelficarra** [comment]
No, JavaScript has the ability to represent all integer values with magnitude less than 2<sup>53</sup>. Why do you want our Int to be Int32?

**Comment by michaelficarra** [comment]
Oh, I see that the maths operations already treat Int as Int32. In that case, :+1:.

**Comment by garyb** [comment]
Yeah, and that's mainly the case so we can have `Data.Int.Bits`. I guess another option would be to extend our `Int` past that range and introduce an actual `Int32` for the bitwise operators.

**Comment by jdegoes** [comment]
> I think it should be an error to write literals that are too large

What is too large depends on the backend. On the JVM it will be at least 64 bits, in some backends, you can imagine `BigInt` or something like that being used so there's no limitation.

**Comment by paf31** [comment]
Yes, but I think enforcing this in the compiler is the better way to go. We can just parameterize the parser with a `Maybe IntBounds` or something.

**Comment by garyb** [comment]
Wouldn't it make sense for `Int` to be the same across platforms? Otherwise we'll potentially start running into libraries that behave differently depending on the platform they're running on...

**Comment by jdegoes** [comment]
> Otherwise we'll potentially start running into libraries that behave differently depending on the platform they're running on...

Well, 'behave differently' = overflow slower or faster than other backends. That's pretty standard. The alternative (limiting `Int` to 32 bits) will mean that `Int` isn't used for most backends, which will mean a lot of libraries don't work or don't work well for JS.

**Comment by garyb** [comment]
Yeah, that's true; as long as it's only the overflow and not the semantics that are changing there is probably less of an issue.

**Comment by andyarvanitis** [comment]
+1 for not making `Int` 32 bits, unless you mean "at least 32 bits", a la Haskell. Always a thorny topic, but having `Int` represent "native machine width" might be preferable. Of course "native machine width" is an overloaded term (LP64, LLP64, etc). Not sure about limiting the size of literals either, since future-proofing for `BigInt`/`Integer` would be a good thing too.

And of course specific-width types (`Int32`, etc) are often helpful/necessary for interop, but those don't have to built out right now.

**Comment by hdgarrood** [comment]
I think, for the JS backend, we should at least change `Int` literals so that they come out in the JS as `x|0`, to ensure that you can't construct an `Int` value that you wouldn't be able to otherwise. For example, `3000000000 > top` currently evaluates to true, which violates the `Bounded` law of `forall x. x <= top`.

**Comment by paf31** [comment]
I would much rather enforce this at compile time, in the parser. I wouldn't want people to get unexpected results from a `|0`.

**Comment by garyb** [comment]
We could check if the literal is too large during the JS part of the compiler and throw an error still, it wouldn't necessarily have to be in the parser.

**Comment by paf31** [comment]
Sure, that gives us better control in the case of different backends. I think I was trying to identify the issue as soon as possible - it seems like a shame to have to wait for typechecking, but it definitely is cleaner to put it into codegen.
