### ISSUE TITLE
Make compile errors from psc-make less verbose by suppressing 'Reading $file' lines by default.

### ISSUE THREAD

**Issue by epost** [purescript/purescript#1097]
Compile errors contain many lines like these:

```
Reading ./output/Data.Traversable/externs.purs
Reading ./output/Data.Foreign.Class/externs.purs
Reading ./output/Data.Identity/externs.purs
```

I think it might be more pleasant  to hide them by default and but them behind a flag, perhaps with a notice that using that flag will provide more detailed info. As it is, all the 'Reading' lines will easily fill up my emacs compilation buffer, so I can't see the actual error(s) without changing to the appropriate window and scrolling down, which is a bit of a pain

**Comment by paf31** [comment]
:+1:

**Comment by paf31** [comment]
The `--verbose-errors` flag would probably work.

**Comment by epost** [comment]
Sounds good!

**Comment by mjgpy3** [comment]
@paf31 can you give me some advice on how to pass/read/access the `--verbose-erors` flag in [the location where these errors are being printed](https://github.com/purescript/purescript/blob/master/psc-make/Main.hs#L71-L73)? I've been mucking with it but I keep fighting the `Parser _` type.

**Comment by puffnfresh** [comment]
:+1:

**Comment by paf31** [comment]
@mjgpy3  Sure, you need to use `ask` from `Control.Monad.Reader.Class`, which will give you the `Options` object, and then read the verbosity flag from there.

**Comment by mjgpy3** [comment]
@paf31, I was wondering if you could give me another nudge in the right direction. I'm pretty close, but I'm not really sure how to unbox `m0 Bool` in the below error.

Interesting lines: 
https://github.com/mjgpy3/purescript/blob/1097_less_verbose_compile_errors/psc-make/Main.hs#L72-L76

Error:
> psc-make/Main.hs:73:10:
    Couldn't match expected type ‘Bool’ with actual type ‘m0 Bool’
    Relevant bindings include
      verboseErrorsEnabled :: m0 Bool (bound at psc-make/Main.hs:76:7)
    In the first argument of ‘when’, namely ‘verboseErrorsEnabled’
    In the expression: when verboseErrorsEnabled

**Comment by mjgpy3** [comment]
I tried using just `ask` and it seemed require a good bit more unboxing that I'm not yet able to wrap my head around.

**Comment by epost** [comment]
@mjgpy3 Awesome! :D :+1:
