### ISSUE TITLE
Lattice -> BooleanAlgebra

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1099]
See https://github.com/purescript/purescript-prelude/issues/18

If `Ord` represents totally ordered types, there are no interesting lattices, only those which arise from `min` and `max`, but I think it would be good to define other complete lattices, like the lattice on tuples where each component can be undefined, which does not arise from any `Ord` instance.

Options are:

- Remove the `Ord` superclass constraint from `Lattice` entirely (c.f. `purescript-algebra`)
- Create a new `Poset` class, and add it as a superclass
- Revert to `BoolLike`
- Change `Ord` to represent partial orders (this breaks some existing code)

I think there is a lot of value in `Lattice`, so I don't want to get rid of it, but we have to nail down the laws before it's released.

Also, the docs for `Ord` currently describe it as a partial order, but that assumption breaks code in core libraries.

**Comment by garyb** [comment]
What would changing `Ord` entail? Adding a constructor for incomparable values?

**Comment by paf31** [comment]
Yes, but we also need to fix some library code to handle non-comparable values.

**Comment by joneshf** [comment]
Combining the first two options, we could do something like:

![poset](https://cloud.githubusercontent.com/assets/1356417/7466942/90d90bdc-f2a2-11e4-8edc-92c230894646.png)

But I'm not sure how things would work with the functions. What would the functions for `Poset` and `Ord` be? 
In this hierarchy, `Ord` would have trichotomy, so it could use `data Ordering = LT | EQ | GT`, but `Poset` would need tetrotomy of `data PartialOrdering = PLT | PEQ | PGT | PNC` or `data PartialOrdering = C Ordering | NC`.

So, we can have:

```purescript
class Poset a where
  pcompare :: a -> a -> PartialOrdering

class Ord a where
  compare :: a -> a -> Ordering

(<), (<=), (>), (>=) :: Ord a => a -> a -> Boolean
```

Or something.

The laws for `Poset` would be the current laws for `Ord`, and then ord simply adds `totality`:

```
∀x, y ∈ Ord a, x <= y or y <= x
```

Though, this might actually be free from the type signature...

**Comment by hdgarrood** [comment]
I quite like @joneshf's suggestion, but one thing that bothers me slightly about it is that having to define `Poset` instances for types which people never intend to use `pcompare` on might be a bit irritating.

Could we do either of:

a) Remove the superclass `Ord => Poset` until we have the ability to do `deriving (Poset, Eq, Ord)`
b) Write an instance `instance ordPoset :: (Ord a) => Poset a where pcompare x y = C (compare x y)`?

**Comment by garyb** [comment]
We could do b). It's a little dodgy in that there's a risk over overlapping instances, but since there is only one sensible `Poset` instance for every `Ord` (right?) I don't think it will be a problem.

Having said that, the way we handle this elsewhere is by providing a function that can be used for default implementations (like `imapF` in `purescript-invariant`, `ap`, `liftM1`, in the prelude) when an instance can be provided in terms of another, so then you'd only have to write:

``` purescript
instance posetSomeTotallyOrderedThing :: Poset SomeTotallyOrderedThing where
  pcompare = pcompareOrd
```

**Comment by hdgarrood** [comment]
> one sensible Poset instance for every Ord (right?)

Yes, this is what I was thinking.

I do like the `pcompareOrd` approach too though; on second thoughts, it doesn't seem too much to ask to write instances like that, particularly since you'd probably only have to write it once per type.

**Comment by paf31** [comment]
Since we want `Lattice` to be more fine-grained than is suitable for `Prelude`, we've decided to keep `BooleanAlgebra` in `Prelude` with `Bounded` as a superclass, and to create a separate library with the `Lattice` classes.
