### ISSUE TITLE
LICENSE file & license directory causes trouble on Windows

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1104]
Windows has a case insensitive file system and also doesn't allow a file with no extension to coexist with a directory of the same name in a parent directory, so some odd things happen after checking out now.

**Comment by paf31** [comment]
Git doesn't seem to want to pull the directory on MacOS either.

/cc @hdgarrood Do you have a Linux box which this can be corrected on?

**Comment by hdgarrood** [comment]
Hahaha oops, sorry, will do
