### ISSUE TITLE
No instance found for Prelude.Show for values declared in psci

### ISSUE THREAD

**Issue by kaervin** [purescript/purescript#1107]
I am trying to call show for an instance of it for a newtype I have declared in my Main file.
The value I call it for I have declared in psci via a let.
```
> let b = Main.Complex {real : 33, imaginary : 12 }
```
When calling show b, I am getting the error:
```
Error in module $PSCI:
Error in value declaration it:
Error at  line 1, column 5 - line 1, column 49:
  No instance found for Prelude.Show Main.Complex
```
Doing the same for a value I have declared in the main file shows the wanted behavior and it gets printed.
I am using pulp as my project manager.
What could be the problem?

**Comment by hdgarrood** [comment]
Does your code in Main.purs look like this?
```purescript
module Main where

newtype Complex = Complex
  { real :: Number
  , imaginary :: Number
  }

instance showComplex :: Show Complex where
  show (Complex x) =
    "Complex { real: " <> show x.real <>
      ", imaginary: " <> show x.imaginary <> " }"
```

**Comment by hdgarrood** [comment]
- because I tried to reproduce your problem using the above code, and I wasn't able to.

**Comment by kaervin** [comment]
Using this code:
```
module Main where

newtype Complex = Complex
  { real :: Number
  , imaginary :: Number
  }

instance showComplex :: Show Complex where
  show (Complex x) =
    "Complex { real: " <> show x.real <> ", imaginary: " <> show x.imaginary <> " }"

a = Complex { real : 12, imaginary : 13}
```
I get this in my terminal:
```
C:\Users\kaervin\PureScript\p1>pulp psci
 ____                 ____            _       _
|  _ \ _   _ _ __ ___/ ___|  ___ _ __(_)_ __ | |_
| |_) | | | | '__/ _ \___ \ / __| '__| | '_ \| __|
|  __/| |_| | | |  __/___) | (__| |  | | |_) | |_
|_|    \__,_|_|  \___|____/ \___|_|  |_| .__/ \__|
                                       |_|

:? shows help
> Main.a
Complex { real: 12, imaginary: 13 }

> let b = Main.Complex { real : 12, imaginary : 14 }
> b
Error in module $PSCI:
Error in value declaration main:
Error at  line 1, column 5 - line 1, column 50:
  No instance found for Prelude.Show Main.Complex
See https://github.com/purescript/purescript/wiki/Error-Code-NoInstanceFound for more information, or to contribute content related to this error.
```
I have the very same problem on my linux installation as well.

**Comment by hdgarrood** [comment]
Ahh, ok. I can reproduce this now; the reason it worked for me previously was that I imported Main manually in psci first (which you could use as a workaround for now).

**Comment by garyb** [comment]
I think this is specific to `psci`, if you use fully qualified names in a module it should bring the instances through for that module too. I'm not entirely sure why it doesn't here though, perhaps due to how the internal `$PSCI` module is constructed.
