### ISSUE TITLE
Explain the origin of type variables in type errors, where possible

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1111]
For example, ghci with `-XScopedTypeVariables` says:

```
λ: let x :: forall i. i -> String; x s = s

<interactive>:3:39:
    Couldn't match expected type ‘String’ with actual type ‘i’
      ‘i’ is a rigid type variable bound by
          the type signature for x :: i -> String at <interactive>:3:17
   [...]
```

The `i is a rigid type variable bound by the type signature...` stuff could potentially make some errors from psc much easier to understand, I think.

**Comment by paf31** [comment]
:+1:

**Comment by paf31** [comment]
Added the `easy` label. This should just be a case of tracking a bit of data in the `Skolem` constructor, like the skolem scope is currently tracked.
