### ISSUE TITLE
Change error for when module is imported twice

### ISSUE THREAD

**Issue by puffnfresh** [purescript/purescript#1112]
I recently did this:

```purescript
import Data.Date (Now(), now)
import Data.Maybe (maybe, Maybe(..))
import Data.Array (filter, modifyAt, (!!))
import Data.Function (on)
import Data.Date (Date(), toEpochMilliseconds)
```

And kept getting a strange error:

```
  Unknown type Now
```

Took me a long time to figure out that I had `Data.Date` imports twice, and I only figured it out as quickly as I did because I've run into it before. It would be more useful to error:

```
  Data.Date module has more than one unqualified import statement.
```

**Comment by garyb** [comment]
Related: #817
