### ISSUE TITLE
Disallow constraints with no type variables

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1115]
(Unless the constraint is nullary)

**Comment by paf31** [comment]
Is there an example? Does this mean "everything on the left of => must be on the right somewhere"?

**Comment by garyb** [comment]
Ah, it's not very clear from the description - I meant things like `SomeClass SomeType => ...` so where only concrete types are provided in a class constraint.

**Comment by paf31** [comment]
This gives a reasonable use case for constraints without type arguments:

http://www.well-typed.com/blog/2015/07/checked-exceptions/

I think it should give a warning though.

**Comment by garyb** [comment]
I can't remember the exact context for raising this - I think someone was using a "concrete constraint" for an instance that doesn't exist. Instead of a warning perhaps we just need a slightly different error (if it's possible to detect) when the lookup fails.

**Comment by paf31** [comment]
Note that we never infer constraints which would give ambiguous types. Also, GHC allows this with `AmbiguousTypes`, so there is some more relevant reading material. I think it's fine to allow this in checking mode only. That is, if the user specifies an ambiguous type, we should probably warn, but let them continue to use it.

**Comment by paf31** [comment]
Show Int => Int
