### ISSUE TITLE
Please document supported OS/ghc versions clearly

### ISSUE THREAD

**Issue by mcclure** [purescript/purescript#1121]
Hello. Last night I spent some time unsuccessfully attempting to install Purescript. My machine is running fairly out of date software: Mac OS X 10.6.8 on 64-bit Intel, and I have a copy of GHC 7.6.3 (w/ Cabal 1.16.0.2) installed since I don't even remember when. Running the OS X binaries from your github "release page" failed (running any one simply resulted in the message "illegal instruction") and cloning git and building master (by running `cabal install` in directory) failed with a cryptic message ( https://pbs.twimg.com/media/CFlh4K_VEAA8coU.png:large ).

I understand you cannot necessarily support old operating system versions or old GHC versions; my point is not to ask that be changed, and I am not asking for help installing (a friend with a newer GHC helped and I now have purescript running). However, I think your messaging about which software versions are supported can and should be improved. Doing so would have saved me a bunch of time. It seems labeling "supported" operating system version for binaries is especially important on Linux and OS X (where Apple routinely introduces backward-incompatible changes to the dev tools, although I do not know how sensitive Haskell programs are to this).

Here are some places a brief message about supported versions could have been, but aren't:

- The "release" page on Github says nothing https://github.com/purescript/purescript/releases/tag/v0.6.9.5 (this is just a commit message, but since it is linked from "latest release page on GitHub" on your website it would be reasonable to expect it to contain this information)
- The README in macos.tar.gz says nothing
- Nor the README in linux64.tar.gz
- The README.md in git does not mention it either in master (which effectively is your "front page" for anyone who happens to stumble onto your github project instead of going to purescript.org first) or the v0.6.9.5 source release, incidentally it is not in the release notes either
- The build could have detected early that it was in an unsupported GHC version, but didn't (note: I *did* build master, maybe a build from v0.6.9.5 or directly from cabal is better-behaved)
- http://www.purescript.org/download/ does not mention this information-- looking now, oops, I *do* see that the "Cabal" install section says it wants "Haskell Platform 2014 or GHC 7.8"!, although this is maybe a vague statement (does it refer to building the source or installing via cabal?).

Expected behavior: Brief statements saying which OS versions are supported by the binaries, and which OS/GHC versions are supported when building from source, should be accessible. I think your release page (or if that's hard, the READMEs in the binary packages) would be a sensible place for this information, and README.md would be a sensible place for source compatibility information. Somewhere on http://www.purescript.org/download/ (maybe more prominently than a subsection) would also make sense. If you do not know exactly which versions are supported, a brief statement about "these binaries were tested on/this source was built on…" would still be useful.

**Comment by hdgarrood** [comment]
GHC 7.8 (which, I think, is what was used to build those binaries) requires OS X 10.7 or later, apparently (see https://www.haskell.org/ghc/download_ghc_7_8_4#macosx_x86_64). This seems like a potential culprit for the "illegal instruction" issue, although if you did manage to get it to work without using a VM then I guess that's not it. Do you remember how you managed to get it working?

**Comment by mcclure** [comment]
A friend of mine volunteers for Homebrew and has a 10.6 build server. She just fired up the build server and made a purescript binary package, apparently using whatever the current ghc 7.8 and purescript packages are in Homebrew. Homebrew possibly has patches to make ghc 7.8 work in 10.6, as they do that kind of thing…?

**Comment by mistydemeo** [comment]
While there isn't an official 10.6 binary for GHC 7.8, it still can be built on older versions of OS X without patching. Homebrew doesn't do anything special to build it. I used GHC 7.6.3 to bootstrap it, since there are 10.6 binaries available for that.

**Comment by hdgarrood** [comment]
Wherever we decide to put this information, it would probably also be a good place to note that if the package "terminfo" fails to install when building from source, this is probably due to missing libncurses headers, and can be fixed on Ubuntu by installing `libncurses5-dev`.

How about `INSTALL.md` in the repository, link to it from the `README`, also write one or more `INSTALL.$OS.md` for OS-specific things, and then copy `INSTALL.md` and `INSTALL.$OS.md` (for the relevant OS) into the readme when creating a binary distribution?

**Comment by hdgarrood** [comment]
Ahhh, I can't believe I didn't realise this sooner! The cryptic error <https://pbs.twimg.com/media/CFlh4K_VEAA8coU.png:large> arises from allowing base-4.6! We can fix this by requiring at least base-4.7 in `purescript.cabal`, then you get a "failed to resolve dependencies" error instead. PR on the way.

**Comment by hdgarrood** [comment]
Silly me, GHC 7.6 _is_ now supported (only in master, though, so the first actual release to support GHC 7.6 will be 0.7.1 I believe).

**Comment by hdgarrood** [comment]
I'm not sure we should close this just yet; I think it's only partially addressed. The `base` requirement in `purescript.cabal` now ensures that only supported GHC versions may be used and avoids cryptic errors like this one, but that leaves a few extra things we could still do:

* Updating information on the website's download page http://www.purescript.org/download/ - it currently says GHC 7.8 is required, but I think it should really say GHC 7.6 or newer.
* On that same page, perhaps clarify that installing from Cabal has the same constraints as building from source?
* Now that we support GHC 7.6, we could also advertise that even though we don't offer downloadable binaries, OS X 10.6 users can get the compiler by building from source with GHC 7.6.

I think a good first step could just be to put all the troubleshooting information we have (including supported OSes, or at least "known to work on") into an `INSTALL.md` file, include it in binary bundles, and reference it in READMEs.

**Comment by hdgarrood** [comment]
Also, if that sounds ok, I would be happy to write it.

**Comment by paf31** [comment]
Sounds good to me. On the website, a reference to `stack` would probably be good too.

**Comment by paf31** [comment]
I think `INSTALL.md` covers most of this, and I have open issues on the website repo for doc fixes there.

**Comment by barracuda156** [comment]
> Silly me, GHC 7.6 _is_ now supported (only in master, though, so the first actual release to support GHC 7.6 will be 0.7.1 I believe).
> 

Wonder if it built for PowerPC as well. (GHC 7.6.3 builds on 10.5.8 and 10.6 for ppc.)
