### ISSUE TITLE
Pattern Guards

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#1123]
I've been finding myself using them more and more: https://wiki.haskell.org/Pattern_guard

**Comment by paf31** [comment]
Can be implemented as sugar. If someone wants to take this on, feel free. Would also be interested in "with-patterns".

**Comment by paf31** [comment]
I've moved this back to Ideas, but I'm in favor.

**Comment by andyarvanitis** [comment]
Great! Funny, I was just thinking about this the other day. I'd like to find some time to implement it if no one else does it first.
