### ISSUE TITLE
Numeric literals with leading zeros

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1125]
This is a little surprising:

```
>> 010 == 10
true
```

In most other languages that I'm aware of, including JavaScript, a leading 0 indicates an octal literal, so `010 == 8`. I think we should either disallow leading zeros, or interpret them as octal.

I prefer the first option; if I ever wanted an octal literal, I think I'd rather do something like `readInt 8 "777" ` (from `purescript-globals`), or simply write the decimal version in the code and add a comment with the octal version.

**Comment by michaelficarra** [comment]
Agreed, disallow leading zeros.

**Comment by garyb** [comment]
Another :+1: for disallow leading zeros.

**Comment by michaelficarra** [comment]
Let's add the `easy` tag to this one.

**Comment by paf31** [comment]
:+1:

**Comment by garyb** [comment]
Closed by #1127
