### ISSUE TITLE
Disallow nullary constraints?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1126]
Since there is no useful way to use them without adding an orphan instance.

From @puffnfresh

**Comment by garyb** [comment]
I'm fine with that. We've had some nice ideas about how they might work, but never actually use them in practice so it's not a great loss.

**Comment by puffnfresh** [comment]
Banning orphans is what I'm really after. This issue would just be a consequence.

**Comment by garyb** [comment]
I'm very much in favour of that too, so :+1:

**Comment by joneshf** [comment]
What about #554? Nullary type classes seem like a good way to encode partiality and such.

Or perhaps there's another way?

**Comment by garyb** [comment]
I'm not sure, that was the main case I had in mind when I mentioned nice ideas.

Perhaps when we get @nicodelpiano's exhaustivity checker we can disallow partial functions outside of modules named `Unsafe` or something. Another suggestion @puffnfresh had was an `Unsafe` type, and then something like `runUnsafe :: Unsafe a -> a`.

**Comment by paf31** [comment]
As we've discussed before, nullary constraints _are_ useful, but you wouldn't use them by defining an instance, as that defeats their purpose and would lead to orphans anyway. You'd use them by providing unsafe escape hatches like `unsafePartial :: forall a. (forall dummy. (Partial) => a) -> a`. I'm closing this as a duplicate of "don't allow orphans".
