### ISSUE TITLE
Proposal: IDE Protocol for PureScript

### ISSUE THREAD

**Issue by archaeron** [purescript/purescript#1128]
I'm working on an atom plugin for idris and have the pleasure of working with it's IDE protocol.

The idea is that the compiler has a built in machine readable repl that you can use to implement IDE features such as:
- type lookup of a word
- documentation lookup of a word
- code completion
- repl in the context of your project
- code highlighting

An example from the idris documentation:
```
> ((:load-file "/home/hannes/empty.idr") 1)
< (:write-string "Type checking /home/hannes/empty.idr" 1)
< (:set-prompt "/home/hannes/empty" 1)
< (:return (:ok "Loaded /home/hannes/empty.idr") 1)
> ((:type-of "Nat") 2)
< (:return (:ok "Prelude.Nat.Nat : Type" ((0 15 ((:name "Prelude.Nat.Nat") (:implicit :False) (:decor :type) (:doc-overview "Unary natural numbers") (:type "Type") (:namespace "Prelude.Nat"))) (18 4 ((:decor :type) (:type "Type") (:doc-overview "The type of types") (:name "Type"))))) 3)
```

The documentation of the idris implementation:
http://docs.idris-lang.org/en/latest/reference/ide-protocol.html

Similar thing for Haskell (but I like it when it's built into the compiler, so that you're always working with the same compiler/ide backend):
https://github.com/chrisdone/ide-backend-client

**Comment by paf31** [comment]
I'd love to support this, but it seems like a good standalone project for someone to take on. I'll happily take PRs to implement this though.

**Comment by archaeron** [comment]
do you have any pointer on where to start with something like this?

**Comment by paf31** [comment]
Implementing something like "given these externs files, give me the type of `x`", seems like a useful first thing to implement, that could be added into an editor.

Plus, we could nail down the protocol even if we only implement one feature.

**Comment by david-christiansen** [comment]
Just as a note, the Idris REPL provides every command in both the machine-readable syntax that @archaeron describes as well as a human-readable syntax. This lets it integrate nicely with both editors that support subprocesses nicely (Emacs, Atom) and those that really just need to dump stuff into a new process (Vim). Also, you can do the fancy stuff with Idris in Notepad if you don't mind copying and pasting snippets of generated code.

**Comment by kRITZCREEK** [comment]
I started working on a tool like this at https://github.com/kRITZCREEK/psc-ide. It's currently in a very early state but the type lookup inside `externs.purs` files is working so far.

I'd love to get your feedback and ideas!

**Comment by paf31** [comment]
@kRITZCREEK very cool!

Here's another option for finding out types inside expressions: add a wildcard type to the term you're interested in, and inspect the wildcard warning after compilation.

**Comment by kRITZCREEK** [comment]
@paf31 sneaky! I'll definitely explore that route.

**Comment by dbushenko** [comment]
Cool! I'll try to start integration with Emacs!

**Comment by dbushenko** [comment]
Your project wants ghc-7.10.2, but on the latest Fedora I have just 7.8.4.... :-(

**Comment by kRITZCREEK** [comment]
@dbushenko the project is set up to be built with stack. I'll provide some instructions in the README.

**Comment by paf31** [comment]
I'd say `psc-ide` is the answer here, at least for the moment. Can this be closed then?

Perhaps one day `psc-ide` could be distributed with the compiler?

**Comment by kRITZCREEK** [comment]
Might be a good idea now that I started integrating with the compiler.

**Comment by archaeron** [comment]
:+1: I'll close this. Thanks all.
