### ISSUE TITLE
Compiler erroneously thinks that a type class member hasn't been implemented. 

### ISSUE THREAD

**Issue by michaelochurch** [purescript/purescript#1141]
I'm trying to define a Sum monoid for the Number type, and finding that the compiler doesn't recognize the implementation of the (<>) member. 

Here's a Gist: https://gist.github.com/michaelochurch/59dd3d50aba701929fbb

**Comment by paf31** [comment]
Try breaking out `(<>)` into a `Semigroup` instance:

https://github.com/purescript/purescript/tree/0.6.9.5/prelude#semigroup

Hopefully it's just the error that's wrong, and this should say something like "`<>` is not a member of `Monoid`".

**Comment by jdegoes** [comment]
You can't deconstruct on records like this, can you? It should be `n.getSum + m.getSum`.

**Comment by paf31** [comment]
Yes, that too.

**Comment by michaelochurch** [comment]
Thanks!
