### ISSUE TITLE
Implement DCE for new foreign modules

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1150]

**Comment by paf31** [comment]
Here's a very preliminary version of a command line tool to do DCE on "PureScript-style" CommonJS modules:

https://github.com/paf31/psc-bundle/

There is still lots of work to be done, but I'm happy to do it if we think this is a good way to go.

**Comment by garyb** [comment]
If we can do it this way it might well be better, as DCE for `psc-make` output in general would be great even if people are still using webpack or browserify to actually make the bundle.

I assume we would still provide an option for actually bundling with this, and `--main` type thing again too?
