### ISSUE TITLE
Duplicate instances allowed?

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#1153]
Module `Data.Array` contains:
```
instance invariantArray :: Invariant Array where
  imap = imapF
```
But so does `Data.Functor.Invariant`, which `Data.Array` imports:
```
instance invariantArray :: Invariant Array where
  imap = imapF
```
Is the compiler supposed to allow this? Sorry if this is a known behavior.

**Comment by garyb** [comment]
No, it's not. If you try and use the `Invariant Array` instance I think it will error, as that's when it performs the lookup and you'll get an overlapping instances error.

What version of `purescript-arrays` do you have? I thought I removed the instance in `v0.4.0-rc.1`.

**Comment by andyarvanitis** [comment]
I see, thanks. I spotted it when the C++ compiler caught the duplication and was a bit surprised.

It is definitely gone from `prescript-arrays` now -- I had forked the day before you fixed it, and thought I was current.
