### ISSUE TITLE
Warnings have no line numbers

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1165]

**Comment by paf31** [comment]
@nicodelpiano Do you think you could have a look at this, since you already handled it for exhaustivity?

**Comment by garyb** [comment]
I had a quick look at it when doing the other thing with error messages actually - I think it's just the shadowed name warnings that are missing them, and it's easy to see why: https://github.com/purescript/purescript/blob/0555e6e735ccc6a17c0c4c9bfc35234f9a67f5ff/src/Language/PureScript/Linter.hs#L55

We kinda need an `everythingWithContextOnValuesM` (or `everythingOnValuesM` and use a reader/writer) to easily do it this way.

**Comment by garyb** [comment]
Or just extend the context to include a `Maybe SourceSpan` I guess.

**Comment by nicodelpiano** [comment]
@paf31 Sure! I'll definitely work on this

**Comment by nicodelpiano** [comment]
I think this can be closed.
