### ISSUE TITLE
Feature request: `psc-make` warn about non-existent files

### ISSUE THREAD

**Issue by mjgpy3** [purescript/purescript#1176]
Recently I ran a command akin to:
```
~/.cabal/bin/psc-make purescript-prelude/src/Prelude.purs --ffi purescript-prelude/src/Prelude.js  IDontExist.purs Foobar.purs
```

And got the output:
> Compiling Foobar
Writing output/Foobar/index.js
Writing output/Foobar/externs.purs

It would have been nice if `psc-make` told me that `IDontExist.purs` didn't exist, since it was what I was actually interested in building/testing. Thoughts?

**Comment by puffnfresh** [comment]
0.6.9.5 gives:

```
psc-make: IDontExist.purs: openFile: does not exist (No such file or directory)
```

So if this is with master, it's probably a regression to do the globbing recently added.

**Comment by paf31** [comment]
Thanks!
