### ISSUE TITLE
psc-make generates invalid externs file in presence of un-exported synonyms

### ISSUE THREAD

**Issue by qxjit** [purescript/purescript#1179]
When a module exports a type synonym but fails to export synonyms used in its definition, psc-make generates an externs file with references to the un-exported synonyms. On subsequent psc-make runs the un-exported synonym is reported as an unknown type since it is not found in the externs file.

Presumably the first build should fail because of the un-exported synonym in the first place?

**Comment by garyb** [comment]
Yep, if it fails on subsequent builds it should fail the first time too. 

Just checking I understand correctly, it's when you have something like this:

``` purescript
module Test (X()) where

type X = Y
type Y = String

```

?

**Comment by qxjit** [comment]
You're too fast! Here's a minimal example: https://github.com/flipstone/purescript_issue_1179

**Comment by garyb** [comment]
Ah perfect, thanks!

**Comment by paf31** [comment]
Possible duplicate of #1318?

**Comment by paf31** [comment]
Can we close this now?

**Comment by garyb** [comment]
Yep!
