### ISSUE TITLE
Verify 'failing' tests fail in the correct way

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1181]
We should use the `ErrorMessage` type to make sure that each failing test is generating the correct general category of error.

**Comment by puffnfresh** [comment]
This was something I was worried about while making my optimisation changes :+1:

**Comment by mjgpy3** [comment]
Maybe it would be useful to include descriptions of the example failure message. I've started running through them and am having difficulty understanding if a given failure is as originally intended, or due to some new change.

**Comment by mjgpy3** [comment]
Or maybe rename the files to be more descriptive, e.g. `DuplicateDeclarationsInLet.purs`

**Comment by LiamGoodacre** [comment]
As part of `tests/Main.hs` would we explicitly write out the test cases loading specific examples and checking the outcome?

Could probably do it incrementally too - where we track tested cases and those that are missed are still checked for compilation failure as they are now?

---

Could I try to do this once we've decided what to do?  As my first contribution to the project :smile:

**Comment by paf31** [comment]
One approach might be to modify the tests temporarily to print out the filename and failure code, then turn that into the mapping we need by hand.

As for where the mapping goes, it could live in code, or just in a text file inside the examples/failing directory.
