### ISSUE TITLE
Optimization: Commit to type class instance if head matches

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1182]
If an instance head matches, we shouldn't need to backtrack and try other instances if the subgoals fail. We should be able to commit to that instance, and fail immediately, with a better error message. This should have the nice advantage of speeding up instance search.

We probably can't use the `List` monad any more though, since we can't prune sibling trees based on information in the current subtree.

**Comment by puffnfresh** [comment]
@paf31 was this done in 0.7.4?

**Comment by paf31** [comment]
Yes, but I still need to look into how it might be used for optimization.
