### ISSUE TITLE
Unexpected "may not be defined" Error

### ISSUE THREAD

**Issue by mjgpy3** [purescript/purescript#1185]
I wrote the following code:
```
module Main where

data Person = Person String Int

getName p = case p of
  (Person name 20) -> name
  _ -> "Unknown"

name = getName (Person "Jimmy" 20)
```
To my surprise, it failed with:
```
Compiling Main
Error found:
Error in module Main:
Error in binding group getName, name:
Error at /home/michael/dev/me/purescript/examples/passing/InternalBindingNameShouldExistAtTopLevel.purs line 9, column 8 - line 9, column 34:
  getName may not be defined in the current scope
See https://github.com/purescript/purescript/wiki/Error-Code-NameNotInScope for more information, or to contribute content related to this error.
```
If I change `name =` to something like `jimmyName =` everything works

Thoughts?

**Comment by mjgpy3** [comment]
Note, this does not seem to be necessarily related to #1169, because if I fix the `case` to accept an `age` it fails the same way

**Comment by paf31** [comment]
I think the error is here: 

https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/BindingGroups.hs#L114

The state of the traversal doesn't extend from the `Binder` to the body of the case statement.

**Comment by mjgpy3** [comment]
Why do `usedNamesE` and `usedNamesB` return type `(Set Ident, [Ident])`? What're the semantics of `fst` and `snd` in this case?

**Comment by paf31** [comment]
The `Set` is the set of bound names, which is the state type, and the `[Ident]` is the return type - it represents the list of used names. Top-level names aren't used up if they're bound by something, like a `Binder`, since the name now refers to something else.

**Comment by mjgpy3** [comment]
Thanks for the clarification

**Comment by mjgpy3** [comment]
I need help. I looked a this for a long while and couldn't figure out where the issue was. Any further suggestions for getting started here?
