### ISSUE TITLE
Make superclass code gen less ugly

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1186]
After the operator renaming, the only really ugly thing (to my eyes) in the current generated code is the code for a superclass instance:

``` javascript
var Category = function (__superclass_Prelude$dotSemigroupoid_0, id) {
    this["__superclass_Prelude.Semigroupoid_0"] = __superclass_Prelude$dotSemigroupoid_0;
    this.id = id;
};
```

How can we tidy this up and keep the same performance?

One simple way might be to just change the naming. The indexing is enough to guarantee uniqueness of argument names, so we don't need the module name, and `__superclass_` is a bit cumbersome too. Since class names are `ProperName`s, and members are `Ident`s, their names can't overlap, so we don't even need the `__`:

``` javascript
var Category = function (Semigroupoid_0, id) {
    this.Semigroupoid_0 = Semigroupoid_0;
    this.id = id;
};
```

If the class name is unique in the set, which it tends to be in a large number of cases, we could dispense with the index too:

``` javascript
var Category = function (Semigroupoid, id) {
    this.Semigroupoid = Semigroupoid;
    this.id = id;
};
```

An alternative could be to put all superclass instances in an array, but then we lose the names:

``` javascript
var Category = function (__superclasses, id) {
    this.__superclasses = __superclasses;
    this.id = id;
};
```

**Comment by garyb** [comment]
Making superclasses an array would impose a performance penalty over what we currently have, so tweaking the naming is probably the way to go.

**Comment by garyb** [comment]
:+1: though, the names are hideous :smile:

We just have to make sure it's easy to reconstruct the names where needed, although #928 will probably help with this if we can fix the typechecker to support it.

**Comment by paf31** [comment]
@garyb This is fixed now, right?

**Comment by garyb** [comment]
Not yet, it'll be part of #928 when I return to that. The dictionary names passed around are better now though.
