### ISSUE TITLE
Suggested `<<<` in definition rewrite

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1189]
Rewrite definitions like `something = f <<< g` as `something x = f (g x)`

**Comment by puffnfresh** [comment]
I already did this, right? https://github.com/purescript/purescript/pull/1070

**Comment by paf31** [comment]
Yes, I think so.

**Comment by puffnfresh** [comment]
At least a duplicate of https://github.com/purescript/purescript/issues/1066

**Comment by garyb** [comment]
Ah, great!
