### ISSUE TITLE
Document GHC-extensions effectively present in PureScript

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#1190]
I think it would be nice to add the list of PureScript features that are the same as (or at least similar to) GHC extensions to the "Differences from Haskell" section of the wiki. I would be happy to add them, but I'd like to collect the list here (if it's agreed that it's a good idea). To start:

* RankNTypes
* ExplicitForAll
* EmptyDataDecls
* ?

**Comment by garyb** [comment]
- ScopedTypeVariables

**Comment by paf31** [comment]
PartialTypeSignatures
MultiParameterTypeClasses
FlexibleContexts
FlexibleInstances

**Comment by andyarvanitis** [comment]
Thanks! Added "Extensions" section to wiki.
