### ISSUE TITLE
Implement record updates using prototypes instead of shallow copying

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#1191]
Currently, this PureScript code

```purs
person { firstName = "John", lastName = "Smith", age = 30 }
```

compiles to this JavaScript

```js
(function () {
    var _62 = {};
    for (var _63 in person) {
        if (person.hasOwnProperty(_63)) {
            _62[_63] = person[_63];
        };
    };
    _62.firstName = "John";
    _62.lastName = "Smith";
    _62.age = 30;
    return _62;
})()
```

but because of the immutability guarantees in our language, it should be safe to do this instead

```js
(function () {
    var _62 = Object.create(person);
    _62.firstName = "John";
    _62.lastName = "Smith";
    _62.age = 30;
    return _62;
})()
```

In ES6 (and likely all ES5 implementations), we can even do this

```js
({
    __proto__: person,
    firstName: "John",
    lastName: "Smith",
    age: 30,
})
```

The problem I see with this is that we could potentially create very large prototype chains, something I'm not sure engines have optimised for, and this may not allow those potentially unused objects to ever be garbage collected. When we can prove that the update source is never used later, we can use mutation instead.

At the very least, when we know all of the fields of the record, we can just manually copy those fields instead of iterating over its own-properties.

**Comment by paf31** [comment]
Moved to "Ideas" since this needs more research into GC etc.

**Comment by paf31** [comment]
Closing, since this hasn't been discussed in over a year, but if someone wants to do the research into the GC implications, we can reopen.
