### ISSUE TITLE
Suggested `flip` rewrite

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1196]
``` purescript
flip f y x = f x y
```

**Comment by garyb** [comment]
I don't think we have this one yet anyway :wink:

**Comment by michaelficarra** [comment]
Who is fully applying `flip` in-place? It seems like they should just do this in their own code.

**Comment by garyb** [comment]
It can be convenient if you want to do something like `flip fn x $ \y -> ...some load of code...`.

**Comment by michaelficarra** [comment]
Not really, I'd just use `let`. But if that's what people actually do, I guess we should optimise it.

**Comment by Fresheyeball** [comment]
Is using flip in-place  for convenience bad? My understanding was that using `let` to define a variable only used once is not considered idiomatic.

**Comment by rightfold** [comment]
Other optimisations may introduce `flip` being applied to all arguments in-place.

**Comment by paf31** [comment]
Closing, and I will open another issue for more general inlining.
