### ISSUE TITLE
After `cabal install purescript`, typing `psc` writes a bunch of Javascript into console

### ISSUE THREAD

**Issue by flq** [purescript/purescript#1201]
ghc : 7.8.3
cabal: 1.22.4.0
which psd : /Users/flq/.cabal/bin/psc

I am on OS X Yosemite

The javascript definitely seems purescript related, but I think that was not the intention of the exercise :)

**Comment by paf31** [comment]
This is the default behavior of `psc` in 0.6.*. You're seeing the compiled Javascript for the Prelude modules which get shipped with the compiler.

**Comment by flq** [comment]
Okay, now I feel silly - thanks!

**Comment by paf31** [comment]
This behavior will change in 0.7 actually. All of the Prelude modules will be moved into libraries, and the default behavior will be to report "No input files" like most other compilers would do.

**Comment by flq** [comment]
Definitely a bit less confusing for a complete noob :+1:
