### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#121]

**Comment by darrrk** [comment]
:+1:

**Comment by LiamGoodacre** [comment]
This would be really nice to have :]

**Comment by dkoontz** [comment]
As an anecdotal addition to this discussion, when I floated PS as a potential successor to vanilla JS amongst my team, lack of sourcemaps was raised as one of the primary concerns. I know runtime exceptions shouldn't happen in PS, but being able to set a breakpoint and step through code is viewed as an indispensable feature to have in a language. I'm not saying it actually is a necessity just that I see it perceived that way, especially from people transitioning from a JS mindset. So from a marketing/adoption standpoint sourcemaps might have a lot of value even though they may not have as much day-to-day value.

**Comment by garyb** [comment]
Agreed, that's pretty much what I was trying to say [here](https://github.com/purescript/purescript/pull/1693#issuecomment-162364507) :smile:

**Comment by codygman** [comment]
I think having source maps would be amazing for purescript adoption.

**Comment by AppShipIt** [comment]
@codygman 👍 Another oft ignored use case is inspecting data at runtime. Could its infrastructure also help the compiler expose types of all expressions to tools by tracking source locations?

**Comment by TehShrike** [comment]
When a compile-to-JS language doesn't have source maps, that signals to me "we expect you to have to debug our transpiler output, not the original language".

When a compile-to-JS language has first-class source maps, it signals to me "we expect the transpiler to always work and you can just pretend you're writing a different language."

I personally prefer my language abstractions to be non-leaky, so I only use languages with full sourcemap support.

You may find my signal-reading inaccurate, but telling me so is unlikely to change how I read those signals :-x

To me, first-class source map support (viewed from Chrome) includes
1. thrown errors have stack traces with all original file names and line numbers, and clicking on the file name/number opens it in the source tab
2. breakpoints and tracing work without any jumping around, as if the original language was natively supported by Chrome

Tastes vary, I do see plenty of people willing to use compiled JS without good sourcemaps.

But be careful about considering sourcemaps as having "not  as much day-to-day value" - once you're used to accurate line numbers that open the right file when you click on them, and full breakpoint/step support, you get value from them every day.

**Comment by garyb** [comment]
Well, the thing is, you shouldn't be seeing runtime errors from PureScript code anyway... that's one of the reasons why the language exists.

There's a PR with progress on this now anyway: #1693

**Comment by AppShipIt** [comment]
@garyb ^ See tooling question?

**Comment by jdegoes** [comment]
Though source maps will soon exist (see above PR), their lack of existence is mainly a problem for people who don't use PureScript. I have never used a debugger nor even looked at generated JavaScript code in all my PureScript coding experience. PureScript programs just don't throw exceptions, unless you're doing something terribly wrong.

**Comment by TehShrike** [comment]
You can mentally replace "thrown errors" in my comment with "console logs".

**Comment by TehShrike** [comment]
@jdegoes I don't think that's accurate - sourcemaps aren't for people who want to intract with the JavaScript output - without sourcemaps, that's actually the only thing you can do.

Sourcemaps enable people to debug their Purescript code with accurate line numbers (that link straight to the source code) in console logs or by using breakpoints to trace through their code.

**Comment by garyb** [comment]
@AppShipIt I'm not too sure actually. It sounds like a great idea, but I suspect you can only annotate with basic line/col span info.

**Comment by jdegoes** [comment]
> Sourcemaps enable people to debug their Purescript code with accurate line numbers (that link straight to the source code) in console logs or by using breakpoints to trace through their code.

Exactly, and as someone who has written more PureScript than most, I have never needed to debug, use breakpoints, or step through code. Even though I do so when writing JavaScript.

The protection afforded by the type system means you spend more time on bugs that a debugger can't really help you with.

I don't think I'm an anomaly, I think most people who write PureScript do not debug their programs and aren't particularly interested in source maps (I gather this from a discussion on the user list).

**Comment by hdgarrood** [comment]
Yeah, my experience is extremely similar to @jdegoes'. The one time I did end up stepping through purescript compiler output, it turned out to be a compiler bug.

**Comment by natefaubion** [comment]
I'll echo a similar sentiment. I can only think of one time when I've thought sourcemaps would be handy, and that was when futzing around with the FFI, which is a great way to introduce run time bugs :P In normal PS, it just won't get the same usage.

I don't know if usual debugger tools make as much sense either. Like would you step through a big do block in `Aff`? At the PS level it looks like a simple block of synchronous code, but it's really a lot of async machinery that can jump around a lot. What does it mean to set a breakpoint on a monadic bind? In general, typeclass machinery results in a bit of runtime indirection, so it wouldn't be at all like debugging your usual imperative routine. I'd say, if you were going to use debugger tools, you'd probably _want_ to look at the JS source so you could fine tune what you actually wanted to observe.

**Comment by starper** [comment]
The only runtime error that I have is "Maximum call stack size exceeded", 'cause I always forget about tail call. Btw I think it would be nice to have some kind of warning about potential runtime error in this case (if it does not exist yet). I felt that I realy need source maps when I was using coffeescript or livescript, but with purescript I don't understand why I should need them. Also I don't understand why some people are so concerned about readable JS (debates about removing primes for example)? As for me, if compiler produced unreadable minified mess, I wouldn't really care. Who's gonna read it anyway?

**Comment by AppShipIt** [comment]
I have _often_ wanted the debugger (in Elm as well when a page someone else worked on wouldn't load because of a HTTP error) to inspect values (e.g. responses) at runtime without recompiling. In other typed languages I've needed to conditionally pause animations to understand unexpected values (although perhaps a side effect of uninhibited mutation). Not to mention error sensitive FFI is a first class use case for PureScript.

From a tooling perspective it should open the door to API for types at the expression level (über wish). As a web developer (among other things) I'd also like to be able to browse a PureScript user's demo right in the inspector. Even without types it might encourage (although not prerequisite) tools like browser extensions that have bolstered the React ecosystem.

Most of all from a marketing perspective it's a basic expectation of JavaScript expats. I also watched source maps asked for and unceremoniously shot down (I empathize) on Elm's mailing list. I'd rather the PS community's response to be iterating on developer experience (with amazing tools like @sharkdp's Flare)  instead of nominalizing it ("you don't need that").

@TehShrike Although errors are rare in native code I don't think anyone needs convinced source maps would be nice to have. The primary issue is man hours and priorities. @nwolverson stepped up in addition to leading conversion of both the Atom and Code extensions to native PS. @paf31 is so productive I suspect he contrived a time warp with @garyb and @hdgarrood. I can barely find time just to update the Wikipedia article 😝

@starper Readability is another touchy feely JavaScript wish but also essential for simple interoperability.

**Comment by natefaubion** [comment]
I don't think it's quite that a PS debugger wouldn't be useful, just that using the built in "set break point at this line" debugger, which is mostly tailored for your typical imperative JS, isn't that useful.

**Comment by hdgarrood** [comment]
Ok, @AppShipIt has convinced me. I *do* use printf-debugging often, and being able to achieve the same thing without recompiling does seem like it could be very useful. Or at least that it's worth a try. :)

**Comment by AppShipIt** [comment]
Resolved by #1693.
