### ISSUE TITLE
Class context synonyms?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1210]
It might be asking for all kinds of trouble, but seems like a nice idea in principle.

From @jdegoes here: https://github.com/slamdata/purescript-halogen/commit/2631061b3c55d6cf89960203fd851e74c772ba3b#commitcomment-11921315

**Comment by paf31** [comment]
Hmm, nice in theory, but synonyms give us trouble generally, since it's not obvious when to expand them. Too soon, and error messages are bad, too late and types don't unify.

Full `ConstraintKinds` would be nice too.

**Comment by jonsterling** [comment]
What about jiggering up the unification to "remember" the things it was initially trying to unify, such that it would report that in the error message when unification failed? Then, it could unfold definitions as it goes. (Disclaimer: I have not looked at the source to the PureScript typechecker)

**Comment by joneshf** [comment]
I haven't tried to update this library for 0.7.x but this worked earlier this year: https://github.com/joneshf/purescript-ui/blob/2e5a9fcffc49dbb2ff8046a4c231c92736bf799f/examples/Examples/Graphics/UI/Logo.purs#L15-L18

Could you do something similar nowadays? I know there was a big change to orphans or classes or something that might affect it.

**Comment by paf31** [comment]
I think this is subsumed by constraint kinds. Close as duplicate?

**Comment by garyb** [comment]
Agreed!
