### ISSUE TITLE
Bundle all js files

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1213]
Why cannot you do something like
psc-bundle "output/**/*.js"  > all.js
?

**Comment by garyb** [comment]
You can!

`psc-bundle output/**/*.js > out.js`

**Comment by user471** [comment]
It just generate empty out.js

**Comment by paf31** [comment]
What does `find output -name '*.js'` give?

**Comment by shinnn** [comment]
`output/*/.js` :x: 

`output/*.js` :o:

**Comment by user471** [comment]
output/*.js still empty
I guess the problem is --module parameter is required

**Comment by user471** [comment]
>find output -name '*.js'
I use windows

**Comment by paf31** [comment]
`output/*/*.js` then?

**Comment by user471** [comment]
I have simple test project with only Main.purs
So the contain of output is
Main\index.js
Prelude\foreign.js
Prelude\index.js

**Comment by garyb** [comment]
> I guess the problem is --module parameter is required

Uh, whoops... it could be, let me check something.

**Comment by garyb** [comment]
Yes indeed. I managed to create an slighlty old version of the binaries for windows. I've updated them now, so if you redownload and reinstall you should get the intended behaviour.

**Comment by user471** [comment]
Thanks. It works now.
