### ISSUE TITLE
How use psc-bundle with foreign.js?

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1214]
For example I want to bundle Prelude.
psc-bundle "output/Prelude/index.js" -m "Prelude" > prelude.js
In prelude.js there is a line 
var $foreign = PS["Prelude"];       
How suppose the functions from foreign.js get into PS["Prelude"]?

**Comment by garyb** [comment]
The bundled file will have two groups of exports for a module, so in the case of `Prelude` it should look something like this:

```
(function(exports) {
  /* global exports */
  "use strict";

  // module Prelude

  ... bunch of foreign js ...
 
})(PS["Prelude"] = PS["Prelude"] || {});

(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Prelude"];       

  ... bunch of purescript js ...
 
})(PS["Prelude"] = PS["Prelude"] || {});
```

Because it uses `PS["Prelude"] = PS["Prelude"] || {}` in both cases, the foreigns actually get merged into the main set of exports for the module.

**Comment by user471** [comment]
But when you use
psc-bundle "output/Prelude/index.js" -m "Prelude" > prelude.js
It only generate second part
(function(exports) { // Generated by psc version 0.7.0.0 "use strict"; var $foreign = PS["Prelude"]; ... bunch of purescript js ... })(PS["Prelude"] = PS["Prelude"] || {});

**Comment by garyb** [comment]
`psc-bundle` needs to be passed all of the `.js` files to operate on, so as you've specified `output/Prelude/index.js` specifically it will only consider that file.
