### ISSUE TITLE
Where is Debug.Trace module?

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1215]
I cannot find it.

**Comment by garyb** [comment]
It doesn't exist in 0.7, the replacement is https://github.com/purescript/purescript-console.

**Comment by user471** [comment]
I think it should be mentioned in release note.
And why there isn't trace function?

**Comment by garyb** [comment]
It kind of is, under "No modules are included with the compiler now, they have been broken out into their own libraries". The `log` function is the old `trace` function.

It was renamed because `Debug.Trace` is misleading, for people coming from Haskell it suggests a function for debug logging that bypasses purity, whereas our version is for general purpose console logging and has a corresponding `Eff` type signature.

**Comment by user471** [comment]
>No modules are included with the compiler now, they have been broken out into their own libraries

I installed purescript today and use pulp to generate project. The project template is using Debug.Trace and I don't really know the language libraries so it was unpleasant experience of seaching this modul. The release note or migration note should have module names so you can use ctrl+F to figure out what exactly is changed

**Comment by paf31** [comment]
I don't think Pulp has been released yet. You will need to use `master`.

**Comment by paf31** [comment]
Also, the migration guide is on the wiki, exactly so that users can contribute useful things which they feel are missing. Please feel free to do so.

**Comment by user471** [comment]
>for people coming from Haskell it suggests a function for debug logging that bypasses purity

Is there real trace function in ps?

**Comment by paf31** [comment]
Like the one in Haskell? Maybe you want https://github.com/CapillarySoftware/purescript-debug-foreign

**Comment by user471** [comment]
They are using inline js. I guess I need to rewrite it?

**Comment by paf31** [comment]
Yes it hasn't been updated for 0.7.

**Comment by user471** [comment]
Is there something to help for migration. like some tool to move inline js to separate file?

**Comment by paf31** [comment]
Sorry, no. Just cut and paste right now.
