### ISSUE TITLE
Ability to parse d.ts files as purescript bindings?

### ISSUE THREAD

**Issue by flq** [purescript/purescript#1216]
Hi,
this is just an idea I would like to throw up for discussion. I have seen that there is the idea that purescript bindings to frameworks / libraries available only as javascript can be defined.

In the typescript world, there are already a big number of bindings available for typescript compile passes & and they are also well maintained. There is also a tool, `tsd`which is available to download and install such definitions.

While the type information may not be as rich as can be expressed in purescript, there may still be a lot of useful information contained.

This could be done in one of two ways, I suppose...

* Compiling directly against a d.ts fie is possible and supported by psd
* A component of pulp that translates a d.ts file into a purescript binding definition.

So I was wondering if there would be interest in the ability to use such d.ts files in order to make available bindings to purescript compile passes.

**Comment by joneshf** [comment]
There have been a couple of issues about this:

https://github.com/purescript/purescript/issues/14
https://github.com/purescript/purescript/issues/29

As far as I can surmise, the typescript type system isn't powerful enough to make it worthwhile.

**Comment by flq** [comment]
Yup, both touch implementing the other direction. I'd rather consume d.ts from purescript. 

Why?

I may be a grumpy pessimist, but I can't see the same numbers of people going into purescript the same way as people are moving towards typescript. Don't get me wrong, purescript may be my salvation, but a lot of people are and will put their effort into Ts. Leveraging this effort (also considering the wealth and pace of change in Js-libraries) may be worth it, if only to have a good starting point to set up purescript bindings.

**Comment by vendethiel** [comment]
Rather than "consume", maybe a tool could generate the correct foreign imports... With a few exceptions you'd have to fix manually? That's how ScalaJS does it IIRC

**Comment by user471** [comment]
There definitely should be some tool to generate ffi from d.ts For example, some day I would like to use phaser game engine with purescript so you not only need to rewrite all this manually https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts but you also have to manually correct all feature changes in new versions.

**Comment by paf31** [comment]
I've written such a tool in the past, for a restricted use case. Believe me when I say, it's very non-trivial to get the types to line up in a non-trivial way (i.e. without resorting to `Foreign` all over the place). I wrote `language-typescript` to parse `.d.ts` files in Haskell, if you want to have a go.

**Comment by user471** [comment]
> (i.e. without resorting to Foreign all over the place)
I don't see a problem. The main benefit if library has d.ts you can use it at the same moment. If you don't like generated code you can always change it. So at least you have some sort of skeleton to work with.

I think the good solution would be if you can write the plugin to this tool so it can auto rewrite generated code specific for this library.

By the way why ps does not have macros system? Do you think it is unnecessary? I believe every language should have macros, it can improve language design because the language can has only basic staff and everything else can be created by macros.

**Comment by paf31** [comment]
Supporting a subset of the `.d.ts` standard shouldn't be too hard, if you don't care about using `Foreign` in a lot of places. I can try to dig out my previous code.

**Comment by flq** [comment]
Well, I asked because I would like to contribute sth to PS. However, I probably try to get my hands dirty with the issues tagged easy, to get a feel for the project.
I am sure that the proper type matching isn't trivial, but I think it's effort well spent.
It seems that the consensus is that a tool converting d.ts to FFI would be the way to go. 
Access to the work you already did would be great. Just let me know how you want to make it available :)

**Comment by paf31** [comment]
I was looking for it today, but could only find a very out-of-date version, which is essentially useless. `language-typescript` is on Hackage though, which gives you the parsing piece.

**Comment by paf31** [comment]
Closing since this is not going to be part of the compiler.

**Comment by pkamenarsky** [comment]
@paf31 Could you elaborate a bit more on why there needs to be `Foreign` all over the place?

I think it would be pretty useful to be able to generate up-to-date bindings from i.e. https://github.com/DefinitelyTyped/DefinitelyTyped (for example for `react` or `react-native`) and then build higher-level libraries on top of those (i.e. `purescript-react` could depend on the generated bindings for `react`).

The bindings could be autogenerated for every new pushed TypeScript type definitions version (using a webhook or whatever) and the higher-level libraries updated in case of incompatibilities.

**Comment by garyb** [comment]
`Foreign` would occur whenever there are functions with overloaded arguments / union types / etc.

More of a problem in my eyes is that there's no information about where effects occur in a `.d.ts`, so that means either making everything `Eff`, or not using it at all. The former is horrible from an API point of view, but the latter is even worse.

**Comment by pkamenarsky** [comment]
Ah yes, of course. Generated bindings would be unusable then.

**Comment by garyb** [comment]
I think there's still possibly something to explore though, it could always generate Eff-everywhere bindings, and then leave it up to you to convert as appropriate - at least that way a bunch of the initial work is done already. It's just the dream of `.d.ts` -> perfect `.purs` that I think is dead :smile:

**Comment by pkamenarsky** [comment]
Regarding union types etc, is it not possible to just play it dumb? I.e. isn't the [following](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/index.d.ts#L77) definition:

    interface DOMFactory<P extends DOMAttributes<T>, T extends Element> {
        (props?: ClassAttributes<T> & P | null, ...children: ReactNode[]): DOMElement<P, T>;
    }

more or less equivalent to the following:

    type Element ext = { ... | ext }

    type DomAttributes t ext = { ... | ext }

    type T extt = Element extt
    type P extp = DOMAttributes (Element extt) extp

    type Null = ...
    type Any = ...

    type DOMFactory p t = forall extp extt.
                          Either (Tuple (ClassAttributes (T extt)) (P extp)) Null
                       -> Array ReactNode
                       -> DOMElement (P extp) (T extt)

I.e. union types are tuples, `nulls` and `anys` are translated directly, interfaces are just extensible records. Am I missing something?

**Comment by pkamenarsky** [comment]
Hm, on second thought `DOMFactory` can't be parameterized on `T` and `P` I guess...

**Comment by felixSchl** [comment]
@garyb Eff everywhere sounds good to me as it captures the truth about JS/TS
