### ISSUE TITLE
Implement Typeclassopedia in Prelude

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#122]
`Prelude` should have standard classes: 

- Functor
- Applicative
- MonadPlus
- Alternative

**Comment by garyb** [comment]
Can we close this one now? I think we've done most of the non-numeric stuff outlined here, and anything we've not done we're probably not doing in the `Prelude` now.

**Comment by paf31** [comment]
Yep, I think so. Thanks very much for working on all of this!

**Comment by garyb** [comment]
No problem, doing things the right way gives me warm fuzzies ;)
