### ISSUE TITLE
Typed Binders

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1227]
E.g. 

```purescript
useString :: forall m. (MonadState String m) => m Blah
useString = do
  s :: String <- get
  ...
```

**Comment by garyb** [comment]
Also would be nice in lambdas for some things:

``` purescript
quickCheck' 100 \xs :: List Int -> ...
```

Maybe bracketing required there.

**Comment by LiamGoodacre** [comment]
Bracketing feels necessary:

~~~purescript
\a :: forall a. a -> a -> a
~~~

Is this the identity function or is it a syntax error because there's no body?

~~~purescript
\(a :: forall a. a -> a -> a) --error no body
\(a :: forall a. a -> a) -> a --identity function
~~~

**Comment by garyb** [comment]
Yeah, exactly :smiley:

**Comment by michaelficarra** [comment]
If there's only one possible parse that's not a syntax error, that's not an ambiguity.

**Comment by 5outh** [comment]
I think I'd like to work on this. Any pointers for where to get started?

**Comment by paf31** [comment]
@5outh Great! I would start by adding a `TypedBinder Binder Type` constructor to `Binder`, and adding a parser for it. Then add an example and see what breaks. There will be a few traversals which need updating, and a line or two will need to be added in `TypeChecker/Types.hs`.

**Comment by 5outh** [comment]
Thanks @paf31 :)

**Comment by 5outh** [comment]
@paf31 Any tips on getting the project to build? Master doesn't seem to want to `cabal install` with ghc 7.10.2 (even in a sandbox):

```
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: purescript (user goal)
rejecting: purescript-0.7.4.1, 0.7.3.0, 0.7.2.1, 0.7.2.0, 0.7.1.0, 0.7.0.0,
0.6.9.5, 0.6.9.4, 0.6.9.3, 0.6.9.2, 0.6.9.1, 0.6.9, 0.6.8, 0.6.7.1, 0.6.7,
0.6.6, 0.6.5, 0.6.4.1, 0.6.4, 0.6.3, 0.6.2, 0.6.1.2, 0.6.1.1, 0.6.1, 0.6.0.2,
0.6.0.1, 0.6.0, 0.5.7.1, 0.5.7, 0.5.6.3, 0.5.6.2, 0.5.6.1, 0.5.6, 0.5.5,
0.5.4.1 (global constraint requires ==0.5.4)
trying: purescript-0.5.4
trying: base-4.8.1.0/installed-075... (dependency of purescript-0.5.4)
next goal: monad-unify (dependency of purescript-0.5.4)
rejecting: monad-unify-0.2.2 (conflict: base==4.8.1.0/installed-075...,
monad-unify => base>=4.5 && <4.8)
rejecting: monad-unify-0.2.1, 0.2.0.1, 0.2.0.0, 0.1.0.0 (conflict: purescript
=> monad-unify>=0.2.2 && <0.3)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by paf31** [comment]
Hmm I don't have that issue. Maybe try `stack` if you have it?

**Comment by 5outh** [comment]
Ah, I'm using a really old version from a previous fork. I'll figure it out, I just need to sync my fork with the current purescript/master.
