### ISSUE TITLE
Move some make and bundle code into the library

### ISSUE THREAD

**Issue by wuzzeb** [purescript/purescript#1229]
So I'm working on updating [yesod-purescript](https://github.com/mpietrzak/yesod-purescript) to version 0.7, and it would help if some of the code that exists in `psc` and `psc-bundle` were moved into the library.  If you don't want to do this, we can change yesod-purescript to execute the `psc` and `psc-bundle` binaries instead of using the library directly.  The only downside to this is then yesod-purescript needs options to be able to find these executables, so needs options for the path to the cabal or stack sandbox (since yesod-purescript depends on the purescript package, it will be installed into the sandbox).  Also, reporting errors is harder since we need to examine the output of the binaries, instead of more controlled error reporting we get from using the purescript library directly.

What I would suggest is the following:

* move the contents of `psc/Make.hs` and the make stuff from `src/Language/PureScript.hs` into a new module at `src/Language/PureScript/Make.hs`.  This might even be a beneficial cleanup since it moves the make stuff out of the root of the library hierarchy at Language.PureScript.  We don't need anything from `psc/Main.hs`.

* move `withDeps`, `compile`, and `codeGen` from `psc-bundle/Main.hs` to a new `src/Language/PureScript/Bundle.hs` module and create a wrapper function `bundle` which calls these three functions similar to how `app` does now.  I would only export this new `bundle` function, not the individual steps in the bundle.

What do you think?

**Comment by paf31** [comment]
I'm in favor of moving some code over, since we can probably share code between `psci`, `psc` and the test suite. I'll also need it when I update the Try PureScript site.

**Comment by wuzzeb** [comment]
So to help the discussion, I made the following commit which moves the make code so you can see what it would look like.  I haven't done any testing but it does compile, and I didn't change any of the code, just moved it.

  https://github.com/wuzzeb/purescript/commit/9ef45690ab1ca46c51da9a492092329dc06e4f2c

**Comment by wuzzeb** [comment]
This is now fixed with pull request #1245 being merged.
