### ISSUE TITLE
Wording change for unknown explicit import

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1232]
For example:

```
module Main where

import Prelude (thisDoesNotExist)
```
currently gives "Unknown value Prelude.thisDoesNotExist". I think "Prelude does not export thisDoesNotExist" would be better, in order to help differentiate it from, eg, errors arising from values not being in scope in expressions.

**Comment by puffnfresh** [comment]
:+1:

**Comment by paf31** [comment]
:+1:
