### ISSUE TITLE
How to use external js files?

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1234]
I have js file Data.js

    var Data = {};
    Data.test = {foo:123};

I wrote JsData.purs

    module JsData where
    type Foo = {foo :: Int}
    foreign import test :: Foo

and JsData.js

    exports.test = Data.test; 

I can use it in browser with

    <script src="Data.js"></script>

But where should I put Data.js if I want to use it in psci?

    > JsData.test.foo
    exports.test = Data.test; 
                   ^
    ReferenceError: Data is not defined

And also with pulp run.

I can put Data.js code in JsData.js file but maybe there is simple solution to use separate files?

**Comment by paf31** [comment]
If you want to bundle external files, you might want to try `psc-bundle`. I'm not sure if there's a good way to include them in `psci`, unless you want to wrap them up as CommonJS modules and import them that way.

**Comment by user471** [comment]
>wrap them up as CommonJS modules

I guess then just copying code to JsData is the simplest way
