### ISSUE TITLE
Why psc-hierarchy is not included in the archive now?

### ISSUE THREAD

**Issue by shinnn** [purescript/purescript#1241]
```
$ wget -O - 'https://github.com/purescript/purescript/releases/download
/v0.7.0/linux64.tar.gz' | tar zxvf -
$ ls purescript
LICENSE
psc
psc-docs
psci
README
psc-bundle
psc-publish
```

AFAIK `psc-hierarchy` is included in the archive in a few days ago.

**Comment by paf31** [comment]
It wasn't included previously either:

https://github.com/purescript/purescript/commit/c92c7a602729a2beea034b20d630da6f9b33533b

**Comment by shinnn** [comment]
Oh, my bad. Should [the npm package](https://github.com/purescript-contrib/node-purescript-bin) include `psc-hierarchy` or not?

**Comment by paf31** [comment]
I never bundled it because it was only ever used for internal documentation (Prelude), so it's up to you.

**Comment by shinnn** [comment]
OK. I won't, too.

Thanks, @paf31.
