### ISSUE TITLE
exports from foreigns and psc-bundle

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#1242]
This module will be bundled 
```javascript
// module Foo
exports.foo = "foo";
exports.bar = "bar";
```
And this won't
```javascript
// module Foo
exports = {
  foo: "foo",
  bar: "bar"
};
```
This is bad because in example one can't do
```javascript
// AwesomeFFI
var inst = new Class();
exports = {};
for (var i in inst) {
  if (inst.hasOwnProperty(i)) {
    exports[i + "Impl"] = function() {
      var me = arguments[arguments.length - 1], 
          args =  Array.prototype.slice.call(arguments, 0, -1);
      return function() { 
        me[i].apply(me, args);
      };
    };
  }
}
```

**Comment by garyb** [comment]
The `AwesomeFFI` example is problematic as we can't analyse that for DCE, so even if the `exports = {}` approach worked it wouldn't help out here.

**Comment by cryogenian** [comment]
But if it is impossible to analyze if this code is dead, why is it deleted 0_o?

**Comment by garyb** [comment]
Hm, it shouldn't be - DCE is supposed to leave everything alone that does not follow the `export.xxx = _` or `exports["xxx"] = _` convention.

Declaring your own `exports` value may be the problem here though, you could try taking that out and just write to the `exports` object that is already in scope.

**Comment by cryogenian** [comment]
Thanks, after I removed `exports = {}` it's started to work. 
Maybe it should be stated in readme or wiki, that only `exports["xxx"] = ...` and `exports.xxx = ...` work.

**Comment by michaelficarra** [comment]
We really need to start using ES6 exports...

**Comment by SimonRichardson** [comment]
But then we would need to run through babel?

**Comment by michaelficarra** [comment]
Or at least something that just transforms the export declarations to CommonJS. The real problem standing in our way is that the third party JS parser we use doesn't currently accept ES6 export declarations. So no DCE until then.

**Comment by paf31** [comment]
> We really need to start using ES6 exports...

Agreed 100%.

**Comment by paf31** [comment]
Closing this since documenting `psc-bundle` is all we can do until we have a better module system.
