### ISSUE TITLE
Error when explicitly importing value re-exported from module

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript#1244]
I wasn't sure if this was known already or not, but I think I ran into a bug:

```purescript
module Foo where

  foo :: Int
  foo = 3

module Bar (module Foo) where

  import Foo

module Baz where

  import Bar (foo) -- this is the problem

  baz :: Int
  baz = foo
```

```
➜  rexport  psc src/Foo.purs 
Error:
Error in module Baz:
Error at /home/joneshf/programming/purs/rexport/src/Foo.purs line 12, column 3 - line 14, column 3:
  Unknown value Bar.foo
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue for more information, or to contribute content related to this error.
```

If the problem line is changed to `import Bar`, then things compile fine.

**Comment by garyb** [comment]
I think that's a new one, thanks for the report :disappointed:

**Comment by themoritz** [comment]
Same holds when `hiding` values.

**Comment by andyarvanitis** [comment]
I can have a look at this -- I'm pretty sure I know the fix.

**Comment by svisser** [comment]
I just got this error. Also note that the page at the indicated URL does not exist:

https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue
