### ISSUE TITLE
Improve error message when variable name "bind" is used in a do block.

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript#1253]
This gives a typechecker error, because desugaring uses the name "bind". This is a tiny little inconvenience, but I will not be the last one who wasted the time on this strange typechecker problem, since bind is (I guess) a relativ frequently used name.

**Comment by michaelficarra** [comment]
Additionally, you have to import `bind` to use do blocks in 0.7. I do not believe this was the case in 0.6, since I would always use explicit imports with Prelude and never needed to do that.

**Comment by nwolverson** [comment]
Error when not importing `bind` and writing a `do` block is a little confusing. The error when the `bind` of purescript-d3 was in scope instead was a lot confusing.

**Comment by michaelficarra** [comment]
@nwolverson See my edit above, #962, and #742. This is actually a PureScript 0.7+ feature.

**Comment by nwolverson** [comment]
Sure, I think this bug should either be renamed or closed in favour of a new one re the error message. Errors that mention identifiers not in your program are unfortunate to say the least, and this one will probably bite both those migrating and newcomers.

(I guess the redefining `bind` accidentally one is both harder to do anything about and less common than not importing it at all)

**Comment by paf31** [comment]
I'm not sure what we can do about this if we want to have rebindable syntax. Whatever name we pick could be used by some function somewhere.

**Comment by michaelficarra** [comment]
Yes, we should just have a better error for this occurrence.

**Comment by paf31** [comment]
It's worth noting that the error here is much better now. For example,

```purescript
foo = do
  bind <- [1,2,3]
  x <- [4, 5, 6]
  pure x
```

gives

```text
  Could not match type
       
    Int
       
  with type
                   
    Array Int -> t0
                   

while applying a function bind
  of type Int
  to argument [ 4
              , 5
              , 6
              ] 
```

The key is to read the last line:

```text
while applying a function bind of type Int to argument [ 4, 5, 6 ]
```

which I think makes it much clearer what's going on.
