### ISSUE TITLE
PSCi requires the purescript-console module to be installed.

### ISSUE THREAD

**Issue by TorosFanny** [purescript/purescript#1254]
I installed npm with `sudo apt-get install npm` and executed the following commands one by one. 
```
sudo npm install -g grunt-cli bower
bower install purescript-prelude
bower install purescript-eff
bower install purescript-st
bower install purescript-console
bower install purescript-functions
```

And I tried to install purescript both with binaries and from source and both can launch. But both reports `PSCi requires the purescript-console module to be installed`. I tried to type in a `3`, it reported that:
```
Error:
Error in module $PSCI.Support:
Error at  line 4, column 1 - line 5, column 1:
  Unknown module Control.Monad.Eff
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information, or to contribute content related to this error.
```

My platform is Ubuntu-14.04, ghc-7.10.2, cabal-1.22

**Comment by paf31** [comment]
Did you load the installed module into `psci`?

**Comment by TorosFanny** [comment]
I can remember what I have done to my computer, the issue is resolved unknowingly. I'm sorry for this issue report.

**Comment by TorosFanny** [comment]
No, I just typed:
```
qs@BF:~/Programs/purescript$ ./psci
 ____                 ____            _       _   
|  _ \ _   _ _ __ ___/ ___|  ___ _ __(_)_ __ | |_ 
| |_) | | | | '__/ _ \___ \ / __| '__| | '_ \| __|
|  __/| |_| | | |  __/___) | (__| |  | | |_) | |_ 
|_|    \__,_|_|  \___|____/ \___|_|  |_| .__/ \__|
                                       |_|        

:? shows help
PSCi requires the purescript-console module to be installed.
For help getting started, visit http://wiki.purescript.org/PSCi

> 3
Error:
Error in module $PSCI.Support:
Error at  line 4, column 1 - line 5, column 1:
  Unknown module Control.Monad.Eff
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information, or to contribute content related to this error.
```

**Comment by paf31** [comment]
Do you have a `.psci` file in your working directory?

**Comment by TorosFanny** [comment]
No, and I have never heard of that. Could you please be more specific? Or could you show me where can I find the related things?

**Comment by paf31** [comment]
Yes, the [getting started guide](http://www.purescript.org/learn/getting-started/) has an intro to PSCi using Pulp. Typically, you create a `.psci` file to automate loading of modules. `psci` will not find them for you.

**Comment by TorosFanny** [comment]
Thank you very much!
