### ISSUE TITLE
"foreign import data" not triggering FFI requirement

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#1255]
If a module only has foreign `data` imports, the checks for FFI files downstream doesn't catch it:

``` purescript
module Data.Foreign.Integer.Long (module Data.Foreign.Integer, Long(..), LongLong(..)) where
import Prelude
import Data.Foreign.Integer

foreign import data Long :: *
foreign import data LongLong :: *
```

I believe this can be fixed in `CoreFn/Desugar.hs` by adding an `ExternDataDeclaration` check:

```haskell
-- |
-- Desugars foreign declarations from AST to CoreFn representation.
--
externToCoreFn :: A.Declaration -> Maybe ForeignDecl
externToCoreFn (A.ExternDeclaration name ty) = Just (name, ty)
externToCoreFn (A.ExternInstanceDeclaration name _ _ _) = Just (name, tyObject)
externToCoreFn (A.ExternDataDeclaration name _) = Just (properToIdent name, tyObject) -- *not there*
externToCoreFn (A.PositionedDeclaration _ _ d) = externToCoreFn d
externToCoreFn _ = _ Nothing
```

If this looks right, I can submit a PR for it. It's fine for the C++ backend, but I wasn't sure if there are other implications for the JS backend.

**Comment by garyb** [comment]
`foreign data` is "just" a type signature, it may have no actual value associated with it, I think that's the reasoning for things behaving the way they do now - for instance, effects are `foreign import X :: !` but there is nothing else that needs to go with that, as they exist purely in the type system.

In some ways I wonder if it might be better if we did away with `foreign import data`, as you can do something similar now with kind signatures (`data Foo (x :: # !)`), it's only when the kind of the thing itself is not `*` that foreign is a requirement, so if we could do something to solve that there would be no "need" for `foreign data` at all.

@paf31?

**Comment by paf31** [comment]
Is this needed by the C++ backend? Do foreign data declarations have runtime dependencies?

**Comment by andyarvanitis** [comment]
Yeah, this is pretty much for cases where you would import a "custom" foreign type -- something not built into the backend, or an alias to something that is. It's not critical, I just thought it might have been a bug or oversight.

**Comment by garyb** [comment]
I'll close this one for now, as the current behaviour is intentional. We can revisit it later if it turns out to be the wrong choice!
