### ISSUE TITLE
Record constructor

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1258]
type Foo = {x :: Int, y :: String}

    newFoo x y = {x: x, y: y}

Is there any way to get newFoo constructor automatically for any record type?

**Comment by garyb** [comment]
``` purescript
newFoo = { x: _, y: _ }
```
?

**Comment by user471** [comment]
It's better, but you still need to write such function for every record type.

**Comment by garyb** [comment]
I can't say I find myself needing constructor functions like that very often - usually, I'd just use the `{ x: _ ...` form inline, like:

``` purescript
{ x: _, y: _ } <$> getX <*> getY
```

Or whatever.

**Comment by user471** [comment]
What if we could write something like this

    type Foo = {x :: Int, y :: String}

    bar :: Foo -> Int
    bar k = k.x + 1

    bar {10, 20}

Such syntax also can be useful for tuples

    fst {1 , 2}

**Comment by garyb** [comment]
The problem with that is rows are a set, not a list, so they don't have a specific order.

Also, when writing functions that operate on properties, keeping them polymorphic makes them more reusable, so for `bar` the better type would be:
```
bar :: forall p. { x :: Int | p } -> Int
bar k = k.x + 1
```

**Comment by user471** [comment]
>The problem with that is rows are a set, not a list, so they don't have a specific order.

How it could affect the use of this syntax?

>so for bar the better type would be:

We can still use this syntax 
    
    bar {10}
