### ISSUE TITLE
Review MakeActions API

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1264]
It's not clear to me how it works. Maybe we can revisit it when we implement parallel builds?

**Comment by garyb** [comment]
Sure thing. It's not much different from `MonadMake`, I switched it to a record as some of the provided functions needed additional info that is provided as an initial argument (`Reader` would have worked too, but it seemed simpler to do it this way).

**Comment by paf31** [comment]
Moving back to 0.8 as it seems this should be done before any parallel build stuff.
