### ISSUE TITLE
Tuple with Row Polymorphism and Effects

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1267]
main :: Eff (console :: Console, random :: Random) {}
    main = do
      n <- random
    print n

It looks like "trace :: " and "random ::" are just syntax noise because ps doesn't have more suitable solution. There should be something similar to tuple but with Row Polymorphism.
So, what if there could be a record type something like {item1::a, item2::b,...} and language could support syntax {a,b,...}

    foo :: {Int, String} 
    foo = {10, "bar"}

and with Eff

    main :: Eff {Console, Random} {}
    random :: forall e. Eff {Random | e} Number

Also I mentioned in https://github.com/purescript/purescript/issues/1258 this syntax could be used for all record constructors.
Does it make sense?

**Comment by mjgpy3** [comment]
So, if I had
```
foo :: {Int, String} 
foo = {10, "bar"}
```

And wanted to access the `"bar"`, I'd have to say `item2 foo`?

**Comment by user471** [comment]
foo is record type so you can use `foo.item2`

There also should be tuple functions like `fst` `snd`

**Comment by mjgpy3** [comment]
Gotcha, thanks for the clarification. So this would be complementary functionality to named getters/fields? Or would it replace them? What about mixed getters, e.g.
```
foo :: { count :: Int, String }
```

**Comment by user471** [comment]
> So this would be complementary functionality to named getters/fields?

Yes, when you don't really need names, like with effects. 

>foo :: { count :: Int, String }

I don't see where such mix can be useful.

**Comment by paf31** [comment]
This has been suggested a few times, but I think the better thing to support would be `(console, random)` meaning `(console :: _, random :: _)`, since often you don't care about the type or effect, just that the label is there. It also doesn't involve arbitrary label generation.
