### ISSUE TITLE
Easier FFI inclusion for `psc` command-line

### ISSUE THREAD

**Issue by mjgpy3** [purescript/purescript#1268]
Hello all,

I tend to compile my PureScript code using `psc` directly a good amount. Is there value in making JS FFI files included more easily? I can think of a couple approaches off the top of my head, the one that sounds most promising is a new flag, something like:
```
psc --auto-ffi-ext=js ...
```
Here it would simply look for files near the `*.purs` files, with the same names (except `js` in place of `purs`), and automatically include them as if they were given to `--ffi`.

Other approaches I can think of are:
 1. Simply assuming the file with the same name (but different extension) is an FFI
 2. Allowing the user to type the JS file name, without the `--ffi` flag, inspect the extension, and conclude it's an FFI

Thoughts?

**Comment by michaelficarra** [comment]
I like other option 2.

**Comment by paf31** [comment]
Option 2 sounds nice.

**Comment by garyb** [comment]
We currently don't even check if the PureScript source files have any particular extension, so we'll have to do that too :wink:

**Comment by michaelficarra** [comment]
That's okay, I think `.purs` is official enough.

**Comment by mjgpy3** [comment]
Ah sorry, that button order gets me sometimes. So other option 2 it is?

**Comment by garyb** [comment]
I only wonder what effect it would have on #1269

**Comment by mjgpy3** [comment]
@garyb, what potential effect(s) are you considering?

**Comment by garyb** [comment]
Uhh, don't mind me. I misread what option 2 was proposing.
