### ISSUE TITLE
psc very slow in processing file args

### ISSUE THREAD

**Issue by stkb** [purescript/purescript#1269]
In a project I've been working on, I've noticed that builds are consistently about 3 seconds slower if I use a long `psc` command with 1 file per arg (created by pulp), as opposed to a shorter command with globs (eg `psc src/**/*.purs bower-components/purescript-*/src/**/*.purs --ffi ...`)

The project, with dependencies has about 140 .purs and 40 .js files.

Don't know why this is or how much it's worth bothering with; as I say it mainly affects builds done with pulp (bodil/pulp#51), though pulp could be changed too to run `psc` with glob arguments instead.

**Comment by paf31** [comment]
Pulp uses globs now, so I'll close this.
