### ISSUE TITLE
False positives with the "function composition is (<<<)" suggestion

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1272]
I am starting to get quite a few false positives with this suggestion. For example:

```
> let x = { y: 3 }
> log x
Error at  line 1, column 1 - line 1, column 5:
  Cannot unify type
    { y :: Prim.Int }
  with type
    Prim.String
Note that function composition in PureScript is defined using (<<<)
```

Can the condition for showing this suggestion be made a bit stronger? Perhaps only when failing to unify an object with a function?

**Comment by paf31** [comment]
Same here. I'd be happy to remove it honestly, we can probably find a better way to add metadata to unification errors.

**Comment by mjgpy3** [comment]
I will remove

**Comment by paf31** [comment]
Well, maybe we should leave it in until we have a better approach. I don't think what we have is _bad_, it's just an experiment which I think didn't quite succeed.

**Comment by hdgarrood** [comment]
I think it's a bit of a shame to admit defeat already; it's certainly useful to learners, and it should be possible to come up with an acceptably accurate test, right? What about displaying the message iff the two types are `Prim.Object _` and `Prim.Function _ _`?

**Comment by hdgarrood** [comment]
I guess that's better, but could still lead to false positives: `let x = { y: 3 } in x 2` would presumably trigger it. Is it feasible to look inside the AST for the property access operator `.`? If that's there too, then I think we can be fairly sure about what's happening.

**Comment by paf31** [comment]
Don't we do that now?

**Comment by hdgarrood** [comment]
Not quite: https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Errors.hs#L673

**Comment by paf31** [comment]
Yeah, that's what I'm getting at with the "metadata" bit.

**Comment by garyb** [comment]
Shouldn't it be when both types are `Function`?

**Comment by paf31** [comment]
Ah ok, well we should definitely make the change to check for `Function`.

**Comment by garyb** [comment]
In fact, why do we check for `Object` at all here? We're looking for `f . g` aren't we?

**Comment by hdgarrood** [comment]
All we have at the moment is the `Error`, none of the AST. I don't think it should be when both are `Function`; for example:

```
> let f = g . g where g = (+1)
Error at  line 1, column 9 - line 1, column 15:
  Cannot unify type
    Prim.Object
  with type
    Prim.Function _0
```

We check for `Object` because that's what the type checker was expecting to find after it saw an object property access `.`.

**Comment by garyb** [comment]
Ah right, yeah.

**Comment by mjgpy3** [comment]
@hdgarrood with #1284, I believe these suggestions should have gone away. Can you provide additional troubling cases?

**Comment by hdgarrood** [comment]
Here's another that provides the suggestion where it probably shouldn't:

```
module ShouldNotSuggestComposition where

f :: forall a. (a -> a) -> a -> a
f g = g

rec :: {x :: Int}
rec = {x: 0}

x = f rec
```

**Comment by hdgarrood** [comment]
I think #1284 will fix the vast majority of these false positives. If we want to improve it further, I think we would need some kind of mechanism for the suggestion code to inspect the AST around where the error occurred, so that we could look for a `.` specifically.

**Comment by garyb** [comment]
Should we close this now #1284 is merged?

**Comment by hdgarrood** [comment]
I can't test right now, but I think the above example still does give the suggestion where it shouldn't.

**Comment by paf31** [comment]
I just tested this, and it works for me with the latest code.
