### ISSUE TITLE
Type checking failure with row instances

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1273]
For example:

```
module Main where

import Prelude
import Control.Monad.State
import Control.Monad.State.Class

type GenState = { newSeed :: Int, size :: Int }

foo :: State GenState String
foo = (show <<< _.newSeed) <$> get
```

Gives me:
```
Error in value declaration foo:
  No instance found for Prelude.Show _14
```

I think psc should be able to infer that `_.newSeed <$> get` is a `State GenState Int`, right?

**Comment by garyb** [comment]
I've had some similar problems recently: https://github.com/slamdata/purescript-halogen/blob/c109a757f95c9efaa482c53dafa9915ea3815886/src/Halogen/Component.purs#L89

**Comment by hdgarrood** [comment]
Possibly related and much more scary:

```
module Main where

import Prelude
import Control.Monad.State
import Control.Monad.Eff
import Control.Monad.Eff.Console
import Control.Monad.State.Class

type GenState = { newSeed :: Int, size :: Int }

foo :: State GenState String
foo = _.seed <$> get

main = log $ evalState foo { newSeed: 0, size: 0 }
```
Passes type checking and prints `undefined`.

**Comment by garyb** [comment]
:fearful:

**Comment by paf31** [comment]
It seems to be picking the `monadStateStateT` instance for `get`. Must be something to do with the recent-ish record-instance changes. I'll look at this.

**Comment by paf31** [comment]
Is this fixed in `master` now?

**Comment by paf31** [comment]
The second example fails to build now, the first still gives the same error.

**Comment by garyb** [comment]
The first one is #1027 isn't it? So we can probably close this one.

**Comment by garyb** [comment]
Oh, no, it's not.

**Comment by garyb** [comment]
It's nothing to do with rows though, you can trigger it this way too:

``` purescript
module Main where

import Prelude
import Control.Monad.State

foo :: State Int String
foo = show <$> get
```

Another one that would require constraint inference perhaps?

**Comment by paf31** [comment]
The first example is expected (usual inference issue, but with polymorphic record access to make it more interesting), the second example now fails on `master` with 

```text
No instance found for

  Control.Monad.State.Class.MonadState { seed :: String
                                       | _7
                                       }
                                       (StateT { size :: Int
                                               , newSeed :: Int
                                               }
                                        Identity
                                       )
```

as one would hope, and the third fails with

```text
No instance found for

  Prelude.Show _3
```
