### ISSUE TITLE
Type inference problem "No instance found for Prelude.Ord"

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1274]
```
module Main where

import Prelude
import Data.Map
import Data.Maybe
import Control.Monad.Eff.Console

-- updateFoo :: forall k. (Ord k) => k -> Map k Int -> Map k Int
updateFoo = update (\v -> Just 10)
```

```
Error at Main.purs line 3, column 1 - line 4, column 1:
  No instance found for Prelude.Ord _4
```
updateFoo isn't compiled without type annotation. Is it a bug? 

Also line and column are wrong.

**Comment by garyb** [comment]
It's not a bug. PureScript can't infer constraints, and as you're not providing any information about the type of `k` it can't find an `Ord` instance for it.

There's an existing issue for line number #1086, and I opened a PR for it earlier that should fix it :smile:

**Comment by user471** [comment]
>PureScript can't infer constraints

Is there any plan to implement it?

**Comment by garyb** [comment]
#202
