### ISSUE TITLE
Getting Started page in the wiki

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1278]
Should we just re-point this to [the article on the site](http://www.purescript.org/learn/getting-started/) now, or is there info in there that is useful in its own right?

**Comment by paf31** [comment]
I changed it to link to the site on the home page. Did you mean to add the page itself back, with a link?

**Comment by garyb** [comment]
I mean someone in IRC was looking at this earlier: https://github.com/purescript/purescript/wiki/Language-Guide:-Getting-Started until I passed on the new article link. So that page is what I was referring to.

**Comment by paf31** [comment]
Oh right. That's _really_ old at this point. I think we might be better off to just remove it honestly.

**Comment by garyb** [comment]
Fine by me!

**Comment by paf31** [comment]
I combined all of the old language guide back into a single page, called "Old Language Guide". I guess we can keep it around for now, in case we ever want to revive it, or as a quick intro for beginners.
