### ISSUE TITLE
Exhaustivity hangs compiler

### ISSUE THREAD

**Issue by nicodelpiano** [purescript/purescript#1281]
When we have a lot of cases to print as warnings, the compiler hangs.

Example:

```haskell
module Main where
 
data Alpha = A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z

f A A A A A A = A
f A B Z X _ _ = A
f B B _ _ _ _ = B
f Z _ Z _ _ Z = Z
```

**Comment by nicodelpiano** [comment]
[Exhaustive Line 244](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Linter/Exhaustive.hs#L244)
Here, I changed `bss` to `take 5 bss`, and the program finished well.

**Comment by paf31** [comment]
Great, could you please make that into a PR?

**Comment by garyb** [comment]
I don't think that's a fix though, is it? I guess unless we just cut it off at a maximum of 5 or whatever warnings...

**Comment by paf31** [comment]
@garyb Why not? `take 5` should be cutting off the number of binders inside a warning. The number of warnings should be one, I think.

**Comment by garyb** [comment]
Oops, I should probably have read the code first.

**Comment by nicodelpiano** [comment]
I've chosen five because it's what haskell takes as a maximum number of cases, is that ok?

**Comment by paf31** [comment]
I think 5 is fine. As I mentioned on IRC, we should be careful to avoid massive binder lists during `checkExhaustive`, but that can be written up as a separate issue.

**Comment by nicodelpiano** [comment]
:+1:

**Comment by nicodelpiano** [comment]
@paf31 I guess this can be closed, I created another issue for avoiding the unnecessary non-exhaustive cases: https://github.com/purescript/purescript/issues/1288
