### ISSUE TITLE
Typed holes

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1283]
Like how GHC does it. For example, if I write this:
```
foo :: List Int -> List Int
foo = map _
```
then I should get an error along the lines of:
```
Found typed hole with type Int -> Int:
  foo = map _
```
Perhaps distinguishing them from the record sugar like `{ foo: _ }` will be a problem though? If so, we could maybe require typed holes to be named, like `_foo`.

**Comment by paf31** [comment]
Or Idris style: `todo?`

**Comment by paf31** [comment]
Actually, this can be implemented using type wildcards.

**Comment by puffnfresh** [comment]
`?todo` is Idris style, to be pedantic.

**Comment by garyb** [comment]
:+1::+1::+1: for some form of this.

**Comment by hdgarrood** [comment]
@paf31 came up with a close approximation to this feature that works now: make sure you have a `todo :: forall a. a` in scope, and then write: `(todo :: _)`.

One way to get `todo :: forall a. a` without needing the FFI is to use `unsafeCoerce unit`.

**Comment by garyb** [comment]
Nice, that's a good way of doing it currently.

It might not work in the future, as I think we're going to relax the warnings to only appear when `_` is used in a top level declaration.

**Comment by AppShipIt** [comment]
Ping! Was there agreement about Idris style? @damncabbage

**Comment by mb21** [comment]
For googlers, the purescript syntax is:

    foo :: List Int -> List Int
    foo = map ?myhole
