### ISSUE TITLE
Warning: Module Prelude has been defined multiple times

### ISSUE THREAD

**Issue by Arsca** [purescript/purescript#1286]
Hi,
I'm noob with PureScript and cannot pass this warning:
```

Running "psc:all" (psc) task
>> Error creating file dist/Main.js
>>
Warning: Module Prelude has been defined multiple times

```

> psc --version
> 0.6.9.5

rgrds,

**Comment by hdgarrood** [comment]
You might find this reddit thread helpful: https://www.reddit.com/r/purescript/comments/3dh7nj/what_to_do_about_module_prelude_has_been_defined/ct57jbp

Also, @paf31 / @garyb, should this say "error" rather than "warning"?

**Comment by garyb** [comment]
Yeah, it halts on duplicate modules so should be an error.

**Comment by hdgarrood** [comment]
Forgot that this was an older version. I just checked and 0.7.1 does say "error".

**Comment by hdgarrood** [comment]
Also, @Arsca, you might find this helpful as well: http://www.purescript.org/learn/getting-started/
