### ISSUE TITLE
Error referenced non-existing wiki page

### ISSUE THREAD

**Issue by haf** [purescript/purescript#1287]
```
ERROR in ./src/ReCQ.purs
Module build failed: Error: Compiling ReCQ

Error:
Error in module ReCQ:
An export for execCommand requires the following to also be exported:
JSCmd
See https://github.com/purescript/purescript/wiki/Error-Code-TransitiveExportError for more information, or to contribute content related to this error.


  at ChildProcess.<anonymous> (/Users/h/dev/logibit/cmdui/node_modules/purs-loader/index.js:2391:32)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Socket.<anonymous> (child_process.js:1183:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:485:12)

 @ ./tests/ReCQ.coffee 5:7-34
```

**Comment by paf31** [comment]
Hence "or to contribute content related to this error" :smile:

This is our lazy evaluation strategy for creating wiki content.

**Comment by haf** [comment]
https://github.com/purescript/purescript/wiki/Error-Code-TransitiveExportError

**Comment by haf** [comment]
So I take it you don't like to get questions in the issue tracker; where's the best place to ask?

**Comment by paf31** [comment]
What was the question?

**Comment by haf** [comment]
For this issue; how do I export the `data` declaration? But I solved it and documented it in the above wiki link.

I tried running 'hello world' but that failed: https://github.com/ethul/purs-loader/issues/23 - so another question I have is how I run the Hello World sample?

**Comment by paf31** [comment]
Great, thank you!

You might like to follow through the [getting started](http://www.purescript.org/learn/getting-started/) guide for 0.7.
