### ISSUE TITLE
Avoid massive binder lists during checkExhaustive

### ISSUE THREAD

**Issue by nicodelpiano** [purescript/purescript#1288]
As Phil clarified:
we need to cap the total number of binders so that we don't run out of memory.

**Comment by paf31** [comment]
Not quite. We might need to evaluate more binders than we plan to print, but we still need to cap the total number of binders so that we don't run out of memory.

**Comment by nicodelpiano** [comment]
Oh, sorry! Now I understand what you pointed before :). Thanks for the
clarification

**Comment by paf31** [comment]
@nicodelpiano Do you plan to work on this one?

**Comment by nicodelpiano** [comment]
Yes, of course!

**Comment by nicodelpiano** [comment]
@paf31 What do you think the upper limit should be? Should it be a constant?

**Comment by paf31** [comment]
Yes, let's try a constant. We can probably decide a value by experiment by constructing some pathological examples.
