### ISSUE TITLE
Overlapping patterns

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1289]
Now we have the exhaustivity checker it would be nice to warn when there are overlapping patterns too.

**Comment by michaelficarra** [comment]
Overlapping patterns are used at times in parameter lists when using guards, so we should be careful not to warn about those.

**Comment by nicodelpiano** [comment]
I'm working with this issue :).

For example, if we have:

```haskell
module Main where
data T a = E | L a | B (T a) (T a)
f (L E) (B _ _) = E
f E E = E
f (L E) (B E E) = E
f _ _ = E
```
The compiler warns:
```
Overlapping cases has been detected.
The definition has the following redundant cases:
(Main.L Main.E) (Main.B Main.E Main.E)
```
The warning messages should be improved.

@michaelficarra Could you give an example of your suggestion? Thanks

**Comment by garyb** [comment]
Ah nice! :smile:

I think he means like:

``` purescript
foo n | if isOdd n = ...
foo n = ...
```

So cases where `otherwise` is not used, but a pattern is matched twice to the same effect.

**Comment by nicodelpiano** [comment]
@garyb Nice, thanks!

**Comment by nicodelpiano** [comment]
This can be closed.
