### ISSUE TITLE
ListLike type class

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1295]
Base library contains several types with similar interface. Array, Seq, List
Is there a reason they don't have common type class?
Something like this

```
module Data.ListLike where
import Prelude

class ListLike f where
	sortBy :: forall a. (a -> a -> Ordering) -> f a -> f a
	length :: forall a. f a -> Int

instance listLikeArray :: ListLike Array where
	sortBy = Data.Array.sortBy 
 	length = Data.Array.length
```

1) There could be common implementation of functions like
```
sort :: forall a b. (Ord a, ListLike b) => b a -> b a
sort xs = sortBy compare xs

sortWith :: forall a b c. (Ord c, ListLike b) => (a -> c) -> b a -> b a
sortWith f = sortBy (compare `on` f)
```
2) No need to worry about different sort functions for different types
3) I guess someday there will be deriving feature, so it could be used like this

```
data Foo a b = Foo a (Array b) deriving (ListLike)
bar = sort $ Foo "foo" [3,2,1]
```

**Comment by jdegoes** [comment]
This repo is for the PureScript compiler, issues like this should be opened in their respective libraries.

**Comment by paf31** [comment]
> Is there a reason they don't have common type class?

Something like this? https://github.com/joneshf/purescript-collections/blob/master/src/Data/Collection.purs

The thing about type classes is that they don't have to be defined in the standard library. They decouple implementation from specification.

Also, I agree with @jdegoes. I recently updated `CONTRIBUTING.md` to ask that questions be kept on IRC/SO/Reddit/Google Groups. I'll close this, but please feel free to raise the issue on one of those forums if the link above doesn't answer your question.

**Comment by user471** [comment]
>They decouple implementation from specification.

What is wrong with ListLike specification? For example I want to implement sortWith function, so I need to write the three same implementations because standard library don't have specification.
