### ISSUE TITLE
psc consumes enormous amount of RAM

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#1297]
During update of slamdata I've noticed that builds take lot more memory. 0.6.9.7 version used to consume about 250Mb in `psc` mode and 150Mb in `psc-make` mode. Now `psc` consumes more then 4Gb :disappointed:

**Comment by jdegoes** [comment]
With this issue, we cannot get our automated builds to pass, because Travis CI instances do not have a spare 4GB of memory. I'm surprised it's not affecting other OSS projects yet.

@puffnfresh How can we bribe you to take a look at this? :wink:

**Comment by puffnfresh** [comment]
It's tricky because the kernel will kill the process and so the GHC runtime won't have a chance to give any profiling information. I do have some rough info from compiling a small chunk of SlamData, though:

We allocated 24GB, around 1/3 under parseInputs, 1/5 under rebuildIfNecessary and 1/5 under typeCheckModule. Although I can't really get a fair comparison, this looks pretty similar to what we used to do.

The only obvious difference I've seen that I can see is that 15% of allocations come from `compile` itself (i.e. it allocates that much by itself, not the things under it) - a pretty big bump from 0%

**Comment by puffnfresh** [comment]
![master-heap-profile](https://cloud.githubusercontent.com/assets/37715/8873613/992c6070-324b-11e5-9827-a8163bac41b9.png)

**Comment by jdegoes** [comment]
@puffnfresh Wow, thanks, this is great.

`makeBindingGroupVisible` seems to have runaway behavior (as well as OTHER, unfortunately, collection of lots of other things). But overall no single culprit for explaining how the SlamData build went from 250MB to 4 GB. Could still be, e.g., a dependency bump in the compiler, used at a fairly low level and pervasively (e.g. mtl or something). But unless it's something like that, it's going to be a long hard road back to 250 MB.

**Comment by puffnfresh** [comment]
And this is the heap, by type of value:

![master-heap-type-profile](https://cloud.githubusercontent.com/assets/37715/8891894/2f4ec966-337e-11e5-81c3-c39284f8a87f.png)

**Comment by bitc** [comment]
I've added to purescript an alternative compile command, that compiles only a single `.purs` file. This way it can be called from an external build system. I have integrated it with [Shake](http://shakebuild.com/)

This way I get fast incremental builds, and support for parallel builds.

From my tests, it is slightly faster than `psc-make` (utilizing parallel compilation steps), and it is about 2x - 10x faster than `psc-make` for incremental builds (where a single ".purs" file has changed, performance difference varies depending on how deep in the dependency chain the modified file is located)

I'd be curious if you could try it out on your large project and tell me the performance. (I'm confident also that you won't experience with it the memory issues described in this issue and that it will successfully build large projects)

https://github.com/bitc/purescript/tree/psc-compile/psc-compile
https://github.com/bitc/purescript/blob/psc-compile/psc-compile/Shakefile.hs

**Comment by jdegoes** [comment]
> And this is the heap, by type of value:

Tuple and Kind account for nearly half of all memory allocations and grow faster than most of the others. ARR_WORDS (ByteArray) also grows very quickly.

**Comment by natefaubion** [comment]
> Tuple and Kind account for nearly half of all memory allocations and grow faster than most of the others. ARR_WORDS (ByteArray) also grows very quickly.

I think its `Map` rather than `Kind`.

**Comment by jdegoes** [comment]
>  I think its Map rather than Kind.

Yeah, sorry, my bad!

**Comment by garyb** [comment]
@paf31 did we `mtl`ify the code between 0.6.9.5 and 0.7, or was that earlier? I'm still completely baffled how we managed to make the memory usage explode like this, it seems like it would have to be something far-reaching like that...

**Comment by paf31** [comment]
I thought it was before. We might need to do a binary search for the commit which caused this :(

**Comment by mjgpy3** [comment]
Are you familiar with `bit bisect`? http://git-scm.com/docs/git-bisect

**Comment by paf31** [comment]
Yes, thanks! I've used it for this sort of thing in the past.

**Comment by garyb** [comment]
Alright. I mustn't have been sufficiently ruthless in excising the `MonadWriter` for warnings when I did that test the other day, going by `git bisect` it is indeed the culprit: 29bbd33e0fbdc7815ba86b540e3d1382b72816da :cry:

Actually, I should say "a culprit" as there's another commit much later that doubles the memory usage again on my mangled transformers test project. Bisecting again now to find culprit #2.

**Comment by garyb** [comment]
I wonder if it's worth investigating using a `State` monad instead of `Writer` for this, as in the case of the "`RSS` monad"...

**Comment by garyb** [comment]
Ok, so using the strict `Writer` helps _a great deal_ but hopefully we can still improve. Compiling `slamdata` clean the memory usage drops from 12gb to 2gb.

**Comment by garyb** [comment]
Re: bisect 2 I had to abandon it, as I ran into that revision where git is broken on Windows due to there being a `LICENSE` file and `license` directory being present at the same time, I'll re-run on my Mac once I've finished playing with `Writer`.

**Comment by garyb** [comment]
Actually I think strict `Writer` is the best we can do for that, the `State` based writer is _too_ strict. I'll look into culprit 2 now.

**Comment by jdegoes** [comment]
Nice work on this, @garyb! Making progress...

**Comment by paf31** [comment]
@garyb Very nice, thanks! I hit the bisect issue too, and I think I used `git reset` to shunt along a couple of commits to avoid the issue.

**Comment by paf31** [comment]
The parallel builds work seems to help a little here. If anyone wants to try out the `incremental` branch and see if it helps with SlamData, that'd be useful to know.

**Comment by garyb** [comment]
SlamData isn't quite ready for the new compiler yet but it's what we're working on currently, I'll give it a try when we get there.

**Comment by garyb** [comment]
Maxim has been trying out the new compiler release, apparently 0.7.5 uses a bit over twice as much RAM (1.4gb -> ~3gb) as 0.7.4.1 when compiling a subset of SlamData.

**Comment by cryogenian** [comment]
False alarm, sorry. I've double checked 0.7.4.1 and 0.7.5. It uses ~4.3Gb with 0.7.4 and ~3Gb with 0.7.5.

**Comment by garyb** [comment]
Oh, cool! :smile:

**Comment by paf31** [comment]
I did a quick test by removing all transformers and using `IO` directly, skipping errors and warnings, and the memory usage on Halogen master went from 1gb down to ~100mb, so `ExceptT` and `WriterT` certainly seem to be contributing something here. Interestingly, it didn't do anything for CPU time.

**Comment by jdegoes** [comment]
Maybe a compromise could be using something like `MonadWriter`, / `MonadExcept` (???) so some abstraction can be kept on the callee-side, but `IO` or something equally fast used on the caller-side.

**Comment by paf31** [comment]
That was the plan, I just need to figure out how to keep the same semantics. Using an `IORef` for warnings didn't quite work, and we can probably use exceptions for `MonadExcept`, but we need to be careful about `catchError`.

**Comment by paf31** [comment]
Trying out [`monad-unlift`](https://hackage.haskell.org/package/monad-unlift-0.1.1.0) now.

**Comment by paf31** [comment]
It's a shame it seems to pull in half of Hackage :smile:

**Comment by paf31** [comment]
Using `WriterRefT` from `monad-unlift` reduces memory usage to ~80M throughout the whole build of Halogen. However, something isn't quite right because the warnings get messed up and I end up with this output:

```text

Warning 1 of 7:

  in module DOM.Node.NodeType
  at bower_components/purescript-dom/src/DOM/Node/NodeType.purs line 21, column 1 - line 36, column 1

    An exhaustivity check was abandoned due to too many possible cases.
    You may want to decompose your data types into smaller types.

  in value declaration eqNodeType
  in value declaration enumNodeType
  in value declaration boundedOrdNodeType
  in value declaration boundedNodeType

  See https://github.com/purescript/purescript/wiki/Error-Code-IncompleteExhaustivityCheck for more information,
  or to contribute content related to this warning.

Warning 2 of 7:

  in module Data.List
  at bower_components/purescript-lists/src/Data/List.purs line 255, column 1 - line 256, column 1

    A case expression could not be determined to cover all inputs.
    The following additional cases are required to cover all inputs:

    Nil _

  in value declaration go
  in value declaration init
  in value declaration index
  in value declaration (!!)
  in value declaration head
  in value declaration groupBy
  in value declaration group
  in value declaration group'
  in value declaration go
  in value declaration functorList
  in value declaration fromList
  in value declaration go
  in value declaration foldableList
  in value declaration foldM
  in value declaration go
  in value declaration findIndex
  in value declaration findLastIndex
  in value declaration filterM
  in value declaration go
  in value declaration filter
  in value declaration intersectBy
  in value declaration intersect
  in value declaration nubBy
  in value declaration nub
  in value declaration go
  in value declaration eqList
  in value declaration elemLastIndex
  in value declaration elemIndex
  in value declaration go
  in value declaration dropWhile
  in value declaration drop
  in value declaration slice
  in value declaration deleteBy
  in value declaration unionBy
  in value declaration union
  in value declaration deleteAt
  in value declaration delete
  in value declaration (\\)
  in value declaration concatMap
  in value declaration concat
  in value declaration catMaybes
  in value declaration bindList
  in value declaration applyList
  in value declaration applicativeList
  in value declaration alternativeList
  in value declaration alterAt
  in value declaration modifyAt
  in value declaration altList

  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information,
  or to contribute content related to this warning.

Warning 3 of 7:

  in module Data.Map
  at bower_components/purescript-maps/src/Data/Map.purs line 178, column 23 - line 179, column 21

    A case expression could not be determined to cover all inputs.
    The following additional cases are required to cover all inputs:

    (Cons (TwoRight Leaf _ _) _)                    (Two _ _ _ _)
    (Cons (TwoRight Leaf _ _) _)                    (Three _ _ _ _ _ _ _)
    (Cons (ThreeLeft _ _ Leaf _ _ (Two _ _ _ _)) _) _
    (Cons (ThreeLeft _ _ Leaf _ _ (Two _ _ _ _)) _) (Two _ _ _ _)
    (Cons (ThreeLeft _ _ Leaf _ _ (Two _ _ _ _)) _) (Three _ _ _ _ _ _ _)
    ...

  in value declaration up
  in value declaration removeMaxNode
  in value declaration maxNode
  in value declaration max
  in value declaration max
  in value declaration max
  in value declaration down
  in value declaration delete
  in value declaration allHeights
  in value declaration checkValid
  in value declaration alter
  in value declaration combine
  in value declaration fromListWith
  in value declaration go
  in value declaration unionWith
  in value declaration union
  in value declaration semigroupMap
  in value declaration traversableMap
  in value declaration unions
  in value declaration update

  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information,
  or to contribute content related to this warning.

Warning 4 of 7:

  in module Data.Map
  at bower_components/purescript-maps/src/Data/Map.purs line 178, column 23 - line 179, column 21

    A case expression could not be determined to cover all inputs.
    The following additional cases are required to cover all inputs:

    _ Leaf

  in value declaration removeMaxNode
  in value declaration maxNode
  in value declaration max
  in value declaration max
  in value declaration max
  in value declaration down
  in value declaration delete
  in value declaration allHeights
  in value declaration checkValid
  in value declaration alter
  in value declaration combine
  in value declaration fromListWith
  in value declaration go
  in value declaration unionWith
  in value declaration union
  in value declaration semigroupMap
  in value declaration traversableMap
  in value declaration unions
  in value declaration update

  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information,
  or to contribute content related to this warning.

Warning 5 of 7:

  in module Data.Map
  at bower_components/purescript-maps/src/Data/Map.purs line 178, column 23 - line 179, column 21

    A case expression could not be determined to cover all inputs.
    The following additional cases are required to cover all inputs:

    Leaf

  in value declaration maxNode
  in value declaration max
  in value declaration max
  in value declaration max
  in value declaration down
  in value declaration delete
  in value declaration allHeights
  in value declaration checkValid
  in value declaration alter
  in value declaration combine
  in value declaration fromListWith
  in value declaration go
  in value declaration unionWith
  in value declaration union
  in value declaration semigroupMap
  in value declaration traversableMap
  in value declaration unions
  in value declaration update

  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information,
  or to contribute content related to this warning.

Warning 6 of 7:

  in module Data.StrMap
  in module Data.StrMap
  in module Data.StrMap
  at bower_components/purescript-maps/src/Data/StrMap.purs line 72, column 1 - line 73, column 1

    Type variable 'b' was declared but not used.

  in type declaration for pureST
  in value declaration values
  in value declaration toList
  in value declaration thawST
  in value declaration showStrMap
  in value declaration pureST
  in value declaration singleton
  in value declaration mutate
  in value declaration monoidStrMap
  in value declaration member
  in value declaration lookup
  in value declaration f
  in value declaration isSubmap
  in value declaration isEmpty
  in value declaration insert
  in value declaration functorStrMap
  in value declaration fromListWith
  in value declaration fromList
  in value declaration freezeST
  in value declaration foldMaybe
  in value declaration foldM
  in value declaration semigroupStrMap
  in value declaration union
  in value declaration traversableStrMap
  in value declaration unions
  in value declaration fold
  in value declaration foldMap
  in value declaration foldableStrMap
  in value declaration eqStrMap
  in value declaration delete
  in value declaration alter
  in value declaration update

  See https://github.com/purescript/purescript/wiki/Error-Code-UnusedTypeVar for more information,
  or to contribute content related to this warning.

Warning 7 of 7:

  in module Data.StrMap
  in module Data.StrMap
  in module Data.StrMap
  at bower_components/purescript-maps/src/Data/StrMap.purs line 114, column 1 - line 120, column 1

    Type variable 'a' was shadowed.

  in value declaration values
  in value declaration toList
  in value declaration thawST
  in value declaration showStrMap
  in value declaration pureST
  in value declaration singleton
  in value declaration mutate
  in value declaration monoidStrMap
  in value declaration member
  in value declaration lookup
  in value declaration f
  in value declaration isSubmap
  in value declaration isEmpty
  in value declaration insert
  in value declaration functorStrMap
  in value declaration fromListWith
  in value declaration fromList
  in value declaration freezeST
  in value declaration foldMaybe
  in value declaration foldM
  in value declaration semigroupStrMap
  in value declaration union
  in value declaration traversableStrMap
  in value declaration unions
  in value declaration fold
  in value declaration foldMap
  in value declaration foldableStrMap
  in value declaration eqStrMap
  in value declaration delete
  in value declaration alter
  in value declaration update

  See https://github.com/purescript/purescript/wiki/Error-Code-ShadowedTypeVar for more information,
  or to contribute content related to this warning.


real	0m4.763s
user	0m13.400s
sys	0m1.999s
```

**Comment by jdegoes** [comment]
> Using WriterRefT from monad-unlift reduces memory usage to ~80M throughout the whole build of Halogen.

:heart_eyes:

**Comment by paf31** [comment]
In any case, the solution is clear: implement our own `WriterT` using an `IORef` (but be careful to implement `pass` correctly, since it's crucial for getting warnings right).

**Comment by paf31** [comment]
:fireworks: https://github.com/purescript/purescript/pull/1572
