### ISSUE TITLE
Error messages cite lines distant from problem

### ISSUE THREAD

**Issue by jasonzoladz** [purescript/purescript#1301]
I'm picking up Halogen and I came across this: 

<img width="880" alt="screen shot 2015-07-23 at 7 49 37 pm" src="https://cloud.githubusercontent.com/assets/8467728/8864763/01441104-3174-11e5-801d-bf4684e798f8.png">

<img width="878" alt="screen shot 2015-07-23 at 7 47 54 pm" src="https://cloud.githubusercontent.com/assets/8467728/8864744/c0015a76-3173-11e5-83db-73e20f92104d.png">

When I add the Applicative constraint, the code will compile, but the error identifies line 3:

<img width="209" alt="screen shot 2015-07-23 at 7 51 36 pm" src="https://cloud.githubusercontent.com/assets/8467728/8864790/48b9b3e0-3174-11e5-9e94-19dfd5249c44.png">

**Comment by garyb** [comment]
#1271 should have fixed this, but it hasn't been released yet. You can either build and install `master` or wait for 0.7.2 which should be out soon (tomorrow hopefully).

**Comment by jasonzoladz** [comment]
Perfect.  (Thanks for all your work on everything PS.  Halogen, et al. is lovely stuff.)
