### ISSUE TITLE
nix fails to build from cabal package

### ISSUE THREAD

**Issue by MasseGuillaume** [purescript/purescript#1302]
https://github.com/NixOS/nixpkgs/issues/8965

If we take a look at the [tar](http://hackage.haskell.org/package/purescript-0.7.1.0/src/) we can see that the `tests/` folder is missing. This [breaks purescript package on nix](https://hydra.nixos.org/build/23422483/nixlog/1#line-553). I suggest adding

```
extra-source-files: examples/passing/*.purs
                  , examples/failing/*.purs
                  , tests/prelude/*.purs
                  , tests/prelude/js/*.js
```
at https://github.com/purescript/purescript/blob/b34ec66d3f360097bd112ae80da1aef853d78114/purescript.cabal#L21

and republishing `version: 0.7.1.1` to hackage. Thanks

**Comment by puffnfresh** [comment]
:+1:

**Comment by garyb** [comment]
We're intending on releasing 0.7.2 soon (later today hopefully) so will roll it in with that.

**Comment by MasseGuillaume** [comment]
:metal:

**Comment by MasseGuillaume** [comment]
@garyb is 0.7.2 coming soon ?

**Comment by garyb** [comment]
I think so...

@paf31 since things are dragging on a bit with #1298 can we release it after #1324 is merged? That on its own seems worthy of a release almost!

**Comment by paf31** [comment]
I'll put in a quick patch for #1298 later today and make a release. It's irritating enough that I want to just fix it quickly even if it's not the best fix.

**Comment by garyb** [comment]
Ok, cool. And... agreed :smile:

**Comment by MasseGuillaume** [comment]
@garyb still fails on nix
`npm install` cannot find package.json
https://github.com/purescript/purescript/blob/master/tests/Main.hs#L243

**Comment by MasseGuillaume** [comment]
@puffnfresh how does `haskell.lib.dontCheck` works ?
https://github.com/purescript/purescript/issues/1302#issuecomment-124496287

**Comment by puffnfresh** [comment]
@MasseGuillaume it disables tests, which were broken.

**Comment by MasseGuillaume** [comment]
@puffnfresh yes I understood that. I wanted to know what's the exact configuration or command that you are using. I did not found something relevant in the documentation.

**Comment by MasseGuillaume** [comment]
@puffnfresh https://github.com/NixOS/nixpkgs/pull/9167
