### ISSUE TITLE
Should psc-publish refuse to run if the working tree is dirty?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1306]
that is, if any files have been added, deleted, or modified since the last commit. I think it should at least warn (currently it doesn't do anything).

**Comment by paf31** [comment]
:+1: Definitely.

**Comment by michaelficarra** [comment]
Let's warn and/or ask for confirmation. Not everyone uses git.

**Comment by hdgarrood** [comment]
Having thought about this a bit more, my vote is to error if we are inside a git repository.

If we want to accommodate for people who don't use git, we need to come up with an alternative solution for getting the version. Currently, we do it by shelling out to git, to get a tag pointing at the currently checked out commit, and then we attempt to parse that.

**Comment by hdgarrood** [comment]
Also, we'd need to come up with an alternative for all the GitHub things Pursuit relies on: authentication, source links, readmes, and links to the project (which currently always point to its github page).

I don't mean to argue that we shouldn't do this, but it is a fairly big undertaking, so I'd like to wait until there's at least some demand for it.

**Comment by tfausak** [comment]
Sorry to revive an old thread, but this behavior is driving me nuts. I run `psc-publish --dry-run` as part of my tests, and the fact that it *fails* (instead of warning) if I have a dirty working tree is extremely frustrating.

**Comment by hdgarrood** [comment]
yeah, good call, :+1: for making psc-publish warn instead of failing when the working tree is dirty.

**Comment by paf31** [comment]
:+1:

**Comment by tfausak** [comment]
In fact, I would prefer it to always be a warning. I ran into this issue again while trying to automatically upload documentation to Pursuit from Travis CI. Since Travis checks out a branch, it's in a detached head state. psc-publish treats that as dirty, even if it's not. See the build for details: https://travis-ci.org/tfausak/purescript-neon/builds/89132864#L1345-L1353

```
$ git status
# HEAD detached at 63df46f
nothing to commit, working directory clean
$ npm run psc-publish | tail -n 1 > purescript-neon-${TRAVIS_TAG}.json
There is a problem with your package, which meant that it could not be         
published.                                                                     
Details:                                                                       
  Your git working tree is dirty. Please commit, discard, or stash your changes
  first.                                                                       
```

**Comment by michaelficarra** [comment]
Well then the method psc-publish uses for a dirty check is wrong. The messages from git and psc-publish should not conflict.

**Comment by tfausak** [comment]
Oh crap. You know what? Outputting to `purescript-neon-${TRAVIS_TAG}.json` made my working directory dirty. So there's no discrepancy. But this highlights the problem I have with making this an error rather than a warning.

**Comment by hdgarrood** [comment]
Yeah, hm. Maybe we could make it only warn instead of failing if there are only untracked files. Why are you using `tail -n 1`, by the way?

**Comment by tfausak** [comment]
Because `npm run` outputs some stuff that I don't know how to get rid of.

``` sh
$ npm run psc-publish

> @ psc-publish /Users/taylor/Documents/Code/purescript-neon
> psc-publish

{…}
````

**Comment by hdgarrood** [comment]
It should only be printing the JSON to stdout, everything else should go to stderr. Is that not happening?

**Comment by tfausak** [comment]
`psc-publish` is only printing the JSON to STDOUT. It's `npm run` that's printing out the garbage to STDOUT. I too expected it to be on STDERR instead, but it's not. I could run `psc-publish` directly with `./node_modules/.bin/psc-publish`, but then I'd have to manually put other stuff (like `bower`) on my PATH.
