### ISSUE TITLE
Inject seems to do something funny with row unification

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1310]
This typechecks without the `CONSOLE` effect:

``` purescript
foreign import data Oops :: !

what :: forall eff. Eff (oops :: Oops | eff) Unit
what = inj (Control.Monad.Eff.Console.log "wow")
```

If you try and drop the row and just use `eff` the error is:
```
No instance found for Data.Inject.Inject (Control.Monad.Eff.Eff (console :: Control.Monad.Eff.Console.CONSOLE | _13)) (Control.Monad.Eff.Eff eff8)
```

So perhaps there's something happening with an unknown unifying with the extra effects perhaps? I don't know if that's even possible. I guess it's a problem with instances not types directly though.

**Comment by garyb** [comment]
This works if the row of effects is closed too actually. It can't be `()` however.

**Comment by puffnfresh** [comment]
I'm using Halogen and noticed Eval does not get type checked:

```purescript
broken :: forall g. Eval Input { x :: Int } Input g
broken (Click a) = gets _.y $> a
```

This is a pretty huge problem. Very easy to generate JS which is broken!

**Comment by zudov** [comment]
@puffnfresh I've been noticing before that Eval never get interfered. Unless you specify the full type it would fail with "scolem variable detected" type error.

**Comment by garyb** [comment]
@puffnfresh yep, something like that was how I first encountered it :(

I have a [WIP branch](https://github.com/garyb/purescript-halogen/tree/wip/updates) which I'll shortly merge into Halogen and then tag* which should prevent this at least, I've taken out the `Inject` usage everywhere.

* Is it Friday you're giving your talk? It'll definitely be in before then, but might be tomorrow before it gets done. I'm still working on making `installL` / `installR` more useful by extending the `Either` over the query algebra and state for the components.

**Comment by puffnfresh** [comment]
@garyb woo, :+1: to removing `Inject`. I'm doing a run through of my workshop at Atlassian in the morning, we're just gonna work of master. I'll work of the release if it comes out before the real deal.

Thanks!

**Comment by paf31** [comment]
@garyb Could you please verify this is fixed? I'm fairly certain it is, but just in case.

**Comment by garyb** [comment]
Will do! It'll probably be Sunday before I get around to it though.

**Comment by garyb** [comment]
It does not :(

**Comment by garyb** [comment]
The complete example:

``` purescript
module Main where

import Prelude
import Data.Inject
import Control.Monad.Eff
import Control.Monad.Eff.Console

foreign import data Oops :: !

what :: forall eff. Eff (oops :: Oops | eff) Unit
what = inj (log "wow")

main = what
```

**Comment by paf31** [comment]
Ok, thanks, I'll take a look.
