### ISSUE TITLE
Could psc-bundle check for missing FFI functions?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1313]
If I write `foreign import spawn :: [...]` inside `Module.purs`, and then I forget to write `exports.spawn = [...]` inside `Module.js`, it would be nice for one out of `psc` or `psc-bundle` to warn me about this.

**Comment by hdgarrood** [comment]
Thinking about this a little more. I might have a go at this.

I feel like this should be done by `psc`, actually; one of the selling points of PureScript ought to be the fact that errors are caught at compile time rather than run time, right? In particular, if we don't check this inside `psc`, it may well end up as a runtime error. People won't use `psc-bundle` in every case.

**Comment by zudov** [comment]
I just thought about how would it work, and thought that it would be much easier to implement if we declared the FFI exports using [`export` statements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by hdgarrood** [comment]
Yeah, I think this is one reason ES6 modules are on the roadmap. This has already been implemented in `psc-bundle` to some extent, though &mdash; using code that's already in `psc-bundle`, it's pretty easy to take an FFI module and get a list of identifiers it exports.

**Comment by zudov** [comment]
> Using code that's already in psc-bundle, it's pretty easy to take an FFI module and get a list of identifiers it exports.

Then we should do it, and probably provide some pragma which would make the psc shut up (you would use it if for some reason you want to put something into `exports` in a non-straightforward way)

**Comment by zudov** [comment]
On a second thought `exports.foo = null` would work equally well to disable "Undefined FFI export" for warning for identifier `foo`.

**Comment by hdgarrood** [comment]
Yes, although there might be other cases where an escape hatch might be useful. For example, suppose you wanted to write something like this:

```javascript
for (let name of something) {
  exports[name] = somethingElse(name);
}
```

**Comment by zudov** [comment]
I see, putting `exports.foo = null` in FFI whenever you want to use some of those names isn't fun.

**Comment by zudov** [comment]
On the other hand you probably should instead do

```javascript
exports.things = {};
for (let name of something) {
  exports.things[name] = somethingElse(name);
}
```

```purescript
foreign import things :: { fooThingy :: Foo, barThingy :: Bar }
```

**Comment by kRITZCREEK** [comment]
ES6 modules lose the ability to conditionally import modules which gives you sometimes needed flexibility.

For example in https://github.com/kRITZCREEK/psc-gui/blob/master/src/Node/Process.js#L3-L4

Electron has two kinds of processes (renderer and browser) and you need to be able to adjust your imports depending on the process.

@zudov the empty object is semantically very different from undefined though

**Comment by hdgarrood** [comment]
@kRITZCREEK ah, good point. You might want to raise that in #1206?

**Comment by paf31** [comment]
That's one of the main reasons I want to move to ES6 modules :smile: 

I'd like imports and exports in foreign files and generated files to be statically determined by syntax. Right now you  have to do some arbitrary amount of evaluation to figure them out.

In fact, once we move to ES6 modules, our dead code elimination could even become general-purpose, just working on a bunch of ES6 modules.
