### ISSUE TITLE
Suggestions for row unification errors

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1315]
Two examples of modules which have type errors, and the error messages that they currently produce:
* Extra record field
```purescript
module ExtraRecordField where
import Prelude ((<>))

full :: { first :: String, last :: String } -> String
full p = p.first <> " " <> p.last
oops = full { first: "Jane", last: "Smith", age: 29 }
```
```
Row last :: Prim.String, first :: Prim.String lacks required property "age"
```
* Missing record field
```purescript
module MissingRecordField where
import Prelude ((>))

john = { first: "John", last: "Smith" }
isOver50 p = p.age > 50.0
result = isOver50 john
```
```
  Cannot unify type
    ()
  with type
    (age :: Prim.Number | _1)
```

I think these could be improved a little. In the first example, I think it makes more sense to say that the object `{ first: "Jane", last: "Smith", age: 29 }` has an *extra* field "age", rather than the row `{ first :: String, last :: String }` missing the required field "age". In the second, I think a `PropertyIsMissing` error would be more appropriate than the current "Cannot unify type" error.

**Comment by paf31** [comment]
:+1:
