### ISSUE TITLE
psc-publish cannot find bower on Windows

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1317]
```
Details:
  While running `bower list --json --offline`:
    bower: readProcess: does not exist (No such file or directory)
```

I think this is because it needs to be called as `bower.cmd`, pulp had a similar issue at one point.

**Comment by hdgarrood** [comment]
Oh dear. Is there a workaround?

**Comment by garyb** [comment]
I used my Mac :smile:

I don't think there's a real workaround though unfortunately.

**Comment by Fresheyeball** [comment]
Lame...

**Comment by garyb** [comment]
?

This was fixed a little while ago.

**Comment by Fresheyeball** [comment]
Oh, sorry. I read the thread wrong, that no workaround was the resolution. I am seeing this error on Windows 8.1 with GitBash. The `bower` command works fine, so I don't think that is the issue.

**Comment by garyb** [comment]
Are you using 0.7.2 or later?
