### ISSUE TITLE
Invalid externs.purs generated containing Unknown Type

### ISSUE THREAD

**Issue by bitc** [purescript/purescript#1318]
The following module:

``` purescript
module BugTest (B(..)) where

data A = A

data B = B1 | B2 A
```

generates the following `externs.purs`:

``` purescript
module BugTest (B(B1, B2)) where
import Prim ()
data B = B1  | B2 BugTest.A
```

It does not compile and gives the error: `Unknown type BugTest.A`

This is code that you probably should not write, but still valid (also in Haskell where there are no warnings even).

I think the fix is to put in the `externs.purs` also the line `data A = A`

**Comment by garyb** [comment]
Thanks for the report. This should actually fail for another reason - it should complain about `A` not being exported despite being used in data constructor `B2`.

**Comment by hdgarrood** [comment]
Not sure if this is the same bug, but the following will fail at runtime with "undefined is not a function":

```purescript
module Main where

import Prelude
import Control.Monad.Eff.Console
import Dep

main = print ok
```
```purescript
module Dep (Ok(), ok) where

import Prelude

data Secret a = Secret a

type Ok = Secret Int

instance showSecret :: (Show a) => Show (Secret a) where
  show (Secret x) = "Secret " <> show x

ok :: Ok
ok = Secret 0
```

**Comment by paf31** [comment]
This is fixed by #1480, but only because the externs file is just assumed to be correct now. I guess the issue is in `Names`?

**Comment by paf31** [comment]
The issue reported by @hdgarrood is still present, however. I guess both of these can be summarized as "there should be a transitive export error thrown", right?

**Comment by paf31** [comment]
@garyb Is this fixed now?

**Comment by garyb** [comment]
Yep

```
Error in module Dep:
An export for Ok requires the following to also be exported:
Secret
```
