### ISSUE TITLE
Warnings for missing top-level type declarations

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1333]

**Comment by paf31** [comment]
Actually, I don't think this should be considered a bug in `psc`. `psc` doesn't assume anything about `main` any more, although `psc-bundle` and `pulp` both do.

In fact, with things like `purescript-preface` available, checking against the type `Eff _ _` is no longer correct.

I think the best thing we can do is to give a warning whenever a top level declaration lacks a type signature.

**Comment by garyb** [comment]
I agree, I think the potential fix we talked about is probably worse than the problem. Warning on untyped top level declarations is good by me too, given that we warn on `_` usage which is potentially more specific it's kinda funny that we don't already :smile:
