### ISSUE TITLE
flattened: does not exist

### ISSUE THREAD

**Issue by phadej** [purescript/purescript#1334]
```
% stack build         
.../purescript/tests/support/flattened/: getDirectoryContents: does not exist (No such file or directory)
```

The files are listed in `extra-source-dirs` but they seems to be generated from something. Would it better to include sources, and generate (if needed) on test run?

**Comment by paf31** [comment]
@hdgarrood Do these need to be in `extra-source-dirs` now?

**Comment by hdgarrood** [comment]
Uh, not sure. They should get fetched when you run `cabal test`. @phadej what do you mean by include sources and generate (if needed) on test run?

**Comment by hdgarrood** [comment]
Looks like they are in `extra-source-files` already.

**Comment by phadej** [comment]
@hdgarrood they are, but `cabal sdist` (or `./travis/test-install.sh`) fails on fresh git clone. 

Looks like that `tests/Main.hs` generates them:
```
tests/Main.hs:  callProcess "node" ["setup.js"]
```

So could one omit them from `extra-source-files`?
