### ISSUE TITLE
Scoped type variables issue with shadowed type variables

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1335]
This declaration: https://github.com/slamdata/purescript-halogen/blob/f0022c672447c3501e8ef4746adbc617775c39a3/src/Halogen/Component.purs#L261-L262 does not typecheck when indented into the `where` block above it:

```
No instance found for Prelude.Functor (Data.Functor.Coproduct.Coproduct f524 (Data.Functor.Coproduct.Coproduct g522 h878))
```

Perhaps it's just related to instance resolution, but whatever it is there's some kind of scope-related problem.

**Comment by paf31** [comment]
Minimal example:

```purescript
x :: forall a. a -> String
x a = y "a"
  where
  y :: forall a. (Show a) => a -> String
  y a = show (a :: a)
```
