### ISSUE TITLE
Could psc-publish check for bower version ranges?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1337]
This might be out of its remit, but we should prefer use of `^` over `~` version ranges.

The original example is lost in slamdata's history somewhere, but when you have two dependencies like `~0.1.0` and `~0.1.1` sometimes it will pull in `v0.1.0`, which obviously is somewhat less than ideal if it has dependencies or fixes you require.

I'm not sure why Bower doesn't default to `^` like npm does now (npm used to use `~` too).

**Comment by paf31** [comment]
A warning for this makes sense, at the least.

**Comment by hdgarrood** [comment]
Just checking I understand - is `0.1.0` is considered an acceptable choice for a dependency specified as `~0.1.1` then?

**Comment by hdgarrood** [comment]
Looking at the [documentation](https://github.com/npm/node-semver#tilde-ranges-123-12-1) I'm not sure it makes much difference for us. I am pretty sure that `^` and `~` ranges act identically when the major version is 0, which is currently the case for the majority of PureScript packages.

Also, `0.1.0` is not an acceptable version if `~0.1.1` is specified:

```
$ npm install semver
```
```javascript
var s = require('semver')
> s.satisfies('0.1.0', '~0.1.1')
false
```

Looks like that might have just been a bug in Bower.

I vote :-1:

**Comment by paf31** [comment]
I'm going to close this since it hasn't been discussed in over a year, got a mixed response, and will soon be irrelevant (hopefully) when we have `psc-package`.
