### ISSUE TITLE
Using -m MyModule excludes foreign imports from .js

### ISSUE THREAD

**Issue by dvdsgl** [purescript/purescript#1338]
This produces a working bundle for my library:

```shell
psc-bundle 'output/**/*.js'
```

Doing the follow, however, drops my foreign definitions, causing "ForeignModule.xyz is not a function" failures in the browser:

```shell
psc-bundle 'output/**/*.js' -m MyModule
```

I'm using purescript 0.7.1.

**Comment by paf31** [comment]
Are your foreign modules in the right format as explained here?

http://www.purescript.org/learn/ffi/

**Comment by dvdsgl** [comment]
They were in the wrong format! Thank you.
