### ISSUE TITLE
REPL not working: "Unknown module Control.Monad.Eff"

### ISSUE THREAD

**Issue by xhevahir** [purescript/purescript#1341]
I just installed Purescript via npm and evaluating anything in the REPL gives me this error message: "Error in module $PSCI.Support:
Error at line 4, Column 1 - line 5, column 1:
Unknown module Control.Monad.Eff"

**Comment by paf31** [comment]
Does the warning about `purescript-console` show up? You need to install it and load it into PSCi.

**Comment by xhevahir** [comment]
I've now installed purescript-console with Bower, along with purescript-eff and purescript-prelude, and put the .psci I found [here](https://gist.github.com/paf31/511f23b576207abe9423) in my home directory, but I'm still getting a bunch of errors: When I start the REPL, this one: 
"Couldn't locate: bower_components/purescript-console/src/Control/Monad/Eff/Console.js
 Couldn't locate: bower_components/purescript-console/src/Control/Monad/Eff/Console.purs
Error:
Error in module $PSCI:
Unknown module Control.Monad.Eff.Console"

I still get the warning about installing purescript-console.

Then, once I try to evaluate, the same message as before. Am I misunderstanding how to install all this? Maybe I need to compile all of it from source?

**Comment by michaelficarra** [comment]
The files it says it can't locate are the ones installed by bower, meaning you didn't end up actually installing them. What did you run to install purescript-console, where did you run it, and what was its output?

**Comment by xhevahir** [comment]
I installed it via 'bower i purescript-console', to the default directory, which turns out to be ~/bower_components. I just tried adding that directory to my PATH, to no effect. I've never used Bower before. I take it there's some extra configuration I need to do in order for it to work with the  Purescript stuff I installed with npm?

**Comment by paf31** [comment]
Perhaps try working through http://www.purescript.org/learn/getting-started/? PSCi won't look on your PATH, it uses paths relative to the current directory. You should try to get Bower to install dependencies locally. Do you have a `.bowerrc` file? Maybe that is overriding the defaults.

**Comment by xhevahir** [comment]
Thanks, I'll look into that. Seems the installation process has changed a lot since I tried Purescript on my old OS installation.

**Comment by samspot** [comment]
This seems to be related to a change in bower defaults.  With no config present, bower puts files in `app/bower_components` instead of `bower_components`.  This has caused problems for me in other tutorials.  You can change this behavior in a .bowerrc.

**Comment by hdgarrood** [comment]
It would be very surprising to me if they changed the default from bower_components to app/bower_components. Are you sure that's the default? Maybe you have a global bowerrc file somewhere? I think bower uses $HOME/.bowerrc if it exists.

**Comment by samspot** [comment]
It surprised me too. Two of us installed bower within days of each other
and got different defaults for the same project. Maybe something else was
going on, but something similar must have happened to the OP.

**Comment by jarvismartin** [comment]
I just had the same issue with bower_components being in app/. I don't have a .bowerrc anywhere, either. I'm on a MBP running Sierra.
Why was this issue closed?

**Comment by paf31** [comment]
> Why was this issue closed?

Because it works fine if you use the defaults, and install `psci-support`.

If you can provide steps to reproduce, we can reopen it.

**Comment by stevematdavies** [comment]
"Because it works fine if you use the defaults and install psci-support."

What does this mean?

**Comment by JordanMartinez** [comment]
@stevematdavies They mean you have to install the `[purescript-psci-support](https://github.com/purescript/purescript-psci-support)` package before the REPL will work.
