### ISSUE TITLE
Add -force option to psc-publish

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1352]
I often find myself in annoying cases like forgetting to add `repository` to `bower.json`, but having already made a tag. It would be nice in such cases to be able to say to `psc-publish` "I know what I'm doing", as long as doing so wouldn't actually generate an invalid `pursuit.json` file. The main cases I'd like to avoid are:

- Not on a tagged commit (can we take the latest tag instead?)
- Working tree is dirty.

**Comment by hdgarrood** [comment]
Having the `--dry-run` flag does improve the situation somewhat, although of course it's not ideal that you have to remember to use it before tagging.

This solution does make me feel a bit uneasy, though. I would prefer to at least try bodil/pulp#57 first and see how well that works.

**Comment by hdgarrood** [comment]
Adding a `--force` flag like this would mean that it's much less likely that we'll be able to regenerate Pursuit data from what's in the git history, which can be very useful. Even without a `--force` flag, there are already lots of packages on Pursuit for which the json blobs weren't actually produced from the same commit that the git history claims it was: https://www.reddit.com/r/purescript/comments/4414xe/announcement_re_migration_of_pursuit_to_080/

In general I'd much rather ask people to rewrite their git history (especially if they've only just tagged that version), and get tooling such as `pulp` to a point where it's easiest to just do the right thing.
