### ISSUE TITLE
Shadowing warning doesn't apply to let bindings

### ISSUE THREAD

**Issue by starper** [purescript/purescript#1369]
This code does not throw "Duplicate value declaration" (or any other) error:
```purescript
foo :: forall e. Eff (console :: CONSOLE | e) Unit
foo = do
  a <- pure 5
  log $ "a is " ++ (show a)
  a <- pure 10
  log $ "a is " ++ (show a)
  let a = 5
  log $ "a is " ++ (show a)
  let a = 10
  log $ "a is " ++ (show a)
```
And if you run it you'll see:

    a is 5
    a is 10
    a is 5
    a is 10

**Comment by michaelficarra** [comment]
This is shadowing, just as is allowed in regular let bindings.

```purs
x = let a = "a" in let a = "b" in a
```

**Comment by starper** [comment]
So this is supposed to be this way? Sorry then.

**Comment by garyb** [comment]
There probably should be a shadowed variable warning, but yeah it's not an error.

**Comment by starper** [comment]
I guess I should have asked in IRC before creating an issue :) I think warning will be great.

**Comment by mjgpy3** [comment]
When I run:
```
module Lets where

b = let a = 4
    in let a = 5
       in a
```

I get:
```
Compiling Lets
Warning found:
Warning in module Lets:
Warning at /home/michael/dev/contrib/purescript/Lets.purs line 3, column 1 - line 5, column 11:
  Name 'a' was shadowed.
See https://github.com/purescript/purescript/wiki/Error-Code-ShadowedName for more information, or to contribute content related to this error.
```

This seems to imply the issue is in desugaring and not lets in general

**Comment by paf31** [comment]
The issue is that linting happens before desugaring, and do notation isn't handled by the linter. But even if it were, `everythingWithContext` does the wrong thing, since it doesn't pass state between do notation nodes.
