### ISSUE TITLE
Derive instances, not instance members?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1371]
We could add new syntax to derive a whole `Generic` instance, instead of deriving any missing instance members. It seems like asking for trouble to let users derive some but not all of an instance's members.

Hopefully we could come up with syntax which would generalize to `newtype` deriving unambiguously:

```purescript
deriving instance genericFoo :: Generic Foo

deriving newtype instance showBar :: Show Bar
```

perhaps?

**Comment by jdegoes** [comment]
:+1:

**Comment by garyb** [comment]
Yes please. :+1:

**Comment by garyb** [comment]
Perhaps `derive` or `derived` though.

**Comment by puffnfresh** [comment]
> It seems like asking for trouble to let users derive some but not all of an instance's members.

Definitely agree!
