### ISSUE TITLE
psc: No files found using pattern: src/**/*.js

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1375]
After #1176 this gets printed when using `pulp` and your project has no FFI files in its main source tree. Since I would hope that's most projects, should we do something about it?

I guess it is useful to know that the glob doesn't match if you think it should, but maybe we can hide it for the case of FFI files as if they're missing the compiler will raise a different error anyway. Although, that error sometimes happens because of the missing or badly formatted comment, so having this extra error in might be helpful there... argh, I don't know. Thoughts?

**Comment by mjgpy3** [comment]
>  but maybe we can hide it for the case of FFI files

I think that when I do #1268, I'm going to turn FFI warnings off, especially if inferring the `.js` becomes the standard way of including FFIs.

**Comment by mjgpy3** [comment]
Wait, nevermind... I've got to think about this some more.

**Comment by paf31** [comment]
I think we can close this now since the `src/**/*` wildcard works instead.

**Comment by mjgpy3** [comment]
:+1:
