### ISSUE TITLE
Feature request: doctests

### ISSUE THREAD

**Issue by mjgpy3** [purescript/purescript#1377]
Doctests in Elixir are really neat:
    http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-pipelines.html#doctests

I could see them having two useful benefits in PureScript:
  1. (obviously) providing accurate usage examples in the docs with free (or near-free) regression testing on said examples
  2. showing that laws hold for specific instances (e.g. I'm an instance of `Semigroup`, here are some interesting examples that show I am associative)

Thoughts?

**Comment by paf31** [comment]
Sounds good, but I don't know if it's something I'd like to have in the compiler itself, as opposed to, say, a core library.

**Comment by mjgpy3** [comment]
Sure, that makes a lot of sense to me

**Comment by robotlolita** [comment]
I particularly think that embedding code in strings is not a good idea. But something like Pyret's meta-data for examples (http://www.pyret.org/docs/latest/testing.html) could be very interesting, and also serve as basis for e.g.: embedding quick-check-like specifications for type classes, so something external can verify if a particular instance fulfils all of the laws automatically.

**Comment by phadej** [comment]
@robotlolita That's exactly what [haskell's doctest do](https://github.com/sol/doctest#readme):
```hs
-- |
-- prop> \xs -> sort xs == (sort . sort) (xs :: [Int])
```

-- |
-- >>> let x = 23
-- >>> x + 42
-- 65

**Comment by jdegoes** [comment]
Doctests too specific, but a feature that allows attaching and retrieving metadata to named entities? Could be useful for doctests and other things. If one considers comments the ultimate form of metadata, this work's already partially done.

**Comment by phadej** [comment]
I'm not sure how it's made in PureScript, but GHC is aware of document strings, and one can traverse AST to find attached comments. Or do you want more structured metadata (like in Clojure?)

**Comment by robotlolita** [comment]
Having something like Clojure's metadata could be very interesting for tooling, since you don't need to parse arbitrary text.

**Comment by paf31** [comment]
I think this can be handled externally. See [purs.md](http://paf31.github.io/purs.md/) for a prototype of something similar.

**Comment by mgajda** [comment]
The link to purs.md does not work. Is there alternative solution yet?

**Comment by paf31** [comment]
Sorry I deleted it. It was using the Try PureScript API but it got way out of date.

Someone could build something using the Try PureScript API easily enough though.

**Comment by mgajda** [comment]
I guess that You know how to do it, but since it is not available I woukd
need to spend lots of time learning how...
Do You keep a copy somewhere?

**Comment by paf31** [comment]
No, sorry, I couldn't find it. It was very simple though. It just looked for code sections in a markdown document and sent them to the API for execution.
