### ISSUE TITLE
derive Generic for phantom types

### ISSUE THREAD

**Issue by zudov** [purescript/purescript#1380]
Compiling the following code
```purescript
data Void
derive instance genericVoid :: GenericVoid
```
Throws
```
psc: Prelude.head: empty list
```

The derived instance should probably look like
```purescript
toSignature _ = SigProd []
fromSpine _ = Nothing
toSpine = absurd
```

**Comment by zudov** [comment]
Defining Void as
```purescript
newtype Void = Void Void
```
doesn't cause that problem (obviously because the constructor list isn't empty anymore :) )

**Comment by paf31** [comment]
@nicodelpiano Would you mind looking into this? I think it's in the exhaustivity checker.

**Comment by paf31** [comment]
You can get the length of the list of arguments from the `Case` statement and pass it as a function argument.

**Comment by nicodelpiano** [comment]
@paf31 Sure! I'm working on this.
