### ISSUE TITLE
Generate dash docsets from psc-docs

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#1383]
It would be nice to be able to browse the documentation for modules within [Dash](https://kapeli.com/dash) or [Zeal](http://zealdocs.org/).

https://github.com/jfeltz/dash-haskell uses the haddock output to generate these docs for Haskell. Maybe we could reuse some of the code? I would be willing to work on this with some help.

*Maybe this issue belongs into the pursuit repo? I wasn't sure...*

**Comment by hdgarrood** [comment]
A lot of the code relevant to pursuit lives here; see `Language.PureScript.Docs`. The HTML generation is all inside pursuit at the moment, though. I expect it will need a small amount of work to take care of links at the moment, that code assumes that links should all use Pursuit URLs, for example, which I presume needs changing?

If I were doing this, I would probably create a new project, depend on `purescript` as a library, copy the `Model.DocsAsHtml` module from Pursuit, and go from there.

**Comment by kRITZCREEK** [comment]
I've got to say I stopped using Dash etc. and I really don't miss anything when I can use pursuit. If someone thinks this is important to him he should open an issue about it.
