### ISSUE TITLE
Use -Werror, and turn off unnecessary import warnings

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1385]
Do we want to do this to allow us to identify PRs which introduce warnings?

**Comment by hdgarrood** [comment]
This sounds good to me. Although this might introduce problems where dependencies produce warnings. Perhaps we need a way of saying "-Werror, but only for stuff in `src/`".

Also, why turn off unnecessary import warnings? Better to fix those, surely?

**Comment by paf31** [comment]
Ah, because we'd need `CPP` to make import warnings go away in 7.10 I think?

**Comment by hdgarrood** [comment]
Ohhh, sorry, I thought you were talking about purescript core library code. Then :+1:

**Comment by erdeszt** [comment]
@paf31 What's the problem with using ```CPP```? I can do the PR unless you have something against it.

**Comment by paf31** [comment]
I just always thought it was a bit hacky, but maybe it's necessary. Yeah, we could do that. If you're willing to make the PR, that'd be great, thanks!

**Comment by paf31** [comment]
Duplicate.
