### ISSUE TITLE
Add `psc-publish --dry-run` to .travis.yml scripts for core libraries

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1386]
Also, it might be nice to have a place where the most up-to-date versions of template project files for core libraries should go, that is, `.travis.yml`, `package.json`, `.jscsrc`, `.jshintrc`, and so on. Then new libraries could copy these, and they'd be useful for anyone else creating packages too.

**Comment by paf31** [comment]
Closing, since we upload to Pursuit in the core Travis scripts now.

The template thing is a good idea, but @garyb points out that not all of the configs are identical, and depend on a few parameters, like whether there is foreign code, examples, etc.
