### ISSUE TITLE
Odd exhaustivity warnings with arrays

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1387]
Compiling this:
```
module The where

the :: forall a. Array a -> a
the [x] = x
```

gives this:
```
Warning in value declaration the:
Warning at /home/harry/documents/code/ps-scratch/src/Main.purs line 3, column 1 - line 4, column 1:
    Pattern could not be determined to cover all cases.
    The definition has the following uncovered cases:

    _
```

which I would interpret to mean that the pattern covers no cases at all?

Incidentally, what's the recommended way of writing this function `the` in a way that won't produce warnings? I know it's unsafe and have taken that into account where I've used it.

**Comment by paf31** [comment]
This is by design, since without cons patterns, you can only cover a cofinite number of array lengths, so the only way to cover everything is to use a wildcard.

I agree though, the error could be a little more helpful.
