### ISSUE TITLE
Warn on duplicate imports

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1390]
Conditions for this:

- [x] Two whole-module imports of the same module
- [x] A whole-module import and a partial-import of the same module
- [x] Overlapping items in two partial-imports of the same module (suggest combining the list)
- [x] Two qualified imports of the same module

**Comment by paf31** [comment]
Wouldn't some of those be errors?

**Comment by garyb** [comment]
No, as they're all importing from the same module, in the PR I submitted it checks whether overlapping imports come from the same module now, so that's not an error. (Previously it was hidden entirely anyway, only the last import would be used.)
