### ISSUE TITLE
Clarify licensing terms from all contributors

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1394]
To all existing contributors,

Thank you very much for contributing to the PureScript compiler code.

There have been some cases recently where we have had to think quite a bit about the way code in the PureScript compiler codebase is licensed by its various contributors. Now seems like a good time to clarify things.

I have never wanted to impose a Contributor License Agreement to force transfer of copyright. As I see it, each piece of code is licensed to the project owners by its contributor under the terms of the MIT license (unless specified otherwise), and the MIT license is enough. Instead of a CLA, I'd like to ask you to take five minutes to just clarify the situation regarding any code you may have contributed in the past (if you have not contributed code, please ignore this message):
- I've created a file called [`CONTRIBUTORS.md`](https://github.com/purescript/purescript/blob/master/CONTRIBUTORS.md) in the root of this repository.
- Please add a comment below which includes your name and clarifies how your code is (and optionally, will in future) be licensed to the project. I will add your comment to the `CONTRIBUTORS.md` file (this saves having too many merge conflicts and email notifications).
- The `CONTRIBUTORS.md` file will be append-only, so you can always change your licensing terms for future contributions by _appending_ new or modified terms to the file.
- Here are some templates which you might like to use:
  - "My existing contributions and all future contributions until further notice are Copyright <your name>, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT)."
  - "I assign copyright of my contributions to date (mm/dd/yyyy) to the owners of the PureScript compiler project."

Hopefully this is as unimposing and lightweight as possible. It accomplishes the following things:
- Individual developers keep ownership of their contributions.
- We have a framework for accepting new contributions under different sorts of license going forward.

Going forward, we'll require updates to this file for new contributors.

**Comment by paf31** [comment]
Hmm apparently you can only mention so many people in a comment.

/cc @pseudonom @puffnfresh @robdaemon @RossMeikleham @sebastiaanvisser @sinelaw @sztupi @taku0 @timmytofu @trofi @utkarshkukreti @vendethiel @vkorablin @zudov

**Comment by michaelficarra** [comment]
Doing this through PRs like this is going to create a *lot* of notifications (65 contributors * 101 watchers). @paf31 Maybe contributors can give their permission here to have you add them directly using one of the proposed templates?

**Comment by paf31** [comment]
Ah right, good idea, I didn't think about that. Your approach would also solve the merge problem.

Yes, let's do that. I'll modify the issue.

**Comment by garyb** [comment]
Great idea :+1:

**Comment by paf31** [comment]
Applying the actor model to real world systems...

**Comment by davidchambers** [comment]
> "I assign copyright of my contributions to date (mm/dd/yyyy) to the owners of the PureScript compiler project."

Were I to select this option, would I need to update the date with each future contribution?

---

<a href="https://xkcd.com/1179/"><img alt="ISO 8601" src="https://imgs.xkcd.com/comics/iso_8601.png" title="ISO 8601 was published on 06/05/88 and most recently amended on 12/01/04."></a>

**Comment by paf31** [comment]
@davidchambers I suppose the append-only assumption of the file and the "until further notice" allows us to get rid of that one, since you could always override what you'd said previously. I'll remove it.

**Comment by davidchambers** [comment]
@paf31, your comment does not seem to relate to the option I quoted.

**Comment by paf31** [comment]
@davidchambers Sorry, it did, but I wasn't clear. I should have said: instead of fixing a date, you could choose the first option, but if/when you change your mind about licensing, send a PR to append new terms to the file. Given that we won't accept a PR without a line in the file from that contributor anyway, these options are equivalent.

**Comment by andyarvanitis** [comment]
@andyarvanitis (Andy Arvanitis) My existing contributions and all future contributions until further notice are Copyright Andy Arvanitis, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by davidchambers** [comment]
My existing contributions and all future contributions until further notice are Copyright David Chambers, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by nicodelpiano** [comment]
@nicodelpiano (Nicolas Del Piano) My existing contributions and all future contributions until further notice are Copyright Nicolas Del Piano, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by phadej** [comment]
@phadej My existing contributions and all future contributions until further notice are Copyright <your name>, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license."

**Comment by paf31** [comment]
@phadej I assume I can fill in your name there? Thanks everyone so far!

**Comment by phadej** [comment]
@paf31 yes, edited previous message.

**Comment by hdgarrood** [comment]
Sure:

My existing contributions and all future contributions until further notice are Copyright Harry Garrood, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by sztupi** [comment]
@sztupi (Attila Sztupak) My existing contributions and all future contributions until further notice are Copyright Attila Sztupak, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by ardumont** [comment]
@ardumont (Antoine R. Dumont) My existing contributions and all future contributions until further notice are Copyright Antoine R. Dumont, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by mpietrzak** [comment]
My existing contributions and all future contributions until further notice are Copyright Maciej Pietrzak, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by vendethiel** [comment]
@paf31 Since my only contribution was 414972932e3dfda4854e3971218783157e5b697f (it's not present anymore), I don't think I need to do that (I'd rather not have my name in public)

**Comment by lukerandall** [comment]
My existing contributions and all future contributions until further notice are Copyright Luke Randall, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by mjgpy3** [comment]
@mjgpy3 (Michael Gilliland) My existing contributions and all future contributions until further notice are Copyright Michael Gilliland, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by nagisa** [comment]
I hereby release my only contribution (https://github.com/purescript/purescript/commit/80287a5d0de619862d3b4cda9c1ee276d18fdcd8) into public domain.

**Comment by pseudonom** [comment]
My existing contributions and all future contributions until further notice are Copyright Eric Easley, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by aspidites** [comment]
"My existing contributions and all future contributions until further notice are Copyright Edwin Marshall, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license."

**Comment by paulyoung** [comment]
My existing contributions and all future contributions until further notice are Copyright Paul Young, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by japesinator** [comment]
My existing contributions and all future contributions until further notice are Copyright JP Smith, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by etrepum** [comment]
My existing contributions and all future contributions until further notice are Copyright Bob Ippolito, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by zudov** [comment]
"@zudov (Konstantin Zudov) My existing contributions and all future contributions until further notice are Copyright Konstantin Zudov, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license."

**Comment by dylex** [comment]
My existing and all future contributions to the PureScript compiler until further notice are Copyright Dylan Simon, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by erdeszt** [comment]
My existing contributions and all future contributions until further notice are Copyright Tibor Erdesz, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by trofi** [comment]
My existing contributions and all future contributions until further notice are Copyright Sergei Trofimovich, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by Bogdanp** [comment]
My existing contributions and all future contributions until further notice are Copyright Bogdan Paul Popa, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by jacereda** [comment]
My existing contributions and all future contributions until further notice are Copyright Jorge Acereda, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by pelotom** [comment]
My existing contributions and all future contributions until further notice are Copyright Thomas Crockett, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by RossMeikleham** [comment]
My existing contributions and all future contributions until further notice are Copyright Ross Meikleham, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by dckc** [comment]
My existing contributions and all future contributions until further notice are Copyright Dan Connolly, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

I chose this option as it seems to be the norm, though I'm open to waiving my copyrights entirely.

**Comment by nullobject** [comment]
My existing contributions and all future contributions until further notice are Copyright Josh Bassett, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by taku0** [comment]
My existing contributions and all future contributions until further notice are Copyright taku0, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by anthoq88** [comment]
My existing contributions and all future contributions until further notice are Copyright anthoq88, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license

**Comment by 5outh** [comment]
My existing contributions and all future contributions until further notice are Copyright Benjamin Kovach, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by joneshf** [comment]
My existing contributions and all future contributions until further notice are Copyright Hardy Jones, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by balajirrao** [comment]
My existing contributions and all future contributions until further notice
are Copyright Balaji Rao, and are licensed to the owners and users of the
PureScript compiler project under the terms of the MIT license.

On Tue, Aug 18, 2015 at 11:29 AM, Hardy Jones <notifications@github.com>
wrote:

> My existing contributions and all future contributions until further
> notice are Copyright Hardy Jones, and are licensed to the owners and users
> of the PureScript compiler project under the terms of the MIT license.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/purescript/purescript/issues/1394#issuecomment-132082123>
> .
>



-- 
Regards,
Balaji

**Comment by sebastiaanvisser** [comment]
My existing contributions and all future contributions until further notice are Copyright Sebastiaan Visser, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by kRITZCREEK** [comment]
My existing contributions and all future contributions until further notice are Copyright Christoph Hegemann, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by eamelink** [comment]
My existing contributions and all future contributions until further notice are Copyright Erik Bakker, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by bergmark** [comment]
My existing contributions and all future contributions until further notice are Copyright Sebastiaan Visser, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by epost** [comment]
My existing contributions and all future contributions until further notice
are Copyright Erik Post, and are licensed to the owners and users of the
PureScript compiler project under the terms of the MIT license
<http://opensource.org/licenses/MIT>.

**Comment by osa1** [comment]
My existing contributions and all future contributions until further notice are Copyright Ömer Sinan Ağacan, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by vkorablin** [comment]
My existing contributions and all future contributions until further notice are Copyright Vladimir Korablin, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by mrhania** [comment]
My existing contributions and all future contributions until further notice are Copyright Łukasz Hanuszczak, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by utkarshkukreti** [comment]
My existing contributions and all future contributions until further notice are Copyright Utkarsh Kukreti, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by L8D** [comment]
My existing contributions and all future contributions until further notice are Copyright Tenor Biel, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by paf31** [comment]
Ping for the remaining 9 code contributors. I'd love to get this wrapped up this week if possible.

/cc @andreypopp @berewt @chrissmoak @darthdeus @guillaume-nargeot @leighman @natefaubion @philopon @puffnfresh

**Comment by natefaubion** [comment]
My existing contributions and all future contributions until further notice are Copyright Nathan Faubion, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by puffnfresh** [comment]
All contributions I made during June 2015 were during employment at SlamData, Inc. who owns the copyright.

I assign copyright of all my personal contributions before June 2015 to the owners of the PureScript compiler.

**Comment by jdegoes** [comment]
On behalf of SlamData employees, our existing contributions and all future contributions to the PureScript compiler are, until further notice, Copyright SlamData Inc., and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by philopon** [comment]
* @philopon (Hirotomo Moriwaki) - My existing contributions and all future contributions until further notice are Copyright Hirotomo Moriwaki, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by leighman** [comment]
Sorry I missed this.

My existing contributions and all future contributions until further notice are Copyright Jack Leigh, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by paf31** [comment]
Added, thanks!

**Comment by paf31** [comment]
Ping @andreypopp @berewt @chrissmoak @darthdeus @guillaume-nargeot @leighman 

We're very close to being able to close this, which will mean the copyright holder and their terms will be known for every line of code in the compiler.

**Comment by cesmoak** [comment]
My existing contributions to the PureScript compiler and all future contributions to the PureScript compiler until further notice, are Copyright Chris Smoak, and are licensed to the owners and users of the PureScript compiler project under the terms of the [MIT license](http://opensource.org/licenses/MIT).

**Comment by paf31** [comment]
Thanks!

**Comment by paf31** [comment]
We're working through issues and I'd really like to close this if possible. Pinging @andreypopp @berewt @darthdeus @guillaume-nargeot @leighman 🙏

**Comment by andreypopp** [comment]
My existing contributions and all future contributions until further notice are Copyright Andrey Popp, and are licensed to the owners and users of the PureScript compiler project under the terms of the MIT license.

**Comment by leighman** [comment]
Mine is already done above :)

**Comment by paf31** [comment]
I recently realized that the section "Contributions Under Repository License" in the GitHub terms and conditions actually covers what we want here, namely that contributors agree to license their terms under the same terms as those in the LICENSE file. So, I think it is good to keep the CONTRIBUTORS.md file as a record (thanks to everyone who retroactively updated it), and continue to add new contributors to it, but we can probably close this issue.

Here is the text of that section, for reference:

> Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms. If you have a separate agreement to license your contributions under different terms, such as a contributor license agreement, that agreement will supercede.
> 
> Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.
