### ISSUE TITLE
Flag to ignore warnings from libraries

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1400]
Something like
```psc no-warnings "../bower_components/purescript-*/src/**/*.purs"```
I don't think I should care about this warnings. If I want fix the library I would work with it as a main project.

**Comment by paf31** [comment]
This matches GHC now. We show the warnings on the first compile only (in 0.7.3)

**Comment by user471** [comment]
How can I force to show all warnings for my modules without changing files?

**Comment by paf31** [comment]
Without changing them? Use `touch`.

**Comment by paf31** [comment]
Or delete the `output` directory.

**Comment by user471** [comment]
>Use touch

How does compiler decide what files should be recompiled? Is it store last change date somewhere?

**Comment by paf31** [comment]
It checks the date of the input file versus the date of the output file.
