### ISSUE TITLE
Bower Improvements

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1404]
How might we enhance or replace Bower for our use case?

Discussion is here #631, please keep this page for listing potential improvements as bullet points so that it's easily read. I'll move discussion items out as necessary.

**Comment by garyb** [comment]
Old discussion on related things: #631

**Comment by garyb** [comment]
Two things bower alone can't handle for us:

- Checking that a compiler/library version is compatible
- Dealing with packages that also have dependencies via `npm` (e.g. those that depend on `virtual-dom`)

**Comment by beckyconning** [comment]
Bower gets bonus points for being a familiar face for front end JavaScript developers looking into PureScript.

**Comment by natefaubion** [comment]
* PSC compiles to CommonJS. Most libs that have FFI requirements are using CommonJS. Pulp bundles things with Browserify. None of these play very well with the existing Bower ecosystem.

**Comment by hdgarrood** [comment]
One thing that I expect would be a massive amount of effort but could be really useful is to have a package manager capable of "private dependencies"; sort of like what npm does, but proved safe by the compiler. For example, I once wanted to install `smolder`, which at the time depended on an older version of `maps`. I was already using the newest version of `maps`, which was incompatible with the version `smolder` depended on. `smolder`, however, didn't expose any functions that took or received any values from `maps` &mdash; `smolder`'s use of `maps` was entirely internal, so I think it would have been safe to install two separate versions of `maps`, and to use the newest one in my code, and use the older one internally inside `smolder`. I think this could help avoid many situations where dependency versions cannot be resolved.

**Comment by manpages** [comment]
Just a quick theoretical observation — if we know that there is a bijection between build results and semantically-versioned releases, then we don't need anything smart, just a constraint-respecting script that fetches stuff from git/npm, which — as @hdgarrood pointed out — ought to support some sort of multilib behaviour.

Real question, of course, is — does that sort of bijection exist and if not, how close to it can we get?

Related work — [Dolstra E. The Purely Functional Software Deployment Model.](http://nixos.org/~eelco/pubs/phd-thesis.pdf), [Elixir Mix utility](http://elixir-lang.org/docs/v1.0/mix/), which is both build system and dependency manager; [Sadly, no paper about Mix is written, so here's intro post](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html).

---

Some opinionated thoughts follow, if you're easily offended, please skip this part. Point of me putting it here is not to offend anyone, but to express my opinion <3

---

Overall, I find using a project, main page implies that it bundles "rainbows with assets" deeply disturbing. Authors of bower fail to articulate what is this tool and why was it written in the first place and as a very-very new member of purescript community, I fail to understand what is this thing doing in purescript ecosystem and why.

@beckyconning's argument for JS developers being familiar with bower is a non-argument — both bower *and* browserify are highly optional for developing frontends these days. I was managing a frontend team and we were using npm, npm-shrinkwrap (buegh) and webpack.

**Comment by hdgarrood** [comment]
Can we please not have any "if you're easily offended, please skip"? If you feel like you need to write that, perhaps consider not posting what it refers to at all, or removing the offensive bit first.

**Comment by hdgarrood** [comment]
Also, it's currently very easy to attempt to build when the set of installed dependencies is either empty or completely different to the set described in `bower.json`. It would be nice if we could make this mistake a bit easier to avoid, and also to improve the error you get in cases where we have no option but to produce an error. At the very least, "Dependencies are not installed, please run bower install" is much better than "Unknown module Data.Int" or similar.

**Comment by zudov** [comment]
- enforce semver whenever possible (or at least alert in some way) (the least possible is to check whether the exported API changed on type level)

**Comment by paf31** [comment]
See #631.
