### ISSUE TITLE
Add PSCi option to customize path to Node executable

### ISSUE THREAD

**Issue by gbaz** [purescript/purescript#1407]
psci.exe: C:\cygwin\bin\node.exe: readCreateProcessWithExitCode: permission denied (Permission denied)

Potentially because the file it asks node to read from hasn't been closed from psci?

**Comment by garyb** [comment]
Interesting, I don't have any issues with psci on windows, but I'm not running via cygwin...

**Comment by gbaz** [comment]
so it works if I put another node first on my path, I just discovered. But that screws me up elsewhere. Can we make psci accept a custom path for the node executable?

**Comment by paf31** [comment]
Yes, I think we should add a command line option.

**Comment by michaelficarra** [comment]
Would an environment variable be better?

**Comment by paf31** [comment]
Probably yes, actually.
