### ISSUE TITLE
Potential soundness issue related to wildcard rows

### ISSUE THREAD

**Issue by beckyconning** [purescript/purescript#1409]
This function compiles and runs as intended but I cannot find any non-wildcard types that typecheck.

https://github.com/beckyconning/purescript-couchdb-coroutines/blob/3cd0da317ef752e739447aeda4b0f4dcba5ff636/test/Main.purs#L71

Maybe STArray doesn't actually work like this and something to do with wildcards and rows is letting it work like this due to soundness issues ("because it says it works").

**Comment by garyb** [comment]
Related to #1310?

**Comment by paf31** [comment]
I don't think so actually.

**Comment by paf31** [comment]
I was able to make this typecheck with the following row in all three places:

```purescript
( exit :: EXIT
, console :: CONSOLE
, st :: ST h
, avar :: AVAR
, random :: RANDOM
| eff
)
```

with a bit of help from the new (not broken) wildcard warnings :smile:

**Comment by paf31** [comment]
I'll close this since it's not apparently a soundness issue, just a case of wildcards not being as helpful as we'd like.
