### ISSUE TITLE
TCO not firing on List foldl

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1413]
See https://github.com/purescript/purescript-lists/issues/38

**Comment by garyb** [comment]
I think @natefaubion mentioned this already, but isn't this just down to the fact that it's tail recursive via a dictionary? Like, it's this:

``` js
Data_Foldable.foldl(foldableList)(o)(o(b)(_87.value0))(_87.value1)
```

I imagine we can only current handle it when its like this:

``` js
foldl(o)(o(b)(_87.value0))(_87.value1)
```

As the JS optimiser has no way of knowing that the function-via-dictionary is the same thing as the current functions.

**Comment by natefaubion** [comment]
I mentioned it in IRC, forgot to carry the discussion over.

A fairly simple options would be to desugar instance declarations somewhat redundantly:
```purescript
instance foldableList :: Foldable List where
  foldl f b Nil = b
  foldl f b (Cons a as) = foldl f (b `f` a) as
```
```purescript
instance foldableList :: Foldable List where
  foldl = foldableList_foldl where
    foldableList_foldl f b Nil = b
    foldableList_foldl f b (Cons a as) = foldableList_foldl f (b `f` a) as
```
Which causes TCO to fire since there's now a real binding instead of a dictionary reference. You'd have to be careful when renaming the recursive call. It doesn't seem like it would even be possible to fix it as is since TCO operates on the JS AST.

**Comment by garyb** [comment]
Yeah, I had started porting our current set of optimisations over to `CoreImp` when I was working on that, we would have enough information to do it properly there, but that's fallen way behind where the compiler is at now. I think it'll be left until after 0., as we're just trying to fix things mainly in 0.8.

**Comment by natefaubion** [comment]
Until then, the workaround is to lift out the definition, and just alias it in the instance, or define a `go` type helper that does the tail recursion.

**Comment by garyb** [comment]
Yeah, that's what @zudov has proposed in purescript/purescript-lists#42, seems like a reasonable but unfortunate compromise for now.

**Comment by paf31** [comment]
I'm not sure I see a good way to fix this actually. The optimizer needs a named function, so without inlining the dictionary call and having named instance members, this will be tricky. Yet another case of TCO being unpredictable unfortunately. I think we might do better to just document the restriction, and have the user write the helper function.

**Comment by paf31** [comment]
I would like to close this as `wontfix`, which is short for "this is an unfortunate side-effect of the unpredictability of TCO". Even moving TCO to the core AST wouldn't make this easier unfortunately.

**Comment by garyb** [comment]
Yeah, I guess that's all we can do. When I eventually finish the CoreImp AST and then spend some time on a supercompiler back end it might be possible :wink:, but I guess that won't be part of `psc` and it will be some time off yet.
