### ISSUE TITLE
Handling re-exported modules in documentation

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1415]
I'm not quite sure what `psc-docs` or Pursuit will do right now with re-exported modules, but I think we need to handle them explicitly. The best way I've thought of so far is something like this, in, say `Control.Monad.Except`, it should also include all of the re-exported declarations, each with a note that says, eg, "Re-exported from Control.Monad.Error.Class".

**Comment by garyb** [comment]
Re-exports are completely invisible currently. I'm current overhauling the exports and was thinking about how we represent this, but I guess just peering into the export declarations is good enough to do what you describe here.

**Comment by garyb** [comment]
Although actually, with the changes I'm about to open a PR for it makes partial re-exporting possible too, so maybe we need to be more specific than just saying which modules are.

**Comment by hdgarrood** [comment]
Closing as a dupe of #1677, which has a little more detail (oops, I opened both of these)!
