### ISSUE TITLE
Function composition inlining is not triggering

### ISSUE THREAD

**Issue by puffnfresh** [purescript/purescript#1427]
Minimal example:

```purescript
module Example where

import Prelude

f :: forall a b c. (b -> c) -> (a -> b) -> (a -> c)
f g h = g <<< h
```

```javascript
var Prelude = require("Prelude");
var f = function (g) {
    return function (h) {
        return Prelude["<<<"](Prelude.semigroupoidFn)(g)(h);
    };
};
```

**Comment by puffnfresh** [comment]
Feel free to assign this to me, I'll fix it sometime.

**Comment by mjgpy3** [comment]
Would the expected inline just be something like the following?
```
var Prelude = require("Prelude");
var f = Prelude["<<<"](Prelude.semigroupoidFn);
```

**Comment by garyb** [comment]
No, it would be like `\x -> f (g x)` - https://github.com/purescript/purescript/blob/5fae3534d873cf1832d8d5f9c8785d3d02ad3cb7/src/Language/PureScript/CodeGen/JS/Optimizer/Inliner.hs#L245-L258

The goal is to remove the composition plumbing from delcarations, not detect the occasional case where there is an eta abstraction of `(<<<)` :wink:

**Comment by mjgpy3** [comment]
I see, thanks @garyb

**Comment by garyb** [comment]
@puffnfresh I think I see what's happening here, `semigroupoidArr` was renamed to `semigroupoidFn` at some point. If that's all it is I'll put a fix in for it now.
