### ISSUE TITLE
genericVoid exhaustivity warning

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1432]
The `genericVoid` test in `core-tests` is firing an exhaustivity warning:

```
Warning in module GenericDeriving:
Warning in value declaration genericVoid:
Warning at tests/generic-deriving/Main.purs line 9, column 1 - line 11, column 1:
    Pattern could not be determined to cover all cases.
    The definition has the following uncovered cases:
    _
```

which is incorrect since `Void` has no constructors.

/cc @nicodelpiano would you like to look at this? (if not, I can)

**Comment by paf31** [comment]
I suppose this isn't simple, because we _always_ start with a wildcard, and there are no cases to guide us. Since the exhaustivity checker doesn't know about types, this is actually quite difficult to solve without a hack. Moving to Backlog.

**Comment by nicodelpiano** [comment]
Yes, no problem Phil. I'll take a look!

**Comment by paf31** [comment]
@nicodelpiano Don't worry about it actually. After thinking about it some more, it's probably not worth the hassle until we get GADTs or the like.

**Comment by paf31** [comment]
I'm going to close this, because it's trickier to fix than it sounds, and once we derive and start using `Data.Generic.Rep.Generic`, this shouldn't be an issue any more.
