### ISSUE TITLE
Improve error location information inside type class instance lookup

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1433]
I'm currently converting the tests in purescript-sequences to use newtype wrappers to avoid orphan instances. For example, [this file](https://github.com/hdgarrood/purescript-sequences/blob/83e81f02154a70b8c94bcb33f0336c1a9a2aeacd/test/Data/Sequence/NonEmpty.purs#L24-L147) contains some of the offending tests. In these files, all the tests are defined using one big `do` block.

In my working copy, I now have the necessary newtype wrappers, and they all have Arbitrary instances. I thought I had converted all the tests over to use these wrappers, but it seems I must have missed at least one, because I'm getting "No instance found for Arbitrary (NonEmpty.Seq Number)" errors.

Unfortunately the source span is huge: "Error at /home/harry/documents/code/purescript-sequences/test/Data/Sequence/NonEmpty.purs line 20, column 1 - line 145, column 57:" - being told the error is somewhere between line 20 and line 145 is not very helpful.

As far as I can tell, this applies to errors arising from missing instances only.

**Comment by garyb** [comment]
I think #1357 would makes this possible when solved.

**Comment by paf31** [comment]
Is this still happening?

**Comment by hdgarrood** [comment]
Yes, using the compiler from master. See purescript-sequences at the commit 25233d98529

https://github.com/hdgarrood/purescript-sequences/blob/25233d985292a75b51d008763c16360efbdb06e8/test/Data/Sequence/Ordered.purs

The error is:

```
Error found:
Error in value declaration orderedSequenceTests:
Error at /home/harry/documents/code/purescript-sequences/test/Data/Sequence/Ordered.purs line 27, column 1 - line 116, column 70:
Error in module Tests.Data.Sequence.Ordered:
No instance found for

  Test.QuickCheck.Arbitrary.Arbitrary (OrdSeq Number)
```

**Comment by paf31** [comment]
Ah ok, this isn't related to do blocks, it's just an issue with errors during type class instance lookup.

**Comment by paf31** [comment]
This is actually quite difficult because of the way we propagate position information using `MonadError`. We might want to consider just passing the list of hints as a function argument.

**Comment by paf31** [comment]
Even though this is related to errors, I'd like to move it to 0.9, and handle it with the new type checker changes.
