### ISSUE TITLE
Provide a way of turning warnings into errors

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1434]
Probably with a `-Werror` flag, although we might be able to come up with a nicer way.

Also we might want to allow making warnings into errors only for a subset of the files being compiled, as warnings in dependencies usually want to be ignored. Perhaps by having an optional glob argument: `--Werror-glob 'src/*'`, maybe?

**Comment by jonsterling** [comment]
We'd also find this super useful at SlamData!

**Comment by paf31** [comment]
I have mixed feelings about this. On the whole, I like using `-Wall -Werror` in GHC, but I also really like the fact that `psc` has no options which change the language.

If we do add this, it probably does need to be glob based, as you suggest.

**Comment by hdgarrood** [comment]
Alternatively we could decide that this should be a job for downstream tools. I think json warnings/errors + `jq` would probably be enough to achieve the same result.

**Comment by hdgarrood** [comment]
Possibly a job for [`psa`](https://github.com/natefaubion/purescript-psa)?

**Comment by paf31** [comment]
Yes, I think so, or some other frontend tool, perhaps.
