### ISSUE TITLE
Case parse bug

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1435]
```purescript
error err = case err of \_ -> 1
```

parses but probably shouldn't.

**Comment by fisx** [comment]
just to make sure: the intended line is

```
error err = case err of _ -> 1
```

see #purescript a few minutes ago.

**Comment by zudov** [comment]
Are there any uses for empty case (besides failing at runtime)?

**Comment by paf31** [comment]
Empty cases are useful for code generation, like `Generic` deriving, but I don't think the current syntax has to support them. Once we have braces-and-semicolons as an alternative to explicit whitespace, I think `case _ of {}` is better. For now I think we should just disallow it in the parser.

**Comment by zudov** [comment]
@paf31 Just to say that haskell allows EmptyVoid without braces:
```haskell
Prelude> :set -XEmptyCase
Prelude> let foo = (case 1 of)
Prelude> :t foo
foo :: t
```
But @fisx's case gives an evidence that it's error prone.
