### ISSUE TITLE
Constructor alias

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1438]
When you frequently use some data constructor, it could be useful to have short alias.
```
data PersonData = PersonData String Int
alias PD = PersonData
foo = (\(PD x y) -> x <> show y) (PD "Foo" 1)

type SomeInformation = {foo::String, bar::Int}
alias SI = {foo: _, bar: _}

foo = (\(SI x y) -> x <> show y) (SI "Foo" 1)
```
Maybe even with using operators
```
alias (@) = Tuple
foo = (\(x @ y) -> x <> show y) ("Foo" @ 1)
```

**Comment by zudov** [comment]
Interesting.
But to make it work as in your sniplet would basically mean to allow capitalized function names when they are declared using `alias` keyword.

**Comment by garyb** [comment]
I think `ViewPatterns` and maybe `PatternSynonyms` too would be a preferrable way of handling cases like these. For construction you could then just make an alias by `pd = PersonData` as a normal function.

**Comment by paf31** [comment]
I'm going to close this and reopen as "Pattern Synonyms", since there are a few issues which are covered by Pattern Guard and Pattern Synonyms taken together.
