### ISSUE TITLE
PSCi should support alternatives to Prelude/Console

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1441]
PSCi currently relies on `purescript-console`, but for teaching purposes, I would like to be able to use `purescript-preface` with PSCi, for example.

I don't know how to support this, but I think it would be good to be able to support different sets of core libraries.

Perhaps we can do something like we do with rebindable do notation, and rely on some name being in scope. Maybe we need to also make the `$PSCI.Support` module available for import.

**Comment by garyb** [comment]
Perhaps something else we could add `:command` to configure it, that way it could be included in a `.psci` file too?

**Comment by tfausak** [comment]
:+1: This would be useful for [purescript-neon](https://github.com/tfausak/purescript-neon).

**Comment by paf31** [comment]
This could be as simple as moving the `PSCI.Support` module into its own versioned package, so that writers of custom preludes can ship an instance for the `Eval` class.

**Comment by hdgarrood** [comment]
Hm, I think it might be a problem if we want to give something both `Show` and `Eval` instances. Perhaps we can cross that bridge when we get to it, though.

**Comment by paf31** [comment]
Yes, it's an overlapping instance problem generally, but maybe we can fix that with instance chains one day.

**Comment by paf31** [comment]
I'll leave this open since `purescript-psci-support` still needs to be updated and moved to core.

**Comment by paf31** [comment]
Closing, since the support module is now available [here](https://github.com/purescript/purescript-psci-support).
