### ISSUE TITLE
Instance resolution and referential transparency

### ISSUE THREAD

**Issue by passy** [purescript/purescript#1442]
Apologies for the rather big test case, I'm not sure how to reduce this further:

```purescript
module Mod where

import Prelude

import qualified Halogen.HTML as H
import qualified Halogen.HTML.Core as H
import qualified Halogen.HTML.Properties as P
import qualified Halogen.HTML.Events as E
import qualified Halogen.HTML.Events.Forms as E
import qualified Halogen.HTML.Events.Handler as E
import qualified Halogen.HTML.Events.Types as E

import Control.Apply
import Data.Functor
import Halogen
import Halogen.Component
import Halogen.Query.StateF

newtype State = State { stuff :: String }
data Input a = NoOp a

c :: forall g p. (Functor g) => Component State Input g p
c = component render eval
    where
    render :: Render State Input p
    render _ = H.div_ []

    eval :: Eval Input State Input g
    eval (NoOp next) = modify (\(State s) -> State s) $> next
```

In the final line, replacing the `(\(State s) -> State s)` with `id` causes a compiler error:

```
Error found:
Error in module PscTest:
Error in value declaration c:
Error at PscTest.purs line 21, column 1 - line 22, column 1:
  No instance found for Data.Inject.Inject (Halogen.Query.StateF.StateF _27) g10
See https://github.com/purescript/purescript/wiki/Error-Code-NoInstanceFound for more information, or to contribute content related to this error.
```

I'm not sure if I'm doing something stupid here, but to me it seems the two equations should be equal.

```bash
$ psc --version
0.7.4.1
```

**Comment by garyb** [comment]
They should be, but when you're using `id` it looks like the compiler can't figure out what the `s` is for `StateF` - the `_27` is an unknown type: https://github.com/purescript/purescript/wiki/Tips-for-interpreting-error-messages#_0_n-types

I've just pushed something to my WIP Halogen branch that should help with this though: it's not using `Inject` anymore, so it might be able to infer the type now.

**Comment by passy** [comment]
Cool, I'll give that a try. :)

So, is it expected that the compiler cannot infer the type in these situations? Originally I had `State` as a type synonym and since there's no way for me to manually unwrap and rewrap the type I couldn't figure out how to make it compile at all.

**Comment by garyb** [comment]
I wouldn't say it's expected - I also was surprised I had to `newtype` the state sometimes when working on the examples. I'm not really sure what the problem is either though! It could be constraint-inference related, or #1027 when you tried with the synonym, or something else that I'm not aware of in the current typechecker.

**Comment by paf31** [comment]
Isn't this just the usual "we need fundeps" issue?

**Comment by garyb** [comment]
I believe so, or it was synoym related - either way it doesn't apply to Halogen now as the types changed quite a bit since this.
