### ISSUE TITLE
Fail to derive Generic with record argument referenced through type synonym

### ISSUE THREAD

**Issue by zudov** [purescript/purescript#1443]
``` purescript
type MyArray   = Array String
type MyString  = String
type MyNumber  = Number
type MyInt     = Int
type MyBoolean = Boolean
type MyProduct = Maybe String
type MyRecord  = { x :: Number, y :: Number }

data Foo = Foo MyArray   -- fine
               MyString  -- fine
               MyNumber  -- fine
               MyInt     -- fine
               MyBoolean -- fine
               MyProduct -- fine
               MyRecord  -- FAIL
derive instance fooGeneric :: Generic Foo
```

fails with

``` shell
No instance found for Data.Generic.Generic MyModule.MyRecord<>
```

**Comment by garyb** [comment]
I assume `MyRecord` was called `Point` when you ran the compiler?

**Comment by zudov** [comment]
@garyb Yes, sorry. Fixed now.

**Comment by garyb** [comment]
Just checking :)

Does it work when `MyRecord` is not a synonym in the `Foo` constructor? I don't know whether we can derive generics for records...

**Comment by zudov** [comment]
Yes it does. Records are a part of our `Generic` data type https://github.com/purescript/purescript-generics/blob/master/src/Data/Generic.purs#L34

**Comment by garyb** [comment]
Cool, it's just "type synonyms again" then. I really need to get around to trying my idea for handling them...

**Comment by zudov** [comment]
I think the issue arises because `Data.Generic` defines instances for everything I listed above, but record. When the record is present directly compiler derives it, but when because of some bug it doesn't follow the type synonym

**Comment by paf31** [comment]
The error is now

```text
Error found:
in module Main
at 1443.purs line 9, column 1 - line 9, column 39

  No type class instance was found for

    Data.Generic.Generic { y :: Number
                         , x :: Number
                         }


in value declaration fooGeneric
```

**Comment by paf31** [comment]
This happens because type class desugaring happens after derived instances get elaborated.

**Comment by paf31** [comment]
Moving to 0.9.

**Comment by user471** [comment]
Is there any possible workaround? Or you can only duplicate the record definition in data constructor?

**Comment by garyb** [comment]
That's the workaround for now. Or using a newtype instead of a synonym, but that's even less convenient most likely.

**Comment by gbaz** [comment]
If there's anything I can do to help here, let me know and I'll take a wack. This is biting us too now that we're using generics in anger.

**Comment by paf31** [comment]
@gbaz That would be great, but it's not obvious to me how this will be fixed yet. Type synonyms are desugared in the typechecker after instance deriving is done. Perhaps there is a nice way to reuse the `Environment` if we move the instance deriving into the typechecker, like what I did in my recent PR for the `Partial` constraint changes.

**Comment by gbaz** [comment]
I'm passing this along, and I think some people on our team want to start looking at it real soon. We'll keep you up to date if we make progress :-)

**Comment by jqyu** [comment]
Is there a reason why type synonyms must be desugared after instance deriving is done? This bug is becoming a blocker for my team as well, and changing the desugaring order sounds like an easy fix.

**Comment by garyb** [comment]
Unfortunately it's not entirely straightforward as the desugaring happens in two different ways.

There's an initial desugaring pass that handles a lot of stuff, like making all names fully qualified, desugaring `do` notation, object wildcards, etc. and the derived instances are also dealt with at this point.

The type synonyms are desugared during the typechecking pass, which happens after all the other desugaring has been done (and in fact requires it to have been done, it will `error` if some of the sugar AST cases are encountered).

I think @paf31 intends to move instance desugaring into the typechecking pass to resolve this, but I've not looked into it myself to see how involved that is. I'm pretty sure you can't just move the desugar function from one place to another though. :smile:

**Comment by jqyu** [comment]
Ah, no wonder I couldn't find the type synonym code, it's in the typechecking pass not the desguaring pass. Thanks for clarifying!
