### ISSUE TITLE
Kind polymorphism

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1444]
It would be nice.

**Comment by puffnfresh** [comment]
Would be very useful for things like https://github.com/purescript/purescript-exists where we have to duplicate everything to do existential row variables. @paf31 what's the feasibility of kind polymorphism?

**Comment by garyb** [comment]
Yeah, that's exactly the kind of thing I had in mind. I imagine if we do this it'll have to wait for the new typechecker?

**Comment by paf31** [comment]
I don't think it's particularly hard to implement, but the tricky bit is when we have values with polykinded types:

```purescript
data Proxy (a :: k) = Proxy

Proxy :: forall k (a :: k). Proxy a
```

so the kind information has to live with both types and values. Right now type and kind inference don't mix. We could of course restrict values to having only monokinded types.

**Comment by LiamGoodacre** [comment]
Duplicate: https://github.com/purescript/purescript/issues/1763
Close this one? The other has more activity.
