### ISSUE TITLE
Evaluation order polymorphism

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1445]
This looks really interesting, and also potentially very useful for our case. As mentioned by @paf31 in IRC.

http://arxiv.org/abs/1504.07680

https://www.youtube.com/watch?v=54esZ1TvFCY

**Comment by LiamGoodacre** [comment]
This does indeed look really interesting :)

What is the specific case/problem that you are saying this would be useful for?

**Comment by garyb** [comment]
There are a lot of Haskellisms we've imported that don't work so well when evaluating strictly - it would be nice to handle these without explicit thunking and forcing.

But even without the Haskell angle it seems like a worthwhile feature, since we don't have to worry about effects outside of Eff it perhaps won't be too difficult to implement either.

**Comment by rightfold** [comment]
See also https://pursuit.purescript.org/packages/purescript-eval/1.1.0/docs/Control.Eval
