### ISSUE TITLE
Document happy and alex as dependencies

### ISSUE THREAD

**Issue by FilWisher** [purescript/purescript#1446]
I don't fully understand how dependencies are installed by cabal but when installing purescript both from npm and the Arch AUR, the pre-build tests were failing and the install would hang for a while. Once the build complete, it the binary would fail to execute. 

After running the tests myself, I saw that language-javascript hadn't been installed. When trying to install language-javascript, some if its dependencies also hadn't been installed.

I have installed all the dependencies and run the build manually. It is now working so the issue is resolved HOWEVER: should the dependencies have installed on their own?

**Comment by paf31** [comment]
Do you have `alex` and `happy` installed?

**Comment by FilWisher** [comment]
I had to install them while trying to install language-javascript. I couldn't see these dependencies documented anywhere. Are they?

**Comment by paf31** [comment]
No unfortunately `language-javascript` requires them, but the `cabal` file doesn't list them. They're binary dependencies, and for some reason I don't understand, it's become normal to just assume they're installed. Maybe we could add them to our own dependencies instead, but I'm not sure that'd work.
