### ISSUE TITLE
GADTs via Prism/Lens

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1448]
I sketched this out on paper and wanted to note it here so I didn't forget. This might be a simple path to adding GADTs which makes exhaustivity checking somewhat trivial.

- Patterns are just prisms (see `purescript-totally` for why this is the case)
- The hard part about implementing GADTs is pattern matching.

We can elaborate patterns into prisms for the purposes of typechecking and exhaustivity checking, but keep the original pattern representation around for code gen. The nice thing about this is that we can implement it as sugar, before typechecking (`case` becomes invisible to the typechecker, replaced by a bunch of prism applications)

/cc @joneshf @nicodelpiano you might find this interesting.

Anyone see any issues with this approach?

**Comment by garyb** [comment]
Uhh, I find it very interesting too! Definitely sounds like a route worth exploring.

**Comment by puffnfresh** [comment]
Huge :+1: to this. It would be **totally amazing** if we could also get composable pattern matching.

**Comment by nicodelpiano** [comment]
This sounds very interesting, I want to work on this for sure!

**Comment by jdegoes** [comment]
> Huge :+1: to this. It would be totally amazing if we could also get composable pattern matching.

Ditto. :+1: :heart_eyes:

**Comment by LiamGoodacre** [comment]
Sounds awesome!

**Comment by garyb** [comment]
Thinking a bit more about this, I guess one downside is it means the compiler will need to rely on the presence of `Applicative` and `Choice`?

**Comment by paf31** [comment]
Well to begin with, I would only want to use prisms for type and exhaustivity checking. Later on they could be turned into real prisms perhaps, but for the initial purpose, we could just assume the existence of the functions and types we need by adding them into `Prim`.

**Comment by paf31** [comment]
i.e. they don't actually have to be implemented at runtime.

**Comment by garyb** [comment]
Ah right, that makes sense.

**Comment by paf31** [comment]
Closing this, it's not a fully-formed proposal, and I'd be more inclined to implement "Complete and Easy Indexed ..."

**Comment by AppShipIt** [comment]
> "Complete and Easy Indexed ..."

[For reference](https://www.reddit.com/r/haskell/comments/1c50t3/complete_and_easy_bidirectional_typechecking_for/) in case anyone stumbles on this.

**Comment by paf31** [comment]
Same authors, but I was referring to the [thrilling sequel](http://www.cs.bham.ac.uk/~krishnan/gadt.pdf).

**Comment by JordanMartinez** [comment]
The link posted by Phil is dead, but one can still access it via the Internet Archive: https://web.archive.org/web/20161121224604/http://www.cs.bham.ac.uk/~krishnan/gadt.pdf (year 2015)

When I searched for the paper's title, I also came across this: https://dl.acm.org/doi/pdf/10.1145/3290322 Not sure if that's a more recent version of their paper (year 2019)
