### ISSUE TITLE
psc-publish doesn't allow my name in bower.json

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript#1449]
Cause I'm german and it contains the Umlaut ü.

Error in JSON in the output of `bower list --json --offline`:              
  The input could not be parsed as JSON aeson said: Failed reading: Cannot 
  decode byte '\xfc': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8
  stream

**Comment by garyb** [comment]
That's odd, is your bower.json saved with UTF8 encoding?

**Comment by zudov** [comment]
@garyb I was able to reproduce it with UTF8 encoded, interestingly some non-ascii symbols work fine and some doesn't.

**Comment by zudov** [comment]
Fixed in a referenced PR
