### ISSUE TITLE
*.tix files from binaries

### ISSUE THREAD

**Issue by seanstrom** [purescript/purescript#1451]
Seems like whenever I run `psc`, or `psci`, it leaves something like `psc.tix` file relative to the where I ran the command. Seems similar to the issue here https://github.com/purescript/purescript/issues/697

**Comment by paf31** [comment]
Looks like the binaries have been built with profiling turned on.

https://downloads.haskell.org/~ghc/7.8.2/docs/html/users_guide/hpc.html
