### ISSUE TITLE
Allowing to alter runtime representation for an ADT

### ISSUE THREAD

**Issue by BartAdv** [purescript/purescript#1452]
Motivation is following (working with react-bootstrap): 

a record of type
```purescript
type ButtonProps = {
  active :: Boolean,
  disabled :: Boolean,
  -- ...
  type :: String
}
```

is passed to React, and props are validated. The `type` field is supposed to be one of `'reset', 'submit', 'button'`.

This begs for simple ADT:
```purescript
data ButtonType = Button | Reset | Submit

type ButtonProps = {
  -- ...
  type :: ButtonProps
}
```

However, the runtime representation for simple ADT like this is not what React expects. Would be great to have a way to alter the runtime representation of some datatype (maybe even just two functions that convert to and from).

**Comment by natefaubion** [comment]
This is a good usecase for newtypes + smart constructors. Newtypes have the same underlying representation as the type they wrap, so you don't need to do any converting when passing it off to the FFI.

```purescript
module ButtonProps (ButtonType(), button, reset, submit) where
newtype ButtonType = ButtonType String
button = ButtonType "button"
reset = ButtonType "reset"
submit = ButtonType "submit"
```

The problem is you lose easy pattern matching + coverage.

**Comment by BartAdv** [comment]
Ah, smart constructors. Yes, this is nice way to do this as I don't need the pattern matching in this case.

As for the issue, it can be closed but I'm gonna leave it opened for a while, maybe someone decides an addition like this could be useful.

**Comment by natefaubion** [comment]
Something like [https://ghc.haskell.org/trac/ghc/wiki/PatternSynonyms](pattern synonyms) would be really nice. It lets you keep the newtype, but then expose nice patterns for the purposes of matching. I don't know how it deals with coverage though. You can also use prisms.

**Comment by paf31** [comment]
Can we close this if smart constructors do the job? I don't think we want to support different interpretations of ADTs, but pattern synonyms would make a nice addition as a separate issue in the `Ideas` milestone.

**Comment by BartAdv** [comment]
Yes, closing it.
