### ISSUE TITLE
Cannot compile: Compile hangs and brings os to a crawl

### ISSUE THREAD

**Issue by felixSchl** [purescript/purescript#1459]
I cannot compile any of the recent commits to my hobby project [felixSchl/docopt.js](https://github.com/felixSchl/docopt.js).

I have noticed the immense lag / freeze in around commit [0385997](https://github.com/felixSchl/docopt.js/commit/03859976f8f6c77d6cb9bf8976b60151cad19d26). It compiles at my office machine but it won't at home.

Both are OSX, I don't know the details of the office machine at this moment (I am at home), but at home I have got a Late 2013 iMac, with:

* CPU - 2.7GHz Interl Core i5
* Memory - 8GB 1600 MHz DD3

Not sure what else might be relevant.

I can see in the activity monitor the memory usage ramping up rapidly to around 3GB, it will occasionally  drop down to 2GB or 1GB. The machine went terrible slow when it was down to 1GB actually. However, on the bottom of the activity monitor main window, the memory pressure window goes from green over yellow to red where it will stay until I force quit the process.

I have had the process run for 10 minutes w/o any success and the system just slowed down to a crawl, getting it to register the "force quit" click alone took several minutes.

I cannot prove it, but I _think_ it my have to with warnings being generated, because `purescript-spec` and `Data.List` had some uncovered pattern match cases, iirc. 

To run the project, just `bower i && pulp test`.

**Comment by garyb** [comment]
Are you using `psc` 0.7.4.1 on both machines?

**Comment by felixSchl** [comment]
@garyb Correct, I have tried both 0.7.4.1 and 0.7.4.

Also when I say it compiles at my office - yes it does but it also takes enough time to go make coffee.

More stats from running against 0.7.4:

The psc process:

* Real memory size: 538MB
* Virtual memory size: 17.7GB
* Shared memory size: 220KB
* Private memory size: 535.2MB

**Comment by garyb** [comment]
`Data.List` is heavily used so I don't think that's the culprit. Interestingly it does compile some stuff, as attempting to build after killing the process reveals this:
```
Error found:
Error at /Users/gary/Desktop/tmp/docopt.js/src/Parser/Lexer.purs line 6, column 49 - line 6, column 52:
  Module Control.Monad.State does not export value get
```
But obviously the actual bug that hangs the compiler needs fixing too.

**Comment by felixSchl** [comment]
> ```
> Error found:
> Error at /Users/gary/Desktop/tmp/docopt.js/src/Parser/Lexer.purs line 6, column 49 - line 6, column 52:
>  Module Control.Monad.State does not export value get
> ```

I have only seen this error when compiling with 0.7.3, both 0.7.4.1 and 0.7.4 don't throw this error. I think it has to do with the re-exporting a whole module?

**Comment by garyb** [comment]
Yeah, I had an odd version of the compiler installed it would seem - it reported itself as 0.7.4.0 but must have been from before the actual release.

**Comment by paf31** [comment]
Is this still an issue in `master`?

**Comment by paf31** [comment]
Can someone please if verify this is fixed or not?

**Comment by felixSchl** [comment]
I did this morning actually. It's compiling again! Thank you and it's also awesome to see the new warning messages, and I get in fact a warning about too many cases.

**Comment by paf31** [comment]
:+1: Thanks for checking!
