### ISSUE TITLE
core-tests is failing again

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1460]
`transformers` conflict.

Also, this should be a build error, not sure why it's not.

**Comment by paf31** [comment]
At least these need to be updated:

- [ ] free
- [ ] parallel
- [ ] quickcheck

**Comment by garyb** [comment]
Huh. My script is definitely wrong - I get this, which is missing `parallel`:

- [ ] purescript-quickcheck
- [ ] purescript-maps
- [ ] purescript-catenable-lists
- [ ] purescript-free
- [ ] purescript-strongcheck
- [ ] purescript-argonaut-core
- [ ] purescript-argonaut-codecs
- [ ] purescript-argonaut-traversals
- [ ] purescript-argonaut
- [ ] purescript-sets
- [ ] purescript-graphs

**Comment by garyb** [comment]
- [x] [purescript-parallel](https://github.com/purescript/purescript-parallel)
- [ ] [purescript-quickcheck](https://github.com/purescript/purescript-quickcheck)
- [ ] [purescript-monad-eff](https://github.com/purescript/purescript-monad-eff)
- [ ] [purescript-free](https://github.com/purescript/purescript-free)
- [ ] [purescript-in-purescript](https://github.com/purescript/purescript-in-purescript)

**Comment by garyb** [comment]
Fixed now.

**Comment by paf31** [comment]
:100: Thanks very much!
