### ISSUE TITLE
VarBinders are incorrectly desugared into case statements

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1475]

**Comment by paf31** [comment]
I think we figured this out, right?

**Comment by garyb** [comment]
I don't think so - the case desugaring was left unchanged in the end.

If we still want to do anything, I guess the best we can do without overhauling the case stuff entirely is to [change this](https://github.com/purescript/purescript/blob/6fec8a0ba274ffe242c43fd84f62a97eb1bf069c/src/Language/PureScript/Sugar/CaseDeclarations.hs#L97) to use a `takeWhile isVarBinder` to at least knock them off the start of the case.

**Comment by paf31** [comment]
Ah, I meant that the typechecker change should fix the underlying issue. I'm not sure if codegen is so much of a problem.

**Comment by garyb** [comment]
Yes, it is figured out then :smile:
