### ISSUE TITLE
Invalid argument to prettyPrintDeclaration

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript#1476]
The following piece of code compiles: (it's completely dumb; just the minimal example I could find)
```  purs
test :: List Int -> Int
test xs = go xs
    where go Nil         = 0
          go (Cons _ ss) = 1 + go ss
```
Now if I accidentally put the wrong type declaration `test :: List Int` (missing the return type), psc throws the following error (originating from [here](https://github.com/purescript/purescript/blob/a4888d2958447b654f5dc5c08fdd1580132b8550/src/Language/PureScript/Pretty/Values.hs#L87-L94)):
```
psc: Invalid argument to prettyPrintDeclaration
```
which is probably not expected. Note that a lot of (trivial) changes to the code result in 'proper' compiler errors (for example, eta-reducing the `xs` parameter...).

**Comment by garyb** [comment]
Thanks for the report!
