### ISSUE TITLE
Wildcard inferred type messages should have source locations

### ISSUE THREAD

**Issue by jonsterling** [purescript/purescript#1477]
It would be helpful if the `WildcardInferredType` messages were accompanied by source locations.

**Comment by paf31** [comment]
:+1:

**Comment by paf31** [comment]
This seems to work for me in the `TypeWildcards` test from the test suite, at least in the `box-errors` branch. Is there a specific example which is not working?

**Comment by garyb** [comment]
I think maybe I fixed this with #1422, but that was after 0.7.2 which is probably what Jon was using when this occurred.
