### ISSUE TITLE
Regression related to unicode identifiers

### ISSUE THREAD

**Issue by rhurmala** [purescript/purescript#1479]
Compiler generates string literals with octal escapes when record labels contain international characters and at the same time are not valid javascript identifiers. In most parts the compiler uses hexadecimal escapes which do not cause runtime errors.

psc version 0.7.4.1

The following works:
```purescript
import Prelude
import Data.Generic
import Control.Monad.Eff.Console

newtype Asgård = Asgård { "asgård" :: String }

derive instance asgårdGeneric :: Generic Asgård

main = log $ gShow $ Asgård { "asgård": "asgård" }
```
related part from compiled typeclass js
```
return {
  asgård: asgård_1
};
```
This fails however:
```purescript
import Prelude
import Data.Generic
import Control.Monad.Eff.Console

newtype Asgård = Asgård { "asgård-a" :: String }

derive instance asgårdGeneric :: Generic Asgård

main = log $ gShow $ Asgård { "asgård-a": "asgård" }
```
related js
```
return {
  "asg\229rd-a": asgård$minusa_1
};
```
```
pulp run
```
using node 0.12 results in
```
SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

**Comment by michaelficarra** [comment]
Wow, yeah we should stop using octal escapes anywhere we are using them.

**Comment by paf31** [comment]
There seem to be three remaining changes needed to fix this:

- Generic deriving shouldn't use record field names as function argument names.
- Accessors containing invalid characters like `å` here, should be escaped (`foo["asgård"]`)
- The same for object literals (`{ "asgård": bar }`)

Added the `easy` label. Anyone care to take this? If not, I'll work on it.

**Comment by paf31** [comment]
Ok, scratch that, the issue is that the generated JS is not encoded as UTF-8.
