### ISSUE TITLE
Packages Listed in Pursuit Should Build Together

### ISSUE THREAD

**Issue by jasonzoladz** [purescript/purescript#1486]
Ran into conflicting dependencies today -- different versions of purescript-strings -- for purescript-smolder and purescript-jquery.

It might make sense to take a 'stack' approach to Pursuit.  Shouldn't it all build together?

**Comment by paf31** [comment]
I think this should move to the Pursuit issues list.

Pursuit is "just" a collection of package documentation right now, it doesn't verify things build together, or at all. We've discussed various ways to check that things will build together including enforcing an approximation to semver using the type system. Something like Stackage needs curation when package managements is decentralized, so I think such a thing would be better implemented on top of Pursuit, not  with it.

**Comment by paf31** [comment]
(Closing since this is not a compiler issue, we can move to Pursuit issues if necessary)

**Comment by jasonzoladz** [comment]
Thanks for the prompt reply.  I had assumed that Pursuit was, in fact, curated (as it appears that v0.7 is required for inclusion -- e.g., purescript-d3 is absent).

I'd definitely love to see automated builds of curated packages; it might also serve to motivate folks to keep their packages up-to-date with the latest compiler.

**Comment by paf31** [comment]
We _do_ test every core library against every build of the compiler, but we don't have a similar thing for other libraries. Should be possible to put something together with Travis though, I imagine.
