### ISSUE TITLE
Use Megaparsec

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1488]
It looks like it solves a few problems which we've run into in Parsec:

- Lexer implementation is less opaque
- Better support for `Text`
- Better error messages
- Indentation support

**Comment by dalaing** [comment]
Any thoughts on `trifecta` (possibly in combination with `indentation`)?

**Comment by lunaris** [comment]
I was considering asking what the thoughts on using e.g. Alex/Happy were since I've had better performance/errors with them in the past, but not sure on the complexities of parsing PureScript and its indentation/whether this is something the project would consider.

**Comment by AppShipIt** [comment]
Also @gabriel439 strongly recommended Earley.

**Comment by Gabriel439** [comment]
Both trifecta and Earley are improvements over Parsec.  The main advantage of trifecta is the beautiful error messages.  The main advantage of Earley is that you don't need to left-factor your grammar.

**Comment by AppShipIt** [comment]
Would Happy make it easier to maintain an official grammar definition per purescript/roadmap#50?

**Comment by Gabriel439** [comment]
I strongly advise against using `happy`, for three reasons:

* Happy parsers are not first class, so you can't configure your parser
* Happy only generates a parser for the top-level expression.  You don't get parsers for sub-expressions
* You can't reuse the Happy parser within other Happy parsers, or more generally they are not composable

All three of these issues bit me while working on `morte` and `annah`

I recommend either `Earley` or perhaps `BNFC-meta` if you want a parser specification resembling a grammar definition.  An Earley parser reads almost exactly like an ABNF spec anyway and the `BNFC-meta` package actually generates a first-class set of parsers directly from an ABNF spec.

**Comment by AppShipIt** [comment]
> An Earley parser reads almost exactly like an ABNF spec

Thanks! I thought I recalled reading that in your writeup but couldn't find it again.

**Comment by AppShipIt** [comment]
Read on [reddit](https://www.reddit.com/r/haskell/comments/33l9cr/ann_earley_parsing_library/) about how Earley resolves ambiguities which @paf31 mentioned as a high priority. I'm vaguely interested in trying it.

**Comment by paf31** [comment]
Ambiguous parses are reduced quite a bit in the new parser, since the `AnonymousArgument` constructor unified a few different productions. My main concern with parsing right now is the speed, although I have some ideas to help there.

**Comment by garyb** [comment]
Isn't the typechecker still where the compiler spends 90% of the time? I thought that was the biggest performance issue last we benchmarked. That was pre-slow-warming fix though.

**Comment by paf31** [comment]
I'm not sure, but certainly parsing plays a big part in the rebuild time.

**Comment by AppShipIt** [comment]
I came back to this specifically because of #2051. I feel like a parser that _looks_ closer to a formal grammar might help route out these issues.

**Comment by paf31** [comment]
I'd say the current implementation is _quite_ close to a grammar description.

**Comment by AppShipIt** [comment]
I'm the least knowledgeable commenter about parsers so I'll agree 😊

**Comment by AppShipIt** [comment]
Looks like Megaparsec would fix #2115.

**Comment by hdgarrood** [comment]
Yep, although it's pretty easy to fix that on its own, and it's a bad enough bug that I'm working on doing that right now ;)

**Comment by AppShipIt** [comment]
Haha I swear you have a team of coders working for you 👏

**Comment by kRITZCREEK** [comment]
So I did a bit of profiling yesterday. I collected data for three repositories:

- slamdata
- purescript-halogen
- pscid

I've never done any profiling of haskell code before, so I just thought I'd put out the data I found so that maybe someone with more experience can see some easy performance gains.

One thing I realized (which is why I'm posting this data in this issue) is that lots of allocations in the earlier stages are list constructors (easy to see in the `*-hy.pdf` files). I think this is caused by our extensive usage of String inside the parser & lexer, so using a Text based parser sounds like an easy win. I'd like to start rewriting a few of our parsers in trifecta to try this out. If someone wants to reproduce this data I can put up step by step instructions for what I did :)

## slamdata/slamdata:

```
	Tue Aug 16 23:15 2016 Time and Allocation Profiling Report  (Final)

	   psc +RTS -N -p -hy -RTS src/**/*.purs test/**/*.purs bower_components/purescript-*/src/**/*.purs

	total time  =      223.05 secs   (223053 ticks @ 1000 us, 1 processor)
	total alloc = 180,593,225,312 bytes  (excludes profiling overheads)

COST CENTRE                 MODULE                                  %time %alloc

==                          Language.PureScript.Names                16.7    0.0
compare                     Language.PureScript.Names                 4.8    0.0
>>=.\.\                     Control.Monad.Logger                      4.6    1.5
>>=                         Control.Monad.Supply                      4.3    7.3
return                      Language.PureScript.Make                  3.1    6.0
>>=.\                       Control.Monad.Logger                      3.0    0.0
warnDuplicateRefs.dupeRefs  Language.PureScript.Sugar.Names.Common    2.4    5.4
>>=                         Language.PureScript.Make                  2.2    4.4
fmap.\                      Control.Monad.Logger                      1.7    2.4
parseToken                  Language.PureScript.Parser.Lexer          1.6    6.6
everywhereOnTypesM.go       Language.PureScript.Types                 1.6    2.0
everywhereOnJS.go           Language.PureScript.CodeGen.JS.AST        1.6    5.1
>>                          Control.Monad.Supply                      1.4    2.5
return                      Control.Monad.Supply                      1.0    1.3
withErrorMessageHint        Language.PureScript.TypeChecker.Monad     1.0    0.7
resolveExports.extract.go   Language.PureScript.Sugar.Names.Exports   1.0    2.1
resolveImport.importAll     Language.PureScript.Sugar.Names.Imports   0.8    1.4
*>                          Control.Monad.Supply                      0.8    1.1
everywhereOnTypes.go        Language.PureScript.Types                 0.8    1.1
resolveImport.importRef     Language.PureScript.Sugar.Names.Imports   0.8    1.4
>>=                         Control.Monad.Logger                      0.6    2.9
resolveExports.extract.go.\ Language.PureScript.Sugar.Names.Exports   0.5    1.1
prettyPrintJS'.matchValue   Language.PureScript.Pretty.JS             0.3    1.1
rebuildModule               Language.PureScript.Make                  0.3    2.3
withIndent                  Language.PureScript.Pretty.Common         0.3    1.3
makeBindingGroupVisible.\   Language.PureScript.TypeChecker.Monad     0.3    1.1
intercalate                 Language.PureScript.Pretty.Common         0.2    1.1
```

[slamdata.prof](https://www.dropbox.com/s/66jprt99wr2jolw/slamdata.prof?dl=0)
[slamdata-h.pdf](https://github.com/purescript/purescript/files/422200/slamdata-h.pdf)
[slamdata-hy.pdf](https://github.com/purescript/purescript/files/422209/slamdata-hy.pdf)

## slamdata/purescript-halogen:

```
	Wed Aug 17 00:55 2016 Time and Allocation Profiling Report  (Final)

	   psc +RTS -N -p -h -RTS src/**/*.purs bower_components/purescript-*/src/**/*.purs

	total time  =       26.50 secs   (26496 ticks @ 1000 us, 1 processor)
	total alloc = 28,601,136,056 bytes  (excludes profiling overheads)

COST CENTRE                MODULE                                  %time %alloc

>>=                        Control.Monad.Supply                      5.3    7.0
>>=.\.\                    Control.Monad.Logger                      4.5    1.5
==                         Language.PureScript.Names                 4.4    0.0
return                     Language.PureScript.Make                  3.7    5.4
compare                    Language.PureScript.Names                 3.5    0.0
>>=.\                      Control.Monad.Logger                      3.4    0.0
parseToken                 Language.PureScript.Parser.Lexer          3.1   10.4
fmap.\                     Control.Monad.Logger                      2.5    2.7
everywhereOnJS.go          Language.PureScript.CodeGen.JS.AST        2.3    5.9
>>=                        Language.PureScript.Make                  2.3    3.9
everywhereOnTypesM.go      Language.PureScript.Types                 1.9    2.0
warnDuplicateRefs.dupeRefs Language.PureScript.Sugar.Names.Common    1.7    2.7
>>                         Control.Monad.Supply                      1.4    1.9
withErrorMessageHint       Language.PureScript.TypeChecker.Monad     1.3    0.8
return                     Control.Monad.Supply                      1.3    1.1
token                      Language.PureScript.Parser.Lexer          1.0    0.7
fmap                       Control.Monad.Supply                      1.0    1.0
resolveExports.extract.go  Language.PureScript.Sugar.Names.Exports   0.7    1.7
rebuildModule              Language.PureScript.Make                  0.7    4.2
>>=                        Control.Monad.Logger                      0.7    2.7
prettyPrintJS'.matchValue  Language.PureScript.Pretty.JS             0.5    1.4
parseComment.lineComment   Language.PureScript.Parser.Lexer          0.5    1.8
withIndent                 Language.PureScript.Pretty.Common         0.5    1.3
```

[purescript-halogen.prof](https://www.dropbox.com/s/c6k4xjpmg7eoceo/purescript-halogen.prof?dl=0)
[purescript-halogen-h.pdf](https://github.com/purescript/purescript/files/422207/purescript-halogen-h.pdf)
[purescript-halogen-hy.pdf](https://github.com/purescript/purescript/files/422208/purescript-halogen-hy.pdf)

## kritzcreek/pscid:

```
	Wed Aug 17 00:47 2016 Time and Allocation Profiling Report  (Final)

	   psc +RTS -N -p -RTS src/**/*.purs bower_components/purescript-*/src/**/*.purs

	total time  =       25.57 secs   (25573 ticks @ 1000 us, 1 processor)
	total alloc = 26,278,440,280 bytes  (excludes profiling overheads)

COST CENTRE                MODULE                                  %time %alloc

>>=                        Control.Monad.Supply                      5.1    6.8
>>=.\.\                    Control.Monad.Logger                      4.8    1.5
==                         Language.PureScript.Names                 4.6    0.0
>>=.\                      Control.Monad.Logger                      3.6    0.0
return                     Language.PureScript.Make                  3.4    5.4
compare                    Language.PureScript.Names                 3.3    0.0
everywhereOnJS.go          Language.PureScript.CodeGen.JS.AST        2.9    7.2
parseToken                 Language.PureScript.Parser.Lexer          2.9    9.9
fmap.\                     Control.Monad.Logger                      2.7    3.0
>>=                        Language.PureScript.Make                  2.4    3.9
everywhereOnTypesM.go      Language.PureScript.Types                 2.1    2.1
withErrorMessageHint       Language.PureScript.TypeChecker.Monad     1.4    0.9
>>                         Control.Monad.Supply                      1.3    1.8
return                     Control.Monad.Supply                      1.2    1.1
fmap                       Control.Monad.Supply                      1.2    1.2
warnDuplicateRefs.dupeRefs Language.PureScript.Sugar.Names.Common    1.1    1.6
fmap                       Language.PureScript.Make                  1.0    0.7
token                      Language.PureScript.Parser.Lexer          1.0    0.8
resolveExports.extract.go  Language.PureScript.Sugar.Names.Exports   1.0    1.6
>>=                        Control.Monad.Logger                      0.7    2.7
prettyPrintJS'.matchValue  Language.PureScript.Pretty.JS             0.6    1.6
rebuildModule              Language.PureScript.Make                  0.6    3.3
parseComment.lineComment   Language.PureScript.Parser.Lexer          0.5    1.9
withIndent                 Language.PureScript.Pretty.Common         0.4    1.6
intercalate                Language.PureScript.Pretty.Common         0.3    1.2
```

[pscid.prof](https://www.dropbox.com/s/oz2xk9ppxycfqo1/pscid.prof?dl=0)
[pscid-h.pdf](https://github.com/purescript/purescript/files/422205/pscid-h.pdf)
[pscid-hy.pdf](https://github.com/purescript/purescript/files/422206/pscid-hy.pdf)
