### ISSUE TITLE
Local Imports

### ISSUE THREAD

**Issue by spion** [purescript/purescript#1492]
I'm not sure what the effort for this might be (or if there are any major problems with the idea), but it would be neat if qualified imports could be brought into scope locally as follows

```purescript
import qualified React.DOM as DOM
import qualified React.DOM.Props as Props
...

counter = createClass $ spec 0 \ctx -> do
  val <- readState ctx
  with (DOM, Props) $ return $ p [ className "Counter"
                                 , onClick (incrementCounter ctx)
                                 ]
                                 [ text (show val)
                                 , text " Click me to increment!"
                                 ]

```

This would be especially useful for operators - the following is a Haskell example but I'm sure the improvement will be just as nice in PureScript

```Haskell
import qualified Text.XML.Cursor as X
import Text.XML.Cursor ((>=>))

getTimestamps = X.descendant >=> X.laxElement "timestamp" >=> X.child >=> X.content
```

vs single import, no global operators:

```Haskell
import qualified Text.XML.Cursor as XMLCursor

getTimestamps = with XMLCursor $ descendant >=> laxElement "timestamp" >=> child >=> content
```

(Of course if there are conflicting imports the same errors would be generated as with global imports)

**Comment by paf31** [comment]
I think @garyb could probably give the best answer with regards to feasibility, but I like the idea in theory. I've thought about something like let/do-scoped imports before too:

```purescript
counter = createClass $ spec 0 \ctx -> do
  import qualified React.DOM as DOM
  import qualified React.DOM.Props as Props
  val <- readState ctx
  with (DOM, Props) $ return $ p [ className "Counter"
               , onClick (incrementCounter ctx)
               ]
               [ text (show val)
               , text " Click me to increment!"
               ]
``` 

but that's a bit unpleasant by comparison.

**Comment by user471** [comment]
@spion Why is it better than ```import qualified React.DOM```? Only to prevent possible conflicting imports?

**Comment by spion** [comment]
@user471 thats part of it, yes. 

Another reason I had in mind is that qualified imports make code easier to read. By itself `import React.DOM` isn't too bad (and the imported functions are fairly well known too if we know the DOM elements) but when reading code that has a lots of those it starts to become unclear where a function comes from without relying on tooling (which is not always available e.g. github) or knowing the imported libraries well (which is not the case when getting familiar with a project). Restricting both the number and the scope of unqualified imports should help with that.

**Comment by user471** [comment]
@spion Personally, I would prefer something like this
```
import React.DOM for (foo, bar)

foo = p [text "Foo"]
   ...
bar = p [text "Bar"]
```
```with (DOM, Props)``` within code looks too noisy

**Comment by spion** [comment]
That would make it harder to move, delete and rename functions. It decreases locality of information which makes it harder, not easier to read functions: I'm not interested about where imports are used at the import site but rather in what imports are used at the use site. In terms of usability it has the wrong kind of information (where does "someFn" come from? well, what are all imports for `functionImReading`? to answer that, I scroll up to the list of imports and start hunting for those that contain `myFunction` in the `for` list)

Its slightly better than unqualified imports though.

**Comment by user471** [comment]
>to answer that, I scroll up to the list of imports 

Someone can use such code
```
import React.DOM
import React.DOM.Props
Import Data.Something
Import Control.Something

foo = p [text "Foo"]
bar = p [text "Bar"]
```
So, if you don't know where does "someFn" come from, you always need to scroll up to the imports list and start to figure out what module could contain "someFn".

```
import React.DOM for (foo,bar)
import React.DOM.Props for (boo,bar)
Import Data.Something
Import Control.Something
```
for part is a hint.

**Comment by LiamGoodacre** [comment]
:+1: for local imports.

One concern I have is that using a local import in a function that leaks imported concepts can make it impossible to write its type.

Unless you can also somehow import in the type and have that scoped over the implementation.
Something like these (possibly silly) examples:

~~~purescript
one :: import Data.Unfoldable in forall f a. (Unfoldable f) => f a
one = singleton
~~~

~~~purescript
bar :: import Data.Unfoldable
              Data.Monoid in
       forall f m. (Unfoldable f, Monoid m) => f m
bar = singleton mempty
~~~

~~~purescript
instance foldableFoo :: import Data.Foldable in Foldable Foo where
  foldMap ...
~~~

Another alternative is import scoped blocks:

~~~purescript
using import Data.Unfoldable

  one :: forall f a. (Unfoldable f) => f a
  one = singleton

  bar :: import Data.Monoid in forall f m. (Unfoldable f, Monoid m) => f m
  bar = singleton mempty


using import Data.Foldable

  instance foldableFoo :: Foldable Foo where
    foldMap ...
~~~

In these specific example cases I suspect it'd be straight forward to implement by just hoisting them up to the normal import section?

**Comment by robotlolita** [comment]
Local imports are a pretty great idea :+1: 

I'd probably go with something like:

```purs
import qualified React.DOM as DOM
import qualified React.DOM.Props as Props
...

counter = createClass $ spec 0 \ctx -> do
  val <- readState ctx
  using (DOM, Props) in
    return $ p [ className "Counter"
               , onClick (incrementCounter ctx)
               ]
               [ text (show val)
               , text " Click me to increment!"
               ]
```

Where:

```purs
usingExpr ::= "using" namespaceList "in" expr
namespaceList ::= namespace | "(" namespace ("," namespace)* ")"
namespace ::= identifier refinement*
refinement ::= "only" bindingList | "hiding" bindingList
bindingList ::= identifier | "(" identifier ("," identifier)* ")"
```

Given that, it might be possible to just expand the bindings in the `using` expression before type checking/linking, but I'm not familiar with PureScript's compiler design — still, it sounds like it should be possible to do this at the same time imports are being resolved.

**Comment by jdegoes** [comment]
> I'd probably go with something like:

:+1: 

The ship has sailed, and it's not really worth the hassle right now, but I've always thought I'd prefer expression-oriented import statements, such as the `using` above.

**Comment by paf31** [comment]
Closing, since this hasn't been discussed in a year, and I think we can do something simpler: if you have a module where reuse of this kind is common, then declare its exports in a record and bring them into scope as follows:

```purescript
case myModule of { foo, bar, baz } -> ...
```

**Comment by sleexyz** [comment]
@paf31 Is there a way to do Haskell-style wildcard imports instead of explicit field punning?
Something like:
```purescript
myModule = 
{ foo = "hello"
, bar = "world"
}

use :: String
use = 
  let {..} = myModule
  in foo <> bar
```

I would say field punning, i.e. local *explicit* imports,  does not address the true motivation to want local imports, which is to **save keystrokes** while preventing namespace clashes everywhere in a file. That can only only be done with some blacklist-style scope pollution mechanism, i.e. Haskell's record wildcards or OCaml's local opens.

Having local open imports are really useful for using DSLs *while keeping lexical pollution isolated to some local scope*. For example, with open imports, I wouldn't need to explicitly type out every single HTML tag I would want use from some HTML DSL; I'd just *use the DSL*.

---

Record Wildcards would be nice... :smile:

...but local open imports for *modules* would be even nicer! :heart_eyes:  <sub>(since almost all things are exported as modules, not records :p)</sub>

**Comment by paf31** [comment]
Possible issue: what is the type of `\x -> let {..} = x in 1`?

**Comment by LiamGoodacre** [comment]
I don't think it makes sense for records.
To build on @paf31 's issue:

What would be the type of:
```purescript
\x -> let {..} = x in z
```
Would it be `forall r t. Record (z :: t | r) -> t`, or `z` not in scope, etc.

How about:
```purescript
\x y -> let {..} = x
            {..} = y
        in z
```
Without an explicit type annotation, we can't know if `z` is coming from `x`, `y`, or from outside.

**Comment by sleexyz** [comment]
What about *type-driven* behavior of the `{..}`?

i.e. a record wildcard import puts into scope *only* the fields that can be determined by the inferred type of the record.

So `\x -> let {..} = x in z` should return a `not in scope` error, since the field `z` cannot be inferred by `x` in the lambda abstraction.

For example:

```purescript
type Foo =  { z :: Int }
...

:t \x -> let {..} = x in z 
-- Not in scope: z

:t \(x :: Foo) -> let {..} = x in z 
Foo -> Int

:t \x -> let {..} = (x :: Foo) in z 
Foo -> Int
```
