### ISSUE TITLE
psc can not compile source files contains multibyte sequence charactor on Windows

### ISSUE THREAD

**Issue by senju** [purescript/purescript#1496]
psc can't compile this file on Windows System.
```haskell
module Main where

import Control.Monad.Eff.Console

main = do
  log "Hello λ→ world!"

-- '→' is multibyte sequence \u2192.
```

Error message:
```
Main.purs: hGetContents: invalid argument (invalid byte sequence)
```
Because System.IO.readFile convert byte sequence from system's default encoding. And unlike Linux or mac, default encoding on Windows is not UTF-8, but CPxxx.
So psc should not call readFile, use openFile and hSetEncoding to force encoding set to UTF-8.

**Comment by paf31** [comment]
Thanks for the report!

**Comment by garyb** [comment]
I've had some strange problems with this. Sometimes it works fine, other times it does not. SlamData uses some unicode characters, and if I run `bower` in the terminal before compiling it fails, but in a fresh terminal it succeeds.

Forcing UTF-8 sounds good to me though.

**Comment by senju** [comment]
I fixed psc and tests/Main.hs only.
But I find psc-doc has same problem. So this issue should not closed yet.
