### ISSUE TITLE
Conflicting imports

### ISSUE THREAD

**Issue by ais04** [purescript/purescript#1497]
I can run this code in Haskell
```
module Foo where
test = 1

module Bar where
test = 2

module Main where
import Foo
import Bar
main = print "test"
```

But PureScript compiler return an error

```Conflicting imports for test from modules Bar and Foo```

Is this a bug?

**Comment by zudov** [comment]
But they are conflicting, aren't they?

IIRC, Haskell simply doesn't bog you with that conflict until you actually refer to conflicting name. Personally, I like purescript's behavior more.

**Comment by zudov** [comment]
The reason why I prefer purescript's behavior is that it would force me to resolve all upcoming conflicts earlier.

When I say "import Foo" psc would tell me "It conflicts, you can't just import it, please resolve the names, either hide some imports or make it a qualified import".

But in case of haskell, I would import it and forget about it, and in the future I'll stumble on conflicting import and would have to go back and resolve that conflict, and then again and again until I decide "Ok, that's enough, let it be a qualified import".

**Comment by ais04** [comment]
No, they are not. No one use test, so there isn't any conflict.

>Personally, I like purescript's behavior more.

Why do you need to know about ```test``` existence if you don't use it?
It should be warning but I don't think it should be enabled by default.

**Comment by zudov** [comment]
Here is a made up example, of how it can bite you in haskell.

I decide that I need to use some modules:
```haskell
import Data.Set
import Data.Map
```
There are some *potential* conflicts but compiler doesn't bring them up. I go further and write a bunch of code which using some non-conflicting names from those modules, e.g. `Map`, `Set`, `keys`, `elems`, `member`, `foldWithKey`.

The code is written and compiles fine.

Now I decide to use some conflicting name, e.g. `fromList`, and here we come I now need to resolve all those conflicting imports either with a bunch of `hiding` or by specifying names explicitly or by making imports qualified.

I much prefer an `import qualified` solution, BUT now I would have to update all my code to use qualified names. It would be much nicer if compiler just told me about that problem earlier.

**Comment by zudov** [comment]
I don't insist on compiler error, a warning should also be fine.

**Comment by ais04** [comment]
> I would have to update all my code to use qualified names

Just add 
```
import Data.Set
import Data.Map
import qualified Data.Map as M
```
and use ```M.fromList```

**Comment by zudov** [comment]
@ais04 Heh. Yes, you are right.

**Comment by garyb** [comment]
It's not a bug, although when I first saw this proposal I was against it... however, I think now it probably is a good idea, as it helps prevent an issue we encountered recently where introducing a new value in a module broke code elsewhere due to a collision in names but not in usage. I think it should be reasonably easy to handle too.
