### ISSUE TITLE
Qualified pseudo-modules don't merge with actual modules

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1499]
This is kinda weird, but I think the current behaviour is incorrect:

```
module A where
  a = 1

module X where
  x = 1

module Test where

  import qualified X as A

  thing = A.a -- fails
```

This example makes it look pretty odd, but when `a` is `DOM` for instance, this can happen easily. e.g. slamdata/purescript-browserfeatures#10

**Comment by garyb** [comment]
@paf31 are we going to make the demand that all modules need importing as per the idea to improve recompilations? I can't remember whether that was a requirement in the end, as we'd also talked about storing dependency info in the externs which might be good enough.

If we are making importing required, this issue is redundant.

**Comment by paf31** [comment]
I would like to implement that. I didn't get any very good performance improvement when I tried it, but that was because we still had to lex every file. It might be useful for editors too, and things like `psc-ide`, to be able to quickly parse a list of all imports.
