### ISSUE TITLE
Revert FFI?

### ISSUE THREAD

**Issue by jasonzoladz** [purescript/purescript#1500]
I understand the rationale behind making FFI harder and, at the release of v0.7, I thought I liked the more restrictive approach.

But I find myself increasingly using Fay for small projects.  (So many Purescript wrappers are incomplete; and when wrapping a function or two, the current solution feels heavy.)  So, my revealed preference is for a more convenient FFI.

I raise it just in case others find the same.

**Comment by paf31** [comment]
Why do you say the new FFI is harder? I consider it to be simpler. I get to use JS tools because the foreign code is actually a JS file, and I don't have to think about how to escape it in a string literal.

Reverting FFI changes would involve reverting other changes which have happened since, so it's a :-1: from me, but I'm interested to hear specific complaints about the new FFI.

**Comment by jasonzoladz** [comment]
("Revert" was a poor word choice.  I really I meant "old inline FFI + new
FFI".)

The new FFI isn't harder for bigger wrapping jobs.  In fact, it's really
nice for bigger jobs.

Yet, if you are using a wrapper library that's missing a function or two,
it's needlessly time consuming.  (Regarding escaping the string literal: I
think that even the old way of doing inline FFI could've been improved.  (
*see*, *e.g.*, Fay's inline FFI))

I understand that making it difficult has benefits (e.g., more "pure"
code), but until the libraries mature, I'm not sure that the benefits
outweigh the hassle.  I raised it just in case others are experiencing the
same.

**Comment by paf31** [comment]
Have you seen `purescript-easy-ffi`? I find it useful for the sorts of things you're describing.

**Comment by jasonzoladz** [comment]
Thanks for the referral!  It didn't occur to me that `easy-ffi` was still available after v0.7.

**Comment by paf31** [comment]
I'm not sure if it needs updating, but it should be possible to update it, I don't think the new FFI prevents it from working.

**Comment by jasonzoladz** [comment]
Perfect.  Thanks!
