### ISSUE TITLE
make "qualified" keyword optional

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#1502]
Is there a reason why the `qualified` keyword in qualified imports is required? I don't see any reason why we can't write

```purs
import qualified A.B.C as C
```

as

```purs
import A.B.C as C
```

**Comment by paf31** [comment]
I guess it depends whether we want to imitate Haskell's imports or not. We already deviate from Haskell in other ways, so :+1: from me.

**Comment by michaelficarra** [comment]
By the way, I suggest this because I've seen some odd alignment formatting like

```purs
import           A
import           B
import qualified C.D as D
```

and I immediately wanted to see less of that.

**Comment by LiamGoodacre** [comment]
:+1:

Whilst this is being considered, what do you think about qualification following a similar syntax to `let`:

~~~purescript
import M = Data.Map
import S = Data.Set
import L = Data.List
import     Foldable (foldMap, fold)
~~~

Although this would break most existing code and it's probably not worth it :P
Just putting it out there as an option.

It's nice in the context of the local imports idea:

~~~purescript
foo :: forall m. (Monoid m) => Array m -> Tuple (Array m) m
foo xs =
  let import F = Data.Foldable
             r = F.fold xs
   in Tuple xs r
~~~

**Comment by zudov** [comment]
:+1:

**Comment by user471** [comment]
>what do you think about qualification following a similar syntax to let
What if module could be some sort of first-class citizen. So you don't really need new syntax
```
f :: {sum::f a -> a, ...}
f = Data.Foldable
foo xs =  let f = Data.Foldable in f.sum xs
foo xs = f.sum xs where f = Data.Foldable
```

**Comment by garyb** [comment]
I've done some experiment with first class modules represented as records. I think there's something there, but haven't quite figured out how to resolve the issues around classes (well, instances more specifically I guess). First class modules is also relevant to the discussion on local imports, as then the proposed `using` / `with` thing could be extended to any record, not just modules.

**Comment by garyb** [comment]
Oh, :+1: for dropping `qualified` though.

**Comment by michaelficarra** [comment]
Let's move the tangential conversation to another issue, please. I want to keep this thread focused on making `qualified` optional so that we can get it done ASAP.

**Comment by jutaro** [comment]
Make "qualified" keyword optional is fine for me, but please do not ban it completely!

**Comment by michaelficarra** [comment]
@jutaro No plans on doing that. We don't want to unnecessarily break compat with existing programs.

**Comment by garyb** [comment]
Agreed, although we will probably remove it in the long run if it stays optional (warn for the life of a 0.x version, remove in the next). Although breaking stuff is bad, accumulating unused cruft in the language pre-1.0 doesn't seem very sensible (in my opinion anyway).
