### ISSUE TITLE
Allow qualified import with hiding

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1507]
``` purescript
import Foo hiding (baz) as X
```

I think putting the `hiding` before the `as` is clearer than having `hiding` follow it, considering the effect this should have. Forming it this way also makes it clear why you can't combine selective imports with `hiding`, as it makes `hiding` a modifer of the selection.

**Comment by LiamGoodacre** [comment]
:+1:

**Comment by paf31** [comment]
Should this be bumped to 0.9?

**Comment by garyb** [comment]
I'd like to sort it out soon actually, there are already cases where I would have liked to do this.
