### ISSUE TITLE
Allow importing of types without the use of () if no constructors are required

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1508]
Currently the behaviour of an import for a proper name is dictated by syntax, but that's basically due to laziness on my part. Also, importing `X()` is a bit pointless, especially in the case of synonyms where `()` can only ever be empty.

**Comment by michaelficarra** [comment]
I don't like it. I regularly use the `()` to visually distinguish imported types from imported type classes when reading import declarations. I know this would be optional, but it's about the reader here, not the author.

**Comment by natefaubion** [comment]
+1 This is something I accidentally hit frequently, especially with synonyms.

I think if you wanted to disambiguate, you could do better than an inadvertent sigil, maybe optional `type`, `class`, or `data` keywords to explicitly pull from the different namespaces?

```purescript
import Bar (class IsBar, type BarC, data Bar(..))
```

**Comment by paf31** [comment]
If you consider that type classes get desugared into type synonyms anyway, this approach makes more sense. I still like having a visual cue though, so I wouldn't be upset if things stayed the way they are now.

**Comment by garyb** [comment]
Good points from everyone - the visual distinction is definitely a benefit that I wasn't thinking of, it was more the case of the non-obviousness that @natefaubion mentioned. Using `class IsBar` stye imports would definitely be good for that. We already have the `module` keyword to distinguish between module proper names and everything else, so there's a precedent for doing things this way.

I think I'd prefer to do without type/data/newtype keywords though, and just assume any non-keyworded proper name is a type. 

If we are going to do it I don't think it should be optional though... I guess ideally we'd make it optional until the next 0.X release and warn whenever a class does not have the `class` keyword, and then drop it after that?

**Comment by garyb** [comment]
By "next 0.X release" I mean, if we do it in the current milestone, we'd keep it optional-with-warning throughout 0.8 and drop at 0.9.

**Comment by paf31** [comment]
> By "next 0.X release" I mean, if we do it in the current milestone, we'd keep it optional-with-warning throughout 0.8 and drop at 0.9.

I'd be fine with that if we can find a good syntax. `class Show` sounds fine to me, but do we want anything like `class Show(..)` meaning "the class and all its members" as well?

Another argument for clearer syntax to disambiguate classes is that it makes it easier for tool-writers to parse imports without knowing about what's in scope.

**Comment by jdegoes** [comment]
I actually _like_ the fact that classes are de-sugared into type synonyms. In fact, it'd be nice if we could use classes names as if they _were_ synonyms. Then in libraries like quickcheck, for example, you could dispense with the `Arbitrary` / `Gen` distinction, and probably do lots of other interesting things.

Albeit this is more related to module / record unification than anything in this ticket. :smile:

**Comment by garyb** [comment]
I'm not really a fan of the "class and all its members" import - since we don't have default members currently what that imports is perhaps not all that useful, given that we usually have very small classes and then a bunch of functions implemented in terms of the core class functions. Especially as it currently wouldn't export operator-versions of the class members either.

**Comment by paf31** [comment]
@jdegoes If we had a do-over, I'd replace data types with polymorphic variants, and classes with implicit values, and then module exports lists _would_ be record types, but it's a bit late for that... :smile:

**Comment by garyb** [comment]
I thought you tried that? We had a `variants` branch from like December 2013 hanging around for a loong time :wink:

**Comment by paf31** [comment]
Yeah, it worked, but had the unfortunate restriction that every constructor had to take exactly one argument. Which is symmetric with products of course, but not how most users like to use sum types...

From a module point of view, it'd be very nice though, and correspond well to what we actually codegen.

**Comment by jdegoes** [comment]
> If we had a do-over, I'd replace data types with polymorphic variants, and classes with implicit values, and then module exports lists would be record types, but it's a bit late for that... :smile:

Not until 1.0! :smiling_imp: 

I also think polymorphic variants are probably superior. Haskell's sum and product types are not (anti?)symmetric.

> Yeah, it worked, but had the unfortunate restriction that every constructor had to take exactly one argument. Which is symmetric with products of course, but not how most users like to use sum types...

That doesn't seem fatal -- tuples or something, right?

**Comment by paf31** [comment]
> That doesn't seem fatal -- tuples or something, right?

No it's not, it's just irritating when you want to use `Nothing` and have to use `Nothing unit` or `Nothing {}`.

Zero arguments is the really bothersome case for this reason, which is why I considered having zero-or-one arguments with a type-level `Maybe` to represent that, but it got even uglier.

**Comment by jdegoes** [comment]
> No it's not, it's just irritating when you want to use Nothing and have to use Nothing unit or Nothing {}.

I don't think that's so bad, especially since you can do:

```purescript
nothing = Nothing unit
```

**Comment by paf31** [comment]
Well I'd love to replace data constructors with polymorphic variants and see imports simplified a bit. But here is one other issue: rank N types and polymorphic variants might end up needing impredicativity, which I don't particularly want. In fact, in the new new typechecker, I was actually planning on restricting record labels to be typed with monotypes, not polymorphic types, to avoid these sorts of issues.

**Comment by paf31** [comment]
The _other_ problem with variants is that they don't really represent what happens in codegen: a data constructor gets its own prototype right now. So we'd need to change codegen so that all variants with the same tag got the same representation, which probably means going back to the old, slower tag-and-value-record approach.

**Comment by paf31** [comment]
Oh, one more: exhaustivity checking is harder since you have to consult the type information, not just the syntactic information in the binders themselves.

**Comment by paf31** [comment]
What about just sharing a namespace for types and type classes in 0.8? Then you'd have e.g.

```purescript
import Prelude (Show, show, Ordering)
import Data.Maybe (Maybe(..))
```

i.e. parens are only used on a type, and only used when importing constructors.

**Comment by garyb** [comment]
That'd work as they do already share a namespace (in that you're not allowed to define classes and types with the same name in a module), but I think my preference is for switching to `class X` imports still as it makes it more obvious what you're getting.
