### ISSUE TITLE
Require modules to be imported even if their members are being referenced fully qualified

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1511]
(From a discussion on IRC).

The motivation is for enabling better tooling, and with some additional changes (require imports at the top, disallow multiple modules per file) potential faster recompilation times.

One thing that would need figuring out: how would it actually work, since we're dropping the `qualified` modifier, so it wouldn't be `import qualified X.Y` as it is in Haskell. Change `import X.Y` to not implicitly import anything and require `import X.Y (..)` as mentioned in #1509? Require `import X.Y as X.Y`?

The three of us who talked about it (@paf31, @natefaubion) don't feel particularly strongly about it, but the pros do seem to slightly outweigh the cons, so, discuss:

**Comment by paf31** [comment]
I've confirmed that the rebuild slowness in the `incremental` branch is due to having to parse every module fully before building.

**Comment by paf31** [comment]
I'd very much like to see this added to the "break before 0.8" list, if it can give a significant performance increase for incremental builds.

A simple way to verify it would be to truncate the module at the last line beginning with `import`, then parse as usual, figure out module dependencies, and reparse the whole module if we determine we need to rebuild it. Of course, for a final version, this won't be good enough, but it would be fine to test the idea out.

**Comment by garyb** [comment]
Fine by me. Wishful thinking, but I'd like us to maybe not break anything in 0.9 (aside from things we mark as deprecated - if we do the suggested `class` imports, for instance, and dropping the `qualified` modifier) if we can manage it - so hopefully get operator aliases in 0.8 too... 

Did you have any thoughts on the "how to qualify as itself" question I mentioned in the issue?

**Comment by paf31** [comment]
I had a quick go at this in the `1511` branch. The time to recompile Halogen is now 0.9s on my machine. The main obstacle seems to be lexing, since we need to lex all the way to the end of the file before we can start parsing. Ideally, we need some way of telling when the imports have finished in the lexer, which doesn't seem simple.

Ironically, if we didn't split the lexer out, this would be faster :)

Another approach might be to parallelize the reading of module headers.

**Comment by AppShipIt** [comment]
Just read this because @paf31 referenced it in mine. @garyb You asked for this not to happen right? In particular to facilitate debugging. Perhaps there's a solution to both simultaneously?

**Comment by garyb** [comment]
Well, I guess I'm arguing for an edge case. The project prelude approach will mostly help, as would using something slightly more advanced than syntax highlighting in my editor, potentially. It's just a pet peeve :wink:

**Comment by hdgarrood** [comment]
I would actually be quite pleased if this were to happen (sorry @garyb ;). I think it can be quite handy to be able to have a vague idea of what a module does (or does not do) just by looking quickly over the imports.

**Comment by AppShipIt** [comment]
> as would using something slightly more advanced than syntax highlighting in my editor, potentially.

I think that's kRITZCREEK/psc-ide#72. Do they need dupilcated here?

**Comment by kRITZCREEK** [comment]
@AppShipIt  I actually started moving issues over today. I'd like to only move the issues that are sufficiently specified to not contribute to the "evergrowing issues" issue :smile:

As for the managing imports one I'd still like to debate how far psc-ide's scope should go. Should it directly modify the sourcefile (take over the import section) or should it make suggestions like the compiler warnings for imports?

**Comment by AppShipIt** [comment]
I think unequivocally the latter? The compiler shouldn't be responsible for any stylistic conventions such which line to insert an import.

**Comment by garyb** [comment]
I wasn't really making a comment on `psc-ide`, I still somewhat shamefully haven't tried it, I just meant I'm sure there's some kind of option where tooling might be able to help.

**Comment by AppShipIt** [comment]
Just tracking it because I remember asking @kRITZCREEK about it on video too.
