### ISSUE TITLE
Use ANSI color codes to highlight error messages

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1517]
Any thoughts on this? We could highlight types and values to subtly distinguish keywords and syntax.

**Comment by michaelficarra** [comment]
I think this could work if it's not overdone. Would you be open to a PR for this or should I wait?

**Comment by paf31** [comment]
Definitely open to a PR!

**Comment by garyb** [comment]
> I think this could work if it's not overdone.

Agreed! I don't think it would need much, just something to help break up the messages in addition to the spacing/layout.

**Comment by epost** [comment]
I think it would be nice to keep a non-ANSI version around as well, for use with emacs compilation mode for example. Pulp uses `--monochrome` for this.

**Comment by zudov** [comment]
I think it also would be nice to detect whether the output goes to actual terminal and only then use ANSI codes, at least that's how many programs work.

**Comment by paf31** [comment]
@michaelficarra You'll want to base your changes on the `hints` branch though, if you work on this before that gets merged.

Thanks!

**Comment by michaelficarra** [comment]
Alright, thanks for the advice. I was planning on working on this last night, but I got distracted. I'll still try to get around to it soon, though.

**Comment by izgzhen** [comment]
How is this idea going now? I think we can fork a part of [HsColour](https://hackage.haskell.org/package/hscolour-1.23/docs/Language-Haskell-HsColour-ANSI.html). The parsing is done here https://github.com/crackleware/hscolour/blob/master/Language/Haskell/HsColour/Classify.hs which I think is not hard to adopt.

Beside, we can use this snippet to detect terminal https://github.com/feuerbach/ansi-terminal/blob/master/includes/Common-Include.hs#L140-L146

I will give a try now. Willing to hear any comment.

**Comment by zudov** [comment]
`purescript-psa` has colours by the way https://github.com/natefaubion/purescript-psa

**Comment by izgzhen** [comment]
@zudov Then it is great. So maybe this can be closed?

**Comment by izgzhen** [comment]
Maybe I am a bit optimistic about `psa` >_< Looks like it can't highlight source code snippet now. And for the more fine-grained highlighting, maybe rendering directly inside compiler would be a bit easier I think.

**Comment by zudov** [comment]
Actually, I simply highlight my error messages by running the compiler inside neovim's `:terminal` on which I do `set syntax=purescript`, and everything gets highlighted in the same way as in my source files. Such way of doing highlighting feels much nicer than handling it in compiler itself.
