### ISSUE TITLE
JavaScript "dialect" support

### ISSUE THREAD

**Issue by ais04** [purescript/purescript#1521]
There are ActionScript and UnityScript. They aren't real dialects but they are similar to JavaScript. I don't really work with Flash, but I heard AS is still pretty popular, for example you can create mobile apps with AIR. Unity is one of the most popular game engine and it would be great if you could use PureScript to create games with it.

**Comment by garyb** [comment]
I think AS3 would probably have to be another backend entirely, I'm pretty sure the compiled code we generate would be rejected as it doesn't really like you using prototypes directly... also `main` would have to be dealt with differently as we'd have to generate a class that extends `Sprite`, etc.

Avoiding AS3 was actually my original motivation for working on a compile-to-ECMAScript language (pre-PureScript), but all my work of that ilk switched over to JS over the last few years.

**Comment by ais04** [comment]
Is there any plans to create some sort of interface, so you could simply change the generated code?
```
class CodeGenerator where
    
    functionCode ast :: PsAst -> String
    recordCode ast :: PsAst -> String
```

**Comment by garyb** [comment]
That's basically the goal of #971 (it's a little more involved than the suggested interface, but it will make a lot more of the compiler reusable for alternative backends), but that probably won't be resumed until we're done with the issues we're working on for 0.8.
