### ISSUE TITLE
Row rendering issue

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1524]
@paf31 I'm seeing things like this in the generated docs when using the current master:

``` purescript
data ExistsR (f :: # * -> *
)
```

``` purescript
newtype IProp (r :: # *
) i
  = IProp (Prop i)
```

We can probably do better than that :smile:. I assume errors for these types would appear similiarly in the output too?

**Comment by paf31** [comment]
Thanks, I'll take a look. I think this should only be happening in docs.
