### ISSUE TITLE
Synonyms... again

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1526]
It seems the synonym unwrapping might not be eager enough:

```
Error unifying type

  RenderP { text :: String
          }

with type

  Function
```

This error comes from a function that is typed with `RenderParent` which is defined below:

``` purescript
type RenderP s f p = s -> HTML p (f Unit)
type RenderParent s s' f f' g p = RenderP s f (SlotConstructor s' f' g p)
```

So it's desugaring `RenderParent` but not the inner `RenderP`. So either this is the new synonym approach not quite working, or maybe we did need the rule in #1487 after all?

**Comment by paf31** [comment]
Is this only happening in `master` then?

**Comment by paf31** [comment]
I think this should be fixable without reinstating the extra type checking rule. We just need to desugar synonyms somewhere, and we're currently forgetting to. It might be after desugaring the first synonym actually.

**Comment by garyb** [comment]
Yep, just in master.

**Comment by paf31** [comment]
Ugh, ok. Is there any minimal example which fails? Is it just any nested synonym?

**Comment by garyb** [comment]
I'm away from my machine for a while now, so I don't have a minimal example yet.

**Comment by paf31** [comment]
I'm trying to produce one, but it's not simple.

**Comment by garyb** [comment]
Looks like it may be function related? So inner synonym is a function, outer is not, and then a function def is typed with the outer synonym.

I'll try and make a simple example when I get home, if you have better things to do. :smile:

**Comment by paf31** [comment]
Hmm, I can't reproduce this. What example was this? `--verbose-errors` might be handy here too.

**Comment by garyb** [comment]
Try compiling the examples in the Halogen PR I just opened - think it was the Ace example I encountered it.

**Comment by paf31** [comment]
The Bower dependencies don't seem to want to resolve nicely. I'll wait until later.

**Comment by garyb** [comment]
Ah, I forgot to mention: `bower link` is the best way to do that. So setup a link for `purescript-halogen` and then `bower link purescript-halogen` in an example and it will install all the other dependencies it needs too: https://github.com/slamdata/purescript-halogen/blob/c9f6efd24a9a3506f2e487ee1ead481bdbcda70c/package.json#L13

I'm just going to get some food but will have a look at constructing an example after.

**Comment by garyb** [comment]
Oh, or as per the above `npm run example-ace` will work. :)

**Comment by paf31** [comment]
It works for me, so I must be doing something wrong :)

**Comment by paf31** [comment]
As discussed on IRC, this happens because the synonym is not exported, so doesn't appear in the externs file, and hence doesn't get unfolded.

**Comment by garyb** [comment]
Maybe we should treat the externs files a little differently then - now they have their own format, perhaps the most useful thing would be to include all type declarations (by that I include synonyms, and type constructors introduced by `newtype` and `data` too) within a module in the externs file, regardless of whether they're exported or not, but then have a flag that determines whether they were exported that we can use when resolving the lookup during desugaring.

The motivation for this then is it allows the type checker has access to all the pertinent information and we preserve the ability to have abstract types: like the synoynm-with-prism-access model I described before. Aside from the benefit to the user, in the long run this should help with the idea for GADT handling too.

Any objections to that approach? If not I'll work on it, as I think it should be easy enough to do.

**Comment by paf31** [comment]
From the point of view of the type checker, and from the point of view of codegen, synonyms are just aliases, and I think the imports should reflect that. Although they reserve a name in the type namespace, they don't generate any distinct types, so I think it's incorrect to allow imports/exports of synonyms without the things they wrap. If we want to hide things, we should be using the type system, i.e. `newtype`, IMO.

I see two valid options:

1. All synonym exports are explicit, in which case we need to ensure via some means that the things a synonyms wraps are also available in the environment, either automatically or via errors.
2. All synonym exports are implicit, in which case we need to make some major changes to the way externs are generated, and do something to avoid naming conflicts.

My preference is for 1).

I don't particularly like having things in the externs which are not actually exported, because as an abstract representation of what's actually happened during codegen, it's not accurate.

**Comment by jonsterling** [comment]
with regard to type synonyms and data abstraction, perhaps newtype is a better fit for this language, but I would just like to register the fact that it can needlessly make code a lot more arcane. in ML, we can enforce abstraction for type synonyms without hiding things behind a data constructor and it is lovely. moreover, this is not in conflict with the fact that synonyms are not generative.

hiding the identity of a synonym falls out naturally from the type structure of modules; from my perspective, at least as a module theorist, it would be stranger to have a special case for type synonyms to make their identities unavoidably transparent, than to provide them the uniform treatment that follows directly from way that we implement transparent exports, which is through singletons in the module system.

**Comment by garyb** [comment]
All synonym exports being implict sounds like a really bad idea to me, so I'm definitely not voting for that option :wink:

Another option then: the synonyms we export should at least expand any inner synonyms. There is no reason at all why `RenderP` needs exporting in the case that kicked this issue off, as it's just another synonym for real types that _are_ exported from the module.

Another motivating example here is I'd like to not have to export [this type](https://github.com/slamdata/purescript-halogen/blob/98cf08884c98a1b0d8ce628c3c000191acb200fc/src/Halogen/Component.purs#L72) at all, as due to the smart constructors and combinators that the module exposes it is never possible to provide anything other than `Const Void` for `o` and `Void` for `p`, so only exporting the `Component` synonym would be desireable.

Also, :+1: for what Jon said :smile:

**Comment by paf31** [comment]
Expanding inner synonyms is another option, but we'd need to make sure we keep the unexpanded versions around for pretty printing in PSCi etc.
