### ISSUE TITLE
Codegen module re-exports by copying fields

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1536]
Module reexports are currently the only type of export which don't have a simple representation in codegen, since resolving module reexports requires knowing about more than just the current module or its externs file. Would it make sense to generate code to copy fields for a module reexport instead? It seems simpler to me this way, but I don't know if there are things which would make this difficult.

**Comment by garyb** [comment]
If you're just talking at the JS level then this should be reasonably straightforward I think, but generating the code at the `AST`/`CoreFn` level is trickier as we would need to do some work to ensure that re-exports arriving within a module through different routes don't conflict (e.g. `A` exports `x`, `B` re-exports `A`, `C` imports `A` and `B` so we need to know that `A.x = B.x` when arriving at `C`).

**Comment by paf31** [comment]
Ah right, good point.
