### ISSUE TITLE
Issue with CTRL+C in PSCi

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1537]
I get this after CTRL+C in `master`:

```text
psci: <stdin>: hGetChar: hardware fault (Input/output error)
```

I'd like to fix this before 0.7.5, by backing out the CTRL+C change if need be.

**Comment by paf31** [comment]
This seems to be a `pulp` issue since it works with `psci` being run on the command line.

**Comment by anttih** [comment]
I get this with plain `psci` in one project.

**Comment by zudov** [comment]
@paf31 Are you referring to that Ctrl+C change? https://github.com/purescript/purescript/pull/1489

**Comment by zudov** [comment]
I've been getting that error message with other programs that use haskelline, for instance with `ghci`. But it was happening only if I did something weird. It might be haskelline issue.

**Comment by leighman** [comment]
I get this with plain `psci`. Version 0.7.6.1.

```
$ psci
> test<Ctrl-C>
psci: <stdin>: hGetChar: hardware fault (Input/output error)
```

Terminal fubared repeatedly.

**Comment by hdgarrood** [comment]
@leighman which OS?

**Comment by leighman** [comment]
@hdgarrood Ubuntu 15.10 using gnome-terminal. ghc 7.8.4

**Comment by hdgarrood** [comment]
@leighman huh, weird. I'm on 14.04 and can't reproduce. Did you compile purescript yourself? What happens if you use one of the binaries from the github releases?

@antiih, can you show us the project that it happens in?

**Comment by leighman** [comment]
@hdgarrood Installed with `npm install -g`. I don't get it using `psci` binary directly but I do when I use npm installed version (which is actually a little js wrapper).

So something to do with the way it's invoked through psci.js in `node-purescript-bin`? (@garyb)

**Comment by hdgarrood** [comment]
ah, yes, I almost certain that's it. I was planning on addressing this in pulp after we release the purescript port. I think if it's being launched via an intermediate process, then that process has to catch SIGINT and forward it on to the `psci` process before exiting.

**Comment by garyb** [comment]
I'm actually not all that familiar with the workings of `node-purescript-bin`, I just mechanically bump the version and release when the compiler is updated, like a trained monkey. Sounds like it may well be the culprit though.

**Comment by hdgarrood** [comment]
Ah, there's already a PR for this: https://github.com/purescript-contrib/node-purescript-bin/pull/11/files

**Comment by jplatte** [comment]
Still having this issue... I didn't notice the error message until now somehow though, thought we still didn't have the Ctrl+C behaviour of other REPLs. I can definitely reproduce it with `pulp psci`, not sure what I'd have to do to reproduce it without (just starting psci and pressing Ctrl+C doesn't crash it).

**Comment by muratg** [comment]
I'm consistently hitting this on my Ubuntu 18.04. v0.13. 

I start the REPL with `spago repl`. Ctrl-D works fine. If I do Ctrl-C, I get "purs: <stdin>: hGetChar: hardware fault (Input/output error)".
