### ISSUE TITLE
Thread block on recompile

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#1548]
```
psc: make: dependency should already have been built.
psc: thread blocked indefinitely in an MVar operation
```
Message after change in already compiled module. Removing `psc` output and recompile works. Error is raised non-determenistically.

**Comment by paf31** [comment]
Thanks, I'll take a look.

**Comment by parsonsmatt** [comment]
Getting the same issue here with this project: https://github.com/parsonsmatt/ql-purs. At least, for this time, the issue seemed to be caused by having two instances sharing the same name (typo :fearful:)

**Comment by paf31** [comment]
@cryogenian @parsonsmatt I can't reproduce this, but could you please try the `1548` branch and see if that solves the issue? Thanks!
