### ISSUE TITLE
Support git@...:... repository URLs

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1549]
The [extractGithub](https://github.com/purescript/purescript/blob/3794bda/src/Language/PureScript/Publish.hs#L195) function requires URLs to start with `git://github.com/`. The clone URLs provided by GitHub start with `git@github.com:`, so they are rejected.

**Comment by paf31** [comment]
Thanks. Is this a `psc-publish` issue, or a Pursuit issue?

**Comment by paf31** [comment]
Oops

**Comment by tfausak** [comment]
I encountered this while using `psc-publish`. My end goal was Pursuit, but I guess it's not a problem with that.

**Comment by hdgarrood** [comment]
Using an SSH url such as `git@github.com:tfausak/purescript-batteries` will fail unless you have push access to that repository though, right?

**Comment by hdgarrood** [comment]
Lol, no, I should have checked first.

**Comment by hdgarrood** [comment]
Yep, this is the right place for this issue, the extractGithub function you already linked to is the bit that wants changing.

Once this is implemented, I think we should test this with Pursuit before releasing, too: uploading a package using an SSH url, and checking the link to the package uploader, and source links. I'm fairly sure these things will simply work, but I think it's worth being safe.
