### ISSUE TITLE
LambdaCase

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1558]
e.g.
``` purescript
fn = \case 
  X -> true
  Y -> false
```

Perhaps an "if lambda" would be neat too, although I'm not too sure how to arrange that so the phrasing works nicely.

``` purescript
fn = \if X else Y
```

Although I guess LambdaCase lets you do it anyway:

``` purescript
fn = \case
  true -> X
  false -> Y
```

**Comment by paf31** [comment]
Lambda case sounds nice. I don't use it much, but it's definitely very nice to have on occasion.

**Comment by paf31** [comment]
Thinking about syntax, another option is something like a "case section":

```purescript
fn = case _ of 
       X -> true
       Y -> false     
```

although that might be more confusing, I don't know.

**Comment by michaelficarra** [comment]
Is this not `fn = (== x)`?

**Comment by paf31** [comment]
Yes, but you can do more interesting things with it too. Anything you can do with a `case`.

**Comment by michaelficarra** [comment]
We have piecewise definitions, though:

```purs
fn X = ...
fn Y = ...
```

How does it improve upon that?

**Comment by paf31** [comment]
`\case ...` is an expression, it doesn't need to be a top-level declaration:

```purescript
justs = filter \case { Just _ -> true; _ -> false }
```

**Comment by garyb** [comment]
I quite like the case section idea, that would certainly work better for the if too. I agree it may be confusing though. Since we already have record sections maybe it's ok?

**Comment by user471** [comment]
Using some sort of separator could be less confusing.
```
\Just x -> x + 1 or Nothing -> 0
```
It could also be useful for top level functions, so you don't need to repeat function name
```
foo (Just x) -> x + 1
 or Nothing -> 0
```

**Comment by natefaubion** [comment]
> I quite like the case section idea, that would certainly work better for the if too. I agree it may be confusing though. Since we already have record sections maybe it's ok?

I think the consistency of turning any syntactic element into a section using `_` is nice. It's somewhat unfortunate that we overload it to mean "wildcard" as well though. For example, I don't think it would be unreasonable after being exposed to wildcard patterns to think that `if _ then foo else bar` is equivalent to `if true then foo else bar`, and thus always evaluates to foo.

**Comment by mietek** [comment]
My main use case for LambdaCase is pattern-matching on the result of assignment within do-notation blocks.

For example, instead of writing:
```haskell
do result <- assignment
   case result of
     pattern1 -> value1
     pattern2 -> value2
```
…with LambdaCase, I can write:
```haskell
do assignment >>= \case
     pattern1 -> value1
     pattern2 -> value2
```
However, since we’re already talking about a specially-sugared do-notation block, here’s what I’d really like to write:
```haskell
do wadlercase assignment of
     pattern1 -> value1
     pattern2 -> value2
```
(Substitute your own favourite keyword for `wadlercase`, keeping in mind [Wadler’s Law.](https://wiki.haskell.org/Wadler's_Law))

**Comment by garyb** [comment]
I quite like the idea of that ^ too, it does crop up fairly often.

**Comment by AppShipIt** [comment]
AFAIK currently planned proposal:

```purs
fwd = case _ of
  X -> true
  Y -> false

bwd = if _ then X else Y
```

**Comment by LiamGoodacre** [comment]
Did we decide on the required/not-required parentheses? `(case _ ...)` vs `case _ ...`

**Comment by AppShipIt** [comment]
I assume it'd follow the same parsing rules as if there were a value present.

**Comment by garyb** [comment]
We recently mused a bit about this on a SlamData channel. My preference would be that if we're going to start requiring parens then it is only for expressions where the underscore is at the boundary: operator sections, record wildcards. 

`case` in particular would be unpleasant to have to wrap in parens, due to its inherent multi line formatting.

**Comment by AppShipIt** [comment]
Ah that background makes sense. I agree its introduced with keywords so parens feel superfluous.

**Comment by AppShipIt** [comment]
Ah background makes more sense. Parens seems superfluous especially when it's typically going to appear on the other side of an operator.

**Comment by Xandaros** [comment]
This is something I'm really missing in PureScript. I, too, use it mostly in do-blocks, so any of the three proposals are fine. However, I'd prefer the _-syntax, I think.
It's already used in record accessor sections thingies and in my opinion conveys the intended meaning a bit better. Albeit at the expense of being slightly more verbose.
