### ISSUE TITLE
Format errors as Markdown?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1563]
I've been thinking about ways to format error messages which would break up the different parts of an error nicely. First of all, I added horizontal rules between parts, like so:

```text
Error found:
Error in module M1:
--------------------------------------------------------------------------------
Error in value declaration compose:
--------------------------------------------------------------------------------
Error at test.purs line 4, column 15 - line 4, column 19:
--------------------------------------------------------------------------------
Error checking type of property accessor

  g."f"

--------------------------------------------------------------------------------
Error checking that expression

  g

has type

  { f :: _0 -> _1
  | _2
  }

--------------------------------------------------------------------------------
Error while trying to match type

  Object

with type

  Function _3

--------------------------------------------------------------------------------
Could not match expected type

  Object

with actual type

  Function _3

--------------------------------------------------------------------------------
```

The main issue with this is that is doesn't deal nicely with multiple errors.

So another option is to format errors as Markdown, using bulleted lists to break up the parts, and indenting values and types by 4 chars, not 2, so that they are valid code sections. Editors could choose to render the markdown in a pretty format, but even on the terminal it should be easier to read. And it generalizes nicely to multiple errors.

As a plus, we can also copy and paste the errors into a GitHub issue.

Any thoughts?

## Sample (as text)

```text
- Error found:
- Error in module M1:
- Error in value declaration compose:
- Error at test.purs line 4, column 15 - line 4, column 19:
- Error checking type of property accessor

        g."f"

- Error checking that expression

        g

  has type

      { f :: _0 -> _1
      | _2
      }

- Error while trying to match type

        Object

  with type

      Function _3

- Could not match expected type

        Object

  with actual type

      Function _3
```

## Sample (formatted)

- Error found:
- Error in module M1:
- Error in value declaration compose:
- Error at test.purs line 4, column 15 - line 4, column 19:
- Error checking type of property accessor

        g."f"

- Error checking that expression

        g

  has type

      { f :: _0 -> _1
      | _2
      }

- Error while trying to match type

        Object

  with type

      Function _3

- Could not match expected type

        Object

  with actual type

      Function _3

**Comment by paf31** [comment]
I think if this happened, it should happen at the same time as JSON errors, so that editors can target whichever type of editors they prefer.

**Comment by garyb** [comment]
I wonder if formatting would be less of a problem if we just did less explaining - for the majority case the only pertinent pieces of information are position / module / declaration info (and we can get rid of the module part if we only allow one module per file), and then the actual error.

We have 7 lines that start with "Error" here, and the two sections "Error while trying to match type" and "Could not match expected type" are identical apart from that wording.

I know a lot of this comes from how we actually build up the error messages, but in an ideal world that error message would be something like this IMO:

```
Error at test.purs line 4, column 15 - line 4, column 19:

  Could not match expected type
    
    Object

  with actual type
    
    Function _3

  in value declaration compose
  while checking type of property accessor g."f"
```

(I didn't realise before trying this out just now, but I think having the expression info under the error is better too actually, GHC-style - that lets us drop a lot of the "error in ..." cruft).

My type-error-fixing process is almost always this: 

1. look at the top of the error to see the position
2. scroll past all the other stuff to find out what the error is

It's true, sometimes the other stuff really is useful, so maybe we need 3 levels of verbosity for our errors then: terse (default), what we have now, and then the fully verbose mode we also have.

I'm pretty sure what I just did above doesn't work that well for all type errors, as the `while checking type of property accessor g."f"` part of this one makes it particularly suitable, but if we could add some more of that kind of info to any of the errors we throw I think we can eliminate all that other info about how the error occurs for the usual case.

I don't know though, just thinking aloud really. I think the size of our type-error messages in particular can be just as intimidating as the content/wording currently is all.

**Comment by paf31** [comment]
How's this?

```text
Error found:
in module M1
at /tmp/1 line 4, column 15 - line 4, column 19

  Could not match expected type

    Object

  with actual type

    Function _3


while trying to match type Object
with type Function _3
while checking that expression g
has type { f :: _0 -> _1
         | _2
         }
while checking type of property accessor g."f"
in value declaration compose

See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information,
or to contribute content related to this error.
```

**Comment by garyb** [comment]
Oh wow, that was quick (assuming you didn't hand produce it :wink:). Yeah, I like that, at least now the most important stuff is at the top.

**Comment by paf31** [comment]
Yeah, I'm quite happy with this. I opened a PR just now.
