### ISSUE TITLE
Verified package set

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1564]
A major problem right now seems to be the number of packages out there which just don't build with the latest compiler.

I think we should keep a list of packages which are known to build with the latest `psc`. This would need to be enforced with a regular automated build.

Let's discuss how to make this work. The community server (purescript.org etc.) can be used to run the builds if necessary, or maybe we could use Travis with a webhook somehow.

**Comment by garyb** [comment]
Integrate with pursuit perhaps? Upon a new compiler release have a process that can test compile each pursuit-published package (one at a time, not as a batch) and have some kind of indicator in pursuit of the version that they last worked with...

**Comment by paf31** [comment]
Sounds like a great idea.

**Comment by tfausak** [comment]
For what it's worth, building [purescript-batteries](https://github.com/tfausak/purescript-batteries) would verify (almost) all packages published by the purescript owner on GitHub. Of course having a build indicator for each compiler version on Pursuit would be great. Batteries could be a quick spot-check, though.

**Comment by puffnfresh** [comment]
Getting PureScript packages into [nixpkgs](https://github.com/nixos/nixpkgs) and onto [Hydra](http://hydra.nixos.org/) would be useful work, too.

**Comment by paf31** [comment]
So `core-tests` already tests the core libraries, but I'd like something which users can opt into for their own libraries.

**Comment by zudov** [comment]
We could make something like stackage-curator.
Could probably even reuse `stackage-curator` for that :D

At first, we can represent the BuildPlan as `acme-everything.json` which would be a bower config with (supposedly) working ranges.

**Comment by zudov** [comment]
Also, since purescript's output is pretty much system-independent, we could distribute the work and have purescript@HOME :3

**Comment by zudov** [comment]
I've started working on one idea this weekend, here is something https://github.com/zudov/purescript-inspection

It's largely work in progress. I tried to outline the basic idea in README. What do you think?

**Comment by paf31** [comment]
@zudov This looks really nice. I'd be happy to host this on `community.purescript.org` if you like?

**Comment by zudov** [comment]
That would be great. It's very raw at the moment though, so lets make it 'official' when I get a bit further.

**Comment by paf31** [comment]
This is tracked on `roadmap` now, closing.
