### ISSUE TITLE
Allow prime symbols in types

### ISSUE THREAD

**Issue by starper** [purescript/purescript#1569]
I don't think that it's very hard to implement (maybe I'm wrong), but I think it can be useful sometimes. Here is an example:

```purescript
module Foo_Test where

import Test.QuickCheck
import Test.QuickCheck.Arbitrary
import Foo (Foo(..))

newtype Foo' = Foo' Foo

instance arbitraryFoo' :: Arbitrary Foo' where ...
```

Underscore could be useful, for example, for some tool that automatically finds all test modules (or something else) and runs them and prime symbol could be useful when you have some wrapper, but you don't want to create a meaningful name for it.

**Comment by paf31** [comment]
I don't see any reason not to support this. @garyb ?

**Comment by garyb** [comment]
:+1:

**Comment by garyb** [comment]
Moved this to 0.9.1 because it should be a very minor change and I've written far too many types with a `P` suffix this afternoon.

**Comment by paf31** [comment]
Sounds good. Presumably, we'd use `$prime` in variable names but not in filenames.

**Comment by garyb** [comment]
I was just thinking about types actually, in which case there are no codegen concerns. Do you think it's worth allowing primed modules too? I can't think of a case I'd want to do that really!

**Comment by paf31** [comment]
I'm fine with just types.

**Comment by starper** [comment]
What I meant was primes for types and underscores for module names. Underscores in types are already supported and like you I can't see how primes in module names could be useful :)

**Comment by paf31** [comment]
Are dots in module names not enough then?

**Comment by garyb** [comment]
That would give us some codegen ambiguity issues actually, since we replace dots with underscores currently.

**Comment by starper** [comment]
I just had an old habit to use underscores in file names and thought that it could be useful in module names, too. But now I think that dots are more than enough :)
