### ISSUE TITLE
Scoped type variables and type annotations issue

### ISSUE THREAD

**Issue by starper** [purescript/purescript#1570]
I think I found a bug:
```purescript
foo :: forall a. a -> a
foo = \(a :: a) -> a
```
`foo` throws "Error unifying type `a0` with type `a`".

**Comment by paf31** [comment]
Thanks, I'll take a look!

**Comment by paf31** [comment]
Also, typed binders aren't kind-checked apparently :fearful:

**Comment by paf31** [comment]
I'd like to try to fix these two today and then release 0.7.5.1, @garyb. Sound ok?
