### ISSUE TITLE
Use Types.Proxy.Proxy instead of Data.Generic.Proxy

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1573]
As discovered in purescript/purescript-generics#19, the compiler uses `Data.Generic.Proxy`. I'm trying to update the purescript-generics package to use the existing `Types.Proxy.Proxy` from purescript-proxy. Doing that requires the compiler to switch from `Data.Generic.Proxy` to `Types.Proxy.Proxy`.

I'm pretty sure [this line](https://github.com/purescript/purescript/blob/2c7f09292648249d9e3dabdd79cad2b26e75a15e/src/Language/PureScript/Sugar/TypeClasses/Deriving.hs#L132) needs to change.

**Comment by paf31** [comment]
Sounds good, thanks.

**Comment by tfausak** [comment]
I see how to add a `ModuleName` for `Types.Proxy`:

``` hs
typesProxy :: ModuleName
typesProxy = ModuleName [ ProperName "Types", ProperName "Proxy" ]
```

But I don't know what else (if anything) has to be done to make purescript-proxy available to the compiler.

**Comment by paf31** [comment]
It's assumed that the user has it installed. If it's a dependency of `generics`, that should be ok. I think your change above is the only one needed, unless any other names changed. What about `anyProxy`?

**Comment by tfausak** [comment]
I left `anyProxy` in purescript-generics since it's not any different than the `Proxy` value.
