### ISSUE TITLE
Read arguments from a text file

### ISSUE THREAD

**Issue by xavierzwirtz** [purescript/purescript#1575]
Windows has an arbitrary limitation of 8192 characters for its command length. This causes issues when you are compiling a large project, or just compiling a project which links a large amount of libraries. The way typescript does it is via a command like so:
```
$ tsc "@path/to/argfile"
```

Something similar in `psc` would make Windows dev much easier.

**Comment by paf31** [comment]
Have you tried using glob patterns?

**Comment by xavierzwirtz** [comment]
I am using `gulp-purescript`, it does not use glob patterns to feed into `psc`.

**Comment by xavierzwirtz** [comment]
I bet your right that glob patterns would work, it would be very un-idiomatic to use from gulp though.

**Comment by xavierzwirtz** [comment]
[Corresponding `gulp-purescript` issue.](https://github.com/purescript-contrib/gulp-purescript/issues/55)

**Comment by paf31** [comment]
Sounds fine, we do a similar thing for `psci`.

**Comment by xavierzwirtz** [comment]
`gulp-purescript` has been updated to use the globs, fixing this issue for me. I will close this issue since my use case is solved.
