### ISSUE TITLE
glob bower_components/**/src/**/*.purs does not find any files

### ISSUE THREAD

**Issue by xavierzwirtz** [purescript/purescript#1576]
I cannot get the glob `bower_components/**/src/**/*.purs` to find any files. It looks like having two ** screws up the glob pattern. If I switch it to `bower_components/purescript_debug/src/**/*.purs` I get the expected results.

**Comment by paf31** [comment]
`bower_components/purescript-*/src/**/*.purs`?

**Comment by xavierzwirtz** [comment]
Ah, that resolved it. I betcha theres a bug in the glob library with having two `**`.

**Comment by paf31** [comment]
I'll close this then. Maybe this is an issue for the `Glob` repo though, as you say.
