### ISSUE TITLE
(..) import warning printed when reading externs

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1578]
e.g. try building `psc-gui`.

**Comment by paf31** [comment]
It seems to be this import warning only: MisleadingEmptyTypeImport

**Comment by paf31** [comment]
@garyb Any idea why this might be happening?

**Comment by paf31** [comment]
@garyb Looks like wildcard imports are not elaborated in externs, so the warning is getting rethrown for every module which imports the bad module too. We could either:

- Make sure elaboration works
- Censor the warnings when applying externs

**Comment by garyb** [comment]
Is this still a thing?

**Comment by paf31** [comment]
I'm not sure, but it's pretty easy to test. Just create three modules, have the first one include a bad import from the second, and the third import the first. Then force a recompile of only the third module, and hopefully, we don't see the warning.

**Comment by garyb** [comment]
Ah, it's not a thing as you added a fix to censor the warnings. The issue was re-opened as I said I'd fix it properly too.

**Comment by garyb** [comment]
Actually, I prefer your fix. Elaborating imports is a bit fiddly as when it comes to re-exports, etc.
