### ISSUE TITLE
Type inference issue with lenses in records

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1579]
Not specific to lenses obviously, I assume it's to do with the treatment of fields in records generally, but encountered here: https://github.com/garyb/slamdata-notebook/blob/c56e99b5e09e279e1fabafe38659be505b393bc3/src/SlamData/Notebook/Cell/Component.purs#L82

The `_State` and `_Query` prisms are unusable if provided in the `Def` record due to an error about unifying a constrained type when trying to do anything with them.

Maybe there's another issue for this already, but I wasn't sure what it falls under.

**Comment by paf31** [comment]
Did you try using `APrismP`?

**Comment by paf31** [comment]
Also, I'm planning to disallow polymorphic record property types in the next typechecker.

**Comment by garyb** [comment]
Ah no I didn't, I'll give that a try.

That will be a little awkward, it'll break Halogen for one. What's the rationale?

**Comment by paf31** [comment]
AFAICT, the issues we've been seeing around polymorphic records and rank N boil down to impredicativity. I'd rather simplify things a little and the least disruptive way to change things (ie. without removing entire features) is to make the type system entirely predicative.

How does it break Halogen?

**Comment by garyb** [comment]
The `eval` function in the component record is a natural transformation, so that would be disallowed under this I think? I assume you mean basically anywhere we end up with a universal quantifier in the type of a property?

**Comment by paf31** [comment]
Actually, maybe I'm wrong about the impredicativity thing. I need to do some reading.

**Comment by paf31** [comment]
But yes, that would break if I made that change.

**Comment by paf31** [comment]
See section 4 [here](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.99.6665&rep=rep1&type=pdf).

**Comment by garyb** [comment]
I see your concern about impredicativity though, and there probably aren't many places where we need it - also we could work around the restriction by not using a record in Halogen.

**Comment by garyb** [comment]
Aha! Thanks for the link.

**Comment by garyb** [comment]
Shame, as it also kills the idea of having modules use a record-style representation for a first class module kind of thiing that was raised in some other issue.

It looks like the impredicativity comes from having a quantifier on the record's type as well as that of the properties - maybe there's something there then - if the record is monotyped the fields can be polymorphic, and vice versa?

**Comment by paf31** [comment]
My understanding was that the `forall` under the record type was the main issue. Basically, I want to get to a state where unification only happens on monotypes and we use something like `GADTs` + `DataKinds` to make sure that invariant doesn't break.

**Comment by paf31** [comment]
Because that simplifies checking _a lot_ and then we might even be in reach of some proofs of correctness or a specification for the type system.

**Comment by natefaubion** [comment]
Doesn't this imply removing rank-n from constructor slots as well? Why is `data Id = Id (forall a. a -> a)` different from `newtype Id = Id { id :: forall a. a -> a }` different from `type Id = { id :: forall a. a -> a }`?

**Comment by garyb** [comment]
Unfortunately `APrismP` doesn't work here either, as you can't use `preview` on one of those:

```
  Could not match expected type

    Star

  with actual type

    Market s0
```

**Comment by paf31** [comment]
You have to use `clonePrism`.

**Comment by garyb** [comment]
Ah, thanks.

**Comment by paf31** [comment]
Did `clonePrism` work?

**Comment by garyb** [comment]
Yeah it did, thanks.

**Comment by texastoland** [comment]
Hmm `ps-localstorage` is using this to make records of curried functions act like objects. FWIW the compiler infers the correct type also noted in https://github.com/purescript/purescript/issues/1957#issuecomment-221186949.
