### ISSUE TITLE
Combine error code pages on wiki into one page?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1589]

**Comment by izgzhen** [comment]
I think it would be too long to read ... Maybe we can serve them on the purescript.org and only leaving a menu in wiki?

BTW, I can't find the source of purescript.org on GitHub.

**Comment by garyb** [comment]
@izgzhen it's available here: https://github.com/purescript/purescript.github.io

**Comment by izgzhen** [comment]
@garyb thanks. If we decide serve another wiki with tree structure, I think I can help organize the stuff.

**Comment by hdgarrood** [comment]
I think we should keep the contents of the wiki together. If any of it goes onto purescript.org, then it all should. As it happens I do like that idea, in the long term at least; I think a pull request workflow is preferable to anyone being able to change anything. The current situation it's nice in that it's low-friction, but eventually I expect stuff will get duplicated and it will become poorly organized. Wikis are generally not very accurate as well in my experience, so new users might not trust it.

Why combine the error codes onto one page, just out of interest?

**Comment by tfausak** [comment]
I like each error being on its own page. I'm not a huge fan of those pages being wikis. My rationale is basically the same as this blog post: http://www.yesodweb.com/blog/2015/08/thoughts-on-documentation

> People don't seem to trust Wiki content, nor explore it. They're also more nervous about editing Wiki content. Files imply: this is officially part of the project, and people feel comfortable sending a PR.

**Comment by paf31** [comment]
Yes, I think moving those pages into the main compiler repository might be the best way to go.

**Comment by garyb** [comment]
That's a good point, having the extra hurdle of a PR review in the way should indeed make it more trustworthy if those of us with merge access are also considered to be trustworthy :wink:

We could also make including a basic error page as part of the process of introducing a new error/warning then too, even if it's just a rehash of the compiler's description of the problem at first.

We can also version the errors/warnings then by linking to the error message page that is specific to the compiler version release tag.

**Comment by paf31** [comment]
[Tracked](https://github.com/purescript/roadmap/issues/41) on `roadmap`
