### ISSUE TITLE
Syntactic sugar for negative numbers requires Prelude

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1591]
Most of the syntactic sugar uses whichever functions are in scope. That means I can use `do` notation with my own `bind` function, for instance. But the sugar for negative numbers like `-0` apparently requires the Prelude.

``` purescript
module Example where
x = -0
```

```
Error found:
in module Example
at /.../Example.purs line 2, column 5 - line 2, column 6

  Unknown module Prelude


See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information,
or to contribute content related to this error.
```

It seems like it should use whichever `negate` function is in scope.

**Comment by paf31** [comment]
Sounds good, thanks.

**Comment by tfausak** [comment]
:+1: Thanks!
