### ISSUE TITLE
Types don't unify when they should

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1592]
I'm pretty sure this definition should type check, but the compiler (npm package version v0.7.5-rc.3) complains. 

``` purescript
module Example where
import Prelude (Functor)
data Either a b = Left a | Right b
instance functorEither :: Functor (Either a) where
  map f (Right r) = Right (f r)
  map _ l = l
```

```
Error found:
in module Example
at /.../Example.purs line 6, column 13 - line 6, column 13

  Could not match expected type

    a00

  with actual type

    b0


while trying to match type a00
  with type b0
while checking that expression l
  has type Either a0 b0
in value declaration functorEither

See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information,
or to contribute content related to this error.
```

Changing `map _ l = l` to `map _ (Left l) = Left l` makes the compiler happy again.

**Comment by garyb** [comment]
It's because the type of `l` from the case is still `Either a0 b0` rather than `Either a00 b0` - there's no way for the type checker to know that the `a` can be ignored when we have a `Left` constructor, unfortunately.

**Comment by garyb** [comment]
#1249 was my suggestion for how to improve the generated code for this, not that it helps with the PureScript definition.

**Comment by paf31** [comment]
What @garyb said. It's unfortunate that we have to pay the price of unwrapping and rewrapping in codegen, but I don't see any nice way to handle this in the type checker.

**Comment by tfausak** [comment]
Works for me! I wasn't sure if this was a bug or not.
