### ISSUE TITLE
Class not defined when defining instance

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1595]
If you import a class from a module that re-exports that class, you cannot define instances of it. 

``` purescript
module A (module A.B) where
import A.B

module A.B where
class X a

module Z where
import A
data Y
instance z :: X Y
```

``` javascript
// Generated by psc version 0.7.5.3
"use strict";
var A = require("A");
var z = A_B.X;
module.exports = {
    z: z
};
```

On the line where `z` is defined, `A_B` is not in scope. I end up getting a reference error when I run it:

```
ReferenceError: A_B is not defined
```

**Comment by tfausak** [comment]
Awesome, thanks!

**Comment by garyb** [comment]
Sorry the fix took so long! I should have jumped on it sooner considering this is a pretty awful bug in that it resulted in an error in the JS...
