### ISSUE TITLE
Wildcard warning with no position or useful information

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#1596]
Compiler version: `0.7.5.3` (62192bd6b5ecd2d7dd12512fbd0a2f6fbca0be68). No source file or position given, and the inferred type printed isn't useful either. My file had errors as well as this warning.

    Warning found:

      Wildcard type definition has the inferred type

        _4

    See https://github.com/purescript/purescript/wiki/Error-Code-WildcardInferredType for more information,
    or to contribute content related to this warning.

**Comment by mietek** [comment]
Same here.  This seems to be caused by an error within the relevant block:
```
Warning found:

  Wildcard type definition has the inferred type

    _441



See https://github.com/purescript/purescript/wiki/Error-Code-WildcardInferredType for more information,
or to contribute content related to this warning.

Error found:
in module Sketch
at /Users/mietek/Experiments/pure-lambda-auth/src/Sketch.purs line 265, column 22 - line 266, column 13

  Could not match type

    { dateHashed :: Date
    , hash :: HashedToken
    }

  with type

    Token


while trying to match type { dateHashed :: Date
                           , hash :: HashedToken
                           }
  with type Token
while checking that expression capability
  has type Token
in value declaration matchAccountByCapability

See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information,
or to contribute content related to this error.
```

**Comment by paf31** [comment]
Does anyone have a minimal example to reproduce this?

**Comment by paf31** [comment]
Ah, here's one:

```purescript
module M where

x :: _
x = \y -> y y
```

**Comment by paf31** [comment]
The issue here is related to the `MonadWriter` instance for `ExceptT`. Specifically, `censor` could be written in such a way as to censor warnings in the event of an error, if `censor` were a member of `MonadWriter`, but `censor` is written in terms of `pass`, and `pass` _cannot_ censor warnings in the event of an error, because its type prevents it.

I'm not sure of a nice way to fix this without tinkering with the `mtl` classes.
