### ISSUE TITLE
Improvements to unused import warnings

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1597]
- [x] Warn when importing data constructors for a type but only the type is used
- [x] Don't warn if the imported module is being re-exported (basically assume everything imported from that module is being used: it is!).
- [x] Warn for unqualified/non-selective imports (e.g. an unnecessary `import Prelude`)

/cc @nwolverson If I get some time I might look at these too, but if you fancy taking a further look that'd be great.

**Comment by nwolverson** [comment]
The third case should be covered already, assuming you mean unqualified implicit import that isn't used as opposed to #1509. `Prelude` may be special (ignored) since I assumed `bind` may appear due to `do` desugaring, maybe there's a way to improve that?

**Comment by garyb** [comment]
Ah okay, if it's just `Prelude` that that happens with I guess it makes sense, due to `bind` as you say.

**Comment by nwolverson** [comment]
OK I was wrong, I was looking for `bind` in every module so nothing was warned. New PR fixes that, but will never warn on `Prelude` (due to `bind`) yet potentially warn on some other module if `bind` is being provided elsewhere.
