### ISSUE TITLE
Empty export list is a parse error

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1599]
If you define a module with an empty export list, it will not compile.

``` purescript
module A () where
```

```
Error found:
at /.../A.purs line 1, column 11 - line 1, column 11

  Unable to parse module:
  unexpected )
  expecting "module", identifier, ( or proper name


See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
or to contribute content related to this error.
```

**Comment by garyb** [comment]
We could allow this but I'm not sure when you'd want an empty exports list, did you have a use case in mind?

**Comment by tfausak** [comment]
Usually I start with an empty export list when I'm writing a new module. It's a reminder to myself to explicitly list the exports. 

But you're right; I would never want a real module with an empty export list. Maybe it could be a warning?

**Comment by michaelficarra** [comment]
I prefer it as an error. The compiler is doing exactly what you wanted: reminding you to list the exports by refusing to compile.

**Comment by tfausak** [comment]
Fair enough :smile:
