### ISSUE TITLE
psc-bundle doesn't work when code has been built with `--require-path`

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1605]
I like to build with `--require-path=../` to avoid `node_modules` hackery, and `psc-bundle` [expects all require statements to be unprefixed](https://github.com/purescript/purescript/blob/dc54faf480c3e5dd64da69ef6b7e21d31bf17016/src/Language/PureScript/Bundle.hs#L145-L146). Should `psc-bundle` support `--require-path` as well?

**Comment by paf31** [comment]
:+1:

**Comment by stkb** [comment]
:+1: from me too. IMO ``` --require-path=../``` should be the default anyway.
