### ISSUE TITLE
Incorrect error when using nonexistent qualified identifier

### ISSUE THREAD

**Issue by jonsterling** [purescript/purescript#1609]
Here's an interesting bug which I have observed in `psc` 0.7.5.1.

```purescript
import MyModule as M

welp = M.SomethingNotInM
```

Instead of getting something like `Unknown identifier M.SomethingNotInM`, I get `Unknown module M`.

**Comment by jonsterling** [comment]
I have updated the ticket to reflect that this only seems to happen with constructors.

**Comment by garyb** [comment]
I thought we fixed this one a while back, perhaps the fix did work for non-constructor members!

**Comment by garyb** [comment]
@jonsterling have you got a test case for this? When trying:

``` purescript
module MyModule where

  data X = Y

module Test where

  import MyModule as M

  welp = M.SomethingNotInM

```

I get `Unknown data constructor M.SomethingNotInM`

**Comment by jonsterling** [comment]
Hmm! Maybe it got fixed since I submitted it? I'll try reproducing tomorrow, and we can close the ticket if it doesn't seem to be real anymore.

**Comment by garyb** [comment]
I'm going to close this as I'm pretty sure it's fixed. We can re-open if it reoccurs!
