### ISSUE TITLE
Add test-compile command for unit testing

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#1620]
For unit tests you usually want to test all functions in a module, not just the ones exported.

The usual advice in Haskell is to write your functions inside an `Internal` module, test that, and hope users don't import it. This isn't great as you now have to jump back and forth between different files that are concerned with the same piece of logic.

My Proposal: Add a test-compile command in which export lists are ignored for a specified set of modules so that you can import and test them freely in your unit tests.

**Comment by paf31** [comment]
This is also useful in PSCi, I think. See `:load` in GHCi.

**Comment by hdgarrood** [comment]
What about if you put everything in the Internal module which contains all the code and exports everything, and then created another "external" module which only imports the Internal module and selectively re-exports the bits that should be public?

**Comment by paf31** [comment]
Closing, because this seems like something better implemented in tooling, e.g. Pulp.
