### ISSUE TITLE
create Gitter channel

### ISSUE THREAD

**Issue by safareli** [purescript/purescript#1629]
It will be awesome if you create a [Gitter](https://gitter.im/) channel :3

**Comment by filib** [comment]
@safareli I know it isn't Gitter, but did you know there was an active IRC channel? They're all a really friendly and helpful bunch there. It's at `#purescript` on `irc.freenode.net`.

**Comment by safareli** [comment]
Yap I know but irc is not the  best way to communicate, in gitter there is history and better integraion with github and more stuff

**Comment by garyb** [comment]
There's history here for the IRC channel: http://ircbrowse.net/purescript, no integration though aside from some bots :)

**Comment by paf31** [comment]
I'd like to avoid having too many channels of communication since most tend to get diluted, see Reddit and the Google group for examples. That said, what's needed to set this up?

**Comment by paf31** [comment]
It's a shame there isn't an IRC host which provides the same Git integrations really. I'd like to be able to continue to use my IRC clients to connect.

**Comment by safareli** [comment]
yap to many channels might not be best way, but it's really great and nice way to communicate for example this is room of [Ramda.js](https://gitter.im/ramda/ramda) and when I had some issues with ramda I ask and got imediate feadback from others. if there was a room for purescript it will make it easy for beginers to reach out to other users of this language in case of problems or quick questions.

to set it up owner of this repo should just signe up and create room

**Comment by SimonRichardson** [comment]
Gitter is a replacement for Google groups imo. So if you wanted to keep the
amount of channels of communication down (which I agree with) then you
should consider dropping groups in replacement.

Yet I'm still unsure if it's worth it or if Gitter is just a fad?

**Comment by kRITZCREEK** [comment]
@safareli you can just join #purescript on irc. https://www.irccloud.com/ has a really nice webclient,

**Comment by safareli** [comment]
I know there are some irc clients but this one is more integrated to github. I don't know how to explain if you haven't tried that, but if no one wants it there's nothing i can do :disappointed:

**Comment by joneshf** [comment]
@paf31 you can connect to gitter over irc: https://irc.gitter.im/

**Comment by stkb** [comment]
I think this was maybe closed a bit prematurely. I guess one's preference would depend on which system you're most "invested" in already, and as I don't use IRC for anything else I'd prefer a Gitter channel too. 

It could be said that Gitter is a fad but there's already a lot of repo's using it. I agree of course that there's a problem with having too many channels of communication, but it costs almost no effort to set the room up so it might be worth just giving it a go and see if anyone uses it. As @joneshf said, there's also an IRC bridge for those who want to use IRC clients.

**Comment by paf31** [comment]
[Here it is](https://gitter.im/purescript/purescript)

Let's see how it goes, and maybe it will replace the Google group.

**Comment by zudov** [comment]
Since gitter splits the communication channels why don't we split them in a meaningful way.

We can use irc for purescript developer's discussions (discussing compiler and libraries development) and gitter for helping newcomers and asking questions.
