### ISSUE TITLE
Allow types like Array (forall a. a)

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#163]

**Comment by paf31** [comment]
I'm now leaning towards making everything impredicative before 0.9.

**Comment by garyb** [comment]
Predicative you mean? :wink: I still thing that making record fields monomorphic is way too harsh a restriction, but anyway... as for this issue, it can be closed. 

Things like `newtype` and `Exists` allow a useful form of this now. My actual motivation for wanting this was the heterogenous-list-with-class-constraint trick, and it was for some FFI type thing too, so `Foreign` would do it as well.

**Comment by paf31** [comment]
Yes, predicative :smile: 

Let's chat about that some more at some point, it's obviously a pretty big topic, and I don't know if I fully understand all of the trade-offs yet.
