### ISSUE TITLE
Any plans on rewriting purescript using purescript?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript#1630]
so then we could use purescript directly from node.js or browser

**Comment by garyb** [comment]
Yes: https://github.com/purescript/purescript-in-purescript

However that's long dormant, I hope to revist it in the future, but the main problem was it performs terribly compare to the Haskell version (around 1000x slower IIRC).

**Comment by spion** [comment]
There have been huge improvements in V8 optimisations between node v0.10 and current node (v4.2 and v5), so it might be worth giving this a shot again. 

How much effort do you estimate it would be just to get it to build with latest purescript?

**Comment by paf31** [comment]
I'd say quite a lot of effort would be needed. Personally, I'm more interested in trying to compile it with pure11, and see what the performance is like there. But I'd love to see the project resurrected anyway.

I'll close this, since issues can be written up on the purescript-in-purescript repo.
