### ISSUE TITLE
Add PureScript quasiquoter

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1643]
Following http://www.well-typed.com/blog/2014/10/quasi-quoting-dsls/, this should be fairly straightforward, and allow us to write actual PS code in things like the optimizer and generic deriving.

**Comment by jdegoes** [comment]
:+1:

**Comment by mgajda** [comment]
:+1:

**Comment by natefaubion** [comment]
This has not seen activity since opened, and there is not a concrete proposal for this feature. I'm going to close this until someone is motivated to take this up.
