### ISSUE TITLE
Polymorphic Record Types

### ISSUE THREAD

**Issue by born2defy** [purescript/purescript#1652]
Not sure if this is a new issue or the way this is supposed to work, but here it is:

This will compile and execute properly:

    color :: forall r. Color -> { color :: Color | r } -> { color :: Color | r }
    color c o = o { color = c }

    type ARecord
      = { size  :: Int
        , color :: Color
        , id_   :: String
        }

    aRecord :: ARecord
    aRecord
      = { size  : 10
        , color : Red
        , id_   : "Record"
        }

    color Red aRecord  -- Works fine

But, if we abstract the polymorphic record type into a type of its own for simplicity, like this:

    type HasColor r = forall r. { color :: Color | r }

    color2 :: forall r. Color -> HasColor r -> HasColor r
    color2 c o = o { color = c }

    color2 Red aRecord  -- this generates a type error

  Could not match type

    r0

  with type

    ( size :: Int
    , id_ :: String
    )

while trying to match typ
  with type ( size :: Int
            , id_ :: Stri
            )
while checking that expre
  has type { color :: Col
           | r0
           }
in value declaration it

**Comment by paf31** [comment]
```purescript
type HasColor r = forall r. { color :: Color | r }
```

I suspect you don't want that `forall r`.

**Comment by born2defy** [comment]
Just realized that :)

**Comment by paf31** [comment]
Does everything work as expected without the `forall`? Can this be closed?

**Comment by born2defy** [comment]
Yes - just a silly error on my part.
