### ISSUE TITLE
More hints for error with missing signature of top-level declaration which contains a type class constraint

### ISSUE THREAD

**Issue by ul** [purescript/purescript#1662]
Can we provide an additional hint when "No type class instance was found for" error is suspected to be connected to a restriction described here https://github.com/purescript/purescript/wiki/Differences-from-Haskell#type-classes-and-type-inference ? Just an additional link in message when no typeclass instance was found for top-level declaration without type signature. Right now it is superconfusing error for beginners like me.

**Comment by garyb** [comment]
I think that should be possible: I guess we want to add a hint that adding an explicit type may be required whenever there are unknowns in the type variables for a missing instance, right @paf31?

**Comment by paf31** [comment]
Yes, I think so.

**Comment by ul** [comment]
Thank you!
Вт, 24 нояб. 2015 г. в 17:28, Phil Freeman <notifications@github.com>:

> Closed #1662 <https://github.com/purescript/purescript/issues/1662> via
> b90fc77
> <https://github.com/purescript/purescript/commit/b90fc77eaf11606d36c78ce714e3a5ab9ba59b5d>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/purescript/purescript/issues/1662#event-473487837>.
>
-- 
ℜ
