### ISSUE TITLE
Invalid argument to infer

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript#1664]
I get the following error message from psc
```
psc: An internal error ocurred during compilation: "Invalid argument to infer"
Please report this at https://github.com/purescript/purescript/issues
psc: thread blocked indefinitely in an MVar operation
```

when trying to compile this code:
``` purescript
module Main where

import Prelude
import Control.Monad.Eff

data Identity a = Identity a

newtype IdentityEff e a = IdentityEff (Eff e (Identity a))

test :: forall e a. IdentityEff e a -> IdentityEff e Unit
test action = Identity $ do
  (Identity x :: Identity _ a) <- action
  return $ Identity unit
```

Some comments:
- This is obviously not the code I wanted to write :smile:. It's just the minimal example I could find which reproduces the error.
- The problem is the type annotation `Identity _ a` in the second-to-last line.
- Without this type annotation, the code does *not* compile (I actually can't figure out why) and gives a proper compiler error:
```
Could not match type

    Identity _1

  with type

    a0
```

**Comment by garyb** [comment]
Looks like it's the type wildcard in the type that causes this, if you use `:: Identity a` there's no compiler error (well, there's still an error, but the right kind :wink:)

**Comment by sharkdp** [comment]
I just realize that the type annotation doesn't make any sense ... I simplified too much without changing the annotation. I'll try to find the original example again. Anyway it's probably still something that shouldn't happen

**Comment by garyb** [comment]
Yeah, it's using a wildcard in a binder is what is raising the internal error I think.

As for a version of your code that typechecks, there's this, but I don't know if it's what you actually want!

``` purescript
module Main where

import Prelude
import Control.Monad.Eff

data Identity a = Identity a

newtype IdentityEff e a = IdentityEff (Eff e (Identity a))

test :: forall e a. IdentityEff e a -> IdentityEff e Unit
test (IdentityEff action) = IdentityEff $ do
  Identity x <- action
  return $ Identity unit
```

**Comment by sharkdp** [comment]
> Yeah, it's using a wildcard in a binder is what is raising the internal error I think.

Yes, it seems I also used the wrong kind (and a wildcard) for the type annotation in my original example...

> As for a version of your code that typechecks, there's this, but I don't know if it's what you actually want!

Ooops :flushed: Thanks! I hope it was a bit more concealed in my original example :smile:
