### ISSUE TITLE
Parens for constraints

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1669]
The following is valid Haskell but not PureScript:
```haskell
let f = ("!" ++) <<< show :: forall a. Show a => a -> String
```
PureScript requires parentheses around the constraints when there's only one, unlike Haskell.

Currently, the error you get is not very helpful:
```
(line 1, column 22):
unexpected ::
expecting ., {, `, qualifier or symbol
```

I propose we either improve this error message, or make the parens optional in the case where there is only one constraint - or maybe always optional? is that possible?

**Comment by paf31** [comment]
:+1:
