### ISSUE TITLE
Literate Support w/ Markdown

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#167]

**Comment by betabrain** [comment]
I always wonder why no programming language lets the user specify the "language version". This could be done with a backwards compatible *smart comment* at the top of the file:
`-- purescript { version: "~7.0" }`

This could also be used to enable a **literate programming mode** or toggle optimization flags:
`-- purescript { literate: true, tco: false, backend: "any" }`

Finally, once enabled at the top of the file, the compiler should look for further comments allowing the following features:
 - debug options for the code under development
 - different optimizations on different subsections of the code
 - combine backend-specific code in the same file
 - combine different language versions (useful while porting)
 - many more

**Comment by jasonkuhrt** [comment]
Not a super useful comment but AsciiDoc seems like a good document syntax to choose assuming we have to pick only one.

**Comment by paf31** [comment]
I'd say this is better handled in tooling. Closing.

**Comment by paf31** [comment]
Relevant:

https://github.com/Thimoteus/literate-purescript

**Comment by rightfold** [comment]
@betabrain no programming language, such as Perl and Erlang? :P

**Comment by dbaynard** [comment]
Would it be viable to accept a literate preprocessor option, like GHC Haskell's `-pgmL`, so purs could operate directly on literate source?

**Comment by paf31** [comment]
Why not just run the command during the build script?

**Comment by rightfold** [comment]
That doesn’t work with libraries

**Comment by rightfold** [comment]
But that could be added to Pulp instead of psc :P

**Comment by garyb** [comment]
Literate style doesn't really work with libraries either, does it? Since library code can rarely be read sensibly top-to-bottom.

**Comment by paf31** [comment]
I really think this is out of scope for `purs`.
