### ISSUE TITLE
Further reduce import boileplate using `NoImplicitPrelude`

### ISSUE THREAD

**Issue by zudov** [purescript/purescript#1672]
@phadej

After https://github.com/purescript/purescript/pull/1610 we have `import Prelude ()` in quite many modules. Is there something that prevents us from using `NoImplicitPrelude`. I think we could even do it package-wide from `purescript.cabal`. I doubt purescript developers would be scared of `import Prelude` on top of every file :p

*P.S: I should have ask that in original PR, but didn't notice it back then since I was too lazy to scroll down the diff a little bit

**Comment by hdgarrood** [comment]
While we're at it, it's probably worth adding a bunch of other pragmas to `purescript.cabal`, to reduce noise from adding/removing them in diffs. For example, I think the following (at least) is reasonable:

* `FlexibleContexts`
* `ScopedTypeVariables`
* `RecordWildCards`
* `RankNTypes`
* `TupleSections`
* `DeriveFunctor`
* `DeriveDataTypeable`
* `OverloadedStrings`
* `GADTs`

**Comment by zudov** [comment]
@hdgarrood I would disagree on adding `OverloadedStrings` there since it makes the type interference a bit harder and you sometimes have to put explicit type definitions for string literals.

:+1: to the rest

**Comment by paf31** [comment]
Yes, I agree with @zudov.

**Comment by hdgarrood** [comment]
Ok, that does make sense.

**Comment by zudov** [comment]
Yesterday @phadej said that he has nothing against `NoImplicitPrelude`.

I think I could go around doing that. I'll then add the following instances to cabal file:

```
NoImplicitPrelude
FlexibleContexts
ScopedTypeVariables
RecordWildCards
RankNTypes
TupleSections
DeriveFunctor
DeriveDataTypeable
GADTs
```

**Comment by garyb** [comment]
I've already added `DataKinds` globally in #1773 too (maybe, depending on whether we keep the approach in there).

**Comment by nwolverson** [comment]
`DeriveDataTypeable` no longer used.
