### ISSUE TITLE
psc-bundle: [...] openFile: resource exhausted (Too many open files) -- Mac OS X

### ISSUE THREAD

**Issue by mgmeier** [purescript/purescript#1673]
While working on a semi-large project, the above error message stopped psc-bundle from completing its job. The scarcity of available file handles on OS X is well known (cf. http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit), and the workaround (changing kernel variables) is unintuitive and unsatisfying.

I've investigated the issue:

* the number of ```inputFiles``` (in ```psc-bundle/Main.app```) is actually not that large in my case (272)
* It seems that nudging ```readFile``` (ibd.) to evaluate less lazy (and thus actually performing the I/O and releasing the file handle) is the least invasive solution.

I've devised a fix which I'll run by the purescript testsuite, PR is upcoming in a couple of hours.

(System: Mac OS X 10.10.5 Yosemite 64bit, purescript 0.7.6.1)

**Comment by garyb** [comment]
Resolved by #1674
