### ISSUE TITLE
Improve documentation for re-exports

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1677]
See https://github.com/tfausak/purescript-batteries, for instance.

One potential design: suppose we have code like this:

```purescript
module Main (foo, bar, module A) where
import Other as A
foo = 1
bar = 2

module Other where
baz = 3
```

Then we could generate docs like this:

```
## Module Main
#### `foo`
foo :: Int
#### `bar`
bar :: Int
### Re-exported from Other
#### `baz`
baz :: Int
```

That is, put a separate section at the end for re-exported values, noting which module each came from.

This design doesn't work brilliantly if you want to do something like having a `Foo.Internal` module in addition to a `Foo` module, where `Foo` re-exports selectively from `Foo.Internal`, though. Perhaps we could copy haddock's mechanism of comment directives inside module export lists to give more control if people want it? Also, perhaps we want some mechanism to tell Pursuit that a module is internal and should not be displayed in the documentation?

Anyway I think this is probably good enough to start with and see how well it works. It's certainly better than the current behaviour, I think.

**Comment by tfausak** [comment]
:+1: 

The current situation for re-exports leaves a lot to be desired. [The generated documentation for Batteries](http://pursuit.purescript.org/packages/purescript-batteries/0.3.0/docs/Batteries) was so useless I had to add my own hard-coded documentation.

**Comment by hdgarrood** [comment]
@garyb in #1415:
> Although actually, with the changes I'm about to open a PR for it makes partial re-exporting possible too, so maybe we need to be more specific than just saying which modules are.

Can you explain what the current situation is? I thought partial re-exporting was only possible by importing part of a module into a virtual module, and then re-exporting that, like this:

```
module Foo (module Virtual) where

import Prelude (Unit, unit) as Virtual
```

Is that correct?

**Comment by garyb** [comment]
Not quite, if you re-export a module after selectively importing from it only the imported values are re-exported, so:

``` purescript
module Foo (module Prelude) where

import Prelude (Unit, unit)
```

would export `(Unit, unit)`

**Comment by hdgarrood** [comment]
Ah, cool, thanks. Is there a function inside the library somewhere which will allow me to pass in a module, and get all the re-exported values from it and which module they came from? Something like `P.Module -> [(P.ModuleName, [P.Declaration])]`?

**Comment by garyb** [comment]
Actually, I think that's rather tricky at the moment as that info is only available during name desugaring - you need an [`Env`](https://github.com/purescript/purescript/blob/896bbcdb91c43b3054297e8c3a28592f00de07d3/src/Language/PureScript/Sugar/Names/Env.hs#L107) (which is different from `Environment` used by the typechecker), as that then contains the [`Exports`](https://github.com/purescript/purescript/blob/896bbcdb91c43b3054297e8c3a28592f00de07d3/src/Language/PureScript/Sugar/Names/Env.hs#L77-L94) for each module.

I don't _think_ name desugaring needs to happen anywhere in particular in the chain of desugaring operations, so maybe we could move it out of `desugar` and run it first, and that way the result could include the final `Env` used for the resolutions along with the updated modules.

**Comment by hdgarrood** [comment]
Ah awesome, thanks, I'll try to do that then. Do you know what happens with virtual modules; i.e. does an `Env` contain any virtual modules, or do they all get "resolved" to real modules before the `Env` is constructed?

**Comment by garyb** [comment]
As of #1759 there is a list of virtual modules names available for the [`Imports`](https://github.com/purescript/purescript/blob/896bbcdb91c43b3054297e8c3a28592f00de07d3/src/Language/PureScript/Sugar/Names/Env.hs#L44-L56) of a particular module, but we don't have the information about what a particular virtual module contains in a handy form - if I remember rightly the virtual versions of the names are present in the keys of the maps in `Imports` though, so they could be extracted from that if you need them in that form.

The `Exports` definitely has the resolved versions however. The `ModuleName` with each definition is supposed to be for the module they were originally exported from... _supposed_ to be. I have a nagging suspicion it might not be (it might not step back through re-exports of re-exports of re-exports, etc), but on the other hand I think the re-exports would be buggy if it wasn't the case, so maybe it's fine now after all.

**Comment by hdgarrood** [comment]
Cool. For the sake of documentation I think it might be better to just step back only until the first real module; for a re-export of a re-export I think you should first be sent to the module it was re-exported from, and from there, you can then go to the original module it was defined in if you want.
