### ISSUE TITLE
"Old language guide"

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1680]
https://github.com/purescript/purescript/wiki/Old-Language-Guide

This page warns that it is out of date, but as far as I can tell, the actual language guide part only requires a minimal amount of effort to update; by which I mean, just the language, ignoring things like grunt or pulp, or how to put purescript code into an html page &mdash; the bit starting at the subheading "Types".

Additionally, I think such a page would be very useful, and could fill a need that isn't currently covered by any other resources, as far as I can tell. It could be useful for people who already are fairly comfortable in the language but just want to check to see what the exact syntax for something is, or who want to stay up to date after syntax changes (like me, who didn't notice that `qualified` became optional!)

I'd be happy to do this but I just wanted to check whether you thought it sounds like a good idea first.

**Comment by michaelficarra** [comment]
I would love that. :+1:

**Comment by paf31** [comment]
Sounds good :+1: 

I think keeping the guide active does solve a particular problem, it's just going to involve some (minor?) ongoing work, but if you're happy to take it on, then yes, please do :smile:

**Comment by hdgarrood** [comment]
I am fairly sure that this is all up to date now. https://github.com/purescript/purescript/wiki/Language-Guide

**Comment by paf31** [comment]
Looks great, thanks!
