### ISSUE TITLE
psc-docs is using Show instance for errors

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1681]
For example, on current slamdata master (I guess they're using an older compiler?)

```
$ pulp docs
* Generating documentation in /home/harry/documents/code/slamdata
psc-docs: error: unknown module "ModuleName [ProperName {runProperName = "View"},ProperName {runProperName = "File"},ProperName {runProperName = "Modal"},ProperName {runProperName = "Mount"}]"
* ERROR: Subcommand terminated with error code 1
```

**Comment by garyb** [comment]
> I guess they're using an older compiler?

Yeah, master is stuck on psc 0.7.2. Main development is in the `new-halogen` branch currently.

**Comment by paf31** [comment]
So is this a bug in master?

**Comment by hdgarrood** [comment]
Sorry, yes, my point was that it would probably be better for `psc-docs` to not use the `Show ModuleName` instance when reporting errors.

**Comment by hdgarrood** [comment]
I can't reproduce this now. Maybe it's been fixed, somehow.

I think the problem must have been somewhere inside `Language.PureScript` (i.e. the library) rather than inside the code specific `psc-docs`, given that the "unknown module" part is displayed in a human-friendly way, it's just the actual module name that's using `Show`.

If I try to run `pulp docs` without first running `bower install`, in order to purposefully trigger an unknown module error, I do now get a properly formatted error:

```
Error found:
at /home/harry/documents/code/slamdata/src/View/Modal/Common.purs line 21, column 1 - line 23, column 1

  Unknown module Control.Plus


See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information,
or to contribute content related to this error.
```

So I'm going to close this.

**Comment by hdgarrood** [comment]
Silly me, the error occurs when you pass something to --docgen that doesn't exist.

Better repro steps:

```
$ pulp init
$ psc-docs 'bower_components/*/src/**/*.purs' 'src/**/*.purs' --docgen LOL
psc-docs: error: unknown module "ModuleName [ProperName {runProperName = "LOL"}]"
```

The culprit is here: https://github.com/purescript/purescript/blob/896bbcdb91c43b3054297e8c3a28592f00de07d3/psc-docs/Main.hs#L99-L107
