### ISSUE TITLE
Better errors when you forget to use "do"

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1683]
It would be nice to have some kind of special cases for the parse errors that result from forgetting to add "do", because they're not very easy to decode at the moment. For example:

```purescript
main =
  x <- foo
  f x
```

Supposing that `foo x` and `y` both have type `(Monad m) => m unit`, this would be nice to address too, although probably a fair bit harder:
```purescript
main =
  foo x
  y
```

**Comment by paf31** [comment]
What is the current error? I'd expect `unexpected "<-"`.

**Comment by hdgarrood** [comment]
Yes, I suppose I ought to concede that the current error is better than I originally implied:
```
Error found:
at /home/harry/documents/code/ps-scratch/src/Main.purs line 13, column 5 - line 13, column 5

  Unable to parse module:
  unexpected <-
  expecting expression


See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
or to contribute content related to this error.
```

However it is an easy mistake to make (well, I do it quite often, at least) and if we added a "perhaps you forgot to add a `do`?" I think that could be very helpful in some cases (eg: learners).

**Comment by soupi** [comment]
For the second case, this program:

```purs
module Main where

import Prelude
import Control.Monad.Eff
import Control.Monad.Eff.Console

main =
  log "hello"
  log "world"
  pure unit

```

Emits the error message:

```
Error found:
in module Main
at /Users/suppi/code/purescript/bug/src/Main.purs line 8, column 3 - line 10, column 8

  Could not match type

    Eff

  with type

    Function


while trying to match type Eff
  with type Function
while inferring the type of (log "hello") log
in value declaration main


See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information,
or to contribute content related to this error.
```

I'm using the master branch, [this](https://github.com/purescript/purescript/commit/0c87efeff2afa3210726791d68a53078bed52bbe) is the last commit I see on `git log`

**Comment by paf31** [comment]
The later error should be improved in 0.8.3. Can this be closed as "acceptable, difficult to improve"?

**Comment by hdgarrood** [comment]
Yep, ok then.
