### ISSUE TITLE
Why does compiler generate curried functions?

### ISSUE THREAD

**Issue by dotneter-** [purescript/purescript#1686]
```
foo :: Int -> Int -> Int
foo x y = x + y

test :: Array Int -> Array Int
test = map (foo 1)

```
```
var foo = function (x) {
    return function (y) {
        return x + y | 0;
    };
};

var test = Prelude.map(Prelude.functorArray)(foo(1));
```
It's bad for performance.
Why not just use ordinary js function and use currying when it's necessary?
```
var foo = function (x, y) {
        return x + y | 0;
};
var test = Prelude.map(Prelude.functorArray)(function(x) {foo(1, x)});
```
Performance-wise it's the same, you create a new function for every call.
But, for this code
```
test2 :: Array Int -> Array Int
test2 = map (\x -> (foo 1 x) * 2)
```
instead of creating two functions
```
var test2 = Prelude.map(Prelude.functorArray)(function (x) {
    return foo(1)(x) * 2 | 0;
});
```
you need to create only one per call
```
var test2 = Prelude.map(Prelude.functorArray)(function(x) {foo(1, x)*2});
```

and the most important part.
when you don't need currying,
```
test3 = foo 1 2
```
compiler use a simple function call
```
var test3 = foo(1, 2);
```
instead of 
```
var test3 = foo(1)(2);
```
Also, it would be easier to write ffi functions

**Comment by robotlolita** [comment]
Generating non-curried functions by default is complicated because the semantics and types themselves are curried. The compiler would have to do much more work to guarantee the correct composition of programs.

It could, however, optimise functions of the form `a b c` when `a` can be statically known to take two arguments. I don't know if such optimisation is implemented right now, but by your comment I'd assume it isn't.

The optimisation is similar to inlining:

```purs
k a b = b

f = k 1 2
g = k 1
```

Would get compiled to:

```js
function k(a) {
  return function(b) {
    return b
  }
}

function _k$2(a, b) {
  return b
}

function f() {
  return _k$2(a, b)
}

function g() {
  return k(1)
}
```

A better optimisation would just compile `f` to `function f(){ return b }`, of course. There was some talk about implementing a supercompiler for PureScript, but I don't know the status of that either.

**Comment by garyb** [comment]
See #479, #693, #696 for previous related discussions.

As for it being easier to write uncurried FFI functions, have you seen the `FnN` stuff in `purescript-functions`? https://github.com/purescript/purescript/wiki/FFI-tips#use-mkfn-and-runfn

**Comment by dotneter-** [comment]
@garyb It looks like nobody thinks it's a problem. But I don't see how such generated code can be used in real project.

**Comment by garyb** [comment]
I'm not sure I understand what you mean. It's definitely usable in a real project, my job is working on a large PureScript front-end. If your concern is about writing part of a project in PS and then calling it from JS you can use the `FnN` types as described in the link above to expose a decent interface to the JS code.

**Comment by dotneter-** [comment]
@garyb For something likes UI, maybe it would not be a problem. But what if I need a good performance (for game or heavy logic). I cannot just create a function for every function call like this ```foo(1)(2)```. According to one of the discussion, the curried version is 30 times slower. So, potentially my application would be 30 times slower than it should be.

**Comment by garyb** [comment]
You can use the `FnN` stuff even within PureScript code for cases like that. Maybe I didn't make it clear that the compiler inlines these values to be exactly what you're asking for, when a fully saturated `runFnN` is used. There are other options too, bundling up values into a record or data constructor rather than passing them as individual arguments, etc.

The "fix" for this is even worse than the problem unfortunately, as it becomes rather unpredictable as to where uncurrying would occur, even if we could find the optimal solution every time. Consider situations like these:

``` purescript
fn1 :: Int -> Int -> Int
fn1 x y = x * y

fn2 :: Int -> Int -> Int
fn2 x =
  let x' = x * 10
  in \y -> y * x'
```

Both functions have the same type, but `fn2` cannot be uncurried without a fair bit of rewriting, and would also change its performance (assuming the calculation of `x'` wasn't entirely trivial) as `x'` would have to be moved inside the function that accepts `y`, and then would be recalculated every time rather than just once when provided with `x`.

Then:

``` purescript
fn3 :: forall b. (forall a. a -> a -> a) -> b -> b
fn3 f x = f x x
```

In the above we have absolutely no way of knowing whether `f` is like `fn1` or `fn2`, so now it means we have to keep around curried and uncurried versions of every function, as we'd have to consistetly pass a predictable form to functions like `fn3`, and the only consistent form is that of being fully uncurried. Either that, or we have to create fully-uncurried wrappers for functions that cannot be fully-uncurried, and then we'd pass that in here. Either way it's more expensive than it otherwise might be.

The kind of problems raised by `fn1` / `fn2` go further too, assuming we accept `fn2` can't be uncurried, but perhaps we can uncurry some of the arguments:

``` purescript
fn3 :: Int -> Int -> Int -> Int
fn3 x y z = x * y * z

fn4 :: Int -> Int -> Int -> Int
fn4 1 = mul
fn4 x = \y -> \z -> y * z
```

`fn3`'s arguments can be grouped as `(Int, Int, Int) -> Int`

`fn4`'s definition means the arguments now could be grouped as either `Int -> (Int, Int) -> Int` (as `mul` here would probably be uncurried as `(Int, Int) -> Int`) or `Int -> Int -> Int -> Int` - so how do we deal with that?

And one final point, although I don't have actual statistics on this, but from the code I write it seems likely that I rely on partial application more often than fully saturated application.

**Comment by garyb** [comment]
Also, the 30 times slower comment... 30x slower than "extremely fast" is still not all that slow. The overhead of calling the function may be a lot slower, but the execution of the function body is not.

Check out this jsperf: http://jsperf.com/curried-vs-uncurried-functions. The "slow" uncurried versions execute 14.7 million ops/sec in Firefox for me, and 25.7 million ops/sec in Chrome. If that kind of overhead is a problem then PS will probably be too slow to do what you need anyway for other reasons.

**Comment by dotneter-** [comment]
>fn2 :: Int -> Int -> Int

```
var fn2 = function (x) {
    var x$prime = x * 10 | 0;
    return function (y) {
        return y * x$prime | 0;
    };
};
```
Why all parameters cannot be moved to the main function
```
var fn2 = function (x,y) {
    var x$prime = x * 10 | 0;
    return function () {
        return y * x$prime | 0;
    };
};
```
Then ```f1``` and ```f2``` would have the same ```function(x,y)```

The same  for ```f4```
```
var fn4 = function (x,y,z) {
    return function () {
        return function () {
            return y * z | 0;
        };
    };
};
```

**Comment by kRITZCREEK** [comment]
@dotneter-  Because you can't partially apply that function without using `Function.bind()`.

**Comment by robotlolita** [comment]
@dotneter- the second `fn2` in your example does more work than the first `fn2`, although they're both likely to be inlined in a hot loop by the v8 JIT or the SM JIT anyway — what you think is a "function call overhead" doesn't necessarily happen when the JS code is executing. v8 will try to NOT do function calls as much as possible.

As for uncurrying by default, I think @garyb has explained the problem pretty clearly. It's *hard*, and would make guaranteeing the correctness of the compiler much trickier. It would also be much less predictable how to interact with something through the FFI, since functions with the same type signature would have very different *call* signature.

The answer to functions you know will always be called with all the arguments is `FnN` and `runFnN`. The answer to other functions that might, in some places, be fully saturated, is a better optimiser for those cases specifically, which can be generalised as a supercompiler. While there were discussions about implementing a supercompiler for PS, I'm not sure what's the status of that.

Either way, uncurrying introduces more problems than it solves.

**Comment by dotneter-** [comment]
@garyb 
> I rely on partial application more often than fully saturated application.
Even in this case functions with more than two parameters can benefit from it.
For example ```foldl``` most of the time is used with two parameters, so you only need to create one function per call instead of three

**Comment by dotneter-** [comment]
> It would also be much less predictable how to interact with something through the FFI, since functions with the same type signature would have very different call signature.
I don't see a problem. You cannot just use functions like this in ffi (function cannot return function)
```
function k(a) {
  return function(b) {
    return a + b;
  }
}
```

**Comment by cryogenian** [comment]
I agree with @garyb's, you could use records as argument of function and this can be good example of alternative to existing `purescript-prelude`, `purescript-foldable-traversable` and so forth 
```purescript
class Foldable f where
  foldr :: forall a b. { foldFn :: { element :: a, accumulator :: b } -> b
                       , initialState  :: b
                       , foldable :: f a
                       } -> b
  foldl :: forall a b. { foldFn :: { accumulator :: b, element :: a } -> b
                       , initialState :: b
                       , foldable :: f a
                       } -> b
  foldMap :: forall a m. (Monoid m) => { foldMapFn :: a -> m
                                       , foldable :: f a} -> m


foreign import foldrArray
  :: forall a b. { foldFn :: { element :: a, accumulator :: b } -> b
                 , initialState :: b
                 , foldable :: Array a } -> b
foreign import foldlArray
  :: forall a b. { foldFn :: { element :: a, accumulator :: b } -> b
                 , initialState :: b
                 , foldable :: Array a } -> b

instance foldableArray :: Foldable Array where
  foldr = foldrArray
  foldl = foldlArray
  foldMap fm =
    foldr { foldFn: (\{element: el, accumulator: acc} -> fm.foldMapFn el <> acc)
          , initialState: mempty
          , foldable: fm.foldable
          }


instance foldableMaybe :: Foldable Maybe where
  foldr {initialState = z, foldable = Nothing} =
    z
  foldr {foldFn = f, initialState: z, foldable = (Just x)} =
    f { element: x, accumulator: z}

  foldl {initialState = z, foldable = Nothing} =
    z
  foldl {foldFn = f, initialState = z, foldable = (Just x)} =
    f { element: x, accumulator: z}

  foldMap {foldable = Nothing} =
    mempty
  foldMap {foldMapFn = f , foldable = (Just x)} =
    f x
```
Generate this code for `foldableMaybe`
```javascript
var foldableMaybe = new Foldable(function (__dict_Monoid_0) {
    return function (_5) {
        if (_5.foldable instanceof Data_Maybe.Nothing) {
            return Data_Monoid.mempty(__dict_Monoid_0);
        };
        if (_5.foldable instanceof Data_Maybe.Just) {
            return _5.foldMapFn(_5.foldable.value0);
        };
        throw new Error("Failed pattern match at Main line 48, column 1 - line 65, column 1: " + [ _5.constructor.name ]);
    };
}, function (_4) {
    if (_4.foldable instanceof Data_Maybe.Nothing) {
        return _4.initialState;
    };
    if (_4.foldable instanceof Data_Maybe.Just) {
        return _4.foldFn({
            element: _4.foldable.value0, 
            accumulator: _4.initialState
        });
    };
    throw new Error("Failed pattern match at Main line 48, column 1 - line 65, column 1: " + [ _4.constructor.name ]);
}, function (_3) {
    if (_3.foldable instanceof Data_Maybe.Nothing) {
        return _3.initialState;
    };
    if (_3.foldable instanceof Data_Maybe.Just) {
        return _3.foldFn({
            element: _3.foldable.value0, 
            accumulator: _3.initialState
        });
    };
    throw new Error("Failed pattern match at Main line 48, column 1 - line 65, column 1: " + [ _3.constructor.name ]);
});
```
Compare with `purescript-foldable-traversable`
```javascript
var foldableMaybe = new Foldable(function (__dict_Monoid_15) {
    return function (f) {
        return function (_355) {
            if (_355 instanceof Data_Maybe.Nothing) {
                return Data_Monoid.mempty(__dict_Monoid_15);
            };
            if (_355 instanceof Data_Maybe.Just) {
                return f(_355.value0);
            };
            throw new Error("Failed pattern match at Data.Foldable line 51, column 1 - line 59, column 1: " + [ f.constructor.name, _355.constructor.name ]);
        };
    };
}, function (f) {
    return function (z) {
        return function (_354) {
            if (_354 instanceof Data_Maybe.Nothing) {
                return z;
            };
            if (_354 instanceof Data_Maybe.Just) {
                return f(z)(_354.value0);
            };
            throw new Error("Failed pattern match at Data.Foldable line 51, column 1 - line 59, column 1: " + [ f.constructor.name, z.constructor.name, _354.constructor.name ]);
        };
    };
}, function (f) {
    return function (z) {
        return function (_353) {
            if (_353 instanceof Data_Maybe.Nothing) {
                return z;
            };
            if (_353 instanceof Data_Maybe.Just) {
                return f(_353.value0)(z);
            };
            throw new Error("Failed pattern match at Data.Foldable line 51, column 1 - line 59, column 1: " + [ f.constructor.name, z.constructor.name, _353.constructor.name ]);
        };
    };
});

```

**Comment by garyb** [comment]
All other considerations aside, things like #687 need addressing to improve performance before we even consider something like this which is a micro-optimisation in comparison.

**Comment by spion** [comment]
The benchmark above has some problems (Math.random() and confusing the JIT)

This one is a bit more illustrative:

https://jsperf.com/curried-vs-uncurried-functions/3

**Comment by dotneter-** [comment]
Here is my simple benchmark
foo1: 225.000ms
foo2: 2527.000ms
10 times slower


```
<html>
  <body>
      <script>
       var foo1 = function (x,y) {x + y};
       var foo2 = function (x) {
           return function (y) {
               return x + y;
           };
       };

       console.time("foo1");
       for(var i = 1; i < 10000000; i ++){
        foo1(1,2);
       }
       console.timeEnd("foo1");
       console.time("foo2");
       for(var i = 1; i < 10000000; i ++){
        foo2(1)(2);
       }
       console.timeEnd("foo2");

      </script>
  </body>
</html>

```

**Comment by dotneter-** [comment]
@garyb Why do you think it's  a micro-optimisation? It will affect almost every function call.

**Comment by dotneter-** [comment]
>you could use records as argument of function

Personally I think [something like this should be the only way](https://github.com/dotneter-/aeiar), but rewriting all PS libraries is too much.

**Comment by spion** [comment]
@dotneter- I think what garyb means is that there is a lot more low(er) hanging fruit to pick with the typeclass dictionaries stuff before this one is tackled :)

Also, using records will likely result with lots of tiny allocations and deallocations, which will be slower for performance-sensitive math code like the above *updating the benchmark*

**Comment by garyb** [comment]
It affects almost every function call by making the call much slower, but since most functions don't have a trivial implementation like `x + y` the overhead is miniscule compared to the function body. See the jsperf benchmarks linked by me and @spion.

**Comment by dotneter-** [comment]
>but since most functions don't have a trivial implementation like x + y the overhead is miniscule compared to the function body

I don't know about this. The function body is composed with calls of other functions. And at the bottom after all this calls there are only trivial operations like x + y.

**Comment by robotlolita** [comment]
@dotneter- `foo1` likely doesn't do any function calls in your example, it **should** be completely inlined, given that it's very trivial. `foo2` probably isn't because they don't do heavy lambda lifting. The difference you're seeing isn't from function call/allocation overhead, in any case. (If VMs were better at constant propagation, `foo1` would run at Infinite ops/sec, in fact, since it does nothing).

**Comment by phadej** [comment]
I see this discussion is not going anywhere.

As in Haskell, in Purescript, each function **takes only single** argument.
Multiple argument functions are *simulated** as return value is function itsel toof. Syntax assists here well, and makes function *feel* like they are multi-argument.

For example:

```hs
foldl :: (b -> a -> b) -> b -> List a -> b
foldl f = go
  where go acc []     = acc
        go acc (x:xs) = go (f acc x) xs 
```

looks like function taking three arguments, but it's actually function taking single argument and returning other function.

One could think that `go` could be compiled into two-argument javascript function. But it cannot, as we have no control on how the result of `foldl` (i.e. the `b -> List a -> b` part) is used.

```js
var foldl = function (f) {
	var go = function (acc) {
		return function (list) {
			// pattern match on list...
		}
	}

	return go;
}
```

Not to mention that `foldl` is *often* used curried, contrived example:
```hs
reverse = foldl (flip List.cons) List.empty
```

---

Smart enough compiler could inline functions aggressively and find opportunities to use "optimal" arity definitions. Yet for `foldl` you'd need to generate 4 variants (and purge unused):

```
foldl(f, acc, list)
foldl(f)(acc, list)
foldl(f, acc)(list)
foldl(f)(acc)(list)
```

Also if `acc` is of type `b -> c`, then `foldl f acc list x` is ok expression as well.

---

I hope that @dotneter- would see, that this is **hard** problem in **general**. It seems trivial in simple examples, but generally it's hard.

---

Another point:

Scala allows you to decide how function parameters are grouped, e.g.

```scala
def foldl[A,B](f: (B, A) => B, acc: B)(list: List[A]): B = ???
```

And then functions have to be applied all parameters in each argument group. **But** that's exactly what `FnN` does for you.

**Comment by spion** [comment]
@garyb the thing is that as far as I know, V8 cannot inline closures at all and cannot optimize away the allocation of a (fairly hefty) memory chunk necessary to create those closures... and when you multiple that to a call tree of a bunch of nested functions, it does add up to a lot.

**Comment by robotlolita** [comment]
@spion do you know if they've addressed that in their new optimising compiler?

**Comment by phadej** [comment]
Musing on `foldl` example

If it's written as:

```hs
foldl :: (b -> a -> b) -> b -> List a -> b
foldl f = runFn2 go
  where go = mkFn2 go' 
        go' acc []     = acc
        go' acc (x:xs) = go' (f acc x) xs
```

then compiler can see that `go'` is always "called" with two arguments, and compile it as two-argument JavaScript function. The `go = mkFn2 go'` would be simple assignment then. This kind of optimisation could be made only on local (non-exported) definitions only.

Then if inlining of `foldl` kicks in, and it's used with all arguments, then `runFn2` can go away too. But AFAIK PureScript doesn't inline across module boundaries, so the benefit would be quite small.

Also you'd need to teach compiler about `FnN`. 

And you (as a library writer) would need to explicitly insert them. I don't know if compiler could insert them correctly by itself (to my original `foldl` definition).

**Comment by dotneter-** [comment]
@phadej Why foldl cannot be compiled to this?
```
var foldl = function (f, acc, list) {
            // pattern match on list...
}
```

**Comment by garyb** [comment]
@phadej that would never be inlined though, the `runFn2` optimization only kicks in if you call it as `runFn2 fn x y`.

@dotneter- I think we've explained that a few ways above.

**Comment by robotlolita** [comment]
@phadej given that @paf31 mentioned being against whole-program optimisations, I think it's unlikely that optimisations across module boundaries land in PureScript (they make things tricky with modularity, too).

I also just realised you can't really do this kind of optimisation (uncurrying by default) without whole-program optimisation, since you can't know the call signature of an imported function from their types.

**Comment by joneshf** [comment]
@dotneter- You feel very strongly about this. Have you thought about taking some time and implementing it as an optimization step in the compiler? That seems like the next logical step.

**Comment by phadej** [comment]
@robotlolita 

> I also just realised you can't really do this kind of optimisation (uncurrying by default) without whole-program optimisation, since you can't know the call signature of an imported function from their types.

my point exactly! :)

--- 

> they make things tricky with modularity, too

GHC does that, PureScript *could* if we really want to. `INLINE` and `RULES` are cool yet maybe to powerful things.

**Comment by dotneter-** [comment]
> since you can't know the call signature of an imported function from their types.

You can if all function will have the same signature, all of them will be uncurried.

**Comment by garyb** [comment]
@robotlolita Yeah, I don't think the main compiler will ever do things of that nature. Regarding the supercompiler backend you mentioned earlier, it's definitely something I have an interest in working on, and some uncurrying could be done in that, but I've not had time to get into yet. There are a few majorish things I'd like to finish up in the main compiler first, like the core imperative representation.

@phadej we have some ideas about providing optimisation rewrite rules as part of the actual code #660, but pragmas are something I hope to never see in PS.

**Comment by garyb** [comment]
@dotneter- if it seems obvious to you how to fix this, then perhaps as @joneshf suggests you should try implementing it. You'll either prove us wrong, or gain an understanding of why we think it's extremely difficult to achieve.

**Comment by phadej** [comment]
@garyb If PureScript starts to inline functions, then you'd eventually need a machinery to specify which functions you'd prefer to inline and which shouldn't ever be inlined. Pragmas is only one way of doing that.

**Comment by garyb** [comment]
@phadej sure, I just meant pragmas specifically are something I'd rather not see. It should be part of the language's syntax proper.

**Comment by spion** [comment]
@robotlolita I just checked, and it seems that latest Chrome doesn't appear to suffer from this anymore - it can inline closures, except of course when they're passed as an argument to the function (which is of course not really possible to inline). I retract a part of previous statement.

**Comment by dotneter-** [comment]
>You'll either prove us wrong, or gain an understanding of why we think it's extremely difficult to achieve.

You you show me a simple PS and JS code which will illustrate, why you cannot have JS uncurried function? Because I think every function can be uncurried.

**Comment by phadej** [comment]
@dotneter- yes they can. But trust us, curried version is better default. Otherwise: 

>  you should try implementing it. You'll either prove us wrong, or gain an understanding of why we think it's extremely difficult to achieve.

**Comment by robotlolita** [comment]
@phadej does it work with the new Backpack modules as well? Since they only specify signatures, not implementation.

@dotneter- Well, suppose you have the following module:

```purs
module A (k)

k a b = b
```

Then, you write the following module, which imports `A`:

```purs
module B

import A only K

f = k 1 2
```

Now, suppose the compiler decides to compile `A` like this:

```js
exports.k = k;
function k(a, b) {
  return b
}
```

Of course, it would need to compile `B` like the following, so it would work:

```js
var k = require('A').k;

function f() {
  return k(1, 2)
}
```

But then, someone comes along and changes the code of `A` to:

```purs
module A (k)

k a = \b -> b
```

Which the compiler decides to compile as:

```js
exports.k = k;
function k(a) {
  return function(b) {
    return b;
  }
}
```

Now, even though the type of `k` remains the same, the way you *call* the function is entirely different. But `B` can't know that, since for `B` you haven't really changed the types in `A`.

The only way this would work is that, if for every compilation, the PureScript compiler recompiled *all modules* that your application depends on. In other words, it needs to do a whole-program optimisation, because modules depend now not only on the type signature of other modules, but also on which optimisations each module decided to incorporate. The same is true for FFI, but that's worse because now you need to manually revisit all your JS files and update them to the signature your compiler decided to use.

**Comment by dotneter-** [comment]
>Which the compiler decides to compile as:
exports.k = k;
function k(a) {
  return function(b) {
    return b;
  }
}

All of you are talking about this, but I don't understand why. I already said, all functions should be compiled to uncurried version. It's the main point.
So, it would be
```
function k(a, b) {
    return b;
}
```

Any function with type ```a -> b -> c``` should be compiled to ```function(a,b) -> c```

**Comment by natefaubion** [comment]
> Any function with type a -> b -> c should be compiled to function(a,b) -> c

I don't think this is a safe transformation, especially in a strict setting. For example, I could write a pure memoization using a lazy data structure.

```purescript
foo :: Int -> Int -> Int
foo x = let memo = // generate lazy memo table here
        in \y -> doSomething memo y

memoedFoo :: Int -> Int
momoedFoo = foo 42
```

Compiling that to any form other than curried form can have major implications to whether that works as expected.

**Comment by dotneter-** [comment]
```
foo x = let memo = // generate lazy memo table here
        in \y -> doSomething memo y
```
Shouldn't there be some side effect?

**Comment by natefaubion** [comment]
> Shouldn't there be some side effect?

Only if you consider laziness a side effect. http://conal.net/blog/posts/elegant-memoization-with-functional-memo-tries A canonical example is using a lazy list for fibonacci numbers.

**Comment by robotlolita** [comment]
@dotneter- you can't do that transformation and maintain semantic correctness of PureScript programs, in general. Consider, for example:

```purs
a b = (flip foldr) b
```

What should `a 0 (+ 1) [1, 2, 3]` be compiled to? `a` takes only one argument, but it returns a function that takes two more arguments. You could compile it to `function a(b, c, d)`, but how do you compile `flip`? Flip takes a binary function, but `foldr` takes *three* arguments. Since `flip f a b = f b a`, you can't really use `flip(foldr, 0, x => x + 1)([1, 2, 3])`, because foldr can only be called as `foldr(a, b, c)`, not `foldr(a, b)`.

**Comment by phadej** [comment]
@robotlolita in that example auto-currying could be inserted.

**Comment by natefaubion** [comment]
@phadej The problem of over/undersaturation can always be solved using a runtime, but its a goal of the main PS compiler to not use a runtime. This is how Elm works, it generates an uncurried function for however many arguments you declare, and then wraps it in curried version. Each function application then does a runtime check for saturation. If the number of arguments match then it calls the uncurried function, otherwise it calls the curried version. Note that this also adds overhead to every function call (in a different way).

**Comment by robotlolita** [comment]
@phadej sure, but keeping track of these things adds complexity to the compiler, without really giving you as many benefits as other optimisation approaches (with inlining/rewriting).

**Comment by dotneter-** [comment]
>I don't think this is a safe transformation, especially in a strict setting.

Ok. The problem is

```
complexCalc x = x
foo :: Int -> Int -> Int
foo x = let memo = complexCalc x
        in \y -> memo + y
```
```
var foo = function (x) {
    var memo = complexCalc(x);
    return function (y) {
        return memo + y | 0;
    };
};
```
We don't want to call complexCalc multiple times. So, the simple transformation would be wrong.
```
var foo = function (x, y) {
    return complexCalc(x) + y;
};
```
The solution could be something like this
```
var foo = function (x, y) {
    this.$memo = this.$memo != null ? this.$memo : complexCalc(x);
    return this.$memo + y;
};
```

**Comment by phadej** [comment]
> The eta expansion of an expression `e` is the expression `\ z -> e z`, where `z` does not occur in `e`. This only makes sense if `e` denotes a function, i.e. is of arrow type. Eta expansion delays the evaluation of `e` until the function is applied, and will re-evaluate `e` each time the function is applied.

I.e. auto-uncurring will change perforance semantics:

    bar :: a -> [b] -> c
    bar x = let y = expensiveComputation x
            in \ z -> y z


Compare using:

    function bar(x, z) {
        var y = expensiveComputation(x);
        return y(z);
    }

and

    function bar(x) {
        var y = expensiveComputation(x);
        return function (z) {
            return y(z);
        }
    }

If `bar` is curried post-definition, it will recalculate expensive computation on each new call anyway.

**Comment by natefaubion** [comment]
> The solution could be something like this
```
var foo = function (x, y) {
    this.$memo = this.$memo != null ? this.$memo : complexCalc(x);
    return this.$memo + y;
};
```

This doesn't make any sense. `this` would refer to the global object in JS.

**Comment by dotneter-** [comment]
> because foldr can only be called as foldr(a, b, c), not foldr(a, b).

function(a,b){return function(c){ return foldr(a,b,c)}

Compiler can still use currying.

**Comment by phadej** [comment]
@robotlolita I was just pointing out that is an example which could be solved, even it's not elegant :) And look, @dotneter- spotted that :)

The performance characteristics changes in eta-expansion / reduction are more convincing.

**Comment by dotneter-** [comment]
>This doesn't make any sense. this would refer to the global object in JS.
it just an example. Instead of global object, compiler can use special object.

```
var foo$scope = {};
var foo = function (x, y) {
    foo$scope.$memo = foo$scope.$memo != null ? foo$scope.$memo : complexCalc(x);
    return foo$scope.$memo + y;
};

```

**Comment by phadej** [comment]
The 
```
var foo = function (x, y) {
    this.$memo = this.$memo != null ? this.$memo : complexCalc(x);
    return this.$memo + y;
};
```

won't work, as it have to work for each `x`. Not the first one. Even you could attach mutable "memoization slot" to each function.

**Comment by natefaubion** [comment]
> 
```
var foo$scope = {};
var foo = function (x, y) {
    foo$scope.$memo = foo$scope.$memo != null ? foo$scope.$memo : complexCalc(x);
    return foo$scope.$memo + y;
};```

This is not equivalent to what I wrote. This creates a single memo table for the function, whereas mine creates a new memo table once you apply the first argument.

**Comment by phadej** [comment]
> ```js
var foo$scope = {};
var foo = function (x, y) {
    foo$scope.$memo = foo$scope.$memo != null ? foo$scope.$memo : complexCalc(x);
    return foo$scope.$memo + y;
};
```

and obviously is wrong. And if you track different `x` in table as

```js
var foo$scope = { $memo: {} };
var foo = function (x, y) {
    foo$scope.$memo[x] = foo$scope.$memo[x] != null ? foo$scope.$memo[x] : complexCalc(x); // 
    return foo$scope.$memo[x] + y;
};
```

Than that one will leak memory very bad.

**Comment by dotneter-** [comment]
>won't work, as it have to work for each x. Not the first one.
>This creates a single memo table for the function, whereas mine creates a new memo table once you apply the first argument.

```
var foo = function (x, y) {
    var memo = complexCalc(x);
    return function () {
        return memo + y;
    };
};
```

Yes, for this case compiler need to create a function, but signature is uncurried.

**Comment by robotlolita** [comment]
@dotneter- how do you know when to use `a(b, c)` and when to use `a(b, c)()`?

**Comment by natefaubion** [comment]
>
```
var foo = function (x, y) {
    var memo = complexCalc(x);
    return function () {
        return memo + y;
    };
};
```
This is not equivalent either. And can only ever run the memo table agains a constant value for y.

**Comment by dotneter-** [comment]
> how do you know when to use a(b, c) and when to use a(b, c)()?

I guess, you could do something like this.
```
function getValue(x){
   typeof x === "function" ? x() : x;
}
getValue(a(b,c))
```

**Comment by dotneter-** [comment]
>This is not equivalent either. And can only ever run the memo table agains a constant value for y.

Could you elaborate?

**Comment by natefaubion** [comment]
```js
var foo = function (x) {
    var memo = complexCalc(x);
    return function (y) {
        return memo + y;
    };
};
```
vs
```js
var foo = function (x, y) {
    var memo = complexCalc(x);
    return function () {
        return memo + y;
    };
};
```
The first function creates a memo parameterized on `x`, which can be used for many `y`s. The second creates a memo parameterized on `x`, but the `y` is constant. I can't reuse the memo for many `y`s.

**Comment by natefaubion** [comment]
Ie, your transformation would deoptimize my function. It is technically the same, but in the worst kind of way.

**Comment by dotneter-** [comment]
>I can't reuse the memo for many ys.
It can,

```
foo1 = foo 10

foo1 = function(y){return foo(10,y)}
```

**Comment by natefaubion** [comment]
I would suggest you try running these examples with a `console.log` thrown in for the `complexCalc`.

**Comment by paf31** [comment]
I think this should be closed and ideally the discussion moved to IRC or elsewhere. It's not a bug, and as a feature request, the details of the proposal need to be elaborated. There are good reasons why this is not being implemented, which have been explained well by others.

**Comment by dotneter-** [comment]
>The first function creates a memo parameterized on x, which can be used for many ys. The second creates a memo parameterized on x, but the y is constant. I can't reuse the memo for many ys.

Ok. I don't see any simple solution for this. Compiler should be able to separate ```(a -> b) -> c``` and ```a -> (b -> c)```.

**Comment by jutaro** [comment]
We use purescript for performance critical applications with Webgl. We
posted before about performance problems with purescript
https://groups.google.com/d/msg/purescript/oXs8j2iFnik/UO67FY2Kh-MJ .
Unfortunately we found little resonance.

With the examples in https://github.com/jutaro/purescript-webgl-examples we
can compare performance in a somehow realistic setting to pure javascript
code as given here: http://learningwebgl.com/blog/ . Roughly speaking the
purescript code takes at least twice the time of pure javascript, even
after trying all kinds of optimizations like STArrays for Matrices and
Vectors. So my guess would be that by removing useless closures we can get
a performance boost of around 30-70%, which would be very valuable for us.

As we are not versed in hacking on the purescript code generator, we are
thinking about adding an optimizer to psc-bundle, which analyse which
functions are only called fully saturated, and then transform the function
code and the caller code to the uncurried form. This concept could be
further refined and inlining would be the next thought on optimizing.

Any thoughts on this and any interest to work with us on this?

Jürgen



2015-12-03 18:14 GMT+01:00 Nathan Faubion <notifications@github.com>:

**Comment by dotneter-** [comment]
@jutaro Did you try Elm? It's also strict Haskell inspired language. You could try it, and if performance would be better, just switch to it.

**Comment by jutaro** [comment]
@dotneter- Hm, I make a proposal how to implement the optimization you
asked for, and you say I should try Elm. Are you kidding? Why did you ask
originally? Do you switch to Elm now?

2015-12-03 18:54 GMT+01:00 dotneter- <notifications@github.com>:

**Comment by dotneter-** [comment]
>Why did you ask originally? 
I am searching a suitable language for gamedev and I don't think purescript is the one. So, I will try Elm next.

**Comment by jutaro** [comment]
Ah I see. I considered to use Elm a year ago. Now I wrote the webgl bindings for purescript and we have >10000 lines of purescript, and it will not be so easy to port to Elm, Ghcjs or Haste. I would like to hear of your experiences with Elm.

**Comment by natefaubion** [comment]
@jutaro FWIW I think that bundling backends are the perfect place to put whole program optimizations like this. You can add your own runtime as needed. It would be neat to see what the performance difference is using Elm's dispatch method.

**Comment by mgmeier** [comment]
Something progress has been made on this end: We've implemented an "uncurry" optimization in ```psc-bundle```, which seems a more suitable place for it than the compiler itself.

If you're interested in the topic, here's the read-up: http://symbolian.net/2016/04/07/513
and this is the branch to check out: https://github.com/jutaro/purescript/tree/BundleAndOptimize

Please do confirm if the optimization works for you, or share figures showing that it doesn't.
Our interest is to get this as an option marked experimental into the mainline bundle tool some time soon, if the community agrees it's the right way to go.

**Comment by Pauan** [comment]
If anybody is still interested in this, [`rollup-plugin-purs`](https://github.com/Pauan/rollup-plugin-purs) now does both uncurrying and inlining. It can't uncurry every function, but it can uncurry most functions.
