### ISSUE TITLE
Syntax for multi-argument functions 

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#1695]
This is not as dramatic as #1686 :smile: 

What if we can do this 
```purescript 
addFn :: Fn2 Int Int Int
addFn = fn2 x y -> x + y 

class FunctorFn where 
  map :: Fn2 (a -> b) (f a) (f b)

instance maybeFunctor :: FunctorFn Maybe where 
  map = fn2 f fa -> case fa of 
    Nothing -> Nothing 
    Just a -> Just $ f a 

(<|$|>) :: forall a b f. (Functor f) => Fn2 (a -> b) (f a) (f b) 
(<|$|>) = map 

foo :: Maybe Int -> Maybe Int
foo mbInp = runFn2 addFn 2 <|$|> mbInp

bar :: Maybe Int -> Maybe Int 
bar mbInp = add 2 <|$|> mbInp
```

What do you think? Is it possible? Would it be helpful? Is it hard to implement?

**Comment by paf31** [comment]
The old syntax for this was `\(a, b, c) -> ...`. It was removed along with built-in multi argument function types. I'd prefer something like this in `L(k)`

As for whether or not this is a good thing generally, I'm undecided. It certainly doesn't hurt, but on the other hand, I try to avoid adding new syntax where possible, and I'm not sure if this is worth a whole new piece of syntax, and one which ties us to a library implementation.

**Comment by hdgarrood** [comment]
Sorry, what is `L(k)`?

I don't understand the benefit of this proposal over what we currently have in `purescript-functions`. For instance:

```purescript
addFn :: Fn2 Int Int Int
addFn = mkFn2 \x y -> x + y
```

and so on; you're only saving a few characters in most places. Is the idea that this should just make the syntax a bit nicer? Or would it affect the generated code?

**Comment by cryogenian** [comment]
There is no difference between current generated optimized code and `fnN a b c ... -> ` 
The idea is to remove dependency of `purescript-functions` library and make this built-in.

**Comment by paf31** [comment]
`L(k)` just means you can commit to what you're parsing by looking at `k` symbols at the start of the input: https://en.wikipedia.org/wiki/LL_parser

**Comment by kRITZCREEK** [comment]
Did we decide on `purescript-functions` being the way to explicitly use uncurried functions and eventually have the automatic flattening as an optimizing step? Should we put this to a vote?

**Comment by paf31** [comment]
> Did we decide on purescript-functions being the way to explicitly use uncurried functions and eventually have the automatic flattening as an optimizing step?

I think so. I'm going to close this, since this is the sort of thing that's best solved in libraries in my opinion, even if it's slightly inconvenient.
