### ISSUE TITLE
Fresh name collision from `do` desugaring

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1697]
This came from purescript-contrib/purescript-profunctor-lenses#17. It's awesome.

``` purescript
module Test where

import Prelude

x :: forall m. (Monad m) => m Unit
x = do
  _ <- pure unit
  pure unit

y :: forall m. (Monad m) => m Unit
y = do
  _ <- pure unit
  pure unit

wtf :: forall m. (Monad m) => m Unit
wtf = do
  _ <- pure unit
  let tmp = _2 1
  pure unit
```

There's no `_2` in scope, but:

```
  A function of type

    Unit

  can not be applied to the argument

    1

while applying a function _2
  of type Unit
  to argument 1
while inferring the type of _2 1
in value declaration wtf
```

Also, you can't take out either of the definitions above `wtf`, and you can't take the binds out of them either, otherwise this doesn't happen. Also there needs to be a bind above the `_2` usage in `wtf`, otherwise you get the expected:

```
Unknown value _2
```

The `_2` is a fresh name we generate:

```
var wtf = function (__dict_Monad_2) {
    return Prelude.bind(__dict_Monad_2["__superclass_Prelude.Bind_1"]())(Prelude.pure(__dict_Monad_2["__superclass_Prelude.Applicative_0"]())(Prelude.unit))(function (_2) {
        return Prelude.pure(__dict_Monad_2["__superclass_Prelude.Applicative_0"]())(Prelude.unit);
    });
};
```

**Comment by garyb** [comment]
I have two ideas for ways to fix this:

1. A quick fix would be to prefix generated names with `$` instead of `_`, as we definitely don't allow identifiers to start with that, and we use it for other generated0name-things.
2. Generated names shouldn't be in the same namespace as user provided names at all, that way we can ensure that when we use them during codegen they can be further refined to avoid collisions with things in scope. I'm not thinking of anything crazy here, just adding something else to the `Ident` sum for this. We could actually generate much more pleasant names this way too... well, single letter variables perhaps rather than `_2` type thing. Equally meaningless, but less ugly at a glance.

**Comment by paf31** [comment]
I like the idea of having separate namespaces, but would that work given that they share the same "target namespace" in the generated JS?

I'll happily take `$` as a workaround though. A few other places use the same scheme (dictionary names as well, I think).

**Comment by garyb** [comment]
Yeah, it still ends up in the same target namespace, but that's what I was saying about further refinements during codegen - kinda like the workaround for module names that collide with data constructors/classes.

**Comment by paf31** [comment]
Gotcha. Maybe the renamer is the place to handle it then?

**Comment by garyb** [comment]
Oh yeah, that would definitely be the place! For some reason I thought that happened earlier in the pipeline.
