### ISSUE TITLE
Minimal source spans

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1702]
Right now, source span tracking is greedy, and it will list the span of a term as all the way up to where the next term begins. It would be nice to have the minimal span (ie. removing white space from the span).

**Comment by paf31** [comment]
:+1:

**Comment by natefaubion** [comment]
It seems like this is mainly due to https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Parser/Lexer.hs#L214

Would it make sense to eat the whitespace in `parsePositionedToken` instead of in `parseToken`?

**Comment by paf31** [comment]
Yes, that's very possible. Worth a try anyway.

**Comment by natefaubion** [comment]
Unfortunately its not that easy :|

The token parser just gets the start position, then in the AST parser it uses the start position, and then whatever position the parser has advanced to as the end position. Then maybe you could use the end position of the _most recently consumed_ token rather than the start position of the next token. I don't know if Parsec supports something like that.
