### ISSUE TITLE
Option to make psc to print a summary of what it did

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1705]
Currently, to speed builds up, `pulp` scans over all the source files and looks for the most recently modified one, and uses that to decide whether or not the build needs to be repeated. Of course, this doesn't make a huge difference if you're just running `pulp build`, because `psc` already works incrementally. However if you're doing `pulp browserify -O`, which needs to call `psc-bundle` and then `browserify`, it does make a big difference. It also seems a bit silly to have to look at file modification times, because of course `psc` already does this.

We could simplify `pulp` and avoid this scanning (which adds around half a second on my machine for a reasonably-sized project) by adding a flag to `psc` to ask it to print a summary of what changed; maybe something like:

```
{ rebuilt: ["Control.Monad.Eff", ...], upToDate: ["Prelude", ...] }
```

This might be useful in other contexts, too. Does that sound sensible?

**Comment by paf31** [comment]
Sounds sensible. Maybe this makes sense as a part of the JSON errors changes.

**Comment by hdgarrood** [comment]
Just stumbled upon this again; incidentally, this feature was removed from pulp, so unless we can think of any use cases for this I vote we close it.

**Comment by paf31** [comment]
Sounds good to close. We can reopen it again if we think of anything.
