### ISSUE TITLE
Fast recompilation by keeping externs files in memory

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1712]
I would like to support a new compilation mode which only recompiles a single module (the one which is active in your editor) and keeps its dependency externs files in memory. This is the approach taken in Try PureScript and it is very fast.

@user471 also suggests a command line option to skip code generation for a further speed up in some workflows.

**Comment by paf31** [comment]
For reference, this is the approach I'd like to use

https://github.com/paf31/purescript-playground/blob/9fe9f44efd339fe05dc8b9c68b305898973bad95/src/index.js#L70-L83

**Comment by garyb** [comment]
I was thinking about this after we talked about it the other week - shouldn't the compiler already do this? If we have a set of modules somewhere separate from the temporary input for tryps, then I would have thought they will only build once anyway - there's nothing the temporary input can do to modify these standard source files, so psc shouldn't recompile them as the timestamps will be in sync, and there will be no way to insert a dependency "above" them that would cause them to be recompiled.

**Comment by paf31** [comment]
Yes, but the input files and output files have to exist. I'd like to avoid parsing the input files at all, and just assume the output files will have been compiled already. The externs would be added to the dependencies of every module.

**Comment by garyb** [comment]
We still parse purs inputs even if the timestamp matches the compilation products then? Why do we use the timestamp mechanism at all then? :smile:

**Comment by paf31** [comment]
We need to know what order to build modules in, so we need to parse all source files to figure that out.

**Comment by garyb** [comment]
Ah of course, as we talked about storing that stuff in the externs files too. I guess doing that would also solve this problem then?

**Comment by paf31** [comment]
We can't do that since the externs wouldn't update if a module's imports did. The solution seems to be to parse only as far as the module imports, if speed is the concern. But you still have to parse every input file.

In this case, I'm assuming the externs files represent modules which are compiled and won't change.

**Comment by paf31** [comment]
I started working on this but ran into issues with module imports. Will continue to work on this, because I think it could be very good for incremental compilation, since we don't need to reparse anything that won't ever be changed (e.g. `bower_components` in most cases).

**Comment by paf31** [comment]
This is implemented in Try PureScript now, and it's very fast. I think it would be good to provide this as an alternative compilation mode for editors.

**Comment by kRITZCREEK** [comment]
:+1:

**Comment by user471** [comment]
:+1:

**Comment by paf31** [comment]
We should also do this in PSCi.

**Comment by paf31** [comment]
This would be a good fit for `psc-ide`, since the externs files are already (re)loaded and cached in memory.

cc @kRITZCREEK

**Comment by kRITZCREEK** [comment]
I think this could be a nice fit for http://www.meetup.com/de-DE/Bay-Area-PureScript-Meetup/events/229372024/?eventId=229372024.

**Comment by paf31** [comment]
Definitely. I'll happily work on that then.

**Comment by kRITZCREEK** [comment]
I'll join in! :+1:

**Comment by kRITZCREEK** [comment]
Close this? :)
