### ISSUE TITLE
Warn for unused declarations

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1713]
For example:
```
module Thingy (thing1) where

thing1 :: Int
thing1 = 1
thing2 :: Int
thing2 = 2
```

If a declaration is neither used in its defining module nor exported from that module, then it might be nice to emit a warning about this. So the above example could emit a warning because `thing2` is unused.

**Comment by garyb** [comment]
#1670 :smile:

**Comment by hdgarrood** [comment]
Oops. I'm almost certain I remember searching for this first...
