### ISSUE TITLE
psc-publish: warn if you forgot a LICENSE?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1714]
`psc-publish` could warn or maybe even error if:

* `bower.json` has no LICENSE specified
* LICENSE file does not exist

Maybe we could also start rejecting packages without a license in pursuit too.

**Comment by paf31** [comment]
:+1:

**Comment by hdgarrood** [comment]
Just realised I didn't make this clear before - my vote is for it to be an error.

**Comment by hdgarrood** [comment]
Thinking about this a bit more - I think we should have a whitelist of open source licences, and reject Pursuit uploads which are not licensed with an open source licence.

**Comment by michaelficarra** [comment]
@hdgarrood That's going to be a touchy subject. Do you define open source as OSI-approved, FSF-approved, Copyfree-approved, etc?

**Comment by hdgarrood** [comment]
Definitely nothing anywhere near as strong as FSF approved. I just mean something that we can be sure we won't have any issues displaying documentation for and redistributing (if/when pursuit becomes a registry). Also, it's quite easy to forget to license your code even if you meant to, that's the kind of problem I'm really thinking about.

**Comment by michaelficarra** [comment]
In that case, I think the existence of the LICENSE file is good enough.

**Comment by hdgarrood** [comment]
Yeah - on second thoughts, I agree.

**Comment by paf31** [comment]
One problem is that we don't require a package to be uploaded by the author. The `LICENSE` file might be empty, or say "You are not allowed to redistribute the documentation", at which point we'd pretty much have to delete a package from Pursuit if someone uploaded it :smile:
