### ISSUE TITLE
Handling of prime symbols in identifiers

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1717]
Continuation from the discussion in #1710.

The behaviour that was merged renames `'` to `ʹ` (unicode prime symbol), and will append a number if an identifier with the unicode-prime-name is already in scope.

Options brought up so far:

1. Remove primes entirely, but support the unicode version.
2. Treat `'` and `ʹ` as identical, and rename `'` to `ʹ` during codegen. This is fine for ES5.
3. Replace prime with `$` or `_` in codegen, for ES3 compatibility.

Option 2 (or "option zero", the currently-merged behaviour) is my preference, as I think prime is a common enough symbol that some special handling is worthwhile.

I think Option 1 is problematic because prime is a common symbol, and there are many variants on things that look like it or apostrophes in unicode, so not taking the most obvious candidate will give a less than wonderful user experience if primes are used in top-level definitions, as without the knowledge of exactly which unicode symbol was used, it will be non-obvious which one was used.

**Comment by tfausak** [comment]
I'll throw in a vote for option 1. Pretty much every other programming language gets by without apostrophes in identifiers. Even in languages where it's allowed, like Clojure, they aren't common. Haskell itself mostly uses primes to differentiate between lazy and strict values. PureScript obviously doesn't have that problem. 

I think allowing the Unicode prime is fine. It will discourage people from exporting values that use them, unless they're already fans of [base-unicode-symbols](http://hackage.haskell.org/package/base-unicode-symbols). But you can still use them locally if you've got your editor set up correctly.

**Comment by garyb** [comment]
@tfausak they're even more commonly used to distinguish between alternate versions of things (following the mathematical notation convention) in `let`/`where`, and that's the case that will bother me most if they go actually.

**Comment by paf31** [comment]
Mine is a hesitant vote for 1). I see the value of primes, but there are other options, and my only really motivating use case is to avoid shadowing in `where` clauses (I have a hard time formalizing what "alternative versions" of a thing means), and I can get by with underscores and numbers there. At the top-level, I almost never use a prime.

**Comment by jdegoes** [comment]
Option 2. At some future point in time, one could deprecate ' if code moves toward Unicode.

**Comment by tfausak** [comment]
I agree with @paf31; underscores and numbers work just as well as primes for avoiding shadowing and are easier to grok. You never see questions like, "What does the `_` mean in `x_`?". On the other hand...

- http://stackoverflow.com/questions/5673916/apostrophe-in-identifiers-in-haskell
- http://stackoverflow.com/questions/10363206/what-does-apostrophe-means-in-haskell
- http://stackoverflow.com/questions/1207649/the-meaning-of-in-haskell-function-name

**Comment by garyb** [comment]
Things ending with `_` means something else to me though, as per its Haskell convention: "this applicative/monadic function is a version that only performs effects and returns `Unit`"

**Comment by tfausak** [comment]
You could say the same thing about `'`: "This function is a version that is strict (as opposed to lazy)." Heck, you could say the same thing about `1`: "This foldable function is a version that requires the container to be non-empty."

**Comment by jdegoes** [comment]
Primes have a long and prosperous history in math, which corresponds closely with how they're used in PureScript and Haskell. They make code much more readable (it's easy to count ', impossible to count _ for many fonts; and numerals incorrectly imply parallel versions of something rather than temporal versions).

**Comment by garyb** [comment]
Yeah, and actually I do think that about `1`, another reason why I wouldn't use it for alternative versions of things, usually. The `'` strict/lazy thing didn't occur to me at all until you mentioned it (I'm not saying that's a good argument, just my 2p).

In the case of "primes for alternative versions", Halogen is a case where I think it's used to good effect:
```
ComponentDSL s f (QueryF s s' f f' g p)
vs
ComponentDSL s f (QueryF s s_ f f_ g p)
vs
ComponentDSL parentState parentQueryAlgebra (QueryF parentState childState parentQueryAlgebra childQueryAlgebra effects slotAddressType)
```

Again, it's just my opinion, but the underscore version looks super weird, and the last example although most explicit, is harder to follow than the single-letter version, if you're familiar with the `sfgp` convention.

**Comment by paf31** [comment]
I think any choice of `_`, `1` or `'` to indicate "but with no return value", "but non-empty" or "but strict" is very poor when we have a whole language's worth of alternatives.

```haskell
foldl :: (a -> b -> a) -> a -> [b] -> a
foldlStrict :: (a -> b -> a) -> a -> [b] -> a
foldlNonEmpty :: (a -> a -> a) -> [a] -> a
```

Better no?

**Comment by garyb** [comment]
Agreed. Although I'm not sure of a good word suffix equivalent to `_` off the top of my head - and we already have `traverse_`, `for_`. Void perhaps, since it's similar to what `void` does?

**Comment by tfausak** [comment]
I agree! 

@jdegoes is right that primes are seen a lot in math and physics. I don't think that means they should be in a general-purpose programming language, though. Especially when you consider that they're used for [lots of different things](https://en.wikipedia.org/wiki/Prime_(symbol)#Use_in_mathematics.2C_statistics.2C_and_science). Is `f'` the strict version of `f`, the derivative of `f`, or just some variant of `f`?

**Comment by paf31** [comment]
Yeah, I struggled for a second there :smile: I came up with `Discarding` eventually, but `Void` would work.

**Comment by jonsterling** [comment]
I prefer option 2.

Disallowing primes entirely seems pretty egregious, since it is essentially a JavaScript problem (which many people came to PureScript to avoid); and having to type in unicode characters will be a non-starter for a lot of people.

In most code, I prefer not to have "primed" versions of things, but sometimes it makes sense.

**Comment by garyb** [comment]
@tfausak All three of those things fall under "variant of `f` (nonspecific)", whereas `f1` and `f2` could be variants of `f` or two entirely different `f`s. It's that representation of "some variant" that makes prime so useful.

**Comment by paf31** [comment]
Mathematics is full of overloaded notation and abuses of notation, and in many cases requires contextual knowledge to read things, not a property you want of a programming language IMO.

**Comment by paf31** [comment]
My main issue with 2) is that it makes it harder to find the definition site of a name. Also it's completely arbitrary, potentially confusing, and sets a bad precedent (is prime really that unique in this regard?)

**Comment by jonsterling** [comment]
@paf31 

- I don't think it makes sense to impose philosophical commitments on identifier naming through a language's concrete syntax.

- Why does (2) make it hard to find the definition site of a name? Users should just use `'` in all cases, so you can always just search for that. The only difference is that this is renamed in code-gen, unless I have misunderstood the proposal.

- The prime *is* unique in the sense that it in the ML/Haskell family of languages, it's the only identifier-letter which cannot be used in all identifiers in PureScript.

**Comment by garyb** [comment]
I did forget an option:

Option 4: we perserve the old mangling and forget this issue ever came up? :see_no_evil: :hear_no_evil:

**Comment by natefaubion** [comment]
I vote option 4. It shouldn't be an FFI issue because I thought things were exported with their actual name, as opposed to the escaped name. Only local definitions have mangled names anyway and its a mangling everyone already expects.

**Comment by paf31** [comment]
I don't think type arguments like the Halogen example need to change, since they don't affect codegen. Just function names.

I'm fine with option 4 as well. My goal is compatibility with JS identifiers, but if we can say `'` is the only exception we're ever going to make, I think that's an ok compromise, and escaping it as `$prime` is fine too. I'll chalk it up to an unfortunate early decision on my part to emulate Haskell :stuck_out_tongue: 

So under option 4, we'd have:

- Identifiers start with a lower case (unicode) letter or an underscore
- Identifiers continue with upper and lower case (unicode) letters, underscores, primes and numbers
- Primes are escaped at the top-level as `$prime` and inside declarations using renumbering
- The `$xyz...` "namespace" is reserved for generated identifiers

Yes?

**Comment by natefaubion** [comment]
Why do we need renumbering? What's wrong with `foo$prime$prime`. I know its "ugly" but that's it.

**Comment by paf31** [comment]
That's the current implementation as of the last PR. It's the only bit I'd consider changing if we picked 4).

**Comment by natefaubion** [comment]
One point for 2 is that, while we can export identifiers with ticks now with commonjs, it doesn't work with ES6.

**Comment by paf31** [comment]
I'm not a fan of having two ways of exporting things with mangled names. If we pick 4) then I'd like to see the mangled versions of exports removed for both operators and things with primes.

**Comment by garyb** [comment]
I think I need to change what's currently committed. Currently it:

1. converts `'` into unicode prime: `a'` -> `aʹ`
2. if there already an `aʹ` in scope, it names it `aʹ1`
3. if there's an `aʹ1` it gets named `aʹ2`
4. etc.

So instead we want to drop any kind of `Renamer` rule for primes, and fall back to 1:1 `'`:`$prime` mangling?

Making the export naming consistent is fine by me too, but I think we should hold off on that change when we make the breaking changes for aliases in 0.9 rather than doing it now, as so far we've preserved backwards compatibility.

**Comment by natefaubion** [comment]
To be fair I'm the only one who voted to keep the current mangling.

Knowing I have this sort of power changes everything.

**Comment by garyb** [comment]
:laughing:

**Comment by paf31** [comment]
There are, I think, some packages using the existing `exports["foo'"]` approach in the FFI. I'm not sure what we should do about that, if anything. Maybe we just need to keep things as is, in the FFI, for now.

**Comment by garyb** [comment]
Yeah, that's why I was suggesting we make the change to export when we make aliases required, as that will be a breaking change anyway. Perhaps we should add a this-will-be-broken warning for foreign imports of primed identifiers too?

**Comment by hdgarrood** [comment]
Pulp is currently using `exports["foo'"]` in the FFI, but I wouldn't mind too much if we had to change that. I think the `_Impl` convention is more common anyway.

I personally wouldn't mind losing `'`. But, having different identifier syntax for terms and type variables strikes me as weird. Is this really a good enough reason for those to diverge?

I do think there are situations where using some kind of symbol as a suffix is preferable to a suffix based on an English word. For functions exported from modules, I would tend to avoid symbol suffixes. For single-letter variables in tiny scopes, I would be much more likely to use them.
