### ISSUE TITLE
Type System Wishlist

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1719]
This issue is here for me to track things I want to finish in the typechecker in `0.8.x`.

- Constraint inference (#202)
- Get rid of `meet` judgment
- Constraint kinds (#1764)
- Functional dependencies (#1580)
- Remove duplicate rows restriction (#2311)
- Ability to pass around error "stack" (#1433)
- Tidy up skolem escape check (#2310)
- Restrict unification to monotypes (#2312)
- Document the type system properly (https://github.com/purescript/roadmap/issues/43)
- Row constraints (#469)
- Polymorphic labels (#823)
- Instance chains
- Kind polymorphism (#1763)

**Comment by natefaubion** [comment]
Is let generalization out of the question? What about a pony?

**Comment by paf31** [comment]
:smile: I can certainly look at let generalization. Let's put it under stretch goals, because I'm not sure how it plays with Rank N. Perhaps I could deal with it as part of constraint inference, since we'll want to generalize over constraints too.

**Comment by jdegoes** [comment]
This looks really awesome! Constraint inference and fundeps are big wins that will greatly increase the expressive power of PureScript and clean up a lot of code.

Related, I'm not sure if this would have any impact on the type system, but something like [instance chains](https://ghc.haskell.org/trac/ghc/ticket/9334) would solve a lot of boilerplate pains in day-to-day PureScript coding.

**Comment by paf31** [comment]
Good point, I've added instance chains to the stretch goals list. Chances are, most of those, if not all, will end up being bumped to some later release, but if I have time, I'll try to work on some of them. Basically, we've had a bug fix release and I'd like to spend 0.9 working only on neat features in the typechecker :smile:

**Comment by garyb** [comment]
- kind polymorphism?

**Comment by paf31** [comment]
I'll put that on the stretch goals list too, but I'm not really sure how to implement it yet. It's not clear to me if kind information has to live at both the term and type levels if we have polytyped values with polykinded types.

**Comment by paf31** [comment]
Basically, the first list is the stuff that actually makes it inconvenient to use PureScript today (the `MonadState` issue, constraint generalization etc.)

Everything else is "nice to have" to a certain extent.

**Comment by garyb** [comment]
Yeah, I meant it as a nice to have :) It would just be great for those cases like `Exists` and `Proxy` where we need to define kinded variations.

**Comment by PipocaQuemada** [comment]
What do you mean by "Remove duplicate rows restriction"?

**Comment by LiamGoodacre** [comment]
I don't know what it's called (or if it makes sense) but I've wanted to do things like this:

```purescript
instance eqFree :: (Eq a, Eq (f a)) => Eq (Free f a) ...
-- or
instance eqFree :: (forall i. Eq i => Eq (f i), Eq a) => Eq (Free f a) ...
```

Which can currently be solved by having a higher version of the class in question:

```purescript
class Eq1 f where
  eq1 :: forall i. Eq i => f i -> f i -> Boolean

instance eqFree :: (Eq1 f, Eq a) => Eq (Free f a) ...
```

But that's kind of annoying.  I'd rather reuse the existing class.

**Comment by jplatte** [comment]
@LiamGoodacre It's called quantified constraints and had an issue (#1015) that was closed for no obvious reason, which you actually commented on yourself :D

I'd actually be interested in implementing this myself, if it's not too hard and I can get a few hints as to where to start (unless there are reasons we don't want to have it?)

**Comment by LiamGoodacre** [comment]
@jplatte oops! 😄

**Comment by phadej** [comment]
I'd not spend any time with *let-generalisation*. [Let Should Not Be Generalised](http://research.microsoft.com/en-us/um/people/simonpj/papers/constraints/let-gen.pdf)

**Comment by phadej** [comment]
Equality constraints, type families, functional dependencies are all a bit related.

I wonder if it makes sense to have small dependent type (e.g. calculus of constraints - e.g. [morte](https://github.com/Gabriel439/Haskell-Morte-Library)) language as (core) type language, i.e. terms of that language would be types of PureScript.

**Comment by paf31** [comment]
@phadej I gave it a go recently, but it was tricky for precisely the reasons described in the paper. I think you're right that it's not worth the hassle.

My current plan in the short term (pre 1.0) is to implement equality constraints, so that the solver can proceed in stages, between type class constraint solving and unification. After that, I might look at things like type families, but I'm not sure yet.

**Comment by LiamGoodacre** [comment]
Illtyped assertions: compile error/warning if some expression is well typed.

When implementing a complex idea that is "correct by construction", it is often useful to write out invalid cases and make sure that they don't typecheck.

Silly example:
~~~purescript
illtyped "Cannot add boolean to string" = true + "false"
~~~

**Comment by hdgarrood** [comment]
@LiamGoodacre If we copied GHC's `-fdefer-type-errors` (#1868), we might be able to implement this on top of that. For example, see https://hackage.haskell.org/package/should-not-typecheck.

**Comment by phadej** [comment]
@hdgarrood `-fdefer-type-errors` needs some lazyness, and maybe explicit annotating would be better, i.e.

```hs
-- magic, that would be needed for typechecker
deferTypeError :: a -> b

illtyped :: Text -> Lazy a -> Assertion

illtyped "Cannot add boolean to string" $ pure $ deferTypeError $ true + "false"
illtyped "Failing test" $ pure $ deferTypeError $ true && true
```
will translate into
```js
illtyped("Cannot add boolean to string", function () { throw DeferredTypeException("some error")});
illtyped("Failing test" $ function () { return true && true; });
```

**Comment by LiamGoodacre** [comment]
@hdgarrood @phadej thanks for the reference/ideas.  I was originally meaning compile-time assertions.

(I don't really want to fill this issue with a discussion of this particular idea - should I move this to a new issue, or is it okay here?)

As a kind of intermediate approach; what do you think about having the following:

```purescript
illtyped :: forall a. a -> TypeError
maybeIlltyped :: forall a. a -> Maybe TypeError
```

Although `illtyped` and `maybeIlltyped` probably shouldn't be functions, and should just be syntax like `if`/`case` because I don't think it ever makes sense to pass `illtyped` to another function.

When applying `illtyped`: if the argument expression is well typed, then we get a compile error.  If the expression is not well typed, then we get a `TypeError` value.  Applying `maybeIlltyped` never causes a compile error.  If the expression is well typed, the expression is equivalent to `Nothing`.  Otherwise `Just` of the `TypeError`

```purescript
-- compiles, expression is not well typed
yep :: TypeError
yep = illtyped (true && "false")

-- should fail at compile time because the expression is well typed
nop :: TypeError
nop = illtyped (1 + 2)

-- always Just of some type error
mayYep :: Maybe TypeError
mayYep = maybeIlltyped (true && "false")

-- always Nothing
mayNop :: Maybe TypeError
mayNop = maybeIlltyped (1 + 2)
```

Possibly later adding the ability to somehow inspect type errors (not like this - needs more thought):
```purescript
import Language.TypeError (TypeError(Mismatch))
test = yep === Mismatch ["Prim", "Boolean"] ["Prim", "String"]
```

**Comment by hdgarrood** [comment]
I think this should go into a separate issue at this point, yes. Also, I don't think we have enough information to evaluate this proposal properly just yet - can you come up with some concrete examples of the problem you're trying to solve, for example?

**Comment by paf31** [comment]
I've broken this down into separate issues. Closing.
