### ISSUE TITLE
Hide warnings

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1720]
Could you add ```--no-warnigns``` flag?
For example, I add type declaration when I think it's necessary, so there is no reason to remind me about this every time.
Also, psc 0.8 shows warnings after recompilation. Is it a bug?

**Comment by garyb** [comment]
Repeated warnings after recompilation if no code changes is a bug, if that's what you're seeing?

I don't think it's likely we'll add a `--no-warnings`... everything we warn about is either something that looks like it might be a mistake and there is a better alternative, or something that is pretty universally accepted as a good practice for code comprehension (like defining types at the top level). Besides, in this case the warning even gives you a copy-and-pasteable fix for the warning.

**Comment by user471** [comment]
Every time I run ```psc "bower_components/**/*.purs" "src/**/*.purs"``` I get the same list of warnings.

>everything we warn about is either something that looks like it might be a mistake and there is a better alternative, or something that is pretty universally accepted as a good practice for code comprehension

No one is arguing with that. Warning is important and useful, but not all the time. If I am prototyping a new application, the type of the function could change many times a day, so every time I need to manually fix the function's type. 

Or maybe I am just writing a script and will delete it after use, do I still need warnings?

**Comment by paf31** [comment]
But I can make the counterargument: if you don't care about them, they aren't doing any harm.

**Comment by hdgarrood** [comment]
If you don't care about them, but you're writing a library, they make life difficult for downstream authors who do care about warnings in their own code. But I think we might have already discussed creating some kind of tool that takes the `--json-errors` compiler output and displays only the warnings you're interested in, somehow.

**Comment by paf31** [comment]
Then they act as a signal of upstream library quality :smile: 

I like the idea of fixing this in tooling.

**Comment by user471** [comment]
>they make life difficult for downstream authors who do care about warnings in their own code.

If you publish you code then yes, you code should not have warnings.

**Comment by user471** [comment]
>I like the idea of fixing this in tooling.

Instead of using one flag every tool will need to implement this feature.

**Comment by paf31** [comment]
@user471 Just replace your build command with 

```bash
psc $1' --json-errors 2> >(jq '.warnings | map(select(.errorCode | test("ShadowedName|DeprecatedClassExport")))')
```

or whatever set of warnings you want to see.

Put that in a script, and tell your editor to run that instead of `psc`.

**Comment by hdgarrood** [comment]
> Instead of using one flag every tool will need to implement this feature.

I was imagining that there would just be one tool which filters warnings somehow, that editors or build tools could talk to. And I think it would be great for such a tool to be unconstrained by the compiler release schedule.

Besides, you very rarely want to silence literally every warning, I think, so I don't think the flag you're suggesting is a good design.

I think realistically, based on experience from this and other language communities, there will always be some libraries which emit warnings. In particular, the current core library set will emit hundreds with 0.8.0-C1 because new warnings were introduced.

**Comment by hdgarrood** [comment]
Ok I just saw @paf31's response after my last comment. Oh my god, that's amazing. I need to learn how to use `jq` properly.

**Comment by paf31** [comment]
It's like `sed` for JSON :smile:

**Comment by paf31** [comment]
So can we close this then?

**Comment by user471** [comment]
What about simple editors which cannot work with json and your only option is plain text?

**Comment by hdgarrood** [comment]
Can you give an example of one? If it's capable of calling your build command for you, it's probably fairly complex already, I would have thought.

**Comment by paf31** [comment]
@user471 In that case, use `jq` to turn the JSON back into text. Point is, I think this is best handled elsewhere, and not a job for the compiler.

**Comment by paf31** [comment]
Or write a script to do it. Or make a PR on Pulp. Lots of options are available.

**Comment by bergmark** [comment]
If anyone comes here and gets disappointed, use https://www.npmjs.com/package/purescript-psa!
