### ISSUE TITLE
Incorrect warnings for qualified imports

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1721]
Not sure if you knew this already, but with 0.8.0-rc1:

```purescript
module Main where

import Prelude (..)
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console as Console

main :: Eff _ Unit
main = Console.log "hi"
```

produces:
```
Module Control.Monad.Eff.Console has unspecified imports, consider using the explicit form:

  import Control.Monad.Eff.Console (log)
```

I was expecting no warning to be generated, because it's a qualified import.

Aside, it's a bit unfortunate that `psc --version` produces `0.8.0.0`, but the release page says `0.8.0-RC1`. I'm fairly sure the latter is a valid version according to Cabal anyway?

**Comment by garyb** [comment]
Yeah, that's definitely a bug, thanks.

**Comment by tfausak** [comment]
:+1:
