### ISSUE TITLE
Cannot define operators for imported values

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1722]
With a module that defines a function like this:

``` purescript
module A where
f :: forall a b. a -> b -> a
f x _ = x
infix 5 f as @
```

You cannot define an operator version of `f` in another package. 

``` purescript
module B where
import A (f)
infix 5 f as @@
-- Warning: The import of module A is redundant
-- Error: Value f is undefined.
```

``` purescript
module C where
import A as A
infix 5 A.f as @@@
-- Error: Unable to parse module: unexpected qualifier expecting identifier or symbol
```

This is with PureScript v0.8.0-rc.1

**Comment by tfausak** [comment]
I thought I would be able to define a local function as an alias of the imported function I want to make an operator for, but that doesn't work either.

``` purescript
module D ((@@@@)) where
import A (f)
g :: forall a b. a -> b -> a
g = f
infix 5 g as @@@@
-- Error: An export for (@@@@) requires the following to also be exported: g
```

**Comment by tfausak** [comment]
As a related question, what is the recommended way to define operators like [`($)` and `(#)`](http://pursuit.purescript.org/packages/purescript-prelude/0.1.3/docs/Prelude#v:($))? There is no function for function application, so they can't be defined as aliases of something. You could make a function called `apply`, but that would conflict with `apply` from [the `Apply` class](http://pursuit.purescript.org/packages/purescript-prelude/0.1.3/docs/Prelude#t:Apply). I was thinking of defining a private function called `_apply`, but if I define an operator for that function I have to make it public.

**Comment by garyb** [comment]
This was intentional on my part, but I'm not sure if I have a good reason for it necessarily... it just somehow didn't seem quite right to be able to define aliases orphaned from their definitions. There's no technical reason why it couldn't happen, so it's definitely worth discussing.

The `($)` case you describe is perhaps a good excuse to allow it, as you could define the functions in an `Internal` module and then define the aliases as part of the "public" modules. Although you could do the same thing with re-exports too: have the `Internal` module define both, but then only import/re-export the operator aliases.

As part of the Prelude updates thing I was going to move `($)` and `(#)` to `Data.Function` and define them as `apply` and `applyFlipped`, but then do this only-re-export-operators from the `Prelude` to avoid the `apply` collision.

**Comment by tfausak** [comment]
Ah, I didn't think about re-exporting them from an internal module. That's probably fine. The only problem with it is that re-exported values aren't documented well (#1677).

**Comment by garyb** [comment]
Yeah :/

Is that why you wanted to define the aliases outside of the defining module, or did you have another use case in mind too?

**Comment by tfausak** [comment]
I want to define all of my operators in one module. Everything else just defines functions. That way it's easy to see all of the operators and their precedence. Check out this module for a concrete example: https://github.com/tfausak/purescript-neon/blob/aa49135/src/Neon/Operator.purs

**Comment by natefaubion** [comment]
I think `$` pretty naturally translates to `of`. Especially if infix identifiers got the same precedence:

```purescript
foo = bar `of` baz 42
```

I know we allow arbitrary expressions in backticks, but I think you could parse the simple case of ``` `identifier` ``` as a separate AST term and just desugar it the same way as the operators.

**Comment by tfausak** [comment]
Actually `($)` is `id` :smile: 

``` purescript
not $ false
-- true
not `id` false
-- true

**Comment by garyb** [comment]
@natefaubion Yeah, I like that actually, thanks. And actually, that's a good point... we (briefly) discussed making fixities applied to aliases also apply to their underling functions, but it hasn't been done yet, and there wasn't much support for doing so at the time (I think @michaelficarra suggested it would be preferable for `infixing` to have predictable, non-customisable fixity and precedence).

If we were to do that, we definitely wouldn't want to allow aliases to be defined separately from their values. But on the other hand, the "operator module" approach @tfausak just linked seems like a decent case for allowing them...

**Comment by garyb** [comment]
Using `id` for `($)` would have some interesting consequences actually (given that it's defined in `Category`) although I'm not so sure it would be too helpful :wink:

**Comment by natefaubion** [comment]
> If we were to do that, we definitely wouldn't want to allow aliases to be defined separately from their values.

Oh that's a good point, didn't really think of that. Or you would have to only apply it if the operator was in scope, which is also really weird since you could have conflicting fixities defined.

**Comment by tfausak** [comment]
For what it's worth, I agree with @michaelficarra. I think all backtick-infix functions should have the same fixity and precedence.

**Comment by hdgarrood** [comment]
I agree, making backticks' precedence non-customisable seems like a good idea to me too.

Unfortunately I think `of` is out of the question, since it's part of the syntax (`case foo of bar -> baz`)

**Comment by garyb** [comment]
Hmm, right you are. I'm not sure if it needs to be a keyword though, since it should be context-sensitive to `case` expressions.

**Comment by paf31** [comment]
You still need to disambiguate an application to the `Var` `of`.

**Comment by paf31** [comment]
For export purposes, do operator aliases act like type synonyms? @garyb

**Comment by garyb** [comment]
Pretty much - after operator rebracketing the operators are substituted for references to the aliased value. This is also why there's a restriction that a value that is aliased must be exported along with the alias from the defining module.

**Comment by tfausak** [comment]
:+1: Thanks!
