### ISSUE TITLE
psc-publish does not include operators

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1724]
Compare this documentation: http://pursuit.purescript.org/packages/purescript-neon/0.1.1/docs/Neon.Operator

To this source: https://github.com/tfausak/purescript-neon/blob/v0.1.1/src/Neon/Operator.purs#L19-L36

**Comment by paf31** [comment]
These are operator aliases, correct?

**Comment by tfausak** [comment]
Yes. Sorry I forgot to specify.

**Comment by hdgarrood** [comment]
This is now fixed. Check the link :)

**Comment by tfausak** [comment]
:smile:
