### ISSUE TITLE
Remove current implementation of :load in PSCi

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1726]
Kind of related to #1725, as #1725 bit someone in IRC because their `.psci` file contained both `:m` and `:load` for some modules.

I think we should get rid of `:module` in psci.

* It does the same as `:load`
* It's undocumented
* I think, 99% of the time, people generate their `.psci` files automatically, with pulp or gulp, so most people probably wouldn't even notice if we removed it.

**Comment by paf31** [comment]
:+1: but also, `:load` has a different meaning in GHCi which we should probably be mindful of.

**Comment by hdgarrood** [comment]
Oh of course, it would be great to have #1135, I think. What about deprecating `:load` for now, then, and document and keep `:module`? Then we can re-add `:load` with the GHCi meaning when we eventually get around to it.

**Comment by paf31** [comment]
What does PSCi use?

**Comment by hdgarrood** [comment]
Both `:load` and `:module` do the same at the moment, I'm pretty sure, but only `:load` is documented.

**Comment by hdgarrood** [comment]
Yep, they do, see `psci/Directive.hs`

**Comment by hdgarrood** [comment]
Pulp uses `:load` at the moment. The pre-0.7 version used `:m` but I think we can safely forget about things from that far back now.

Actually, I have another idea: allow `psci` to take source globs on the command line, just like `psc` and `psc-docs`. Then, discourage automatic generation of `.psci` files completely. In this case, 99% of users have no need for the `:module` or `:load` commands at all, I think.

**Comment by paf31** [comment]
Moving to 0.9.
