### ISSUE TITLE
Can't use bottom integer values

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1731]
```
> let x = -2147483648
Error found:
in module $PSCI
at  line 1, column 5 - line 1, column 10

  Integer value 2147483648 is out of range for the JavaScript backend.
  Acceptable values fall within the range -2147483648 to 2147483647 (inclusive).
```

Maybe make a special case for `negate 2147483648`?

**Comment by hdgarrood** [comment]
I only stumbled upon this by chance, by having an older prelude installed, from before we moved it into the FFI!

**Comment by garyb** [comment]
Hah!

By that point `negate` has been desugared, we detect this in the JS codegen, but yeah, it should be possible to add a case for this.

**Comment by paf31** [comment]
:smile: That's a bit confusing.

**Comment by tfausak** [comment]
:+1: I hit this too. I worked around it by doing `round (-2147483648.0)`.

**Comment by garyb** [comment]
Amazing timing, I just opened a PR with the fix :smile:
