### ISSUE TITLE
Incorrect error message for unexported values

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1733]
This code:
```purescript
module Main where

import Thingy as Thing

main = Thing.doesntExist "hi"

module Thingy where

foo :: Int
foo = 1
```
gives this error:
```
Error found:
in module Main
at /home/harry/documents/code/ps-scratch/src/Main.purs line 10, column 8 - line 12, column 1

  Unknown module Thing
```

I was expecting "Unknown value Thing.doesntExist" or something along those lines.

However, the right error is produced when the module is imported qualified using the same virtual name as its real name.

**Comment by garyb** [comment]
Great, we had an issue for this before, but I couldn't reproduce the error. This used to happen all the time but I added some fixes for it, so it was hard to find a case that still raised this message (although I've seen it since too).
