### ISSUE TITLE
DuplicateModuleName error message could be more informative

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1734]
```
psc "bower_components/**/*.purs" "src/**/*.purs"
Error found:

  Module Example.Components.Main has been defined multiple times.
```
The message could have the files with these modules.

Also, is there any way to tell psc to ignore ```test``` folders?

**Comment by garyb** [comment]
> Also, is there any way to tell psc to ignore `test` folders?

The easiest way would be to use a more specific path:

```
psc "bower_components/src/**/*.purs" "src/**/*.purs"
```

**Comment by user471** [comment]
https://github.com/purescript/purescript/issues/1801
