### ISSUE TITLE
Remove `import X (..)` syntax again

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1742]
After a discussion on IRC. There is an annoyance factor to this, but that can probably be resolved with tooling, and the warnings generated are only a copy-and-paste away from fixing too.

The motivation is so that all imported values must be fully enumerated. When this is done conflicts cannot arise due to change in upstream modules.

**Comment by michaelficarra** [comment]
:grin: This will make me so happy!

**Comment by hdgarrood** [comment]
Thinking about this a little more, and I'm sorry for flipping back and forth, but - if I were going to resolve the annoyance with tooling, the way I would do that would be to simply ask the tooling to swallow all the open import warnings. (Is there any other feasible way of doing so?) And if we're going to add this warning and then tell everyone to just swallow it again, well, that seems a bit silly.

The problem of having no idea where identifiers come from is a great thing to try to mitigate, but I can't help feeling this should be done via style guides, not warnings. Regarding the problem of stuff breaking after updates that only add new functions (and therefore are not "breaking changes"), I'm not sure we should be going this far to mitigate it:

* I don't think this has ever affected me, in either PureScript or Haskell.
* I'd much rather take 20 minutes during a dependency update, in the very rare case that it does actually happen, to make a couple of imports a little more explicit, than for the default position taken by the compiler to be that literally no imports should be open at all, ever.

**Comment by garyb** [comment]
The tooling fix I had in mind was not to ignore the errors, but to apply the suggestions automatically.

We've already encountered the situation where an upstream library has broken others too... I don't recall which exactly, but we added a combinator to one of the core libraries and it broke another.

The problem is you can't take the time to fix that during a dependency update, as you need to test every dependant library against the one you're updating (and transitive dependants), and since you can't even see all those (since some may be private projects, it's not just libraries that are affected) it means you can never be sure adding to a module is not breaking another somewhere else as long as open imports are seen as safe.

**Comment by hdgarrood** [comment]
Ok, I think I am (finally) seeing where you're coming from :)

What do you think about holding off on 0.8 proper until this automatically-apply-suggestions tool exists?

Also I'm not sure I completely understand what you were talking about with private projects vs libraries, could you give an example?

**Comment by paf31** [comment]
I'd rather hold off on the tool until the feature is ready and bump it to 0.9 :smile:

**Comment by garyb** [comment]
@hdgarrood I just meant that if someone has an app they're working on that isn't open source, and they're using open imports, then their app can be broken by changes in the dependencies too.

**Comment by hdgarrood** [comment]
Ok, fair enough :)

**Comment by telser** [comment]
@garyb How does this impact qualified imports? With 0.8.0-rc.1 a qualified import gets the same warnings as non-qualified, but in this case the issue you mentioned above (a dependency change breaking code elsewhere) wouldn't be a cause for breaking. I agree with this change in principle because I'd rather have things be explicit and clear. However I can see where someone would say that the qualification is being explicit and more usable if a large number of symbols from said module are being used.

Also if this is being removed then will `import Data.Either (Either(..))` style of openness be removed as well?

**Comment by garyb** [comment]
@telser you're quite right, the warning about qualified imports in `0.8.0-rc.1` was a bug. 

However, the case where multiple modules are imported `as` the same thing there will be a warning unless each `import X as Y` also has an explicit import list (`import X (z, w) as Y`, `import A (b, c) as Y`).

The `(..)` style for types will not be removed but we will start warning when it appears. We're not removing it, as `import X (T)` only imports the type `T` anyway, without data constructors, unlike `import X` that imports the entire of `X`.

@paf31 maybe this is something we should change (eventually, 0.9, whatever) though? Perhaps `import X` should be treated as `import X as X`, as if we introduce this thing where every module requires its imports to be explicitly listed (so no arbitrary fully-qualified references), we no longer have a convenient way of doing that, without explicitly writing it (`import Control.Monad.Eff.Console as Control.Monad.Eff.Console`). As then we could keep/re-introduce `import X (..)` which would share the same behaviour as type imports? I don't know, maybe it'd be too confusing for people from Haskell.
