### ISSUE TITLE
Warn when importing-qualified into a virtual module without an explicit list

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1743]
For similar reasons to #1742 - this will ensure name collisions can't be introduced by changes in upstream modules.

**Comment by paf31** [comment]
We don't necessarily need to put these in 0.8 by the way. I was just suggesting that we try to make these changes a longer term goal for import warnings.

**Comment by hdgarrood** [comment]
Just to be clear: the following would generate this warning?

```purescript
import Data.Map as Map
```

If so, :-1: :-1: :-1:  unless the warning only appears when you're importing two different modules into the same pseudo module, like this:

```purescript
import Data.Maybe as Maybe
import Data.Maybe.Unsafe as Maybe
```

**Comment by garyb** [comment]
It's the latter case I'm talking about, the former is fine as there's no chance of name collisions.
