### ISSUE TITLE
Disable code generation

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1753]
For example, when your editor is checking a project, it only needs an errors list.
So, code generation is unnecessary.
Is it possible to add ```-no-code``` flag?

**Comment by paf31** [comment]
You can send output to a trash folder for now, using `--output`, but this might be a useful option.

**Comment by garyb** [comment]
One disadvantage of this is it will also disable incremental compilation, unless we still write the externs files when codegen is disabled.

**Comment by user471** [comment]
>You can send output to a trash folder for now, using --output, but this might be a useful option.

Could such option improve performance or everything after typecheck include codegen doesn't have significant impact?

**Comment by user471** [comment]
>One disadvantage of this is it will also disable incremental compilation, unless we still write the externs Is there any description how incremental compilation works right now?

**Comment by garyb** [comment]
Yeah, the stuff before codegen is the slow part.

I'm not sure if the process is described anywhere but it's relatively simple: along with the `output/Module/index.js` file an `externs.json` file is generated also. This contains the compiled module info such as types, elaborated exports, etc. When recompiling we load up an externs file for a module rather than recomputing all this stuff, as long as the module and the modules it depends on have not been modified since the last compile.

**Comment by user471** [comment]
I think, ```externs.json``` should be generated otherwise compilation would be just too slow.

**Comment by paf31** [comment]
Given that this won't give a big speedup, what's the goal? Can this be closed?

**Comment by user471** [comment]
>Given that this won't give a big speedup, what's the goal? 

Would it be hard to implement? Even small speedup would be enough. The editor runs `psc` after every file save. So it's hundreds of compilation a day.

**Comment by paf31** [comment]
I think that a better solution would be to set up the editor to recompile in a manner like try PS does. That is, by caching externs files in memory for files which aren't going to change.

**Comment by user471** [comment]
>set up the editor

Could you elaborate? The editor can use `psc` and its command line options. How could `psc` use externs files from memory?

**Comment by paf31** [comment]
See #1712.

**Comment by paf31** [comment]
If the goal here is a fast code-save-compile loop while in the editor, then I'll close this as a duplicate. Otherwise, please could you clarify why you don't want to generate code?

**Comment by user471** [comment]
>If the goal here is a fast code-save-compile loop while in the editor, then I'll close this as a duplicate.

The overall goal is to get the list of errors as fast as possible.

>Otherwise, please could you clarify why you don't want to generate code?

Because I don't need this generated code, so It's just waste. The editor only needs an json-errors.

**Comment by paf31** [comment]
Ok, in that case, I think this flag should be added to the new mode suggested in #1712. I'll add it there and close this.
