### ISSUE TITLE
Additional messages with json-errors 

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1754]
```psc "bower_component/*/src/**/*.purs" "src/**/*.purs"  --json-errors```
Right now psc prints messages like 
```
Compiling Main
{"warnings":[{"moduleName":"Main","errorCode":"ImplicitImport" ...
```
or
```
psc: No files found using pattern: bower_component/*/src/**/*.purs
Compiling Main
{"warnings":[],"errors":[{"moduleName":"Main","errorCode":"UnknownModule"
```
Is it nessesary? Could ```--json-erros``` return only json?

**Comment by paf31** [comment]
One is on stdout, the other on stderr. Editors should only read stderr if they want the JSON. That said, we might add additional info to the JSON on success later.
