### ISSUE TITLE
psc-bundle: error if the main module doesn't exist

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1755]
It would be nice if `psc-bundle` would error if the provided `--main` module does not exist.

For example:
```
$ psc-bundle 'output/*/*.js' --main ThisDoesntExist
```
currently succeeds, but puts a call to `PS["ThisDoesntExist"].main()` at the end, which will fail at runtime. Instead, I think psc-bundle should fail and not produce any output.

**Comment by paf31** [comment]
:+1:
