### ISSUE TITLE
Can one file be compiled with all dependencies?

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1757]
I have two files ```Main.purs``` and ```Foo.purs``` in src directory. I can compile ```Main.purs``` like this
```
psc "bower_components/*/src/**/*.purs" "src/Main.purs"
```
But if you add ```import Foo``` in ```Main.purs``` you get an error
```
Compiling Main
Error found:
in module Main

  Unknown module Foo
```
Could compiler search for ```Foo``` module in Main.purs directory?

**Comment by michaelficarra** [comment]
No, just pass the file (or a glob that includes it) to the compiler. Implicitly searching around for the file will lead to unexpected surprises, of which I am not very fond.

**Comment by user471** [comment]
Yes, I can use
```
psc "bower_components/*/src/**/*.purs" "src/**/*.purs"
```
But I only want to check one file.
I don't really see how searching for ```Foo.purs``` could be a problem.

**Comment by hdgarrood** [comment]
Yeah I'm with @michaelficarra here. At the moment, the semantics are very easy to understand; if a file matches the glob, it gets included. I think trying to do this automatically would lead to "module defined multiple times" errors, as files would be included unintentionally.

**Comment by paf31** [comment]
Yes, @michaelficarra gave the reason why the compiler does not currently do this. An external tool could choose to invoke `psc` in this way, but we don't want to do reference chasing by default.
