### ISSUE TITLE
Kind polymorphism

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1763]

**Comment by LiamGoodacre** [comment]
Is it worth starting a list of libraries that will benefit from this?

Off the top of my head I can think of:

- [ ] `Proxy` of [purescript-proxy](https://github.com/purescript/purescript-proxy)
- [ ] `Exists` of [purescript-exists](https://github.com/purescript/purescript-exists)
- [ ] `Leibniz` of [purescript-leibniz](https://github.com/paf31/purescript-leibniz)

**Comment by rgrempel** [comment]
I believe that [purescript-typeable](https://github.com/joneshf/purescript-typeable) would also benefit.

It could enabled a switch to a polymorphoically-kinded `Typeable` implementation, similar to the approach [now used in Haskell](https://ghc.haskell.org/trac/ghc/wiki/GhcKinds/PolyTypeable).

**Comment by paf31** [comment]
I had a bit of a strange idea for an alternative to kind polymorphism.

Instead of adding more machinery to the kind level, we could go the other way and make the type-level language dynamically typed. Here is how this could work:

- Just like dynamic languages track types at runtime, by tagging values, our _types_ will be tagged with kinds.
- Instead of inferring and checking kinds, we simply _evaluate_ kinds during type-checking. For example, whenever we see a type application `f a`, we look at the tag on `f` and make sure it is a function, and then apply that function to the tag on `a`.
- This will allow us to define things like a `Proxy` type constructor which accepts types of any kind.
- Things like `List Maybe` will still be ill-kinded, but this will be caught during type-checking, since the kinds in question do not evaluate to `*`.
- This will allow some relatively crazy type definitions like `type Omega a = a a`, but that's fine, since any issues will be caught during type-checking anyway. Generally, type definitions will not get checked (except to make sure that data declarations actually contain data of kind `*`)
- This should fix another issue (#2103 - "Prefer kind errors to type errors where both occur")

Of course, this is a bit at odds with other things going on at the moment, namely @LiamGoodacre's work on user-defined kinds, but I think we can incorporate that work at the same time. Specifically, instead of defining the kind of a type, we just declare a type with its tag.

So, what do people think?

**Comment by jdegoes** [comment]
At first glance, I really like it. 👍

**Comment by LiamGoodacre** [comment]
I think this has the potential to be really awesome.  Coin the term `dynamically-kinded types`? 😄 

Though I am wondering how this will play with type classes - I suspect in some (unusual) cases it may be undecidable to select an instance if the type class doesn't have fixed kinds for its arguments - but I need to explore that more and come up with a good example.

**Comment by LiamGoodacre** [comment]
Actually I think my previous concerns would manifest with poly kinds too.

**Comment by Pauan** [comment]
@paf31 I like it.

It also potentially paves the way for more dependent-type stuff later.

I think it's okay to have kinds/types be dynamically typed, because ultimately the type checker is running at compile time, so any "dynamic kind" errors are caught at compile-time.

**Comment by jjl** [comment]
One of my libraries would really benefit from either approach. It would be nice to nail down a spec for implementation.

**Comment by EpicOrange** [comment]
Hey! Data.Exists is slightly non-useful without poly kinds (can't add any constraints to the Exists type), so I'm interested in seeing progress here! Is there anything against @paf31's 'dynamically-kinded' types (other than the diverging typechecking issue)?

**Comment by LiamGoodacre** [comment]
@EpicOrange What do you mean by "can't add any constraints to the Exists type"?
If you're talking about a `Constraint` kind like in Haskell, then poly-kinds wouldn't give you that.
If you're talking about constraints on data-constructors, then you'd want (something like) GADTs - which is also unrelated to poly-kinds.
Or have I misunderstood?

**Comment by garyb** [comment]
@EpicOrange You can have constrained existentials even without using `Exists` too with an alternate encoding:

``` purescript
newtype Boxed = Boxed (∀ r. (∀ a. Show a ⇒ a → r) → r)

mkBoxed ∷ ∀ a. Show a ⇒ a → Boxed
mkBoxed a = Boxed \unbox → unbox a

showBoxed ∷ Boxed → String
showBoxed (Boxed f) = f show
```

**Comment by natefaubion** [comment]
Note: there is an ongoing branch for this:
https://github.com/natefaubion/purescript/tree/polykinds

With an update:
https://github.com/natefaubion/purescript/tree/polykinds

**Comment by natefaubion** [comment]
Completed as part of #3779
