### ISSUE TITLE
Type synonyms instances should be disallowed

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#177]
`instance Test {}` fails with the nice error message, but `instance Test T` where `T` is a synonym for `{}` fails in the subsumption check.

**Comment by michal-jewel** [comment]
Is there a plan to resurrect type synonym instances any time soon?
I have seen an [API adaptation for Screeps](/hoodunit/purescript-screeps) based on nested `newtype`s, instead of type classes, and wonder whether it needs a complete rewrite, or is it possible to adapt it.

**Comment by garyb** [comment]
Synonyms in newtypes are being tracked as #2416 / #2481, depending on which kind of deriving you mean. The fix for one or the other might well fix both too.
