### ISSUE TITLE
Warn/error on mixture of tabs and spaces

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1776]
I was recently working on a VM with a default installation of Notepad++. I didn't realise that its default settings are to insert a tab character when you press tab. This led to some really confusing parse errors, because the purescript compiler disagreed with me about how far things were indented.

Could the compiler warn or maybe even error if a source file contains a mixture of tabs and spaces?

**Comment by garyb** [comment]
:100:

Even better, it should error if a source file contains tabs at all :smiling_imp: (only joking... mostly)

**Comment by nwolverson** [comment]
Think literal strings would be an exception.

**Comment by michaelficarra** [comment]
Exotic whitespace characters in strings are better written using an escape sequence.

**Comment by natefaubion** [comment]
@michaelficarra they make more sense in multiline strings

**Comment by hdgarrood** [comment]
We did this as part of #3517.

> Even better, it should error if a source file contains tabs at all :smiling_imp: (only joking... mostly)

nice :smile:
