### ISSUE TITLE
Constructorless data type

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1781]
I have defined this type and function
```
data StringOrInt = String | Int
foreign import foo :: StringOrInt -> Int
```
Why can I not use it?

```
x = foo 10
```
```
  Could not match type
    Int
  with type
    StringOrInt
```
Also, why this type cannot be defined?
```
data ObjectOrString = {foo::String} | String
```

```
Unable to parse module:
unexpected {
expecting proper name
```

**Comment by zudov** [comment]
Because it's not supposed to work like that.

What you are trying to do looks more like anonymous union types if that helps https://www.reddit.com/r/haskell/comments/3vfq69/what_languages_support_anonymous_union_types/cxn3yzy

**Comment by user471** [comment]
>Because it's not supposed to work like that.

Then what does this code ```data StringOrInt = String | Int``` mean and how can it be used?

**Comment by garyb** [comment]
This:

``` purescript
data StringOrInt = String | Int
```

Declares the type `StringOrInt` with data constructors `String` and `Int`, each of which accept no value. Basically it's an enum with constructors that happen to have the same name as primitive types.

This:

``` purescript
data ObjectOrString = {foo::String} | String
```
Is "anonymous" in the way you're trying to use it in the sense that you're trying to construct values for a type without using a data constructor. It's also what `Either` is for:

``` purescript
type ObjectOrString = Either {foo::String} String

foo :: ObjectOrString
foo = Right "hi"
```

**Comment by user471** [comment]
@garyb Is there any plans to support something like this?
If javascript function can accept object or string ```{foo::String} | String```.
What is the best way to write a FFI?

**Comment by garyb** [comment]
No plans, no. There's no eliminator (function/pattern that can extract a definite value from the sum) for types like that, so passing around weird union typed values is only useful to the FFI, and most code should not be FFI code.

Where we have that currently we tend to write a wrapper that expects an Either (or some other sum type if there are many cases) and then unwraps it and hands it off to an unexported JS function typed with a `Foreign` argument. Or perhaps define multiple wrappers for the JS function, each with a different argument type. It depends how many variations there are really.

**Comment by user471** [comment]
@garyb Are there any disadvantages with such approach?
```
class StringOrInt a

instance str :: StringOrInt String where
instance int :: StringOrInt Int where

foreign import foo :: forall a. StringOrInt a => a -> Int

x = foo 1
y = foo "text"

```

**Comment by natefaubion** [comment]
@user471 The problem with that is typeclasses are open (anyone can make an instance of it), and your typeclass has no operations, so this is essentially dynamic programming in a statically typed language. For this to be safe we would need closed typeclasses.

One possibility is to have a canonical argument type, and then your typeclass can have an operation to convert to that canonical type. Halogen does this in the HTML DSL https://github.com/slamdata/purescript-halogen/blob/c22ea3e1f8e20aefc0f495b8a3ccc90cd1eba0cb/src/Halogen/HTML/Core.purs#L129-L148

**Comment by LiamGoodacre** [comment]
@user471 If you want to go down that route; one quick way to constrain it (kind-of) is to add an abstract type constructor (no exported constructors) and a class member which needs to make a term of that type.

~~~purescript
-- note the Closed constructor is not exported so no-one else can make one (without pretending)
module Foo (Closed(), StrOrInt, strOrInt) where
data Closed t = Closed
class StrOrInt t where strOrInt :: Closed t
instance StrOrInt String where strOrInt = Closed
instance StrOnInt Int where strOrInt = Closed
~~~


But you could always just have different functions
```purescript
barFoo :: {foo :: String} -> Int
barString :: String -> Int
```

Or a way of converting one into the other - similar to the canonical argument type which @natefaubion mentioned.
