### ISSUE TITLE
Inference issue with typed binder

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1785]
```
foo (x::Array Int) = x <#> id
```
```
  No type class instance was found for
    Prelude.Functor _0
  The instance head contains unknown type variables. Consider adding a type annotation.
in value declaration foo
where _0 is an unknown type
```
Why PureScript cannot figure out type class instance if it knows the type of x?
Sometime the return type could be pretty complex, so I want to compiler help me to understand it.
Is there any work around?

**Comment by garyb** [comment]
I'm not sure why inference doesn't work there. Is it any better if you type the `x` value rather than the binder?

If you want to infer specific parts of a type, that's what wildcards are for though:

``` purescript
foo :: Array Int -> _
foo x = x <#> id
```

Any time you use `_` in a type `psc` will raise a warning with the inferred type.

**Comment by user471** [comment]
> Is it any better if you type the x value rather than the binder?
Yes, in this way it works.

>Any time you use _ in a type psc will raise a warning with the inferred type.
This also works, but psc doesn't show any warnings.

**Comment by paf31** [comment]
What is PreludeFunctor?

**Comment by user471** [comment]
I don't understand the question. I guess it's https://github.com/purescript/purescript-prelude/blob/master/src/Prelude.purs#L167

**Comment by paf31** [comment]
Sorry, the dot got removed in the email version for some reason.

**Comment by garyb** [comment]
@paf31 is this a bug/restriction with typed binders then? I'd have thought if typing the value works then typing the binder should behave similarly.

**Comment by paf31** [comment]
Yes, quite possibly.

**Comment by paf31** [comment]
This works as of 0.10-RC1.
