### ISSUE TITLE
Include expected indentation level in parser errors

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1787]
This code:
```purescript
module Main where

main = do
  f $ \x ->
    let y = z
        z = 0

g :: Int
g = 3
```
gives this error:
```
  Unable to parse module:
  expecting no indentation or indentation
```

I guess the parser doesn't believe in the law of excluded middle? ;)

Seriously though, I wonder if we can do anything to improve this?

_Edit_ (@paf31): I think a decent fix here is to include the expected indentation level and say something like

```
  Unable to parse module:
  expecting indentation at column 9 or indentation at column 5
```

**Comment by michaelficarra** [comment]
To be clear, you're just saying that this error message is bad, right? This input should still be a parse error because no expression follows the `let` bindings.

**Comment by hdgarrood** [comment]
Yes, I'm just saying that we should perhaps think about improving this parse error, as it doesn't seem to make sense. I would have thought that all tokens are either indentation or not indentation &mdash; although maybe my model of how the parser works is wrong; I'm not very familiar with it.

I think something like "expecting `in <expression>`" would be more appropriate.
