### ISSUE TITLE
Cannot mix puns and labels in update syntax

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1790]
```
foo = 1
x = {foo, bar : 2}
y = x {foo, bar = 2}

```

```
Unable to parse module:
   unexpected {
   expecting no indentation or end of input

```

**Comment by garyb** [comment]
Puns don't work in update syntax and are not ever intended to do so, as it's ambiguous.

`x { foo, bar }` would be passing a new record to `x`, `x { foo, bar = 2 }` would be modifying `x`.

**Comment by user471** [comment]
Could PureScripb have less ambiguous update syntax?
Elm
```
{ x | foo = 1}
```
F# 
```
{x with foo = 1}
```
maybe just add new keyword?
```
x with {foo = 1}
```

**Comment by garyb** [comment]
Yeah, maybe. I quite like the elm version as it's similar to the types (and doesn't unnecessarily reserve a word). If/when we have record constraints it might be useful as a way of differentiating between adding a field to a record and updating a field too.

**Comment by user471** [comment]
Should I open a new issue?

**Comment by garyb** [comment]
Yes please :smile:
