### ISSUE TITLE
Possible alternatives to record update syntax

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1791]
The problem with current one is you cannot use puns in it.
https://github.com/purescript/purescript/issues/1790
There are many alternatives
Elm

```
{ x | foo = 1}
```

F# 

```
{x with foo = 1}
```

maybe just add optional keyword?

```
x with {foo = 1}
```

**Comment by garyb** [comment]
As mentioned in the referred issue I can see one benefit of using something like Elm's syntax: it would be possible to distinguish between extending records and updating records (when we can do that) by having something like `{ x | foo: 1 }` as well as `{ x | foo = 1 }`... although actually that makes the punning ambiguous again.

**Comment by user471** [comment]
There could be two different syntaxes
extend
```
{x ! foo:1}
```
update
```
{x | foo:1}
```

**Comment by garyb** [comment]
It'd be nice to be able to mix updates and extends in the same expression though: `{ x | foo: 1, bar = 2 }`.

Adding `!` in there moves us further away from echoing the type's appearence too (pre-empting your suggestion of `{ x | foo: 1 ! bar = 2 }` :wink:).

It'd need some more thinking out anyway, we haven't considered the syntax for removing fields from records either here. Could perhaps have something like `{ x | +foo }` for a punned extension vs `{ x | foo }` for a punned update, with `{ x | -foo }` for a field removal. I don't know.

**Comment by spion** [comment]
Is this one any good?

```purescript
{x | + addedField = 1
   , - removedField, 
   , reassignedField = 2, 
   , reassignedPunnedField, 
   , + addedPunnedField
}
```

**Comment by starper** [comment]
I think something like this would be a little clearer:
```purescript
{ x | + addedField: 1
    , - removedField, 
    , = reassignedField: 2, 
    , = reassignedPunnedField, 
    , + addedPunnedField
}

**Comment by garyb** [comment]
If you're not using puns I don't think the `+` would be needed. `x: y` is "creation", `x = y` updates, as with the current syntax.

The thing I was thinking about is you can have a field named `"+foo"` (which I guess could still work: `+ "+foo" = x`, it's just a bit weird), but you definitely can't have a punned field with that name as it's not a valid identifier.

**Comment by LiamGoodacre** [comment]
Different keyword sections?
~~~purescript
{ x | set a: 1, b: 2, punnedFieldA
    | add c: 3, d: 4, punnedFieldB
    | del e, f }
~~~

**Comment by user471** [comment]
>x: y is "creation", x = y updates,

This syntax differentiation make sense only when language doesn't have puns. But if you use puns then there aren't any ```:``` and ```=``` and you have an ambiguity. I think records should use either ```:``` or ```=``` but not both.

**Comment by user471** [comment]
@garyb If you could extend records, would it be possible to extend record's type as well?
```
type Foo = {foo::Int}
type Bar = {Foo | +bar :: String}
```

**Comment by jdegoes** [comment]
Upsert is a more convenient semantic than preserving the distinctions between "add" and "update". If you have a right biased operator to merge two records, then you get both update and addition with the same construct, e.g.:

```purescript
defaults with { foo : "bar" }
```

A similar semantic for removing fields would be helpful (i.e. it doesn't care if the fields exist or not, it's not an error to remove a non-existent field from a record). Possibly the syntax could reuse the existing one for row types, but lifted (lowered?) to values, something like:

```purescript
foo without (a, b, c)
```

**Comment by tbenst** [comment]
Perhaps we can follow the lead of ES6 class syntactic sugar? `{foo: 1} extends x`. 

Even better if it works for types, too. Would be great for translating Javascript Prototypes to Purescript, e.g.

```javascript

class Stimulus {
    constructor(lifespan) {
        this.lifespan = lifespan
        this.age = 0
  }
}

class Bar extends Stimulus {
    constructor(lifespan, speed, width, angle, barColor) {
        super(lifespan)
        this.speed = speed
        this.width = width
        this.barColor = barColor
    }
}
```

Purescript:
```purescript
type Color = String
newtype Stimulus r = Stimulus {lifespan :: Number, age :: Number | r}
newtype Bar = {speed :: Number, width :: Number, barColor :: Color} extends Stimulus
bar lifespan speed width angle barColor = {lifespan: lifespan, speed: speed, 
                                           width: width, angle: angle, age: 0}
```

Today, I suppose `Stimulus` could be an Algebraic Data Type, but each type would have to repeat `lifespan` and `age`. I'm new to purescript so do let me know if there's already a better way to do this.

**Comment by LiamGoodacre** [comment]
Close?

**Comment by paf31** [comment]
Yes, thanks
