### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1795]
If you run `psc --version` with the 0.8.0 RC, you get `0.8.0.0`. A couple of suggestions:

* From now on, please can we make sure that, for any release, the tag is the same as the output of `psc ---version`?
* When we release the first proper 0.8 release, can we please call it 0.8.1, given that there is already an 0.8.0 "in the wild"?

**Comment by paf31** [comment]
Sounds good. I'll close this and make sure we release as 0.8.1 when the release is ready.
