### ISSUE TITLE
JSON error messages should omit indentation

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1797]
Right now, error messages have indentation and extraneous whitespace from the default error printer. It would be nice to have it sans indentation so I don't have to strip it.

**Comment by mjgpy3** [comment]
Are you thinking a simple trim would suffice, or should something more complicated be done (e.g. trim then squash all whitespace into single space)?

**Comment by natefaubion** [comment]
Right now there errors are something like:
```

  Some error here:
  
    Detail

  in this place



```

Note the extra newline at the beginning and end, plus overall indentation. It would be nice if it was whitespace neutral:

```
Some error here:

  Detail

in this place
```

Right now I do:
* Trim leading newline
* Count initial indentation on first line
* Trim initial indentation from each line
* Trim whitespace from end
* Collapse more than 2 newlines in a row into 2 newlines max

**Comment by natefaubion** [comment]
Note that the above doesn't always work because TypesDoNotUnify has inconsistent indentation:
```
  Could not match type

    Int

  with type

    Array (Array (Array AnsiText))


while trying to match type Int
  with type Array (Array (Array AnsiText))
while checking that expression 2
  has type Array (Array (Array AnsiText))
in value declaration renderStats
```

The top half is indented, while the bottom half isn't.

**Comment by paf31** [comment]
Yes, that section is always indented, but it looks a bit odd with JSON errors since the first couple of lines has been stripped out.
