### ISSUE TITLE
Add warning for absence of `_ <-` when throwing away non-Unit values in a `do`

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1803]
It can help prevent some rather annoying bugs, like if you do something like this:

``` purescript
do
  maybe (pure unit) ($ (Left act)) <$> readRef emitRef
  pure next
```

When you meant to do this:

``` purescript
do
  maybe (pure unit) ($ (Left act)) =<< readRef emitRef
  pure next
```

(The former case has a return like `m (m Unit)` rather than `m Unit`, but because I didn't notice that the action was not sequenced and therefore nothing happened)

**Comment by paf31** [comment]
:+1: Warning or error?

**Comment by paf31** [comment]
The simplest way to address this would be to add a `:: Unit` annotation during desugaring, but that would make it an error.

**Comment by garyb** [comment]
I'd be okay with it being a error, but I guess that might be a bit too strict given it's not necessarily wrong; it seems more like one of those "are you sure this is right?" cases.

That would be a convenient fix though :smile:. I guess it shouldn't be too hard to check at the lint stage, as we have type annotations then, don't we?

**Comment by michaelficarra** [comment]
I don't mind making discarded non-Unit values an error. That sort of thing should really be explicit.

**Comment by natefaubion** [comment]
While `a :: Unit` is convenient, I'm afraid that might make the error really opaque, unless you can attach the hint to it.

**Comment by paf31** [comment]
Yes, that's true.

**Comment by paf31** [comment]
The linter doesn't have type info since it runs before type checking.

**Comment by garyb** [comment]
Ah, so it does. Although exhaustivity checking runs after the typechecker.

**Comment by hdgarrood** [comment]
What if `Unit` isn't in scope? Eg, if you were using an alternative Prelude. I think that if we were going to do this, then we should define `Unit` inside the compiler.

**Comment by paf31** [comment]
Well, `bind` isn't in `Prim` either.

**Comment by hdgarrood** [comment]
Right, but we're making assumptions here about what `Unit` means. None of the other rebindable syntax does that, as far as I know.

**Comment by garyb** [comment]
I still think it's worth it. We could also do something to check that the `Unit` we have is the `Unit` we expect (newtype around `{}`) before enabling this warning.

**Comment by michaelficarra** [comment]
We don't care which Unit it is. If you're throwing away a value of a type *you haven't called Unit*, then it should require explicit syntax.

**Comment by hdgarrood** [comment]
Doing it based on the name feels very wrong to me. The compiler shouldn't change its behaviour based on what things are called, I don't think.

With the current proposal, the compiler will arguably do the wrong thing with both of these:

```purescript
-- Phantom types for physical units
data Metres
data Miles
data Unit u a = a

x :: Unit Metres Int
x = 100
```
```purescript
-- Perhaps you wanted different instances to what Unit has.
data DontCare = DontCare
```

Haskell does warn in the second case, so that's probably not such a big deal. It's the first I'm more worried about.

**Comment by michaelficarra** [comment]
`Unit` with kind `*`. Regarding names, we do the same thing with `bind` and `negate`.

**Comment by hdgarrood** [comment]
Ok, here's another example then

```purescript
data Unit = Metres | Yards | Feet | ...
```

**Comment by hdgarrood** [comment]
I just really don't like the idea of the compiler producing nonsense warnings/errors unless you use the language in a certain way.

Suppose we say that some `Unit` has to be in scope - we don't care which. Then consider this program:

```purescript
import Prelude ((++))
import Control.Monad.Eff.Console (log)
import Some.Hypothetical.Module (getLine)

main = do
  line <- getLine
  log ("read line: " ++ line)
```

`Unit` is not in scope, but that doesn't matter, because no results are discarded. Now suppose we add `log "about to getLine"` just after the `do`. Now we get an error about `Unit` not being in scope, which is going to make exactly zero sense to anyone not familiar with how this works.

**Comment by garyb** [comment]
They won't get a warning there as we're not going to do this by annotating `:: Unit` - as mentioned above that will make the messages to cryptic. We'll be checking if a sequenced value's type is not `m Prelude.Unit` for the appropriate `m`. We can also restrict this to only apply when `Monad`'s `bind` is being used.

**Comment by hdgarrood** [comment]
Ok, that sounds much better. Still, I think it's a shame to build in knowledge of prelude. What if you're allowed to discard values only when a type has exactly one inhabitant?

**Comment by paf31** [comment]
> What if you're allowed to discard values only when a type has exactly one inhabitant?

That's difficult to test, especially if you include things like `type MyUnit = forall a. a -> a` :smile:

**Comment by paf31** [comment]
(strange idea) What about a type class in `Prim`?

```purescript
class Discard a

instance discardUnit :: Discard Unit -- in Prelude
```

and adding a `Discard` dictionary, and special error message support?

**Comment by hdgarrood** [comment]
Re types having exactly one inhabitant, I was thinking of cases where the compiler can easily prove that it has only one inhabitant. So, eg, if it's `{}`, or if it's a data declaration with one constructor with zero fields, or a data declaration with one constructor where every field has exactly one inhabitant, or a newtype around any of these.

I like the `Discard` idea too.

**Comment by rightfold** [comment]
2¢: in Rust you can specify a custom message for this, for example:

    #[must_use = "you probably forgot to check the error"]
    enum Either<E, T> {
        Left(E),
        Right(T),
    }
    
    fn foo() -> Either<String, i32> {
        // ... I/O
        return Either::Right(42);
    }
    
    fn main() {
        foo();
    }

Gives warning:

    <anon>:13:5: 13:11 warning: unused result which must be used: you probably forgot to check the error, #[warn(unused_must_use)] on by default
    <anon>:13     foo();
                  ^~~~~~

**Comment by paf31** [comment]
I did a quick experiment by adding a function named `bind_` to Prelude. Right now, we get errors like this one:

```text
Error found:
in module Control.Monad.Rec.Class
at .psc-package/psc-0.10.2/tailrec/v2.0.0/src/Control/Monad/Rec/Class.purs line 114, column 1 - line 130, column 42

  No type class instance was found for
                                     
    Control.Bind.Discard (Step a0 b1)
                                     

while checking that expression \f ->               
                                 \a ->             
                                   let             
                                     fromDone = ...
                                     f' = ...      
                                   in runST (...)  
  has type forall a b eff. (a -> Eff eff (Step a b)) -> a -> Eff eff b
while applying a function runST
  of type forall a r.        
            (forall h.       
               Eff           
                 ( st :: ST h
                 | r         
                 )           
                 a           
            )                
            -> Eff r a       
  to argument (bind (f' a)) (\$4 ->      
                               case $4 of
                                 e -> ...
                            )            
in value declaration tailRecEff
```

so I'd like to do a little work to improve things there, but this is pretty straightforward from an implementation point of view.

Either way though, it's going to require a breaking change in Prelude which will be tied to a compiler change, so we'll probably want to leave it until 0.11.0.

**Comment by paf31** [comment]
I'd like to break this in 0.11 as well.

**Comment by garyb** [comment]
It's not actually breaking though, is it? In that it's just a warning. Or are you thinking it should become a full error? Seems a bit strict perhaps, given it's mostly a "good practice" thing.

**Comment by garyb** [comment]
Oh, a breaking library change though, I see. Perhaps we can use the `Warn` typeclass for `bind_` rather than introducing `Discard` too?

**Comment by paf31** [comment]
I'm not sure we can use `Warn`, at least not without some other class (which would probably need to use overlapping instances) since we want to case on the type being discarded. Essentially, we need disequality constraints (warn on any type _not equal_ to `Unit`, or not in some set of approved discardable types).

**Comment by paf31** [comment]
I would just make it an error, since there is a simple way to indicate explicitly that we want to discard a result (which is to use `_ <- ...`).

**Comment by beckyconning** [comment]
👍
