### ISSUE TITLE
Warn on unused qualified import

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1804]
Right now if you don't use a qualified import, no warnings are generated. It should give a redundant import warning.

**Comment by garyb** [comment]
Oh, that's weird, I would have thought this case was already covered. Should be an easy fix at least!

**Comment by nwolverson** [comment]
I thought it was originally but I could be wrong. Some tests of these warnings would really have been useful, I wish I spent the time originally to get some warnings tests running.

**Comment by garyb** [comment]
I'm doing some major work on this stuff again right now - this one is fixed. Adding warning tests is on my todo list, but it's not entirely trivial, but would indeed be very helpful for this in particular!
