### ISSUE TITLE
eqString is not being inlined

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1805]
I noticed this in some output:
```js
if (Prelude["=="](Prelude.eqString)(l)("")) {
```
And that should probably be getting inlined.

**Comment by hdgarrood** [comment]
The inliner seems so fragile - perhaps we should put all the stuff we might want to inline inside the compiler, in `Prim`, perhaps? It does seem a bit wrong that the compiler has special knowledge of libraries, I think.

**Comment by garyb** [comment]
Rewrites should solve that problem eventually. I wouldn't be in favour of distributing PureScript code with the compiler again, it makes updates painful as you can't version them the same way you can library code, and you can't do minor patch updates without releasing a new compiler.

The rewrites need looking at again anyway, as all the operator rewrites will not be working in 0.8 with the updated Prelude, given the handling of aliases.

**Comment by paf31** [comment]
Inlining is the main rewrite we care about, right? Maybe we could implement an inliner as a warm up.

**Comment by paf31** [comment]
I suppose inlining foreign definitions makes things much harder.

**Comment by garyb** [comment]
Yeah, that's the tricky part!

**Comment by paf31** [comment]
It might be simpler to implement if we restrict things to spines of function applications: `f x y ... z`. Then we could probably do it all in one pass.

The tricky bit remains - how do we encode the replacements. I have some ideas, but none are particularly great.

**Comment by paf31** [comment]
Anyway, I'll continue this on the rewrites issue.
