### ISSUE TITLE
Subrecord type

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1806]
Just an idea.
Subrecord type means record with any subset of fields ```{|field1:: Type1, field2 :: Type2, ... |}```
Imagine that PureScript has a new updating record syntax
```
type Foo = {x :: Int, y :: Int}
bar = {x:1, y :10}
foo = {bar| x = 10}
```
What if you could define update part separately.
```
update = if something then {x : 1} else {x: 10, y : 10}
foo = {bar | update}
```
The type of ```update``` is ```{|x :: Int, y :: Int|}```

Such type could be used for default parameters values
```
test :: {|x :: Int, y :: Int|} -> _
test x = let defaultValues = {x:1, y:10} in something {defaultValues | x} 
```
For example, html element constructor
```
type ImgAttributes = {|src :: String, alt :: String, ... |}
img :: ImgAttributes -> _
img {src : "foo.jpg"}
```

**Comment by paf31** [comment]
I would like to solve this using row constraints. For example:

```purescript
blah :: forall r rest. (r ⨆ rest ~ (foo :: String, bar :: Int)) => Object r -> String
```

Here, `blah` takes any record whose row can be unioned disjointly with some other row to form the row `(foo :: String, bar :: Int)`. This is equivalent to saying that `r` is a subrow of `(foo :: String, bar :: Int)`. In the construction direction, you need existential types.
