### ISSUE TITLE
Nested record update

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1807]
Is it possible to support this?

```
foo = {x: {y: 1}}
bar = foo {x.y = 2}
```

would be equal to 

```
bar = foo {x = foo.x {y = 2}}
```

**Comment by hdgarrood** [comment]
I like the look of this. :)

**Comment by paf31** [comment]
Neat :)

**Comment by LiamGoodacre** [comment]
:+1: nice.  For reference: [Idris has this too](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#nested-record-update)

**Comment by kRITZCREEK** [comment]
One thing that is a little sad is that this discourages the use of "newtype" because it can't benefit from all the sugar.

**Comment by paf31** [comment]
I like this idea, but on the other hand, lenses handle this more compositionally and more generally.

**Comment by user471** [comment]
> lenses handle this more compositionally and more generally.

But, you need an additional hundreds lines of code for them. So, in some cases it's easier to use update syntax

**Comment by user471** [comment]
Also, I think it should work for 
```
x = _.foo.bar
```
Right now it doesn't really make much sense for trying to get field `bar` from function `_.foo`

**Comment by rvion** [comment]
> bar = foo {x.y = 2}

yes please !!

**Comment by rvion** [comment]
big +1 for me. 👍 

I understand lenses bring some more power, but they also brings dependencies, and complexity.
If the language change is small, the following 3 features would be great to have IMO 
(2 first are @user471, last one is a small proposal addition)

```purescript
x = {a:{b:{c:2}}

get = _.a.b.c
set = _{a.b.c=2}
upd = _{a.b.c->(_+2)}
```

**Comment by paf31** [comment]
Since we have anonymous accessor chains (#2264), I think it would be nice to have nested updates in 1.0 too.

**Comment by rvion** [comment]
> Since we have anonymous accessor chains (#2264), I think it would be nice to have nested updates in 1.0 too.

@paf31 and nested types annotations ? 

``` purescript
f :: { b.c.d :: Int | stuff } -> Int 
f = _.b.c.d
```

@paf31 Also, regarding the update syntax mentioned in this [comment above](https://github.com/purescript/purescript/issues/1807#issuecomment-232920461), I now really think it it is needed to deal properly with union types;

```
x = {a: {b: c: {Left "ok"}}}

y :: {a.b.c :: Either String Int | x} -> {a.b.c :: Int | x}
y = x {
  a.b.c -> case _ of 
    Left str -> length str
    Right int -> int +2
}
```

lenses with prisms are __not__ an answer because they lack exhaustive pattern matching (things like [this](http://www.haskellforall.com/2015/01/total-100-exhaustive-pattern-matching.html) exist, but  well...)

also, the act of `updating` a variable is pretty fundamental, useful, more powerful than setting, etc, so having a first class way to update a value really makes sense IMO

**Comment by garyb** [comment]
Nested type annotations: No thanks. It's either too restrictive (inner records are closed) or it's ambiguous (nowhere to put the type variables that are needed to describe the "rest" part of the rows).

**Comment by rvion** [comment]
@garyb I'm not quite sure to understand the problem:
Can't ambiguousity be solved quite easilly in all case :

```purescript
forall x y. {a.b: {c :: Int, d :: Double | x} | y}
forall x.   {a.b.c :: Int, a :: x}
forall x.   {a.b.c :: Int, a.b.d :: Double | x}
```purescript

here,  the record tree would be created and updated along parsing to the usual form, and regular errors message would work in all cases I can think of.

Do you have an example of something that doesn't work ?

**Comment by rvion** [comment]
@garyb Oh, you're right !

in 

```
forall x. {a.b.c :: Either String Int | x} -> {a.b.c :: Int | x}
```

 `b` can't be known to be the same if no annotations are given for a, b, and c !

**Comment by LiamGoodacre** [comment]
I'm starting work on this.

**Comment by LiamGoodacre** [comment]
An update to the design: it is an error for paths to overlap.  The following are therefore disallowed:
```purescript
x { foo = { bar: 2 }, foo.bar = 3 }
y { foo.bar = { baz: 2 }, foo.bar.baz = 3 }
```

However the following is permitted:
```purescript
z { foo.bar = 2, foo.baz = 3 }
```
As neither `foo.bar` nor `foo.baz` are a sub-path of the other.

**Comment by LiamGoodacre** [comment]
I've just been thinking about the syntax.  Perhaps instead of:
```purescript
r = { op: Add, args: { lhs: 0, rhs: 0 } }
r' = r { op = Mul, args.lhs = 2, args.rhs = 3 }
```
The following may have been nicer:
```purescript
r = { op: Add, args: { lhs: 0, rhs: 0 } }
r' = r { op = Mul, args { lhs = 2, rhs = 3 } }
```

**Comment by LiamGoodacre** [comment]
That is, `args { lhs = 2, rhs = 3 }` is the same style as `r { op = Mul }`, but you don't have to refer to `r`/`args`/`r.args` multiple times.

**Comment by paf31** [comment]
That does seem preferable. Do you think it would be an easy change?

**Comment by LiamGoodacre** [comment]
Yes, I'll have a go at it tonight.

**Comment by LiamGoodacre** [comment]
It's a good job I started looking into this, I found a bug with the original implementation.
