### ISSUE TITLE
Warnings about future changes to imports?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1818]
@paf31 re: your point in #1817 there are several warnings that we should probably put in if we're going to go ahead with this approach:

- [ ] Warn when a qualified reference is used but the module is not imported
- [ ] Warn when imports are not all grouped together at the top of a module
- [ ] Warn when there are multiple modules in a file

I'm still not crazy about this though to be honest, I find the need to import and not be able to just use qualified modules infuriating in Haskell at times. Mainly when I just want to drop some debug logging in, but it happens often enough that I find it pretty tiresome. My preference would still be to keep dependency information in the externs files instead, and load up the information from those first rather than parsing the modules.

Also, not sure if you saw this? http://blog.ezyang.com/2016/01/ghc-shake-reimplementing-ghc-make/ It talks about some of the relevant issues too, like projects with large module graphs.

**Comment by paf31** [comment]
> My preference would still be to keep dependency information in the externs files instead, and load up the information from those first rather than parsing the modules.

Yes, but that won't work if the imports change because the externs file will be stale, right?

As a reminder for others, the motivation is to improve the recompilation speed by only parsing as little as possible of the module header in order to determine what work needs to be done.

> Also, not sure if you saw this?

I didn't but I'll take a look, thanks!

**Comment by paf31** [comment]
It might make sense to read imports from externs if the timestamp on the externs file is more recent than on the source file, but we should still try to parse as little as possible whenever we do have to revert to parsing the source file.

**Comment by garyb** [comment]
Wouldn't we have to parse the whole file anyway if it's modified? How would we know that it's safe to stop at the imports when a file has been modified?

**Comment by paf31** [comment]
In any case, I have a better solution now, viz. the new Try PureScript API. Close?

**Comment by garyb** [comment]
Cool :+1:
