### ISSUE TITLE
if-then-else sometimes doesn't parse in do blocks

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1819]
I noticed if you format your `if-then-else` like this in a do block:
```purescript
foo = do
  x <- File.exists "foo"
  if x then
    Console.log "exists"
  else
    Console.log "does not exist"
```
It fails to parse, sometimes in unexpected ways.

**Comment by paf31** [comment]
The `else` must be indented past the current indentation level, which in this case is where the `if` is.

**Comment by natefaubion** [comment]
The only reason I made this an issue is that its acceptable outside of do-blocks. So code that was working, can be made to not work by putting a do before it.

**Comment by natefaubion** [comment]
Also because the parse errors can be really bad, since its not necessarily localized to the specific statement. I had some nested do blocks, and it failed the parse on the top-most expression, which wasn't close to where the error was.

**Comment by paf31** [comment]
We should be able to provide a better parse error, but it _is_ consistent: the `else` must always be indented past the reference point, but in some cases, that is the same as the `if`, and in some cases is isn't.

**Comment by paf31** [comment]
Closing, since this will be addressed by improving error messages for bad indentation, which is tracked elsewhere for 1.0.
