### ISSUE TITLE
Relax rules for documentation comments

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1820]
Currently, all of the documentation lines before a declaration must begin with a pipe character for those comments to be considered documentation (which determines whether they show up in `psc-docs` and pursuit).

This means that lots of documentation gets accidentally lost. For instance, `slice` from `arrays`:
* Source: https://github.com/purescript/purescript-arrays/blob/v0.4.4/src/Data/Array.purs#L416-L421
* Pursuit: http://pursuit.purescript.org/packages/purescript-arrays/0.4.4/docs/Data.Array#v:slice

The documentation disappears because of the preceding "Subarrays" comment.

I propose that instead of requiring every line starts with a pipe, we simply take only those that start with a pipe. I doubt that this would lead to us including anything that people didn't intend to include - I don't consider this change very risky.

See also the relevant source: https://github.com/purescript/purescript/blob/a0b92c797fdb283a1a8356249517df3e4a9093b4/src/Language/PureScript/Docs/Convert.hs#L201-L218

**Comment by hdgarrood** [comment]
This is super easy to implement, so I can send a PR, but preferably not until #1770 is merged.

**Comment by garyb** [comment]
:+1:!

I thought that's the way it worked already actually (just taking pipe-prefixed lines).

**Comment by zudov** [comment]
TIL, that every line has to be prefixed with a pipe (not like in haskell, where it's only the first line and the subsequent pipes would appear in the docs)

**Comment by hdgarrood** [comment]
Hmm, we should probably document this somewhere. Language Guide?

**Comment by zudov** [comment]
@hdgarrood Differences-from-haskell page also wouldn't hurt. I find it intuitive that *every* line has to have a pipe, and I thought that it's not the case only because of Haskell knowledge (in Haskell I've ended up with lots of bars in my docstrings a few times)

**Comment by hdgarrood** [comment]
:

**Comment by paf31** [comment]
:+1:

**Comment by hdgarrood** [comment]
Wiki updated:
* https://github.com/purescript/purescript/wiki/Differences-from-Haskell/_compare/b58e9b337c2441ac0838f4c3be90c18de996007f...d90800780be4c59c2a4294c6edf55acec2d0f53f
* https://github.com/purescript/purescript/wiki/Language-Guide/_compare/61587ff0c9a23fb30b9e922749ef715e1075b43f...08a07124724c876695467fe79f64af071b3edd43
