### ISSUE TITLE
Invalid redundant import warning

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1823]
Consider the following module:

``` purescript
module Example (module Example, module X) where

import Prelude (Unit()) as X
import Prelude as Prelude

foo :: X.Unit
foo = Prelude.unit
```

It exports `Unit()` from the prelude and also exports `foo` as an alias for `unit`. Compiling it with PureScript 0.8.0-rc.1 gives the following warning:

```
Warning 1 of 2:

  in module Example
  at /private/tmp/ps/src/Example.purs line 3, column 1 - line 4, column 1

    Import of Prelude (Unit) is redundant due to a whole-module import



  See https://github.com/purescript/purescript/wiki/Error-Code-RedundantUnqualifiedImport for more information,
  or to contribute content related to this warning.
```

I think that is incorrect. I am explicitly importing `Prelude` twice under different aliases in order to selectively export some values and refer to others.

**Comment by paf31** [comment]
Bump to 0.8.1?

**Comment by garyb** [comment]
Yep, definitely.

**Comment by paf31** [comment]
Shall I cut a release then or do we want to do more testing after the last merge?

**Comment by garyb** [comment]
I think we can do the release. As far as I can see, the worst thing that might have happened in the last commit is some optimisations will not be applied properly, which we can fix in 0.8.1... and hopefully we can get that out pretty quickly :wink:

**Comment by paf31** [comment]
Ok, I'll tag 0.8.0 now.

**Comment by paf31** [comment]
Or should we make this 0.8.1? @hdgarrood had expressed some concern over having 0.8.0 in the wild for some weeks now.
