### ISSUE TITLE
Variable in scope from another binding

### ISSUE THREAD

**Issue by spencerjanssen** [purescript/purescript#1825]
```purescript
module Main where

import Control.Monad.Eff.Console

data W
    = X 
    | Y 
    | Z 

bad X a = a 
bad Y _ = a 
bad Z a = a 

main = print (bad Y 0)
```

This program compiles and prints `0`.  I'd expect it to fail compilation because `a` is not in scope in the second case.  If I rename the `a` binding in either the case above or below psc spits out `Unknown value a` for the `Y` case.

I'm using Purescript 0.7.6.1

**Comment by garyb** [comment]
Argh, good find. Thanks for the report!
