### ISSUE TITLE
DuplicateModuleName error does not specify what file Modules are defined in

### ISSUE THREAD

**Issue by leighman** [purescript/purescript#1828]
I split up my file into multiple files and missed a `module Parser where` somewhere so I get

     Module Parser has been defined multiple times.

It would be good if this said what files the modules are defined in.

I had a quick look and `RedefinedModule` does seem to specify filenames but `DuplicateModuleName` does not. I don't know why my example triggers the latter (using `pulp build`) and I can't see a way to get at filenames where `DuplicateModule` is called.

Happy to have another look at fixing this with some guidance.

**Comment by garyb** [comment]
That's interesting, I'm not sure why we have two errors for the same thing either actually. I'm surprised it wasn't caught by the case for `RedefinedModule`, as that happens earlier in the compile process... I haven't tried it, but maybe `DuplicateModule` always happens over `RedefinedModule`. Can you boil down a test case to raise the error?

**Comment by leighman** [comment]
» pulp --version
    Pulp version 6.2.1
    psc version 0.8.0.0 using /home/jack/.npm/bin/ps

    pulp init
    echo "module Main where" > src/Test.purs
    pulp build
