### ISSUE TITLE
Bug when a module has the same name as constructor

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1839]
```
module Main where
import Prelude
import Control.Monad.Eff.Console
import Foo

data X = Foo Foo.Bar

eval (Foo (Foo.Bar x)) = x

main = print $ eval $ Foo None

module Foo where
data Bar = Bar Int | None

```

```
        if ($2 instanceof Foo.Bar) {
                             ^

TypeError: Expecting a function in instanceof check, but got undefined
```

**Comment by garyb** [comment]
This is fixed in 0.8 / master, unless you've found a new way to trigger it here.

**Comment by user471** [comment]
@garyb does this bug has an issue?

**Comment by sharkdp** [comment]
#1789

**Comment by hdgarrood** [comment]
Or #867?

**Comment by garyb** [comment]
#867 was the original bug, #1789 was a new one I introduced with the fix :smile:. It's also fixed in `master` now.

**Comment by user471** [comment]
> It's also fixed in master now.

I built psc from master, but I still have this error.

**Comment by sharkdp** [comment]
> I built psc from master, but I still have this error.

You are right. This is a (probably related but) different error. Here is a simpler example, showcasing the same runtime error:

``` purescript
module Main where
import Prelude
import Control.Monad.Eff.Console

data X = Prelude Ordering

eval (Prelude GT) = unit

main = print $ eval (Prelude GT)
```
(can be confirmed with [Try PureScript](http://community.purescript.org/try/) :smile:)

So the issue here is that a data constructor is named like an *imported* module.

**Comment by user471** [comment]
Does try ps always use master version?

**Comment by paf31** [comment]
No but it does right now.
