### ISSUE TITLE
Parse error let ... in  expecting indentation

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1848]
This code can be parsed
```
foo x =
  let y =
    10
  in y
```
But this cannot
```
foo x =
  let y =
    case x of
      (Foo z) -> 10
  in y

```
```
  Unable to parse module:
  expecting indentation
```

**Comment by paf31** [comment]
The correct indentation is past the `y`. I suspect numeric literals just don't check indentation, which is technically a bug, but not really a big problem.

**Comment by michaelficarra** [comment]
@paf31 That correct indentation is extremely complex, and requires changing indentation when the identifier name changes. I would have written my code exactly the way @user471 did. Isn't that Jon-dentation&trade; or something?

**Comment by garyb** [comment]
That's a good point, `let` requires things to be indented further than any other construction, it trips me up every single time I try to define something over multiple lines too. Can't we do something about that? What's the ambiguity that the extra indentation fixes?

**Comment by garyb** [comment]
Although Haskell behaves the same way, so there probably is a good reason for it I'm not thinking of.

**Comment by paf31** [comment]
You don't have to move anything if the identifier changes, the reference point is the first column of the first line of the declaration.

**Comment by paf31** [comment]
You need to be able to differentiate between different declarations and different lines of the same declaration.

**Comment by garyb** [comment]
> You don't have to move anything if the identifier changes, the reference point is the first column of the first line of the declaration. 

Ah right, yes, like:

``` purescript
foo x =
  let
    y =
      case x of
        (Foo z) -> 10
  in y
```

**Comment by paf31** [comment]
Well, yes, but this is simpler:

```purescript
let y = case x of
          (Foo z) -> 10
```

**Comment by AppShipIt** [comment]
I personally always break lines after keywords (except used in conjunction like `case`/`of`) for this reason.

**Comment by paf31** [comment]
Closing, since again, this will be addressed by including column information in indentation errors, which is tracked elsewhere.
