### ISSUE TITLE
One line case statement

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1849]
Is it possible to support?
```
 case x of {0 -> "0"; 1 -> "1"}
```

**Comment by garyb** [comment]
:-1: from me, I would not want to see braces or semicolons in the syntax, especially for things that are already possible without it.

**Comment by user471** [comment]
> I would not want to see braces or semicolons in the syntax

Not necessary braces or semicolons, it could be anything.
With small cases it just require too much space.
```
foo x =
  case x of
    (Foo y) ->
      case y of 
        X -> 1 
        Y -> 2
        Z -> 3
```

```
foo x =
  case x of
    (Foo y) -> case y of X -> 1 or Y -> 2 or Z -> 3
```

**Comment by garyb** [comment]
Too much vertical space for what? We have a near infinite supply of lines :smile:

If you find yourself writing many cases of this kind for a single type and want to collapse them all, why not write a catamorphism (fold) for the type and then use that? The above case would be something like `foo = foldFoo 1 2 3` then.

**Comment by user471** [comment]
>We have a near infinite supply of lines

But we still use finite monitors.

>The above case would be something like foo = foldFoo 1 2 3 then.

But ps doesn't support lazy evaluation. so it would be like `foo = foldFoo (\_ -> 1) (\_ -> 2) (\_ -> 3)`

**Comment by hdgarrood** [comment]
I agree with @garyb in that I'd much rather see one line per case alternative in actual code. However, a single line syntax could be very useful in psci.

**Comment by paf31** [comment]
This is a duplicate.

I'd like to see braces and semicolons supported as alternative syntax, I think they are useful in some rare situations.

**Comment by garyb** [comment]
#774

**Comment by srghma** [comment]
does one like case statements work as of now?

e.g.

`case maybeXXXYYY of; (Just (XXX (YYY _))) -> true _; -> false` throws error `Unable to parse module:    Unexpected ;`

**Comment by hdgarrood** [comment]
No, #774 was closed for lack of interest. You can only put a case statement on one line if it matches just one case, but not otherwise, e.g.
```
case x of X y -> f y
```
