### ISSUE TITLE
When duplicate patterns exist an unhelpful warning is given

### ISSUE THREAD

**Issue by dkoontz** [purescript/purescript#1853]
Given the following code

```purescript
module Main where

data Options = Foo | Bar | Baz

brokenPatternMatch :: Options -> Boolean
brokenPatternMatch Foo = true
brokenPatternMatch Foo = true
brokenPatternMatch Bar = false
brokenPatternMatch Baz = false
```

produces the warning `A case expression contains unreachable cases: Baz` which is probably technically true but not very helpful. "duplicate pattern Foo" would seem better.

**Comment by paf31** [comment]
No, that'd be a bug. `Baz` is not unreachable. The error should be that `Foo` is unreachable.

cc @nicodelpiano, any thoughts on this?

**Comment by nicodelpiano** [comment]
Yes, it seems to be the redundancy checker. Let me check that out.
