### ISSUE TITLE
type Object in error messages

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1855]
```
data Foo = Foo {foo :: Int}

bar x = x + 1
foo = Foo bar
```
```
Could not match type

    Object

  with type

    Function Int


while trying to match type Object
  with type Function Int
while checking that expression bar
  has type { foo :: Int
           }
in value declaration foo
```
Is there any reason why it cannot use `{ foo :: Int }` instead of `Object`?
```
Could not match type

    { foo :: Int }

  with type

    Function Int
```

**Comment by garyb** [comment]
You could say the same about `Function` appearing here too, rather than `Int -> Int`.

I think it's down to the way the types are checked: the type constructor for any record is `Object` and that is the part that is first found not to match the other type - we've "stepped into" the record in the typechecker. You can see it does still mention `{ foo :: Int }` in the part underneath.

**Comment by user471** [comment]
>the type constructor for any record is Object and that is the part that is first found not to match the other type

Could this part be skipped? I don't see how mention Object instead of record type can be helpful.

**Comment by garyb** [comment]
I don't think it can be skipped as such, as this is how the typechecker works, but maybe there's something we could do to tweak the error later, to recover the record type in the main error... @paf31?

**Comment by user471** [comment]
I mean, skip it in error reporting.

**Comment by paf31** [comment]
This would be implemented as a hint, or perhaps we just add a special case to the unifier, if this is really so common.

**Comment by user471** [comment]
> if this is really so common.

I work with records most of the time and this errors are very common.

**Comment by paf31** [comment]
Closing, since I think the error is clear enough, you just have to read the right part:

```
while checking that expression bar
  has type { foo :: Int
           }
```
