### ISSUE TITLE
typeclass constraints not seeing non-exported local type

### ISSUE THREAD

**Issue by clinuxrulz** [purescript/purescript#1856]
bug can be found in

    module Main.Model.Modes.TypeBug
      ( someFunc
      ) where
    
    import Prelude
    
    import Control.Monad.State.Trans
    
    newtype A = A {}
    
    someFunc :: Int -> Int
    someFunc = (+1)
    
    someOtherFunc :: forall m. (MonadState A m) => Int -> m Unit
    someOtherFunc a = do
      return unit

compiling gives

    Unknown type Main.Model.Modes.TypeBug.A

changing the exports to

    module Main.Model.Modes.TypeBug
      ( someFunc
      , A(..)
      ) where

now everything compiles fine. But I've hit a case where I do not want to export A(..) (This is a shorter code to demonstrate the problem)

**Edit**: I'm on psc version 0.7.5.3

**Comment by LiamGoodacre** [comment]
Also present on `0.7.6.1`

**Comment by garyb** [comment]
Thanks for the report. There's a chance this is already fixed in 0.8, but I've not checked yet.

**Comment by paf31** [comment]
This seems to be fixed in master.
