### ISSUE TITLE
Array parse error

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1857]
```
y = [show x.Foo]
```
has error
```
  Unable to parse module:
  unexpected "Foo"
  expecting identifier or string literal
```
but 
```
y = bar [show x.Foo]
```
doesn't
```
  Unable to parse module:
  unexpected [
  expecting no indentation or end of input
```

**Comment by paf31** [comment]
Is the issue just that the second error's location should be more accurate?

**Comment by user471** [comment]
>Is the issue just that the second error's location should be more accurate?

No, I think error message should be the same ``` unexpected "Foo"``` because ```unexpected [``` doesn't make sense to me.

**Comment by paf31** [comment]
I get `unexpected "Foo"` in the latest compiler.
