### ISSUE TITLE
Disallow depending on git for published packages?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1858]
If we have a `bower.json` like this:
```
{
  "dependencies": {
    "purescript-foo": "https://github.com/random-person/purescript-foo#abd2523ffe19395"
  }
}
```
I think `psc-publish` should refuse to create the JSON file. Published packages should only be depending on other published packages, I think. This can be very annoying if other dependencies you use also depend on `purescript-foo`.

Note that I'm still very much in favour of being able to declare such dependencies, just not in published libraries.

**Comment by michaelficarra** [comment]
When it's a SHA, the only real concern is someone deleting the repo. It'd be an easy :+1: from me if this was for references to a branch/tag. But there's not too much legitimate concern about SHAs.

**Comment by hdgarrood** [comment]
Ah ok, I should clarify: I really meant, anything other than a version range should be rejected.

**Comment by michaelficarra** [comment]
Okay, I don't see how that relates to my point.

**Comment by hdgarrood** [comment]
I think there is concern about anything other than a version range, because I think it can screw up other libraries.

Let's say you depend on A and B, both of which depend on C. A uses a normal version range for its dependency on C, but B uses a git url (which happens to point to a different repository entirely, let's say). I *think* what happens here is that you get the one B points to, with no warning from Bower. I'm going to check this now.

**Comment by hdgarrood** [comment]
SHAs can also disappear if they are on branches that get deleted too, I think? They stay around for a short time but I think they get garbage collected.

**Comment by garyb** [comment]
I'd say branches are more problematic than hashes even - bower locally caches whatever it downloads the first time it fetches from a branch, so if further changes are pushed to it people can end up with different things for the same dependency, depending on when they install. At least with hashes you get the same thing every time, assuming the commit hasn't been deleted.

**Comment by hdgarrood** [comment]
Ok, I was actually wrong, you do get a message about version incompatibility with that situation I described earlier, which is a lot better than silently messing everything up. However, it does make it extremely likely that bower won't be able to find an install plan. I think packages that are on Pursuit shouldn't be doing this. On a related note, I think we should also consider rejecting packages which have a "resolutions" property in their bower.json.

**Comment by paf31** [comment]
Is this because of a problem with Bower or something else? I think I would quite like to be able to use Git SHA hashes for dependencies as a last resort, if/when we implement our own package manager.

**Comment by hdgarrood** [comment]
I wouldn't describe it as a problem with Bower. I think we should disallow non-version-range constraints and resolutions for packages we publish to pursuit, because a) they widen the scope of what you might get from transitive dependencies from other published purescript/bower packages to literally any code that's available on github, or via a tarball from any random website, or whatever, and b) they make conflicts extremely likely, if any other dependency depends on the same package.

I still think they can be really useful while you're playing around with something, or if you've made some change in a dependency and pushed it to your fork on github but not cleaned it up enough to be merged yet or something. I just don't think they belong on pursuit.

**Comment by hdgarrood** [comment]
Maybe this restriction should be on purescript-stackage instead, when we get around to it, actually.

**Comment by michaelficarra** [comment]
@hdgarrood I don't see how a SHA is any worse than `>=0 <=999` or `*`.

**Comment by hdgarrood** [comment]
The way I see it, if one of your dependencies depends on something (call it A) via a SHA, then that pretty much guarantees a conflict if any other dependency depends on A.

**Comment by garyb** [comment]
I'm not sure the restriction belongs in pursuit as doing so doesn't actually stop you from releasing a package - it just means you can't publish the documentation.

**Comment by hdgarrood** [comment]
@garyb Yeah, good point. I'm going to close this for now, then. Maybe worth revisiting if/when the packaging situation changes.
