### ISSUE TITLE
psc suggesting to import everything from Prelude

### ISSUE THREAD

**Issue by cdepillabout** [purescript/purescript#1862]
When compiling the following file in the linked commit from the purescript-email-validate package, psc suggests that I import everything from Prelude, even though I am not using everything from Prelude.

https://github.com/cdepillabout/purescript-email-validate/blob/4b47b9c05fbaa9596d4139a7c375eff6c89a0b3c/src/Text/Email/Validate.purs#L11

Here is the output of `pulp build`:

```
$ pulp build
* Building project in /home/ec2-user/git/purescript-email-validate
psc: No files found using pattern: src/**/*.js
Warning found:
in module Text.Email.Validate
at /home/ec2-user/git/purescript-email-validate/src/Text/Email/Validate.purs line 11, column 1 - line 13, column 1

  Module Prelude has unspecified imports, consider using the explicit form:

    import Prelude (class Applicative, class Apply, class Bind, class BooleanAlgebra, class Bounded, class BoundedOrd, class Category, class DivisionRing, class Eq, class Functor, class ModuloSemiring, class Monad, class Num, class Ord, class Ring, class Semigroup, class Semigroupoid, class Semiring, class Show, Unit, Ordering(EQ, GT, LT), add, ap, append, apply, asTypeOf, bind, bottom, compare, compose, conj, const, disj, div, eq, flip, id, liftA1, liftM1, map, mod, mul, negate, not, one, otherwise, pure, return, show, sub, top, unit, unsafeCompare, void, zero, (#), ($), (&&), (*), (+), (++), (-), (/), (/=), (<), (<#>), (<$>), (<*>), (<<<), (<=), (<>), (==), (>), (>=), (>>=), (>>>), (||))



See https://github.com/purescript/purescript/wiki/Error-Code-ImplicitImport for more information,
or to contribute content related to this warning.

* Build successful.
```

It should only be suggesting something like this:

```purescript
import Prelude ((==), (<<<), ($), show, map)
```

**Comment by garyb** [comment]
Woah, thanks for the report. I've definitely not seen this before, so the example will be useful to test against too.

**Comment by telser** [comment]
Hey @garyb I've hit this bug using 0.8.1-rc.1 that was published via npm while building slamdata/purescript-jtable master branch. Is this still on track to be fixed? Anything I can do to help?

**Comment by garyb** [comment]
0.8.1 has some more serious problems (#1905) so I imagine we'll be releasing another version soonish. I've not looked into this at all yet though, so don't really know what would be causing it.

With #1903 in 0.8.1 it should be possible to open-import `Prelude` now as long as all the other imports are made explicit, so maybe that will avoid the warning?

**Comment by telser** [comment]
>  0.8.1 has some more serious problems (#1905) so I imagine we'll be releasing another version soonish. 

I saw #1905 and was going to ask if that's why it is marked as an rc on npm. 

> With #1903 in 0.8.1 it should be possible to open-import Prelude now as long as all the other imports are made explicit, so maybe that will avoid the warning?

I'm still seeing it with no other open imports in jtable. Is the preference going to be to leave just prelude as an open import going forward? If so I'll make that change to the pull requests I've submitted to various libs.

**Comment by garyb** [comment]
Not necessarily, no, I just wondered if that would avoid triggering the spurious warning. I've actually been avoiding the `Prelude` import entirely in the core libraries I'd been updating, favouring importing directly from the defining modules - it doesn't particularly matter though, as long as it's not warning :smile:

**Comment by garyb** [comment]
Oh, and it's marked as an RC due to the "no takebacks" rule on `npm` :wink:

I made a mistake publishing once and it forever ruined that version, so now I always publish an RC first to ensure it works. When testing that everything was good I ran into #1905 which interrupted me releasing it as non-RC.
