### ISSUE TITLE
Include more information about why constraints are missing

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1866]
Given this code:
```
> let f x y = x + x * y
Error found:
in module $PSCI
at  line 1, column 5 - line 1, column 21
  No type class instance was found for
    Prelude.Semiring _0
  The instance head contains unknown type variables. Consider adding a type annotation.
in value declaration f
where _0 is an unknown type
```

the error message does the job well enough, I think.

However, for functions with large bodies, it can be difficult to track down why the constraint is required - which is a problem if you weren't intending your function to have that constraint at all. GHC includes a little extra information for missing instance errors, something like this:

```
    No instance for (Num a1) arising from a use of ‘+’
    In the expression: x + x * y
```

Could psc do this too?

**Comment by user471** [comment]
Is it just bad error position? I added it to https://github.com/purescript/purescript/issues/1801#issuecomment-180215949

**Comment by garyb** [comment]
No, the idea here is to explain which value within an expression causes a constraint to be required, so if you use `get` for the `State` monad it will specifically mention the expression involving `get`, not just print an error for the whole thing.

**Comment by user471** [comment]
>the idea here is to explain which value within an expression causes a constraint to be required

If there is a value that causes an error, it could be explain by error position. With correct position it would seem pretty obvious. 
![error](https://cloud.githubusercontent.com/assets/5988253/12845753/2d08e0ae-cc19-11e5-8d23-58d0f051c621.png)

**Comment by hdgarrood** [comment]
There's no harm in a little redundancy here, I think, and in fact I think we should be doing everything we can to make errors easier to understand (as long as it doesn't make them too long). Also, not all errors are reported through editors with fancy tooling like that; take CI build logs, for example.

**Comment by user471** [comment]
>Also, not all errors are reported through editors with fancy tooling like that; take CI build logs, for example.

Then I think there should be a common solution for all errors not just for specific one. 
Instead of error location compiler could show the code and point the error position in it, similar to Elm
http://elm-lang.org/assets/blog/error-messages/0.15.1/naming.png

So the error would be
```
Error found:
in module $PSCI

let f x y = x + x * y
              ^
  No type class instance was found for
    Prelude.Semiring _0
  The instance head contains unknown type variables. Consider adding a type annotation.
in value declaration f
where _0 is an unknown type
```

**Comment by hdgarrood** [comment]
Yes, purescript-psa does this. But actually, I think the correct error span in this case is the whole right hand side of that binding, because that's the expression where type checking failed:

```
let f x y = x + x * y
            ^^^^^^^^^
```

The fact that type constraints arise from uses of particular values is specific to how type classes work, and no other language feature has this property, so I think it's appropriate that the errors reflect this.

**Comment by hdgarrood** [comment]
Also, I think this additional information would be much more helpful than an error span like you suggest if the person reading the error wasn't already familiar with the particular function or value causing the error. Most people are familiar with `+`, but if it were something else, it would be much less obvious.

**Comment by hdgarrood** [comment]
Maybe we should move the original source span reporting into the compiler, though, as obviously psa can't do anything about errors in psci.
