### ISSUE TITLE
Deferred type errors

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#1868]
Learned about [`-fdefer-type-errors`](https://ghc.haskell.org/trac/ghc/wiki/DeferErrorsToRuntime) via [Twitter](https://twitter.com/paf31/status/695685629300969472). Using live reloading on Try PS I wanted to continue testing working parts of my code while I matched up types in another part. I believe this is the golden egg of dynamically typed workflows. @rvion presented an additional scenario for identifying more type errors at once in #2222.

**Comment by paf31** [comment]
Deferred type errors in GHC rely on laziness in a crucial way, since type errors get code gen'd as error calls, essentially, but maybe we can work around that.

**Comment by spicydonuts** [comment]
Would implementing an otherwise pure function as that line's compile error cause problems (seems like it might be weird for currying):

```purescript
foo x = bar x
```
into:
```js
const foo = () => throw new Error("Compile error: Unknown value `bar`", ...)
```

**Comment by natefaubion** [comment]
I think you could probably push the errors to the nearest function, case, if, etc. If a type error is not behind a function guard, it gets pushed to the usage sight. While it isn't as simple as relying on laziness, it could probably get you most of the way there for how people want to use the feature.

A translation might be:
```purescript
obviousError :: Int
obviousError = "Foo"

simpleCase :: Int -> Int
simpleCase = case _ of
  42 -> obviousError
  x | x > obviousError -> 0

simpleFn :: Int -> String
simpleFn x = x + 1

simpleFn2 :: String -> String
simpleFn2 x = x <> 1
```
```javascript
function __throw(err) {
  throw new Error(err);
}
var obviousError = "Foo";
var simpleCase = function(_1) {
  if (_1 == 42) {
    return __throw("Type mismatch: Int String while checking expression obviousError");
  }
  if (_1 > __throw("Type mismatch: Int String while checking expression obviousError")) {
    return 0;
  }
};
var simpleFn = function(x) {
  return __throw("Type mismatch...");
}
var simpleFn2 = function(x) {
  return x + __throw("Type mismatch...");
}
```

**Comment by paf31** [comment]
I think we could use the definedness checker state here, which basically tracks whether we're under at least one function binder. In that case, it should be safe to insert a `throw`.

However, the other tricky bit here is how this interacts with elaboration.

**Comment by paf31** [comment]
Closing until we have a proposal for a simple, safe, compositional semantics for this.
