### ISSUE TITLE
Reexport wrongly includes aliased modules

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1872]
When reexporting a module, other imports of the same module are included even if they are aliased. This seems like a bug to me.

``` purescript
-- A.purs
module A where
data X = X
data Y = Y

-- B.purs
module B (module A) where
import A (X(X))
import A (Y(Y)) as C

--
import B as B
B.X -- available
B.Y -- also available
```

Curiously I do get a warning about the qualified import.

```
Warning found:
in module B
at /private/tmp/example/src/B.purs line 3, column 1 - line 3, column 17

  The import of module A is redundant


See https://github.com/purescript/purescript/wiki/Error-Code-UnusedImport for more information,
or to contribute content related to this warning.
```

I can work around this by importing the module qualified as itself.

``` purescript
-- B.purs
module B (module A) where
import A (X(X)) as A
import A (Y(Y)) as C

--
import B as B
B.X -- available
B.Y -- no longer available
```

**Comment by garyb** [comment]
Thanks, yep, that's a bug.

The second problem I think it's complaining about `import A (Y(Y)) as C` as you're not making use of `C`.

**Comment by tfausak** [comment]
Right, but that's not really a problem. It's correct. I thought it was funny that it would warn me it's not used and then export it anyway :smile:
