### ISSUE TITLE
Derive Functor instances

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1875]
See https://mail.haskell.org/pipermail/haskell-prime/2007-March/002137.html.

**Comment by LiamGoodacre** [comment]
:+1: :+1:

**Comment by phadej** [comment]
I'd try to solve this in `TemplateHaskell` / reflection way. I.e. that one could write PureScript to generate PureScript code. So the instance deriving code could live in the user land.

**Comment by jdegoes** [comment]
> I'd try to solve this in TemplateHaskell / reflection way. I.e. that one could write PureScript to generate PureScript code. So the instance deriving code could live in the user land.

If that becomes possible at some point, then we can also do deriving for contravariant functors, invariant functors, and profunctors.

**Comment by paf31** [comment]
Agreed, that would be ideal. I will propose Template PureScript as a GSOC project again this year.

**Comment by jdegoes** [comment]
@paf31 Good idea! Are you tracking possible projects yet? I have a few ideas.

**Comment by paf31** [comment]
[Yes](https://github.com/purescript/gsoc)

Let's please discuss projects on IRC though. I want to come up with a short, focused list of ideas, especially since we'll probably get at most two slots.

**Comment by damncabbage** [comment]
Please pardon the thread necromancy. 😅

So currently deriving for Eq, Ord and Generic are currently checking for specific classes exposed by modules named in a particular way, for example as per [Eq from `Language.PureScript.Sugar.TypeClasses.Deriving`](https://github.com/purescript/purescript/blob/144dd6f020167d2a21095e315afc5e60b3c2bc2f/src/Language/PureScript/Sugar/TypeClasses/Deriving.hs#L47):
```haskell
dataEq :: ModuleName
dataEq = ModuleName [ ProperName "Data", ProperName "Eq" ]

-- ...
 | className == Qualified (Just dataEq) (ProperName "Eq")
-- ...
```

If a `derive instance …` for Functor (and maybe Traversable and Foldable) were to be added, would you do similarly (checking for `class Functor` from `Data.Functor` specifically), or would you want a different approach taken?

**Comment by paf31** [comment]
I think it would use the same approach.

**Comment by damncabbage** [comment]
Got it; thanks. 😄
