### ISSUE TITLE
Allow deriving for records

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1877]
Since all deriving instances would be the same no matter where they are defined, I think this should be allowed.
```
derive instance eqFoo :: Eq {foo :: Int}
```
So even if it would be defined in several modules, compiler can use any instance because they are have identical implementation.
```
module A where
derive instance eqFoo :: Eq {foo :: Int}

module B where
derive instance eqFoo :: Eq {foo :: Int}
```

**Comment by zudov** [comment]
> All deriving instances would be the same no matter where they are defined

How about:

```haskell
module A where
  derive instance ordFoo :: Ord { foo :: Int, bar :: String }

module B where
  derive instance ordBar :: Ord { bar :: String, foo :: Int }
```

`{ foo :: Int, bar :: String }` unifies with `{ bar :: String, foo :: Int }`, but their derived `Ord` instances aren't the same. 

If [I understood this correctly](https://github.com/purescript/purescript/pull/1870#issuecomment-181150033), `Ord` deriving depends on the order of `fields`/`constructors`. 

However in case of `Eq` I think it could work. But I don't think it would be easy to implement.

**Comment by user471** [comment]
>If I understood this correctly, Ord deriving depends on the order of fields/constructors. 

I think for pure records they shouldn't depend on the order. So, fields should be sorted alphabetically, then Ord instances would be the same.

**Comment by paf31** [comment]
Let's say you defined `instance Eq { | r }` in `Prelude`, the only place where it would not be an orphan. Then how would you implement it? If you used `==` or `===` in Javascript, you would not get the structural equality given by `Eq` on the fields, which is probably what you'd want. And restricting field types to those where `Eq` is just `===` is not an option right now.

One option is to add a new type of constraint to the language, something like `(Row Eq r) => Eq { | r }`, where `Row :: (k -> Constraint) -> # k -> Constraint` is baked in, and `Row c` means constraint `c` holds on the type in each label. Its evidence would be a record of dictionaries. I don't have the motivation to work on that at the moment, but it might be a neat solution, and I'd happily help someone who wanted to put the effort in to implement it.

**Comment by natefaubion** [comment]
I think what's being said is that, even though its an orphan, since it can only be derived by the compiler, its irrelevant as each derived instance would be the same and you could use any one of them.

**Comment by garyb** [comment]
@natefaubion that's true, but it only applies to closed records, as Phil mentioned.

The other slightly tricky thing here is that I'm not sure where the instances would "come from": a dictionary is an actual value at the moment, so it seems a bit weird that you would have to specifically derive instances _somewhere_ for records for them to become comparable. Really you'd want "fully automatic" deriving for these instances, and then in codegen some function could construct the dictionary for arbitrary records (when the extra constraint satisfaction stuff holds, as that evidence would still be needed to construct the instance), but that seems like it might have issues with performance, complexity, etc.

**Comment by user471** [comment]
>Let's say you defined instance Eq { | r } in Prelude, the only place where it would not be an orphan. 

No. Nothing should be defined is `Prelude`. Everyone define record instances in their modules, so for records there should be an exception about orphans, because instances have the same implementation.

>Then how would you implement it?
How is it different from?
```
newtype Foo r = Foo { | r }
derive instance eqFoo :: Eq Foo
```
deriving should work in the same way as for newtype but without newtype.

**Comment by user471** [comment]
>The other slightly tricky thing here is that I'm not sure where the instances would "come from"

Another solution and I think it's much better.
Compiler should automatically generate this instances.
I guess compiler right now can get a list of all pure records in all modules.
For example the list is `{id :: Int}` `{size :: Int}` `{name :: String}`. So, compiler could generate this code.
```
derive instance  Eq {id :: Int}
derive instance  Eq {size :: Int}
derive instance  Eq {name :: String}
```
and put it somewhere where they wouldn't be an orphans.

**Comment by paf31** [comment]
Closing, see above.
