### ISSUE TITLE
Ctrl-c kills psci

### ISSUE THREAD

**Issue by jchayat** [purescript/purescript#1878]
Normally (see bash, ipython) pressing Ctrl-c just creates a new blank line without executing current line.
This is standard behaviour for a shell/REPL.
It would be good to adhere to that standard.
We have Ctrl-d to end the session.

**Comment by michaelficarra** [comment]
What version are you using? This was fixed back in September: https://github.com/purescript/purescript/pull/1489

**Comment by jchayat** [comment]
0.8 on a Mac.

**Comment by hdgarrood** [comment]
Are you using pulp psci? If so, you might need to update pulp.

**Comment by jchayat** [comment]
Yes, it only seems to happen in pulp psci.
I'm using pulp 8.0.0. I'll open an issue there.

BTW, in psci, Ctrl-c seems to break two lines instead of just one.

**Comment by jchayat** [comment]
[Issue](https://github.com/bodil/pulp/issues/176) opened for pulp.
