### ISSUE TITLE
Empty function's body is parsed without error

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1881]
```
foo =
bar :: Int
bar = 1
```

**Comment by michaelficarra** [comment]
Isn't this just parsing as

```purs
foo = bar :: Int
bar = 1
```

which is perfectly fine PureScript code?

**Comment by user471** [comment]
Yes, but should it parse it such way?
I think only something like this should be parsed
```
foo =
  bar :: Int
bar = 1
```

**Comment by spicydonuts** [comment]
That could be very surprising.. Is there any case where it would be a problem to require indentation?

**Comment by paf31** [comment]
I agree that this should be a parse error without indentation.
