### ISSUE TITLE
Incorrect polymorphic type's name

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1882]
```
module Test where
import Prelude
import Data.Array

bar :: forall a. Array a -> Int -> _
bar l i = l !! i
```
`psci`
```
> :b Test
bar :: forall a. Array a -> Int -> Maybe a0
```
warning
```
in module Test

    Wildcard type definition has the inferred type

      Maybe a0
```
Should be `Maybe a`

**Comment by michaelficarra** [comment]
I don't see anything wrong. What do you think the issue is? Please provide the expected behaviour with issues you open.

**Comment by user471** [comment]
`Maybe a0` instead of `Maybe a`

**Comment by hdgarrood** [comment]
I see the problem - if you took that type signature from the output of ":browse Test" and put it into the source file, you'd get a compile error because of the undefined type variable a0.

**Comment by user471** [comment]
It also affects compilation.
```
data Foo a = Foo a

foo :: forall a. a -> _
foo x = Foo x

bar = foo 1
```
```
A type variable has escaped its scope.

in the expression foo 1
in value declaration bar

See https://github.com/purescript/purescript/wiki/Error-Code-EscapedSkolem for more information,
or to contribute content related to this error.
```
I guess it's relevant to https://github.com/purescript/purescript/issues/1793

**Comment by paf31** [comment]
#1793
