### ISSUE TITLE
Remove Markdown documentation from core libraries?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1883]
Pursuit has been around for a while now and we know it works, so I think we should consider removing checked-in Markdown documentation from core libraries.

See also: https://groups.google.com/forum/#!topic/purescript/9GX6--tOmGE

**Comment by garyb** [comment]
:+1: I've already started doing so in the libraries I've updated.

**Comment by kRITZCREEK** [comment]
If you wanted to look at documentation offline you'd need to run psc-docs inside `bower_components/purescript-*` then?

**Comment by hdgarrood** [comment]
Yeah, I might get around to that eventually. In the meantime there's "pulp docs --with-dependencies" :)

**Comment by kRITZCREEK** [comment]
uhh fancy! Thanks for the hint :+1:

**Comment by spion** [comment]
Does this include the REDAME?

If so, please at least recommend that a link to the pursuit docs is placed in the readme. 

Nothing more frustrating than Haskell libraries with no github README: https://github.com/lpsmith/postgresql-simple

**Comment by hdgarrood** [comment]
`pulp docs --with-dependencies` doesn't do anything with READMEs, but I don't think it needs to, as it's easy enough to just open `bower_components/purescript-foo/README.md`.

We do recommend linking to pursuit docs on READMEs in the wiki [Style Guide](https://github.com/purescript/purescript/wiki/Style-Guide). Also, Pursuit displays READMEs for all projects &mdash; if you don't write one, you'll get a big yellow box saying "No README available", which is a fairly strong hint that you should write one, I think. Given also that the vast majority of PureScript libraries do have READMEs (at least, the ones that people still use and which are kept up to date do), I don't think we need to worry about people not writing READMEs.

However lots of PureScript libraries have extremely minimal readmes, like postgresql-simple, and that's a perfectly fine approach in my book. If you look on Hackage, the documentation that might otherwise go into a README is part of the generated Haddock docs, in the obvious module (Database.PostgreSQL.Simple).

**Comment by spion** [comment]
@hdgarrood its still important to cater to the absolute beginner IMO. Nothing in the postgres-simple repo even remotely indicates the right place to look (Hackage). It may look perfectly fine, but I'd say its a disaster in practice: the github page is a dead-end for someone who doesn't know about Hackage.

**Comment by garyb** [comment]
This is the approach I've been taking as a minimal readme: https://github.com/purescript-contrib/purescript-http-methods#purescript-http-methods and is the pattern the new non-documentation-provided core libraries will follow.

**Comment by hdgarrood** [comment]
Have you ever encountered someone who found postgresql-simple on github, was sufficiently experienced with haskell that they would actually be able to use it, and hadn't heard of Hackage? I'm not convinced that this actually happens. If beginners aren't being taught about Hackage, then that's a problem with the tutorials aimed at absolute beginners.

We do mention Pursuit in lots of places, particularly the places where beginners would start, like the website, and the PureScript by Example book, and also, most libraries have "documentation is on pursuit" in their READMEs with a link, so I don't think we need to worry about people not having heard of Pursuit.

**Comment by spion** [comment]
I have, but I can only give you my word for it :) I hope you would agree that a self-taught beginner that knows of github but not about hackage (coming from other languages) is a likely occurrence.

"Documentation is on pursuit: link" is perfectly fine btw

**Comment by Thimoteus** [comment]
What about when Pursuit is down, or if something like the move to 0.8 happens again (where all the docs had to be reuploaded over some bit of time)?

For the core libraries especially I think the more backups available the better.

**Comment by hdgarrood** [comment]
>  I hope you would agree that a self-taught beginner that knows of github but not about hackage (coming from other languages) is a likely occurrence.

Absolutely, but you've missed out the most important precondition: "sufficiently experienced with haskell that they would actually be able to use it [the library]".

I just find it a little hard to believe that people could get to the haskell level necessary to be able to use stuff like that and not have heard of hackage. "Self-taught" really means using resources that other people created and put on the web, which have got to refer to Hackage at some point. Maybe Haskell existed for a while before Hackage, though, so perhaps some of the Haskell resources don't mention Hackage. But knowing what PureScript resources there are, I can't see it 

For instance, googling stuff like "haskell json", "haskell web framework", "haskell filesystem" all have the first few results either actually Hackage, or pages that prominently link to Hackage (such as on the Haskell wiki).

The first time I looked at postgresql-simple, it only showed me the alt text (slow internets), so I didn't realise it was just one of those badges. I agree that I'd rather have text than just the badge.

**Comment by hdgarrood** [comment]
@Thimoteus My perception of the current state of the ecosystem is as follows. Please correct me if I'm wrong, @paf31, @garyb, or anyone else.

PureScript and Pursuit are <1.0 because things such as this happen. We want to focus on improving the language and tools over avoiding disruption of people's workflows. Of course we try to avoid disrupting workflows where possible, but if these two things are ever in contention, the first usually wins. I think this is the right approach for now, too, because we have to be able to make breaking changes if we want to end up with a good language. If that's a deal breaker then perhaps PureScript isn't suitable for you just yet (perhaps we could communicate this better).

I think `pulp docs --with-dependencies` handles both of the situations you describe better than checking in Markdown docs does, anyway.

**Comment by starper** [comment]
One thing that I've noticed is if you have a link like `Module documentation is published on Pursuit.` in README, then the same link is placed on the library's Pursuit page (page has a link to itself) which looks kind of weird. I guess Pursuit shouldn't show the README file then?

Btw one thing that I would really love to have, is `changelog` (on Github or Pursuit), some page were you can see all the changes without looking through all the commits that were made since the last version.

**Comment by hdgarrood** [comment]
@starper I agree that it's a bit weird, but I don't think we can a) detect this reliably enough or b) accurately judge whether a README also contains other important information, so I'd rather leave it as it is. If anyone has other suggestions, though, I'm all ears. :)

Most libraries use GitHub's releases feature for the changelog, I think. For example: https://github.com/purescript/purescript-prelude/releases

**Comment by starper** [comment]
@hdgarrood Oh, I didn't know that. Thanks =) But maybe having something like this on Pursuit is a good idea too?

**Comment by hdgarrood** [comment]
Yeah, quite possibly. If we were going to do that I think I'd like to get people to start using a CHANGELOG.md file inside the repo instead.

**Comment by paf31** [comment]
I'm moving this to the [roadmap](https://trello.com/b/1cxCKURC/purescript-roadmap).
