### ISSUE TITLE
Shorter deriving syntax

### ISSUE THREAD

**Issue by agrafix** [purescript/purescript#1891]
Currently a lot of my purescript type definitions look like this:

``` purescript
newtype MeasurementId = MeasurementId Int

derive instance genericMeasurementId :: Generic MeasurementId

instance eqMeasurementId :: Eq MeasurementId where
    eq = gEq

instance showMeasurementId :: Show MeasurementId where
    show = gShow

instance ordMeasurementId :: Ord MeasurementId where
    compare = gCompare

-- ...
```

I would like to propose the following syntax to make this more readable:

``` purescript
newtype MeasurementId = MeasurementId Int
    deriving 
    ( genericMeasurementId :: Generic MeasurementId
    , eqMeasurementId :: Eq MeasurementId
    , showMeasurementId :: Show MeasurementId
    , ordMeasurementId :: Ord MeasurementId
    )
```

There are some requirements for type classes listed in the deriving clause:
- The type class is the `Generic` type class
- Current type derives the `Generic` typeclass
- There's a `Generic` implementation for the listed type class

I'm not sure if it's easy or even possible to figure out the last point though?

**Comment by paf31** [comment]
One issue here is that we'd need a way to distinguish between `deriving` and the new `deriving newtype` syntax.

I'm not sure if this is worth it to save a few lines, although for generated code, maybe it's more beneficial.

**Comment by LiamGoodacre** [comment]
Close? @paf31

**Comment by paf31** [comment]
Yes, thanks.

**Comment by mjhoy** [comment]
> One issue here is that we'd need a way to distinguish between deriving and the new deriving newtype syntax.

@paf31 I'm curious what this refers to? Can't seem to find it in the docs or in the release notes.

**Comment by paf31** [comment]
`derive newtype instance name :: Cls ty ty ... ty`

which is like our version of `GeneralizedNewtypeDeriving` from GHC.

**Comment by mjhoy** [comment]
Ah, I thought you meant there was already a `deriving` keyword.

I still find deriving to be a chore in Purescript, especially compared to Haskell, and it makes creating `newtype` harder than it should be -- which is unfortunate because that's a very easy way to introduce more type safety. I'm working on putting together some thoughts. Might open a new issue about, or chat on slack. Thanks.
