### ISSUE TITLE
Automatically generate a Generic instance

### ISSUE THREAD

**Issue by agrafix** [purescript/purescript#1892]
GHC supports `-XDeriveDataTypeable`, it would be very cool if typescript had something alike. As far as I am aware, currently PureScript does not have a concept of language extensions, but automatically generating `Generic` instances should be configurable at least on a per module basis. One option here would be to allow per module pragmas, like in haskell?

**Comment by hdgarrood** [comment]
What's wrong with the current setup? Is it just that you don't want to have to write the `derive instance generixFoo` stuff?

**Comment by agrafix** [comment]
This should be very useful together with #1891

**Comment by paf31** [comment]
You can use `derive instance name :: Generic MyType` for this.
