### ISSUE TITLE
"binderToJs: Invalid ConstructorBinder in binderToJs" v0.8.0.0

### ISSUE THREAD

**Issue by clinuxrulz** [purescript/purescript#1895]
psc: An internal error ocurred during compilation: "binderToJs: Invalid ConstructorBinder in binderToJs"
    Please report this at https://github.com/purescript/purescript/issues
    psc: thread blocked indefinitely in an MVar operation
    Compiling FRP.Sodium.Trans

psc version 0.8.0.0

source: https://github.com/clinuxrulz/purescript-sodium/blob/f2c25a103f5efc55fb15a10c889d388a1f7992be/src/FRP/Sodium/Trans.purs

method: ```mkEventNode n@(EMap mapData)```

If that method gets commented out then the internal error goes away. So its something in that method.
I do not understand what is wrong, but though I'd report it.

**Comment by garyb** [comment]
Definitely a bug, thanks for the report. There may be another problem here which should be an error, as for this to occur it would seem that we have a pattern for a constructor but the compiler doesn't think it's a newtype or data constructor at the point it reaches JS codegen. If it is an error we should have complained about it earlier.

**Comment by clinuxrulz** [comment]
Yes, its an error in my code missed by the compiler.
Just spotted it. ```newtype EMapDataF m b a = EMapDataF (a -> b) (Event m a)```, an invalid use of ```newtype```.
