### ISSUE TITLE
Question: C++11 backend - uncurried functions in the FFI

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#1904]
I've been experimenting with the C++11 backend using uncurried (i.e. normal multiarg) FFI functions, and the compiler automatically generating curried wrappers (for its own use). So far, it's been working quite nicely, and makes the FFI a little easier to use.

I was wondering if you guys had explored doing something similar in the standard JS backend, and if you had decided against it for some reason. If so, I'd like to hear your thoughts, before I put any more work into it and make it official (for the C++11 backend, that is).

Thanks!

**Comment by paf31** [comment]
This seems to be the only sensible alternative to curried functions everywhere, if we want to keep modularity. I think it makes sense for the C++ backend, if it improves the FFI, but maybe less for Javascript, since it would either need a (minimal) runtime, or add an overhead to every function.

**Comment by andyarvanitis** [comment]
Great, thanks. I was just hoping to avoid some large drawback I might have been overlooking, especially since it would affect end-users and libraries.

**Comment by hdgarrood** [comment]
I have no idea what working with the FFI in C++ is like, but I think there's a lot to be said for doing these kinds of conversions in "userland". If something has gone wrong in FFI code it's valuable to keep these things as simple as possible, I think.

To solve the issue that currying foreign functions by hand is error prone and painful, I prefer something like https://pursuit.purescript.org/packages/purescript-eff-functions

**Comment by andyarvanitis** [comment]
If you don't mind, I think I'll close this to reduce the issues backlog. I've gotten the information I was interested in, and have proceeded with the C++11 changes. It was really just a question and not necessarily applicable to the JS backend anyway.

**Comment by paf31** [comment]
Sounds good, thanks.
