### ISSUE TITLE
Missing wiki page on "Error-Code-InfiniteType" as specified in psci 0.8.0.0

### ISSUE THREAD

**Issue by stevenproctor** [purescript/purescript#1911]
I am working through PureScript by Example (on my own, and got us working though it as part of a Programming Languages Study Group at work), and was doing the `reverse` in terms of `foldl`, and my quick first pass resulted in the error:

```
> foldl (\x xs -> x : xs) [] [1, 2, 3, 4]
Error found:
in module $PSCI
at  line 1, column 8 - line 1, column 23

  An infinite type was inferred for an expression:

    Array _1


while trying to match type Array _1
  with type _0
while checking that expression ((:) x) xs
  has type _0
in value declaration it

where _0 is an unknown type
      _1 is an unknown type

See https://github.com/purescript/purescript/wiki/Error-Code-InfiniteType for more information,
or to contribute content related to this error.
```

As I got an Infinite Type error, and was wanting to get a better picture of what that entailed, I tried going to the url given (https://github.com/purescript/purescript/wiki/Error-Code-InfiniteType), but there is no page there.

Output of `psci --version` for info.

```
$ psci --version
0.8.0.0
```

Not concerned about the answer to the `reverse` (that was only how I stumbled across the missing page), but that the page being referred doesn't take someone to where they might need to go to understand the error message if coming in from a non-ML type system.

**Comment by paf31** [comment]
Not all error pages have content yet. We have an issue to track this on the `roadmap` repo. Note the message says "or to contribute content related to this error". The expectation is that users will add content as they figure out the information from other channels (IRC, etc).

**Comment by stevenproctor** [comment]
No problem.

I saw that message, but wanted to make sure that it was still "there" and not moved, as well as wanting to make sure that it wasn't just missed in what seems to be a myriad of potential type errors that PureScript can now catch up front vs runtime. ;)

**Comment by AppShipIt** [comment]
@stevenproctor Interestingly the fix is `\xs x ->` (arguments are out of order). My understanding is the checker inferred `xs : x` to build infinitely nested `Arrays` instead of one level like `[ 1, 2, 3, 4 ]`. Definitely a ticket to look back at when I try rethinking messages :)

**Comment by stevenproctor** [comment]
Yeah, I realized that after taking a deeper look at the type difference of `foldl` vs `foldr`. ;)

I figured the specific would be easy enough to tackle, but was interested in what an InfiniteType error means from just starting to dig into ML family of types. :grinning:

Just happened to come across this as I thought having an actual error for that type would let me cement it more by looking at the general error in relation to a specific instance of the error.

**Comment by hdgarrood** [comment]
For me, what made this class of error click was it being presented in terms of solving an equation of types: https://github.com/purescript/purescript/issues/703#issuecomment-65313668

In this case, though, I'm a bit surprised that the error talks about unknown types, as I think it's fairly clear what all the types need to be, given that the last argument is an `Array Int`. Is it that the type checker throws an error as soon as it knows something is wrong? Could it instead try to gather some more information from the context first?

**Comment by hdgarrood** [comment]
That is: I feel we ought to get the same error here as if we had written

    [1,2,3] : 0

or similar.

**Comment by paf31** [comment]
Tracked elsewhere, closing.
