### ISSUE TITLE
purescript-dom does not compile with 0.8.2 (Fails to import exported type)

### ISSUE THREAD

**Issue by agrafix** [purescript/purescript#1912]
After 0.8.2 was released, I wanted to update my project currently compiling with 0.8.0 to 0.8.2. This did not work, because `purescript-dom` (Version `0.2.19`) does compile with 0.8.0, but not with 0.8.2 due to this error:

```
Error 1 of 47:

  in module DOM.HTML.HTMLAnchorElement
  at /Users/xxxxxx/frontend/bower_components/purescript-dom/src/DOM/HTML/HTMLAnchorElement.purs line 8, column 24 - line 8, column 43

    Cannot import type HTMLAnchorElement from module DOM.HTML.Types
    It either does not exist or the module does not export it.


  See https://github.com/purescript/purescript/wiki/Error-Code-UnknownImportType for more information,
  or to contribute content related to this error.

Error 2 of 47:

  in module DOM.HTML.HTMLAreaElement
  at /Users/xxxxxxx/frontend/bower_components/purescript-dom/src/DOM/HTML/HTMLAreaElement.purs line 8, column 24 - line 8, column 41

    Cannot import type HTMLAreaElement from module DOM.HTML.Types
    It either does not exist or the module does not export it.


  See https://github.com/purescript/purescript/wiki/Error-Code-UnknownImportType for more information,
  or to contribute content related to this error.
...
```

Looking at `purescript-dom`, `HTMLAnchorElement` actually is exported (see https://github.com/purescript-contrib/purescript-dom/blob/v0.2.19/src/DOM/HTML/Types.purs#L75).

**Comment by garyb** [comment]
I don't get this error actually, could you try clearing out your `output` folder and recompiling?

**Comment by agrafix** [comment]
Clearing the `output` folder helped, thanks! Maybe the purescript compiler should add some kind of checksum and do this automatically on compiler version upgrade?

**Comment by garyb** [comment]
We currently just look at file timestamps to determine whether files have changed so that we do as little work as possible in the compiler, but you're right that some method of invalidating old compilation results would be valuable... I'm just not sure how best to do it :wink: Maybe we could include the version number in the externs filename, as that way upgrading the compiler would mean it wouldn't even look for the old compilation products.

I'm also actually not too sure why this occurred, the changes between 0.8.0 and 0.8.2 shouldn't really have made a difference here. Glad it's sorted anyway!

**Comment by agrafix** [comment]
Yes, including the version number in the externs filename sounds like a solid plan. An alternative would be to add a single "tag" file in the output directory, and if the version there does not match then discard the whole directory.

**Comment by hdgarrood** [comment]
I find that upgrading dependencies sometimes necessitates clearing the output folder. At least I think so. I've never quite managed to reproduce it reliably.

**Comment by agrafix** [comment]
Yeah, you sometimes also need to clear the `bower_components` dir, because bower gets confused with version to use. But that's a different issue...

**Comment by hdgarrood** [comment]
I think it is the same issue. I've had situations like this before:

```
$ rm -r bower_components
(modify version ranges in bower.json)
$ bower install
$ pulp build
(error)
$ rm -r output
$ pulp build
(works)
```

Bower doesn't seem to be confused or working incorrectly at any stage.

**Comment by garyb** [comment]
I've had bower issues, if you already have `bower_components` then change some versions and reinstall without clearing `bower_components` out it can bring up all kinds manual resolutions that shouldn't be needed.

**Comment by hdgarrood** [comment]
Yeah, that's why I usually start by doing `rm -r bower_components`.

**Comment by paf31** [comment]
The externs file already contains the version which created it. We should be filtering by that any time we use the externs files. Can this be closed?

**Comment by hdgarrood** [comment]
:+1:. I do have a suspicion that there is something not quite right around invalidation of compilation products, but without repro steps, I don't see any use in keeping this open.
