### ISSUE TITLE
First open import should be considered as the intended open import

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1915]
In `0.8.2` if you have multiple open imports, it considers the *last* open import to be the primary open import, and gives warnings for all others.

```purescript
module Foo where
import Prelude
import Data.Array
```

Would yield `ImplicitImport` warnings for `Prelude` instead of `Data.Array`

**Comment by garyb** [comment]
Actually, I think this is working as intended. If you have more than one open import it warns about all of them - is that not what you're seeing?

**Comment by natefaubion** [comment]
You are right. I can't reproduce this now with 0.8.3.

**Comment by garyb** [comment]
Maybe it would be better if we only warned about the latter imports, going with the assumption the first one is desired?

**Comment by hdgarrood** [comment]
Perhaps, yes, especially if people are using text editors that apply suggestions for you.

**Comment by kRITZCREEK** [comment]
The Import suggestion functionality I built respects the first open import it finds and keeps it at the top of the import section.
I think it's nicer to only warn for the 2nd, 3rd..., so that we can automatically apply the suggestions
