### ISSUE TITLE
Deleted modules still get found

### ISSUE THREAD

**Issue by agrafix** [purescript/purescript#1921]
This is somewhat related to #1912 : 
- Create a new module Foo
- Create a new module Bar
- Import Bar from Foo
- Compile everything
- Remove module Bar
- Compile everything <-- no errors

**Comment by paf31** [comment]
Can you please include the commands you ran. Is this using `pulp` or `psc` directly?

**Comment by paf31** [comment]
Ping.

**Comment by natefaubion** [comment]
This is easy to reproduce moving modules around:

**Foo.purs**
```purescript
module Foo where
import Bar (bar)
foo = ["var", bar]
```

**Bar.purs**
```purescript
module Bar where
bar = "bar"
```

1. `psc src/*` (everything compiles)
2. `mv src/Bar.purs src/Baz.purs`
3. Rename everything in `Baz.purs`
4. `psc src/*` (everything still compiles even though `Bar` no longer exists

**Comment by damncabbage** [comment]
Confirmed; I earlier (incorrectly) reported this on Pulp: https://github.com/bodil/pulp/issues/56
(I forgot to get around to reporting it here as per my last comment on the issue. Oops.)

**Comment by agrafix** [comment]
Sorry for the delay :disappointed: - thanks for @natefaubion for reproducing! I use `gulp-purescript` like this:

```javascript
var psSources = [
    "pssrc/**/*.purs",
    "bower_components/purescript-*/src/**/*.purs"
];

var psForeins = [
    "pssrc/**/*.js",
    "bower_components/purescript-*/src/**/*.js"
];

gulp.task("ps-make", function () {
    return purescript.psc({
        src: psSources,
        ffi: psForeins,
        output: dist.js + "/ps/modules"
    });
});

gulp.task("ps-bundle", ["ps-make"], function () {
    return purescript.pscBundle({
        src: dist.js + "/ps/modules/**/*.js",
        output: dist.js + "/ps/bundle.ps.js",
        namespace: "TC",
        module: ["TC.Widgets.MeasurementDetail"]
    });
});

```

**Comment by natefaubion** [comment]
FWIW, I think this is likely just a matter of a bad case. `psc` is likely just accepting an extern instead of checking that the extern also exists in the input graph.

**Comment by paf31** [comment]
The thing that confuses me about this is that this is not consistent with how `psc` uses externs files. It doesn't load all externs files from the `output` directory. It just loads them as needed, based on what needs to be recompiled.

`psc-ide` does load all externs, I think, so I could understand this being an issue with `psc-ide`, but it doesn't sound like that's what's happening here.

**Comment by natefaubion** [comment]
I was bitten by this again this week. I pulled out a module that was used pretty extensively and forgot to clean my output. Everything kept compiling fine! It wasn't until Travis yelled at me about compile errors did I find all the places I missed.

I think it's just that when you delete a module, and you haven't touched all the other modules that depend on it, `psc` sees those as unchanged and doesn't bother checking them, even though they've clearly been invalidated.

**Comment by paf31** [comment]
Ah, ok, now I see what's going on, thanks. I wonder what `make` would do in this situation.

**Comment by natefaubion** [comment]
@paf31 Maybe something to do with https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Make.hs#L221? Looks like it's checking the timestamps of dependencies by hitting the output directory? Since it's already waiting on dependencies to be rebuilt, maybe the MVar should be returning something about rebuild status and we could check there instead of hitting the FS?
