### ISSUE TITLE
Coercible newtypes and field accessors

### ISSUE THREAD

**Issue by agrafix** [purescript/purescript#1922]
Currently all records can be accessed by the `.`, eg `foo.bar` reads the field foo of a record 

```purescript
type FooRec x = { bar :: Int | x }
```

Now if I define a newtype
```purescript
newtype FooRec' x = FooRec' { bar :: Int | x }
```

trying to read a value with `foo.bar` produces a type error, which of corse is expected. What you'd have to do is unwrap the value first, and then access the field. Or use lenses. But both become a little bit unhandy when you have nested data structures like

```purescript
newtype A = A { b :: B }
newtype B = B { c :: C }
newtype C = C { value :: Int }
```

If I have a value of `wrappedA :: A` and want the `value` field of the contained `C`, then would like to write `wrappedA.b.c.value`, but that's not possible because I have to unwrap after every field access.

Now Haskell has included a type class in `base 4.7`

```haskell
class Coercible a b

coerce :: Coercible a b => a -> b
```
(see https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Coerce.html) and the compiler automatically generates instances for things that have the same representation. We could limit that to newtypes for now (and maybe arrays/lists of newtypes) like so:

```purescript
newtype Foo = Foo { bar :: Int }

-- always holds:
instance coercibleSameType :: Coercible a a

-- generated automatically:
instance coercibleFooRec :: Coercible Foo { bar :: Int }

-- not sure if we want these too?
instance coercibleRecFoo :: Coercible { bar :: Int } Foo
instance coercibleFooArray :: Coercible (Array Foo) (Array { bar :: Int })
-- ...
```

Now we could introduce a new way of accessing fields so that `wrappedA.b.c.value` from above desugars to `(coerce (coerce (coerce wrappedA).b).c).value`. This would also work if there would be unwrapped records along the path due to `Coercible a a`. As `coerce` is a runtime No-op, the compile should probably optimize it away after type checking.

**Comment by hdgarrood** [comment]
There are cases where the current behaviour is desired, though. For instance, if you want the internals to he inaccessible, you would avoid exporting the constructor, and write the rest of your code assuming that only functions inside the defining module can access those fields.

**Comment by AppShipIt** [comment]
Out of ignorance are the `newtype` wrappers are needed since records are more flexible than Haskell's? What's the use case in context?

**Comment by agrafix** [comment]
@hdgarrood Yes, that's true! For those cases you could use a `data` declaration?

@AppShipIt There multiple use cases, but a big one is: You can not define type class instances for records (which I think is good)

**Comment by hdgarrood** [comment]
If you're forced to use a `data` declaration, you lose the advantage of having no runtime overhead for the extra constructor, which would be a shame.

**Comment by agrafix** [comment]
Okay, good point! Maybe then the alternative would be to make the `Coercible` instance opt-in or opt-out for each newtype?

**Comment by hdgarrood** [comment]
If it were opt-in, I can't think of any other reasons to object. :)

**Comment by AppShipIt** [comment]
Yeah record instances had occurred to me. It'd certainly make using records less inconvenient with `Eq`/`Ord`. I assumed you were asking for something optional in the vane of deriving 'Generic`.

**Comment by joneshf** [comment]
> But both become a little bit unhandy when you have nested data structures

What sorts of things are unhandy with lenses? Having to define them? Or actually using them?

If it's defining them, I thought there was a thing that made that easier, though I might be making that up.

If it's using them, I know most examples show unwrapping the newtype first, then you get to the record. But you can go straight for the record if you want.

If you have 

```purescript
newtype A = A { b :: B }
newtype B = B { c :: C }
newtype C = C { value :: Int }
```

You can define lenses

```purescript
b :: LensP A B
c :: LensP B C
value :: LensP C Int
```

Then you can do

```purescript
wrappedA^.b..c..value
```

which isn't too far off from your original request.

**Comment by agrafix** [comment]
@joneshf yes, one could theoretically solve this with lenses, but you'd have to write an aweful amount of boilerplate code defining all those lenses. A possible alternative would be to have something like "TemplatePurescript" to generate lenses automagically - but you'd still get a lot of runtime overhead from this. 

Apart from that - lenses also work as setters, and that currently is not included in my proposal. I'm going to give that a thought.

**Comment by joneshf** [comment]
Ah, yeah, definition a pain. I could've sworn there was a thing for that though.

If you don't want the setter part, you could just change the signatures to:

```purescript
b :: Getter A B
c :: Getter B C
value :: Getter C Int
```

and keep the same implementation.

**Comment by joneshf** [comment]
There is a thing for that: https://github.com/paf31/purescript-derive-lenses/ !

**Comment by AppShipIt** [comment]
So there's several issues where optics provide a more general solution (typically pointed out by @paf31 or @joneshf). Is there any precedent for the compiler to generate them a la deriving (except without a type class)? Moreover `Profuctor` lenses aren't necessarily compatible with Van Laarhoven's right? Is the library for the latter still supported?

**Comment by user471** [comment]
>What sorts of things are unhandy with lenses? Having to define them? Or actually using them?

Even lenses would benefit from `Coercible`. For example

```
type Foo1 = {foo::Int}
newtype Foo2 = Foo2 {foo :: int}
```
With `Coercible` it would be possible to use one lens for both types
```
foo :: forall a b r. Lens { foo :: a | r } { foo :: b | r } a b
foo = lens _.foo (_ { foo = _ })
```

**Comment by AppShipIt** [comment]
Would it provide any benefit to #514? I tried to google its relationship to `GeneralizedNewTypeDeriving` and just found [complexity](http://ezyang.tumblr.com/post/96448232652/safe-zero-cost-coercions-for-haskell-richard).

**Comment by paf31** [comment]
Strong :-1: from me.

**Comment by user471** [comment]
@paf31 Will this be solved in different way or you don't see any problems with records and newtypes?

**Comment by paf31** [comment]
I don't consider it to be a problem.

**Comment by paf31** [comment]
To be clear, I think the proposal needs quite a bit of development before it can even be considered. It relies crucially on an overlapping instance (`coercibleSameType`), and there are all sorts of other concerns related to type inference, error messages, how automatic instance generation should work, etc. Meanwhile, lenses provide a working solution today.

**Comment by user471** [comment]
@paf31 
>I don't consider it to be a problem.

I don't understand. Records have a nice syntax to read and update fields, but without instances they are useless because you cannot even compare them. If we should use lenses instead

```
newtype Foo = Foo {x :: Int}
newtype Foo2 = Foo2 {foo :: Foo}
newtype Foo3 = Foo3 {foo2 :: Foo2}
```
Is this the idiomatic way to work with records?
```
y = Foo3 {foo2 : (Foo2 {foo : (Foo {x : 1})})}

r = y ^. _Foo3 <<< foo2 <<< _Foo2 <<< foo <<< _Foo <<< x
```
It looks not so great in comparison with ```y.foo2.foo.x```

**Comment by agrafix** [comment]
@paf31 I agree 100% that this needs more thought and work. In addition to what @user471 said, the lens approach has a huge runtime overhead and the generated code is a lot less readable. If you remove the `coerce` before JavaScript generation, you'd recieve clean javascript code `y.foo2.foo.x`. The adress your other concerns: 

* overlapping instance could be solved by generating a concrete `Coercible Foo Foo` instance for all defined types
* type inference: yes, that is probably a problem, but with functional dependencies it should at least improve a lot? I think there's already an issue for that? #1580 
* error messages: I was thinking of this too, I am afraid that the compiler will need special knowledge of coerce in the context of field accessors to make good error messages possible.
* instance generation: there's not much to it, because there are no instance methods to be implemented. The `Coercible` type class should be like the `Partial` type class, eg. only informing the compiler that two types have equal runtime representation, and that `coerce` (= no op) can be used. 

This also solves the overhead in list unwrapping. If you have a list of `newtype Foo = Foo Int` and you wanted a list of `Int`s, right now you'd write `unFoo (Foo x) = x` and `map unFoo listOfFoo`. This will generate code that needs to go over each element of the list, doing nothing? On the other Hand, if you had a `Coercible` instance `Coercible Foo Int` and `Coercible a b => Coercible (Array a) (Array b)` then you could just write `coerce listOfFoo` and it will again result in a runtime no op.

**Comment by user471** [comment]
> the lens approach has a huge runtime overhead
```
main = do
  let init1 = Foo3 {foo2 : (Foo2 {foo : (Foo {x : 1})})}
  let init2 = {foo2 : {foo : {x : 1}}}
  let count = 300000
  time "1"
  let r1 = foldl (\r i -> r # _Foo3 <<< foo2 <<< _Foo2 <<< foo <<< _Foo <<< x +~ 1) init1 (1..count)
  timeEnd "1"
  time "2"
  let r2 = foldl (\r i -> r {foo2 = r.foo2 {foo = r.foo2.foo {x = r.foo2.foo.x + 1}}}) init2 (1..count)
  timeEnd "2"
```
```
1: 3742.96ms out.js:34744
2: 267.8ms
```
It's 10 times slower. Is it reasonable cost?

**Comment by hdgarrood** [comment]
If the motivation is performance, then I'm very much :-1:. We shouldn't be making any language changes on the basis of performance before we have a real optimizer inside the compiler. Ed Kmett has written that aggressive inlining is basically the most important thing about making lenses have good performance in Haskell, so to do anything else first, and especially anything that changes the language, would be a huge mistake, I think.

**Comment by garyb** [comment]
Not defining the lens inline would probably also help a fair bit in that performance comparison.

``` purescript
let lens = _Foo3 <<< foo2 <<< _Foo2 <<< foo <<< _Foo
    r1 = foldl (\r i -> r # lens <<< x +~ 1) init1 (1..count)
```

**Comment by user471** [comment]
>If the motivation is performance

```
y ^. _Foo3 <<< foo2 <<< _Foo2 <<< foo <<< _Foo <<< x
```
vs
```
y.foo2.foo.x
```

**Comment by user471** [comment]
>Not defining the lens inline would probably also help a fair bit in that performance comparison.

Not so much.
```
1: 3830.04ms 
2: 3086.86ms
```

**Comment by hdgarrood** [comment]
Previously I was on the fence but now I'm against too. The code in @user471's most recent example is a lot simpler on the syntax level, yes, but the cost is a significant complication of what `x.y` means. I agree with @paf31; the problem that this is meant to solve is not much of a problem for me either, and I'd also want to see a much more clearly thought through approach to type inference and type errors before pursuing this any further.

**Comment by garyb** [comment]
My main issue with `Coercible` is it will have to be deeply magical, much moreso than `Partial` even. We'd have to check for a `Coercible` instance for type mismatch, we couldn't treat it like a normal class as there is no expectation of the dictionary argument at each function definition, there will almost certainly be overlapping instance issues, etc.

I think this approach is certainly better than the previous discussion about having some kind of special case for a record in a newtype, as at least this applies universally without arbitrary rules being thrown in to deal with each edge case, but unfortunately I don't think it's quite the answer either.

I'm also not finding the problem this attempts to solve to be much of an issue in real world usage (and I write PS full time), so it's not really painful enough for me to be enthusastic about solutions as drastic as this one.

**Comment by user471** [comment]
>I'm also not finding the problem this attempts to solve to be much of an issue in real world usage

Could you show how do you work with `Foo3` type in real world usage?

**Comment by garyb** [comment]
I've never encountered a type like that in real world usage, that's what I meant. I would use lenses if I did, even with the performance hit.

**Comment by agrafix** [comment]
@garyb I have some types like that, but you are right, often I don't have to unwrap into something embedded deeply. Probably #764 will already improve things here. 

Moving away from the field accessors (which were my main motivation for `Coercible`), there are still a lot of other advantages that can be drawn from `Coercible` (see http://www.cis.upenn.edu/~eir/papers/2014/coercible/coercible.pdf). For example: performance and javascript-readability. This code:

```purescript
newtype Foo = Foo Int
unFoo (Foo i) = i

w = map unFoo [Foo 1, Foo 2, Foo 3]
```

currently generates 

```javascript
var Foo = function (x) {
    return x;
};
var unFoo = function (_0) {
    return _0;
};
var w = Prelude.map(Prelude.functorArray)(unFoo)([ 1, 2, 3 ]);
```

A good inliner will not help, you would also need to partially evaluate code and/or rewrite rules. It should translate into 

```javascript
var w = [ 1, 2, 3 ];
```

**Comment by AppShipIt** [comment]
@agrafix I must admit that looks as <q>deeply magical</q> as @garyb surmised. Regardless whether it'd be convenient it doesn't sound worth the implementation effort or potential quagmires.

**Comment by spion** [comment]
I think the actual problem here may be: exactly how are experienced PureScript users working with record based types?

When I read that @garyb never encountered such a type I was honestly a bit surprised. 

Take a typical JS canvas API for example:

```js
fillRect(x, y, width, height)
```js

If you actually model a rectangle as two corner Coordinate (not an ideal example, but bear with me)

```purescript
newtype Rectangle = Rectangle { bottomLeft :: Coordinate, topRight :: Coordinate }
newtype Coordinate = Coordinate { x :: Number, y :: Number }
```

and 

```js
foreign import fillRect :: Context -> Number -> Number -> Number -> Number -> Eff (draw :: Draw) Unit
```

then to invoke fillRect with the proper arguments you would need some of the lens gymnastics above.

So I find the statement that this situation doesn't arise in real world code strange. Another example, it seems like it would arise any time you deal with data coming from API that looks like this: https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline

Is it possible that I'm (we are) missing some key insights here? :)

**Comment by garyb** [comment]
I was thinking more of deeply nested newtyped records, I certainly use newtype-wrapped records a fair bit, but I don't find it a great hardship to unwrap/rewrap that single layer as needed.

In the example above I'd prefer to never have exposed a function with arguments like that in the first place :wink: so wouldn't hesitate to make my own `fillRect' :: Context -> Coordinate -> Rectangle -> ...`, or if it's not as generally useful as that then I'd define something similar in a `where`.

I'm not saying it _never_ happens, just that the cases where I do have to do something that involves a bit of effort occur rarely enough that I don't find it troubling.

**Comment by paf31** [comment]
Just because something involves a small amount of boilerplate code doesn't mean we should reach for heavyweight type system features to address it. The benefit of the boilerplate is that it is explicit and only involves terms with simple, inferable types.

There is a difference between GHC's `Coercible`, for which you still have to manually insert the `coerce` term, and overloading something as primitive as property accessors.

I vote to close this. I personally have no plans to implement it.

**Comment by jdegoes** [comment]
> Just because something involves a small amount of boilerplate code doesn't mean we should reach for heavyweight type system features to address it.

Exactly. And this is an issue that has been beaten to death under many different tickets and many different proposals. Personally, I think any issue which suggests allowing instances for records, or which provides an ability to access newtyped records without unwrapping them (the flip side), should be closed immediately and we can link to one of the many discussions on the topics.

**Comment by paf31** [comment]
> should be closed immediately

Agreed, _if_ there is an established answer already. It's just a case of curating a list of standard responses. I think the best way is to close and freeze the issue, and move it to some milestone which we can use exclusively for tracking such things.

**Comment by user471** [comment]
>bit of effort occur rarely enough that I don't find it troubling.

If such cases occurred all the time would it be troubling? I think the reason why there are two different opinion is because there are two kinds of people, who works with complex records logic and who doesn't (like game state vs simple crud). Big part of my code is records manipulation. So if you multiply `small amount of boilerplate code` by thousand it will be not so small.

**Comment by agrafix** [comment]
@paf31 What about implementing `Coercible` without the sugar for field accessors? Are you against that too?

**Comment by paf31** [comment]
@agrafix Possibly, but it's not a priority for me and the proposal still needs some development, relative to the current implementation of the constraint solver.

**Comment by agrafix** [comment]
Yes, it probably needs at least functional dependencies ( #1580 ).

**Comment by paf31** [comment]
So, let's make a decision on this, yes? (contributors, assemble!)

:-1: from me, sorry, for the reasons given above.

**Comment by hdgarrood** [comment]
:-1: from me on the record access sugar. I'm not necessarily against something like GHC's Coercible, but I feel that it should wait until at least we have inlining and rewrites.

**Comment by garyb** [comment]
:-1: likewise, agree that `Coercible` may be useful in some form, but not automatically inserted to allow record access.

**Comment by user471** [comment]
So, no label syntax for newtype? 
Could some one clarify how records and newtypes should be used?
Here what I did when I started using ps. 
Obviously I started with record with its fancy syntax because it's advertised as one of kill features compare to Haskell. 
Then I realize I need Eq instances and I rewrite everything with newtypes with wrapping unwrapping nightmare. 
Then I learned about lens and rewrite everything third time. Overall not a pleasant experience.

**Comment by hdgarrood** [comment]
@user471: PureScript is a young language, so this is to be expected (to some extent). The compiler and all core libraries have 0.x.y versions at the moment, for instance. If the fact that we don't yet have well established patterns is a deal breaker for you, perhaps GHCJS or Elm would be a better fit. We've already clarified how records and newtypes should be used in this issue (and in a fair few others), and I don't think we're getting anywhere with these discussions regarding newtypes, records, and instances, so I'm going to ask that you drop this, please.

**Comment by garyb** [comment]
Using newtyped records is fine. Just unwrap them in the argument of your function and rewrap in the return. Provide an `unFoo` function that unwraps for the cases where you want to use it inline. Write small functions to modify a record that perform the necessary unwrap/rewrap rather than modifying a monolithic record directly. Use lenses. Use less records and more normal data constructors. There are endless options.

**Comment by user471** [comment]
> so I'm going to ask that you drop this
Could you learn some manners and stop teaching people what they need to do? If you don't want a discussion just don't answer. It's that simple.

>There are endless options.
I think I already know all the options. But I don't know what would be the best option in what cases.

**Comment by hdgarrood** [comment]
The thing is, this issue tracker isn't just for the benefit of users. We (contributors) also rely on it to help us decide what to work on. It becomes significantly harder for us to use the issue tracker effectively when people are always bringing the same points up. In particular, it's becoming clear that it's just no longer workable to leave issues alone if we don't feel like discussing them. It's also exhausting to always be receiving emails (and, to be frank, it is almost exclusively you) demanding that people implement things which are basically unworkable.

I think it might be time to consider locking this issue.

**Comment by AppShipIt** [comment]
> I think I already know all the options. But I don't know what would be the best option in what cases.

@user471 I feel this way about a couple closed issues. But for the benefit of maintainers (as @hdgarrood alluded) compiler issues aren't the best discussion forum. In the case of `newtype` related problems there simply isn't an agreed proposal that anyone wants to implement themselves in the near future. Although the volume is high I do appreciate your readiness to challenge basic assumptions on occasion.

**Comment by user471** [comment]
>(and, to be frank, it is almost exclusively you) demanding that people implement things which are basically unworkable.

What exactly is unworkable from the last issues?
https://github.com/purescript/purescript/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Auser471+
Instances for records two months ago? Sorry, I write a unworkable issue every two months It should be really exhausting to read.

> compiler issues aren't the best discussion forum

I understand, but all other places is dead and irc isn't a forum.

**Comment by paf31** [comment]
Closing. For future reference, IRC or Google Groups is a good place to assess/develop idea requests before creating an issue here.
