### ISSUE TITLE
Differences from Haskell, code sharing

### ISSUE THREAD

**Issue by pkamenarsky** [purescript/purescript#1924]
Has anyone tried sharing code between Haskell and Purescript? The main use case for me right now is data/form validation - I'd like to use the same code both on the server and the client. Sticking to Haskell2010 (or even 98) should be fine, validation logic is mostly simple anyway.

Differences like `Array` and `Boolean` are trivial - just make type aliases. `true = True` etc on the Haskell side should take care of lower case bools. Explicit `forall` in Haskell isn't gonna hurt.

Destructuring records is one thing that may be a showstopper. If validation functions look like `String -> Boolean` that should be fine too.

What else? I'm gonna try, but I'd be interested in hearing about other peoples' experience.

EDIT: if code sharing is at all possible, I'd also be interested in hearing if this is something the Purescript community values, or if future changes might break Haskell interop. The freedom of not being tied to another language really makes things like the awesome record system possible, on the other hand sharing code is really nice too.

**Comment by jdegoes** [comment]
I'd not recommend it. Instead, create an applicative DSL for validation that can generate either code or data, which can be leveraged on client or server side.

**Comment by paf31** [comment]
Can we please move this to the mailing list?

**Comment by hdgarrood** [comment]
Yeah, agreed. Maybe we should add a note to contributing.md too, saying that this sort of discussion belongs on the mailing list.
