### ISSUE TITLE
Syntax to improve readability for exceptional cases

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#1928]
## Syntax extension proposal

Taking a cue from Idris which in turn was inspired by Perl's [or die syntax](https://youtu.be/rXXn4UunOkE?t=1851), I suggest adding syntax for handling exceptional cases in do blocks.

Turning this situation:
```purescript
main = do
  c <- getCanvasById "canvas"
  case c of
    Nothing -> throwError "Canvas Element could not be found"
    Just c' -> do
       ctx <- getContext2D c'
       ...
```
... into this (which still passes the totality checker):
```purescript
main = do
  Just c <- getCanvasById "canvas" | Nothing => throwError "Canvas Element could not be found"
  ctx <- getContext2D c
  ...
```

The general idea is to reduce the indentation level incurred by exceptional cases that just return with a single statement.

In case the line gets too long I suggest we allow breaking the exceptional case onto it's own line with indentation:

```purescript
main = do
  Just c <- getCanvasById "canvas" 
    | Nothing => throwError "Canvas Element could not be found"
  ctx <- getContext2D c
  ...
```

Another consideration to make is if we wanted to allow multiple cases to be specified:

```purescript
main = do
  Just (Just c) <- getCanvasById "canvas"
    | (Just Nothing) => throwError "Element was not a Canvas element"
    | Nothing        => throwError "Canvas Element could not be found"
  ctx <- getContext2D c
  ...
```

Right now I think it would be better to only allow one alternative to reduce the urge to cram more extensive errorhandling into oneliners. The main purpose is to reduce partiality without taking a hit on readability.

**Comment by hdgarrood** [comment]
I'm not sure we need extra syntax for this. Why not use function in a where clause if you want pattern matching?

**Comment by garyb** [comment]
I can't say I've ever had a particular problem with this kind of thing, if a `do` ends up indenting a lot due to error handling I'd probably switch to using `MaybeT` or `ExceptT` to avoid handling each individual error.

In the case above, I'd probably do something like this if I really wanted to avoid the indent:

``` purescript
main = do
  c <- getCanvas
  ctx <- getContext2D c
  where
  getCanvas = 
    maybe (throwError "Canvas Element could not be found") pure <=< getCanvasById "canvas"
```

**Comment by kRITZCREEK** [comment]
But `maybe (throwError "Canvas Element could not be found") pure` has the type `MonadError m => m Unit`, right? I sat down and tried to work out the types:

```purescript
   maybe :: b -> (a -> b) -> Maybe a -> b
   throwError "Canvas Element could not be found" :: forall m. (Monad m, MonadError m) => String -> m Unit
   pure :: forall a m. Monad m => a -> m a -- I know this is overconstrained

   maybe (throwError "Canvas Element could not be found") pure :: MonadError m => Maybe Unit -> m Unit

   (<=<) :: Monad m => (b -> m c) -> (a -> m b) -> a -> m c

   (<=<) (maybe (throwError "Canvas Element could not be found") pure)
     :: forall a c m. (Monad m, MonadError m) => (a -> m (Maybe Unit)) -> a -> m Unit

   getCanvasById :: String -> Maybe CanvasElement

   (<=<) (maybe (throwError "Canvas Element could not be found") pure) getCanvasById

   -- => Can't unify CanvasElement with Unit
```

As for the MaybeT/EitherT suggestion: It always seems verbose to mix these with non-Maybe computations *(lift <<< lift)*. Trying to mix the two the two of them without converting every `Maybe a` into an `Either Unit a` also seems very ugly.

**Comment by hdgarrood** [comment]
Not quite - `throwError` doesn't return `Unit`, the type is `forall e m a. MonadError e m => e -> m a`: https://pursuit.purescript.org/packages/purescript-transformers/0.8.4/docs/Control.Monad.Error.Class#v:throwError

I think @garyb's example wants `=<<` instead of `<=<`, and also a call to `error` (In `Eff`, you can only throw `Error`, not `String`) but other than that, I think it's fine.

**Comment by hdgarrood** [comment]
I did basically the same thing in multipac, FWIW: https://github.com/hdgarrood/multipac/blob/b78c45c0003e608157fe8c3b3888f51fc9de5f29/src/Rendering.purs#L67-L79

**Comment by kRITZCREEK** [comment]
Okay this was not meant to be about `MonadError`. Does this clean it up a bit?

```purescript
main = do
  Just c <- getCanvasById "canvas" | Nothing => pure unit
  ctx <- getContext2D c
  log "done"
```

In case of a `Nothing` this shouldn't log to the console. I don't think you can get around the branching with a combinator.

**Comment by hdgarrood** [comment]
I'd rather write that as:

```purescript
whenJust :: :: forall a b f. (Applicative f) => Maybe a -> (a -> f b) -> f Unit
whenJust = Data.Foldable.for_

main = do
  whenJust (getCanvasById "canvas") \c -> do
    ctx <- getContext2D c
    log "done"
```

Yes, there's still indentation, but IMO, there should be. There's branching going on here, so I think it's a good thing that the syntax reflects that.

**Comment by jdegoes** [comment]
The language has sufficient power to abstract over this pattern without any new syntax. In particular, you can achieve what you want (generically) with `ContT` and prisms. Exercise left for reader. :wink:

**Comment by kRITZCREEK** [comment]
@hdgarrood But branching that is meant to ensure totality and catch errors early isn't real "branching" in the sense that your logic branches out but rather that you need to bail in case of an unexpected input.

multipac is a great piece of "realworld" PureScript to demonstrate this:

If we take https://github.com/hdgarrood/multipac/blob/b78c45c0003e608157fe8c3b3888f51fc9de5f29/src/BaseServer.purs#L175-L207 and apply the sugar:

https://gist.github.com/kRITZCREEK/5f157d23e40fc779089e

It doesn't look too invasive or terse and captures a very common pattern.

@jdegoes `ContT` would give the same semantics as exceptions I guess? That doesn't work too well with resource handling. One field where this syntax could be used is in serverside code dealing with filesystems and networks.

Prisms reduce the verbosity of pattern matching but I'm not sure how I would use them to walk multiple branches.

**Comment by hdgarrood** [comment]
Somewhat offtopic, but a request: can we please avoid referring to any part of PureScript as "ensuring totality" or "having a totality checker"? Neither of these things are true; this code, for example, compiles without any problems:

```purescript
oops :: forall a b. a -> b
oops x = oops x
```

We just have a nice way of indicating and propagating the (incomplete) partiality information that we do have.

**Comment by kRITZCREEK** [comment]
Sure. I was referring to totality regarding the pattern matches, but I guess non-partiality of patterns describes it more accurate.

**Comment by garyb** [comment]
Exhaustivity is the word we tend to use :)

**Comment by jdegoes** [comment]
> That doesn't work too well with resource handling.

It works exactly the same as your above proposal, which is: it gives you the ability to have partial pattern matches and escape early from a `do` block.

> Prisms reduce the verbosity of pattern matching but I'm not sure how I would use them to walk multiple branches.

You just need a `case`-like combinator which allows you to handle a bunch of terms.

Note that due to the way `do` notation de-sugars, what you are basically asking for is a way to define anonymous functions piecewise, in the same fashion that named functions may be defined piecewise.

e.g.:

```
\Just a -> ...
???
\Nothing -> ...
```

Indeed, I've sometimes wanted that myself, but I don't see any clean way of doing it.

**Comment by kRITZCREEK** [comment]
@jdegoes in Haskell that would be `{-# LANGUAGE LambdaCase #-}`. I asked on the #idris irc channel  how much they use this syntax/what their experiences are with it and got positive responses all around.

I then asked how they felt about the ContT/Prism solution and got this back:

```
3:18 PM <edwinb> the nice thing abotu the special syntax is that you can encode it without the need for Prisms or ContT ;)
3:18 PM <edwinb> much as I like types, they're meant to help you write programs, not give you more semantics to think about for the sake of readability
```

I think in PureScript land this gets "oneupped" because case statements are still readable in JavaScript land while transformers/lenses become assembly.

**Comment by garyb** [comment]
We're probably going to introduce something like `LambdaCase` but using underscore syntax to match our other placeholdery things: `case _ of ...`

**Comment by AppShipIt** [comment]
> case statements are still readable in JavaScript land while transformers/lenses become assembly.

This is what piques my curiosity. I only recently learned `Cont` and just started into transformers. But my understanding is `Eff` provides some of MTL’s benefits? It seems nicer to benefit from a higher level abstraction? Is the use case just too narrow?

> https://gist.github.com/kRITZCREEK/5f157d23e40fc779089e

The gist doesn't quite do your proposal the same justice as your example because there's no `do` nested inside `case`. I see it a lot more like `Cont` than branching. I'm puzzled why `=>` was picked? Other than that I like the syntactic analogy to guards.

**Comment by paf31** [comment]
:-1: I'd rather implement `LambdaCase`.

**Comment by AppShipIt** [comment]
How would that look in @kRITZCREEK's Canvas example? I didn't grok that when @garyb suggested it (although the proposed syntax sounds perfect).

**Comment by kRITZCREEK** [comment]
I don't think LambdaCase adresses this issue. If you want to use LambdaCase you have to give up on do notation and go back to explicit binds. You also get the 2 extra levels of indentation.

```purescript
main =
  getCanvasById "canvas" >>= \case 
    Nothing -> pure unit
    Just c -> do
      ctx <- getContext2D c
      log "done"
```

**Comment by garyb** [comment]
I wasn't suggesting `LambdaCase` solves this, just someone else mentioned it so I thought I'd explain the plans for that. Although if you were using `throwError` like your original example it would help, as you could do away with the block in the `Just`, as per @AppShipIt's example.

:-1: from me as I think this is can already be avoided using a few different approaches as it is (`where`, transformers, prisms, etc).

**Comment by AppShipIt** [comment]
@garyb I couldn't get it to work with `throwError` (without `ContT`) but did with the `throwException`.

@kRITZCREEK [Working gist](http://sharkdp.github.io/try-flare/?gist=096d33da7d71c89b3a55) (adapted from your Space Invader one).

**Comment by paf31** [comment]
Sorry, I missed the point on LambdaCase. Still :-1: from me though, I think it's better to handle this with functions.

**Comment by kRITZCREEK** [comment]
Allright, with general disagreement from the contributor side I'll close this. I think it could be interesting to see if "syntax transformation only" features could be pluggable as a step before the lexer.
