### ISSUE TITLE
Unicode and PSCI

### ISSUE THREAD

**Issue by born2defy** [purescript/purescript#1929]
I loaded a project into `psci` which was using the unicode forall symbol (∀) rather than "forall," and it would not load due to a parsing error.  `psc` will parse it fine and build the project succesfully.  Is this a known issue?

**Comment by paf31** [comment]
This looks like a new bug. Thanks for the report!

**Comment by born2defy** [comment]
My pleasure.  Loving the unicode support so far.

**Comment by soupi** [comment]
@born2defy can you include an example and your version of psc? I wasn't able to reproduce it on the latest master (commit 5db88e47ff8e423cb3c4a11cbbf2701297cee5b2).

I succeeded importing the following module to psci:

```purs
module Main

id :: ∀ a. a -> a
id x = x
```

**Comment by born2defy** [comment]
Sure.  If I load this into psci:

```
main :: ∀ e. Eff (console :: CONSOLE | e) Unit
main = do
log "Hello sailor!"
```

I get the following error:

```
Error found:
at src/Main.purs line 7, column 14 - line 7, column 14

  Unable to parse module:
  unexpected .
  expecting no indentation or end of input
```

Where line 7 is the type signature of `main`.  This is with:

```
$ psci --version
0.8.2.0
```

**Comment by DavidLindbom** [comment]
I'm able to get this error message is if I'm using the [Turned A](https://en.wikipedia.org/wiki/Turned_A) character instead of forall. They are very similar and with some fonts may look exactly the same. Tried to paste them but seems like Github converts them both to forall.

**Comment by garyb** [comment]
I think I may have fixed this with my updates to use `readUTF8File` everywhere, as `psci` was not using it previously.

**Comment by deamme** [comment]
I think this is already fixed.

**Comment by paf31** [comment]
Thanks!
