### ISSUE TITLE
Unknown module Math

### ISSUE THREAD

**Issue by raould** [purescript/purescript#1935]
I just installed PureScript 0.7.6.1 for Mac OS X from the tar.gz today, and was trying to learn from the eBook. 

```
module Main where
import Prelude
import Math
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)
main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  log "Hello sailor!"
```

```
Error found:
in module Main
at /Volumes/OS/Users/x/Dev/purescript/purescript/Test/src/Main.purs line 3, column 1 - line 4, column 1

  Unknown module Math
```

**Comment by raould** [comment]
(P.S. "import Math (sqrt)" doesn't work either, just to be clear.)

**Comment by hdgarrood** [comment]
I think this might be because the book hasn't yet been updated regarding the fact that Pulp no longer bundles Bower. (PureScript is a young language, and lots of things are changing rapidly, so not all the documentation is up to date).

If you run `npm install -g bower`, and go back to the beginning of 2.9, you should be ok, I think.

**Comment by raould** [comment]
Thanks for your note.

The very first time I did "pulp init" I got yelled at for not having bower :-) so i did already then install it, and then ran "pulp init --force" or whatever again, so I do not expect that is really the root cause here. When I type "bower" at the command prompt, it does exist and run.

So I guess something else, dunno what.

**Comment by hdgarrood** [comment]
Ah, ok. Try substituting `pulp dep` for `bower`? So eg `bower install purescript-math --save-dev`.

**Comment by raould** [comment]
The error is that I did not run the command to install Math because I had been trying to skip all the stuff about compiling for the browser which I really do not care about right now. 

```
$ pulp dep install purescript-math --save
```
1) gives me a warning saying I should use bower directly. Ok.
2) so I used bower as well just to be sure ;-)

works!

so I guess I'd like to suggest
1) that 2.9 and 2.10 become 3.+ instead, to have a cleaner break and avoid impatient jerks like me from missing the obvious pre-requisities.
2) that the error message say something more like "the module is missing, check if it is even installed with <bower whatever> please silly human."

mea culpa.

**Comment by doppioslash** [comment]
Stumbled on the same problem. Definitely a better error message would help here, as @raould said.
