### ISSUE TITLE
Errors when globs include directories

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1937]
Using a glob of eg `src/**/*` was recommended in #1375, however, this is what I get when trying to compile Pulp:

```
$ psc 'src/**/*' 'bower_components/purescript-*/src/**/*'
psc: /home/harry/code/pulp/src/Pulp/: openFile: inappropriate type (is a directory)
```

The obvious fix is to ignore directories which match the glob. I wonder if we might also consider allowing people to specify directories, which then get included recursively for both `.purs` and `.js` files; this might be a bit simpler.

**Comment by paf31** [comment]
I've never seen this before. Is there some additional special thing about Pulp which I'm not seeing?

**Comment by hdgarrood** [comment]
The reason you haven't seen this before is that pulp currently uses separate globs for PureScript source files and FFI files. I encountered this when I was trying to modify Pulp to just use globs like `src/**/*`, in order to avoid generated the "No files found matching pattern: src/**/*.js" message.

**Comment by hdgarrood** [comment]
There's nothing special about the layout of source files in Pulp, though, I think this happens whenever you have a project that contains a directory in either `src` or `bower_components/purescript-*/src` (which is probably most of them).

**Comment by paf31** [comment]
:+1:

**Comment by paf31** [comment]
Since we do the lookup of the `.js` files based on `.purs` file locations, this can be resolved by using `*.purs` in the glob instead of `*`.
