### ISSUE TITLE
Compiler allows multiple data declarations

### ISSUE THREAD

**Issue by stevejb71** [purescript/purescript#1945]
The compiler allows duplicate data declarations within a module. Not caused me any particular problems, but it might be confusing.

```
module Main where

data X = X Int
data X = X String
```

**Comment by garyb** [comment]
Yeah, that's not right at all. Thanks for the report. :)

**Comment by garyb** [comment]
I've moved this to 0.9.1 because it's pretty bad, and shouldn't be too hard to fix.
