### ISSUE TITLE
Generated docs have incorrect source link

### ISSUE THREAD

**Issue by ejconlon** [purescript/purescript#1946]
Hi folks,

Please let me know if this is the wrong component or if this is a duplicate:

I noticed while navigating some pursuit docs (https://pursuit.purescript.org/packages/purescript-prim/0.8.0/docs/Prim) that the "Source" links point to incorrect offsets on Github.

For instance, the "Source" link for "Function" points incorrectly to
https://github.com/hdgarrood/purescript-prim/blob/v0.8.0/src/Prim.purs#L22-L28
which includes the type alias (correctly) but also so unrelated trailing lines.  I would expect it to point to
https://github.com/hdgarrood/purescript-prim/blob/v0.8.0/src/Prim.purs#L8-L22

What component in the purescript ecosystem calculates this?  psc, pulp, pursuit, something else?

Thanks,
Eric

**Comment by paf31** [comment]
The compiler library generates the `SourceSpan` data for Pursuit and also for the error messages. This is tracked in #1702.
