### ISSUE TITLE
recursive let on zero parameter function?

### ISSUE THREAD

**Issue by clinuxrulz** [purescript/purescript#1947]
The following compiles fine.

```
module Main.Model.Test where

import Prelude (class Monad, Unit, unit)

recursiveLetTest :: forall m. (Monad m) => m Unit
recursiveLetTest = do
  let doIt _ =
        do
          doIt unit
  doIt unit
```

And the following I would of expected to compile fine too.

```
module Main.Model.Test where

import Prelude (class Monad, Unit, unit)

recursiveLetTest :: forall m. (Monad m) => m Unit
recursiveLetTest = do
  let doIt =
        do
          doIt
  doIt
```

But I get the following.

```The value of doIt is undefined here, so this reference is not allowed.```

It is not really a big problem that needs to be fixed, the unused parameter work-around is fine. Just thought I'd bring it to your attention.

**Comment by paf31** [comment]
This would compile to the following JS if the check were missing:

```javascript
recursiveLetTest = (function() {
  var doIt = doIt;
  return doIt;
})();
```

which returns `undefined`, and this is why it's disallowed.

**Comment by paf31** [comment]
(closing as by-design)
