### ISSUE TITLE
Include exact versions of used libraries in binary bundles?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1952]
This could turn out to be very useful for debugging.

**Comment by hdgarrood** [comment]
This would be super easy if we used `stack` for creating binary bundles, it's just:

```
$ stack list-dependencies
```

And it's probably a good idea to use LTS package sets for the binary builds too, since they're much more likely to be used together.

**Comment by paf31** [comment]
`stack list-dependencies` didn't work for me.

**Comment by hdgarrood** [comment]
Yeah, I was thinking a text file. What happened when you ran `stack list-dependencies`?

**Comment by paf31** [comment]
It just said it wasn't a valid command.

**Comment by hdgarrood** [comment]
That's strange. According to the changelog it's been there as of 0.1.3.0: https://github.com/commercialhaskell/stack/blob/master/ChangeLog.md#0130
