### ISSUE TITLE
psc-publish fails for eskimor/purescript-localstorage

### ISSUE THREAD

**Issue by eskimor** [purescript/purescript#1956]
Problematic package to be found here:

 https://github.com/eskimor/purescript-localstorage

It told me to report a bug:
[robert@xps13:~/projects/purescript-localstorage]$ psc-publish 
psc-publish: An internal error ocurred during compilation: "Docs.Convert.ReExports: while collecting re-exports for module: Browser.LocalStorage, lookupValueDeclaration: unexpected result:\nother: []\nident: Ident \"sessionStorage\"\ndecls: [Declaration {declTitle = \"STORAGE\", declComments = Nothing, declSourceSpan = Just (SourceSpan {spanName = \"src/Browser/LocalStorage.purs\", spanStart = SourcePos {sourcePosLine = 21, sourcePosColumn = 1}, spanEnd = SourcePos {sourcePosLine = 23, sourcePosColumn = 1}}), declChildren = [], declFixity = Nothing, declInfo = TypeSynonymDeclaration [] (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Browser\"},ProperName {runProperName = \"LocalStorage\"},ProperName {runProperName = \"Raw\"}])) (ProperName {runProperName = \"STORAGE\"})))},Declaration {declTitle = \"Storage\", declComments = Nothing, declSourceSpan = Just (SourceSpan {spanName = \"src/Browser/LocalStorage.purs\", spanStart = SourcePos {sourcePosLine = 23, sourcePosColumn = 1}, spanEnd = SourcePos {sourcePosLine = 32, sourcePosColumn = 1}}), declChildren = [], declFixity = Nothing, declInfo = TypeSynonymDeclaration [] (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Object\"}))) (RCons \"length\" (ForAll \"eff\" (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Browser\"},ProperName {runProperName = \"LocalStorage\"},ProperName {runProperName = \"Raw\"}])) (ProperName {runProperName = \"EffLocalStorage\"}))) (TypeVar \"eff\")) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Int\"})))) Nothing) (RCons \"getItem\" (ForAll \"a\" (ForAll \"key\" (ForAll \"eff\" (ConstrainedType [(Qualified (Just (ModuleName [ProperName {runProperName = \"Data\"},ProperName {runProperName = \"Generic\"}])) (ProperName {runProperName = \"Generic\"}),[TypeApp (TypeVar \"key\") (TypeVar \"a\")]),(Qualified (Just (ModuleName [ProperName {runProperName = \"Data\"},ProperName {runProperName = \"Generic\"}])) (ProperName {runProperName = \"Generic\"}),[TypeVar \"a\"])] (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Function\"}))) (TypeApp (TypeVar \"key\") (TypeVar \"a\"))) (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Browser\"},ProperName {runProperName = \"LocalStorage\"},ProperName {runProperName = \"Raw\"}])) (ProperName {runProperName = \"EffLocalStorage\"}))) (TypeVar \"eff\")) (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Data\"},ProperName {runProperName = \"Maybe\"}])) (ProperName {runProperName = \"Maybe\"}))) (TypeVar \"a\"))))) Nothing) Nothing) Nothing) (RCons \"setItem\" (ForAll \"a\" (ForAll \"key\" (ForAll \"eff\" (ConstrainedType [(Qualified (Just (ModuleName [ProperName {runProperName = \"Data\"},ProperName {runProperName = \"Generic\"}])) (ProperName {runProperName = \"Generic\"}),[TypeApp (TypeVar \"key\") (TypeVar \"a\")]),(Qualified (Just (ModuleName [ProperName {runProperName = \"Data\"},ProperName {runProperName = \"Generic\"}])) (ProperName {runProperName = \"Generic\"}),[TypeVar \"a\"])] (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Function\"}))) (TypeApp (TypeVar \"key\") (TypeVar \"a\"))) (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Function\"}))) (TypeVar \"a\")) (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Browser\"},ProperName {runProperName = \"LocalStorage\"},ProperName {runProperName = \"Raw\"}])) (ProperName {runProperName = \"EffLocalStorage\"}))) (TypeVar \"eff\")) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prelude\"}])) (ProperName {runProperName = \"Unit\"}))))))) Nothing) Nothing) Nothing) (RCons \"removeItem\" (ForAll \"a\" (ForAll \"key\" (ForAll \"eff\" (ConstrainedType [(Qualified (Just (ModuleName [ProperName {runProperName = \"Data\"},ProperName {runProperName = \"Generic\"}])) (ProperName {runProperName = \"Generic\"}),[TypeApp (TypeVar \"key\") (TypeVar \"a\")])] (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Function\"}))) (TypeApp (TypeVar \"key\") (TypeVar \"a\"))) (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Browser\"},ProperName {runProperName = \"LocalStorage\"},ProperName {runProperName = \"Raw\"}])) (ProperName {runProperName = \"EffLocalStorage\"}))) (TypeVar \"eff\")) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prelude\"}])) (ProperName {runProperName = \"Unit\"})))))) Nothing) Nothing) Nothing) (RCons \"clear\" (ForAll \"eff\" (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Browser\"},ProperName {runProperName = \"LocalStorage\"},ProperName {runProperName = \"Raw\"}])) (ProperName {runProperName = \"EffLocalStorage\"}))) (TypeVar \"eff\")) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prelude\"}])) (ProperName {runProperName = \"Unit\"})))) Nothing) REmpty))))))}]"
Please report this at https://github.com/purescript/purescript/issues

**Comment by hdgarrood** [comment]
You might just need to update your compiler. What version is it?

**Comment by eskimor** [comment]
[robert@xps13:~/projects/gonimo-front]$ psc --version
0.8.0.0

- Ok, I will try. Thanks!

**Comment by eskimor** [comment]
Jep - it works now: https://pursuit.purescript.org/packages/purescript-localstorage/0.1.1

Thanks alot!
