### ISSUE TITLE
Type checker issue with records and constraints

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1957]
```purescript
type Rec = {
 myShow :: forall a. (Show a) => a -> String
}

mkRec :: Int -> Rec
mkRec _ = {
  myShow: show
}

rec :: Rec
rec = mkRec 1
```

gives

```text
Error found:
in module Main
at  line 22, column 7 - line 24, column 1

  Could not match constrained type

    (Show _0) => _0 -> String

  with type

    (Show a0) => a0 -> String


while trying to match type (Show _0) => _0 -> String
  with type (Show a0) => a0 -> String
while checking that expression mkRec 1
  has type { myShow :: forall a. (Show a) => a -> String
           }
in value declaration rec
```

[Taken from here](https://github.com/eskimor/purescript-localstorage/blob/788323c7c306a11b8f1d96f72336f996a6750820/src/Browser/LocalStorage.purs).

**Comment by AppShipIt** [comment]
Seems to be limited to constraints:
```purs
type Rec = {
 myId :: forall a. => a -> a
}
```

**Comment by pkamenarsky** [comment]
Is there a workaround for this in the meanwhile?

**Comment by LiamGoodacre** [comment]
Did some experimenting, doesn't seem to be limited to records.  Appears to be issues with mixing rank-n-types and constraints.

~~~purescript
-- for each of these
type Foo = { key :: forall t. Show t => t -> t }
type Foo = { key :: Partial => Unit }
type Foo = forall t. { key :: Show t => t -> t }
type Foo = forall t. Unit -> Show t => t -> t
type Foo = Array (forall t. Show t => t -> t)
type Foo = Unit -> Partial => Unit
type Foo = Array (Partial => Unit)
---
foo :: Foo -> Foo
foo = id -- type mismatch

foo' :: Foo -> Foo
foo' x = x -- type mismatch
~~~

~~~purescript
-- for each of these
type Foo = forall t. Show t => { key :: t -> t }
type Foo = forall t. Show t => t -> t
type Foo = forall t. (Show t => t -> t)
type Foo = Partial => Unit
---
foo :: Foo -> Foo
foo = id -- type mismatch

foo' :: Foo -> Foo
foo' x = x -- compiles
~~~

Hope this helps with debugging/testing!

**Comment by eskimor** [comment]
Glad this got reported already - also purescript-localstorage suffers from this, a workaround there was to drop the time annotation for certain [functions](https://github.com/eskimor/purescript-localstorage/blob/master/src/Browser/LocalStorage.purs). 

For servant-purescript I did an unsafeCoerce for now. *brrrrr*

**Comment by paf31** [comment]
I'm going to close this. The reason why I don't want to support this is a little subtle, but there are at least two workarounds:

- Newtype the record
- Newtype the field inside the record

The problem is that we have to check subsumption of the record type against itself, and I don't see a way around this. This means that we need to check that

```
    (Show _0) => _0 -> String
```

subsumes

```
    (Show a0) => a0 -> String
```

which it does, but at that point, we don't have a place to pin the dictionaries, since we're already inside a record field, and we don't have an expression available which corresponds to something in the elaborated code.
