### ISSUE TITLE
Compiler yields “additional cases required” warning even though all cases covered

### ISSUE THREAD

**Issue by 0dB** [purescript/purescript#1959]
Following code yields “additional cases required” warning where it shouldn’t:

```
module Abs where

import Prelude

abs :: Int -> Int
abs x | x < 0     = (-x)
      | otherwise = x

```

psc --version is 0.8.1.0.

**Comment by hdgarrood** [comment]
I can't reproduce this with 0.8.2.0. Perhaps you could try updating?

**Comment by garyb** [comment]
Indeed, #1909

**Comment by 0dB** [comment]
Cannot reproduce anymore with 0.8.2.
