### ISSUE TITLE
support language-javascript-0.6

### ISSUE THREAD

**Issue by phadej** [purescript/purescript#1966]
Related: https://github.com/fpco/stackage/issues/1292

From `language-javascript` readme:

>There are currently two versions:
>
>* 0.5 series : Is a continuation of the 0.5.X.Y series, from the [master]
>(https://github.com/erikd/language-javascript/tree/master) branch of this
>github repository.
>
>* 0.6 series : This has a vastly different and improved AST which makes if far
>more difficult to build an non-sensical Javascript AST. This code is in the
>[new-ast](https://github.com/erikd/language-javascript/tree/new-ast) branch of
>this github repository.

So the change isn't trivial, but probably still quite straightforward. I hope.

**Comment by paf31** [comment]
Sounds good, but I don't have time to work on this myself right now. Does anyone want to take this?

If we don't update, is that a problem for Stackage?

**Comment by paf31** [comment]
Ping.

**Comment by AppShipIt** [comment]
Bring it up at Hacked? The only interest I've personally heard has been for the compiler.

**Comment by nwolverson** [comment]
Looking at it
