### ISSUE TITLE
Lisp-case (spinal, kebab, train)

### ISSUE THREAD

**Issue by darrrk** [purescript/purescript#1971]
Seems PureScript prefer functional programming style. But I surprising, that it uses CamelCase instead LispCase. For example, in ClojureScript and LiveScript conversely.

**Comment by AppShipIt** [comment]
Is there an issue with the compiler? The IRC channel would be a better medium for such discussions.

**Comment by darrrk** [comment]
> Are you requesting - as an identifier character?

Yes

**Comment by paf31** [comment]
Our syntax for identifiers is inspired by Haskell and JavaScript. As Texas says, please direct these queries to the #purescript IRC channel before opening issues. Thanks!

**Comment by paf31** [comment]
> Our syntax for identifiers is inspired by Haskell and JavaScript

Specifically `lisp-style-identifiers` are not valid JS identifiers.

**Comment by darrrk** [comment]
> Specifically lisp-style-identifiers are not valid JS identifiers.

LiveScript convert it to CamelCase. Ok, I understand, that by design of Haskell. :(

**Comment by robotlolita** [comment]
@darrrk there's a bigger problem here than the fact that `lisp-style-identifiers` aren't valid JS identifiers though: allowing this would increase the ambiguous surface of PureScript's grammar:

```purs
3 - 3 == 3-3
a - b /= a-b
```

**Comment by darrrk** [comment]
Yes, agree) It's breaking change.
