### ISSUE TITLE
Use Stack/LTS for CI builds

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1974]
As long as we have reproducible builds and a simple way to get new contributors up and running, I don't see a need to build against multiple GHC versions any more, since Stack will download the correct version of GHC anyway.

Why not just standardize on a single LTS version (which can change over time)?

**Comment by hdgarrood** [comment]
Also, on the topic of simplifying CI, are we using coveralls any more? I'm not sure what happened but their bot seems to have stopped commenting on PRs a while ago.

**Comment by paf31** [comment]
I think it'd be nice to have Coveralls working again. It seems to run, just doesn't show notifications any more.

**Comment by paf31** [comment]
Closing as dupe of #2034
