### ISSUE TITLE
Redundant import warning for re-exported modules

### ISSUE THREAD

**Issue by jonsterling** [purescript/purescript#1982]
I'm largely pleased with the new warnings for unnecessary imports, but there's one thing that we might be able to tweak for an improved experience. In particular, consider the following case:

```purescript
module Jon
  ( module Jon.Core
  , module Jon.Syntax
  , module Jon.Semantics
  ) where

import Jon.Core as Core
import Jon.Syntax as Syn
import Jon.Semantics as Sem
```

In this case, the imported modules are not used in the implementation of `Jon`, and so there is a warning that they are redundant. But I have imported them specifically for the purpose of exporting them, so I feel that these shouldn't be counted as redundant.

Maybe we should change it so that a module which is re-exported is excluded from this check.

What do other people think?

**Comment by garyb** [comment]
If you export `Core`, `Syn` and `Sem` I think they will be counted as used... it should actually be an error to export the un-aliased versions, but there's a slight bug with that at the moment (tracked elsewhere).

**Comment by jonsterling** [comment]
@garyb Ah, interesting... I didn't realize that I could export `module Core`. I'll try that out and if it works, I'll close this ticket. thanks!
