### ISSUE TITLE
Bundling fails in PureScript 0.8.3 on unicode characters in strings

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1986]
One example case: `"…"` is output as `"\u2026"`, but then when the module is bundled we're getting:

```
  The module could not be parsed:
  lexical error @ line 36 and column 54
```

Maybe something to do with `language-javascript`?

**Comment by nwolverson** [comment]
https://github.com/erikd/language-javascript/issues/48 ?

**Comment by nwolverson** [comment]
Actually should be fixed on latest 0.5 release https://github.com/erikd/language-javascript/commit/67c46ae0124c781a2b8d43e8c1f3adb3ec406903

**Comment by nwolverson** [comment]
Again with latest prelude:
```
Error in module Prelude (Foreign):

  The module could not be parsed:
  lexical error @ line 217 and column 14
```
(this case is on `\b`, a valid JS escape). Tested with https://github.com/purescript/purescript/pull/1989

**Comment by teh** [comment]
Unfortunately I forgot the \a escape because it wasn't documented on the es5 standard. If someone is blocking on this just add `a` and submit PR otherwise I'll do it this weekend

**Comment by hdgarrood** [comment]
I'm fairly sure the `\a` escape is only a thing in Haskell, not JavaScript. I think language-javascript was right to reject that.

**Comment by teh** [comment]
I think it's coming from here: https://github.com/purescript/purescript-prelude/blob/ce827333e813579b569a545235ffeb002c89d6b6/src/Data/Show.js#L18

**Comment by teh** [comment]
https://github.com/purescript/purescript-prelude/issues/65 looks like it's already fixed? I think we can close this issue then with my fixes in language-javascript

**Comment by nwolverson** [comment]
@hdgarrood Sort of right, *any* non escape character (ish) should be valid (http://www.ecma-international.org/ecma-262/5.1/#sec-7.8.4), the value of `\a` is `a`, similarly for other unrecognised escapes, so I think language-javascript is technically being too strict there.

@teh you're pointing at a fixed line, and I think the issue should be closed only when `psc-bundle` is actually using the fixed language-javascript? Either by bumping the version bounds or via #1989.

**Comment by paf31** [comment]
Fixed by @nwolverson's PR, correct?

**Comment by garyb** [comment]
It should be, yep. I'll test it now.

**Comment by hdgarrood** [comment]
Using `psc-bundle` with both unicode string literals and the string escapes in Prelude are working for me on master now, yep.

**Comment by garyb** [comment]
Looks like it probably works, I have a new issue raised by SlamData now though :wink:

**Comment by nwolverson** [comment]
@garyb noooo what? I probably should have written some tests before making the psc-bundle change but I didn't entirely know what it did until I worked through it...

**Comment by garyb** [comment]
@nwolverson oh, don't worry - it's not your fault! #1992

**Comment by hdgarrood** [comment]
Oh, actually, I can't reproduce this now, using the OSX binary on the github releases page. Maybe a later version of `language-javascript` got used for that one?

**Comment by garyb** [comment]
The Prelude was patched to fix that, but SlamData was failing on a unicode character in a string.

**Comment by hdgarrood** [comment]
Yeah, I was testing with a unicode character in a string too. Also @nwolverson said it failed on `\b` which is a valid JS escape?

**Comment by garyb** [comment]
Ah, hm, I don't know then. It's definitely including the file with the unicode char/escape sequence in the bundle?

The specific unicode string that breaks SlamData is `"…"`

**Comment by hdgarrood** [comment]
Yep, I had the same string, and the bundle has:

```javascript
var main = Control_Monad_Eff_Console.log("\u2026");
```

**Comment by hdgarrood** [comment]
#1952 would help a lot here. I think I'm going to take a look at that soon.
