### ISSUE TITLE
[psc-ide] - Add a dummy FFI definition

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#1987]
Given a PureScript module with a foreign import declaration, it would be nice if `psc-ide` could look up the corresponding `.js` file and insert a dummy implementation with the correct number of arguments.

If the file does not exist it could create it at the proper location and with the proper header.

Maybe this rather belongs into the editor plugins?

**Comment by paf31** [comment]
> Maybe this rather belongs into the editor plugins?

Well, if it could be shared nicely between plugins, then I think that would be good.

**Comment by kRITZCREEK** [comment]
I'd say it's fine to require the entire file to be in a syntactically valid state for this command, as it shouldn't come up in the middle of writing a definition, but rather after you finished writing out the type.

That means it's fine if the editor passes us the identifier for the FFI import, as we can figure out the type from the AST.
After writing to the `.js`file `psc-ide` would respond with the filepath and line number and the editors could jump there. I think everything but the "find the identifier" and "jumping" could very well be shared by moving it into `psc-ide`.

**Comment by paf31** [comment]
I think this could also be implemented by a separate tool entirely, one which parsed a `.purs` file, and produced a minimal `.js` file to go along with it. There is something similar tracked on `roadmap`. Maybe that's the better place to discuss this one?

**Comment by kRITZCREEK** [comment]
I don't mind as long as it's written down somewhere.
