### ISSUE TITLE
Scope of `where` and guard clauses differs from Haskell

### ISSUE THREAD

**Issue by parsonsmatt** [purescript/purescript#2005]
[Link to example and reproduction](https://github.com/parsonsmatt/psc-parse/blob/master/src/Main.purs#L11-L17).

Given some code like

```purescript
parseError :: Int -> Int -> Int
parseError x y
    | x < y     = f x y
    | otherwise = g x y
  where
    f = add
    g = subtract
```

I would expect `f` and `g` to be available in both the guard clauses. However, compilation gives this error:

```
* Building project in /home/matt/Projects/psc-parse
psc: No files found using pattern: src/**/*.js
Error found:
in module Main
at /home/matt/Projects/psc-parse/src/Main.purs line 13, column 19 - line 14, column 5

  Unknown value f


See https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue for more information,
or to contribute content related to this error.


Compiling Main
* ERROR: Subcommand terminated with exit code 1
```

The `where` clause only attaches to the closest guard. My guess is that the `where` is desugared to `let` before the guards are desugared, so the scope of the let doesn't float out as much as it would in Haskell.

**Comment by bagl** [comment]
Duplicate #888

**Comment by garyb** [comment]
Ah thanks! I was pretty sure we had an issue for this as I thought I'd seen it discussed recently. Maybe that was on IRC though as the issue has been around for a while.
