### ISSUE TITLE
Building haddock documentation fails for 0.8.4.0

### ISSUE THREAD

**Issue by TerrorJack** [purescript/purescript#2008]
When I was using `stack install --haddock --haddock-deps purescript` to build `purescript-0.8.4.0` along with documentation, the documentation fails to build and `stack` fails with `ExitFailure 1`. Removing `--haddock --haddock-deps` and only building the executables works fine. I haven't encountered this in previous versions, so I'm wondering if there's anyone else experiencing the same issue.

**Comment by hdgarrood** [comment]
Not just you, see #2001.

**Comment by hdgarrood** [comment]
This will be fixed in the next release, thanks for reporting!
