### ISSUE TITLE
Internal compiler error after adding purescript-jquery

### ISSUE THREAD

**Issue by roti** [purescript/purescript#2011]
Hi,

I created a new project, added purescript-jquery with `bower install` and now the compiler seems to crash:

```
* Building project in /home/razvan/personal/puretut
psc: No files found using pattern: src/**/*.js
psc: An internal error ocurred during compilation: "checkForeignDecls: unexpected idents: \"(line 1, column 2):\\nunexpected \\\"on\\\"\\nexpecting symbol\""
Please report this at https://github.com/purescript/purescript/issues
psc: thread blocked indefinitely in an MVar operation
Compiling Control.Monad.Eff.JQuery
* ERROR: Subcommand terminated with exit code 1
```

I am using psc v0.8.4.0 and pulp v8.1.1.

**Comment by paf31** [comment]
Here is the line which throws: https://github.com/purescript/purescript/blob/5fe25aabc2107584d1d514530b263c18a1058494/src/Language/PureScript/Make.hs#L422

@hdgarrood Do you know what this might be?

**Comment by paf31** [comment]
I think it's this: https://github.com/purescript-contrib/purescript-jquery/blob/master/src/Control/Monad/Eff/JQuery.js#L210

`on$prime` is the JS version of the name `on'`, but isn't itself a valid PS identifier.

**Comment by garyb** [comment]
I think that should be `exports["on'"] = ...` actually, I guess it's good that it picked up the error, just that we need a real error message!

**Comment by paf31** [comment]
Ah right. Yes, I'll put this under error messages then.

**Comment by roti** [comment]
Yep, changing the Javascript to `exports["on'"] = ...` made the error go away.

**Comment by roti** [comment]
Actually, I think the issue should remain open until the compiler bug is fixed.

**Comment by hdgarrood** [comment]
I'm working on this.

**Comment by filib** [comment]
I've issued a PR for the `purescript-jquery` issue https://github.com/purescript-contrib/purescript-jquery/pull/25.
