### ISSUE TITLE
Don't warn on a single `hiding` import

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2017]
This should be allowed, just as one fully open import is (but not a `hiding` + full open, etc. just that `hiding` is a special case of open and is currently not treated the same way).

**Comment by kRITZCREEK** [comment]
This will also require changes to https://github.com/purescript/purescript/blob/6cb50eea47d653e8824718378d2ebcfd24f7fe37/src/Language/PureScript/Ide/Imports.hs#L65-L81.

@garyb don't worry about it, this is more of a reminder for me.
