### ISSUE TITLE
Unification error?

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2019]
Pretty sure this is a bug.  Running purescript version `0.8.4.0`.

The following compiles as expected:

~~~purescript
newtype Nat f g = N (forall a. f a -> g a)
runNat :: forall f g. Nat f g -> (forall a. f a -> g a)
runNat (N m) = m

newtype I f g = I (forall a. f a -> g (Tuple (I f g) a))

prefix :: forall f g. Functor g => Nat f g -> I f g -> I f g
prefix n i = I \fx -> Tuple i <$> runNat n fx

prefixes :: forall f g. Functor g => Array (Nat f g) -> I f g -> I f g
prefixes xs i = foldr prefix i xs
~~~

However if `Nat` is a `type` alias and not a `newtype` it doesn't compile:

~~~purescript
-- all this is fine
type Nat f g = forall a. f a -> g a
newtype I f g = I (forall a. f a -> g (Tuple (I f g) a))
prefix :: forall f g. Functor g => Nat f g -> I f g -> I f g
prefix n i = I \fx -> Tuple i <$> n fx

-- this is not
prefixes :: forall f g. Functor g => Array (Nat f g) -> I f g -> I f g
prefixes xs i = foldr prefix i xs
~~~

Error message talking about the implementation of `prefixes`:

~~~purescript
  Could not match type

    a3

  with type

    a1


while trying to match type f0 a3
  with type f0 a1
while checking that expression xs
  has type _0 (f0 a1 -> g2 a1)
in value declaration prefixes

where g2 is a rigid type variable
        bound at line 18, column 1 - line 20, column 1
      f0 is a rigid type variable
        bound at line 18, column 1 - line 20, column 1
      a1 is a rigid type variable
      a3 is a rigid type variable
      _0 is an unknown type
~~~

**Comment by paf31** [comment]
Thanks for the report!

**Comment by paf31** [comment]
Oh wait, this is an impredicative types thing, since you have a `forall` inside `Array`. It's basically getting instantiated too early.

I'm tempted to mark this as `wontfix`.

**Comment by paf31** [comment]
By adding a type signature to `foldr`, I think this can be made to work:

```purescript
foldr :: forall f g. Functor g => (Nat f g -> I f g -> I f g) -> I f g -> Array (Nat f g) -> I f g
```

I had to put it in a `where` clause, and I had some trouble checking `foldr` against that type, but I believe it could work.

**Comment by paf31** [comment]
Closing for the reason described above. The recommended solution is to use a `newtype`, as you did before. The Haskell article on impredicativity gives a pretty good overview of the issues here.

**Comment by LiamGoodacre** [comment]
Thanks for your feedback.  I'll have a read about impredictativity :smile:

It also typechecks if I wrap/unwrap arguments in `Unit ->`:

~~~purescript
prefixes :: forall f g. Functor g => Array (Nat f g) -> I f g -> I f g
prefixes xs i = foldr prefix' (const i) (const <$> xs) unit
  where
  prefix' :: forall f g. Functor g => (Unit -> Nat f g) -> (Unit -> I f g) -> Unit -> I f g
  prefix' a b x = prefix (a x) (b x)
~~~

**Comment by AppShipIt** [comment]
> The Haskell article on impredicativity gives a pretty good overview of the issues here.

For future reference: [wiki](https://wiki.haskell.org/Impredicative_types) and [Trac](https://ghc.haskell.org/trac/ghc/wiki/ImpredicativePolymorphism). Apparently Haskell special case's `$` which would fix a common class of PS errors.
