### ISSUE TITLE
IDE server fails to start when there is no `output` path

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2030]
Running `psc-ide-server` results in this:

```
Left /Users/gary/GitHub/slamdata/output/: canonicalizePath: does not exist (No such file or directory)
```

If it really is _needed_ that `output` exists, perhaps we could create it here rather than erroring out?

**Comment by kRITZCREEK** [comment]
I think this happens here: https://github.com/purescript/purescript/blob/48e2766845bcb304d0842b257b97965c28738ef9/psc-ide-server/Main.hs#L85

It just means that we can't install the file watchers and the watcher thread dies, but other than that psc-ide-server should be able to load externs once you create them and manually call the load command.

It would make for a better UX however to inform the user in a nicer way and not make it sound like `psc-ide-server` crashed.

You can customize the `--output-directory` if you don't want `output/`.

**Comment by hdgarrood** [comment]
I'd vote to create that directory if it doesn't exist, too, especially since compiler does this already. Is there any reason not to?

**Comment by garyb** [comment]
Ah interesting. Whatever it is that dies `pscid` doesn't like it anyway:

```
Starting psc-ide-server
/Users/gary/.nvm/versions/node/v5.9.1/lib/node_modules/pscid/output/Control.Monad.Eff.Exception/foreign.js:28
    throw e;
    ^

Error: connect ECONNREFUSED 127.0.0.1:4243
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

**Comment by kRITZCREEK** [comment]
Oh right. Yep that needs proper error handling.

So creating the `output/` folder (or whatever --output-directory was set to) on startup if it doesn't exist?

**Comment by garyb** [comment]
:+1:
