### ISSUE TITLE
IDE server not reading files as UTF8?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2031]
This occurs on Windows.

Yesterday I had to update a bunch of places to use `readUTF8File` rather than `readFile` for `psc-publish`, `psc-docs`, etc, but the IDE executables use `readFile` from `Data.Text`. I was under the impression that was already going to read them as UTF8, but perhaps not, as I get parse errors for any file using unicode symbols for things like `→` or `∷`.

**Comment by garyb** [comment]
Definitely a Windows (or maybe locale) issue, now my PATH is fixed on OSX it works a treat, unicode symbols or not.

**Comment by garyb** [comment]
I'm not even sure where this is happening. I already updated `parseModuleFromFile` to use `readUTF8File`, and it looks like apart from that the server just reads the externs file and doesn't parse the whole thing when dealing with imports. The errors looks like this:

```
Error found:
at D:\Home\GitHub\slamdata\src\SlamData\Notebook\Card\Save\Component.purs line 89, column 14 - line 89, column 14

  Unable to parse module:
  unexpected {
  expecting @, ::, binder operator, ,, | or ->


See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
or to contribute content related to this error.
```

Any ideas?

**Comment by kRITZCREEK** [comment]
I've found the culprit. The call to readFile is inside Rebuild.hs

But I can for the love of god not teach git that that is not a binary file... Could someone else try?

**Comment by garyb** [comment]
Ahh! I think my editor thinks it is binary also, as it didn't find the `readFile` reference when I searched... I'll see what I can do.
