### ISSUE TITLE
Travis does not use stack for deployment builds

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2034]
This is bad, because the build-stack script assumes that you are using stack. This will mean that the deployment will fail, because cabal and stack put executables in different places, but also if it somehow succeeds, it will probably put an incorrect list of dependencies into dependencies.txt in the bundle. I think we will probably have to create binary bundles manually until this is fixed. 

@phadej following from your comment: https://github.com/purescript/purescript/pull/1938#issuecomment-194507533 is it a problem if we switch to `stack` in CI builds, and stop using `cabal-install` entirely? They're both using `Cabal` under the hood, and I don't think I've ever seen an instance where something could be compiled with `stack` but not with `cabal-install`. I guess you could have a case where `cabal` ends up doing a massive search for dependencies that takes ages, but given that we know which Stackage snapshots to use, it ought to be very easy to work out what constraints to add to get it to work, right?

I would like to stop using `cabal-install` if we can because only using stack (like we do in appveyor currently) makes everything *so* much simpler.

/cc @jplatte

**Comment by hdgarrood** [comment]
See also #1974.

**Comment by paf31** [comment]
👍

**Comment by paf31** [comment]
Can this be merged with #1974?

**Comment by hdgarrood** [comment]
I guess, yeah.

**Comment by paf31** [comment]
Let's make this a priority for 0.9, since the release build is breaking right now (`bundle.sh not found`).
