### ISSUE TITLE
Error writing externs file

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2036]
This pops up relatively frequently (1 in 5 compiles perhaps) while working on SlamData now:

```
Error found:

  Unable to write file:

    output\SlamData.Prelude\externs.json



See https://github.com/purescript/purescript/wiki/Error-Code-CannotWriteFile for more information,
or to contribute content related to this error.
```

Happens on both Windows and OSX. @cryogenian mentioned it to me originally.

**Comment by paf31** [comment]
Putting this in 0.10 until we know more about the cause of this.

**Comment by paf31** [comment]
Now that #2338 is merged, maybe this is fixed?

**Comment by kRITZCREEK** [comment]
I've not seen this error for a long time. Does this still happen?

**Comment by garyb** [comment]
It's been so long since I've seen it, I forgot the issue existed. Think we can safely close it 😁
