### ISSUE TITLE
Bad results from the expression pretty printer

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2039]
The following appears in the error message for the expression: `(let o = {a: 0} in o).b`

``` purescript
(let           ."b"
   o = { a: ...
       }
 in o
)
```

Firstly the `"b"` is quoted.  Secondly it's in the wrong place :smiley:

**Comment by natefaubion** [comment]
Its not in the wrong place if you think of the expressions as being side by side :laughing:

**Comment by AppShipIt** [comment]
Ever the optimist 😂

**Comment by garyb** [comment]
Which is exactly what I think is happening :wink: `<>` in boxes joins things top & horizontally I think.

**Comment by LiamGoodacre** [comment]
Woah, quoting is somewhat correct? I didn't know this was valid: `_."a m a z i n g"` !

**Comment by garyb** [comment]
Yeah, it's the PS equivalent to `obj["foo"]` in JS, only it's restricted to literal strings, not expressions. It's so you can have record fields with keyword names and the like. The record syntax is `{ "s i m i l a r": true }`.

**Comment by LiamGoodacre** [comment]
Noticed some other oddities with the quoting - PR incoming :smiley:

**Comment by paf31** [comment]
We have a combinator for this sort of layout, I think.

**Comment by nwolverson** [comment]
Side by side rendering is really confusing.

https://github.com/nwolverson/atom-ide-purescript/issues/112 (search 'psci')
