### ISSUE TITLE
[psc-ide] Rebuild parse error should be JSON

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#2042]
https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Ide/Rebuild.hs#L40

Regular compiler parse errors are output as JSON, I feel this should be similar, avoid having to parse the location (imperfect as it may be) out of a string

**Comment by paf31** [comment]
Should/can this be fixed in 0.8.5?

**Comment by kRITZCREEK** [comment]
Awesome don't know what I was thinking there 👍
