### ISSUE TITLE
Inline newtype destructuring

### ISSUE THREAD

**Issue by dkoontz** [purescript/purescript#2048]
I'm not sure if this feature has a specific name, but in Haskell you can do this

```haskell
newtype Foo = Foo String

myFunction :: Foo -> _
myFunction foo =
    let (Foo f) = foo
    in ... use f here ...
```

The same thing fails in Purescript with `Unable to parse module, unexpected "Foo" expecting symbol`

This would make working with newtypes a bit more convenient as the alternatives are a `case of` or a specific conversion function.

**Comment by paf31** [comment]
I think this is a duplicate of https://github.com/purescript/purescript/issues/764. There is some discussion there of the tradeoffs.

**Comment by dkoontz** [comment]
Sorry yes this is a dupe, I thought I had searched properly but nope!
