### ISSUE TITLE
Change in parser from 0.8.4 to 0.8.5

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#2050]
Consider the following terrible definition of `true`:

``` purescript
module Example where

import Prelude

g :: forall a. (Eq a) => a -> Boolean
g = \ (x :: a) -> x :: a == x
```

In PureScript 0.8.4, it compiles without issue. In PureScript 0.8.5, I get the following error:

```
Error found:
in module Example
at /private/tmp/example/src/Example.purs line 6, column 19 - line 6, column 29

  Unknown type operator (==)


See https://github.com/purescript/purescript/wiki/Error-Code-UnknownTypeOp for more information,
or to contribute content related to this error.
```

Seems like something with the precedence of `::` changed. I noticed this when upgrading Neon from 0.8.4 to 0.8.5: https://github.com/tfausak/purescript-neon/commit/e2d7e6195f0bd71417a71c5ebb1f8e30a797e6f8. I'm not sure if it used to be correct or it's correct now, but it's probably worth a mention in the change log.

**Comment by michaelficarra** [comment]
I would say it's correct now. As someone who doesn't mix infix operators without parens frequently, I would naïvely expect `::` to have a very low precedence.

**Comment by garyb** [comment]
I would tend to agree. What were you intending to do about this @paf31? I think it's almost unavoidable that the parse would be treated this way now, unless we're saying `x :: (a == x)` would be the syntax for type annotations involving operators, which seems a bit weird. For me at least, needing `(x :: a) == x` would be the expected way to write the above.

@tfausak sorry about the breakage though.

**Comment by paf31** [comment]
I agree that the precedence as it is now is probably fine, even if it is a shame that it will cause some breakage.

**Comment by tfausak** [comment]
I also agree that the new precedence is good. 

The change log mentions type operators, which I think is why the precedence changed. A small note there would be sufficient as far as I'm concerned. Something like:

> `x :: a == y` is now parsed as `x :: (a == y)` instead of `(x :: a) == y`.

**Comment by garyb** [comment]
I've just added a note to the change log for 0.8.5 for that. Is this okay to close?

**Comment by tfausak** [comment]
As far as I'm concerned, yeah.
