### ISSUE TITLE
Change indentation after keywords

### ISSUE THREAD

**Issue by AppShipIt** [purescript/purescript#2051]
##### I'm brand new to Parsec parlance. I'll revise as I spend more time in the implementation understanding the current behavior. I should consider expressions without reserved words and possible danger of <q>pythonic</q> rules.

The reference point for indentation currently allows formatting a user should never write. Example:

```purs
main =
        case
      unit
    of
  _ -> 
log "Hi"
```

I propose changing the parser:

1. Mark the reference point for indentation at each reserved word.
2. Subsequent reserved words in a construction (`case`/`of`, `let`/`in`, `if`/`then`/`else`, etc.) should be at least as indented as the previous.
3. Subexpressions (the thing matched by `case`, `let` bindings, etc.) should be indented beyond their respective reserved word.

Syntactically valid ways to format the counterexample:

```purs
main = case unit of
  _ -> log "Hi"
```

```purs
main = case
         unit
       of
         _ ->
           log "Hi"
```

```purs
main =
  case unit
    of
      _ -> log "Hi"
```

**Comment by paf31** [comment]
Indentation doesn't work exactly the same way as in Haskell. Inside certain blocks (`do`, `let`, `case` `where` etc.), a new indentation scope is created, and it is defined by the indentation of the first character inside that block. The block must be indented past the previous block.

What exactly is the confusing part in the examples you gave?

**Comment by AppShipIt** [comment]
It's confusing that 1) it's different than Haskell (although beneficial if it fixed the following points), 2) we in fact do _not_ require indentation inside a `do` block, _unless_ that block is nested, compounding oddity (Haskell's) with inconsistency (our own), not to mention I didn't understand where the parser allows that, and 3) we allow `let` and `in` at different columns (like Haskell but easily fixed) which is misleading in the example provided.

**Comment by paf31** [comment]
The Haskell behavior comes at the cost of greatly-increased complexity in the lexer. In fact, the lexer and parser have to share information (see the Haskell 98 report for details).

I'd rather differ from Haskell than increase the complexity of the lexer.

**Comment by tfausak** [comment]
> we in fact do not require indentation inside a do block, unless that block is nested

That is pretty weird. I would expect `do` blocks to either always require indentation or never require it. (Of course they should always allow indentation.) I've never noticed this oddity because I've never tried to make a `do` block without indentation. 

> we allow let and in at different columns

I wouldn't call this misleading, but it is also strange to me. The only thing that *can* come after a `let` is an `in`, so it doesn't really matter where it's at. That being said, I personally always keep them in line and thought that's the way it had to be.

I'm most confused about not needing to indent a `let` after a definition. Why is this valid PureScript?

``` purescript
main =
let x = "..." in putStrLn x

**Comment by paf31** [comment]
Some of these are related to #1881 and should be fixed by #1968.

The `do` issue is related, and we should require indentation there.

The `let`...`in` issue is not an issue though. Both keywords need to follow the indentation rules of their enclosing block, so it's just as valid as

```purescript
x = case 
      y
      of 1 -> 1
````

Here, `of` is required to be indented past column 4, since that is the current indentation level, introduced by the start of the declaration at "`case`". But there is no requirement for `of` to be exactly at column 4. If that were the case then `case y of`, all on one line, would not parse. Same with `let`...`in`.

I think this can be closed as a combination of "intended" and "duplicate" then.

**Comment by tfausak** [comment]
Oh, I didn't realize that #1881 was still open. 

👍 for `do` always requiring indentation.

I see what you're saying about indentation for `case` and `let`. Makes sense.

**Comment by AppShipIt** [comment]
> 'd rather differ from Haskell

Strongly agree.

> Some of these are related to #1881 and should be fixed by #1968.
> 
> The do issue is related, and we should require indentation there.

I disagree from the fix that it is a dupe. Could we at least update the issue description and add tests in that case?

> If that were the case then case y of, all on one line, would not parse.

I didn't consider `case`.

> `of` is required to be indented past column 4,

I did consider that behavior however which would be preferable to the current behavior:

```hs
main =
      let
    hi = "hi"
  in
putStrLn hi
```

```hs
main =
main =
        case
      unit
    of
  _ -> 
putStrLn "Hi"
```

**Comment by paf31** [comment]
I only say close because this should be broken into two separate issues:

- Fix `do`
- Add docs/tests

**Comment by AppShipIt** [comment]
I'm fine with separate issues but `case` and `let` don't work as advertised either? You said they should advance indentation but I know from the implementation that they don't.

**Comment by AppShipIt** [comment]
@paf31 pointed out my original issue [mostly] works as designed. I rewrite the description as a proposal to change which column we use to reference indentation for most syntactic constructions to match universally accepted conventions.

**Comment by paf31** [comment]
👍 I'm in favor of adding this to 0.9.

**Comment by AppShipIt** [comment]
I'll attempt it this weekend instead of imports then.

**Comment by paf31** [comment]
`do` is a bit of a special case here, since we probably want to keep the ability to put statements on a new line after `do`:

```purescript
myAction = do
  something
  somethingElse
```

Actually, one could make the same case for the new lambda-case like syntax:

```purescript
lefts = mapMaybe $ case _ of
  Left a -> Just a
  _ -> Nothing
```

**Comment by garyb** [comment]
:+1: to those, both are very common currently, and "feel" natural when you're writing code. Same goes for

``` purescript
foo = \_ ->
  unit
```

style lambdas actually, but I assume that's a different case from this anyway.

**Comment by AppShipIt** [comment]
> I assume that's a different case from this anyway.

You're right it's the same issue as for every construct. That's almost certainly the source of surprise to me since I always break lines after `=` (for for functions) and keywords. The only surprise left in the example is that `of` can be indented less than `case` (likewise other paired keywords). But I don't feel that's worth changing alone and can't think of an intuitive solution.

**Comment by garyb** [comment]
I think we can still improve some of the behaviours you pointed out, being able to dedent the value being matched and the `of` is definitely weird.

**Comment by AppShipIt** [comment]
I think de-indent inside value is still desirable?

```purs
main = case
  unit
of
    _ -> 
  log "Hi"
```

**Comment by garyb** [comment]
I wouldn't be sorry to see ^ that go, it definitely doesn't look right to me, but ¯\_(ツ)_/¯

**Comment by paf31** [comment]
I would say everything between `case` and `of` inclusive should be indented past the `case` itself, but the case alternatives don't need to be.

**Comment by AppShipIt** [comment]
That's 1) potentially inconsistent with the `do` and lambda examples (if you had a complex expression between `case` and `of`), less special case which I find more surprising, and maintains consistency with Haskell (not the goal but nice when the changes aren't conspicuous).

**Comment by paf31** [comment]
I think the only practical alternative is to leave things as is.

**Comment by AppShipIt** [comment]
That's my vote. I really appreciate the explanation.
