### ISSUE TITLE
Quote types in type errors?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2056]
If you refer to the `Error` type without importing it first, then you get this:

```
Unknown type Error
```

which is easy to misread as "a type error occurred which was unknown to the compiler" rather than "your code refers to an unknown type called 'Error'". Perhaps we can make this distinction a little clearer? `Unknown type: Error` or `Unknown type 'Error'` perhaps?

**Comment by hdgarrood** [comment]
Same for `UnknownValue` too.

**Comment by soupi** [comment]
I littered the code parts of the errors with backticks. [commit here](https://github.com/soupi/purescript/commit/92e79592c3729375477af7addc366542c93a8d79).
You can try to run `stack test` and see if the errors are to your liking :)

**Comment by AppShipIt** [comment]
Naively it seems like their ought to be a common formatting function?

**Comment by soupi** [comment]
yeah, i'll make the changes when i have time today. :)

**Comment by paf31** [comment]
This is fixed now that we color types in errors.
