### ISSUE TITLE
Explain Missing Row Effect

### ISSUE THREAD

**Issue by robkuz** [purescript/purescript#2061]
Given the following code that

    bar :: forall a. Aff( ajax :: AJAX, random :: RANDOM | a) Number
    bar = do
        e <- liftEff random
        g <- liftAff access
        return e

where 

    random :: Aff (ajax :: AJAX) Number
    type JsonResponse = AffjaxResponse Json
    access :: forall e m. Aff (ajax :: AJAX | e) (Either Error JsonResponse)

everything is fine - however if I leave out on of the row effects from the signature like this

    bar :: forall a. Aff( ajax :: AJAX | a) Number -- minus the random

I get this

    121  bar :: forall a. Aff( ajax :: AJAX | a) Number
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    No type class instance was found for

    Control.Monad.Eff.Class.MonadEff ( random :: RANDOM
                                     | _0
                                     )
                                     (Aff
                                        ( ajax :: AJAX
                                        | a0
                                        )
                                     )

    The instance head contains unknown type variables. Consider adding a type annotation.

     in value declaration bar

      where a0 is a rigid type variable
          bound at line 122, column 1 - line 125, column 12
        _0 is an unknown type

Luckily I know what the right signature was - as I was experimenting with stuff. Had I not known the correct answer upfront already I wouldn't have been able to figure out what this message means.

**Comment by hdgarrood** [comment]
Do you mean `random :: forall e. Eff (random :: RANDOM | e) Number`? I don't think it would typecheck otherwise.

Anyway, I guess the answer here would be to improve constraint inference so that it can deal with more types (specifically: row types) in constraints?

**Comment by robkuz** [comment]
Actually I mean the "Error Message" should be "Improved". 

Obviously this doesn't compile as the particular effect is missing.

But "No type class instance found ..." huh!?

**Comment by garyb** [comment]
That requires knowledge of what a class "means", so I don't think we can do that without some kind of programmable error system. Rows are not restricted to effects, records (objects) use the same feature of the type system.

**Comment by hdgarrood** [comment]
I think "no type class instance found" is correct; you're asking for a `MonadEff` instance which can lift `forall e. Eff (random :: RANDOM | e) Number` actions into `forall e. Aff (ajax :: AJAX | e) Number`, but no such instance exists, because the rows don't match.

Might it make sense / be feasible to add a special case in instance resolution where type classes have row parameters to make these error messages a little easier to understand?

**Comment by robkuz** [comment]
hmm - then lets do another experiment

    foo :: forall r. { bar :: String, baz :: String | r} -> String 
    foo r = r.bar ++ r.baz

will compile obviously. Now lets subtract a part of the signature like this

    foo :: forall r. { bar :: String | r} -> String --no 'baz' here
    foo r = r.bar ++ r.baz

we will get the following error message

    93  foo r = r.bar ++ r.baz
                ^^^^^^^^^^^

    Could not match type

      r0

    with type

      ( baz :: String
      | _1
      )

    while checking that type { bar :: String
                             | r0
                             }
      is at least as general as type { baz :: String
                                     | _0
                                     }
    while checking that expression r
      has type { baz :: String
               | _0
               }
    while checking type of property accessor r."baz"
    in value declaration foo

    where r0 is a rigid type variable
            bound at line 93, column 1 - line 93, column 20
          _0 is an unknown type
          _1 is an unknown type

this is not exactly that much better ;-) but at least it says something about the accessor r."baz" which would bring me on the right track.

**Comment by spicydonuts** [comment]
It would at least be nice for the compiler to notice that the types involved in the error are similar besides their effects and suggest looking at them.

**Comment by paf31** [comment]
One thing which might help here is to fully expand types in errors, according to the final substitution, but I think that would be better written up separately.

I think this can be closed as "known issue" (no fundeps), unless I'm missing something?

_Side note_: Perhaps it's worth `aff` providing a monomorphic `Eff -> Aff` function to make the errors better in the simpler case.
