### ISSUE TITLE
Participation in Summer of Haskell 2016

### ISSUE THREAD

**Issue by evansb** [purescript/purescript#2062]
[Reddit thread](https://www.reddit.com/r/haskell/comments/4gh1tu/summer_of_haskell_now_accepting_applications/)

May I know the participation status of Purescript in Summer of Haskell?

It seems that the source map idea from last year's GSoC hasn't been taken. I want to give it a shot as a summer project

**Comment by paf31** [comment]
As I understand it, it's unlikely that a PureScript project will be chosen for HSOC, unless either:

- the PureScript community can collectively pay for a slot (unlikely)
- we can come up with project suggestions which benefit the Haskell community as a whole

Also, source maps are already implemented. More recent project ideas can be found [here](http://github.com/purescript/gsoc).
