### ISSUE TITLE
I think some features from Idris could be useful

### ISSUE THREAD

**Issue by ptol** [purescript/purescript#2063]
## Laziness
http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#laziness
Functions `maybe`, `fromMaybe`, `bool`, etc would have only one version
```
fromMaybe :: forall a. Lazy a -> Maybe a -> a

x = fromMaybe (1+2) Nothing
```

Also operators `&& ||` could have lazy second argument.
Now they have different behavior compare to the same operators in other languages.

## Nested record update
http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#nested-record-update

```
x2 = x1 {y->z = 10}
```
And "over" update syntax
```
x2 = x1 {y->z %= (_ + 1)}
```
I think these two features would cover like 80% of `lens` use.

## Explicit Namespaces
http://docs.idris-lang.org/en/latest/tutorial/modules.html#explicit-namespaces

A small improvement, but sometime I want to group some functions and I
don't want to create another module for them.

```
namespace Position
  move : Position -> Position
  move = ...

  check: Position -> Boolean
  check = ...
```

**Comment by paf31** [comment]
Could you please break these into separate issues?

We do have lazy values, see the `purescript-lazy` library.

**Comment by soupi** [comment]
I think we can emulate something like explicit namespaces with records today:

```purs
position ::
  { move  :: Position -> Position
  , check :: Position -> Boolean
  }
position =
  { move: ...
  , check: ...
  }
```

**Comment by hdgarrood** [comment]
We already have an issue for nested records, #1807.

**Comment by ptol** [comment]
@paf31 
It isn't really issues just a food for thought about possible improvements.
I believe PureScript doesn't support any syntax sugar for lazyness and it's the
most important part.
Idris compiler can convert `fromMaybe (1 + 2) Nothing` to `fromMaybe
(defer \_ -> 1 + 2) Nothing` if argument has type `Lazy` 
@soupi 
It's ugly, but with alternative syntax for records similar to [Idris record type declaration](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#records) it could be even better solution
```
record initState where
  level = 1
  score = 0

record position where
  move : Position -> Position
  move = ...

  check: Position -> Boolean
  check = ...
```

**Comment by rightfold** [comment]
What would the following do?

    f :: forall a. Lazy a -> Int
    g = f (lazy \_ -> 42)

Will it automatically lazify the argument to `f`? Why? Why not? Special cases like these cause confusion, horror, and complexity.

**Comment by hdgarrood** [comment]
> Will it automatically redefer the argument to f?

No, and I'm a bit confused about why you think it might. Note that `Lazy a` and `a` are different types: why would the compiler force you to write out `defer` if it was going to insert an additional call to `defer` itself?

Currently there is no special language support for laziness because the laziness libraries seem to do the job.

**Comment by rightfold** [comment]
Because `forall a. Lazy a` is subsumed by `forall a. a`, the rule is ambiguous. I thought you could still write `defer` yourself, but if you can't then there shouldn't be a problem.

**Comment by hdgarrood** [comment]
Oh, sorry, I thought you were talking about PureScript's current behaviour, not how it might potentially work if we copied Idris. I don't know how Idris does it.

Anyway, sorry, @ptol, but the GitHub issue tracker is not a good place for food for thought / vague discussion about potential future language changes, and particularly not when 3 different ideas are brought up in one issue. The mailing list or subreddit are better suited, so I'm closing this.

**Comment by paf31** [comment]
I agree, let's close this, but let's extract "Nested record update" into another issue, if there isn't one already. That one sounds interesting.

**Comment by ptol** [comment]
@paf31 What about `&& ||` operators?

Wouldn't it be better if `false && (1 + 2 == 3)` didn't execute right part of the expression?

**Comment by paf31** [comment]
> Wouldn't it be better if false && (1 + 2 == 3) didn't execute right part of the expression?

It doesn't. Those operators are inlined by the optimizer, so they are as lazy as the JS equivalent.

**Comment by ptol** [comment]
What if I want to create my own operator with similar behavior?

**Comment by paf31** [comment]
Then you need to use `Lazy` or a function.

Have a look at evaluation order polymorphism. In my opinion, that's a promising route.

**Comment by ptol** [comment]
version 8.2.0 
```
x = false && (1 + 2 == 3)
```
generate this
```
var x = Prelude["&&"](Prelude.booleanAlgebraBoolean)(false)(Prelude["=="](Prelude.eqInt)(Prelude["+"](Prelude.semiringInt)(1)(2))(3));
```
It doesn't have any inlining.

**Comment by paf31** [comment]
What about 0.8.5.0?

**Comment by ptol** [comment]
Yes it works in 0.8.5. So the only option would be `Lazy` and use `defer `\_ ->` everytime?

**Comment by paf31** [comment]
For now, yes.
