### ISSUE TITLE
Performance problem with psc-ide

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2064]
MacMini 2012 i7 16GB 1.2TB Fusion drive, OS X 10.11.4 El Capitan.

MacVim takes 10-20 seconds when closing/quitting the purescript source file with psc-ide integration installed, even if no changes were introduced. 
When this happens one can notice ReportCrash process hanging for a few minutes with the following in the system.log:

```
Apr 29 03:39:30 kika-mini com.apple.xpc.launchd[1] (com.apple.ReportCrash.Root[8423]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash.DirectoryService
Apr 29 03:39:31 kika-mini ReportCrash[8423]: Invoking spindump for pid=8385 wakeups_rate=185 duration=244 because of excessive wakeups
```
 
PID 8385 is the pid of the psc-ide-server process.
Diagnostic report from ReportCrash: https://gist.github.com/kika/b358b53a0411e79d45ead38870052c34

**Comment by paf31** [comment]
Can anyone reproduce this?

**Comment by kRITZCREEK** [comment]
I tried on my MPB 2015 but couldn't. I only asked him to make an issue here in case any of the more "veteran" haskellers that dwell in this repository have seen something similar before...

**Comment by paf31** [comment]
If this can't be reproduced, I think we should close it. Can we figure out if it is a Vim plugin issue?

**Comment by kika** [comment]
@paf31, this seems to be the network issue, I'm working on diagnosing it. May be related to my Mac having IPv6. I'll get back soon.

**Comment by kika** [comment]
It is a networking issue. Amazingly, `accept` in Haskell Network library is not a system call, it does a reverse name resolution which makes any application doing `accept` dependent on the proper configuration of name resolution/DNS. 
PR #2107

**Comment by kika** [comment]
BTW, https://hackage.haskell.org/package/network-2.6.2.1/docs/Network.html suggests that this "high level" library is deprecated and new users are advised towards low-level Network.Socket library (that's essentially what I did in psc-ide-server patch)
