### ISSUE TITLE
Nested Record Updates

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2066]
http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#nested-record-update

```
x2 = x1 {y->z = 10}
```
And "over" update syntax
```
x2 = x1 {y->z %= (_ + 1)}
```
I think these two features would cover like 80% of `lens` use.

(extracted from #2063)

**Comment by kRITZCREEK** [comment]
See https://github.com/purescript/purescript/issues/1807

**Comment by paf31** [comment]
D'oh, thanks!
