### ISSUE TITLE
Intall issue?

### ISSUE THREAD

**Issue by wpoosanguansit** [purescript/purescript#2075]
I am trying to install purescript and I have got this error:

npm install -g purescript pulp bower

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install" "-g" "purescript" "pulp" "bower"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! purescript@0.8.5 postinstall: `node --harmony_destructuring lib/install.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the purescript@0.8.5 postinstall script 'node --harmony_destructuring lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_destructuring lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.
  

 node --version
v6.0.0

I am not sure if it is my env anything local to my setup.  Thanks for your help.

**Comment by paf31** [comment]
I think this is a known issue and is being tracked on the `node-purescript-bin` repo:

https://github.com/purescript-contrib/node-purescript-bin/issues/19

**Comment by hdgarrood** [comment]
In case it's not clear, there are two workarounds; either of these should get you up and running:

* Downgrade to node 4 or 5, then `npm install purescript` should work.
* Run `npm install -g purescript@next` and then `npm install -g pulp bower`.

**Comment by wpoosanguansit** [comment]
That works.  Thanks!
