### ISSUE TITLE
Typecheck main in psc-bundle?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2086]
Might it make sense to require `main` to be `Eff _ _` in the `--main` module (if one is specified) when running `psc-bundle`? This has tripped me up a couple of times and can be quite hard to diagnose. I accidentally had `main` as an Aff instead of an Eff, which was extra confusing because my program appeared to run normally and then threw an error right at the end.

Also, if we are going to do this, should we move the `Eff` type into `Prim`?

See also #1350.

**Comment by garyb** [comment]
We talked about it quite a bit before, and most of the fixes seemed worse than the problem they were trying to solve, but perhaps it's time to discuss again. Did you have any ideas for how we might do this? We have no type or AST information in `psc-bundle`, just the input JS.

I don't think `Eff` should be in `Prim` personally. It's already magic in the compiler thanks to the optimiser, so I'm not sure what the move would buy us.

**Comment by paf31** [comment]
This would effectively disallow alternative Preludes.

**Comment by hdgarrood** [comment]
Ah, yeah, both good points. I forgot that `psc-bundle` only has access to the JS. I don't really see any good way of doing this right now, then, other than perhaps coming up with a build system that would have to be a bit higher level than anything we have currently, which could specify build targets kind of like cabal (so that it would know which declarations should be typechecked as entry points), and then would take care of calling `psc` and then `psc-bundle` and somehow also check `main` somewhere in the process, perhaps comparing its type with a whitelist of acceptable entry point types.

That seems like a ton of effort for a not particularly large gain, and it's not even clear to me that creating such a build system would be a good idea, either. 😕

**Comment by garyb** [comment]
Maybe it's something `pulp` could do? Peek at the externs json for the main module to determine information that way, while bundling... something something :wave: :smile:

**Comment by hdgarrood** [comment]
Yeah, we probably can do something like that. `pulp build` can at least make a good guess based on the presence of the `--main` and `--skip-entry-point` flags.

**Comment by paf31** [comment]
Even then, should `pulp` be tied to the core libraries? I suppose it already is in a way, since `pulp init` pulls `console` and its dependencies.

**Comment by rightfold** [comment]
Add a flag to turn off the check or to specify a custom type.

**Comment by hdgarrood** [comment]
How often does the externs format change? I'd really prefer to avoid depending on it directly in pulp.  I wonder if it would make sense for us to use some of what's currently in `psc-ide-server` to provide a more stable API for asking about types of things in externs files?

I've just realised another potential footgun, which is that it's quite easy to accidentally end up with a `Partial` constraint on your `main` if you omit an explicit type declaration for it, in which case your program will simply do nothing!

**Comment by sharkdp** [comment]
> I've just realised another potential footgun, which is that it's quite easy to accidentally end up with a Partial constraint on your main if you omit an explicit type declaration for it, in which case your program will simply do nothing!

This is exactly what just happened to me... Took me a while to figure out why the program was just silently doing nothing.

**Comment by Pauan** [comment]
With regards to allowing multiple preludes, how about something like this?

```
module Prelude.Unsafe

class Main a where
  unsafePerformMain :: a -> Unit
```

Then `purescript-eff` would provide an instance for `Eff`:

```
module Control.Monad.Eff

import Prelude.Unsafe

instance mainEff :: Main (Eff e Unit) where
  unsafePerformMain = unsafePerformEff
```

And when compiling this program...

```
module Main

main :: Eff () Unit
main = pure unit
```

...the compiler would automatically insert something like this at the end:

```
Prelude.Unsafe.unsafePerformMain Main.main
```

(This is assuming that the entry point is `Main.main`)

Then it's just standard typeclass instance lookup.

This has the benefit that `Eff` can be used as the entry point to the program (just like it is right now), but custom preludes can also provide their own instances for the `Prelude.Unsafe.Main` typeclass.

And of course everything would be statically checked:

* If `main` is something which isn't an instance of `Prelude.Unsafe.Main` then it will be a compile error.

* If `main` is an `Eff e a` where `a` isn't `Unit` then it will be a compile error.

* If `main` has a `Partial` constraint then it will be a compile error.

Another cool benefit is that it would be possible to have an instance for `Aff`, which means that it would be possible for `main` to be either `Eff` or `Aff`

**Comment by paf31** [comment]
@Pauan That's an interesting idea, I'll think about that some more, thanks!

**Comment by hdgarrood** [comment]
I think it would be nice to have a system where the compile step remains separate from the bundle step, and where the compile step doesn't have to make any assumptions about the things it's compiling - based on names of exported functions or otherwise, so I think I prefer @garyb's suggestion (even though having `main :: Aff _ _` 'just work' would indeed be lovely).

**Comment by hdgarrood** [comment]
Would it be feasible to address this by providing some tool which can look in the output directory to check whether a given identifier's type unifies with a given type? I'm imagining that `pulp` or some other bundling tool might run, say, `purs check-type ./output Main.main 'Control.Monad.Eff.Eff _ _'`, and then `purs` would look in the externs files for `Main` and `Control.Monad.Eff` (and possibly dependencies of those modules too, if necessary) and exit with 0 if they do unify and 1 otherwise.

**Comment by paf31** [comment]
We could actually get this information from the externs files right now:

```
cat output/Test.Main/externs.json | jq '.efDeclarations[].EDValue
```

**Comment by hdgarrood** [comment]
Is that safe to depend on for separate tools?

**Comment by hdgarrood** [comment]
Ok, I just put together a little library which I think should be able to do these checks: https://github.com/hdgarrood/purescript-externs-check/blob/324fb2fd2aad6311eb6ada350f48ef0d907151a1/src/ExternsCheck.purs. I'm planning to use that inside Pulp. If this works we'll be able to close this issue, I think.

**Comment by hdgarrood** [comment]
You can give this a try in pulp v12.0.0-rc1 (get it with `npm install -g pulp@next`). For example, if your `main` has a `Partial` constraint:

```
$ pulp build --to out.js
* Building project in /home/harry/code/ps-scratch
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
* Bundling JavaScript...
* Main.main is not suitable as an entry point because it:
* 
*  - has a Prim.Partial constraint
* 
* If you need to create a JavaScript bundle without an entry point, use
* the --skip-entry-point flag.
* 
* If you are certain that Main.main has the correct runtime
* representation, use the --no-check-main flag to skip this check.
* 
* ERROR: Failed entry point check for module Main
```

On reflection I think it probably is the right approach to say that taking care of this problem is the responsibility of build tools, in which case this issue can probably be closed. Any other maintainers of build tools might find [externs-check](https://pursuit.purescript.org/packages/purescript-externs-check/) useful — it's a library I just put together which contains the bulk of the checking logic.

**Comment by hdgarrood** [comment]
Now that Pulp does this (see above) I'm tempted to close this. I think this is probably best left to build tools.

**Comment by kRITZCREEK** [comment]
Agreed
