### ISSUE TITLE
Parsing of type operators isn't quite right

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2092]
They bind too tightly, 

``` purescript
StateF s ~> StateF s'
```

is not parsed as:

``` purescript
(StateF s) ~> (StateF s')
```

but instead something like:

``` purescript
StateF (s ~> StateF) s'
```

**Comment by paf31** [comment]
On a related note, does it make sense to have `->` be an infix synonym for `Function` so that users can assign precedences lower than it?

**Comment by garyb** [comment]
Yeah, I think so :). We'd want to keep the special handling in the pretty printer, I assume that wouldn't be a problem?

**Comment by paf31** [comment]
Why keep the special handling?

**Comment by paf31** [comment]
Oh, printer, sorry. Yes.

**Comment by garyb** [comment]
What do you think the precedence should be for `(->)`?

**Comment by paf31** [comment]
Hmm, not sure. Something low but not zero.
