### ISSUE TITLE
Odd type error for Object being used where something implementing Monad is expected (…?)

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#2095]
(With psc v0.8.5.0)

Given this (intentionally incorrect) code:
```purescript
module Main where

import Prelude
import Data.Array as Array

type MyRecord = { abc :: Int }

example :: MyRecord
example = Array.foldM (\a b -> process a b) {abc: 1} [2,3,4]

process :: MyRecord -> Int -> MyRecord
process r n = r { abc = n }
```

I get this error:
```
[1/1 TypesDoNotUnify] src/Main.purs:9:32

  9  example = Array.foldM (\a b -> process a b) {abc: 1} [2,3,4]
                                    ^^^^^^^^^^^

  Could not match type

    ( abc :: Int
    )

  with type

    { abc :: Int
    }

  while trying to match type { abc :: Int
                             }
    with type _0
                { abc :: Int
                }
  while checking that expression (process a) b
    has type _0 _1
  in value declaration example

  where _1 is an unknown type
        _0 is an unknown type
```

What I would've expected is it whinging that `Object` doesn't have a Monad instance (I accidentally used `foldM` instead of `foldl`), not that `{ abc :: Int }` is not `( abc :: Int )` (note braces vs parens).

**Comment by damncabbage** [comment]
Additional info, in case it's useful:
```purescript
-- Replacing line 9:
example = Array.foldM (\a b -> a) {abc: 1} [2,3,4]
```

Produces:
```
[1/1 InfiniteType] src/Main.purs:9:32

  9  example = Array.foldM (\a b -> a) {abc: 1} [2,3,4]
                                    ^

  An infinite type was inferred for an expression:

    _0 _1

  while trying to match type _1
    with type _0 _1
  while checking that expression a
    has type _0 _1
  in value declaration example

  where _1 is an unknown type
        _0 is an unknown type
```

**Comment by hdgarrood** [comment]
Admittedly this error isn't great, but I think it is correct. Looking at the type of `foldM`:

    foldM :: forall m a b. Monad m => (a -> b -> m a) -> a -> Array b -> m a

The type of `process` tells us that `a ~ MyRecord`, that is `a ~ Object (abc :: Int)`, and the type signature of `example` tells us that `m ~ Object`, so then it tries to unify `m a` with the return type of `process`, which of course can't be done. Although if that is what's happening I'm a little surprised it doesn't complain about a kind mismatch first, `*` vs `# *`.

Whatever route the type checker is taking to reach this error, I think there is a type mismatch here, so I think it's correct that it doesn't get as far as looking for a `Monad Object` instance.

**Comment by paf31** [comment]
I suspect the kind check is happening after the type check, but arguably it would be more useful in this case.

**Comment by hdgarrood** [comment]
Do you have any idea whether kind checks are likely to be more useful in general?

**Comment by paf31** [comment]
I suspect yes, since generally if you get a kind error, it indicates something is more fundamentally wrong with the code in some sense, so you look for different classes of problems.

**Comment by paf31** [comment]
So can we write this up as "prefer kind errors to type errors where both apply"?

**Comment by hdgarrood** [comment]
That sounds sensible to me, yeah.

**Comment by damncabbage** [comment]
Thank you both. :)
