### ISSUE TITLE
Support source maps in psc-bundle

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2096]
At the moment, you have to use some other bundling tool if you want to use source maps.

**Comment by paf31** [comment]
👍

**Comment by nwolverson** [comment]
There are 2 options here, transform input source maps, or just produce a source map for the bundling step which can then be combined with an external tool (sorcery), which might be simpler.

I mean to look at this and see if a solution falls out or it requires effort.

**Comment by nwolverson** [comment]
I have a WIP for this, code needs cleaned up & not good enough for breakpoints yet but promising.

**Comment by ryantm** [comment]
Did #2474 close this, or is additional work needed?

**Comment by hdgarrood** [comment]
Yes, #2747 did resolve this, thanks!
