### ISSUE TITLE
Verify core-tests runs before 0.9 release

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2101]
Should a core-tests failure cause the CI build to be marked as having failed, though? I'd assume not (and this is how we had it before), although in this case I expect we just won't notice in most cases when we break core-tests.

Perhaps it makes more sense to have "check core-tests passes" as an item on a release checklist?

**Comment by paf31** [comment]
👍 I can put this under 0.9 so that we remember to check it before the release.

**Comment by hdgarrood** [comment]
Perhaps it makes sense to have a markdown file in the repository with a release checklist, which we can copy an issue to track a specific release?

**Comment by paf31** [comment]
Yes, I think so. We have release checklists from previous releases somewhere.

**Comment by paf31** [comment]
https://github.com/purescript/purescript/issues/1209

**Comment by paf31** [comment]
Tracked under #2151.
