### ISSUE TITLE
Improve error message when 'negate' isn't imported

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2109]
Currently, using rebindable syntax when the relevant names are not in scope can produce some very confusing errors, especially in `psci`, or when using an explicit `Prelude` import which doesn't include `bind` or `negate`:

```
$ pulp psci
 ____                 ____            _       _   
|  _ \ _   _ _ __ ___/ ___|  ___ _ __(_)_ __ | |_ 
| |_) | | | | '__/ _ \___ \ / __| '__| | '_ \| __|
|  __/| |_| | | |  __/___) | (__| |  | | |_) | |_ 
|_|    \__,_|_|  \___|____/ \___|_|  |_| .__/ \__|
                                       |_|        

:? shows help
> let x = 1
> let y = -1
Error found:
in module $PSCI
at  line 1, column 9 - line 1, column 10

  Unknown value negate


See https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue for more information,
or to contribute content related to this error.
```

The obvious fix is to add special cases for `UnknownValue` errors where the name is a rebindable syntax name, although I suppose we might also have to add some information to the AST to tell the difference between desugared rebindable syntax and explicit calls to `bind` or `negate` etc.

Also, I wonder if we might also consider making the names a little more obvious and specific, like `_syntax_bind` or `_syntax_negate`, so that people can define functions called `bind` or `negate` without messing up do notation or unary negation.

**Comment by hdgarrood** [comment]
Also, it seems like `psc-ide` might be vulnerable to this too. Does it know about rebindable syntax / preludes? Perhaps it would make sense to have some way of indicating to `psc-ide` that one import is a "prelude" import, so that it is left alone? cc @kRITZCREEK

**Comment by hdgarrood** [comment]
Is it just `negate` and `bind` which act as rebindable syntax, or are there any others? I was thinking of updating the wiki page as an interim fix.

**Comment by kRITZCREEK** [comment]
Oh sorry I missed the mention. What do you mean by "left alone"? `psc-ide` knows to not mess up the ordering of open imports when adding imports.

**Comment by hdgarrood** [comment]
By "left alone", I mean not turning an open import into one with an explicit export list, potentially causing a confusing error if someone then decides to use do notation or unary negation in that module. Although I guess adding a note to the error would probably be enough.

**Comment by kRITZCREEK** [comment]
If it finds an open import for the identifier to add, it doesn't add an explicit one. The only situation that is a bit shady in that context is around adding an identifier that is in a hidden list, as it won't add that either.

**Comment by hdgarrood** [comment]
Ahh, I see. Thanks!

**Comment by tfausak** [comment]
> Also, I wonder if we might also consider making the names a little more obvious and specific, like _syntax_bind or _syntax_negate, so that people can define functions called bind or negate without messing up do notation or unary negation.

I would like that. Neon provides a [`bind`](https://pursuit.purescript.org/packages/purescript-neon/0.5.3/docs/Neon.Helper#v:bind) function but I don't really want people to use it. It's only there for compatibility with the syntax.

**Comment by tfausak** [comment]
I'm not sure if this is the right place to mention this, but: Can `if … then … else …` be rebindable too? As far as I know it's the only syntax that you can't rebind. In Haskell with [`RebindableSyntax`](https://downloads.haskell.org/%7Eghc/8.0.1/docs/html/users_guide/glasgow_exts.html#ghc-flag--XRebindableSyntax) you can define an `ifThenElse` function to be called for `if` expressions. It would be nice to be able to do the same in PureScript.

Haskell has other rebindable syntax that isn't relevant to PureScript, including: `fromInteger`, `fromRational`, `(==)`, n+k patterns, `(>>)`, `fail`, and arrow notation.

**Comment by paf31** [comment]
I think this can be closed now? The error for `bind` at least is now much better.

**Comment by hdgarrood** [comment]
I'd still like to at least address `negate` too first. Are there any others?

**Comment by tfausak** [comment]
I think `bind` and `negate` are the only identifiers required by syntax.

**Comment by garyb** [comment]
`discard` will be now too (or whatever we end up naming it).

**Comment by tfausak** [comment]
The error messages for `bind` and `discard` are very good now:

- Unknown value bind. You're probably using do-notation, which the compiler replaces with calls to the bind function. Please import bind from module Prelude
- Unknown value discard. You're probably using do-notation, which the compiler replaces with calls to the discard function. Please import discard from module Prelude

The error message for `negate` isn't quite as good:

- Unknown value negate

**Comment by mhmdanas** [comment]
I'm taking a stab at this.
