### ISSUE TITLE
Improve static defined-ness checker

### ISSUE THREAD

**Issue by Podlas29** [purescript/purescript#2113]
Hello.

This compiles, which it probably should not, since it uses undefined value
```purescript
module Testing where

import Prelude

getUndefined :: forall a. a -> Unit
getUndefined a = undef
  where undef = (\a -> undef) a
```

Generated output:
```javascript
var Prelude = require("../Prelude");
var getUndefined = function (a) {
    var undef = (function (a1) {
        return undef;
    })(a);
    return undef;
};
```
Using this code will obviously result in runtime errors

I used Purescript 8.4.0

**Comment by paf31** [comment]
This is by design. We apply an approximate rule for testing when a recursive function produces an undefined result (every recursive call must be guarded by a function binder), but we don't try to solve that problem in general. It would be difficult to do so without making things too restrictive.
