### ISSUE TITLE
PSC-IDE error when using nested record type aliases across modules

### ISSUE THREAD

**Issue by alexmingoia** [purescript/purescript#2123]
I get an error in `psc-ide` that does not happen when compiling with `psc`. See this repository to reproduce the issue: https://github.com/alexmingoia/repro-pscide . Compile with `psc`, then use `psc-ide` to rebuild `src/First.purs`.

**Comment by kRITZCREEK** [comment]
After applying fixes for [`0.9`](https://github.com/kRITZCREEK/repro-pscide/commit/90aa71311c1e30a834353bf7e59db3f09688009b) the error no longer happens for me.
