### ISSUE TITLE
Possible compile time optimization in Sugar/Names/Env.hs?

### ISSUE THREAD

**Issue by adarqui** [purescript/purescript#2124]
Hi everyone,

I have a fairly large purescript project. As the project grows, my compile times worsen. Currently, it takes a little over 3 minutes to perform a fresh build. I am using psc-0.8.5.0.

```
$ find output -type f | wc -l
    1178
$ find output -type f | xargs cat | wc -l
   77524
```

Here's an example fresh build: removing the output directory, on an 8 core macbook pro:
```
* Build successful.
real    3m4.977s
user    12m59.221s
sys     0m56.923s
```

I recently compiled psc with profiling enabled so that I could obtain a .prof dump (pulp build +RTS -p -RTS):
- https://gist.github.com/adarqui/b83ecd2e94db1e3e89a07f4dcbdfe55e

As you can see from that dump, most of the time is spent in the addExport function:

```
==                        Language.PureScript.Names            46.6    0.0
addExport                 Language.PureScript.Sugar.Names.Env  44.9    5.0
```

Is it possible that module could be optimized? Maybe using a Map instead of lists? I have no idea.

Hope that dump actually helps & makes sense.

Thanks!

-- Andrew

btw, how I built psc using profiling:
```
stack build --executable-profiling --ghc-options="-fprof-auto -rtsopts"
```

**Comment by paf31** [comment]
I changed everything to `Map`, but only in `addExports`, using `M.toList` in other places to make the existing code compatible, and the performance didn't change. I expect all of the `toList`s added their own cost, so a fix for this will need a bit more work, using `Map` in other places which use the exports.

**Comment by garyb** [comment]
Which list is being referred to here? The list in `addExports` is required as it's used to check for conflicts and to allow us to warn when there's a non-fatal scope conflict. We can't do that with a map.

The actual lookup of things later is done using the head of the list, the list should always be a singleton unless there is a conflict of some kind.

I'm really surprised that this function is responsible for any noticeable amount of time at all! I'll have to try compiling SlamData with profiling enabled too, and see what we get there.

**Comment by garyb** [comment]
Ah, we could use a `Set` though, I think.

**Comment by garyb** [comment]
I'm in `Names` already so I'll make the change while I'm at it.

**Comment by paf31** [comment]
It looks like it's acting like a map based on 

```haskell
if any (\(name', mn') -> name == name' && mn /= mn') exports
  then throwConflictError what name
  else return $ nub $ (name, mn) : exports
```

**Comment by garyb** [comment]
Oh, maybe you're right. I thought these lists were already stored under a keyed lookup though. I'll double check.

**Comment by paf31** [comment]
We could always move this out of 0.9 too if it proves to be tricky to fix.

**Comment by paf31** [comment]
Is this fixed now?

**Comment by garyb** [comment]
I guess it didn't close as I typo'd the issue number originally. I think so! Or at least, the suggested approach has been taken.
