### ISSUE TITLE
Try to get rid of Language.PureScript.AST.Exported

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2130]
Just a refactoring suggestion: I would like to get rid of this module, or at least try to, as it overlaps fairly significantly with `.Sugar.Names.Env`, and is only used in a couple of places in the Docs modules and in psci. The Docs stuff has access to real `Env` values already so that should be easy to change, I think.

**Comment by garyb** [comment]
I think that should be possible, I'm going to elaborate the re-exports during `Names`, so all the information should be readable from then on. That should help with the psci autocompletion too.

**Comment by hdgarrood** [comment]
I think this should probably be closed, actually. It's difficult to imagine how to get rid of this module given that we need information from the AST to make sure that docs appear in the right order; see #3003 and #2525.

**Comment by paf31** [comment]
Ok, we can always reopen it, thanks.
