### ISSUE TITLE
Inlining of negate can produce out of bounds Int values

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2136]
For example, with prelude v1.0.0-rc.3:

```
> let x = negate (bottom :: Int)
> x
2147483648

> x > top :: Int
true
```

I think this is because `negate` is being inlined without a `| 0` for `Int` values. For example:

``` purescript
module Main where

import Prelude

main = negate (bottom :: Int) > top
```

produces

``` javascript
var main = -Data_Bounded.bottom(Data_Bounded.boundedInt) > Data_Bounded.top(Data_Bounded.boundedInt);
```

Adding a bitwise-or with 0 would mean that we would get `negate bottom == bottom :: Int` instead, which is a bit weird, but at least means that `Int` is actually a 32-bit integer.

**Comment by garyb** [comment]
I vote we remove all representations of number from PureScript.

**Comment by MaiaVictor** [comment]
Sorry, is that a joke I'm missing, or do you actually think it would be a good idea? Why?

**Comment by garyb** [comment]
Yeah, it's a joke - we've had a few issues with them. Our number and integer representation are... imperfect shall we say (not law abiding, etc, but unavoidably so if we're using IEEE-754), so not dealing with them would be the easy way out, but not practical at all.
