### ISSUE TITLE
Shadowed type exports should be merged so all listed data constructors are exported

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2138]
Repro case:
```purescript
module Problem (A, A(..)) where
data A = B | C
```

```purescript
import Problem (A(B,C))
```

Compiling the second file generates `Module Problem does not export data constructor B for type A`

I suggest giving an error for such shadowing or at least warning if such export might be useful in some case (which I can't think of).

**Comment by garyb** [comment]
The first module should already raise a warning for a duplicate export of `A`. 

Even though duplicate exports is "bad", I think it's probably a bug that the constructors don't appear to be exported, so I'll fix that instead.

**Comment by paf31** [comment]
@garyb Do you think this is doable for 0.9.1?
