### ISSUE TITLE
Allow multiple entry points to be specified to psc-bundle

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2141]
The use case is for example Google Apps Script. The GAS is the monolithic javascript module (use of libraries is allowed but frowned upon due to serious performance impact) which doesn't have a single entry point a-la `main`. It has multiple entry points which look like event handlers, like `onOpen`, `onInstall`, etc. One can achieve almost necessary result with `psc-bundle`'s `-m` option and export appropriate functions from the module(s), but these modules are wrapped inside closures and only `var PS` is available in the global scope. 

As an alternative I can think of adding an option to add "startup" js code which will be just concatenated to the resulting bundle and call functions, available inside the "PS" (or specified through `-n`) namespace. 
That's what I'm doing manually now. But I'm not sure how that would affect DCE and other possible optimizations.

**Comment by garyb** [comment]
I'm not exactly sure what you want to happen here, if you use `--main` a line of code like `PS["Main"].main();` is injected at the end of the bundle, which I'm pretty sure is not what you want for these entry points. :wink:

If I understand rightly, you want something like this as your bundle:

``` js
var PS = ...
exports.onOpen = PS["Main.Open"].onOpen
exports.onInstall = PS["Main.Install"].onInstall
```

It sounds to me like post-process concat your own JS at the end of the bundle approach is the right way of handling this, as it's a pretty uncommon use case (I assume at least, since we've never had a discussion about this before).

DCE will work just fine, as long as your `--module`s match up with the modules you reference in the bundle.

**Comment by kika** [comment]
Yes, your understanding is correct. 

> It sounds to me like post-process concat your own JS at the end of the bundle approach is the right way of handling this, as it's a pretty uncommon use case

Not sure about commonality, but I thought it may improve interop abilities of Purescript. There are many projects already written in javascript which do not use webpack/browserify or any other build system and just rely on concatenating "bare" files together (uglify, etc. ). I have such project myself, 10Kloc in CoffeeScript, and it would be easier for me to integrate modules written in PS with it if PS had a "bare export" feature.

**Comment by kika** [comment]
I can immediately think of one other application for "bare exports": CouchDB. I have a very complex and large CouchApp and I'd like to be able to write map/reduce/show/list functions for it in pure Purescript without bundling it with boilerplate bare javascript functions.

**Comment by paf31** [comment]
> It sounds to me like post-process concat your own JS at the end of the bundle approach is the right way of handling this

I think so too

**Comment by hdgarrood** [comment]
Why not have a Main module in purescript that exports all the functions that you want to be made available to JS? In that case, you only have to append `module.exports = PS["Main"]` to the file.

**Comment by kika** [comment]
@hdgarrood I use the word "bare" as understood by CoffeeScript compiler for the lack of better term. It means that all "bare exported" functions are present in the global namespace, not as part of the module.exports object. Neither Google Apps Script nor CouchDB support CommonJS (which is not technically true for Couch, but its support is quite limited). They expect you to expose certain functions with certain calling convention from your code.

**Comment by hdgarrood** [comment]
Ohhh, I see now. The only thing is, I'd worry that trying to build this into `psc-bundle` would be at least as boilerplate-y as the manual concatenation solution, as well as presenting a larger (and therefore harder to learn) API, and also it would most likely not be as flexible as manual concatenation. Unless there's a good way of designing it that I've missed?

**Comment by kika** [comment]
@hdgarrood There's one reason why I'd prefer to have this functionality built in, instead of just mechanically concatenating a "startup" file: if the function being called from the Purescript code is effectful, I need to call it as `funcFoo(arg)()` from "startup" file and if not, then just `funcFoo(arg)`. And it's very easy to forget and get the runtime exception. Compiler, on the other hand, has this information (I don't know about the psc-bundle though, I believe it doesn't have the type information) and can create "bare exports" properly in either case.  
At the end of the day, it's just the question of Purescripts reputation of having the best JS interop on the market :-)

Are there any objections against, for example, adding some "magic comments" to the Purescript compiler to control codegen? `-- @export` similar to what Closure compiler does.

**Comment by hdgarrood** [comment]
If you're going to be calling effectful functions from JS, then I would recommend using [eff-functions](https://pursuit.purescript.org/packages/purescript-eff-functions/0.1.2) and exporting `EffFn` versions, then you don't need to worry, regardless of what your bundling solution does.

You are indeed correct that `psc-bundle` does not have any type information, it only gets JS as input. It's not clear to me how the sort of checking you're talking about could work, certainly we don't have any special handling for `Eff` right now (other than that `psc-bundle` assumes the `main` declaration in your designated main module should be "run" by calling it).

How would `-- @export work`?

**Comment by kika** [comment]
@hdgarrood I had the impression that eff-functions is only for the other way around - prevent returning the function without arguments from JS FFI effectful implementation. I'll look into that.

`-- @export` will mark the function as `main`-like, i.e. as an entry point available in the global scope.

**Comment by hdgarrood** [comment]
eff-functions can convert in either direction, so it should work here. I don't think we should be converting effectful functions/computations to the idiomatic JS representation automatically inside the compiler; I'd definitely want that kind of conversion to be explicit. I don't want to see `a -> Eff _ b` and not have sufficient information to know about its runtime representation; if I'm understanding your proposal correctly, I'd have to check the build script too.

I'm not really keen on `-- @export` either - I think it makes modules more complex than they need to be, mixing in concerns such as the global scope, the build/bundling process, and arguably even the compilation target language, which don't really show up in the definition of modules as they are now.

Sorry, but I think this would be a case of the cure being worse than the disease, unfortunately.

**Comment by kika** [comment]
Well, `-- @export` has valid meaning for almost any target I can think of. For C++ target, for example, that would mean exported function for `.so` or `.dll`.
