### ISSUE TITLE
Remote connection to PSCi (REPL)

### ISSUE THREAD

**Issue by artemyarulin** [purescript/purescript#2142]
Hi,

Didn't found anything - is it possible to evaluate code in remote clients (like browser/mobile devices,etc) using repl? 

According to this [PSCi.hs#L194-L208](https://github.com/purescript/purescript/blob/master/psci/PSCi.hs#L194-L208) psci runs Node.JS process env evaluates code there. Other tools/languages like ClojureScript/ghcjs using a (web)socket in order to build a bridge between different clients and a repl process, can we do the same here?

I would be more than happy to contribute as it's an only missing feature for me in PureScript, although I'm very new to Haskell and PureScript, so I would appreciate some help.

Thanks

**Comment by paf31** [comment]
I would like to see this too, and I was planning to work on it soon(ish). I would be happy to work together with you on it, if you like. My plan was to start a HTTP server inside PSCi, and then have that serve the initial compiled CommonJS modules and then incremental build products over a websocket to the browser, but we could discuss alternatives.

One alternative would be to provide the console in the browser as well, and then just have PSCi run in server mode.

**Comment by artemyarulin** [comment]
Very nice, I would be happy to work together on this: Next week I'm partially available, but week after that I'm on vacation and can put all my free time on that. 

I'll get familiar with code and write down my ideas here tomorrow

**Comment by artemyarulin** [comment]
I completely agree with your idea, but here how I see it in details. Sorry for the wall of text, but I would like to be sure that we didn't miss anything. Coming from ClojureScript where REPL based development is an incredible productivity boost I hope to bring the same to PureScript. 

Here rough plan:

1 `psci` should optionally open a socket: Not everyone needs it
2 It should be possible to specify the socket port: In certain cases user want to have multiple REPL sessions for different projects and using a hardcoded value is not good. Alternative way could be choosing random port, but in this case we would be forced to implement retry logic (port is busy - choose another, etc.)
3 Assuming you are fine with number 2, we may say that running `psci --listen-port=43222` will start listening on specified port. If port is unavailable - `pcsi` halts with error, otherwise it could be very confusing for the end user, especially with multiple sessions.
4 Only the server is not enough - there should be a client part. It will be responsible for maintaining WebSocket connection with a server (it's very important to make connection robust - for example in  ClojureScript world [figwheel](https://github.com/bhauman/lein-figwheel) can maintain repl sessions for weeks, which makes REPL based development a peace of cake).  Just to give you a rough idea what client should do here is [GHCjs client REPL part](https://github.com/ghcjs/ghcjs/blob/master/lib/etc/ghcjsiClient.js).
5 `psci` may start serving basic REPL client on `http://localhost:[listen-port]` while start listening for web socket connection on `http://localhost:[listen-port]/ws` (as a possible feature improvement it would be nice to allow user to select server hostname rather than default `localhost`, when you have multiple networks, VM-based development, testing on a real mobile device, etc.)
6 Once `psci` has started listening for websocket connection from the client we may want to block a REPL and give a message in REPL smth like `Wating for websocket connection on a port [listen-port]. Open http://localhost:[listen-port] in your browser` in order to remove any confusion
7 Once user has open the specified url, client part will establish a connection with a server and REPL is ready to rock. Starting from that time all expressions would be compiled and result JS would be send to client browser, evaluated there and result of it would be send backwards to the server using the same socket. Then evaluated expression result will be printed in the REPL

Random thoughts:
1 There has to be timeout (20s?) for evaluating expressions - client may be closed, down, etc. Or does `psci` have a cancel command already? Like `Ctrl-D` or something?
2 We may expect to have different clients for different environments - consider for example my latest attempt to connect React Native environment to GHCjs [ghcjs-repl-react-native](https://github.com/artemyarulin/ghcjs-repl-react-native). There is native-script environment (where PureScript could also run) which also became more and more popular, so no need to support it as it is, but at least make it possible
3 As we are talking about async execution we should filter results from previous expressions. Like expr1 failed with timeout, user entered expr2, result from exp1 got back. As exp1 can be equal to exp2 I guess the easiest way would be using some random UUID for each expression
4 Broadcasting - it should be fine to have multiple clients connected to the same server. Once user entered an expression we will send it to all connected clients. Once first result came back - we print it to the REPL, ignoring all the rest results (based on UUID). It would give multiple bonuses:

  - User opens browser1, closes it and decided to use browser2 instead
  - User wants to do some side effects for multiple clients, like changing JS state (rough example of what I want to be able to achieve with PureScript as well: [clojurescript-mobile-repl](https://github.com/artemyarulin/om-next-cross-platform-template/raw/master/om-next-cross-platform-demo.gif)

5 Assuming that I have already some kinda of webpack hot reloader (or any other tool actually) and I'm working with my webapp on `localhost:7888` it should be possible to connect repl to it. Meaning I should be able to add `<script src='localhost:[listen-port]/repl.js'/>"` to my page and that's it. Allowing to do that our REPL session would have an access to all project compiled files, imported JS files, etc. Meaning we would have a REPL into existing app with all state and UI, rather than just a place to execute JS.

**Comment by paf31** [comment]
That all sounds good to me.

> Or does psci have a cancel command already?

We use the interrupt mechanism in Haskeline. I suspect we'd be able to do something similar in the UI.

> User opens browser1, closes it and decided to use browser2 instead

I'm not sure this is such a great idea if we allow the user to run commands which have arbitrary effects. Running things twice by accident might not be ideal.

> Assuming that I have already some kinda of webpack hot reloader (or any other tool actually) and I'm working with my webapp on localhost:7888 it should be possible to connect repl to it.

For the first version, I'm thinking we'd just set up a static file server to serve compiled modules as CommonJS, and a websocket to serve incremental build products. I think we could support such use cases later if we can get that working first.

**Comment by artemyarulin** [comment]
Got it, you are right - let's start with smaller things.

How would you like to see it - one big PR once I think it's ready or number of smaller one like just client, just server, psci command line options, etc?

What do you think would be the appropriate first step?

**Comment by paf31** [comment]
I think we should try to come up with a minimal set of features for a first version and put that all into one pull request. For me, that means:

- Starting a web server when PSCi starts and showing the address to the user,
- Serving static resources on one endpoint (prebuilt dependencies),
- Serving incremental build products on a websocket endpoint,
- Providing a minimal HTML page to listen and evaluate modules, and serving that too.

The first task should probably be to identify the websocket protocol we'd want to use - what commands we'd send, what responses we'd expect, etc.

Once we know the protocol, we could actually implement a Node client too, which switches things around compared to the GHCJSi way, but that might be interesting.

We'd have to think a little carefully, since the current Node backend is stateless, but the browser version would keep the browser state between evaluations. I suspect that's not an issue for the first version, but we might want to consider supporting some kind of store of values later on, to avoid doing too much evaluation.

**Comment by artemyarulin** [comment]
I'll think about protocol and create some kind of a spec so you can approve it before implementation
