### ISSUE TITLE
"Type variable a was shadowed" warning raised spuriously by partial function

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2145]
``` purescript
fromJust :: forall a. Partial => Maybe a -> a
fromJust (Just x) = x
```

If you rename the type variable to something else it works, so I assume this is to do with the `Partial` handling @paf31?

**Comment by paf31** [comment]
Perhaps this explains #2134 then. It would make sense that `Partial` were the cause of this.

**Comment by garyb** [comment]
Ahh yes, that seems very plausible. I'll check it with my PR.

**Comment by garyb** [comment]
Yep! It fixes that too :tada:.
