### ISSUE TITLE
PSCI errors on load.

### ISSUE THREAD

**Issue by mckeankylej** [purescript/purescript#2147]
When I run `pulp psci` in a bower project I get the following error: 

    [kyle@daniela pure_grove]$ pulp psci
    /usr/lib/node_modules/purescript/vendor/psci: error while loading shared libraries: libtinfo.so.5: cannot open shared 
    object file: No such file or directory

**Comment by jplatte** [comment]
This isn't a problem with psci, you are simply missing a shared library. If you tell me which distribution you're using, I can probably tell you the corresponding package.

**Comment by mckeankylej** [comment]
arch linux!

**Comment by kRITZCREEK** [comment]
libtinfo-5 from the AUR

**Comment by mckeankylej** [comment]
Works great, closing.

**Comment by jplatte** [comment]
For reference for who stumbles upon this thread: The maintainer of `libtinfo-5` just created `libtinfo5` to replace the package with the dash in the name (no content changes) so the one with the dash in the name might not be around for much longer.

Also, you might be interested in the fact that the purescript binary releases can be installed from the AUR as well: https://aur.archlinux.org/packages/purescript-bin/
