### ISSUE TITLE
Remove `=` syntax for record pattern matching?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2149]
This was brought up in IRC today. It's so long since `:` didn't work that I forgot it was even possible to use `=`. It would probably be better if we just went with one of the two.

**Comment by AppShipIt** [comment]
Was there an example?

**Comment by garyb** [comment]
Here you go:

```
fn1 :: { x :: Int } -> Int
fn1 { x = value } = value

fn2 :: { x :: Int } -> Int
fn2 { x: value } = value
```

They both work and mean the same thing.

**Comment by AppShipIt** [comment]
Woah I didn't know that.

**Comment by garyb** [comment]
It's leftover from earlier times :smile: - that's Haskell's record destructuring syntax, but since we kept writing it with colons, and someone eventually opened an issue for it, both became acceptable.

**Comment by LiamGoodacre** [comment]
:+1: Discovered this recently too 😄
