### ISSUE TITLE
Warn about unnecessary imports when a member is imported from two places

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2150]
For example, `import Control.Apply ((<*))` is redundant when there is also an `import Prelude` present. This may be a regression in the current name resolving PR.

**Comment by paf31** [comment]
@garyb Do you think this is doable for 0.9.1?

**Comment by garyb** [comment]
This is actually working as intended. If there are multiple explicit imports for a value there will be a warning, but in the open case there are not. There are two reasons for this: 

1. it's annoying to figure out which import came first at the moment (but fixable, obviously)
2. (and this is actually a good reason), explicit imports are given a higher priority when resolving names as part of the mechanism that makes it safe to have even one open import. If the above was written at a time where only the version in `Control.Apply` existed, and then later a new addition was made to the prelude with another implementation for `(*>)`, we only have to warn that the prelude version is being hidden. So we don't want to change the warning to weaken the import used, even if it is a duplicate-via-re-export, as explicit is always better.
