### ISSUE TITLE
Optimize tail calls modulo cons

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2154]
This Boolean-returning function is not tail-recursion optimized:

```
    go fx fy | fx == w   = go 0 (fy + 1)
             | fy == h   = true
             | otherwise = something fx fy && go (fx + 1) fy
```

However, since `&&` is lazy, this should be tail-recursion optimizable, right? Because `x && f y` is equivalent to `if not x then false else f y`, where `f y` is clearly in tail position.

**Comment by paf31** [comment]
I think you want something like "tail call modulo cons", which we don't support. However, it's equivalent to `tailRecM` for the `Writer` monad, so you can use `Writer (Any Boolean)`, and `tell (something fx fy)` at each step, for the same result (safely).

**Comment by rightfold** [comment]
Doesn't "tail call modulo cons" only apply to data constructors? `&&` isn't a data constructor. It's inlined to a JS operator.

**Comment by rightfold** [comment]
Ok, I'll just go with `if not (something fx fy) then false else go (fx + 1) fy` then :)

**Comment by paf31** [comment]
Correct, hence "something like tail call modulo cons" :)

The claim is that if you have a tail call up to something which looks like `x <> recursive call` for some commutative operation `<>`, then you can allocate the stick in an accumulator parameter instead.

**Comment by rightfold** [comment]
Yeah, however `&&` is somewhat special in its evaluation semantics when applied directly. Since it's already treated as special by the optimizer, I thought the tail-call optimizer might treat it as special as well

**Comment by paf31** [comment]
Oh right, then no.

**Comment by paf31** [comment]
I don't think we should try to support tail recursion modulo cons.

**Comment by robertmassaioli** [comment]
> I don't think we should try to support tail recursion modulo cons.

Oh, why not? 

This function could use some unwrapping:

    go :: InfiniteList b a -> L.List a
    go il = let u = uncons il
            in if keep u.head then u.head `L.Cons` go u.tail else L.Nil

The generated code makes me sad.

**Comment by paf31** [comment]
Cross-posted from Reddit:

These sorts of patterns of recursion can be implemented using existing tools like `tailRecM` and `STArray`:

http://try.purescript.org/?gist=decf38c8352a95c8e5e68fcdc66cff33&backend=core

The TCO code is fragile and interacts poorly with other optimizations. I have no interest in expanding it. If someone is willing to do the work and write the necessary tests and documentation, then we can talk about reopening this, but for now I think this is a decent enough workaround.

If you really need the performance of a `while` loop, then you could get that by using `STArray` directly.

**Comment by robertmassaioli** [comment]
That works for me! I'll give this a look shortly and try and understand tailRecM and STArray fully.

**Comment by hdgarrood** [comment]
I'm tempted to agree with @paf31 here:

> The TCO code is fragile and interacts poorly with other optimizations. I have no interest in expanding it. If someone is willing to do the work and write the necessary tests and documentation, then we can talk about reopening this, but for now I think this is a decent enough workaround

Shall we close this?
