### ISSUE TITLE
Bug in FFI identifier validation

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2172]
For the following FFI module:

    exports['replace\''] = function(x) { ... };

I get the following error:

> The identifier `replace\'` is not valid in PureScript.
> Note that exported identifiers in FFI modules must be valid PureScript identifiers.

To fix it, I have to write:

    exports["replace'"] = function(x) { ... };

This is silly.

**Comment by michaelficarra** [comment]
👍 I'll work on this.
