### ISSUE TITLE
`psci` modules in `library` cause `libtinfo` problem

### ISSUE THREAD

**Issue by menelaos** [purescript/purescript#2176]
There has been a long-standing issue with a missing `libtinfo` library on some systems:
https://github.com/purescript/purescript/issues/2147
https://github.com/commercialhaskell/stack/issues/257

Up until 0.8.5, `libtinfo` was only required for `psci` but not for `psc`.
Starting with 0.9.0, `psc` requires it too:
```
psc --help

psc: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

On a quick glance it seems that 9e562663210e0bb798cf183a25fb84a142a7f17b introduced a dependency for `psc` on 
[`haskeline`](https://hackage.haskell.org/package/haskeline) (which depends on `terminfo` which in turn depends on `libtinfo`) by moving `psci` modules (`Language.PureScript.Interactive`) into the `library` part of `purescript.cabal`.

Depending on the system, the solution is sometimes as easy as installing
a package via the package manager. In other cases, e.g. in Arch Linux, the workaround is a little bit more involved. In any case it is another hurdle to take for the (psc-only) user.

**Comment by hdgarrood** [comment]
I vaguely remember talk about just having a single executable, with subcommands which correspond to each of the separate executables that we currently have. So e.g. `psc compile` might do what `psc` does now, `psc interactive` would do what `psci` does, `psc docs` for `psc-docs`, and so on. If this is still planned, perhaps we should consider this in any fix for this issue.

If we do want to support psc-only installs then I guess we can define a flag in `purescript.cabal` which, when active, removes the `haskeline` dependency, and either doesn't include `psci` executable at all, or causes it to exit immediately with an error message saying it isn't supported?

Both of the issues you link to seem to me to have been resolved, though; is there anything making it difficult for people to install libtinfo on arch linux now? I really think I'd prefer just making it easy to get a full installation.

**Comment by jplatte** [comment]
@menelaos Are you using arch without an AUR helper? If you have one installing purescript should be as easy as running `pacaur -S purescript-bin` / `aura -A purescript-bin` / `yaourt -S purescript-bin`.

**Comment by menelaos** [comment]
@hdgarrood Installing `libtinfo` on arch linux is not overly difficult but it still requires the user to be familiar with the [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) and importing PGP keys.

@jplatte Last time I checked, even AUR helpers did require the import of the PGP key.

**Comment by jplatte** [comment]
You have a point there about PGP, I already forgot about that issue. I guess you could ask the maintainer of the ncurses compat package to remove the pgp check, or start a discussion with the makepkg developers about importing pgp keys automatically / verifying signatures automatically without permanently importing the key into the users keyring. I agree that it sucks for makepkg to support pgp signature checking, but not supporting automatically downloading the public keys.

**Comment by jplatte** [comment]
@menelaos I just uploaded [`purescript-stack`](https://aur.archlinux.org/packages/purescript-stack/) to the AUR, which builds purescript from source via stack pretty much exactly like explained in the Stack section on purescript.org ([download page](http://www.purescript.org/download/)). Because it's build from source, it doesn't require the older ncurses (or a libtinfo symlink). I think that's about as user-friendly as we can hope to get on arch before purescript finds its way into the community repo.

**Comment by hdgarrood** [comment]
@jplatte awesome, thank you!

**Comment by menelaos** [comment]
@jplatte :+1: 
Interesting that stack does not run into the same problem.

**Comment by jplatte** [comment]
@menelaos That's simply because terminfo is part of ncurses, and for some reason can be build both as part of libncurses, or as a seperate library. Some distributions like Debian have them as seperate libraries, and some like Arch have them as one. The Haskell `terminfo` package, which psc / psci depend on through `haskeline`, then checks at compile time which one of the libraries is available (see [their configure.ac](https://github.com/judah/terminfo/blob/master/configure.ac#L42-L46)) and links against that.

**Comment by felixonmars** [comment]
I have made a purescript package in Arch's [community-testing] package, which was built from source with GHC 8.0.1. There's also a simple pulp package that pulls in all the needed dependencies.

https://www.archlinux.org/packages/community-testing/x86_64/purescript/
https://www.archlinux.org/packages/community-testing/any/pulp/

Please let me know if there are any issues associated with them, or I'll move them into [community] together with the rest of GHC 8.0.1 collection after a few days.

**Comment by jplatte** [comment]
@felixonmars Oh, I did not expect this! That's awesome. I don't have an installation with any of [*testing] enabled yet, but I think I'll be able to test it soon. One thing I am already wondering about though: Why is the purescript-package statically linked? All the haskell packages already in [community] seem to be dynamically linked, or at least they have runtime dependencies on other haskell packages.

**Comment by felixonmars** [comment]
All the libraries are dynamically linked, while the executables are still statically linked. There were some issues with dynamically linked executables before, and we also want to evaluate if it worth it to install like ~100 haskell packages that takes gigabytes of disk space for this :)

**Comment by jplatte** [comment]
@felixonmars I've tested the basic functionality now, I don't really know what else to test. Everything seems good to me. So what does the process of removing something from the AUR look like? Is there a way of removing the package from the AUR while leaving a notice about the community package, possibly even something AUR helpers can detect automatically?

By the way, it's surprisingly easy to set up an arch chroot inside another arch system, and it hardly requires any disk space! It's totally awesome :D

**Comment by paf31** [comment]
This looks solved, closing.
