### ISSUE TITLE
psc-bundle should remove unused imports

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript#2177]
@paf31 – as mentioned, I got a lot of compressor warnings when trying to optimize a bundled file using `webpack.optimize.UglifyJsPlugin`.

Steps to reproduce are:
- Build with `psc 'bower_components/purescript-*/src/**/*.purs' 'src/**/*.purs'`
- Bundle with `psc-bundle output/*/*.js --module <module one> --module <module two> --module <module three> --namespace modules --output index.js`
- Build and optimize with webpack
- See compressor warnings
- Inspect output file and see variables created for things which were stripped out

There were 179 warnings in total for my particular file. Here's a subset:

```
Side effects in initialization of unused variable Control_Category [/<path to my project>/index.js:46,6]
Side effects in initialization of unused variable Data_Show [/<path to my project>/index.js:123,6]
Side effects in initialization of unused variable $foreign [/<path to my project>/index.js:129,6]
Side effects in initialization of unused variable Control_Semigroupoid [/<path to my project>/index.js:132,6]
Side effects in initialization of unused variable Data_Unit [/<path to my project>/index.js:173,6]
Side effects in initialization of unused variable Data_Void [/<path to my project>/index.js:174,6]
Side effects in initialization of unused variable Data_Functor [/<path to my project>/index.js:191,6]
Side effects in initialization of unused variable Data_Semigroup [/<path to my project>/index.js:192,6]
Side effects in initialization of unused variable $foreign [/<path to my project>/index.js:282,6]
Side effects in initialization of unused variable Control_Apply [/<path to my project>/index.js:315,6]
Side effects in initialization of unused variable Data_Functor [/<path to my project>/index.js:316,6]
Side effects in initialization of unused variable Data_Unit [/<path to my project>/index.js:317,6]
Side effects in initialization of unused variable Control_Alt [/<path to my project>/index.js:331,6]
Side effects in initialization of unused variable Data_Functor [/<path to my project>/index.js:332,6]
Side effects in initialization of unused variable Control_Alt [/<path to my project>/index.js:346,6]
Side effects in initialization of unused variable Control_Applicative [/<path to my project>/index.js:347,6]
Side effects in initialization of unused variable Control_Apply [/<path to my project>/index.js:348,6]
Side effects in initialization of unused variable Control_Plus [/<path to my project>/index.js:349,6]
...
```

**Comment by wegry** [comment]
Would this have anything to do with #1509?

**Comment by garyb** [comment]
Unless that's the wrong issue number, nope! :smile:

DCE is purely handled in psc-bundle, which knows nothing about the details at the PS level.

**Comment by wegry** [comment]
@garyb Not in regards to DCE. What I mean is, if you import `Data.Maybe` and only use `isNothing` without specifying imports, do other unused properties of the `Data.Maybe` module, `Just` for example, get removed by psc-bundle?

**Comment by Cmdv** [comment]
I've just been looking at this and wanted a little more clarification.
I firstly thought this issue would arise if there was an `.purs` file with unused `import` but I soon came to realise that those are stripped out when compiled with this simple experiment:

```
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)
import DOM (DOM) -- unused import

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  log "Hello sailor!"
```
was correctly built then bundled to be:
```
var PS = {};
(function(exports) {
  // Generated by purs version 0.11.7
  "use strict";
  var Control_Monad_Eff =require("../Control.Monad.Eff");
  var Control_Monad_Eff_Console =require("../Control.Monad.Eff.Console");
  var Prelude =require("../Prelude"); 
  var main = Control_Monad_Eff_Console.log("Hello sailor!");
  exports["main"] = main;
})(PS["Main"] = PS["Main"] || {});
```
Is this issue more related to foreign imports? (I'm unsure that is the case because looking at the log above it mentions `Data_Show`, `Data_Functor` which are from Ps libraries)

**Comment by hdgarrood** [comment]
It seems to me that what's happening in that example is that imports which are unused in PureScript are indeed removed, but imports which are only needed for types (and therefore aren't used in the JS) are not removed. So in your example it should be safe to remove the requires of `Control_Monad_Eff` and `Prelude`, for instance; the only one we actually need is `Control_Monad_Eff_Console`; that is what this issue is for, I think.

**Comment by Cmdv** [comment]
@hdgarrood ah yes I see what you mean, right will investigate how that is happening my hunch is that I need a function to checks the variables with `require` and if those are used inside the function or not.
My thinking is that I need to check the variable that have require and see if there are used in the function or not probably somewhere around the `[compile](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Bundle.hs#L327)` function. Just feels like that would mean a lot of traversing for each variable 🤔

**Comment by garyb** [comment]
It perhaps occurs in situations where DCE eliminates a chunk of a file too, where the imports were used by part of the eliminated code. That's purely a guess though, maybe that case is handled already.

**Comment by Cmdv** [comment]
Took a good look into this and have a couple of questions 😄 

Firstly I wonder if these should be generated when doing the initial compilation with `psc` so maybe deal with it there?

If not then I tried to decipher what was happening in `Bundle.js` and the most logical place I could find where this might fit in would be in `codeGen` [here](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Bundle.hs#L505).
does this look right?

and lastly what would be the best way to do these checks?

- Check each require and if the attached variable is used in current file; if yes leave if no delete it
- What would be the logical way to do this, would I need to traverse the file numerous times for each require statement or accumulate and array of require names and check those in one pass? (this is the part I need pointers as to how I could achieve this 😄)
