### ISSUE TITLE
Wiki: "Differences from Haskell" - Numbers example doesn't compile

### ISSUE THREAD

**Issue by chris-martin** [purescript/purescript#2179]
There's a snippet [here](https://github.com/purescript/purescript/wiki/Differences-from-Haskell#numbers) on the wiki:

> `((x + y)|0 * z)|0`

I tried running it in psci:

```
> let x = 1
> let y = 2
> let z = 3
> ((x + y)|0 * z)|0
(line 1, column 9):
unexpected |
expecting ., {, `, qualifier or symbol
```

This is the first purescript code I've ever tried to run, so I have no idea - Is the wiki wrong?

**Comment by hdgarrood** [comment]
It's not wrong, but perhaps that paragraph could do with being made a little clearer. What that means is that writing `(x + y) * z` in PureScript with `x, y, z :: Int` will compile to `((x + y)|0 * z)|0` in JS.

**Comment by hdgarrood** [comment]
I've just updated the wiki, do you think that's better?

**Comment by chris-martin** [comment]
Oh! Hah. Yeah, that's perfect. Thanks :+1:
