### ISSUE TITLE
Specializing functions

### ISSUE THREAD

**Issue by AppShipIt** [purescript/purescript#2180]
Fancy type features are well and good but https://github.com/purescript/purescript-prelude/pull/83#issuecomment-223785523 brought to my attention there are multiple common cases PureScript has to repeat itself. The Prelude originally eschewed functions like `Prelude.Data.List.map` in favor of polymorphic equivalents. When I've read issues about specializing functions the emphasis has been on compiler optimization. There are 3 cases I'd like to be able to define variants for (perhaps some of these are covered by #1866 but I don't think it reached concensus):

1. Haskell-like default class methods (n.b. the `*Default` [naming convention](https://pursuit.purescript.org/search?q=default))
2. Haskell-like default signatures (e.g. `ap` in https://github.com/purescript/purescript/issues/361#issuecomment-193016216)
3. Constrained functions such as generalized `flip` rather than inventing new names to avoid calling it `fflip`.

**Comment by paf31** [comment]
I think some examples would help me to understand what you'd like here.

In the case of `fflip`, it might be a generalization of `flip` at the value level, but I don't think of it that way, and I doubt others do. Similarly, we don't tend to think of `pure` as a generalization of `const`, even though its type subsumes the type of `const`.

**Comment by AppShipIt** [comment]
> I think some examples would help me to understand what you'd like here.

Haskell documents 1 and 2 with trivial examples in the [<q>Default signatures</q> section](https://downloads.haskell.org/~ghc/7.2.2/docs/html/users_guide/type-class-extensions.html) aside from the links provided in the description.

> we don't tend to think of `pure` as a generalization of `const`, even though its type subsumes the type of `const`.

Different names for different use case sounds fundamentally monomorphic? Prelude keeps names like `bind` instead of `chain` or `andThen` in part because the latter imply some instance. Regardless I could pick any function with a class constraint to specialize. A trivial example would be if to do `lessThan` without having to call `compare` for hypothetical performance reasons.

**Comment by paf31** [comment]
> Different names for different use case sounds fundamentally monomorphic?

Perhaps, but it's not like that's a bad thing. Monomorphic functions are easier to document, test and teach. Also, there are often multiple equally valid generalizations of a monomorphic function.

I feel strongly that we should not overgeneralize in Prelude.

There should be an open issue for default superclass instances. I think it'd be nice, but it's not a priority for me right now.

For default signatures, note that many Haskell libraries still provide `*Default` functions, since you can only have one default implementation per class member.

**Comment by AppShipIt** [comment]
> Monomorphic functions are easier to document, test and teach.

The ticket was about first class syntactic monomorphic specialization.

> I feel strongly that we should not overgeneralize in Prelude.

That's surprising considering `Num` was just renamed `Field`.

> There should be an open issue for default superclass instances.

It was linked in the description. I opened this ticket because it subsumes the former in terms of use cases.

> many Haskell libraries still provide `*Default` functions

A quick Hoggle didn't turn many up but PS mandates such a convention. At the root of the issue is conventions and patterns always indicate the user either knows more about the code than the compiler or must needlessly repeat themselves. But Closing since DRY-ness hasn't necessarily the overriding principal in other issues.
