### ISSUE TITLE
Binaries leave `.tix` files

### ISSUE THREAD

**Issue by menelaos** [purescript/purescript#2181]
Running `psc` or `psci` leaves `psc.tix` and `psci.tix` files, respectively.

I think this is the same issue as in
https://github.com/purescript/purescript/issues/1451
https://github.com/purescript/purescript/issues/697

**Comment by paf31** [comment]
Yes, looks like the issue is in `.travis.yml`:

```
env: BUILD_TYPE=normal COVERAGE=true DEPLOY=true
```

`COVERAGE` and `DEPLOY` should probably not be set together.

Thanks for the report.
