### ISSUE TITLE
Out-of-date documentation

### ISSUE THREAD

**Issue by jplatte** [purescript/purescript#2187]
I think we could use an issue to track all the documentation that isn't up to date anymore (for 0.9.1 or just in general), so I'll start with all the issues in the Wiki that I didn't fix myself because I'm not sure how to:

* [x] https://github.com/purescript/purescript/wiki/Language-Guide#record-patterns I think the record syntax there has been removed (`=` has to be `:`). Will check that later myself.
* [x] https://github.com/purescript/purescript/wiki/Error-Code-MissingFFIModule lists proper use of `--ffi` for `psc` as the only solution, but that option doesn't exist anymore.
* [x] https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule I think I remember something about `:load` having been removed from PSCi. If that is the case, the proposed solution needs updating.
* [x] https://github.com/purescript/purescript/wiki/Error-Code-TransitiveExportError seems to have multiple issues. It seems to have been written before exporting typeclasses required the class keyword, and it also contains something that was apparently meant to be a markdown link but has the syntax the wrong way around, and also points to a non-existent wiki page.
* [x] https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify has an `Eff` before `[F]` in the first code block, which I'd assume doesn't belong there. Also the last two code blocks should not be the exact same, but I don't know which one needs to have `Eff` and `Function` swapped.
* [x] https://github.com/purescript/purescript/wiki/Error-Code-UnknownImportTypeClass Does this error even still exists?
* [x] https://github.com/purescript/purescript/wiki/Language-Guide#rows The 4th paragraph seems to have been cut in half. That is the case even for the oldest revision of the page. No idea what happened there..
* [x] https://github.com/purescript/purescript/wiki/Language-Guide#pattern-matching Didn't have time to rewrite the last paragraph about non-exhaustive pattern matches, might do that myself later.
* [x] https://github.com/purescript/purescript/wiki/Language-Guide#modules needs updating..
* [x] https://github.com/purescript/purescript/wiki/Language-Guide#extending-records I think this and the other two sections after it are redundant, but I haven't checked yet.
* [x] https://github.com/purescript/purescript/wiki/PSCi If I am right about `:load` being removed, this needs updating as well
* [x] https://github.com/purescript/purescript/wiki/Understanding-fixity-declarations#default-fixity Is this information still up-to-date, given that that section hasn't been updated since the first revision available on the GitHub wiki?

**Comment by garyb** [comment]
Thanks for making a start and assembling this! I'm sure there are plenty more out of date out there too, the errors have definitely been changed a bit since 0.8 (some were merged under a common error type, some no longer exist as you noticed, etc.)

**Comment by paf31** [comment]
@jplatte Thanks for looking at this!

**Comment by dgendill** [comment]
I've updated this one to distinguish between the 0.9.1 and the old version.
https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule
