### ISSUE TITLE
FFI exports check is too strict

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2188]
When updating `purescript-behaviors`, I ran into a problem where I could not `export` anything which was not a PureScript identifier (I was trying to export the `Event` constructor [here](https://github.com/paf31/purescript-behaviors/blob/7ead6f052688fa627eeccc23298b6cd365218848/src/FRP/Event.js#L130)). 

I think this is too strict, since in general, we need to be able to export arbitrary things from our foreign modules in order to present a useful interface to JavaScript code.

A workaround for now is to use `module.exports`, which is not checked.

**Comment by spicydonuts** [comment]
It seems really strange to check `exports.X` but not `module.exports.X`, since they're the same thing.  Can that get fixed as part of this too?

**Comment by hdgarrood** [comment]
Hm, I'm not convinced. If people are writing JS that wants to be consumed by other JS as well as PS, why not put that JS code into its own script/module and `require` it in the FFI module? It feels weird and asymmetric to me to be able to put invalid PS identifiers in foreign modules, but not regular modules.

**Comment by paf31** [comment]
I guess it depends what we think the foreign modules should be. If they should only be for FFI code, then what we have is fine. If they should be regular Common JS modules which can be used for other purposes, then maybe not. I'm fine if we pick option 1, I just need to refactor my code.

**Comment by natefaubion** [comment]
I think the CommonJS aspect is just an implementation detail for the compiler. Since the files get moved around by the compiler anyway, and it makes its own assumptions wrt to DCE, I'd say `require`ing foreign modules directly from outside of PS code is an extremely brittle anti-pattern.

**Comment by paf31** [comment]
Alright, I'm convinced, I'll fix up my code instead. Thanks.
