### ISSUE TITLE
Using row kinds in instance declarations

### ISSUE THREAD

**Issue by daniel-chambers** [purescript/purescript#2196]
The PureScript compiler seems to prevent the following `monadMine` instance from being created:

```purescript
import Prelude
import Control.Monad.Aff (Aff)
import Network.HTTP.Affjax (AJAX)

class Monad m <= MonadMine m where
  test :: Unit -> m Unit
  
instance monadMine :: MonadMine (Aff (ajax :: AJAX | e)) where
  test _ = pure unit
```
(ignore that the `ajax` effect isn't actually used in the instance, that's just for simplifying the example. Imagine replacing the `pure unit` call with something that requires that effect)

It gives the following error:

```
Type class instance head is invalid due to use of type at line 8 col 1
    ( ajax :: AJAX
    | e
    )
  All types appearing in instance declarations must be of the form T a_1 .. a_n, where each type a_i is of the same form.
in type class instance MonadHttp.MonadMine (Aff
                                              ( ajax :: AJAX
                                              | e
                                              )
                                           )
```

To work around this, one must create a newtype to wrap the type being instanced, and then create the instance for that newtype instead. ([Example](https://gist.github.com/daniel-chambers/76bc2c3d601e1c65f25b945e32d0eafd/4014b7d312fc7c55198dea790a98e2d4e67591b5))

Is there a reason why the PureScript compiler rejects using rows in the instance declaration? It seems like on face value that this should work.

**Comment by paf31** [comment]
Rows are not allowed in instance heads, although there may be a workaround once we get `~` constraints:

```
instance monadMine :: (e ~ (ajax :: AJAX)) => MonadMine (Aff e)
```

There are existing discussions about this in #1510 and #1822.
