### ISSUE TITLE
Type shadowing error

### ISSUE THREAD

**Issue by rintcius** [purescript/purescript#2197]
The following mechanism used to compile and work before but does not compile with v0.9.1:

```
module Shadow where

import Prim as P

type Number = P.Number
z :: Number
z = 0.0
```

Error:

```
Error found:
in module Shadow
at ..../Shadow.purs line 6, column 1 - line 6, column 12

  Conflicting definitions are in scope for type Number from the following modules:

    Prim
    Shadow
```

**Comment by paf31** [comment]
@garyb Do you think this is a simple fix? Do you still want to put it into 0.9.2 or should I move it back to 0.10.0?

If the latter, we can probably release 0.9.2 today.

**Comment by garyb** [comment]
I don't know, I'm surprised it does this at all actually, so it might not be that straightforward. I'll not be working on PS again until later in the week at the earliest, so sure, bump it to 0.9.3 or something :)

**Comment by paf31** [comment]
Alright, sounds good, will do. Thanks.

**Comment by paf31** [comment]
@garyb Speaking of which, let's try to find some time to prioritize the stuff in 0.10.0 soon. There's quite a lot in there, but I think we can break it up nicely. Now that the book is updated, I'm hoping to get back to "real work" on the compiler soon.
