### ISSUE TITLE
"A type variable has escaped its scope" when using `$`

### ISSUE THREAD

**Issue by adamw** [purescript/purescript#2200]
The following compiles just fine:

```
type Any = (forall t. (forall o. o -> t) -> t)
test :: forall t. Any -> (forall o. o -> t) -> t
test ff f = ff f
```

However, adding `$` between `ff` and `f` (which shouldn't have any effect in this case I think) causes a compile error:

```
type Any = (forall t. (forall o. o -> t) -> t)
test :: forall t. Any -> (forall o. o -> t) -> t
test ff f = ff $ f

A type variable has escaped its scope.

 in the expression ($) ff
 in value declaration test
```

(I know this specific type doesn't make much sense, but it's a simplified version of https://groups.google.com/forum/#!topic/purescript/yUAg22J9n9I. I haven't been able to simplify this further)

**Comment by jplatte** [comment]
This sounds to me like it's exactly what the wiki page for the error (which the compiler should output a link to) explains: https://github.com/purescript/purescript/wiki/Error-Code-EscapedSkolem#-and-runst

It's not a bug, Haskell just has some compiler magic that allows `$` in this kind of situation even though the type system doesn't really allow it, and PureScript does not have that kind of trick in the compiler.

**Comment by adamw** [comment]
Ah didn't see the link as I'm using `psc-ide` - thanks. Can't say I understand what's going on (e.g. which type variable escapes), but as I understand the wiki this is kind of a limitation of the type checker? As I suppose both programs (using application and `$`) are correct?

**Comment by natefaubion** [comment]
https://ghc.haskell.org/trac/ghc/wiki/ImpredicativePolymorphism

short answer: impredicative *inference* is really hard, and not a solved problem.

**Comment by paf31** [comment]
By design. To see why this is difficult, consider the type of `$` in your example.

**Comment by adamw** [comment]
Thanks! My knowledge of impredicative types increased significantly :) I allowed myself to edit the wiki to add the above link, as my case wasn't explicitly named.
