### ISSUE TITLE
Inferencing `StateT` monad instance when the state is universally quantified

### ISSUE THREAD

**Issue by adamw** [purescript/purescript#2201]
This is based on the forum thread: https://groups.google.com/forum/#!topic/purescript/tr4xQ1F-YRA

Given the following state definition and usage:

```
type TestState = forall x. x -> x

test :: StateT TestState (Either String) Unit
test = do
  testState :: TestState <- get
  return unit
```

This fails to compile with the following error:

```
  No type class instance was found for
  
    Control.Monad.State.Class.MonadState (forall x. x -> x)
                                         (StateT (forall x. x -> x) (Either String))
  
  in value declaration test
```

If I change TestState to be e.g. an alias for Int, things work. So the crucial element here is the specific type of the state (`forall x. x -> x`)

A work-around is to wrap this in a constructor (e.g. `newtype TestState = TestState forall x. x -> x`), then things work.

**Comment by paf31** [comment]
Again this is due the impredicative instantiation of a type variable, this time the first one in `StateT`. You should make `TestState` into a `newtype`.
