### ISSUE TITLE
Allow prime symbols in data constructors

### ISSUE THREAD

**Issue by starper** [purescript/purescript#2208]
It's great to have primes in type names, but can we have them in data constructors too? It feels a little weird to write something like this:
```purescript
module Bar where

import Foo (Foo)

newtype Foo' = FooP Foo

**Comment by paf31** [comment]
I'd rather not, since data constructor names show up in generated code and type constructor names do not. We'd have to mangle the prime character. Admittedly, we already do that for values, but I would prefer that we didn't.

**Comment by garyb** [comment]
Minor point: `Foo'` is the type constructor here, `FooP` is a data constructor.

I personally wouldn't mind mangling the names in the generated code, but that is the reason why it didn't go in with the previous change.

What's the concern with name mangling Phil? Especially now we have source maps it seems less of a problem.

**Comment by starper** [comment]
@garyb Oops, sorry :)
@paf31 I understand that readable `JS` is important for some people, especially if they write half of their code in `JS` and half in `PS`, but since compiler already produces function names like `foo$prime`, will producing something like `Foo$prime` make any difference? I also understand that names like `foo$prime$prime$prime` are not very readable, but as far as I know (maybe I'm wrong) prime is the only character that is allowed in `PS`, but is not allowed in `JS`, so maybe we can remove `prime` and leave only `$`? `foo$$$` and `Foo$$$` are much more readable in my opinion.
