### ISSUE TITLE
psc-ide: filewatcher issues on MacOS X

### ISSUE THREAD

**Issue by adamw** [purescript/purescript#2209]
This doesn't happen always, but the larger the project & the source file, the more often this happens. When running `psc-ide` and e.g. adding a definition in one file, this isn't then visible when editing another file. 

Here's the original issue as reported in `psc-ide-emacs`: https://github.com/epost/psc-ide-emacs/issues/51#issuecomment-228432565

One suggestion by @kRITZCREEK was:

"If the problems only pop up on OSX it might be a possibility to use the bindings for [kqueue](https://hackage.haskell.org/package/kqueue) on OSX and stick with fsnotify on the other systems."

**Comment by paf31** [comment]
@kRITZCREEK What would you like to do with this issue?

**Comment by kRITZCREEK** [comment]
Well I can't reliably reproduce it and I really have no idea how to tackle this either. One way to circumvent this issue would be to implement a custom polling solution and offer it as an alternative to the filewatcher. This isssue has been pretty stale though, so it might be time spent on a very rare problem.

**Comment by paf31** [comment]
What do we currently use for watching files?

**Comment by kRITZCREEK** [comment]
https://hackage.haskell.org/package/fsnotify

**Comment by natefaubion** [comment]
FWIW I hit this issue every day :) working on slamdata (which is around 1000 modules) I have to reload the server every time I switch files because literally nothing propagates correctly. I manually invoke the checker when I save, so I don't really know architecture-wise why it needs a watcher. Should the server know dependent modules based on its in memory representation of the DAG?

**Comment by natefaubion** [comment]
What I mean to say, my editor knows which file it's being invoked on. Maybe there's a way I can  manually tell pscide to update via a command. A file watcher shouldn't even be necessary then. I realize it's needed for other use cases.

**Comment by kRITZCREEK** [comment]
The file watcher watches the `output` directory and reloads `externs.json` files when they change.

> literally nothing propagates correctly

That sounds terrible 🙀 We should definitely look into it then. One thing you could do for now instead of restarting the server is to send a `reset` command followed by a `load` command.

So the problematic workflow you're having is:

1. Everything compiles fine
2. Edit a source file and add a new exported definition `foo`
3. Save and invoker the rebuild command
4. It succeeds
5. You change to a different file in your editor and invoke completions
6. `foo` doesn't show up

If that sounds about right I'll download the 500mb of slamdata onto my macbook 💃

**Comment by natefaubion** [comment]
That may be what I'm doing. It just the reset command in psc-ide-vim. Thankfully a reset isn't too slow. It's usually just an automatic muscle memory thing for me :D

**Comment by garyb** [comment]
The issue with SlamData affects Windows as well as OSX.

**Comment by kRITZCREEK** [comment]
Okay so I've tried to reproduce the issue but failed. If you could rerun the steps I'm taking maybe we can find out what's happening on your end:

```sh
cd slamdata
bower i
npm run psa
psc-ide-server --debug "src/**/*.purs" "bower_components/purescript-*/src/**/*.purs"
```

In your editor:

1. Load all
2. Add a new definition and rebuild the module

I'm seeing the following when I add a definition `foo` to
`src/SlamData/FileSystem/Dialog/Mount/MongoDB/Component/State.purs`

```
> psc-ide-server --debug "src/**/*.purs" "bower_components/purescript-*/src/**/*.purs"
[Debug] Accepted a connection @(main:Main psc-ide-server/Main.hs:139:5)
[Debug] {"command":"load"} @(main:Main psc-ide-server/Main.hs:149:9)
[Debug] Finished populating Stage2 in TimeSpec {sec = 0, nsec = 121770} @(pures_D22AgOqT9llEcdyquhTFXw:Language.PureScript.Ide.State src/Language/PureScript/Ide/State.hs:177:5)
[Debug] Finished populating Stage3 in TimeSpec {sec = 0, nsec = 3280} @(pures_D22AgOqT9llEcdyquhTFXw:Language.PureScript.Ide.State src/Language/PureScript/Ide/State.hs:198:5)
[Debug] Accepted a connection @(main:Main psc-ide-server/Main.hs:139:5)
[Debug] {"command":"rebuild","params":{"file":"/Users/christophhegemann/Documents/purs/slamdata/src/SlamData/FileSystem/Dialog/Mount/MongoDB/Component/State.purs","cacheSuccess":true,"outpath":null}} @(main:Main psc-ide-server/Main.hs:149:9)
Reloaded File at: /Users/christophhegemann/Documents/purs/slamdata/output/SlamData.FileSystem.Dialog.Mount.MongoDB.Component.State/externs.json
[Debug] Setting Rebuild cache: SlamData.FileSystem.Dialog.Mount.MongoDB.Component.State @(pures_D22AgOqT9llEcdyquhTFXw:Language.PureScript.Ide.Rebuild src/Language/PureScript/Ide/Rebuild.hs:98:9)
```

**Comment by garyb** [comment]
Open atom
```
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"command":"cwd"} @(main:Main psc-ide-server\Main.hs:149:9)
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"dependencies":[],"modules":[]},"command":"load"} @(main:Main psc-ide-server\Main.hs:149:9)
[Debug] Finished populating Stage2 in TimeSpec {sec = 0, nsec = 59977} @(pures_DY50iKtksoPKQfYZxguIb8:Language.PureScript.Ide.State src\Language\PureScript\Ide\State.hs:177:5)
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"file":".../src/SlamData/Workspace/MillerColumns/Component/State.purs","type":"import"},"command":"list"} @(main:Main psc-ide-server\Main.hs:149:9)
[Debug] Finished populating Stage3 in TimeSpec {sec = 0, nsec = 1755} @(pures_DY50iKtksoPKQfYZxguIb8:Language.PureScript.Ide.State src\Language\PureScript\Ide\State.hs:198:5)
```

Save file
```
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"file":".../src/SlamData/Workspace/MillerColumns/Component/State.purs"},"command":"rebuild"} @(main:Main psc-ide-server\Main.hs:149:9)
Reloaded File at: D:\Home\GitHub\slamdata\output\SlamData.Workspace.MillerColumns.Component.State\externs.json
[Debug] Setting Rebuild cache: SlamData.Workspace.MillerColumns.Component.State @(pures_DY50iKtksoPKQfYZxguIb8:Language.PureScript.Ide.Rebuild src\Language\PureScript\Ide\Rebuild.hs:98:9)
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"file":".../src/SlamData/Workspace/MillerColumns/Component/State.purs","type":"import"},"command":"list"} @(main:Main psc-ide-server\Main.hs:149:9)
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"currentModule":"SlamData.Workspace.MillerColumns.Component.State","filters":[{"params":{"modules":["SlamData.Workspace.MillerColumns.Component.State","SlamData.Prelude"]},"filter":"modules"}],"search":"Boolean"},"command":"type"} @(main:Main psc-ide-server\Main.hs:149:9)
```

Save file a second time, with a breaking change:
```
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"file":".../src/SlamData/Workspace/MillerColumns/Component/State.purs"},"command":"rebuild"} @(main:Main psc-ide-server\Main.hs:149:9)
[Debug] Setting Rebuild cache: SlamData.Workspace.MillerColumns.Component.State @(pures_DY50iKtksoPKQfYZxguIb8:Language.PureScript.Ide.Rebuild src\Language\PureScript\Ide\Rebuild.hs:98:9)
[Debug] Accepted a connection @(main:Main psc-ide-server\Main.hs:139:5)
[Debug] {"params":{"file":".../src/SlamData/Workspace/MillerColumns/Component/State.purs","type":"import"},"command":"list"} @(main:Main psc-ide-server\Main.hs:149:9)
```
^ no `Reloaded File`

There is one thing here though: the first save always works - that's why restarting `psc-ide-server` for every change is a sort-of workaround currently. :smile:

When you tested, did you try saving multiple times / different files after you saw the initial one work?

**Comment by rvion** [comment]
2 things: 

 1. it might be related to https://github.com/nwolverson/atom-ide-purescript/issues/101 ?

 2. On a recent project, I experimented quite a lot of "Too many open files in system” error on OS X after stating `psc-ide` and runing `pulp --watch build` on a large project. might be related too, not sure.

**Comment by natefaubion** [comment]
Sorry, forgot about this, but I can confirm @garyb's diagnosis (and FWIW I'm using `psc-ide-vim`). If you compile and there's an error, then the next successful compile will propagate. But after that, successful compiles will not propagate.

**Comment by kRITZCREEK** [comment]
Allright thank you for confirming it. I think we can do a lot better here by simply polling every 2-3 seconds and keeping the timestamps in memory. This way we can also monitor the source files without opening too many file descriptors.

**Comment by kRITZCREEK** [comment]
I've added the `--polling` flag which switches the watching behavior. Polling is the default on windows and using file system events on other systems. If you are seeing problems with the file watcher try the polling toggle and see if it resolves things.
