### ISSUE TITLE
Dependent Types

### ISSUE THREAD

**Issue by MaiaVictor** [purescript/purescript#2214]
I really think there is a huge room for a dependently typed language that compiles to JavaScript. There is Idris, but the JavaScript compiler isn't very mature yet. I'm trying to improve it, but I'm not sure I can. PureScript's compiler, on the other hands, has proven itself and is even used in production. It would be fantastic if we had a fork of PureScript with dependent types - but how hard would that be?

**Comment by garyb** [comment]
It probably wouldn't affect the AST or codegen a great deal, so in terms of how difficult it would be to take purescript as a basis for a language with dependent types - probably not that hard. You're only left with the trivial task of implement a typechecker that supports dependant types along with records and typeclasses :wink:

**Comment by paf31** [comment]
Pi types would probably be a good first feature to add. I think it would be an interesting experiment to take something like the Simply Easy paper and try to implement a type checker and code generator with similar goals as PureScript. Then, as @garyb said, you'd need to add records and a few other bits and pieces, but if that were successful, you could probably back-port the ideas to PureScript.

Another option is to pursue things like data kinds and GADTs. Not full dependent types, but something similar with many common benefits.

**Comment by phadej** [comment]
FWIW, you probably don't want to have full-blown Pi-types, until you can be sure you can evaluate `PureScript` during the compilation (with all FFI-stuff), or there have to be some well-thought-out restrictions. Not sure if those work:
- subkind, let's call it `☆`, for types which consist of "good" types: ADTs
    - `(a : ☆) (b : ☆), a -> b : ☆`
- Pi type'd have signature `Π (x : ☆). expr : ☆`
- is `☆ : ☆` or `☆_n : ☆ n_1` or some other universe hierarchy?

To summarise: there aren't as obvious choice for dependent-typed language as there is for polymorphic one (extending System F).

---

Also there are "technical" problems like type-erasure: http://idris.readthedocs.io/en/latest/reference/erasure.html.
Simple option, which Idris also picks, is to annotate arguments which should be erased.
```hs
half : (n : Nat) -> .(Even n) -> Nat       -- Not sure if you can dot non-implicits in Idris
toList : .{n : Nat} -> Vect n a -> List a
```

Implicit parameters is nice feature (or necessary for programming to be even possible)

---

Also, refinement types probably require quite similar machinery as dependent-types, though surface language is different, as well as *"how much compiler can do for you"*. `{a | P}`, where `P : a -> Set` is a refinement predicate, is the same as sum-type, `∑ x P`. (I'm using Agda notations here).

**Comment by paf31** [comment]
Closing as out-of-scope, possible research project, etc. although I do think the idea is interesting.

**Comment by corporatepiyush** [comment]
Can it be revisited ? or at least before 1.x go GA ?

**Comment by aretrace** [comment]
@soupi refinement types would be stupendous! @paf31 what do you think?
