### ISSUE TITLE
Language-Guide#nested-patterns : invalid syntax in example?

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2224]
https://github.com/purescript/purescript/wiki/Language-Guide#nested-patterns

```purescript
f { arr = [x, _], take = "firstOfTwo" } = x
f { arr = [_, x, _] take = "secondOfThree" } = x
f _ = 0
```

- L1&2: matching with `=` raise an `Unable to parse module` error
- L2: a coma seems to be missing

shouldn't it be :

```purescript
f { arr: [x, _], take: "firstOfTwo" } = x
f { arr: [_, x, _], take: "secondOfThree" } = x
f _ = 0
```

**Comment by garyb** [comment]
Yeah it should, thanks. I've updated accordingly - please feel free to go ahead an edit changes in like this if you spot any more!
