### ISSUE TITLE
inference issues arising with state-ish monads

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2228]
when I'm in a monad transformer, and use some function whose return type depends on some type parameters (get, ask, reader, or lens-related stuff), I have problem, because those functions fail to properly infer their only possible valid return type.

To make it compile, I have to write types annotations, but in In some cases, those type annotations turns out to be quite heavy.

eg: 

with 

```purescript
data Factory e = Factory
  { elems :: Array e
  }
```

🍏  this works:

![image](https://cloud.githubusercontent.com/assets/2150990/16869950/8f47fd2e-4a7f-11e6-880c-3e97cb6d088c.png)

🔴  but this doesn't:

![image](https://cloud.githubusercontent.com/assets/2150990/16869935/78d47a54-4a7f-11e6-947a-c7cc1973acd7.png)

![image](https://cloud.githubusercontent.com/assets/2150990/16869940/81af67a6-4a7f-11e6-9038-184ea75db434.png)

I found https://github.com/purescript/purescript/wiki/Error-Code-NoInstanceFound

> This error can also arise in situations where there is no problem with your code, because the compiler is not yet capable of inferring more complex constraints. In these cases, the solution is to add a type signature.

is this the case I'm hitting ?

As it starts to happen almost everywhere in my code, I decided to use fewer lens and stateT-ish stuff for now.

is there some issue related to this ? I found some issues about inference, but I can't really tell if they are about the same thing.

**Comment by garyb** [comment]
#1580 is the related issue, closing this in favour of that.
