### ISSUE TITLE
Why bower when there is npm?

### ISSUE THREAD

**Issue by MaiaVictor** [purescript/purescript#2231]
For what reason do we keep 2 different package managers? `npm` for some things (react, PureScript itself) and `bower` for most PureScript libs. Why not just keep it simpler and use only `npm`?

**Comment by chexxor** [comment]
There is lots of discussion on this topic already:
- https://github.com/purescript/purescript/issues/631
- https://github.com/purescript/purescript/issues/1404
- https://github.com/purescript/purescript/issues/1447
- http://harry.garrood.me/blog/purescript-why-bower/

How is this question different than those discussions?

**Comment by texastoland** [comment]
TL;DR npm doesn't address the client side use case of wanting a single version of any given dependency when there are conflicting ranges regardless where in the hierarchy it's required. Neither does JSPM but Bower functions superbly. We would eventually prefer a standalone package manager like Elm's but it'd need an owner.

**Comment by MaiaVictor** [comment]
I don't think it is, I just didn't find those.

**Comment by pelotom** [comment]
Maybe this is worth revisiting now that the maintainers of Bower themselves are recommending people migrate away from it?

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

The [the bower homepage](https://bower.io/) even has a banner:

![image](https://user-images.githubusercontent.com/128019/31580808-5931fbb6-b10f-11e7-92b9-d723ff72fc9b.png)

**Comment by coot** [comment]
If you want a 'native' package manager, use `psc-package`.

**Comment by coot** [comment]
@hdgarrood yarn has `yarn install --flat` which solves one of the problems of `npm install`.

**Comment by kRITZCREEK** [comment]
@coot The problem with that is, that it is common for a PureScript project to have both PureScript as well as NPM dependencies. Now `yarn install --flat` could install the PureScript dependencies just fine, but all the NPM dependencies wouldn't install because they rely on nesting.

**Comment by git-in-my-anus** [comment]
@kRITZCREEK nesting node modules was an implementation detail, and [it's no longer true](https://docs.npmjs.com/how-npm-works/npm3) for packages without conflicts since npm@3. Though there is no version conflict resolution mechanism, like in bower/yarn, so it will fallback to nesting.

**Comment by kRITZCREEK** [comment]
> or packages without conflicts

Which is a very small subset of NPM. Yarn does NOT serve as a proper package manager for PureScript projects. If you're not happy with bower `psc-package` is the way to go.

**Comment by Pauan** [comment]
@git-in-my-anus 

* Nesting modules isn't an implementation detail. It is an intentional design of npm.

* A lot of npm packages **require** nested modules.

* Npm 3 still nests modules. Npm 5 still nests modules. Yarn still nests modules.

* Using flat mode with Yarn doesn't nest modules, however that causes a **lot** of npm packages to break.

**Comment by hdgarrood** [comment]
> Maybe this is worth revisiting now that the maintainers of Bower themselves are recommending people migrate away from it?

I kind of wish they hadn't made such a strong recommendation; I think they're right to recommend Yarn and Webpack instead, but only in the case of new JS projects (or projects in any other languages which can cope with multiple copies of dependencies and where people host code on npm). Nothing has changed within Bower that makes it no longer suitable for PureScript projects. I'd argue that it's largely community effects that make npm the right choice for new JS projects, even (I didn't find the "don't use Bower" post that went around a few years ago very convincing).

There are indeed problems with Bower (see [some tweets I made](https://twitter.com/hdgarrood/status/884953207612506116)) but these have been around for a long time, and aren't really related to this notice.

In the long term, I would very much like there to be a package manager for PureScript which can take advantage of a solver *as well as* using package sets, like Stack does; I think that's the sweet spot. In fact I do have a slight worry that in the long run, if we go all-in on package sets and avoid using version bounds and solving entirely, we'll struggle to reuse code effectively, eg the amount of effort required to continue producing package sets could increase quite sharply once the ecosystem reaches a certain size. I can't imagine the Stackage maintainers would be able to do the work they do without information from version bounds. But at this point I'm maybe getting a little carried away. It would require a lot of work to get to that point, and Bower + psc-package do the job for now.

**Comment by paf31** [comment]
I think Bower is fine for most use cases, and there's `psc-package` or Purify for others. Or raw Git, or any other means of getting files onto the disk in a place where `purs` can see them. But the compiler has no hard dependency on Bower any more, so really this issue belongs on the Pulp repo, since the Bower dependency has been pushed into Pulp (`init`/`publish`) now.

**Comment by pelotom** [comment]
> There are indeed problems with Bower (see some tweets I made) but these have been around for a long time, and aren't really related to this notice.

The biggest problem with Bower increasingly will be that no one is using it to publish or update their JS packages. The onus will fall on the PureScript community to maintain the entire JS ecosystem’s “image”  within Bower.

**Comment by kRITZCREEK** [comment]
@pelotom We are not using any JS package from the bower registry. It's sorely used to provide the PureScript dependencies. JS dependencies usually get pulled in via NPM.

**Comment by stevematdavies** [comment]
As a Haskell enthusiast and a front end developer with a passion for functional programming, I would love to use Purescript, but I find things still confusing, and akward.

 The package debate should really be over in these days when tech like yarn has reached maturity. Getting Purescript up and running is still not out of the box in 2019, particularly following the latest installation instructions, it needs a lot of hacking and googling before even hello world runs. This isn't conducive to creating prod ready purescript projects. Simply pointing people to psc-package also doesn't help as here there is more issues and confusion with setup, and indeed setup itself doesnt work unless there is more hacking.

I love the opinion and approach of Purescript, and would truly love to use it, but even now, a mere 3 years after these debates, Purescript up and running is still elusive, still in discussion, and still not addressing users issues, and above else, still not working out of the box!

**Comment by JordanMartinez** [comment]
@stevematdavies We know. For some context, see the [Why are PS docs lacking?](https://github.com/chexxor/purescript-documentation-discussion/blob/f85df758618990e9de0d9747d49a53ac5da77621/02-Context-or-Narrative/State-of-PureScript-Documentation-2019.md#why-is-purescripts-documentation-lacking) section in the work Alex and I have been doing lately.

**Comment by hdgarrood** [comment]
@stevematdavies I would love to have the officially recommended package manager be npm rather than bower, but npm is not an option for us at the moment for reasons given in the linked posts above. (If npm implements [singleton packages](https://github.com/npm/rfcs/pull/23) we can consider it.)

The getting started guide does work for the majority of people. I’m not sure why it’s not working for you, but your best bet for help is to post on the [Discourse instance](https://discourse.purescript.org) with all of the steps you’ve taken, together with the full error messages you’re getting.

**Comment by stevematdavies** [comment]
Thank you @JordanMartinez  its encouraging to see a shaed concern, and indeed progress on improvement.

**Comment by VizorKit** [comment]
I picked up this language literally just now, and its quite elegant. I will say if this project can't get off bower, it most likely will never pick up the steam it could.

**Comment by JordanMartinez** [comment]
Two thoughts. First, (I believe) this issue has already been answered
elsewhere in this repo and (I believe) a quick Google search would answer
that question.

Second, read this to answer your question:
https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/02-Build-Tools/01-Dependency-Managers/01-Bower-Explained.md#why-doesnt-purescript-use-npm
