### ISSUE TITLE
Add inline application / normal form operator?

### ISSUE THREAD

**Issue by MaiaVictor** [purescript/purescript#2232]
Again, sorry if this was debated before. Since it seems that PureScript doesn't do any inlining, some high order functions get a huge performance penalty. For example:

    vAdd :: V3 -> V3 -> V3
    vAdd (V3 ax ay az) (V3 bx by bz) = V3 (ax+bx) (ay+by) (az+bz)

Is really fast, but...

    binOp :: (Number -> Number -> Number) -> V3 -> V3 -> V3
    binOp op (V3 ax ay az) (V3 bx by bz) = V3 (op ax bx) (op ay by) (op az bz)
    
    vAdd :: V3 -> V3 -> V3
    vAdd = binOp (+)

Is 10 times slower. Obviously, something like:

    vDot :: V3 -> V3 -> Number
    vDot a b = sum (zipWith (*) (toList a) (toList b))

Is utterly impractical. That forces you to inline your critical function manually, which reduces abstraction, increases duplication, makes bugs more likely. I was thinking about the problem, and, while adding a good inliner is a hard task, I think the addition of those two functions would easily amend the problem:

     -- Inlined application. This causes the application to expand
     -- at compile time, making a function work as a macro.
     (#) :: forall a b . (a -> b) -> a -> b

    -- Normal form: this causes *all* applications inside a term
    -- to be fully applied, i.e., reducing it to nf.
    (nf) :: forall a . a -> a
     
You could use one or another depending on how much you want to inline. 

    vAdd = binOp # (+)
    vDot a b = nf (sum (zipWith (*) (toList a) (toList b)))

This way, both `vAdd` and `vDot` would compile to the fastest definitions. That could also be highly helpful for the generics package. 

I also have a suggestion for Generics: why, instead of using a conventional ADT for GenericSpine, we don't church-encode it? By doing so, we should be able add a rewrite rule `toSpine . fromSpine == fromSpine . toSpine == id`. That would not only completely remove the cost of using generics, but also *enable fusion for free, for all generic functions, for all datatypes!* Yes, that is right, `map (* 2) (map (* 3) (map (+ 1) yourArbitraryContainer` would compile to a tight loop with no intermediate representations. Neat, ins't it? I would gladly write such a definition of GenericSpine myself, all I need is compiler support for inlining and rewrite rules.

**Comment by paf31** [comment]
I think we would like to do more aggressive inlining, but it's a large project.
