### ISSUE TITLE
Build issue with purescript-0.9.2

### ISSUE THREAD

**Issue by phadej** [purescript/purescript#2238]
```
Dependency protolude ==0.1.6: using protolude-0.1.6
```

```
src/Language/PureScript/Ide/Pursuit.hs:56:32:
    Ambiguous occurrence ‘fromStrict’
    It could refer to either ‘Protolude.fromStrict’,
                             imported from ‘Protolude’ at src/Language/PureScript/Ide/Pursuit.hs:22:1-26
                             (and originally defined in ‘Data.Text.Lazy’)
                          or ‘Data.ByteString.Lazy.fromStrict’,
                             imported from ‘Data.ByteString.Lazy’ at src/Language/PureScript/Ide/Pursuit.hs:26:49-58

````

**Comment by kRITZCREEK** [comment]
Hopefully fixed by #2225

**Comment by phadej** [comment]
I made a revision to restrict `protolude` dep version: http://hackage.haskell.org/package/purescript-0.9.2/revisions/

**Comment by paf31** [comment]
Thanks, @phadej and @ilovezfs. Should we constrain the new version to `0.1.6.*` then?

**Comment by ilovezfs** [comment]
If 0.1.7 happens to break it, whenever that occurs, presumably it's best to find out as soon as possible, no?

**Comment by hdgarrood** [comment]
Whether we constrained the new version to `0.1.6.*` or not, we would find out pretty soon anyway, because purescript is in stackage.

👍 from me for `0.1.6.*`. It seems fairly likely to me that this could break in the same way in the future.
