### ISSUE TITLE
Partial class opaqueness

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#2248]
I've been struggling to debug unexpected `Partial` constraints. I'll chime in on a related issue about a vague message related to binding groups. But at the root `Partial` acts like `IO` instead of `Eff`. There's no way to ascertain which parts of a type contributed to the whole type being inexhaustive. A naive example is `Partial => Tuple (Mabye a) (List a)`. Was `Maybe` or `List` missing a case? Regardless `unsafePartial` clears them both. I initially thought it'd make APIs nicer like `Data.Array.Partial.head`. But any function calling `head` also becomes `Partial` if not handled with no way to express <q>why</q> using types (just documentation or a descriptive `crashWith`). `Partial` feels like an implicit `Either a a` flagging whether exhaustivity checking worked in a previous context without compiler verification what's left. I was also surprised it only works at the top level as opposed to inside a `where`. I don't know how to improve the design with parameters or preferably rows but wanted to raise it for discussion.

**Comment by paf31** [comment]
Adding a parameter is tricky because it complicates the way the instances would flow through the solver, I think. Anyway, I think this is an interesting problem for the quality of error messages too.

**Comment by texastoland** [comment]
In my case if I were told which function call(s) introduced the constraint it would've helped a lot. It was coming from an explicitly `Partial`-less annotated mutually recursive function that I missed was calling a partial one.

**Comment by paf31** [comment]
Ah, well my open PR should fix that, at least.

**Comment by texastoland** [comment]
That's what @garyb told me. I meant (I haven't considered how tenable) to know which function call introduced a given constraint (`Partial` or otherwise). If my function `view` is missing a `Partial` constraint it'd help to be directed where it calls partial `head`?

**Comment by texastoland** [comment]
There's also an issue with mutual recursion (<q>binding groups</q>) not reporting a line number. Is that tracked already?

**Comment by paf31** [comment]
I'll close this then?

**Comment by texastoland** [comment]
Sure it was mainly a discussion point.
