### ISSUE TITLE
Compiler requires adding a case which is impossible to encounter

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2265]
```Purescript
mfoo <- getFoo
mbar <- getBar
case [mfoo, mbar] of 
  [Just foo, Just bar] -> doStuff foo bar
  [_, _] -> badStuff
```
Error message:
```
A case expression could not be determined to cover all inputs.
  The following additional cases are required to cover all inputs:
    _
  Alternatively, add a Partial constraint to the type of the enclosing value.
```

**Comment by texastoland** [comment]
That can be known for `List` but not `Array` no?

**Comment by garyb** [comment]
It can't be known for either without baking some magic into the compiler. If the pattern you're trying to write is just what you have above then the multi-case thing should work instead:

``` purescript
case mfoo, mbar of 
  Just foo, Just bar -> doStuff foo bar
  _, _ -> badStuff
```

**Comment by kika** [comment]
@garyb That's what I ended up using, just didn't know it's possible now.
Thanks to @paf31 now I know. He asked to open the issue.

**Comment by texastoland** [comment]
Woah I didn't know that either. It's like a special case tuple??

**Comment by garyb** [comment]
Not exactly, it's the `case` correspondance to writing an equational style function:

``` purescript
fn (Just foo) (Just bar) = doStuff foo bar
fn _ _ = badStuff
```

Originally you couldn't write cases that way, even though internally the AST for `case` has always supported multiple inputs and patterns. The syntax was added in 0.8.0.

**Comment by paf31** [comment]
I asked @kika to write this up since I figured we could extend the checker to deal with literals in the cased values, like array literals etc. 

But the only use cases for those are subsumed by these comma-separated cases, so I'm going to close this. Sorry @kika, I should have remembered this when you asked.
