### ISSUE TITLE
No file or line number for missing Partial constraint

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#2272]
Error: `No type class instance was found for Prim.Partial in binding group viewL, deepL`. Neither function declared a `Partial` constraint, but they're mutually recursive, and `viewL` calls a `Partial` function. I would expect one error for each including file and line number.

**Comment by paf31** [comment]
Which compiler version? Can you try with 0.9.3 if you're not already please?

**Comment by texastoland** [comment]
Doh my npm update script was broken. Confirmed fixed 👌
