### ISSUE TITLE
Pain point writing Effect types in apps

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#2273]
I have APIs for building up a session and each one adds an effect. Even in libraries it makes me format code inconveniently. Is there a technical reason PS can't aggregate effect synonyms after `|`? Ideally I wish effect rows worked like sets instead of maps but perhaps that's inconsistent with records.

```purs
-- a bigger deal for rewriting the intermediate functions that build this up
type EffSession e = Eff ( DomE e | StorageE e | RandomE e | NowE e | e )
type e. DomE = ( dom :: DOM | e )
type e. StorageE = ( storage :: STORAGE | e )
type e. RandomE = ( random :: RANDOM | e )
type e. NowE = ( now :: NOW | e )
```

**Comment by paf31** [comment]
Sounds like you want row constraints (duplicate?)

What do you the lines in your code sample mean? How would you say them out loud?

**Comment by texastoland** [comment]
I don't think I want row constraints? I'd just like to make synonyms for groups of rows that can be combined. I had a case today I wanted the same for records.

**Comment by paf31** [comment]
Then why not

```purescript
type EffSession e = Eff (DomE (StorageE (RandomE (NowE e))))
type DomE e = ( dom :: DOM | e )
type StorageE e = ( storage :: STORAGE | e )
type RandomE e = ( random :: RANDOM | e )
type NowE e = ( now :: NOW | e )
```

?

**Comment by texastoland** [comment]
Wow yes THAT 🙏

**Comment by texastoland** [comment]
@paf31 I'm struggling to use the same trick with records (contrived but I have a real use case):

```hs
type FooBarBaz = Foo (Bar (Baz ())))
type FooR r = { foo: Foo | r }
type BarR r = { bar: Bar | r }
type BazR r = { baz: Baz | r }
```

**Comment by garyb** [comment]
You can't mix the record part and the row part like that:
``` purescript
type FooBarBaz = Foo (Bar (Baz ())))
type FooBarBazRecord = Record (Foo (Bar (Baz ()))))
type FooR r = ( foo :: Foo | r )
type BarR r = ( bar :: Bar | r )
type BazR r = ( baz :: Baz | r )
```

**Comment by texastoland** [comment]
Ah I suspected that's the solution but had never seen `Record` used thanks 🙌

**Comment by garyb** [comment]
It used to be called `Object` :smile:, but yeah, `{ x :: Int | r }` is syntactic sugar for `Record (x :: Int | r)`.

**Comment by afcondon** [comment]
Excellent!

Since Purescript has such fancy and useful Records (compared to Haskell, i mean) it would be lovely to have a page documenting all the tricks one can do with them. Should i add a page in the Wiki or is there something already out there?

**Comment by texastoland** [comment]
There's a note on _Extending Records_ in the _Language Guide_ that it'd be worth adding to!

**Comment by afcondon** [comment]
Seems like a good place to add it - which i would do now except i can't get Gary's example above to compile:
`Could not match kind
    *
  with kind
    # u19 -> u18
while checking the kind of Foo (Bar (Baz ()))`
What am i missing here? (took out the extra closing parens, and tried a few syntactic variations but no joy so far)

**Comment by garyb** [comment]
I should probably have tried compiling it first. This works:

``` purescript
data Foo
data Bar
data Baz
type FooBarBaz = FooR (BarR (BazR ()))
type FooBarBazRecord = Record FooBarBaz
type FooR r = ( foo :: Foo | r )
type BarR r = ( bar :: Bar | r )
type BazR r = ( baz :: Baz | r )
```

**Comment by garyb** [comment]
Although actually, if I was going to use something like the above "for real", I'd probably skip having both record and row versions of `FooBarBaz` and go straight to:

```
type FooBarBaz = Record (FooR (BarR (BazR ())))
```

**Comment by afcondon** [comment]
Super!  i'm going to play with this right now in a program where i'm progressively enriching records in a Tree structure.

thanks!

**Comment by texastoland** [comment]
I'm using it to aggregate pieces of analytics data before sending over the wire. My convention so far has been `*E` for effect rows, `*R` for record rows, and `*Obj` for records when needed, saving there unembellished named for `newtypes`. Aggregating effects this way visually evokes of how they get stacked by previous functions.
