### ISSUE TITLE
Missing warning for unused binding

### ISSUE THREAD

**Issue by oblitum** [purescript/purescript#2277]
Exercise 1 from Chapter 8 in PureScript by Example asks to write code that may be like the following:

```purescript
third :: forall a. Array a -> Maybe a
third xs = do
    xs' <- tail xs
    xs'' <- tail xs'
    head xs''
```
At first I've made a typo and wrote:
```purescript
third :: forall a. Array a -> Maybe a
third xs = do
    xs' <- tail xs
    xs'' <- tail xs
    head xs''
```
where `xs'` goes unused, but I noticed that I didn't get any warning for that.

**Comment by hdgarrood** [comment]
This looks like a duplicate of #1670.

**Comment by oblitum** [comment]
@hdgarrood ah thanks, I missed that while searching the issue tracker.

**Comment by hdgarrood** [comment]
No worries, thanks for the report anyway :)
