### ISSUE TITLE
Defer syntactic sugar

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2283]
I ~~invoke Wadler's law~~ propose syntactic sugar:
- `~x` becomes `defer \_ -> x`
- `!x` becomes `force x`

Additionally, the defer quasi-operator `~` can be used in patterns, where the generated code will call `force`:

```
f (Cons _ ~Nil) = 1
-- if (v instanceof Cons && force(v.value1) instanceof Nil) {
--     return 1;
-- };
```

Rebindable, just like `do`, so it can be used with various libraries such as purescript-lazy and purescript-eval.

I think such syntax will make lazy evaluation a more attractive option, and code that makes use of it more legible.

**Comment by paf31** [comment]
Why not a regular operator for force/function application?

```purescript
forcing :: forall a b. (a -> b) -> Lazy a -> b
forcing f a = f (force a)

infixl 4 forcing as $!
```

**Comment by rightfold** [comment]
I think `infixr 0` would chain more nicely with `$`.

**Comment by rightfold** [comment]
The tilde (`~`) is problematic because it is already usable as an infix operator. `f ~(g x)` would thus be ambiguous. The only option I can think of is the semicolon (`;`).

**Comment by paf31** [comment]
I'd like to reserve semicolon for explicit indentation actually.

**Comment by garyb** [comment]
And I'd prefer to have neither of these things :laughing:

**Comment by natefaubion** [comment]
I don't know, I wouldn't mind _at the least_ sugar for `\_ ->exp` such as `\(exp)`.

**Comment by garyb** [comment]
That's a little different than sugar for `defer` / `force` specifically. I wouldn't mind something that made defining "thunk lambdas" even simpler, but I'm not too offended by the current syntax either.

**Comment by paf31** [comment]
I think it's possible to go overboard with syntactic sugar, and with `$!` possible as an operator, I don't know think we need anything special in the compiler.

**Comment by garyb** [comment]
That's my feeling too, and to alleviate the pattern match issues you define a catamorphism style fold that will force the patterns.

**Comment by natefaubion** [comment]
```purescript
foo = do
  when bar \do
    this
    then that
  and then that
```

Would be nice and alleviate much of the surprise around `when`, etc as is.

**Comment by LiamGoodacre** [comment]
Somewhat related experiment that I'll be turning into a library at some point: https://github.com/LiamGoodacre/purescript-procrastination

**Comment by paf31** [comment]
I think this is quite similar in spirit to Evaluation order polymorphism (#1445), so I'm going to close this as a duplicate.
