### ISSUE TITLE
Install on node 6.2 appears to fail

### ISSUE THREAD

**Issue by Cloven** [purescript/purescript#2285]
I tried following the basic directions in http://www.purescript.org/learn/getting-started/.  

Installing node on alpine linux gave me 6.2.0.

The first failure echoed the ELIFECYCLE issue seen in  https://github.com/purescript/purescript/issues/2075 -- I tried 'npm install purescript bower pulp' and it failed.  I then tried to follow the remediation instructions in 2075 and tried 'npm install -g purescript@next', but it complained that 'next' wasn't a valid tag, and offered me some other choices.  I chose 'purescript@0.6.11' as being the closest thing to 6.2.0, and it died as follows:

/usr/bin/psc-bundle -> /usr/lib/node_modules/purescript/bin/psc-bundle.js
/usr/bin/psc-publish -> /usr/lib/node_modules/purescript/bin/psc-publish.js
npm ERR! Linux 4.4.17-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "purescript@0.6.11"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/lib/node_modules/purescript/bin/psc.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/purescript/bin/psc.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/purescript/bin/psc.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
The command '/bin/sh -c npm install -g purescript@0.6.11' returned a non-zero code: 254

npm-debug.log is very large but I can include if it'd be helpful.

I could try to install an earlier node but it might require building it from source on this platform, which would be somewhat challenging.

**Comment by paf31** [comment]
I'm not sure why this would happen, but you're probably better off filing an issue on the `node-purescript-bin` repo, or compiling from source.

**Comment by garyb** [comment]
Odd that it suggested 0.6.x, that's over a year out of date now. 

The `next` branch was temporarily a fix for PureScript 0.8.5 to install on node6, the `node-purescript-bin` package has since been updated and there have been several releases - all the 0.9.x releases should work on node6, as that's what Travis has been running for a while, and I use it on Windows and OSX too.

Perhaps the [provided binaries](https://github.com/purescript/purescript/releases/tag/v0.9.3) are not suitable for alpine linux and it's trying to build from source? If so, you'll need [`stack`](https://www.haskellstack.org) installed.

**Comment by paf31** [comment]
Doesn't the NPM package build from source if the binaries don't work?

**Comment by garyb** [comment]
Yeah, that was what I was saying above - it will need `stack` to be installed for it to be able to build them.

**Comment by paf31** [comment]
Do you think it's possible for the Node bundle to install Stack itself?

**Comment by hdgarrood** [comment]
I wouldn't want the npm package to install Stack in the sense of placing the `stack` executable somewhere on the user's PATH, but I don't see any issue with fetching it, putting it in a temporary location while it installs purescript, and deleting it when it's done. See also the Windows CI script, which does something similar to what I'm describing: https://github.com/purescript/purescript/blob/2e715758866ea45fdac65a9558d04a48ea967994/appveyor.yml#L15-L21

**Comment by paf31** [comment]
Closing. There is a possible issue here, but it should be reported on `node-purescript-bin`. Please also see the instructions in `INSTALL.md` if the NPM package doesn't work for you.
