### ISSUE TITLE
Allow λ as alternative to \ for lambdas?

### ISSUE THREAD

**Issue by oblitum** [purescript/purescript#2289]
I realize that the λ Unicode character currently seems to be available as an identifier, still, I'd like to ask about its use as a lambda initiator too. I use Vim and I had even seen in the past some concealing syntax plugins for Haskell that does that (conceal \ with λ), so I think it shouldn't be so alien to request that.

**Comment by oblitum** [comment]
Well, just found this... https://ghc.haskell.org/trac/ghc/ticket/1102.

**Comment by paf31** [comment]
I'd rather leave lower-case lambda as an identifier, personally.

**Comment by oblitum** [comment]
To tell the truth, the change I wished would still leave it as an identifier, too. It would be a contextual change where λ as a lambda initiator would be so solely in the lambda grammar, elsewhere it could still be valid identifier. So, possibly, `λλ → λ` would still work, the first one being the initiator, the others identifiers. Personally I'd really wish that but, I guess this seems a bit of effort to get supported, so I'll close it. I found it interesting though that it was considered on GHC as well.
