### ISSUE TITLE
`apply` and `applyFlipped` are no longer inlined

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#2298]
I'm pretty sure `$` and `#` both used to be inlined to a standard function call when saturated, but this is no longer the case.

**Comment by garyb** [comment]
Yeah, definitely a bug. The cases for this are still present in the inlining, but they're not firing. I'm pretty sure I know why though, having looked at the code.

**Comment by andyarvanitis** [comment]
In `.../JS/Optimizer/Inliner.hs`, you have:

````Haskell
inlineOperator :: (String, String) -> (JS -> JS -> JS) -> JS -> JS
inlineOperator (m, op) f = everywhereOnJS convert
  where
  convert :: JS -> JS
  convert (JSApp _ (JSApp _ op' [x]) [y]) | isOp op' = f x y
  convert other = other
  isOp (JSIndexer _ (JSStringLiteral _ op') (JSVar _ m')) = m == m' && op == op'
  isOp _ = False
````

You're still matching for the old `JSIndexer` constructor for the operator, instead of the function name now used.

**Comment by garyb** [comment]
Yeah, that's what I meant when I said I was pretty sure I knew why it wasn't working :smile:

**Comment by andyarvanitis** [comment]
Figured as much 🙂. Since I had already fixed it in the C++ backend a while back, thought I'd post the info here in case someone else wanted to fix it (very low-hanging fruit).

**Comment by garyb** [comment]
Ah right, cool! I'll open a PR for tonight, I've just been spending my PS-time on fooling with the fundeps stuff today so far.
