### ISSUE TITLE
Multi-line `let`s in `do` blocks fail to parse

### ISSUE THREAD

**Issue by joshuahhh** [purescript/purescript#2301]
# Problem

`let` inside of a `do` block often fails to parse if the binding stretches over multiple lines. For instance:
```
do
  let x = (
    1 + 1
  )
  ...
```
results in
```
  Unable to parse module:
  unexpected +
  expecting expression
```

(Meanwhile, `let` outside of a `do` block does just fine. Even
```
let
  x =
    1
    +
    1
in
  ..
```
parses.)

Is this the expected behavior? Thanks for any help!

# P.S.

I just discovered that _double_ indentation of the RHS sometimes helps... For instance,
```
do
  let x = (
      1 +
      1
  )
  ...
```
will parse. But
```
do
  let x = (
      1
      + 1
  )
  ...
```
is still broken, as is
```
do
  let x =
      1 + 1
  ...
```
I find this all quite perplexing! 😛

**Comment by paf31** [comment]
The current rule is that the body of a let must be indented past the identifier, so yes, this is expected right now, but it could probably be improved.

**Comment by joshuahhh** [comment]
Oh I see! That actually sounds like a fine rule to me. Thanks a bunch.

(My only remaining concern is that I wasn't able to discover this rule myself. It would be great if error reporting could explicitly reference the rule, though that's easier said than done...)

**Comment by paf31** [comment]
Closing, since this is behaving as expected, although I agree we could probably document this better. Maybe it can be documented on the wiki.
