### ISSUE TITLE
Special syntax for unsigned literals

### ISSUE THREAD

**Issue by jacereda** [purescript/purescript#2306]
I would like to use raw bit patterns to specify Int numbers, but the compiler refuses anything above 0x7fffffff as a valid Int. Could the compiler parse something like "0xffffffffU" as an Int?

**Comment by garyb** [comment]
I don't think we can support that, the `Int` type is restricted to being an Int32. We're stuck with that as otherwise the JS bitwise operations would misbehave or truncate.

There are alternative types that can represent `0xFFFFFFFF`: [purescript-bigints](https://pursuit.purescript.org/packages/purescript-bigints), [purescript-hugenums](https://pursuit.purescript.org/packages/purescript-hugenums), [purescript-int-53](https://pursuit.purescript.org/packages/purescript-int-53), but we don't have literal overloading so it doesn't help with the syntax issue unfortunately.

**Comment by jacereda** [comment]
The fact that it ends up being an `Int` isn't a problem. It would be just an alternate syntax for entering an `Int`. It can be useful with things like `Data.Int.Bits`. Or for things like my concrete use case now, where I want to be able to specify a 64-bit DES key with something like:

```
data Word64 = Word64 Int Int
...
  let key = Word64 0xdeadbeef 0xabadcafe
```

There are ugly solutions, like manually finding the negative number corresponding to each of those literals, or use something like `fromString "deadbeefabadcafe"`. I just thought a special syntax was cleaner.

**Comment by hdgarrood** [comment]
So essentially you want to use `Int` as a 32 bit unsigned integer type?

I don't think we should build in any language support for this, as I think such a type really ought to be distinct from `Int`. For example, you'll want instances to be different — Show, of course, but also I think division would have to be treated differently too. Imagine `1 / (-1)` vs `1 / (2^32-1)`.

**Comment by jacereda** [comment]
No, I just want to specify an `Int` with a bit pattern.

**Comment by jacereda** [comment]
Maybe I'm missing something. How would you specify a mask such as 0xcccccccc for use with `Data.Int.Bits`?

**Comment by hdgarrood** [comment]
Oh ok, fair enough. I guess I'd do `parseInt("deadbeef", 16)` (can't remember exactly how to do that in PS right now).

For integers between 2^31-1 and 2^32-1, i guess it could make sense to allow hex literals to come out as negative integers, but I don't think we should allow literals written in base 10 to do the same, as that seems like it could lead to nasty surprises.

**Comment by michaelficarra** [comment]
I'm opposed to any literals wrapping around like this. It's very surprising behaviour. Nothing is stopping you from doing the overflow/wrapping maths yourself and writing that number in your program. :-1:

**Comment by hdgarrood** [comment]
I'm tempted to agree with @michaelficarra on this. Given this, and the fact that there doesn't seem to be much of an appetite for it, judging by the lack of responses on this issue, I think this should be closed.
