### ISSUE TITLE
Remove duplicate rows restriction

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2311]
Extracted from #1719.

**Comment by LiamGoodacre** [comment]
Could you add a description of what this means, what it enables, etc?

**Comment by garyb** [comment]
I don't think we can do it "safely" without row constraints (or a "lacks label" constraint at the least).

It would mean for one thing we don't have the current situation where you have to replicate the exact same `eff` row everywhere, as it wouldn't matter if, say, `dom` arrives in an `eff` from multiple rows being unified.

**Comment by paf31** [comment]
Why do you think we need lacks constraints?

**Comment by paf31** [comment]
To give an example, suppose we wanted to write a function to extend a record with a `foo` label, then we might need a lacks constraint:

```purescript
addFoo :: forall r. Lacks "foo" r => Record r -> Record (foo :: Foo | r)
```

But I think this is fine:

```purescript
addFoo :: forall r. Record r -> Record (foo :: Foo | r)
```

If we have duplicate labels, then passing a record which already contains `foo` will just result in a duplicate `foo` label. That's fine as long as the types are ordered for each label, and as long as we don't expect deletion to work. 

You wouldn't be able to write this, for example:

```purescript
removeFoo :: forall r. Record (foo :: Foo | r) -> Record r
```

without a lacks constraint on `r`, because the argument might have two types for the `foo` label, but we have to remove all of them if we want to use regular JS objects as the representation.

Similarly, ordered rows with duplicate labels let us write things like 

```purescript
try :: forall e a. Eff (exception :: EXCEPTION | e) e -> Eff e (Either Error a)
```

without worrying about whether `e` lacks `EXCEPTION` or not.

**Comment by garyb** [comment]
Yeah, if we don't mind that `addFoo` can "overwrite" a `foo` in `r` if it already existed then the constraint doesn't matter. I thought that was part of the reason duplicate rows were disallowed in the first place. :)

**Comment by paf31** [comment]
I think that's probably okay, as long as we document that the meaning of `Record ⍴` only takes into account the first element for each label in `⍴`.
