### ISSUE TITLE
Add `Newtype` class deriving

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2314]
@paf31 any objections to this? I can do the work of making the instance derivable, etc.

**Comment by paf31** [comment]
I don't see why not 😄 

One thing I'd like to support here is the inference of types under functional dependencies, so that we can write things like:

```purescript
deriving instance newtypeFirst :: Newtype (First a) _ 
```

and have the `_` inferred as `Maybe a`. We'd also need that if we wanted to switch over to using GHC-style generics using fundeps.

**Comment by paf31** [comment]
There are a couple of other libraries I'd like to move to core, actually. We should discuss that, and also issues generally, at some point soon.
