### ISSUE TITLE
Sort when adding an explicit import with psc-ide

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2323]
Right now we just add the new identifier to the beginning of the import list. This creates unnecessary noise in git diffs.

Preferably we'd not only sort alphabetically but also sort categorically so that datatype imports or class imports are grouped together.

**Comment by garyb** [comment]
We have sorting like that in the suggestions, so should use the same ordering here I guess :)

**Comment by kRITZCREEK** [comment]
That's a good hint. I'll try to find it

**Comment by garyb** [comment]
It's probably just whatever comes out thanks to the `DeclarationRef` `Ord` instance.

**Comment by nwolverson** [comment]
I think the change for this is now merged?

**Comment by kRITZCREEK** [comment]
Thanks!
