### ISSUE TITLE
Typed holes in declarations

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/purescript#2333]
Having typed holes in declarations would be a nice convenience, ie:

```purescript
let ?foo = ...
```

or in do notation,

```purescript
?foo <- ...
```

which is easier than coercing the type with `:: ...` and which also provides the context as well

**Comment by garyb** [comment]
I'm not really sure what those mean, unless it's an equivalent to a `let x = ?foo $ ...` / `x <- ?foo <$> ...` kinda thing? In which case I think it's fine as it is personally, as it seems easy enough already.

**Comment by arthur-xavier** [comment]
I guess that, for the first case, you could use:
```purescript
let x :: _
    x = ...
```
For the one in do notation I have no clue about how it could be done :/

**Comment by Risto-Stevcev** [comment]
@garyb Yep, that's the one, I just didn't think of doing that. I agree that's easy enough, so I'll close this ticket
@arthur-xavier I was doing that initially but it wouldn't provide the rest of the context which I didn't like

**Comment by garyb** [comment]
Ah cool :)

Yeah I tend to use the "apply value to hole" technique quite a lot, when I'm too lazy to figure out exactly what type something has, or if I have a function I want to check the type of without using Pursuit, etc.
