### ISSUE TITLE
Single consolidated executable

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2336]
This is something I'd like to do before 1.0:

``` text
> psc build 'src/**/*.purs'
> psc bundle 'output/*/*.js'
> psc docs
> psc publish
> psc repl
> psc ide
```

etc.

It should also reduce the size of the binary distribution a bit.

**Comment by kRITZCREEK** [comment]
I was hoping we could move the executables into their own package. With stack it seems easy to keep them in the same repo and manage them together. The benefit I'm hoping for would be to reduce build times when working on PS "the library".

**Comment by paf31** [comment]
> The benefit I'm hoping for would be to reduce build times when working on PS "the library".

I think reducing down to one executable would also help there though.

**Comment by rvion** [comment]
> I was hoping we could move the executables into their own package.

This is a bit less pleasant to work with than having only one executable in the same package IMO
I personally really prefer having one large executable, with a clean and good module hierarchy so build times are acceptable

**Comment by kRITZCREEK** [comment]
> I think reducing down to one executable would also help there though.

And I'm totally :+1: there. Would also be a nice opportunity to combine psc-ide-server and client into `psc ide` and `psc ide --client`.

**Comment by hdgarrood** [comment]
Should we do this in 0.11?

**Comment by paf31** [comment]
I think that would be good. I'll make a milestone so we can make a list of things to concentrate on.

We should come up with a migration plan though. We can't have all existing blog posts etc. immediately being invalidated 😄 It could be as simple as providing small wrapper executables for now.
