### ISSUE TITLE
Do notation should use tailRecM for monadic tail recursion

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2340]
It might be nice if we inserted a call to `tailRecM` whenever we see monadic tail recursion in a `do` notation block.

**Comment by natefaubion** [comment]
There are cases where this isn't necessary, like with `Free`, or some Monad that's already trampolined. `tailRecM` can add non-trivial overhead in that case.

**Comment by paf31** [comment]
Hmm, good point. I was thinking about things like `StateT` in QuickCheck, where it's necessary and irritating to use `tailRecM` directly.

**Comment by garyb** [comment]
`dorec`?

**Comment by paf31** [comment]
That's not a bad idea.
