### ISSUE TITLE
Type class based desugaring

### ISSUE THREAD

**Issue by starper** [purescript/purescript#2342]
I've been thinking about this feature for a long time and since [2340](https://github.com/purescript/purescript/issues/2340) came up, I finally decided to open an issue. It started with `tailRecM` too, but then I took it a little farther. The general idea is to use type classes for desugaring.

Let's say that you have some kind of syntactic sugar, now if you want to use it with some type, then this type should be an instance of some type class, so that compiler could desugar it. We already use this approach with `Monad` and `do` (and with `Arrow` and `proc` in Haskell), so I don't see why we can't use it for other kinds of desugaring.

`tailRecM` and `dorec` is good example. Another good example is to use this approach to desugar `[]`. Both `Array` and `List` could be instances of some `ArrayLike` class and we could use `[]` to construct both of them. And then compiler will desugar it to something like `alCons 1 (alCons 2 (alCons 3 alNil))`.

I also think that if all syntactic sugar was made using this approach there could be a lot of benefits. I will use `Array` and `List` as an example.

- First of all it would feel more structured and less "magical". For example what's so special about `Array` other then it is `JS` built-in type and why I can't use `[]` with `List`?

- It would make refactoring easier. If for some reason you want to switch from `List` to `Array`, just replace `List` with `Array` in type annotation and you are done.

- Using syntactic sugar is usually a more pleasant experience (if it's not abused). It is less noisy and reduces amount of code you have to write (`do` notation is great example of it). And it hides some implementation details (like whether some type is `JS` built-in type or it's not).

- Desugaring can be performed in different ways. For example since compiler could still be aware that `Array` is `JS` built-in type, it could desugar it not as `alCons 1 (alCons 2 (alCons 3 alNil))` but as `[1,2,3]` (possibly with `--js-array` flag). Maybe some other kind of optimisation can be performed. But as for me the most interesting example is to desugar (with some flag) making everything that is an instance of `Lazy` type class lazy.

- It would be easier to add new kind of syntactic sugar, since all you have to do is to teach compiler how to desugar it using type classes, everything else is up to users.

- And the last one. If you don't want to use it, just don't use it :) As a user you actually won't lose anything and won't have to change your code. You can still use `List`'s `Cons` directly if you want to. So as far as I can see it's not a breaking change.

What do you think about this idea?

**Comment by paf31** [comment]
We already use this approach for a few things:

- `bind`
- `negate`
- `eval` in PSCi

I would like something like `IsArray`/`IsList` as a possible replacement for some of the functions which use `Unfoldable` and `Foldable` right now. That could potentially be used for array literal overloading.

I think it's possible to do too much here though. We should be careful not to add too much overloading since it can lead to performance and type-inference issues.

Let's identify which sorts of overloading we'd like to support and then break this up into separate issues. So far the candidates seem to be

- `tailRecM` as part of `dorec`
- `IsList`/`Consable` etc. (I'd like to think about this one some more)
- Other overloaded literals
- `Arrow` functions via `proc` (I'd like to leave this until after 1.0)

Anything else?

**Comment by starper** [comment]
I know that it has already been discussed thousand times, but I'll ask one last time :) What do you think about `IsTuple` type class and `(,)` syntactic sugar for it? Or even better `{,}` (to show that it is an object that just have no meaningful keys). Do you still think that it is redundant?

**Comment by paf31** [comment]
I'd like to avoid any special syntactic sugar for `Tuple`. We already have data constructor operators, so we can use `/\` or something else to construct a tuple. If you wanted, you could even alias `Tuple` as some unreserved punctuation character, and get even closer to Haskell.

**Comment by paf31** [comment]
This should be broken into separate issues, so I'm going to close it.
