### ISSUE TITLE
[psc-ide] Find usages

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2351]
Ideally this would find both occurences of types aswell as values, but since the AST does not hold position information for types yet this will have to wait a bit.

**Comment by sudhirvkumar** [comment]
@kRITZCREEK any plans for this? usages will help in refactoring across files easily.

**Comment by kRITZCREEK** [comment]
@sudhirvkumar We don't have position information for types in the AST yet, so that's one blocker. Two other prerequisits that need to be met before tackling this are:

1. Sourcefiles need to be reloaded when they change like externsfiles. We need to do this in a way that scales to projects with > 1000 source files, so installing a filewatcher for every file is probably not an option.

2. We need a pass in the Renamer that works on the non-desugared AST so that we can take the shadowing rules of the compiler into account.

When these are done, we can look at implementing the find usages command with an AST Traversal.

**Comment by sudhirvkumar** [comment]
@kRITZCREEK I am neck deep in projects right now... may be in a month or so... I will make sure I have time allocated to work on tasks in PureScript and start sending PRs.

Thanks for the clear explanation! Awesome!

**Comment by kRITZCREEK** [comment]
Implemented for all declarations at the value level in #3206. I've opened a follow-up issue for types at #3228.
