### ISSUE TITLE
Type-driven record wildcard packing/unpacking

### ISSUE THREAD

**Issue by sleexyz** [purescript/purescript#2360]
i.e. [Haskell-style record wildcards](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#record-wildcards) for Purescript

Purescript's structurally typed records seem to amenable to Haskell-style `RecordWildcards` as long as the semantics of packing/unpacking is _type-driven_.

What we get for free is `open` for approximating ML modules with records

| ML | Purescript |
| --- | --- |
| signature | open record type |
| structure | record term |
| abstract type | type parameter |
| functor | function from open record to closed record |
| `open Foo` | `{..} = (foo :: Foo)` |
| N/A | `foo = ({..} :: Foo)` |
| first class modules | existentially typed records |
## Packing binders into records:

The semantics of `{..}` to pack binders into a record should be driven by the type of the record.
#### Example:

``` purescript
module Algebraic where

type Semigroup a rest = Record ( append :: a -> a -> a | rest )
type Monoid a rest = Semigroup ( zero :: a | rest )
```

``` purescript
additiveMonoid' :: Monoid Number ()
additiveMonoid' = {..} -- additiveMonoid = {zero, append}
  where
    zero = 0.0
    append = (+)
```
#### Note

The type of our record determines what binders are packed in the record. So if we had omitted the type annotation for `additiveMonoid'`, the semantics of `{..}` would be ambiguous and our program should fail to compile:

```
-- Error: The use of {..} is ambiguous! What binders do I pack??
additiveMonoid' = {..}
  where
    zero = 0.0
    append = (+)
```
### Packing binders into open records(?):

AFAIK the only way to introduce open records is by eliminating another one via a _record update_ .

Use case: Structure-polymorphic ML "endo"-functors?

``` purescript
cayleyRep :: forall a rest. Monoid a rest -> Monoid (a -> a) rest
cayleyRep r = r {...} -- cayleyRep r = r {zero=zero, add=add}
  where
    zero = case r of
      {zero, add} -> add zero
    add = (<<<)
```

Note that Haskell doesn't support wildcard record updates. I'm not sure if this is a super-useful feature.
## Unpacking records:

We should unpack both open and closed records by pattern matching with `{..}`
### Unpacking closed records into binders:

``` purescript

foo :: forall a. Monoid a () -> a
foo {..} = append zero zero -- foo {append, zero} = append zero zero
```
### Unpacking open records into binders:

``` purescript
foo :: forall a rest. Monoid a rest -> a
foo {..} = append zero zero -- foo {append, zero} = append zero zero
```
#### note:

Again, our program should fail to compile if the type of our record is ambiguous:

```
-- Error: The use of {..} is ambiguous! What binders do I unpack??
foo {..} = append zero zero
```

**Comment by paf31** [comment]
I would be interested to see this rephrased in terms of row constraints.

```purescript
additiveMonoid' = {..}
  where
    zero = 0.0
    append = (+)
```

It seems to me like the inferred type of this could be

```purescript
additiveMonoid' :: forall r r'. (r | r' ~ ( append :: ..., zero :: ... )) => Record r
```

i.e. any record whose row of fields is a subset of `append` and `zero` (where this set is determined by what is in scope, which might be a _lot_ - this is problem one).

However (problem two), what would the implementation of `additiveMonoid'` do? Would it just pack up everything in scope? Or would it use some sort of evidence passed around by the row constraint? In the latter case, it's not obvious what the evidence would be, and in the first case, there is an efficiency issue.

**Comment by sleexyz** [comment]
I think driving type inference with scope is finicky.

```purescript
foo = 1.0

bar = 1.0

additiveMonoid' = asdf
  where
    asdf = {..}
    zero = 0.0
    append = (+)
```
What does asdf package into the record? `zero`, `append`, but what about `foo`,`bar`, `additiveMonoid` itself, `asdf` itself?

I would rather require the semantics of `{..}` to be type-driven, instead of driving type judgments.

**Comment by paf31** [comment]
> I think driving type inference with scope is finicky

> I would rather require the semantics of {..} to be type-driven, instead of driving type judgments.

I agree, and you're probably right that type-driven `{..}` makes more sense, but I don't really want to add type-driven features which are not implementable in the constraint solver, and that's why I'd rather avoid `{..}` entirely.

**Comment by sleexyz** [comment]
For packing wildcards, I can imagine a typeclass with an associated type of a constraint composed of implict parameters:

In semi-psuedo haskell:
``` haskell
type Monoid a rest = { zero :: a, add :: a -> a -> a | rest }

class IsRecord  r where
  type HasFields r :: Constraint
  {..} :: HasFields r =>   r

instance IsRecord (Monoid a rest) where
  type HasFields (Monoid a rest) = (?zero :: a, ?append :: a -> a -> a)
  {..} = ... -- compiler magic
```

Possible complications:
- Can we constrain type synonyms in purescript?
- Implicit params in purescript?

If we use constraints on rows instead of record type synonyms, what happens to type variables?

**Comment by paf31** [comment]
We've already decided not to allow instances on record types, or rows in general.

**Comment by paf31** [comment]
Closing for now, due to lack of discussion, and because of the reasons above.
