### ISSUE TITLE
Compiler infers wrong constraints for inline annotations

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2362]
In `psci`:

```purescript
import Prelude
f = (\x -> show (x + x)) :: forall a. a -> String
```
compiles just fine and infers the following type for `f`:
```
(Show a0, Semiring a0) => (forall a. a -> String)
```

However with a standalone type declaration like so:
```purescript
import Prelude
f  :: forall a. a -> String
f = (\x -> show (x + x))
```

`psc` correctly fails with:

```
 No type class instance was found for

    Data.Show.Show a0
```

**Comment by garyb** [comment]
I'm not sure this is incorrect so much as it's just surprising. An inline annotation (even if it's for the whole expression) is subject to constraint generalisation for the declaration, whereas a typed declaration is only checked.

Will what Phil says anyway :)

**Comment by paf31** [comment]
I think there are two possible issues here:

- We shouldn't generalize over the skolem type `a0`
- An expression with a type annotation at the top level should act like it has a type declaration, so we need to change the check for `shouldGeneralize` to take that into account.
