### ISSUE TITLE
Update core libraries for 0.10

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2372]
PRs open / in progress:
- [x] [purescript-const](https://www.github.com/purescript/purescript-const)
- [x] [purescript-strings](https://www.github.com/purescript/purescript-strings)
- [x] [purescript-orders](https://www.github.com/purescript/purescript-orders)
- [x] [purescript-arrays](https://www.github.com/purescript/purescript-arrays)
- [x] [purescript-generics](https://www.github.com/purescript/purescript-generics)
- [x] [purescript-lists](https://www.github.com/purescript/purescript-lists)
- [x] [purescript-enums](https://www.github.com/purescript/purescript-enums)
- [x] [purescript-functor-coproducts](https://www.github.com/purescript/purescript-functor-coproducts)
- [x] [purescript-functor-products](https://www.github.com/purescript/purescript-functor-products)
- [x] [purescript-profunctor](https://www.github.com/purescript/purescript-profunctor)
- [x] [purescript-semirings](https://www.github.com/purescript/purescript-semirings)
- [x] [purescript-catenable-lists](https://www.github.com/purescript/purescript-catenable-lists)
- [x] [purescript-transformers](https://www.github.com/purescript/purescript-transformers)
- [x] [purescript-inject](https://www.github.com/purescript/purescript-inject)
- [x] [purescript-quickcheck](https://www.github.com/purescript/purescript-quickcheck)
- [x] [purescript-foreign](https://www.github.com/purescript/purescript-foreign)
- [x] [purescript-free](https://www.github.com/purescript/purescript-free)
- [x] [purescript-datetime](https://www.github.com/purescript/purescript-datetime)
- [x] [purescript-maps](https://www.github.com/purescript/purescript-maps)
- [x] [purescript-sets](https://www.github.com/purescript/purescript-sets)
- [x] [purescript-generics-rep](https://www.github.com/purescript/purescript-generics-rep)
- [x] [purescript-parallel](https://www.github.com/purescript/purescript-parallel)

The rest (toposorted):
- [x] [purescript-graphs](https://www.github.com/purescript/purescript-graphs)

The toposort isn't "strict" in that some things further down the list might be doable now, but at least if we proceed down that order we shouldn't run into any problems.

**Comment by paf31** [comment]
Just a note that once these are done, I need to remember to:

- [ ] Update Try PureScript
- [ ] Create a `psc-package` package set for testing
- [ ] Write a blog post about the features in 0.10

**Comment by paf31** [comment]
@garyb I'm trying to keep [this package set](https://github.com/paf31/purescript-package-db/pull/12) up to date as well, so hopefully we should be able to start using `psc-package` shortly after all of the updates are complete.
