### ISSUE TITLE
Add error message for ambiguous type variables in inferred contexts

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2374]
Right now we reuse `NoInstanceFound` for this, but it would be better if we indicated that we found an instance but didn't use it because it involved ambiguous type variables.

**Comment by joneshf** [comment]
Can this be closed? Seems like https://github.com/purescript/purescript/pull/2410 and https://github.com/purescript/purescript/pull/2428 addressed this enhancement.

**Comment by paf31** [comment]
Yes, thanks.
