### ISSUE TITLE
Allow rows in instance heads, under functional dependencies

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2376]
`Newtype` instances can't be derived for newtypes around records, but we can derive instances which use `TypeEquals` in the context (see `RowsInInstanceContexts.purs` in `examples`).

**Comment by paf31** [comment]
I think there is a better alternative here actually. We should allow rows in instance heads if they appear in a type argument which can be solved by a functional dependency. That way, we still avoid having different instances for different record fields, at least so long as some other type argument differs.

**Comment by LiamGoodacre** [comment]
I'm having a go at this (pretty much done I think).
