### ISSUE TITLE
Error "Invalid type in instance in checkOrphanInstance"

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2378]
I get this error when instances include type-level strings.

**Comment by joneshf** [comment]
It seems like adding another case might do the trick.

```purescript
checkType (TypeLevelString _) = False
```

It seems like `False` is the right thing here since any instance not in the same module that uses a type level string would be an orphan. Is that right?

**Comment by paf31** [comment]
Yes, I think that's right.
