### ISSUE TITLE
Pure by Ex runV function

### ISSUE THREAD

**Issue by Tshimanga** [purescript/purescript#2395]
Playing with purescript by example, which is now grossly out of date, and just updating the modules as I go along. In chapter 7, It seems that Data.Validation was deprecated at some point in favor of a Semigroup and Semiring module, but now seemingly the last compiler error left is an unrecognized "runV" function that appears as following:

validatePerson :: Person -> V Errors Person
validatePerson (Person o) =
  person <$> (nonEmpty "First Name" o.firstName *> pure o.firstName)
         <*> (nonEmpty "Last Name"  o.lastName  *> pure o.lastName)
         <*> validateAddress o.address
         <*> (arrayNonEmpty "Phone Numbers" o.phones *> traverse validatePhoneNumber o.phones)

validatePerson' :: Person -> Either Errors Person
validatePerson' p = **runV** Left Right $ validatePerson p

I imagine it is a relic of the old Validation module that wasn't rewritten into either Semiring or Semigroup. Is there a replacement function somewhere or is this implementation of this example broken?

**Comment by paf31** [comment]
> which is now grossly out of date

The book works with 0.9.3, which is one release behind the compiler. The book will be updated for 0.10.1 once all libraries are updated and when I have time to do the work. If you use 0.9.3 with the `purescript-book` repo, you should get the right library versions, and everything should work fine.

In future, please report book issues on the book repo. Thanks.

**Comment by Tshimanga** [comment]
Awesome! Thanks Phil!

**Comment by garyb** [comment]
The function is called `unV` now, by the way.
