### ISSUE TITLE
Performance regression since 0.10.1

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2398]
@paf31 you mentioned something about noticing this on IRC I think - in how long the tests take to run. I just updated to `master` and when running verify-package-sets it's noticeably slower than with 0.10.1, so it was introduced since then apparently. Or made worse.

**Comment by paf31** [comment]
How much slower is it? `verify-package-sets` should only build what's changed, but finding out what has changed could be taking some time, perhaps. I can't think of anything recently merged into `master` which would cause any additional slowdown. I was just referring to a perceived slowdown over the last few minor releases.

**Comment by paf31** [comment]
Also, I'm not sure if this is clear, but `verify-package-sets` builds each package independently, so performance is not linear in the total number of modules in the package set. It does this to make sure that any subset of the package set will build in isolation.

**Comment by paf31** [comment]
Here is a profile which I just generated:

```text
        Sat Jan 14 21:53 2017 Time and Allocation Profiling Report  (Final)

           psc +RTS -N -p -RTS --json-errors -o ./output bower_components/purescript-*/src/**/*.purs src/**/*.purs

        total time  =       28.23 secs   (28228 ticks @ 1000 us, 1 processor)
        total alloc = 33,098,362,152 bytes  (excludes profiling overheads)

COST CENTRE                            MODULE                                     %time %alloc

>>=.\.\                                Control.Monad.Logger                         6.2    1.7
>>=                                    Control.Monad.Supply                         6.0    8.0
return                                 Language.PureScript.Make                     5.3    6.3
>>=.\                                  Control.Monad.Logger                         3.8    0.0
makeIO                                 Language.PureScript.Make                     3.2    0.6
>>=                                    Language.PureScript.Make                     3.1    4.6
parseToken                             Language.PureScript.Parser.Lexer             2.8    9.9
fmap.\                                 Control.Monad.Logger                         2.6    3.5
everywhereOnJS.go                      Language.PureScript.CodeGen.JS.AST           2.1    5.5
==                                     Language.PureScript.Names                    2.1    0.0
compare                                Language.PureScript.Names                    2.0    0.0
>>                                     Control.Monad.Supply                         1.8    2.6
warnDuplicateRefs.dupeRefs             Language.PureScript.Sugar.Names.Common       1.8    2.6
return                                 Control.Monad.Supply                         1.5    1.3
everywhereOnTypesM.go                  Language.PureScript.Types                    1.4    1.6
resolveExports.extract.go              Language.PureScript.Sugar.Names.Exports      1.3    2.3
withErrorMessageHint                   Language.PureScript.TypeChecker.Monad        1.1    0.8
fmap                                   Control.Monad.Supply                         1.0    1.1
replaceTypeClassDictionaries.deferPass Language.PureScript.TypeChecker.Entailment   0.8    1.3
>>=                                    Control.Monad.Logger                         0.8    3.1
typesOf.\                              Language.PureScript.TypeChecker.Types        0.7    1.3
resolveExports.extract.go.\            Language.PureScript.Sugar.Names.Exports      0.6    1.2
prettyPrintJS'.matchValue              Language.PureScript.Pretty.JS                0.6    1.6
parseComment.lineComment               Language.PureScript.Parser.Lexer             0.4    1.8
```

I generated this with `stack build --profile` followed by `pulp build -- +RTS -p -RTS`.

It looks pretty good in general, but it does identify a few hotspots:

- `Control.Monad.Logger` and `Control.Monad.Supply` take the most CPU time. This might be okay, but maybe we can improve things a bit.
- It feels like `Language.PureScript.Make` should not be so high in the profile
- `everywhereOnJS.go` in `Language.PureScript.CodeGen.JS.AST` is an allocation hotspot. I think this is due to the way we repeatedly traverse the JS AST during the optimisation phase.
- `Language.PureScript.Parser.Lexer` is a big allocation hotspot. I know where the space leak is, and I plan to work on it soon.
- `Language.PureScript.Names` appears a few times, but we already know there are some possibly less-than-optimal uses of `Eq` there. I think there is an open issue for that already.

**Comment by kRITZCREEK** [comment]
The less than-optimal uses of Eq might be related to usage of `nub` O(n²) over `ordNub` O(n * log n). For expensive comparisons like strings with lots of characters in common hashNub might be even better.

**Comment by hdgarrood** [comment]
I'm still a little confused about this - to determine two strings are different via Ord, you might indeed have to look at a fairly long prefix of each, but surely you are required to examine the entirety of both strings in every case if you're using Hashable?

**Comment by kRITZCREEK** [comment]
I think it's because with Hashing you get O(1) insertion instead of having to do (log n) comparisons per insertion.

**Comment by hdgarrood** [comment]
Ahh, right, yes, that makes sense. Thanks!

**Comment by garyb** [comment]
Here's a profile of SlamData:

```
	Sun Jan 15 14:53 2017 Time and Allocation Profiling Report  (Final)

	   psc +RTS -N -p -RTS --json-errors -o ./output bower_components\purescript-*\src/**/*.purs src/**/*.purs

	total time  =      341.79 secs   (341786 ticks @ 1000 us, 1 processor)
	total alloc = 360,106,036,672 bytes  (excludes profiling overheads)

COST CENTRE                 MODULE                                  %time %alloc

makeIO                      Language.PureScript.Make                  8.5    1.2
==                          Language.PureScript.Names                 7.7    0.0
>>=                         Control.Monad.Supply                      4.5    8.7
>>=.\.\                     Control.Monad.Logger                      4.5    1.7
return                      Language.PureScript.Make                  4.4    7.4
compare                     Language.PureScript.Names                 3.6    0.0
>>=.\                       Control.Monad.Logger                      3.4    0.0
warnDuplicateRefs.dupeRefs  Language.PureScript.Sugar.Names.Common    3.2    6.0
>>=                         Language.PureScript.Make                  2.9    5.4
checkExhaustive.step.(...)  Language.PureScript.Linter.Exhaustive     2.2    0.0
>>                          Control.Monad.Supply                      2.1    3.6
==                          Language.PureScript.AST.Binders           1.6    0.0
fmap.\                      Control.Monad.Logger                      1.5    2.5
resolveImport.updateImports Language.PureScript.Sugar.Names.Imports   1.4    2.4
resolveImport.importAll     Language.PureScript.Sugar.Names.Imports   1.3    2.6
resolveExports.extract.go   Language.PureScript.Sugar.Names.Exports   1.3    3.0
everywhereOnJS.go           Language.PureScript.CodeGen.JS.AST        1.2    3.4
resolveImport.importRef     Language.PureScript.Sugar.Names.Imports   1.1    2.4
return                      Control.Monad.Supply                      1.1    1.5
everywhereOnTypes.go        Language.PureScript.Types                 1.1    1.9
*>                          Control.Monad.Supply                      1.1    1.5
parseToken                  Language.PureScript.Parser.Lexer          1.0    4.5
everywhereOnTypesM.go       Language.PureScript.Types                 0.9    1.5
unifyTypes.unifyTypes'      Language.PureScript.TypeChecker.Unify     0.8    1.3
resolveExports.extract.go.\ Language.PureScript.Sugar.Names.Exports   0.8    1.6
>>=                         Control.Monad.Logger                      0.8    3.5
filterModule                Language.PureScript.Sugar.Names.Exports   0.4    1.1
makeBindingGroupVisible.\   Language.PureScript.TypeChecker.Monad     0.4    1.1
```

A bit more name/module stuff popping up, but since there are 1,149 modules involved it's not too surprising. As far as I can tell, these are the "new" entries compared to the Thermite profile:

```
checkExhaustive.step.(...)  Language.PureScript.Linter.Exhaustive     2.2    0.0
==                          Language.PureScript.AST.Binders           1.6    0.0
resolveImport.updateImports Language.PureScript.Sugar.Names.Imports   1.4    2.4
resolveImport.importAll     Language.PureScript.Sugar.Names.Imports   1.3    2.6
resolveImport.importRef     Language.PureScript.Sugar.Names.Imports   1.1    2.4
everywhereOnTypes.go        Language.PureScript.Types                 1.1    1.9
*>                          Control.Monad.Supply                      1.1    1.5
unifyTypes.unifyTypes'      Language.PureScript.TypeChecker.Unify     0.8    1.3
filterModule                Language.PureScript.Sugar.Names.Exports   0.4    1.1
makeBindingGroupVisible.\   Language.PureScript.TypeChecker.Monad     0.4    1.1
```

**Comment by paf31** [comment]
I tried a couple of things here, with little success:

- Switching to a strict state monad in `Control.Monad.Supply`
- Avoiding the allocation hotspot in the lexer by looping over lexemes explicitly

Many of the profiler hints point to places which don't seem to make much sense, like the ones in `Make`.

Some other things to try:

- Forcing the monoidal value in various places in `Control.Monad.Logger`
- Avoid repeated traversals in the optimizer

Since we're talking about a couple of percentage points here, I'd be fine with pushing this until after 1.0 if I can't make more progress on it soon.

**Comment by paf31** [comment]
> Avoid repeated traversals in the optimizer

I was able to get a ~1.6% speedup this way. I'll make a PR.

**Comment by paf31** [comment]
I've looked through each of the hotspots in the profile now, and I can't find any simple fixes to any of them. Performance seems acceptable to me right now, so I'm closing this, but if anyone has evidence of a new performance issue due to a compiler bug, we can create a new issue and put it into Approved.
