### ISSUE TITLE
Derived newtype instances can give wrong superclass through entailment

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#2399]
If you manually declare an `Apply` instance, and then `derive newtype` an `Applicative` instance, you can get the wrong instance through entailment. Because newtype deriving is just a dictionary coercion, it will give the "original" `Apply` if you ask for an `Applicative` rather than the declared instance.

**Comment by paf31** [comment]
There is a related issue here, which is that you can derive `Apply` without deriving `Functor` 😄

**Comment by LiamGoodacre** [comment]
What is the intended behaviour: Have the `Applicative` use the manual `Apply` instance? Disallow newtype deriving sub classes of manually implemented classes? Something else?
Is this considered `breaking` because people depend on this behaviour?

**Comment by garyb** [comment]
If we can do something so it's still possible to `derive newtype` and have it generate a dictionary with the correct superclass instances it'd be nicest, but that does change the meaning of what newtype deriving is a little bit. Maybe it's best to just disallow newtype deriving for any class that has a non-derived superclass instance?

I guess the problem of not checking whether there are superclass instances at all when newtype deriving is also something that should be addressed, but not sure whether it'll have entirely the same fix!
