### ISSUE TITLE
Test suite should use latest versions of core libraries

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2400]

**Comment by paf31** [comment]
It would be really great if we could switch to `psc-package` for pulling test dependencies at the same time actually.

**Comment by paf31** [comment]
@LiamGoodacre I think you fixed this with your most recent PR, yes?

**Comment by LiamGoodacre** [comment]
Yes, fixed in https://github.com/purescript/purescript/pull/2511

Although, do you want to convert this issue into: use psc-package for test deps?

**Comment by paf31** [comment]
Sounds good, but I'll open another issue.
