### ISSUE TITLE
Explicit module imports and --dump-corefn

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript#2404]
The following imports:

``` purescript
import CoreFn.Module (Module)
import Data.Either (Either)
import Data.Foreign (ForeignError)
import Data.Foreign.Class (readJSON)
```

are represented as:

``` json
{
  "imports": [
    "Prim",
    "CoreFn.Module",
    "Data.Either",
    "Data.Foreign",
    "Data.Foreign.Class"
  ]
}
```

It seems that perhaps the type of `moduleImports` should include `[Ident]` to be able to include all of the required information in the JSON output.

I see that `Module` is polymorphic in `a`, and that `a` is used in the type of `moduleComments`, so perhaps that satisfies this somehow.

If not, how is this intended to work? Thanks.

**Comment by paf31** [comment]
I deliberately chose to cut down the amount of information in the core output for the first version, but we can add more if it is useful. So, do we really need the identifier list in the output? Is it useful?

**Comment by paulyoung** [comment]
I was thinking that without the list of identifiers, it woundn't be possibly to do a similar thing during code gen.

Here's a contrived example for a hypothetical JS backend:

```purescript
-- | PureScript
import Control.Monad.Eff.Console (log)
```

```javascript
// JavaScript
import { log } from 'Control.Monad.Eff.Console';
```

I can see that at present the generated JavaScript simply calls functions like `log` as Control_Monad_Eff_Console.log(...)` which should work for other backends too.

I suppose it should also be possible to reconstruct the identifier list if desired, rather than including it in the JSON output.

**Comment by garyb** [comment]
On first read, it seemed to me like we should include the imports explicitly, but actually:

> I suppose it should also be possible to reconstruct the identifier list if desired, rather than including it in the JSON output.

Yeah, I think you should be able to find the imported things within a module easily enough, since all references within the AST should be fully qualified. I'm not sure we even need the imported module list really!

**Comment by paulyoung** [comment]
> I'm not sure we even need the imported module list really

It's definitely convenient, and the identifier list would be even more so.

Perhaps there's an argument that it makes it possible to do things like build a dependency graph more efficiently.

**Comment by garyb** [comment]
> It's definitely convenient

I don't disagree with that :smile:. Although it does depend a bit on what you're doing with it - if you're reading it back as the `CoreFn` ADT we use in the compiler, then you can use one of the [existing traversals](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/CoreFn/Traversals.hs) to easily grab all the references.

I guess the question is how much "unnecessary" stuff we want to include in the dumped corefn format for convenience's sake.

**Comment by paulyoung** [comment]
I'm in favor of putting things in the JSON output that remove the need for multiple implementations of the same thing (in various backends)

Having sad that, I'm not sure that this qualifies for reasons we've already discussed.

**Comment by natefaubion** [comment]
Regarding dependency graphs, is that something we should put in the upcoming `graph` command? This has not seen activity in a while. Should we close this?

**Comment by paulyoung** [comment]
I haven’t tried to do anything with this in a while but my thoughts haven’t changed regarding multiple backends each having to implement the same thing.

I assume figuring out the dependency graph is something each backend needs to do, but I’m not sure if making alternative backends convenient  is goal/concern at the moment.

cc @andyarvanitis @nwolverson @felixSchl

**Comment by andyarvanitis** [comment]
I guess I don't have an opinion at this point (I'd have to dig back into the codebase to see).

**Comment by nwolverson** [comment]
I don't think either dependency graphs or import lists (either modules or identifiers) are something I care about for purerl

**Comment by natefaubion** [comment]
I'm going to close this for now then.
