### ISSUE TITLE
case expression with ADTs has horrible compiler performance

### ISSUE THREAD

**Issue by jazmit** [purescript/purescript#2405]
The following program takes over a mnute to compile on my machine, emitting an `IncompleteExhaustivityCheck` warning.

```
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)

data Foo = A | B | C | D | E | F | G | H | I

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = log $ show $
    case A, B, C, D, E of
        A, A, A, A, A -> 0
        A, A, A, A, B -> 1
        A, A, A, C, A -> 2
        A, A, D, A, A -> 3
        A, A, E, A, A -> 4
        A, A, A, B, A -> 5
        _, _, _, _, _ -> 5
```

This kind of code occurs naturally when processing zipped lists of ADTs, which happens a lot in the app I'm working on - killing the compiler performance, even for whitespace changes in different modules. I realize that in general exhaustivity checks are non-trivial, but perhaps there could be a shortcut when the case expression includes a catch-all case as above?

**Comment by paf31** [comment]
This is somewhat expected right now since the checker works top down over the cases. As you say, we could add a special case at the bottom, but we still need to work top-down to do the check for redundant cases.

I suggest trying to break your sum type down into smaller types if possible.

**Comment by jazmit** [comment]
The workaround we used was to use nested case statements - ugly, but gets the job done.  Could I request that the compiler bails with `IncompleteExhaustivityCheck` much earlier, say after ~200ms rather than the ~30s that it currently takes?   I spent a good portion of a morning tracking down why incremental compile was taking more than 20s and I'd like to save others that pain...

**Comment by paf31** [comment]
Feel free to experiment with the threshold in `Linter/Exhaustivity.hs`, but reducing the threshold will mean that even smaller exhaustive cases will not be tested.

**Comment by paf31** [comment]
I'm going to close this, since we don't have a better algorithm which can also deal with redundant cases, as far as I know.
