### ISSUE TITLE
Incorrect ShadowedName warning in do blocks

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2409]
Here:

``` purescript
test = do
  x <- do
    x <- pure 1
    pure x
  pure x
```
The inner `x` is warned about, but that's incorrect since `x` is not defined at that point. As evidenced by:

``` purescript
test = do
  x <- do
    x' <- pure 1
    pure x -- Unknown value x error
  pure x
```

**Comment by LiamGoodacre** [comment]
Already fixed in master: https://github.com/purescript/purescript/pull/2385

**Comment by garyb** [comment]
Nice, thanks!
