### ISSUE TITLE
Allow `Newtype` deriving for newtypes that use type synonyms

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2416]

**Comment by paf31** [comment]
This is the same as the corresponding Generic deriving issue, right?

**Comment by garyb** [comment]
I don't know if it is exactly, the error is that you're not allowed to declare instances for type synonyms... is that the same reason it fails there?

**Comment by paf31** [comment]
Oh I see, then no, it's different.

**Comment by joshuahhh** [comment]
I think I've run into this bug. My minimal reproduction is
```
type MyString = String
newtype WrappedString = WrappedString MyString
derive newtype instance semigroupWrappedString :: Semigroup WrappedString
```
which produces the error
```
    No type class instance was found for

      Data.Semigroup.Semigroup MyString


  while checking that expression #dict Semigroup
    has type { append :: WrappedString -> WrappedString -> WrappedString
             }
  in value declaration semigroupWrappedString
```
even though 
```
newtype WrappedString = WrappedString String
derive newtype instance semigroupWrappedString :: Semigroup WrappedString
```
compiles without error.

Am I covered by this issue, or is this something different?

(Thanks!)

**Comment by joshuahhh** [comment]
OK – I just ran into a second, different bug, which actually uses capital-N Newtype deriving. Minimal reproduction is
```
type MyString = String
newtype WrappedString = WrappedString MyString
derive instance newtypeWrappedString :: Newtype WrappedString _
```
which produces the error
```
    Type class instances for type synonyms are disallowed.

  in type class instance

    Data.Newtype.Newtype WrappedString
                         MyString
```
even though
```
newtype WrappedString = WrappedString String
derive instance newtypeWrappedString :: Newtype WrappedString _
```
compiles without error.

I'm guessing _this_ is the bug referred to by this issue, and the bug I posted yesterday is a different one. Is that right?

(Thanks even more!)

**Comment by garyb** [comment]
The second one is the case that this is for, yep :)

The first one might actually be yet another issue though! As it's for lowercase-n newtype deriving.

**Comment by LiamGoodacre** [comment]
Aren't these all the same issue based around when we replace type synonyms?

**Comment by garyb** [comment]
They fall into that general category yeah. But on the other hand I think we shouldn't normally allow instances for type synonyms, to avoid confusion. So we want them to be desugared for deriving, but not for a hand written instance.

**Comment by adamw** [comment]
Just hit the same thing (https://groups.google.com/forum/#!topic/purescript/HG7uiRChNhE). I suppose  the same argument as why instances for functionally-dependent record types are allowed would apply to type synonyms?

**Comment by rubenmoor** [comment]
Not sure if that belongs here: I get the error "Type class instances for type synonyms are disallowed." when trying to define a `MonadAsk` instance for a monad transformer:

```
newtype UlffT m a = UlffT ( ExceptT Error (ReaderT Env m) a )

instance monadAskUlffT
      :: MonadAsk Env (UlffT m) where
  ask = UlffT <<< lift <<< ask
```

More context on stackoverflow: http://stackoverflow.com/questions/43469903/type-synonym-instances-are-disallowed-even-though-i-have-a-newtype-monad-trans
