### ISSUE TITLE
Noticed a strange pretty printing of forall

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2419]
From the [Control.Coroutine.fuseWith](https://pursuit.purescript.org/packages/purescript-coroutines/3.0.0/docs/Control.Coroutine#v:fuseWith) pursuit docs:

```purescript
fuseWith :: forall f g h m a par. (Functor f, Functor g, Functor h, MonadRec m, Parallel par m) =>
  (forall d. forall b c. (b -> c -> d) -> f b -> g c -> h d) -> Co f m a -> Co g m a -> Co h m a
```

Notice the unneccesarily doubled `forall` in the type of the first argument.

Whereas in the actual source:

```purescript
fuseWith
  :: forall f g h m a par
   . (Functor f, Functor g, Functor h, MonadRec m, Parallel par m)
  => (forall b c d. (b -> c -> d) -> f b -> g c -> h d)
  -> Co f m a
  -> Co g m a
  -> Co h m a
```

**Comment by LiamGoodacre** [comment]
I'm looking into this - now thinking it might just be a Pursuit issue: if I run `pulp docs` for coroutine the markdown that is generated is correct.  Currently waiting for Pursuit to build locally so I can test :)

**Comment by paf31** [comment]
This doesn't seem to happen in `psc-docs`.

**Comment by hdgarrood** [comment]
I'm not sure what was going on here, but this appears to be fixed now, looking at the pursuit docs.

**Comment by LiamGoodacre** [comment]
Great - I'll close this then :)
