### ISSUE TITLE
Docs on Pursuit don't show fundeps

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2439]
I think this is an issue with psc-docs, hence I report it on this repo.

The declaration:

```purescript
class (Semiring d, Ord d) <= Metric a d | a -> d where
```

results in the documentation:

```purescript
class (Semiring d, Ord d) <= Metric a d where
```

Note the absence of the fundep.

**Comment by LiamGoodacre** [comment]
I'm having a look into this.

**Comment by soupi** [comment]
@LiamGoodacre Sorry I didn't see your comment until now. I probably should have said I'm working on it as well.

**Comment by LiamGoodacre** [comment]
@soupi no prob. Looks like we changed everything in pretty much the same way: https://github.com/LiamGoodacre/purescript/commit/cffdb187772a18b0e5170985001c3753f9e70267

**Comment by hdgarrood** [comment]
Not entirely fixed just yet, but now we just need to wait until the next compiler release and then make a small change to Pursuit, so I've made an issue to track this at https://github.com/purescript/pursuit/issues/253.
