### ISSUE TITLE
Idiom Brackets

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#244]
It would be neat to support something like this

https://personal.cis.strath.ac.uk/conor.mcbride/pub/she/idiom.html

**Comment by AppShipIt** [comment]
Reading about idiom brackets this morning and stumbled on [applicative-quoters](http://hackage.haskell.org/package/applicative-quoters) inspired by it using quasi-quotation.

**Comment by paf31** [comment]
Closing, since something like (but not exactly) Applicative `do` is more likely to happen, and I prefer the syntax.
