### ISSUE TITLE
Thanks to Phil & all the contributors!

### ISSUE THREAD

**Issue by jdegoes** [purescript/purescript#2444]
This is a great day for me to reflect on a little-known language called PureScript...which has totally transformed the way my company builds front-end applications!

About three years ago, hanging out in the #purescript IRC chat room, it was pretty empty. Somedays, I was the only one there, although Phil would pop in from time to time.

The language looked a lot different than it does today, but the core of something beautiful and powerful was there—and that's what got me hooked.

Since then, I've taught PureScript to a couple hundred people, built many PureScript libraries, and adopted PureScript as the primary language driving the development of the SlamData open source visual analytics platform.

The language is a pleasure to use—I get so excited whenever I have a chance to code in it!—and has enabled my company to consistently develop high-quality, type-safe software that leaps past the usual unreasonable, complicated, and tangled jQuery GUI projects that I have hand-crafted in the past.

Today, the language is mature, the ecosystem is phenomenal, and the tooling continues to improve with each passing day. While there's always more we can push for (and I hope we do!), there's a tremendous amount to be grateful for. And none of it would be possible without the amazing and largely unpaid volunteer work done by dozens and dozens of people across the world.

Thanks to everyone who has helped make PureScript such a delightful and productive tool for front-end development, including @paf31, @garyb, @hdgarrood, @anttih, @bodil, @joneshf, @kRITZCREEK, @nwolverson, @LiamGoodacre, @rightfold, @phadej, @brandonhamilton, and countless others. I owe you all a beer, coffee, or tea, next time we're in the same town (actually, much more than that, but it'll have to do for now 😉).

**Comment by paf31** [comment]
Thanks for the note John - it's great to know that PureScript is providing some real value (And thank you for your own contributions of course!)

I'd like to say my own big thank you to the community as well. As you say, the project started out very small, but it continues to grow at a steady pace, with all sorts of fantastic progress being made. I'm constantly amazed by the sort of work going on, from the many excellent libraries, to compiler contributions from more and more contributors, to papers, student projects, conference talks, etc. When I started the project, I couldn't have dreamt of it growing into something so productive.

So thank you to everyone who has been involved so far, and let's think about how we can continue to get new contributors involved!

**Comment by sudhirvkumar** [comment]
@paf31, @garyb, @hdgarrood, @anttih, @bodil, @joneshf, @kRITZCREEK, @nwolverson, @LiamGoodacre, @rightfold, @phadej, @brandonhamilton @jdegoes 

Thanks Phil and all the other contributors! I cannot appreciate your effort enough!

Even six months ago, I couldn't have dreamt of having the kind of fun I am having right now while working...

Six months ago it was FDD (Fear Driven Development) and now its FDD (Fun Driven Development). I am planning to write a blog post soon about the transition from RoR, JavaScript to Haskell & PureScript.

We use Spacemacs, Haskell and PureScript. Its pure pleasure! It gives me the confidence to refactor and its like having a partner who really helps! I believe I am really pair programming! ;)

We are building API using Haskell Servant and its rock solid. Web front end using PureScript Pux, may be we will migrate to thermite and we are building a library to build React Native Applications (https://github.com/atomicits/purescript-rnx) using PureScript and Thermite.

Without your contribution, my life would be worse... Thats the kind of impact your effort is having on people like me and countless others who are yet to discover these amazing tools!

Thank you! Thank you so much!

**Comment by Cmdv** [comment]
Have to say as a new comer to Purescript the community is great and super helpful.

I'd highly recommend others to check it out because in my eyes this should definitely be the direction taken for web application tools. Functional programming as a whole is what's needed to clarify the complexities that our apps require and users expect. 😎 

Obviously Purescript isn't limited to just apps as it compiles to JS, of which it's application is available nearly everywhere.

As the community grow so will the content / resources for beginners so this should hopefully reduce the learning curve as there will be plenty of content out there. As well as the IRC / Slack channels. 

Overall the core contributors mentioned above are super friendly, helpful and it's a really enjoyable language to learn and code in 😄

**Comment by kRITZCREEK** [comment]
I'd like to give a shoutout to @garyb, @bodil and @paf31 in particular.

It was Bodil's [PureScript talk at Strangeloop](https://www.youtube.com/watch?v=yIlDBPiMb0o) that got me interested in and started with the language in the first place.

Gary helped me through my [first contribution](https://github.com/purescript/purescript/pull/1127) which would've probably taken him 2min on his own, but instead he invested in me and took the time to improve my PR and teach me something I didn't know.

Phil is on a totally next level though. He supervised my bachelors thesis on adding [*Type directed search for PureScript*](https://github.com/purescript/purescript/pull/2352) to the compiler and saw it through from its inception (writing the "sales pitch" for the topic) to its finish (actually taking the fricking plane and coming to Cologne for my defense).  He spent countless hours answering my questions, teaching me and revising my thesis and I'm incredibly grateful to him. We have lots of ideas on how to improve the type directed search feature and use it to power all kinds of interesting tooling and I'm looking forward to seeing how far we can take it.

So the three action items I see for me:

- Spread the word like @bodil. Don't let others miss out on PureScript 🎤 
- Be welcoming to new contributors like @garyb. Grow this community ❤️ 
- Become a saint like @paf31 one day? Not sure how to put this... 👼

**Comment by owickstrom** [comment]
I love how much positive energy there is in PureScript, and how much progress this community is making. It's very rewarding to be (a small) part of it. Since putting my own language project aside, I've kind of searched for something else to invest my time in. Purescript feels like a solid choice. I'm so excited for the future of the language and it's ecosystem, and I'm EXTREMELY impressed with the skills of the people involved and the maturity Purescript has reached. I hope to be able to go out to conferences next year to talk about Purescript, and to meet you all out there. Anyway, great work everyone! 👌

**Comment by natefaubion** [comment]
I'm thankful that I get to write code in such a wonderful language, all day, every day, and even _get paid to do it!_ I can honestly say I've never had so much fun in my professional life. I frequently, just before I start my day, tell myself, "I get to write @#$!ing _PureScript_ today." (I may have said the same about JavaScript, but with a very different intonation). I feel very blessed to work with a kind of tool that inspires so much creativity. Thanks to all who have contributed to making this language and ecosystem possible!

**Comment by paulyoung** [comment]
Thankful for everyone making the PureScript language, ecosystem, and community what it is!

**Comment by paf31** [comment]
Going to close this, but thank you everyone!
