### ISSUE TITLE
Crash when annotating a constructor binder with a quantified type

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2445]
The following code:

```purescript
eg = \(Proxy :: (forall a. Proxy a)) -> Proxy
```

Causes this:

```
psc: An internal error ocurred during compilation: "unifyTypes: unspecified skolem scope"
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:8:3 in purescript-0.10.2-Hp2rHRU6NraBMzRyfJIcIX:Language.PureScript.Crash
psc: thread blocked indefinitely in an MVar operation
```

Although it's not necessarily a sensible thing to write, it probably shouldn't crash 😄

**Comment by joneshf** [comment]
What is the expected behavior?

**Comment by hdgarrood** [comment]
I think we would expect the "a type variable has escaped its scope" error in this case, right?

**Comment by LiamGoodacre** [comment]
No I think this should be valid.  At least it's valid in GHCi.

**Comment by hdgarrood** [comment]
Ah ok, so we should get `eg :: (forall a. Proxy a) -> (forall a. Proxy a)`?

**Comment by LiamGoodacre** [comment]
Yes. Well, `forall b. (forall a. Proxy a) -> Proxy b`, but same thing 😄
