### ISSUE TITLE
psc-docs can consume lots of RAM

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2448]
Just tried running `pulp docs` on https://github.com/LiamGoodacre/purescript-type-map.  After a few minutes `psc-docs` was trying to use over 6G of RAM.  My poor 4G macbook pro was not particularly happy with it.

**Comment by hdgarrood** [comment]
I think the problem is coming from inside `Language.PureScript.Docs.Convert`, possibly `Language.PureScript.Docs.ReExports`.
