### ISSUE TITLE
Dump output for psc tests (examples/passing) to file?

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#2453]
I have a local branch with minor changes to `tests/TestCompiler.hs` to make it dump the console results of the tests to a tmp file. I do the same with my C++ backend test runner and regularly compare them as a sanity check on the execution behavior. It might be useful for other backends to do the same, even if it is pretty basic/crude. Would you like me to submit a PR for it?

**Comment by paf31** [comment]
This sounds interesting and potentially useful. Right now, we're just making sure the test case runs and prints out the word "Done!" at the end of stdout.

**Comment by andyarvanitis** [comment]
Ok, I'll get a PR ready, then. Yeah, maybe it can be a first step to more (automated) verification.
