### ISSUE TITLE
Moving the wiki to a separate repository

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2455]
I think quite a few people have suggested that we replace the wiki with a git repository where changes get reviewed. This should help us keep it well-structured and correct, and also would mean that people are more likely to trust the information contained within.

To this end, I have cloned the github wiki, written a little script to convert wiki links into regular relative Markdown links, and pushed the result to https://github.com/hdgarrood/documentation.

If everyone agrees, I suggest we proceed as follows:
* Transfer the above repository to the "purescript" organisation
* Add a link to the README in this repository, pointing to this new documentation repository
* Modify each page on the current wiki, replacing the content with a note pointing to the new location (I can automate this fairly easily),
* Restrict edits on the wiki to collaborators only (so that well-meaning people don't contribute changes to the wiki that later get forgotten about and lost when we eventually disable it).

Once this has been done, I can start cleaning it up and structuring it better. I think there's a bit of duplicated or outdated information in the wiki at the moment.

Eventually we can remove the wiki completely but I don't think we should do that for a while because of how the compiler includes links to it in error messages.

I mentioned this in IRC earlier today and some people mentioned GitBook and/or ReadTheDocs. Once the above is done, we can think about presenting this information nicely using tools/services like these; I don't want to bite off too much in one go.

**Comment by paf31** [comment]
Previous discussion is at #1771 (closed, but it makes sense to reopen this, I would still like to move pages into a repo)

**Comment by paf31** [comment]
The plan sounds good to me, thanks for writing this up.

**Comment by paf31** [comment]
One thought though: does it make sense to have a separate repo for the error messages? Or at least a subdirectory? Those pages tend to make it hard to scan the list.

**Comment by garyb** [comment]
👍 for errors subdirectory. Now it's a repo generally we can impose a bit more hierarchy I think!

Also 👍 for this generally, as discussed on IRC :smile:

**Comment by hdgarrood** [comment]
Yep, I was planning to create an errors subdirectory. :)

**Comment by michaelficarra** [comment]
Why a separate repo? If it was maintained under a `docs` directory in this repo, it would always be in sync with the implementation and the same git tags could be used for versioning them.

**Comment by hdgarrood** [comment]
I think because there's quite a lot of information in there that isn't really to do with the compiler. Also, I'm not sure if we do want to use the same tags; often, documentation corresponding to a particular version is modified after that version is released.

**Comment by paf31** [comment]
I do think some things could be moved into different repos. The PSCi page is a good example - that could be merged with the README.md file in the psci directory.

**Comment by chexxor** [comment]
Bravo to @hdgarrood for taking the first steps in the direction of better doc management. :+1: I feel like this is a really groundbreaking move. In addition to having the content be considered more reviewed and true than in a wiki page, users can create issues to request new doc pages or clarification on existing pages.

I think @michaelficarra's concern is a good one. The `purescript/purescript` repository *should* have some form of docs directory which stays in sync with the code, but its *contents* requires some planning/discussion. I think this migration to git-based docs is step in that direction and should be the accepted first step while the `purescript/purescript/docs` discussion occurs. We can clean up its contents before slowly merging it into the `purescript/purescript` repo

Some of my thoughts on the contents of the `purescript/purescript/docs` directory:

The stuff currently in the `hdgarrood/documention` repo seems to intend to document things from a human/meta point-of-view, like how to solve problems using PureScript concepts, which libraries are helpful, comparisons with other languages, build/packaging patterns, and others in this category. Should this type of docs be versioned along with the psc executables? Will discussion/PRs on this one-level-removed category of docs be unwanted noise in the `purescript/purescript` repo?

I imagine that the contents of the `purescript/purescript/docs` directory should at least describe how the binaries and language work at that time, like psc, psc-ide-server, and psc-bundle. The content currently in the `hdgarrood/documentation` repo *could* also exist there but in a different directory.

I imagine a `purescript/purescript/docs` directory structure like:

- `docs/{psc-language.md, psc-bundle.md, psc-ide-server.md}`
- `docs/conceptual/{eff.md, ffi.md}`
- `docs/patterns/{wrapping-node-libs.md, build-management.md}`
- `docs/ecosystem/{recommended-libraries.md, alternate-backends.md}`

**Comment by hdgarrood** [comment]
My initial thought was to have some docs inside this repository too, but now I'm not so sure. Having docs separate is helpful because:

* we don't want too much noise in the issue/PR tracker in this repository (as @chexxor already noted)
* Having the docs separate allows us to set up a separate CI to do things like check for broken links and markup syntax errors, which won't depend on the compiler's CI. Theoretically, yes, we could do both in one go, but the compiler's CI script is really slow and really brittle, and we don't want to put off potential documentation contributors by making them wait for ages for CI and then having it show up as a failure for something that isn't related to their change (I think this does happen occasionally, Travis can be a bit temperamental with more demanding CI scripts like the compiler's).

I'm not entirely convinced that having docs in the same repo will do that much to help us remember to keep them up to date, or at least not enough to justify it in light of the above.

---

Thanks @chexxor for starting to outline a structure, that's really helpful. I'd like to expand on that a little - in my mind the purescript/documentation repo should eventually contain the following:

* Reference-style documentation for the language itself (more or less what was previously contained in the Language Guide on the wiki). Not aimed at absolute beginners - that's what e.g. PureScript by Example is for. This is contained in the `language/` subdirectory.
* Documentation for compile errors, their causes, and suggested fixes (previously on the wiki). This is in the `errors/` subdirectory.
* Introductory guides, e.g. to intermediate level concepts like the FFI and the Eff type. Unlike the language guide, these are aimed at people who haven't used a particular aspect of the language very much before. There are some great examples of these on the purescript.org website already. I plan to put these in a `guides/` subdirectory.
* In-depth reference-style documentation for each of the binaries that comes with the compiler: `psc`, `psc-ide-server`, `psc-bundle`. I don't think this really exists at the moment, apart from the psci page. I also think it might be preferable to have this with the rest of the docs, since readmes in subdirectories of the compiler repo are a bit difficult to find. This section could subsume some part of the "purescript without node" page (although that page could also move under `guides/`). This section could go under `binaries`.
* A catalogue of links to various other things in the ecosystem: related libraries, meetups, video conferences, presentations, alternate backends, editor+tool support (I think pages in this section should not contain very much additional information over these links, because said information is probably better placed at the targets of those links). This can go under `ecosystem/`.

If something doesn't fit into one of these categories, I think we should try to move it elsewhere. For example, the lambdaconf 2015 page. There are a few exceptions though: related projects, contrib guidelines, and style guide don't really fit into any of these categories, but I think they deserve to stay in the documentation repo.

Some of this information already exists on purescript.org. I think we should start off by pretending that doesn't exist and not worry about duplication, and a little later, we can start removing things from purescript.org and link to the new docs instead.

---

Finally, markdown files in a github repository is great for collaboration and review, but perhaps not so great for presentation, so I think we should start thinking about how we want to address that now, because e.g. it affects how the files are structured and what kind of markup we use. I would like to try using reStructuredText and ReadTheDocs; it seems to have worked pretty well for [Idris](http://docs.idris-lang.org/en/latest/index.html). reST appears very similar to Markdown except with a bunch of extras that will probably be really useful for documentation: http://www.sphinx-doc.org/en/1.4.9/rest.html. Another aspect of ReadTheDocs that could work well for us is that we could use git branches for different versions - we could have a `current` branch which corresponds with what has been released already, a `master` branch which corresponds to features that are in `master` but haven't been released yet. When we want to make a new major compiler release, say, when we want to release 0.11.0, we would tag the `current` branch as v0.10, effectively archiving it, and then merge `master` into `current`. So on ReadTheDocs, there would be a version selector offering a choice between `master`, `current`, and previous archived versions. Another alternative that we could consider is taking care of HTML generation ourselves and making it all available at, say, purescript.org/docs.

**Comment by garyb** [comment]
Haha. We used to use reST when the compiler docs were originally on RTD. I find the syntax a bit weird personally, compared with markdown. What extras do we gain that would be useful over markdown? Depending on which markdown parser is in use, I don't think I see anything there that isn't also possible.

**Comment by hdgarrood** [comment]
Oh, I didn't realise there were compiler docs on RTD before! How come they moved away?

Things that jump out at me: [tables of contents](http://docutils.sourceforge.net/docs/ref/rst/directives.html#table-of-contents), [notes and warnings](http://docutils.sourceforge.net/docs/ref/rst/directives.html#warning), [links to arbitrary locations within documents](http://www.sphinx-doc.org/en/1.4.9/markup/inline.html#role-ref), [checked links just by enabling a flag](http://www.sphinx-doc.org/en/1.4.9/config.html#confval-nitpicky).

**Comment by paf31** [comment]
Shall we close this now? We can track remaining work in issues on the docs repo.

**Comment by hdgarrood** [comment]
Sounds good to me.
