### ISSUE TITLE
Add verify-set command to psc-package 

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2459]
This will just contain the code which is currently in the `package-sets` Travis job, but it will mean that the Travis job can just install the compiler and run `psc-package update` followed by `psc-package verify-all`.

**Comment by MQuaresma** [comment]
Im a first time contribuiter, do you think it would be possible to give me any directions as to how i should attempt to do this?

**Comment by paf31** [comment]
@MQuaresma Definitely - it's mostly a case of copying the code from the `purescript/package-sets` repo, and modifying some paths, but I can help out on IRC if you need more details.

**Comment by MQuaresma** [comment]
@paf31 Well I'll have a look and see if i can do anything, if i need anything i will get back here, which i probably will as im sort of new to git and opensource projects in general.

**Comment by MQuaresma** [comment]
Ok so i think i got it figured out and I've added the verify-set command, what should i do now? Test? Make a pull request? Should i have created another branch for this issue? Thanks in advance for the patience!

**Comment by paf31** [comment]
@MQuaresma Great! Could you create a pull request please? We can review the code there and hopefully get it merged.

**Comment by MQuaresma** [comment]
@paf31 Im in the process of doing so, haven't done it sooner because i just now realized i hadn't forked the repo...
