### ISSUE TITLE
Use fully qualified type names in compiler errors

### ISSUE THREAD

**Issue by Lewerow** [purescript/purescript#2461]
Currently in a situation when there is a type mismatch we get an error message with type names taken from two different namespaces - actual type as it is visible at the call site and expected type as it is visible in declaration site. This may cause confusion when different modules are imported with the same alias (e.g., `List`), since the error will be as follows:
```
Error found:
in module Main
at G:\BugReports\Purescript\List-is-not-List\src\Main.purs line 6, column 8 - line 6, column 14

  Could not match type

    List

  with type

    List


while trying to match type List t1
  with type List t0
while checking that expression List 1
  has type List t0
in value declaration g

where t0 is an unknown type
      t1 is an unknown type
```
This is of course correct from compiler perspective (`List` visible in module A is a different type than `List` visible in module B), but at the same time is very misleading from human perspective. A solution to that might be to use fully qualified type name (`Data.List`, `Data.List.Lazy`, `Data.List.MyOwn` etc.) instead of the name as visible at the call site.

An example of such setup can be found in: https://github.com/Lewerow/BugReports directory `Purescript/List-is-not-List`

**Comment by garyb** [comment]
Thanks for the report, but we already have an issue for this: #1647
