### ISSUE TITLE
Lift constants to module level to avoid re-evaluating them repeatedly

### ISSUE THREAD

**Issue by wereHamster** [purescript/purescript#2471]
In our view (pux, html) rendering code, we often place styles (essentially `:: CSS`) inside a `where` block to keep them local to the function and not pollute the top-level namespace. Like this:

```haskell
aphroditeStyle :: CSS -> Style
aphroditeStyle = ... -- implemented using the khan/aphrodite library

shortHeader :: ShortHeaderProps -> Html Action
shortHeader (ShortHeaderProps props) =
    div [className rootStyle] [ ... ]
  where
    rootStyle = aphroditeStyle $ do
        position relative
        paddingBottom (px 110.0)
```

However, generating the `CSS` (the do block after `aphroditeStyle`) is quite expensive and not something we want to do each time we render the HTML. Furthermore, it is constant, it doesn't depend on the function arguments, so it could be placed outside of the function. But if you have many such small functions inside a module you quickly run out of names. Or have to start prefixing the functions (`shortHeader_rootStyle = ...` etc) which is ugly and defeats the purpose of `where`, which is used here for encapsulation.

I believe GHC may make constant expressions CAFs as one of the optimisation steps.

https://ghc.haskell.org/trac/ghc/ticket/917
https://wiki.haskell.org/Constant_applicative_form

It would be even more awesome if PureScript would make those constants lazy (eg. automatically `Lazy a`) so that they are only evaluated when needed and not when the module is loaded.

**Comment by garyb** [comment]
#496, maybe #687 :)
