### ISSUE TITLE
Type synonyms in instance head under fundeps

### ISSUE THREAD

**Issue by starper** [purescript/purescript#2480]
I don't know if it is a bug or a feature (I really hope that it's a feature), but I found that this code compiles:
```purescript
type Rec r = { foo :: Int | r }
newtype Foo r = Foo (Rec r)

instance newtypeFoo :: TypeEquals a (Rec r) => Newtype (Foo r) a where
  wrap = Foo <<< to
  unwrap (Foo r) = from r
```
Is there anything that prevents us from adding support for type synonyms in instance head under fundeps, just like we now have for rows?

Like:
```purescript
instance newtypeFoo :: Newtype (Foo r) (Rec r) where
  wrap = Foo
  unwrap (Foo r) = r
```
Or:
```purescript
derive instance newtypeFoo :: Newtype (Foo r) _
```

**Comment by paf31** [comment]
This fails for the same reason as #1443, so I'll close this as a duplicate.
