### ISSUE TITLE
Infinite recursion in derived Generic for recursive data types 

### ISSUE THREAD

**Issue by zudov** [purescript/purescript#2482]
It appears like deriving `Generic` for recursive data types can give you an infinitely spinning implementation of `toSignature`.

The following sniplet ([on try.purescript.org](http://try.purescript.org/?gist=145fa2b3be6b0dc1778757d10229b8e0)) runs infinitely. Adding `do` with `pure unit` makes it fail with "too much recursion" message.

```haskell
data List a
  = Cons a (List a)
  | Nil

derive instance genericList  :: Generic a => Generic (List a)

main = 
  render =<< withConsole
    (logShow (toSignature (Proxy :: Proxy (List Int))))
```

It appears like it was introduced in a recent releases (we noticed it because the tests of purescript-strongcheck-generics aren't terminating anymore).

**Comment by paf31** [comment]
Are you sure that this is a compiler bug and not a bug in `generics` itself?

**Comment by zudov** [comment]
Ah, didn't think about it. I'll make sure.

**Comment by zudov** [comment]
It appears that the instance code gets a rather unconditional recursive call and if I understand correctly the compiler is responsible for desugaring those deriving declarations into that code.

```javascript
var genericList = function (dictGeneric) {
    return new Data_Generic.Generic(function (v) {
        ...
        }, function ($dollarq) {
        return new Data_Generic.SigProd("Main.List", [ {
            sigConstructor: "Main.Cons", 
            sigValues: [ function ($dollarq1) {
                return Data_Generic.toSignature(dictGeneric)(Data_Generic.anyProxy);
        }, function ($dollarq1) {
                return Data_Generic.toSignature(genericList(dictGeneric))(Data_Generic.anyProxy);
                                                ^^^^^^^^^^^^^^^^^^^^^^^
            } ]
        }, {
            sigConstructor: "Main.Nil", 
            sigValues: [  ]
        } ]);
    }, function (v) {
       ...
    });
};
```

**Comment by zudov** [comment]
> It appears that the instance code gets a rather unconditional recursive call

I guess I was wrong with that conclusion, because the recursive call that I marked actually seems valid, and it's not "unconditional" (since it's suspended in a function).

I'll have a better look at what might be causing this.

**Comment by zudov** [comment]
Nevermind, after a better thought I see that this is a valid behavior, fully evaluating a recursive `GenericSignature` isn't supposed to terminate since it always contains itself.

**Comment by paf31** [comment]
Ah, that makes sense. `generics-rep` might help here, depending on what you're trying to do.
