### ISSUE TITLE
non (Eff _ _) Main typecheck without type annotation due to set of constraints

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2487]
🔴 this compiles but doesn't run (it returns immediately without doing anything)

```purescript
module Demo where

import Prelude
import Control.Coroutine (await, emit, runProcess, ($$))
import Control.Monad.Cont (lift)
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Class (liftEff)
import Control.Monad.Eff.Console (logShow)
import Control.Monad.Rec.Class (forever)

-- nats :: forall m. (Monad m) => Producer Int m Unit
nats = go 0 where go i = do emit i *> go (i + 1)

-- printer :: forall a. Consumer String (Eff _) Unit
printer = forever do
  s <- await
  when (s `mod` 100 == 0) $ lift (liftEff (logShow s))
  pure unit

-- $$ => imply a Parrallel constraint
-- main :: Eff _ Unit
main = runProcess (nats $$ printer)
```

inferred type is :

```
main :: forall t38 t39 t42 t47.
  ( MonadRec t39
  , Parallel t42 t39
  , MonadEff
      ( console :: CONSOLE
      | t47
      )
      t39
  ) => t39 t38
```

🔴 if we add above type, it type-checks
🍏 if we add a simple `Eff _ Unit` annotation as below, psc reject the code:

```purescript 
main :: Eff _ Unit
main = runProcess (nats $$ printer)
```

```shell 
[1/1 NoInstanceFound] src/Demo.purs:22:1

  22  main = runProcess (nats $$ printer)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  No type class instance was found for

    Control.Parallel.Class.Parallel t1
                                    (Eff
                                       ( console :: CONSOLE
                                       | t2
                                       )
                                    )

  The instance head contains unknown type variables. Consider adding a type annotation.
```

the problem, as I understand it, is that `psc` is not able to understand that those constraint will prevent Main from beeing an Eff:

```
  , Parallel t42 t39
  , MonadEff
      ( console :: CONSOLE
      | t47
      )
      t39
```

--------------

❔  is it related to https://github.com/purescript/purescript/issues/2086 ?
📝 the readme [here](https://pursuit.purescript.org/packages/purescript-coroutines/3.1.0) is very misleading

**Comment by natefaubion** [comment]
The README for coroutines is wrong. Current coroutines required `Parallel`, which is not satisfied by `Eff` directly. Otherwise this is just an issue of bundle code expected `Eff`, and this not being `Eff` (the issue you linked to). It doesn't do anything because the constraints desugar to more parameters, so when calling `main()`, it is not invoking an `Eff`. To get this to type check as `Eff`, you probably want to use `runAff` or `launchAff`, as `Aff` is what's most commonly used with coroutines.

**Comment by rvion** [comment]
yes, I used launchAff, thanks :)

I don't use psc bundle, I was calling it manually from node... Hm, so there is actually no bug here, since there is no reason for psc to prevent me from creating  a main function with a non Eff _ _ type. And indeed, I am now realizing that this should be a psc-bundle check.

Sorry for the non-bug report,
and thanks again ! :)
