### ISSUE TITLE
Kinded types can cause instance solving to fail

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2490]
I found this whilst working on https://github.com/purescript/purescript/pull/2486

The following works as expected:
```purescript
eg = show (unit :: Unit)
```

If we annotate `Unit` with its kind, it fails:
```purescript
eg = show (unit :: (Unit :: *))
```

We get:
```purescript
No type class instance was found for

    Data.Show.Show (Unit :: *)


while inferring the type of show unit
while applying a function show
  of type forall a. (Show a) => a -> String
  to argument unit
in value declaration eg
```

**Comment by LiamGoodacre** [comment]
Looks like `KindedType` is missing from various functions in `TypeChecker.Entailment`; e.g: `typeHeadsAreEqual`, `typesAreEqual`.

**Comment by paf31** [comment]
Oops, thanks :)

**Comment by LiamGoodacre** [comment]
Okay I've worked out a solution to this, I'll submit a PR shortly.
