### ISSUE TITLE
Various dependencies fail to build constantly since update to psc 0.9?

### ISSUE THREAD

**Issue by Podlas29** [purescript/purescript#2493]
Hi.

There was a time before psc 0.9 when I developed my side-project: https://github.com/Podlas29/purescript-murph

Then some kind of issues appeared in build after psc was updated to 0.9 (all libraries got updated to 1.x.x versions). I did not have time to solve the problem back then, so I just left project for a while.

Now I wanted to come back, hoping things have stabilized. I updated psc to newest release, and started adding newest versions of dependencies one by one.

At this point
```
    "purescript-prelude": "^2.1.0",
    "purescript-maybe": "^2.0.1",
    "purescript-either": "^2.0.0",
    "purescript-dom": "^3.3.1"
```
my build started faling once more. I checked failing libraries on their own and they worked fine, but when combined in my project, build fails. Even funnier, reasons for this errors seem very diverse:

```
Error 1 of 4:

  in module Control.Monad.Rec.Class
  at /home/mateusz/Programowanie/Projects/purescript-murph/bower_components/purescript-tailrec/src/Control/Monad/Rec/Class.purs line 128, column 8 - line 128, column 25

    Unknown value U.unsafeCoerceEff


  See https://github.com/purescript/purescript/wiki/Error-Code-UnknownName for more information,
  or to contribute content related to this error.

Error 2 of 4:

  in module Control.Monad.Cont.Trans
  at /home/mateusz/Programowanie/Projects/purescript-murph/bower_components/purescript-transformers/src/Control/Monad/Cont/Trans.purs line 13, column 36 - line 13, column 50

    Cannot import type class MonadAsk from module Control.Monad.Reader.Class
    It either does not exist or the module does not export it.


  See https://github.com/purescript/purescript/wiki/Error-Code-UnknownImport for more information,
  or to contribute content related to this error.

```

Am I the only person having such issues with builds?

Thanks in advance and have a nice day :)

**Comment by paf31** [comment]
Try `rm -rf output` if you haven't already. If that still fails, try wiping out `bower_components` and reinstalling dependencies from scratch.

**Comment by Podlas29** [comment]
Wow. I feel so stupid now. Removing old `output` helped. 
I really did not code in purescript for few months just because I forgot to clean one directory. :)
Thank you very much! ;)

**Comment by paf31** [comment]
Glad it's working :)

**Comment by hdgarrood** [comment]
I think this ought to be considered a bug in `psc`, really. It should never be necessary to manually delete a cache directory, IMO. Eventually I will get around to making a solid set of repro steps so that we can start thinking about how we can address this.
