### ISSUE TITLE
Include documentation for Prim types in the library

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2494]
I'm trying to address a Pursuit issue where links to primitive types are broken: https://github.com/purescript/pursuit/issues/218

Currently we have a hacky solution for Prim types where I have published a pseudo-package 'purescript-prim' which mirrors the Prim module and provides documentation. However this has turned out to be too easy to forget to update. If we could include this information in the purescript library instead, Pursuit could just use that and we wouldn't need to worry about forgetting to update it. If the Prim module were to ever change again, Pursuit could then pick up any change just by updating its dependency on the purescript library and nothing else would need to happen.

I am only imagining a very small change to Language.PureScript.Environment, the rest would happen in Pursuit. If this sounds good to people I'll send a PR.

**Comment by paf31** [comment]
👍 Sounds good to me
