### ISSUE TITLE
Cannot hide things from Prim

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2499]
The following code attempts to hide `Int` from `Prim` and define a new local `Int`:
```purescript
module Main where
import Prim hiding (Int)
type Int = String
m :: Int
m = "hi"
```

This fails with the following error:
```
Conflicting definitions are in scope for type Int from the following modules:

    Main
    Prim
```

**Comment by rightfold** [comment]
@LiamGoodacre Do you have an idea of how hard this would be to implement? We actually need this in one of our tools.
