### ISSUE TITLE
psc-ide-server crashes once project gets a little bigger

### ISSUE THREAD

**Issue by sudhirvkumar** [purescript/purescript#2504]
We are using spacemacs with purescript layer. We have are in the process of building a React Native Mobile app with PureScript.

It used to work fine earlier, nowadays it crashes after sometime. When we start it uses 100% cpu for a few seconds and then it crashes once we make changes to the code in emacs. We started adding more files and then it started crashing.

May be its a memory leak or something?

**Comment by paf31** [comment]
Thanks for the report. Do you think it would be possible to get a profile?

**Comment by sudhirvkumar** [comment]
@paf31 how do i get the profile? Help is appreciated.

**Comment by paf31** [comment]
@sudhirvkumar First, build with profiling enabled: `stack build --profile`, then run `psc-ide-server` with profiling options (`+RTS -p`, although you might like to have a look [here](http://downloads.haskell.org/~ghc/5.00/docs/set/prof-rts-options.html) too). Then have a look at the resulting `.prof` file in your editor to see what functions are taking the most time and space.

**Comment by kRITZCREEK** [comment]
This sounds similar to #2249. 
- Could you try starting `psc-ide-server` outside of emacs without passing source globs and see if the issue still appears? 
- Are you using `bower link` inside your project?
- Could you check if this is a windows only issue?

For profiling see @paf31's comment

**Comment by sudhirvkumar** [comment]
@paf31 @kRITZCREEK Thanks for your super fast responses.

1. yes, I used pscid --port 4242 and connected from spacemacs and it worked a bit and then it crashed
2. yes, I am using bower link
3. I am using ubuntu and not windows.

is `bower link` bad? can you please explain?

**Comment by sudhirvkumar** [comment]
@paf31 I will check the profiling build and let you know.

@kRITZCREEK in https://github.com/purescript/purescript/issues/2249 there is a mention of 9gig. I checked the memory usage of 400MB or less and then it crashes.

**Comment by kRITZCREEK** [comment]
@sudhirvkumar when it crashes inside emacs do you get any output inside the `*psc-ide-server*` buffer?

**Comment by kRITZCREEK** [comment]
> yes, I used pscid --port 4242 and connected from spacemacs and it worked a bit and then it crashed

Allright so it doesn't seem related to the parser

> yes, I am using bower link
> is bower link bad? can you please explain?

No no `bower link` is fine. It's just a similarity between the two issues, so it sounds like a good lead to where the problem lies.

>I am using ubuntu and not windows.

Okay so it's not a windows issue then, phew I hate to debug these :D

**Comment by sudhirvkumar** [comment]
@kRITZCREEK I will check that `*psc-ide-server*` and get back to you tomorrow. I don't have an issue in my laptop at home. Have to check the laptop at office.

btw, It was working fine earlier and at that time we were using `bower link`

my colleague mentioned he started having this issue around the time we started using `yarn`. I am puzzled as why would `yarn` be an issue. We are using the commands which are available in paths and regardless of whether we use `npm` or `yarn` they should work!?

**Comment by sudhirvkumar** [comment]
@kRITZCREEK I checked the buffer and this is what I saw. I tried restarting and it again crashed.

```
Process *psc-ide-server* exited abnormally with code 1
psc-ide-server: <socket: 12>: hPutBuf: resource vanished (Broken pipe)

Process *psc-ide-server* exited abnormally with code 1
```

when we use pscid, it simply works! we use multiple buffers to edit files... will that be an issue?

**Comment by paf31** [comment]
> when we use pscid, it simply works

Sounds like this is an Emacs plugin issue, possibly? If so, can we move this over to that repo please.

**Comment by sudhirvkumar** [comment]
@paf31 After I posted that comment. pscid did crash twice... but not as often as inside spacemacs. Mainly because it works only after we save the file? emacs plugin works for every change. could that be the issue?
