### ISSUE TITLE
psc-bundle -> 'PS' namespace for the browser is local to a function, not global

### ISSUE THREAD

**Issue by Andrew-Webb** [purescript/purescript#2512]
I wish to call a PS function from a vanilla JS function.

[This FFI reference](http://www.purescript.org/learn/ffi/) says `You might also like to bundle JavaScript code for the browser, using psc-bundle. In that case, you would access the Test module on the global namespace, which defaults to PS.`

But actually, the `pulp browserify` + `psc-bundle` combination writes:-

    // Generated by psc-bundle 0.10.3
    var PS = {};

within an immediately invoked function, and so is local to that function.

Stepping through the execution of the bundled / browserified code in IE's debugger, it reported (as far as I can tell) that the code created no globals at all.

Perhaps the code should do this instead:-

    window.PS = {};
    var PS = window.PS;

?

**Comment by Andrew-Webb** [comment]
I modified my generated .js file as indicated above, i.e. turning:-

    var PS = {};

into:-

    window.PS = {};
    var PS = window.PS;

and joy and happiness resulted.  Very easy to call the PS function from my JS function (and that is how I intend to operate for while: writing the UI in a thin layer of vanilla JS with Vue.js, and calling into PS for application data and logic).

Normally I'd be happy to generate a PR for such a small and simple issue, but frankly I haven't got a clue how your Haskell works.  I'm still only a PureScript newbie, and haven't ever touched Haskell.

**Comment by natefaubion** [comment]
Check out the `--standalone` options for `pulp`: https://github.com/bodil/pulp#reimporting-browserified-bundles

**Comment by hdgarrood** [comment]
The guide you've read is talking about what happens when you just use psc-bundle on its own, i.e. not with browserify too. You can use psc-bundle on its own by running `pulp build --to bundle.js`. Alternatively if you do need to browserify and call into your PS code from JS, `--standalone` will do the job, as @natefaubion says.

**Comment by Andrew-Webb** [comment]
Yes, adding `--standalone PS` defined `PS` as a global, although somewhat altering the syntax I should use.

Before:-

    PS.MyModule.myFunction(...);

With standalone:-

    PS.myFunction(...);

Thanks.

**Comment by Andrew-Webb** [comment]
@hdgarrood: Yes, `pulp build --to bundle.js` is much more what I want - no need for browserify - and it restores the `PS.MyModule.myFunction(...);` calling syntax, which I was expecting.  Plus the generated JS code is easier to understand.  Thanks.
