### ISSUE TITLE
Comment style

### ISSUE THREAD

**Issue by spicydonuts** [purescript/purescript#2514]
It seems a bit silly in a typed, compiled language like PureScript, but in the dynamic world of JavaScript comments have become a common way to provide hints to code analysis tools.  A project I'm working on is using Istanbul for code coverage reports and there's a lot of compiler-generated code I'd like to skip.  For example:

```purescript
-- istanbul ignore next
derive instance genericGUID :: Generic GUID
```

That comment doesn't work because Istanbul is expecting a comment in exactly this form:

```javascript
/* istanbul ignore next */
```

The "next" statement or expression can be on the following line or immediately to the right of the comment after a space:

```javascript
/* istanbul ignore next */
foo
```

```javascript
/* istanbul ignore next */ foo
```

Currently a PS comment always gets transformed to a block comment in JS:

```purescript
-- some insightful comment
someCode ...
```

```javascript
/**
 *  some insightful comment
 */
someCompiledCode ...
```

This works most of the time, but there are some JS analysis tools which use comments as hints or extra metadata which are more picky about the format.

Below are some potential ways comment format could be controlled.

Single line, until end of line:

```purescript
-- comment
```

```javascript
// comment
```

They would not automatically be transformed to blocks:
```purescript
-- comment
-- another comment
```

```javascript
// comment
// another comment
```

Single line, block (`--|` would be nice, but it would change the behavior of existing code):

```purescript
--| comment |--
```

```javascript
/* comment */
```

Multi line, block:

```purescript
--| comment
--| more comments
--| these need to line up
--| to become a single block comment
```

```javascript
/**
 *  comment
 *  more comments
 *  these need to line up
 *  to become a single block comment
 */
```

Again, I know from a PS perspective the details of comment formatting seem a bit silly, but one of the main draws of PS is how close it is to its main compile target of JS.  You can include a little PS in almost any JS project.  Allowing this control when it's needed makes existing JS-analysis tools usable in PS projects.

**Comment by hdgarrood** [comment]
I won't take a stance on this issue but if we were going to do this I'd say it would be more appropriate to translate PureScript line comments into JS line comments, and PS block comments into JS block comments:

```purescript
-- this is a line comment

{- this is a block comment
  it can span multiple lines -}
```
==>
```javascript
// this is a line comment

/* this is a block comment
  it can span multiple lines */
```

I think it would be best not to overload the `--|` syntax as currently that just means a line comment which should be included in generated documentation such as Pursuit.

**Comment by paf31** [comment]
Sounds relatively straightforward, and I think it'd be a good idea to generate line comments if we can, as @hdgarrood suggested, but single line block comments should ideally become single line block comments in the generated JS too.

I'm fine with adding this, but I don't know how I feel about users relying on it too heavily, so I'm fine with it being a "hidden feature" 😄

**Comment by spicydonuts** [comment]
That makes sense.  They'll probably just do what I did and look at the compiled file to see if the comments survive.  `{- comment -}` should probably be documented as another available syntax though.

**Comment by hdgarrood** [comment]
It is documented :) https://github.com/purescript/documentation/blob/master/language/Syntax.md#comments

**Comment by paf31** [comment]
I meant the code generation.

**Comment by spicydonuts** [comment]
Ooh, I see now, sorry 🙂

**Comment by funnyjokes** [comment]
Oh! This article has suggested to me many new ideas. I will embark on doing it. Hope you can continue to contribute your talents in this area. Thank you.
[instagram quotes](http://instagquotes.com)
