### ISSUE TITLE
Derive Foldable and Traversable

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2518]

**Comment by thautwarm** [comment]
Help help! I need this! Is it possible to achieve this with the existing type level computation?

**Comment by JordanMartinez** [comment]
Since this issue doesn't list any info about _how_ to do this, I did a search and found this:
- https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/derive-functor
- https://gitlab.haskell.org/ghc/ghc/-/issues/2953
