### ISSUE TITLE
Package registry

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2526]
Based off conversation in #2520, but I just realised that this is orthogonal and I think it deserves its own issue.

As @bodil [previously pointed out](https://github.com/purescript/purescript/issues/631#issuecomment-174215862), relying on git tags for dependencies is problematic, since git tags can disappear or be rewritten, or the repository can disappear completely. For example, with the current setup, it might only take one purescript library author's GitHub account to be compromised to cause complete chaos for everyone trying to fetch dependencies for their projects.

Additionally, using Git tags means that we don't control the registry, which means we have no ability to perform any pre-release screening of packages, which could save a lot of hassle for package authors and consumers alike. Most importantly, we should be able to identify many kinds of breaking changes mechanically and thereby avoid situations where breaking changes are released without a corresponding major bump. Similarly it would be nice to be able to reject packages which don't include licensing information, and also to be able to reject packages which declare dependencies based on local paths or branches in some git repository (since published packages should only depend on published versions of other packages).

I think if we were going to do this we would probably want to build it into Pursuit, together with a read-only mirror hosted somewhere more reliable, perhaps GitHub, so that we don't have to worry too much about uptime. But we should establish if/when we want do this before thinking too hard about the implementation.

**Comment by paf31** [comment]
A package set repository is the closest thing to a registry. I think the problem you mentioned can be solved by adding the expected SHA hash of the cloned repo to the package in the package set file, like Nix does.

> I think if we were going to do this we would probably want to build it into Pursuit

I was actually thinking of things the other way around, with Pursuit's data (the search index) being regenerated periodically from each package set tag. Documentation could be statically generated once when the tag is created.

**Comment by Pauan** [comment]
@hdgarrood Adding in [checksums for package sets](https://github.com/purescript/package-sets/issues/32) solves the integrity issue. As for availability, that's an issue with *any* hosting site anywhere on the internet.

As for "pre-release screening of packages", can't it just clone all the GitHub repos, run whatever tests you want on them, and then do the release? It needs to do that anyways in order to generate the checksums, so that's a natural time to do any additional tests/builds/generate docs/whatever.

If you view GitHub as simply a "good place to host code", and checksums solve the integrity issue of Git tags, then what benefit is there to having a separate registry?

**Comment by paf31** [comment]
> As for "pre-release screening of packages", can't it just clone all the GitHub repos, run whatever tests you want on them, and then do the release? It needs to do that anyways in order to generate the checksums, so that's a natural time to do any additional tests/builds/generate docs/whatever.

Yes, the `package-sets` CI job takes care of this right now. There is an open issue to run the test suites as part of that job. It should also verify any SHA hashes if we add that data.

> If you view GitHub as simply a "good place to host code", and checksums solve the integrity issue of Git tags, then what benefit is there to having a separate registry?

I agree, but I'd like to just point out that nothing depends on GitHub specifically right now, just Git.

**Comment by Pauan** [comment]
@hdgarrood Just to clarify, when I say "checksum" I don't mean something weak like a parity bit or MD5, I mean something with strong cryptographic guarantees, like sha512sum, so it does completely solve the integrity issue. In fact if implemented correctly, it can be even more secure than hosting our own registry.

**Comment by bodil** [comment]
If you're not solving the problem of reliably obtaining the data you're checksumming, it doesn't matter one bit how cryptographically strong your algorithm is.

Seriously, let's not paint ourselves into the same corner Go did. If we can't provide a reliable way to download release artifacts, including historical release artifacts, we're doing it very wrong. There's no way to do this other than providing an artifact repository which guarantees that the same URL (or at least the same version tag) will lead to exactly the same data in perpetuity.

**Comment by paf31** [comment]
Why is it doing something wrong if we don't host artifacts? Could you be more specific please?

I feel like we could handle this problem later as long as we can fix the integrity issue now, but I really don't want to centralize everything. I know things like IPFS exist, but I don't know if that is a better solution. There is also the problem of the cost of hosting and maintainance.

**Comment by hdgarrood** [comment]
I just think it's important that we find something that's more reliable. I would really like our package registry to be append-only; for me, the risk that something might change or disappear is currently too large. The most obvious way to achieve that is a traditional centralised package registry (and that is what I was imagining) it but I'd be happy if we ended up with a decentralised system too. I'm going to read up on IPFS a bit more actually.

On the subject of whether the package-sets repo can be considered a registry: I'd rather not do that either, because I think we should encourage people to only submit packages to package sets if they expect to be able to maintain them for some period of time. It should be possible to publish packages (by which I mean, make them available for other people to depend on easily) without including them in package sets.

**Comment by bodil** [comment]
If we don't provide a mechanism for downloading artifacts in a consistent manner (and please see previously about what that means), the end result is that artifacts will inevitably become unavailable. When this happens, the entire ecosystem is at risk if it's something that's heavily depended on. This has already become a problem in Go, where they thought it would be a cool idea to use Git URLs to refer to dependencies.

If it comes down to a problem of securing hosting, I can take care of that. I'm also not at all opposed to figuring out how to make it distributed, as long as the properties of append-only and full historical availability hold - though retaining editorial control may be useful (and could possibly become a legal requirement).

**Comment by Pauan** [comment]
@bodil Genuine question: which hosting services do you think are more reliable than GitHub?

**Comment by paf31** [comment]
> I just think it's important that we find something that's more reliable.

I think we can deal with reliability later, by adding mirrors. I don't see why hosting our own registry means anything will be more reliable.

> I would really like our package registry to be append-only; for me, the risk that something might change or disappear is currently too large.

The package sets repo can be append-only, enforced by the PR process, at least until we make a new major release.

We can't do anything about people deleting their repos, but we could mirror repos later if this proved to be an issue. We at least have a layer of abstraction in front of the repos themselves, which allows us to switch between mirrors. Again, this is not something which concerns me in the short term. I'm not interested in building the perfect system as part of 1.0.

> On the subject of whether the package-sets repo can be considered a registry: I'd rather not do that either, because I think we should encourage people to only submit packages to package sets if they expect to be able to maintain them for some period of time.

I don't understand this - no more maintenance is needed. If the user no longer wants to maintain the package, it simply won't be included in the next major release of the package set.

> If we don't provide a mechanism for downloading artifacts in a consistent manner (and please see previously about what that means), the end result is that artifacts will inevitably become unavailable. When this happens, the entire ecosystem is at risk if it's something that's heavily depended on.

Again, I think we can deal with this later, by mirroring repositories.

Now, more generally, `psc-package` was supposed to be a minimal Git-based solution to a particular problem. I would say it solves that problem quite well, and many of the problems discussed here seem to be orthogonal. I don't have the motivation or time to solve them all now. So I'd rather scrap `psc-package` entirely and stick with Bower than change to a radically different approach now.

**Comment by hdgarrood** [comment]
Regardless of which conclusion we reach here, I don't think we should consider scrapping `psc-package`, since I think we can separate the details of how our registry works from the implementation of `psc-package`. I think we could do it with a data type like this, for example:

```haskell
data PackageRegistry = PackageRegistry
  { registryFindAvailableVersions :: PackageName -> IO [Version]
  , registryGetPackageTarball :: PackageName -> IO ByteString
  , ...
  }

**Comment by Pauan** [comment]
@paf31 
> I don't see why hosting our own registry means anything will be more reliable.

I think @bodil and @hdgarrood are basically worried about people renaming/deleting their GitHub repo, renaming/deleting their Git tags, etc. This doesn't cause a security issue (due to checksums), but it does cause the repo to be unavailable to anybody who wishes to download it.

However, a centralized registry isn't a panacea: running a good web hosting service is hard or expensive (or both). I appreciate that @bodil is willing to help out with that, but what if the web service is flaky? What if @bodil goes missing and the service lapses? What if it becomes too expensive to maintain? What if there's a sudden increase in PureScript users, which overloads the server beyond its quota? These are difficult questions to answer, it's not as simple as "centralized registry is more reliable".

As far as mirroring goes, GitHub provides tarballs for all Git tags, and it's easy to mirror those tarballs on a simple, cheap, static server. I don't know whether it's the best option, but it is an option.

----

> So I'd rather scrap `psc-package` entirely and stick with Bower than change to a radically different approach now.

Please don't. I really do think `psc-package` is the right path forward, and I agree that we can deal with issues like availability later. One step at a time.

**Comment by hdgarrood** [comment]
I'm just about to start my second semester of this academic year so I don't have a huge amount of spare time now but I will do during the summer, at which point I would like to have a proper stab at this. Having done a bit of googling, I think a system based on IPFS is at least conceivable, and that would solve the issue of availability pretty comprehensively. We [wouldn't be the first to consider such a system](https://github.com/whyrusleeping/gx), either.

> but we could mirror repos later if this proved to be an issue

From what I hear from Go users, it has proved to be an issue (perhaps someone can corroborate this, I'm not involved with Go), so I think we should expect it to become an issue for us too. I'm not very keen on mirroring repositories, I imagine that would be rather difficult logistically.

> I don't understand this - no more maintenance is needed. If the user no longer wants to maintain the package, it simply won't be included in the next major release of the package set.

I made a comment along these lines earlier: https://github.com/purescript/purescript/issues/2423#issuecomment-259532102 essentially, I expect that if a new package is added to a package set and then dropped shortly afterwards, that would cause more work for basically everyone involved. Curators have to first merge a PR that adds it and then, when it needs to be removed again, approach the original author, give them time to respond, then remove the package again after that time has elapsed, and in the meantime explain to everyone else what's holding their packages back. Consumers of that package are essentially back to square one if the package is removed from the set, too, as they have to find some other way to depend on it. This is why I think we should use the same policy as Stackage does: only submit a package to a package set if you expect to be able to maintain it for some period of time, i.e. if it starts to cause any problems, you would like to know about it and you would want to try to fix it.

**Comment by paf31** [comment]
Using Git everywhere was the key idea behind `psc-package` as far as I'm concerned, so while I think IPFS is interesting, it would be a very different approach.

I don't think we have to solve everything at once. These would be interesting approaches, but I'd very much prefer to get something working with Git first.

I don't think we should rush to solve problems which affect communities at the scale of Go yet, when we have no evidence that they are problems for us.

**Comment by hdgarrood** [comment]
I fully agree with all of this - I didn't mean to suggest we should rush to solve this, although I think it would be good to do before 1.0 (although presumably what 1.0 should mean is quite subjective). The way I see it there is no problem with continuing in the direction we're going with `psc-package` and addressing this later.

**Comment by bodil** [comment]
Agree, and it doesn't seem to me like modifying psc-package later would be especially difficult. I did believe package sets were the key idea behind psc-package, though. ☺️

I've actually been wanting to sit down with some Rust people (who seem to have gotten package management very right) and talk it through with them. I'd also be very interested in chatting with someone from npm inc, who will have dealt with all the unforeseen stuff, like legal issues, one is likely to encounter in the long term. Maintaining a registry is definitely not something to be taken lightly, and certainly not rushed into - but we already know from Go and Erlang especially that relying on third parties (ie. author hosted git repos) for availability and integrity can get out of control, so it won't do in the long term.

I'm also not sure about IPFS - technically it's an ideal solution, but it might present legal issues unless we have a sure way of thoroughly removing packages from the repo. This could probably be solved with sufficient legal disclaimers, but IANAL etc. I'm still itching to try it out. ☺️

**Comment by hdgarrood** [comment]
WRT to editorial control and being able to remove packages if we are ever legally obliged to, I think we could solve this in an IPFS system by having a single 'repository' which we control, which is just a file containing a mapping from pairs (package name, version) to references to package tarballs. That's what https://github.com/whyrusleeping/gx does.

**Comment by paf31** [comment]
The reason I like using Git is that it's simple, and there are a wealth of existing tools. If we need to remove a package, we just remove it. And it's very easy to migrate to a hosted Git server later if we want/need to, even hosting copies of packages on the same Git server if necessary. But the abstractions stays the same, and other package sets can continue to use GitHub or whatever else for hosting.

I'm planning to write up a detailed proposal for `psc-package` soon, including how it would integrate with things like Pursuit and Try PureScript.

**Comment by shmish111** [comment]
I'd just like to chip in as a PS user, you may be farther along than some of you seem to think, people are using PS seriously enough to hav real concerns about this stuff. I've started using PS at work after making a decision between Elm and PS and although PS is in my mind clearly a better language, the package management of Elm is much better and that made Elm a serious contender. One thing not mentioned here either is that it's important in some places to be able to easily mirror a repo internally.  Please don't let dependency management be thought of as a second class citizen like it is with so many other languages, it really can make or break it.

**Comment by hdgarrood** [comment]
@shmish111 None of us underestimate the importance of package management. The fact is that it takes a lot of time to do these things properly, and none of us are paid to work on the PureScript language or tools full time. I personally am always trying to make a tradeoff between what I think is likely to benefit the ecosystem the most for the least amount of effort, and also what I can realistically get done in the small chunks of time I can find to work on PureScript (I think trying to address a big project like this one is quite difficult if you're working in this manner).

The good news is that if PureScript package management is that important to you in a commercial context, I'd very happily accept payment in return for working on it full time over the summer. (Here isn't the place to discuss this, so email me if you're interested).

**Comment by jdegoes** [comment]
Here are some ideas I like:

 * **Composable Packages**. One package can be a composite of others, etc. 
 * **Git-Defined Dependencies**. Require specification of Git URL + hash / tag.
 * **User-Defined Resolution**. While default resolution would be "identity", users can specify their own resolution mechanism if they wish to map specify URLs to internal or backup repositories.

And one of:

 * **Centralized Backups**. While Git URLs specify dependencies, they are not actually used for downloading dependencies. Rather, adding a Git URL as a dependency forces a download and backup of the repository to a centralized (& user-configurable) source, which is then used as the source of the Git URL going forward for all clients. Thus, if a build succeeds once, it always succeeds.
 * **Decentralized Backups**. While Git URLs specify dependencies, they are not actually used for downloading dependencies. Rather, adding a Git URL as a dependency forces a shallow download and storage of the contents in the local package (`psc-components`?), which are then checked in as per usual. Thus, each package maintains its local dependencies (essentially local caches of Git URLs) and other tools can decide if dependencies are compatible through API comparisons. Thus, if a build succeeds for some project one time, it always succeeds on that same project.

Of these two, I'd have a slight preference for the decentralized version, because the API-level comparisons it enables would be really nice for determining actual compatibility between the same dependency transitively required (rather than semvar which is a weak indication at best).

**Comment by paf31** [comment]
I'm going to close this, but we should open separate issues on the psc-package repo as necessary.
