### ISSUE TITLE
Compile failure for `purescript-0.10.4`

### ISSUE THREAD

**Issue by hvr** [purescript/purescript#2528]
See https://hackage.haskell.org/package/purescript-0.10.4/reports/1

I've been able to track down the problem to `bower-json` and I've updated the metadata on Hackage so users won't run into the same compilation error

https://hackage.haskell.org/package/purescript-0.10.4/revisions/

**Comment by hdgarrood** [comment]
Thanks!

**Comment by ilovezfs** [comment]
Same failure in Homebrew: https://bot.brew.sh/job/Homebrew%20Core/13984/version=el_capitan/console

**Comment by hdgarrood** [comment]
I think maybe this is happening a bit too often now. When I get a chance I'm going to investigate adding a CI job which checks that `cabal` is able to resolve dependencies.

Is homebrew still having issues now that the version bounds on Hackage have been amended?

**Comment by ilovezfs** [comment]
Yes, using https://hackage.haskell.org/package/purescript-0.10.4/purescript-0.10.4.tar.gz.

With Sierra (for which we use GHC 8.0.2-rc2):
https://bot.brew.sh/job/Homebrew%20Core/13988/version=sierra/console

With Yosemite and El Capitan:
```
[101 of 141] Compiling Language.PureScript.Docs.RenderedCode.Types ( src/Language/PureScript/Docs/RenderedCode/Types.hs, dist/dist-sandbox-8ca1132/build/Language/PureScript/Docs/RenderedCode/Types.o )

src/Language/PureScript/Docs/RenderedCode/Types.hs:82:5: warning: [-Wname-shadowing]
    This binding for ‘<|>’ shadows the existing binding
      imported from ‘Data.Aeson.BetterErrors’ at src/Language/PureScript/Docs/RenderedCode/Types.hs:39:1-30
      (and originally defined in ‘Data.Aeson.BetterErrors.Internal’)
[102 of 141] Compiling Language.PureScript.Docs.RenderedCode.Render ( src/Language/PureScript/Docs/RenderedCode/Render.hs, dist/dist-sandbox-8ca1132/build/Language/PureScript/Docs/RenderedCode/Render.o )
[103 of 141] Compiling Language.PureScript.Docs.RenderedCode ( src/Language/PureScript/Docs/RenderedCode.hs, dist/dist-sandbox-8ca1132/build/Language/PureScript/Docs/RenderedCode.o )
[104 of 141] Compiling Language.PureScript.Docs.Types ( src/Language/PureScript/Docs/Types.hs, dist/dist-sandbox-8ca1132/build/Language/PureScript/Docs/Types.o )

src/Language/PureScript/Docs/Types.hs:416:48: error:
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected type: String -> Either BowerError PackageName
        Actual type: Text -> Either BowerError PackageName
    • In the first argument of ‘withString’, namely ‘parsePackageName’
      In the first argument of ‘perhaps’, namely
        ‘(withString parsePackageName)’
      In the second argument of ‘key’, namely
        ‘(perhaps (withString parsePackageName))’

src/Language/PureScript/Docs/Types.hs:535:72: error:
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected type: Text -> Text
        Actual type: Text -> String
    • In the second argument of ‘(.)’, namely ‘T.unpack’
      In the second argument of ‘(.)’, namely
        ‘parsePackageName . T.unpack’
      In the first argument of ‘eachInObjectWithKey’, namely
        ‘(mapLeft ErrorInPackageMeta . parsePackageName . T.unpack)’

src/Language/PureScript/Docs/Types.hs:560:61: error:
    • Couldn't match type ‘Text’ with ‘[Char]’
      Expected type: PackageName -> String
        Actual type: PackageName -> Text
    • In the second argument of ‘(.)’, namely ‘runPackageName’
      In the first argument of ‘assocListToJSON’, namely
        ‘(T.pack . runPackageName)’
      In the second argument of ‘(.=)’, namely
        ‘assocListToJSON
           (T.pack . runPackageName)
           (T.pack . showVersion)
           pkgResolvedDependencies’
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
```

**Comment by hvr** [comment]
@ilovezfs Is there any chance homebrew could pick up the `.cabal` meta-data revisions? I'd expect this to become a problem in the long-run as Hackage is relying more and more on revisions for metadata-only fixups that don't require a more costly full  release upload.

Here's e.g. how Cabal's bootstrap.sh shell script fetches the latest `.cabal` revisions:

https://github.com/haskell/cabal/blob/master/cabal-install/bootstrap.sh#L320-L350

**Comment by ilovezfs** [comment]
@hvr `cabal update` isn't sufficient?

**Comment by ilovezfs** [comment]
@hvr the main issue with that for Homebrew would be the lack of checksums for those cabal files, but since it's https we could probably :see_no_evil: if it's necessary and we don't want to add them one by one. That said, it would be good if this were handled by cabal update or if there were a "cabal get-metadata" command of some kind to retrieve them and ideally checksum them too.

**Comment by hvr** [comment]
@ilovezfs I've been meaning to add some sub-command which allows to dump the raw .cabal file from the pkg index (`cabal info --raw foo-1.2.3` or maybe extend `cabel get` to retrieve the `.cabal` file w/o unpacking), possibly with the ability to select the exact revision to dump (`cabal get` already supports that more or less, but it also unpacks the tarball before (over)writing the `.cabal` file).

**Comment by ilovezfs** [comment]
@hvr without modifying our backend here's how it looks currently to do what you're recommending: https://github.com/Homebrew/homebrew-core/pull/8397/files

Note that for purescript to build with GHC 8.0.2, turtle is going to need the `directory` constraint bumped for turtle-1.2.8.

**Comment by hvr** [comment]
@ilovezfs I've commented at the homebrew PR

**Comment by ilovezfs** [comment]
@hvr :bowing_man: much appreciated. Had no idea about /1.cabal link.
