### ISSUE TITLE
Breaking change to pursuit JSON format

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2530]
Trying to use the current Pursuit package database with the new compiler gives you errors such as:

> When parsing Language.PureScript.Kinds.Kind expected an Object with a tag field where the value is one of [KUnknown, Row, FunKind, NamedKind], but got Bang.

In retrospect it makes sense why this would be a breaking change but it's easy to see how we missed it initially. I think the easiest way to address this might be to add a special case for kinds which were moved to Prim into the parsers in `Language.PureScript.Docs` and release it as 0.10.5; does that sound sensible?

*edit:* to clarify, it should be possible to restore backwards compatibility with this approach so that JSON generated with e.g. 0.10.3 is still usable.

**Comment by paf31** [comment]
Yes, a 0.10.5 release makes sense to me.
