### ISSUE TITLE
Type class deriving errors don't include location

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#2543]
```
[1/8 CannotFindDerivingType]

  Cannot derive a type class instance, because the type declaration for VarMapValue could not be found.
```

**Comment by paf31** [comment]
Can we merge this with #1801?

**Comment by natefaubion** [comment]
We can, but I honestly think any error that has zero information (not even a module name!) should be prioritized.

**Comment by paf31** [comment]
Yes, but there are others which also have no information, and I want to avoid one issue per error type. Maybe we can just have two issues to track the two categories.
