### ISSUE TITLE
Better documentation for dead code elimination

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2545]
@Pauan and @wegry have been working on bundling using Rollup (see #2207)

The implementation of `psc-bundle` relies on some guesswork as to the output of the compiler, and the result is that it is quite fragile. It can be difficult to understand why some FFI code works when bundled and some doesn't. 

I would very much like to reduce the scope of `psc-bundle` before 1.0. I would remove almost all of the features except for concatenating our Common JS output, shimming `require` if necessary, and outputting source maps. This is the minimum needed to support PSCi in the browser, and Try PureScript, both of which use `psc-bundle` for serving compiled dependencies.

**Comment by hdgarrood** [comment]
My aim now is to get `pulp` to a point where `pulp build --to bundle.js` uses Rollup instead of `psc-bundle`; hopefully I can do that in a way that isn't a breaking change. We might even be able to deprecate `pulp browserify` too, as my impression is that the standard PureScript+Rollup setup already takes care of including code from `node_modules`. I'd like to wait until after we have a released version of Pulp working in this way before we start looking at this.

**Comment by hdgarrood** [comment]
Also, does this affect #1239 at all?

**Comment by hdgarrood** [comment]
I think #2206 is a prerequisite for doing this. I'm not sure if we knew this already but Rollup doesn't deal well with how we codegen data constructors right now. See [this example](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlNUNuJTVDJTIydXNlJTIwc3RyaWN0JTVDJTIyJTNCJTVDbiU1Q24lMkYlMkYlMjBBcyUyMGdlbmVyYXRlZCUyMGJ5JTIwcHNjJTIwMC4xMC41JTVDbnZhciUyMEp1c3QlMjAlM0QlMjAoZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmdW5jdGlvbiUyMEp1c3QodmFsdWUwKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aGlzLnZhbHVlMCUyMCUzRCUyMHZhbHVlMCUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwSnVzdC5jcmVhdGUlMjAlM0QlMjBmdW5jdGlvbiUyMCh2YWx1ZTApJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMG5ldyUyMEp1c3QodmFsdWUwKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwSnVzdCUzQiU1Q24lN0QpKCklM0IlNUNuJTVDbiUyRiUyRiUyMEh5cG90aGV0aWNhbCUyMGFsdGVybmF0aXZlJTVDbmZ1bmN0aW9uJTIwSnVzdEFsdCh2YWx1ZTApJTIwJTdCJTVDbiUyMCUyMHRoaXMudmFsdWUwJTIwJTNEJTIwdmFsdWUwJTNCJTVDbiU3RCU1Q25KdXN0QWx0LmNyZWF0ZSUyMCUzRCUyMGZ1bmN0aW9uKHZhbHVlMCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwbmV3JTIwSnVzdEFsdCh2YWx1ZTApJTNCJTVDbiU3RCU1Q24lNUNuJTJGJTJGJTIwRVMyMDE1JTIwY2xhc3MlNUNuY2xhc3MlMjBKdXN0Q2xhc3MlMjAlN0IlNUNuJTIwJTIwY29uc3RydWN0b3IlMjAodmFsdWUwKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB0aGlzLnZhbHVlMCUyMCUzRCUyMHZhbHVlMCUzQiU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwJTVDbiUyMCUyMHN0YXRpYyUyMGNyZWF0ZSh2YWx1ZTApJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMG5ldyUyMEp1c3RDbGFzcyh2YWx1ZTApJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBjYW5ub3QlMjBiZSUyMGRldGVybWluZWQlMjB0byUyMGJlJTIwcHVyZSUyMGFuZCUyMGlzJTIwbGVmdCUyMGluJTVDbm5ldyUyMEp1c3QoMCklM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBpcyUyMHJlbW92ZWQlNUNubmV3JTIwSnVzdEFsdCgwKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGlzJTIwYWxzbyUyMG5vdCUyMHJlbW92ZWQlNUNubmV3JTIwSnVzdENsYXNzKDApJTNCJTVDbiUyMiU3RCU1RCU3RA==).

Note that my example also contains an ES2015 class version of how we might codegen the `Just` data constructor, and Rollup can't determine that to be pure right now either. However the author has expressed interest in dealing with that case on the issue tracker. So I guess we will want to codegen data constructors as ES2015 classes eventually, but probably not just yet.

**Comment by hdgarrood** [comment]
I think https://github.com/rollup/rollup/issues/1263 is also a prerequisite for this.

**Comment by nwolverson** [comment]
@hdgarrood isn't it currently the case that you might use `pulp build --to bundle.js` where you want to keep the `require` of any node modules, while browserify will also bundle the node modules? Is that just a case of [pulp] using different rollup config in each case?

**Comment by hdgarrood** [comment]
That is the case, yes. I don't know whether the former is possible at the moment with rollup-plugin-purs, although I'd guess that it is. Perhaps @Pauan knows?

**Comment by Pauan** [comment]
@nwolverson @hdgarrood At my job I use Rollup to bundle both browser and Node.js programs. Both work perfectly fine: by default, if you import an npm module, Rollup will treat it as external, which means that it isn't bundled.

If you *want* the npm dependencies to be bundled, you can use the [`rollup-plugin-node-resolve`](https://github.com/rollup/rollup-plugin-node-resolve) plugin. You might also need [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs)

Unfortunately, the `rollup-plugin-node-resolve` plugin is mandatory with `rollup-plugin-purs` (at least for now), which means that npm dependencies are *always* bundled.

So what if you *don't* want your npm dependencies to be bundled? You can use the [`external`](https://github.com/rollup/rollup/wiki/JavaScript-API#external) property to mark certain modules as being external:

```
import purs from "rollup-plugin-purs";
import resolve from "rollup-plugin-node-resolve";

export default {
  entry: "src/Main.purs",
  dest: "bundle.js",
  format: "iife",
  sourceMap: true,
  plugins: [
    purs(),
    resolve()
  ],
  external: [
    "lodash"
  ]
};
```

This isn't great, so I'd like if `psc` could be changed so that we don't need `rollup-plugin-node-resolve` anymore.

**Comment by Pauan** [comment]
I filed [an issue](https://github.com/purescript/purescript/issues/2621) about `psc`

**Comment by paf31** [comment]
What features should `psc-bundle` support at 1.0? I'm assuming we'll move to ES6 modules and get rid of DC, recommending Rollup instead. But if DCE is removed, what's left? Just a generic ES6 bundler? We will need _something_ to bundle output modules in PSCi and Try PureScript, but it doesn't need to support much else.

So if we move to ES6, then how would we bundle our output modules? Presumably we'd have to write something to parse the ES6 modules we generate, and then rebundle them as ES3/ES5? That seems ugly to me. Are there any better options?

**Comment by hdgarrood** [comment]
If we avoid all ES6 features other than ES6 modules in codegen (which I think we should for the time being), my impression is that the code that this hypothetical reduced-scope psc-bundle would produce would automatically be suitable for consumption by basically any browser..?

**Comment by Pauan** [comment]
@paf31 Earlier I recommended using Rollup to do the bundling. Rollup can be run in the browser, and you can also disable tree shaking if you want it to run faster. The Rollup API is pretty simple and stable as well.

By itself Rollup only bundles ES6 modules, it doesn't do any transpiling, so if you disable tree shaking it should be quite fast. I think it's the easiest and most minimal solution (aside from creating a custom ES6 bundler from scratch).

Also, even if `psc` generates ES6 modules, most FFI files will still be using CommonJS, so you'll probably still need to use `rollup-plugin-purs` (but with optimizations disabled, for increased speed).

**Comment by hdgarrood** [comment]
I think the goal here is minimising dependencies / not needing Node rather than speed, though. It seems like running Rollup inside the browser might be the way to go, then, maybe?

**Comment by Pauan** [comment]
@paf31 Aside from Rollup, the other alternative would be to take the ES6 modules, transpile them to CommonJS modules, concatenate all of the CommonJS modules, and then use a small `require` shim.

**Comment by paf31** [comment]
Well, right now Try PureScript and PSCi bundle the dependencies once and cache the result, which will be much faster than doing the same work each time in the browser. That's why I'd like to try to support bundling in the compiler if we can.

**Comment by paf31** [comment]
Also, I expect some libraries will continue to use CommonJS for foreign modules, if we leave that as an option, but I think we should recommend that foreign modules also be written as ES6 modules going forward.

**Comment by paf31** [comment]
Perhaps we could support both types of modules in the code generator, and then use a require shim, as you suggest @Pauan.

> If we avoid all ES6 features other than ES6 modules in codegen (which I think we should for the time being)

Well I think we will need to start using `let` or `const` instead of `var`, to fix a scope issue related to TCO (#2689). At that point, we might as well start using some other features, like arrows instead of `function() { ... }`, especially if we're going to keep the CJS code generator around anyway.

**Comment by Pauan** [comment]
@paf31 I don't think having two separate code-gens will handle everything, because FFI files will be using ES6 modules. So you really do need to have some kind of ES6 bundler, or an ES6->CommonJS converter.

As for `let`, `const`, arrow functions, etc. that's all great, but in that case it will be necessary to use `rollup-plugin-babel` to bundle PureScript code (in addition to `rollup-plugin-purs`). And you get into sticky situations with ES6 polyfills. So that's something to keep in mind.

**Comment by michaelficarra** [comment]
@paf31 The difficulty of writing your own module bundler has little to do with the module bundling; @shapesecurity [did it in Java](https://github.com/shapesecurity/bandolier), and it was a piece of cake. You'll first need a decent parser (or similar) that supports import/export declarations. I think the easiest way to get here would be somebody from the PureScript community adding support for just import/export declarations to language-javascript.

> Also, I expect some libraries will continue to use CommonJS for foreign modules, if we leave that as an option, but I think we should recommend that foreign modules also be written as ES6 modules going forward.

I hope we can get away with not supporting CommonJS foreign modules at all. But a `require` shim will probably work if we want to support legacy modules.

**Comment by gasi** [comment]
> @michaelficarra I think the easiest way to get here would be somebody from the PureScript community adding support for just import/export declarations to language-javascript.

Started work on that in https://github.com/erikd/language-javascript/pull/79

**Comment by kevinbarabash** [comment]
I did some work this weekend on updating the compiler to output ES6 modules.  I thought that rollup would do a better job of removing dead code.  The main issue is that it doesn't remove any top level statements that are function calls such as:
```
let boundedMillisecond = new Bounded(function () {
    return ordMillisecond;
}, 0, 999);
```
In my program, I don't use `boundedMillisecond` nor does anything else and in fact `boundedMillisecond` exists only once in the bundle – in its declaration.

I'm planning on writing a script to post-process the rollup output to remove all of these unused objects. 
The nice thing about the rollup output is that all of these statements are the top level which should make it easier to do this analysis.

**Comment by wegry** [comment]
@kevinbarabash Size considerations taking minification into consideration are probably the most faithful to real world scenarios. Depending on the level of integration with the JS ecosystem you intend to keep, you might want to take a look at the `toplevel` and `sideEffects` flags in [uglify](https://github.com/mishoo/UglifyJS2). 

The uglify `warnings` flag will let you know if code is being dropped. I can't remember if constructors(?) are skipped by default or not.

If purescript now outputs anything at a syntax level above ES5 (i.e. the `let` in your example)  besides module syntax, you may have to try with something like terser instead.

**Comment by rhendric** [comment]
Made irrelevant by #4255.
