### ISSUE TITLE
Allow data and type synonym declarations in let bindings

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#255]
e.g. 

    example = let data Foo a b c = Foo a (Either b c) in ...

where the type Foo is not allowed to leak into the type signature of `example`.

**Comment by MrMormon** [comment]
All referencing issues are closed. Is it time to say goodbye?

**Comment by hdgarrood** [comment]
I don't think this issue should be closed right now. The referencing issues are vaguely related, but the fact that they're all closed doesn't say anything about the state of this one.

**Comment by hdgarrood** [comment]
We do already have a pretty good solution for this problem, incidentally: just put the data declaration into a separate module, together with functions that need to know about it, and don't export the data declaration. Re-exports make this more viable, too.

**Comment by paf31** [comment]
Closing, due to lack of discussion and interest.
