### ISSUE TITLE
Derive Bounded and Enum

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#2555]
Would be very nice to be able to derive these in the trivial cases outlined in the Haskell 98 report (https://www.haskell.org/onlinereport/derived.html sections 10.2 and 10.3).

**Comment by matthewleon** [comment]
On further thought, since Enum is not part of the prelude, I imagine it only makes sense to do this for Bounded. Feedback?

**Comment by paf31** [comment]
These could also be derived using `generics-rep`.

**Comment by matthewleon** [comment]
@paf31 since `Enum` is not part of the prelude, it seems like `generics-rep` is the right way to do it for that. For `Bounded` however, do you have any clear preference?

**Comment by paf31** [comment]
`Bounded` deriving seems like it might be a bit ad-hoc, since there isn't a good single set of laws for `Bounded` yet. So `generics-rep` might be the right way to prototype it, and see if it works well.

**Comment by paf31** [comment]
Please open an issue on `generics-rep` if that solves the problem. Thanks!
