### ISSUE TITLE
undefined inhabits Void

### ISSUE THREAD

**Issue by minad** [purescript/purescript#2557]
~~~ haskell
undefined :: forall a. a
undefined = (\_ -> undefined) "foo"

void :: Void
void = undefined
~~~

Is this a problem with the scoping?

**Comment by garyb** [comment]
You can use that `undefined` anywhere, since `forall a. a` will unify with everything.

**Comment by paf31** [comment]
Thanks for the report, but this is a known limitation of the way we handle scoping. We do disallow things like

```purescript
undefined = undefined
```

since that would lead to an actual `undefined` (in the JS sense) at runtime.

We require self-recursion to be guarded by a function for this reason. Unfortunately, that means your `undefined` passes the checker, even though it's obviously not a good definition.

**Comment by minad** [comment]
well, but undefined returns javascript "undefined"

**Comment by minad** [comment]
@paf31 I would still argue that the scoping should be fixed. Is there some known limitation preventing that?

**Comment by paf31** [comment]
How would you fix it?

**Comment by garyb** [comment]
Could we check when we have a recursive lambda to see if the lambda is evaluated as part of its definition?

**Comment by paf31** [comment]
I'd rather not make the check more complicated. I don't think it's possible to solve this in general, and what we have now seems like a decent approximation.

**Comment by minad** [comment]
@paf31 You could allow only lambdas in recursive bindings. But then you lose many cases which work right now, e.g., recursive monads.

I haven't found a better solution yet. I was toying around with my own small strict lambda interpreter and had the same problem.

**Comment by garyb** [comment]
I dunno, it seems like a rather big flaw if the typechecker will let runtime-undefined definitions through!

It is tricky though, as yeah, I've already thought of a way that the check I described is not good enough...

**Comment by minad** [comment]
@garyb It is a big flaw.

**Comment by paf31** [comment]
It is a big flaw in any language with general recursion.

**Comment by minad** [comment]
@paf31 Yes, but I would expect an endless loop, but not undefined.

This is what I meant concerning recursive bindings:

~~~ haskell
data Expr
  = LetAtom Atom Expr
  | LetLambda [(Name, Lambda)] Expr --- Recursive lambdas
  | ...
~~~

**Comment by paf31** [comment]
How is an endless loop more useful?

**Comment by garyb** [comment]
It doesn't really help, requiring recursion to be explicit, as the problem still exists though right?

**Comment by minad** [comment]
I would argue that the only possible bad behaviour in a non-total language should be an endless loop. But this is just my opinion.

@garyb If recursion is explicity allowed in the core language only for functions then this problem would not occur.

**Comment by garyb** [comment]
@paf31 it's a little easier to figure out what's going on if the program stalls while evaluating definitions vs an undefined popping up somewhere later on.

**Comment by minad** [comment]
@paf31 I think my opinion is the commonly accepted one. For example in the dependent haskell proposal by Eisenberg, equality proofs must be evaluated to keep the type system sound. This means that fake proofs would loop. But in this case here, we get "undefined", which means the type system is not sound in the sense of Haskell.

**Comment by garyb** [comment]
@minad I'm not sure I follow... but nevermind, as I don't think we're likely to change the language that fundamentally at this point given general recursion usage is already very common.

**Comment by paf31** [comment]
I'm saying this is impossible because it requires us to solve the halting problem. What's the solution?

**Comment by minad** [comment]
@paf31 How is this equivalent from the halting problem? I am just asking to detect the invalid scoping as in this case, not checking totality in general.

**Comment by paf31** [comment]
I'd also like to point out that Elm does the exact same thing. I say Elm because it's the one strict language with an online editor that I know of. I can check others.

**Comment by minad** [comment]
Again, what would solve the issue is if one allows only lambdas in the recursive bindings (as in the LetLambda above), since then the bound functions are well defined in javascript.

~~~ js
var f1, f2;
f1 = function() { calls f2 }
f2 = function() { calls f1 }
~~~

What you allow right now is something like this:

~~~ js
var x;
x = (function() { use x here while it is not yet defined })(...);
~~~

**Comment by paf31** [comment]
That disallows too many useful things though.

**Comment by minad** [comment]
@paf31 Yes, indeed 😞 So the only acceptable solution is modifying the checker. But nevermind, I was just playing around - I don't think fixing this issue is very important, since this problem probably wouldn't occur in normal use. Thx for the quick responses!

**Comment by paf31** [comment]
Sure, and sorry the answer is so disappointing. I agree it's not ideal, but I've thought quite a bit about this in the past, and this is the best approximation I could come up with, with decent trade-offs.

**Comment by minad** [comment]
Hmm, I think it could be solved by wrapping in functions (like introducing laziness).

Currently ps generates:

~~~ js
var $$undefined = (function (v) {
    return $$undefined;
})("foo");
~~~

Replace this with:

~~~ js
var $$undefined2 = function() { (function (v) {
    return $$undefined2();
})("foo") };
var $$undefined = $$undefined2();
~~~

This would also work for mutually recursive bindings. But I don't really like this transformation since it would recompute things when it isn't really necessary.
