### ISSUE TITLE
Can't type in repl when 'pulp psci'

### ISSUE THREAD

**Issue by pfeodrippe** [purescript/purescript#2561]
I'm not able to write anything at the psci repl.
I can ```CTRL+Z```, but not anything beyond this.
I'm in a 10.12 OSX in a macbook pro 2012 and just installed everything as in https://leanpub.com/purescript/read
 
```bash
PSCi, version 0.10.5
Type :? for help

>
```

**Comment by hdgarrood** [comment]
What version of node.js are you using?

**Comment by hdgarrood** [comment]
That's a rather old one, could you try upgrading that first?

**Comment by pfeodrippe** [comment]
Ok, now working with node v7.4.0.

Thanks, @hdgarrood!

**Comment by hdgarrood** [comment]
You're welcome, that's great to hear :)
