### ISSUE TITLE
Internal error: "Unknown type index in checkOrphanInstance"

### ISSUE THREAD

**Issue by joshuahhh** [purescript/purescript#2562]
I ran into an internal error ("Unknown type index in checkOrphanInstance") during compilation, and was able to strip the offending code down to:

```purescript
import Prelude
import Control.Monad.Writer (class MonadTell, WriterT)

newtype Wrapper m a = Wrapper (
  WriterT Unit m a
)

derive newtype instance monadTellChangeableT ∷ Monad m => MonadTell (Wrapper m)
```

This code is invalid because `MonadTell` takes two type parameters. If I replace `MonadTell (Wrapper m)` with `MonadTell Unit (Wrapper m)`, the code compiles successfully.

Thanks. 😃

**Comment by paf31** [comment]
Thanks for the report!

@LiamGoodacre You might be able to guess what's going on here, but I'll take a look this weekend if it's not obvious.

**Comment by LiamGoodacre** [comment]
In the orphan instance check there is an assumption that the class has all the arguments it expects.  I can look into a fix for this later this evening.
