### ISSUE TITLE
Support custom warnings using a Warn type class, analogous to Prim.Fail

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#2564]
Say you have your own Prelude or helpers module. You define the following function:
```haskell
todo :: forall a. a
todo = unsafeCoerce unit
-- AKA "undefined" in Haskell.
```

It's useful in dev, but you want to make sure it always produces a warning so you remember to remove it (or, have your CI fail the build because you've turned on `--strict` when building with purescript-psa).

How would you want to accomplish something like this? [In Haskell](https://github.com/ambiata/p/blob/ecd9c62bb682a9f9f9e8f148d6d5e6d0295f3bca/src/P/Debug.hs#L37-L39), it's:
```haskell
{-# WARNING trace "Do not use 'trace' in production code" #-}
trace :: P.String -> a -> a
trace = T.trace
```

There's has previously been [some resistance to introducing an INLINE pragma](https://github.com/purescript/purescript/issues/2345); I don't know if that objection is across the board.

Any thoughts?

**Comment by LiamGoodacre** [comment]
A cheap way of doing this with an error at the moment is to define the function in a module that you use when developing, but don't include the module when building for production.

**Comment by paf31** [comment]
I'm not a fan of pragmas in general, but I see why something like this is useful for real-world programming in PureScript. I prefer the idea of having an external linter with customizable linting rules.

Another option is to use a variant on customizable errors, i.e. adding a `Warning :: Symbol -> Constraint` class to `Prim` and having the solver discharge the constraint automatically with a warning.

**Comment by LiamGoodacre** [comment]
A `Warning` class is quite nice; and it's consistent with `Fail`.

**Comment by garyb** [comment]
Making it a real part of the language with something like that would be my preference too.

**Comment by paf31** [comment]
Ok, I'll change the title and move this to approved then. This should be relatively simple since we already have all of the work done for `Fail`.
