### ISSUE TITLE
Check everything required by a derived `Newtype` is exported

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2565]
`ListT` has a `Newtype` instance but the `Step` type used in the `newtype` is not exported from the module:

https://github.com/purescript/purescript-transformers/blob/7b82f15ef5452a720e1728f2f5b134204570c08f/src/Control/Monad/List/Trans.purs#L241

**Comment by LiamGoodacre** [comment]
Could you explain how this is a bug?

**Comment by hdgarrood** [comment]
The `Newtype` instance allows you to get at the `Step` inside a `ListT`, but I think whenever we try to export a function which mentions some unexported type, we should get a `TransitiveExportError`.

**Comment by LiamGoodacre** [comment]
To enforce this generally, I think the following implementation is correct: for a public class, if the head type of at least one argument in any covering set of functional dependencies is exported, then all mentioned types in the instance need to also be exported.  Does that make sense?

Or more simply put: if an instance could possibly be referenced outside of the defining module then every mentioned type must be accessible.

**Comment by LiamGoodacre** [comment]
Sorry that should be "all arguments in any covering set".

**Comment by garyb** [comment]
Actually, this might not really be a problem. If you try to use `unwrap` outside of the module it says there's no instance. I think that's acceptable?

**Comment by paf31** [comment]
The problem is that I don't think we have the covering set information at the point where we'd throw the error. But I'd be fine with a more conservative check, in which every mentioned type had to be exported.

**Comment by paf31** [comment]
This bug would also apply to derived `Generic` instances (in the `generic-rep` sense), yes?

**Comment by garyb** [comment]
I'm going to close this, as I don't think it actually is an issue. Or at least, not in a way that causes real problems - you can use the instances privately, but they will fail to resolve elsewhere. So yeah, you don't find out that there's a problem until later perhaps, but it's not actually _wrong_ per se.
