### ISSUE TITLE
Disappearing constraints

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2567]
I've noticed that if you specify a constraint but don't use it, then it never gets checked:
```purescript
-- no error
class M s
foo :: forall t. t -> Int
foo = ((\_ -> 0) :: M t => t -> Int)
```

```purescript
-- no error
foo :: Int
foo = (0 :: Fail "Bananas" => Int)
```

```purescript
-- fails
foo :: Int
foo = (0 :: Fail "Bananas" => Int) + 1
```

**Comment by paf31** [comment]
I know where the problem is here, and I have a fix, but it relies on disabling the skolem escape checker, like my other recent type checker bug fix ☹️ 

I think it might be time to think hard about how to reimplement the skolem escape check.
