### ISSUE TITLE
Suggest pulp when running psci without arguments

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2573]
There's been talk about this in IRC many times and I couldn't find an issue for it.

Currently if you run `psci` without arguments it'll show:
```
PSCi requires the psci-support package to be installed.
You can install it using Bower as follows:

  bower i purescript-psci-support --save-dev

Or using psc-package:

  psc-package install psci-support

For help getting started, visit https://github.com/purescript/documentation/blob/master/PSCi.md
```

It does mention `pulp psci` on the linked page, but I think we should display it here too.

Something along the lines of:

```
> psci
No input given to PSCi; try running `pulp psci` instead.
For help getting started, visit https://github.com/purescript/documentation/blob/master/PSCi.md
```

**Comment by hdgarrood** [comment]
:+1: :+1: :+1:

**Comment by nwolverson** [comment]
Should this not at least indicate the proper usage of psci (i.e. `psci [input glob]`) as well as suggesting pulp?

**Comment by noraesae** [comment]
How about defaulting `[input glob]` part to `psci 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs'`, which may be the most common use case? I sometimes just want to check something very quickly wich `psci`, like how I usually do with `ghci`.

The usage will be like below:

### with neither pulp nor psci-support

```
> psci 
With Pulp, try running `pulp psci` instead.

Without Pulp, PSCi requires psci-support to be installed.
You can install it using Bower as follows:

  bower i purescript-psci-support --save-dev

Or using psc-package:

  psc-package install psci-support

For help getting started, visit https://github.com/purescript/documentation/blob/master/guides/PSCi.md
```

### with psci-support

```
> psci
```

... just defaults to ...

```
> psci 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs'
```

**Comment by noraesae** [comment]
Also, the documentation URL should be modified to https://github.com/purescript/documentation/blob/master/guides/PSCi.md.

**Comment by hdgarrood** [comment]
It's a good suggestion, but I'd rather not do that, because we're trying to remove any hardcoded assumptions of particular package managers from the compiler; see #2604.

**Comment by noraesae** [comment]
I can understand. Then this issue may be obsolete?

**Comment by hdgarrood** [comment]
No, I think suggesting Pulp is still a good idea (Pulp isn't a package manager).

**Comment by noraesae** [comment]
Oh, right. I will work on this in a while.

**Comment by noraesae** [comment]
The current `ghc` prints the following message when run without input:

```
> ghc
ghc: no input files
Usage: For basic information, try the `--help' option.
```

It may be nice to show the `Usage:` section for `psc` and `psci` too? The current `psc` prints the following.

```
> psc
psc: No input files.
```

What I suggest:

```
> psc
psc: No input files.
Usage: For basic information, try the `--help' option.

> psci
psci: No input files; try running `pulp psci` instead.
For help getting started, visit https://github.com/purescript/documentation/blob/master/guides/PSCi.md
Usage: For basic information, try the `--help' option.
```

If it looks okay, I will use the sentences. Also, this may be better be done after #2633?

**Comment by vendethiel** [comment]
> What I suggest:

I'm not sure. I often launch a `ghci` just to try some stuff out without a need for any of my project's files.

**Comment by hdgarrood** [comment]
If you run ghci with no input files, you still get all of `base` and the contents of the global package db, so it makes sense to do that. PureScript has nothing corresponding to either of these things - no built in libraries, no global package db - so I think it's very rare that you do actually want to run psci with no input files.

@noraesae your suggestion looks good to me. Also I would recommend waiting until after #2633 is merged.

**Comment by noraesae** [comment]
I may wait for #2632 to be merged too.
