### ISSUE TITLE
Large amount of time in loop spent in instanceof

### ISSUE THREAD

**Issue by theqabalist** [purescript/purescript#2577]
Hi, this is less of an issue, and more of a discussion for my understanding.  I did advent of code 2016 in node, and I was going back to do some of the problems in PS.  One of the problems I reimplemented, and I noticed that the performance was degrading with fringe size (in A*).  I profiled the outputted code and noticed that 1/3rd of the time was spent in C++ instanceof checks, and I was looking at the referenced javascript code.  I notice that instanceof is used extensively for the pattern matching mechanism, and was curious if this is the most performant way to do pattern matching or if something like performance on an operator like that cannot be predictably evaluated ahead of time, and you have to take what you can get.  A second part of my question is how you would go about reducing the number of these checks, because it would seem like avoiding pattern matching loses quite a bit of robustness in expression.

Here is a profile preview for reference
```
89758   90.0%   33.6%  v8::internal::Runtime_InstanceOf(int, v8::internal::Object**, v8::internal::Isolate*)
9350    9.4%    3.5%  v8::internal::Runtime_Interrupt(int, v8::internal::Object**, v8::internal::Isolate*)
88    0.1%    0.0%  v8::internal::Runtime_ToInteger(int, v8::internal::Object**, v8::internal::Isolate*)
88    0.1%    0.0%  v8::internal::Object::GetMethod(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Name>)
```

Referencing code like

```
var lookup = function (dictOrd) {
    return Partial_Unsafe.unsafePartial(function (dictPartial) {
        return function (k) {
            return function (tree) {
                if (tree instanceof Leaf) {
                    return Data_Maybe.Nothing.value;
                };
                var comp = Data_Ord.compare(dictOrd);
                var __unused = function (dictPartial1) {
                    return function ($dollar42) {
                        return $dollar42;
                    };
                };
                return __unused(dictPartial)((function () {
                    if (tree instanceof Two) {
                        var $177 = comp(k)(tree.value1);
                        if ($177 instanceof Data_Ordering.EQ) {
                            return new Data_Maybe.Just(tree.value2);
                        };
                        if ($177 instanceof Data_Ordering.LT) {
                            return lookup(dictOrd)(k)(tree.value0);
                        };
                        return lookup(dictOrd)(k)(tree.value3);
                    };
```

**Comment by hdgarrood** [comment]
This is a good point actually, there may well be a better way. In the case where `instanceof` returns false (which presumably happens quite often, i.e. every time a match on a data constructor fails), it seems like there are three lookups in the prototype chain before you get to null:

```javascript
// not exactly what the compiler generates but this will have the same effect
function Just (value0) {
  this.value0 = value0;
}

var j = new Just(0);
var p1 = Object.getPrototypeOf(j);
console.log(p1 == Just.prototype); // true
var p2 = Object.getPrototypeOf(p1);
console.log(p2 == Object.prototype); // true
var p3 = Object.getPrototypeOf(p2);
console.log(p3 == null); // true
```

Which presumably means at least three pointer dereferences. Perhaps storing a property on `Just.prototype` which uniquely identifies the data constructor and checking that during pattern matches might be more efficient.

**Comment by rightfold** [comment]
@hdgarrood Or compare `x.constructor === Just`.

**Comment by garyb** [comment]
There is some discussion on at least one old issue about this. I think both a tag and `constructor` approach were brought up, but I don't remember why we stuck with `instanceof`.

**Comment by hdgarrood** [comment]
Oh nice, I didn't realise `obj.constructor` was standardised.

**Comment by hdgarrood** [comment]
Previously: https://github.com/purescript/purescript/pull/454#issuecomment-48046532

**Comment by garyb** [comment]
Oh wow, good find! That result might not be true in 2017 too of course.

**Comment by theqabalist** [comment]
I think it would be difficult to optimize this I guess, and not run afoul of how different engines implement run time type checking.  Because in the previous discussion it was brought up that prototype checking is more idiomatic, and its possible that an engine could implement types as tags internally and then check constructor first during instanceof before walking prototype, and its just not possible to really know.  I guess the point I was raising was that in my profiling it just seemed like such a large constant value that it was alarming, but there may not be anything that can be done.

This may be dense, but is there not a type-erasure way of handling things that doesn't rely on runtime type checking?  Because isn't haskell's core IL untyped, or am I just misremembering something.  It seems like if you want to talk actual idiomatic javascript, run time type sniffing, except for single dispatch, is a no no in general, at least in my experience working in JS.

**Comment by natefaubion** [comment]
@theqabalist the `instanceof` checking is for the tagged constructors. You have to have some way of discriminating the variants in a union. Each constructor (not type) is a JS "class", and when you pattern match it must check against the tag of the class.

**Comment by theqabalist** [comment]
@natefaubion yeah, I understand what it's doing, what I was more asking was how does this differentiation happen in something like Haskell Core?  I thought core was untyped, and thus untagged, but I guess it could be tagged and not typed.

**Comment by natefaubion** [comment]
You have to do some sort of check somewhere, whether it's boxing it up with some integer or some identifier of some kind. How else would you dispatch a pattern match?

**Comment by theqabalist** [comment]
That's exactly what I am asking though, only because I assume that profiling a compiled Haskell app would not show 33% of execution time in pattern matching. I could be wrong though and that's what I am inquiring about.

**Comment by rightfold** [comment]
Haskell terms are tagged with integers, which are just compared for equality.

`instanceof` however walks the prototype chain in case there is a mismatch.

**Comment by theqabalist** [comment]
Also, to be clear, at this point I am fairly sure this cannot be improved per se, but my question was more to invite double checking of my assumptions rather than a recommendation. Just due diligent on my part.

**Comment by theqabalist** [comment]
And when a core data structure (Data.List) is implemented as a discriminated union type, this aspect has sweeping performance implications for iterating large lists through destructuring.

**Comment by hdgarrood** [comment]
I wouldn't be so confident to say it cannot be improved. I'd like to try generating data constructors as something like this and see how that affects performance:

```javascript
function Just(value0) {
  this.value0 = value0;
}
const Just_ = 0; // this value would be different for different data constructors
Just.prototype.tag = Just_;

// in pattern matches
function match(x) {
  if (x.tag === Just_) {
    [...]
  }
}

**Comment by theqabalist** [comment]
@rightfold I assume integer comparison is much cheaper than comparing strings, but would make output code difficult to decipher at times.

**Comment by natefaubion** [comment]
@theqabalist Strings like that would be interned and checked for pointer equality.

**Comment by theqabalist** [comment]
@hdgarood that's an interesting combination of names and int tags I didn't consider. I like that for readability if it turns out faster.

**Comment by natefaubion** [comment]
@hdgarrood I'd like to try having a single JS class for all variants of a sum, padded with nulls.

```js
function Maybe(tag, value0) {
  this.tag = tag;
  this.value0 = value0;
}
Maybe.Nothing = new Maybe(0, null)
var just = new Maybe(1, "foo");
```

That way you never have inline-cache misses wrt hidden classes.

**Comment by theqabalist** [comment]
@natefaubion that's a good point too. JavaScript internals are too complicated lol.

**Comment by hdgarrood** [comment]
@natefaubion good point - there are so many options! I think it would be nice to try to preserve readability too though. Perhaps if we took that approach we could generate pattern matches like `if (x.tag === 0 /* Nothing */) { ... }`.

**Comment by natefaubion** [comment]
Well, you could still use interned strings. It was just an example.

**Comment by spicydonuts** [comment]
Wouldn't numbers conflict with other PS bundles running in the same system (not that that's recommended, but it isn't _not_ recommended as far as I know as long as the compiler versions were the same).

`Symbol` seems more appropriate for always-unique values.  They can be passed strings for debugging info as well.  Though that would actually have a similar issue with mixed libraries as each `Just` would appear to be different types.  Maybe that's a good thing? ¯\_(ツ)_/¯

**Comment by puffnfresh** [comment]
Would Church-encoding help?

**Comment by garyb** [comment]
> @natefaubion: I'd like to try having a single JS class for all variants of a sum, padded with nulls.

Wouldn't this fall foul (in v8 at least) of having the type become megamorphic? (http://mrale.ph/blog/2015/01/11/whats-up-with-monomorphism.html)

**Comment by hdgarrood** [comment]
I would guess that Church-encoding sum types would degrade performance if anything, but perhaps I'm missing something there.

My impression was that the idea of having a single class for all variants of a given sum type was specifically designed in order to benefit from optimizations like the ones described in that article i.e. not be megamorphic! Also, the article makes it sound (to me) like V8 performs optimizations at each property access site individually, so presumably since any field access can't happen until after pattern matching, if you've reached a branch that involves a sum type field (property) access, you've already done pattern matching. So I think any given property access site will only ever involve one variant of any given sum type.

**Comment by natefaubion** [comment]
> Also, the article makes it sound (to me) like V8 performs optimizations at each property access site individually, so presumably since any field access can't happen until after pattern matching, if you've reached a branch that involves a sum type field (property) access, you've already done pattern matching. So I think any given property access site will only ever involve one variant of any given sum type.

That's a great point. I made a basic test https://jsperf.com/sum-vs-monoclass though though I don't know if it's the best way to test it. According to that they are essentially the same performance-wise.

**Comment by natefaubion** [comment]
Actually I take that back. In FF they are the same, in Chrome the monoclass is 2x as fast.

**Comment by natefaubion** [comment]
Additionally, the null padding is unnecessary, you can just leave them as `undefined`.

**Comment by STRML** [comment]
@theqabalist When did you take this profile? Any chance you ran afoul of https://github.com/nodejs/node/issues/9634?

**Comment by theqabalist** [comment]
I did do it against 7, so this is possibly related. That being said the discussion does seem to involve going around using instanceof.

**Comment by rightfold** [comment]
Can you measure a performance difference if you apply `sed 's/instanceof/.constructor ===/g'` to the generated code?

**Comment by berdario** [comment]
@rightfold the jsperf contains a `Sum (constructor pointer)` test.

I ran it on Chrome 58 (which ships V8 5.8) which apparently is not affected by https://github.com/nodejs/node/issues/9634

And the ops/sec for `constructor` are 447 (against 126 with `instanceof` and 575 for monoclass), so it's better, but falls short of the monoclass approach

**Comment by berdario** [comment]
I just added another alternative to jsperf:

https://jsperf.com/sum-vs-monoclass3

(`Monoclass (polymorphic array)` which is equivalent to the monoclass, but I'd have expected it to perform better with a lot of constructors, since there're always only 2 fixed keypairs: `tag` and `values`)

`Monoclass (polymorphic array, single key-value pair for value)` performance instead is as bad as `Sum`, but changing `var tag = Object.keys(a)[0]` with `for (var tag in a){break}` seems to make it even faster than the normal polymorphic Monoclass:

https://jsperf.com/monoclasses-extra

Unfortunately, jsperf is really FUBAR: https://github.com/jsperf/jsperf.com/issues/236

And I wasn't able to edit the original test (and the new revisions are f**ked up, so if you want to look again at what Natefaubion prepared, you'll want to have a look at the first revision:

https://jsperf.com/sum-vs-monoclass/1

**Comment by berdario** [comment]
Btw, I just ran the tests on Firefox, the scores (ops/sec) go from 30 to 200, and the ranking is quite a bit different:

- inline records is the best (200)
- `constructor`
- `instanceof`
- Monoclass
- Monoclass array
- Monoclass array with single key-value pair

(which is interesting... since one of the fastest on Chrome, is the slowest on Fx)

**Comment by Pauan** [comment]
@berdario V8 will try to represent JS objects as (something similar to) C structs when it can, so the fields will be stored contiguously in memory, and key lookup is just a pointer offset (just like with an array).

So I would expect there to be very little difference in memory usage between a JS object and a JS array.

But I'm not an expert on V8 either, so take what I say with a grain of salt.

**Comment by rightfold** [comment]
V8 only uses hash tables when you use `delete`

**Comment by Pauan** [comment]
@rightfold It also uses hash tables when you store a large amount of keys. But for a small number of keys like in this example, it shouldn't.

@berdario Also, if arrays really were more efficient than objects, then the ideal output would be `[1 | 0, left, key, value, right]`. In other words, the first index of the array is the tag (which is stored as a 32-bit int for speed).

**Comment by chexxor** [comment]
Worth mentioning that the new Aff implementation and the Ef experiment uses the monoclass approach, described in this thread, and both seem to have good performance.
- https://github.com/slamdata/purescript-aff/blob/a048d9ce88c1a4faacb64e77ae8917102373ff0c/src/Control/Monad/Aff.js#L59
- https://github.com/safareli/purescript-ef/blob/b6969dbc5e503bfd4f7d4ffe03a2abf5137054d3/src/Control/Monad/Ff.js#L18

They are also processing the Aff and Ef values by looping over an array, rather than processing nested (?) thunks.

**Comment by utkarshkukreti** [comment]
I'm working on an optimizing compiler for PureScript -> JS. While benchmarking code that involved looping and matching a bunch of `data` variants, I found `instanceof` to be the bottleneck.

I modified @berdario's jsperf to add 2 snippets. These are the codes BuckleScript and Elm generate. Both use `switch` to branch on the tag. BuckleScript always uses integer as tag while Elm uses strings in debug mode and integers in production (I added the production mode code). Both attempts seem to be a lot faster than all the alternatives.

Firefox:

<img width="969" alt="screen shot 2018-09-17 at 10 24 07 pm" src="https://user-images.githubusercontent.com/217126/45638036-95401d80-bac9-11e8-9993-bc31ebcb2cee.png">

Chrome:

<img width="966" alt="screen shot 2018-09-17 at 10 24 28 pm" src="https://user-images.githubusercontent.com/217126/45638043-9cffc200-bac9-11e8-8184-dfa6564a6346.png">

URL: https://jsperf.com/sum-vs-monoclass-9

Implementation in case jsperf goes down:

```
function H1 (a) { return [0, a]; }
function H2 (a, b) { return [1, a, b]; }
function H3 (a, b, c) { return [2, a, b, c]; }
function H4 (a, b, c, d) { return [3, a, b, c, d]; }
function H5 (a, b, c, d, e) { return [4, a, b, c, d, e]; }

function hfn (cell, a) {
  switch (a[0]) {
    case 0: return H2(0, a[1] + 1);
    case 1: return H3(0, 0, a[2] + 1);
    case 2: return H4(0, 0, 0, a[3] + 1);
    case 3: return H5(0, 0, 0, 0, a[4] + 1);
    default: return H1(a[5] + 1);
  }
}

function I1 (value0) { return {$: 0, value0}; }
function I2 (value0, value1) { return {$: 1, value0, value1}; }
function I3 (value0, value1, value2) { return {$: 2, value0, value1, value2}; }
function I4 (value0, value1, value2, value3) { return {$: 3, value0, value1, value2, value3}; }
function I5 (value0, value1, value2, value3, value4) { return {$: 4, value0, value1, value2, value3, value4}; }

function ifn (cell, a) {
  switch (a.$) {
    case 0: return I2(0, a.value0 + 1);
    case 1: return I3(0, 0, a.value1 + 1);
    case 2: return I4(0, 0, 0, a.value2 + 1);
    case 3: return I5(0, 0, 0, 0, a.value3 + 1);
    default: return I1(a.value4 + 1);
  }
}
```

```
var cell = { value: H1(0) };
for (var i = 0; i < 100000; i++) {
  hfn(cell, cell.value);
}
```

```
var cell = { value: I1(0) };
for (var i = 0; i < 100000; i++) {
  ifn(cell, cell.value);
}
```

I hope I didn't mess up and the implementations are correct. I'm yet to implement this in my compiler. I'll be using Elm's representation and see how that performs with real code.

**Comment by utkarshkukreti** [comment]
As expected, I was completely wrong. I'll delete this comment in a minute.
