### ISSUE TITLE
Wildcard inference is of questionable use now

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2578]
Since the wildcard inference was changed a while back it's become not entirely useful if you're trying to use it to find the type of things, since you always get results like this:

```
[1/2 WildcardInferredType] Whatever.purs:132:15

  132  doSomething ∷ _ → _ → Int
                     ^
  
  Wildcard type definition has the inferred type
  
    t0
  
  in value declaration doSomething
  
  where t0 is an unknown type

[2/2 WildcardInferredType] Whatever.purs:132:19

  132  doSomething ∷ _ → _ → Int
                         ^
  
  Wildcard type definition has the inferred type
  
    t0
  
  in value declaration doSomething
  
  where t0 is an unknown type
```

Which is odd, because it still typechecks correctly, but I always seem to get `t0` as the inferred type now.

**Comment by garyb** [comment]
Oh, for reference, this is `doSomething`:

``` purescript
doSomething ∷ _ → _ → Int
doSomething x y = x + y
```

**Comment by paf31** [comment]
What would you expect to see in that case?

**Comment by LiamGoodacre** [comment]
In this case I'd expect `Int`, due to `+` being closed over a type.

**Comment by paf31** [comment]
Oh, sorry, I see.
