### ISSUE TITLE
JSIndexer overused in codegen

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2581]
I just tried the latest compiler (after #2554 specifically) and noticed that the code generator is now emitting the `M["x"]` form for accessors pretty much everywhere.

Here is an example I was just working on:

```js
var length = (function () {
    var go = function (acc) {
        return function (arr) {
            var $1 = Data_Array["null"](arr);
            if ($1) {
                return acc;
            };
            if (!$1) {
                return go(acc + 1 | 0)((function (dictPartial) {
                    return Data_Array_Partial["tail"](dictPartial);
                })()(arr));
            };
            throw new Error("Failed pattern match at Main line 13, column 5 - line 15, column 49: " + [ $1["constructor"]["name"] ]);
        };
    };
    return go(0);
})();
```

**Comment by michaelficarra** [comment]
Thanks, I will look into this ASAP. FYI, https://github.com/purescript/purescript/pull/2554/commits/3c9f14b5a7049df09a665be40f4bce31eedd50c0 is the commit that should have handled outputting `a["b"]` as `a.b` for any `b` that is an ECMAScript `IdentifierName`.

**Comment by paf31** [comment]
This actually breaks `psc-bundle` output too, since we generate `module["exports"]` now, which `psc-bundle` doesn't recognize.

**Comment by michaelficarra** [comment]
@paf31 I looked for a bit last night and couldn't find anything obvious. I'll look again tonight, but I don't have much knowledge about Haskell debugging tools/processes. It's hard to confirm that a given input has an expected output for a function that is not exported, but I just realised that I can simply expose the things I want to test in the REPL. I'll let you know how it went either way.

**Comment by hdgarrood** [comment]
@michaelficarra you might find the `:load` command in ghci useful - it sets up your repl as if you were inside that module, so all the same imports are available and you can also use functions inside that module even if they're not exported.

**Comment by michaelficarra** [comment]
@hdgarrood Thanks, that helped a bunch. See #2583.
