### ISSUE TITLE
Provide an additional reason with the 'cannot derive instance' error

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2595]
Currently the following attempts to derive instances all produce a compiler error "cannot derive a type class instance for X" and nothing else:

```purescript
-- Eq has just one type argument
derive instance eqIntInt :: Eq Int Int

-- missing the wildcard type argument
derive instance genericFoo :: Data.Generic.Rep.Generic Foo

-- cannot derive this class
class Foo
derive instance foo :: Foo
```

I think it would be nice to provide a little more detail in this error message. Possible reasons the compiler might have failed to derive an instance that I can think of:

* It's not aware of the class
* The instance was given the wrong number of type arguments (in particular, I think `derive instance genericFoo :: Generic Foo` missing the second wildcard might be a common mistake)

It's also possible that we might later add more reasons to this list as the compiler is able to derive more instances.

**Comment by garyb** [comment]
Ah yeah, I figured the latter one would be fixed by @LiamGoodacre's recent work on instance arity, but of course it won't here as this is arises during in desugaring and doesn't reach the typechecker. 

👍

**Comment by hdgarrood** [comment]
I just noticed #2519. Perhaps these two should be addressed at the same time - maybe this issue subsumes that one, even?

**Comment by garyb** [comment]
The errors mentioned in there are caught during typechecking instead of desugaring, but the suggestion is to use a message more like when it fails during desugaring, so I think they are different despite the desired result being the same :smile:
