### ISSUE TITLE
ShadowedName warning isn't firing?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2600]
I can't seem to get this to fire. Can someone please try to verify if it's working for them?

**Comment by owickstrom** [comment]
I do, both in value bindings and in type variable quantification.

**Comment by paf31** [comment]
Which compiler version are you using? I'm using master.

**Comment by owickstrom** [comment]
Let me try with master.

**Comment by owickstrom** [comment]
No problem on latest master either:

```
[1/3 ShadowedName] src/Main.purs:11:1

      v
  11  main = do
  12    let foo :: forall e. Int
  13        foo = 345
  14    log "Let's do it."
          ^

  Name foo was shadowed.

  in value declaration main

...

[3/3 ShadowedTypeVar] src/Main.purs:12:7

  12    let foo :: forall e. Int
            ^^^^^^^^^^^^^^^^^^^^

  Type variable e was shadowed.

  in value declaration main
```

**Comment by kRITZCREEK** [comment]
@owickstrom that's a `ShadowedTypeVar ` though. I'll try it in a minute.

**Comment by owickstrom** [comment]
@kRITZCREEK Both, the first one (`[1/3]`) is `ShadowedName`.

**Comment by kRITZCREEK** [comment]
Oh :D sorry I'm an idiot

**Comment by owickstrom** [comment]
No, not at all! But do try it as well, regardless. :)

**Comment by LiamGoodacre** [comment]
@paf31 can you post some of the examples that you tried?

**Comment by LiamGoodacre** [comment]
Also, there is a `ShadowedName` warning test: `examples/warning/2411.purs`

**Comment by paf31** [comment]
I can't seem to reproduce this now after clearing all cached output. Never mind, but thanks for checking, everyone.
