### ISSUE TITLE
Issue with custom kinds and classes?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2601]
Say you have these:

``` purescript
foreign import kind Nat
foreign import data Z ∷ Nat
foreign import data S ∷ Nat → Nat

class ListIx ix list out | list → out
instance listIxS ∷ ListIx n as out ⇒ ListIx (S n) (Cons elem as) out
instance listIxZ ∷ ListIx Z (Cons elem as) elem
```

The compiler is happy, but then if you do this:

``` purescript
assertTyIx
  ∷ forall ix list out
  . ListIx ix list out
  ⇒ NProxy ix
  → Proxy list
  → Proxy out
assertTyIx _ _ = Proxy
```

There's a kind error with `Nat` and `Type`. It can be fixed by kind-annotating the class:

``` purescript
class ListIx (ix ∷ Nat) list out | list → out
instance listIxS ∷ ListIx n as out ⇒ ListIx (S n) (Cons elem as) out
instance listIxZ ∷ ListIx Z (Cons elem as) elem
```

So I think there's a problem here, although I'm not exactly sure where. I think probably the instances should error, due to the use of a `Nat`-kinded type for the `ix` parameter.

Basically it seems like the `ListIx` class parameters act a little bit like they're polykinded unless you actually try and use the constraint in a function, at which point it expects the parameters to be `Type` kinded.

edit: this was using 0.10.5, I've not checked with `master` actually, so maybe it's already been fixed?

**Comment by paf31** [comment]
Yes, it sounds like we should be catching this on the instance declaration.

On an unrelated note, don't you need the fundep to be `ix list → out` there?

**Comment by garyb** [comment]
I'm not sure... it seems to work without that, but looking at it it does seem like it should be necessary. @natefaubion originally wrote it (I was just trying out the `Nat` kind), and said he just handwaved his way through the fundeps so maybe :smile:

**Comment by natefaubion** [comment]
Hah, yeah. I originally thought `ix list -> out` seemed reasonable, but then I saw some example in the type-level-map repo that were more permissive (using the equivalent to `list -> out`). It seemed to work either way and I don't know what I'm doing so _shrug_

**Comment by LiamGoodacre** [comment]
In the type-map repo apart from `FromZipperCons_` (which I will fix), all the others have a single fun dep: those arguments that the instances "pattern match" on are the determiners, everything else is listed as determined.
I know @paf31 tends to write these in a similar way to functions with `input -> output`, but I usually only have things I pattern match on as the determiners.

Correct me if I'm wrong; the minimal covering sets for `ix list out | list -> out` will be `{{ix, list}}`, so it will be working in the same way as `ix list -> ix out` (and therefore `ix list -> out`), that is: you need both `ix` and `list` to start committing to instances.

**Comment by paf31** [comment]
We don't even need custom kinds for this:

```purescript
class Class (a :: * -> *)
instance inst :: Class Int
```

This passes the type checker right now.

**Comment by paf31** [comment]
Even worse:

```purescript
type Syn (a :: * -> *) = String

val :: Syn Int
val = "bad"
```

**Comment by paf31** [comment]
Actually, this fails correctly on `master`. I think I know what's happened here: this was broken by my bad type synonym PR, and then fixed by my other type synonym fix. 😄

**Comment by hdgarrood** [comment]
Do we have a test for this?

**Comment by paf31** [comment]
Probably not, but I can add one from the list above.

**Comment by garyb** [comment]
Does the fix apply to the case with instances also?

**Comment by LiamGoodacre** [comment]
@garyb it does :)
