### ISSUE TITLE
Compiler cannot compile exported data constructor that has a quote in its name

### ISSUE THREAD

**Issue by chrisdotcode** [purescript/purescript#2609]
```purescript
module Test (Foo(Bar, Bar')) where

data Foo = Bar | Bar'
```
fails to compile with:
```bash
  Unable to parse module:
  unexpected "Bar'"
  expecting proper name
```
But:

```purescript
module Test (Foo(..)) where

data Foo = Bar | Bar'
```
compiles successfully.

**Comment by chrisdotcode** [comment]
This seems (potentially) easy enough that I might like to attempt to resolve it. If somebody could point me in the right direction, that would be great :)

**Comment by LiamGoodacre** [comment]
@chrisdotcode :)
For this I think you will need to change `parseDeclarationRef` in `src/Language/PureScript/Parser/Declarations.hs` to use the same parser for constructors that `parseDataDeclaration` does.
This should fix it for both exports and imports.

Or perhaps `properName` should parse single-quotes? @paf31 

We should also add a test case for this in `examples/passing/`.  There are some multi-file tests you could copy for inspiration, but you will also need to list the folder you add to `purescript.cabal` with all the others.

Thanks!

**Comment by chrisdotcode** [comment]
Speaking of that, I should mention that quotes aren't allowed in foreign import names (e.g.: `foreign import insert'`), either. If it's using the same code, and we update it, that would be A Bad Thing(TM) because we know JavaScript function names  can't have quotes in them.

Just something to be aware of.

**Comment by rvion** [comment]
could we orgnanize a poll about primes ?
I have the impression that most people are against those nowdays

**Comment by chrisdotcode** [comment]
(I personally find them highly convenient and use them frequently for slight variations of functions; I wasn't necessarily aware of any stigma, either).

**Comment by hdgarrood** [comment]
@rvion that's not my impression, it's been suggested a couple of times before and people haven't been keen. I don't have the issue numbers to hand but there have been at least two discussions on this issue tracker.

**Comment by hdgarrood** [comment]
Primes are definitely allowed in foreign imports, Data.Array imports an FFI function called `uncons'` (but doesn't export it).

**Comment by chrisdotcode** [comment]
My mistake. Corrected above.
