### ISSUE TITLE
Lack of warning/error when using deriving with polymorphic records

### ISSUE THREAD

**Issue by Pauan** [purescript/purescript#2616]
Let's say I have some code like this:

```
newtype Foo = Foo { foo :: Int }

derive instance eqFoo :: Eq Foo
derive instance ordFoo :: Ord Foo

(Foo { foo: 1 }) == (Foo { foo: 2 })
(Foo { foo: 1 }) > (Foo { foo: 2 })
```

This works perfectly fine, exactly what I expected.

But now let's say I have some code like this:

```
newtype Foo r = Foo { | r }

derive instance eqFoo :: Eq (Foo r)
derive instance ordFoo :: Ord (Foo r)

(Foo { foo: 1 }) == (Foo { foo: 2 })
(Foo { foo: 1 }) > (Foo { foo: 2 })
```

This does not behave at all like I expected: `==` always returns `true`, and all of the `Ord` operations always return `EQ`:

```
var eqFoo = new Data_Eq.Eq(function (x) {
    return function (y) {
        return true;
    };
});

var ordFoo = new Data_Ord.Ord(function () {
    return eqFoo;
}, function (x) {
    return function (y) {
        return Data_Ordering.EQ.value;
    };
});
```

Unfortunately, PureScript does nothing to prevent this: there isn't any errors, and there isn't even a warning.

I think PureScript should warn/error when deriving instances that don't work in an expected way (like with polymorphic records).

**Comment by garyb** [comment]
Should deriving be allowed for open records even?

**Comment by Pauan** [comment]
@garyb Is there a list of derivable typeclasses somewhere? I can't think of any typeclasses that make sense with polymorphic records, but I may be missing something.

**Comment by garyb** [comment]
I'm not sure, we should probably document it if not :smile:... but: `Eq`, `Ord`, `Generic`, `Newtype`, `Functor`. Yeah, apart from `Newtype` it wouldn't make sense.

**Comment by hdgarrood** [comment]
I don't think there is; if we had one, I think it would go here: https://github.com/purescript/documentation/blob/master/language/Type-Classes.md

**Comment by Pauan** [comment]
@garyb I agree that `Newtype` makes sense. I'm in favor of making the others an error.

@hdgarrood `TODO: list derivable type classes` so I guess that's a no, then. :stuck_out_tongue:
