### ISSUE TITLE
Remove command line arguments which should trigger rebuild or are unnecessary

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2618]
Some of `psc`'s command line arguments affect what is written to the `output` directory; for example, `--comments`, `--dump-corefn`. If you run `pulp build` followed by `pulp build -- --comments`, the second time, nothing will happen as `psc` seems to consider everything in the `output` directory up-to-date. I was expecting see everything get rebuilt with comments.

Would it make sense to store the command-line arguments inside `externs.json` and check that those are the same when deciding whether to rebuild?

**Comment by paf31** [comment]
Just a note that `--dump-corefn` should not require a full rebuild, since it only results in creating strictly more output.

I would actually also be fine with removing some of these options before 1.0. There are existing tools for stripping comments, for example, so why not just always include comments? And things like `--no-tco` really don't need to be there any more.

**Comment by hdgarrood** [comment]
I think it would be great to remove `--comments` and `--no-tco` :)

**Comment by paf31** [comment]
I changed the title and moved this to 0.11.

**Comment by natefaubion** [comment]
Should we remove `no-magic-do` and `no-opts` as well? I'd imagine there are programs that would break without magic-do (due to stack around binds and ST behavior). I don't see any reason to have these flags except maybe if you were debugging their implementations.

**Comment by paf31** [comment]
Yes, I'd like to remove all of those before 1.0.

**Comment by hdgarrood** [comment]
There's still the issue that building with `--dump-corefn` doesn't actually write the corefn.json if that module has already been built, though, unless we want to always dump corefn?

**Comment by paf31** [comment]
Ah right. I would be fine with always dumping out the core, but it might affect compilation speed, so maybe we should just fix the timestamp check to include the `corefn.json` file.
