### ISSUE TITLE
Support polymorphic types in typed binders

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2626]
See also #2445

**Comment by LiamGoodacre** [comment]
In `master`, if I update `parseBinder` to use `parsePolyType` then this just seems to work.
Are there any other specific changes you had in mind for this?

(Also, did you mean to add the `ready for review` tag?)

**Comment by paf31** [comment]
When I tried it, I ended up getting skolem errors. I'll try some more experiments.

**Comment by paf31** [comment]
Hmm, maybe it's fixed with the latest changes then:

```
> let f = \(x :: forall a. a -> a) -> x x
> (f \x -> x) 1
1
```
