### ISSUE TITLE
(x - 1) compiles to (x - 1) instead of (x - 1 | 0)

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2629]
Is this a bug? The JS implementation in the prelude does read `| 0`:

https://github.com/purescript/purescript-prelude/blob/v2.3.0/src/Data/Ring.js#L6

**Comment by hdgarrood** [comment]
I think so, my guess would be that the inliner for Int's `sub` is forgetting the |0. The relevant code should be in Language.PureScript.CodeGen.JS.Optimizer.Inliner iirc.

**Comment by rightfold** [comment]
Thanks Harry, I'll see if I can work on it this week.

Kind regards,
rightfold

**Comment by paf31** [comment]
I verified this is already fixed in 0.10.6.

**Comment by rightfold** [comment]
Excellent 😁

Sent from my iPhone.
