### ISSUE TITLE
let ... in doesn't work in psci

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2630]
For example:

```
> let f _ = 0 in f 0
(line 1, column 13):
unexpected "in"
expecting ., {, _, number, char literal, string literal, "true", "false", [, "\\", qualifier, data constructor name, identifier, "case", "if", "do", "let", (, hole literal, ::, operator, "where", indentation at column 5 or end of input
```

I was hoping to just get `0` printed just as if I'd typed `0` at the prompt.

**Comment by LiamGoodacre** [comment]
It does work when wrapped in parens:

```purescript
> (let f _ = 0 in f 0)
0
```

**Comment by noraesae** [comment]
Is there anyone working on this? If none, I may look into this soon.

**Comment by paf31** [comment]
I don't think so, but let's formulate a plan first, since there are a few possible solutions.

**Comment by noraesae** [comment]
I will look into the code and check if I can come up with some solutions. Is there a nice way you can imagine to fix it?

**Comment by paf31** [comment]
The most obvious strategies to me are:

- Don't require `let` for declarations, like @hdgarrood submitted a PR for before. Maybe 0.11 is the time to reconsider this. It just needs someone to see what the impact on the error messages is like.
- Find a way to parse both using the same `let` syntax.
- Introduce a "declaration mode", like paste mode, just for typing in declarations.

There may be other approaches.

**Comment by noraesae** [comment]
The first one looks nice. GHCi also support this although I'm not sure that supporting both form as GHCi does is a good decision. How do you think?

**Comment by hdgarrood** [comment]
I'd prefer to support both. People will be used to typing `let x = y` now, so I expect it would be very annoying to start disallowing that. I'm pretty sure that it would still be unambiguous even if `x = y` and `let x = y` are both allowed (although I agree that some investigation re error messages will be needed).

**Comment by paf31** [comment]
I agree that we should support both for a while, but I'd prefer to pick one before 1.0.

**Comment by hdgarrood** [comment]
Why is that? So that it's easier for us to give good parse errors?

**Comment by paf31** [comment]
Yes, and I just prefer having one way to do things in general.

**Comment by hdgarrood** [comment]
Ok, yeah, makes sense. I'll vote for the version without the `let` then, I think.

**Comment by noraesae** [comment]
Great. I'll vote for the version with no `let` decl too.

By the way, where is the place to write PSCi tests for evaluation asserts?

**Comment by hdgarrood** [comment]
There is none, sadly. I tried to do that once and it turned out to be quite a lot more difficult than I imagined. Haskeline docs seem to indicate that repls built with it should work noninteractively (ie piping input from a text file) but I couldn't get that to work. It would be really great to have this though, I'd be very grateful if you were able to look into it.
