### ISSUE TITLE
Should error when a type class member doesn't reference at least a covering set of arguments

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2631]
Consider the following class, for example:

```purescript
class C a b | a -> b where
  m :: a
  n :: b
```

Given the functional dependency here, `m` is perfectly fine because a type for `a` must be known for us to select an instance, but `n` couldn't possibly be used.

**Comment by LiamGoodacre** [comment]
Actually, I think this make sense to check on all constraints not just type class members? ...maybe

It's also not as trivial as I first thought, an argument could only appear in a type via a constraint - so whether or not the member could be used may depend on the constraints functional dependencies.

But perhaps just checking the free variables in each member's type is good enough for now.

**Comment by paf31** [comment]
> Actually, I think this make sense to check on all constraints not just type class members?

Yes, but I think classes would be a good place to start.
