### ISSUE TITLE
Travis CI cache doesn't work with new stack.yml

### ISSUE THREAD

**Issue by noraesae** [purescript/purescript#2635]
I think the cache doesn't work now in Travis Ci and the build takes much longer (~40mins) than before (~6mins).

I think it's because of #2611. I will look into this.

**Comment by noraesae** [comment]
Maybe it's not caching `extra-deps`? It seems like packages listed in the `extra-deps` are rebuilt everytime.

**Comment by noraesae** [comment]
Also, to clear the previous cache and rebuild one with the new stack yaml, we need to change (or remove) the `compiler` field, I guess.

@hdgarrood, may you have done the work in the [extend-travis](https://github.com/purescript/purescript/tree/extend-travis) branch?

**Comment by hdgarrood** [comment]
I'm looking at Travis CI and caching at the moment, yeah. I'm currently trying to find a way of addressing the issue that builds often time out when switching to new snapshots or compiler versions. Once I've sorted that out I'll look at this.

**Comment by hdgarrood** [comment]
I think I've found a way to re-enable OSX builds: https://gist.github.com/hdgarrood/29fa8ebcd5b5acd679cf429fd0a93e3e

I'm fairly sure that `extra-deps` get stored in `.stack-work` local to the project directory, but I don't think we should include that directory in the build cache unless it's really necessary, as I think there might be some risk of accidentally persisting state that we don't want to be persisted in CI jobs that way.

**Comment by noraesae** [comment]
Yes. I also think `extra-deps` are not really a big deal in reducing the build time, #2636 will already removed most of them though. The biggest problem was that the new stack env had not been properly cached, because it was using the same `compiler` name and thus the same cache(of the previous resolver). I think it's fixed by removing `compiler` fields, as you have done in the extend-travis branch.

**Comment by noraesae** [comment]
#2636 is now merged. Travis CI build also takes about 10 mins in the extend-travis branch (with macOS build enabled too!), so I think this issue can be closed after the branch is merged into master.
