### ISSUE TITLE
ModuleNotFound error in 0.10.6

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2639]
After upgrading to 0.10.6, the errors for missing modules are not so great. If one occurs it blocks any other errors from arising, and has no position info apart from the module it occurs within:

```
Error found:
in module Halogen.Menu.Component

  Module Halogen.HTML.Events.Handler was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.


See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
or to contribute content related to this error.
```

Compare with the result from 0.10.5:

```
Error 1 of 15:

  in module Halogen.Menu.Submenu.Component
  at /Users/gary/GitHub/slamdata/bower_components/purescript-halogen-menu/src/Halogen/Menu/Submenu/Component.purs line 12, column 1 - line 12, column 41

    Unknown module Halogen.HTML.Events.Indexed


  See https://github.com/purescript/documentation/blob/master/errors/UnknownName.md for more information,
  or to contribute content related to this error.

Error 2 of 15:

  in module Halogen.CustomProps
  at /Users/gary/GitHub/slamdata/src/Halogen/CustomProps.purs line 22, column 1 - line 22, column 52

    Unknown module Halogen.HTML.Events.Handler


  See https://github.com/purescript/documentation/blob/master/errors/UnknownName.md for more information,
  or to contribute content related to this error.

Error 3 of 15:

  in module SlamData.Dialog.Render
  at /Users/gary/GitHub/slamdata/src/SlamData/Dialog/Render.purs line 22, column 1 - line 22, column 42

    Unknown module Halogen.HTML.Events.Handler


  See https://github.com/purescript/documentation/blob/master/errors/UnknownName.md for more information,
  or to contribute content related to this error.

Error 4 of 15: ...
```

It's a different error case, since it's `UnknownName` vs `ModuleNotFound`, and I guess it's not a _serious_ problem, but it's super annoying in the case we have here where we're upgrading Halogen in SlamData.

**Comment by paf31** [comment]
We could add this to the existing list of error messages with bad position info, perhaps?

**Comment by garyb** [comment]
I was more complaining about the fact that all other errors a blocked when one of these occurs - including other `ModuleNotFound` errors.

**Comment by paf31** [comment]
Ah. The problem is that we can't even perform the first step of the compilation (sorting modules) in this case. This error gets thrown there. We might be able to use `parU` to get more errors, but is that necessary?

**Comment by toastal** [comment]
I got this error too when I tried to use a function I hadn't yet implemented in a module. Instead of saying something like "yo, this isn't exported/doesn't exist", the error message says a module doesn't exist.
