### ISSUE TITLE
Efficient Immutable Data Structures

### ISSUE THREAD

**Issue by rtfeldman** [purescript/purescript#264]
ClojureScript's approach to emitting JS with high-performance immutable data structures is:

1. Use [mori.js](http://swannodette.github.io/mori/) for all emitted data structures
2. Emit code that is guaranteed to fit the guidelines for the [Google Closure Compiler's Advanced Optimizations](https://developers.google.com/closure/compiler/docs/api-tutorial3), which means emitted production JS can trivially be stripped of whichever parts of Mori aren't being used. (This would also do the same for Prelude, etc., incidentally)

It seems like a low-cost way to get much better performance for functional use cases than the default JS implementations of these data structures, which are designed for mutation.

Thoughts on using some of these ideas in PureScript?

**Comment by paf31** [comment]
We now have arrays, lists, lazy lists, catenable lists, maps, string maps, sequences, sets, `ST` arrays and maps, zippers, ... so most cases are covered from a performance point of view. 

Bindings for something like Mori could be implemented in a library, but would be best tracked elsewhere I think. I'll close this.

**Comment by wires** [comment]
Hi, just a thought/remark.

I think it might be worth reconsidering the Google Closure Compiler. When it used in the `ADVANCED_OPTIMIZATIONS` and especially when all code is compiled in one pass, the resulting code can be really very small. It using smart function inlining and aggressive symbol name shortening. That is why some restrictions on the input JS are imposed, but at least from afar it seems doable. See here https://developers.google.com/closure/compiler/docs/limitations

**Comment by robotlolita** [comment]
@wires because PureScript gives the compiler more guarantees, investing on PS-specific transformations just pays off better there wrt inlining, tree-shaking/DCE, and stuff than using GCC — afaik the current PS compiler already does all of this. People suggested implementing a supercompiler (https://github.com/purescript/purescript/wiki/GSOC-2015-Projects#supercompiler-for-functional-core) for PureScript some time ago, which would give even better performance, as it can do partial evaluation during compilation and stuff.

**Comment by jdegoes** [comment]
A supercompiler for PureScript will likely be one of Fantasyland's summer of code projects in 2017.

**Comment by wires** [comment]
Right, thanks! I was suspecting that maybe by now the compiler caught up with GCC.

Still, when used in a PS project using JS-FFI, its would be good to have some form of tree-shaking across the entire PS+JS codebase.  For instance, you have probably seen http://rollupjs.org/ (it uses ES2016 `import` declarations to do it's work). Supporting tools like this is arguably outside the scope of `psc`,  but is seems nice/useful.

**Comment by garyb** [comment]
There's a lengthy discussion about that sort of thing here https://github.com/purescript/purescript/issues/2207
