### ISSUE TITLE
PS 0.10.6 produces broken bundles

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2642]
As reported here: https://github.com/purescript/purescript-maybe/issues/26

I assume this is a problem in `psc-bundle`, perhaps since the change to constructors. I'm not exactly sure what is going on. The generated JS for the `Data.Maybe` module in `output` contains the export, but when bundled (with DCE) it is disappears, even though the `Just` definition is retained.

Looks like we'll be needing a 0.10.7 after all, and soon!

**Comment by hdgarrood** [comment]
We can make this less urgent by marking 0.10.6 as deprecated on hackage and also by setting the default dist-tag on npm (i think it's called 'latest') back to 0.10.5. That way people should continue to get 0.10.5 for most methods of installing the compiler.

**Comment by paf31** [comment]
The other solution is to revert #2619 and to release 0.10.7. Since the purpose of #2619 seems to be to enable better DCE in Rollup, maybe we can just put it on hold until the Rollup plugin is ready, at which point `psc-bundle` can be drastically simplified anyway.

**Comment by hdgarrood** [comment]
That sounds good to me.

**Comment by paf31** [comment]
Should be fixed by #2648.

**Comment by garyb** [comment]
Good to release 0.10.7 then? Or was there something that needed updating for Pursuit too?

**Comment by paf31** [comment]
I think so, but I'll need to cherry-pick some commits into a branch in order to make 0.10.7. I can try to work on it later.

**Comment by hdgarrood** [comment]
There was #2641 which has now been merged. Since we're doing an 0.10.7 it would be quite convenient for me/Pursuit if we included those commits in this new release.
