### ISSUE TITLE
PSCi :help points to wrong URL for documentation

### ISSUE THREAD

**Issue by i3games** [purescript/purescript#2651]
PSCi :help / :? shows a wrong link to documentation. 

> Further information is available on the PureScript documentation repository:
>  --> https://github.com/purescript/documentation/blob/master/PSCi.md

This URL is a 404. There is a PSCi guide under: 
[https://github.com/purescript/documentation/blob/master/guides/PSCi.md](https://github.com/purescript/documentation/blob/master/guides/PSCi.md)

(this could be fixed by moving the documentation)
purescript 10.6

**Comment by noraesae** [comment]
#2650 will fix this.
