### ISSUE TITLE
Define a type operator (->) for Function in Prim

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2661]
This should allow us to remove much/all of the special-casing code in the compiler that treats `->` differently from other type operators. This should also automatically address issues like https://github.com/purescript/pursuit/issues/282.

We will also need to make a small update to the docs for `Prim.Function` while doing this.

**Comment by paf31** [comment]
We don't usually pretty print type operators, since they get desugared, so we'd still need a special case there.

**Comment by hdgarrood** [comment]
Ok cool. I'll leave the pretty-printing special casing in for now, then.

**Comment by hdgarrood** [comment]
Should we deal with the unicode right-arrow by having Prim export two separate type operators for `Function`, ie both `->` and `→`?

**Comment by paf31** [comment]
Makes sense to me.

**Comment by kRITZCREEK** [comment]
We still have to treat `->` special in the type checker, since it has special subsumption rules (finally something I know :D).

**Comment by hdgarrood** [comment]
Oh, actually, I think we probably will have to keep quite a bit of special-casing code in the parser too, since `->` needs to be treated as a token, not an operator, for parsing lambdas and case alternatives.

Also it seems like it might be rather difficult to introduce new type operators for `Function`, because of all the places the compiler uses things like `isFunction` and `== tyFunction` - we might have one of those checks incorrectly fail because a type operator `->` isn't going to compare equal to the actual `Function` type.

Perhaps a better approach for now is to modify the `PrettyPrintFunction` constructor so that it can work for pretty-printing partially applied occurrences of the `Function` type constructor as well as fully applied occurrences of it?

**Comment by hdgarrood** [comment]
> Perhaps a better approach for now is to modify the PrettyPrintFunction constructor so that it can work for pretty-printing partially applied occurrences of the Function type constructor as well as fully applied occurrences of it?

At least, that is what motivated me to open this issue in the first place.

**Comment by garyb** [comment]
Type operators should be desugared by the time they'd be used with `tyFunction` / `isFunction`, so that might not be much of a concern after all.

**Comment by hdgarrood** [comment]
Ah ok. Come to think of it, given that type operators all get desugared, and given that I don't think there's all that much special-casing code we would then be able to remove, I'm no longer actually sure what we would gain by doing this..?

**Comment by paf31** [comment]
Close this then?
