### ISSUE TITLE
ReferenceError: Warn is not defined

### ISSUE THREAD

**Issue by leighman** [purescript/purescript#2663]
I have a function with a `Warn "Prefer X"` constraint.

I run `pulp build` and I correctly get a warning from Main.

When I run `pulp run` I get `ReferenceError: Warn is not defined` and a js stacktrace.

If I add `var Warn` to output/Main/index.js it runs correctly.

Using 0.10.7

**Comment by hdgarrood** [comment]
I can reproduce this too, with the following program:
```purescript
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (log)

msg :: Warn "oops" => String
msg = "hi"

main = log msg
```

Here's `output/Main/index.js`:

```javascript
"use strict";
var Prelude = require("../Prelude");
var Control_Monad_Eff = require("../Control.Monad.Eff");
var Control_Monad_Eff_Console = require("../Control.Monad.Eff.Console");
var msg = function (dictWarn) {
    return "hi";
};
var main = Control_Monad_Eff_Console.log(msg(Warn));
module.exports = {
    main: main, 
    msg: msg
};
```

**Comment by paf31** [comment]
The dictionary generated is

```purescript
TypeClassDictionaryConstructorApp C.Warn (Literal (ObjectLiteral []))
```

So maybe this has never worked in the way we're expecting?

**Comment by LiamGoodacre** [comment]
I think I know what the problem is here.  The dictionary is fine, it's just that we aren't importing the type class constructor when the dictionary is used - we have done this with IsSymbol, so it's not difficult.  I'll make a PR shortly.

**Comment by LiamGoodacre** [comment]
Or maybe not.  Hmm, I'll have a think.

**Comment by LiamGoodacre** [comment]
Actually I think I'm wrong on that - although we should be doing that for the other classes we solve for, not just IsSymbol - (so that's also a bug).  I think this one is different because Warn is defined in Prim - and therefore doesn't have a real definition.

**Comment by paf31** [comment]
@LiamGoodacre I think the solution is to change the evidence to an empty record literal instead of a `TypeClassDictionaryConstructorApp`. There is nothing to say that the evidence has to be in that form.

**Comment by LiamGoodacre** [comment]
@paf31 yes, I've already done so and everything seems to be working :)

**Comment by pitzqa** [comment]
Hello,
I faced Same issue "**E/configParser - ReferenceError: WARN is not defined**" while running my protractor.conf.js file in protractor cli.

protractor.conf.js file,

const HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

exports.config = {
    allScriptsTimeout: 120000,
    seleniumAddress: 'http://localhost:4444/wd/hub',
    baseUrl: 'https://***/login',
    capabilities: {
        browserName: 'chrome'
    },
    framework: 'jasmine',
    specs: [
        '/home/k**l/Desktop/EV/ev-ng/e2e'
    ],
    logLevel: WARN,
    beforeLaunch: () => {
        require('ts-node').register({
            project: './tsconfig.e2e.json'
        });
    },  
    jasmineNodeOpts: {
        defaultTimeoutInterval: 120000,
        showColors: true,
        random: false,
    },
    onPrepare: () => {
        jasmine.getEnv().addReporter(new HtmlScreenshotReporter({
            dest: 'target/screenshots',
            filename: 'protractor_jasmine_report.html'
        }));
    },
};


![example 1](https://user-images.githubusercontent.com/39620464/41353842-0352782a-6f3b-11e8-8966-32d43315244b.png)

**Comment by LiamGoodacre** [comment]
@pitzqa Your issue has nothing to do with this project.  Presumably you want: https://github.com/angular/protractor
