### ISSUE TITLE
Test for PSCi evaluation.

### ISSUE THREAD

**Issue by noraesae** [purescript/purescript#2664]
It would be nice to have test structure for PSCi evaluation.

I'm not sure which data type to use for defining the tests, but maybe something like below.

```haskell
[ ("let f _ = 10 in f 0", shouldReturn 10)
, ("[a, b] = [1, 2]",     shouldFail) -- hope to see though!
]
```

It's from #2630.

**Comment by paf31** [comment]
Do you mean in the test suite?

**Comment by noraesae** [comment]
It could be in the test suite. I imagined something similar to `completionTestData`.

**Comment by noraesae** [comment]
I think now it became better to tackle this issue, because #2721 allow PSCi test env to actually run commands in test suites. I will do some experiments of ExprCommand evaluations.
