### ISSUE TITLE
PureScript ecosystem proposal

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2670]
# purescript ecosystem proposal:

I think the purescript web ecosystem could be improved.
I'm willing to spend some time to help improving things.

-----------------------------------------

#### 1. Unify the ecosystem

For now, the ecosystem is fractioned: 

1.1 There is no link between those websites:

  - http://try.purescript.org/
  - https://news.purescript.org/
  - http://www.purescript.org/
  - https://pursuit.purescript.org/

1.2 CSS is a little bit inconsistent between websites:

  - yellow color is not the same:
    - #C49`53`A for news.*
    - #C49`43`A for pursuit.* 
    etc.

  - header size is not the same
    - `90px` for pursuit
    - `62px` for news 
    - `150px` for home

  - text sizes not always the same

I would like to unify the ecosystem by unifying the CSS and the headers with a two level menu as below:
![image](https://cloud.githubusercontent.com/assets/2150990/23026398/6d27b568-f461-11e6-9d0e-835e3b9f37be.png)

  - first menu would be shared amongst all websites :
    `Purescript | Try | Install | Learn | Libraries | News | Community`
      
  - second menu would be site specific:
    - example for try.*
      ![image](https://cloud.githubusercontent.com/assets/2150990/23026348/45d959da-f461-11e6-98c2-768e2cedeace.png)

#### 2. Use https everywhere

some website use https: 
  - https://news.purescript.org/

but some websites don't:
 - http://try.purescript.org
 - http://www.purescript.org/

[Why HTTPS matters] (https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https)

 
#### 4. Actualize some pages

I would like to actualise some content in pages like http://www.purescript.org/projects/

---------------------------------------

## Concrete action plan

to do that, I would like to Re-arrange and dockerize all components

 - [ ] create a free [docker-hub organisation](https://docs.docker.com/docker-hub/orgs/)
 - [ ] add a `Dockerfile` in each repo along scripts to `build` and `push` repos
 - [ ] create two `docker-compos` files  (dev and prod) to be able to deploy the whole purescript infrastructure at once
 - [ ] improve the prod dockerfile so it also deploys a `load balancer and https proxy`
 - [ ] improve again the prod dockerfile so it also deploys a let's encrypt worker that automatically `retrieve`, `install`, and `renew` https certificates
 - [ ]  change some repository names such as `purescript.github.io` to reflect their new location / real purpose
 - [ ] create a new `website` repository containing the docker-compose files. This repo would submodules all other websites-related repos (news, try, pursuit, etc.)
 - [ ] move all css into this new website (other repos would just reference it)
 - [ ] change trypurescript repo [infrastructure](https://github.com/purescript/trypurescript/branches) so there is no longer 2 branches: one for the server, one for the client
 - [ ] open dozens of small and focused PR to improve ergonomics that can be discussed and validated independently
 - [ ] document the ecosystem architecture in one file so everything is very easily maintainable

--------------------

does it sound ok ?

**Comment by paf31** [comment]
Thanks for writing this up. I agree some things can be improved, but this overlaps a bit with some other plans I have, which I haven't documented yet:

- I would like to reimplement the main website as a single page, replacing articles with the documentation repo and adding prominent links other sites like Pursuit and Try PureScript.
- I don't know if I want to use Docker, but I don't want to depend on Docker Hub. I have been considering Nix for the next iteration of the community server instead, and some work has already been done there.

Note that some of the sites you mentioned use GitHub pages for hosting, and I'd like to keep it that way. That excludes HTTPS unfortunately. We could host those sites on the same server as the services which back them, but that would make it harder to accept pull requests, and add a sysadmin burden which we don't have right now.

Also, please let's file issues for CSS inconsistencies on individual repos where they need to be changed.

**Comment by hdgarrood** [comment]
@naehrstoff mentioned being interested in helping unify styles across purescript web sites/apps around when he did the pursuit redesign. I'm not sure if he's able to dedicate time to this right now but I thought it might be worth mentioning.

**Comment by spicydonuts** [comment]
Caddy server is a nice way to quickly host a few sites together with automatic certificate generation (via letsencrypt) and GitHub webhook support for auto-deploying when new commits come in.  Most likely the same things can be done with Docker.  The sysadmin work would be pretty minimal.

**Comment by rvion** [comment]
@paf31 thanks for your answer :)

> I would like to reimplement the main website as a single page, replacing articles with the documentation repo and adding prominent links other sites like Pursuit and Try PureScript.

Not quite sure to see the direct benefit of having a single page, but enhancing the documentation using the documentation sure seems like a good idea !

>  I have been considering Nix for the next iteration of the community server instead, and some work has already been done there.

⚠️  really personal and subjective opinion ⚠️  I don't think Nix is a good idea here. Everytime I used Nix, I had problems adapting pieces of architecture not yet available in Nix. Also, lot of cognitive burden. I love the concept behind Nix, but I think it's a bit too immature IMO. Most projects I know that support Nix ended up merging lots of nix-related bugfix PR.This being said, I'm not a Nix expert at all.

> I don't know if I want to use Docker, but I don't want to depend on Docker Hub.

in all cases, I didn't plan to depend on docker hub. since each repo would have had its own dockerfile, no need to use docker hub if we don't want. it would have just been a free image store we could have used, but deployment would have worked from local images too.

> Note that some of the sites you mentioned use GitHub pages for hosting, and I'd like to keep it that way.

One can register [github hooks](https://developer.github.com/v3/repos/hooks/) and tell a server to pull your changes on every commit. Michael Snoyman even has a small project that does this already: https://github.com/snoyberg/yesod-gitrepo

Still, I'm not sure that the way the trypurescript client and server are split in different branches is good. I have the impression it makes hacking and discoverability much more complex. 

> but that would make it harder to accept pull requests

As said just above, using a server that pull changes from github (with a readonly key) would fix this concern.

> and add a sysadmin burden which we don't have right now.

as @spicydonuts said, I think the sysadmin work could be very minimal, well documented, and completely automated with scripts.
https://caddyserver.com/ is indeed a nice HTTP/2 web server with automatic HTTPS.
I were thinking about using https://traefik.io : it has automatic HTTPS, a admin pannel with perfs monitoring,  and integrates directly with docker (or other schedulers) to discover services and reroute / load balance requests. Quite a magic piece of software.

I think a nicely crafted set of dockerfile and docker-compose would even reduce a little bit the complexity to maintain, deploy and update purescript related websites. (I have some experience with larger infrastructures)

@hdgarrood thanks for the mention

------------

I was just offering some help, I'm really happy to know you're already planning to change things. I understand you may not feel like offloading such tasks right now.

**Comment by naehrstoff** [comment]
Thanks for the mention, @hdgarrood. Time is indeed a bit of a rare commodity for me at the moment, but I'd be happy to contribute. I think that this initiative by @rvion is a great idea and that it would help bring all the PureScript resources closer together, which will be great for beginners.

From my perspective as an interaction designer what I think would benefit the ecosystem the most is a living style guide. There's a nice [overview of living style guides](http://styleguides.io/) that shows the possibilities. We've been using and developing our own tool, [Catalog](https://interactivethings.github.io/catalog/) at our company for several years and found it to help a lot with unifying development efforts and making sure that components are developed in a reusable way – not only to save double work, but also to achieve consistency across different products. (We've also used it in a recent PureScript project.)

Important parts of such a style guide are color palettes, typography definitions, spacings, imagery and logos, etc. By collecting these things in one place they are more accessible to people who want to contribute to the projects so that they don't have to invent their own definitions for each subsite. And by speaking the same (design) language across all the products we can build more trust with our users, especially those peeking in from the outside 😄 You can find a bit more on this in my [Pursuit PR](https://github.com/purescript/pursuit/pull/266).

So, @rvion, if you're interested to discuss ideas and/or would like some help let me know.

**Comment by soupi** [comment]
I think we can merge the two try-purescript branches to one branch by moving all of the content in gh-pages to a `/docs` folder in master.

I think replacing the PureScript website to a single page with links to other relevant places is a good idea. Right now the website don't get much love and has some out-of-date content. Making it minimal and linking to other places will make it more flexible to changes IMO.

**Comment by paf31** [comment]
We can't use `docs/` unfortunately, since GitHub Pages doesn't support that when using a subdomain.

**Comment by paf31** [comment]
I think we should probably move this discussion to the https://github.com/purescript/community-server repo, which contains configuration files for the current (ad-hoc) deployment.

**Comment by paf31** [comment]
I'd like to move this to the community-server repo please, and break it up into smaller issues.
