### ISSUE TITLE
:browse Prim does not work

### ISSUE THREAD

**Issue by marick** [purescript/purescript#2672]
(Moved from purescript-psci-support per @paf31)

--------

The Purescript book says that primitive types are defined in the `Prim` module. So I wanted to see what functions were available. I can import `Prim`:

```
> import Prim
```

But `:browse` doesn't work:

```
> :browse Prim
Module 'Prim' is not valid.
```

That's the same message as for a completely bogus module. Why this message? If it's because `Prim` is somehow magic, should that be made clear?

**Comment by hdgarrood** [comment]
Prim is magic to some extent - it's the only module baked in to the compiler. I think `:browse Prim` in psci should work though.

**Comment by kRITZCREEK** [comment]
Just in case someone comes along searching for everything in `Prim` there's documentation for it on [Pursuit](https://pursuit.purescript.org/builtins/docs/Prim).
