### ISSUE TITLE
macOS Sierra: Cannot interact with PSCi

### ISSUE THREAD

**Issue by IvantheTricourne** [purescript/purescript#2682]
Currently running through the examples in "PureScript by Example" and I've gotten all the way up to the part where PSCi is introduced without any issues (up to section 2.11). 

I am able to run `pulp run` and every iteration of the `pulp build` command as described in the book, however, I cannot seem to get `pulp psci` to work at all. When I try to run it, I get the compiling messages, then I get the REPL but cannot type anything into it:

```
> pulp psci
Compiling Math
Compiling Data.Show
Compiling Data.Unit
Compiling Data.Void
Compiling Data.Semiring
Compiling Data.Ring
Compiling Data.NaturalTransformation
Compiling Data.Semigroup
Compiling Data.HeytingAlgebra
Compiling Data.Eq
Compiling Data.CommutativeRing
Compiling Data.BooleanAlgebra
Compiling Data.Ordering
Compiling Data.EuclideanRing
Compiling Data.Ord.Unsafe
Compiling Data.Boolean
Compiling Control.Semigroupoid
Compiling Control.Category
Compiling Data.Function
Compiling Data.Field
Compiling Data.Functor
Compiling Data.Ord
Compiling Control.Apply
Compiling Data.Bounded
Compiling Control.Applicative
Compiling Control.Bind
Compiling Control.Monad
Compiling Prelude
Compiling Control.Monad.Eff
Compiling Control.Monad.Eff.Class
Compiling Control.Monad.Eff.Console
Compiling Control.Monad.Eff.Unsafe
Compiling Main
Compiling Test.Main
Compiling PSCI.Support
PSCi, version 0.10.7
Type :? for help

>
```

Then, nothing. Currently using Pulp version 10.0.1 and Bower version 1.8.0. I also installed PureScript via `npm`. Help?

**Comment by noraesae** [comment]
This problem is not reproduced in my env(macOS Sierra, PSCi 0.10.7, Pulp 10.0.1). You mean the REPL shows up but doesn't get input? Which terminal and shell are you using?

**Comment by IvantheTricourne** [comment]
@noraesae Yes. I get a prompt, but I'm not able to type anything into it. 

I'm using a bash shell inside of iTerm. It also doesn't work in the default terminal for macOS.

**Comment by hdgarrood** [comment]
What version of node.js are you using? I think you might be able to fix this by updating it.

**Comment by IvantheTricourne** [comment]
@hdgarrood I'm using version 5.5.0.

**Comment by IvantheTricourne** [comment]
That was the kicker! Updated to the latest LTS and it works. Thanks!
