### ISSUE TITLE
var can capture mutable value in TCO loop

### ISSUE THREAD

**Issue by jolod** [purescript/purescript#2689]
psc version: 0.10.7

In the `sumTCObug` function below, `n` is reset to zero in TCO code, even though `f'` binds `n`. The result is that `f'` adds `a` to zero. If `f'` is inlined, i.e. `go (\a -> n + a) 0` on the last line, then TCO is not triggered and the correct result is returned. If `f'` is `(+) n` then the correct result is also returned, since no JavaScript function closing over `n` is generated.

    sumTCObug = go id
        where 
      go f n = 
        if n == 0 then
          f
        else
          let
            f' a = n + a
          in
            go f' 0

    sumTCObug 7 3 -- Returns 3 instead of 10.

In the generated JavaScript code below, lines 13 and 16 make up the problematic combination.

    var sumTCObug = (function () {
        var go = function (__copy_f) {
            return function (__copy_n) {
                var f = __copy_f;
                var n = __copy_n;
                tco: while (true) {
                    var $0 = n === 0;
                    if ($0) {
                        return f;
                    };
                    if (!$0) {
                        var f$prime = function (a) {
                            return n + a | 0;
                        };
                        f = f$prime;
                        n = 0;
                        continue tco;
                    };
                    throw new Error("Failed pattern match at Main line 27, column 5 - line 35, column 1: " + [ $0.constructor.name ]);
                };
            };
        };
        return go(Control_Category.id(Control_Category.categoryFn));
    })();

**Comment by paf31** [comment]
This seems like it might be a pain to fix, and I suspect it's been around forever essentially. I bet we could fix it by using an IIFE to close over current values, but that doesn't seem like a complete solution, especially in the presence of other types of mutation (ST?)

@michaelficarra I'd be interested to hear your thoughts on this.

**Comment by paf31** [comment]
Could we fix this by using `let` once we move to ES6 codegen?

**Comment by garyb** [comment]
Yeah, that should do it. I'm sure we can think of something before then too though 😜

**Comment by paf31** [comment]
I'm not sure actually, but the nice thing is that if we do use `let` or `const` then we can support TCO for many more things than we currently do.

I'm going to move this back to 1.0.

**Comment by michaelficarra** [comment]
@paf31 As an alternative to using `let`, you can use the IIFE pattern to create a new binding with every loop iteration for any variables that will be closed over:

```js
while (true) {
  (function (n) {
    // ...
  })(n);
}
```

But in general I think we should move to using ES2015+ features in the compiler output. If someone also wants support for old JS engines, there are compilers designed specifically for that.

Sorry for the delay in my response.

**Comment by Pauan** [comment]
For the record, [`let` and `const` are well supported even in IE11](http://kangax.github.io/compat-table/es6/#ie11), so the only browsers that don't support them are old mobile browsers.

The non-supportive browsers [seem to be about ~3% of total market share](http://caniuse.com/usage-table).

**Comment by paf31** [comment]
@michaelficarra That fix won't work for me, since the `tco` label is unavailable inside the function body. Any thoughts?

**Comment by natefaubion** [comment]
@paf31 I don't think you'd necessarily have to wrap the entire loop body. Couldn't you just wrap bindings that capture tco variables?

**Comment by paf31** [comment]
I guess we could do something like set a flag based on whether we want to `return` or `continue`, and do that outside the closure.

**Comment by natefaubion** [comment]
ie, modified codegen:

```js
                if (!$0) {
                    var f$prime = function(tco_n) {
                      return function (a) {
                        return n + a | 0;
                      };
                    }(n);
                    f = f$prime;
                    n = 0;
                    continue tco;
                };
```

**Comment by paf31** [comment]
That's going to incur a performance hit for every use of a name though, right? If I use a name multiple times, that might be a problem.

**Comment by natefaubion** [comment]
You only have to wrap closures over tco variables, right? If you always wrap the entire loop body, you'll likely get a similar performance hit.

**Comment by michaelficarra** [comment]
@natefaubion Yeah, that works. You can also name that function and pull it out of the loop so it gets reused.

**Comment by paf31** [comment]
@michaelficarra What about something like this?

```js
    var go = function (__copy_f) {
        return function (__copy_n) {
            var f = __copy_f;
            var n = __copy_n;
            var __tco_done = false;
            var __tco_result;
            var __tco_f;
            var __tco_n;
            tco: while (!__tco_done) {
                __tco_result = (function (f, n) {
                    var $0 = n === 0;
                    if ($0) {
                        __tco_done = true;
                        return f;
                    };
                    var f$prime = function (a) {
                        return n + a | 0;
                    };
                    __tco_f = f$prime;
                    __tco_n = 0;
                    return undefined;
                })(f, n);
                f = __tco_f;
                n = __tco_n;
            };
            return __tco_result;
        };
    };
```

I think we could generate that easily enough based on the code that's there now.

**Comment by michaelficarra** [comment]
@paf31 Yeah, that works as well, and I would still recommend you pull the function out of the loop for performance.

**Comment by paf31** [comment]
Do you mean `f$prime`? Yes, I agree, if the user does that, then we can get rid of the IIFE. I think the compiler already will do that actually.

**Comment by michaelficarra** [comment]
No, I mean the entire immediately-invoked function. It can be lifted out and then only called within the loop.

**Comment by paf31** [comment]
Oh, I see, thanks. I'll try to implement that later then.

**Comment by michaelficarra** [comment]
Code is clearer:

```js
    var go = function (__copy_f) {
        return function (__copy_n) {
            var f = __copy_f;
            var n = __copy_n;
            var __tco_done = false; // Can't use continue inside the function block, so use a flag
            var __tco_result;
            var __tco_f;
            var __tco_n;
            function __loopBody(f, n) { // Close over current values
                var $0 = n === 0;
                if ($0) {
                    __tco_done = true;
                    return f;
                };
                var f$prime = function (a) {
                    return n + a | 0;
                };
                __tco_f = f$prime; // Copy values over
                __tco_n = 0;
                return undefined;
            }
            tco: while (!__tco_done) {
                __tco_result = __loopBody(f, n);
                f = __tco_f; // Copy new values back
                n = __tco_n;
            };
            return __tco_result;
        };
    };
```
