### ISSUE TITLE
Parser backtracking issues with nested arrays

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#2690]
http://try.purescript.org/?gist=e22c2b96c145d7c475ce4f26bc473704

```purescript
render a =
  [ Left "One"
  , Right
      [ Left "Two"
      , { foo = 1 }
      ]
  ]
```
```
 Unable to parse module:
  unexpected [
  expecting , or ]
```

But if you remove the nesting, it's a better error
```purescript
render a =
  [ Left "Two"
  , { foo = 1 }
  ]
```
```
 Unable to parse module:
  unexpected =
  expecting :, , or }
```

**Comment by natefaubion** [comment]
Originally, the issue manifested for me with record binders in a case statement. But it seems to be an issue with nested arrays in general.

**Comment by paf31** [comment]
I've made multiple attempts to fix this, but all of them have involved non-trivial changes to the AST to avoid backtracking, and none of them have quite worked how I would like. I'm going to suggest this wait until we can move away from Parsec and towards something with better support for automatically left-factoring the grammar.

**Comment by hdgarrood** [comment]
Now that the cst parser has been merged the error is better:

```
Error found:
at example.purs:6:15 - 6:16 (line 6, column 15 - line 6, column 16)

  Unable to parse module:
  Expected ':', saw '='


See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.
```

so I think this can be closed.
