### ISSUE TITLE
Error: psc-package.json does not exist

### ISSUE THREAD

**Issue by naomik** [purescript/purescript#2692]
I installed purescript via

```sh
$ brew install purescript
```

after trying to run `$ psci` I get the following message

```
PSCi requires the psci-support package to be installed.
You can install it using Bower as follows:

  bower i purescript-psci-support --save-dev

Or using psc-package:

  psc-package install psci-support

For help getting started, visit https://github.com/purescript/documentation/blob/master/PSCi.md
```

Not really wanting Bower, I choose the psc-package options. I try running

```sh
psc-package install psci-support
```

Then I get the following error

```
psc-package.json does not exist
```

OK, so that's not working. Then I click the PSCi help link from the previous message - <https://github.com/purescript/documentation/blob/master/PSCi.md> but that leads me to a http 404 error

--

OK, bower if you insist. So I install the bower thingy in my project's directory

```sh
bower i purescript-psci-support --save-dev
```

Then I reattempt to run `psci`. I get the same error message:

```
PSCi requires the psci-support package to be installed.
You can install it using Bower as follows:

  bower i purescript-psci-support --save-dev

Or using psc-package:

  psc-package install psci-support

For help getting started, visit https://github.com/purescript/documentation/blob/master/PSCi.md
```

---

To top it off, <http://try.purescript.org/> seems to be broken at the moment. I'm just trying to compile/run a simple script and running into lots of trouble.

Any help would be appreciated

**Comment by hdgarrood** [comment]
The link is now https://github.com/purescript/documentation/blob/master/guides/PSCi.md - the URL is fixed in `master` now.

If you want to use `psc-package`, btw, I think you can run `psc-package init` to create a basic `psc-package.json` file for your project.

**Comment by hdgarrood** [comment]
I think there should be enough information on the page I linked to for you to get started; if not, please open an issue on the [documentation repo](https://github.com/purescript/documentation/issues). Thanks!
