### ISSUE TITLE
Record synonyms fail to derive with Generic

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#2695]
I didn't notice an issue about this (maybe it is expected?), but while most synonyms will work with deriving, record synonyms still don't.

http://try.purescript.org/?gist=ea6794e4608f13c46a77148ff3b36dcf

If you inline the record synonym in the newtype, or use something other than a record, it will work.

**Comment by garyb** [comment]
It seems to be specifically related to deriving for `Generic`:

http://try.purescript.org/?gist=4aec6e537b95fe96921539344b3f03b2&backend=core&session=25814a03-bd97-5399-1f88-9e1567997881

**Comment by paf31** [comment]
I think we should take steps to remove the old generic implementation and deriving, but we should probably fix this in the interim.

**Comment by natefaubion** [comment]
> I think we should take steps to remove the old generic implementation and deriving

Probably true, but the reason I tried is that there's still quite a few very useful libraries (actively maintained) that use the old style Generic.

**Comment by paf31** [comment]
Is there any reason they couldn't be migrated?

**Comment by paf31** [comment]
It might be useful to make a list of the remaining libraries which use the old implementation.

**Comment by natefaubion** [comment]
I'm not familiar with differences. Are there cases where the old Generic will work where the new one won't? I seem to vaguely remember something around records with the new one as well, but my memory is quite hazy on this matter :)

**Comment by paf31** [comment]
I am trying to encode old-style generics with new-style generics here.

https://github.com/purescript/purescript-generics-rep/pull/7

There is some related discussion on that PR.
