### ISSUE TITLE
Deprecate kind symbols and move Effect into eff

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2701]
Deprecate `!` and `*` in favor of the named equivalents and move `Effect` into `eff` as a foreign kind.

**Comment by paf31** [comment]
@rightfold pointed out on IRC that `#` can't actually by implemented as a `NamedKind` in `Prim`, for the same reason as `->`. Only ground kinds (no kind arguments) can be in `Prim`.

**Comment by garyb** [comment]
I take it there's no chance we can specify the sort of imported kinds? :wink:

**Comment by rightfold** [comment]
@garyb There is only one sort, so that wouldn't have disambiguating advantages.

**Comment by garyb** [comment]
Yeah, I guess I'm using the wrong term, I meant a way of defining kind constructors basically.

**Comment by rightfold** [comment]
Ah yes, then we would need arrow sorts, e.g. `BOX -> BOX`, or dynamically-sorted kinds.

**Comment by paf31** [comment]
Here is a (partial) list of core libraries which use the existing symbols:

```
purescript-assert/src/Test/Assert.purs line 14, column 31 - line 14, column 31
purescript-console/src/Control/Monad/Eff/Console.purs line 10, column 32 - line 10, column 32
purescript-eff/src/Control/Monad/Eff.purs line 24, column 30 - line 24, column 30
purescript-functions/src/Data/Function/Uncurried.purs line 6, column 28 - line 6, column 28
purescript-prelude/src/Data/Unit.purs line 11, column 29 - line 11, column 29
purescript-proxy/src/Type/Proxy.purs line 55, column 19 - line 55, column 19
purescript-st/src/Control/Monad/ST.purs line 12, column 27 - line 12, column 27
purescript-strings/src/Data/String/Regex.purs line 27, column 30 - line 27, column 30
```

**Comment by paf31** [comment]
After more thought, I'm not sure this is worth the breakage. I might close it.
