### ISSUE TITLE
:reload for PSCi

### ISSUE THREAD

**Issue by noraesae** [purescript/purescript#2713]
Previous issues: #2088, #2125

Currently we have `:reset`, which clears all the imported modules. I wonder if there was a reason that it was implemented as it is, not `:reload` in which GHCi works?

I may like `:reload`, with `:module` for the clearing as they work in GHCi.

**Comment by paf31** [comment]
We could just modify `:reset` instead if we could support an `:unimport` command.

**Comment by noraesae** [comment]
I'm thinking of implementing this by re-importing modules in `:show import` after resetting. Is there any better method for reload?

**Comment by paf31** [comment]
Sounds about right. I think we can just not clear the imports on reset.

**Comment by soupi** [comment]
I think for me `reset` says "start from scratch as if you just started `psci`". May I suggest that if you plan on changing this behaviour to change the name as well? `reload` sounds good. Ideally I would prefer having both :)

**Comment by paf31** [comment]
The only problem with `:reload` is that `:r` will stop working.

**Comment by noraesae** [comment]
I was thinking  of changing `:reset` to `:reload`. In this way, `:r` will be a different thing. The original `:reset` can be replaced with `:unimport`, which also support a form of `:unimport A.Module`. What does it look like?

**Comment by chexxor** [comment]
@soupi, What do you think about removing `:reset`, and instead advise users to simply do `:quit` and re-enter PSCi?

**Comment by garyb** [comment]
How about renaming `:reset` to `:clear`, and adding `:reload`?

**Comment by soupi** [comment]
@chexxor, Not having to quit gives a better user experience.  I don't think it will be very difficult to support both so IMO we should do it.

**Comment by chexxor** [comment]
I hope you're successful, @noraesae!

**Comment by noraesae** [comment]
I followed @garyb's suggestion as it looks like the best one.

**Comment by evgenykochetkov** [comment]
Thank you so much for this!
I am just a beginner working through "PureScript by Example" book, and this change will make playing with examples much easier!
