### ISSUE TITLE
Improve "openness" check for re-exports

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2726]
Writing this does not currently raise a warning:

``` purescript
module ReExport
  ( module A
  , module B
  ) where

import Data.Functor as A
import Data.Semigroup as B
```

But it should, as it suffers from the same issue as this:

``` purescript
module ReExport
  ( module Data.Functor
  , module Data.Semigroup
  ) where

import Data.Functor
import Data.Semigroup
```

Which does warn, asking for explicit imports from both modules, as they're being opened into the same namespace. In the first example this is also true as `A` and `B` are merged into one namespace in the exports of the module.

No doubt this will annoy people, unfortunately, as I'm pretty sure it's used to work around the export rules as they stand in some libraries - but we should at least apply the rules consistently or give up on safe import behaviour entirely.

**Comment by paf31** [comment]
Sounds good, but does this need to be in 1.0? It won't break anything to fix it later, right?

**Comment by garyb** [comment]
I would kinda like to do it for 1.0, as I think it'll raise warnings in a bunch of libraries. I'll bump it if we get done with everything else first though :wink:
