### ISSUE TITLE
Errors about `discard` could be improved

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2732]
The error about `discard` not being defined is a bit weird, it mentions `do` notation and asks you to import `bind` from `Prelude` to resolve it.

Also, this is a side thing, but I think maybe `bind_` would have been a better name, to go with the other discardifying things we have like `for_`, `traverse_`, `sequence_`, etc. When I started getting errors about `discard` I found it confusing as I knew I was using `void $ ...` or `_ <- ...`, so thought it should still be `bind`-y... the name `discard` seemed to suggest ignoring something entirely, not running its effects and discarding the result (yeah, I know I even used the word "discard" in that description :smile:, but still...).

**Comment by paf31** [comment]
Agreed, these are not ideal. The position information is also not as helpful as it could be. The errors are reported at the function level.

**Comment by paf31** [comment]
Closing this, and we can take care of renaming `discard` separately if need be.
