### ISSUE TITLE
Read commands from .psci file when starting session

### ISSUE THREAD

**Issue by chexxor** [purescript/purescript#2734]
In the past, PSCi would check for a ".psci" file in the project directory or `~` directory, then execute the commands in their when starting a PSCi session. This was removed several months ago (I can't find the issue/PR), but it would be nice to have that back. One motivation for it is to have `pulp init` create a ".psci" file having "import Prelude". With this, newcomers can do `pulp psci` followed by `1+1` and see a success case, rather than `Unknown operator (+)` error.

**Comment by paf31** [comment]
I think we should probably limit this to imports and declarations.
