### ISSUE TITLE
Lenses from object properties

### ISSUE THREAD

**Issue by puffnfresh** [purescript/purescript#275]
From #270, it'd be really great to have a lens created from a property:

```purescript
p :: { x :: Int, y :: Int }
p = { x: 1, y: 2 }

lens _x x
-- I guess should have a type like:
-- _x :: Lens' { x :: a | r } a

t :: Int
t = get _x p
-- 1

u :: { x :: String, y :: Int }
u = set _x "Wat" p
-- { x: "Wat", y: 2 }
```

Partial lenses would also be great:

```purescript
x :: Either String Int -> Maybe Int
x = get _Right
```

What magic would we need to make this work?

**Comment by gbaz** [comment]
So, we have a lens library here: https://github.com/purescript-contrib/purescript-lens

I've been trying to think through what would actually be useful in codegen and I think the proposal here is a bit too narrow.

Rather, we'd want something that given a data type splats  out a whole _bunch_ of lenses and prisms into the namespace:

    data Foo = Bar Number | Baz {x :: Number, y :: String}

and we'd get prisms `_Bar` and `_Baz` and lenses `_x` and `_y`.

maybe with special syntax like `generateLenses Foo` -- but this is starting to feel more like a "template-purescript" to generalize this case than to push this into the compiler. I could sort of go either way on it actually...

**Comment by paf31** [comment]
This seems like a fine goal for an external tool which could process a module and output another module.

**Comment by gbaz** [comment]
On the whole, I agree. And I thus tend to think there's no point to an intermediate "half-measure" of more limited lens support in the compiler directly...

**Comment by puffnfresh** [comment]
This is pretty easy with the underscore syntax now:

```purescript
_dropdowns :: LensP State (Array DropdownItem)
_dropdowns = lens _.dropdowns _{dropdowns = _}	
```

I think it'd probably be better if `_.dropdowns` were a full lens instead, but this is good enough.
