### ISSUE TITLE
Can't publish anymore

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2753]
It worked before I updated to the latest psc.

```
$ pulp publish
Internal error: this is probably a bug. Please report it:
  https://github.com/purescript/purescript/issues/new    
                                                         
Details:                                                 
Unable to parse the date for a git tag: v0.0.21          
                                                         
* ERROR: Subcommand terminated with exit code 1
```

I looked at the source and found that it invokes this command:
```
$ git tag -l v0.0.21 --format='%(taggerdate:unix)'
error: unknown option `format=%(taggerdate:unix)'
```

**Comment by hdgarrood** [comment]
Oh bloody hell, we changed it to that fairly recently because the old command wasn't working for someone else!

I don't have time to look at this properly right now but it would be good to know a) what version of git you're using b) if you're able to find a command that works on your machine and prints the tag date of a given tag in ISO format.

**Comment by hdgarrood** [comment]
I'm kind of tempted to give up on the git CLI and just go digging around in .git at this point.

**Comment by rightfold** [comment]
a) I use Git 2.1.4
b) ...

**Comment by hdgarrood** [comment]
Understandable. Thanks!

**Comment by paf31** [comment]
Does this work?

```
git show -s --format=%ct v0.0.21
```

**Comment by rightfold** [comment]
@paf31 Yes, but since I use signed tags it also shows the PGP signature:
```
$ git show -s --format=%ct v0.0.21 | cat
tag v0.0.21
Tagger: rightfold <rightfold@gmail.com>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAABAgAGBQJYy+tIAAoJEBmdA3OskXqP6QQH/Rdl27Mu4zcj7E1EhceVVXLB
6fEj68ZjNLIrY4IiIDUqMLWXadSdpCmL4jHP+gtAC1ZlUDEN6k4Exsl8vMYeLW6f
zm4y7/H+UyNjpLy/UEFAdwAS19iavWLHMw+gxaO0ZAt8xAsYK0TqUJ1KnfPpOy1P
Sn713WhYpeOKIkcbOes7vxeTY/k5dC6zHTrtvj8slEdw0v+TGJsTAK7t/ePfLNei
RBg/9Nj85GgcplmLeUMb+aMgt2Be+37fMGOT3Zjej0p72/K5CQNEYba+MrqWgv9f
VdYBobOSb9AkEz291k2nhflTY8A82FrTGZurADHIJiQa3ldhSALY3VffTwXGQ64=
=yD7I
-----END PGP SIGNATURE-----
1489759010
```

**Comment by hdgarrood** [comment]
Can we safely assume that the last line will be the data we are interested in perhaps?

**Comment by paf31** [comment]
I'm not sure - I think you might be right that looking in `.git` might be the only good option.

**Comment by paf31** [comment]
It seems like just getting the created date on the file `.git/refs/tags/<tagname>` could work.

**Comment by rightfold** [comment]
Will that be correct for cloned repositories?

**Comment by hdgarrood** [comment]
Whatever we do, I'd like to verify any assumptions we want to make (such as whether this file modification date will be accurate) properly, i.e. preferably by looking at official documentation.

**Comment by paf31** [comment]
@rightfold One more - what about `git log -1 --format=%ct v0.0.21`?

**Comment by rightfold** [comment]
@paf31
```
$ git log -1 --format=%ct v0.0.21 | cat
1489759010
```

**Comment by paf31** [comment]
Looks promising.
