### ISSUE TITLE
Pulp fails to find PSC on Windows systems

### ISSUE THREAD

**Issue by KirinDave** [purescript/purescript#2755]
After installation via NPM on an up-to-date Windows 10 system in powershell, the pulp executable is unable to perform basic commands such as init, reporting the error:

    * ERROR: `psc` executable not found. (nor `psc.cmd`)

Other node-based executables such as bower and tsc work correctly.

**Comment by hdgarrood** [comment]
I know that other people use Pulp successfully on Windows &mdash; Pulp has a Windows CI build, even &mdash; so I think this might be something to do with your system in particular. Could you possibly try to investigate this a bit more? Also what is the output of `where psc`?

**Comment by KirinDave** [comment]
Even after a -g install, there is no psc.

**Comment by KirinDave** [comment]
I can't see any other executables other than pulp.

**Comment by hdgarrood** [comment]
Ok, that will be what's causing this. In case it wasn't clear, Pulp doesn't take care of installing `psc` for you, it expects you to put `psc` on your PATH somewhere. Are you following a getting started guide?

**Comment by KirinDave** [comment]
Ahh, I see what has happened. Somehow that didn't succeed and npm couldn't complete it. Restarting from scratch with both fixed the problem.

Sorry to be a bother! Please close my issue.

**Comment by hdgarrood** [comment]
Good, I'm glad you got it sorted. No worries!
