### ISSUE TITLE
Could not instantiate type variable under type constructor

### ISSUE THREAD

**Issue by int-index** [purescript/purescript#2756]
The program below should not result in a type error.

http://try.purescript.org/?gist=c87cefd559a66e9c310865b7834fde73&backend=core

```
module Main where

import Prelude
import Control.Monad.Eff (Eff)

pu :: forall eff. Eff eff Unit
pu = pure unit

type C eff = { pu :: Eff eff Unit }

-- Compiles.
sampleC :: C ()
sampleC = { pu: pu }

newtype Identity a = Id a

-- Does not compile.
sampleIdC :: Identity (C ())
sampleIdC = Id { pu : pu }
```

**Comment by kRITZCREEK** [comment]
It does work if you annotate `pu`:

```
-- Does compile.
sampleIdC :: Identity (C ())
sampleIdC = Id { pu : pu :: Eff () Unit}
```

I think this might be fixed by https://github.com/purescript/purescript/pull/2625 in master? I'll try it out later

**Comment by int-index** [comment]
> It does work if you annotate `pu`

I know. (Tried quite a few things while making this minimal example).

> EDIT: Yes it compiles fine on the current master

Meanwhile I checked it myself and I can confirm, it does compile with `master`.

Do you think adding this example to the test suite is a good idea? I'll go ahead and make a PR if so.

**Comment by paf31** [comment]
Yes, that sounds like a good idea! Since there's no "bug" here any more, I'll close this, but please feel free to add your example to `examples/passing`.
