### ISSUE TITLE
`psc-bundle` and `psc-publish` doesn't support `--version` option

### ISSUE THREAD

**Issue by shinnn** [purescript/purescript#2764]
In v0.11.0-rc.1, it would be nice if `psc-bundle` and `psc-publish` also support `--version` option to keep them consistent with other wrapper scripts.

```
$ psc --version
> 0.11.0
$ psc-bundle --version
> 0.11.0
$ psc-docs --version
> 0.11.0
$ psc-hierarchy --version
> 0.11.0
$ psc-ide-server --version
> 0.11.0
$ psc-ide-client --version
> 0.11.0
$ psci --version
> 0.11.0

$ psc-bundle --version
Invalid option `--version'

Usage: purs bundle FILE [-o|--output ARG] [-m|--module ARG] [--main ARG]
                   [-n|--namespace ARG] [--source-maps]
  Bundle compiled PureScript modules for the browser

$ psc-publish --version
Invalid option `--version'

Usage: purs publish --manifest FILE --resolutions FILE [--dry-run]
  Generates documentation packages for upload to Pursuit
```

**Comment by paf31** [comment]
Looking at the code, I would expect only `purs --version` to work. Weird..

**Comment by hdgarrood** [comment]
Some discussion around this in https://github.com/purescript/purescript/pull/2681/commits/b849532d11752d9579ea5248141d78d57effbfe7. It seems really weird that all the wrapper scripts work apart from just two, I have no idea what's going on there.

**Comment by shinnn** [comment]
@hdgarrood Thanks for pointing to the issue.

OK, if `--version` option is an unintentionally supported feature in other 7 scripts, I don't want `psc-bundle` and `psc-publish` to have it.

**Comment by garyb** [comment]
@shinnn the scripts are provided for backwards compatibility for now, but will be eventually dropped in favour of just using `purs` (as far as I know @paf31?), so for the tests that were testing each of the scripts maybe they can be dropped in favour of `purs --version`, since that is meant as the primary entry point.

**Comment by shinnn** [comment]
> the scripts are provided for backwards compatibility for now

IMHO you can just drop them in v0.11.0, since a lot of other breaking changes are already included in v0.11.0.

Anyway, providing wrapper scripts is not as simple as you think, because [`$@`](https://github.com/purescript/purescript/blob/98a7728d0d11ff1a12927657ea24385733c2abbd/scripts/psci#L2) doesn't work on Windows.

**Comment by garyb** [comment]
Yeah, that makes sense to me 👍. I think all the tools will be updated to use `purs` anyway so the scripts may turn out to be redundant.

**Comment by hdgarrood** [comment]
It's not too hard to provide wrapper scripts that work on Windows too - npm does something like this for executables - but on reflection I agree that it might be easier in the long run not to ship any wrapper scripts.
