### ISSUE TITLE
Remove runtime overhead of typeclass instances with no dictionary

### ISSUE THREAD

**Issue by doolse** [purescript/purescript#2768]
With the new `Union` typeclass which exists purely for proof at compile time as it has no functions, it would be nice if when it was used as a constraint the runtime didn't have to pass a dictionary in for it. 

I understand that might be a difficult thing to change but what might be more feasible is to remove the overhead of creating blank dictionaries from the dictionaries of other constraints. E.g. 

```purescript
class MergeDefaults (o :: # Type) (mr :: # Type) (mo :: # Type)
instance mergeInstance :: (Union o m mo, Union m r mr, Subrow r o) => MergeDefaults o mr mo
```

Currently whenever it's used generate something along the lines of:
```javascript
Data_Record.mergeInstance({})({})(Data_Record.subrow({}))
```
which could be optimised simply to `{}`

**Comment by garyb** [comment]
We could just remove the dictionary value usage entirely probably, so instead of converting the value to `{}`:

```
myFn(Data_Record.mergeInstance({})({})(Data_Record.subrow({})))(rec1)(rec2);
```

Could become:
```
myFn()(rec1)(rec2);
```

(see https://github.com/purescript/purescript/pull/2761#discussion_r107633521 - `{}` performs surprisingly badly)

**Comment by paf31** [comment]
I think it should be relatively easy to generate `__unused` in `Entailment.hs` if the dictionary

- has no member functions and
- has no subgoals

**Comment by matthewleon** [comment]
What do people think of a solution that removes the parameter entirely when it's an "empty" dictionary?

Disadvantages I can think of:
1) This would be (slightly) breaking; FFI code with "empty" constraints would have to have one "layer" peeled off.
2) When writing FFI code with constraints, you'd have to keep this in mind.

Advantages:
The JS generated would be simpler, more readable, and a bit more optimized.

**Comment by matthewleon** [comment]
Oops. On further thought, I think I understand that this is exactly what @paf31 is suggesting: By converting the parameter to `__unused`, it will subsequently be killed by `removeUnusedArg` in the CoreImp optimizer.

**Comment by matthewleon** [comment]
(though that still leaves us with an empty parameter, avoiding the FFI difficulties/inconsistencies but still leaving us with a needless function call. But I guess a later tool can get rid of that.)
