### ISSUE TITLE
Command line arguments parser

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#277]
Something like `cmdtheline`

**Comment by Profpatsch** [comment]
`purescript-node-args` is gone, what is the current recommendation for command line parsing?

**Comment by Profpatsch** [comment]
I can find

* https://github.com/paf31/purescript-yargs (wraps a node-library, so requires package.json setup)
* https://pursuit.purescript.org/packages/purescript-optlicative (pure purs, lightweight dependencies)
* https://pursuit.purescript.org/packages/purescript-optparse (port of Haskell’s optparse-applicative)

**Comment by afcondon** [comment]
i used `optparse` the other day and it worked fine, can't speak to the others
