### ISSUE TITLE
purs docs --html gets stuck somewhere on QuickCheck

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2772]
It seems like `purs docs` gets stuck when I run

```
purs docs --format html 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs'
```

@hdgarrood Do you have any time to look at this?

**Comment by hdgarrood** [comment]
I'll try to look at this soon but I might struggle to find time; I have a few big pieces of coursework due in the next couple of weeks. After that I'll have more time though.

**Comment by hdgarrood** [comment]
Started looking at this. I think it's getting stuck on `Data.List.ZipList`.

**Comment by hdgarrood** [comment]
I think it would be good to do another minor release and update Pursuit with this fix, as currently asking Pursuit to render anything that has a type-level string in it (e.g. `Data.List.ZipList`) seems to trigger the same issue.

**Comment by paf31** [comment]
Sounds good, I'll make a release later today. Thanks!
