### ISSUE TITLE
Suggestion: use stack-ghc-8.0.yaml as default

### ISSUE THREAD

**Issue by noraesae** [purescript/purescript#2777]
I suggest using `stack-ghc-8.0.yaml` as default, and rename the current `stack.yaml` as `stack-ghc-7.10.yaml`. The personal reason is that GHC 7.10 no longer works in the newest macOS.

Would there be a reason to keep GHC 7.10 as a default?

**Comment by garyb** [comment]
Big thumbs up from me 👍

**Comment by hdgarrood** [comment]
No objections here. Should we also consider dropping support for 7.10 while we're at it?

**Comment by paf31** [comment]
👍
