### ISSUE TITLE
[purs ide] Speed up loading by parallelising parsing

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2783]
Currently we parse all the source files sequentially in the `Load` command. We could gain significant speed boosts by doing this in parallel like the compiler does. I think this could be a good first task for a contributor to `purs ide`.

**Comment by gambogi** [comment]
Hi, I'm going to take a pass at this over the weekend.

**Comment by kRITZCREEK** [comment]
Sounds good, you can usually reach me on IRC or the fpchat Slack. If you get stuck feel free to reach out and we can take a look :)

**Comment by gambogi** [comment]
I have a preliminary change in a [branch](here:https://github.com/gambogi/purescript/tree/2783_purs-ide_load-par-parse).

Steps to reproduce the reported slowness would be helpful. What can I do to compare?

**Comment by kRITZCREEK** [comment]
If you start the server with `--log-level=perf` you get timings for how long it took to complete commands. If you find a decently sized project that parses with 0.11 you should be able to get some benchmarks by starting the server with globs and running the load all command.

The `slamdata` codebase takes about 10secs to load, but it's not ready for 0.11 yet, maybe you can create a test project that contains all of the core packages from here: https://github.com/purescript/purescript/issues/2745#issuecomment-289236186

**Comment by kRITZCREEK** [comment]
@gambogi you still want to finish this? Otherwise I might take a shot at it soon.

**Comment by gambogi** [comment]
feel free, coursework ramped up and my first pass didn't seem to be substantially better during testing.
