### ISSUE TITLE
`between` be all insane

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2787]
I don't... it, I... 🙊 

``` purescript
between :: forall a. Ord a => a -> a -> a -> Boolean
between low hi x
  | x < low = false
  | x > hi = false
  | true = true
```

``` javascript
var between = function (dictOrd) {
    return function (low) {
        return function (hi) {
            return function (x) {
                return true;
            };
        };
    };
};
```

**Comment by paf31** [comment]
I'm guessing this is due to some dodgy optimization which is looking at `if (true)` in the last case.

**Comment by paf31** [comment]
This worked before 0.11?

**Comment by garyb** [comment]
A knock-on of #2654 perhaps?

**Comment by paf31** [comment]
My money is on either that or pattern guards, since I know there was some new logic for fallthrough cases there too.

**Comment by garyb** [comment]
It was picked up by the tests in `purescript-orders`, so yeah it must have worked before... should be in the prelude tests now though actually, so I'll move it there.

**Comment by paf31** [comment]
I can confirm this is not an optimizer issue.
