### ISSUE TITLE
Exception compiling on ARM/armhf

### ISSUE THREAD

**Issue by tluyben** [purescript/purescript#2793]
After  a full day of cross compiling, at the end, I got this; 

purescript-0.11.0: build
Preprocessing library purescript-0.11.0...
In-place registering purescript-0.11.0...
Preprocessing executable 'purs' for purescript-0.11.0...
[ 6 of 14] Compiling Command.Docs.Html ( app/Command/Docs/Html.hs, .stack-work/dist/arm-linux/Cabal-1.22.5.0/build/purs/purs-tmp/Command/Docs/Html.o )

/usr/lib/node_modules/purescript/purescript-0.11.0/app/Command/Docs/Html.hs:181:17:
    Exception when trying to run compile-time code:
      app/static/pursuit.css: hGetContents: invalid argument (invalid byte sequence)
    Code: embedStringFile "app/static/pursuit.css"
    In the splice: $(embedStringFile "app/static/pursuit.css")

--  While building package purescript-0.11.0 using:
      /home/tluyben/.stack/setup-exe-cache/arm-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/arm-linux/Cabal-1.22.5.0 build lib:purescript exe:purs --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

Ubuntu Xenial with the GHC on there (7.10.3) and all tools standard on there. Tried it multiple times and really would not want to do a clean if I can prevent it.

**Comment by tluyben** [comment]
Ok, I posted too soon. Locale problem from anyone who has this as well. Not related to ARM. Works now. Can close.

**Comment by themoritz** [comment]
@tluyben I have the same problem (NixOS, GHC 7.10.3). What do you mean my "local problem" and how did you fix it?

**Comment by ijks** [comment]
@themoritz I had the same issue on Arch Linux, but I think I just found a workaround. The reason seems to be that my locale is a bit exotic:

```shell
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_NL.UTF-8
LC_CTYPE="en_NL.UTF-8"
LC_NUMERIC="en_NL.UTF-8"
LC_TIME="en_NL.UTF-8"
LC_COLLATE="en_NL.UTF-8"
LC_MONETARY="en_NL.UTF-8"
LC_MESSAGES="en_NL.UTF-8"
LC_PAPER="en_NL.UTF-8"
LC_NAME="en_NL.UTF-8"
LC_ADDRESS="en_NL.UTF-8"
LC_TELEPHONE="en_NL.UTF-8"
LC_MEASUREMENT="en_NL.UTF-8"
LC_IDENTIFICATION="en_NL.UTF-8"
LC_ALL=
```

So, by running the build with a more 'normal' locale, it stopped complaining:

```shell
$ LC_ALL="en_US.UTF-8" stack install --flag purescript:RELEASE
```
