### ISSUE TITLE
Wrappers for purs / armhf  

### ISSUE THREAD

**Issue by tluyben** [purescript/purescript#2794]
I managed to create a working purs binary for armhf. Seems everything works well, but psc/psci/etc do not work (they are ELF binaries for Linux64 Intel, and everything seems geared towards that). So I am wondering; are they just wrappers around purs ? And if they are, why are they substantial binaries and not just tiny bash scripts? 

If not; I cannot find the sources for those wrappers, only the binaries for mac/linux64/win64 in the tgz file? 

Then finally; now that I built that anyone; can I contribute it somewhere; it was rather hellish to build even on a fast (bunch of top of the line Xeon cores) cross compile Qemu setup. If not, I'll just toss them on some server and post the URL so others might benefit.

**Comment by hdgarrood** [comment]
As of 0.11.0, the compiler distribution consists of just one executable: `purs`, together with a few really tiny wrapper scripts to somewhat preserve BC. Previously, that is up to 0.10.7, the compiler distribution consisted of a few: `psc`, `psci`, `psc-publish`, and so on. Does that help?

**Comment by tluyben** [comment]
Yep, that's excellent! Thanks. 

Much easier for me. For backward compat, I'll create the wrappers so my build tools keep working normally until I refactored.
