### ISSUE TITLE
Inconsistent constraint syntax

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#2804]
Now that `=>` acts like a type operator in 0.11, functions have to be defined like this:

``` purescript
f :: forall a. C1 a => C2 a => a
-- before: f :: forall a. (C1 a, C2 a) => a
```

I was surprised to find that this new syntax isn't supported for instance declarations. This is a syntax error:

``` purescript
instance i :: C1 a => C2 a => C3 a
-- works: instance i :: (C1 a, C2 a) => C3 a
```

Is this intentional? It took me a minute to figure out how to declare an instance because I wasn't expecting the old syntax to work.

**Comment by paf31** [comment]
I think `instance i :: C1 a => C2 a => C3 a` would make sense if we could talk about `C2 a => C3 a` in isolation, but we can't. If `instance i :: C1 a => C2 a => C3 a` is valid syntax then I think `instance i :: (C1 a => C2 a) => C3 a` should be allowed as well. The syntax should reflect exactly those things which are possible, and in a minimal way, and I think the current approach achieves that gives the current constraints.

**Comment by tfausak** [comment]
Fair enough. It just surprised me.
