### ISSUE TITLE
Custom type errors should not use quotes

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2811]
I noticed that symbols in custom type errors get wrapped in quotes when rendered.

**Comment by michaelficarra** [comment]
Ah, this was my fault! 😳 I think it's because we're [running `prettyPrintString`](https://github.com/purescript/purescript/blob/df9a1d3142f0bad25a025cb7f07d88af164df2c2/src/Language/PureScript/Pretty/Types.hs#L127) on the `TypeLevelString` when we pretty print it.

**Comment by paf31** [comment]
Actually, I seem to have imagined this.
