### ISSUE TITLE
`Warn` constraints warning on definitions

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2813]
I wanted to add `Warn` constraints to the functions in `Debug.Trace` so that if they're left in the code the compiler will pick them up.

This works, but the warnings arise for each of the definitions in the module, as well as the places they're used - I can kinda see why it does that, but is it necessary?

I've worked around it by doing this for now:

```
class DebugWarning
instance warn :: Warn "Debug.Trace usage" => DebugWarning
```

and then using the `DebugWarning` constraint on the functions instead.

**Comment by paf31** [comment]
Do you mean a situation like this:

```purescript
foo :: Warn "blah" => a
foo = ...

bar :: Warn "blah" => b
bar = foo -- warning here, because we use foo
```

or something else? I think if we have a dictionary in scope already for the same warning string, then we should use it.

**Comment by garyb** [comment]
I mean if I write a function like:

``` purescript
foo :: Warn "blah" => a
foo = ...
```

Then the warning will arise both for the _definition_ of `foo`, as well as when it is used elsewhere.

**Comment by paf31** [comment]
No, that definitely shouldn't happen. Unless you're using `foo` somewhere, I don't know how it could. Can you paste the code and the warning please?

**Comment by garyb** [comment]
Hmm, although now you mention it, all the functions in question were calling another function with the `Warn` constraint, so maybe I'm being dense :)

**Comment by paf31** [comment]
No, it's still a good point. If the warning is the same, we can use the same dictionary and not warn.

**Comment by garyb** [comment]
Yeah, just confirming - that is the case here. I had the same warning on a bunch of functions, some of which dependend on earlier definitions with the "same" warning, but I guess the dictionary / symbol equality check needs improving for these or something. 👍
