### ISSUE TITLE
Duplicate label error partly wrong

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#2820]
The following code:
```
foreign import data Foo :: Effect

test :: forall e. Eff (foo :: Foo, foo :: Foo | e) Unit -> Eff (foo :: Foo | e) Unit
test f = f
```

Produces an error which appears to mention a wrong type in the initial part (same side twice):

```
  Could not match type
  
    ( foo :: Foo
    , foo :: Foo
    | e0
    )
  
  with type
  
    ( foo :: Foo
    , foo :: Foo
    | e0
    )
  
  while trying to match type Eff
                               ( foo :: Foo
                               , foo :: Foo
                               | e0
                               )
    with type Eff
                ( foo :: Foo
                | e0
                )
  while checking that expression f
    has type Eff
               ( foo :: Foo
               | e0
               )
               Unit
  in value declaration test
  
  where e0 is a rigid type variable
          bound at line 10, column 1 - line 10, column 11
```

**Comment by paf31** [comment]
This is an easy fix for anyone who'd like to work on error messages. It's due to the `sortRows` function in `Errors.hs`, which should take account of duplicates. I forgot to update it when I added support for duplicate rows.

If nobody takes this, I'll fix it before 1.0.

**Comment by natefaubion** [comment]
FWIW, I think this is affecting Halogen https://github.com/slamdata/purescript-halogen/commit/30621af15d558220b1aa7c5f224285853cb6d289

**Comment by Cmdv** [comment]
I can't seem to reproduce, I'm getting:

```
Label foo appears more than once in a row type.
  Relevant expression:

    \f ->
      f
```
which I assume is right?

**Comment by garyb** [comment]
@Cmdv is that on 0.11.x?

**Comment by Cmdv** [comment]
@garyb yeah I'm on `0.11.3[development build;...]`

**Comment by thoradam** [comment]
I actually took a stab at this yesterday but haven't tested it enough, does it make sense?
 https://github.com/thoradam/purescript/commit/1138c8fed58807d58636e311e2e3f666381ebd90
