### ISSUE TITLE
Implementing a stepper (PS developers input requested)

### ISSUE THREAD

**Issue by chrisdone** [purescript/purescript#2821]
Hi all,

## A stepper

I've been researching implementing a substitution stepper, which is essentially this.

```haskell
> :step (\x -> x) 1
1
> :step (\x f -> 1 + f x) 6
(\f -> 1 + f 6)
```

You are given a module and an expression to evaluate (or a name of a declaration defining an expression to evaluate, e.g. `:step it`), and you output the same expression in source code substituted by exactly one step. For the most part, this consists literally of just expanding any function application `id 6`, the function name `id` with its body `(\x -> x) 6` and substituting in the arguments `6`. When you hit an FFI function, you just return the name as-is. On the other hand, some package functions like `(+)` or whatnot can be specially handled and reduced (`1 + 3` => `4`). A handful of functions (e.g. `show 5`) will probably want to be implemented, otherwise they simple won't reduce further than `show 5`.

Later, it's possible to implement rules like "expand immediately applied lambdas", or things like that. Or: here is a set of rules, here is a set of transformation steps that I performed with the stepper, as a proof; please check that this can still be proved after I compile. Or maybe you can write classes which demand that instances provide a `proof` keyword that they satisfy the class's laws. Possibilities, endless, etc. But that's pie in the sky type of thinking. At the moment I'm just interested in a dumb stepper.

## Observations/insights

There are some observations I've made while investigating this problem, and how I'd *personally* like to approach it as something that's usable for ye olde common folke like myself, and those are:

1. **Not all code is nice to step through**: Some parts of the source language (be it Haskell or PureScript) do not substitute very well. That is, they can't be just plonked in directly: they need to be transformed somehow. An example of this is pattern matches on binds (cannot be dropped in) vs a case expression (can be dropped in directly). `If` expressions drop in nicer than guards. `Let`s drop in nicer than `where`. Etc. A "drop-in" expression does not need to be translated. Why is translation bad? Because when you're looking at how code evaluates, or writing a proof, you don't need that process obscured by translations. Syntactic sugar, basically. So one might implement a restriction (or a warning), but certainly a separation, between, the source language and the core language.
2. **The conversion from the source language to the core language should not change the structure of the code.** In GHC Haskell, when you desugar Haskell to Core, you get a different program. If you were to implement a stepper using Core, you wouldn't be stepping through Haskell anymore, you'd be stepping through Core. That's a usability disaster. So the function `SourceLang -> CoreLang` should preserve the structure, but it *may* reject some programs because they use too much sugar which doesn't lend itself nicely to stepping (or otherwise implement it later). 
3. **The `CoreLang` should be printable as source again**, and in exactly the same syntax as the `SourceLang`. 
4. **Renaming helps:** A (reasonable) renaming process on the `SourceLang -> CoreLang` enables much easier substitution as it doesn't require alpha-conversion. In GHC (and I believe PureScript?), `\x -> x` becomes e.g. `\x_12 -> x_12`. That's not amazing for usability, but variables can be renamed again just before being outputted to the user, reducing noise.
5. **Type classes:** In languages like Haskell and PureScript, you probably want to be able to step through code that contains type classes. So the instances need to be resolved during the conversion from `SourceLang -> CoreLang`. Ideally, we definitely would not insert dictionary arguments directly in the `CoreLang`, which would make it difficult to read. Rather, we'd preserve the look of the original source and make the dictionary arguments invisible, which would be preserved by type inference between each step. So for code like `let print x = log (show x) in do print 5; print "hi"`, you want that `print` still has its implicit argument, and that underneath we have `print showInt 5` and `print showString "hi"`, but to the user we show the original code. When we eventually have to expand `print 5`, we get `log (show showInt 5)` underneath, but again, showing `show 5`, and finally we unpack the method with `showInt.show` (or whatnot) and it becomes e.g. `(\x -> ...)` or in this case, as it's a built-in type, probably `"5"` immediately.

## Choosing PureScript

I've done some investigation into this in GHC. It would be nice to have a stepper in Haskell, but GHC's codebase is really not something I want to go near. The desugarer is just, wow. I looked through it and it's shockingly messy.

On the other hand PureScript's compiler is really cleanly written. I must praise the authors for doing a really nice job on making it readable. An additional advantage to PS is that the compiler currently compiles everything directly from source, which makes stepping arbitrarily a lot easier.

The difference between stepping PureScript and Haskell is just when to expand the lambda versus expanding the arguments, it's not a big deal. I'm more interested in exploring the design space and introducing stepping to newbies (both to programming and to pure-functional programming). If it also happens to turn out useful for PureScript developers and end up in psc-ide, that's cool too.

## Proposal

I've looked though the desugaring code [here](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar.hs#L52) and some related modules (e.g. type-classes). One thing that concerns me is that there does seem to be a *dependency* between the transformations that is somewhat implicit (although that module does lay it out clearly). I'd ideally write a new desugarer alongside this one like `desugarForStepping` which would produce the AST I described above, restricting things I don't want to deal with now, adding type class dictionaries, etc. Supposing I want to support a restricted subset of PureScript (for stepping), for e.g. this AST:

``` haskell
data Exp = App Exp Exp | App Exp ClassInstance | ClassMember String ClassInstance 
  | Var String | Let Binds | Case Exp Alts
-- More or less, not sure how I'd encode the instance dictionaries presently
```

Does what I wrote above sound achievable?

**Comment by chrisdone** [comment]
@paf31 Any thoughts? I'm bothering you just in case you're not watching the repo. 🙈

**Comment by paf31** [comment]
@chrisdone I like the idea, here are a few thoughts:

- I've seen a few things along these lines written _in_ PureScript, but not _for_ PureScript. One I could find the link for is [lambda machine](http://cdparks.github.io/lambda-machine/), but I remember at least one other that I can't find right now. Maybe this is not what you're looking for exactly, but it might help with teaching.
- I think starting from the functional core would be the way to go. It's not PureScript exactly, but it's pretty close, and it should be possible to print out a nice representation of the program. Using the JSON output from `--dump-corefn` should be a quick way to get something started.
- I think it might make sense to prototype something like this outside the main compiler, especially before 1.0. If you decide to use the functional core AST, it shouldn't change between 1.0 and 2.0, so you can assume stability. It would be quite nice to have something like this in PSCi, for pure code at least, but I'd prefer to wait until after 1.0 to merge anything new which is not already prioritized.

**Comment by hdgarrood** [comment]
I'm going to close this for now; it should be possible to prototype this outside the main compiler by using the compiler as a library, and this issue hasn't seen any movement for a long time. While this would be really nice to have, I think realistically we don't have the bandwidth for it at the moment.
