### ISSUE TITLE
TCO introduces memory leak

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#2822]
It looks like the JavaScript code generated by TCO retains the `__copy_var` function argument unnecessarily, creating a memory leak.

Some test code demonstrating this is available here: https://github.com/matthewleon/purescript-lists/tree/profile-length. `npm run qa` will create a `test.js` file in the `qa` directory, which you can then serve to verify the memory issues I'll discuss below.

The test is quite simple: in a single line of code, print the `length` of a sufficiently long lazy List (1000000 in the case of this test).

Expected behavior: `length` is a left fold of `( _ + 1)`. Since we aren't retaining a reference to the list anywhere in our PS code, as the list gets progressively forced and the length progressively calculated, GC should progressively clean up the forced left side of the list.

What actually happens: Alas, no. GC cannot kick in until the entire list is forced, by which point, with a sufficiently long list of sufficiently fat members, we will have devoured an enormous amount of RAM.

Why this happens: TCO compiles `foldl` into the JS below:

```javascript
    var go = function (__copy_b) {
        return function (__copy_xs) {
            var b = __copy_b;
            var xs = __copy_xs;
            var __tco_done = false;
            var __tco_result;
            var __tco_b;
            var __tco_xs;
            function __tco_loop(b, xs) {
                var v = step(xs);
                if (v instanceof Nil) {
                    __tco_done = true;
                    return b;
                };
                if (v instanceof Cons) {
                    __tco_b = op(b)(v.value0);
                    __tco_xs = v.value1;
                    return;
                };
                throw new Error("Failed pattern match at Data.List.Lazy.Types line 117, column 7 - line 119, column 40: " + [ v.constructor.name ]);
            };
            while (!__tco_done) {
                __tco_result = __tco_loop(b, xs);
                b = __tco_b;
                xs = __tco_xs;
            };
            return __tco_result;
        };
    };
    return go;
``` 

Line 2 retains a reference to `__copy_xs`, which is then copied into `xs` and never touched again. This reference results in retaining the entire linked list that we are gradually forcing, preventing GC from kicking in.

Solutions:

After line 4, you can add a line `__copy_xs = undefined`, which fixes the issue and allows GC to function properly.

Likewise, simple eliminating the copy of `__copy_xs` to `xs` and directly referencing `__copy_xs` fixes the issue.

As a side note, there is probably something similar happening above with `__copy_b` and `b`, but the potentially leak is far less damaging in that case.

**Comment by matthewleon** [comment]
Some data.

Heap timeline using the code generated by `purs`. Heap expands to 246 MB, with a tiny bit of GC in the middle. Then it gets stuck there.:
![screenshot 2017-04-10 at 2 42 33 pm](https://cloud.githubusercontent.com/assets/278859/24865369/f32c247a-1dfe-11e7-88f5-38b84e3354c6.png)

Heap timeline with the single `__copy_xs = undefined` inserted. We can see that Major GC kicks in during `foldl` and works very effectively, preventing the heap from expanding beyond 189 MB:
![screenshot 2017-04-10 at 2 46 06 pm](https://cloud.githubusercontent.com/assets/278859/24865406/0fd05970-1dff-11e7-9b7b-d277e71c9ba5.png)

**Comment by matthewleon** [comment]
As a side benefit, notice that the calculation drops from taking ~800ms to ~500ms.

**Comment by michaelficarra** [comment]
At least in this example, we can remove a bunch of those variables to simplify it.

```js
var go = function (__tco_b) {
  return function (__tco_xs) {
    var __tco_done = false;
    var __tco_result;
    function __tco_loop(b, xs) {
      var v = step(xs);
      if (v instanceof Nil) {
        __tco_done = true;
        return b;
      };
      if (v instanceof Cons) {
        __tco_b = op(b)(v.value0);
        __tco_xs = v.value1;
        return;
      };
      throw new Error("Failed pattern match at Data.List.Lazy.Types line 117, column 7 - line 119, column 40: " + [ v.constructor.name ]);
    };
    while (!__tco_done) {
      __tco_result = __tco_loop(__tco_b, __tco_xs);
    };
    return __tco_result;
  };
};
return go;
```

Maybe this will generalise to a more simplified TCO implementation?

**Comment by matthewleon** [comment]
@michaelficarra I think `__tco_loop` could also just be inlined into the `while`... At least, again, in the example above. But then, I imagine any JS optimizer could to that, too. I'll take this one step at a time, though, under the assumption that old patterns exist for a reason.

**Comment by paf31** [comment]
It's copied since the reference might change during the while loop. If the reference is reused somewhere else, that would be bad, but we could optimize it by inlining if the reference is used at most once in the body.

**Comment by matthewleon** [comment]
@paf31 I'm having trouble visualizing something that would cause the reference to change during the `while` loop. I imagine there is some obvious case that I'm just not able to conjure up. Is there a quick example you could give?

I can see why the "outer" parameters need to be copied – because of currying. But not the innermost/final one.

**Comment by michaelficarra** [comment]
Ah, yes, the code I suggested has a bug if the inner function (`function (__tco_xs) { ...`) is applied more than once. The fix is to re-separate the parameter bindings from the `__tco_...` bindings.

**Comment by matthewleon** [comment]
@paf31 okay I think I see what you mean now... TCO needs to be able to work on anything that has been compiled to `CoreImp` as a language, and can't make any assumptions regarding the kind of `CoreImp` that PS would generate in its current form, in order to remain robust. As such, we have to assume that a reference could be reused in a place where PS wouldn't necessarily do so. Hopefully I'm understanding this correctly.

**Comment by paf31** [comment]
In general, that's right, but I think it's possible to generate functions which reuse their argument, but not in recursive position, like this:

```purescript
rec x f = rec (x + 1) (\y -> f y + x)
```

**Comment by matthewleon** [comment]
Right, so in that case it is important that `__copy_x` be generated. `__copy_f`, however, is redundant, no? It seems to me that is will _always_ be redundant in the case of a tail call. Isn't that implicit in the very definition of a tail call in the first place?

**Comment by matthewleon** [comment]
Ah, I think I see it now. We in fact can't let `y` be overwritten. If this is the case, though, then that is another, separate bug in TCO, because it is currently generating the following:

```javascript
var rec = function (__copy_x) {
    return function (__copy_f) {
        var x = __copy_x;
        var f = __copy_f;
        var __tco_result;
        var __tco_x;
        var __tco_f;
        function __tco_loop(x, f) {
            __tco_x = x + 1 | 0;
            __tco_f = function (y) {
                return f(y) + x | 0;
            };
            return;
        };
        while (!false) {
            __tco_result = __tco_loop(x, f);
            x = __tco_x;
            f = __tco_f;
        };
        return __tco_result;
    };
};
```

**Comment by matthewleon** [comment]
Okay, got it. Subtle. Every piece of this mechanism has its purpose.

Thanks.

**Comment by paf31** [comment]
😄 Yes, although it's poorly documented, and it took this conversation for me to remember why I did this in the first place. I should document it at some point soon.
