### ISSUE TITLE
add support browserify options in `purs bundle`

### ISSUE THREAD

**Issue by coot** [purescript/purescript#2823]
I raised that initial in [pulp](https://github.com/bodil/pulp/issues/274) but it seems we need it first here.

**Comment by natefaubion** [comment]
`purs bundle` does not call browserify in any way. The linked issue just says that extra pulp arguments are routed to `purs bundle` instead of to `browserify`. It does not suggest that `purs bundle` should proxy arguments to `browserify` (it can't).

**Comment by hdgarrood** [comment]
Yeah, sorry, I wasn't clear. We shouldn't give `purs bundle` any knowledge of browserify.
