### ISSUE TITLE
psci hangs on macosx

### ISSUE THREAD

**Issue by PositronicBrain** [purescript/purescript#2829]
Tested with 0.11.2, 0.11.3.

How to reproduce

    mkdir test
    cd test
    pulp init
    pulp psci

The prompt loads, but you cannot input any character, or exit with ^C.

**Comment by hdgarrood** [comment]
I think this is really a bug in older versions of Node.js. What version are you using? Can you try updating?

**Comment by PositronicBrain** [comment]
You are right, I was using 5.11.1, it works with 6.9.5

**Comment by halcwb** [comment]
Same problem here with node v 6.2.2 using pulp -w repl. When the psci get's reloaded, entered keystrokes do not show up. When you hit enter, the characters get interpreted.
Starting the repl without the 'watch' option works normally.

**Comment by hdgarrood** [comment]
@halcwb See https://github.com/purescript-contrib/pulp/issues/240
