### ISSUE TITLE
[purs ide] Add import chomps line on windows

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#2833]
Running on windows, with a source file with CRLF line endings, add import seems to be removing a line after the import section. Converting to LF line endings, seems to be fine with everything else unchanged.

e.g.
```purescript
module Main.Module where

import Prelude
import Control.Monad.Eff.Console (log)
main = do
  log "Hello sailor!"
  logShow
```
becomes

```purescript
module Main.Module where

import Prelude
import Control.Monad.Eff.Console (log, logShow)
  log "Hello sailor!"
  logShow
```

Called as `addImport` with temp file as input/output

Originally raised as https://github.com/nwolverson/vscode-ide-purescript/issues/52

**Comment by paf31** [comment]
@kRITZCREEK Please reprioritize these if you think they're not good for 1.0.
