### ISSUE TITLE
purs cmd-line help messages should pluralize module paths argument

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#2835]
For example:

```
Usage: purs repl [FILE] ([-p|--port ARG] | [--node-path FILE]
                 [--node-opts OPTS])
  Enter the interactive mode (PSCi)

Available options:
  -h,--help                Show this help text
  FILE                     Optional .purs files to load on start
  -p,--port ARG            The web server port
  --node-path FILE         Path to the Node executable
  --node-opts OPTS         Flags to pass to node, separated by spaces
```

The more appropriate name for the `FILE` parameter would be `FILES`. It's subtle, but I can easily imagine a newbie stumbling on it.

**Comment by nwolverson** [comment]
Another subtlety that might be captured is that the files parameter is/can be a glob - i.e. a literal glob rather than expanded by your shell. Relevant at least where your shell may not support `**`, but I think preferable in general.
