### ISSUE TITLE
Instances and duplicate rows

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2838]
I'm not sure whether this is technically a bug or not... it's very unfortunate if it is the correct behaviour though, as it means we can't really take advantage of duplicate rows after all.

Explanation: in `purescript-dom`, I made this change:

``` diff
 foreign import addEventListener
    :: forall eff
     . EventType
 -  -> EventListener (dom :: DOM | eff)
 +  -> EventListener eff		 
    -> Boolean
    -> EventTarget
    -> Eff (dom :: DOM | eff) Unit
```
In theory this shouldn't be a problem now, but it doesn't play well with `liftEff`:

```
[1/1 TypesDoNotUnify] src/Halogen/Aff/Util.purs:33:36

  33  awaitLoad = makeAff \_ callback -> liftEff $
                                         ^^^^^^^
  
  Could not match type
  
    ( dom :: DOM
    , dom :: DOM
    | eff2
    )
  
  with type
  
    ( dom :: DOM
    , dom :: DOM
    | eff2
    )
  
  while solving type class constraint
  
    Control.Monad.Eff.Class.MonadEff ( dom :: DOM
                                     , dom :: DOM
                                     | eff2
                                     )
                                     (Eff
                                        ( dom :: DOM
                                        | eff2
                                        )
                                     )
  
  while checking that type forall a m eff. MonadEff eff m => Eff eff a -> m a
    is at least as general as type t0 -> t1
  while checking that expression liftEff
    has type t0 -> t1
```

There is the #2820 thing happening here, but aside from that, the real issue is this instance doesn't work in the presence of the duplicate row.

**Comment by paf31** [comment]
I'm tempted to say this is correct behavior, and that the type was already correct.

**Comment by garyb** [comment]
That's what I suspected, it's just unfortunate as it means that the primary case where duplicate label errors were annoying is still often true, even after they've been allowed. It's rarely a problem for me, because I know the "always use the exact same effect row everywhere" rule, but it has always been a usability hurdle for newcomers, and an easy mistake to make.

**Comment by garyb** [comment]
I guess this is where that idea of the "normalised row" (in the sense of set-ifying the row) constraint that was mentioned once would possibly have been helpful.

**Comment by paf31** [comment]
@garyb Can you post the full code snippet please?

**Comment by garyb** [comment]
Sure, I'll try and concoct a minimal example - the instance I mentioned isn't really suitable for snippetifying.

**Comment by paf31** [comment]
Any more thoughts on this one?

**Comment by garyb** [comment]
I've still got this on my todo list of things to return to, just since we restored the old signature in `-dom` it's not been so pressing.

**Comment by paf31** [comment]
@garyb Is there anything to do here? If there is, I'd like to label it. I think repeating the label in both the callback and the result makes sense, since it's the only way in which we could wrap such a thing in `ContT` and use something like `forever` and not get an infinite type. Relying on duplicate labels is a nice convenience for simple cases, but it reduces the number of ways in which we can use the function in a type-safe way.

I do think it was the right decision to allow duplicate labels though, but it was to deal with things like `catchException`, not necessarily things like this, although I appreciate it's frustrating.

**Comment by garyb** [comment]
Closing this as I think `Nub` would probably work for what I had in mind here.
