### ISSUE TITLE
Proxy syntax

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2839]
Discussed some of this on Slack with Phil and Nathan. This is a way to make proxies easier to use without going full polykinds.

New type syntax for proxies. `Proxy` will no longed be a user-defined type, but rather a language construct.

    <type> ::= 'Proxy' <type>
             | …

![kindinf]

New expression syntax for proxy literals. This syntax comes from the recent [GHC syntax for type arguments][ghc], however we prefer proxies so that the order of nested universal quantifiers stays insignificant.

    <expr> ::= '@' <type>
             | …

![typeinf]

Code generation of such expressions may just be `{}` or `null` or something. The values can't be inspected so it doesn't matter what their JS representation is.

[ghc]: https://ghc.haskell.org/trac/ghc/wiki/TypeApplication
[kindinf]: http://mathurl.com/n7set37.png
[typeinf]: http://mathurl.com/mkbnlyd.png

**Comment by paf31** [comment]
I think adding special support for things like `Proxy` and `Exists` is a nice practical option for 1.0, as opposed to full-blown polykinds or some "unkind" experiment.

**Comment by paf31** [comment]
Let's move `Exists` into `Prim` and make it polykinded at the same time?

**Comment by natefaubion** [comment]
You have to make the construction/elimination built-in too, right? Can't have functions in `Prim`.

**Comment by paf31** [comment]
No, they'd still live in `purescript-exists`, but with the new types.

**Comment by paf31** [comment]
Oh you're right, sorry.
