### ISSUE TITLE
Update codegen to use mangled names in exports?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2847]
For example, at the moment, we do:
```
module.exports = { "foo'": foo$prime }
```

Perhaps instead we should use the same name in the exports that we have locally:
```
module.exports = { foo$prime: foo$prime }
```

This applies to any mangling, `$prime` was just an example, there are a bunch of other cases too.

This would fix a whole bunch of warnings that `rollup-plugin-purs` spits out, and would match the behaviour that we'll eventually use for ES6 modules whenever that happens.

**Comment by paf31** [comment]
I'd be happy to do this at the same time we move to ES6, since I think the current behavior is slightly nicer from the JS side.

**Comment by hdgarrood** [comment]
Do we have an issue open for something like this already? I vaguely remember something about changing mangling to help with a future switchover to ES6.

**Comment by garyb** [comment]
@hdgarrood you're right, #2558 - I thought it was tucked away in one of the mega-ES6-discussion threads
