### ISSUE TITLE
.cabal file has invalid url to issue tracker

### ISSUE THREAD

**Issue by bergmark** [purescript/purescript#2853]
https://hackage.haskell.org/package/purescript-0.11.4 points to purescript.git/issues. I'm assuming it has something to do with hpack, is `.git` in the package.yaml for a reason?

**Comment by seanwestfall** [comment]
I was trying to use hpack for this PR https://github.com/purescript/purescript/pull/2849 but can't get it to update the cabal file. Is this related?

**Comment by hdgarrood** [comment]
@seanwestfall I don't think so, #2854 fixes this.

**Comment by kRITZCREEK** [comment]
fixed in #2854
