### ISSUE TITLE
[purs ide] Sourcespans are relative instead of absolute since 0.11

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2855]
This breaks all the editors go-to-definition. It's most likely just a matter of prepending the current working directory of the server when extracting the source spans from the ASTs.

The error reporting is also affected by this, but that's because the JSON format of the compiler errors changed, so we can't really fix it in purs ide.

EDIT: Introduced in #2707

Question @garyb @paf31 :
If this was done solely for prettier error messages, wouldn't it be better to trim the paths in the pretty printer rather than during parsing?

**Comment by paf31** [comment]
Well we can't solve this only during pretty printing, since we need to be in `IO` to get the current directory.

**Comment by kRITZCREEK** [comment]
What about adding a field to `PPEOptions`:

`ppeRelativeDirectory :: FilePath` and make the pretty printer drop prefixes from file paths. This also works nicely with `mempty` as a default for "drop nothing".

**Comment by paf31** [comment]
Sounds good to me!
