### ISSUE TITLE
Unnecessary newtype constructor application with ($)

### ISSUE THREAD

**Issue by craigbilner** [purescript/purescript#2866]
Hi,

I raised this on gitter and it was suggested it may be a bug.

I created a `newtype` [here](https://github.com/craigbilner/pbee/blob/master/ch2/src/Main.purs) called `Area` which is returned from the `circleArea` function.

```
circleArea :: Radius -> Area
circleArea (Radius r) = Area $ pi * r `pow` 2.0
```

when I ran `pulp build -O --to output.js`

it turned it into

```
var Area = function (x) {
  return x;
};
  
var circleArea = function (v) {
  return Area($$Math.pi * $$Math.pow(v)(2.0));
};
```

but I was expecting there to be no `Area` func at all, just the value passed. Is this a bug or my misunderstanding?

**Comment by hdgarrood** [comment]
Thanks for the report, but this is not a bug. The reason we generate an `Area` function is that we want codegen to be predictable; if the module exports an `Area` constructor, then the JS module produced as output from the compiler should export a corresponding function. Perhaps at some point in the future we might be able to optimize this away with a whole-program optimization step, but for now at least, there are other lower-hanging fruits with respect to optimization anyway.

**Comment by garyb** [comment]
The `Area` function needs to exist as the compiler isn't clever enough to optimize something like `map Area xs` - but you're right that it shouldn't appear in `circleArea`. It's occuring due to the use of `($)` - if you use parens instead it won't insert that constructor.

Pretty sure we can fix that without too much trouble, so I'm going to reopen this.

**Comment by hdgarrood** [comment]
Oops, sorry :)

**Comment by omefire** [comment]
Hey all, I'm new around here and trying to contribute. I'm gonna take a shot at helping fix this issue.

**Comment by omefire** [comment]
Quick status regarding this issue:
I've been out for the last two weeks. I've resumed work on this issue and will provide updates as I move forward with this or if I need any help.
