### ISSUE TITLE
TCO codegen has bad hygiene, results in undefined values

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#2868]
If you name an argument to a tco'd function `result`, it clashes with the tco generated name `tco_result`, yielding undefined values.

```
            var go = function (__copy_result) {
                return function (__copy_p) {
                    var __tco_result = __copy_result;
                    var __tco_done = false;
                    var __tco_result;
```

**Comment by natefaubion** [comment]
Since PureScript identifiers can't have `$` in them, maybe special variables should use that to avoid clashing.

**Comment by paf31** [comment]
Thanks for the report. I think the simplest fix is to just modify the `__tco_` prefix for variables to something like `__tco_var_`, yes?

**Comment by natefaubion** [comment]
As long as all the regular vars are prefixed with `__tco_` as well, then it's not hygienic. You have to name them in such a way it can't clash. Using `__tco$result` and `__tco$done` would work, though.

**Comment by paf31** [comment]
Well `"__tco_var_" <> s` is never equal to `"__tco_result"`, right?

**Comment by natefaubion** [comment]
Yes, that would work.
