### ISSUE TITLE
Documentation of type does not list instances if instances were defined using operator alias for type

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2872]
The instance is defined as such:

```instance eqQuotient :: (Eq a, Canonical a e) => Eq (a / e) where```

Instead of such:

```instance eqQuotient :: (Eq a, Canonical a e) => Eq (Quotient a e) where```

Because of this, the documentation does not list the instances under the `Quotient` type. Example: https://pursuit.purescript.org/packages/purescript-quotient/0.0.3/docs/Type.Quotient#t:Quotient

**Comment by paf31** [comment]
Sounds like we need to run the operator desugaring as part of the docs generation process.

**Comment by seanwestfall** [comment]
I'll take this one on as a new contributor, to be a new contributor.

**Comment by hdgarrood** [comment]
I've removed the new contributor label, as this turns out to be not that simple after all. Also I'm looking at it :)

**Comment by seanwestfall** [comment]
@hdgarrood You're right, it's not that easy. If you want, I can run you through what I've found so far. I don't even think the fix exists in this repo, but is more along the lines of being somewhere in here https://github.com/purescript-contrib/pulp with the `docs` command -- but even when you get that far, you'll find that what actually gets on to the pursuit page is something else, that's built into json somewhere I don't know, that maybe only @paf31 knows...

**Comment by hdgarrood** [comment]
It's fixed in this repo already: #2991 :smile:

**Comment by hdgarrood** [comment]
The majority of the HTML generation code is now in this repo, by the way, to support `purs docs --format html`; there's just a small amount of additional stuff inside Pursuit to take care of generating the right links between different packages and so on.
