### ISSUE TITLE
Host binaries somewhere not affected by API rate limits?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2877]
Can we please try to find somewhere to host the compiler binaries which is not subject to API rate limits? It's taken up an alarming amount of my time trying to get various projects' CI to work (right now, pulp); going to get a token and working out how to make it available to the CI build in a way that doesn't allow other people to authenticate as you to github is the relatively easy part, and then you have to pass it through the myriad of different environments that CI scripts seem to have to deal with and make sure the environment variable is actually accessible to the part of your CI that needs it. I'm sure it's not just me that this has been a time sink for.

**Comment by garyb** [comment]
I've not run into being rate limited when fetching the binaries myself, but it seems reasonable.

Surprisingly we never seem to have had rate limiting problems with the core libraries too - they fetch the compiler with unauthenticated requests. They rely on the link one would get in the browser and following a redirect though, so maybe that isn't a rate limited endpoint. I don't know.

What was the CI trouble? Adding the private variable in travis settings for the repo has been enough to have it accessible via the environment whenever I've tried it. The only gotcha is the variable being unavailable for PRs from outside the repo for security reasons.

**Comment by hdgarrood** [comment]
I take back what I said about getting the CI scripts to work, I think I have just been applying the configuration to the wrong repo 😐

> The only gotcha is the variable being unavailable for PRs from outside the repo for security reasons.

This is a very good point actually - most of the recent PRs pulp received failed CI because of rate limiting, and so configuring an api token wouldn't help address that.

**Comment by Pauan** [comment]
Is this the problem where `npm install purescript` takes 5+ minutes because of installing the PureScript binary? Because I've had that happen many times, and somebody else on Gitter had it too.

Then again, I'm using a VPN, so that could explain why the throttling is happening.

**Comment by hdgarrood** [comment]
I haven't seen that before, so I'm not sure if it's to do with us hosting the binaries on GitHub.

**Comment by paf31** [comment]
We could always host binaries somewhere on purescript.org if need be.

**Comment by garyb** [comment]
> Is this the problem where `npm install purescript` takes 5+ minutes because of installing the PureScript binary?

I don't think so, the rate limiting rejects requests if you exceed the quota.

**Comment by hdgarrood** [comment]
> somewhere on purescript.org

i.e. on the same server that hosts Try PureScript and Pursuit? Might there be an issue with download limits imposed by the hosting service if we did that?

It just occurred to me that IPFS might be a good option, I might start by trying that.

**Comment by hdgarrood** [comment]
I think I was mistaken before. From GitHub’s docs:

> Limitations on binary files
> 
> We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 2 GB in size.

https://help.github.com/en/articles/about-releases#limitations-on-binary-files

I think the rate limiting only arises when you try to use the API endpoint for retrieving releases or release assets via api.github.com, such as https://api.github.com/repos/purescript/purescript/releases/assets/11221946

Instead, people should use the normal download link, such as https://github.com/purescript/purescript/releases/download/v0.12.3/linux64.tar.gz. Thankfully most ci scripts and the npm compiler binary package all already do this. I think this is actually just something we need to fix in psvm.

**Comment by hdgarrood** [comment]
@garyb in retrospect I should have read your original response more closely, since you immediately sussed it 😅
