### ISSUE TITLE
Appveyor CI fails with Access Violation

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2880]
```
[ 2 of 14] Compiling Version          ( app\Version.hs, .stack-work\dist\ca59d0ab\build\purs\purs-tmp\Version.o )
Segmentation fault/access violation in generated code
```

Observed in #2878.

**Comment by hdgarrood** [comment]
If the problem is due to gitrev and the TH in that file, we might be able to work around this by modifying `appveyor.yml` to always build with `--flag purescript:RELEASE` so that it doesn't attempt to use TH or gitrev.

**Comment by hdgarrood** [comment]
Looks like it isn't specific to that module, as the same thing happened on a different module here: https://github.com/purescript/purescript/pull/2978#issuecomment-313927396

**Comment by kRITZCREEK** [comment]
```
[ 2 of 14] Compiling Version          ( app\Version.hs, .stack-work\dist\ca59d0ab\build\purs\purs-tmp\Version.o )
[ 3 of 14] Compiling Command.REPL     ( app\Command\REPL.hs, .stack-work\dist\ca59d0ab\build\purs\purs-tmp\Command\REPL.o )
Segmentation fault/access violation in generated code
```

I have a feeling it's still breaking in `Version`, but because of parallelism it showed the compiling message.

**Comment by hdgarrood** [comment]
Oh, good point, yeah.

**Comment by paf31** [comment]
Moved into #3010
