### ISSUE TITLE
Something akin to "stack script"

### ISSUE THREAD

**Issue by felixSchl** [purescript/purescript#2883]
I think this would be useful at least in the node.js context. Build and maintenance scripts and so on could then be expressed using purescript and simply run, while still retaining the ability to call into any relevant JS libraries. I just wanted to bring this up for discussion, I have not put any thought into how this would actually work.

For what it's worth here was the RFC to add a "script" command to stack: commercialhaskell/stack#2805.

**Comment by hdgarrood** [comment]
Thanks, but we tend to try to keep this issue tracker for features that are a bit more developed / have already had some amount of thought into how they should work. Also if the idea is to behave like stack in that you can easily pin down exact versions of libraries to depend on, it shouldn't be part of the compiler, as the compiler doesn't assume any particular package manager. Perhaps the psc-package repo might be more appropriate?

**Comment by paf31** [comment]
I agree this seems like a better fit for something like `psc-package` and not the compiler itself. Please can you move this to an issue there? Thanks!
