### ISSUE TITLE
How to print & inspect the AST data type ?

### ISSUE THREAD

**Issue by omefire** [purescript/purescript#2887]
Hi all, 
I'm new here and wanna help out with some bugs in the compiler & tools, and various other contributions.
I'm stuck I've been trying to print/show/inspect the AST data types produced when I compile a sample 'hello world' program: https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Make.hs#L365

**Comment by kRITZCREEK** [comment]
@omefire Maybe this can help? https://github.com/purescript/purescript/pull/2590 It might be a bit outdated, but a starting point nonetheless

**Comment by paf31** [comment]
@omefire There are also `show` and the `prettyPrintX` family of functions for printing out various internal data types. I often use GHCi for inspecting them as well.

If there's no bug here, I'm going to close this. I suggest #purescript IRC or Slack as a better place for getting answers to these sorts of things, FYI.
