### ISSUE TITLE
[purs ide] Revamp import formatting

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2888]
I'd like to bring up `purs ide`'s import formatting for discussion, so we can discuss the pros and cons of different formats and finally come to an informed decision, which will then be implemented.

## The current format

1. All implicit imports in the ordering they were parsed in
2. All qualified imports sorted by module name
3. All explicit imports, sorted by module name

``` purescript
import Prelude
import Control.Module as CA
import Data.Module as DM
import Control.Explicit (a, b, c)
import Data.Explicit (a, b, c)
```

The original motivation for preserving the ordering of implicit imports was to make sure adding an explicit import didn't alter the compiler emitted warnings, but that's a weak argument. The reason for grouping imports by implicit, qualified and explicit was that as a user of `purs ide`'s import functionality you primarily want to edit implicit and qualified imports by hand, and so these are placed at the top (There's functionality to add implicit imports through commands as well, but it's clunkier to use than explicit imports and in the common usecase you only have the implicit `Prelude` import anway).

## A new format

The current format is optimized for users of `purs ide`, but a drawback is that it makes it harder to work together with people who are not using it, because you can't run a single sort command on the import section, and instead have to run a sort for both qualified as well as explicit imports.

1. Implicit imports sorted by module name
2. An empty line
3. Mixed qualified and explicit imports sorted by module name

``` purescript
import Prelude

import Control.Explicit (a, b, c)
import Control.Module as CA
import Data.Explicit (a, b, c)
import Data.Module as DM
```

Any widely used editor (Atom, VSCode, Emacs, ..., even Vim) can format a selected region, so this format can be used by `purs ide` users as well as non-believers, without too much friction. The additional newline after the implict import(s) helps distinguish the two sections, and makes it easier to select and sort the second block.

By now I prefer the second format, but I'm hoping we can get some more opinions to find a consensus on this topic. One drawback of changing the format would be that we'd create annoying import diffs for projects that have been using the old format so far.

**Comment by paf31** [comment]
👍 for the new format. Now's the time to break it 😄

**Comment by garyb** [comment]
:100: 👍 from me, obviously :smile:

**Comment by afcondon** [comment]
Aspirationally, it would be nice if version control changes were more intelligent about imports anyway - i know that's not likely to happen any time soon, but conceptually i think the imports should be like a separate file with it's own diffs.

**Comment by kRITZCREEK** [comment]
Then it's settled. Option 2 will be implemented :)

**Comment by nwolverson** [comment]
I like it, for me the main benefit (other than reducing collab. friction) is actually that if you have mixed qualified and unqualified imports of the same module they will be together, e.g. the common

```purescript
import Data.List (List)
import Data.List as List
```

(More often I just accidentally import explicitly & unqualified from something I've also imported qualified without noticing)

**Comment by kRITZCREEK** [comment]
@nwolverson That particular problem is just gone for me after https://github.com/epost/psc-ide-emacs/pull/99. Might be worth a shot to try and implement that in Atom as well. I think we could support something like this from within the completion command if we parsed the file we are completing an identifier in.
