### ISSUE TITLE
Alternative binding syntax like Idris

### ISSUE THREAD

**Issue by utatti** [purescript/purescript#2894]
It would be nice to have alternative binding syntax in PureScript.

```purescript
data X = A Int | B

getA :: forall e. Eff e X
getA = pure $ A 123

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  A a <- getA | B -> error "it is B"
  logShow a
```

It helps to avoid partial pattern bindings. Here are some more examples

```purescript
A <- getX
       | B -> ...
       | C -> ...

A <- getX | _ -> ...
```

I'm not sure if it can work with `let-in` bindings too.

```purescript
let
  [one, two] = someArr | _ -> ... -- which type should this expr have here?
  otherBind = otherExpr
in
  ...
```

Currently pattern bindings are desugared into case expression, so implementation itself should be minor.

**Comment by noraesae** [comment]
I'm working on this and it seems quite nice. The main merit from this is that we can easily avoid partial expressions. For example,

```purescript
someAction = do
  -- result here is not Partial!
  Right result <- anotherAction | Left err -> throwError err
  ... do something with result ...

someArrayAction = do
  x : xs <- generateNonEmptyArray | Nil -> panic
  ... do something with x and xs ...
```

Using it with `let-in` also works well.

```purescript
parseInt :: String -> Maybe Int

myParseInt :: String -> Int
myParseInt str =
  let
    Just result = parseInt str | Nothing -> 0
  in
    result
```

I will upload a PR when I finish the work.

**Comment by kRITZCREEK** [comment]
I actually suggested this once, but it was rejected. I can't check right now, but if you search closed issues by me you should find some discussion on it.

**Comment by noraesae** [comment]
@kRITZCREEK I found it: https://github.com/purescript/purescript/issues/1928

I am sad this syntax was once rejected. However, I guess the context of discussion has been changed.

The thing is that pattern binding with `let` or `<-` has already been implemented (#2627). Currently, if the binding is partial, we should manually call `unsafePartial` to peel the `Partial` constraint off. Therefore, now it seems natural to provide a way to handle other (alternative) cases to avoid the partial bindings.

The pattern binding is implemented as a disugaring path to case expression, so adding alternative cases also seems natural to me.

```purescript
-- before
A <- action
a
-- after
action >>=
  case _ of
    A -> a

-- before
A <- action | B -> b
a
-- after
action >>=
  case _ of
    A -> a
    B -> b
```

Further discussion is surely welcomed 😃

**Comment by paf31** [comment]
I'd like to avoid adding more syntax for something which can be accomplished fairly easily with `case`. The `case` version is fairly readable, at least to me.

**Comment by noraesae** [comment]
I agree that using `case` is still a simple and intuitive way, but it can easily result in more indents.

```purescript
someMaybe >>= case _ of
  Just a -> do
    doSomething
    otherMaybe a >>= case _ of
      Just b -> do
        ..
      Nothing -> 
        ..
  Nothing ->
    ..

-- with alt bindings
Just a <- someMaybe | Nothing -> ..
doSomething
Just b <- otherMaybe | Nothing -> ..
..
```

The code above looks a bit silly because it's `Maybe` and we can just use monad transformer stack, but there are still many cases where alt binding can be useful. For example, when we're playing around lists and we'd like to pattern-match only `x:xs` case and then just discard `Nil` as an exception. There could be other examples where we'd just like to bind a pattern, and handle (or just discard) other alt patterns as an exception. Using `case` for these can easily make code verbose.

I'm not like arguing this feature must be included, but just hope this can be accepted because it was really handy when playing with it in Idris, and actually help us to write safer code as it provides simple way to avoid non-exhaustive pattern.

**Comment by hdgarrood** [comment]
Sorry, but I agree with @paf31 on this one; this doesn't seem to me to be enough of an improvement on what we have currently to justify new syntax.

**Comment by noraesae** [comment]
I can agree we should be careful when adopting a new syntax.

Nevertheless, I still think that for the time being it's difficult to use pattern binding without being partial.

```purescript
data X = A | B | C

fnA = do
  A <- someAction
  -- already partial!
```

Currently we have following ways to handle these.

- Use pattern binding and manually use `unsafePartial`
- Do not use pattern binding, use `case` instead

However, I think the options above are quite limiting and make it difficult to use pattern binding (I personally feel reluctant using `unsafePartial` 😞).

If it's difficult to adopt this syntax, it would be nice to provide devices to handle these cases.
