### ISSUE TITLE
Generate TypeScript Definition Files

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#29]
To expose a PureScript library to TypeScript, we can generate `.d.ts` files from an externs file.

**Comment by minoki** [comment]
In case anyone is interested in this topic: I've written a tool to do this. See https://github.com/minoki/purescript-tsd-gen

**Comment by i-am-tom** [comment]
I think @justinwoo has also worked on some stuff around this!

**Comment by justinwoo** [comment]
My thing is just a PureScript library in the end though https://github.com/justinwoo/purescript-ohyes

**Comment by babakness** [comment]
If PureScript compiled to TypeScript and could read TypeScript definitions, it would take over the front-end world.

**Comment by garyb** [comment]
That'd be nice, but TS can't (directly) express a lot of PS types and vice versa. Plus there's effects to consider.

I think tools that assist with some cases is the best we'll get really.

**Comment by muratg** [comment]
I think this would be really nice. It would make it much nicer to make libraries with purescript and make them usable with the typescript/javascript world. But also in integrating purescript components into existing TypeScript codebases.
