### ISSUE TITLE
Rename classes in Prim

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2903]
We'll probably end up adding more automatically-solved classes after 1.0, so I think it makes sense to move them into submodules of `Prim` before 1.0, and not import those modules automatically. 

For example, `Union` and `RowCons` could move into `Prim.Rows` (and we'd rename `RowCons` to just `Cons` while we're at it, probably).

I'll put this under 1.0 for now.

**Comment by parsonsmatt** [comment]
Currently there are five classes:

- `Partial`
- `Fail`
- `Warn`
- `Union`
- `RowCons`

Implementing this issue would put `Union` and `RowCons` into a separate module, `Prim.Row`, which would not be imported by default.

`Fail` and `Warn` are related, too -- would `Prim.Errors` be a good module for them, or do we want them to be imported as normal?

`Partial` seems like the only one that stays in the `Prim` module.

**Comment by hdgarrood** [comment]
I don't have a strong opinion either way on whether `Fail` and `Warn` should stay in `Prim`, although I'd say if we do move them to a submodule of `Prim`, the related types (`TypeString`, `TypeConcat`, etc) should probably go with them.

**Comment by hdgarrood** [comment]
I've thought about this a bit more and changed my mind: see https://github.com/purescript/purescript/pull/3176#issuecomment-353048254

> I think the idea is that we decide that pretty much everything apart from the most ubiquitous stuff belongs in submodules of Prim, and only Prim is imported automatically. Also, Prim itself should change very rarely. This gives us the freedom to be able to add more kinds/types/classes into submodules of Prim in the future without worrying about breaking people's code (e.g. if someone has already created a class called Warn, we want them to be able to upgrade the compiler to a new version including a compiler-magic class of the same name without having to change their imports).
