### ISSUE TITLE
psc-ide-server-start post hook

### ISSUE THREAD

**Issue by Ptival** [purescript/purescript#2904]
Hey everyone,

The architecure is pretty great, I just have one tiny problem.
I was trying to have my emacs config to run `psc-ide-server-start` for me.

So I added:
```
(psc-ide-server-start (psc-ide-suggest-project-dir))
```
And something to start `flycheck-mode`.

But on startup, I get spurious messages, it seems possibly while the server is loading the files.

This might be mitigated if there was a way to make flycheck-mode only activate after the server is done starting?

**Comment by kRITZCREEK** [comment]
Let's move this issue to the [emacs plugin repo](https://github.com/epost/psc-ide-emacs).
