### ISSUE TITLE
Potential bug with generated JavaScript

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript#2906]
I'm failing to understand why the following is happening and wondering if it's a bug or if I'm just doing something wrong.

Please forgive the obfuscated types.

***

_PureScript repl:_

```purescript
> prettyPrintMyType foo
"FOO"

> :t foo
MyType Bar Unit

> :t prettyPrintExpF
forall c a. MyTypeclass c => Show c => Show a => MyType c a -> String
```

_Node repl:_

```javascript
> prettyPrintMyType(foo);
[Function]

> foo
MyType { value0: {}, value1: Baz { value0: 'FOO' } }

> prettyPrintMyType.toString()
'function (dictMyTypeclass) {\n      return function (dictShow) {\n          return function (dictShow1) {\n              return prettyPrintMyType$prime(dictMyTypeclass)(dictShow)(dictShow1)(Data_Show.show(dictShow));\n          };\n      };\n  }'
```

**Comment by hdgarrood** [comment]
This seems reasonable to me. Constraints turn into extra arguments in the generated JavaScript (I think this is described in more detail in the documentation repo). What were you expecting?

**Comment by paulyoung** [comment]
Thanks for the reply. I wasn't aware of that. I've done this before without the constraints and was confused about why it wasn't working this time.

I was expecting something like this:

_Node repl:_

```javascript
> prettyPrintMyType(foo);
'FOO'
```

I'll read up on this in the documentation. Thanks again!

**Comment by paulyoung** [comment]
For anyone else who finds this – I was able to achieve the above by creating a monomorphic variant of this function.
