### ISSUE TITLE
[purs ide] remove duplicates from completion

### ISSUE THREAD

**Issue by coot** [purescript/purescript#2908]
The completion results often contain the same function re-exported from different modules.  For example if I complete `ge` I might get:
```
get :: forall m s. MonadState s m => m s (Control.Monad.RWS)
get :: forall m s. MonadState s m => m s (Control.Monad.State)
get :: forall m s. MonadState s m => m s (Control.Monad.State.Class)
get :: forall m s. MonadState s m => m s (Control.Monad.State.Trans)
```

And this is just one single `get` defined in `Control.Monad.State.Class`.  It would be nice to have a filter that would pick
* the module where it is defined or
* the one with the shortest path - some libraries export all their functions from top level module (`Data.Lenses` is a good example), though in this case this strategy would not find unique module, but that's ok.

**Comment by kRITZCREEK** [comment]
This is being worked on in #2907. If you have any suggestions regrarding the API or how you'd want to configure the grouping please let me know in the PR.
