### ISSUE TITLE
Allow modules to re-export imported values

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#291]
So, for example, `Control.Monad.Writer` can also export the functions from `Control.Monad.Writer.Class`.

``` haskell
module Control.Monad.Writer
  ( Writer()
  , runWriter
  , writer
  , listen
  , pass
  , tell
  , listens
  , censor
  ) where

import Prelude
import Control.Monad.Identity
import Control.Monad.Writer.Trans
import Control.Monad.Writer.Class
import Data.Monoid
import Data.Tuple

type Writer w a = WriterT w Identity a

runWriter :: forall w a. Writer w a -> Tuple a w
runWriter = runIdentity <<< runWriterT
```

**Comment by paf31** [comment]
Shall we close this one and create a new issue for refining the re-exports list?

**Comment by garyb** [comment]
Sure, if you like - but this one is about refined exports really. The example above is manually exporting functions from `.Class` along with the current module's members... although I'm not sure doing it this way is quite what we'd want to do actually.
