### ISSUE TITLE
Add machinery for reflecting a type's constructors into a row?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2913]
This is a pretty specific thing, so not sure whether maybe it's _too_ specific (or just plain goofy) to warrant compiler magic. :smile:

The idea here is you could perhaps do some interesting tricks with `Variant`-like machinery if there was some mechanism for this. For example, you could take `Either`, get a row back something like `("Left" :: ??, "Right" :: ??)`, and then use that information to do something else. In my particular motivating case, I'd like to ensure total matches for defining bi-directional codecs without having to use something like the `Totally` class.

As for the `??`, maybe that could be something like `@a` / `@b`, or for ctors with multiple arguments, it could be a row like `@(value1 :: @Int, value2 ::  @Boolean, value3 :: @c)` or something.

Sound reasonable / interesting at all? I guess it's something kind of "generics at the type level" that I'm looking for, and now our rows are getting fancier it seems like a way that could be done.

**Comment by LiamGoodacre** [comment]
I've done something similar to this using generics-rep and @natefaubion's variant: https://github.com/LiamGoodacre/purescript-variant/blob/feature/variant-generic/src/Data/Variant/Generic.purs
It generates an iso between a data type and variant with constructor names as row labels.  It can easily be extended with the argument thing - in a similar way to what I did with my [generic-rep-optics](https://github.com/LiamGoodacre/purescript-generics-rep-optics) library.  I don't think we need any extra compiler magic to achieve any of this.

**Comment by garyb** [comment]
Oh nice! I'll check it out when actually awake. I forgot to include a point in the issue asking whether maybe it was already possible potentially, it had occurred to me it might already be doable - I suspected you'd probably be the one to know about it too :wink:. Thanks!

**Comment by paf31** [comment]
I came here to say "@LiamGoodacre already did it" 😄

**Comment by garyb** [comment]
I guess the only advantage of having a compiler feature for something like this is it could work for types that don't have a generic-rep derived instance also.

**Comment by cyrbon** [comment]
On the reverse side of this, it would be great to have some way to reflect rows into another type. One  application would be to convert one `Union` into another `Union` efficiently since right now we can't reflect the type of `r` or `r2`: 

```
foreign import convertRecord
  :: forall r r2 def.
   . Union r def (field1 :: String, field2 :: String, field3 :: String)
  => Union r2 def (field1 :: ReactElement, field2 :: ReactElement, field3 :: ReactElement)
  => MagicReflection r
  => Record r -> Record r2
```
If we can reflect which rows `r` has, then `convertRecord` instead of checking whether each field exists can just iterate over fields that the type system knows exists. In `{ field1: "foo" }` it can iterate over `["field1"]` instead of checking all other fields.

More generally, I think this would also be useful to be able to have some dependent type magic over records, which collapses different types of records to different types. For example, when `Union r def (firstname :: String, lastname :: String, fullname :: String)` is used it can collapse it to `Fail` or `Warn`, if `r` has type `{ firstName :: String, fullName :: String}`, because API is supposed to have either firstName + lastName or fullName.

**Comment by LiamGoodacre** [comment]
@garyb having instances of this solved by the compiler instead of opt-in derived instances sounds like a bad idea.  Because iIf you define a foreign data type or have some internal representation that you don't want to export - it might be unsafe to expose those internals.  Also, using generics-rep means that even if you do have some internal representation, you can still define an instance with something equivalent without exposing your internal structure.

I hope this makes sense - I'm half asleep.

**Comment by paf31** [comment]
Another option here is to split `Generic` into two classes, one for `data` and one for records, then have the compiler solve both. It'd be a breaking change, of course.

**Comment by garyb** [comment]
Another variation on this theme: perhaps we could enhance `Partial` with a row, or introduce a new subclass for partial matches specifically, so that when failing to cover all cases the missed cases are reflected into a row. e.g.

``` purescript
myPartial = case _ of
  Left a -> a
```

This could fail due to a missing `PartialCase (Right :: ?whatever)` constraint, where `Partial <= PartialCase r`, and `?whatever` could just be some new `Prim` type like `MissingCase` or something.

This probably wouldn't be as good as what the typechecker errors can currently tell us, as I'm not sure how we'd deal with partial matches due to nested patterns:

``` purescript
myPartial = case _ of
  Left a -> a
  Right (Just b) -> b
```

I guess this would fail with the same error as above, since the `Right` case isn't exhaustive, but I don't know whether it's pratical/usable to somehow encode that `Right Nothing` is the missing case.

Thoughts? It could be an interesting way to allow construction of exhaustive functions from partials, without the need for an `unsafeCoerce` catch all / `Totally` style representation.

**Comment by paf31** [comment]
I have thought about having `Partial` dictionaries carry a string around, to explain why the user thought it was okay to run `unsafePartial`. Then, exhaustivity matches could print that message in addition to the error message.

As for carrying around a row of types, is there a particular problem you're trying to solve? I would think that would only be useful if you intended to match the row somehow.

**Comment by garyb** [comment]
> As for carrying around a row of types, is there a particular problem you're trying to solve? I would think that would only be useful if you intended to match the row somehow.

What I'm getting at, is (admittedly with even more stuff) we could use more exhaustivity information in the types, enabling things like "dynamic" exhaustive functions from partials, e.g.

``` purescript
f :: PartialCase _ => Either a a -> a
f (Left a) = a

g :: PartialCase _ => Either a a -> a
g (Right a) = a

h :: Either a a -> a
h = ?glue f g
```

I guess `PartialCase` would need to carry around more coverage info than just what is missing - `?glue` would need to know what is covered too, for this to work.

I suppose it doesn't scale too well when `Partial` is propagated from a `where` to its containing function or something, but in those cases the `Partial` constraint still works if `PartialCase` is a subclass.

I'm just thinking aloud really. There are other ways of doing this, just they involve more boilerplate. I just thought it might be interesting to explore including more of the information we already have when dealing with exhaustivity, since it gives more options now we can do some typelevel stuff.

**Comment by natefaubion** [comment]
It isn't clear to me if there is anything to resolve here or not, and there has not been activity in some time. Should this be closed?

**Comment by hdgarrood** [comment]
Closing this one sounds good to me.
