### ISSUE TITLE
ℏ (planck constant) encoding problem in browser psci

### ISSUE THREAD

**Issue by dgendill** [purescript/purescript#2914]
When I run  `purs repl 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs' -p 8000` for some reason [planck's constant](http://www.fileformat.info/info/unicode/char/210f/index.htm) doesn't get encoded correctly in the bundle.js file.

```purescript
import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)

ℏ :: String
ℏ = "planck"

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  log ℏ
```

![image](https://cloud.githubusercontent.com/assets/1159795/26533110/a243d54c-43d0-11e7-8d78-0446f0852e23.png)

However, if I build the bundle with `pulp build --to test.js`, the generated file works fine.  Other lowercase unicode characters work fine.

**Comment by hdgarrood** [comment]
Does your HTML page declare a character set?

**Comment by hdgarrood** [comment]
Oh actually I guess in this case it would depend on the response headers after requesting that JS file; maybe they have something to do with it? Also can you tell us what bytes there are in the offending file where that variable name should be?

**Comment by garyb** [comment]
The charset can make a difference to the linked JS files too, I encountered something similar lately - although not sure if it is the case here, the server seems just as likely.

This is probably an issue for `pulp` rather than `purescript` though? :)

**Comment by hdgarrood** [comment]
I wasn't aware that `pulp` was involved?

**Comment by garyb** [comment]
Oh, sorry, I misread. Ignore that!

**Comment by dgendill** [comment]
It does look like this might be a server issue.  When I run purs repl with a port number, the files in app/static get served on localhost. I tried modifying index.html and index.js by pasting in the offending character, and it looks like those files also don't render correctly.

This is the hex dump of the character that can't render (that should render as planck character).

```
00000000: 2020 0f0a 
```
Normally planck character has this hex dump.
```
00000000: e284 8f0a
```

If I try serving the files with something like python's SimpleHTTP Server, the response headers look like this and the content renders correctly... 

```
Content-Length:211
Content-type:text/html
Date:Mon, 29 May 2017 20:33:13 GMT
Last-Modified:Mon, 29 May 2017 20:28:58 GMT
Server:SimpleHTTP/0.6 Python/2.7.11
```

Whereas Warp server returns these headers.

```
Content-Type:text/html
Date:Mon, 29 May 2017 20:36:42 GMT
Server:Warp/3.2.11.1
Transfer-Encoding:chunked
```

**Comment by dgendill** [comment]
This is what index.html looked like after I pasted the character and added the character set.

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>PureScript Interactive</title>
  <script src='js/bundle.js'></script>
  <script src='js/index.js'></script>
</head>
<body>
  ℏ
</body>
</html>
```

**Comment by dgendill** [comment]
Now I'm thinking it's an encoding problem.  If I set indexPage as a String and then convert to a UTF8 ByteString, I can get the index page to render the special character.

```haskell
-- REPL.hs
import qualified Data.ByteString.Lazy.UTF8 as U

indexPage :: String
indexPage = $(embedStringFile "app/static/index.html")

staticServer :: Wai.Application
staticServer req respond =
  case Wai.pathInfo req of
    [] ->
      respond $ Wai.responseLBS status200
                                [(hContentType, "text/html; charset=UTF-8")]
                                (U.fromString indexPage)
```
