### ISSUE TITLE
Enable polymorphic defaults in records (possibly adding constraint defaults)

### ISSUE THREAD

**Issue by cyrbon** [purescript/purescript#2919]
In JS it's very common for an object to have defaults. One such example is React props. Most React components have default props and when creating a binding you need to account for that. Luckily, `Union` allows us to do that as of `0.11`. Using `Union suppliedProps defProps allPossibleProps`, you can create a component with a variable number of props `checkbox { checked: true }` or `checkbox { checked: true, label: text "euro"}`. However, it's very common for `Props` to be also polymophic and accept several types. For example, `label` can be a string or it can be a react component. This is where `Union` starts to break, because it disallows any ambiguity when defaults are used.

A compressed example of this is:

``` purescript
foreign import testPolyUnion
  :: forall r def s
   . Union r def ( foo :: String, bar :: s)
  => Show s
  => Record r -- This record has defaults
  -> Unit

main =  do
  let exampleRecord1 = { bar : "bar" }
       exampleRecord2 = { foo : "foo" } -- This will fair because poly `bar` is not used
      record1Result = testPolyUnion exampleRecord1
      -- It can't figure out the type of `bar` even though that is never used and it does not need to know it
      record2Result = testPolyUnion exampleRecord2
  pure unit
```

`bar` in example 2 is specified as a default and is never used, so it does not need to know its type, but it
still can't compile due to ambiguity:

```
            record2Result = testPolyUnion exampleRecord2
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  No type class instance was found for
  
    Data.Show.Show t2
  
  The instance head contains unknown type variables. Consider adding a type annotation.
  
  while applying a function testPolyUnion
    of type Union t0 t1
              ( foo :: String
              , bar :: t2
              )
             => Show t2 => { | t0 } -> Boolean
    to argument exampleRecord2
  while inferring the type of testPolyUnion exampleRecord2
  in value declaration main
  
  where t2 is an unknown type
        t1 is an unknown type
        t0 is an unknown type

```

I think one solution would be to create a `Default constraint type`, which in case of ambiguity defaults constraint to the specified type:

```
foreign import testPolyUnion
  :: forall r def s
   . Union r def ( foo :: String, bar :: s)
  => Show s
  => Default s String
  => Record r -- This record has defaults
  -> Unit
```

It feels like that it could be used somewhere else, besides in a `Union`, but if this is not useful outside `Union`, then perhaps a simper solution would be to allow ambiguity in `Union r def ambiguity`. This will make it unnecessary to pollute type signatures with extra default information.

Considering how widely polymophic defaults are used in JS objects, I think it would simplify and make many Purescript bindings a lot more powerful. For example, I'm currently writing bindings for `semantic-ui-react` and almost every component has this. With polymophic defaults a lot of end APIs would look extra clean and increase probability of PS looking more attractive for folks coming from JS and considering to use it.
 
What do you think?

**Comment by paf31** [comment]
I suspect `testPolyUnion` has the wrong type. How would you implement it? I don't think it can be implemented by merging records.

What's the actual problem we're trying to solve here? Sounds like you want to have records with optional fields, and where those optional fields can use union types. I think we should try to look for a simpler solution first.

**Comment by cyrbon** [comment]
I probably made it even more confusing by trying to use a smaller unrealistic example. Here is a real world example:

```
foreign import data CheckboxProps :: Type
foreign import checkboxClass :: ReactClass CheckboxProps

-- | Props expected by the react class
type AllCheckboxProps eff props st res =
  ( as :: String
  , checked :: Boolean
  , className :: String
  , defaultChecked :: Boolean
  , defaultIndeterminate :: Boolean
  , disabled :: Boolean
  , fitted :: Boolean
  , indeterminate :: Boolean
  , label :: ReactElement
  , name :: String
  , onChange :: (Event -> EventHandlerContext eff props st res)
  , radio :: Boolean
  , readOnly :: Boolean
  , slider :: Boolean
  , toggle :: Boolean
  , _type :: STypes.CheckboxType
  , value :: String
  )

-- | A checkbox allows a user to select a value from a small set of options,
-- | often binary.
checkbox
  :: forall r r2 eff props st res
   . Union r r2 (AllCheckboxProps eff props st res)
  => Record r
  -> Array ReactElement
  -> ReactElement
checkbox props children =
  createElement checkboxClass (unsafeCoerce props) children
```

In this example, all possible props are represented by `AllCheckboxProps` and `checkbox` accepts `Record r` containing  any or none of those props.

This allows users to provide any combination of optional fields `checkbox { name: "Some name"} []` or `checbox { disabled: true, label: text "some text"} []`. 

The problem is that `label` prop is not really `ReactElement`. It's either `ReactElement` or `String`. 

One way to mimic that would be to create  `class IsReactElement a`, make instances `IsReactElement String` and `IsReactElement ReactElement`, extend `type AllCheckboxProps eff props st res reactElement`, make label polymorphic `label :: reactElement`, and add a constraint to `checkbox` function `IsReactElement reactElement =>`:

```
checkbox
  :: forall r r2 eff props st res reactElement
   . Union r r2 (AllCheckboxProps eff props st res reactElement)
  => IsReactElement
  => Record r
  -> Array ReactElement
  -> ReactElement
```

However, this will fail when you try to use that API, because if `label` is not supplied (it's optional), it can't deduce the type of `label`. This will work `checkbox { label: "some label", name: "some name"} []`, but this will fail `checkbox {name: "some name"} []`.

This will fail in every other scenario where `Union` is used to specify that the binding has optional fields. Those defaults are not provided in Purescript, they are provided somewhere in a JS library. And if you try to create bindings for those libraries, currently can't have polymorphic fields inside a `Union`.

I hope that makes sense.

**Comment by coot** [comment]
That's true, I hit the same problem when writing bindngs for react-transition-group.

What about using polymorphic [Variants](https://pursuit.purescript.org/packages/purescript-variant/1.1.0/docs/Data.Variant).  But likely you will hit similar problem when unwrapping the Variant (that function will also need to have Union type, and there is no way of writing it once for all possible Variants).

**Comment by paf31** [comment]
Unless there is a reason why using the FFI to express union types won't work, I'd like to close this, since there is a low-tech solution without the need for compiler changes.

**Comment by cyrbon** [comment]
@paf31 Okay, I agree. It would be great to have as a cosmetic improvement (its very common for react components to have optional polymorphic props), but it's not a priority.

**Comment by cyrbon** [comment]
As I continue writing binding for react libraries, it gets uglier and uglier without this, to the point that I think there will be no choice but to sacrifice safety and use arbitrary strings, because anything else will be completely unusable.

Imagine `iconPosition` prop being `"left" | "right" `. Another, `labelPosition` prop being `"left" | "right" | "left corner" | "right corner"`. Another prop can be `"left" | "right" | "top" | "bottom"`.

We need some way in Purescript to express this in optional props. 

With a lot of boilerplate, which is fine, it would be possible to make it safe and looking good, if it had not had this problem with constraints in a `Union`. Here would be one valid way of doing it:
 
```purescript
data LeftPos = LeftPos
data RightPos = RightPos

data LeftCorner = LeftCorner
data RightCorner = RightCorner

class LeftOrRightPos a where
  fromLeftOrRightPos :: a -> String

instance leftIsLeftOrRightPos :: LeftOrRightPos LeftPos where
  fromLeftOrRightPos _ = "left"

instance rightIsLeftOrRightPos :: LeftOrRightPos RightPos where
  fromLeftOrRightPos _ = "right"

class LeftOrRightOrLeftCornerOrRightCorner a where
  fromLeftOrRightOrLeftCornerOrRightCorner :: a -> String

instance leftIsLeftOrRightOrLeftCornerOrRightCorner
  :: LeftOrRightOrLeftCornerOrRightCorner LeftPos where
  fromLeftOrRightOrLeftCornerOrRightCorner  _ = "left"

instance rightIsLeftOrRightOrLeftCornerOrRightCorner
  :: LeftOrRightOrLeftCornerOrRightCorner RightPos where
  fromLeftOrRightOrLeftCornerOrRightCorner  _ = "right"

instance leftCornerIsLeftOrRightOrLeftCornerOrRightCorner
  :: LeftOrRightOrLeftCornerOrRightCorner LeftCorner where
  fromLeftOrRightOrLeftCornerOrRightCorner  _ = "left corner"

instance rightCornerIsLeftOrRightOrLeftCornerOrRightCorner
  :: LeftOrRightOrLeftCornerOrRightCorner RightCorner where
  fromLeftOrRightOrLeftCornerOrRightCorner  _ = "left corner"

type AllInputProps iconPosition labelPosition =
  ( iconPosition :: iconPosition
  , labelPosition :: labelPosition
  )

foreign import data InputProps :: Type
foreign import inputClass :: ReactClass InputProps

-- | An Input is a field used to elicit a response from a user.
input_
  :: forall props defProps iconPosition labelPosition
   . Union props defProps (AllInputProps iconPosition labelPosition)
  => LeftOrRightPos iconPosition
  => LeftOrRightOrLeftCornerOrRightCorner labelPosition
  => Record props
  -> Array ReactElement
  -> ReactElement
input_ props children =
  createElement inputClass (unsafeCoerce props) children
```
It has a bit of boilerplace, but the end result is rather good:

```purescript
inputExample :: ReactElement
inputExample = input_ { iconPosition: LeftPos } []

inputExample2 :: ReactElement
inputExample2 = input_ { labelPosition: LeftPos } []

inputExample3 :: ReactElement
inputExample3 = input_ { labelPosition: LeftCorner } []
```

However that does not compile, because it tries to instances for props which are clearly will never be used:

```
 inputExample3 = input_ { labelPosition: LeftCorner } []
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  No type class instance was found for
  
    Modular.LeftOrRightPos t2
  
  The instance head contains unknown type variables. Consider adding a type annotation.
  
  while applying a function input_
    of type Union t0 t1
              ( iconPosition :: t2
              , labelPosition :: t3
              )
```

Currently, the only way to do this would be to completely forget about type safety and just using strings `input_ { labelPosition: "left" } []`.

**Comment by LiamGoodacre** [comment]
@cyrbon 

Usually people provide a record with all the defaults and the users opt in to override specific ones:

```purescript
-- in library
inputDefaults = { iconPosition: iconPositionDefault, labelPosition: labelPositionDefault }

-- use
inputExample = input_ (inputDefaults { labelPosition = LeftCorner }) []
```

You could even do it with a function argument instead, and have `input_` apply it to the defaults:

```purescript
inputExample = input_ (_ { labelPosition = LeftCorner }) []
```

Does this do what you want?

**Comment by garyb** [comment]
There's also https://github.com/purescript-contrib/purescript-options

**Comment by cyrbon** [comment]
@LiamGoodacre Unless I'm missing something that does not really work in this case. `iconPosition` still can't be polymorphic:

```purescript
-- in library
inputDefaults = { iconPosition: LeftPos, labelPosition: LeftPos }

-- use
inputExample = input_ (inputDefaults { labelPosition = RightCorner }) []
```

Because it will not be able to unify types:

```
 Could not match type
  
    LeftPos
  
  with type
  
    RightCorner
```

Since they are different types:

```
data LeftPos = LeftPos
data RightPos = RightPos

data LeftCorner = LeftCorner
data RightCorner = RightCorner
```

It may be trickier than it looks. You can't just define: 

```purescript
data LeftOrRight = LeftPos | RightPos
data LeftOrRightOrLeftCornerOrRightCorner = LeftPos | RightPos | LeftCorner | RightCorner
```

Because each constructor needs to have a unique name:

```
Declaration for data constructor LeftPos conflicts with an existing data constructor of the same name.
```

This similar to that old problem in Haskell where fields inside records need to have a unique name, which Purescript solved elegantly. In Semantic UI alone there are over 50 react components, and name collision will occur even within prop values of one single component. And if multiple different react libraries written by different people will be used within the same project, then unique names will be extremely long and impossible to remember, and this is all only to allow expressing something as simple as "right" or "left" (`RightPos` or `LeftPos`).

**Comment by paf31** [comment]
Have you tried `purescript-variants`?

**Comment by LiamGoodacre** [comment]
I was only suggesting a solution to the issue of record defaults.

From a user point of view, you can use the same name to mean different things via a type class method `leftPos` - the user doesn't have to care what you call the constructor.
Alternatively you can put them in different modules and required use of them to be qualified.
Or even export a record "namespace" with each field mapping to the constructors.

**Comment by paf31** [comment]
Also, I don't understand how `Default` is supposed to work. Can you please explain in more detail what the compiler would need to do?

**Comment by kRITZCREEK** [comment]
If you combine `purescript-variants` with Liam's default record suggestion you end up with this:

```purescript
module Main where

import Prelude

import Data.Variant as V

data LeftPos = LeftPos
data RightPos = RightPos

data LeftCorner = LeftCorner
data RightCorner = RightCorner

rightPosS = V.SProxy ∷ V.SProxy "rightPos"
leftPosS = V.SProxy ∷ V.SProxy "leftPos"
rightCornerS = V.SProxy ∷ V.SProxy "rightCorner"
leftCornerS = V.SProxy ∷ V.SProxy "leftCorner"

rightCorner = V.inj rightCornerS RightCorner
leftCorner = V.inj leftCornerS LeftCorner
rightPos = V.inj rightPosS RightPos
leftPos = V.inj leftPosS LeftPos

rightPosToString = V.on rightPosS (const "right")
leftPosToString = V.on leftPosS (const "left")
rightCornerToString = V.on rightCornerS (const "right corner")
leftCornerToString = V.on leftCornerS (const "left corner")

type LeftOrRightPos = V.Variant (leftPos ∷ LeftPos, rightPos ∷ RightPos)

type LeftOrRightOrLeftCornerOrRightCorner = V.Variant
  ( leftPos ∷ LeftPos
  , rightPos ∷ RightPos
  , leftCorner ∷ LeftCorner
  , rightCorner ∷ RightCorner
  )

showLeftOrRightPos ∷ LeftOrRightPos → String
showLeftOrRightPos =
  V.case_
    # rightPosToString
    # leftPosToString

showLeftOrRightOrLeftCornerOrRightCorner ∷ LeftOrRightOrLeftCornerOrRightCorner → String
showLeftOrRightOrLeftCornerOrRightCorner =
  V.case_
    # rightPosToString
    # leftPosToString
    # rightCornerToString
    # leftCornerToString

type InputProps = { iconPosition ∷ LeftOrRightPos, labelPosition ∷ LeftOrRightOrLeftCornerOrRightCorner }

defaultInputProps ∷ InputProps
defaultInputProps = { iconPosition: leftPos, labelPosition: leftPos }

renderInputProps { iconPosition, labelPosition} =
  { iconPosition: showLeftOrRightPos iconPosition
  , labelPosition: showLeftOrRightOrLeftCornerOrRightCorner labelPosition
  }

input_
  ∷ InputProps
  → Array ReactElement
  → ReactElement
input_ props children =
  createElement inputClass (renderInputProps props) children

inputExample :: ReactElement
inputExample = input_ (defaultInputProps { iconPosition: leftPos }) []

inputExample2 :: ReactElement
inputExample2 = input_ (defaultInputProps { labelPosition: leftPos }) []

inputExample3 :: ReactElement
inputExample3 = input_ (defaultInputProps { labelPosition: leftCorner }) []
```
This also has the nice benefit that users of your library can just use typed holes to figure out what options they have for each property. For example:

```purescript
myProps ∷ InputProps
myProps = defaultInputProps { labelPosition = ?x}
```

returns this error:

```purescript
Error: d:/Documents/GitHub/variants-example/src/Main.purs:62:47:
  Hole 'x' has the inferred type

    Variant
      ( leftPos :: LeftPos
      , rightPos :: RightPos
      , leftCorner :: LeftCorner
      , rightCorner :: RightCorner
      )

  You could substitute the hole with one of these values:

    Main.leftCorner   :: forall t86.
                           Variant
                             ( leftCorner :: LeftCorner
                             | t86
                             )
    Main.leftPos      :: forall t48.
                           Variant
                             ( leftPos :: LeftPos
                             | t48
                             )
    Main.rightCorner  :: forall t25.
                           Variant
                             ( rightCorner :: RightCorner
                             | t25
                             )
    Main.rightPos     :: forall t11.
                           Variant
                             ( rightPos :: RightPos
                             | t11
                             )


in value declaration myProps
```

**Comment by cyrbon** [comment]
@paf31 I'll look at `purescript-variant`.

If the compiler can't find an instance, right before it decides to conclude that no type class instance is found:

```
  No type class instance was found for
  
    LeftOrRight t2
  
  The instance head contains unknown type variables. Consider adding a type annotation.
```

it checks if `t2` has `Default t2 t3` constraint like `Default t2 LeftPos`, and if `t2` is not a concrete type it infers that `t2` is `t3` (in this example, `LeftPos`). 

In theory, knowing the concrete type of a field in a record is not necessary if that field is never used. However, it will be be hard to solve, and it still needs to know what dictionary to pass (even if that dictionary will not be used), otherwise it will break semantics and require a lot of changes. 

`Default t Type` hopefully offers a simple way to infer the type of `t` when `t` not used (as is the case when `t` is one of the optional fields).

```
-- | An Input is a field used to elicit a response from a user.
input_
  :: forall props defProps iconPosition labelPosition
   . Union props defProps (AllInputProps iconPosition labelPosition)
  => LeftOrRightPos iconPosition
  => LeftOrRightOrLeftCornerOrRightCorner labelPosition
  => Default iconPosition LeftPos
  => Default labelPosition RightCorner
  => Record props
  -> Array ReactElement
  -> ReactElement
input_ props children =
  createElement inputClass (unsafeCoerce props) children
```

**Comment by cyrbon** [comment]
@kRITZCREEK Thanks for the example! It looks really good. I like how type holes can be used to figure out what options each property has.

**Comment by paf31** [comment]
I'm trying to understand the request in terms of features which are known to work in Haskell or other languages. The closest thing I know is type class defaulting. Now, it might be interesting to allow classes to define default instances, such as:

```purescript
class Show a where
  show :: a -> String

  default instance showUnit :: Show Unit where
    show _ = "unit"
```

This can sometimes be handy in GHCi in Haskell. Consider something like this:

```
> show (read "()")
"()"
> show (read "42")
"*** Exception: Prelude.read: no parse
```

which works since `Show` defaults the unknown type to `()`.

So I'd be happy to close this in favor of an issue discussing type class defaulting, if you think that solves your problem. I would probably not be in favor of default instances, for what it's worth, since I think they can affect usability, and there is almost always a workaround, like adding a type signature.

If this doesn't solve the problem, then let's please rephrase it in terms of something which already exists in the PureScript type system, or something which is known to work elsewhere, because I don't think a special `Default` class will work very well.

**Comment by paf31** [comment]
Note also, that if you're willing to use overlapping instances, you can solve this now, as follows:

```purescript
instance defaultLeftOrRight :: TypeEquals a LeftPos => LeftOrRight a
```

You just need to make sure that this instance will be selected last. However, I urge you to try the other solutions listed above first.

I'm going to close this issue, but please do open a separate issue if you think that default instances would be an adequate solution, or if you have some other proposal.

**Comment by cyrbon** [comment]
@paf31 I'm trying to explore the overlapping instances option, but I can't figure out how it works. Doesn't `TypeEquals` says that `a` should always be only `LeftPos`? I think that I'm missing how to "make sure that this instance will be selected last". I searched everything I could find in Issues, but weren't able to find an example of this.

In this code:

```purescript
data LeftPos = LeftPos
data RightPos = RightPos

class LeftOrRight a where
  fromLeftOrRight :: a -> String

instance leftPosLeftOrRight :: LeftOrRight LeftPos where
  fromLeftOrRight _ = "left"

instance rightPosLeftOrRight :: LeftOrRight RightPos where
  fromLeftOrRight _ = "right"

instance defaultLeftOrRight :: TypeEquals a LeftPos => LeftOrRight a where
  fromLeftOrRight _ = "left"

input
  :: forall props defProps iconPosition labelPosition
   . Union props defProps (AllInputProps iconPosition labelPosition)
  => LeftOrRight iconPosition
  => LeftOrRightOrLeftCornerOrRightCorner labelPosition
  => Record props
  -> Array ReactElement
  -> ReactElement
input props children =
  createElement inputClass (unsafeCoerce $ props) children
```

The compiler will complain when `RightPos` is used like `input { iconPosition: RightPos } []`, because `TypeEquals` forces that `iconPosition` needs to be  `LeftPos`.

In the end of this small adventure, I plan to publish a repository with different methods of modeling react props in Purescript and their tradeoffs, including benchmarks for each one. It would be great to add this to the collection, as I suspect it will be the fastest method.

**Comment by paf31** [comment]
The instance selection algorithm in the presence of overlaps is not documented right now, but it basically corresponds to the order in which keys are stored in the map structure inside the compiler, which means it is by module name, then instance name, then probably class names. So I think you can force instances to be chosen last by choosing some instance name carefully. It's undocumented, undefined behavior, so I wouldn't recommend it (that's why overlaps give a warning after all). I would instead recommend trying to find a lower-tech solution like not using type classes in the first place, but instead using `purescript-variants` or some other FFI-powered representation.

**Comment by cyrbon** [comment]
@paf31 Thanks! Yeah, that's one hell of a hack. I'm still on the fence with this, because I like the type inference in a variant and that naming hack looks like a timebomb. I'll still write a couple more tests before deciding. But, at first glance, if I compare all cons and pros, `Union` seems a more attractive choice for that library.

1. No default duplication. Union does not force to define defaults twice, which are already defined in the JS library, for which bindings are written. So, using a variant + defaults will also introduce some dose of hackiness. I'll have to find all default values in a library that I'm writing binding for, and define them again in PS. Needing to perform this code archeology is already a significant bummer. This will also mean that defaults are defined in two places. Once in the Purescript and once in JS code of the library it binds to. Those default values can potentially go out of sync.

2. Performance and readability of generated code. Using `Union` means that props are immediately created just the same way as one would create them when writing JS by hand, as a simple object `{}`. Not only this achieves the ideal performance, but also makes the generated code much easier to read, especially when noise is removed with `rollup-plugin-purs`.

3. Syntactic noise in the resulting API. `input { iconPosition: LeftCorner } []` just looks better. And when writing components that syntax might appear on almost every line in every UI related module, so this is something that I think is important. And this looks even more efficient syntactically than JSX that was designed for this domain, which I think is a good small victory to have.

So, yeah, you have shown me the path to the evil, but the end result of this instance naming satanism looks pretty attractive.

**Comment by kRITZCREEK** [comment]
> Union does not force to define defaults twice, which are already defined in the JS library, for which bindings are written. So, using a variant + defaults will also introduce some dose of hackiness. I'll have to find all default values in a library that I'm writing binding for, and define them again in PS.

Just make the fields `Maybe's` and either turn them into `Nullable` or use a StrMap and don't add the values that are `Nothing` at the FFI boundary.

**Comment by cyrbon** [comment]
As promised, I've created a repository with examples of several methods to model React props in Purescript. Each example includes benchmarks and unit tests. I was surprised how well variant did on the benchmark, being faster than using `Data` and converting types. https://github.com/cyrbon/props-models-and-benchmarks

I'll later make public bindings for `semantic-ui-react`. If anybody needs them, I'll try making it public sooner.
