### ISSUE TITLE
Unexpected int overflow behaviour

### ISSUE THREAD

**Issue by mat8913** [purescript/purescript#2921]
The [Differences from Haskell] wiki page has:
> There is a native Number type which represents JavaScript's standard IEEE 754 float and an Int which is restricted to the range of 32bit integers.

Which lead me to believe that Purescript's `Int` type should behave similarly to Haskell's `Int32` type. However, this does not seem to be the case on operations that overflow. Is the intended behavior of int overflow for Purescript documented anywhere?

For reference, [Haskell's int overflow bahaviour]:
> This module provides signed integer types of unspecified width (Int) and fixed widths (Int8, Int16, Int32 and Int64). All arithmetic is performed modulo 2^n, where n is the number of bits in the type.

[Differences from Haskell]: https://github.com/purescript/purescript/wiki/Differences-from-Haskell#numbers
[Haskell's int overflow bahaviour]: https://www.haskell.org/onlinereport/haskell2010/haskellch18.html

**Comment by hdgarrood** [comment]
Can you please show us a minimal program which behaves in a way different from what you expected, and what you did expect as well as what you actually got? I may well be wrong but my impression was that arithmetic on `Int` is indeed all modulo 2^32.

**Comment by mat8913** [comment]
On try.purescript.org:

    module Main where

    import Prelude
    import TryPureScript

    main = render $ h1 (text $ show x)
      where
        x = 2147483647 * 2147483647 :: Int

Gives `0`

Whereas, in GHCi:

    Prelude Data.Int> 2147483647 * 2147483647 :: Int32
    1

**Comment by hdgarrood** [comment]
Right, I see, thank you! I suppose this must be because above 2^53, JS Number values aren't precise enough for operations involving integers to be guaranteed to work as expected?

**Comment by paf31** [comment]
Is this something we think can be fixed? Or we should just document it and recommend some bignum library for these cases?

**Comment by hdgarrood** [comment]
I think probably the latter.

**Comment by paf31** [comment]
In that case, I'll close this, and let's open something in the `documentation` repo.

Thanks!

**Comment by Pauan** [comment]
Actually, this *can* be fixed! You can use [`Math.imul`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul) to multiply two 32-bit integers.

Multiplication is the only 32-bit operation which requires a special function, all other operations work correctly with `foo | 0` (which PureScript already uses).

**Comment by paf31** [comment]
@Pauan Interesting, thanks! Which version of the spec was that function added in?

**Comment by Pauan** [comment]
@paf31 It was added in ECMAScript 6 (aka 2015).

However, because it's such a simple function to add (it's just standard C integer multiplication), and it was needed for asm.js, browsers very quickly added in support for it.

As such, [it's supported by every browser other than IE11](http://kangax.github.io/compat-table/es6/#test-Math_methods_Math.imul_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;).

If compatibility is a concern, there is a polyfill available on the MDN page which I linked to.

**Comment by hdgarrood** [comment]
Oh that's great to know! I would be in favour of using `Math.imul` with a polyfill.

**Comment by mat8913** [comment]
`pow` from `Data.Int` would also have the same problem, wouldn't it? As far as I can tell, the fastest `pow` implementation for integers is [exponentiation by squaring]. You'd also have to check that the power isn't negative.

[exponentiation by squaring]: https://en.wikipedia.org/wiki/Exponentiation_by_squaring

**Comment by hdgarrood** [comment]
I think `pow` from `Data.Int` would indeed have the same problem, as `pow x y` is just `Math.pow(x,y) | 0`.

For example:

```
-- haskell
(maxBound :: Int32) ^ 2 == 1

-- purescript
Int.pow top 2 == 0
```
