### ISSUE TITLE
Allow instance i :: () => C a

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2923]
Allowing empty constraint lists makes generating code easier. I think this is a simple `s/commaSep1/commaSep/`.

**Comment by kRITZCREEK** [comment]
I'd prefer not to optimize for making generating code easier when that complicates the parser or gives worse errors for users.

**Comment by garyb** [comment]
> I'd prefer not to optimize for making generating code easier when that complicates the parser or gives worse errors for users.

Word. Also it's not clear whether `(C x, C y) =>` will even remain as valid syntax given it seems to trip people up now that doesn't work in functions.

How about you add the special case to your codegen instead? 😛

**Comment by paf31** [comment]
👎 from me as well, sorry. It seems this should be easy enough to handle in a code generator, no?
