### ISSUE TITLE
Add documentation on what minimum version of Node is required

### ISSUE THREAD

**Issue by FranklinChen** [purescript/purescript#2930]
It's not clear what minimum version of Node is required for PureScript, e.g. https://github.com/alexmingoia/pux-starter-app/issues/33

**Comment by hdgarrood** [comment]
The code that the purescript compiler generates will work on pretty much any version of node; what is most likely happening there is that some FFI code is the cause, I think. The minimum Node version that pux-starter-app requires is probably best documented on that repo, not here.

**Comment by natefaubion** [comment]
> The minimum Node version that pux-starter-app requires is probably best documented on that repo, not here.

It may also be `purescript-contrib/node-purescript-bin`, which is how people often install PureScript, and is written with ES2015 syntax.

**Comment by natefaubion** [comment]
So as long as we officially recommend `npm install purescript`, we should probably document that alongside it.

**Comment by paf31** [comment]
We should document this on the `node-purescript-bin` repo and also on the website then. I will include it in the work for https://github.com/purescript/purescript.github.io/pull/119#issuecomment-306676626.

Thanks!
