### ISSUE TITLE
Should type aliases for type constructors be a warning?

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript#2936]
From https://github.com/purescript/purescript/pull/2932

In short, since we don't have some kind of consensus on this from people participating in the pull request, I think we should try to poll users in some way.

Just a reminder that I only mean to target things like `type URL = String` with this, nothing more fancy. The main motivation being that I often have shot my feet off doing this in my own code, and there's not much reason to when one can easily consume APIs that expose newtypes (e.g. `Pattern` is only `P-A-T-[completion]-enter` or `wrap` away), not to mention libs that don't export constructors for values that should be validated (like URLs, FilePaths, and the like) are easier to use for the vast majority of cases.

Any aliasing of type constructors like this that shouldn't throw a warning are basically impossible to handle without knowing the user intent or doing some ugly hardcoded list or something.

Please do say if I've forgotten to say anything here, and if there'd be a good way to get people to respond and talk about their own issues.

**Comment by hdgarrood** [comment]
I don't think we need to do any polling, honestly. The way I see it, we have identified cases where these sorts of aliases are sensible, and therefore it's not reasonable to make it a warning.

I think it's worth mentioning that there are plenty of other ways to shoot yourself in the foot which the compiler also doesn't warn about. If some way of writing code can backfire, that alone isn't a sufficient condition for there to be a compiler warning about it; we also need the compiler to be able to reliably identify code that should be changed, and we can't do that here. IMO code review is for catching this sort of thing, not compiler warnings.

**Comment by natefaubion** [comment]
I don't think this is going to make it as a warning. There's nothing wrong with making type aliases like this, and I know I personally use it to future proof some modules so I can only change on declaration instead of 30.
