### ISSUE TITLE
Remove or document the need to eta-expand foldlDefault and foldrDefault

### ISSUE THREAD

**Issue by Ptival** [purescript/purescript#2938]
It took me a while to realize that `foldlDefault` and `foldrDefault` have to be used this way:

    foldl f = foldlDefault f

and do not work with this:

    foldl = foldlDefault

The error you get is:
```
The value of <foldableYourType> is undefined here, so this reference is not allowed. [CycleInDeclaration]
```

I don't know if this is documented anywhere, but it took me looking code on Github to figure out what to do.

**Comment by paf31** [comment]
Thank you for bringing this up, but I think we should open an issue on `purescript/documentation` to track this, since it would probably be handled there.

**Comment by Ptival** [comment]
Done! https://github.com/purescript/documentation/issues/80
