### ISSUE TITLE
Cycle in declaration check too strict?

### ISSUE THREAD

**Issue by Ptival** [purescript/purescript#2939]
I have some code that looks a bit like this:

```
choiceOrNextP' :: ∀ a. Array (Parser a -> Parser a -> Parser a) -> (Parser a -> Parser a)
choiceOrNextP' ps nextP =
  fix $ \ selfP -> choice $ map (\ p -> p selfP nextP) ps <> Array.singleton nextP

foldP' :: ∀ a. Array (Array (Parser a -> Parser a -> Parser a)) -> Parser a
foldP' a = fix $ \ self -> foldr ($) (parens self) (map choiceOrNextP' a)

parser' :: ∀ a. Array (Array (Parser a -> Parser a -> Parser a))
parser' = [ [ arrowP' ] ]

termP' = foldP' parser'

arrowP' selfP nextP = do
  -- some stuff
  termP'
  -- some stuff
```

This works find in Haskell, but PureScript rejects it because of the cycle between parser', termP', and arrowP'.
In practice, the cycle does not cause bad things to happen though. The Haskell code runs fine.

Is the cycle checker too strict?
Are the conditions upon which it will accept/reject cycles documented?

**Comment by paf31** [comment]
The Haskell code runs fine because of lazy evaluation, but with strict evaluation we have to be more careful. It might be the case that this code will run fine if we turn off the check, but we need _some_ way to tell whether a set of mutually recursive functions is going to blow up at runtime. The check we have now is possibly too conservative, but we don't have a proposed replacement for it.

**Comment by hdgarrood** [comment]
I don't think this is a false positive; the fact that PureScript is strict means that programs which would work in Haskell because of laziness sometimes need minor modifications to work in PureScript.

**Comment by paf31** [comment]
I'd recommend something like this:

```
parser' :: ∀ a. Array (Array (Parser a -> Parser a -> Parser a))
parser' = fix \self ->
  let
    termP' = foldP' self

    arrowP' selfP nextP = do
      -- some stuff
      termP'
      -- some stuff
  in [ [ arrowP' ] ]
```

**Comment by Ptival** [comment]
@paf31 
Well I simplified it a little too much, but, in practice:
- `foldP` is defined by itself (in a different module actually)
- `parser'` and `termP'` and `arrowP'` are indeed mutual

What in your fix does fix the issue?

**Comment by Ptival** [comment]
Looks like it works as long as I put the mutual things in a single definition with a `where` clause. Thanks!

**Comment by Ptival** [comment]
Ah, in fact I can even untie things even more by changing `arrowP` to receive `termP` as a parameter, and plugging it in from `foldP`.

Thanks!
