### ISSUE TITLE
Instance signatures don't bring type variables into scope

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#2941]
```purescript
class Test t where
  test :: forall a. t -> a

instance testUnit :: Test Unit where
  test :: forall a. Unit -> a
  test = go
    where
      go :: Unit -> a
      go = unsafeCoerce
```

Error:

```
  Type variable a is undefined.

while checking the kind of Unit -> a0
while checking that expression let                
                                 go = unsafeCoerce
                               in go              
  has type Unit -> a0
in value declaration testUnit

where a0 is a rigid type variable
        bound at line 10, column 3 - line 10, column 20
```

**Comment by garyb** [comment]
I wondered about this myself, as if it worked it would make instance signatures way more useful than "just" being there for documentation!

**Comment by matthewleon** [comment]
Looks like `introduceSkolemScope` should be getting called, but isn't.

**Comment by matthewleon** [comment]
Looks like the problem is more general and applies to records as well, though not sure if we consider it a bug there. It comes in once the typeclass is desugared:

```purescript
rec :: {attr :: forall a. a -> Int}
rec = {attr: let go :: a -> Int
                 go = \_ -> 0 
             in go
      }
```

This will fail for the same reason. http://try.purescript.org/?session=4e9f8283-f493-b286-5c42-0515f39cb415

**Comment by matthewleon** [comment]
To clarify, I guess this isn't really a _problem_ with records themselves, per se. It's just that the desugaring mechanism turns the TC instances into records, which don't have a mechanism for specifying that the type variables from the property types should be brought into scope.

This could be resolved by desugaring instances with signatures into `let`s. But that results in wrapping the JS output for that property in a redundant anonymous function invocation. There should be a better solution.

**Comment by hdgarrood** [comment]
I think this example

```purescript
rec :: {attr :: forall a. a -> Int}
rec = {attr: let go :: a -> Int
                 go = \_ -> 0 
             in go
      }
````

should fail; I think that type should be treated differently from `rec :: forall a. { attr :: a -> Int }`. Consider the following type declaration:

```purescript
rec :: {attr :: forall a. a -> Int, attr2 :: forall a. a -> Int }
```

If we automatically hoisted the `forall a.` to the start of the type, what could we do in cases like this one? I don't think there's a good answer.

**Comment by paf31** [comment]
I don't think we should do this by adding any special cases for polymorphic types in records. Maybe we need to rethink the way the type class desugaring works.

**Comment by LiamGoodacre** [comment]
For that example with `rec` you'd need to introduce a declaration for the tyvar to be scoped over, right?  Something like:

```purescript
rec :: {attr :: forall a. a -> Int}
rec = {attr}
  where
  attr :: forall b. b -> Int
  attr = let go :: b -> Int
             go = \_ -> 0 
         in go
```
