### ISSUE TITLE
Instances with just one method do not require that the method be indented

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2947]
That is, the following compiles:

    data Unit = Unit

    instance eqUnit :: Eq Unit where
    eq _ _ = true

**Comment by quesebifurcan** [comment]
New contributor here -- I'd be happy to give this one a try.

**Comment by kpadmasola** [comment]
@paf31 , New contributor here -- I'd be happy to give this one a try. What more is needed here?

**Comment by paf31** [comment]
@kpadmasola There was a previous PR for this, which I need to include in the changes for 0.12.0.

https://github.com/purescript/purescript/pull/2965

Thank you though, and if you're interested in finding something else to work on, maybe we can help on Slack.
