### ISSUE TITLE
Purescript fails to install via npm -g

### ISSUE THREAD

**Issue by jg** [purescript/purescript#2948]
### Environment

- npm 3.5.2
- node 7.2.0
- ubuntu 16.04

### Log

```
-> sudo npm install -g purescript
/usr/local/bin/purs -> /usr/local/lib/node_modules/purescript/bin/purs.js

> purescript@0.11.5 postinstall /usr/local/lib/node_modules/purescript
> node lib/install.js

/usr/local/lib/node_modules/purescript/lib/install.js:10
const {BASE_URL, SOURCE_URL} = require('.');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.11.5 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.11.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by paf31** [comment]
Please could you report this on the `node-purescript-bin` repo. I suspect you need to turn on some flags in Node, although I'm not sure.

**Comment by brennancheung** [comment]
How do we get to the `node-purescript-bin` repo.  There's one that hasn't been updated in years.  The other one just returns a 404.  Is it a private repo?

I'm seeing this same exact issue.  I'm not able to install either.  I tried with Node 8, 10, and 12.  NPM version 6.9.0.

**Comment by hdgarrood** [comment]
No, the original maintainer deleted it. The code is now hosted at https://github.com/purescript/npm-installer (so please open issues there). Are you absolutely sure you were using node 10+ and you didn't have an earlier version of node sneak in front of it in your PATH or something? I can't think of how a SyntaxError could happen on node 10+.
