### ISSUE TITLE
FFI & dead code elimination

### ISSUE THREAD

**Issue by KtorZ** [purescript/purescript#2950]
Hi all,

I am using the FFI to create a wrapper around IndexedDB and I ran into a couple of issues while trying to use a PureScript module on the native-side.

`pulp build -t bundle.js` will generate an optimized JavaScript bundle, however, every foreign import is ignored. Therefore, the following code:

```js
const Maybe = require('Data.Maybe');

export.foreignFn = function foreignFn(marg) {
    const arg = Maybe.fromMaybe("default")(marg);
    // whatever
};
```

will fail if no PureScript modules involved is using the `fromMaybe` function. The `Data.Maybe` module is indeed reduced to its strict minimum and the generated bundle is likely not to contain all methods called by the native code.

Any inputs?

**Comment by hdgarrood** [comment]
You should either use `Nullable` so that you don't need `fromMaybe` in your FFI code, or pass in `fromMaybe` as an argument to your function from the purescript side. The latter approach is described in more detail at https://github.com/purescript/documentation/blob/master/guides/FFI-Tips.md

**Comment by garyb** [comment]
What Harry says is good advice, but as well as that it is possible to list multiple entry point modules for the DCE via the purs command line. I assume pulp has an option for that too.

**Comment by KtorZ** [comment]
Thanks for the tips!
