### ISSUE TITLE
purescript.org/learn is all 404

### ISSUE THREAD

**Issue by chrisdone** [purescript/purescript#2956]
E.g.

http://www.purescript.org/learn/generic/

www.purescript.org/learn/eff/

I just hit like 3 dead links from top Google results in the space of half an hour. 

Perhaps fix or setup redirects?

**Comment by paf31** [comment]
All of the articles have moved to the [documentation repo](https://github.com/purescript/documentation), but we should probably add some pages which redirect there, for any existing links.

**Comment by paf31** [comment]
I'll move this to the website repo though.
