### ISSUE TITLE
No warning for overlapping instances

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2957]
The compiler only warns for overlapping instances when solving. This is actually a bug, as illustrated by the following example, which prints `false`, but gives no overlap warning:

```purescript
class IsInt a where
  isInt :: a -> Boolean
  
instance intIsInt :: IsInt Int where
  isInt _ = true
  
instance isn'tInt :: IsInt a where
  isInt _ = false
  
class F a b | a -> b where
  f :: a -> b
  
instance fInt :: F Int Int where
  f = id
  
main = logShow (isInt (f 1))
```

The problem is that the type of the call to `isInt` is not determined, since the `F` constraint gets solved later. Therefore we pick the `isn'tInt` instance, which is wrong.

In order to commit to `isn'tInt`, we must know that `a` can never become `Int` (apartness). Alternatively, we could try to warn at the definition site.

cc @LiamGoodacre You will probably find this interesting.

**Comment by rightfold** [comment]
Has this been fixed with the recent disallowing of overlapping instances?

**Comment by paf31** [comment]
No, unfortunately, it's a separate issue.

**Comment by LiamGoodacre** [comment]
I am adding a check on declaration site.

**Comment by hdgarrood** [comment]
Would it be ok to make a release which includes instance chains before fixing this?

**Comment by paf31** [comment]
This isn't technically a bug in the sense of any unsoundness. It just means the error happens at an inconvenient place. So I would say it's probably fine to release instance chains, with maybe a line in the release notes about this.
