### ISSUE TITLE
Show progress in "Compiling ..." messages

### ISSUE THREAD

**Issue by Cmdv** [purescript/purescript#2961]
It would be nice for a `--silent` flag for builds that compile large projects end up with a massive output:
```
Compiling ...
Compiling ...
........ n'times
```
when sometimes the part user is interested in is bellow and any compilation failures:

```
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
```
This was originally opened in pulp https://github.com/purescript-contrib/pulp/issues/290

**Comment by garyb** [comment]
That summary is printed by `purescript-psa` rather than the compiler.

**Comment by Cmdv** [comment]
ah ok on I move 👍

**Comment by hdgarrood** [comment]
The summary is indeed printed by psa but I think this is the right place for this issue - it is the compiler that generates and prints the "Compiling" messages.

Rather than adding a flag I'd like to consider just changing that message slightly so that the compiler prints "Compiling module X (1/n)" followed by a "\r" character so that the line gets replaced once it starts on the next module. You would also get a better idea of how far through you were that way.

**Comment by Cmdv** [comment]
@hdgarrood could you give me a pointer as to where I can get the total value of modules that are going to be compiled so I can pass it through to [renderProgressMessage](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Make.hs#L90-L91)? I was then going to simply `+1` after each module is rendered for the first half then the total which is passed into the function.

ie:
`1/n`
`2/n` and so on 😄

**Comment by hdgarrood** [comment]
I think there's a decent chance that it hasn't been explicitly computed. I think you could use `length ms` where `ms` was the argument to `make` but that would include modules which don't need rebuilding, so ideally we would take account of that somehow. I think the code might actually need a nontrivial bit of restructuring to be able to do that, come to think of it. Also I've just realised that the fact that modules can be built in parallel complicates this somewhat...

**Comment by Cmdv** [comment]
Ah I see I was just trying to grab the length of [sorted](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Make.hs#L172) it looked like it might be the one. But I didn't realise it could build modules in parallel only ever seen the messages come out one at a time.

**Comment by hdgarrood** [comment]
I expect `length ms` and `length sorted` will be the same. Yes - it looks like the message comes out at the moment the module starts being rebuilt, so the if the compiler output shows something like this

```
Compiling Mod1
Compiling Mod2
```

it's possible that Mod1 hasn't finished being built yet.

**Comment by Cmdv** [comment]
ahhh that's a shame, could it be swapped to the messages being shown on completion? so reword `compiling` -> `compiled` ?

**Comment by paf31** [comment]
I'd rather keep it the way it is. Is there any reason to switch it to showing the number of completed modules?

**Comment by Cmdv** [comment]
Oh I thought that's what you wanted, you did rename it to `show progress..` But it's nice to know how far along the compilation is doing as well as the option to not seeing the whole output. That's why I initially thought a flag so current functionality wouldn't be changed only if you required it.

**Comment by garyb** [comment]
I'd quite like having the n/x count in the compilation message, as at least some idea of how far the compile has progressed. Even if it's the way Haskell does it where the `n` will skip modules that have already been compiled or whatever, so it's not a linear percentage-y indication.

**Comment by hdgarrood** [comment]
I think generally it's best to keep the number of flags as low as possible — the more code paths there are, the more places there are to introduce an error, the harder it is to test, and the more complex the code becomes.

I think the idea behind having it show the number of modules which have finished compiling is that that number is easy to produce when modules are being compiled in parallel, whereas "we are now compiling 1 out of n" isn't really true if, say, it's really the case that 1, 2, 3, and 5 are being compiled concurrently.

**Comment by Cmdv** [comment]
@hdgarrood I see what you are saying about flags and agree now. We could just use a percentage and have the modules flash up when they start compiling, then if they are concurrent it won't be a massive issue it's just an indication as to how far along the compilation has gone. With build tools like webpack the percentage jumps up and down a little but just the knowledge of how far there is left is nice.

**Comment by hdgarrood** [comment]
I think we really should strive to make any output as correct as we can, as people probably wouldn't only use the output for the sake of estimating how much remaining time there is. For example, if one module was causing an internal compiler error, or if one module started taking a very long time to compile due to a performance regression in a new release of the compiler, reporting the wrong module could waste quite a lot of someone's time and make issues more difficult to track down.

**Comment by Cmdv** [comment]
agreed, didn't think about it from that point of view. I tried to make the modules show once they had completed compilation. Rather than when they start.

But I struggled with gathering all the required data to display length of modules and current modules.

But that direction was probably not what we're after. I'd like to help with this issue but got stumped with the implementation. 😄

**Comment by safareli** [comment]
+1 for having something like this, It will be helpful especially when updating some library so you have some notion of progress while app compiles.
