### ISSUE TITLE
Effect Type Library

### ISSUE THREAD

**Issue by coot** [purescript/purescript#2962]
This isn't an issue with the compiler, but this might be the best place to discuss this.

The row polymorphism requires some coordination in the community to reuse the the same effects accross libraries we write / use.  It would be nice to have a module (in prelude?) from which one can import common effect types.  For example, the purescript-react library has two effects `Read` and `Write` which constrain how you can read & write state, props and refs in react.  But they might be useful in other libraries.  For example I could reuse them in purescript-redox where now I have to introduce my own `ReadRedox`, `WriteRedox`, `CreateRedox`, `SubscribeRedox`, but they all could be just imported from a common place.

I wonder if there are other overlaps in the purescript ecosystem that could be simplified.

**Comment by joneshf** [comment]
We discussed this a few years back: https://github.com/purescript/purescript/issues/506. At the time I was satisfied (though I know I don't speak for everyone). Maybe it's worth revisiting? Are any of the suggestions still relevant/useful?

**Comment by paf31** [comment]
This belongs in `purescript-eff` I think.

**Comment by paf31** [comment]
There is definitely a problem with an open world of effects, but I don't know how to solve it. `purescript-run` improves on `purescript-eff` in this regard, because you can invent new effects and write handlers to convert from one to the other. But `purescript-eff` can only do that unsafely.

**Comment by paf31** [comment]
I'm going to close this, but please reopen it on `purescript-eff` if the discussion in #506 doesn't solve the problem for you.
