### ISSUE TITLE
purescript bundle add support for multiple entry points

### ISSUE THREAD

**Issue by coot** [purescript/purescript#2963]
It would be nice to support multiple entry points by `purs bundle` and build es5 module for each entry point plus a common chunk module or a simpler solution mimick the module structure of the output directory (no bundling). Bundling can be done by other tools (webpack, browserify).

**Comment by hdgarrood** [comment]
Can you explain what this would add over the existing support for multiple entry points? I'm not sure I understand.

**Comment by coot** [comment]
hmm I didn't know that one can ask for multiple entry points. I would like to get a non bundled output (but maybe it already can do that?) - so it can be fed into webpack common chunk plugin.  It could also create those modules already prepared for that (n entry point modules, plus a module with common code).

**Comment by hdgarrood** [comment]
`purs bundle` always creates just one bundle but you can have multiple entry points, in the sense that you can ask that all code which is not used by any of the entry point modules should be removed. If you need more flexibility than that you might be able to achieve it using the rollup purescript plugin maybe?

**Comment by paf31** [comment]
Is there an example of something you'd like to be able to do that you can't currently do with `purs bundle`? Could you describe the output you'd like to see?

**Comment by Pauan** [comment]
I don't think Rollup supports outputting multiple files like that. I think your only option right now is to use Webpack.

**Comment by coot** [comment]
There are two webpack features that it would be nice to use within purescript webapps:

* using CommonChunksPlugin
* lazy loading of modules

To get support for the first one it would be enough to do DCE but no bundling.

There is a spec for [dynamic imports](https://github.com/tc39/proposal-dynamic-import) in ecmascript. Webpack is compliant with that.  I think one could add support for that in a library exporting the `import` function. When I will have time I will put an example for a simple lazy loaded component. But eventually one would like to use it not with the `output` directory, but with a DCE version of it that I speak in the first place.

**Comment by hdgarrood** [comment]
Have you seen [purs-loader](https://github.com/ethul/purs-loader)? Would that repo be a more appropriate place for this issue?

**Comment by coot** [comment]
Yes, I use purs-loader every day, and in order to get a better webpack plugin for purescript we need at least get the `purs bundle` which does DCE but not bundling.  That webpack can handle much better.

**Comment by Pauan** [comment]
So, essentially, this issue is about providing dead code elimination *without* bundling (i.e. the file structure will be the same as the current `output` directory, but with unused variables removed), correct?

`rollup-plugin-purs` does dead code elimination, it should be possible for me to split the dead code elimination algorithm so that it's separate from the Rollup plugin. That should solve the problem.

**Comment by hdgarrood** [comment]
Ok, so this isn't a compiler issue after all?

**Comment by paf31** [comment]
I would like to try something here. We could do the graph traversal as an intermediate step on the `--dump-corefn` output, to figure out what to keep, and then pass that structure back into `purs build`. This time, we'd only generate code for the functions we need. This way, `purs bundle` can really become just a bundler, and the dead code elimination code can I think be much clearer.

**Comment by Pauan** [comment]
@paf31 I certainly agree with that. Having the dead code elimination in the compiler means it can work for all the backends, not just JavaScript.

And the dead code elimination algorithm knows about things like purity and currying, so it will work a *lot* better than a JavaScript dead code eliminator.

**Comment by paf31** [comment]
@coot should this be closed or renamed?

**Comment by coot** [comment]
I would like to see you proposition being pushed forward.

**Comment by paf31** [comment]
Ok I'll make a separate issue for it. I'll close this since we already have support for multiple entry points in `psc-bundle`.
