### ISSUE TITLE
Expose module's exports type as a record

### ISSUE THREAD

**Issue by coot** [purescript/purescript#2966]
When using webpacks `require.ensure` to lazylly import a module (through ffi) it would be useful to say that a record has the same type as exports of a given module. [Example here](https://github.com/coot/purescript-lazy-loading-example/blob/master/src/Main.purs#L18) where I would like to write:
```
foreign import clickFn :: forall e err eff. Event -> Eff eff (Promise err (Module Common))
```

Where `Module Common` has a record type the same as exportsof the `Common` module.
This information should be used also by the DCE while computing transitive dependencies.

**Comment by chexxor** [comment]
So, the "Module" keyword in the "Module X" expression would instruct the compiler to resolve it as a type describing module X's exports, right? Like `{ fn1 :: Number -> String, fn2 :: String -> Aff _ Unit }`, if those were the exported functions of module X and their types.

Is this a feature which only applies to JS backend? I suppose the concept could apply to any language which has lazy-loaded modules, like dynamically-linked libraries in C. IDK if other backends, like Erlang or Java, have that concept.

**Comment by LightAndLight** [comment]
This reminds me of [First-class modules for Haskell](http://www.cis.upenn.edu/~bcpierce/FOOL//papers9/shields.pdf). It may be ambitious, but I think rather than a specific primitive just for this use-case it could be better to explore the idea that modules actually are records.

**Comment by Pauan** [comment]
@LightAndLight So with `import Foo as Bar`, `Bar` would be a record. I like it.

**Comment by chexxor** [comment]
Implementation of first-class modules sounds ambitious, indeed. In the meantime, we could make a Perl script to preprocess PureScript source files and insert it in place of a marking symbol. :)

**Comment by paf31** [comment]
There are a lot of questions to be answered here. For modules-as-records, how would type classes work, for example?

@coot Can you describe the core problem you want to solve?  I'm not familiar with `require.ensure`.

**Comment by hdgarrood** [comment]
> For modules-as-records, how would type classes work, for example?

I *think* the linked paper (First-class modules for Haskell) proposes one answer to that specific question, but of course the answer in PureScript might look quite different - especially since PureScript already has records, of course. I agree though, I think a proposal adding features to the language like this should be a bit more fleshed out before earning a space on the issue tracker, ideally.

**Comment by kRITZCREEK** [comment]
Maybe this can be achieved by parsing the externs/teaching `purs ide`/some special compiler command to output the externs format in a non-binary format?

**Comment by paf31** [comment]
> I think the linked paper (First-class modules for Haskell) proposes one answer to that specific question, but of course the answer in PureScript might look quite different

Yes, I think so. The problem is that wrapping everything in a rank-2 function which brings instances into scope is somewhat at odds with the goals of PureScript. It makes PS-to-JS FFI much more difficult for example.

Maybe with constraint kinds we'd be able to do something simpler.

I agree though, let's please come up with concrete proposals for anything to do with modules, or just generally really. We've discussed a lot of options before.

For the original issue though, I'd like to just distill this down to a single problem, and decide if it's possible to solve it without thinking about a module system yet.

**Comment by coot** [comment]
@paf31 useing `require.ensure` I can expose a PureScript module.  In the example I linked I did it using a promise.  Importing it through ffi I would like to say that the promise resolves with to a given PureScript module.

**Comment by paf31** [comment]
Can't you do that with records now?

**Comment by coot** [comment]
Yes I can, but the type system already knows them.

**Comment by paf31** [comment]
So, the minimal feature to support this would be something like a new piece of type syntax `module M` where `M` is a named module, which resolves to a record containing the values exported by `M`. Does that sound right? For now, we'd presumably ignore type classes.

I'd be interested to hear the details of what the type system changes might look like, but I'm inclined to say I would not want this right now, and instead recommend using some sort of script to create those types for you.

**Comment by coot** [comment]
Another way to tackle this would be to have closed type families and each module would come with a predefined
```
type family Import Symbol :: Type
```

**Comment by hdgarrood** [comment]
Shall we close this? I'm not sure it justifies changes to the type system, and @natefaubion has described a way of achieving the same goal (being able to load modules lazily) in userland in the [discourse discussion on lazy loading](https://discourse.purescript.org/t/lazy-loading-routes-in-tea-style-app/141).

**Comment by coot** [comment]
Agreed
