### ISSUE TITLE
Trimming surrounding white space from type level strings in compiler messages

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript#2971]
from https://github.com/purescript/purescript/pull/2954

I'd really like to trim the surrounding white space *but leave all white space inside the string in-tact for users to format things as they wish if needed*. Mostly because I like to write my type level strings with triple quotes by doing the following:

```purs
instance ctorArgumentGenericEncodeEnum
  :: Fail """
    genericEncodeEnum cannot be used with constructors with arguments.
"""
```

And I see this often in other libraries that have longer type level strings, especially for Fail/Warn. Thoughts?

**Comment by hdgarrood** [comment]
I'm not keen, because if we teach people that doing this won't include the unwanted whitespace, then it'll be a nasty surprise if they (reasonably) expect the same trimming to occur in other contexts, like value-level string literals.

**Comment by natefaubion** [comment]
```purescript
class TrimSymbol s1 s2 | s1 -> s2

instance ctorArgumentGenericEncodeEnum
  ::  TrimSymbol """
    genericEncodeEnum cannot be used with constructors with arguments.
""" s2
  => Fail s2
```
🤔

**Comment by natefaubion** [comment]
I'm not opposed to other formatting options for errors, but I don't think this should be done by default. Perhaps a `FailFormat` class which can take formatting options?

**Comment by hdgarrood** [comment]
I also think it's worth noting that since this issue was created, we changed `Prim.TypeError.Fail` to take a `Doc` rather than a plain `Symbol`, and in particular I think the new `Beside` and `Above` somewhat reduce the need to write longer multiline strings in triple quotes when writing type errors.

**Comment by natefaubion** [comment]
That's a good point. I think since we provide more fine-grained layout options via `Doc`, this can be closed?

**Comment by hdgarrood** [comment]
I think so, yeah.

**Comment by natefaubion** [comment]
For reference, here is an example of using `Doc` to achieve non-trivial formatting:
https://github.com/natefaubion/purescript-typelevel-eval/blob/04e86ce3be5c46a7a13270d4fca183af6de648f5/src/Type/Eval.purs#L17-L40
