### ISSUE TITLE
Language Server Protocol support for psc-ide

### ISSUE THREAD

**Issue by jazmit** [purescript/purescript#3000]
http://langserver.org/

Has any thought gone into making psc-ide compatible with this?  It seems like a easy win for getting better editor support for purescript.

**Comment by chexxor** [comment]
Yeah, there has been discussion. AIUI, lang server gives answers to
line-column queries, whereas psc-ide answers queries for symbol in some
module (for example). It's reasonable to implement lang server APIs in
separate project which then creates a request that psc-ide can answer. I
think @nwolverson made a little progress on this kinda thing.

**Comment by nwolverson** [comment]
There is a LSP already as a node wrapper around psc-ide, currently used by vscode https://www.npmjs.com/package/purescript-language-server. I'm happy to work with anyone that wants to further integrate with a different IDE - my only attempt to do so didn't get so far as I had installation issues (neovim I think?). 

Of course this could eventually be folded into psc-ide, but one indication of the value of that would be it is actually being used (don't think it's used by other than vscode ATM).

The big wins to my mind for editor support compared to current possibilities are features like type information for arbitrary identifiers, refactoring support, etc - which are not hampered by psc-ide API but by the fundamental feature support.

**Comment by paf31** [comment]
This doesn't really seem like it's a compiler or psc-ide issue necessarily, especially since there is already an LSP wrapper, so I'm going to close this.

**Comment by rgrinberg** [comment]
@paf31 you don't think it would be better if psc-ide provide support for a widely used protocol? This would really reduce the effort for editors to integrate with purescript. It will not be necessary to write psc-ide specific plugins, but simply use one of the general purpose lsp plugins.

**Comment by matthewleon** [comment]
@rgrinberg support exists in the form of https://github.com/nwolverson/purescript-language-server

Granted, this requires a sort of middleware layer between psc-ide and the language client, but this seems to be working out fine.
