### ISSUE TITLE
psc command not found

### ISSUE THREAD

**Issue by stifspear** [purescript/purescript#3004]
I have installed PureScript using npm.
npm verision:5.3.0
node version:v8.2.1

after npm install -g purescript i get:
stifspear@stifspear:/usr/local/lib/node_modules$ npm install -g purescript
/usr/local/bin/purs -> /usr/local/lib/node_modules/purescript/bin/purs.js

> purescript@0.11.6 postinstall /usr/local/lib/node_modules/purescript
> node lib/install.js

  ✔ pre-build test passed successfully
+ purescript@0.11.6
added 298 packages in 100.443s

psc command is not found. Other binary files are also missing. psc-ide-server and psc-ide-client missing among many.
Guide provided  at github is not working.

**Comment by paf31** [comment]
`psc` was renamed to `purs compile`. If you use the latest Pulp, you won't need to use it directly anyway.

**Comment by hdgarrood** [comment]
Which guide were you following?

**Comment by stifspear** [comment]
Thank you for your reply
I am trying to use psd-ide-vim but it is giving me some error.
It may be different topic but I dont get it.
E121: Undefined variable: g:psc_ide_syntastic_mode
E15: Invalid expression: g:psc_ide_syntastic_mode == 0
I am looking for autocompletion editor for PS. Can you guys suggest some?

**Comment by coot** [comment]
vim plugin is actively maintained now, and you're welcome to contribute too.  I think best integration at the moment you'll get in `emacs`, though `vim` isn't much behind.

**Comment by hdgarrood** [comment]
That sounds like it might be an issue in [psc-ide-vim](https://github.com/FrigoEU/psc-ide-vim), so I'd report it there.
