### ISSUE TITLE
Canonical location for CSS for HTML docs

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3016]
Currently we have `app/static/pursuit.css` in this repo, as well as `static/css/pursuit.css` in the Pursuit repo, and `static/css/pursuit.less` (which generates it). Since these are starting to diverge I think we need to have a single place for this CSS. How about:

* Moving the LESS source to this repo
* Checking in the result of compiling it to CSS (we've kind of done this already)
* Creating a module `Language.PureScript.Docs.CSS`, which just exports the compiled CSS as `docsCSS :: Text`, via `file-embed`, so that Pursuit can use that.

**Comment by kRITZCREEK** [comment]
Is there any point in using Clay, so we don't need an extra toolchain?

**Comment by hdgarrood** [comment]
We're already using npm in the tests, so I don't think it's extra toolchain. I'd also really rather not use a Haskell EDSL for CSS.

**Comment by kRITZCREEK** [comment]
I thought the idea was to switch to `psc-package` and only use node to run the examples? But I can totally see why. Less is a very battle-tested technology^^

**Comment by hdgarrood** [comment]
Oh right, yeah, I agree that switching to `psc-package` for the tests would be good. Just in case it's unclear, with what I'm proposing, you would only need to install LESS if you wanted to modify this CSS: everyone else would just use the checked-in result without needing to do anything. I don't want to somehow shoehorn LESS compilation into the build process (that doesn't tend to work very well, in my experience).

**Comment by joneshf** [comment]
Why is Less necessary at all? Can we switch to plain CSS?

**Comment by hdgarrood** [comment]
Mainly because it helps keep things like colours consistent, and makes it significantly easier to tweak colour schemes without breaking things. See the LESS source: https://github.com/purescript/pursuit/blob/master/static/css/pursuit.less. In my mind, having to do `npm install less && lessc pursuit.less > pursuit.css` is a really rather small price to pay for that.
