### ISSUE TITLE
[purs ide] Externs parse failure needs a better error

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#3036]
This is where the error is coming from: https://github.com/purescript/purescript/blob/7a59b02221df1f906efa4a911b8ad83c86d2fdc6/src/Language/PureScript/Ide/Externs.hs#L34-L54

I added a case to show the version mismatch, but that only works if the outdated externsfile still parses with the new version, which is a silly assumption to make. We should ignore the remaining structure and read the version field with Aeson which should allow us to give a version mismatch error even if the structure of the ExternsFile format has changed.

**Comment by joneshf** [comment]
Should we attempt to parse just the version in the `Nothing` case? Or is there some other path to success here?

**Comment by kRITZCREEK** [comment]
Yeah I think that's the path forward, the version should always be available as a top level field: https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Externs.hs#L41. And even if that fails we should talk about a potential compiler version mismatch.

**Comment by kRITZCREEK** [comment]
Fixed in #3037
