### ISSUE TITLE
psci tab completion can't be accessed by certain tools

### ISSUE THREAD

**Issue by actionshrimp** [purescript/purescript#3042]
I jumped the gun a bit and opened PR #3038 - this issue is for a bit of discussion first.

I noticed using psci-mode in emacs that I seemed to be unable to access the tab completion available when running psci in the terminal (although tab completion of things like filenames seems to be provided out of the box). I'm assuming this is a problem in psci-mode as I spotted an issue in it's own repo (https://github.com/ardumont/emacs-psci/issues/8), however I'm not ruling out that my setup is incorrect in some way (it would be great if someone could confirm this - I asked a couple of times in slack but didn't get a definite confirmation).

After a bit of digging around it seems this is a limitation of the way emacs communicates with the psci process, sending input as whole commands at a time, rather than character at a time as a terminal would. This effectively means tab completion is inaccessible to these kind of tools.

A potential solution would be to expose the completion functionality via a psci directive as in the pull request. I did consider trying to use psc-ide here, but synchronising the state between the ide process and the repl process sounded pretty tricky, so the directive definitely seems like the cleanest option.

As a fair few people use spacemacs and psci-mode is a default into the purescript layer it'd be great to have this working as cleanly as possible - although I guess another solution would be to amend the spacemacs layer and strip out psci-mode if encouraging people to use psc-ide is the way forwards 😄

**Comment by hdgarrood** [comment]
After having seen @kRITZCREEK's comment

> Well ide is another (long running) process you have to manage, and it doesn't know the things the repl knows about its current environment (what modules are imported under what alias).

I do think this is reasonable, and it's a fairly small change too, so I'm in favour.

**Comment by actionshrimp** [comment]
#3038 got merged so closing this!
