### ISSUE TITLE
Problem coercing type class methods combined with effect rows

### ISSUE THREAD

**Issue by rpeszek** [purescript/purescript#3043]
This maybe related to https://github.com/purescript/purescript/issues/1510 and similar tickets. 
I am new to PureScript and I apologize if this is know or somehow obvious.

My understanding is that the mechanizm for coercing Eff type calculation 
from fewer effect to more effects is the use of liftEff.
This does not work well if typeclasses are used. Consider something like this contrived example: 

```
-- Assume:
foreign import data APPCONFIG :: Effect
foreign import data NAVIGATION :: Effect
getBaseUrl :: forall e . Eff (appconf :: APPCONFIG | e) String

type AppConfigM eff = (Eff (appconf:: APPCONFIG | eff))
type MoreEffM eff = Eff (appconf:: APPCONFIG, nav:: NAVIGATION | eff)

-- | compiles fine
test:: forall eff. MoreEffM eff String
test = liftEff getBaseUrl 

-- | but:
class AppConfigClass eff a where
  getConfig :: a -> AppConfigM eff String

-- | the following does not compile with
-- | No type class instance was found for TempTest.AppConfigClass ( nav :: NAVIGATION | eff4) a5
test2 :: forall eff a. AppConfigClass eff a => a -> MoreEffM eff String
test2 a = liftEff $ getConfig a
```
Type checker tells me I need:
```
test2 :: forall eff a. AppConfigClass (nav :: NAVIGATION |eff) a => a -> MoreEffM eff String
test2 a = liftEff $ getConfig a
```
Implementing a generic way to lift to more effects seems not trivial
```
liftNav :: forall e a . Aff e a -> Aff (nav :: NAVIGATION | e) a
```
I can do that (ugly):
```
liftNav = unsafeCoerceAff
```
What is the right way to lift computations from fewer to more effects?  Thank you for help!

**Comment by paf31** [comment]
The recommended way is to leave all effect rows open, except for in `main`. Then unification will do the right thing in almost all cases. In this case, you should probably just modify the context so that `AppConfigClass eff a` becomes `AppConfigClass (nav:: NAVIGATION | eff) a`.

Closing, since this isn't a compiler issue.

**Comment by rpeszek** [comment]
Thank you, I will try it out
