### ISSUE TITLE
UnknownExport error is missing position information

### ISSUE THREAD

**Issue by sudhirvkumar** [purescript/purescript#3044]
When I am exporting something which is not defined in the file. It doesn't show error in that particular line. And also it doesn't show any others errors in the file unless the `UnknownExport` error is fixed.

Maybe because the line number and position information is missing for this particular error?

I am not sure about other editors, but this is the situation in emacs.

**Comment by kRITZCREEK** [comment]
Yeah, this is a problem with the Error missing position information, probably introduced recently when moving the spans into declarations.

**Comment by paf31** [comment]
Closing as a duplicate, since we have an issue to track all missing error position info.
