### ISSUE TITLE
Unexpected output buffering in PSCI

### ISSUE THREAD

**Issue by dariooddenino** [purescript/purescript#3052]
```haskell
simple = do
  t <- setInterval 1000 do
    traceAnyA "Hey"
    pure unit
  _ <- setTimeout 5000 $ clearInterval t
  pure unit
```
With `pulp run` this prints one "Hey" every second.
In `pulp psci` all the "Hey"s are printed at the same time at the end.

**Comment by paf31** [comment]
This is because PSCi runs in batch mode by passing the compiled code to Node. It is expected behavior.

**Comment by hdgarrood** [comment]
Maybe, but I think it's not a good behaviour, and I think we should try to address it. I also don't think it would be very difficult.

**Comment by paf31** [comment]
We could run Node as a server process and try to reuse parts of the existing browser backend code. It would need a proposal for how to deal with things like cancellation, and if we would reuse the existing websocket, for example, but I'd suggest a separate issue for that discussion.

**Comment by hdgarrood** [comment]
I'd like to do that too but I think in the meantime we can just use the `Inherit` option from `System.Process` for the standard output streams when creating the process, and then wait for it: https://hackage.haskell.org/package/process-1.6.1.0/docs/System-Process.html#t:StdStream

**Comment by paf31** [comment]
Sure, that sounds like something worth investigating.
