### ISSUE TITLE
purs bundle uses too much memory

### ISSUE THREAD

**Issue by wereHamster** [purescript/purescript#3055]
I have a project which consists of ~650 modules, total size of the `output` directory is 19MB, roughly 100k lines of code in `output/*/*.js` files. purs bundle (0.11.6) and psc-bundle (0.10.5) both need more than 9GB of RAM to generate the bundle. This is far too much and the process is killed by the OOM killer on our CI/CD service.

**Comment by coot** [comment]
You could try [zephyr](https://github.com/coot/zephyr), but you will need to compile purescript from this #3039 . It would be interesting to see how it runs on such a big project.

**Comment by garyb** [comment]
Hmm, that's very strange - `purs bundle`ing SlamData (1612 modules, 53MB, 270k loc in output) takes 2.5GB of RAM.

**Comment by wereHamster** [comment]
Is there anything I can help to track this down? Like running purs-bundle with profiling enabled to see where memory is used?

**Comment by wereHamster** [comment]
```
$ psc-bundle --version
0.10.5
$ psc-bundle output/*/*.js --main App.Client --module App.Client --output app.js +RTS -s
  45,887,748,784 bytes allocated in the heap
  31,181,544,320 bytes copied during GC
   6,855,521,184 bytes maximum residency (16 sample(s))
     149,406,984 bytes maximum slop
           13714 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     88483 colls,     0 par   13.263s  16.844s     0.0002s    0.0407s
  Gen  1        16 colls,     0 par   15.122s  37.965s     2.3728s    22.3517s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time   18.885s  ( 39.687s elapsed)
  GC      time   28.385s  ( 54.809s elapsed)
  EXIT    time    0.117s  (  1.991s elapsed)
  Total   time   47.392s  ( 96.488s elapsed)

  %GC     time      59.9%  (56.8% elapsed)

  Alloc rate    2,429,871,870 bytes per MUT second

  Productivity  40.1% of total user, 19.7% of total elapsed
```

**Comment by wereHamster** [comment]
@coot the codebase is old and we're still stuck with purescript 0.10. Upgrading to a newer compiler is not economical.

**Comment by wereHamster** [comment]
Had no luck running with `+RTS -h`, the process was still running after 30 minutes and appeared stuck, didn't even respond to ^C, had to kill it with SIGKILL.

**Comment by paf31** [comment]
Obviously we're doing a lot of garbage collection there, but it would be good to get a full profile if possible, to see where the allocation and CPU time hotspots are.

**Comment by wereHamster** [comment]
After I trimmed the output folder and only left ~200 modules (only Control and Data), and then did a `purs bundle […] --module Data.Show […]` (which should take just a milisecond since that's a self-contained module without any external dependencies!), I was able to capture a heap profile

## `+RTS -hm`

![screen shot 2017-08-30 at 08 02 17](https://user-images.githubusercontent.com/34538/29857612-cb4fe76e-8d59-11e7-98bc-1e1c389adab9.png)

## `+RTS -h`

![screen shot 2017-08-30 at 08 04 40](https://user-images.githubusercontent.com/34538/29857653-fc6c44aa-8d59-11e7-9f59-7439c208a92f.png)

## `+RTS -p`

Just the top cost centres.

```
COST CENTRE                  MODULE                              SRC                                                                                                       %time %alloc

catchIO                      System.FilePath.Glob.Utils          System/FilePath/Glob/Utils.hs:167:1-17                                                                     19.8   19.8
doesDirectoryExist.\.\       System.FilePath.Glob.Utils          System/FilePath/Glob/Utils.hs:(121,18)-(125,32)                                                            18.5    0.2
doesDirectoryExist.\         System.FilePath.Glob.Utils          System/FilePath/Glob/Utils.hs:(117,7)-(125,32)                                                             13.3   12.7
happyReduceArr               Language.JavaScript.Parser.Grammar5 .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/Language/JavaScript/Parser/Grammar5.hs:(1001,1)-(1349,9)   11.8    0.0
getRecursiveContents.entries System.FilePath.Glob.Utils          System/FilePath/Glob/Utils.hs:134:11-53                                                                     6.7   31.6
>>=.\                        Language.JavaScript.Parser.Lexer    templates/wrappers.hs:(207,27)-(209,63)                                                                     3.3    0.7
indexShortOffAddr            Language.JavaScript.Parser.Grammar5 templates/GenericTemplate.hs:(139,1)-(145,39)                                                               3.2    0.0
matchTypedAndGo              System.FilePath.Glob.Directory      System/FilePath/Glob/Directory.hs:(159,1)-(194,72)                                                          3.0    1.5
happyDoAction                Language.JavaScript.Parser.Grammar5 templates/GenericTemplate.hs:(111,1)-(136,60)                                                               2.2    2.1
happySpecReduce_1            Language.JavaScript.Parser.Grammar5 templates/GenericTemplate.hs:(189,1)-(193,64)                                                               2.1    1.8
alexGetByte                  Language.JavaScript.Parser.Lexer    templates/wrappers.hs:(73,1)-(77,67)                                                                        1.3    4.5
alex_scan_tkn                Language.JavaScript.Parser.Lexer    .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/Language/JavaScript/Parser/Lexer.hs:(1211,1)-(1244,65)      1.2    1.2
happyGoto                    Language.JavaScript.Parser.Grammar5 templates/GenericTemplate.hs:(249,1)-(254,55)                                                               1.1    0.7
globDir'.\                   System.FilePath.Glob.Directory      System/FilePath/Glob/Directory.hs:142:36-74                                                                 0.5    2.7
utf8Encode                   Language.JavaScript.Parser.Lexer    templates/wrappers.hs:(34,1)-(51,25)                                                                        0.5    2.2
unconsB                      Codec.Binary.UTF8.Generic           Codec/Binary/UTF8/Generic.hs:297:1-18                                                                       0.4    2.3
decode.choose                Data.ByteString.UTF8                Data/ByteString/UTF8.hs:(72,3)-(78,39)                                                                      0.4    1.1
doesDirectoryExist           System.FilePath.Glob.Utils          System/FilePath/Glob/Utils.hs:(115,1)-(125,32)                                                              0.3    1.8
foldr                        Data.ByteString.UTF8                Data/ByteString/UTF8.hs:(171,1)-(173,40)                                                                    0.3    1.8
```

**Comment by wereHamster** [comment]
It appears that if you expand the list of input files yourself (and to be honest, the `purs bundle` command doesn't indicate that it supports globs itself), then purs bundle tries to expand every single input file with `System.FilePath.Glob.Utils.glob`. And that function is /really/ expensive, both in terms of time and memory, even if the string doesn't contain any wildcards.

**Comment by naehrstoff** [comment]
To add some more context: I remembered we took the command

```psc-bundle output/*/*.js --module Main --main Main```

from the [PureScript Without Node](https://github.com/purescript/documentation/blob/master/guides/PureScript-Without-Node.md) documentation page and wanted to suggest to change it to say

```psc-bundle 'output/*/*.js' --module Main --main Main```,

i.e. pass the glob as a string instead of a huge list of files. But then @wereHamster correctly noted that it should not matter whether we pass a list of files or a glob, `psc-bundle` (or `purs bundle` as it is called now) should be able to handle either well.

**Comment by kRITZCREEK** [comment]
So in that case the fix is to pass the globs quoted to psc-bundle. I doubt anything will be backported to 0.10 if there is a workaround, but for 0.12 we could think about scanning the passed arguments for wildcards and only attempt to expand those that contain them.

**Comment by hdgarrood** [comment]
I think it would be nice to see if we can make a contribution to the `Glob` library to reduce the cost of globbing when the supplied pattern is just a straightforward file path.

**Comment by hdgarrood** [comment]
I commented on an upstream issue with respect to this; see https://github.com/Deewiant/glob/issues/10#issuecomment-326066118

**Comment by hdgarrood** [comment]
Glob-0.9.0 is now on Hackage, updating should fix this.
