### ISSUE TITLE
Matching on Unit (and a possible solution with View Patterns)

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#3056]
Take this silly example case:
```
data Abc = A | B | C

silly :: Unit -> Int
silly x = case x of
  _ -> 1
```

Change the type signature to:
```
silly :: Abc -> Int
silly x = case x of
  _ -> 1
```

... and PureScript gives you no warning that you're swallowing the potential variants that the `Abc` type could give you.

I'm aware we don't want to be able to match on a `Unit` constructor directly, but there's a way of solving this with [View Patterns](https://ocharles.org.uk/blog/posts/2014-12-02-view-patterns.html) that doesn't require this:
```haskell
{#- LANGUAGE ViewPatterns -#}
type Unit = () -- to make it look like purescript

takeUnit :: Unit -> Unit
takeUnit = id

data Abc = A | B | C

silly :: Abc -> Int
silly x = case x of
  (takeUnit -> _) -> 1   -- Kaboom! Now fails to compile. 
                         -- Compiles if we switch back to Unit -> Int
```

I know View Patterns are a large chunk of work in themselves, but I couldn't find mention of either "pattern-matching on Unit" or "view patterns" in the tracker, so I figured I'd talk about both. 😄 

Any thoughts?

**Comment by hdgarrood** [comment]
I don't find this use case particularly compelling, personally — by the same argument shouldn't the compiler warn on any use of `const`? — but view patterns are nice.

**Comment by hdgarrood** [comment]
How about this, which you can do now:

```purescript
constUnit :: forall a. a -> Unit -> a
constUnit = const

silly :: Unit -> Int
silly = constUnit 1

```
With this, if you change the type signature of `silly` so that it takes an `Abc`, the code will no longer compile.

**Comment by damncabbage** [comment]
> I don't find this use case particularly compelling, personally — by the same argument shouldn't the compiler warn on any use of const? 

The argument wasn't complaining that `_ -> ...` produced a warning; it was more that I couldn't think of a way to avoid using the overly-broad `_` match for the single Unit value I was trying to target.

My actual motivating case is matching on the result of a `Either SomeError Unit` that will shortly be changing into an `Either SomeError SomeResult`. At the moment I have `Right _ -> ...` in a few places (to currently match Unit), and was not looking forward to having to manually hunt them down.

**Comment by damncabbage** [comment]
Regarding my example: I just realised I could `Right (_ :: Unit) -> ...` to make the same assertion as a more direct (hypothetical) `Right Unit -> ...`.

Let me know if I should close this, and/or add this to the docs somewhere.

**Comment by hdgarrood** [comment]
I think probably best to close, yeah. If we were going to add this to the docs we would probably put it in the language reference in the documentation repo, where it describes the syntax of `case` expressions.
