### ISSUE TITLE
Solve IsSymbol for TypeString

### ISSUE THREAD

**Issue by dwhitney** [purescript/purescript#3059]
Hey all, there is a lot of cool type level programming going on these days, but I can't seem to figure out how to get much done without instances of types. 

What I'd like to do is generate a GraphQL schema from a type, like a record. So given `type MyRecord = { foo :: String }` I'd like to generate the a String representation of the GraphQL object type `type MyRecord { foo : String! }`. If it's not possible to get `MyRecord`, even just `foo: String!` would be good enough, but I cant figure out how to get at the name of the type (String).

I asked this question in IRC and someone said it was not possible and I should post an issue here asking to "solve IsSymbol for TypeString". Frankly I have only a vague idea of what this means, but this does seem like a useful language feature. If it already exists, I'd appreciate any help pointing me in the right direction. Otherwise maybe it's something useful to consider. Thanks!

**Comment by paf31** [comment]
I wonder if we should remove `TypeString` and `TypeConcat` in favor of fundeps actually, since we already have `SymbolAppend`.

**Comment by LiamGoodacre** [comment]
Are you saying we should replace `TypeString` with a type class, like `class IsSymbol s <= ShowType t (s :: Symbol) | t -> s`.  Allowing anyone to render types as strings.  How would that work with type variables which haven't yet been determined.  Would need to be very careful with out of order constraint solving.
If you didn't mean that, what would we substitute in its place for the `Fail` type class?

**Comment by paf31** [comment]
Oh good point. Well the same applies to solving `IsSymbol`, doesn't it? How do we know when we've solved enough unification variables to return a string?

**Comment by LiamGoodacre** [comment]
With `IsSymbol` we pattern match on the type argument being a literal symbol.  So the instance isn't automatically solved until after unification has progress enough to yield a symbol that we can match on.

**Comment by hdgarrood** [comment]
Is this compatible with https://github.com/purescript/purescript/issues/3134, if we're doing that?

**Comment by LiamGoodacre** [comment]
@hdgarrood It wouldn't be compatible in the sense that the type level data structure for quoting a type expression: `TypeString` would no-longer be of kind `Symbol`, and therefore not be a suitable argument to the `IsSymbol` type class.  However, I'm not convinced that we should render type expressions to symbols like this anyway.

I believe the original question is about how to get a symbol representation of the name of a data type.  This sounds like a very restricted use case that I'd rather solve with some kind of generics-rep extension or other similar procedure.

I'd love to hear specific use cases of this feature that couldn't be better solved with some slight variation of something we already have.

**Comment by hdgarrood** [comment]
Come to think of it, this reminds me of some of @justinwoo's libraries, e.g. `kancho`, which gives you a way of generating types for Elm code based on your types in PureScript; see [the code](https://github.com/justinwoo/purescript-kancho/blob/ce7bbed6a313db748c2caea99a6a009def653170/src/Kancho.purs). As far as I can tell, a similar technique should probably work for what @dwhitney is asking for.

**Comment by dwhitney** [comment]
Hmmm yeah that looks like it'd work for what I need. These lines look like
they do exactly what I was looking for:

https://github.com/justinwoo/purescript-kancho/blob/ce7bbed6a313db748c2caea99a6a009def653170/test/Main.purs#L57-L59

Thanks!  We can close this one if you all want.

**Comment by hdgarrood** [comment]
Great! Without a motivating use case for this feature I'm tempted to close, what do others think?
