### ISSUE TITLE
Hiding syntax for exports

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/purescript#3060]
Would work maybe something like this:

```purescript
module Foo hiding (somethingInternal) where
...
```

instead of having to export everything explicitly:

```purescript
module Foo (foo, bar, baz, norf, worble, ...) where
...
```

More often than not it seems like there are only a few internal functions and the vast majority of identifiers would actually be public-facing

**Comment by paf31** [comment]
I'd really rather not. Export lists serve as documentation, and with this proposal, any analysis of imports/exports would have to parse entire files, not just the exports and imports lists.

**Comment by chexxor** [comment]
This syntax can more accurately describe what a module author would like to do, so I'd like to continue discussion. It would be good documentation for other people searching this issue in the future.

Whenever I see an export list in a module, the only reason I've seen to do this is to hide a type constructor and enforce smart constructors. When a module has 20 functions and 1 data type, the exports list becomes unmaintainable - easy to add a new function but forget to export it so it's unusable by accident. The more precise way to hide a type constructor would be `module Foo hiding (MyType(..)) where`.

You say the price of hiding exports syntax would be in complicating exports analysis. I'm curious - 
where is that happening? In type-checking phase? Or when picking up cached compilation results? Or perhaps only in repl or psc-ide?

**Comment by jdegoes** [comment]
Another reason (for the way things are presently) is that it helps  reduce conflicts during upgrades.

I do admit imports get painful sometimes but it's certainly nice to be able to know where everything comes from, at a glance, without digging through source files, and nice to know you can upgrade libraries with additive elements w/o introducing conflicts.

**Comment by kRITZCREEK** [comment]
> the exports list becomes unmaintainable - easy to add a new function but forget to export it so it's unusable by accident

I'd prefer to tackle this problem by emitting a warning for non-exported, non-used functions instead of complicating the export section. 

I think `purs docs` also uses the export section to determine the ordering of definitions in the documentation, so it would be nice to encourage people to use that feature (Not because I want all our features to be used, but because thinking about how your module forms a cohesive unit and how its functions related to one another leads to better design).

**Comment by hdgarrood** [comment]
> Whenever I see an export list in a module, the only reason I've seen to do this is to hide a type constructor and enforce smart constructors.

Just to add a data point - I regularly define top-level functions which aren't exported, and I see them quite often in other people's code too.

**Comment by paf31** [comment]
I agree with Christoph. If we could generate an initial exports lists automatically as well, in response to the warning, that would be ideal.

**Comment by hdgarrood** [comment]
Shall we close this one, then?

**Comment by aranchelk** [comment]
PureScript as since added hiding for imports, but this page is the top Google result for "PureScript hiding", see https://github.com/purescript/documentation/blob/master/language/Modules.md#hiding-imports
