### ISSUE TITLE
purs-ide add import sorting doesn't recognize `hiding` imports as open

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3068]
If I do

```
import SlamData.Prelude hiding (note)
import DOM as DOM
```

This will be resorted to
```
import DOM as DOM
import SlamData.Prelude hiding (note)
```

It does not recognize the `hiding` import as an open import, and so it gets moved around.

**Comment by kRITZCREEK** [comment]
Should be a pretty small change in `prettyPrintImportSection ` inside `/src/Language/PureScript/Ide/Imports.hs`. I'll let it sit for a week in case anyone wants to pick it up, should be a decent first contribution.
