### ISSUE TITLE
duplicate modules disambiguation

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3074]
Problem:
In some cases it's nice to have two config files (PureScript modules).  The simplest example is to have two `Config` modules which exports `isProduction :: Boolean` flag (one in `src/ConfigDev.purs` and the other `src/ConfigProd.purs`. 

Proposed solution:
PureScript complains about a module being defined multiple times.  If there was a switch to point to one of them to disambiguate which one the compiler should use we could have project level config defined in purescript. In bash one can use `GLOBIGNORE`, but this not cross platform (or even cross shell) solution.  I propose to have a switch for that: 
```bash
purs compile --choose src/ConfigDev.purs 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs'
```

What I like about the proposed solution:
* configuration is type checked (and it's just a PureScript module with all it's super powers ;))
* [zephyr](https://github.com/coot/zephyr) will be able to DCE dead branches of `case` expressions, so debugging code/settings will not land in production code.

**Comment by hdgarrood** [comment]
I'm not a fan of this. If you need to switch implementations between different compiles, why not have separate directories for them e.g. `purs compile "src/**/*.purs" "src-dev/*.purs"` for dev builds, and likewise a `src-prod` directory which you use for production builds.

**Comment by coot** [comment]
@hdgarrood that's even simpler!
