### ISSUE TITLE
Switch from Eff to IO

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3080]
Optimizer rules need to be updated as part of the switch to `IO` as the default effect monad.

**Comment by Pauan** [comment]
Woah woah woah woah, PureScript is getting `IO` instead of `Eff`? When did this happen?

**Comment by michaelficarra** [comment]
@Pauan It was done via [emoji-based Twitter poll](https://twitter.com/paf31/status/908760073303764993) &mdash; the most appropriate medium for language design discourse.

**Comment by Pauan** [comment]
@michaelficarra Thanks for the link.

That's great news! I always really liked the *idea* of `Eff`, but I hated the *implementation*:

1. So many unintuitive errors for things which *should* work.

2. `Eff` is always a 0-argument JS function, which means you can't have different implementations for different effects.

**Comment by paf31** [comment]
Actually, it's been discussed in several other places before that, including on Slack, and [on the `eff` repo](https://github.com/purescript/purescript-eff/issues/25), including [an unmerged PR for a previous version](https://github.com/purescript/purescript-eff/pull/20). I think the `eff` repo is the right place to discuss it if there are objections, but this is the issue to track the necessary compiler changes. The Twitter poll was just one more check I wanted to do to see how the broader community (who might not watch all of the repos) might respond to the change.

**Comment by garyb** [comment]
Should we have a real issue about the name of `Eff` vs `IO`? I think a couple of threads on Slack about it means people's voices on it may be easy to miss. I was there for the first discussion that Phil wasn't, and it seemed like the consensus of having `Eff :: Type -> Type` was _much_ preferable to renaming to `IO`, but then I saw the tail end of a Slack conversation the other day where the reverse seemed to be the case.

**Comment by paf31** [comment]
Yes, sounds like a good idea.

**Comment by spicydonuts** [comment]
I don't know much of the background on this, but `Eff e a` -> `Eff a` seems like a much better way to go if everything currently using `Eff` and `Aff` should be removing its effect rows.  `IO` seems better if there's still a use case for keeping the current `Eff` implementation around (no idea what that would mean for `Aff`).

**Comment by garyb** [comment]
I'm slightly more in favour of keeping the `Eff` name and dropping the row than renaming to `IO` too. I could get used to it either way, but it definitely seems like the update overhead will be lower by continuing with `Eff` / `Aff`.

**Comment by hdgarrood** [comment]
Let’s discuss what we call it in https://github.com/purescript/purescript-eff/issues/25 perhaps?

**Comment by garyb** [comment]
Sure, I'll port the comments over.

**Comment by starper** [comment]
+1 for having base `IO a` and `Eff e a` as an extended version of `IO a`

**Comment by Risto-Stevcev** [comment]
Now that Eff is being replaced, what do you guys think of bringing back the restriction that rows can't have duplicate labels?

**Comment by natefaubion** [comment]
Purescript-run wouldn’t be possible without duplicate labels.

**Comment by paf31** [comment]
I think duplicate labels are a better, more principled choice for other reasons.

**Comment by urs-of-the-backwoods** [comment]
I'm absolutely looking forward to this. Trying to write callbacks in React and stumble on Effects proliferation, since they spread upwards AND downwards, something I just learned, please go ahead! I have no substantial opinion on naming, but Eff/Aff seems ok, Aff is cool :-)

**Comment by darkf** [comment]
To clarify, does this mean PureScript will no longer have extensible / algebraic effects? Who thought this was a good idea? 😕

**Comment by kRITZCREEK** [comment]
@darkf PureScript will still have algebraic effects in the `purescript-run` library. Our current Eff implementation does not allow you to specify interpreters for effects, the effect row is purely a phantom type and does not allow introspection.

**Comment by darkf** [comment]
@kRITZCREEK Fair enough, but why not keep the phantom row type? It's rather useful to demarcate effects, even if it's not entirely safe. I'll take a look at `purescript-run` (but is it going to mesh well with third party libraries?)

**Comment by kRITZCREEK** [comment]
@darkf Check https://github.com/purescript/purescript-eff/issues/25 and see if that answer your question.

**Comment by darkf** [comment]
@kRITZCREEK Thanks for the summary. I see the point now, but I still philosophically disagree with an all-encompassing IO monad... As a beginner (at least coming from Haskell) I found Eff easy to use and nicer than IO, and it lets me read (and write) what categories effects certain code will use.

Will Purescript retain a tagged Eff monad, or will it be left to packages like `purescript-run`? (I'm not sure if it's been decided yet, there was a lot of discussion on that issue.)

**Comment by kRITZCREEK** [comment]
The optimizer changes for `Effect` are in. `Eff` continues to be optimized for now as well as the `Eff` based `ST`. We should also look into optimizing the new standalone `ST`, but hopefully we can do a better job than the current hacky `Eff` `ST` optimizations with that.

@hdgarrood I assume we'll also need an instance for `Effect` for `psci`? Would that go into the `psci-support` repo or into the compiler?

**Comment by LiamGoodacre** [comment]
It'd be added to this instance chain https://github.com/LiamGoodacre/purescript-psci-support/blob/59ebfb83097629530249bba267384857d90d9638/src/PSCI/Support.purs right?

**Comment by garyb** [comment]
:tada:
