### ISSUE TITLE
Checking the modification times might slow incremental builds down

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#3087]
This is something I noticed with @garyb lately. The compiler spends a significant amount of time between startup and printing the first progress messages and I initially suspected the parser. However that time is severely reduced when I previously cleared the output directory.

I'm now suspecting that checking the modification times for externs files might be the culprit (This is on windows, I still need to check it on Linux).

**Comment by garyb** [comment]
For context, we're talking >10 seconds before receiving any output on SlamData.

**Comment by paf31** [comment]
Are you sure it's not parsing the externs files?

**Comment by kRITZCREEK** [comment]
@paf31 Yes, because I do that in psc-ide and it takes < 500ms for all of SlamData's modules.

**Comment by kRITZCREEK** [comment]
I fixed this in #3270
