### ISSUE TITLE
Clashing module loaders in FFI modules?

### ISSUE THREAD

**Issue by maxhillaert** [purescript/purescript#3090]
Hi,

I'm sold on Purescript and am bringing it into the company I work for.  I started contributing writing bindings for JS libraries I'm using in my projects.   

Unfortunately , my first one has hit a snag, I don't know how to resolve and would like to have some advice with.   I'm writing bindings for the microsoft monaco code editor.  It uses a way of module loading which I believe is AMD, and it doesn't seem to play nicely with FFI module definitions.  It clashes with the require mechanism of FFI modules.

What this means is that I had to resort to having a manual Script link for the monaco editor , set a global variable for require , before loading the PureScript generated build.js.

```html
<script src="/monaco-editor/min/vs/loader.js"></script>
<script>
	var monacoRequire = require
</script>
<script src="build.js"></script>
```

And then in the FFI:

```javascript
exports.createImpl = function(options) {
    return function(el) {
        return new Promise(function(resolve, reject) {
            monacoRequire.config({ paths: { 'vs': '/monaco-editor/min/vs' }});
            monacoRequire(['vs/editor/editor.main'], function() {
            var editor = monaco.editor.create(el, options);
            resolve(editor);
            });
        });
    };
};
```

I really dislike this, but I haven't gotten enough experience with the world of JS Module loader systems to know if and how it can be resolved.  I would really appreciate a tip with this from the veterans.

The code base is here for your reference
[https://github.com/maxhillaert/purescript-monaco](https://github.com/maxhillaert/purescript-monaco)

**Comment by hdgarrood** [comment]
Have you tried using `pulp build --to` with options like `--skip-entry-point` and `--main` to expose the relevant parts of your purescript code to js code? Generally if you use a bundling tool to bundle up your JS instead of using the compiler output directly it should avoid these kinds of issues.

**Comment by paf31** [comment]
Maybe you could pass the Monaco object in as a function argument if you don't like the AMD vs. CommonJS problem. It's not ideal but it would defer the decision to the point where you imported the PureScript code.

In any case, I don't think this is an issue for the compiler since we don't plan to support AMD directly.

**Comment by paf31** [comment]
Closing as this is not a compiler issue, but let's discuss it here if you still have questions.

**Comment by paf31** [comment]
Closing as this is not a compiler issue, but let's discuss it here if you still have questions.
