### ISSUE TITLE
"unspecified imports" warnings regarding Prelude inconsistent (on-and-off)

### ISSUE THREAD

**Issue by metaleap** [purescript/purescript#3092]
Running `pulp build` (11.0.2, purs 0.11.6, assuming it's about `purs` not `pulp` for now) on a project whose `./src/Ohai` contains the following simple module `Greet.purs` will warn `in module Ohai.Greet:` both that `Module Ohai.Howdy has unspecified imports` and `Module Prelude has unspecified imports`:

    module Ohai.Greet where
    import Prelude
    import Ohai.Howdy
    
    greet :: String -> String
    greet name =
    	hola <> ", " <> name <> "!"

Now with a slight tweak:

    module Ohai.Greet where
    import Prelude
    import Ohai.Howdy as Hi
    
    greet :: String -> String
    greet name =
    	Hi.hola <> ", " <> name <> "!"

now, both warnings don't come up --- even though nothing was done with regards to `Prelude`.

I suppose the bug here is either that the `Prelude` warning was never supposed to show up in scenario 1, **or** that it's supposed to *still* show up in scenario 2 but goes missing.

Can highly confound a newcomer =)

**Comment by paf31** [comment]
This is expected behavior. You can have at most one open import in a module without a warning. Otherwise you will get a warning for every open import. Open means not qualified and without explicit imported named listed.

**Comment by metaleap** [comment]
Ah sorry, didn't see that (not immediately intuitive) notion mentioned at all in https://github.com/purescript/documentation/blob/master/language/Modules.md  =)
