### ISSUE TITLE
Empty lines between comment lines 

### ISSUE THREAD

**Issue by metaleap** [purescript/purescript#3096]
Given PureScript's spirit of "generate readable JS that one can put into a JS codebase or hand off to other JS developers", having an extra empty line for each comment line hurts readability and may impair further tool-driven doc processing/rendering:

![screenshot from 2017-09-27 11-24-26](https://user-images.githubusercontent.com/22109/30906013-c6254012-a376-11e7-8039-6153b0317ef7.png)

Note `purescript-prelude`s original `Data/Semigroup.purs` doesn't have these, so seems like a bug

**Comment by LiamGoodacre** [comment]
I haven't checked, but could this be a line ending issue?

**Comment by metaleap** [comment]
I thought these only happen on Windows  =)

**Comment by metaleap** [comment]
One thing I can tell right now is it occurs at some point *after* the CoreImp AST has been fully formed (I'm `--dump`ing it), so somewhere in the transformation from coreimp AST to textual JS-source

**Comment by natefaubion** [comment]
It's probably because the printer inserts newlines when the comments probably already have newlines. https://github.com/purescript/purescript/blob/master/src/Language/PureScript/CodeGen/JS/Printer.hs#L126
