### ISSUE TITLE
Wrong 0.11.6 link on release page?

### ISSUE THREAD

**Issue by pkamenarsky** [purescript/purescript#3105]
Downloading [this](https://github.com/purescript/purescript/releases/download/v0.11.6/macos.tar.gz) file and running `psc --version` prints `0.11.4`.

EDIT: same goes for the `0.11.5` MacOS package.

**Comment by pkamenarsky** [comment]
My bad, didn't realise those are scripts calling the already installed binary on the global path.

**Comment by natefaubion** [comment]
`psc` in particular is a script. The binary was renamed to `purs` and the scripts were provided for compatibility.
