### ISSUE TITLE
Allow infix type aliases to be used non-infix in parens

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3107]
This works:
```
import Data.Tuple (Tuple)

foreign import data Exists2 :: (Type -> Type -> Type) -> Type

type X = Exists2 Tuple
```

But this does not compile (parsing error):
```
import Data.Tuple.Nested (type (/\))

type X = Exists2 /\
```

**Comment by kRITZCREEK** [comment]
Since we don't have operator sections like Haskell at the value level either, I'd wouldn't expect that to work. The only thing I could see (which doesn't work either) is `type X = (/\) Exists`, but that just seems strange.

**Comment by LiamGoodacre** [comment]
The `type X = Exists2 (/\)` should work but doesn't.
Consider that `type X = Exists2 (->)` does.

**Comment by LiamGoodacre** [comment]
Smaller example:

```purescript
type X = (->) -- works
type Y = (/\) -- fails
```

**Comment by paf31** [comment]
`(->)` is a special case in the parser right now. I don't think this should be called a `bug`, it's more of a feature request.

**Comment by natefaubion** [comment]
I think this can be upgraded to a bug. The parser accepts this, but it now fails with an internal error in the typechecker, because I think the operator desugaring does not handle this case for types.
