### ISSUE TITLE
Feature request: Mixin syntax for row type aliases

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3112]
As I've been doing more and more with variant/run, I've found myself really wanting some sort of syntax for mixins in rows. Right now the way to construct mixins is by taking the tail as an argument:

```purescript
type Mixin1 r =
  ( foo :: Foo
  , bar :: Bar
  | r
  )

type Mixin2 r =
  ( baz :: Baz
  | r
  )

type MyRecord r = Record (Mixin1 (Mixin2 r))

type MyVariant = Variant (Mixin1 (Mixin2 ()))

type WithSTATE s r  = (state :: FProxy (State s) | r)
type WithREADER a r = (reader :: FProxy (Reader a) | r)
type WithEXCEPT e r = (except :: FProxy (Except e) | r)

myProgram :: forall r. Run (WithSTATE Int (WithREADER Config (WithEXCEPT String r))) Unit
```

The right associative bracketing is particularly annoying, and any non-trivial mixins make this impenetrable. I'd like to propose we implement a desugaring step for rows which expands type aliases for _closed_ row sets.

```purescript
type Mixin1 =
  ( foo :: Foo
  , bar :: Bar
  )

type Mixin2 =
  ( baz :: Baz
  )

type MyRecord r = { Mixin1, Mixin2 | r }

type MyVariant = Variant (Mixin1, Mixin2)

type STATE s  = (state :: FProxy (State s))
type READER a = (reader :: FProxy (Reader a))
type EXCEPT e = (except :: FProxy (Except e))

myProgram :: forall r. Run (STATE Int, READER Config, EXCEPT String | r) Unit
```

The rule is simply that we extend the row grammar to allow proper names and type applications as members. During type alias desugaring we pass over rows and attempt to expand these applications/names. If these terms are not a type alias or do not expand to a _closed_ row, then it results in an error. Otherwise they are trivially substituted.

**Comment by natefaubion** [comment]
Note: I'm _not_ proposing we add arbitrary nesting as permitted syntax, since I think there may be some ambiguities there.

```purescript
type MyRows = ((foo :: Foo, bar :: Bar), (baz :: Baz) | r)
```

But I think it works conceptually, since rows are associative, that they allow arbitrary nesting of closed rows, and they just get flattened to a list.

**Comment by natefaubion** [comment]
An alternative is to desugar into the tail passing form:

```purescript
type Mixin1 r =
  ( foo :: Foo
  , bar :: Bar
  | r
  )

type Mixin2 r =
  ( baz :: Baz
  | r
  )

type MyRecord r = { Mixin1, Mixin2 | r }

type MyVariant = Variant (Mixin1, Mixin2)

type STATE s  r = (state :: FProxy (State s) | r)
type READER a r = (reader :: FProxy (Reader a) | r)
type EXCEPT e r = (except :: FProxy (Except e) | r)

myProgram :: forall r. Run (STATE Int, READER Config, EXCEPT String | r) Unit
```
```
type MyRecord r = Record (Mixin1 (Mixin2 r))
type MyVariant = Variant (Mixin1 (Mixin2 ()))
myProgram :: forall r. Run (STATE Int (READER Config (EXCEPT String r))) Unit
```

I think this is a more complicated tranformation, but it introduces no other semantics for rows. It just captures the syntactic tail of the row set.

**Comment by paf31** [comment]
I don't think this should be done as syntactic sugar. The term former `(x, y)` doesn't have a meaning except for when `x` is a closed row, or a synonym for a closed row. This means we need to follow synonyms, possibly across modules, to even decide if something is a well-formed expression.

If we had some form of infix type application, we wouldn't need this:

```purescript
type A r = ( foo :: Int | r )
type B r = ( bar :: String | r )
type C r = ( baz :: Char | r )

-- Suppose you could apply types using an infix operator like $
type Test = A $ B $ C ()
```

**Comment by paf31** [comment]
I see that your second suggestion is closer to the infix idea, but I'd rather have a separate syntax for this sort of union-as-type-application, since

- overloading always makes for worse parse errors
- it only works if the synonyms are written correctly, so I think the syntax should emphasize type application over row union.

**Comment by natefaubion** [comment]
> overloading always makes for worse parse errors

What is overloaded here wrt parsing? There is no backtracking since it requires a proper name, which isn't allowed as a label.

> it only works if the synonyms are written correctly, so I think the syntax should emphasize type application over row union.

This is the disadvantage of the second solution, yes. It's possible to write `Foo r = (foo :: Bar)` where the argument is never used and things get swallowed.

What makes this nice is that it works with existing record syntax as well.

**Comment by natefaubion** [comment]
> This is the disadvantage of the second solution, yes. It's possible to write Foo r = (foo :: Bar) where the argument is never used and things get swallowed.

It's possible to do the same with type application as well.

**Comment by natefaubion** [comment]
> I don't think this should be done as syntactic sugar. The term former (x, y) doesn't have a meaning except for when x is a closed row, or a synonym for a closed row. This means we need to follow synonyms, possibly across modules, to even decide if something is a well-formed expression.

I don't follow this. If this is done as part of desugaring of synonyms, why do we need this extra information? Isn't synonym desugaring eager?

**Comment by natefaubion** [comment]
A type application operator would have to be built-in special reserved syntax, right? We can't write a type application operator in user-land.

**Comment by paf31** [comment]
> What is overloaded here wrt parsing?

Parens are already overloaded, but now a proper name might refer to a regular synonym or one of these new synonyms. Note that they are new for the purposes of desugaring, even if their meaning as types is the same.

The point is that desugaring is always syntax-directed, but this is not.

**Comment by paf31** [comment]
One more thing: I don't think `(x, y)` is the best choice of syntax anyway, since it's used for tuples in Haskell and other languages.

**Comment by natefaubion** [comment]
> Parens are already overloaded, but now a proper name might refer to a regular synonym or one of these new synonyms. Note that they are new for the purposes of desugaring, even if their meaning as types is the same.

They aren't new synonyms because the synonyms are useful on their own regardless of their usage in row syntax. I like the first solution because `(Mixin)` does not have to be parsed as rows, whereas with the second you'd need `(Mixin ())` or `(Mixin,)` to close it.

> The point is that desugaring is always syntax-directed, but this is not.

Both cases are still purely syntactic substitutions.

**Comment by natefaubion** [comment]
> Both cases are still purely syntactic substitutions.

At least if you consider type synonyms to be syntactic substitutions, which is how they behave.

**Comment by paf31** [comment]
I don't think we should consider it to be syntax directed. It's not a local transformation - it uses information which is scattered over multiple modules. Consider the other syntactic sugar, which is purely local, based on only the syntax surrounding the expression.

**Comment by joneshf** [comment]
> A type application operator would have to be built-in special reserved syntax, right? We can't write a type application operator in user-land.

I think we can.

```PureScript
module Main where

data Foo = Foo
data Bar = Bar
data Baz = Baz

type Mixin1 r =
  ( foo :: Foo
  , bar :: Bar
  | r
  )

type Mixin2 r =
  ( baz :: Baz
  | r
  )

type MyRecord r = Record (Mixin1 (Mixin2 r))

x :: { foo :: Foo, bar :: Bar, baz :: Baz }
x = { foo: Foo, bar: Bar, baz: Baz }

myRecord :: MyRecord ()
myRecord = x

-- Define a synonym and kind it explicitly.
type Mixin (f :: # Type -> # Type) (g :: # Type -> # Type) (r :: # Type) = f (g r)

-- Dunno what the fixity should be.
infix 0 type Mixin as +

-- Then, we can build an equivalent formulation to the nested one.
type MyRecord' r = Record ((Mixin1 + Mixin2) r)

-- And it appears to work.
myRecord' :: MyRecord' ()
myRecord' = x

-- We can even clean it up a bit with another synonym.
type Ap (f :: # Type -> # Type) (r :: # Type) = f r

-- Again, dunno what the fixity should be.
infix 0 type Ap as \

type MyRecord'' r = Record (Mixin1 + Mixin2 \ r)

-- It also appears to work.
myRecord'' :: MyRecord'' ()
myRecord'' = x

-- Can also give a little sugar to mixin record definitions
type Record' (f :: # Type -> # Type) (r :: # Type) = Record (f r)

type MyRecord''' r = Record' (Mixin1 + Mixin2) r

myRecord''' :: MyRecord''' ()
myRecord''' = x

-- Or use it directly.
myRecord'''' :: Record' (Mixin1 + Mixin2) ()
myRecord'''' = x
```

**Comment by joneshf** [comment]
I guess looking at the case of 3+ is more interesting, which also seems to work:

```PureScript
module Main where

data Foo = Foo
data Bar = Bar
data Baz = Baz
data Qux = Qux
data Cor = Cor

type Mixin1 r =
  ( foo :: Foo
  | r
  )

type Mixin2 r =
  ( baz :: Baz
  | r
  )

type Mixin3 r =
  ( bar :: Bar
  | r
  )
  
type Mixin4 r =
  ( qux :: Qux
  | r
  )

type Mixin5 r =
  ( cor :: Cor
  | r
  )

type MyRecord r = Record (Mixin1 (Mixin2 (Mixin3 (Mixin4 (Mixin5 r)))))

x :: { foo :: Foo, bar :: Bar, baz :: Baz, qux :: Qux, cor :: Cor }
x = { foo: Foo, bar: Bar, baz: Baz, qux: Qux, cor: Cor }

myRecord :: MyRecord ()
myRecord = x

-- Define a synonym and kind it explicitly.
type Mixin (f :: # Type -> # Type) (g :: # Type -> # Type) (r :: # Type) = f (g r)

-- Dunno what the fixity should be.
infix 0 type Mixin as +

-- Then, we can build an equivalent formulation to the nested one.
type MyRecord' r = Record ((Mixin1 + Mixin2 + Mixin3 + Mixin4 + Mixin5) r)

-- And it appears to work.
myRecord' :: MyRecord' ()
myRecord' = x

-- We can even clean it up a bit with another synonym.
type Ap (f :: # Type -> # Type) (r :: # Type) = f r

-- Again, dunno what the fixity should be.
infix 0 type Ap as \

type MyRecord'' r = Record (Mixin1 + Mixin2 + Mixin3 + Mixin4 + Mixin5 \ r)

-- It also appears to work.
myRecord'' :: MyRecord'' ()
myRecord'' = x

-- Can also give a little sugar to mixin record definitions
type Record' (f :: # Type -> # Type) (r :: # Type) = Record (f r)

type MyRecord''' r = Record' (Mixin1 + Mixin2 + Mixin3 + Mixin4 + Mixin5) r

myRecord''' :: MyRecord''' ()
myRecord''' = x

myRecord'''' :: Record' (Mixin1 + Mixin2 + Mixin3 + Mixin4 + Mixin5) ()
myRecord'''' = x
```

But again, if that's not what you're looking for, that's not helpful :sweat_smile:.

**Comment by paf31** [comment]
Nice work! But aren't those partially applied type synonyms?

**Comment by natefaubion** [comment]
@joneshf That will fail as soon as you have more than one argument for the synonym, unfortunately (like in my `-run` example for effects) because it would require partially applied type synonyms.

**Comment by joneshf** [comment]
This seems to type check:

```PureScript
module Main where

data Foo = Foo
data Bar = Bar
data Baz = Baz

type Mixin1 r =
  ( foo :: Foo
  | r
  )

type Mixin2 r =
  ( baz :: Baz
  | r
  )

type Mixin3 bar r =
  ( bar :: bar
  | r
  )

type MyRecord r = Record (Mixin1 (Mixin2 (Mixin3 Bar r)))

x :: { foo :: Foo, bar :: Bar, baz :: Baz }
x = { foo: Foo, bar: Bar, baz: Baz }

myRecord :: MyRecord ()
myRecord = x

-- Define a synonym and kind it explicitly.
type Mixin (f :: # Type -> # Type) (g :: # Type -> # Type) (r :: # Type) = f (g r)

-- Dunno what the fixity should be.
infix 0 type Mixin as +

-- Then, we can build an equivalent formulation to the nested one.
type MyRecord' r = Record ((Mixin1 + Mixin2 + Mixin3 Bar) r)

-- And it appears to work.
myRecord' :: MyRecord' ()
myRecord' = x

-- We can even clean it up a bit with another synonym.
type Ap (f :: # Type -> # Type) (r :: # Type) = f r

-- Again, dunno what the fixity should be.
infix 0 type Ap as \

type MyRecord'' r = Record (Mixin1 + Mixin2 + Mixin3 Bar \ r)

-- It also appears to work.
myRecord'' :: MyRecord'' ()
myRecord'' = x

-- Can also give a little sugar to mixin record definitions
type Record' (f :: # Type -> # Type) (r :: # Type) = Record (f r)

type MyRecord''' r = Record' (Mixin1 + Mixin2 + Mixin3 Bar) r

myRecord''' :: MyRecord''' ()
myRecord''' = x

myRecord'''' :: Record' (Mixin1 + Mixin2 + Mixin3 Bar) ()
myRecord'''' = x
```

http://try.purescript.org/?session=7f440086-49bc-66e0-a87d-982d0ec5e6de&backend=core&gist=bb47e174384bc1fdcf55a1a758828095

Tried with different combinations as well. Maybe I'm misunderstanding where it would break.

**Comment by paf31** [comment]
I think because they get desugared top-down, everything actually _is_ fully applied when it gets replaced, but not syntactically.

Seems like something worth documenting ...

**Comment by natefaubion** [comment]
This is really interesting! For my use cases, this seems to get me mostly there (modulo minor syntax ergonomics).  If this is a "feature", then I'm OK with closing this.

**Comment by natefaubion** [comment]
@joneshf I think the compose is less useful than just application because you _will_ get partially applied synonym errors if you try to lift it out into another synonym. I'm happy with this though: http://try.purescript.org/?session=556bf0bb-2c14-2712-07a4-b1b48bbd820b&backend=core&gist=2c7013a683a8c9e2226229b389f121a4
