### ISSUE TITLE
Feaure Request: Labeled Arguments

### ISSUE THREAD

**Issue by freddi301** [purescript/purescript#3113]
like in reasonml

**Comment by garyb** [comment]
That's pretty much incompatible with the `a -> b` curried representation of functions that PS has, unless you have some more detailed idea for the propsal?

You can also use just a record for a function if you want it to have named arguments:

``` purescript
area :: { width :: Number, height :: Number } -> Number
area { width, height } = Math.sqrt (width * width) (height * height)
```

It does mean you always have to use the names when applying the function though.

**Comment by paf31** [comment]
Please add more information to the issue so that we can assess if this is possible.

**Comment by freddi301** [comment]
I mean it literally, just emulate how it is done [here](https://reasonml.github.io/guide/language/function/#labeled-arguments).
Or provide a syntax sugar to do curried record composition in a structure where the original function is maintained and applied when arguments record is complete

**Comment by paf31** [comment]
> Or provide a syntax sugar to do curried record composition in a structure where the original function is maintained and applied when arguments record is complete

You could  almost certainly build that as a library though. No compiler support needed.
