### ISSUE TITLE
Core libraries work for 0.12.0

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3116]
- [ ] `eff` changes to remove effect rows
  - [ ] Changes to `refs`, `exceptions` and so on
- [ ] Reimplement `ST` in terms of `refs` as its own separate monad
- [x] `psci-support` changes for instance chains
- [ ] `typelevel-prelude` merges
- [ ] ~Remove kind-specific proxy types~
- [ ] Move `RowList` to PreludelPrim and add `Record` instances for `Show`, `Eq`, `Ord`, etc.
- [ ] Deprecate old generics and remove record support from `generics`
- [ ] updates to try purescript, demos, etc

EDIT (Liam) - proxy syntax was removed so we shouldn't remove kind-specific proxies, and `RowList` may be moved to `Prim` via #3179

Libraries:

- [x] [`purescript-arrays`](http://www.github.com/purescript/purescript-arrays)
- [x] [`purescript-assert`](http://www.github.com/purescript/purescript-assert)
- [x] [`purescript-bifunctors`](http://www.github.com/purescript/purescript-bifunctors)
- [x] [`purescript-catenable-lists`](http://www.github.com/purescript/purescript-catenable-lists)
- [x] [`purescript-console`](http://www.github.com/purescript/purescript-console)
- [x] [`purescript-const`](http://www.github.com/purescript/purescript-const)
- [x] [`purescript-contravariant`](http://www.github.com/purescript/purescript-contravariant)
- [x] [`purescript-control`](http://www.github.com/purescript/purescript-control)
- [ ] [`purescript-datetime`](http://www.github.com/purescript/purescript-datetime)
- [x] [`purescript-distributive`](http://www.github.com/purescript/purescript-distributive)
- [x] [`purescript-effect`](http://www.github.com/purescript/purescript-effect)
- [x] [`purescript-either`](http://www.github.com/purescript/purescript-either)
- [x] [`purescript-enums`](http://www.github.com/purescript/purescript-enums)
- [x] [`purescript-exceptions`](http://www.github.com/purescript/purescript-exceptions)
- [x] [`purescript-exists`](http://www.github.com/purescript/purescript-exists)
- [x] [`purescript-foldable-traversable`](http://www.github.com/purescript/purescript-foldable-traversable)
- [x] [`purescript-foreign`](http://www.github.com/purescript/purescript-foreign)
- [x] [`purescript-free`](http://www.github.com/purescript/purescript-free)
- [x] [`purescript-functions`](http://www.github.com/purescript/purescript-functions)
- [x] [`purescript-functors`](http://www.github.com/purescript/purescript-functors)
- [x] [`purescript-gen`](http://www.github.com/purescript/purescript-gen)
- [ ] [`purescript-generics-rep`](http://www.github.com/purescript/purescript-generics-rep)
- [x] [`purescript-globals`](http://www.github.com/purescript/purescript-globals)
- [x] [`purescript-identity`](http://www.github.com/purescript/purescript-identity)
- [x] [`purescript-integers`](http://www.github.com/purescript/purescript-integers)
- [x] [`purescript-invariant`](http://www.github.com/purescript/purescript-invariant)
- [x] [`purescript-lazy`](http://www.github.com/purescript/purescript-lazy)
- [x] [`purescript-lcg`](http://www.github.com/purescript/purescript-lcg)
- [x] [`purescript-lists`](http://www.github.com/purescript/purescript-lists)
- [x] [`purescript-math`](http://www.github.com/purescript/purescript-math)
- [x] [`purescript-maybe`](http://www.github.com/purescript/purescript-maybe)
- [x] [`purescript-minibench`](http://www.github.com/purescript/purescript-minibench)
- [x] [`purescript-newtype`](http://www.github.com/purescript/purescript-newtype)
- [x] [`purescript-nonempty`](http://www.github.com/purescript/purescript-nonempty)
- [x] [`purescript-orders`](http://www.github.com/purescript/purescript-orders)
- [x] [`purescript-parallel`](http://www.github.com/purescript/purescript-parallel)
- [x] [`purescript-partial`](http://www.github.com/purescript/purescript-partial)
- [ ] [`purescript-prelude`](http://www.github.com/purescript/purescript-prelude)
- [x] [`purescript-profunctor`](http://www.github.com/purescript/purescript-profunctor)
- [x] [`purescript-proxy`](http://www.github.com/purescript/purescript-proxy)
- [x] [`purescript-psci-support`](http://www.github.com/purescript/purescript-psci-support)
- [ ] [`purescript-quickcheck`](http://www.github.com/purescript/purescript-quickcheck)
- [x] [`purescript-random`](http://www.github.com/purescript/purescript-random)
- [x] [`purescript-record`](http://www.github.com/purescript/purescript-record)
- [x] [`purescript-refs`](http://www.github.com/purescript/purescript-refs)
- [x] [`purescript-semirings`](http://www.github.com/purescript/purescript-semirings)
- [x] [`purescript-st`](http://www.github.com/purescript/purescript-st)
- [x] [`purescript-strings`](http://www.github.com/purescript/purescript-strings)
- [x] [`purescript-tailrec`](http://www.github.com/purescript/purescript-tailrec)
- [x] [`purescript-transformers`](http://www.github.com/purescript/purescript-transformers)
- [x] [`purescript-tuples`](http://www.github.com/purescript/purescript-tuples)
- [x] [`purescript-type-equality`](http://www.github.com/purescript/purescript-type-equality)
- [ ] [`purescript-typelevel-prelude`](http://www.github.com/purescript/purescript-typelevel-prelude)
- [x] [`purescript-unfoldable`](http://www.github.com/purescript/purescript-unfoldable)
- [x] [`purescript-unsafe-coerce`](http://www.github.com/purescript/purescript-unsafe-coerce)
- [x] [`purescript-validation`](http://www.github.com/purescript/purescript-validation)

**Comment by joneshf** [comment]
I call dibs on the st as ref one!

**Comment by joneshf** [comment]
Uh, actually, what's the goal of the st as ref one?

1. Are we looking to remove FFI bits ala https://github.com/purescript/purescript-st/issues/4?
    So, keep mostly the same signatures, but use `-refs` machinery to accomplish it.
1. Are we looking to remove the ST effect altogether ala https://github.com/purescript/purescript-st/issues/8?
1. Something else?

**Comment by paf31** [comment]
I was just thinking it would be good to build `ST` in terms of the new `Eff` and `unsafeCoerce`, so that it's one less things for new backends to have to port. The effect will go away and we'll have a dedicated `ST` monad instead.

**Comment by paf31** [comment]
> The effect will go away and we'll have a dedicated ST monad instead.

It does mean we won't be able to interleave certain things as easily. I do like being able to mix `RANDOM` and `ST` for example :(

**Comment by natefaubion** [comment]
Does it make sense to keep ST indexed, but with a closed sum of effects?

**Comment by natefaubion** [comment]
Oh, why do you need ST if you are interleaving with "impure" effects? If everything is unindexed, then you can just use ref.

**Comment by paf31** [comment]
Well, I'm not sure if we want to allow any set of effects in `ST`. It's not clear to me which are safe and which aren't unfortunately. I'm not even sure if `RANDOM` is safe, I just find it useful.

**Comment by paf31** [comment]
> If everything is unindexed, then you can just use ref.

Good point :)

**Comment by hdgarrood** [comment]
Having read #2903, I'm wondering: should all automatically-solved empty classes go into submodules of `Prim`? In particular, would it make sense to move any of the following move into `Prim`?

* `RowToList`
* `ListToRow`
* `AppendSymbol`
* `CompareSymbol`

**Comment by gabejohnson** [comment]
If someone merges https://github.com/purescript/purescript-eff/pull/27 I'd be happy to do some of the monkey work to get the core libs in line as well as `-dom`.

**Comment by hdgarrood** [comment]
Thanks for the offer @gabejohnson! I think it would be best to wait until we're a little bit closer towards having made all the compiler changes we want to make for 0.12 first.

**Comment by hdgarrood** [comment]
Also, `unsafePartialBecause` has been deprecated since v1.2.1, published 13 June; shall we bump `purescript-partial` up to v2.0.0 and remove it when we do all these other changes as well?

**Comment by hdgarrood** [comment]
One more thing I'd like to do since we're breaking things: remove the (non-law-abiding) `Semiring` instance for `Either`; see https://github.com/purescript/purescript-either/issues/34.

**Comment by anilanar** [comment]
It would be great to have a double checklist (one checkbox for in progress, another for done) of all core libraries + important libraries in the first post, similar to how it was done for 0.11.0 release. Wonder if there's a tool to topologically sort bower dependency graph so that we can go from top to bottom.

After compiler changes are finalized, list of breaking changes would make another checklist similar to the current one.

**Comment by garyb** [comment]
I have some code that builds the toposorted list of core libraries, since it's usually me who does the janitorial work of updating and releasing everything :wink:

It will be a little different this time since part of the breaking changes with typelevel prelude etc. might change the ordering.

**Comment by joneshf** [comment]
@garyb can we automate that away as part of #3185?

**Comment by hdgarrood** [comment]
@garyb I was thinking it might be nice for it to not have to be you every time; do you think you could maybe put that code up on github somewhere? if it's a bit messy I could go through and clean it up and add comments and things, and then that would probably be a decent way of familiarising myself with it.

**Comment by garyb** [comment]
@joneshf maybe, it'd need to be an interactive kinda thing though, as it's not just an entirely straightforward case of bumping & releasing each thing in turn, since we want to make any pending breaking changes to each of the libraries as we go. I did intend to automate this a long time ago, but every time it comes around I think "ah whatever" and just do it mostly manually again :smile:

@hdgarrood sure, I'll throw the bits I have together in a gist.

**Comment by kRITZCREEK** [comment]
I've created https://github.com/purescript/purescript-effect <- a non-effectrow version of purescript-eff. How should we go about `purescript-st`? I'd suggest we break `purescript-st` and make a dedicated `ST` type and create a `purescript-st-eff` in contrib in case people want to continue using it. If noone wants to I'm fine with just droppping it.

**Comment by hdgarrood** [comment]
I think we should just drop the current version of ST, and let someone else resurrect it if they want to use it; it should just be a case of checking out an earlier tag and going from there, so it’s not as if anything is lost.

**Comment by paf31** [comment]
I think `ST` in `Eff` is actually a bit dodgy, since it lets you mutate vars in an async callback, for example. So I'm on board for just moving it into its own monad and only interpreting it in `Effect`.

**Comment by hdgarrood** [comment]
Presumably we can close this now?
