### ISSUE TITLE
An internal error occurred during compilation: "missing type for data constructor MyDataConstructor in findTypeForDctor"

### ISSUE THREAD

**Issue by theunixman** [purescript/purescript#3118]
Hey hey, so, at the moment I'm deep in the midst of writing a demo, but this does keep popping up. I'm working on a minimal reproducible case, but thought I'd at least start a ticket to track it in case someone else has spotted it as well.

```
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-0.11.6-Aycu5A5gUJk77UghJXgS0T:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/Linter/Imports.hs:331:22 in purescript-0.11.6-Aycu5A5gUJk77UghJXgS0T:Language.PureScript.Linter.Imports
purs: thread blocked indefinitely in an MVar operation
```

**Comment by misandrist** [comment]
So as it turns out this is caused by importing a module from itself. Which, as one might imagine, isn't quite necessarily the best idea. I'll write up a short test for this at some point soon hopefully.

**Comment by misandrist** [comment]
I did find another bug where after fixing this, I wasn't defining the type, so that wasn't a valid test. However, I defined the type, and it came up with regular PureScript errors instead of internal errors, so I do believe that this internal error was caused by a self-import.

**Comment by LiamGoodacre** [comment]
Related to https://github.com/purescript/purescript/issues/3079

**Comment by misandrist** [comment]
@paf31 @LiamGoodacre yep, that's definitely the issue, thanks!
