### ISSUE TITLE
Won't Install for Ubuntu

### ISSUE THREAD

**Issue by tuxagon** [purescript/purescript#3122]
Hello! I have been trying to install purescript for the past couple days and I've even tried it on different versions of Ubuntu (17.04 and 17.10). Every time I attempt to install, I get the following error

```
$ sudo npm install -g purescript
/usr/bin/purs -> /usr/lib/node_modules/purescript/bin/purs.js

> purescript@0.11.6 postinstall /usr/lib/node_modules/purescript
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/lib/node_modules/purescript/vendor'
  ⚠ pre-build test failed
  ℹ compiling from source
  ✖ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/purescript/ea275dc8-157d-4050-bd71-c28a893106cb'
+ purescript@0.11.6
added 296 packages in 10.774s
```

Version Info
- os: Ubuntu 17.04/17.10
- npm: 5.4.2

**Comment by fix-fix** [comment]
It looks like a bug in npm https://github.com/npm/npm/issues/17268.

Does the workaround command `sudo npm install -g purescript --unsafe-perm=true` from [this comment](https://github.com/npm/npm/issues/17268#issuecomment-310167614) work for you?

**Comment by LiamGoodacre** [comment]
It might make more sense for this issue to be on https://github.com/purescript-contrib/node-purescript-bin

**Comment by tuxagon** [comment]
@fix-fix That actually worked. I was not aware of `--unsafe-perm=true`. Thanks!

@LiamGoodacre That would make more sense. I didn't think to look for the package repo.

**Comment by neatville** [comment]
Adding `--unsafe-perm=true` made it work for me as well, on Ubuntu Mate. When trying that on Antergos, it still can't install PureScript... here's an example of the problems that come up in the output. 
```

  ⚠ The `/usr/lib/node_modules/purescript/vendor/purs` binary doesn't seem to work correctly
  ⚠ pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup --allow-different-user && stack install --allow-different-user --local-bin-path /usr/lib/node_modules/purescript/vendor
Command failed: stack install --allow-different-user --local-bin-path /usr/lib/node_modules/purescript/vendor
```

**Comment by kRITZCREEK** [comment]
Arch is just broken for Haskell right now. You can try to install the ncurses-5-compat package from the AUR but the last time I tried to get a working Haskell environment on Arch I wasted 2 days...

**Comment by stevematdavies** [comment]
Ubuntu 19
`npm i -g purescript `

> heck if 'stack' command is available
>   stack --allow-different-user --numeric-version
>   ┌──────────────────────────────────────────────────────────────────────────┐
>   │                                                                          │
>   │ 'stack' command is required for building PureScript from source, but     │
>   │ it's not found in your PATH. Make sure you have installed Stack and try  │
>   │ again.                                                                   │
>   │                                                                          │
>   │ → https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux     │
>   │              

Cant find any help on this and the link in the error is useless

**Comment by garyb** [comment]
What do you mean? It tells you how to install `stack`, and the thing that is missing to make `purescript` installable via `npm` in this case is `stack`.

**Comment by stevematdavies** [comment]
Isn't Stack for Haskell? 

Following the purescript documentation, for getting started, Stack is not mentioned at all.

**Comment by hdgarrood** [comment]
@stevematdavies you need to install libncurses, see INSTALL.md

**Comment by stevematdavies** [comment]
Thanks @hdgarrood but no go,

ibncurses5-dev is already the newest version (6.1+20181013-2ubuntu2)

still the same issue

**Comment by hdgarrood** [comment]
The error is a bit misleading though. The real problem is the error while loading shared libraries; even if you did have stack installed and had succeeded in building the compiler from source yourself, the resulting binary would have failed with the same error. I’m not sure how this could be improved though (other than perhaps by statically linking libtinfo.) /cc @shinnn

**Comment by stevematdavies** [comment]
@hdgarrood Yes, the issue now, its all becoming a little too involved just to get purescript up and running.

**Comment by hdgarrood** [comment]
Ah; I guess Ubuntu 19.04 must have updated to the version of libtinfo in their repos to version 6. Odd that the package is still called `libncurses-5-dev` though. I’m not sure what to do then. Perhaps there is some discussion on the haskeline repo, I’ll have a look. Incidentally stack is required for building the compiler from source because the compiler is written in Haskell.

**Comment by stevematdavies** [comment]
@hdgarrood ahh I see. I have Haskell up and running just fine, and Cabal, so I'm not to keen to add more like Stack. I could give it a go, but as I mentioned before, I'm not attempting to build from source. I had ps running OK on Mac, so certainly its an Ubuntu lib issue?

**Comment by hdgarrood** [comment]
The npm package attempts to build the compiler from source if a prebuilt binary isn’t available or doesn’t work; this is by design. I think building from source is possibly your best bet here, actually: the Haskell bindings to libncurses have a configure script which hopefully could handle this.

**Comment by stevematdavies** [comment]
I may give this a bit of a go when I have time. Thank you very much for the input

**Comment by shinnn** [comment]
Though I'm /cc-ed here, this kind of confusion should be resolved by the compiler itself:

- When there is a missing shared library, `purs` should catch the error and avoid totally crashing the process, show a useful message to encourage installing the shared library, and exit the process with a specific exit code.
  - Then the npm installer can skip the fallback step and just stop the installation earlier when `purs --version` exits with the code.
- Or, can't you make `stack install` automatically download required libraries to a temporary directory and statically link it to a built binary? It's very straightforward for end users. I'm not sure it's technically feasible, though.

**Comment by hdgarrood** [comment]
Well on reflection I think I was wrong before: I think that if a prebuilt binary fails because of a missing shared library, it doesn’t necessarily mean that compiling from source will fail in the same way, because the Haskell terminfo package includes a configure script which is presumably intended to handle these sorts of things. I definitely wouldn’t want to try to download the library automatically.

**Comment by shinnn** [comment]
> the Haskell terminfo package includes a configure script which is presumably intended to handle these sorts of things

Glad to hear that.

Then, I can't find any room for improvement on error messages.

> ```
> ↓ Fallback: building from source
>```

>```
> ✖ Check if 'stack' command is available
>   stack --allow-different-user --numeric-version
> ```

> ```
> 'stack' command is required for building PureScript from source,
> but it's not found in your PATH. Make sure you have installed Stack and try again
> → https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux
> ```

However, an actual user "cant find any help on this and the link in the error is useless". Hmm.

@stevematdavies (or others) Do you have any suggestion? How could the installer better encourage you to install the `stack`command in this case?

**Comment by shinnn** [comment]
ping @stevematdavies

**Comment by waynevanson** [comment]
I'm running void linux, so the npm install downloads a binary (which we cool with). I have no experience in haskell, so I have no idea what `stack` even is.

`stack` is the recommended tools, like the haskell compiler (ghc) + friends: https://docs.haskellstack.org/en/stable/README/

This is how to install the stack:
https://docs.haskellstack.org/en/stable/install_and_upgrade/#installupgrade

**Comment by waynevanson** [comment]
To add to others, I believe the error is "useless" because it doesn't direct the user where to go next.
I had no idea what stack was, so that was another bit of learning curve.

**Comment by matil019** [comment]
I think the name `stack` is too general to understand unless you already know what it is. Perhaps a wording like `'stack' command, from the Haskell build tool`, `'stack' command provided by Haskell Stack` or `Make sure you have installed Stack, the Haskell build tool` helps a bit? Yes the URL contains the word `haskell` but I don't think it's a very kind way to introduce a tool of another programming language.

**Comment by hdgarrood** [comment]
If you are having trouble getting the compiler installed, please open a new issue on the purescript/npm-installer repo; this issue is regarding an unrelated problem anyway and is not related to stack. I really don’t see any issue with the current error message since it does tell you that it needs the ‘stack’ command as well as linking you to its website. You can just follow the link and poke around on the website if you’re curious.

**Comment by waynevanson** [comment]
I didn't see a link to the site on my messages, but perhaps i glazed over it.
