### ISSUE TITLE
Broken pattern matching of parameters of algebraic types

### ISSUE THREAD

**Issue by totycro** [purescript/purescript#3123]
In the following example, `f` will be compiled to JS code which performs the actual pattern matching, whereas for `g`, the compiler will optimize the pattern matching away assuming it to be true always. The compiler also emits a warning that the case `_` in `g` is unreachable.

This occurs with purescript 0.11.6.

Purescript code:
```
newtype ItemId = ItemId Int
newtype Item = Item { id :: ItemId }
                
f :: Item -> Boolean       
f (Item item)  =
  case item of
       {id : (ItemId 4)} -> true
       _ -> false

g :: Item -> Int -> Boolean
g (Item item) i =
  case item of
       {id : (ItemId i)} -> true
       _ -> false
```

Resulting JS code:
```
var f = function (v) {
    if (v.id === 4) {
        return true;
    };
    return false;
};
var g = function (v) {
    return function (i) {
        return true;
    };
};
```

However I would have expected that the resulting code looks  something like this:
```
var g_expected = function (v) {
    return function (i) {
        if (v.id === i) {
            return true;
        };
        return false;
    };
};
```

**Comment by natefaubion** [comment]
This is expected. Pattern matching doesn't assume an `Eq` constraint. In the second example, the inner `i` introduces a shadowed binding, it won't compare for equality.

**Comment by Pauan** [comment]
This syntax:

```purescript
case item of
     {id : (ItemId i)} -> true
     _ -> false
```

Means that it will bind a *new* variable `i` to the value of the `ItemId`. It does **not** do any checks for equality or anything like that.

If you want to check for equality you must use the [`==`](https://pursuit.purescript.org/packages/purescript-prelude/3.1.0/docs/Data.Eq#v:(==)) function, like this:

```purescript
g :: Item -> Int -> Boolean
g (Item item) i1 =
  case item of
       {id : (ItemId i2)} -> i1 == i2
       _ -> false
```

**Comment by LiamGoodacre** [comment]
Closing as this is expected behaviour with the semantics as described above.

In addition to what @Pauan said: if you require the equality to be part of the pattern you could use a pattern guard `  {id : (IdentId i2)} | i1 == i2 -> ...`.

**Comment by Pauan** [comment]
It's the same way with JavaScript:

```javascript
var g = function (i) {
    var i = v.id;
    return true;
};
```

Obviously the above code doesn't do any equality checking, it binds a *new* variable `i`

If you want to do equality checking, you have to explicitly use `===`. It's the same way in PureScript

**Comment by michaelficarra** [comment]
@Pauan Funny story there, but that's actually just an assignment to the one and only `i` binding declared in the parameter list. JavaScript...
