### ISSUE TITLE
Functional dependencies behavior

### ISSUE THREAD

**Issue by juselius** [purescript/purescript#3130]
The following code compiles without errors with purs 0.11.6:
```purescript
class Foo a b | a -> b 
instance a :: Foo Int Int 
instance b :: Foo Int Number 
```
Is this the expected/correct behavior under PureScript? Compiling the same code with GHC gives
```
Foo.hs:7:10: error:
    Functional dependencies conflict between instance declarations:
      instance Foo Int Int -- Defined at Foo.hs:7:10
      instance Foo Int Double -- Defined at Foo.hs:9:10
```
which is what I would normally expect.

As a side note, adding implementation to the PureScript version results in a warning about overlapping instances, but no errors.
```purescript
class Foo a b | a -> b where
  foo :: a -> b

instance a :: Foo Int Int where
  foo _ = 42

instance b :: Foo Int Number where
  foo _ = 42.0
```

**Comment by paf31** [comment]
I believe this will give an overlapping instances error (at the site of the second definition) in 0.12.0. I'm closing this since it's effectively fixed already, but thanks for the report.
