### ISSUE TITLE
Fail, TypeConcat, & TypeString shouldn't end in kind Symbol

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#3134]
The `TypeConcat` and `TypeString` types aren't really symbols.  We should really build up an expression in some error message kind instead.  Perhaps:

```purescript
foreign import kind ErrorMessage
foreign import data Lit :: Symbol -> ErrorMessage
foreign import data TypeConcat :: ErrorMessage -> ErrorMessage -> ErrorMessage
foreign import data TypeString :: Type -> ErrorMessage
class Fail (error :: ErrorMessage)
```

**Comment by paf31** [comment]
I like it. While we're at it we could add constructors for vertical concatenation and indentation perhaps.

**Comment by XertroV** [comment]
I agree with this. Was trying to do something like this earlier:

```purescript
class ValidSymbol (s :: Symbol)

instance failBadSymbol 
    :: Fail "Tags cannot start with 'z'" 
    => ValidSymbol (TypeConcat "z" a)
instance goodSymbol :: ValidSymbol s

class ValidSymbol s <= V2 s
instance shouldBeBadButIsnt :: V2 "zA"
instance badInst :: V2 (TypeConcat "z" "Test")
```

Which I now realise doesn't work; the last line does trigger the `Fail` though.

Aside: would it be useful to build up `kind Symbol` like we build up Peano numbers at the type level? Or maybe a type level list? (Maybe I'm getting a bit carried away here)

**Comment by hdgarrood** [comment]
This seems relatively uncontroversial, so shall we move it to the 1.0 milestone?

**Comment by LiamGoodacre** [comment]
Related to the rearrangement of prim, I'm thinking about something like:

```purescript
module Prim.Type.Data.Doc where
foreign import kind Doc
foreign import data Text :: Symbol -> Doc
foreign import data Quote :: Type -> Doc
foreign import data Beside :: Doc -> Doc -> Doc
foreign import data Atop :: Doc -> Doc -> Doc

module Prim.Compiler.Raise where
import Prim.Type.Data.Doc (kind Doc)
class Fail (doc :: Doc)
class Warn (doc :: Doc)
```

Any thoughts?

Relates to https://github.com/purescript/purescript/pull/3176 and https://github.com/purescript/purescript/issues/2903

**Comment by hdgarrood** [comment]
:+1:  although the module names seem a bit excessive; how about `Prim.Raise` and `Prim.Doc`?

**Comment by LiamGoodacre** [comment]
Yeah I wasn't sure about that, I was following what we currently do in typelevel-prelude for typelevel data structures, e.g: `Type.Data.Boolean`.  I do like `Prim.Raise`.
