### ISSUE TITLE
purs docs doesn't complete when using new proxy syntax

### ISSUE THREAD

**Issue by sloosch** [purescript/purescript#3135]
Using purs 0.11.6 [development build; commit: 71fc308a53bf89678c1e1d4a242cc01561d556d1] and trying to create the documentation (purs docs) when having the new proxy syntax doesn't seem to complete. Even though it uses up to 500% CPU.

Minimal Example:
````purescript
foo :: forall a. @a -> Int
foo _ = 42
````

Removing the proxy and it finishes just fine.

**Comment by paf31** [comment]
Are you using the code on master?

**Comment by paf31** [comment]
This seems quite likely actually, there is a separate pretty printer in the `Docs` modules which might not have been updated.
