### ISSUE TITLE
Interop with functions that take "options" objects

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#314]
Something that crops up quite a lot when using the FFI is dealing with functions that take options objects. We talked a bit about it before...

At the moment the best way I've come up with for dealing with these is doing something like this:

``` haskell
type Options = { optA :: Number, optB :: Number, optC :: Number }
options = { optA: 1, optB: 2, optC: 3 }

foreign import whatever :: Options -> {}

main = whatever (options { optA = 42, optC = 9000 })
```

In a magical world where everything is ideal, it'd be great to be able to do something like this instead:

``` haskell
type Options = { optA :: Number | optB :: Number | optC :: Number }

main = whatever { optA: 42, optC: 9000 }
```

So basically you could have a row which defines a closed set of allowed possibilities rather than an open set with a `(... | a)` kind of thing - it could also be useful in situations where you want to restrict the allowed effects (I realise you can already do this, but it seems more explicit this way).

I'm not sure if it's really possible to make rows do that though. Just throwing it out there, there's probably all kinds of problems it I'm not thinking of.

**Comment by paf31** [comment]
I guess we have library support for this now, so I'll close it.
