### ISSUE TITLE
Class constraints type checking is lazy

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3152]
The following module will type check:
```
module Empty where

class Empty x

x :: Empty Int => Int
x = 1
```

The type checker will refuse such a module only if `x` is unified with some other type, e.g. when adding:
```
y :: Int
y = x
```

I think that constraint checking should not be lazy, but strict.  This seems like a cosmetic change, since this will not change the scope of programs that runs correctly.

**Comment by LiamGoodacre** [comment]
That doesn't look like what is going on here.  You're type is saying that under the constraint of `Empty Int`, then you can get an `Int`.  It is up to the caller to provide this evidence.  I.e, `Empty Int` is an input to the function `x`.

**Comment by LiamGoodacre** [comment]
Closing as this is expected behaviour, but please reopen if you believe I have misunderstood your issue.  Thanks.

**Comment by coot** [comment]
I see the point.  This would also change the behaviour of custom warning and errors different, which is not desirable.
