### ISSUE TITLE
Determining the location of FFI files by module name

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript#3162]
When interpreting `corefn.json` and encountering foreign declarations, I haven't been able to find a way to determine the location of the file which contains them.

For example, the module `Control.Monad.Eff.Console` has a foreign import for `log`.

If using `psc-package`, the location of this function (for the JS backend) is `.psc-package/[set]/console/[version]/src/Control/Monad/Eff/Console.js`.

If using Bower, it would be `bower_components/purescript-console/src/Control/Monad/Eff/Console.js`.

I've noticed that this path is used throughout the `externs.json` file but it seems unreliable and unintuitive to go digging around in there for this purpose.

Does anyone see an issue with providing a map from module name to location?

For example:

```json
{
  "Control.Monad.Eff.Console": ".psc-package/psc-0.11.7/console/v3.0.0/src/Control/Monad/Eff/"
}
```

I suppose this could be part of `corefn.json` but I think a separate file (e.g. `modules.json`) would also be OK.

**Comment by gabejohnson** [comment]
I could be wrong, but I thought @coot added this in #3049

**Comment by paulyoung** [comment]
I'll take a look at that, thanks. I might be looking at the output from an older version.

**Comment by gabejohnson** [comment]
I don't think it's in 0.11.7, just in master.

**Comment by kRITZCREEK** [comment]
https://github.com/purescript/purescript/pull/3049/files#diff-a2ab4e2d0bbc6ce4f71402a351c6d889R113

From the `modulePath` you can recover the FFI file by looking at the path with a `.js` extension instead. That's the same algorithm used to detect FFI files in the compiler.

**Comment by paf31** [comment]
What @kRITZCREEK said is right.

**Comment by paulyoung** [comment]
Unfortunately the `corefn.json` format has changed drastically, so I'll need to spend some time supporting that first.

I thought I heard some rumors of another 0.11.x release. It seems a bit odd that this would be part of that as opposed to 0.12

**Comment by matthewleon** [comment]
> I thought I heard some rumors of another 0.11.x release. It seems a bit odd that this would be part of that as opposed to 0.12

I posted an issue asking for people's opinions: https://github.com/purescript/purescript/issues/3225

This seems like another potentially good reason not to do it.

**Comment by paulyoung** [comment]
Although I think it would be a bit strange to make the change in a patch release, I'm in favor of getting the new format into a release sooner rather than later.

I've already done most of the work to support it: https://github.com/paulyoung/purescript-corefn/pull/42
