### ISSUE TITLE
Existentials are working incorrectly with `flip`

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#3165]
Minimal example 
```purescript
thisOneWorks = runExists (const 1) (mkExists Nothing)
thisOneDoesnt = flip runExists (mkExists Nothing) (const 1)
```

**Comment by natefaubion** [comment]
Isn't this just the usual impredicativity (`runST $ do`)?

**Comment by paf31** [comment]
Correct. In fact, `flip runExists` is enough to cause an escaped skolem error.

**Comment by paf31** [comment]
The solution is to give a type to `flip runExists` explicitly, or to not use `flip`.

**Comment by joneshf** [comment]
Alternatively, use `flap`: https://pursuit.purescript.org/packages/purescript-prelude/3.1.0/docs/Data.Functor#v:flap

http://try.purescript.org/?session=a3663f2c-2f3b-270e-6017-e0da131930ce&backend=core&gist=e5b8cf9c752c5f954ff2b6d4717be13d

**Comment by natefaubion** [comment]
Crazy. Any idea why this gets around the issue?

**Comment by joneshf** [comment]
I don't really understand impredicativity well enough to give a definitive answer. My guess, however, is that it's not trying to instantiate the variables when you apply `flap` in the same. It may very well be a bug for all I know.

**Comment by joneshf** [comment]
Here's a GHCi session
```Haskell
λ: :set -XRankNTypes 
λ: let flap f x = fmap (\g -> g x) f
λ: :t flap
flap :: Functor f => f (t -> b) -> t -> f b
λ: data Exists f = Exists (forall a. f a)
λ: let runExists :: forall f r. (forall a. f a -> r) -> Exists f -> r; runExists f (Exists x) = f x
λ: :t flip runExists

<interactive>:1:6: error:
    • Couldn't match type ‘a’ with ‘forall a1. f a1 -> c’
      ‘a’ is a rigid type variable bound by
        the inferred type of it :: Exists f -> a -> c at <interactive>:1:1
      Expected type: a -> Exists f -> c
        Actual type: (forall a. f a -> c) -> Exists f -> c
    • In the first argument of ‘flip’, namely ‘runExists’
      In the expression: flip runExists
λ: :t flap runExists

<interactive>:1:6: error:
    • Couldn't match type ‘f’ with ‘(->) (forall a. f1 a -> b)’
      ‘f’ is a rigid type variable bound by
        the inferred type of it :: Exists f1 -> f b at <interactive>:1:1
      Expected type: f (Exists f1 -> b)
        Actual type: (forall a. f1 a -> b) -> Exists f1 -> b
    • In the first argument of ‘flap’, namely ‘runExists’
      In the expression: flap runExists
```

Seems like a bug then?

**Comment by paf31** [comment]
I don't think matching GHC was ever expected behavior, the type checking approaches are very different.

**Comment by joneshf** [comment]
Does that mean `flap` is the move here? Or should `flap` not work either?

**Comment by paf31** [comment]
No, I think `flap` works "by accident", but that shouldn't be considered a bug. I think the recommended solution should be to provide a type signature in the right place.
