### ISSUE TITLE
purs fails to run on Cygwin

### ISSUE THREAD

**Issue by cebaa** [purescript/purescript#3166]
Installing a fresh purescript:

```
$ npm install -g purescript
```

(current version `purescript@0.11.7`) leaves the following `purs` script:

```
"$basedir/node_modules/purescript/purs.bin"   "$@"
exit $?
```

When run:

```
$ purs
/cygdrive/c/node-6.11.1/purs: line 1: /node_modules/purescript/purs.bin: No such file or directory
```

Changing to something like this (similar to e.g. `pulp` script) seems to solve the issue:

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"$basedir/node_modules/purescript/purs.bin" "$@"
exit $?
```

**Comment by paf31** [comment]
This doesn't seem like a compiler issue specifically, but a Node (package?) issue. Please open an issue on the `node-purescript-bin` repo instead of here. Thanks!

**Comment by cebaa** [comment]
Done! https://github.com/purescript-contrib/node-purescript-bin/issues/54
