### ISSUE TITLE
Handing off ownership of various projects

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3170]
In light of my recent ["resignation"](https://twitter.com/paf31/status/941745900426215424), I need to find people to take over ownership of some of my projects. I mentioned this on Slack and we decided to move the conversation here.

Here is a list of all of the things I currently manage in any sense. This might also be a good time to assign official maintainers for some things whose ownership is currently shared.

- Mostly managed by me
  - Try PureScript
  - `psc-package`
  - The `package-sets` repo
  - Making releases and writing release notes (@hdgarrood plus one other?)
- Stuff I help out with
  - `purescript-node` repositories
  - `purescript-contrib` "oversight" (making sure repos are maintained to at least some basic level)
  - The purescript.org website
- Compiler code I "own" (for want of a better word)
  - Type checker
- Contrib libraries which need new owners
  - `canvas` (@hdgarrood)
  - `drawing` (@hdgarrood)
  - `string-parsers` (@MiracleBlue)
  - `nullable` (@hdgarrood)
  - `freet` (@natefaubion)
  - `coroutines` (@natefaubion)
  - `handlebars` (@craigdallimore)
  - `parsing` (@spicydonuts)
  - `profunctor-lenses`
  - `foreign-lens`
  - `sammy`
- Infrastructure (I'm happy to keep doing this for a while, and it seems simplest that way anyway, but I'll list it here so it's spelled out anyway)
  - Linode server (Try PS, Pursuit, news.purescript.org)
  - *.purescript.org domains
  - SSL certificates

**Comment by MiracleBlue** [comment]
I'll put my hand up to maintain string-parsers, I quite like it and would love to help keep it going :)

**Comment by MiracleBlue** [comment]
(I am nyancat on slack btw)

**Comment by craigdallimore** [comment]
Likewise `handlebars` (decoy on slack)

**Comment by joncfoo** [comment]
I mentioned this on a few issues and in Slack - I'd be happy to help with the infrastructure and tooling around PureScript.  I'm quite new to the community and my [relevant] experience is mostly limited to Haskell and Nix (PureScript forthcoming).  As such I'd be interested in helping with the following:

- managing and maintaining servers and services
- contributing/maintaining:
    - pursuit
    - trypurescript
        - psc-package (insomuch as it relates to trypurescript but happy to expand the scope)
        - package-sets (^ likewise)

**Comment by hdgarrood** [comment]
I'd like to help more with planning releases and writing release notes, but I don't think I'm able to devote enough time to it to take responsibility for it.

I'm happy to take `canvas`, `nullable`, and `drawing` (those are the ones I think I'm sufficiently familiar with). I'm also reasonably familiar with the REPL code in the compiler, and I think a few other people are too, so I don't think we need to worry about that.

**Comment by natefaubion** [comment]
Happy to take freet and coroutines.

**Comment by craigdallimore** [comment]
Putting my hand up for `handlebars`

**Comment by paf31** [comment]
Thanks everyone! I've started listing potential new owners next to projects above.

**Comment by matthewleon** [comment]
I'm happy to lend a significant hand on `psc-package`, but would feel a bit nervous about "ownership." Not sure what the right approach there is.

**Comment by paluh** [comment]
I want to help with `package-sets` maintenance (merging, migrating to psc-0.12 etc.). I'm not able to take any more responsibilities at this moment :-(

**Comment by MiracleBlue** [comment]
I would also put my hand up to maintain psc-package itself.

**Comment by spicydonuts** [comment]
Maybe put me down for `parsing`?  I'm no expert but I really enjoy what I've done so far and want to learn more.

**Comment by justinwoo** [comment]
I guess I've already been trying to make psc-package easier to use in terms of features and docs/blogging, so I'll do some of the work too.

**Comment by MonoidMusician** [comment]
I would love to help out with `profunctor-lenses` ... why not `foreign-lens` too?

**Comment by parsonsmatt** [comment]
Sign me up for the type checker. :smile:
