### ISSUE TITLE
Avoid NoInstanceFound errors in REPL where possible

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3172]
Currently, in the REPL, it's not too difficult to come across well-typed expressions which could be printed when given type annotations, but not without:

```
> Left 0
Error found:
in module $PSCI
at <internal> line 0, column 0 - line 0, column 0

  No type class instance was found for
                          
    Prelude.Show t4
                          
  The instance head contains unknown type variables. Consider adding a type annotation.
```

This happens because, to have a `Show (Either a b)` instance, we need both `Show a` and `Show b` (even though we are only going to use `Show a` in this case). Because the type of `Left 0` is `forall b. Either Int b`, we can't magic up a `Show b` instance, and so we get the above error. Ideally, this would happen instead:

```
> Left 0
Left 0
```

One way of achieving this could be to do something a little bit like what ghci does, which is to "default" the type variable `b` to be `Unit`. The general approach I'm proposing is:

1. Bind what's entered in the prompt to `it` and attempt to infer the type of `it`. If this causes a type error, fail as normal. Otherwise:
2. See if the expression `eval it` compiles successfully.
   * If it does, run it as normal.
   * If not, try specialising the type of `it` by replacing all the type variables with `Unit`, and retry `eval it`.
     * If this now compiles successfully, run it.
     * Otherwise, fail with the original error raised from `eval it`.

Questions/issues:

* Instead of replacing all type variables in the type of `it` with `Unit`, can we be a little cleverer and only replace those for which we need `Show` instances?
* What do we do if `Unit` is not available? Should we require that `PSCI.Support` re-exports `Unit`?

**Comment by paf31** [comment]
GHCi does type class defaulting based on the constraints you have on unsolved type variables. Replacing everything with `Unit` seems a bit heavy handed and arbitrary to me.

Also, compare:

```
> Data.Semiring.zero
unit
```

with

```
> fromInteger 0
0
```

So maybe `Unit` isn't always the best choice.

Also, I'd suggest that anything involving backtracking is going to make the behavior of the REPL harder to understand. What we have now is very basic, but very simple and easy to understand. There are a number of workarounds for the issues listed above - the simplest is to just add a (partial) type annotation.

**Comment by hdgarrood** [comment]
You're right, this is a bit half-baked. It occurred to me that it might be a bit heavy handed but I didn't realise that it would be so unhelpful in cases like `zero`.

I think I'll close this for now and maybe revisit this after I've researched how GHCi does it a bit more.
