### ISSUE TITLE
naming an fn parameter __unused breaks codegen

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3187]
Admittedly a very, very tiny edge case but still, it feels morally wrong:

```purescript
abuseUnused :: forall a. a -> a
abuseUnused __unused = __unused
```

```javascript
var abuseUnused = function () {
    return __unused;
};
```

The culprit here is the `removeUnusedArg` optimization, which bases its functionality off the name of the argument.

Potential easy solution: change the constant to an illegal name?

**Comment by matthewleon** [comment]
If this is desired behavior, at the least it should be documented somewhere. But I have trouble imagining what people would want this for.

**Comment by hdgarrood** [comment]
Yeah, this definitely seems wrong. Changing the constant to an illegal name sounds like it could work.

**Comment by paf31** [comment]
I think we should change the name to something the user can't type, or better still, remove the hack by creating a new type of name for this purpose.

**Comment by matthewleon** [comment]
> better still, remove the hack by creating a new type of name for this purpose.

Yeah, I am leaning toward something like this.

**Comment by nwolverson** [comment]
I'm not sure what I did but I managed to get typed hole suggestion to suggest `__unused` as an option recently...

**Comment by matthewleon** [comment]
@nwolverson if you are able to do that again at some point, would you mind creating an issue for it? I'd be curious to see what's happening.

**Comment by nwolverson** [comment]
I will do, I wasn't entirely clear what the case was because I couldn't reproduce it immediately afterwards, I think I noticed a `Partial` constraint
