### ISSUE TITLE
Add flag to disable Javascript backend

### ISSUE THREAD

**Issue by owickstrom** [purescript/purescript#3196]
I'm writing an alternative VimL backend for PureScript based on the CoreFn dump produced by `--dump-corefn`. That is, I haven't forked the compiler codebase. There are two things with the regular `purs compile` command that would be nice to disable:

* CommonJS module output
* Checking/inclusion of `<Module>.js` files (foreign definitions)

Specifically the latter is of interest, as I don't want to write foreign definitions for Vim-specific things for the JS backend.

At a high level, this might be considered "disabling the entire JS backend", I'd say, so I'm not sure what would be a good name for a flag to disable it. Perhaps `--no-codegen` or `--no-js-codegen`. Anyway, I could have a stab at this and provide a PR if this seems reasonable.

Thanks!

**Comment by natefaubion** [comment]
Maybe `--no-backend`?

**Comment by owickstrom** [comment]
@natefaubion Sounds good. And the result would be only `corefn.json` and `externs.json` in the output directory.

Should `--no-backend` implicitly add `--dump-corefn`, or perhaps exit with an error if `--dump-corefn` isn't provided?

**Comment by natefaubion** [comment]
I'd think that `--no-backend` on it's own would only write externs (which is useful if you just want to typecheck everything), while `--no-backend --dump-forefn` would write externs and corefn.

**Comment by paulyoung** [comment]
I brought this up in https://github.com/purescript/purescript/pull/3049#issuecomment-338505442 for the same reasons 👍

**Comment by LiamGoodacre** [comment]
This sounds good.  Specifically with @natefaubion's comment.
I'll mark this as approved.  Please continue to discuss any concerns that arise.

**Comment by hdgarrood** [comment]
@coot suggested in https://github.com/purescript/purescript/pull/3049#issuecomment-338507346:

> I think that `--dump-corefn` shouldn't generate javascript at all.

Is there ever a situation where you would want corefn as well as JS produced?

**Comment by hdgarrood** [comment]
Because if we are not able to come up with one I think we should just stop producing JS when --dump-corefn is supplied instead.

**Comment by garyb** [comment]
That seems sensible to me.

**Comment by paf31** [comment]
`purescript-derive-lenses` works on the generated core (I think it's one of only a few tools currently using corefn), but the original module is used too. It'd be a shame to have to compile a module twice IMO.

**Comment by gabejohnson** [comment]
So maybe a `--dump-all` which would output JS and CoreFn, (CoreImp too if something like #3117 happens)?

The `--dump-corefn` would just output...CoreFn but you wouldn't have to recompile for your use case @paf31.

Ideally, JS codegen would be a separate tool (or package at least).

**Comment by garyb** [comment]
Yet another option: some kind of `dump` / `codegen` parameter that when present specifies exactly what is going to be output? So if it's not specified we get the current output (equiv to `--codegen js`), but when it is present it does exactly what it says, so you could `--codegen corefn` or `--codegen js corefn coreimp` or whatever. Might be easier than trying to figure out a bunch of on/off flags?

**Comment by owickstrom** [comment]
Nice! Sorry for being so inactive in this discussion, I've not been in PureScript land at all lately. Glad to see the result anyway. :clap:
