### ISSUE TITLE
Don't warn about redundant import for qualified imports

### ISSUE THREAD

**Issue by adius** [purescript/purescript#3203]
```purescript
import Data.Color (Color)
import Data.Color as Color
```

This is not really redundant.
I want the Color type imported directly and the functions qualified.

Can we not show the error message for this case?
Or is there another way to achieve this?

**Comment by hdgarrood** [comment]
The error is only shown if either of the imports are not used; if you use both of those imports you won't get a warning. For example, the following produces no warnings:

```purescript
module Main where

import Data.Maybe (Maybe)
import Data.Maybe as Maybe

foo :: Maybe Int
foo = Maybe.Just 1
```

**Comment by adius** [comment]
Indeed. Don't know how I missed that.
Thanks for the help, and sorry for the noise 😅.

**Comment by hdgarrood** [comment]
No worries! :)
