### ISSUE TITLE
Warnings/errors without source spans

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#3208]
Aside from #1801 we have some warnings currently with no source spans at all:

- [x] `ShadowedName`
- [x] `UnusedTypeVar`
- [x] `UnnecessaryFFIModule`
- [x] `UnusedFFIImplementations`
- [x] `MissingFFIImplementations`
- [x] `ScopeConflict`
- [x] `ScopeShadowing`
- [x] `DuplicateModule`
- [x] `ExportConflict`
- [x] `IntOutOfRange`
- [x] `ExpectedWildcard`
- [x] `MissingClassMember`
- [ ] `PartiallyAppliedSynonym`?
- [x] `ErrorParsingFFIModule`
- [x] `KindsDoNotUnify` (#3275)

If there are any others you run into, please post them below! (Or edit them in here if you have permission).

**Comment by garyb** [comment]
`DuplicateModule` kinda has the same problem as `CycleInModules` in that we don't know which location is the cause of the issue. We could choose an arbitrary module and use the source span for that, but another alternative might be to raise an error for every module in the duplicates/cycle. Thoughts?

**Comment by hdgarrood** [comment]
I’m not sure about what makes sense from an implementation perspective, but from a UX perspective I think ideally there would be just one error for each module name which is used more than once, but have the error include a list of all the files which define a module of this name.

**Comment by hdgarrood** [comment]
I guess an appropriate source span would be the `module Foo` bit?

**Comment by garyb** [comment]
The module names are included in the error text (and paths in the case of duplicate modules), but we can't attach source spans to those errors in the unless we change positioned errors to have a `NonEmptyList` of source spans or something, along with then finding a way of expressing that so that editors/tools can make use of it.

And yeah, the module header(s) is the span I had in mind :)

**Comment by hdgarrood** [comment]
Oh, I didn’t realise all the paths are already included in the message text. Never mind then!

I think since we are doing that already it should be sufficient to pick an arbitrary one to use as the source span.

**Comment by garyb** [comment]
@kRITZCREEK had another idea too - we can perhaps include spans for everything in the error data, and have that available in the JSON as `additionalSpans` or something, but when we print a text error we just use the arbitrary one. 🙂

**Comment by Houndolon** [comment]
`MissingFFIImplementations` error is also missing source spans. I think it makes sense to report the locations of `foreign import someFunction ...` that lack the FFI implementation.

**Comment by rndnoise** [comment]
I think `PartiallyAppliedSynonym`, at least I don't see location info in the message on the console -- but I can't seem to produce a minimal example (the error only occurs in a different project).

**Comment by bklaric** [comment]
`ErrorParsingFFIModule` is also missing source spans. Encountered when trying to do `const { Pool } = require("pg")` with the following error message:

    [1/1 ErrorParsingFFIModule]

        Unable to parse foreign module:

        E:\something.js

        The module could not be parsed:

        LeftCurlyToken {tokenSpan = TokenPn 23 3 7, tokenComment = [WhiteSpace (TokenPn 22 3 6) " "]}

**Comment by nwolverson** [comment]
Simple `PartiallyAppliedSynonym` seems fine:

```[1/1 PartiallyAppliedSynonym] src/Main.purs:9:1

  9  type X = Foo Int
     ^^^^^^^^^^^^^^^^
  
  Type synonym Main.Foo is partially applied.
  Type synonyms must be applied to all of their type arguments.
  
  in type synonym X
```

**Comment by garyb** [comment]
The `PartiallyAppliedSynonym` case may have occurred in a binding group or data binding group, as I discovered that those errors were unpositioned when working on #3275.

I'm going to close this out now as the known reproducible cases are all covered now, and a "ensure errors and warnings have positions" check was added in the compiler tests, so we can add new tests easily if we find any more.
