### ISSUE TITLE
wildcard bindings should get optimized away

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3222]
Take the following:
```purescript
f :: Int -> Int
f _ = 0

i :: Int
i = f 1
```

It compiles to the following:

```purescript
var f = function (v) {
    return 0;
};
var i = f(1);
```

The parameter should ideally be optimized away to the following:

```purescript
var f = function () {
    return 0;
};
var i = f();
```

**Comment by hdgarrood** [comment]
I’d rather not - I’m not sure this is necessarily an optimisation; I imagine this is the sort of thing we should leave to the VM to worry about.

**Comment by garyb** [comment]
I thought that at first too, but given it also removes the argument when applying the function, it could well be - it depends if the argument is expensive to compute.

**Comment by hdgarrood** [comment]
Oh of course, yes. Looking again has made me realise though - we’ve always previously had predictable, simple codegen as a goal, and this proposal seems to go against that.

**Comment by matthewleon** [comment]
On the other hand, it seems so odd to me that when you're working with `Proxy`, for example, a meaningless lookup in the `Proxy` module has to actually happen. There are many cases where these wildcard bindings exist just to satisfy the typechecker, and it seems unfortunate to have more runtime cost than is necessary in those cases.

**Comment by matthewleon** [comment]
> we’ve always previously had predictable, simple codegen as a goal, and this proposal seems to go against that.

This is quite subjective, of course, but I do feel that while this proposal adds a small bit of complication to the codegen, it _is_ predictable.

**Comment by hdgarrood** [comment]
What I mean by ‘predictable’ here is that afaik it currently isn’t  necessary to look at anything other than types of things in any modules you’re importing to be able to predict what your code is going to look like; this would no longer be the case.

**Comment by matthewleon** [comment]
Ah, I see. I'm actually surprised that there are no other optimizations so far that break this property, but I certainly can't think of any...

And yet, this feels to me like a very reasonable optimization to make.

I suppose that breaking the "predictability" property just for this optimization would not be a popular choice. Is there any other reasonable way to do something like this?

**Comment by matthewleon** [comment]
I can't think of a smarter way to do this, so I'm closing. In those cases where there is a real, unfortunate, runtime cost due to the current behavior, there is probably generally going to be a way for the used to optimize their code manually.

**Comment by hdgarrood** [comment]
Yeah, I'm really not sure. My feelings on this proposal aren't any stronger than 'vague discomfort.' It does indeed seem like a veyr reasonable optimisation, as you say.
