### ISSUE TITLE
Observable TC39 proposal - async behaviour

### ISSUE THREAD

**Issue by fghibellini** [purescript/purescript#3229]
I apologise for posting this on this repository but it was the only way I could think of to address the correct people.

There's a [proposal to introduce Observables into JavaScript](https://github.com/tc39/proposal-observable/issues/179), I created an issue on it that I think would be best if reviewed by someone with a strong understanding of both functional programming and JavaScript.

I guess a this would in turn also affect this project as it would have to implement a new mechanism for handling Observables if they turned out to not be compatible with callbacks.

**Comment by hdgarrood** [comment]
This kind of query should go on the mailing list.
