### ISSUE TITLE
Relax orphan constraints

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#3233]
Take the modules of all type constructors that appear in non-determined instance arguments into account (instead of just those at the head) when detecting whether an instance would be an orphan.

For example, the following instance could be allowed to live in the same module as `Either`, but currently it must live with `Bind` or `Flip`:
```purescript
instance bindFlipEither :: Bind (Flip Either a) where
```

Taken from a slack discussion.  Although I've never wanted to do this, I don't believe it would cause any problems to do so.

**Comment by kevinbarabash** [comment]
I ran into the same issue when trying to do:
```
instance encodeNodeF :: Encode (Mu NodeF) where
```
I ended up copy/pasting the implementation of `Mu` into the implementation of `NodeF` as a workaround, but it's not ideal.

**Comment by hdgarrood** [comment]
Would Haskell consider that `Bind (Flip Either a)` instance an orphan if it were defined in the same module as `Either`?

**Comment by hdgarrood** [comment]
I think allowing this would cause problems. For example:
```purescript
module Tagged where
newtype Tagged t a = Tagged a
class IsTagged t where
  x :: Tagged t Int
```
```purescript
module Id where
import Tagged
data Id a = Id a
instance tagId :: IsTagged (Id a) where
  x = Tagged 0
```
```purescript
module X where
data X = X
instance tagX :: IsTagged (f X) where
  x = Tagged 1
```
The instance `tagX` would currently be rejected on the grounds that it is an orphan. If we drop that restriction, we can end up with a situation where there are multiple possible instances in scope:
```purescript
module Problem where
import Id
import X
oops :: Int
oops =
  let Tagged y = (x :: Tagged (Id X) Int)
  in y
```
Both of the above instances match the requested `IsTagged (Id X)` instance, so we don't know which one to pick.

**Comment by MonoidMusician** [comment]
We probably need a concrete head for the rule to be safe. We could probably say the head, and if the head is concrete any of its children recursively (i.e. while still under concrete heads), should be defined in the same module.

**Comment by natefaubion** [comment]
Would that mean adding instances is a breaking change?

**Comment by hdgarrood** [comment]
I think so, yeah, since I can’t add an instance `C (X a)` in the module which defines X without breaking downstream code which, say, defines a type Y along with an instance `C (X Y)`.

**Comment by natefaubion** [comment]
I personally don't think it's worth it then. You can't _not use_ instances like you can just not import a function.

**Comment by hdgarrood** [comment]
Yeah, I agree. This issue hasn’t generated a lot of interest in the time it’s been open either. Shall we close?

**Comment by garyb** [comment]
:+1: for close.
