### ISSUE TITLE
"Data declaration only has one constructor and value; consider using `newtype`"

### ISSUE THREAD

**Issue by i-am-tom** [purescript/purescript#3235]
Just an idea I had this morning: the compiler could report `data` declarations that _could_ be replaced with a `newtype`. There are a couple reasons why the user might _not_ want to do this  (a dependence on the underlying representation, for one), so I suspect it would be better suited to a lint warning (such as name shadowing).

What do people think? Happy to work on this if it would be useful :)

**Comment by matthewleon** [comment]
Is there actually any reason in PS to have a `Newtype`/`Data` separation like this? Couldn't such `Data`s just be treated as `Newtype`s? As I understand, in Haskell laziness allows you to have `bottom` behind `Data` without exploding, whereas `Newtype` does not. Is there any similar benefit in PS?

**Comment by garyb** [comment]
Using `newtype` guarantees you're going to get a `newtype` - without it you might accidentally introduce a new field and forget that would violate the optimisation, breaking code elsewhere that assumes the erased runtime representation (mainly an issue for FFI-related code / some types of coercion-optimisation).

**Comment by garyb** [comment]
(and newtype-derived instances)

**Comment by matthewleon** [comment]
> breaking code elsewhere that assumes the erased runtime representation (mainly an issue for FFI-related code / some types of coercion-optimisation).

Yeah, I thought of that after posting my comment. It's a bit unfortunate... In an ideal world, I would think that a post-FFI optimization tool could take care of this.

**Comment by hdgarrood** [comment]
It’s a nice idea but I’m personally not a fan; it’s not obvious enough to me that using data instead of newtype (where possible) is always the right thing to do, or at least not obvious enough to justify putting a check for  this in the compiler (imo). It also incurs a risk of trying to force beginners to understand the distinction before they really need to, i think.

**Comment by natefaubion** [comment]
This has not had any activity in a while, and the discussion is mixed. Should this be closed?

**Comment by hdgarrood** [comment]
Yes, I think so.
