### ISSUE TITLE
Ambiguous type check should take determined type arguments into account

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3238]
The type checker currently reports an ambiguous type ("...has type variables which are not mentioned in the body of the type") even when the only type variables not mentioned are determined by type class constraints. This probably shouldn't be considered ambiguous.

**Comment by zyla** [comment]
Here's a test case:


```purescript
module Main where

class C a

class FD a b | a -> b

fn1 :: forall a b. FD a b => C b => a -> String
fn1 _ = ""

fn2 x = fn1 x
```

Currently fails with:

```
Error found:
in module Main
at InferredFunDep.purs line 10, column 1 - line 10, column 13

  The inferred type
                                                  
    forall t2 t3. FD t3 t2 => C t2 => t3 -> String
                                                  
  has type variables which are not mentioned in the body of the type. Consider adding a type annotation.

in value declaration fn2
```

It compiles when the `C b` constraint is removed from `fn1`.

**Comment by masaeedu** [comment]
Just to dump my own use case here; I'm trying to write a function that appends two records, using a monoid to append shared fields. Leaving the rest of the code for the end, the salient type signature is:

```
class Append (r :: RowList) (s :: RowList) (t :: RowList) | r s -> t
-- ...

append ::
  forall r s t r' s' t'.
  RowToList r r' =>
  RowToList s s' =>
  Append r' s' t' =>
  ListToRow t' t =>
  { | r } -> { | s } -> { | t }
append = unsafeCoerce
```

when I apply this to two arguments, I get the correct inferred type, and everything is fine:

```
e = append { foo: "foo", bar: "bar" } { baz: 1, foo: "..." }
```

with the warning:

```
  No type declaration was provided for the top-level declaration of e.
  It is good practice to provide type declarations as a form of documentation.
  The inferred type of e was:

    { bar :: String
    , baz :: Int
    , foo :: String
    }


in value declaration e
```

But if I just drop the second argument, like so:

```
e = append { foo: "foo", bar: "bar" }
```

then I get the following error:

```
  The inferred type

    forall t79 t80 t82 t83 t87. RowToList t83 t80 => Lacks "bar" t80 t87 => AppendCase t87 "bar" String (Cons "foo" String Nil) t80 t79 => ListToRow t79 t82 => Record t83 -> Record t82

  has type variables which are not mentioned in the body of the type. Consider adding a type annotation.

in value declaration e
```

However, simply adding that type as an explicit annotation resolves the problem. Looking at the type more closely, all the type variables in the context are actually determined (via functional dependency) by the variables `t83` and `t82`, so if the type checker was smart enough and followed things backwards along the functional dependencies, it seems like it could discover that there is actually no ambiguity here.

For reference, here's the full code: https://gist.github.com/masaeedu/8567e7797b1e00fcd5c276620b7a00cf
