### ISSUE TITLE
Something like Warn for managing runtime dependencies

### ISSUE THREAD

**Issue by safareli** [purescript/purescript#3251]
Let's say we have special type class like Warn which allows to declare module and it's version, which  is needed to run some function.

``` purs
class NPMDeps (a :: # Symbol)
instance warnNPM :: Warn "npm.dependencies = [TODO generate staff from a]" => NPMDeps a
```

For example this is [FFI part](https://github.com/sharkdp/purescript-bigints/blob/master/src/Data/BigInt.js#L3-L29) of "big-integer" wrapper (by @sharkdp). as you can see only `fromBase'`, `fromInt` and `fromNumber` depend on `require("big-integer")`. And they are "imported" in purescript like this:

``` purs
foreign import fromBase' :: forall a. (a -> Maybe a) -> Maybe a -> Int -> String -> Maybe BigInt
foreign import fromInt :: Int -> BigInt
foreign import fromNumber :: Number -> BigInt
```

Instead if we have something like the `NPMDeps` class, we could do:

``` purs
type WithDeps a = NPMDeps ("big-integer" :: "1.2.x") => a

foreign import fromBase' :: forall a. WithDeps ((a -> Maybe a) -> Maybe a -> Int -> String -> Maybe BigInt)
foreign import fromInt :: WithDeps (Int -> BigInt)
foreign import fromNumber :: WithDeps (Number -> BigInt)
```

And during build, such "warnings" will be accumulated and used to make sure correct versions of deps are present in `{package,yarn, ... }.json`. 
I think we don't need this deps for such FII functions which invoke a method on already existing instances, as it means there is already the dependency in runtime. We need this "warnings" when the function explicitly depends on `require`.

Came up with this based on [from my recent tweets](https://twitter.com/safareli/status/967344782627561475)

**Comment by safareli** [comment]
I think it could be done with Just `Warn` class and special support for this warnings in purescript-ide (so in editor you don' get usual warnings for it), and in purescript-psa or some different lib on top of ps-psa. 

I think something like this will have huge benefits for app developers as you would have much better guaranties and information on what you depend on.  for example, if we have some lib which looks like this:

``` purs
foreign import foo :: NPMDeps ("foo" :: "1.x.x") => String -> String
foreign import bar :: NPMDeps ("bar" :: "2.x.x") => String -> String
```

And the app only uses bar you would get warning for module bar only so you would be sure that you can only install bar and app will work just fine.


I opened this issue here to get feedback on the idea, and possible implementation directions.

**Comment by LiamGoodacre** [comment]
Probably wouldn't want to add the constraint directly to the foreign imports - this would require an extra argument in the JS for the instance's empty dictionary.

**Comment by garyb** [comment]
Whatever it is we wouldn't want to bake any special support into the compiler either, as it's very JS-specific, and even npm specific too :)

**Comment by garyb** [comment]
No need to /cc us on issues either, we all get notified.

**Comment by safareli** [comment]
> Probably wouldn't want to add the constraint directly to the foreign imports - this would require an extra argument in the JS for the instance's empty dictionary.

good point! Also for such code I guess you would need separate file so so you have only one require in FFI code (otherwise I thinking web-pack or staff like this you might get error if dependency is not there).

> Whatever it is we wouldn't want to bake any special support into the compiler either, as it's very JS-specific, and even npm specific too :)

sure, as mentioned I opened it to get feedback on the idea.

if we name `NPMDeps` to something else like just `Deps` then it's not js or npm specific any more and it could be interpreted in some lib on top of ps-psa for example, and could be used for even different backends, in the same way as for npm.

**Comment by safareli** [comment]
the only special support might be needed in ps-psa and/or ps-ide (or instead actual ps-ide editor plugins)

**Comment by hdgarrood** [comment]
I'm not really a fan. In addition to what @garyb said, for this to be useful, we'd need to have a way of feeding information such as which npm dependencies are installed locally into the type checker, so that warnings aren't displayed when all of the required dependencies are actually there. To me, that sounds like it would be awkward to set up and delicate (especially given the diverse selection of purescript build tools which already exist). This job is better suited to a package manager, I think.

**Comment by hdgarrood** [comment]
Oh, perhaps I misunderstood; if your idea doesn't involve changes to the compiler, that's fine, but I think it should be discussed elsewhere. So, close this?

**Comment by kRITZCREEK** [comment]
I think there's probably something here, but it's going to need experimentation and a working prototype before we can really evaluate if we want to change the compiler to work around some rough edges. Until then I'm going to close this issue, and we can resume the discussion if we have something concrete to evaluate.
