### ISSUE TITLE
Local bindings (let, where) do not infer most general type

### ISSUE THREAD

**Issue by rndnoise** [purescript/purescript#3257]
This might be as designed, but I couldn't find documentation or issues (#1022 was closest). These examples fail to type check:

```purescript
f = Tuple (g "a") (g false) where g _ = 10
```

```purescript
f = let g _ = 10 in Tuple (g "a") (g false)
```

However, this example does type check:

```purescript
g _ = 10
f = Tuple (g "a") (g false)
```

**Comment by natefaubion** [comment]
For background on PS’s behavior https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tldi10-vytiniotis.pdf

**Comment by garyb** [comment]
Yeah, this is intentional - we were going to do it at one point, but decided against it in the end. The paper Nate linked has some of the reasons why. Another reason is doing so can introduce a decent amount of overhead in propagated class dictionaries.
