### ISSUE TITLE
"second level" value declarations are removed during purs bundle

### ISSUE THREAD

**Issue by safareli** [purescript/purescript#3259]
`src/Main.js`:
``` js
"use strict";

var baz = { "biz": true };

function gez(x) {
  return baz[x] || false;
};

exports.foo = gez;
```

`src/Main.purs`:
``` purs
module Main where

foreign import foo :: String -> Number
```

after `pulp build`, `output/Main/index.js`:
``` js
// Generated by purs version 0.11.6
"use strict";
var $foreign = require("./foreign");
module.exports = {
    foo: $foreign.foo
};
```

(`output/Main/foreign.js` is same as `src/Main.js`, as expected)

But `purs bundle "output/**/*.js" --module Main` outputs:
``` js
// Generated by purs bundle 0.11.7
var PS = {};
(function(exports) {
    "use strict";           

  function gez(x) {
    return baz[x] || false;
  };

  exports.foo = gez
})(PS["Main"] = PS["Main"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var $foreign = PS["Main"];
  exports["foo"] = $foreign.foo;
})(PS["Main"] = PS["Main"] || {});
```

Problem is there is no `var baz = { "biz": true };` any more I guess this is known bug but still opening with this small reproducible case.

I guess we might need to do a thing which determines that `gez` should be contained in output, recursively or something.

**Comment by hdgarrood** [comment]
I think #2290 and #3082 are the same issue. It is indeed useful to have a simple repro case though.

**Comment by hdgarrood** [comment]
I actually think we should do as little static analysis of JS code as we possibly can; if there's any doubt, the code should stay in. The onus should be on library authors to write their FFI code in such a way that the dead code elimination can safely eliminate everything which is uneeded, I think.

**Comment by safareli** [comment]
In that case rules of dead code elimination algorithm should be documented so it's well understood by users

**Comment by natefaubion** [comment]
I'm pretty sure the DCE on foreign modules is the same routine as that on normal PS modules, so it only really looks at forms generated by the compiler. I wonder if you can break code like your example in normal PS land by using Data.Record.

**Comment by safareli** [comment]
Just to note if I had  `exports.foo = function(x) { return gez(x) };` definition of `baz` is still lost. but `gez` is still present in bundled code.

**Comment by safareli** [comment]
@natefaubion I tried following,

`src/Lib.purs`:
``` purs
module Lib (foo) where

baz :: { t :: Boolean, f :: Boolean }
baz = { t: true, f: false }

gez :: Boolean -> Boolean
gez true = baz.t
gez false = baz.f

foo :: Boolean -> Boolean
foo x = gez x
```
`src/Main.purs`:
``` purs
module Main where

import Lib (foo)

t :: Boolean -> Boolean
t _ = foo true
```


and output of bundle is:
``` js
// Generated by purs bundle 0.11.7
var PS = {};
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var baz = {
      t: true, 
      f: false
  };
  var gez = function (v) {
      if (v) {
          return baz.t;
      };
      if (!v) {
          return baz.f;
      };
      throw new Error("Failed pattern match at Lib line 6, column 1 - line 6, column 26: " + [ v.constructor.name ]);
  };
  var foo = function (x) {
      return gez(x);
  };
  exports["foo"] = foo;
})(PS["Lib"] = PS["Lib"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var Lib = PS["Lib"];        
  var t = function (v) {
      return Lib.foo(true);
  };
  exports["t"] = t;
})(PS["Main"] = PS["Main"] || {});
```

Which is fine.

**Comment by safareli** [comment]
Now if you are using babel or some es6 -> es5 thing you can change such declarations to us `const` which bypasses dead code elimination, but it's "hacky".

**Comment by natefaubion** [comment]
Aff/AVar circumvents it by putting things that shouldn't be eliminated in an IIFE.

**Comment by safareli** [comment]
> I actually think we should do as little static analysis of JS code as we possibly can; if there's any doubt, the code should stay in. The onus should be on library authors to write their FFI code in such a way that the dead code elimination can safely eliminate everything which is uneeded, I think.

I agree that if it's not clear that a some declaration should be removed or not then it should not be removed as it's safer.

Would be nice if the issue is formalized so someone who is willing to fix it can have clear directions.
