### ISSUE TITLE
Idea: `RuntimeInitOnly` constraint

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#3260]
The name is weird, so open to suggestions on that. The idea is weird too probably.

Basically: we have some functions that are unsafe, throwing errors at runtime as a convenience way of constructing things like regex, or other values that are only otherwise allowed to be created by a partial smart constructor.

We could perhaps have a constraint on these functions that makes them error if they're ever used in a "dynamic" or "delayed" context, requiring them to be defined in such a way so that the app will immediately throw an error when the script is loaded, rather than potentially allowing their use in places that will blow up later.

I guess another option is we get super clever at writing type-level parsers for symbols so we can determine any property we might want of these values and reflect them safely, but to be honest I think that's even less realistic than this harebrained scheme.

**Comment by garyb** [comment]
@justinwoo suggested `InstaCrash` :smile:

**Comment by hdgarrood** [comment]
I think some kind of macro system, Template PureScript or something, would also address this. Possibly quite a bit more effort, but presumably there is at least plenty of existing research into macro systems..?

**Comment by garyb** [comment]
It depends a bit on what kind of macros we're talking about too. A templating/hygenic thing would probably not be enough, as it wouldn't be able to, say, look at a string and determine it is both non-empty and does not contain the `:` character. Or that it's a valid regex. Or at least, not without it being just as bad as our current symbol based options in that regard.

If we're talking about "interpret purescript at compile time and do whatever" it's more likely, but then you have issues of how to deal with the compiler running FFI code, etc. which is... tricky. :smile:

I suggested this as it seems like something fairly approachable in the near term, as it'd "just" be a case of checking whether these values are evaluated at definition-time. Even an extremely crude heuristic for that would be enough for an initial thing (used in a top-level definition, not under a lambda).

**Comment by hdgarrood** [comment]
Right, yeah. I guess what I'm saying is I'm not hugely keen; I think this is a bit too specific to deserve a language feature all of its own (whereas a macro system wouldn't be, even if it is a lot harder).

**Comment by paf31** [comment]
Why is it bad if such a thing fails at module load time?

**Comment by safareli** [comment]
So what if such unsafe functions take only values which are known compile time `SProxy` of some symbol instead of a String etc. this way we have guaranty that arguments are known compile time at least.

(In case of Regex for example we could weite some typelevel representation of `RegexFlags`):
``` purs
class UnsafeIsRegex (rg :: Symbol) (fg :: RegexFlag )where
  unsafeRegex :: forall rg fg. SProxy rg -> RegexFlagProxy fg -> Regex

instance (IsSymbol rg, IsRegexFlags fg) => UnsafeIsRegex rg fg where
  unsafeRegex _ _ = case regex (Symbol.reflectSymbol (SProxy :: SProxy s)) (reflectFlags ...) of
    Left x -> unsafeCrash $ "oops: " <> x
    Right regex -> regex
```

**Comment by garyb** [comment]
Like #3251, this was an interesting discussion but has served its purpose since we're not going to be acting on it in any obvious way for now. Thanks all!
