### ISSUE TITLE
Type match Error

### ISSUE THREAD

**Issue by bilalsp** [purescript/purescript#3261]
`first :: forall a. List a -> Maybe a`
`first Nil = Nothing   --Error in this line, why?`
`first (x:_) = Just x`

Could not match type
    Step
  with type
    List
while trying to match type Step t0
  with type List a1
while inferring the type of case $0 of
                              Nil -> Nothing
                              (Cons x _) -> Just x
in value declaration first

where a1 is a rigid type variable
      t0 is an unknown type

**Comment by bilalsp** [comment]
Anyone, can resolve this issue?

**Comment by hdgarrood** [comment]
Looks like you're mixing up lazy and strict lists, but this is not the place to ask these sorts of questions. Try Slack, stackoverflow, or the mailing list instead.
