### ISSUE TITLE
Excessive parser backtracking in lambda arguments

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3262]
http://try.purescript.org/?backend=core&gist=40b83a8631b49dfb1cc7584aaea0fb1d

```purescript
module Main where

import Prelude

foo = id \a ->
  let
    bar =
      let
        baz =
          { a: 42, -- Extra comma
          , b: 12
          }
      in baz
  in bar
```
```
  Unable to parse module:
  unexpected ->
  expecting indentation at column 1 or end of input
```

If you remove `id` then there is a sensible error position.

**Comment by paf31** [comment]
A smaller example:

```
foo = id \a -> [1,,2]
```

**Comment by natefaubion** [comment]
`\` is a valid operator, so maybe since the lambda body parse failed, it's backtracking to parse `id \ a`. I think since the lambda head is correct, it should be able to commit, since `->` is not a valid operator.

**Comment by natefaubion** [comment]
I think this is anything that causes backtracking to the `Parsec.buildExpressionParser`.

```purescript
bad = id [,]
```
```
Unable to parse module:
unexpected [
```

This example should clearly fail with an unexpected `,` instead, which you'd get if you left off the `id`.

**Comment by hdgarrood** [comment]
Shall we close this in favour of #3517?

**Comment by hdgarrood** [comment]
I think this is safe to close unless we want to add tests for error positions, but that might be more effort than it's worth.
