### ISSUE TITLE
Typing ^C in REPL causes exit in some cases

### ISSUE THREAD

**Issue by rndnoise** [purescript/purescript#3269]
There seems to be random behavior when <kbd>^C</kbd> is entered. Starting a new REPL session and pausing for a few seconds, then entering it just prints a new prompt, sometimes with the cursor on the line *after* the prompt -- but either way, the REPL doesn't exit. But pressing it again often results in "purs: Interrupt" and the REPL exits.

It doesn't seem to matter if some text has been entered in the buffer or not. I'm not sure if it happens more often when an expression is being evaluated or not. I think when ncurses is waiting for input to search history (after typing <kbd>^R</kbd>), pressing it will always abort the REPL.

My preference would be that <kbd>^C</kbd> won't ever abort the REPL, but can abort the currently evaluating expression, and will discard any text already entered in the command buffer, then print a new prompt.

**Comment by kRITZCREEK** [comment]
I like the behaviour where hitting Ctrl-C twice will quit the repl (I think node does something similar). This kind of terminal behaviour is vastly different between all the OS's (there have been previous issues with Ctrl-C)

**Comment by blinky3713** [comment]
I just got bit by this pretty hard. Some could argue that I shouldn't be testing things so deep in the repl, but coming from ghci I expect that Ctrl-c clears a line no matter how many times you press it, and Ctrl-d will quit the session. Would be nice to have something like this, will volunteer if people agree and someone scopes the things to consider while doing this.

**Comment by hdgarrood** [comment]
@rndnoise: I think the desired behaviour which you describe is actually how it is intended to work now - I think it's just not quite clear to any of us why it sometimes exits. It's quite possible that this is to do with how `pulp repl` is running `purs repl` as a subprocess of a node.js process also, we've had similar weirdness with that before. Might be worth keeping that in mind for anyone investigating this.

**Comment by hdgarrood** [comment]
Can anyone reproduce this by running `purs repl` directly -- that is, *not* via `pulp repl`? I'm pretty sure this is a pulp issue.

**Comment by rndnoise** [comment]
@hdgarrood Good point. No, I cannot.

**Comment by hdgarrood** [comment]
Thanks! I'll move this over to github.com/purescript-contrib/pulp then.
