### ISSUE TITLE
 Unable to parse foreign module when using rest and spread syntax

### ISSUE THREAD

**Issue by bklaric** [purescript/purescript#3272]
I'm trying to have a JavaScript event listener be called with an unknown number of arguments and then call a curried function using those arguments one by one. This is the foreign module code:

    exports.toEventListener = function (listener) {
        return function (...args) {
            var listenerResult = listener
            for (var index = 0; index < args.length; ++index) {
                listenerResult = listenerResult(args[index])
            }
            listenerResult()
        }
    }

This results in:

    [1/1 ErrorParsingFFIModule]

    Unable to parse foreign module:

        E:\Solutions\purescript-idiomatic-node\purescript-idiomatic-node-events\src\Node\Events\EventEmitter.js

        The module could not be parsed:

        DotToken {tokenSpan = TokenPn 519 15 22, tokenComment = []}

FWIW, this is the workaround I'm using which seems to work just fine: 

    exports.toEventListener = function (listener) {
        return function () { // This function receives all event arguments.
            const argumentsArray = Array.from(arguments)
            var listenerResult = listener
            for (var index = 0; index < argumentsArray.length; ++index){
                listenerResult = listenerResult(argumentsArray[index])
            }
            listenerResult()
        }
    }

**Comment by garyb** [comment]
Yeah, this is a known thing - the library we rely on for JS parsing only support ES5.

**Comment by hdgarrood** [comment]
This is the desired behaviour: this way, we don't have people unintentionally publishing libraries which are a pain to depend on, since you then need to compile the FFI files to ES5.

I think the ideal approach is to set up your own build step to compile ES6 FFI files and place the ES5 versions in the appropriate place so that those are the ones the compiler sees. If you're writing a library, make sure you check those in so that people depending on them get them too.

**Comment by birdbrained** [comment]
I'd like to reopen this, as node is now supporting es6 using the --experimental-modules flag, it'd be nice if purescript could find a .mjs foreign module, and compile to .mjs modules.

**Comment by chexxor** [comment]
@birdbrained: I think there are better issues to discuss ES6, but I'm not sure which one is most appropriate. There's been lots of issues opened and closed about it, and I'm not sure the latest plan. It's a really complicated topic. Last I heard, some people just want ES6 _modules_ while others want full ES6 enforcement and yet others want to support emitting both ES3 and ES6 from PureScript.

Related reading:
Vincent's latest work on adding ES6 support: https://github.com/purescript/purescript/pull/3427
Some past discussion on ES6: https://github.com/purescript/purescript/issues/1206
Jan 2017: https://github.com/purescript/purescript/issues/2207
Apr 2017: https://github.com/purescript/purescript/issues/2574
