### ISSUE TITLE
Scoped type variables don't work for instance methods

### ISSUE THREAD

**Issue by rndnoise** [purescript/purescript#3274]
This fails with "Type variable `a` is undefined". However, moving it to a top-level declaration (and also quantifying w) works as expected.

```purescript
instance applyFoo :: Apply (Foo w) where
  apply :: forall a b. Foo w (a -> b) -> Foo w a -> Foo w b
  apply (Foo f) (Foo x) = Foo (op =<< x)
    where
        op :: Tuple w a -> Array (Tuple w b) -- this should refer to the `a` quantified above
        op = ...
```

**Comment by garyb** [comment]
I thought we already had an issue for this, but I can't seem to find it now.

**Comment by rndnoise** [comment]
Is it #2969, and is that not yet in a release?

**Comment by rndnoise** [comment]
Oh, it's #2941 and I see there isn't a fix. I'll close this then.

**Comment by garyb** [comment]
That's the one! Thanks for digging it out.
