### ISSUE TITLE
Location missing from KindsDoNotUnify for recursive function

### ISSUE THREAD

**Issue by rndnoise** [purescript/purescript#3275]
I'm not sure if this is separate from #3208, since `KindsDoNotUnify` does have source spans in some cases. This issue might apply to other kinds of type checker errors. Here's an example, it only happens if `wrong` is recursive, otherwise there is a line number. :

```purescript
> type Result = Array Int
> :paste
… wrong :: Int -> Result String
… wrong n = wrong (n-1)
…
Error found:
in module $PSCI

  Could not match kind

    Type

  with kind

    Type -> k4


while checking the kind of Int -> Result String
in binding group wrong
```

**Comment by garyb** [comment]
Thanks! I'll add a test case and fix for it with the other stuff for #3208
