### ISSUE TITLE
Inlining function composition reduces sharing

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3280]
Inlining `f <<< g` gives `\x -> f (g x)`. However, `f` might be a partial application which closes over some intermediate result. For example, `f` might be the result of compiling a complex regular expression. So inlining destroys the opportunity to share work.

**Comment by natefaubion** [comment]
something like
```
foo <<< bar (evaluate something expensive) <<< baz
```

Could instead be optimized to
```
(\a -> \b -> foo (bar a (baz b))) (evaluate something expensie)
```

**Comment by paf31** [comment]
This generally seems like a whole can of worms which can be avoided by just undoing the optimization. Doing a full analysis of what should and should not be inlined seems preferable, but not really an option at the moment.

**Comment by natefaubion** [comment]
I think that the analysis can be straightforward. Anything that is not an identifier gets an abstraction and application.

**Comment by paf31** [comment]
Personally I don't see any issue with generating a call to compose.

But if you do this analysis, is it going to be for any nested sequence of compositions, because I'm not sure if only handling the binary case is enough.

That's why I'd rather do nothing at all, or look seriously at writing a proper optimizer - because any partial solution is going to get complicated really quickly as soon as people ask "why doesn't it fire in this case?"

**Comment by natefaubion** [comment]
The current optimization handles syntactic applications of <<< and throws it under an abstraction. So I would assume you could just take whatever it gathers, and substitute any applications in arguments with further abstraction/application.
