### ISSUE TITLE
Multiline string can not end with double quote

### ISSUE THREAD

**Issue by kika** [purescript/purescript#3283]
in `psci`:
```
> :paste
… x = """
… "some text"
… """
…
> x
"\n\"some text\"\n"

> :paste
… y = """
… "some text""""
…
(line 2, column 15):
unexpected "\n"
expecting string character or end of string
> :paste
… y = """
… "some text" """
…
> y
"\n\"some text\" "
```

**Comment by michaelficarra** [comment]
This is expected. `""""` is a valid token. And even if it wasn't, the tokeniser would be greedy and consume the `"""`.

**Comment by kika** [comment]
Should I submit a PR to the documentation then?

**Comment by natefaubion** [comment]
Is it expected that escape sequences don't work in triple-quotes blocks?

**Comment by spicydonuts** [comment]
I've had issues with this before. There should be some escape sequence even if it's different.

**Comment by paf31** [comment]
Fixing the lexer in the way you describe isn't going to be simple.

**Comment by kika** [comment]
What about implementing escapes? It's cool to have them anyway.

**Comment by garyb** [comment]
How would that work? I see `"""` existing as "dump unescaped things here" heredoc kinda thing more than it being for multiline specifically - it not already having escape sequences is a feature :smile:

**Comment by parsonsmatt** [comment]
@kika What languages with multi-line strings work like you want? While Python lets you write:

```python
z = """i can end with double quotes."""""
```

the evaluated value is:

```
λ ~/ python -i foo.py
>>> z
'i can end with double quotes.'
```

As far as I can tell, this is because Python parses that as `"""foo""" ""` and then apparently Python does string concatenation for adjacent string literals?

**Comment by kika** [comment]
@parsonsmatt I can't think of one that allows 4 quotes in a row, but at least python and coffeescript allow escapes, so it's a non-issue for them. 
`z = """i can end with double quotes.\""""`
works in both of them.

**Comment by kika** [comment]
@garyb Allowing escapes is not mutually exclusive with 'dump unescaped things'. You can dump unescaped things while allowing escapes. But the unescaped backslash will fall victim of such change.

**Comment by gabejohnson** [comment]
FWIW, Idris supports this https://www.idris-lang.org/idris-1-2-0-released/

> Verbatim strings now support trailing quote characters. All quote characters until the final three are considered part of the string. Now a string such as """"hello"""" will parse, and is equivalent to "\\"hello\\"".

**Comment by natefaubion** [comment]
This is fixed in master with the new lexer.
