### ISSUE TITLE
Warning for missing kind annotations to phantom parameters?

### ISSUE THREAD

**Issue by rndnoise** [purescript/purescript#3288]
This took me a while to work out, but I think I understand now what happened. When defining a phantom type, the parameters are assumed to have kind `Type`. In this case, the type parameter `m` for the type alias `O` needs an annotation `(m :: Type -> Type)` or kind checking fails.

```purescript
» pulp repl
import Prelude
> newtype Ex (s :: Type) (o :: Type) (m :: Type -> Type) = Ex Unit
> newtype S (i :: Type) (m :: Type -> Type) = S Unit

> type O m = Unit -- m :: Type is assumed

> type Fail i m = Ex (S i m) (O m) m
Error found:
in module $PSCI
at  line 1, column 1 - line 1, column 34

  Could not match kind

    Type

  with kind

    Type -> Type


while checking the kind of Ex (S i m) (O m) m
```

I was confused because I was on my way to making `O` a non-phantom type, but I hadn't gotten to using its parameters yet. My proposal is to issue a warning when phantom parameters aren't explicitly given a kind annotation, similar to how warnings are given for top-level values without a type annotation.

Perhaps something like:

```
[3/4 MissingKindDeclaration] src/Main.purs:8:1

  8  type O m = Unit
     ^^^

  No kind declaration was provided for the phantom type parameter of m.
  It is good practice to provide kind declarations as a form of documentation.
  The inferred kind of m was:

    Type

  in type declaration O
```

**Comment by garyb** [comment]
I don't know about this. I've thought about it on and off since you mentioned it. I've occasionally run into this too, but it generally doesn't take me too long to track down when it occurs - I think maybe if we had better kind errors it wouldn't be necessary, but that's probably way harder to solve.

**Comment by hdgarrood** [comment]
:-1: I think `Type` is the right default for phantom parameters; this would cause lots of previously fine code to start emitting warnings of questionable benefit, and we should improve the kind errors anyway.

**Comment by natefaubion** [comment]
I also think a warning is unnecessary. I think the proper fix for this is polykinds, which infers phantom type parameters to be polymorphic.

**Comment by hdgarrood** [comment]
Sounds good to me. Speaking of which, I guess we can probably justify a dedicated polykinds issue now?

**Comment by hdgarrood** [comment]
We do indeed have one already. Closing in favour of #1763
