### ISSUE TITLE
psc: help text still references `purs`

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3296]
Example:

```
~/proj/purescript-string-zoo$ psc --help
Usage: purs compile [FILE] [-o|--output ARG] [-v|--verbose-errors]
 ...
```

References to `purs` rather than `psc` show up in all the help texts.

**Comment by natefaubion** [comment]
`psc` is the old binary name (we provided wrapper scripts for compat). Do we still distribute the psc scripts?

**Comment by hdgarrood** [comment]
We do, but they have been removed and will not be in 0.12.0, see https://github.com/purescript/purescript/pull/3011. I wouldn't consider this a bug, personally.

**Comment by matthewleon** [comment]
Ah, I see what's happening here. Makes sense. Closing.
