### ISSUE TITLE
Exhaustivity Checker

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#33]
Optional exhaustivity checking / warnings

**Comment by LiamGoodacre** [comment]
The following is a list of possible approaches I thought of for this.
Some of these have issues with breaking existing code (opt out annotations [2] for example) which will probably automatically rule them out, but I included them anyway for the sake of completeness.


#### 1. new command in psci to list locations of non-exhaustive cases for a given type

given the code:

~~~purescript
    module Main where
    data Exp = Lit Bool | Not Exp
    eval (Lit b) = b
    pprint (Not e) = "not " <> show e
~~~

running the command in psci

~~~purescript
    > :exhaustive Exp
    Found 2 occurence(s):
    [1] line 3 - Main.eval (src/Main.purs)
        missing case(s)
        * Not a
    [2] line 4 - Main.pprint (src/Main.purs)
        missing case(s)
        * Lit a
    Enter those numbers you wish to be inserted for you:
    > 1
    Inserted case(s) for 1
    > :exhaustive Exp
    Found 1 occurence(s):
    [1] line 4 - Main.pprint (src/Main.purs)
        missing case(s)
        * Lit a
    Enter those nu...
~~~


#### 2. check by default and annotate cases to opt out

~~~purescript
    data Exp = Lit Bool | Not Exp

    -- fails check
    eval (Lit b) = b

    -- not checked
    unchecked
    eval' (Lit b) = b
~~~


#### 3. annotate cases to opt in to checks

~~~purescript
    data Exp = Lit Bool | Not Exp

    -- fails check
    exhaustive
    eval (Lit b) = b

    -- fails check
    -- case marked somehow (here with an ! for example)
    eval' m = case! m of
                Lit b -> b

    -- not checked
    eval'' (Lit b) = b
    eval''' m = case m of
                  Lit b -> b
~~~


#### 4. cascading checks

if we check a function for exhastiveness should we check all the functions it calls too


#### 5. annotate data/newtype declarations to opt in to checks for all pattern matching of constructors for that type

~~~purescript
    data Exp = Lit Bool | Not Exp
      exhaustive

    -- fails check because `Exp` is annotated as exhaustive
    eval (Lib b) = b
~~~


#### 6. annotate files/regions of file for checks

~~~purescript
    module Batman where
    exhaustive -- from here on check for exhaustiveness

    data A = A0 | A1

    fn A0 = unit -- fails check

    nonexhaustive -- from here on don't check

    fn' A0 = unit -- not checked
~~~


#### 7. mark usages of the type

~~~purescript
    -- either, mark as possibly non-exhaustive
    fn :: T? -> Unit -- non-exhaustive
    fn :: T -> Unit  -- exhaustive

    -- or, mark as exhaustive
    fn :: T -> Unit  -- non-exhaustive
    fn :: T! -> Unit -- exhaustive
~~~


#### 8. severity level of annotation

~~~purescript
    exhaustive  -- compiler warning - you missed a case
    exhaustive! -- compiler error - cases must be exhaustive
~~~

**Comment by garyb** [comment]
I'd quite like to disallow partial functions outside of modules ending with `.Unsafe`, that aligns with what we already do, and is a form of annotation in itself too. The information doesn't escape out of the call site, but actually that is sometimes desirable (there are cases where you have made a check manually and by reasoning can see that the usage of the partial function is 100% safe, like `if null xs then Nothing else Just (U.head xs)` kind of situations), if we truly wanted to carry that information up the hierarchy there should be a `PARTIAL` effect instead.

My 2p anyway. :smile:

**Comment by paf31** [comment]
I think compiler errors should be stable under module renamings, which is why I'm not sold on the `Unsafe` module idea, but I like the idea of using a partiality effect. I'll have a think about that.

**Comment by puffnfresh** [comment]
@paf31 I agree, it would prevent refactoring which is an important criteria for me.

The partial effect sounds good, similar and consistent with what I proposed in IRC a while ago.

**Comment by paf31** [comment]
I personally still like the `Partial` type class idea, just because it composes so nicely, but I appreciate the orphan instance issue.

**Comment by garyb** [comment]
With the partiality effect I guess we'd also want something like `runUnsafe = runPure <<< unsafeInterleaveEff` to accomodate cases like I mentioned above then.

**Comment by paf31** [comment]
The issue with that approach is that you can't easily propagate partiality to a caller (without using the `Monad` machinery). Usually, we want to write pure partial functions, and `Eff` confuses that, I think.

**Comment by LiamGoodacre** [comment]
@paf31 what's the orphan instance issue with a `Parital` type class?

**Comment by paf31** [comment]
Nullary type class instances are automatically orphaned, unless they are defined in the module with the class, in which case they are effectively useless.

However, in practice, this is not a problem. We don't **need** to define a `Partial` instance, we just need to provide a function

```
unsafePartial :: forall r. (Partial => r) -> r
```

**Comment by garyb** [comment]
Ok, I was just writing something, but I hadn't considered `unsafePartial` as the way of removing the `Partial` constraint. I do like that.

**Comment by garyb** [comment]
We don't necessarily need to disallow nullary classes either, as it's the instances that are checked, not the classes. Yes *all* other nullary classes we can think of right now are useless, but this one makes not adding an explicit check worthwhile. :wink:

**Comment by paf31** [comment]
Prototype here in Haskell: http://hackage.haskell.org/package/partial

**Comment by paf31** [comment]
Also:

```
partial :: forall eff r. (Partial => r) -> Eff (partial :: PARTIAL | eff) r
```

**Comment by LiamGoodacre** [comment]
Would this mean that any function explicitly calling a partial function will automatically get the `Partial` constraint?  And it'd be a type mismatch error if the author added a type annotation and omitted the constraint?

**Comment by paf31** [comment]
Yep, that's the idea. It's still up for debate though.

**Comment by vendethiel** [comment]
(What about an idris-like %partial or so?)

**Comment by LiamGoodacre** [comment]
Hmm I feel that the name `Parital` is confusing, we're using it to mean is that a function may throw; but there are other kinds of partiality (such as non-termination).  Having a construct called `Partial` feels to me that it implies that all partial things are marked as `Partial`.  I'd probably prefer `Throws`?

~~~purescript
class Throws
catchThrows :: forall eff r. (Throws => r) -> Eff (throws :: THROWS | eff) r
~~~

**Comment by garyb** [comment]
`Partial` seems pretty well defined to me as a function that is not defined for all of its arguments.

I'm not sure non-termination counts as partial, as ⊥ is still a value :wink:, although it doesn't really have the same place in PS as in Haskell.

**Comment by LiamGoodacre** [comment]
As far as I know a non terminating function isn't total.

**Comment by freebroccolo** [comment]
For what it's worth, I'm using something called `Partial` for some of the topology and lattice stuff defined [here](https://github.com/freebroccolo/purescript-synthetic-semicomputable/blob/master/src/Synthetic/Topology/Time/Partial.purs). It's specifically for non-termination since `bot` in the lattice represents the divergent computation from domain theory (`Time a` is a domain). I don't have a strong attachment to the name though and have considered changing it. Either way, I do think it's worth keeping (non-observable) non-termination as a separate notion from other forms of partiality if possible.
