### ISSUE TITLE
Warn on "phantom type synonym"

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#3303]
Unused type variables in a synonym are kinda weird - they won't be used in unification or checking to reject any types, so probably should be warned about at the declaration site.

**Comment by LiamGoodacre** [comment]
:-1: from me as this is useful: synonyms can be partially applied when used with other synonyms.
There are some example usages here: https://gist.github.com/LiamGoodacre/9ee4933861b57a98282758acd4e4fd9f

**Comment by paf31** [comment]
Agreed, this is sometimes useful. Optics probably can provide another example.
