### ISSUE TITLE
Very unclear how to use FFI for node modules

### ISSUE THREAD

**Issue by naglalakk** [purescript/purescript#3316]
Hi. As a dumb Purescript beginner I have a few problems with how the FFI is explained. It does not really go into how to import external javascript files from npm packages. Foreign imports seem no problem when you have the .js file in the same directory as your .purs file. But I cannot seem to be able to make it work when I'm trying to require an external npm package. 

the javascript

```
'use strict';

// module Pluralize

exports.pluralize = function(word) {
    return function(count) {
        return function(inclusive) {
            return require('pluralize').pluralize(word, count, inclusive)
        }
    }
}
```

Purescript

```
module Pluralize where

foreign import pluralize :: String -> Int -> Boolean -> String
```

This compiles and all but now when running this I get the following error

```
> import Pluralize
> pluralize "Entry" 5 false
/Users/Donna/Code/naglalakk/apidotps/.psci_modules/node_modules/Data.Show/foreign.js:31
  return "\"" + s.replace(
                  ^

TypeError: s.replace is not a function
    at exports.showStringImpl (/Users/Donna/Code/naglalakk/apidotps/.psci_modules/node_modules/Data.Show/foreign.js:31:19)

```

I mean I suspect that this is because pluralize is not returning a string.
Now if I'm going to test this in the browser I get the error that: require is not defined.
How do I require an external npm module and make sure that Purescript adds that to the bundle? How would I provide require myself if purescript handles the bundling? 
I feel that these questions are really missing from the docs which is otherwise outstanding.

**Comment by naglalakk** [comment]
Hey @i-am-tom thank you for your answer. Yeah I thought so too but when I do this I get 

```
> pluralize "Entry" 5 false
/Users/Donna/Code/naglalakk/apidotps/.psci_modules/node_modules/Pluralize/foreign.js:8
            return require('pluralize')(word, count, inclusive)
                                       ^
```

but it's weird because that is totally how the library is exporting it

**Comment by joneshf** [comment]
The original definition doesn't work in node:

```
$ node
> require('pluralize').pluralize('Entry', 5, false)
TypeError: require(...).pluralize is not a function
```

Trying it with your second definition seems to work:

```
$ node
> require('pluralize')('Entry', 5, false)
'Entries'
```

Changing the FFI module to be your second definition also seems to work:

```
$ npx pulp psci
PSCi, version 0.11.7
Type :? for help

import Prelude
> import Main
> pluralize "Entry" 5 false
"Entries"
```

It also seems ot work with bare `purs` (not `pulp`):

```
$ npx purs repl src/**/*.purs bower_components/purescript-*/src/**/*.purs
PSCi, version 0.11.7
Type :? for help

import Prelude
> import Main
> pluralize "Entry" 5 false
"Entries"
```

Maybe try a fresh build. Dunno how you're building now, but it usually amounts to removing the `output` directory and building again.

**Comment by naglalakk** [comment]
Hi @joneshf, thank you for your answer. I'm using pulp build to build it. I tried a fresh build by deleteing the output directory and building again. It just keeps telling me that require is not a function. Do I need to install require in my project with bower?

Trying this with purs gives me the same error. But it works for you. Maybe this has got something to do with my runtime environment. I'm using PSCi, version 0.11.1, running on OSX High Sierra.

**Comment by naglalakk** [comment]
Hang on, nevermind I see. It works when calling it from main but not when calling it directly from the Pluralize module. That is to say this works

```
main :: Eff ( console :: C.CONSOLE ) Unit
main = do
    C.log $ pluralize "Entry" 5 false
```

and not

```
import Pluralize

pluralize "Entry" 5 false
```

I get the require error in the second case. But I don't need to call it directly in psci anyway I just need it to run in my code and it seems to do that. Thank you very much for your help both @i-am-tom, @joneshf 

Closing this issue for now. The problem was mainly my misunderstanding on how the external library works.

**Comment by naglalakk** [comment]
Hi @hdgarrood thank you I had not noticed. Very good to know :)
