### ISSUE TITLE
Subgoals of compiler solved type classes get ignored

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#3333]
In the following reproduction `example` should require `Lacks "hello" r` but the compiler accepts this as solved.

```purescript
module Main where

import Prim.Row (class Lacks)

undefined :: forall a. a
undefined = (\_ -> undefined) 0

data S (r :: Symbol) = S
data R (r :: # Type) = R

union :: forall s r. Lacks s r => S s -> R r
union = undefined

example :: forall r. R (k :: Int | r)
example = union (S :: S "hello")
```

The implementation of the solved type class `Lacks` (attempts to) defer to solving the tail of a row when it knows some non-empty prefix.

This isn't specific to `Lacks`.

**Comment by natefaubion** [comment]
https://github.com/purescript/purescript/blob/master/src/Language/PureScript/TypeChecker/Entailment.hs#L353

Is it because it produces undefined? I noticed Union does something slightly different for subgoals.

**Comment by LiamGoodacre** [comment]
Oh interesting, it's probably that.  Thanks.  I'll see if that fixes it.
