### ISSUE TITLE
ExtraneousClassMember error is missing source span

### ISSUE THREAD

**Issue by bklaric** [purescript/purescript#3336]
Repro case:

    foreign import kind Method

    foreign import data Get :: Method

    foreign import data Post :: Method

    foreign import data Put :: Method

    data MethodProxy (method :: Method) = MethodProxy

    class MethodRouter (method :: Method) where
        methodRouter :: MethodProxy method -> String -> Boolean

    instance methodRouterGet :: MethodRouter Get where
        methodRouter _ "GET" = true
        methodRouer _ _     = false

This fails with:

    Error found:

    methodRouer is not a member of type class Main.MethodRouter

    in type class instance

    Main.MethodRouter Get

    See https://github.com/purescript/documentation/blob/master/errors/ExtraneousClassMember.md for more information,
    or to contribute content related to this error.

**Comment by garyb** [comment]
Thanks for the report, this is already fixed in master :)
