### ISSUE TITLE
Contrib library updates for 0.12

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#3348]
Some of these are as good as dead anyway I think, but here's a list of everything:

- [x] [`purescript-aff-coroutines`](https://github.com/purescript-contrib/purescript-aff-coroutines)
- [x] [`purescript-argonaut-core`](https://github.com/purescript-contrib/purescript-argonaut-core)
- [x] [`purescript-arraybuffer-types`](https://github.com/purescript-contrib/purescript-arraybuffer-types)
- [x] [`purescript-canvas`](https://github.com/purescript-contrib/purescript-canvas)
- [x] [`purescript-coroutines`](https://github.com/purescript-contrib/purescript-coroutines)
- [x] [`purescript-freet`](https://github.com/purescript-contrib/purescript-freet)
- [x] [`purescript-http-methods`](https://github.com/purescript-contrib/purescript-http-methods)
- [x] [`purescript-js-date`](https://github.com/purescript-contrib/purescript-js-date)
- [x] [`purescript-js-timers`](https://github.com/purescript-contrib/purescript-js-timers)
- [x] [`purescript-media-types`](https://github.com/purescript-contrib/purescript-media-types)
- [x] [`purescript-now`](https://github.com/purescript-contrib/purescript-now)
- [x] [`purescript-options`](https://github.com/purescript-contrib/purescript-options)
- [x] [`purescript-these`](https://github.com/purescript-contrib/purescript-these)
- [x] [`purescript-unsafe-reference`](https://github.com/purescript-contrib/purescript-unsafe-reference)
- [x] [`purescript-form-urlencoded`](https://github.com/purescript-contrib/purescript-form-urlencoded)
- [x] [`purescript-nullable`](https://github.com/purescript-contrib/purescript-nullable)
- [x] [`purescript-machines`](https://github.com/purescript-contrib/purescript-machines)
- [x] [`purescript-precise`](https://github.com/purescript-contrib/purescript-precise)
- [ ] [`purescript-argonaut`](https://github.com/purescript-contrib/purescript-argonaut)
- [ ] [`purescript-argonaut-codecs`](https://github.com/purescript-contrib/purescript-argonaut-codecs)
- [ ] [`purescript-argonaut-generic`](https://github.com/purescript-contrib/purescript-argonaut-generic)
- [ ] [`purescript-argonaut-traversals`](https://github.com/purescript-contrib/purescript-argonaut-traversals)
- [ ] [`purescript-base`](https://github.com/purescript-contrib/purescript-base)
- [ ] [`purescript-drawing`](https://github.com/purescript-contrib/purescript-drawing)
- [ ] [`purescript-foreign-lens`](https://github.com/purescript-contrib/purescript-foreign-lens)
- [ ] [`purescript-handlebars`](https://github.com/purescript-contrib/purescript-handlebars)
- [ ] [`purescript-jquery`](https://github.com/purescript-contrib/purescript-jquery)
- [ ] [`purescript-lens`](https://github.com/purescript-contrib/purescript-lens)
- [ ] [`purescript-parsing`](https://github.com/purescript-contrib/purescript-parsing)
- [ ] [`purescript-profunctor-lenses`](https://github.com/purescript-contrib/purescript-profunctor-lenses)
- [ ] [`purescript-react`](https://github.com/purescript-contrib/purescript-react)
- [ ] [`purescript-react-addons-css-transition-group`](https://github.com/purescript-contrib/purescript-react-addons-css-transition-group)
- [ ] [`purescript-react-dom`](https://github.com/purescript-contrib/purescript-react-dom)
- [ ] [`purescript-sammy`](https://github.com/purescript-contrib/purescript-sammy)
- [ ] [`purescript-string-parsers`](https://github.com/purescript-contrib/purescript-string-parsers)
- [ ] [`purescript-strings-extra`](https://github.com/purescript-contrib/purescript-strings-extra)
- [ ] [`purescript-strongcheck`](https://github.com/purescript-contrib/purescript-strongcheck)
- [ ] [`purescript-unicode`](https://github.com/purescript-contrib/purescript-unicode)

**Comment by gabejohnson** [comment]
Do we want to migrate libraries off of `-generics` a the same time?

**Comment by hdgarrood** [comment]
Not sure about `arraybuffer-types`. I think we will indeed want to migrate libraries off of `generics`, and I think now is a good time to do so.

**Comment by garyb** [comment]
> Does `-arraybuffer-types` need any updates?

No I don't think it does actually, it has no dependencies and just defines some stuff. I've checked it off for now.

**Comment by matthewleon** [comment]
Should the dead ones be killed?

**Comment by hdgarrood** [comment]
I think putting a “this library is currently not maintained. If you would like to take over as maintainer please open an issue” notice on any which don’t currently seem worth updating (it any) is probably sensible?

**Comment by justinwoo** [comment]
I made some PRs for many of these, so whoever is in `purescript-contrib`, please make some branches and push them up to compiler/0.12 :smiley:
