### ISSUE TITLE
prebuilt binary not working for armv7

### ISSUE THREAD

**Issue by dipucian** [purescript/purescript#3368]
I'm trying to install purescript, but seems the prebuilt binary does not work correctly for my machine: [error](https://i.imgur.com/rlRu5sY.png)

> Verify the prebuilt binary works correctly
  Error: Command failed: /home/dipucian/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/purs.bin --version
/home/dipucian/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/purs.bin: 1: /home/dipucian/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/purs.bin:ELF: not found
/home/dipucian/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/purs.bin: 2: /home/dipucian/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/purs.bin: Syntax error: "(" unexpected
    at makeError (\~/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (~/.nvm/versions/node/v10.2.1/lib/node_modules/purescript/node_modules/execa/index.js:277:16)

and falling back to building from source failed due to out of memory...

**Comment by kRITZCREEK** [comment]
Don't think there's a lot we can do here. Either you get yourself an ARM machine beefy enough to compile from source or you look into cross-compiling with GHC. There's been a resurgence of interest in that are recently, this might be a good starting point: https://medium.com/@zw3rk/a-haskell-cross-compiler-for-raspberry-pi-ddd9d41ced94
