### ISSUE TITLE
Poor compile time performance with deeply nested types

### ISSUE THREAD

**Issue by jonathanlking** [purescript/purescript#3376]
I am working on a project where I represent large amounts of data at the type level using `RowList`s and noticed terrible (super-exponential) asymptotic compile time performance with respect the the number of elements in the list. It isn’t noticable for fewer than 8 elements, but takes ~30 minutes for a 15 element list.

Initially I thought it was an unavoidable issue with constraint solving, however after further experimentation I found that I could reproduce the slowdown with this following (invalid) program:

```purescript
module Main where
t :: ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T )))))))))))))))))
```

This takes ~15 seconds on my laptop to get an error message.

(I have experience this behaviour on both versions 0.11.6 and 0.12.0)

I haven't yet investigated any further, but I'm guessing it's an issue with the parser/AST representation.

I've written a [script](https://gist.github.com/jonathanlking/986280e1c01abb3ec0561aa2d8eb43b5) that generates programs with increasingly nested types and plotted a graph displaying the results:

![graph](https://user-images.githubusercontent.com/979725/40896711-8bac9af0-67ae-11e8-96de-8574819b2662.png)

I would be happy to work on a fix, however I am *very* busy until the start of July.

**Comment by jonathanlking** [comment]
If you rewrite a nested type using type synonyms there is no performance degradation - so it looks like it's definitely an issue with the parser!

```purescript
module Main where
type T1 = T
type T2 = (T1 T)
type T3 = (T2 T)
type T4 = (T3 T)
type T5 = (T4 T)
type T6 = (T5 T)
type T7 = (T6 T)
type T8 = (T7 T)
type T9 = (T8 T)
type T10 = (T9 T)
type T11 = (T10 T)
type T12 = (T11 T)
type T13 = (T12 T)
type T14 = (T13 T)
type T15 = (T14 T)
type T16 = (T15 T)
type T17 = (T16 T)
type T18 = (T17 T)
type T19 = (T18 T)
type T20 = (T19 T)
t :: T20
```

**Comment by jonathanlking** [comment]
So unfortunately the [`TypeSynonymInstance`](https://github.com/purescript/documentation/blob/master/errors/TypeSynonymInstance.md) error limits the type synonym trick as a temporary workaround...

**Comment by jonathanlking** [comment]
I have profiled `purs` compiling one of these programs, and have the [profiterole output here](https://gist.github.com/jonathanlking/986280e1c01abb3ec0561aa2d8eb43b5#file-purs-profiterole-txt).

**Comment by garyb** [comment]
Thanks for the report and investigation!

**Comment by hdgarrood** [comment]
@natefaubion Your new parser would fix this, presumably?

**Comment by hdgarrood** [comment]
Yep, this is indeed a problem with `parseType`. Another repro, this time in the repl:
```
$ stack repl purescript:lib
> Right toks = Language.PureScript.lex "" "T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T ( T )))))))))))))"
> runTokenParser "" parseType toks
```
which takes 10 seconds or so before producing any output.

**Comment by hdgarrood** [comment]
I just checked and @natefaubion's new parser does indeed fix this.

**Comment by hdgarrood** [comment]
This doesn't seem worth the effort of putting together a test for so I think we can close it. (come to think of it, at some point I suppose we will probably want to add performance regression tests for the compiler as a whole)
