### ISSUE TITLE
--port is broken in 0.12

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3387]
Looks like the `require` changes broke it.

**Comment by omefire** [comment]
I can help with this.

**Comment by dariooddenino** [comment]
What's the correct way to debug this?
What are the correct steps to build and then call the newly built `purs` instead of the one installed on my system?
Thanks!

**Comment by hdgarrood** [comment]
@dariooddenino thanks for this! In case you didn't work it out, for building and running a version of `purs` from a local working copy, I'd recommend doing `stack build --fast` to build it, and then `stack exec bash` to put yourself into a new shell session with the newly built `purs` at the front of your PATH.
