### ISSUE TITLE
RFC: Implementing Lua backend for PureScript

### ISSUE THREAD

**Issue by osa1** [purescript/purescript#339]
Hi all,

PureScript is relatively easy to compile to Lua because of semantic similarities of Lua and JS(and especially JS subset used in PureScript) and I think both Lua community and PureScript would greatly benefit from having a Lua backend of PureScript. Lua is one of my favorite languages and it has great game development libraries/frameworks and widely used for game development.

Another strong point of Lua is LuaJIT, which provides super fast interpretation of Lua 5.1.5 and very easy communication with C.

So I started working on Lua backend for PureScript, but I'm afraid this is not possible without some modification in current PureScript implementation(e.g. by using PS as a library).

Some of the problems are:

* `$` character is used in variables, which is an invalid character in Lua variables. It'd be easy to fix this without changing PureScript if variables were not be used in strings(e.g. while assigning object attributes). Currently it's impossible to eliminate `$` characters in variables because there's no way to distinguish `$` characters used in user strings vs. `$` characters used in object attributes and later used in variable syntax. Example:
```
  > function f() {}
  > f["$a"] = 1;
  > f.$a
  1
  > var userString = "hello$world"; // this should not be changed but how can I distinguish this string from "$a" ?
```
* Some Lua keywords are used as variables. Like `not`.
* JSRaw syntax. We need something more abstract than that because
different code generators will need different FFI strings. 
* Lua already has TCO.
* Lua 5.1.5 does not have labels, break, continue keywords. (as far as I can see, these are all used for TCO, so they're not needed)
* Not having separated statement/expression syntax makes compilation a bit harder.

You can see first prototype implementation in my fork of the project.

There are probably other problems too, but none of the problems should be very hard to fix.

So at this point I think what we need to do is to have an intermediate language that will allow us to run all optimizations we need. After code generation, only target-language-specific optimizations should be done. For tail-call optimization, I think we can have a syntax tree node for this and Lua backend can simply ignore that, since it already has TCO.

As a first very rough design, I have something like this in mind:

We can separate syntax to 4 types:

* Module: This contains module name, list of exported symbols and list of top-level declarations. Code generators then generate target-language-specific patterns for modules.
* Top-level declaration: Function and variable declarations.
* Statement: This includes variable assignments, loops(I think we need to have different loops for traversing through fields of an object vs. looping for a range etc. I think in theory we can have only one kind of loop but that would make generated code more complicated), return/error statements, function calls, maybe labels. Btw, Lua 5.1.5 does not support labels(which is the version I'd like to compile to, because LuaJIT supports this version), but I think labels are only used for TCO, and Lua has that already so maybe we can have a different syntax node for TCO and then JS codegen could generate labels as necessary. Also, about assignments, I think it'd be nice to statically specify what kind of object we're assigning to. e.g. assigning to an object field vs. assigning to a variable.
* Expressions: Ordinary expressions. One important point is that Lua does not have conditional expressions like `e1 ? e2 : e3`.

Of course there's a tradeoff when designing an intermediate language. We can have a more functional IR which could simplify type checking, but for optimizations maybe we need this kind of imperative one? I can't say for sure since I don't know implementation details of current implementation, but as far as I can see type checking is done on PureScript syntax, so we could design an imperative IR like I gave an example above and typechecking would work without any modifications.

I'd like to know your ideas about this, any ideas/suggestions/comments are welcome.

**Comment by gitfoxi** [comment]
Sorry to hijack but I was wondering, with your experience, what you'd think about the prospects of a [Nim](http://nim-lang.org) backend.

The reason I'm dreaming about this is that Nim has accomplished something kind of amazing: Painless FFI for C, C++ and Objective C. It does this by compiling itself to any of those target languages on request.

I think that Row Types are a great idea and I wish Haskell had them. It really bridges the object style used by most languages into FP very nicely. In particular it gives you a way to interface C++ classes with inheritance. (No clue what to do with C++ templates though.)

The challenge of writing a Nim pretty printer doesn't seem too great to me. One place the project might run into trouble is that Nim's basic types are C's basic types. PureScript buys into JavaScript types like Number which is fine for Lua but has no place in C world. I could see it turning out to limit compatibility with a lot of libraries.

I'd love to hear your thoughts.

**Comment by garyb** [comment]
There is a C++ backend in progress, so I would think Nim is definitely possible: https://github.com/andyarvanitis/pure11. We're currently making changes to the compiler to make it easier to write additional backends for it, it's going into the 0.7 release that will be done in the very near future hopefully (perhaps a week or two).

I'm not sure how @andyarvanitis gets around the `Number` etc. problem though as I've not really had time to have a play with his version yet. The changes we're making don't extend to changing the primitive types, aside from adding an `Int` type, but are more about pushing any foreign-related code out of the library part of the compiler so it's up to the frontend and backend to deal with it, and also removing foreign string literals from the `.purs` files so FFI implementations are provided in external files.

**Comment by andyarvanitis** [comment]
@gitfoxi As Gary mentioned, in the 0.7 branch we have the PureScript `Int` type, so the C++ backend currently renders `Int` as `int` and `Number` as `double`.

**Comment by paf31** [comment]
Once we implement something like `--dump-core`, this will be much simpler to implement outside the main compiler.

Can we close this? It is probably best tracked elsewhere.

**Comment by osa1** [comment]
Yep.

**Comment by DoctorRyner** [comment]
So, is there any working lua backend?

**Comment by YellowOnion** [comment]
Okay for posterity sake, `--dump-core` was renamed twice, `--dump-corefn` then renamed to `-g corefn`.

This link has a crappy js implementation that outputs a subset of Lua: https://github.com/paf31/24-days-of-purescript-2016/blob/master/22.markdown

I guess it wouldn't be that hard to write a modern Lua transpiler in PureScript/Haskell using core output, and then start writing a FFI for Factorio modding.

now to just figure out corefn.

**Comment by JordanMartinez** [comment]
> Okay for posterity sake, `--dump-core` was renamed twice, `--dump-corefn` then renamed to `-g corefn`.
> 
> This link has a crappy js implementation that outputs a subset of Lua: https://github.com/paf31/24-days-of-purescript-2016/blob/master/22.markdown
> 
> I guess it wouldn't be that hard to write a modern Lua transpiler in PureScript/Haskell using core output, and then start writing a FFI for Factorio modding.
> 
> now to just figure out corefn.

You might consider looking at [`purs-backend-optimizer`](https://github.com/aristanetworks/purescript-backend-optimizer/). All you need to do is define a printer (more or less) for your language and then you're done (besides FFI and all that). As an example, the [`backend-es`](https://github.com/aristanetworks/purescript-backend-optimizer/tree/main/backend-es) produces JavaScript that's more optimized than the compiler's output. However, it's not incremental.

**Comment by Unisay** [comment]
I've implemented a Lua back-end recently. Its in the alpha state at the moment and I am looking for feedback, please check it out: https://github.com/Unisay/purescript-lua

**Comment by JordanMartinez** [comment]
@Unisay If you haven't already, I'd suggest submitting a PR to the `documentation` repo, adding this backend to the list of backends.
