### ISSUE TITLE
Improve error information

### ISSUE THREAD

**Issue by Baudin999** [purescript/purescript#3390]
Hi, I've been learning PureScript and I've noticed a little improvement which could make things a little bit easier for newbies (like me):

The original error is:
```
[PureScript]
Type class member mempty has not been implemented.

in type class instance

  Data.Monoid.Monoid Order
Monoid :: Type -> Type
```

I'd suggest doing something like:

```
[PureScript]
Type class member "mempty" has not been implemented in type class instance:

  Data.Monoid.Monoid Order
Monoid :: Type -> Type

mempty :: Order
```

It's mostly a visual change and I've added the type signature of the member which is missing, saves people a lookup and rounds our the error message.

When you make a mistake when implementing a typeclass member the message would look a little better if it looked something like:

Original:

```
[PureScript]
Could not match type

    Person -> Person

  with type

    Person


while checking that type t0 -> t1
  is at least as general as type Person
while checking that expression \$6 ->
                                 case $6 of
                                   (Person p) -> temp
  has type Person
in value declaration semiringPerson

where t0 is an unknown type
      t1 is an unknown type
```

Suggestion:

```
[PureScript]
Could not match type:

    one :: Person -> Person

  with type

    one :: Person


while checking that type t0 -> t1
  is at least as general as type Person
while checking that expression \$6 ->
                                 case $6 of
                                   (Person p) -> temp
  has type Person
in value declaration semiringPerson

where t0 is an unknown type
      t1 is an unknown type
```

In the original error I couldn't find the actual member name of the member throwing the error; just throwing in the actual name of the member helps a lot.

**Comment by Baudin999** [comment]
Should I close this issue or be patient?

**Comment by LiamGoodacre** [comment]
@Baudin999, thanks for raising this issue and sorry that no-one responded promptly.
As you can see above this sparked multiple pieces of work.
Thanks again!

**Comment by Baudin999** [comment]
Thank you for the response! I know how hectic things can get.

Should I close this issue?

**Comment by hdgarrood** [comment]
No need just yet, we can close it once we've come to a decision on how to proceed.

**Comment by hdgarrood** [comment]
Since #3398 addresses the first part, and the second part is best served by improving error spans (
#1801) and showing actual code in errors (#1898), I think this can now be closed.
