### ISSUE TITLE
Diff row/record type errors

### ISSUE THREAD

**Issue by spicydonuts** [purescript/purescript#3392]
(I thought there was an issue for this but I couldn't find it)

The "Could not match type ... with type ..." error is really difficult to read when the types in question are rows/records. For example:

```purescript
  Could not match type

    ( onChange :: EffectFn1 t5 Unit
    , options :: Array t4
    , searchable :: t2
    , style :: t1
    , value :: t3
    , className :: String
    , filterOptions :: Array
                         { value :: String
                         , label :: String
                         | additionalData0
                         }
                       -> Array
                            { value :: String
                            , label :: String
                            | additionalData0
                            }
    , id :: String
    , name :: String
    , noResultsText :: String
    , optionRenderer :: { value :: String
                        , label :: String
                        | additionalData0
                        }
                        -> JSX
    , placeholder :: String
    )

  with type

    ( noBorder :: Boolean
    , onChange :: EffectFn1
                    (Nullable
                       (Array
                          { value :: String
                          , label :: String
                          | additionalData0
                          }
                       )
                    )
                    Unit
    , options :: Array
                   { value :: String
                   , label :: String
                   | additionalData0
                   }
    , searchable :: Boolean
    , style :: CSS
    , value :: Array String
    , className :: String
    , filterOptions :: Array
                         { value :: String
                         , label :: String
                         | additionalData0
                         }
                       -> Array
                            { value :: String
                            , label :: String
                            | additionalData0
                            }
    , id :: String
    , name :: String
    , noResultsText :: String
    , optionRenderer :: { value :: String
                        , label :: String
                        | additionalData0
                        }
                        -> JSX
    , placeholder :: String
    )
```

The actual error here is that the first row is missing the label `noBorder :: Boolean`. It'd be great to show that diff at the beginning of the error message.

The error message is also reported in a strange place:

```purescript
component :: ReactComponent { ... }
component = ...
  where
    initialState = ...                      -- the error is reported here
    
    ...

    render props state setState =
      ...
      where
        helper =
          ...
            (props.render                   -- the error should be reported here
              { className: props.className
              , style: props.style
              , searchable: props.searchable
              , id: props.id
              , name: props.name
              , noBorder: props.noBorder
              , noResultsText: props.noResultsText
              , placeholder: props.placeholder
              , optionRenderer: props.optionRenderer
              , filterOptions: props.filterOptions
              , value: props.value
              , options: []
              , onChange: mkEffectFn1 \_ -> pure unit
              })
```

**Comment by LiamGoodacre** [comment]
I would love to have some form of type diffs in error messages, especially for rows. So :+1: from me.

**Comment by natefaubion** [comment]
> The error message is also reported in a strange place:

I've seen this several times as well and it's very confusing. It seems as though type errors within a recursive binding group often end up off-by-one.

**Comment by dariooddenino** [comment]
I can give a try at row diffs in errors. Any pointers to where I can start looking? :)

**Comment by kRITZCREEK** [comment]
I'd probably start here https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Errors.hs#L585-L604

You can still move whatever you come up with to another module if it becomes too big.

**Comment by dariooddenino** [comment]
Thanks! I'll give it a shot hoping it's not too much for me :)
How do we want to approach this? A record could have additional labels, missing labels, or labels with wrong types. Should we just show the diff, or give a more explicative message?

**Comment by kRITZCREEK** [comment]
I'd say just try a few options and make suggestions in here? Always easier to talk about something concrete.

**Comment by dariooddenino** [comment]
I'm making some tests, but before I end up pasting a useless wall of text, there's something confusing me: I can't replicate the error message in the first comment.

I'm not getting the `Could not match type ... with type ...` error, but either `Type of expression contains additional label ...` or `Type of expression lacks required label ...`, which are actually good.

The only instance where I get a similar message is when there are both additional and missing labels, but it's still not printing the full records, but something like:
```
Could not match type

     ()

   with type

     ( baz :: Int
     | t0
     )
```

Is it because things where changed after this issue was opened, because it prints this message only in specific cases, or because I'm doing anything wrong?

Anyways, elm won't help us here. They just show the full records. The only extra thing they do, is that that they catch similar labels hinting that there could be a typo.

**Comment by LiamGoodacre** [comment]
@dariooddenino how far did you get with this?

To get an error similar to the original comment, you can do something like:

```purescript
h = [{a: 2, b: 3}, {b: 4, c: 5, d: 6}]
```

Which gives:

```
Could not match type
    ( a :: Int
    , b :: Int
    )
  with type
    ( c :: Int
    , d :: Int
    , b :: Int
    )
```

**Comment by dariooddenino** [comment]
@LiamGoodacre I had a bit of a rough month (with some vacations in between), so I wasn't able to do anything.
I'll put in some time on it this/next week, but If anyone else wants to work on it in the meanwhile, it's fine (obviously!) :)

**Comment by garyb** [comment]
I assumed what you're describing above is exactly what we wanted to do here :smile: (assuming both label and type are considered in the uniqueness) - what else would be meant by diffing in this context, just out of curiosity?

**Comment by dariooddenino** [comment]
If I'm not mistaken, when a label has a different type, a different error is shown already.

What I meant is that it seems to imply that the "diffs" are the actual rows, but maybe I'm overthinking this?
Also it would be cool to have something like:
```

**Comment by garyb** [comment]
Ok, I'm still not really sure what that means, but as long as you have an idea that's good! :grin:

I think aside from anything else we do, this thing of only keeping the unique labels would be a great improvement already.

**Comment by natefaubion** [comment]
I think it would be useful to show an ellipses or something to indicate that it's potentially a subset of the rows.

```
      Could not match type

        ( b :: Boolean
        ...
        )

      with type

        ( d :: Int
        ...
        )
```
