### ISSUE TITLE
Bower is deprecated now...

### ISSUE THREAD

**Issue by luochen1990** [purescript/purescript#3396]
> npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by garyb** [comment]
Consider https://github.com/purescript/psc-package instead if this worries you 🙂

**Comment by LiamGoodacre** [comment]
If anyone lands on this and has questions, see the comments here: https://github.com/purescript/purescript/issues/2231
