### ISSUE TITLE
How to export `show` of Purescript for JavaScript to call?

### ISSUE THREAD

**Issue by luochen1990** [purescript/purescript#3397]
Reproduce:
---

test.purs:
```
module Test (module Prelude) where

import Prelude
```

test.js
```
const Test = require('./.psci_modules/node_modules/Test')

console.log(Object.keys(Test))
console.log(Test.show(1))
```

Expected:
---

test.js works correctly

Observed:
---

test.js not works and following message is printed:

```
[]
TypeError: Test.show is not a function
```

And use something like `module Test (module Prelude, show) where` will cause `Cannot export unknown value show`.

**Comment by garyb** [comment]
Re-exports are just resolved as absolute names in the compiler, so they don't appear in the generated JS. We have an issue for it from a while back: #1888.

If you want to force it to be exported, at the moment you'd have to explicitly re-declare it:

```purescript

module Test (show) where

import Prelude as P

show :: forall a. Show a => a -> String
show = P.show
```

It's also worth noting that you won't be able to just call `Test.show(1)` in JS either, as `Show` expects a dictionary argument too.
