### ISSUE TITLE
Types printed in error messages should probably have a maximum length

### ISSUE THREAD

**Issue by spicydonuts** [purescript/purescript#3401]
Extremely long error messages can take minutes to print to the terminal and the useful bits at the top usually end up getting dropped.

Can work around by piping to a file: `pulp build 2> error.log`

**Comment by paf31** [comment]
The issue here is specific to type class instance errors. Types do get shortened in unification errors, but apparently not in type class instances.

This should be a pretty easy fix, most likely changing a true to a false.

**Comment by hdgarrood** [comment]
> Types do get shortened in unification errors, but apparently not in type class instances.

I'm not sure this is the case. _Values_ get shortened, but types don't seem to. See e.g. https://github.com/purescript/purescript/blob/194d8645a61001094cab5faa26c350af55709d45/src/Language/PureScript/Errors.hs#L1094-L1102:

We use `valueDepth` to control how much of the relevant value is printed, and we're using the maximum depth argument provided by `Language.PureScript.Pretty.Values`, but `Language.PureScript.Pretty.Types` doesn't appear to provide a similar way of controlling the depth to which we print.

**Comment by paf31** [comment]
Oh ok. Well I think it'd be nice to be able to control the depth if possible. We have errors which (no exaggeration) take _minutes_ to print out to the console when you get your types wrong.

**Comment by hdgarrood** [comment]
Yes, I absolutely agree. (In fact the reason I posted here is that I stumbled across some of these errors today!)
