### ISSUE TITLE
--jobs flag for compile

### ISSUE THREAD

**Issue by Profpatsch** [purescript/purescript#3403]
It would be nice to have control over the amount of parallelism `purs compile` uses. In my case I’d like to reduce to `-j1` because the parallelism is already provided by another tool.

**Comment by garyb** [comment]
You can do that already using `+RTS -N1`.

**Comment by kRITZCREEK** [comment]
@garyb That's going to reduce the number of threads to 1, but we're still going to be compiling things concurrently. (Not sure which of the two is asked for here)

@Profpatsch you could also try to compile without `-threaded` to get the leaner single-threaded runtime if you don't need the threading capabilities.

**Comment by kRITZCREEK** [comment]
Seems like this can be closed then.
