### ISSUE TITLE
Pulp (and other tools) should use binaries from local node_modules when available

### ISSUE THREAD

**Issue by mnn** [purescript/purescript#3406]
I think it is considered bad practise to rely on globally installed packages, mainly because there can be instances when different projects use different versions of these packages (executables - in this case `purs`) and when you have installed them globally it means you cannot work on these two (or more) projects at a same time (well, you could have different `PATH` for every project, but that's not great to use).

```
$ ls node_modules/.bin/purs
node_modules/.bin/purs
$ node_modules/.bin/pulp test
* ERROR: `purs` executable not found.
```

(Binaries from local `node_modules` can be easily run via `npx` - e.g. `npx pulp test`.)

**Comment by justinwoo** [comment]
You should actively choose what you want to use yourself. If you want to use binaries from your project node modules, you should set your PATH

```
export PATH="./node_modules/.bin:$PATH"
```

**Comment by mnn** [comment]
I am not sure how safe this solution is, since global packages must be installed as root and also you can have malicious executables hidden in `node_modules/.bin` in some other directories. I don't want running an e.g. `ls` from some directory, which happen to contain `node_modules/.bin/ls`, so in effect a system utility `ls` is replaced by random executable named same. Also how would you handle when you do want to run a globally installed package, when you have at a same time installed different version of the package locally (local version will always mask the global one)?

I have re-tested it and now it seems to work with the `npx` tool, missing `package.json` might be the reason why it didn't see executables from local packages. It seems to work with script fields in `package.json` as well, so for my purposes it's fine. :slightly_smiling_face: 

But I would still recommend not to advice new users to install anything globally via npm when it doesn't need to be (which also means new users cannot use it at all if they don't have superuser rights - e.g. schools or big companies with strict IT rules) or adding `./node_modules/.bin` to a path env. variable, since it is similar security problem as adding `.`.

If you think those potential security problems are not important for you, feel free to close this issue (my problem was solved).

**Comment by LiamGoodacre** [comment]
Closing as is unrelated to the PureScript compiler (node & npm aren't required by purs) and there are solutions like npx, npm package scripts, PATH, etc.  The npm package is maintained separately, as is pulp.  If you want to suggest feature requests to those, please open issues on their respective repositories.
Could you mention where you saw a recommendation to install globally via npm?  Thanks.

**Comment by mnn** [comment]
> Could you mention where you saw a recommendation to install globally via npm? Thanks.

On your main page http://www.purescript.org/ :smile: 
![purescript - mozilla firefox_002](https://user-images.githubusercontent.com/1975567/43676542-be896302-97f3-11e8-9caf-24bcab929943.png)

and quick start guide https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md
