### ISSUE TITLE
Different syntax-sugared strings cannot be appended: Types do not unify

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3408]
Running this code using Purescript `0.12.0` produces this error:
```purescript
string_syntax_sugar :: String
string_syntax_sugar = 
   "multi-line\
   \string" <> """appended to different syntax sugared string"""
```
error:
```
Could not match type
            
      String
            
    with type
            
      String
            
  while checking that type String
    is at least as general as type String
  while checking that expression (append "multi-line") ((append "string") "appended to different syntax sugared string")
    has type String
  in value declaration string_syntax_sugar

  See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
  or to contribute content related to this error.

```

**Comment by JordanMartinez** [comment]
The above bug might be misleading as I'm getting a compiler error when just using the triple-quote string syntax sugar:
```purescript
string_syntax_sugar_triple_quote :: String
string_syntax_sugar_triple_quote = """a"""
```
Error:
```
Could not match type
          
    String
          
  with type
          
    String
          

while checking that type String
  is at least as general as type String
while checking that expression "a"
  has type String
in value declaration string_syntax_sugar_triple_quote

See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
or to contribute content related to this error.
```

**Comment by hdgarrood** [comment]
The only way I've managed to reproduce this if the module also contains some other declaration like `data String = String Unit`.

**Comment by garyb** [comment]
I'm almost 100% sure that that ☝️ must be the case. We don't have multiple types of `String` anywhere, the difference between `"` and `"""` strings is handled purely in the parser.

I'd imagine the first case is nothing to do with the append, but is like the second case, and is happening due to the annotation.

**Comment by JordanMartinez** [comment]
Yeah that's definitely the case.
There's a "data String" in scope. I'll need to change that to String_

Context: I'm making a repo that has compileable documentation using
meta-language as a way to learn Purescript and verify my understanding of
its syntax.
In the file where I talk about primitive types, I decided I should include
the syntax sugar for strings since it relates to that file's content.

On Aug 7, 2018 3:38 AM, "Gary Burgess" <notifications@github.com> wrote:

I'm almost 100% sure that that ☝️ must be the case. We don't have multiple
types of String anywhere, the difference between " and """ strings is
handled purely in the parser.

I'd imagine the first case is nothing to do with the append, but is like
the second case, and is happening due to the annotation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/purescript/purescript/issues/3408#issuecomment-411013394>,
or mute the thread

**Comment by hdgarrood** [comment]
Thanks for the update. In that case, this is intended behaviour. The error message could certainly be improved, of course. We have an issue for that: #1647

**Comment by JordanMartinez** [comment]
Thanks for your help in troubleshooting this and linking to that issue.
