### ISSUE TITLE
Feature expressions / reader conditionals (sharing code across backends)

### ISSUE THREAD

**Issue by jjl** [purescript/purescript#3412]
Now that there are several purescript backends, it would be nice to start sharing code between backends.

In Haskell, we'd probably use the C preprocessor to selectively compile code dependent on backend. In lisp there are reader conditionals. What should we have for purescript?

**Comment by hdgarrood** [comment]
The FFI is already designed to be able to support multiple backends: if you use the FFI in `MyModule.purs`, you can then provide JS implementations in `MyModule.js`, Erlang implementations in `MyModule.erl`, and so on. If you want to branch based on which backend you're using in PureScript code, that can be achieved via a library: something like `foreign import currentBackend :: String` in the `purs` file, together with `exports.currentBackend = "JavaScript";` in the JS file, and so on.

**Comment by jjl** [comment]
Ah yeah, it hadn't occurred to me to do the latter. Thanks!
