### ISSUE TITLE
Question: type-level records?

### ISSUE THREAD

**Issue by chrisdone** [purescript/purescript#3413]
Has anyone considered adding support to use record syntax at the type-level?

For example:

```haskell
data Component (h :: Type -> Type -> Type) (f :: Type -> Type) i o (m :: Type -> Type)
```

> h is the type that will be rendered by the component, usually HTML
>f is the query algebra
>i is the input value type that will be mapped to an f whenever the parent of this component renders
>o is the type for the component's output messages
>m is the monad used for non-component-state effects

This comes from Halogen. I have a similar problem with Duet, my small Haskell compiler. How do we make types like this more readable? I'd like to be able to write e.g.: (making up random syntax)

```haskell
data Component <surface, query, input, output, monad>
```

So then instead of types looking like these:

```haskell
myButton :: forall m. H.Component HH.HTML Query Unit Message m

eval :: Query ~> H.ComponentDSL State Query Message m
```

it'd look like:

```haskell
myButton :: forall m. 
  H.Component<surface: HH.HTML, query: Query, input: Unit, output: Message, monad: m>

eval :: Query ~> H.ComponentDSL<state: State, query: Query, output: Message, monad: m>
```

The same kind of thing applies to e.g. conduit from Haskell world.

-------

Incidentally it could have interesting applications for type-classes:

```haskell
data Either<left, right> = Left left | Right right
```
and then you could partially apply to re-use existing positional class instances, to make an instance of Functor on the Left of an Either (not for a good reason, but they exist):

```haskell
instance Functor Either<right> where
  fmap f (Left a) = Left (f a)
  fmap _ (Right c) = Right c
```
or otherwise be radical and invent class instances which let you specify the parameters:
```haskell
class Functor t<element | r> where
 fmap :: forall a b. (a -> b) -> t<element: a | r> -> t<element: b | r>

instance Functor Either<left=element|r> where ...

class Bifunctor t<first, second | r> where
 first  :: forall a b. (a -> b) -> t<first: a | r>  -> t<first:  b | r>
 second :: forall a b. (a -> b) -> t<second: a | r> -> t<second: b | r>

instance Functor Either<left=first, right=second|r> where ...
```
-----

Has there been any discussion or research like this? I feel like PureScript is a step forward in avoiding [complecting](https://www.youtube.com/watch?v=rI8tNMsozo0&t=24m10s) which we suffer from in Haskell at the value level, but at the type-level it can be a bit lacking.

**Comment by garyb** [comment]
That's pretty interesting, I don't think anyone has discussed or proposed it before that I'm aware of.

We looked into using a row type to do something similar as your proposal for Halogen's types here, but there are a bunch of things that made it difficult - all the types needing to have the same kind, having to use trickery to project the types out of the row at the named field, etc. A type-level record kinda thing might well have enabled us to solve those problems more naturally.

**Comment by garyb** [comment]
I like `surface` as a better name for `h` by the way, will probably steal that :smile:

**Comment by justinwoo** [comment]
What was the objection to using a row type with a bunch of proxies anyway?

**Comment by LiamGoodacre** [comment]
Here's an example using a row for the arguments to Star:
```purescript
data FProxy (f :: Type -> Type) = FProxy

class RowEquals (lhs :: # Type) (rhs :: # Type) | lhs -> rhs, rhs -> lhs
instance rowEqualsRefl :: RowEquals x x

-- normal: Star f i o ~= (i -> f o)
-- with row: Star (context :: FProxy f, input :: i, output :: o) ~= (i -> f o)
data Star (args :: # Type) =
  Star (forall r .
    (forall f i o .
      RowEquals args (context :: FProxy f, input :: i, output :: o) =>
      (i -> f o) -> r) ->
    r)

runStar :: forall f i o . Star (context :: FProxy f, input :: i, output :: o) -> i -> f o
runStar (Star f) = f \i -> unsafeCoerce i -- cba to prove

mkStar :: forall f i o . (i -> f o) -> Star (context :: FProxy f, input :: i, output :: o)
mkStar f = Star \onStar -> onStar f

mapStar ::
  forall f g i x y o .
  Functor g => (f ~> g) -> (i -> x) -> (y -> o) ->
  Star (context :: FProxy f, input :: x, output :: y) ->
  Star (context :: FProxy g, input :: i, output :: o)
mapStar fg ix yo cxy = mkStar (map yo <<< fg <<< runStar cxy <<< ix)
```

Seems a bit too awkward to use though.

**Comment by chrisdone** [comment]
@LiamGoodacre Nice! I was hoping something like this was doable.

**Comment by LiamGoodacre** [comment]
@chrisdone, assuming you're happy with the above solution, shall we close this?

**Comment by chrisdone** [comment]
Sure!
