### ISSUE TITLE
purs docs breaks when using Applicative do notation

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3414]
I'm not sure why but here is a minimal test case:

```purescript
module Main where
  
map f x = f x

test = 
  ado x <- 1
   in x
```

`purs compile Main.purs` works fine (with warnings) but `purs docs Main.purs` fails.

**Comment by hdgarrood** [comment]
> Here's an option: in purs docs, we require that up-to-date externs files exist for all of the input files passed, and for any declarations which do not have type signatures, we get the types from the externs files. Then there shouldn't be a case where purs compile works but not purs docs.

Does anyone have any objections to this? If not I'll go ahead and try implementing it.

**Comment by hdgarrood** [comment]
#3264 is the other example I had in mind, incidentally
