### ISSUE TITLE
How do I state the type of this function with records?

### ISSUE THREAD

**Issue by chrisdone** [purescript/purescript#3415]
E is an expression in some language, the r might contain location information or something like that.
```haskell
data E r = E r
data Typ
generate :: forall r. E r -> E { typ :: Typ | r }
generate = ?x
```
I want that the E type already contains some record, that we don't know. Then generate is going to insert an additional type annotation of everything in E as the field typ :: Typ. Is this achievable with PureScript's type system?

Currently I keep getting `Type` vs `# Type` kind errors with the above.

**Comment by justinwoo** [comment]
Type vs # Type: curly brace is record, so `{ a :: Int }` is `Record (a :: Int)`, where `Record` is `# Type -> Type` https://pursuit.purescript.org/builtins/docs/Prim#t:Record

Contains some unknown record? As in will be determined later? Then maybe you want Row Union: https://pursuit.purescript.org/builtins/docs/Prim.Row#t:Union

This question is probably better answered on Slack/Discourse/IRC

**Comment by hdgarrood** [comment]
In your `generate`, the first occurrence of `r` (in `E r`) forces the kind of `r` to be `Type`, because of how `E` is defined. However, the second occurrence of `r` would need to have kind `# Type`. Perhaps you want `data E r = E (Record r)` instead so that the kind of `r` can be `# Type` throughout? I'll close this, as this does not appear to be a compiler issue.

**Comment by chrisdone** [comment]
@hdgarrood @justinwoo  Sorry, I could've provided more info but I was stepping out and was hoping the answer was more obvious. 

> In your generate, the first occurrence of r (in E r) forces the kind of r to be Type, because of how E is defined. Perhaps you want data E r = E (Record r) instead so that the kind of r can be # Type throughout? I'll close this, as this does not appear to be a compiler issue.

It seems not to make a difference whether E's `r` has the proper kind or not.  Here's what I tried:

## Using Record

```haskell
module X where
data E r = E (Record r)
data Typ
generate :: forall r. E r -> E { typ :: Typ | r }
generate = ?x
```
```
 X.purs     Could not match kind # Type with kind  Type
```

## With a kind signature

```haskell
module X where
data E (r :: # Type) = E (Record r)
data Typ
generate :: forall r. E r -> E { typ :: Typ | r }
generate = ?x
```
```
 X.purs     Could not match kind # Type with kind  Type
```

You can paste these examples into a `X.purs` and run it. I

I don't know whether what I'm doing just doesn't make sense, or whether it's a compiler bug. Can you clarify that what I'm writing above doesn't make sense and what I'm misunderstanding? I feel like the kind inference is confused, but I'm happy to be wrong. 

@justinwoo 

> Contains some unknown record? As in will be determined later? Then maybe you want Row Union: https://pursuit.purescript.org/builtins/docs/Prim.Row#t:Union

Thanks, I feel like that, and along with the purescript-records package will probably be my best way of modelling this problem. However I am still very curious why my example above fails with a kind error.

**Comment by chrisdone** [comment]
The following is not a kind error:

```
module X where
data E (r :: # Type) = E (Record r)
data Typ
generate :: forall r. E r -> E ( typ :: Typ | r )
generate = ?x
```

What's the difference between `( typ :: Typ | r )` and `{ typ :: Typ | r }`? :confused: 

@justinwoo The following models my problem properly:

```haskell
module X where
import Data.Symbol (SProxy(..))
import Prim.Row (class Lacks)
import Record (insert)
data E r = E (Record r)
data Typ = Typ
generate :: forall r. Lacks "typ" r => E r -> E ( typ :: Typ | r)
generate (E r) = E (insert (SProxy :: SProxy "typ") Typ r)
```

If I change  `( typ :: Typ | r )` to `{ typ :: Typ | r }` then I reproduce the kind error here too. What's all that about?

**Comment by chrisdone** [comment]
Oh, wait. I understand now. { foo } is `Record foo` where `foo :: #`. So `E { ..}` is `E (Record ..)` when I should have used `E (...)`. That's the source of my confusion.
