### ISSUE TITLE
Bower can't connect and take purescript-console package

### ISSUE THREAD

**Issue by mosleymos** [purescript/purescript#3421]
I'm trying to install purescript and got this error.

``` shell
bower EINVRES       Request to https://bower.herokuapp.com/packages/purescript-console failed with 502
```
So the server got a problem, is there another way to install this package ?

**Comment by justinwoo** [comment]
If you load that link, there's a warning https://bower.herokuapp.com/packages/purescript-console

> This Bower version is deprecated. Please update it: npm install -g bower. The new registry address is https://registry.bower.io

**Comment by mosleymos** [comment]
I see. I've updated my local bower and pulp and it's work.
Purescript seem's interesting.

Thanks

**Comment by mosleymos** [comment]
I'll do some projects. I'm closing the issue.
