### ISSUE TITLE
Add `Prim.TypeError.QuoteLabel`

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3428]
It would be nice if there was a primitive quote/escape a symbol that is meant to be a label/property.

**Comment by LiamGoodacre** [comment]
I am happy for this to exist. 👍 

To elaborate for anyone wanting to try implementing this:

Examples of row and record labels are:
1. Regular, no need to quote: `foo`  or `"foo"` or `"""foo"""`
2. Special chars, need to quote: `"f o o"` or `"""f o o"""`
3. Special chars with escaping, need to quote: `"a\"b"` or `"""a"b"""`

This ticket is about extending the `Prim.TypeError.Doc` kind with a new data type `QuoteLabel :: Symbol -> Doc`.
This should then be interpreted by both the `Prim.TypeError.Warn` and `Prim.TypeError.Fail` type classes (in the compiler), to print the quoted symbol as a label with appropriate escaping as necessary.  Note that this escaping already happens elsewhere in the code.

**Comment by dariooddenino** [comment]
I'm giving a try at this. I'm mostly stumbling in the dark, but I guess I'm almost there

**Comment by LiamGoodacre** [comment]
@dariooddenino thanks for taking a look!

For `Warn (QuoteLabel "ba\"oo")` I would expect `"ba\"oo"` as the output.
For `Warn (QuoteLabel "hello")` I would expect `hello` as the ouput.

There should already be a function to do the printing/escaping for you in the pretty printer.

To write your `baz { hello: 1 }` example, you could do something like:
```purescript
bar ::
  forall row label typ .
  RowToList row (Cons label typ Nil) =>
  Warn (QuoteLabel label) =>
  Record row ->
  String
bar _ = ""

foo = bar { hello: 42 }
```

Feel free to open a work-in-progress pull request and we can discuss more there?

**Comment by dariooddenino** [comment]
Ugh, I was overcomplicating it. Yeah, I saw the pretty printing functions but first I wanted to clear these doubts.
I will try to open a pull request tomorrow (hopefully with everything already done!)

Thanks
