### ISSUE TITLE
Add codegen targets to `purs ide server`

### ISSUE THREAD

**Issue by paluh** [purescript/purescript#3447]
@kRITZCREEK already suggested that this option should __probably__ be handled on the protocol level by `Rebuild` command.

---
I'm pasting here also some hacking hints by @kRITZCREEK. I think that these suggestions can be useful to anybody who wants to work on this:

The actual change that needs to happen is that `defaultOptions` in here: https://github.com/purescript/purescript/blob/2bf6ba192b368ea3aa895abb02a5c484cb4e0c27/src/Language/PureScript/Ide/Rebuild.hs#L72
needs to have its `optionsCodegenTargets` field overwritten with user specified values.
For example to force `coreFn` generation we can change this line to:
``` haskell
. P.runMake (P.defaultOptions {P.optionsCodegenTargets = Set.fromList [P.JS, P.CoreFn]})
```

**Comment by kRITZCREEK** [comment]
If you want to work on this ping me and I'll list the different parts of the code that'll need to be touched. If noone picks this up before the next minor release I'll do it myself though as I really want to have it :)

**Comment by kRITZCREEK** [comment]
Allright, noone's picked this up for hacktoberfest, so I'll do it :)
