### ISSUE TITLE
PSCi :kind fails to parse type operators

### ISSUE THREAD

**Issue by rndnoise** [purescript/purescript#3455]
This seems to be a parse error rather than an issue with `(~>)` being declared as a type operator. It might be also the case that it won't work anyway, since `:kind NaturalTransformation` fails because it's a type synonym and I haven't provided all its arguments.

```
> :kind (~>)
(line 1, column 2):
unexpected ~>
expecting type
```

**Comment by hdgarrood** [comment]
I think this is actually a duplicate of #3107, since e.g.

```purescript
type Foo = (~>)
```

also fails (both within a source file and in the repl).
