### ISSUE TITLE
Improve generic deriving's JS output for long sum types

### ISSUE THREAD

**Issue by ad-si** [purescript/purescript#3475]
```purescript
data Digit
  = D000 | D001 | D002 | D003 | D004 | D005 | D006 | D007 | D008 | D009
  | D010 | D011 | ...

derive instance genericDay :: Generic Day _
instance showDay :: Show Day where show = genericShow
```

With a few dozen of those it takes minutes to compile.
With several dozen it crashed my Mac with a kernel panic 😳.

This, however, isn't particular surprising after looking at the JavaScript code:

```js
var genericDay = new Data_Generic_Rep.Generic(function (x) {
    if (x instanceof D001) {
        return new Data_Generic_Rep.Inl(Data_Generic_Rep.NoArguments.value);
    };
    if (x instanceof D002) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(Data_Generic_Rep.NoArguments.value));
    };
    if (x instanceof D003) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(Data_Generic_Rep.NoArguments.value)));
    };
```
This is growing sideways pretty fast and generates a lot of JavaScript 😅.
Sorry it this is already a known problem, but I couldn't find anything in the issue tracker.

**Comment by natefaubion** [comment]
Really large sums are always going to be problematic for various reasons. One option is to use either a tree representation, or even just something more compact.

```purescript
data D = D0 | D1 | D2 | D3 | D4 | D5 | D6 | D7 | D8 | D9
data P2 = P2 D D
data P3 = P3 D D D
```

**Comment by ad-si** [comment]
I was actually using this for days: `data Day = D001 | D002 | … | D364` which is a really stupid series for simplification 😅

**Comment by hdgarrood** [comment]
I don't want to rule this out entirely, but it's not immediately clear to me how we might implement a version of `generics-rep` which provides more efficient runtime representations for large sums while still enabling straightforward matching on cases via instance selection (which is what many of the various use cases of `generics-rep` rely on). Given that (as @natefaubion pointed out) you probably don't want huge sum types anyway, and also given that we don't yet have a concrete proposal for how to achieve this, I'm going to close this for now. We can discuss further if someone puts a concrete proposal together.
