### ISSUE TITLE
Remove derived JSON instances for Type

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3494]
#3484 added annotations to `Type` which technically breaks compatibility since the JSON instances are derived. We should remove these and do something similar to what we've done with the `Kind` codecs before the next release.

**Comment by hdgarrood** [comment]
refs #2655

**Comment by hdgarrood** [comment]
aeson-better-errors only deals with the parsing direction; I think we generally use standard aeson for producing json, and aeson-better-errors for parsing it. The ide code seems to use standard aeson for both directions, though. There's not any huge reason to prefer one over the other these days, I don't think, as a little while after I first released aeson-better-errors, aeson's own errors improved to be more or less on par with it. The one thing I would say is that I think aeson-better-errors' API is a bit better suited for hand-written instances.
