### ISSUE TITLE
Doc-comments for typeclass methods are not included in the generated docs

### ISSUE THREAD

**Issue by Dretch** [purescript/purescript#3507]
For example, given this module:

```purescript
module MethodDocs where

import Prelude

-- | Adds drama to the given text.
dramaFunction :: String -> String
dramaFunction s = s <> "!"

class Drama t where
  -- | Adds drama to the given value.
  dramaMethod :: t -> t
```

The following docs are generated - with docs for the function, but not the method:

#### `dramaFunction`

``` purescript
dramaFunction :: String -> String
```

Adds drama to the given text.

#### `Drama`

``` purescript
class Drama t  where
  dramaMethod :: t -> t
```

It is possible to workaround this issue to some degree by including the method docs in the docs for the class itself. However, this is a bit annoying when refactoring functions to make them methods, and starts to become impracticable with more than a couple of methods per class.

As precedence, Haskell has this feature in its docs generation, e.g. http://hackage.haskell.org/package/base-4.12.0.0/docs/Text-Show.html

**Comment by hdgarrood** [comment]
Yes, I'd like to do this too. I'd also like to do it for data constructors and potentially even record fields in type synonyms. For example, declarations like [React.Basic.ComponentSpec](https://pursuit.purescript.org/packages/purescript-react-basic/6.2.0/docs/React.Basic#t:ComponentSpec) would benefit a lot from this.

I think we'd need to do https://github.com/purescript/purescript/issues/2216 first.

**Comment by JordanMartinez** [comment]
@hdgarrood I believe the `0.13.3` release closes this issue, correct?

**Comment by hdgarrood** [comment]
Yes, thanks!
