### ISSUE TITLE
0.12.2 Release

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#3508]
Intended release date: 13th Jan

---

Possible things to include still:

- [x] #3500 Add named type wildcards
- ~#3446 Deriving `Hashable` (@kRITZCREEK mentioned he was going to look into this more in hopes of getting it in. Will also need a new non-breaking `Prelude` release)~

---

Post-release tasks:

- [x] Publish to Hackage
- [x] Update npm package

---

# New features

- Named type wildcards (#3500, @natefaubion)

  It's now possible to use `?hole` style syntax in type signatures where you want the compiler to tell you the missing type. This was previously possible by using `_` in a type signature, but now `_` can be used without raising a warning, as long as it does not appear in a top level declaration.

# Enhancements

- Improve error message for missing node.js in the repl (#3456, @justinwoo)
- Add `Boolean` kind to `Prim.Boolean` (#3389, @justinwoo)
- Link to documentation repo as docs for non-Prim built-in types/kinds (#3460, @JordanMartinez)
- PSCi: Support multiple command types in paste-mode (#3471, @LiamGoodacre) 
- Add `row:column` printing for source positions in error messages (#3473, @justinwoo) 
- Add `:print` directive for customizable repl printing (#3478, @hdgarrood) 
- Implement qualified `do` (#3373, @pkamenarsky)
- Add better source positions to kind errors (#3495, @natefaubion)

# Fixes

- Remove references to previous kinds `*` and `!` (#3458, @LiamGoodacre)
- Fix linting of unused type variables (#3464, @LiamGoodacre)
- Avoid dropping super class dicts for the same class (#3461, @LiamGoodacre)
- Fix issue where `Partial` can foil TCO optimizations (#3218, @matthewleon)
- Fix quoting of record labels in error messages (#3480, @hdgarrood)
- Prevent invalid JS being generated from awkward record labels (#3486, @hdgarrood)
- Fix unnecessary quoting of reserved names when used as labels (#3487, @hdgarrood) 
- Fix source spans for binding groups (#3462, @LiamGoodacre)
- Fix kind error for recursive data type (#3511, @natefaubion) 

# Other (internals)

- Add annotations to `Type` and `Kind` (#3484, @natefaubion)
- Use handwritten JSON instances for `Type`/`Kind` (#3496, @natefaubion)
- Remove pretty print constructors from `Type` (#3498, @natefaubion) 
- Add JSON compatibility tests (#3497, @hdgarrood)
- Remove the concept of the 'current module' in Docs (#3506, @hdgarrood) 

---

Let's try and do the 6-week release schedule after this, meaning the next one will be on the 24th of Feb, unless anyone objects / thinks we should do 8-week or something?

**Comment by justinwoo** [comment]
Hopefully #3416 can be here too? :)

**Comment by justinwoo** [comment]
Note #3389 requires https://github.com/purescript/purescript-typelevel-prelude/pull/41, but I guess after that merge no consumers are affected (only a library upgrade should be required?)

**Comment by hdgarrood** [comment]
> Let's try and do the 6-week release schedule after this, meaning the next one will be on the 24th of Feb, unless anyone objects / thinks we should do 8-week or something?

Sounds good to me. We can always adjust the schedule after trying it if we think 6 weeks ends up being too little, I guess. Also now that I'm no longer a student and I'm using PureScript at work (:tada:) it should be easier for me to devote a bit more time to maintenance tasks; in particular I'd be keen to help with any of the various admin stuff involved in making a release. (Although I suppose there won't be too much of that this time, because we're not breaking anything?)

**Comment by garyb** [comment]
Yeah, there shouldn't be anything on this one really. We don't need to update Pursuit or anything do we? As there were those changes to the JSON stuff - or was that ensuring it wouldn't actually change? :smile:

**Comment by hdgarrood** [comment]
Yeah, the intention was that Pursuit should continue to be able to parse the existing data (I'll check this now). It is worth updating Pursuit to depend on purescript-0.12.2 once it's out so that #3460, #3389, and #3458 are reflected on pursuit.purescript.org too.

**Comment by hdgarrood** [comment]
I've just compiled Pursuit against the current `master` and it works beautifully :) once 0.12.2 is tagged, I'll tag a version of Pursuit which depends on it.

**Comment by joneshf** [comment]
> I'm no longer a student and I'm using PureScript at work

Just stopping by to say, congrats @hdgarrood!
