### ISSUE TITLE
Incorrect error when trying to derive instances for type synonyms

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3510]
For example:
```purescript
module Main where
import Prelude (class Eq)
type T = {}
derive instance eqT :: Eq T
```
Currently gives you
> `CannotFindDerivingType`: "Cannot derive a type class instance, because the type declaration for T could not be found."

Perhaps 

> `TypeSynonymInstance`: "Type class instances for type synonyms are disallowed."

would be more appropriate?

**Comment by rhendric** [comment]
For anyone following along here but not in recent PRs: as of today, type class instances for type synonyms *are* allowed, but attempting to derive them still produces the above error. Per discussion in #3940, this may be resolved by changing the proposed error message to specifically identify derived instances for type synonyms as unsupported, or by actually supporting deriving instances for type synonyms.
