### ISSUE TITLE
Possible bug in apartness checking

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3531]
Consider the following program:
```purescript
module Main where

import Prelude

import Effect.Class.Console (log)
import Prim.TypeError (class Fail, Beside, Quote, Text)

class C x where
  thing :: x -> x

data X a b = X

test1 :: forall a. X a Unit
test1 = X

instance cx :: C (X x x) where
  thing = identity

else instance cxFail ::
  Fail
    (Beside
      (Beside (Text "Fell through: x ~ ") (Quote x))
      (Beside (Text ", y ~ ") (Quote y)))
      => C (X x y) where
  thing = identity

main = do
  let X = thing test1
  log "Done"
```
It fails to pass type checking, with the following error:
```
Compiling Main
[1/1 NoInstanceFound] src/Main.purs:28:7

  28    let X = thing test1
            ^^^^^^^^^^^^^^^
  
  A custom type error occurred while solving type class constraints:
  
    Fell through: x ~ t1, y ~ Unit
  
  while applying a function thing
    of type C t0 => t0 -> t0
    to argument test1
  while inferring the type of thing test1
  in value declaration main
  
  where t0 is an unknown type
        t1 is an unknown type
```

However, my understanding is that the `cx` instance should be selected, and that we should only be able to fall through to the next instance once we can ensure that the two type variable arguments to `X` are apart. In this case, they are not, since `t1` could unify with `Unit`.

**Comment by paf31** [comment]
I'm seeing a similar bug where the type checker is falling through to a catch-all instance when trying to find an instance for a skolem type variable, even though the apartness check should cause it to fail on the first instance. Something like this:

```purescript
class C a where
  c :: Proxy a -> Unit

instance c1 :: C String where
  c _ = unit
else instance c2 :: C a where
  c _ = unit

fn :: forall a. Proxy a -> Int
fn _ = 42 where
  x = c (Proxy :: Proxy a) -- this chooses c2 but should fail the apartness check for c1
```

**Comment by hdgarrood** [comment]
@paf31 so I guess that program should produce a type error? If so, what should it say? I don't think "Cannot find instance `C a`" is enough, since there clearly is a catch-all instance in the chain; I guess we'd want to include additional explanation along the lines of "can neither match `a` with `String`, nor prove that `a` is apart from `String`"? IIRC the paper doesn't discuss this case.

**Comment by paf31** [comment]
I think it's probably fine to say something like "the instance for `C a` is ambiguous due to unverifiable apartness constraints", or you know, something friendlier.

**Comment by paluh** [comment]
I have a scenario (@hdgarrood suggested that it can be attached here) when a change in the order of instances in instance chain causes match failure. The below version matches instance `matchAInt` but when I change the order of two instances matchAInt and matchIntA I get `No type class instance was found...`:

```purescript
module Main where

import Prim.TypeError (class Fail, Text)
import Unsafe.Coerce (unsafeCoerce)

class Match a b

instance matchSameType :: (Fail (Text "Matched a a")) => Match a a

else instance matchAInt :: (Fail (Text "Matched a Int")) => Match a Int

else instance matchIntA :: (Fail (Text "Matched Int a")) => Match Int a

else instance matchArray :: (Match a b) => Match (Array a) (Array b)

coerce :: forall a b. Match a b => a -> b
coerce a = unsafeCoerce a

x :: Array Int
x = coerce []
```
I've also created two separate gists which shows this problem "live": 

https://try.purescript.org/?gist=b43c227abcc97e9743d341bafe316049
https://try.purescript.org/?gist=0357b62c934b437a9ca1f9028ab67abd
