### ISSUE TITLE
Pulp compile dependency

### ISSUE THREAD

**Issue by knaman2609** [purescript/purescript#3542]
I have a Utils file which has a lot of functions. Its being imported in almost all the other files. Right now changing Utils file cause all the other files to recompile.

Even though i am importing specific functions in other files for eg. `import Utils (toNumber)`. All the other files are getting recompiled which are importing utils file but not this function.

Is there fix for this? Or do i need to restructure what i put in Utils file?

**Comment by hdgarrood** [comment]
These kinds of questions are better suited to the [Discourse forum](https://discourse.purescript.org), so please ask there in future. To answer your question though, yes, you will need to restructure your Utils file if you want faster builds; we have no plans to make compilation units more granular than modules at the moment.
