### ISSUE TITLE
can't install purescript

### ISSUE THREAD

**Issue by sagax** [purescript/purescript#3544]
command
```
npm install -g purescript
```

simple log https://termbin.com/yene
complete log https://termbin.com/kzs7

- linux kernel 4.15.13-1-default
- node v8.12.0
- npm 6.4.1

**Comment by justinwoo** [comment]
This should be reported to https://github.com/purescript-contrib/node-purescript/

**Comment by shinnn** [comment]
@justinwoo No.

**Comment by justinwoo** [comment]
The binary I download from the release works via three ways:

* I am able to download the binary from the archive and run it

```
[bash:~/Downloads] > l purs
-rwxr-xr-x 1 justin justin 43M Feb 24 23:46 purs
[bash:~/Downloads] > ./purs
Usage: purs COMMAND
  The PureScript compiler and tools
# ...
```

* I am able to install purescript in a new project https://github.com/justinwoo/purs-test:

```
> command -v purs
./node_modules/.bin/purs
> purs --version
0.12.3
```

* I am able to use the binary from the archive, patching in zlib, gmp, and ncurses5: https://github.com/justinwoo/easy-purescript-nix/blob/0debbe629de2c2d6278ba772e40a0851a57b9d2f/purs.nix#L29

**Comment by hdgarrood** [comment]
From https://github.com/purescript-contrib/node-purescript/issues/65:

>[purescript/purescript#3544 (comment)](https://github.com/purescript/purescript/issues/3544#issuecomment-467960791) is a wrong direction. You ran into two problems both of which are not directly related to this repository.

>    1. The prebuilt binary downloaded from https://github.com/purescript/purescript/releases/tag/v0.12.3 is not working.

>    2. `stack setup` command fails when using [PureScript's stack.yaml](https://github.com/purescript/purescript/blob/v0.12.3/stack.yaml)

@shinnn I've just checked on my own linux system and the v0.12.3 binary is working normally, so I don't think 1) is correct. I wonder if the download might have gone wrong somehow, or are you perhaps on a different architecture (i.e. 32-bit vs 64-bit)? @sagax can you try downloading the binary manually from that url and executing it? Also, can you paste the output of `uname -a`?

The `stack setup` failure happened while configuring GHC so I think it is highly unlikely that it has anything to do with our stack.yaml file. I suspect that is to do with your system. Unfortunately the output from GHC's `configure` script seems to have been suppressed, so you might want to try running it yourself?

**Comment by shinnn** [comment]
> ```
> /home/sagax_nb/local/bin/purs -> /home/sagax_nb/local/lib/node_modules/purescript/purs.bin
> 
> > purescript@0.12.3 postinstall /home/sagax_nb/local/lib/node_modules/purescript
> > install-purescript --purs-ver=0.12.3 .
> 
> [ SUCCESS ] Check if a prebuilt 0.12.3 binary is provided for Linux (5s)
> [ SUCCESS ] Download the prebuilt PureScript binary (5s)
> [ FAILURE ] Verify the prebuilt binary works correctly (628ms)
> Error: Command failed: /home/sagax_nb/local/lib/node_modules/purescript/purs.bin --version
> /home/sagax_nb/local/lib/node_modules/purescript/purs.bin: /home/sagax_nb/local/lib/node_modules/purescript/purs.bin: cannot execute binary file
>     at makeError (~/local/lib/node_modules/purescript/node_modules/execa/index.js:172:9)
>     at Promise.all.then.arr (~/local/lib/node_modules/purescript/node_modules/execa/index.js:277:16)
>     at <anonymous>
> 
> ↓ Fallback: building from source
> 
> [ SUCCESS ] Check if 'stack' command is available
> [ SUCCESS ] Download the PureScript 0.12.3 source (5s)
> [ RUNNING ] command: stack setup
>   Preparing to install GHC to an isolated location.
>   This will not interfere with any system-level installation.
>   Preparing to download ghc-8.4.3 ...
>   Already downloaded.
>   Unpacking GHC into /home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3.temp/ ...
>   Configuring GHC ...
>   Received ExitFailure 77 when running
>   Raw command: /home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3.temp/ghc-8.4.3/configure --prefix=/home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3/
>   Run from: /home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3.temp/ghc-8.4.3/
> [ FAILURE ] Ensure the appropriate GHC is installed (3m)
> Error: Command failed: stack --allow-different-user setup
> Preparing to install GHC to an isolated location.
> This will not interfere with any system-level installation.
> Preparing to download ghc-8.4.3 ...
> Already downloaded.
> Unpacking GHC into /home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3.temp/ ...
> Configuring GHC ...
> Received ExitFailure 77 when running
> Raw command: /home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3.temp/ghc-8.4.3/configure --prefix=/home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3/
> Run from: /home/sagax_nb/.stack/programs/i386-linux/ghc-8.4.3.temp/ghc-8.4.3/
>     at makeError (~/local/lib/node_modules/purescript/node_modules/execa/index.js:172:9)
>     at Promise.all.then.arr (~/local/lib/node_modules/purescript/node_modules/execa/index.js:277:16)
>     at <anonymous>
```

**Comment by hdgarrood** [comment]
@shinnn I did check the log. Notice that the error is "cannot execute binary file", which is why I suggested checking the architecture. See https://superuser.com/questions/435988/how-can-i-resolve-the-error-cannot-execute-binary-file. Does the node purescript package check that system architecture is correct?

**Comment by hdgarrood** [comment]
@shinnn also, it's not really fair of you to assume that @justinwoo didn't check the log either. Either way the fact that it works on both of our systems is useful context. Clearly the binary is not _totally_ broken, and so more investigation is needed to work out what's actually gone wrong.

**Comment by shinnn** [comment]
> Does the node purescript package check that system architecture matches the binary?

If INSTALL.md clearly states the required system architecture, of course it will. If there is no mention about it in the documentation, users and integrated tools generally don't assume the binary works only on 64-bit systems.

**Comment by hdgarrood** [comment]
The compiler should work on all the architectures that GHC supports. However, any given compiled binary will usually only work on one architecture. I think it's pretty rare for a single binary to run on more than one architecture in general.

In the case of our binaries, there are some pretty big clues in the file names: "linux64", "win64". Should I take that as a "no", the node purescript package doesn't check that the architecture matches the architecture the binary is expecting? If so, I think it should.

**Comment by hdgarrood** [comment]
Or at least, 32-bit binaries can often run on 64-bit systems, but not vice versa.

**Comment by shinnn** [comment]
> In the case of our binaries, there are some pretty big clues in the file names: "linux64", "win64".

Oh, that's exactly what I wanted to know. Then, with also considering

> Unfortunately the output from GHC's `configure` script seems to have been suppressed

I will add them to the npm package when I have time:

1. a step for checking the current system architecture
2. `--verbose` flag to `stack setup` command to receive more useful reports from users

Anyway, Thanks for taking your time to approve this is not actually a bug of the npm package but more like room for UX improvement of it and documentation improvement of this repository.

**Comment by hdgarrood** [comment]
I’m going to close this as it seems like this is not a compiler issue.

**Comment by shinnn** [comment]
Why this issue is closed? Though this is not a compiler issue in a sense, again, it's a documentation issue of *this* repository.

**Comment by hdgarrood** [comment]
Oh yes of course, thanks. I’ll update INSTALL.md later today.
