### ISSUE TITLE
Integrate purescript-cst

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3555]
https://github.com/natefaubion/purescript-cst is at the point where it can parse and compile anything you throw at it (modulo intended breaking changes). It's faster, has better error reporting for many cases that require a lot of backtracking in the current parser, and it can serve as a basis for tooling (formatter) and a grammar specification.

**Comment by natefaubion** [comment]
Fixes
* #2690 
* #3262 
* #3376 
* #3443 
* Many of the things in #3517 
* #3554

**Comment by natefaubion** [comment]
purescript-cst adds currently adds some stuff to account for a few of the things mentioned in #3517 so more code in the wild parses, but it can be removed (particularly stuff around `case` indentation).

**Comment by natefaubion** [comment]
This would also fix #3549.

Some other things it accounts for:
* `if/then/else` in `do` syntax. You can chain them without stair-stepping.
* It fixes error positions in general so they are the correct span and don't include whitespace/comments. This obviates the need for all the heuristics `psa` uses to find the minimal span for an error.
* It fixes the issue where the last token in a source file as the wrong span.

**Comment by natefaubion** [comment]
This also fixes some error ranges in #1801 which pertain to parsing. For example, errors around `=` or `:` in records always point to the exact token with a helpful error.

**Comment by hdgarrood** [comment]
Looks like the cst parser also fixes #3283.
