### ISSUE TITLE
Vulnerable version of Bower referenced in purescript/tests/support/package.json

### ISSUE THREAD

**Issue by VlkrS** [purescript/purescript#3564]
purescript/tests/support/package.json specifies "bower ^1.4.1"
Bower versions < 1.8.8 have an arbitrary file write vulnerability described here:
https://snyk.io/blog/severe-security-vulnerability-in-bowers-zip-archive-extraction/

The current purescript 0.12.3 archive from stackage comes with a test/support/package-lock.json that locks bower to version 1.8.4.

Can we consistently upgrade bower to 1.8.8 or later?

**Comment by hdgarrood** [comment]
Yes, that sounds sensible.
