### ISSUE TITLE
Deprecate and eventually remove the legacy resolutions format

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3573]
Following from #3499: we should start emitting warnings for the legacy (bower) json format for the resolutions file expected by `purs publish`, and eventually remove it entirely.

**Comment by thomashoneyman** [comment]
With #3499 in place, will `pulp publish` generate the new format? Or does it need to be generated another way? I'd like to get some of these Halogen libraries up on Pursuit.

**Comment by hdgarrood** [comment]
Pulp publish will generate the new format. I’m working on that already but haven’t quite gotten to a point where I can PR yet.

**Comment by hdgarrood** [comment]
We've been warning on this format since v0.12.4, so I'd like to remove it in v0.14.0.
