### ISSUE TITLE
Shrinking of types in Errors seems too aggressive

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#3577]
On current master, given:
```purescript
module Main where

import Data.Tuple.Nested (Tuple4)

something :: Tuple4 Int String Int String
something = ?y
```

I get the following compiler output:
```
Error found:
in module Main
at src\Main.purs:6:13 - 6:13 (line 6, column 13 - line 6, column 13)

  Hole 'y' has the inferred type

    Tuple Int (Tuple String (... ... (... ...)))

  You could substitute the hole with one of these values:

    Main.something  :: ... ... String Int String

in value declaration something
```

This strips away relevant information for the inferred type (I need to know all the fields to build such a Tuple) and weirdly enough seems to strip depth the other way around when printing the type for the hole.

This is a minimal example, but I've hit this a lot at work when doing things with Halogen or Codecs, where the stripping removes whether my hole is a `HTML` or `Component` and just leaves me with type parameters.

**Comment by hdgarrood** [comment]
I think what's going on there is that if you have a type like `Tuple4 Int String Int String` then it's parsed as `(((Tuple4 Int) String) Int) String`, so it sort of makes sense (even though what you end up with isn't very helpful). I think we could address this by increasing the default depth and by treating nested TypeApps as all being at the same level, if that makes sense? I'll send a PR tomorrow.

**Comment by garyb** [comment]
I think we might need to apply the same somewhere else too, as I'm getting this:

``` purescript
forall t2 t3. FD t3 t2 => C t2 => ... -> ...
```
for
```
forall t2 t3. FD t3 t2 => C t2 => t3 -> String
```

Which seems a tad aggressive. Any ideas @hdgarrood?

**Comment by garyb** [comment]
Maybe another thing we should do is only truncate the printed types past the max depth if they are "compound" too? So in the above, even if the depth calculation was right, it'd still print `t3` and `String` since they are simple.

**Comment by joneshf** [comment]
What was the reason for the initial change? Maybe we could solve that problem in a different way?

**Comment by garyb** [comment]
Here was the original issue: #3401, and PR: #3543

**Comment by hdgarrood** [comment]
How about having foralls and constraints not count as adding depth? It’s a bit crude but it is very easy to implement, and it ought to err towards not truncating enough instead of truncating too much, which is probably the right approach.

I am still confident that truncating types in errors is the right thing to do in most circumstances.

**Comment by garyb** [comment]
I had a very cursory look and I think the way foralls are handled means they don't count for depth already. Could well be the constraints do, not counting those makes sense for sure.

**Comment by joneshf** [comment]
Maybe the flag is backwards? The common case of PS code doesn't have huge types, but the default behavior assumes that huge types are a regular thing. The uncommon case of huge types could be opt-in via the flag instead of the default behavior.

**Comment by hdgarrood** [comment]
I don’t think having types truncated by default represents an assumption that huge types are a regular thing, rather a belief that when you do have huge types, it would be best to have the compiler behave sensibly by default rather than having to opt in to it behaving sensibly. I still think a sensible truncating algorithm is achievable, even if we aren’t quite there yet.

**Comment by joneshf** [comment]
Sorry, lemme ask in a more objective way: could flipping the behavior of the flag fix the issue?

**Comment by hdgarrood** [comment]
We could flip the flag, but as I say I don’t think that would be a good default.
