### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by sajalcody** [purescript/purescript#3589]
There are a lot of compatibility issues among different packages.

I am using purs v0.11.7. 

PSCi is working fine
but after the command:

`bower install purescript-spec `

`pulp repl` gives errors

```
Error 1 of 2:

  at bower_components\purescript-strings\src\Data\String\NonEmpty\Internal.purs line 37, column 1 - line 37, column 1

    Unable to parse module:
    unexpected "else"
    expecting declaration or end of input


  See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
  or to contribute content related to this error.

Error 2 of 2:

  at bower_components\purescript-functors\src\Data\Functor\Coproduct\Inject.purs line 17, column 1 - line 17, column 1

    Unable to parse module:
    unexpected "else"
    expecting declaration or end of input


  See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
  or to contribute content related to this error.


* ERROR: Subcommand terminated with exit code 1
```

**Comment by hdgarrood** [comment]
You’ll find that things are much easier if you upgrade to v0.12.x. However, GitHub issue trackers are not for these sorts of questions; please use Slack or Discourse instead.

**Comment by thomashoneyman** [comment]
@sajalcody here's the [Slack](https://functionalprogramming.slack.com/), and you can [get an invite here](https://fpchat-invite.herokuapp.com/) and join #purescript; here's the [Discourse](http://discourse.purescript.org/).
