### ISSUE TITLE
Windows missing in v0.12.4

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript#3590]
https://github.com/purescript/purescript/releases/tag/v0.12.4

https://ci.appveyor.com/project/hdgarrood/purescript-lfgff/builds/23665315

Job restart -> success?

**Comment by justinwoo** [comment]
@hdgarrood or someone with AppVeyor access

**Comment by hdgarrood** [comment]
No, appveyor doesn’t work right now. We’ll need a maintainer who has access to a windows machine to do it manually

**Comment by garyb** [comment]
I'm building it just now.

**Comment by garyb** [comment]
Done!

**Comment by hdgarrood** [comment]
Thanks!

**Comment by hdgarrood** [comment]
> Job restart -> success?

But also I'd just like to quickly point out: if a CI build times out, restarting it won't help, because the progress made in the first attempt isn't reusable unless you push a new commit. Don't restart jobs, push new commits (`git commit --allow-empty` is useful here).
