### ISSUE TITLE
Importing a type with the same name as its module is confusing

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript#3591]
e.g. with psc-ide-emacs, importing on "Effect" leads to just errors reported on undeciable importing between Effect the module and the type. Why shouldn't it import the type as it did before?

I'm also already using my branch of psc-ide-emacs to be able to complete on not yet imported qualified imports: https://github.com/purescript-emacs/psc-ide-emacs/pull/166

Reporting here because it seems like purs ide server should default in one way over the other.

**Comment by kRITZCREEK** [comment]
I think you're right, we should be filtering out modules when we determine candidates for imports.

Needs filtering here:
https://github.com/purescript/purescript/blob/35038c7ef472d7ae27bf9f31a9155ba32bada812/src/Language/PureScript/Ide/Imports.hs#L280

We could work around it in the editors by passing filters that exclude the module namespace for now.
