### ISSUE TITLE
Running `purs ide server` on macOS crashes

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript#3594]
```bash
purs ide server
purs: Network.Socket.listen: unsupported operation (Operation not supported on socket)
```

This happens since `0.12.4`.

**Comment by kRITZCREEK** [comment]
This is very likely because of the bump of the `network` library, which deprecated the old interface we were using. I don't have an OSX machine that I can test on, so I'll be unlikely to be able to fix this. It'll need someone else to step in.
