### ISSUE TITLE
 For module names with apostrophe, generated javascript is invalid

### ISSUE THREAD

**Issue by matthew-hilty** [purescript/purescript#3601]
I've noticed quite a few past issues related to codegen and name mangling (e.g., #2558, #2847) and also an issue specifically about module names (#3254).

This may be a new issue not yet addressed by any of the prior.

As of version 0.12.3, module names and qualifiers can have apostrophes, but the corresponding variable names in generated javascript aren't mangled properly.

For example, javascript for the two purescript modules

```purescript
module Foo' where
foo = "foo"

module Main where
import Foo'
```

contains the following import

```javascript
var Foo' = require("../Foo'/index.js");
```

`purs compile ...` completes without error, but trying to call the main module with `spago run` causes the following error:

```
Build succeeded.
~/proj/output/Main/index.js:6
var Foo' = require("../Foo'/index.js");
     ^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
spago: Running failed, exit code: 1

```

**Comment by hdgarrood** [comment]
Thanks for the report. I’m in favour of disallowing primes in module names entirely.

**Comment by adnelson** [comment]
I haven't thought through everything here, but I think the answer could be as simple as replacing `'` with `$` in `Language.PureScript.CodeGen.JS.Common.moduleNameToJs`

```haskell
moduleNameToJs :: ModuleName -> Text
moduleNameToJs (ModuleName pns) =
  let name = T.replace "'" "$" (T.intercalate "_" (runProperName `map` pns))
  in if nameIsJsBuiltIn name then "$$" <> name else name
```

**Comment by adnelson** [comment]
Did a little more looking in that same module and I think there's an even simpler solution using existing functionality:

```haskell
moduleNameToJs :: ModuleName -> Text
moduleNameToJs (ModuleName pns) = anyNameToJs name
  where name = T.intercalate "_" (runProperName `map` pns)
```

**Comment by hdgarrood** [comment]
Using the existing name mangling for proper names should indeed work for JS, but I'd prefer to just disallow primes in module names, as allowing primes might require more awkward mangling in other backends. I also doubt that the extra flexibility would be particularly useful to many people anyway; nobody has specifically asked for it to be allowed as far as I can remember.

**Comment by adnelson** [comment]
Sure, I can see the argument against allowing primes in module names for simplicity's sake, but in effect this is changing the language specification, which seems like an unnecessary step when the functionality already exists and a simple bugfix would suffice. For what little it's worth, I'd advocate for fixing the bug first and then making a decision on whether to change the language.

**Comment by natefaubion** [comment]
> but in effect this is changing the language specification

There's a language specification? 😛 

I'm pretty sure the bug is that we are allowing primes to go through. To me it seems clear from existing validation code that the intention was to disallow it.

**Comment by hdgarrood** [comment]
Yes, I'm almost certain that primes were never intended to be allowed in module names, and that this was an unintentional side-effect of a change which was only mean to relate to other proper names (like types, classes, or data constructors).

**Comment by adnelson** [comment]
> There's a language specification? 😛

Theoretical only 😆 

OK, well Haskell supports primes in module names, so I figured PureScript was meant to as well. But let's say for the sake of argument that that's not desired. I would argue that's the topic of a separate pull request. The real bug here is that the code is currently is capable of producing invalid javascript. Regardless of whether primes are desired or not, we should still probably be using `anyNameToJs` when converting module names.

**Comment by hdgarrood** [comment]
I think having something like a newtype over Text denoting strings which are safe to use as JS variable names would indeed be good, yes.

**Comment by matthew-hilty** [comment]
Would the closed pull request #3602 work to fix this issue too? It both disallows primes in module names and mangles them just in case they do get through.

I closed it because it seemed that hdgarrood and natefaubion thought the best fix for this issue would be cst. Maybe, though, a quick fix is needed in the interim?

**Comment by hdgarrood** [comment]
No, I don’t think this is urgent and cst will most likely be in the next release anyway.

**Comment by adnelson** [comment]
I got the bug and spent some time creating a `JsIdent` type and replacing usage of `Text` with that. https://github.com/purescript/purescript/compare/master...adnelson:jsident?expand=1

It's type checking, but the tests are currently failing -- not sure why. If I can get them passing I might open a PR

**Comment by hdgarrood** [comment]
The package.yaml file should enable -XNoMonadFailDesugaring, so I am surprised you’re seeing that. I’m not sure why it would come up at all

**Comment by adnelson** [comment]
Im using nix, so it’s a bit of a special situation :) although if it were
in the .ghci I think it would have worked
