### ISSUE TITLE
Default superclass instances

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#361]

**Comment by puffnfresh** [comment]
@joneshf that's a good idea! :+1:

**Comment by LiamGoodacre** [comment]
Very cool :+1:

**Comment by AppShipIt** [comment]
Does @puffnfresh's tweet mean something like `DefaultSignatures` would make an alternate/preferable proposal? I liked the look in his [gist](https://gist.github.com/puffnfresh/f907fb752186aa5e8343).

**Comment by gabejohnson** [comment]
I like
```hs
class (Applicative m, Bind m) <= Monad m
  map :: forall a b. (a -> b) -> m a -> m b
  map f ma = ma >>= (pure <<< f)
```
and
```hs
class Eq a where
  eq :: a -> a -> Boolean
  eq x y = not (notEq x y)

  notEq :: a -> a -> Boolean
  notEq x y = not (eq x y)
```

In the former case, `Monad.map` shadows `Functor.map` and is delegated to whenever there is a defined instance for `Monad` and not `Functor`. Otherwise `Functor.map` is used.

In the latter, instances must be checked to ensure that they define either `eq` or `notEq`. My knowledge of the type checker is limited, so I don't know what's involved here.

I anticipate objections to the implicit shadowing in the `Monad` example. Another possibility is
```hs
class (Applicative m, Bind m) <= Monad m
  Functor.map f ma = ma >>= (pure <<< f)
```

**Comment by paf31** [comment]
There is a problem with separate compilation here though, unless I'm missing something. How does the compiler know which modules to look at to find all possible implementations in subclasses?

**Comment by LiamGoodacre** [comment]
Could you write an example of a problematic situation? @paf31

**Comment by paf31** [comment]
Well in the example above, if I want a `Functor` dictionary, I don't know that I need to look in `Control.Monad` in order to find the default superclass instance. I need to know all possible subclasses in order to know where to look.

Adding new modules can be a breaking change for existing code, because those modules can implement superclass instances in new ways.

Am I missing something?

**Comment by LiamGoodacre** [comment]
If when you implement an instance and don't have the super classes implemented I was thinking it would expand out into multiple instances.  So from a module location point of view it'd be as though you wrote them yourself.

**Comment by paf31** [comment]
So they'd be orphans unless defined with the data type? Makes sense, although I think the errors might be confusing.

There are still issues though. What if I have unrelated classes `A <= B` and `A <= C`, and I implement `B` and `C`? How do we fill in `A`? For example, I might have `Eq <= Ord` and `Eq <= Hashable` which give completely different implementations of `Eq`. Presumably that becomes an overlapping instance error, but at the call site.

Finally, I think having to figure out if the super class is implemented before making a decision about whether or not to fill something in might be tricky to implement.

I'd rather implement regular default implementations first, and see if we still need this.

**Comment by gabejohnson** [comment]
@paf31 would you prefer a separate issue for discussing default implementations?

**Comment by paf31** [comment]
Yes please.
