### ISSUE TITLE
More specific error on TransitiveExportError

### ISSUE THREAD

**Issue by JamieBallingall** [purescript/purescript#3611]
I manage to trigger `TransitiveExportError` on a fairly regular basis. The error prints as "An export for [class] requires the following to also be exported:" followed by a list of all members of the class.

Any chance we can indicate which of those members is actually missing from the export list?

**Comment by garyb** [comment]
That would definitely be much better :+1:

**Comment by colinwahl** [comment]
Do y'all think that it would be better to still show the list of all the members of the class, or instead just show a list of the member that are missing from the module exports?

**Comment by garyb** [comment]
I'd say just listing the missing ones, as that's the relevant info needed to fix the error.

**Comment by colinwahl** [comment]
Sounds good, I can take a look at this later tonight.
