### ISSUE TITLE
Docs confused by multiple binds in `ado`

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#3622]
Doc generation for:
```purescript
foo = ado
  x <- mx
  y <- my
  in x + y
```

Produces the error:
```
    Unknown value x
```

**Comment by hdgarrood** [comment]
@LiamGoodacre I can't reproduce this, can you please provide a self-contained example?

**Comment by LiamGoodacre** [comment]
Yeah I'm having trouble re-reproducing.  I must have been doing something else wrong :sweat_smile:
