### ISSUE TITLE
`purs docs` fails due to thinking a Newtype instance is using a type synonym

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3624]
Apologies if this is a duplicate.

Originally reported JordanMartinez/learn-halogen#5 and later in slamdata/purescript-halogen#601, running `spago docs` on the `purescript-halogen`'s `v5.0.0-rc.4` release will fail with the below error. [In his comment in the Halogen issue](https://github.com/slamdata/purescript-halogen/issues/601#issuecomment-489799441), Gary said this is likely a bug in `purs docs`.

```
Generating documentation for the project. This might take a while..
Error found:
in module Halogen.Query.EventSource
at .spago/halogen/v5.0.0-rc.4/src/Halogen/Query/EventSource.purs:32:8 - 32:66 (line 32, column 8 - line 32, column 66)

  Type class instances for type synonyms are disallowed.

in type class instance
                                                         
  Data.Newtype.Newtype (EventSource m a)                 
                       (m                                
                          { finalizer :: Finalizer m     
                          , producer :: Producer a m Unit
                          }                              
                       )                                 
                                                         

See https://github.com/purescript/documentation/blob/master/errors/TypeSynonymInstance.md for more information,
or to contribute content related to this error.


spago: Docs generation failed.
```

**Comment by hdgarrood** [comment]
Thanks for the report. This is the kind of thing I’m intending to fix by doing #3503. Can you try to come up with a minimal reproduction case please?

**Comment by JordanMartinez** [comment]
> Can you try to come up with a minimal reproduction case please?

Will do. I realized after posting this that that would be the next step.

**Comment by garyb** [comment]
The likely culprit here is the `Producer` synonym (for `Co (Emit o)`) used inside the `EventSource` definition, if that helps with reproduction.

**Comment by JordanMartinez** [comment]
So, here's what I have found so far.
- I created a project whose only file was only the bare minimum needed to recreate the `EventSource` type and its Newtype instance with all dependencies satisfied, so that it's defined exactly as it is in Halogen. `spago docs` did not fail
- I then recreated the `EventSource` file and satisfied its dependencies. Again, `spago docs` did not fail
- I then checked out a new branch for `purescript-halogen` and satisfied its dependencies using `spago`. `spago docs` did not fail.

When I first created my `learn-halogen` repository, I recall executing `spago docs` successfully. So, I checked what the versions of the tools I used were to see what had changed. The only thing that changed was spago: I had upgraded it from `0.7.5.0` to `0.7.7.0`. I thought that might somehow be related. Thus, I uninstalled that version of spago on my computer, deleted the old `.spago` folder in case that somehow affected things, and installed spago `0.7.5.0`, the original version I had used when creating that repo. The docs command still failed with the same error.

There are some other folders in my learning repo that I haven't committed and which I reference when writing the lessons. So, I did a fresh clone of my repo into a new directory and ran `spago docs` (`v0.7.5.0`). The command still fails.
So, I then checked out a new branch of my `learn-halogen` repo where I wrote the first example. I ran `spago docs` (`v0.7.5.0`) and it succeeded. I removed the `.spago` and `generated-docs` folders, upgraded spago to `v0.7.7.0` and reran the command. It succeeded.

I'm going to jump through my commit history and rerun this command to see what is the first commit which causes the command to fail. I'll post back here when I find it.

**Comment by JordanMartinez** [comment]
Ok... this is weird.

First commit where it fails is [here](https://github.com/JordanMartinez/learn-halogen/commit/dd80f7458ca4bc0d3d547ce9d02450a6b2c3f103)

I was able to get docs to build by changing the first line below to the second group of lines:
```purescript
-- shorthand
_child = SProxy :: SProxy "child"

-- longhand
_child :: SProxy "child"
_child = SProxy
```

The strange thing is that I use the shorthand version elsewhere in that repo and it doesn't cause this problem there.

**Comment by hdgarrood** [comment]
The way it works is that we only invoke the type checker to if there are any missing type signatures in order to fill them in, and when generating docs we don't look for annotations like in your shorthand example, so this behaviour doesn't seem too surprising. Are the other places you're using the shorthand version depending on halogen?

**Comment by JordanMartinez** [comment]
Yeah. [In the commit immediately before it](https://github.com/JordanMartinez/learn-halogen/commit/9012944158562b2193e2526bf6e961a30ad6675b#diff-e2f9ba817459f8f75d3a204d9db5d534R76), I use `_child = SProxy :: SProxy "child"`

Does it matter if this is the same variable name (i.e. `_child`) or same label name?

**Comment by hdgarrood** [comment]
I don't understand the question

**Comment by hdgarrood** [comment]
I suspect this bug will only be triggered if one of the modules you're generating docs for both has a missing type signature and imports something from Halogen (either directly or transitively).

**Comment by JordanMartinez** [comment]
Thinking about my question more, I doubt its relevant. I was wondering whether defining a variable named `_child` multiple times throughout my codebase might be the reason why this also occurs. Then I remembered that the commit where I introduced `ComponentTemplate.purs` isn't the second time I declared a variable called `_child`. It's more like the 6th time in that codebase.

> I suspect this bug will only be triggered if one of the modules you're generating docs for both has a missing type signature and imports something from Halogen (either directly or transitively).

I'm not so sure. I've been importing something from Halogen in most of that repo's files and there aren't any missing type signatures in any of my files in the commit before and at the commit that causes doc failure.

**Comment by hdgarrood** [comment]
Um, that seems consistent to me?

**Comment by hdgarrood** [comment]
Just to be clear, when I say missing type signatures, this counts as a missing type signature:
```purescript
-- shorthand
_child = SProxy :: SProxy "child"
```

**Comment by JordanMartinez** [comment]
Ah... ok. 

That still leaves me wondering why this bug didn't get triggered earlier though...

**Comment by hdgarrood** [comment]
I don't think it's worth worrying about too much honestly, especially if you've managed to fix it in your repo. For coming up with a minimal reproduction example, the lessons is that you'll want to include:
* A `newtype` which uses a type synonym somewhere in its definition
* A `Newtype` instance for that type
* A top-level declaration which is missing a type signature in the same module (to trigger using the type checker to fill it in)

**Comment by JordanMartinez** [comment]
I updated `learn-halogen` to use my fix, but the [CI build still failed](https://travis-ci.com/JordanMartinez/learn-halogen/builds/110904279#L1300). 

So, I used `purs docs` directly to see whether it would build the docs or not using a variant of @hdgarrood's suggestion in the `purescript-halogen` issue:
```bash
purs docs --format html '.spago/**/*.purs' 'src/**/*.purs'
# ^ This failed because it picked up 'benchmark/src/**/*.purs' in one of the packages
# So I looked at `.spago`'s structure and updated it to try to account for that issue
purs docs --format html '.spago/*/*/src/**/*.purs' 'src/**/*.purs'
# ^ this command built fine
```
Unfortunately, I don't have more time to look into this right now, so I thought I'd just post this here for now.

**Comment by JordanMartinez** [comment]
I changed the directories I was caching in the CI build and it passed. Closing this.

**Comment by JordanMartinez** [comment]
@hdgarrood & @garyb Just wanted to say thank you for helping me track down this issue.

**Comment by garyb** [comment]
No problem!

Should we keep this open, since I think there is actually a problem here still?

**Comment by hdgarrood** [comment]
Yeah I agree, I think it would be good to keep this open.
