### ISSUE TITLE
Write to a tags file instead of stdout when generating tags

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3642]
The current behaviour that e.g. `purs docs --format ctags` writes its output data to standard output doesn't work fantastically well together with tools which might (sensibly) assume that `purs docs` will always write to the file system. Put differently: it's weird that the `--format` option controls not only the format of output, but also how output is produced; supplying `html` or `markdown` means you get files written to disk, but supplying `etags` or `ctags` means you get data written to standard output. See also https://github.com/purescript-contrib/pulp/issues/368

**Comment by hdgarrood** [comment]
Instead I think we should consider having `purs docs --format ctags` write to a file `tags`, and `purs docs --format etags` write to a file `TAGS`, based on the documentation at http://ctags.sourceforge.net/ctags.html.

**Comment by GoNZooo** [comment]
vim/nvim indeed uses a local "tags" file by default, though you can configure it to load any list of files. I have it set to pick up `codex.tags` because I always forget to rename codex-generated tags files in Haskell, for example.

**Comment by hdgarrood** [comment]
People seem to be in favour, so any objections on adding this to 0.13.0? We are already breaking the `purs docs` CLI in a few of other ways, e.g. #3490, #3503.

**Comment by garyb** [comment]
Sounds good to me 👍
