### ISSUE TITLE
Ignore repeated source files passed to the CLI

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3653]
For example:
```purescript
-- example.purs
module Example where
```
```
$ purs compile example.purs
Compiling Example
[OK]
$ purs compile example.purs example.purs
Error found:
at example.purs:1:1 - 1:21 (line 1, column 1 - line 1, column 21)

  Module Example has been defined multiple times


See https://github.com/purescript/documentation/blob/master/errors/DuplicateModule.md for more information,
or to contribute content related to this error.
```
Ideally both commands would do the same thing.

**Comment by robertDurst** [comment]
Interested in taking a swing at this!

**Comment by hdgarrood** [comment]
Sounds great - let me know if you get stuck.

**Comment by joneshf** [comment]
What are we intending to change that will cause `purs compile` to ignore a file: the file path? the module name? something else?

**Comment by hdgarrood** [comment]
If, after expanding globs, a particular file path appears more than once, the compiler should ignore the extra occurrences.

**Comment by joneshf** [comment]
Gotcha. THanks.

**Comment by robertDurst** [comment]
Don’t quite have the time to check this out — got busy. Someone else can take it on.

**Comment by dyerw** [comment]
I can take this over if it's helpful.
