### ISSUE TITLE
How to dynamic load purescript?

### ISSUE THREAD

**Issue by Escapingbug** [purescript/purescript#3671]
I'm not sure if it is a silly question to ask. Is there any possible way to dynamically load purescript module at runtime? This might be related to plugin system implementation. For example if I want to implement a nodejs system in purescript, and I want to have plugins supported, one thing to consider is to dynamically load user script into my project. I think FFI could do the trick, but if my user script is purescript already, user needs the type to call function inside my system. This could be a burden for normal users since they have to redefine the type themselves..

**Comment by hdgarrood** [comment]
It’s a good question, but it’s better suited to discussing in other channels; we prefer to keep the GitHub issue tracker for things which have more concrete proposals and relate to the compiler specifically. You might like to read  https://discourse.purescript.org/t/lazy-loading-routes-in-tea-style-app/141/7
