### ISSUE TITLE
Purescript Package broken when installing via npm

### ISSUE THREAD

**Issue by cruhl** [purescript/purescript#3678]
![image](https://user-images.githubusercontent.com/4983357/59524007-5f816700-8e98-11e9-95e2-cad253bea10e.png)

**Comment by garyb** [comment]
Duplicate of #3677 🙂 

It can be resolved by updating to a newer node version.

**Comment by cruhl** [comment]
Gotcha, thanks. You might consider adding some note about this to the getting started guide :)
