### ISSUE TITLE
Consider using static linking in binary distributions

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3696]
Many of the difficulties people have had with getting the compiler running boil down to shared libraries at the versions the compiler is expecting being difficult to get hold of via their distribution's standard package manager. For example:

* https://github.com/purescript/purescript/issues/3122
* https://github.com/purescript/purescript/issues/2026
* https://github.com/purescript/purescript/issues/2176
* https://github.com/purescript/purescript/issues/2147
* https://github.com/purescript/purescript/issues/2175#issuecomment-223844287
* https://github.com/purescript/documentation/issues/119

There's a small drawback with statically linked binaries though: they would be a little larger. I think static linking is probably worth it, on balance, although we should see how easy it is to actually produce statically linked binaries first.

**Comment by hdgarrood** [comment]
It turns out that the `terminfo` library, which is the main cause of these kinds of errors, can’t really be statically linked (see https://github.com/judah/terminfo/issues/36 ). However, it turns out that it is an optional dependency of `haskeline`, as `haskeline` has a build flag to control whether `terminfo` should be used. From haskeline’s Cabal file:

> -- There are three main advantages to the terminfo backend over the portable,
> -- "dumb" alternative.  First, it enables more efficient control sequences
> -- when redrawing the input.  Second, and more importantly, it enables us
> -- to draw on multiple lines, so we can wrap long input strings.  And third,
> -- the backend adds some extra key sequences such as forwards delete.
> --
> -- (The "dumb" terminal also allows editing of long input strings, but is
> -- restricted to only one line and thus only shows part of the input at once.)

https://github.com/judah/haskeline/blob/master/haskeline.cabal#L28

The drawbacks

**Comment by rainbyte** [comment]
Is this for the REPL? I didn't even know about multiline strings there.
Does so many people use this feature?

Personally, I think being able to easily install PureScript is a priority.

**Comment by Swonkie** [comment]
> Personally, I think being able to easily install PureScript is a priority.

I strongly agree. It is literally the most important "feature" of _any_ software. If the official and documented way of installing PureScript doesn't work, that looks extremely bad and most users experiencing any difficulties this early on, while trying something new, will simply give up and look for something else than PureScript.

In my case, installation on Manjaro doesn't work beause of this issue:
https://github.com/purescript/documentation/issues/119

**Comment by hdgarrood** [comment]
I tested out what the repl is like with the `terminfo` flag disabled. Here's a side-by-side comparison:
![Peek 2020-07-12 23-02](https://user-images.githubusercontent.com/1270186/87257591-108b7400-c494-11ea-83ac-21a1cfb45ee1.gif)
With the one on the left, the binary doesn't depend on `libtinfo`, but there's definitely a user experience hit; I expect quite a lot of users find the ability to edit long inputs useful. I'm not sure if it's worth it.

**Comment by milesfrain** [comment]
The lack of line wrapping in the "dumb" terminal could be seen as feature (at least I always like to disable line wrapping when editing code). I assume you can still move the cursor to edit content earlier in the line?
Although this doesn't seem as practical for the repl where you're only have one line available for editing at a time.

**Comment by pmiddend** [comment]
> Is this for the REPL? I didn't even know about multiline strings there.
> Does so many people use this feature?
> 
> Personally, I think being able to easily install PureScript is a priority.

This also applies to continuous integration. I'm using Purescript with Gitlab CI and have to add another `apt-get install libtinfo5 -y` everywhere. That's a bummer.
