### ISSUE TITLE
Altering capitalisation of module breaks incremental compilation

### ISSUE THREAD

**Issue by stacycurl** [purescript/purescript#3698]
1) Create module FOO with a function that's referenced by a Main, linked against
2) build & verify FOO is present by grep -i "foo" index.js
3) Rename FOO to Foo, updated references.
4) build & grep -i "foo" index.js yields "var Foo = require("Bar/index.js");
5) clean (not sure what command does this, I just wipe out the output directory)
6) build & now grep -i "foo" index.js yields "var Foo = $PS["Foo"];"

**Comment by hdgarrood** [comment]
Thanks for the report. I'm working on #3145 right now and I think my fix will address this too.

**Comment by hdgarrood** [comment]
Actually could you expand and clarify the repro steps a bit more please? I'm not sure I completely follow.

**Comment by stacycurl** [comment]
Which step is confusing you ?

**Comment by stacycurl** [comment]
I'm not sure fixing #3145 will solve this issue, my module was being recompiled, but it was suffering from some past compilation.

A property of compilation is that cleaning and recompiling doesn't produce a different output, right ?
Having had a module named FOO and then renaming it to Foo breaks this property.

I have a hypothesis that when the module was called FOO that led to some intermediate persisted state.
When the module was renamed to Foo that persisted state caused Foo to be compiled differently, to always result in a 'require' line in index.js.
When the output folder was cleared (i.e. the intermediate persisted state was removed) the compilation of Foo now produced the expected result.

**Comment by stacycurl** [comment]
I should also mention that this was on OSX, which has an odd 'case insensitive but case preserving' behaviour.

**Comment by hdgarrood** [comment]
It's really that they're incomplete. Can you please include the complete filenames, file contents, and commands you ran? For example, you mention that at one point, one of the compiled artifacts contains a reference to a module Bar, but you never mention a module of that name in the steps.

**Comment by stacycurl** [comment]
I didn't realise the requirement for raising issues is a complete failing example.
I'm not willing to provide more detail.
