### ISSUE TITLE
Build failure on PPC64le/Linux platform

### ISSUE THREAD

**Issue by kgardas** [purescript/purescript#3700]
Hello,
while trying to build purescript v.0.13.2 on ppc64le-linux it failed and while trying with -j1 to get some insight what's going on, the failure shows as
```
$ cabal new-install purescript -j1
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - purescript-0.13.2 (exe:purs) (requires build)
Configuring executable 'purs' for purescript-0.13.2..
Preprocessing executable 'purs' for purescript-0.13.2..
Building executable 'purs' for purescript-0.13.2..
[ 1 of 12] Compiling Command.Bundle   ( app/Command/Bundle.hs, dist/build/purs/purs-tmp/Command/Bundle.o )
[ 2 of 12] Compiling Command.Compile  ( app/Command/Compile.hs, dist/build/purs/purs-tmp/Command/Compile.o )
[ 3 of 12] Compiling Command.Docs.Markdown ( app/Command/Docs/Markdown.hs, dist/build/purs/purs-tmp/Command/Docs/Markdown.o )
[ 4 of 12] Compiling Command.Hierarchy ( app/Command/Hierarchy.hs, dist/build/purs/purs-tmp/Command/Hierarchy.o )
[ 5 of 12] Compiling Command.Ide      ( app/Command/Ide.hs, dist/build/purs/purs-tmp/Command/Ide.o )
<command line>: can't load .so/.DLL for: /home/karel/.cabal/store/ghc-8.6.5/purescript-0.13.2-292d5a8133e3bb6fed4a713b1f7d288c5c3b4ee65e87d2e29ebfe21e7c5a6cb2/lib/libHSpurescript-0.13.2-292d5a8133e3bb6fed4a713b1f7d288c5c3b4ee65e87d2e29ebfe21e7c5a6cb2-ghc8.6.5.so (/home/karel/.cabal/store/ghc-8.6.5/purescript-0.13.2-292d5a8133e3bb6fed4a713b1f7d288c5c3b4ee65e87d2e29ebfe21e7c5a6cb2/lib/libHSpurescript-0.13.2-292d5a8133e3bb6fed4a713b1f7d288c5c3b4ee65e87d2e29ebfe21e7c5a6cb2-ghc8.6.5.so: undefined symbol: cpXNo_closure)
Warning: Some package(s) failed to build. Try rerunning with -j1 if you can't
see the error.
```
Honestly I'm not sure if this is PureScript issue or my GHC 8.6.5 issue, but first reporting here at least for the reference.

**Comment by hdgarrood** [comment]
I think this is most likely to be a GHC/cabal issue. Can you try building using the instructions in INSTALL.md please?

**Comment by kgardas** [comment]
Indeed, I'm trying now, but so far no success as INSTALL.md recommended step fails with
```
karel@power:~/tmp/purescript-0.13.2$ time stack install --flag purescript:RELEASE
I don't know how to install GHC for (Linux,PPC64), please install manually
```
and both `setup` and `build` commands also fails with the same message:
```
karel@power:~/tmp/purescript-0.13.2$ stack setup
I don't know how to install GHC for (Linux,PPC64), please install manually
karel@power:~/tmp/purescript-0.13.2$ stack build
I don't know how to install GHC for (Linux,PPC64), please install manually
```
The obvious problem is that GHC is already installed and I'm just stack newbie so don't know how to convince it to use preinstalled GHC instead of compiling a new one...

**Comment by hdgarrood** [comment]
Try `stack --system-ghc install --flag purescript:RELEASE`?

**Comment by kgardas** [comment]
This does not work and it's a little bit fishy since resolver lts-13.26 should be on ghc-8.6.5 which is exactly version I do have installed. It's not in /usr/bin but in my `$HOME` specific installation directory, but `$PATH` is set right so `ghc --version` is correct:
```
karel@power:~/tmp/purescript-0.13.2$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```
and my stack is:
```
$ stack --version
Version 2.1.3.1 ppc64
```

**Comment by hdgarrood** [comment]
Huh, that is weird. Then again I guess it’s not completely surprising that it’s not working properly since it sounds like stack doesn’t support your architecture.

Anyway, I’m able to install with cabal with the command you were using so I don’t think this is a purescript issue. I have no idea how to approach this, unfortunately. I’d suggest asking maybe in the Haskell channel in fp slack or on cabal’s bug tracker.

**Comment by hdgarrood** [comment]
I'm going to close this for now as I don't think it's something we can address in the compiler. Good luck! Sorry I couldn't be more help.
