### ISSUE TITLE
Update Record Fuction

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript/purescript#3704]
It would be nice if the update record syntax could also define a function.

A simple example where this would be helpful is with [modify](https://pursuit.purescript.org/packages/purescript-transformers/4.2.0/docs/Control.Monad.State.Trans#v:modify).

```purescript
type State = {a :: String}

-- some monad context
  modify_ ({a = "new string"})
```

What has to be done right now is `modify_ \s -> s {a = "new string"}`.

**Comment by LiamGoodacre** [comment]
This exists with the notation: `_ { foo = bar }`, for example: `modify_ (_ { a = "new string" })`.

**Comment by BebeSparkelSparkel** [comment]
Thanks, I don't see that in https://github.com/purescript/documentation/blob/master/language/Records.md

Should I add that with a pr?

**Comment by LiamGoodacre** [comment]
Yes please!

**Comment by BebeSparkelSparkel** [comment]
https://github.com/purescript/documentation/pull/261
