### ISSUE TITLE
Warn on derived Newtype & Generic instances for exported types with non-exported constructors

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3707]
Defining a Newtype or Generic instance for a data type effectively means that anyone who can see the type can also see its constructor(s). Therefore, I don't think there is ever a good reason to export a data type without its constructors if that data type has Newtype or Generic instances. Additionally, I suspect that when exported types have these instances without exported constructors, it's usually accidental, and the author doesn't realise that they are effectively making the constructors public by providing these instances.

I'd suggest having the compiler emit warnings for data types where all of the following are true:
- The data type is exported
- Not all of the constructors are exported
- The type has a derived `Newtype` or `Generic` instance

**Comment by garyb** [comment]
Definitely :+1:. I thought we already had an issue for it even, but I can't find it now, maybe it was just mentioned in passing somewhere.

**Comment by thomashoneyman** [comment]
I've made this mistake myself more than once 👍
