### ISSUE TITLE
Emit metadata for data constructors in dev environment

### ISSUE THREAD

**Issue by thebrodmann** [purescript/purescript#3723]
For debugging purposes in https://github.com/slamdata/purescript-halogen/issues/614 editing of PureScript datatypes is a challenge due to lack of access to related data constructors.
So as a solution maybe we can add some metadata to data constructors in the dev environment.

As an example:
```purs
data Quantum = Yes | No | Both
```
The `Quantum` datatype may can be transpile to:
```js
var Yes = (function () {
  function Yes() {

  };
  Yes.value = new Yes();
  Yes.metadata = {}
  return Yes;
})();
var No = (function () {
  function No() {

  };
  No.value = new No();
  No.metadata = {}
  return No;
})();
var Both = (function () {
  function Both() {

  };
  Both.value = new Both();
  Both.metadata = {}
  return Both;
})();

var Quantum = { Yes: Yes, No: No, Both: Both }

Yes.metadata.constructors = Quantum
No.metadata.constructors = Quantum 
Both.metadata.constructors = Quantum

// Tests

Yes.value.constructor === Yes   // true
No.value.constructor === No     // true
Both.value.constructor === Both // true
```

**Comment by hdgarrood** [comment]
This feature request is not yet at a stage where it can earn a spot on the issue tracker (sorry). Please open a Discourse thread instead: https://discourse.purescript.org/

Note that this use case ought to be covered by the `generics-rep` library: https://pursuit.purescript.org/packages/purescript-generics-rep/6.1.1. If it isn't, please can you explain why `generics-rep` is not sufficient (in a Discourse thread)?
