### ISSUE TITLE
Regression 0.13.4: resource exhausted (Too many open files)

### ISSUE THREAD

**Issue by emiel** [purescript/purescript#3743]
After upgrading from purs 0.13.3 to 0.13.4 I started seeing the following error when building under spago. On Slack I've seen other are seeing this as well so I thought I'd go ahead and open an issue. From what I can tell the issue is triggered when there are many files in the project. However in the sample project below there are only some 200 *.purs files.

```
purs: getCurrentDirectory:getWorkingDirectory: resource exhausted (Too many open files)
spago: Failed to build.
```

```
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ name =
    "my-project"
, dependencies =
    [ "arrays"
    , "canvas"
    , "console"
    , "lists"
    , "psci-support"
    , "random"
    , "refs"
    , "web-dom"
    ]
, packages =
    ./packages.dhall
, sources =
    [ "src/**/*.purs", "test/**/*.purs" ]
}
```

```
$ spago version
0.10.0.0

$ purs --version
0.13.4

$ spago -v build
Running `spago build`
Transformed config is the same as the read one, not overwriting it
Ensuring that the package set is frozen
Getting transitive deps
Running `fetchPackages`
Checking if `purs` is up to date
Running `getGlobalCacheDir`
Installation complete.
Compiling with "purs"
Running command: `purs compile  ".spago/arraybuffer-types/v2.0.0/src/**/*.purs" ".spago/arrays/v5.3.1/src/**/*.purs" ".spago/bifunctors/v4.0.0/src/**/*.purs" ".spago/canvas/v4.0.0/src/**/*.purs" ".spago/console/v4.2.0/src/**/*.purs" ".spago/control/v4.1.0/src/**/*.purs" ".spago/datetime/v4.1.1/src/**/*.purs" ".spago/distributive/v4.0.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/either/v4.1.1/src/**/*.purs" ".spago/enums/v4.0.1/src/**/*.purs" ".spago/exceptions/v4.0.0/src/**/*.purs" ".spago/foldable-traversable/v4.1.1/src/**/*.purs" ".spago/functions/v4.0.0/src/**/*.purs" ".spago/gen/v2.1.1/src/**/*.purs" ".spago/globals/v4.1.0/src/**/*.purs" ".spago/identity/v4.1.0/src/**/*.purs" ".spago/integers/v4.0.0/src/**/*.purs" ".spago/invariant/v4.1.0/src/**/*.purs" ".spago/lazy/v4.0.0/src/**/*.purs" ".spago/lists/v5.4.1/src/**/*.purs" ".spago/math/v2.1.1/src/**/*.purs" ".spago/maybe/v4.0.1/src/**/*.purs" ".spago/newtype/v3.0.0/src/**/*.purs" ".spago/nonempty/v5.0.0/src/**/*.purs" ".spago/nullable/v4.1.1/src/**/*.purs" ".spago/ordered-collections/v1.6.1/src/**/*.purs" ".spago/orders/v4.0.0/src/**/*.purs" ".spago/partial/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" ".spago/random/v4.0.0/src/**/*.purs" ".spago/refs/v4.1.0/src/**/*.purs" ".spago/st/v4.0.0/src/**/*.purs" ".spago/tailrec/v4.1.0/src/**/*.purs" ".spago/tuples/v5.1.0/src/**/*.purs" ".spago/type-equality/v3.0.0/src/**/*.purs" ".spago/unfoldable/v4.0.2/src/**/*.purs" ".spago/unsafe-coerce/v4.0.0/src/**/*.purs" ".spago/web-dom/v4.0.0/src/**/*.purs" ".spago/web-events/v2.0.1/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`
purs: getCurrentDirectory:getWorkingDirectory: resource exhausted (Too many open files)
spago: Failed to build.
```

```
$ purs --version
0.13.3

$ spago -v build
Running `spago build`
Transformed config is the same as the read one, not overwriting it
Ensuring that the package set is frozen
Getting transitive deps
Running `fetchPackages`
Checking if `purs` is up to date
Running `getGlobalCacheDir`
Installation complete.
Compiling with "purs"
Running command: `purs compile  ".spago/arraybuffer-types/v2.0.0/src/**/*.purs" ".spago/arrays/v5.3.0/src/**/*.purs" ".spago/bifunctors/v4.0.0/src/**/*.purs" ".spago/canvas/v4.0.0/src/**/*.purs" ".spago/console/v4.2.0/src/**/*.purs" ".spago/control/v4.1.0/src/**/*.purs" ".spago/datetime/v4.1.1/src/**/*.purs" ".spago/distributive/v4.0.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/either/v4.1.1/src/**/*.purs" ".spago/enums/v4.0.1/src/**/*.purs" ".spago/exceptions/v4.0.0/src/**/*.purs" ".spago/foldable-traversable/v4.1.1/src/**/*.purs" ".spago/functions/v4.0.0/src/**/*.purs" ".spago/gen/v2.1.1/src/**/*.purs" ".spago/globals/v4.1.0/src/**/*.purs" ".spago/identity/v4.1.0/src/**/*.purs" ".spago/integers/v4.0.0/src/**/*.purs" ".spago/invariant/v4.1.0/src/**/*.purs" ".spago/lazy/v4.0.0/src/**/*.purs" ".spago/lists/v5.4.1/src/**/*.purs" ".spago/math/v2.1.1/src/**/*.purs" ".spago/maybe/v4.0.1/src/**/*.purs" ".spago/newtype/v3.0.0/src/**/*.purs" ".spago/nonempty/v5.0.0/src/**/*.purs" ".spago/nullable/v4.1.1/src/**/*.purs" ".spago/ordered-collections/v1.6.1/src/**/*.purs" ".spago/orders/v4.0.0/src/**/*.purs" ".spago/partial/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" ".spago/random/v4.0.0/src/**/*.purs" ".spago/refs/v4.1.0/src/**/*.purs" ".spago/st/v4.0.0/src/**/*.purs" ".spago/tailrec/v4.1.0/src/**/*.purs" ".spago/tuples/v5.1.0/src/**/*.purs" ".spago/type-equality/v3.0.0/src/**/*.purs" ".spago/unfoldable/v4.0.2/src/**/*.purs" ".spago/unsafe-coerce/v4.0.0/src/**/*.purs" ".spago/web-dom/v4.0.0/src/**/*.purs" ".spago/web-events/v2.0.1/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`
Build succeeded.
```

**Comment by justinwoo** [comment]
In the meanwhile, you can also look at how to raise the file descriptor limit on your OS.

**Comment by f-f** [comment]
We are able to replicate this reliably on Spago's CI: [the macOS job](https://travis-ci.com/spacchetti/spago/jobs/249710065) fails with this error, but interestingly only when passing the `--codegen` flag

**Comment by hdgarrood** [comment]
I've started looking into this. I am fairly sure that the problem was introduced in #3705, specifically in [Language.PureScript.Make.BuildPlan.construct](https://github.com/purescript/purescript/pull/3705/files#diff-706293edea5e642a59908d7643102df9R137), where 
```haskell
A.forConcurrently sorted findExistingExtern
```
became
```haskell
A.forConcurrently sortedModuleNames getRebuildStatus
```
The previous `findExistingExtern` function only looks at file modification times, but `getRebuildStatus` rereads the file if the timestamps match in order to compare content hashes. The files have already been read once by this point so I think the fix should be either to hash immediately the first time we read the file, or to do the above processing less concurrently, by breaking the list of sorted module names into chunks and processing each chunk serially, say.

**Comment by hdgarrood** [comment]
Hm, actually maybe not; we were already reading externs files in `findExistingExtern`, and replacing the `forConcurrently` with `for` doesn't fix the issue.

**Comment by vlatkoB** [comment]
Installed `purescript-bin 0.13.4-1` from Arch `AUR` repo again yesterday and I do not experience this issue anymore. I can't remember, but I think it is the same version (dated 2019-10-26) I had issues with before, so could it be something outside of the `purescript` compiler (as Arch updates system packages daily)?

**Comment by emiel** [comment]
My Haskell knowledge is limited but I've been poking at this a bit anyway.

My "ulimit -n" value on macos is 256. Any project with more than 256 source files appears to blow up. I can see with dtruss that the source files are opened (open syscall). They don't appear to be closed though. My understanding is that due to Haskell's lazy nature the files will be closed by the GC. But perhaps this is a case where explicitly closing the files is warranted?

I see usage of "import qualified Data.ByteString.Lazy as B" in Make/Monad.hs in the readTextFile function. Perhaps for obtaining hashes laziness doesn't add anything. At least you don't want to keep every source file open right?

Apologies for my ad hoc brain dump. It's late. :)

**Comment by afcondon** [comment]
I ran into this problem last week and spent quite a bit of time trying to see if some other process on my (macOS 10.15.1) machine was hogging the file descriptors...didn't seem to be, even after selectively killing practically all apps and a fair number of likely-candidate daemons and so on. I was dumbfounded that the problem persisted after machine reboot. Upgraded to a later version of Spago and problem went away, which is even stranger.

Given the well-publicized bugginess of this year's Apple OS releases, i have to ask - is this perhaps an OS bug rather than a purescript one?

**Comment by elliotdavies** [comment]
At work we're seeing this on Linux, both locally and on CI, for what that's worth.

**Comment by hdgarrood** [comment]
I’ve reproduced this on my Ubuntu machine too.

**Comment by hdgarrood** [comment]
My PR #3747 seems to fix this locally for me. Can others please give it a try?

**Comment by hdgarrood** [comment]
@emiel 

> I see usage of "import qualified Data.ByteString.Lazy as B" in Make/Monad.hs in the readTextFile function. Perhaps for obtaining hashes laziness doesn't add anything. At least you don't want to keep every source file open right?

The way you would hope it would work is that using lazy IO here would mean that the file was read and hashed in chunks. The advantage of doing it this way vs. strictly is that it should give us a small upper bound on memory usage no matter how big the file we're hashing is, and it should also potentially allow the GHC runtime to work faster by making the system call to read the next chunk at the same time as adding the current chunk to the hash. With naively written strict IO, you have to read the whole file into memory before you can start hashing it. Anyway, your hunch seems to have been right, so thanks :)
