### ISSUE TITLE
Unused kind import warning does not consider re-exports

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3744]
If a kind is imported and not used within the module except for being re-exported, it is incorrectly marked as unused and a warning is emitted. See e.g. https://github.com/purescript/purescript-st/pull/23 in which I accidentally release a breaking change as a patch-level change because this warning was incorrectly emitted.

**Comment by hdgarrood** [comment]
cc @matthew-hilty

**Comment by garyb** [comment]
Funnily enough I think we had this bug back a while ago too. Or maybe it was the inverse where kinds were never considered unused. Probably both at different times. :wink:

**Comment by hdgarrood** [comment]
Kinds were never considered unused until 0.13.4, yeah
