### ISSUE TITLE
Remove `:complete` command in REPL

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3746]
See jordanmartinez/purescript-jordans-reference#401 for context.

The REPL (if started via pulp or spago, so I'm assuming this is true even if one uses just `purs repl`) now supports tab completion, so is the `:complete` command still necessary? Or should it be removed?

**Comment by hdgarrood** [comment]
The `:complete` command isn't a vestige from a repl which didn't support completion; in fact the repl had competion before it was added. It's to allow external tooling to access completions: https://github.com/purescript/purescript/pull/3038
