### ISSUE TITLE
Unison-like AST approach?

### ISSUE THREAD

**Issue by pkamenarsky** [purescript/purescript#3755]
With the recent release of [Unison](https://www.unisonweb.org) I was wondering - would Purescript benefit from the same approach of storing and hashing immutable AST definitions in an append-only data store, which are then referred to by easily refactorable aliases?

This would for example replace https://github.com/purescript/purescript/issues/2869 and give us all the other benefits the Unison devs are talking about, like to ability to do transparent distributed programming, as in the [Unison introduction](https://github.com/unisonweb/unison):

```
x = factorial 6
Remote.transfer alice
y = foo x -- happens on `alice` node
Remote.transfer bob
bar x y -- happens on `bob` node
```

This would require at least a [codebase manager](https://www.unisonweb.org/docs/tour/hello-ucm) and would have far reaching implications on the ecosystem, build tools and the language itself, so it's not anything that will happen any time soon. On the other hand, Purescript still doesn't have the baggage of a more established language, so it might be beneficial to have a discussion and ponder the possibilities.

**Comment by natefaubion** [comment]
I think that Unison is very interesting. However, I think a discussion like this is better suited for the [Discourse](https://discourse.purescript.org/).
