### ISSUE TITLE
Feature request: String interpolation

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript#3757]
Although I know Strings are evil etc. it's often possible to construct some. The problem with:
```
  "a really really" <>
  "long string " <>
  age
```
Is that it's easy to forget spaces. Would there be interest in string interpolation syntax?

**Comment by hdgarrood** [comment]
Can you open a thread on Discourse instead please?

**Comment by michaelficarra** [comment]
Could it be added in a backward-compatible way? Maybe a new escape sequence?

**Comment by i-am-the-slime** [comment]
@hdgarrood I did. Let's see if a moderator approves it.

**Comment by hdgarrood** [comment]
Thanks! I'll see if we can remove that reviewal step, it was flagged because Discourse thought you typed it "suspiciously fast"... forgetting that it's pretty common for people paste text in which they have already written down elsewhere.

**Comment by hdgarrood** [comment]
https://discourse.purescript.org/t/feature-request-string-interpolation/1061
