### ISSUE TITLE
Documentation for `Prim` modules not included in `purs docs`

### ISSUE THREAD

**Issue by f-f** [purescript/purescript#3767]
As per title, documentation for `Prim` modules (i.e. `docs.json` files) is currently not generated when calling `purs docs`, but it would be desiderable to do so - currently the only place that has documentation about `Prim` modules so far it's Pursuit, and it'd be useful to have that documentation locally too.

Relevant issues: spacchetti/spago#534 and https://github.com/spacchetti/purescript-docs-search/issues/31

**Comment by hdgarrood** [comment]
Makes sense; I'd accept a PR for this. I'd prefer to continue saying that these are not part of the compiler's public API though, i.e. a breaking change to the JSON format doesn't necessarily require us to do a major version bump, at least for now.
