### ISSUE TITLE
Use Happy's new %shift pragma to resolve shift/reduce conflicts in the parser

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3780]
See the example from the PR:
https://github.com/simonmar/happy/pull/153/files#diff-60a217b794510b71f9782a6ec8ad6574R17-R19

We currently have a lot of benign shift/reduce conflicts and this would make them explicit.

**Comment by dariooddenino** [comment]
I was looking at happy the other day and I'd be interested in working on this to learn a bit more. Is there a way to identify these conflicts? Are they marked or are there tests already that cover them?

**Comment by dariooddenino** [comment]
I was finally able to put some more time into it, only to find out that I don't know nearly enough about parsers to fix this right now.  :dagger: 

This will take me a while, so if anyone else wants to work on this issue there's no problem :D

**Comment by natefaubion** [comment]
Thanks for looking at it! I think a lot of the conflicts are unnecessary and come from too much rule factoring. Happy likes a really flat rule set. I think the parameterized rules are a problem.

**Comment by hdgarrood** [comment]
This requires fixing #3664 first, presumably? I had a go at that a while ago and didn't manage it, so perhaps this shouldn't be tagged "new contributor".

**Comment by natefaubion** [comment]
Yes, that's a good point.

**Comment by JordanMartinez** [comment]
It looks like this issue could be resolved now that #3664 has been fixed, correct?

**Comment by hdgarrood** [comment]
Yes, and I think we could add the "new contributor" label back now that #3664 has been fixed too.

**Comment by JordanMartinez** [comment]
I'm assigning this to myself. I'd like to see what I can do.

I read through the Happy guide to get an idea as to what's going on in the `Parser.y` file and how Happy works in general. I've run `stack build` and generated the `.info` file via `stack exec happy -- lib/purescript-cst/src/Language/PureScript/CST/Parser.y -ilib/purescript-cst/src/Language/PureScript/CST/parser-info.info`. 

I don't expect to finish this task quickly, but I'd like to spend some time working on it once a week. If someone can do it faster, please let me know.
