### ISSUE TITLE
Making CodeGen backends

### ISSUE THREAD

**Issue by thautwarm** [purescript/purescript#3784]
Hi, purescript developers, I just found purescript extremely practical and productive(syntax level support for row polymorphisms in a higher rank programming language looks perfect to me), thus I want to make several code generation backends(for some dynamic languages like Python/Julia/Ruby/Lua, etc) for you.

The code at https://github.com/purescript/purescript/blob/master/src/Language/PureScript/CodeGen 
shows it's likely to be not a cumbersome task, but before I start I wonder if implementing the codegen interface like `CodeGen.JS` is sufficient to export the whole ecosystem of purescript to another programming language? Is there anything special I need to take care of? e.g., any code other than those in `CodeGen` responsible for code generation, some special hacks for JavaScript, etc,

Thanks in advance.

**Comment by natefaubion** [comment]
I'm glad you're interested! I think that this sort of informational discussion is better for the community discourse, however. We try to keep the issue tracker specifically for compiler/language issues. https://discourse.purescript.org/
