### ISSUE TITLE
A compilation issue when using other backends

### ISSUE THREAD

**Issue by thautwarm** [purescript/purescript#3785]
There're quite a lot of essential purescript packages written with foreign imports, for instance,
https://github.com/purescript/purescript-console , which however replies on some javascript files like [Effect/Console.js](https://github.com/purescript/purescript-console/blob/master/src/Effect/Console.js) .

I wonder if there're any options for us to make the foreign imports awared by different backends, to make the compiler more language-independent.

My suggestion is, if we specify `backend=pspy` in spago.dhall, the compilation of [Console.purs](https://github.com/purescript/purescript-console/blob/master/src/Effect/Console.purs) should get failed because there's only [Console.js](https://github.com/purescript/purescript-console/blob/master/src/Effect/Console.js) but no Console.py.

**Comment by thautwarm** [comment]
I think this is good:
```javascript
`ffi
python ::
  to_export = 0
cpp::
   static int to_export = 0
endffi`

exports.to_export = 0;
```

Each back end implementation is responsible to handle the string `ffi ... endffi`

**Comment by kritzcreek** [comment]
I'd start here https://github.com/spacchetti/spago/issues/434

The compiler doesn't fail on missing `.js` files if you don't pass it the `js` codegen target and pass `corefn` instead, so this is already supported.

**Comment by thautwarm** [comment]
Oh good.
