### ISSUE TITLE
Codegen question

### ISSUE THREAD

**Issue by thautwarm** [purescript/purescript#3786]
https://github.com/purescript/purescript/blob/27f6cf05e4eb22a6421bdd274942d53ba825f45f/src/Language/PureScript/CoreImp/AST.hs#L55

Did you ever use tricks like `+"1" == 1` via this AST? I need to know if any JS specific tricks used during purescript code generation for making backends based on JS ASTs(by this, I can reuse the existing optimizers)

**Comment by hdgarrood** [comment]
Thanks for your interest, but we prefer to keep this issue tracker for specific tasks relating to the compiler; please use Discourse or Slack for questions.
