### ISSUE TITLE
`unifyTypes: unspecified skolem scope`

### ISSUE THREAD

**Issue by Woody88** [purescript/purescript#3790]
Hi, 

I am looping through a RowList and when I forget to add the instance for `Nil` case I get the error below. 

Code: https://github.com/Woody88/purescript-swerve/blob/compiler-error-example/src/Swerve/Server/Internal.purs#L101

This is the command I use that produces the error:
`spago bundle-app -p examples/BasicServer.purs -m Examples.BasicServer`

```
purs: An internal error occurred during compilation: unifyTypes: unspecified skolem scope
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-0.13.6-4NEubueYkHcBs11fQO4ga7:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker/Unify.hs:106:28 in purescript-0.13.6-4NEubueYkHcBs11fQO4ga7:Language.PureScript.TypeCheck
er.Unify
purs: thread blocked indefinitely in an MVar operation
```

**Comment by garyb** [comment]
Thanks for the report, regardless of cause whenever there's an error reported from the compiler like this it's definitely a bug 🙂

**Comment by natefaubion** [comment]
I've triggered this before by having `forall` in type synonyms for rows in instance constraints. I'd be interested to see what happens if you remove the `forall`s from you `Connection` synonym.

**Comment by Woody88** [comment]
@natefaubion I removed all the `forall`s and it compiled. I also tested without the `Nil` instance and it worked. Does this help?

This is how I removed thed the `forall`s: 
```purescript
type Connection bdy prams
  = ( body   :: bdy
    , params :: prams
    )
```

**Comment by rhendric** [comment]
The link to the reproducing code is broken. This is the same error message as #3681; given that and my inability to reproduce I'm closing in favor of that issue.
