### ISSUE TITLE
Recompilation of unmodified modules can be triggered by outputs timestamp change

### ISSUE THREAD

**Issue by paluh** [purescript/purescript#3802]
Thanks for maintaining and developing `PureScript`!

It seems that modules are possibly recompiled based solely on the timestamp modification. I've tested this flow against `0.13.6`:

* I have two modules.

* One depends on the another (`B` imports `A`).

* I compile them.

* I modify timestamps in the ./output directory.

* When I run `purs compile` the `B` module is recompiled.

* When testing the other scenario and `B` doesn't import `A` nothing is recompiled after timestamp modification.

Here I've recreated a minimal example repository: https://github.com/paluh/purescript-recompilation

**Comment by hdgarrood** [comment]
I think this is working as designed. It’s not based solely on output timestamps: we make a record timestamps and hashes for each source file in the output directory, in order to decide whether each individual module has been updated; the timestamps of the outputs are only used to ensure that recompiling a module marks all downstream modules as needing recompilation too.

**Comment by paluh** [comment]
> I think this is working as designed.

Ah, ok. Sorry for the noise then and thanks for quick response!

I thought that source content hash from `cache-db.json` is the final way to determine whether given module has really changed against existing compilation results and timestamps are only here to have a fast way to find these candidates.
In other words I hoped that transferring compilation artifacts can be a bit simpler between projects, machines etc.

Should I close this?

**Comment by hdgarrood** [comment]
No worries! As you may have already worked out, you should be able to transfer output directories across different projects provided that you keep the timestamps intact. I think rsync and tar both have a flag to do this. I think I will indeed close this for now, but I’m open to reconsidering if using output timestamps has some other drawback which is harder to work around.
