### ISSUE TITLE
'DuplicateModule.purs' golden test fails in local builds

### ISSUE THREAD

**Issue by rhendric** [purescript/purescript#3809]
See https://travis-ci.org/github/purescript/purescript/jobs/661671477#L2124:

```
purescript    >       'DuplicateModule.purs' golden test:                                                                                                                                                                                FAIL
purescript    >         Test output was different from 'tests/purs/failing/DuplicateModule.out'. It was: "Error found:\nat tests/purs/failing/DuplicateModule/M1.purs:1:1 - 1:16 (line 1, column 1 - line 1, column 16)\n\n  Module \ESC[33mM1\ESC[0m has been defined multiple times\n\n\nSee https://github.com/purescript/documentation/blob/master/errors/DuplicateModule.md for more information,\nor to contribute content related to this error.\n\n"
```

This output looks incorrect to me (DuplicateModule.out places the error on line 2 instead of line 1, which looks correct), but I'm not sure how it got this way.

Previously observed here: https://github.com/purescript/purescript/pull/3793#issuecomment-595337397

Blocks #3808. Based on git blame, CC @dariooddenino, @garyb.

**Comment by natefaubion** [comment]
I wonder if this output is deterministic? The golden test refers to the source as M1, where line 1 is correct. Since these modules don't have a dependency, will this output depend on which ever was read first by the runtime?

**Comment by rhendric** [comment]
Ahhh, of course, how silly of me. I didn't realize the output was referring to a different file. Yeah, that seems like a good theory. I wonder what we should do about it? Force determinism into the compiler, or make this test more lax?

**Comment by rhendric** [comment]
You were right, the output depends on which file appears first in the list of files to compile, which in the test program is determined by a call to [`System.FilePath.Glob.globDir`](https://hackage.haskell.org/package/Glob-0.10.0/docs/System-FilePath-Glob.html#v:globDir), which is documented, ‘The results are not in any defined order.’ (It looks like everything downstream of that uses stable sorting and grouping functions.) Inserting a sort in the test framework seems the right thing to do; see #3811.
