### ISSUE TITLE
Make ghcid no longer works with multi-package setup

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3820]
I wonder if there's anything we can do about this. Currently ghcid will only watch and recompile if you are editing anything under `src`. GHCi is notoriously difficult to get working with multi-package setups, and I haven't found a configuration that works yet. Adding `purescript-ast` and `purescript-cst` to the ghci command results in conflicts (expecting things to be from one of the libs, but ghci has put it all in one scope).

**Comment by joneshf** [comment]
Are we sure `ghcid` not working is an artifact of having multiple packages? I tried using it before splitting the packages and ran into some error with `ghcid`. Was it working for you recently?

**Comment by joneshf** [comment]
I just checked out 281eb3cad88a26865472c4dad37e9aa30c485204 (a commit before the package split), removed all artifacts (to start from a clean slate), ran `make ghcid`, and this is what it spit out:
```
/home/joneshf/programming/purescript/purescript/src/Language/PureScript/CST.hs:31:1-37: error:
    Could not find module ‘Language.PureScript.CST.Parser’
    Perhaps you meant
      Language.JavaScript.Parser (from language-javascript-0.7.0.0)
    Use -v to see a list of the files searched for.
   |
31 | import Language.PureScript.CST.Parser
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I don't remember exactly if this was the same error I ran into before, but I do remember it failing to run. Is it similar for you, or does it also work?

**Comment by natefaubion** [comment]
> I tried using it before splitting the packages and ran into some error with ghcid. I had assumed that make rule was bit rotted. Was it working for you recently? If so, how'd you get it to work?

Yes, it's how I do most of my work on the compiler. It's always just worked for me.

If you add purescript-cst and purescript-ast to the command:
```
ghcid --command "stack ghci purescript:lib purescript:test:tests purescript-ast:lib purescript-cst:lib --ghci-options -fno-code"
```

You'll get errors like:
```
1: error:
    Could not load module ‘Language.PureScript.Names’
    It is a member of the hidden package ‘purescript-ast-0.1.0.0’.
    You can run ‘:set -package purescript-ast’ to expose it.
    (Note: this unloads all the modules in the current scope.)
   |
16 | import qualified "purescript-ast" Language.PureScript.Names as N
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If you follow this advice:
```
ghcid --command "stack ghci purescript:lib purescript:test:tests purescript-ast:lib purescript-cst:lib --ghci-options '-fno-code -package purescript-ast'"
```

You'll get errors like:
```
purescript/lib/purescript-cst/.stack-work/dist/x86_64-osx/Cabal-2.4.0.
1/build/Language/PureScript/CST/Parser.hs:1500:41: error:
    • Couldn't match type ‘Language.PureScript.Names.ModuleName’
                     with ‘N.ModuleName’
      NB: ‘N.ModuleName’ is defined at
            /Users/nathan/Sites/git/purescript/lib/purescript-ast/src/Language/PureScript/Name
s.hs:(155,1)-(156,35)
          ‘Language.PureScript.Names.ModuleName’
            is defined in ‘Language.PureScript.Names’
                in package ‘purescript-ast-0.1.0.0’
      Expected type: Name N.ModuleName
        Actual type: Name Language.PureScript.Names.ModuleName
    • In the first argument of ‘happyIn26’, namely ‘r’
      In the first argument of ‘happyReturn’, namely ‘(happyIn26 r)’
      In the expression: happyReturn (happyIn26 r)
     |
1500 |         ) (\r -> happyReturn (happyIn26 r))
     |                                         ^
```
But this happens for _everything_ referenced from purescript-ast (so it's not just a cst parser issue). I'm not sure why "purescript-ast" is hidden, and I'm guessing that using the `-package` flag conflicts with package imports in ghci.

**Comment by joneshf** [comment]
Huh, weird that that commit (or the rule in general) doesn't break for you but does for me.

If the `PackageImports` extension is causing problems, let's remove it. As mentioned when they were introduced, I don't have a strong enough will to force them to stay in this repo.

If the split packages is causing problems, let's revert it. As mentioned in that PR, I'm not going to push hard for it. I'll maintain my fork indefinitely, if need be.

**Comment by natefaubion** [comment]
I'm not suggesting we do either, I just don't know enough about internals of GHCi to diagnose it. I suspect that package imports might be an issue because putting them all in a ghci session effectively amounts to pretending they are all in the same package.

**Comment by natefaubion** [comment]
I was able to get ghcid working again by:
* Use the command `ghcid --command "stack ghci purescript:lib purescript:test:tests purescript-ast purescript-cst --ghci-options -fno-code"`
* Removing package imports (for reason stated above, it needs to pretend that these are all in the same package).
* Making everything compile under the same language flags.

The last one is an issue because of ast enabling `TypeFamilies` globally which implies `MonoLocalBinds`. This breaks some code here and there (which can be fixed by a type signature or disabling the extension for that module). We should really be using the same extensions everywhere anyway.

**Comment by joneshf** [comment]
> I'm not suggesting we do either, I just don't know enough about internals of GHCi to diagnose it.

Same. I'm just making it clear that I'm down with either of these options.

> The last one is an issue because of ast enabling `TypeFamilies` globally which implies `MonoLocalBinds`. This breaks some code here and there (which can be fixed by a type signature or disabling the extension for that module).

Another option is to not turn on `TypeFamilies` globally for `purescript-ast` (or the project in general). It doesn't have to be on everywhere, it just made it into the list by happenstance of being in one module.

I know there's a want to be able to copy/paste any code anywhere and have it work, but some of these language extensions are too wild for that.

> We should really be using the same extensions everywhere anyway.

This is being tracked in #3805. There's _a_ plan there, but not the only plan. Feel free to do whatever to push that forward.

**Comment by joneshf** [comment]
Also, in case it's not clear, I'll gladly review a PR if you assign me to it.

**Comment by natefaubion** [comment]
> This is being tracked in #3805. There's a plan there, but not the only plan. Feel free to do whatever to push that forward.

Ah, great. I remember seeing that, but it passed under my radar. Thanks for reminding me.

**Comment by natefaubion** [comment]
I don't have a problem with global `TypeFamilies`. I think we should be compiling with `MonoLocalBinds` anyway.

**Comment by joneshf** [comment]
With #3821 being merged, does this work again? If so, let's close this.

**Comment by joneshf** [comment]
Side question, is the underlying want to use `ghcid` specifically or is it to have a quick feedback loop during development no matter the tool used?

**Comment by natefaubion** [comment]
I still need to merge #3823 and PR a change to the `make ghcid` command.

It's to have an (mostly) instantaneous feedback loop in my editor on save. `ghcid` is the only way I've been able to reliably get that. I've tried all the other ide integrations and they either don't work (none of them like multiple package setups) or they leak memory, or are slower than just running ghc manually in a shell.

**Comment by joneshf** [comment]
Gotcha. Thanks for explaining.

**Comment by joneshf** [comment]
Again, sorry for breaking this workflow.

**Comment by natefaubion** [comment]
> Again, sorry for breaking this workflow.

No worries at all. Just Haskell things...
