### ISSUE TITLE
Improve GitHub issues

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript#3832]
# Situation

There's been quite a few issues closed with a redirect link elsewhere. For instance, these are all responded with pointing to Discourse:

* https://github.com/purescript/purescript/issues/3542
* https://github.com/purescript/purescript/issues/3589
* https://github.com/purescript/purescript/issues/3671
* https://github.com/purescript/purescript/issues/3674
* https://github.com/purescript/purescript/issues/3723
* https://github.com/purescript/purescript/issues/3755
* https://github.com/purescript/purescript/issues/3757
* https://github.com/purescript/purescript/issues/3784
* https://github.com/purescript/purescript/issues/3786

We don't want questions to end up in the GitHub issue tracker. We want those to go elsewhere. Yet, we're having to triage these after the fact.

# Suggestion

Instead of letting people open an issue that we pretty much know we're going to close with a link elsewhere, we can provide that link up-front.

GitHub has support for [issue template][]s. The templates by themselves help to categorize issue we want people to create. If we know we only want bug reports, compiler improvements, etc, then we can provide templates for those. When we know we want people to raise their question or concern elsewhere, we can provide [`contact_links`][] to those locations.

The documentation around [issue template][]s isn't great but for an example of how this looks in practice, see [TypeScript's new issue chooser][]. For posterity, a screenshot of what it looks like at the moment:
![screenshot-1586109312](https://user-images.githubusercontent.com/1356417/78506073-23bbd480-772c-11ea-81c3-3efc2b1d2a7c.png)

# Proposal
Concrete proposal to implement this:

1. [ ] Follow the steps for [creating issue templates][] to make at least one [issue template][].
1. [ ] Follow the steps for [configuring the template chooser][] to make the [`contact_links`][].

Anyone strongly against doing this?

[`contact_links`]: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
[configuring the template chooser]: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
[creating issue templates]: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates
[issue template]: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates
[typescript's new issue chooser]: https://github.com/microsoft/TypeScript/issues/new/choose

**Comment by garyb** [comment]
This sounds great to me :+1:
