### ISSUE TITLE
Row type inference issue

### ISSUE THREAD

**Issue by IfSixWasNine** [purescript/purescript#3835]
Record types which are parametrized with row types can obviously not properly be inferred by the 0.13.6 compiler when employed for typing function results. 

In the subsequent example, type inference works properly when calling test1 with parameters that are generated by using test2.

However, when trying to perform a composition test1 <<< test3, type inference does NOT work for test3 (cf. compiler 0.13.6. output in the comment).

Can this be fixed? Is there any workaround?

module RowTypeInference where

type Extensible x = { a :: Int | x }

test1 :: forall y . Extensible y -> Int
test1 e = e.a 

test2 :: Boolean -> Int
test2 false = test1 { a:4 }
test2 true = test1 { a:2, b:"x" }  

{-
test3 :: Boolean -> forall y . Extensible y
test3 false = { a:4 }
test3 true = { a:2, b:"x" }

at src/RowTypeInference.purs:14:15 - 14:22 (line 14, column 15 - line 14, column 22)

  Expression
          
    { a: 4
    }     
          
  does not have type
              
    { a :: Int
    | y0      
    }         
              

while checking that expression case $1 of         
                                 false -> { a: ...
                                          }       
                                 true -> { a: ... 
                                         , b: ... 
                                         }        
  has type { a :: Int
           | y0      
           }         
in value declaration test3

where y0 is a rigid type variable
        bound at (line 0, column 0 - line 0, column 0)

See https://github.com/purescript/documentation/blob/master/errors/ExprDoesNotHaveType.md for more information,
or to contribute content related to this error.

[error] Failed to build.
-}

**Comment by hdgarrood** [comment]
This is correct. You can’t construct a record whose type is `forall y. { x :: Int | y }` because you’re claiming that wherever it is used, the use site can decide what the rest of the fields are, and the record can just magic up those fields. You may be after existential quantification (exists) rather than universal (forall).

**Comment by IfSixWasNine** [comment]
Thanks Harry

for this rapid clarification!

Is there any means to generate polymorphic objects for flexible calls of Javascript functions without using a number of dedicated variants modeled via ADTs?

E.g. there are numerous JavaScript functions such as the browser MediaTrackConstraints parameters where polymorphic types would be a suitable way for ad-hoc typing of parameters.

The (minor) disadvantage of ADTs is that there is a tighter dependency on the compiled FFI code, meaning there is always at least a "value0" that needs to be de referenced.

**Comment by hdgarrood** [comment]
Can I request that we move this discussion to Discourse? We prefer to keep the issue tracker for tracking compiler work. You’ll probably get more responses there, too.

**Comment by hdgarrood** [comment]
I think https://discourse.purescript.org/t/how-to-create-a-javascript-object-with-a-value-that-doesnt-have-a-fixed-type/1233 is relevant

**Comment by IfSixWasNine** [comment]
OK, Thanks, I've reiceived sufficient feedback. In addition, your linked discussion also helps me further. So, I close the issue and we can continue to discuss outside the bug tracker if needed.

Thanks again!
