### ISSUE TITLE
Support for visible type application

### ISSUE THREAD

**Issue by lykahb** [purescript/purescript#3844]
Haskell has a handy Visible type application feature. It would be great to have it ported to PureScript. Ideally, it would work with kinds too, so that one could write `put (SProxy @ "apple")` instead of `put (SProxy :: SProxy "apple")`
The GHC wiki has a [proposal](https://gitlab.haskell.org/ghc/ghc/-/wikis/type-application) that includes motivation and design.

**Comment by natefaubion** [comment]
Please see discussion in #3137
