### ISSUE TITLE
Add BigInt and syntactical support for it

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3848]
Via [caniuse.com](https://caniuse.com/#feat=bigint), it seems the main browsers support it now, but it's still not widespread yet. Regardless, the latest version of Node (v13.12.0) supports it, so things running on that backend could still benefit from it.
```purescript
data BigInt :: Type

normalSyntax :: BigInt
normalSyntax = 123456789012345n

underscoreSyntax :: BigInt
underscoreSyntax = 123_456_789_012_345n
```
I imagine support for this would need to be added to `language-javascript` if it hasn't been already.

**Comment by hdgarrood** [comment]
We already have [purescript-bigints](https://pursuit.purescript.org/packages/purescript-bigints), which we use quite heavily in production at Lumi, and it does the job well. I'd like to see a stronger case for adding bigints to the language as opposed to having them in a library. The benefits I can think of are:

- it's more comfortable to write literals which are larger than what Int allows (as right now you'd have to put them in a string and use `unsafePartial <<< fromJust <<< BigInt.fromString`),
- we can depend on `BigInt` higher up in the ecosystem, e.g. the `degree` function from `EuclideanRing` should really return a `BigInt`.

Are there others? For me, the above reasons alone aren't quite compelling enough to support adding bigints to the language, at least not at the current moment in time.

**Comment by JordanMartinez** [comment]
The only other one I can think of is not needing to rely upon an NPM package like BigIntegers.js to make this work. However, that might be necessary for polyfilling until more browsers support it.

Other than that, I can't think of any myself.

**Comment by natefaubion** [comment]
Adding it to the language also means that all backends must provide support for it as well. I don't think we should consider this until there is broader, stable support for it.

**Comment by JordanMartinez** [comment]
Makes sense. I'll close this then. We can reopen it when the support for BigInts becomes more widespread among browsers and support for non-JS backends becomes stronger.

**Comment by srghma** [comment]
probably it's time, because [ethereumjs have removed all polyfills and now use BigInt](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/rlp%403.0.0)

Also, I should note that BigInt right now doesn't support custom radixes when converting from String (one have to use [these slow functions](https://stackoverflow.com/questions/55646698/base-36-to-bigint)

(the proposal for this is [here](https://github.com/tc39/proposal-number-fromstring))

to convert from string - this is all that is possible (correct me if I'm wrong)

```js
const fromDecimalToBigInt = str => BigInt(str)
const fromHexToBigInt = str => BigInt("0x" + str)
const fromOctalToBigInt = str => BigInt("0o" + str)
const fromBinaryToBigInt = str => BigInt("0b" + str)
```

so having

```purs
0xfffffn
0o7777n
0b1111n
1n

-0xfffffn
-0o7777n
-0b1111n
-1n
```

**Comment by rhendric** [comment]
@srghma, have you tried [`Data.BigInt.fromBase`](https://pursuit.purescript.org/packages/purescript-bigints/4.0.0/docs/Data.BigInt#v:fromBase)? Are you saying it's too slow for your needs?

**Comment by srghma** [comment]
Good that You asked, https://www.npmjs.com/package/big-integer is not compatible with ethereum 

https://github.com/peterolson/BigInteger.js/blob/f4e2c23423ed5c6ec22b81e2861449fcba46416b/BigInteger.js#L1440

https://github.com/ethereumjs/ethereumjs-monorepo/blob/f4f34c8d668c359aa56abd984ffa69aaac4f1b08/packages/rlp/src/index.ts#L274

![Screenshot (1)](https://user-images.githubusercontent.com/7573215/154761009-a635f056-720f-4248-bb60-6c15c0887332.png)

**Comment by srghma** [comment]
> I imagine support for this would need to be added to language-javascript if it hasn't been already.

good news, support is already here, it even parses what should not be parsed

![2022-02-18-11pm-16-50-screenshot](https://user-images.githubusercontent.com/7573215/154762312-b1c10629-6efc-45de-9100-de0cd873129b.png)
