### ISSUE TITLE
If in do issues

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#386]
The impossible happened in desugarDo:
```
test = do 
  if true 
  then return true 
  else return false
```

Let statement cannot be the last statement in a do block:
```
test = do 
  let x = 1
  if true 
  then return true 
  else return false
```

**Comment by michaelficarra** [comment]
I've managed to trigger the compiler crash with the same error as @garyb (using 0.6.9.5):

> psc: The impossible happened in desugarDo

I believe it was code like this that triggered it:

```purs
... $ \a -> do
  if a then do
    ...
  else do
    ...
```

I fixed the problem by removing that first unnecessary `do`.

**Comment by sharkdp** [comment]
Possibly related: the same compiler error (`the impossible happened..`) also appears for empty `do` blocks. It would be convenient if the compiler would throw a compile error (Error at ...: Empty do block).
