### ISSUE TITLE
Multiple supperclasses

### ISSUE THREAD

**Issue by srghma** [purescript/purescript#3865]
## Description

is it possible to define class with multiple supperclasses?

## To Reproduce

it is possible to write

```purs
class Foo a b <= Bar a
```

but when I write

```purs
class Foo a b <= Bar a <= Baz b
```

it throws error `Unexpected token '<='`

or

```purs
class Foo a b <= (Bar a, Baz b)
```

it throws error `Unexpected token '('`

or

```purs
class Foo a b <= Bar a, Baz b
```

it throws error `Unexpected token ','`

## Expected behavior

it should support multiple inheritances with either of these syntaxes

## PureScript version

0.13.6

## Context

this is not very important, just wanted to notify that it's not possible to write multiple superclasses, thought type of `ClassHead` allows it

```
  , clsSuper :: Maybe (OneOrDelimited (Constraint a), SourceToken)
```

**Comment by hdgarrood** [comment]
It is possible, here’s an example:

https://github.com/purescript/purescript-prelude/blob/v4.1.1/src/Data/Field.purs#L39-L39

**Comment by srghma** [comment]
oh, it's on left side, I misunderstood, tnx
