### ISSUE TITLE
Explicit roles may be more permissive than inferred

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3867]
## Description

When an explicit role annotation is provided, the user is able to give a less restrictive role than what the compiler would have inferred. This is a problem because it allows you to make invalid coercions, compromising the safety of `Coercible`:

```purescript
module Main where

import Safe.Coerce (coerce)

data Oops a = Oops a

unOops (Oops x) = x

type role Oops phantom -- This should be rejected

invalid :: forall a b. a -> b
invalid x = unOops (coerce (Oops x))
```

## To Reproduce

Provide an explicit role declaration in which at least one parameter is given a more permissive role than its inferred role would have been.

## Expected behavior

The compiler rejects the program, with a message saying that the roles given are too permissive.

**Comment by hdgarrood** [comment]
Currently, `foreign import data` types have the nominal role inferred for all of their parameters, which is maximally restrictive, so perhaps we should continue to allow explicit annotations to relax roles in the case of `foreign import data`.

**Comment by hdgarrood** [comment]
Additionally, it looks to me like we don't actually store inferred roles anywhere (only explicit role declarations end up in the Environment and in externs files). This does not seem ideal, because for types which don't have role declarations, I think we will end up inferring their roles repeatedly, i.e. every time the type appears in a `Coercible` constraint being solved. In fact, I think we should consider determining roles eagerly, i.e. before the type is used in any `Coercible` constraint. That way, we can store roles in Environments and externs files unconditionally, and avoid having to recompute them if they're used repeatedly downstream. Note that we have to eagerly infer roles if there is a role declaration in any case, because we need to produce an error at the site of the role declaration if that declaration is more permissive than the inferred one.

**Comment by hdgarrood** [comment]
@lunaris do you have any thoughts on the above? No worries if you don't have time / don't remember doing this work well enough to say.

**Comment by lunaris** [comment]
I have thoughts but I am not sure how useful they are and don't expect to be able to contribute much more at the present time 😄 

* Agree with inferring roles once and putting them in the environment -- definitely an oversight on my part when I first implemented the feature.
* On strictness, I'm inclined to do what GHC Haskell does -- that is, it rejects it with something like:

```
    Role mismatch on variable a:
      Annotation says phantom but role representational is required
    while checking a role annotation for ‘T’
```

* This is slightly annoying as it means we need a special case for `foreign import data` but I think that's the right call here (at first blush; perhaps I should give deeper thought before lunging in with this reply).

**Comment by hdgarrood** [comment]
Ok great, thanks. I'm going to take a stab at this.
