### ISSUE TITLE
Need to expand type synonyms during role inference

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3871]
## Description

Type synonyms are currently treated by the type checker as having all of their arguments being "phantom", i.e. anything happening under a type synonym is ignored. This can lead to invalid coercions; for example:

```purescript
module Main where
import Safe.Coerce (coerce)
newtype Age = Age Int
data Maybe a = Just a | Nothing
type SMaybe a = Maybe a
data G a = G (SMaybe a)
-- This is okay
testA :: G Age -> G Int
testA = coerce
-- This is not
testB :: G Age -> G String
testB = coerce
```
Instead, the compiler should expand type synonyms as necessary during role inference.

## To Reproduce

Use a parameterised type synonym within a data type declaration.

## Expected behavior

The type checker should expand type synonyms while inferring roles so that the inferred roles are the same as if the data type had been written without any reference to type synonyms. (We already have a linting step to ensure that we don't have loops in type synonym expansion, so this should be safe, right?)

## PureScript version

master

**Comment by natefaubion** [comment]
We need to make sure role inference is done after kind inference.

**Comment by hdgarrood** [comment]
I can't quite work out why at first glance - could you show an example of what might go wrong if we did them in the wrong order?

**Comment by natefaubion** [comment]
Kind inference elaborates kind applications, which is necessary for expanding polykinded type synonyms.

**Comment by hdgarrood** [comment]
Ahh, gotcha.

**Comment by kl0tl** [comment]
I think I have a fix for this but it depends on https://github.com/purescript/purescript/pull/3860.
