### ISSUE TITLE
Coercible constraints on rows aren’t solved

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript#3875]
## Description

Rows are only considered when inferring roles for constructors holding types parametrized by rows.

Given the following declaration of `Rec1`:

https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/tests/purs/passing/Coercible.purs#L103

When inferring its roles we discover its only constructor holds a `Record (f :: a)`, which is representational in its row so we consider the types in the row (here the type variable `a`) and infer the `a` parameter of `Rec1` to be representational.

And indeed we can coerce `Rec1 a` to `Rec1 b` given `Coercible a b`:

https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/tests/purs/passing/Coercible.purs#L105-L106

But we can’t coerce the underlying records themselves.

## To Reproduce

```purs
module Example where

import Safe.Coerce (coerce)

newtype N a = N a

example :: { x :: Int } -> { x :: N Tnt }
example = coerce
```

```
Error found:
in module Example
at Example.purs:8:11 - 8:17 (line 8, column 11 - line 8, column 17)

  No type class instance was found for
                                      
    Prim.Coerce.Coercible ( x :: Int  
                          )           
                          ( x :: N Int
                          )           
                                      

while checking that type forall (a :: Type) (b :: Type). Coercible a b => a -> b
  is at least as general as type { x :: Int     
                                 }              
                                 -> { x :: N Int
                                    }           
while checking that expression coerce
  has type { x :: Int     
           }              
           -> { x :: N Int
              }           
in value declaration example

See https://github.com/purescript/documentation/blob/master/errors/NoInstanceFound.md for more information,
or to contribute content related to this error.
```

## Expected behavior

`coercibleWanteds` in `Language.PureScript.TypeChecker.Entailment` should decompose rows into `Coercible` constraints for types with the same labels in both rows and fail when the rows length or labels don’t match.

For instance `Coercible ( x :: Int ) ( x :: N Int )` should yield the subgoal `Coercible Int (N Int)` and `Coercible ( x :: Int, y :: String ) ( x :: N Int, y :: N String)` should yield the subgoals `Coercible Int (N Int)` and `Coercible String (N String)` but `Coercible ( x :: Int ) ()` and `Coercible ( x :: Int ) ( y :: N Int )` should fail.

## PureScript version

master (df3170f5bb0ba21517e2ca72db6aee5c479c99df)

**Comment by hdgarrood** [comment]
Come to think of it, this probably doesn't need to be fixed for v0.14.0, does it? It's inconvenient but it only prevents you from doing things that you might expect to be able to do; it doesn't let you do things you shouldn't be allowed to do. Should we remove the milestone and aim to fix this in v0.14.1?
