### ISSUE TITLE
Can declare roles multiple times

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript#3876]
## Description

Multiple roles declarations are authorized but only the last one is considered.

## To Reproduce

```purs
module Example where

import Safe.Coerce (coerce)

data A a = A
type role A nominal
type role A phantom

example :: ∀ a b. A a -> A b
example = coerce
```

## Expected behavior

The compiler shouldn’t allow duplicate role annotations.

GHC fails with the following message in that situation:

```
Example.hs:6:1: error:
    Duplicate role annotations for ‘A’:
      type role A nominal -- written at Example.hs:6:1-19
      type role A phantom -- written at Example.hs:7:1-19
  |
6 | type role A nominal
  | ^^^^^^^^^^^^^^^^^^^
```

## PureScript version

master (df3170f5bb0ba21517e2ca72db6aee5c479c99df)

**Comment by hdgarrood** [comment]
Thanks! I think we should check for this in a desugaring step at the same time as checking that any referenced types actually exist (#3870).
