### ISSUE TITLE
Proposal: Wildcards in role declarations

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript#3882]
## Summary

Allow role declarations to leave some roles unspecified by replacing them with `_`.

Those roles should be inferred by the compiler.

## Motivation

This is mostly for convenience when restricting some of the parameters of a type.

Also GHC allows this, see https://downloads.haskell.org/ghc/latest/docs/html/users_guide/glasgow_exts.html#role-annotations.

## Proposal

I _think_ this is a matter of parsing roles to `Maybe Role` and assigning `Phantom` to `Nothing` when inferring roles. I have a vague idea of how to do it and would be happy to implement this proposal should it be accepted.

## Examples

```purs
module Example where

data F a b
type role F nominal _
```

**Comment by natefaubion** [comment]
Role annotations aren't particularly common, and I don't think it's a burden to provide them for all arguments. I personally think a signature like this, when provided, should always be complete.

**Comment by garyb** [comment]
I'm in favour of requiring complete role signatures too - we don't allow `_` in declarations at the top level normally, `Generic` and `Newtype` deriving aside, but the meaning is a bit different there / a consequence of not having associated types.

**Comment by hdgarrood** [comment]
I don't feel particularly strongly on this, but not allowing wildcards in role declarations sounds reasonable to me. I think "not particularly common" is probably an understatement.

**Comment by kl0tl** [comment]
That’s fair, let‘s close this then.
