### ISSUE TITLE
purs fails to update corefn output

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3914]
## Description

When I modify code and run `purs compile --codegn corefn` the `corefn.json` file is not updated unless one deletes it first.

## To Reproduce

Compile your project with
```
purs compile --codegen corefn **/*.purs
```
Modify one of the modules and recompile it with the same command.

## Expected behavior

`coregn.json` should be updated.

## PureScript version

0.13.8

**Comment by hdgarrood** [comment]
I think this might be related to #3911; there might be a bug where the compiler is failing to update the "nonstandard" `--codegen` targets like `corefn` or `docs` if the externs file is already up to date.

**Comment by nwolverson** [comment]
What I presume is another instance of the same underlying issue, `purs ide server` with the `--codegen corefn` option, compiling on save, does not seem to build the `js` when a standard`purs compile` is run (context: that was my default configuration as I also use an alternate backend). Guessing the assumption is that if the externs is up to date then all targets must have been generated.

**Comment by hdgarrood** [comment]
Sounds likely. Externs are generated unconditionally, so I think we should only consider the other targets to be up to date if their modified times are greater than or equal to the externs file’s modified time.

**Comment by hdgarrood** [comment]
Should be fixed by #4053.
