### ISSUE TITLE
Proposal: STFn functions -> create lib and add compiler support

### ISSUE THREAD

**Issue by srghma** [purescript/purescript#3923]
## Summary

_Originally posted by @hdgarrood in https://github.com/purescript/purescript-arrays/pull/178#issuecomment-680965097_

The idea would be that we have a collection of data types like
```
STFn1 :: Type -> Type
STFn2 :: Type -> Type -> Type
STFn3 :: Type -> Type -> Type -> Type
```
and so on, like `EffectFn{1,2,3}`, which would perform their effects immediately rather than returning a nullary function, together with inlinable functions like
```
runSTFn1 :: forall a h r. STFn1 a r -> a -> ST h r
runSTFn2 :: forall a b h r. STFn2 a b r -> a -> b -> ST h r
```
and so on, so that code like
```purescript
ST.run do
  arr <- STArray.new
  _ <- runSTFn2 STArray.push arr 3
  pure (STArray.unsafeFreeze arr)
```
might compile to something like
```javascript
function () {
  var arr = STArray.new();
  Data_Array_ST.push(arr, 3);
  return unsafeFreezeImpl(arr);
}
```
where `Data_Array_ST.push` would have the type `forall a. STFn2 (Array a) a Int`.

## Motivation

To make ST code as fast as FFI

https://github.com/purescript/purescript-arrays/pull/178#issuecomment-680938969

**Comment by hdgarrood** [comment]
I guess this would be obsoleted if we did https://github.com/purescript/purescript-st/issues/31

**Comment by JordanMartinez** [comment]
I believe this was added in #4386.
