### ISSUE TITLE
Core library updates for 0.14

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3942]
Opening this issue to keep track of core library updates for 0.14. I've managed to get @garyb's purescript-dependency-helper running again (see https://github.com/hdgarrood/purescript-dependency-helper) so that I could produce this list. The list is topologically sorted so that if we update the libraries in this order, any library we start working on should already have had its dependencies updated.

I think the procedure for each library should be more or less this:

* Update .travis.yml to grab the most recent RC (see eg https://github.com/purescript/purescript-prelude/commit/268870d5ec7d8f425f952d6db8307c8d06e3a75d)
* If there's already an 0.14 branch, merge that into master
* Temporarily update bower.json to pull the master versions of all dependencies
* Make sure `psa` in package.json is on v0.8.0 or newer (because of the stderr/stdout changes)
* Merge any outstanding PRs with breaking changes
* Look over the issues to see if there are any breaking changes we want to do now

Once we have v0.14.0 tagged, we should go back over all of these libraries in the same order and do the following for each:

* Revert the changes to .travis.yml so that the most recent compiler version is pulled in
* Update dependencies in bower.json to specify real version ranges, rather than master
* Tag a version and update the package-sets repo

- [x] [prelude](https://github.com/purescript/purescript-prelude.git)
- [x] [math](https://github.com/purescript/purescript-math)
- [x] [effect](https://github.com/purescript/purescript-effect.git)
- [x] [functions](https://github.com/purescript/purescript-functions.git)
- [x] [console](https://github.com/purescript/purescript-console.git)
- [x] [refs](https://github.com/purescript/purescript-refs.git)
- [x] [assert](https://github.com/purescript/purescript-assert.git)
- [x] [newtype](https://github.com/purescript/purescript-newtype.git)
- [x] [bifunctors](https://github.com/purescript/purescript-bifunctors.git)
- [x] [control](https://github.com/purescript/purescript-control.git)
- [x] [psci-support](https://github.com/purescript/purescript-psci-support.git)
- [x] [invariant](https://github.com/purescript/purescript-invariant.git)
- [x] [maybe](https://github.com/purescript/purescript-maybe.git)
- [x] [numbers](https://github.com/purescript/purescript-numbers)
- [x] [orders](https://github.com/purescript/purescript-orders.git)
- [x] [foldable-traversable](https://github.com/purescript/purescript-foldable-traversable.git)
- [x] [either](https://github.com/purescript/purescript-either.git)
- [x] [exceptions](https://github.com/purescript/purescript-exceptions.git)
- [x] [identity](https://github.com/purescript/purescript-identity.git)
- [x] [distributive](https://github.com/purescript/purescript-distributive.git)
- [x] [tailrec](https://github.com/purescript/purescript-tailrec.git)
- [x] [st](https://github.com/purescript/purescript-st.git)
- [x] [record](https://github.com/purescript/purescript-record.git)
- [x] [lazy](https://github.com/purescript/purescript-lazy.git)
- [x] [tuples](https://github.com/purescript/purescript-tuples.git)
- [x] [contravariant](https://github.com/purescript/purescript-contravariant.git)
- [x] [const](https://github.com/purescript/purescript-const.git)
- [x] [profunctor](https://github.com/purescript/purescript-profunctor.git) (https://github.com/purescript/purescript-profunctor/issues/23)
- [x] [unfoldable](https://github.com/purescript/purescript-unfoldable.git)
- [x] [nonempty](https://github.com/purescript/purescript-nonempty.git)
- [x] [exists](https://github.com/purescript/purescript-exists.git)
- [x] [arrays](https://github.com/purescript/purescript-arrays.git) (https://github.com/purescript/purescript-arrays/issues/192)
- [x] [gen](https://github.com/purescript/purescript-gen.git)
- [x] [enums](https://github.com/purescript/purescript-enums.git)
- [x] [generics-rep](https://github.com/purescript/purescript-generics-rep.git)
- [x] [lists](https://github.com/purescript/purescript-lists.git) (https://github.com/purescript/purescript-lists/pull/181)
- [x] [catenable-lists](https://github.com/purescript/purescript-catenable-lists.git)
- [x] [ordered-collections](https://github.com/purescript/purescript-ordered-collections.git)
- [x] [transformers](https://github.com/purescript/purescript-transformers.git)
- [x] [free](https://github.com/purescript/purescript-free.git)
- [x] [proxy](https://github.com/purescript/purescript-proxy.git)
- [x] [typelevel-prelude](https://github.com/purescript/purescript-typelevel-prelude.git)
- [x] [foreign-object](https://github.com/purescript/purescript-foreign-object.git)
- [x] [globals](https://github.com/purescript/purescript-globals.git)
- [x] [integers](https://github.com/purescript/purescript-integers.git)
- [x] [datetime](https://github.com/purescript/purescript-datetime.git)
- [x] [random](https://github.com/purescript/purescript-random.git)
- [x] [lcg](https://github.com/purescript/purescript-lcg.git)
- [x] [strings](https://github.com/purescript/purescript-strings.git)
- [x] [foreign](https://github.com/purescript/purescript-foreign.git) (https://github.com/purescript/purescript-foreign/pull/74)
- [x] [quickcheck](https://github.com/purescript/purescript-quickcheck.git)
- [x] [functors](https://github.com/purescript/purescript-functors.git)
- [x] [parallel](https://github.com/purescript/purescript-parallel.git)
- [x] [minibench](https://github.com/purescript/purescript-minibench.git)
- [x] [validation](https://github.com/purescript/purescript-validation.git)
- [x] [semirings](https://github.com/purescript/purescript-semirings.git)
- [x] [graphs](https://github.com/purescript/purescript-graphs)

**Comment by garyb** [comment]
Oh nice! Glad you could figure out the `dependency-helper`, I think it was hacked together very haphazardly, probably should have done it in PS 😄.

**Comment by hdgarrood** [comment]
The main issue was a breaking change in bower's API, so I'm not sure it would have made much difference to have it in PS in this case anyway.

**Comment by JordanMartinez** [comment]
Strange... This was the list my package-graph program outputted: 
[purescriptLib.txt](https://github.com/purescript/purescript/files/5322070/purescriptLib.txt)


It has `quickcheck` last because it depends on everything else.

**Comment by hdgarrood** [comment]
Topological ordering of libraries like this generally aren’t unique; there are multiple valid ways of ordering them such that every library occurs after its dependencies. For example, if you have three libraries A, B, C, such that B and C both depend on A, then you can order them in two ways: ABC or ACB. For the above list, the quickcheck library doesn’t depend on any of functors, parallel, minibench, validation, or semirings, so it doesn’t have to come after them.

**Comment by afcondon** [comment]
which would be a good reason to see it as a graph/tree rather than a list...hope to help with that someday not-soon-but-medium-term-ish

**Comment by garyb** [comment]
Outputting a `dot` from that dependency updater script thing is easy enough, I had it doing that at one point. It's just not very useful to use a graphic when you want a list you can check things off in in GH :smile:

**Comment by afcondon** [comment]
Fair point!

**Comment by garyb** [comment]
Actually, that might be a fun little project though - have a visual version of the hierarchy, could colour-code them for which are ready to be worked on, etc. and could link it back to a GH issue as a flat list since the names of the nodes in the graph will be unique. If you wanted to get fancy, could probably use the GH API to have checkboxes in the visual graph that would update the original issue too, rather than it just being a visualisation.

**Comment by thomashoneyman** [comment]
Especially because we need to do this for `-contrib`, too, and it would be _really_ nice to see what libraries become unblocked once a particular library has been updated. Otherwise we have to go cross-reference dependencies every time we want to update something, which can get pretty annoying over time.

**Comment by afcondon** [comment]
i have three repos (little more than gists, but pointers to a vaguely unified solution in this space that exists only in my head) that are relevant to this...a DSL for D3, a half-baked port of the haskell parser for dot files and a little PureScript program that renders the existing `purs` graph output using D3's force-layout...not much but if it helps anyone working in that direction, so much the better.

There's a potential for very strong tooling with not-so-heroic effort for Purescript using those elements (plus parser for CoreFn output and graphing of same).

**Comment by JordanMartinez** [comment]
Harry updated `effect` to v0.14.0

I've submitted PRs to the following repos
- unsafe-coerce (merged and no other work to do)
- prelude (merged and I believe will have no other work)
- invariant (waiting to be merged)
- refs (waiting to be merged)
- console (waiting to be merged)
- newtype (waiting to be merged)
- partial (waiting to be merged)
- functions (waiting to be merged)

**Comment by csicar** [comment]
I'll be working on:
- [ ] typelevel-prelude

**Comment by JordanMartinez** [comment]
Just a thought, but should PRs link back to this issue, so we know which repos have an open PR already?

**Comment by JordanMartinez** [comment]
Note: this meta-repo search shows (for the most part) all PRs submitted to update a library to v0.14.0: https://github.com/search?q=org%3Apurescript+is%3Apr+state%3Aopen+Update+to+v0.14.0

**Comment by JordanMartinez** [comment]
I'm taking `maybe`.

**Comment by JordanMartinez** [comment]
I'm taking `globals`

**Comment by JordanMartinez** [comment]
Taking `foldable-traversable`

**Comment by JordanMartinez** [comment]
Taking `either`

**Comment by JordanMartinez** [comment]
Taking `identity`

**Comment by JordanMartinez** [comment]
Taking `orders`

**Comment by JordanMartinez** [comment]
Taking `integers`

**Comment by JordanMartinez** [comment]
Forgot to say it, but I took `distributive` and `lazy`.

I'm now taking `validation`

**Comment by paluh** [comment]
I've just (auto)updated `exceptions`

**Comment by hdgarrood** [comment]
While `control` is updated, I've unchecked it as I'd like to resolve purescript/purescript-control#62 first.

**Comment by JordanMartinez** [comment]
Thanks for your help @paluh!

**Comment by JordanMartinez** [comment]
I'm taking `contravariant`

**Comment by paluh** [comment]
I'm working on `minibench` right now.

**Comment by JordanMartinez** [comment]
As noted on Slack, it seems that we're getting bottlenecked by Travis CI. For some reason, builds are hanging for 30+ minutes at the 'Queued' stage.

**Comment by hdgarrood** [comment]
Maybe they've decided that too many builds have been started from the `purescript` org and are rate-limiting us? This seems like a good opportunity to switch to GitHub actions. I think it should be fairly easy since the core library CI setups are quite simple.

**Comment by thomashoneyman** [comment]
@hdgarrood setup-purescript could be moved to this organization if desired.

**Comment by hdgarrood** [comment]
Ah, maybe it's a system-wide issue on Travis CI; right now on https://www.traviscistatus.com/ it says there's a backlog of a few thousand builds for Linux

**Comment by hdgarrood** [comment]
I think we should port the existing .travis.yml script used by the core libraries mostly as-is rather than using the setup-purescript readme example if we switch to GH actions, but we can discuss that on a PR.

**Comment by JordanMartinez** [comment]
Here are the current open PRs that are ready to be reviewed and possibly merged:
- https://github.com/purescript/purescript-numbers/pull/12
- https://github.com/purescript/purescript-functors/pull/24
- https://github.com/purescript/purescript-lazy/pull/30

**Comment by rhendric** [comment]
> While `control` is updated, I've unchecked it as I'd like to resolve [purescript/purescript-control#62](https://github.com/purescript/purescript-control/issues/62) first.

@hdgarrood Is this still the plan? It looks like `control` got checked (by @thomashoneyman?) but purescript/purescript-control#62 looks blocked on purescript/purescript-control#63.

**Comment by thomashoneyman** [comment]
My mistake — when reviewing this list I noticed that 0.14 changes had been merged for the library, but I missed that there were other changes “blocking” it from being 0.14-ready. I’ll uncheck it.

**Comment by thomashoneyman** [comment]
Unfortunately it’s a bit difficult to tell what libraries are pending some PRs or issues that we definitely want to be merged / fixed before considering the library 0.14-ready. Perhaps we could introduce a tag indicating what issues and pull requests are considered required before the library is ready?

**Comment by rhendric** [comment]
Probably easier to just link any non-obvious blocking issues/PRs next to the list item (I just did this for `control`).

**Comment by thomashoneyman** [comment]
We should probably apply this broadly, as well:

https://github.com/purescript/purescript-arrays/pull/171

**Comment by JordanMartinez** [comment]
> Unfortunately it’s a bit difficult to tell what libraries are pending some PRs or issues that we definitely want to be merged / fixed before considering the library 0.14-ready. Perhaps we could introduce a tag indicating what issues and pull requests are considered required before the library is ready?

I've been keeping track of v0.14.0-compatibility here: https://github.com/JordanMartinez/updatePsLibs/blob/master/libDeps-purescript.txt

Once all libs are updated, I thought we would use a [meta-search](https://github.com/search?q=org%3Apurescript+state%3Aopen) to determine what other changes we want to make after that.

> We should probably apply this broadly, as well: purescript/purescript-arrays#171

Agreed.

**Comment by thomashoneyman** [comment]
I've just added [math](https://github.com/purescript/purescript-math) and [numbers](https://github.com/purescript/purescript-numbers) to the checklist, as they were previously missing.

**Comment by hdgarrood** [comment]
Thanks! I recently realised that this list originally only included libraries which have a prelude dependency. There might be one one two others I missed.

**Comment by JordanMartinez** [comment]
We currently have [17 core repos left to update](https://github.com/JordanMartinez/updatePsLibs/blob/master/libDeps-purescript.txt). They're all blocked by purescript/purescript-numbers#12, which ports the `Number`-related code from the deprecated `purescript-globals` repo to the `purescript-numbers` repo. 

Just want to say thanks to everyone who has helped out with this process! We're getting there.

**Comment by JordanMartinez** [comment]
Most PRs are currently blocked by this one. No rush, but can someone review it when they have time: https://github.com/purescript/purescript-lcg/pull/9

**Comment by thomashoneyman** [comment]
@JordanMartinez That PR has now been merged. Thanks!

**Comment by JordanMartinez** [comment]
Next batch:
- https://github.com/purescript/purescript-gen/pull/26
- https://github.com/purescript/purescript-lists/pull/175

**Comment by JordanMartinez** [comment]
Next batch:
- https://github.com/purescript/purescript-enums/pull/44
- https://github.com/purescript/purescript-catenable-lists/pull/41
- https://github.com/purescript/purescript-semirings/pull/16 (I'm pretty sure CI will pass once it builds)

**Comment by JordanMartinez** [comment]
Next batch:
- https://github.com/purescript/purescript-generics-rep/pull/42
- https://github.com/purescript/purescript-strings/pull/129

**Comment by JordanMartinez** [comment]
Next batch:
- https://github.com/purescript/purescript-foreign/pull/80
- https://github.com/purescript/purescript-quickcheck/pull/115
- https://github.com/purescript/purescript-free/pull/106

**Comment by JordanMartinez** [comment]
Next batch:
- https://github.com/purescript/purescript-ordered-collections/pull/35

I'll have to troubleshoot the others later.

**Comment by JordanMartinez** [comment]
LAST BATCH! :tada: 

First time building so I assume it will succeed:
- https://github.com/purescript/purescript-datetime/pull/81 ([CI result](https://travis-ci.org/github/purescript/purescript-datetime/builds/743790477))

Problematic ones. CI as of this writing is still queuing:
- https://github.com/purescript/purescript-validation/pull/28 ([CI result](https://travis-ci.org/github/purescript/purescript-validation/builds/735364218))
- https://github.com/purescript/purescript-foreign-object/pull/17 ([CI result](https://travis-ci.org/github/purescript/purescript-foreign-object/builds/743551188))

Assuming the `ordered-collections` merge that happened doesn't affect things, I can't figure out why the CI for these repos aren't building.

**Comment by hdgarrood** [comment]
I suspect it's related to the fact that Travis CI is basically killing its free tier (or at least making it much less appealing). See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. I doubt there's anything we can do other than switch to GitHub Actions or just wait.

**Comment by JordanMartinez** [comment]
> I suspect it's related to the fact

Are you referring to the long 'queue' times? Or the fact that CI is failing when it does end up running? I get the former, but the latter is what surprises me.

**Comment by hdgarrood** [comment]
Oh, never mind, I thought you meant the former.

**Comment by JordanMartinez** [comment]
I figured out what was messing up `foreign-object`. My script didn't update one of the dependencies because it was using version bounds rather than a specific release.

**Comment by JordanMartinez** [comment]
Oh... looks like `validation` had a test dependency on `ordered-collections` as well. That's probably what was causing non-`master` dependencies to get pulled in

**Comment by thomashoneyman** [comment]
We could fairly easily roll out a transition for all core libraries from Travis to GitHub Actions, updating the installation instructions to use Bower at the same time. For example:
https://github.com/purescript/purescript-semirings/pull/17

**Comment by JordanMartinez** [comment]
Ok, these should build now. `datetime` was pulling in `proxy` via a test dependency. `validation` was using `Global (unsafeStringify)`
- https://github.com/purescript/purescript-datetime/pull/81
- https://github.com/purescript/purescript-validation/pull/28

**Comment by JordanMartinez** [comment]
:tada: All core repos now compile on `v0.14.0-rc3` the release. We still haven't made all the breaking changes we want to yet (see the opening thread of this issue), but it'll be easy to see how breaking changes propagate throughout the core repos via the `prepare-0.14` branch in the package sets repo.

**Comment by thomashoneyman** [comment]
I think we missed https://github.com/purescript/purescript-math! But otherwise, 🥇 thank you Jordan for all your work getting these updated. With these libraries compiling on 0.14 we can go ahead and update the `purescript-contrib` libraries as well, circling back for any ones affected by breaking changes in core.

**Comment by JordanMartinez** [comment]
Huh... I guess I did forget about that one. Oh well. I just made a PR for it here: https://github.com/purescript/purescript-math/pull/24

**Comment by JordanMartinez** [comment]
Ok, NOW all core repos are good.

**Comment by JordanMartinez** [comment]
There's a few other PRs made by `kl0tl` that add role declarations. These weren't included in my PRs that update the repos. All his other ones got merged:
- https://github.com/purescript/purescript-exists/pull/9
- https://github.com/purescript/purescript-foreign-object/pull/16

**Comment by JordanMartinez** [comment]
`kl0tl`'s role declaration PRs have been merged.

**Comment by kl0tl** [comment]
I noticed a few remaining references to monomorphic proxies in the following packages:

- https://github.com/purescript/purescript-generics-rep/pull/44
- https://github.com/purescript/purescript-record/pull/67
- https://github.com/purescript/purescript-strings/pull/134
- https://github.com/purescript/purescript-quickcheck/pull/116
- https://github.com/purescript/purescript-typelevel-prelude/pull/64

We want to get rid of them right, or did I misunderstood?

**Comment by hdgarrood** [comment]
Yes, for 0.14 the plan is to deprecate any monomorphic proxy types like SProxy and replace any uses of them with either the Proxy type, or a `proxy` type variable where that's less likely to cause breakage, and the intention is that we will remove the deprecated proxy types in a subsequent release.

**Comment by thomashoneyman** [comment]
Quick update: next week when I and other on the Contributors team are back from vacation we are going to update the libraries in that organization to 0.14 as well. Hopefully by the time the breaking changes are resolved and core is 0.14-ready we will also have contrib ready.

In a perfect world we'd also be able to get Halogen, React Basic, and Concur updated as well in time for the 0.14 package set, though understandably that may not be possible and it's not sufficient reason to hold up the official release.

**Comment by mhmdanas** [comment]
> control (blocked on purescript/purescript-control#62)

The issue was fixed, so it's not blocked anymore.

**Comment by thomashoneyman** [comment]
I've marked control as complete. I've also deprecated proxy, so that's complete as well. Looks like free, transformers, arrays, and strings could all use a little love to get them over the finish line.

**Comment by JordanMartinez** [comment]
`strings` PR just got merged, so I checked it off.

**Comment by kl0tl** [comment]
I checked all core libraries after noticing that `safe-coerce` was missing from the package set (https://github.com/purescript/package-sets/pull/753), and it looks like https://github.com/purescript/purescript-graphs is not in the set either but we also forgot to update the library.

**Comment by JordanMartinez** [comment]
I just created a PR for `graphs`. It didn't show up in my list because nothing depends on it in core and it wasn't in the package set.

**Comment by thomashoneyman** [comment]
@JordanMartinez @kl0tl @hdgarrood I have pull requests open for the `purescript-web` organization migrating CI to GitHub Actions. The next step is for @JordanMartinez to update them for 0.14.3 and merge any open @kl0tl PRs for role annotations.

- https://github.com/purescript-web/purescript-web-html/pull/41
- https://github.com/purescript-web/purescript-web-dom/pull/30
- https://github.com/purescript-web/purescript-web-cssom/pull/6
- https://github.com/purescript-web/purescript-web-uievents/pull/9
- https://github.com/purescript-web/purescript-web-xhr/pull/8/files
- https://github.com/purescript-web/purescript-web-file/pull/12
- https://github.com/purescript-web/purescript-web-promise/pull/5
- https://github.com/purescript-web/purescript-web-events/pull/15
- https://github.com/purescript-web/purescript-web-dom-xpath/pull/6
- https://github.com/purescript-web/purescript-web-dom-parser/pull/7
- https://github.com/purescript-web/purescript-web-clipboard/pull/2
- https://github.com/purescript-web/purescript-web-touchevents/pull/2
- https://github.com/purescript-web/purescript-web-socket/pull/5
- https://github.com/purescript-web/purescript-web-storage/pull/10

**Comment by JordanMartinez** [comment]
I've approved the above PRs or left comments explaining why CI isn't passing on all of them except for the Promises one.

**Comment by JordanMartinez** [comment]
I've submitted PRs to all web libs except for `purescript-canvas` because I'm still waiting for it's GH Actions migration PR to get merged.
I also switched these repos to Spago in the PRs because Bower was pulling in non-master dependencies and I didn't know why. Spago was the easiest way to get around that, but we might want to revisit that when making the next releases for these libraries.

**Comment by kl0tl** [comment]
There’s also web-encoding, web-streams and web-fetch. Those libraries are not in the package set either.

**Comment by thomashoneyman** [comment]
I’m going to work on those tonight, as they don’t even have README files in the first place.

**Comment by thomashoneyman** [comment]
> I also switched these repos to Spago in the PRs because Bower was pulling in non-master dependencies and I didn't know why. Spago was the easiest way to get around that.

I’m on board with switching the -web and -node libraries to Spago, but that should include changing the CI builds and moving away from pulp then (same as the -contrib libraries). If we’re not ready for that, then I’d be interested in sticking with bower until then and finding what’s pulling in non-master dependencies.

**Comment by kl0tl** [comment]
> I’m going to work on those tonight, as they don’t even have README files in the first place.

I took a stab at configuring a CI workflow for them already, based on the PR you made on web-promise 🙂

**Comment by thomashoneyman** [comment]
Great! That's these three as well then, all merged:

https://github.com/purescript-web/purescript-web-encoding/pull/1
https://github.com/purescript-web/purescript-web-streams/pull/1
https://github.com/purescript-web/purescript-web-fetch/pull/1

**Comment by JordanMartinez** [comment]
> I’m on board with switching the -web and -node libraries to Spago, but that should include changing the CI builds and moving away from pulp then (same as the -contrib libraries have done).

Haven't we migrated all core libs over to Spago anyway? Why not do so here, too? Unless there's something related to the registry, I don't see why we wouldn't.

Also, we could potentially revert this change when making releases of all the updated libraries.

**Comment by thomashoneyman** [comment]
No, the core libraries haven't migrated to Spago (just the installation instructions). So far, only the `-contrib` organization has migrated to Spago (and soon `-web` as well).

I'm in favor of migrating everything to Spago, but until the registry is up and running we can't forget about Bower + Pulp.

**Comment by JordanMartinez** [comment]
> No, the core libraries haven't migrated to Spago (just the installation instructions). So far, only the -contrib organization has migrated to Spago (and soon -web as well).

Ah... That was my misunderstanding. That makes more sense now.

The push to move to Spago with `-web` libs was due to the problems I experienced with Bower in the [`web-events` PR](https://github.com/purescript-web/purescript-web-events/pull/16).

**Comment by hdgarrood** [comment]
We really ought to fix those problems rather than dropping Bower support. Having a bower.json in the repo which doesn't work is not very helpful to Bower users.

**Comment by JordanMartinez** [comment]
Ok. What are your suggestions for fixing the Bower problem then? Its dependencies were updated and its transitive dependencies AFAICT were updated, too. I don't believe we're caching dependencies in CI. So, what could it be?

**Comment by thomashoneyman** [comment]
To clarify -- we need to maintain a Bower file in each of these repositories, at _least_ for the sake of publishing new library versions but also to support Bower users. But I'm in favor of making sure that Spago users are able to stick with that tool to contribute to library development, as it's certainly become the standard at this point. It also makes for a (slightly) simpler CI setup, as `setup-purescript` already provides the compiler, Spago, and psa by default.

**Comment by JordanMartinez** [comment]
See purescript-web/purescript-web-events#18 where I'm trying to figure out what's causing Bower to fail.

**Comment by hdgarrood** [comment]
I'll just explain my position a bit further as to why I am not keen on switching the web and node libraries over to Spago. It's for the same reason as core. There are three options here:
1. Provide bower.json but no spago.dhall.
2. Provide spago.dhall but no bower.json
3. Provide both.

As @thomashoneyman already pointed out, all downstream users can use the library in cases 1 and 3, but only spago users can use the library in case 2. So that rules out case 2 as an option, really; when we drop bower support I think it's very important that we clearly indicate an intention to do this well in advance to the community.

As I say, I also think it's important that we exercise the bower.json file in CI. If we don't, then it will inevitably stop working at some point. If there's a spago.dhall, we should exercise that too. So the simplest CI setup is option 1 (again as @thomashoneyman already pointed out). Option 3 doesn't quite deliver the ease of contributing benefits you might hope for for people who are more used to spago, because we will be exercising bower.json in CI anyway, so if the bower job starts failing then it will still need fixing. It's 

There's another reason to keep a functional bower.json file around, though, and that's for keeping track of version bounds. There's no way to keep track of version bounds with a spago configuration, but we'll need bounds data for the new registry. While it is possible to generate version bounds from a package set, I think we ought to maintain bounds by hand, because otherwise they'll be pessimistic. For instance, if we have a version bound of `>=2.0.0 <3.0.0` for some dependency, and then version 3.0.0 of that dependency comes out and the library doesn't need any changes to use the new version, then there's no reason to tighten the lower bound; ideally we should update the bounds to `>=2.0.0 <4.0.0`.

**Comment by JordanMartinez** [comment]
:angry: (I figured out what was causing this to fail)

Here's the issue. `purescript-nullable` is a contrib library, which no longer uses `master` for its default branch. Rather, it uses `main`. That's why it's pulling in non-`master`/`main` dependencies.

**Comment by hdgarrood** [comment]
Ah, good spot. Shall we switch the core libraries over to `main` so that this is less likely to cause confusion going forward?

**Comment by hdgarrood** [comment]
Actually I guess that's going to be a huge pain to do right now, since the bower.json files all have `master` in them. Maybe we should wait until after we've released proper versions of everything.

**Comment by thomashoneyman** [comment]
I'm on board with that. We moved forward with that with `-contrib` as I'm more comfortable making forward-looking changes over there and being quite conservative in core.

GitHub makes the transition quite easy (you choose a new default branch, update the base branch for open pull requests, and that's about it). But it _will_ be a pain to update all the Bower files.

This is something that the core team as a whole should have a chance to consider; I'm personally in favor, though.

**Comment by rhendric** [comment]
@hdgarrood re https://github.com/purescript/purescript/issues/3942#issuecomment-741414900

> As I say, I also think it's important that we exercise the bower.json file in CI. If we don't, then it will inevitably stop working at some point.

> I think we ought to maintain bounds by hand

This is a bit contradictory, isn't it? Unless CI tests the library with the upper *and* lower bounds (and maybe representative versions of everything in the middle?) of each dependency? Otherwise the same argument applies: at some point someone makes a change and the `>=2.0.0` bound is no longer correct, but it goes unnoticed because it's only ever tested on `3.x.y`.

I like the principle of not making guarantees that we aren't backing up with testing, if we can help it, and deciding whether that entails making narrower guarantees or doing more testing on the basis of the value-to-effort ratio of each case.

**Comment by JordanMartinez** [comment]
@thomashoneyman @kl0tl How should we proceed from here? I'm thinking I should close all the PRs I've currently submitted to `web` libs and just start over. Which repos do we need to migrate back to `bower`?

**Comment by thomashoneyman** [comment]
That would be all of the `purescript-web` organization except `web-events`.

**Comment by hdgarrood** [comment]
@rhendric That is a good point. I guess that is a good argument in favour of using pessimistic bounds for the time being (i.e. "version we tested with up to the next major bump"). I don't think there is any tooling which would enable us to easily test with the lower bounds of what's specified in bower.json in CI, and in the absence of that I think automatically generating bower.json files is probably okay, although any automatically generated bower.json files should still be checked in and tested in CI. Of course there's still the issue that we just want to get 0.14.0 out the door, so unless people already have some experience with this strategy it might be best to stick with hand-maintained bower.json files?

**Comment by JordanMartinez** [comment]
> That would be all of the `purescript-web` organization except `web-events`.

Sigh... On the upside, the `ci.yml` file should be the same across all of them, right? So, it's still easily scriptable, correct?

**Comment by thomashoneyman** [comment]
That's right. We pretty much just have to add PureScript 0.14.3 and make sure the Bower deps are on master (along with any other 0.14-related changes). I believe I've ensured everything is on the latest Pulp already.

**Comment by thomashoneyman** [comment]
All of the `-node` libraries are updated with GitHub Actions, though many of these pull requests are failing with linting errors now that they're on eslint and the standard configuration (if anyone can get to these before I can tomorrow noon PST, please feel free to push linting fixes directly to the branches):

- https://github.com/purescript-node/purescript-node-process/pull/22
- https://github.com/purescript-node/purescript-node-streams/pull/30
- https://github.com/purescript-node/purescript-node-http/pull/30
- https://github.com/purescript-node/purescript-node-net/pull/3
- https://github.com/purescript-node/purescript-node-buffer/pull/38
- https://github.com/purescript-node/purescript-node-fs-aff/pull/25
- https://github.com/purescript-node/purescript-node-readline/pull/19
- https://github.com/purescript-node/purescript-node-fs/pull/45
- https://github.com/purescript-node/purescript-node-child-process/pull/24
- https://github.com/purescript-node/purescript-node-url/pull/9
- https://github.com/purescript-node/purescript-node-path/pull/15
- https://github.com/purescript-node/purescript-posix-types/pull/7

**Comment by thomashoneyman** [comment]
@JordanMartinez once these merge, it's the same deal as the `-web` libraries: switch to compiler 0.14-rc3 in CI, switch Bower dependencies to master, take care of any other 0.14-rc3 code changes, and we're good to go.

**Comment by thomashoneyman** [comment]
Once the web and node libraries are updated for 0.14 I'd appreciate a quick group sync quickly on what really remains to be done across the organizations, as I'm starting to lose track. We could also discuss non-library changes (like Pursuit) that also have to be addressed, as well as libraries outside the organization we need to take care of if possible (like Halogen).

**Comment by JordanMartinez** [comment]
@thomashoneyman Most if not all of your above `node` PRs need to include `pull_request` in the CI part.

**Comment by thomashoneyman** [comment]
The node libraries are all updated to GitHub Actions now.

**Comment by JordanMartinez** [comment]
I believe all of the node libraries now have a PR.

**Comment by thomashoneyman** [comment]
At this point we only have:

- https://github.com/purescript-node/purescript-node-net/pull/4
- https://github.com/purescript-web/purescript-web-dom-xpath/pull/7 (blocked by `naturals`)
- https://github.com/LiamGoodacre/purescript-naturals/pull/7

and then everything is up-to-date for 0.14 as far as syntax / role annotations / coercible / etc. goes. That's not necessarily including any breaking changes we still want to make, which can be tracked by this search:

https://github.com/issues?q=is%3Aopen+archived%3Afalse+user%3Apurescript-contrib+user%3Apurescript-web+user%3Apurescript-node+label%3A%22fix+before+0.14%22+is%3Aissue+

**Comment by thomashoneyman** [comment]
Other than those, it looks like there are only blocking issues for us to resolve on these libraries:

- https://github.com/purescript/purescript-arrays
- https://github.com/purescript/purescript-transformers
- https://github.com/purescript/purescript-free

Getting _really_ close to the finish line!

**Comment by JordanMartinez** [comment]
In my [PR updating the `prepare-0.14` package sets to use v0.14.0-rc3](https://github.com/purescript/package-sets/pull/763), seem the following packages aren't in the package set:
```
[error] The following packages do not exist in your package set:
[error]   - precise
[error]   - web-dom-parser
[error]   - web-dom-xparser
[error]   - web-encoding
[error]   - web-fetch
[error]   - web-promise
[error]   - web-streams
```

**Comment by thomashoneyman** [comment]
I've un-checked `lists` due to https://github.com/purescript/purescript-lists/issues/178.

**Comment by kl0tl** [comment]
I’ve updated the list with all the issues and pull requests mentioning deprecations or breaking changes I could find.

**Comment by JordanMartinez** [comment]
Thanks @kl0tl! That helps to see how much more we have.

**Comment by JordanMartinez** [comment]
Here are PRs in core libraries that have been approved by at least one person: https://github.com/search?q=is%3Aopen+user%3Apurescript+is%3Apr+review%3Aapproved&type=Issues

**Comment by hdgarrood** [comment]
@kl0tl Agreed on not trying to address those ones for 0.14.0. I'll remove them from the list for now; we can restore them if anyone objects.

**Comment by hdgarrood** [comment]
I've removed all of those except for https://github.com/purescript/purescript-profunctor/issues/23 as I would quite like to get that one in, and I don't think it's too complicated as it's just rearranging things.

**Comment by hdgarrood** [comment]
I think we can leave https://github.com/purescript/purescript-arrays/issues/192 and https://github.com/purescript/purescript-arrays/issues/196 for later, so that we can mark `arrays` as done.

**Comment by hdgarrood** [comment]
Actually never mind, I think we need to deal with the sort stability issue now: https://github.com/purescript/purescript-arrays/issues/196

**Comment by JordanMartinez** [comment]
While working on `typelevel-equality`, I came across [this issue](https://github.com/purescript/purescript-type-equality/pull/14#issuecomment-757560122) involving functional dependencies not propagating. I can't recall which issue it is in this PR, but I know we have one open for it.

**Comment by JordanMartinez** [comment]
The `bifunctor`/`profunctor` change is the only last breaking change we have planned to make.

**Comment by JordanMartinez** [comment]
All core library have been updated to v0.14.0. Should this issue be closed?

**Comment by hdgarrood** [comment]
Fine by me! Really nice work, everyone 🎉
