### ISSUE TITLE
purs docs unexpected result for ProperName

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/purescript#3946]
## Description

This is happening when I try to generate docs for this file: https://github.com/xc-jp/purescript-protobuf/blob/showeq/src/Protobuf/Library.purs

<pre><font color="#4E9A06"><b>$</b></font> spago docs
<font color="#3465A4">[info] </font>Generating documentation for the project. This might take a while...
purs: An internal error occurred during compilation: Docs.Convert.ReExports: while collecting re-exports for module: Protobuf.Library, lookupTypeDeclaration: unexpected result for ProperName {runProperName = &quot;Bytes&quot;}: []
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-0.13.8-COscWkGZ6j0FifhWjtk8mz:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/Docs/Convert/ReExports.hs:513:17 in purescript-0.13.8-COscWkGZ6j0FifhWjtk8mz:Language.PureScript.Docs.Convert.ReExports
<font color="#CC0000">[error] </font>Docs generation failed.
</pre>

## To Reproduce

```
git clone https://github.com/xc-jp/purescript-protobuf.git
cd purscript-protobuf
git checkout showeq
nix shell
spago docs
```

## Additional context

Similar to #3384

## PureScript version

0.13.8

**Comment by jamesdbrock** [comment]
It seems that deleting `output` and re-running `spago docs` fixed it.

**Comment by hdgarrood** [comment]
If deleting output fixes the issue, it’s still a bug that it happened in the first place. I think this might just be another manifestation of #3911 though, so I think I’ll treat it as a duplicate of that for now.
