### ISSUE TITLE
PartiallyAppliedSynonym error without source span

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#3949]
## Description

Managed to track down a case of `PartiallyAppliedSynonym` occurring which is reported without source span (possibly related to the non-reproducible case remaining when #3208 was closed out.

## To Reproduce

The following module 
```purescript
module TypeSynLocation where

import Data.Newtype (class Newtype)

type Foo f = f Int
newtype NewT = NewT Foo
derive instance newtypeProcessor :: Newtype NewT _
```
gives an error not containing source span:
```
Error found:

  Type synonym TypeSynLocation.Foo is partially applied.
  Type synonyms must be applied to all of their type arguments.
```
Removing the derived `Newtype` instance, the error is reported at the usage of `Foo` as would be expected.

## Expected behavior

Source span should be reported when Newtype instance is not derived.

## PureScript version

0.13.8

**Comment by kl0tl** [comment]
This happens because the errors emitted while replacing type synonyms when deriving instances aren‘t rethrown with their declaration source span. The issue can also be observed for any derivable class and with the newtype deriving strategy.
