### ISSUE TITLE
Parse error when using minus sign in a pattern match

### ISSUE THREAD

**Issue by d86leader** [purescript/purescript#3953]
## Description

In this snippet I try to create an operator alias for a constructor:
```purescript
module Main where

data Tuple a b = Tuple a b

infixl 6 Tuple as -

test =
    let tuple = "" - ""
        left - right = tuple
    in left
```
When I compile it with `purs compile src1/Main.purs`, it compiles without errors.
But when I try to run it with `spago repl`, it fails with:
```
at src1/Main.purs:9:16 - 9:21 (line 9, column 16 - line 9, column 21)

  Unable to parse module:
  Unexpected token 'right'
```
Using other symbols like `+` or `*` compiles and runs as expected, it seems only `-` is affected.

## To Reproduce

Create a file with code above and run it with `spago repl`

## Expected behavior

Module compiles and repl starts

## PureScript version

0.13.8

**Comment by rhendric** [comment]
Can confirm this is an issue in 0.14.0-rc3 as well.

**Comment by rhendric** [comment]
What I can't confirm is the part where this works without the REPL, in 0.13.8 or on master. Are you sure that you can compile this file exactly as written without errors?

**Comment by d86leader** [comment]
You're right, must've been my mistake when checking. It doesn't compile either and with the same mistake. I'm going to edit the title of the issue now.

**Comment by hdgarrood** [comment]
I've labelled this as "breaking" because fixing it means removing the ability to match on negated number literals in pattern matches (see the discussion in #3954).
