### ISSUE TITLE
TCO does not trigger in `case` expressions with assign guards

### ISSUE THREAD

**Issue by radrow** [purescript/purescript#3957]
## Description

The compiler misses an opportunity for tail-call optimization when the self call happens inside a `case` clause guarded with assign (`<-`) expression. 

## To Reproduce

Compile module
```
module Test where

fixPokemonHp :: Int -> Int
fixPokemonHp x = case x of
  n | _ <- n -> fixPokemonHp x
  _ -> fixPokemonHp x
```

## Expected behavior

Produce some tail recursive code

## Actual behavior

```
// Generated by purs version 0.13.8
"use strict";
var fixPokemonHp = function (x) {
    var v = function (v1) {
        return fixPokemonHp(x);
    };
    return fixPokemonHp(x);
};
module.exports = {
    fixPokemonHp: fixPokemonHp
};
```

## Additional context

btw I am using Arch Linux

## PureScript version

0.13.8

**Comment by radrow** [comment]
Same thing for
```
f :: Int -> Int
f x = case x of
  n | n == n && true -> f x
  _ -> f x
```
(works)
```
f :: Int -> Int
f x = case x of
  n | n == n, true -> f x
  _ -> f x
```
(does not)

**Comment by gorbak25** [comment]
Context:
Together with @radrow we are working on an Erlang to Purescript transpiler - we rely on tail recursion heavily.
https://github.com/gorbak25/erlscripten
