### ISSUE TITLE
Core library updates to GitHub Actions

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/purescript#3962]
This issue tracks the pull requests open to migrate libraries in the core organization to use GitHub Actions as their CI provider, and to update their installation instructions to use Spago.

**Comment by thomashoneyman** [comment]
@hdgarrood, @kl0tl, @JordanMartinez -- all of these pull requests can be reviewed now. Almost all of them build just fine. A couple (`maybe`, `catenable-lists`, `lists`, `transformers`) had to be updated to accommodate the `MonadZero` warning and I've opened relevant issues if so.

**Comment by hdgarrood** [comment]
Could we close this now?

**Comment by JordanMartinez** [comment]
I believe so. We'll come across any when we make releases that don't have any.
