### ISSUE TITLE
Include kind information in HTML docs

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3973]
## Summary

#3779 implemented polykinds and explicit kind annotations, but right now not all kind information is represented in HTML documentation.

## Motivation

HTML docs should ideally contain all type information which is observable from downstream code, which includes kinds. For example, the following two data types are not distinguishable in HTML documentation in `0.14.0-rc4`, except by their names:

```purescript
data MonoProxy :: Type -> Type
data MonoProxy a = MonoProxy

data PolyProxy :: forall k. k -> Type
data PolyProxy a = PolyProxy
```

## Proposal

The specifics of how we represent this information are still up for debate, but I think ideally the HTML docs shouldn't look too different from what's in the source files, so we could copy the kind annotations from the source files into the HTML docs where they exist.

**Comment by JordanMartinez** [comment]
The additional information needed in the docs will break the `docs.json` format. Does that make this a breaking change?

Also, this change will affect `Prim` modules' docs creation. Right now, those docs are generated by creating a `TypeClassDictionary` and then creating a corresponding `Doc.Declaration` value for them (or something like that).

**Comment by hdgarrood** [comment]
I think we should aim to make this a non-breaking change to the `docs.json` format. That is, `docs.json` files produced by older compilers should be understandable by the newest one, but `docs.json` files produced by the newest compiler need not be understandable by older compilers.
