### ISSUE TITLE
Core Library - Adding changelogs and PR templates

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3984]
This issue tracks PRs, so that we can more easily know which ones have yet to be merged. It'll follow the same format used in purescript/purescript-prelude#252

**Comment by rhendric** [comment]
For the ‘unreleased’ sections, is it worth adding another step to submitting PRs and another place for merge conflicts to arise (if there is any concurrent development, this pretty much guarantees merge conflicts), versus using one of the many tools for automatically generating the new changelog fragment from Git commit messages?

**Comment by thomashoneyman** [comment]
@f-f have you experienced challenges with this in Spago?

**Comment by f-f** [comment]
In my experience conflicts arising from the Changelog are very rare, and in any case very easy to solve (even from GitHub's own interface).
I think the Changelog should not be generated from GitHub commits but should be typed by a human, tailored to the audience that's supposed to read it - e.g. in Spago we use the changelog content for populating the Release notes and for the Discourse posts, so it's tailored more for users rather than contributors.

**Comment by JordanMartinez** [comment]
I'm going to run the script. Each lib will get hit with the updates. Sorry for spamming your notifcations.

**Comment by JordanMartinez** [comment]
Sigh... something else came up. I'll work on this tomorrow.

**Comment by JordanMartinez** [comment]
PRs for the following packages did not generate the CHANGELOG.md file due to the following error.:
```
throw util.fromLeft(step);
                  ^

Error: An error occurred while decoding a JSON value:
  Expected value of type 'Array'.
```

List of repos (in order of appearance):
exists
gen
foreign
catenable-lists
lcg
minibench
integers
numbers
unfoldable
const
contravariant
st
refs
random
tailrec
distributive
exceptions
invariant
safe-coerce
functions
assert
console
unsafe-coerce
parallel

**Comment by JordanMartinez** [comment]
Yup, got rate limited. That's easy to fix, but I'll do it later.

**Comment by JordanMartinez** [comment]
Ok, all PRs should have their changelog included in the PR now.

**Comment by JordanMartinez** [comment]
Only 3 PRs are waiting for approval:
- https://github.com/purescript/purescript-lcg/pull/11
- https://github.com/purescript/purescript-psci-support/pull/22
- https://github.com/purescript/purescript-minibench/pull/18

**Comment by JordanMartinez** [comment]
All PRs have been merged. Moreover, all repos were updated to `v0.14.0-rc5`. Closing this issue.
