### ISSUE TITLE
Proposal: Add a CHANGELOG to this repository

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/purescript#3987]
## Summary

I propose that we add and track a changelog file to the compiler repository as is done by [Spago](https://github.com/purescript/spago/blob/master/CHANGELOG.md) and [the core libraries](https://github.com/purescript/purescript/issues/3984).

## Motivation

The [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) website provides several reasons why keeping a changelog is a good idea in a project like this one. More specifically, I think keeping a changelog will help:

- Ensure that contributors and users can see notable changes from version to version in one place, without being tied to a particular platform (this is currently done via GitHub releases)
- Reduce the time required to write release notes for each compiler version by keeping track of unreleased changes. Writing the release notes then comes down to editing the existing changelog rather than to begin anew.

## Proposal

I propose that we:

1. Adopt the changelog template used by Spago
1. Use @JordanMartinez's script to create a changelog from existing GitHub releases, as was used to [implement this change for the core libraries](https://github.com/purescript/purescript/issues/3984)
1. Update the pull request template to add a checklist item to ensure that changes are included in the changelog as they merge (vs. being collated at release time)

## Examples

See:
  - [Spago](https://github.com/purescript/spago/blob/master/CHANGELOG.md)
  - [Prelude](https://github.com/purescript/purescript-prelude/blob/master/CHANGELOG.md)

**Comment by JordanMartinez** [comment]
Closed by #3989
