### ISSUE TITLE
Variable names starting with Chinese characters should be valid

### ISSUE THREAD

**Issue by sgalal** [purescript/purescript#3992]
## Description

Variable names that starts with Chinese characters, like `數`, `音韻地位` and `反切`, should be valid.

## To Reproduce

```purescript
module Main where

import Prelude

import Effect (Effect)
import Effect.Console (logShow)

數 :: Int
數 = 1

main :: Effect Unit
main = logShow 數
```

## Expected behavior

The program should compile and output `1`.

## Actual behavior

```
Error found:
at src/Main.purs:8:1 - 8:2 (line 8, column 1 - line 8, column 2)

  Unable to parse module:
  Unexpected 數


See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.
```

## PureScript version

0.13.8

## More imformation

This is valid in Haskell,

```haskell
Prelude> 數 = 1
Prelude> show 數
"1"
```

Related: https://github.com/purescript/purescript/issues/3804

**Comment by rhendric** [comment]
The character ‘數’ is in the ‘Letters, Other’ Unicode category. This might actually be a bug in GHC; at least, my reading of the Haskell 2010 report is that identifiers have to start with characters in the ‘Letters, Lowercase’ category. I'm not sure exactly what GHC is doing here—perhaps it treats ‘Letters, Other’ as lowercase, or perhaps it's treating them as ambiguous somehow?

For whatever reason though, what GHC does and what the Haskell spec says seem to disagree, and it's not clear to me which PureScript should treat as precedent.

**Comment by hdgarrood** [comment]
While Haskell is obviously a strong inspiration, PureScript doesn’t just follow it blindly; the fact that GHC behaves a certain way shouldn’t be enough to justify having the PureScript compiler behave the same way on its own, any change should be justifiable on its own merits. In this case the merit does seem fairly clear though.

The syntax does care about uppercase vs lowercase for a reason though, and that’s that we need to be able to distinguish data constructors from regular values at the term level, and we need to be able to distinguish concrete type names from type variables at the type level. I think that we could decide that every “Letter, Other” counts as lowercase for the purpose of syntax, although that might be a bit limiting as you’d be able to use Chinese characters only as value names and type variable names, but not as type names or data constructor names. I don’t see any way of allowing Chinese characters for both value/type variable names and for type/data constructor names.

**Comment by rhendric** [comment]
@sgalal, do you have experience writing Haskell using Chinese characters? Does the requirement to start type and constructor names with a non-Chinese character cause any problems?

I ask because I could imagine having Chinese count as uppercase characters instead might be better: things that must be lowercase could be prefixed with `_`, whereas there isn't a neutral equivalent for forcing things to be uppercase. You could just pick an arbitrary letter, of course, or do some sort of Hungarian notation thing where types are T[Chinese] and constructors are C[Chinese], but I honestly don't know much about the experience of using programming languages for non-English speakers.

**Comment by toastal** [comment]
Just tested some. It seems the Latin, Armenian, Greek, and Cyrillic scripts work just fine and I think all other scripts fail (including emoji). This isn't an English-based, or any particular language issue, but one of scripts and which ones are bicameral (have upper and lower cases).

I would assume the only way to do this is to allow a (n overrideable? and omittable?) sigil to denote the differences in types (i.e. Shell's `$VAR` or see [Perl](https://www.perl.com/article/on-sigils/)). This would massively change the ergonomics of the language and would make reading code in these other languages difficult.

**Comment by sgalal** [comment]
Thank you all for the replies. I am actually creating a binding for a JavaScript library that uses Chinese characters. I decide to translate the names into English now, so this would not be a problem for me any more.

**Comment by rhendric** [comment]
In that case, I think this is closable without prejudice. PureScript's current behavior is unambiguous and conservative, in that we won't break anything if we decide to include Chinese characters in the set of characters that can start identifiers in the future. If you, future reader, have a case to make for why we should do that, I invite you to do so.
