### ISSUE TITLE
Logo is not clearly legible in GitHub's dark mode

### ISSUE THREAD

**Issue by ptrfrncsmrph** [purescript/purescript#4001]
## Description

The logo in the repo's main README is not very legible in GitHub's dark mode.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/26548438/106219146-cb682e80-61a6-11eb-9597-d1b3597e6c10.png">

## To Reproduce

1. Follow [these instructions](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-theme-settings) to set your GitHub theme to **Dark**.
2. Navigate to https://github.com/purescript/purescript, scroll to [README section](https://github.com/purescript/purescript#readme).

## Expected behavior

Logo should be legible.

## PureScript version

0.x.x

**Comment by hdgarrood** [comment]
Maybe we could give everything a thin white outline?

**Comment by ptrfrncsmrph** [comment]
Something like one of these? (The stroke is on the outside of the path, so not perceptible against white background.)
<img width="1033" alt="Screen Shot 2021-01-30 at 10 59 54 AM" src="https://user-images.githubusercontent.com/26548438/106361316-476b8f00-62eb-11eb-8c17-52be5acab404.png">
<img width="1033" alt="Screen Shot 2021-01-30 at 11 00 16 AM" src="https://user-images.githubusercontent.com/26548438/106361317-48042580-62eb-11eb-84e1-1f364236adcf.png">
<img width="1033" alt="Screen Shot 2021-01-30 at 11 00 44 AM" src="https://user-images.githubusercontent.com/26548438/106361318-489cbc00-62eb-11eb-8bd6-5ea9f7a622f9.png">

**Comment by hdgarrood** [comment]
Any of those looks good to me, yeah 👍
