### ISSUE TITLE
REPL outputs illegal escape sequence \& in string literals

### ISSUE THREAD

**Issue by stengerh** [purescript/purescript#4008]
## Description

The REPL outputs string literals containing the escape sequence `\&` but this escape sequence is not accepted as input.

## To Reproduce

In the REPL:

```
> "\x0000001"
"\0\&1"

> "\0\&1"
Illegal character escape code at line 1, column 3
```

## Expected behavior

The REPL outputs valid string literals.

## Additional context

Haskell supports `\&` to delimit a numeric escape sequence from the following characters, see [The zero-width escape sequence](http://book.realworldhaskell.org/read/characters-strings-and-escaping-rules.html#id690781). This is exactly the way in which the PureScript REPL uses `\&` to produce canonicalized string literals. However the compiler does not actually accept this escape sequence. If it did this would provide a solution to the problem in #3750.

## PureScript version

0.13.8

**Comment by stengerh** [comment]
I discovered this while experimenting with the PureScript plugin for IntelliJ and comparing its syntax highlighting with the behavior of the PureScript compiler/REPL. Unfortunately I could not find any documentation on the escape sequences which PureScript supports. At least not in the sections on [Syntax](https://github.com/purescript/documentation/blob/master/language/Syntax.md) and [Differences from Haskell](https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md). The only source of truth here is the source code of the PureScript compiler itself.

This lack of documentation seems to have caused some confusion in PureScript itself and even more so in the IntelliJ plugin. I can prepare a pull request for the documentation, so other can benefit from what I learned.

**Comment by MonoidMusician** [comment]
I can confirm this still affects 0.14. Interestingly, it doesn't affect type-level symbols (at least in 0.14):
```purescript
> "\x0000001"
"\0\&1"

> "\x000001"
"\1"

> data SProxy (s :: Symbol) = SProxy
> :t SProxy :: SProxy "\x0000001"
SProxy "\x0000001"

> :t SProxy :: SProxy "\x000001"
SProxy "\x000001"

> :t SProxy :: SProxy "\x00001"
SProxy "\x000001"
```

I'm not familiar enough with the pretty printer to diagnose/fix this.

**Comment by MonoidMusician** [comment]
Wait. I just realized that this is an issue with the `Show String` instance in the prelude, not the compiler. See https://github.com/purescript/purescript-prelude/blob/898f35ae53ccbf2f9d2dd609754513e0b6ddb776/src/Data/Show.js#L29-L51

We should probably update it to match the compiler's output though though.
