### ISSUE TITLE
Proposal: Remove ad-hoc handling of `case` formatting in the parser

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#4012]
## Summary

The parser has a couple of ad-hoc cases in the parser that should not be necessary.

https://github.com/purescript/purescript/blob/e56d28b211864075c7232e56350539806efbb01f/lib/purescript-cst/src/Language/PureScript/CST/Parser.y#L404-L411

## Motivation

I originally added these cases to keep some core modules compiling that use extremely odd formatting for single-branch cases. Normally these would run afoul the offside rule, but the old parser accepted them due to various idiosyncrasies. 

https://github.com/purescript/purescript-transformers/blob/42175954755a0fa0fe688579309032a948d919fb/src/Control/Monad/Writer/Trans.purs#L82-L86

## Proposal

We should remove these cases in 0.15 and update the core libraries. We can warn in a followup 0.14 release.

**Comment by JordanMartinez** [comment]
Adding a warning seems to be an easy task. We should likely add a warning here and release it in the next v0.14.x release. Otherwise, we might forget about it and then not be able to do a breaking change for it in `v0.15.x`.
