### ISSUE TITLE
Kind signatures not taken into account when declaring instances

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#4018]
## Description

I'm pretty sure this is wrong, but maybe I am here. It seems that if you define a class with a particular kind signature, and then try to provide an instance for a type that has a more flexible kind, it accepts it, and allows the instance to be used even when instantiated with a type with an incorrect kind.

## To Reproduce

``` purescript
newtype Indexed ∷ forall k1 k2 k3. (k1 → Type) → k2 → k3 → k1 → Type
newtype Indexed m x y a = Indexed (m a)

class IxFunctor ∷ ∀ ix. (ix → ix → Type → Type) → Constraint
class IxFunctor f where
  imap ∷ ∀ a b x y. (a → b) → f x y a → f x y b

instance ixFunctorIndexed ∷ Functor m ⇒ IxFunctor (Indexed m) where
  imap f (Indexed ma) = Indexed (map f ma)

foreign import kind D1
foreign import kind D2

foo :: Indexed Array D1 D2 Int
foo = Indexed [1]

bar :: Indexed Array D1 D2 Int
bar = imap identity foo
```

## Expected behavior

I'm pretty sure this should be rejected somewhere - either the instance should be disallowed, or the instance shouldn't be found when attempting to `imap` here, as `D1` and `D2` aren't the same kind - that's fine according to `Indexed`'s signature, but not `IxFunctor`'s.

**Comment by natefaubion** [comment]
D1 and D2 both have kind `Type`, right?. `foreign import kind` isn't a thing anymore, it's desugared to empty `data`, which declares a type with kind `Type`. 😖

**Comment by garyb** [comment]
Oh, maybe you're right. I did think about that when I was declaring it, as I though we'd actually removed `foreign import kind` so was surprised to see it work. I'll try again.

**Comment by natefaubion** [comment]
`foreign import kind` is deprecated and warns.

**Comment by garyb** [comment]
It doesn't seem to warn for me? But okay yeah, revised version complains:

``` purescript
import Prelude

newtype Indexed ∷ forall k1 k2 k3. (k1 → Type) → k2 → k3 → k1 → Type
newtype Indexed m x y a = Indexed (m a)

class IxFunctor ∷ ∀ ix. (ix → ix → Type → Type) → Constraint
class IxFunctor f where
  imap ∷ ∀ a b x y. (a → b) → f x y a → f x y b

instance ixFunctorIndexed ∷ Functor m ⇒ IxFunctor (Indexed m) where
  imap f (Indexed ma) = Indexed (map f ma)

foreign import data K1 :: Type
foreign import data K2 :: Type

foreign import data D1 :: K1
foreign import data D2 :: K2

foo :: Indexed Array D1 D2 Int
foo = Indexed [1]

bar :: Indexed Array D1 D2 Int
bar = imap identity foo
```
```
[1/1 KindsDoNotUnify] src\Test:21:8

  21  foo :: Indexed Array D1 D2 Int
             ^^^^^^^^^^^^^

  Could not match kind

    K1

  with kind

    K2

  while trying to match type Indexed @Type @K1 @K2 Array
    with type t0
  while checking that expression foo
    has type t0 t1 t2 t3
  in value declaration bar

  where t0 is an unknown type
        t3 is an unknown type
        t1 is an unknown type
        t2 is an unknown type
```

As you can see from what PSA is doing here though, it has completely the wrong error span. I'll open a new issue for that.

**Comment by natefaubion** [comment]
> It doesn't seem to warn for me?

Do you have it filtered in some way? 

https://github.com/purescript/purescript/blob/20f529424c2bbf9bf786e8e23c51592f328350af/tests/purs/warning/DeprecatedForeignImportKind.out
