### ISSUE TITLE
Error span showing in the wrong place for kind mismatch when calling an instance member

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#4019]
## Description

The error span is wildly out - I don't really have a theory for what exactly it is doing as it manifests in interesting ways. The example should illustrate further:

## To Reproduce

``` purescript
import Prelude

newtype Indexed ∷ forall k1 k2 k3. (k1 → Type) → k2 → k3 → k1 → Type
newtype Indexed m x y a = Indexed (m a)

class IxFunctor ∷ ∀ ix. (ix → ix → Type → Type) → Constraint
class IxFunctor f where
  imap ∷ ∀ a b x y. (a → b) → f x y a → f x y b

instance ixFunctorIndexed ∷ Functor m ⇒ IxFunctor (Indexed m) where
  imap f (Indexed ma) = Indexed (map f ma)

foreign import data K1 :: Type
foreign import data K2 :: Type

foreign import data D1 :: K1
foreign import data D2 :: K2

foo :: Indexed Array D1 D2 Int
foo = Indexed [1]

bar :: Indexed Array D1 D2 Int
bar = imap identity foo
```
```
  Could not match kind

    K1

  with kind

    K2

  while trying to match type Indexed @Type @K1 @K2 Array
    with type t0
  while checking that expression foo
    has type t0 t1 t2 t3
  in value declaration bar

  where t0 is an unknown type
        t3 is an unknown type
        t1 is an unknown type
        t2 is an unknown type
```

In this instance, the `foo` type declaration is being marked as the problem, but `bar` is the issue (illustrated by the fact that commenting out `bar` resolves the issue also). If you move `bar` into a different file the error span will still point at `foo` in this file, which is pretty neat. 

If you try type-annotating the value:

``` purescript
bar :: Indexed Array D1 D2 Int
bar = imap identity (Indexed [1] :: Indexed Array D1 D2 Int)
```
The span will be here:
```
  25  bar = imap identity (Indexed [1] :: Indexed Array D1 D2 Int)
                                          ^^^^^^^^^^^^^
```

## Expected behavior

I would expect the usage of the value `foo` to be the span for the error for the first case, and I guess the whole annotated expression for the second case.

**Comment by natefaubion** [comment]
I suspect it's because the `foo` reference looks up the original type with the original source spans, and they don't get re-annotated with the usage source span.

The second one is likely because unification error spans use a terrible heuristic that biases the span farther along in the file.
