### ISSUE TITLE
Sourcemap generated with negative lines/columns

### ISSUE THREAD

**Issue by RedGlow** [purescript/purescript#4034]
## Description

I think there is some problem with sourcemaps generation, in that it produces lines/columns with negative indexes. I'm not 100% sure because I'm not an expert in the sourcemaps format, but I've got errors from webpack+purs-loader and using the source-map npm package, which makes me believe they are indeed incorrect.

## To Reproduce

I'll give the steps I've used under Windows 10, but there shouldn't be any difference in other environments

- install purescript and spago globally
- create a new directory
- run "spago init"
- run "spago build"
- run "npm init -y"
- install source-map package: "npm install source-map --save"
- save a script in the project root with this content:
```javascript
const s = require("source-map");
const fs = require("fs");
const path = require("path");
const content = fs.readFileSync(path.join(__dirname, "output", "Effect.Console", "index.js.map"), {encoding: "utf-8"});
s.SourceMapConsumer.with(
  JSON.parse(content),
  null,
  (consumer) => {
    console.log("sources:");
    console.log(consumer.sources);

    console.log("mappings:");
    consumer.eachMapping(function (m) {
      console.log(JSON.stringify(m));
    });
  }
)
  .then(() => console.log("all done"))
  .catch(console.error);
```
- run the script

## Expected behavior

It should print a list of mappings between Effect.Console's purescript sources and generated javascript sources. Instead, it fails with an error:

```
sources:
[ '..\\..\\.spago\\console\\v5.0.0\\src\\Effect\\Console.purs' ]
mappings:
Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
    at BasicSourceMapConsumer._parseMappings (E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:360:13)
    at BasicSourceMapConsumer._getMappingsPtr (E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:315:12)
    at E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:387:57
    at Object.withMappingCallback (E:\Documents\projects\smbug\node_modules\source-map\lib\wasm.js:95:11)
    at BasicSourceMapConsumer.eachMapping (E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:371:16)
    at E:\Documents\projects\smbug\test.js:13:14
    at E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:78:16
```

## Additional context

Spago version: 0.19.1
source-map package version: 0.7.3
psc: psc-0.14.0-20210318

## PureScript version

0.14.0

**Comment by nwolverson** [comment]
If there's an issue in generated source maps, it should be apparent either in the source maps in `output/`, or the result of `purs bundle`; unfortunately source map generation is a chain of flaky tools, or it was the last time I saw it, the chaining of maps in multiple build steps was problematic

**Comment by jterbraak** [comment]
In this case purs emits faulty maps. For example for Data.Lens.Internal.Re purs 0.13.8 emits this mapping:
`;;AACA;AAAA;AAAA;AAAA;AAAA;AAAA;AAWA,SAAA;WAAA;;AAIA,mBAAA;0CAAA;eAAA;mBAAA;gBACqB,gCAlBtB,gBAkBG,GAAA`

Which translates to 

```
([1,0](#0)=>[2,0])
([1,0](#0)=>[3,0])
([1,0](#0)=>[4,0])
([1,0](#0)=>[5,0])
([1,0](#0)=>[6,0])
([1,0](#0)=>[7,0])
([12,0](#0)=>[8,0]) | ([12,0](#0)=>[8,9])
([12,0](#0)=>[9,11])
([16,0](#0)=>[11,0]) | ([16,0](#0)=>[11,19])
([16,0](#0)=>[12,42])
([16,0](#0)=>[13,15])
([16,0](#0)=>[14,19])
([17,21](#0)=>[15,16]) | ([-1,-1](#0)=>[15,48]) | ([17,2](#0)=>[15,64]) | ([17,2](#0)=>[15,67])
```

So in line 17 it emits a negative column and line. Maybe some invalid source span gets passed to the source map generator.

**Comment by i-am-the-slime** [comment]
@kevinbarabash Had improved the correctness of sourcemaps and was only missing tests by the end. I meant to try to finish his work up but never got around to it and now I don't even know where to find the changes anymore.

**Comment by klarkc** [comment]
It happened with me when trying to debug the source code with my IDE: `spago build --purs-args "-g sourcemaps --json-errors"`
