### ISSUE TITLE
Docs on types with kind signatures aren't included in html docs

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4036]
## Description

It seems that documentation on types with kind signatures aren't rendered.

## To Reproduce

1. Create a file with the following code:
```purescript
module Main where

-- | Foo is a type with a kind signature whose documentation doesn't show up.
newtype Foo :: forall kind. kind -> Type -> Type
newtype Foo k a = Foo a
```

2. Run `purs docs "src/**/*.purs" to generate HTML docs locally
3. Open the `Main` module's docs

The docs on `Foo` aren't shown.

## Expected behavior

The docs of `Foo` should appear in the HTML file.

## PureScript version

v0.14.0

**Comment by JordanMartinez** [comment]
Figured out what is causing this bug. It can be fixed by moving the doc comments underneath the kind signature. For example:
```purescript
newtype Foo :: forall kind. kind -> Type -> Type
-- | Foo is a type with a kind signature whose documentation doesn't show up.
newtype Foo k a = Foo a
```
The kind signature i.e. `newtype Foo :: forall kind. kind -> Type -> Type`) is stored as a [`DeclKindSignature` in the CST](https://github.com/purescript/purescript/blob/master/lib/purescript-cst/src/Language/PureScript/CST/Parser.y#L671-L673). It is later converted into AST as a [`KindDeclaration`](https://github.com/purescript/purescript/blob/master/lib/purescript-cst/src/Language/PureScript/CST/Convert.hs#L494-L502). The `KindDeclaration` is [currently not rendered in outputted docs](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Docs/Convert/Single.hs#L115-L162) as seen by the lack of a case that renders it to HTML, so the comments that would be stored with it aren't rendered either.

The fix would be to reassociate the kind signature with its corresponding `DataDeclaration` and then render both the kind signature and the comments above them in the same part on the page.

**Comment by JordanMartinez** [comment]
Looks like the order in the list of declarations guarantees that a kind signature can be reassociated with it's corresponding `DataDeclaration`, `TypeSynonymDeclaration`, and `TypeClassDeclaration`. The compiler [finds a kind signature first and ensures its' name matches the following declaration's name or throws an error](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/TypeDeclarations.hs#L61-L63). Then it [guarantees that the kind signature isn't orphaned](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/TypeDeclarations.hs#L71-L72).

We could follow this same approach to reassociate the kind signatures together with their declarations by doing a pass over a modules declarations before we render them as HTML

**Comment by JordanMartinez** [comment]
This seems to be (somewhat of) a duplicate of #3973

**Comment by hdgarrood** [comment]
Yeah, I think we can consider this a duplicate.
