### ISSUE TITLE
Kind annotated class causes "Unknown super class in TypeClassDeclaration" crash when used in a superclass implication

### ISSUE THREAD

**Issue by jy14898** [purescript/purescript#4038]
## Description

Kind annotated class causes "Unknown super class in TypeClassDeclaration" crash when used in a superclass implication. When the kind annotation is removed, it works

Crash report:
```
Compiling Main
purs: An internal error occurred during compilation: Unknown super class in TypeClassDeclaration
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-ast-0.1.0.0-Gtmwmu4N43KCxo7Qi9BiwQ:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker.hs:176:20 in purescript-0.14.0-FNUkHeAp48Q5tFoT4dYs4J:Language.PureScript.TypeChecker
purs: thread blocked indefinitely in an MVar operation
```

## To Reproduce

Compile the code with purs v0.14.0
```haskell
module Main where

class A :: Constraint -- remove this line and it works
class A

class B :: Constraint
class A <= B
```

## Expected behavior

Successful Compilation

## PureScript version

0.14.0

**Comment by natefaubion** [comment]
Probably something to do with the sorting in Sugar/DataBindingGroups.hs. By default we will only incur a dependency on a kind signature if it's available, but it sounds like the routine for checking superclasses currently expects a dependency on the class itself.
