### ISSUE TITLE
Migrate CI to GH Actions

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4043]
I started doing this previously in #3980 before we released `v0.14.0`, but we decided it would be better to do this after the release is out. Now that some PRs have been created to fix a few bugs (e.g. #4042, #4041, #4040), I'm remembering that we're still on Travis CI and that eventually our minutes will run out.

**Comment by JordanMartinez** [comment]
I believe Travis CI said they would give people 10,000 minutes for free before they'd be out. Then one would be forced to migrate to a different CI, pay for Travis, or see if they are willing to continue supporting an open source project for free. Does anyone know how many more minutes we have on Travis CI before we run out? 

I have no idea if the following calculation is correct. I'm just trying to get an estimate. The final commit for [#4052](https://travis-ci.org/github/purescript/purescript/builds/766697042) used ~37 minutes if you round up each build's total minutes and sum them. 10,000 minutes / 37 minutes per commit that triggers CI = ~270 commits that trigger CI.

I don't think this issue is a high priority yet as we still likely have time, but I'd rather it not be a sudden bottleneck that kills momentum.

**Comment by hdgarrood** [comment]
I am not aware of any way of checking, but I think we could probably burn through 10,000 minutes surprisingly quickly. It’s not unusual for one PR to trigger 10 CI builds over its lifetime, which would be ~400 mins on its own.
