### ISSUE TITLE
Remove tasty, use only hspec

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#4056]
## Summary

Remove use of tasty and tasty-hspec in the test suite and use only hspec directly.

## Motivation

Tasty and hspec are both testing frameworks: they are meant to satisfy the same need, and they're not really intended to be used together.  See e.g. this comment from the tasty-hspec Haddocks:

> hspec and tasty serve similar purposes; consider using one or the other.
>
> However, in a pinch, this module allows you to run an hspec Spec as a tasty TestTree.

I'd like to switch back to using hspec throughout for two reasons:

1. With hspec, failures are summarised at the end of the test output.  Tasty reports failures inline, which can be very annoying, especially in CI, as you then have to search through the logs to find the failure. Displaying failures at the end seems like a much more sensible default to me.

2. We get to take advantage of HasCallStack in hspec-expectations to help narrow down where a failure is coming from. This is particularly helpful in tests like the ones in TestMake.hs where we run something like ``someAction `shouldReturn` someResult`` more than once in a particular test, as without the source location from HasCallStack it's not immediately clear which assertion is failing. (This would have been useful in #4053).

## Proposal

Drop the `tasty`, `tasty-hspec`, and `tasty-golden` dependencies and use hspec throughout our test suite. There's a `hspec-golden` but I don't really like the look of it and I'd prefer we roll our own golden testing (you only need like 6 or 7 lines of code for what we want).

I'd also like to merge the cst tests back into the main `purescript` package. Having all of the tests in one place seems simpler, and I don't think we gain a lot from having the cst tests separated. This can happen separately, though.

One of the main motivations for introducing tasty originally (see #2848) was that it would let us run individual tests via CLI options. This is still possible if we switch back to hspec: hspec has a `--match` CLI option for this.

In hspec, there's no `--accept` flag for regenerating golden tests, but we can preserve similar behaviour by having our test suite recognise an environment variable (say, `HSPEC_ACCEPT`) or simply by letting the user delete the files they want to regenerate.

**Comment by rhendric** [comment]
> we roll our own golden testing (you only need like 6 or 7 lines of code for what we want)

If we do that, let's remember to have one of those lines of code check for the equivalent of `TASTY_NO_CREATE`, as seen in #3808.

**Comment by rhendric** [comment]
I've tried playing around with this, and while it's especially nice not to have to scroll back through the console to find specific errors, there are some things I miss about Tasty. Namely:
1. Tasty reports when a test begins, not just when it ends. When the build appears to hang after printing `'AutoPrelude2.purs' should compile and run without error`, I have to remember that `BigFunction.purs` is the next test.
2. Relatedly, I found Tasty's reporting of per-test execution times to be kind of nice.

I don't know if either of these should be show-stoppers, but I wonder if the things we like about Hspec could be bodged into Tasty more easily than the reverse.

**Comment by hdgarrood** [comment]
I think reporting failures at the end would probably be easier to bodge into tasty, rather than getting the things you listed into hspec, since hspec doesn’t tell the “formatter” (the thing responsible for printing test results as they come) when a particular test starts and while there is an issue for it, doesn’t seem to be getting much interest.

**Comment by hdgarrood** [comment]
https://github.com/UnkindPartition/tasty/issues/273

**Comment by sol** [comment]
> Tasty reports when a test begins, not just when it ends.

`hspec-2.7.10` supports this with the new `checks [✔]/[✘]` formatter.  You can enable it with `--format checks`.

Technically we could shoehorn this into the current default formatter too, by printing the description uncolorized first when the spec item starts.  Not sure yet, still contemplating.

> Relatedly, I found Tasty's reporting of per-test execution times to be kind of nice.

`hspec-2.8.0` will support this.  You can enable it with `--times`.  I might wait for a couple of more breaking changes before releasing `2.8.0`.  But if this is a blocker for you guys please let me know and I'll prioritize it.

You can enable these settings globally or on a per project basis by adding these options to `.hspec` or `~/.hspec`. `checks` might become the default at some point in the feature.

And of course no obligations to use any of these, use what ever makes most sense for you guys (personally, I can't make a good case for `tasty-hpesc` in most scenarios).

**Comment by hdgarrood** [comment]
Thanks for the information! I agree that I'd like to drop `tasty-hspec` in any case - at this point I think we are trying to choose between pure `hspec` or pure `tasty`, rather than what we currently have which is a mixture of both.

**Comment by hdgarrood** [comment]
I don't want to ask you to rush getting 2.8.0 out just on our account, and I don't mind having this PR open for a little while. We can always depend on a particular commit temporarily if need be, I think.

**Comment by rhendric** [comment]
I'm really glad to hear that! I personally would be content with removing Tasty if we depend on 2.7.10 and set `-f checks` to be our default; I can wait for `--times`, knowing that it's on the way.
