### ISSUE TITLE
Merge purescript-ast and purescript-cst

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#4067]
## Summary

Merge purescript-ast and purescript-cst into one package in order to simplify maintenance and reduce the risk of users building compilers with untested combinations.

## Motivation

Having the compiler spread across three packages makes maintenance - specifically releases - harder (see #4061), and also increases the risk of users building versions of the compiler with untested combinations. For example, v0.14.0 currently has a version bound of >=0.1.0.0 <0.2 on purescript-cst and purescript-ast, which means that if we make a 0.1.1.0 release of purescript-cst and/or purescript-ast, people building the compiler from source could pick up that new version, which opens the door for surprising or incorrect behaviour. The more inter-package dependencies there are, the more opportunities there are for this to happen. (Aside: after writing this issue up I'm going to make a revision on Hackage to pin these bounds down to a specific version.)

As far as I am aware nobody is depending on purescript-ast directly (versus just depending on purescript-cst) anyway. Merging purescript-ast and purescript-cst into a single package will simplify maintenance and still provide almost all of the benefits of having the parser published as a separate package, since people will still be able to depend on purescript-cst and create tooling which depends on the parser without having to build the whole compiler together with all of its own dependencies.

## Proposal

At the moment, the dependency graph of the three packages that make up the compiler is as follows:

```
       ┌────────────┐
       │ purescript │
       └───┬───────┬┘
           │       │
┌──────────▼───┐   │
│purescript-cst│   │
└──────────┬───┘   │
           │     ┌─▼────────────┐
           └─────►purescript-ast│
                 └──────────────┘
```

I propose we merge purescript-cst and purescript-ast into a single package, so that we would have:

```
 ┌──────────┐
 │purescript│
 └────┬─────┘
      │
┌─────▼────────┐
│purescript-cst│
└──────────────┘
```

**Comment by JordanMartinez** [comment]
When I read through #4061, my thought was, "Wow... there's a lot that can go wrong there." So :+1: from me.

**Comment by wclr** [comment]
> Merge purescript-ast and purescript-cst into one package in order to simplify maintenance and reduce the risk of users building compilers with untested combinations.

> For example, v0.14.0 currently has a version bound of >=0.1.0.0 <0.2 on purescript-cst and purescript-ast, which means that if we make a 0.1.1.0 release of purescript-cst and/or purescript-ast, people building the compiler from source could pick up that new version, which opens the door for surprising or incorrect behaviour.

I'm not claiming that AST and CST things (in terms of PS case) should come separately or together, it should depend on a degree of inner coupling between them and real/assumed use cases. But if you want to solve the problem of "stable dependency" you can fixate versions (which is already have been done). Merging and combining packages is another aspect, it can soften the problem of dependency versions management but not get rid of or solve it. 

So what I would like to state here is that splitting packages apart is not a problem by itself, but incorrect and inappropriate splitting (as well as merging) will be a problem that will be constantly reminding about itself in the long run.

**Comment by wclr** [comment]
I also would let myself use this issue to make a small analysis of the situation and explain better [the proposal I made on packages and their management](https://discourse.purescript.org/t/proposal-on-purescript-package-management/2245). Though the current situation relates to Haskell land, it is still theoretically applicable, and also can reveal some issues with currently used module namespaces.

According to the prosed approach to packages, if applied, the situation would look the following way:

**purescript-cst:**

This package would exist as `Language.PureScript.CST` package and would contain only this namespace (the internal thing which currently is named `Data.Text.PureScript` would be not exposed).

**purescript-ast:**

This would be a package named `Language.PureScript.AST`, which would only expose this namespace. `Control.Monad.Supply` looks like an internal thing.  But also `purescript-ast` contains a number of modules with namespaces `Language.PureScript.*` (where is * is `Constants`, `Comments`, `Label`, `Names`, etc.) that are not part of `Language.PureScript.AST` namespace. 

I'm not sure if these modules are supposed to be internal only for `AST` package, or they should be exposed and available for consumers. If the latter is true then those namespaces could not be contained inside the same package `Language.PureScript.AST`, but could be only contained and exposed either by higher level `Language.Purescript` package or they would require to have their own packages each (which would reasonably be strange).

This also reveals the issue with currently used namespaces: there exist distinctively different domain namespaces like `Language.Purescript.CodeGen`, `Language.Purescript.Ide`, etc., and those modules that were mentioned above with their names (`Langauge.Purescript.Comments/Names/Label`) **definitely fall out of the general naming scheme.** They would better be combined inside their own common namespace (which they belong in terms of their common purpose) for example, `Language.PureScript.Syntax`.

So we could have already three packages here `Language.PureScript.Syntax`, `Language.PureScript.AST` `Language.PureScript.CST`. This would be reasonable if all of these three things would be considered to be relatively independent and there would be use cases of using them separately. But if not, it probably would be a good option to have only one package named `Language.PureScript.Syntax`, which would also expose nested namespaces `Language.PureScript.Syntax.AST` and `Language.PureScript.Syntax.CST`.

This is how I propose to deal with packages based on a more conscious approach to module namespaces if we don't want to pollute and abuse them.

This is of course just a hypothetical analysis. But still what could really be considered from it in the current situation is to combine syntax related modules (`Language.PureScript.Comments/Name`) under common namespace (e.g., `Language.PureScript.Syntax`), and also a merged package (which should contain inside `AST` and `CST`) could probably be named `purescript-syntax`, as this name may better communicate the contents than `purescript-cst`.
