### ISSUE TITLE
Fix warnings in core libs revealed `v0.14.1` PS release

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4071]
Now that `v0.14.` is out, we should fix any of the warnings found by the update in core libs. This issue tracks which of them need that and whether a PR has been submitted/merged yet. A checked box below means a PR has been submitted (but not necessarily merged). See methodology below for how this list was produced.

- [x] arrays
- [x] catenable-lists
- [x] datetime
- [x] filterable
- [x] foldable-traversable
- [x] foreign
- [x] free
- [x] functors
- [x] lists
- [x] ordered-collections
- [x] prelude
- [x] quickcheck
- [x] st
- [x] tailrec
- [x] transformers
- [x] tuples

Method for producing the above list:
1. Created a new project using `spago init`
2. Manually updated `packages.dhall` file to update `metadata.version = "v0.14.1"`
3. Ran `spago install $(spago ls packages | cut -f 1 -d ' ' | tr '\n' ' ')` to install all packages in the set
4. Ran `spago build --purs-args "--censor-codes='UserDefinedWarning'"`. I was trying to stop MonadZero deprecation notices from being include din list of warnings. I don't think this worked because `censor-codes` likely only works on source code defined in the `src/` directory, not the `.spago/` directory.
5. Copied shell's output that listed all warnings into file called `fix-warnings-source`
6. Ran `cat fix-warnings-source | grep '.spago/' | cut -f 3 -d ' ' | cut -f 2 -d '/' | uniq > fix-warnings.txt` (record a list of deduplicated packages that have a warning in them)
7. Copied and pasted data into Excel file
8. Ran `spago ls packages | grep '/purescript/' | cut -f 1 -d ' ' > purescript.txt` to get a list of all core repos
9. Ran `spago ls packages | grep '/purescript-contrib/' | cut -f 1 -d ' ' > purescript-contrib.txt` to get a list of all contrib repos
10. Pasted `purescript.txt` and `purescript-contib.txt` into Excel fil
11. Used `VLOOKUP` Excel formula to find all purescript and purescript-contrib libs that had warnings.

This likely isn't the best method for determining things, but seems like it's likely 90% right.

**Comment by JordanMartinez** [comment]
Looks like 5 left for core libs

**Comment by thomashoneyman** [comment]
@JordanMartinez would it be possible to do the same for the `web` and `node` libraries and add them to the contrib governance issue?

**Comment by JordanMartinez** [comment]
Done.

**Comment by JordanMartinez** [comment]
Only 2 more PRs to merge and then this issue can be closed once new releases are made of the libraries.
