### ISSUE TITLE
Automatic eta abstraction to fix binding group issues

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#408]
Something that would be really nice to have... encountered in `Language.PureScript.Pretty.Types`, there are a lot of mutually recursive functions/values, one of which could be defined like this:

``` haskell
prettyPrintTypeAtom :: Type -> String
prettyPrintTypeAtom = runPretty $ pattern (matchTypeAtom unit) unit <<< insertPlaceholders
```

But it doesn't work, and the fix is very simple:

``` haskell
prettyPrintTypeAtom :: Type -> String
prettyPrintTypeAtom p = runPretty (pattern (matchTypeAtom unit) unit <<< insertPlaceholders) p
```

It would be great if we could work out how to insert that kind of thing automatically.

**Comment by paf31** [comment]
I think we've sort of committed to disallowing this at this point, and I think it has a good error message. And the usual comments about generating names, simple codegen etc. apply.

Close?

**Comment by garyb** [comment]
I still think it's a very unfortunate implementation detail to leak, the few times I've run into it it has been rather frustrating, especially when the fix is something the compiler obviously could do itself. But if you really don't want to do it then I guess I can live without it, it's not something that occurs super often.

I think we have a slight philosophical difference with the generated JS :wink:. I don't care about it being 1:1 with the input, as long as it is somewhat readable, and that every declaration in PS corresponds to a declaration in the generated JS. Besides, our generated JS has far worse problems than introducing an additional `function (_0) { ... }`! (Which we also already do a lot of, there are many places we generate a name for arguments as we cannot take one from the PS code).

**Comment by paf31** [comment]
It's not just that. It's not clear to me that eta expanding a function will fix these problems in general. I like the force the developer to think about why eta expansion is the appropriate solution. In some cases, it's probably more appropriate to use something like `fix` or `defer`.

**Comment by garyb** [comment]
Ah, that's a good point. The case I was concerned with here is self-referential point-free declarations. Eta abstraction allows the self reference by postponing the reference until the argument value is supplied.

The case where I think it perhaps doesn't work is where you have a binding group of point-free declarations. I encountered this in Halogen actually, where I had to do something more `fix`-like, but I feel like it should still be solvable by eta-abstracting all the relevant definitions. I'll have to investigate a bit more, but really the main consideration here was just for self-referential declarations.

**Comment by paf31** [comment]
I think you need to do a strictness analysis in general. Consider

```purescript
ones :: List Int
ones = Cons 1 ones
```

This won't compile, and eta reducing it is both wrong on the type level, and wrong for strictness reasons.

But this brings up an interesting point. Eta-reduction should happen, if at all, in the elaborator, where types are known, and where we have a good way to think about correctness. Right now, this analysis happens in desugaring.

**Comment by garyb** [comment]
Yeah, I was definitely thinking this would be type directed, only applying to function declarations, so wouldn't apply to the case above.

**Comment by AppShipIt** [comment]
Combing for stale issues. Did y'all decide against this?

**Comment by paf31** [comment]
I vote to close. @garyb ?

**Comment by garyb** [comment]
Perhaps we could keep it in ideas for now. I'd at least like to take a stab at it... although admittedly now we're not working on ps-in-ps anymore this situation does occur much less frequently in the code I'm writing!

**Comment by paf31** [comment]
I worry that this is potentially harmful. We'd have to be very careful to decide when we add the extra function. It would have to be in a function in a recursive binding group, but which didn't call itself recursively, with the possible exception of calling itself under another function. I just think a better error message would be good enough, and safer, and more predictable.

**Comment by natefaubion** [comment]
I'm inclined to agree with @paf31 on this. Since this hasn't seen activity in a while, I'm going to close for now.

**Comment by garyb** [comment]
I'm fine with that too now. I think the whole thing could have been boiled down to "PS is strict, deal with it 🕶".

**Comment by garyb** [comment]
I'm fine with that too now. I think the whole thing could have been boiled down to "PS is strict, deal with it 🕶".
