### ISSUE TITLE
Infix names with backticks don't use the same offside rule as operators

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#4171]
## Description

Infix (backtick) names do not affect layout in the same way as operators do. Operators use the `offsideEndP` rule which lets you write:

```purescript
example = do
  foo bar
  <|> baz
```

An operator at the same column as a layout block will close the layout block. Infix expressions use the `offsideP` rule through `insertDefault`.

```purescript
example = do
  foo bar
  `wat` baz
```

This will result in a parse error. It should parse with the same offside rule as operators.

## Additional context

https://github.com/natefaubion/purescript-tidy/issues/15#issuecomment-894552462

## PureScript version

0.14.3

**Comment by JordanMartinez** [comment]
Is this fix a simple oneliner change?

**Comment by natefaubion** [comment]
Yes, I believe it's enough to change `insertDefault` here:
https://github.com/purescript/purescript/blob/ec4dd2b368acdd94b94b548239486ce631369fbb/lib/purescript-cst/src/Language/PureScript/CST/Layout.hs#L268

To look more like the operator case here:
https://github.com/purescript/purescript/blob/ec4dd2b368acdd94b94b548239486ce631369fbb/lib/purescript-cst/src/Language/PureScript/CST/Layout.hs#L317

As well as adding a layout golden test for this.
