### ISSUE TITLE
Compiler error with kind unification

### ISSUE THREAD

**Issue by xgrommx** [purescript/purescript#4180]
Hello, I have this code
https://try.purescript.org/?gist=2a520630acabc7922850c63f0b4aeae1&session=b36a64fa-26e7-1a2d-33c2-a9feaa5db509

But I got some error with kind unification

I know that this code isn't easy, but this problem I can reproduce only with this code.

**Comment by LiamGoodacre** [comment]
Assuming it's the same kind of bug, I've managed to get:

```
Internal compiler error:

    Unsolved unification variable ?13 is not bound

  CallStack (from HasCallStack):
  internalCompilerError, called at src/Language/PureScript/TypeChecker/Kinds.hs:142:16 in purescript-0.14.5-8LnlRSMAPyjZJtqHKRFLb:Language.PureScript.TypeChecker.Kinds
  lookupUnsolved, called at src/Language/PureScript/TypeChecker/Kinds.hs:466:19 in purescript-0.14.5-8LnlRSMAPyjZJtqHKRFLb:Language.PureScript.TypeChecker.Kinds
  promoteKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:440:9 in purescript-0.14.5-8LnlRSMAPyjZJtqHKRFLb:Language.PureScript.TypeChecker.Kinds
  solveUnknown, called at src/Language/PureScript/TypeChecker/Kinds.hs:409:7 in purescript-0.14.5-8LnlRSMAPyjZJtqHKRFLb:Language.PureScript.TypeChecker.Kinds
  unifyKindsWithFailure, called at src/Language/PureScript/TypeChecker/Kinds.hs:369:15 in purescript-0.14.5-8LnlRSMAPyjZJtqHKRFLb:Language.PureScript.TypeChecker.Kinds
  unifyKinds', called at src/Language/PureScript/TypeChecker/Entailment.hs:322:21 in purescript-0.14.5-8LnlRSMAPyjZJtqHKRFLb:Language.PureScript.TypeChecker.Entailment
  Please report this at https://github.com/purescript/purescript/issues
```

From this tiny example:

```purescript
class C :: forall k . k -> Constraint
class C t
instance C (t i) => C (t i)
eg :: Int
eg = (0 :: forall t i . C (t i) => Int)
```

**Comment by rhendric** [comment]
Even smaller example:

```purs
class C (t :: Type)
instance C (f a)
eg :: Int
eg = (0 :: C (Array String) => Int)
```

The problem seems to be triggered by the kind polymorphism inherent in `instance C (f a)`. The kind of `a` is completely unconstrained in this instance; there isn't even a way to constrain it, as we don't yet have #1120 and `instance C (f (a :: Type))` isn't legal either. `f` is partially constrained by the kind expected by `C`, but it doesn't constrain `a` the same way that `instance C (Array a)` would.

Is this a case where we should say, oh well, until #1120 such instances are always going to be maximally generalized and we need the type checker to be able to cope with polykinded instances? Or should we restrict such instances until some way to opt in or out of kind generalization is provided?

**Comment by natefaubion** [comment]
> but it doesn't constrain a the same way that instance C (Array a) would.

Is there a reason not to support this?

> Is this a case where we should say, oh well, until https://github.com/purescript/purescript/issues/1120 such instances are always going to be maximally generalized and we need the type checker to be able to cope with polykinded instances? Or should we restrict such instances until some way to opt in or out of kind generalization is provided?

It seems like it should be generalized. It's not clear to me why it couldn't be. I expect it's not because I didn't think about it.

**Comment by rhendric** [comment]
> > but it doesn't constrain a the same way that instance C (Array a) would.
> 
> Is there a reason not to support this?

Assuming the referent of ‘this’ is `instance C (f a)`, my highly tentative reason not to support it would be that we can control the kind polymorphism of every other type of declaration in PureScript, and we even go so far as to warn users if they've written something polykinded without an annotation that affirms it. That suggests to me that we consider kind polymorphism an advanced feature that we don't want to give to users without their consent. With `instance C (f a)`, there's no way to affirm that kind polymorphism is intended, and no way to opt out. We would be violating the implied don't-hand-out-kind-polymorphism-without-consent policy.

**Comment by rhendric** [comment]
On the other hand, I guess we generalize without warning users when defining polykinded values like `f :: forall a. Proxy a -> Int`, so maybe instances belong in that bucket—they're ultimately terms with some extra metadata. It's still a minor issue that we have no syntax that allows the user to fix the kinds of instance type parameters, but maybe in practice it's far more likely either that something else in the instance definition will determine kinds or that kind polymorphism is the desired outcome.

**Comment by natefaubion** [comment]
> Is there a reason not to support this?
Sorry, I mean the type ascription in an instance head.

**Comment by rhendric** [comment]
Oh, because `f (a :: Type)` is parsed as applying `f` to a row. Maybe we could bludgeon the parser into not doing that in instance heads?

Although... I did not try `f ((a) :: Type)` before, and that does work! And prevents this crash if kind polymorphism isn't needed.

**Comment by natefaubion** [comment]
> Although... I did not try f ((a) :: Type) before, and that does work! And prevents this crash if kind polymorphism isn't needed.

That's good to hear 😅
