### ISSUE TITLE
Installing purescript via npm fails with EPERM

### ISSUE THREAD

**Issue by pmiddend** [purescript/purescript#4185]
## Description

I'm trying to `npm install` purescript 0.14.4 and am getting this error:

```
✔ Check if a prebuilt 0.14.4 binary is provided for linux (503ms)
✔ Download the prebuilt PureScript binary (596ms)
✖ Verify the prebuilt binary works correctly
  /home/pmidden/amarcord/purescript-frontend/node_modules/purescript/purs.bin --version
  Error: Command failed: /home/pmidden/amarcord/purescript-frontend/node_modules/purescript/purs.bin --version
/home/pmidden/amarcord/purescript-frontend/node_modules/purescript/purs.bin: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/pmidden/amarcord/purescript-frontend/node_modules/purescript/purs.bin)
/home/pmidden/amarcord/purescript-frontend/node_modules/purescript/purs.bin: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/pmidden/amarcord/purescript-frontend/node_modules/purescript/purs.bin)

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)
▬ Save the downloaded binary to the npm cache directory

↓ Fallback: building from source

✔ Check if 'stack' command is available
        2.7.3 found at /home/pmidden/software/stack
✔ Download the PureScript 0.14.4 source (2s)
✖ Ensure the appropriate GHC is installed (239ms)
  stack setup
  Error: Command failed with exit code 1 (EPERM): stack --allow-different-user setup
    at makeError (/home/pmidden/amarcord/purescript-frontend/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/pmidden/amarcord/purescript-frontend/node_modules/execa/index.js:112:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
▬ Build a binary from source
▬ Save the built binary to the npm cache directory
```

First of all: the output is very easy to comprehend, kudos to that!

Second, for the actual problem: It seems to not find a compatible binary, which is fine, I guess. It finds stack, and then tries to call stack to build the compiler. But it fails with `EPERM`. Fair enough, but what permissions are wrong here? It gives no indication. I tried using `strace` to dig deeper, but found nothing interesting.

**Comment by JordanMartinez** [comment]
Does [this section](https://github.com/purescript/purescript/blob/master/INSTALL.md#eacces-error) provide info on how to fix that?

**Comment by pmiddend** [comment]
Interesting! I tried the solutions mentioned and didn't have any luck.

Any idea on how I can get more output, maybe? I could compile Purescript separately and put it into my path, sure, but I think it would be great to fix the installation process so more people have easy access to Purescript.

**Comment by hdgarrood** [comment]
I've not seen this particular error before, as far as I can remember. Are you able to build the compiler using stack manually (i.e. outside of `npm install purescript`)?

**Comment by pmiddend** [comment]
Interestingly, I wasn't. The build was failing because of the _ancient_ gcc version that's installed on the machine (it failed after a minute or so). When I load a newer gcc, not only does it build _outside_ of `npm install`, but also _inside_ it.
It's weird, because...why does `stack setup` fail, and why with `EPERM`?

**Comment by hdgarrood** [comment]
That is indeed quite weird. Glad to hear the problem is solved, at least!

**Comment by pmiddend** [comment]
Yes, thanks for the pointers. I'll close this for now, then.
