### ISSUE TITLE
KindsDoNotUnify error when deriving Newtype from alias

### ISSUE THREAD

**Issue by wclr** [purescript/purescript#4200]
## Description

The case, seems like a bug: 
- there is a parameterized data type and an alias for this data type (in practice defined in different modules)
- in another module deriving `Newtype` instance for a `newtype` that contains mentioned alias type
- the compiler gives an error `KindsDoNotUnify`

## To Reproduce

The minimal example to reproduce requires two modules:

```purs
module Test.A where

import Test.B (TAlias)
import Data.Newtype (class Newtype)

newtype NewA a = NewA (TAlias Int)

derive instance Newtype (NewA a) _
```

```purs
module Test.B where

data T :: forall m. m -> Type
data T msg = E

type TAlias :: forall k. k -> Type
type TAlias msg =
  T msg -- here is an error
```

The error:
```
  Could not match kind

    Type

  with kind

    k


while checking that type Int
  has kind k
while inferring the kind of T @k Int
while inferring the kind of Newtype (NewA a) (T @k Int)
in type class instance

  Data.Newtype.Newtype (NewA a)
                       (T @k Int)
PureScript(KindsDoNotUnify)
```

## Expected behavior

Should be no error.

## Additional context

It starts working if to replace `TAlias's` kind signature with `Type -> Type`

## PureScript version

0.14.5

**Comment by PureFunctor** [comment]
I'm currently investigating this and type kind application (`T @k Int`) here seems to be pertinent to the bug. If `TAlias` is moved to `Test.A`, the `replaceAllTypeSynonyms` routine doesn't add the kind application which causes the failure above.
