### ISSUE TITLE
Proposal: Support optional shebang line in module header

### ISSUE THREAD

**Issue by colinwahl** [purescript/purescript#4210]
## Motivation

There are now a few mechanisms for executing a PureScript file, such as through `spago run` or `spago script`. Supporting a shebang line in the a module header would allow users to configure how to run the module (on unix systems) directly within the file itself.

## Proposal

Support an optional [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) line. It must be on the first line of a file.

## Examples

The shebang line is optional, so module headers can stay the same:

```
module Main where

...

main = do
  ...
```

However, they could be present in the module header before the module keyword:

`Main.purs`

```
#! /usr/bin/spago script -d node-fs

module Main where

...

main = do
  ...
```

This can then be run with `./Main.purs`, instead of having to write out the `spago script` command each time.

**Comment by f-f** [comment]
I think we should support multiple shebang lines, so that things like `nix-shell` work, e.g.

```
#! /usr/bin/env nix-shell
#! nix-shell -i "spago script" -p spago
```

**Comment by colinwahl** [comment]
Hah! I didn't even realize you could do that. Makes sense.

**Comment by colinwahl** [comment]
It looks like GHC uses a preprocessing step to transform shebang lines into comments before parsing: https://github.com/ghc/ghc/blob/56eb57a6b348d44370fc84f6a35caabd1c548b5e/utils/check-exact/Preprocess.hs#L62-L85

This approach is attractive in the sense that there doesn't have to be any changes to the CST grammar, but it also means that printing the CST doesn't print exactly the same code, which is not ideal.
