### ISSUE TITLE
Proposal: Gitpod Configuration

### ISSUE THREAD

**Issue by PureFunctor** [purescript/purescript#4211]
## Summary

[Gitpod](https://www.gitpod.io/) offers cloud development environments, and they also provide a template for developing Haskell projects, which can be seen [here](https://github.com/gitpod-io/template-haskell). Introducing a `.gitpod.yml` file for configuring Haskell tooling e.g. `ghcup` + `cabal/stack` + `hls` would allow for faster bootstrapping for Gitpod users.

## Motivation

Gitpod is a pretty neat platform for developing heftier applications on underpowered machines; Haskell, especially, tends to be one of the worse offenders. I don't think this necessarily adds a maintenance burden as it'd really be just an installation script for Haskell tooling; `stack` already installs the appropriate compiler version too, and likewise, I don't think the GHC version would be updated all that much.

**Comment by rhendric** [comment]
Closing per (brief) discussion in #4222.
