### ISSUE TITLE
UnusedDeclaration link is not working

### ISSUE THREAD

**Issue by codingedgar** [purescript/purescript#4212]
I had this error 
```
  See https://github.com/purescript/documentation/blob/master/errors/UnusedDeclaration.md for more information,
  or to contribute content related to this warning.
```

But the link was broken, it seems https://github.com/purescript/documentation does no longer documents UnusedDeclaration

**Comment by nwolverson** [comment]
It looks like the error text in the issue has been truncated, there is in fact no link.

If I recall these documentation used to be a wiki in which case the page could be created if you hit it, not now in a documentation repo.

In any case this should probably be an issue on the documentation repo linked in the issue description.
