### ISSUE TITLE
Proposal: Add compiler-solved class for converting type-level `Int` to type-level `String` (Symbol)

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4263]
## Summary

Add a compiler-solved type class that converts type-level integers into type-level strings.

## Motivation

One of the drawbacks of the JS backend is that it doesn't support large integers. Thus, reflecting a large type-level Int to a value-level Int can be impossible to do. Consider the following example in the REPL:
```purescript
> (top :: Int)
2147483647
> reflectType (Proxy :: Proxy 2147483647)
2147483647
> -- add 1
> reflectType (Proxy :: Proxy 2147483648)
An error will be thrown here
> (bottom :: Int)
-2147483648
> reflectType (Proxy :: Proxy (-2147483648))
-2147483648
> -- subtract 1
> reflectType (Proxy :: Proxy (-2147483649))
An error will be thrown here
```

This issue could be worked around if we could instead convert the type-level integer into a type-level string, reflect that type-level string to a value-level one, and then call `Data.BigInt.fromString`.

## Proposal

Since I don't yet understand the compiler deeply, I'm not sure how much of the below content is correct. Correct me where I'm wrong.

Given that `Reflectable` is a class that will be defined like so (see https://github.com/purescript/purescript-prelude/issues/286)
```purescript
class Reflectable v t | v -> t where
  reflectType :: Proxy v -> t
```
we essentially want the compiler to solve the type class via the instances below:
```purescript
-- Assume backtracking works in the below example
instance Between (-2147483648) 2147483647 value => Reflectable (value :: Prim.Int) Int where
  reflectType _ = jsIntValue
else instance Reflectable (allOtherValues :: Prim.Int) String where
  reflectType _ = stringifiedVersion
```

There are two issues with the above implementation. First, the functional dependency ensures that `Prim.Int` determines the type we return. In one version, we should return `Int`. In another, we should return `String`. To fix this, we would need to drop the functional dependency. But if that was done, the solver wouldn't know how to determine what `t` is.

We could get around that issue by wrapping the returned value in `Either`...
```purescript
-- Assume backtracking works in the below example
instance Between (-2147483648) 2147483647 value => Reflectable (value :: Prim.Int) Int where
  reflectType _ = Right jsIntValue
else instance Reflectable (allOtherValues :: Prim.Int) String where
  reflectType _ = Left stringifiedVersion
```
... but that's not ideal.

Second, backtracking isn't yet supported (and I'm not sure whether and when it will be supported). So, how would the compiler solve the class? Is backtracking only needed when implementing instances in PureScript? Or does the compiler need it to solve things, too?

It would seem that both problems can be solved if we provide another type-level type to indicate which kind of `Int` it is. For example `Prim.Int` would be reflectable to a normal JS Int whereas `Prim.BigInt` would always reflect to a `String` that can be used by `Data.BigInt`.

I'm not sure how that would affect syntax though. If we wrote `type TypeLevelInt = 14`, does PureScript interpret that as having kind `Prim.Int` or kind `Prim.BigInt`? Do we always need to indicate which one it is via some annotation? Do we add some suffix/prefix that indicates which kind of int it is (e.g. `14i` vs `14bi`?)?

See also #3848 for other context on a similar discussion.

**Comment by natefaubion** [comment]
I think  that  we should just add a `Prim.Int.ToSymbol/ToString` class.

**Comment by JordanMartinez** [comment]
If we're already considering #3103, then I think it should be `Prim.Int.ToString` so there's one less thing to rename later, even if it's a bit confusing initially.

**Comment by JordanMartinez** [comment]
I think the principles that govern whether to add support for a compiler-solved type class (e.g. type-level function) are:
1. Define the ideal type class the first time with forwards-compatible changes, so we don't need to make breaking changes later
1. If the class cannot be done in PureScript-land, then do it in the compiler
1. If the class can be done but 1) doing so incurs an extraordinarily high performance cost and 2) many people rely on it, then do it in the compiler
1. In any other situation, the person who wants to add such a class needs to garner more support among others until principle 3's second condition is satisfied.

While working on #4267, a couple of issues arose. I started out with this type class:
```purs
class ToString :: Int -> Symbol -> Constraint
class ToString int string
  | int -> string
```

### Issue 1. Support for both directions.

Since we support conversion going one way, conversion going the other way may as well be supported because we don't need to define two separate type classes for arguably the same purpose. Refining the type class, we then get:
```purs
class ToString :: Int -> Symbol -> Constraint
class ToString int string
  | int -> string
  , string -> int
```

AFAICT, implementing this in PS land is possible but the performance hit would be very large. I also presume that many would use this for at least the original cause of this issue--to reflect integers outside of the `Int` range into a `BigInt` type--if not more things discovered later. 

### Issue 2. Roundtrip

Should these roundtrip? I assume yes because of the functional dependency. Depending on what we support (next few issues), that makes the implementation more complex or ambiguous.

```purs
convert
  :: forall i1 i2 s1 s2
  . IntToString i1 base s1
  => Int.ToString i2 base s2
  => Tuple (Proxy i1) (Proxy s1)
  -> Tuple (Proxy s1) (Proxy i2)
  
tyEq
  :: forall a b c d
  . TypeEquals a b
  => TypeEquals c d
  => Tuple a c
  -> Tuple b d
  -> Unit
  
test = do
 let
   arg = Tuple (Proxy :: _ 1) (Proxy :: _ "1")
   expected = Tuple (Proxy :: _ "1") (Proxy :: _ 1)
  tyEq (iToS arg) expected
```

### Issue 3. Common or Arbitrary Bases

An integer `1000` can be converted to a string in a couple of ways based on the base. For example:
- base 2 (binary): "1111101000"
- base 8 (octal): "1750"
- base 10 (decimal): "1000"
- base 16 (hexadecimal): "3E8"

Do we only support a common set of bases? If so, which bases? If we support a common set of bases, the type class might then look like this:
```purs
data Base
foreign import data Base2 :: Base
foreign import data Base8 :: Base
foreign import data Base10 :: Base
foreign import data Base16 :: Base

class ToString :: Int -> Base -> Symbol -> Constraint
class ToString int base string
  | int base -> string
  , string base -> int
```

Or do we support an arbitrary number of bases? In other words, something like this?
```purs
data BaseKind
foreign import data Base :: Int -> BaseKind

class ToString :: Int -> BaseKind -> Symbol -> Constraint
class ToString int base string
  | int base -> string
  , string base -> int
  
-- usage
foo :: forall i s. IntToString i (Base 20) s => Proxy i -> Proxy s
```

Assuming we only supported Base10, likely the most common usage, and dropped the `base` type parameter completely, then reimplementing the type class for the other bases in PS land would incur a huge performance cost. However, it's unknown whether people would use such bases. But, if we found out later that using other common bases is desired, then we would need to make a breaking change by adding the `base` type parameter back to the `ToString` class. Similarly, if we made such a change and then wanted to support arbitrary bases, we would need to make yet another breaking change.

### Issue 4. Simple or Arbitrary Mappings

Moreover, do we also want to support arbitrary mappings? For example, [Base58](https://learnmeabitcoin.com/technical/base58) omits the `0`, `I`, `l`, and `O` characters to prevent possible typos or confusion. If we wanted to support arbitrary bases with arbitrary mappings, we might then refine the type class to this:

```purs
class ToString :: Int -> Symbol -> Symbol -> Constraint
class ToString int base string
  | int base -> string
  , string base -> int
```
The `base` could be calculated based on how many characters are in the string (e.g. `base10` would be `0123456789`, and `base2` would be `01`)

But this does not entirely solve the problem. Consider `base16`. Are the letter parts of the base case sensitive (e.g. `0123456789ABCDEF` vs `0123456789abcdef`)? So, to support that, we might have a type-level list that indicates either a specific value or one or more values. For example
```purs
foreign import data One :: Symbol -> BaseKind
foreign import data Either :: Symbol -> BaseKind

-- Assuming literal type-level arrays syntax was supported
foo :: forall i s. ToString s [One "1", Either "Aa"] s => ...
```

But this also introduces ambiguity. If `A` and `a` can both map to an integer value, then to which character does one map an Int using the same `base` arg? In other words, it would break roundtripping.

### Issue 5. Delimiters.

In PureScript, we parse `1_000` and `1000` the same. Humans tend to write `1,000` or `1.000` depending on their culture, and some may copy values that include such delimiters and paste them into source code. Do we support something similar in this `ToString` class? If this was supported, the type class might be refined to
```purs
data Base

class ToString :: Int -> Base -> Delimiter Symbol -> Constraint
class ToString int base delimiter string
  | int base delimiter -> string
  , string base delimiter -> int
```

I'm thinking no on this one because it could be handled in user-land if we added more primitive compiler-solved type-level functions for type-level `String`s (e.g. `take :: Int -> String -> String`).

**Comment by rhendric** [comment]
IMO, this is taking a speculative (?) but understandable need—enable a run-time representation of large compiler-solved integers—and totally running away with it.

Does anyone have a use case in mind for doing a type-level computation that produces a string and wanting to convert that string into a type-level integer? I expect that to be a vanishingly rare need, and as it's possible to implement in userspace given the type-level arithmetic classes we've provided (in any base, with any encoding), not worth solving in the compiler.

Without that, I think we can stop at Issue 1: the purpose of `ToString` shall be to convert type-level integers into decimal strings for culture-agnostic machine consumption, and not the other way around.

**Comment by JordanMartinez** [comment]
> and totally running away with it.

:laughing: Yeah, I agree, but I did want to explore the possible design space to ensure we weren't missing something.

> Does anyone have a use case in mind for doing a type-level computation that produces a string and wanting to convert that string into a type-level integer?

I think this can be answered by thinking of possibilities. If a possibility can be shown to pointless, then there is likely no actual use case for it. AFAIK, `Symbol`s can be used for 
1. custom type errors (e.g. [`Text`](https://pursuit.purescript.org/builtins/docs/Prim.TypeError#t:Text))
1. potentially as the index in indexed monads
1. a compile-time-computed runtime `String` value
1. labels in row kinds (e.g. `Record`s or `Variant`s)

Outside of those use cases, I'm not sure how else `Symbol`s would be used. 

Regarding 1, there's no reason why one would need to convert a type-level `String` into a type-level `Int` if that `String` is being used for a custom error. If one wants to use an `Int` in a custom type error, the `ToString` class already handles that.

Regarding 2, 3, and 4, I would imagine a user would just start with a type-level `Int` in the first place, soon thereafter convert it to `Symbol`, and have both types passed around as needed. If a computation needed to be done, they could operate on the `Int` or the `Int` and `Symbol`. For example, the primary purpose with regard to `Record`s would likely be to check if some label in a row (an `Int` that was converted into a `String`) is the same value as some `Int`. And that could also be done by passing the original `Int` around, converting it back into a `String`, seeing if the two values are equal, and if so using the original `Int` for the next computation.

Put differently, I don't think there is a possible use case for converting a type-level `String` to a type-level `Int` that can't be solved by some other workaround.

**Comment by natefaubion** [comment]
I think that you could justify a String -> Int conversion in some sort of type-level parser, but I'm not sure that is the interface you want. You could also implement that in user land. More than that though, I don't really agree that the inverse functional dependency necessarily holds. I think the conservative approach would be to omit it for now.

**Comment by JordanMartinez** [comment]
Good point.

All that to say, I think we're in agreement that `ToString` should only be in one direction (`Int -> String`) using base10.
