### ISSUE TITLE
Packaged binary does not run on NixOS

### ISSUE THREAD

**Issue by blackheaven** [purescript/purescript#4280]
## Description

The linux packaged binary does not run on NixOS.

## To Reproduce

```
$ wget https://github.com/purescript/purescript/releases/download/v0.14.9/linux64.tar.gz
$ tar xvzf linux64.tar.gz
$ purescript/purs
zsh: no such file or directory: purescript/purs
```

## Expected behavior

Have a running binary

## Additional context

In nixpkgs they use `patchelf`:

```
patchelf --interpreter ${dynamic-linker} --set-rpath ${libPath} $PURS
```

However I'm trying to update bazel's `rule_purescript`, and I can't find an easy way to do it.

## PureScript version

0.14.9

**Comment by natefaubion** [comment]
FYI, I think for nix, you might consider https://github.com/justinwoo/easy-purescript-nix

**Comment by JordanMartinez** [comment]
Should this issue be closed?

**Comment by blackheaven** [comment]
The bug remains but I'll eventually find a workaround
