### ISSUE TITLE
Error in Handbook - Asynchronous Effects

### ISSUE THREAD

**Issue by twentyonepepes** [purescript/purescript#4281]
## Description

The following pertains to this chapter of the handbook:

https://book.purescript.org/chapter9.html

## To Reproduce

Consider the following code example, taken directly from the handbook chapter on Asynchronous Effects.
```

-- https://book.purescript.org/chapter9.html
module Main where 

import Prelude
import Data.Either (Either(..))
import Effect.Aff (Aff, attempt, message)
import Effect.Class.Console (log)
import Node.Encoding (Encoding(..))
import Node.FS.Aff (readTextFile, writeTextFile)
import Node.Path (FilePath)

copyFile :: FilePath -> FilePath -> Aff Unit
copyFile file1 file2 = do
  my_data <- readTextFile UTF8 file1
  writeTextFile UTF8 file2 my_data

main :: Aff Unit
main = do
  result <- attempt $ copyFile "file1.txt" "file2.txt"
  case result of
    Left e -> log $ "There was a problem with copyFile: " <> message e
    _ -> pure unit
```
However, when this application is run with Spago Run, it produces the following puzzling error, which seems to resemble a JavaScript error instead of a PureScript error.

`require(...).main is not a function`

## Expected behavior

A fix was discovered by Fyodor Soikin, detailed here:

https://stackoverflow.com/questions/71737310/purescript-aff-require-main-is-not-a-function

## PureScript version

Unknown (how do you check?)

**Comment by thomashoneyman** [comment]
Thanks for the report! This issue should actually be opened on https://github.com/purescript-contrib/purescript-book, which hosts the book's contents.

As Fyodor Soikin noted, the fix is to ensure the `main` function is running in `Effect` by using [`launchAff_`](https://pursuit.purescript.org/packages/purescript-aff/6.0.0/docs/Effect.Aff#v:launchAff_) from the `Effect.Aff` package.

**Comment by twentyonepepes** [comment]
Why not move the issue?

**Comment by thomashoneyman** [comment]
Oh, can we? It's a different organization altogether, so I didn't think I could. If we _can_ move it then let's do that!

**Comment by twentyonepepes** [comment]
Recreated manually to save time

https://github.com/purescript-contrib/purescript-book/issues/417

**Comment by garyb** [comment]
Ah, thanks! Also, you're right @thomashoneyman we can't move it cross-organization. 🤦‍♂️
