### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by rhendric** [purescript/purescript#4303]
## Summary

From https://github.com/purescript/purescript/issues/4294#issuecomment-1102800906, compile and publish prereleases to GitHub and npm for every successful build of the master branch.

## Motivation

* Prereleases are a necessary part of the major release process, and making them manually drains time from our already busy release managers and delays progress on other parts of the ecosystem while they wait for approval. A continuous deployment process that uses the same publication channels as a manual release would eliminate these delays.
* Our release process is currently largely manual, exercised infrequently, and limited to a subset of core team members with the necessary permissions in GitHub, Hackage, and the npm registry. All of these factors make the process brittle, and a continuous deployment process would make incremental progress on all of them (except for Hackage; I don't plan to touch that one).
* As publishing to npm is one of the final steps in our release process, it isn't possible to catch some downstream release issues until after they have been published, at which point fixing those issues requires burning a version number. Having a compiler already available on npm with nearly identical code to the upcoming release would mean that most of those issues could be caught before the version bump commit is pushed.
* Users who are enthusiastic about testing upcoming compiler features will be able to do so more easily if built and published versions of the compiler including unreleased features are available at all times. The result would be a smoother transition process for them and more early feedback for us; a win-win.

With the above points in mind, the following proposal aims to:
* save our release managers time
* improve the health of our infrastructure and processes
* make user experimentation and early migration easier

If the above goals are in conflict with any aspect of the proposal, it is due to my ignorance, and the proposal should be amended.

## Proposal

At the highest level, this proposal amounts to:
* For every build, enforce consistency between the various files that store version numbers (fail the build if `purescript.cabal`, `app/Version.hs`, and `npm-package/package.json` disagree).
* For every push-to-branch build where the version number in the code matches a released version of PureScript:
  * Perform an appropriate version bump (in `purescript.cabal`, `app/Version.hs`, and both occurrences in `npm-package/package.json`) prior to the build
  * Assuming the build is otherwise successful...
  * Produce release bundles
  * Create a GitHub prerelease and tag with the bundles, but no release notes
  * Publish the npm package to the `next` tag, using a token that we add to GitHub's secrets storage for this repository
* Do not make any changes to bumping or publishing on PR builds or release builds (#4295 already covers manually updating the `next` tag after a full release)
* Do not make any automated publications of PureScript to Hackage

I assume that for full releases, we still want a human making an explicit version bump PR, having other humans approve it, and then manually creating a GitHub release for that version. This is the reason for the ‘matches a released version of PureScript’ clause; the intended effect is for a version bump commit to pause the continuous deployment process until a manual release is created. (People with experience actually doing releases: is this the right amount of conservative to save you time?)

### Version naming

‘Appropriate version bump’ merits some detailed consideration. PureScript exists at the uncomfortable junction between what npm expects from a version number (SemVer, [mostly](https://github.com/npm/cli/issues/4257)) and what Cabal expects from a version number (PVP, [mostly](https://github.com/haskell/cabal/issues/890)). Notably, the former allows prerelease suffixes in version numbers while the latter does not. As part of this proposal, I aim to resolve this mismatch and codify the resolution.

Full release version numbers shall use the MAJOR.MINOR.PATCH format, which is allowed by both npm and Cabal. Prerelease numbers shall use the MAJOR.MINOR.PATCH-[PHASE.]BUILD format, which is allowed by npm but not by Cabal. (PHASE stands for an optional `alpha`, `beta`, `rc`, or equivalent tag.) Consequently, `purescript.cabal` will always use MAJOR.MINOR.PATCH for PureScript's version, and any prerelease suffix will need to be bumped in `app/Version.hs`. None of these values should change in Git until it's time to cut a manual release or manually name a prerelease phase.

With that in mind, here's what the automated version bump should do at various points in compiler development:

|Committed version in purescript.cabal|Committed prerelease suffix in Version.hs|Committed version in package.json|Recent Git tags|Breaking changes in CHANGELOG.d|Version used in CD|
|---|---|---|---|---|---|
|0.15.0| — |0.15.0|0.15.0| |0.15.1-0|
|0.15.0| — |0.15.0|0.15.0, 0.15.1-0| |0.15.1-1|
|0.15.0| — |0.15.0|0.15.0, 0.15.1-1| |0.15.1-2|
| *version bump PR is merged* |
|0.15.1| — |0.15.1|0.15.0, 0.15.1-2| | — |
| *0.15.1 release is published* |
|0.15.1| — |0.15.1|0.15.1| |0.15.2-0|
|0.15.1| — |0.15.1|0.15.1, 0.15.2-0| |0.15.2-1|
|0.15.1| — |0.15.1|0.15.1, 0.15.2-1|breaking|0.16.0-0|
|0.15.1| — |0.15.1|0.15.1, 0.15.2-1, 0.16.0-0|breaking|0.16.0-1|
|0.15.1| — |0.15.1|0.15.1, 0.15.2-1, 0.16.0-1|breaking|0.16.0-2|
| *breaking change is reverted* |
|0.15.1| — |0.15.1|0.15.1, 0.15.2-1, 0.16.0-2| |0.15.2-2|
| *version bump PR is merged* |
|0.15.2| — |0.15.2|0.15.1, 0.16.0-2, 0.15.2-2| | — |
| *0.15.2 release is published* |
|0.15.2| — |0.15.2|0.16.0-2, 0.15.2| | 0.15.3-0 |
| *breaking change is re-added* |
|0.15.2| — |0.15.2|0.16.0-2, 0.15.2, 0.15.3-0|breaking|0.16.0-3|
|0.15.2| — |0.15.2|0.15.2, 0.16.0-3|breaking|0.16.0-4|
| *we decide to designate an alpha prerelease of 0.16 with a PR* |
|0.16.0|-alpha.0|0.16.0-alpha.0|0.15.2, 0.16.0-4|breaking|0.16.0-alpha.0|
|0.16.0|-alpha.0|0.16.0-alpha.0|0.15.2, 0.16.0-alpha.0|breaking|0.16.0-alpha.1|
| *version bump PR (really, a suffix-removing PR) is merged* |
|0.16.0| — |0.16.0|0.15.2, 0.16.0-alpha.1| | — |
| *0.16.0 release is published* |
|0.16.0| — |0.16.0|0.16.0| |0.16.1-0|

As this table suggests, the version bumping algorithm needs as inputs:
* the current version number committed to Git
* the git tags that have been used already
* whether any breaking changes have been merged

The proposed algorithm is as follows:
```
if current version contains a prerelease suffix
then
  if any Git tags match the current version except for the build number
  then
    take the largest such tag, increment its build number, and use that
  else
    use the current version as-is
else (current version does not contain a prerelease suffix)
  if current version appears in Git tags
  then
    if any breaking changes
    then
      increment minor number of current version (would be major if we were out of 0.x)
      set patch/prerelease to 0-0
    else
      increment patch number of current version
      set prerelease to -0
    if any Git tags match that version except for the build number
    then
      take the largest such tag, increment its build number, and use that
    else
      use that version as-is
  else (current version does not appear in Git tags)
    do not alter the code and do not publish an automated release
    (we are between the merging of a version bump PR and the corresponding manual release)
```

When the above algorithm produces a new version to use for a build, the MAJOR.MINOR.PATCH part of the number is used in `purescript.cabal`, the prerelease suffix is used in `app/Version.hs`, and both parts are used in `npm-package/package.json`.

Note the following features:
* Automatically-published builds always use a prerelease suffix.
* According to SemVer and npm, unnamed prerelease versions (0.16.0-2) sort before named prereleases (0.16.0-alpha.0), so we can use named prereleases as intermediate between early automated releases and full releases.
* The algorithm accounts for temporarily out-of-version-order prereleases, such as the 0.15.2-1 -> 0.16.0-0 -> ... -> 0.15.2-2 -> ... -> 0.16.0-3 sequence in the example. Early adopters might experience some churn this way but at least no version number will be reused.

### Infrastructure

To achieve this, someone with the appropriate credentials will need to generate an [npm automation token](https://docs.npmjs.com/creating-and-viewing-access-tokens), either for their personal account or for a new account that is made a PureScript collaborator in npm, and then add it to the [environment secrets](https://github.com/purescript/purescript/settings/secrets/actions) for this repository.

### Storage uncertainty

Storing a large number of artifact-laden prereleases in GitHub may run up against some sort of quota, now or in the future. (I have no indication of what that quota would be; it would just surprise me if we were given unbounded storage for large binary blobs.) We may need to extend this proposal with a plan to clean up automated prereleases that are older than some appropriate window. This would impact npm consumers as well, since the npm package is really just a thin shim that downloads binaries from GitHub.

**Comment by JordanMartinez** [comment]
First, this is really clear and accounts for edge cases. Thank you!

> either for their personal account or for a new account that is made a PureScript collaborator in npm

Since npm tokens work for the account, I think a new account should be made specifically for this purpose. 

> the intended effect is for a version bump commit to pause the continuous deployment process until a manual release is created. (People with experience actually doing releases: is this the right amount of conservative to save you time?)

Typically, I've been the one making releases since Harry stepped down. I think this works fine. We can always adjust if needed later.

**Comment by rhendric** [comment]
Any objections to me posting a little Discourse announcement about this, announcing the availability of the `@next` tag, emphasizing that it is unstable, subject to reversion, and that prerelease versions aren't guaranteed to be available forever, but otherwise is a resource for anyone who wants to sample from the bleeding edge?

**Comment by JordanMartinez** [comment]
Go for it! I was thinking of asking if you wanted to write that up. Kind of defeats the purpose of CD if no one knows to try it out.
