### ISSUE TITLE
Wildcard inferred type warning occurs in more contexts than before

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4308]
## Description

As reported in the Discord server by `fsoikin`, the "Wildcard type definition has the inferred type..." warning is now printed in contexts in which it didn't print in `0.14.x`.

## To Reproduce

```purs
f :: Int
f = (\(y :: _ {- compiler warning here is unexpected -}) -> y) 42

g :: _ {- compiler warning here is ok and expected -}
g = do
  binding :: _ {- compiler warning here is unexpected -} <- pure 1
  pure unit
```

## Expected behavior

The warning should not occur

## Additional context

Probably caused by https://github.com/purescript/purescript/pull/4269/files#diff-3c45800519d3f683b65e8801ff344ac24c233efd04bf5809a3ccb4699d353458R26-R30

## PureScript version

0.15.0

**Comment by fsoikin** [comment]
I think in `g` we should get a warning, on the very first line `g :: _`. 
But not on the third line `binding :: ...`

**Comment by fsoikin** [comment]
Hmmm, actually, it's a bit more nuanced: the intent of #4269 was to remove these warnings _only under fully-typed top-level declarations_. Which means that in `g` both warnings should be expected.
