### ISSUE TITLE
Bundling error for /\ instances

### ISSUE THREAD

**Issue by easafe** [purescript/purescript#4310]
Hello! This problem happens to me since upgrading to the new compiler version. I have reduced the code to the bare minimum that still prompts the issue.

## Description

Class instances for ```Data.Tuple.Nested./\``` fail at runtime (```is not a function``` if there are other instances, ```undefined``` if ```/\``` is the only instance)

## To Reproduce

Clone https://github.com/easafe/test and run ```spago test```

Note:

* The error only occur if the class instance is declared in a separated file 
* The error does not occur if the instance is named, or ```Tuple``` is used

## PureScript version

0.15.0

**Comment by rhendric** [comment]
Can confirm, issue is caused because the instance is named `test$div$bslash` in its file but referred to as `Test["test/\\"]` in the usage file.

**Comment by natefaubion** [comment]
Should the instance namer eliminate operator aliases first? What changed in 0.15 to affect this vs when it was implemented?

**Comment by rhendric** [comment]
Not sure yet, but something we changed (possibly me) related to names in the ES modules work is the most likely culprit.

**Comment by rhendric** [comment]
Yup, the issue was that the mangling inserted in https://github.com/purescript/purescript/pull/4232/files#diff-cb52c59a38e5742bbe2204955c4d8bb67b8d36e1872cab336dafa8162090cdb1R255 isn't comprehensive enough. PR inbound.
