### ISSUE TITLE
Hoisted CoreFn definitions are inconsistently qualified

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#4363]
## Description

0.15.3 introduced expression hoisting in CoreFn for synthetic applications. The top-level hoisted definitions are referenced unqualified. This is inconsistent with other user-written top-level definitions, which are always referenced fully qualified in CoreFn, regardless of whether they are exported.

## Expected behavior

I would expect top-level definitions to be referenced uniformly, either always unqualified, or always fully qualified. Having some top-level definitions referenced qualified and some unqualified is confusing. I would prefer qualified.

## PureScript version

0.15.4

**Comment by rhendric** [comment]
Agreed, I'll look into it.
