### ISSUE TITLE
Remove base-compat as a dependency

### ISSUE THREAD

**Issue by PureFunctor** [purescript/purescript#4377]
## Summary

If I understand correctly, `base-compat` was originally introduced as it was possible to compile PureScript over a range of GHC versions. More specifically, it gets rid of the CPP directives needed to get the compiler to build with both GHC 7.x and 8.x (#1610); currently though, we only build the compiler using 9.2.3 and a specific version of the package set, effectively nullfying `base-compat`'s use case.

Are there any other implications that this change would entail?

**Comment by JordanMartinez** [comment]
I wouldn't know. If there aren't any other implications, then this change should be made.

**Comment by PureFunctor** [comment]
I guess one thing to consider is cleaning up imports now that we'll be using `Protolude` everywhere. There's also some code that'd have to be changed but I don't think it's necessarily drastic.

**Comment by JordanMartinez** [comment]
> There's also some code that'd have to be changed but I don't think it's necessarily drastic.

Which code is that?

**Comment by PureFunctor** [comment]
`Protolude` defines some functions differently, like `show`, so some usages of it need a type annotation to build like the following: https://github.com/purescript/purescript/blob/0b5a87e08f77ce90884a8696f15ef87d725879c9/src/Language/PureScript/Bundle.hs#L114-L119

`Protolude` also re-exports a lot more stuff by default so some modules would complain about redundant imports as well.
