### ISSUE TITLE
Improve error spans for class and instance declarations

### ISSUE THREAD

**Issue by PureFunctor** [purescript/purescript#4382]
## Proposal

Given the following code:
```purs
module Main where

class A a <= B a where
  b :: a -> a
  
instance A a where
  a _ = a
```

The compiler throws the following errors:
```purs
[1 of 1] Compiling Main
[1/2 UnknownName] /Users/jgarcia/Temporary/tmp/Main.purs:3:1

     v
  3  class A a <= B a where
  4    b :: a -> a
                 ^
  
  Unknown type class A

[2/2 UnknownName] /Users/jgarcia/Temporary/tmp/Main.purs:6:1

     v
  6  instance A a where
  7    a _ = a
             ^
  
  Unknown type class A
```

Ideally, the error span should point to `A` in both cases, instead of the entire declaration.

**Comment by PureFunctor** [comment]
Would it be possible to have extra information for the `Constraint` type? Ideally, it'd be nice to have the `SourcePos` for where the class name starts. We can then just print the qualified name and interpolate the length from there.

**Comment by nwolverson** [comment]
I looked into this before, as the span leads to a bad suggestion from the language server (interpreting the bad name as starting `instance` etc) but stopped short when it became clear it was a non-local change.
