### ISSUE TITLE
Bump hlint to v3.x

### ISSUE THREAD

**Issue by PureFunctor** [purescript/purescript#4385]
## Summary

`hlint` was initially introduced back in 2020 by #3816, and its version (`2.2.11`) has remained largely the same for the past 2 years. Over time, more hints were added to `hlint` and it was not immediately apparent at the developer side as CI was running on an older version. I don't really think there's any harm in keeping it pinned for extended periods of time, but it'd be nice to catch up every couple of years or so.

## Motivation

Updating to a more recent version would catch hints that have never been hit before, which would also elide the extraneous hints given by `haskell-language-server` once the codebase is updated.

**Comment by rhendric** [comment]
Another reason to bump is that our current version of HLint can't parse files at all if they use some newer GHC features (I just encountered this with type applications in patterns).
