### ISSUE TITLE
`derive newtype` uses the wrong superclass dictionaries

### ISSUE THREAD

**Issue by JaSpa** [purescript/purescript#4387]
## Description

When a typeclass with superclass constraints (e.g. `Monoid`) is derived using `derive newtype` superclasses are not handled correctly.

## To Reproduce

```purescript
module M where

import Prelude

newtype T = T String

-- We derive the Monoid instance via newtype
derive newtype instance Monoid T

-- But define our own Semigroup instance
instance Semigroup T where
  append (T x) (T y) = T $ x <> "!!" <> y

-- These two functions exist to request
--   a) a `Semigroup a` dictionary and extract `append` from there
--   b) a `Monoid a` dictionary and extract `append` from the superclass's dictionary
viaSemigroup :: forall a. Semigroup a => a -> a -> a
viaSemigroup = append
viaMonoid :: forall a. Monoid a => a -> a -> a
viaMonoid = append

-- Wrap two strings in `T` and call
--   a) viaSemigroup
--   b) viaMonoid
test :: { viaSemigroup :: String, viaMonoid :: String }
test = { viaSemigroup: a, viaMonoid: b }
  where
    T a = viaSemigroup (T "abc") (T "xyz")
    T b = viaMonoid    (T "abc") (T "xyz")
```

Running `test` results in:

```js
{ viaSemigroup: "abc!!xyz", viaMonoid: "abcxyz" }
```

## Expected behavior

The values returned for `viaSemigroup` and `viaMonoid` should be the same. More specifically: the `Semigroup T` dictionary should be no different than the superclass dictionary carried in `Monoid T`.

## Additional context

Note that in the generated JS the `Monoid T` dictionary is defined as

```js
var monoidT = Data_Monoid.monoidString;
```

It just reuses the `Monoid String` dictionary. Correctness would require an overwrite of the superclass dictionary at `monoidT.Semigroup0`.

## PureScript version

0.15.4

**Comment by natefaubion** [comment]
I think this is supposed to be a compiler error? Shouldn't we be rejecting derive newtype if the superclasses aren't also derived?

**Comment by MonoidMusician** [comment]
Yeah I already wrote this up in #3168. I can return to my patch there, it came up during the foldable/traversable PR (#4371) discussion so I probably want to wait for that to land first.

**Comment by natefaubion** [comment]
Closing in favor of #3168
