### ISSUE TITLE
Local (Hoisted) CoreFn definitions are inconsistently qualified 

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#4400]
## Description

It seems that in fixing #4363, #4364 has over-qualified, such that non-top-level floated expressions are also qualified. This is a change to the previous behaviour where local bindings were always referenced unqualified.

This has no effect on the JS backend, as references to bindings in the same module are already unqualified with the same form, but is breaking for at least purerl.

## To Reproduce

A local function binding which has a constraint:
```purescript
module A where
fnBreaking = 
  let
    g :: forall a. Eq a => a -> a 
    g n = n
  in 
    [ g 1, g 2]
```
appears like this at the call site `g`:
```json
                  "type": "Var",
                  "value": {
                    "identifier": "g1",
                    "moduleName": [
                      "A"
                    ]
                  }
```
(the application of the Eq typeclass dictionary is split into a separate *local* binding `g1`). While a similar local binding without a constraint:
```purescript
fnOk = 
  let
    g :: forall a. a -> a
    g n = n
  in 
    [ g 1, g 2]
```
appears like this at point of use:
```json
                  "type": "Var",
                  "value": {
                    "identifier": "g",
                    "sourcePos": [
                      14,
                      5
                    ]
                  }
```

## Expected behavior

Locally bound identifiers in CoreFn are have a consistent qualification, specifically they remain unqualified as they were previously.

(I would propose a corollory to nate's "All top-level identifiers are fully qualified" with "All non-top-level identifiers are not qualified")

## PureScript version

Issue introduced in 0.15.5

**Comment by rhendric** [comment]
Oh, I see! Somehow I had gotten into my head the idea that ‘top-level’ meant outside of any enclosing `Abs`s, and I went and explicitly included let-bindings at the module level in the set of things to be qualified. That doesn't seem to be what Nate asked for, and I don't know why I thought it was the right thing to do; I think I can revert a large chunk of #4364 and that'll fix it.
