### ISSUE TITLE
Change error message of custom errors

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript#4417]
## Summary

Change: "A custom type error occurred while solving type class constraints" to "Custom error:"

## Motivation

Check [here](https://discourse.purescript.org/t/get-rid-of-a-custom-type-error-occurred-while-solving-type-class-constraints/3215)

**Comment by MonoidMusician** [comment]
Relevant parts of the code:
https://github.com/purescript/purescript/blob/7f72c6939d564c24c2a0c075401af65748a93e17/src/Language/PureScript/Errors.hs#L886-L889

https://github.com/purescript/purescript/blob/7f72c6939d564c24c2a0c075401af65748a93e17/src/Language/PureScript/Errors.hs#L1263-L1267

**Comment by i-am-the-slime** [comment]
+ a few tests, right?
