### ISSUE TITLE
Strange behavior regarding Markdown section headings

### ISSUE THREAD

**Issue by dunnl** [purescript/purescript#4423]
## Description

In generated documentation, the first declaration or definition appearing immediately under a Markdown section heading is (always?) displayed above that heading, while its associated documentation lines are displayed under the heading. This only applies to the first declaration/definition, while later ones are displayed under the heading as you would expect.

This issue is similar to #2525, except I think this issue constitutes a (maybe straightforward) bug, while the referenced issue is about overhauling the documentation system to behave more like Haddock in general.

## To Reproduce

Consider the following:

```
module Test where

import Prelude (Unit)
import Data.Pair
import Data.Tuple
import Data.List

-- | # Level one heading
-- | This is some text directly under the heading.

-- | This line is meant to document `Silly`, but it will be merged
-- | with the previous line, while `Silly` will be lifted over the
-- | heading. This is a little baffling in my opinion.
type Silly = Pair Unit

-- | This content will be attached to `Sillier`, which makes sense.
type Sillier = Tuple Unit Unit

-- | This content will be attached to `Silliest`, which makes sense.
type Silliest = List Unit

-- | ## Level two heading
-- | This is some text directly under the level two heading.

-- | Just like before, this line is meant to document `bignum`, but
-- | instead it will be merged with the previous line, while `bignum`
-- | will be lifted over the heading.
bignum :: Int
bignum = 3

-- | This content will be attached to `biggernum`, which makes sense.
biggernum :: Int
biggernum = 4

-- | This content will be attached to `biggestnum`, which makes sense.
biggestnum :: Int
biggestnum = 5
```

This gives the following output:
<pre>
#### `Silly`

``` purescript
type Silly = Pair Unit
```

# Level one heading
This is some text directly under the heading.
This line is meant to document `Silly`, but it will be merged
with the previous line, while `Silly` will be lifted over the
heading. This is a little baffling in my opinion.

#### `Sillier`

``` purescript
type Sillier = Tuple Unit Unit
```

This content will be attached to `Sillier`, which makes sense.

#### `Silliest`

``` purescript
type Silliest = List Unit
```

This content will be attached to `Silliest`, which makes sense.

#### `bignum`

``` purescript
bignum :: Int
```

## Level two heading
This is some text directly under the level two heading.
Just like before, this line is meant to document `bignum`, but
instead it will be merged with the previous line, while `bignum`
will be lifted over the heading.

#### `biggernum`

``` purescript
biggernum :: Int
```

This content will be attached to `biggernum`, which makes sense.

#### `biggestnum`

``` purescript
biggestnum :: Int
```

This content will be attached to `biggestnum`, which makes sense.
</pre>

## Expected behavior

The first line should be displayed under the heading, just like all of the others are.

<pre>
## Module Test

# Level one heading
This is some text directly under the heading.

#### `Silly`

``` purescript
type Silly = Pair Unit
```
This line is meant to document `Silly`, but it will be merged
with the previous line, while `Silly` will be lifted over the
heading. This is a little baffling in my opinion.

#### `Sillier`

``` purescript
type Sillier = Tuple Unit Unit
```

This content will be attached to `Sillier`, which makes sense.

#### `Silliest`

``` purescript
type Silliest = List Unit
```

This content will be attached to `Silliest`, which makes sense.

## Level two heading
This is some text directly under the level two heading.

#### `bignum`

``` purescript
bignum :: Int
```

Just like before, this line is meant to document `bignum`, but
instead it will be merged with the previous line, while `bignum`
will be lifted over the heading.

#### `biggernum`

``` purescript
biggernum :: Int
```

This content will be attached to `biggernum`, which makes sense.

#### `biggestnum`

``` purescript
biggestnum :: Int
```

This content will be attached to `biggestnum`, which makes sense.
</pre>

## Additional context

N/A

## PureScript version

```
purs --version
0.15.2
```

**Comment by rhendric** [comment]
I think this is exactly #2525, without which `purs` isn't distinguishing between doc comments containing `#` headers and other sorts of doc comments. Absent that, the consistent rule that `purs` is applying is that all doc comments preceding a declaration in the source text are ‘associated with’ (meaning, rendered below) the declaration in the generated file.

**Comment by dunnl** [comment]
>all doc comments preceding a declaration in the source text are ‘associated with’ (meaning, rendered below) the declaration in the generated file.

Ah, I think I see now this is a consistent rule and not some kind of off-by-one error. Gotcha.
