### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Tridu33** [purescript/purescript#4424]
## Description

"""bash
[root@VM-12-13-centos ~]# npm install -g purescript spago purs-tidy bower pulp
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
/usr/local/bin/pulp -> /usr/local/lib/node_modules/pulp/index.js
/usr/local/bin/purs -> /usr/local/lib/node_modules/purescript/purs.bin
/usr/local/bin/purs-tidy -> /usr/local/lib/node_modules/purs-tidy/bin/index.js
/usr/local/bin/spago -> /usr/local/lib/node_modules/spago/spago

> purescript@0.15.6 postinstall /usr/local/lib/node_modules/purescript
> install-purescript --purs-ver=0.15.6

/usr/local/lib/node_modules/purescript/node_modules/@npmcli/fs/lib/fs.js:6
const fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>
                      ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/purescript/node_modules/@npmcli/fs/lib/fs.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/purescript/node_modules/@npmcli/fs/lib/index.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm WARN notsup Unsupported engine for purescript-installer@0.3.1: wanted: {"node":">=12"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: purescript-installer@0.3.1
npm WARN notsup Unsupported engine for make-fetch-happen@10.2.1: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: make-fetch-happen@10.2.1
npm WARN notsup Unsupported engine for cacache@16.1.3: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: cacache@16.1.3
npm WARN notsup Unsupported engine for lru-cache@7.14.1: wanted: {"node":">=12"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: lru-cache@7.14.1
npm WARN notsup Unsupported engine for minipass-fetch@2.1.2: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: minipass-fetch@2.1.2
npm WARN notsup Unsupported engine for ssri@9.0.1: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: ssri@9.0.1
npm WARN notsup Unsupported engine for glob@8.0.3: wanted: {"node":">=12"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: glob@8.0.3
npm WARN notsup Unsupported engine for unique-filename@2.0.1: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: unique-filename@2.0.1
npm WARN notsup Unsupported engine for @npmcli/move-file@2.0.1: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: @npmcli/move-file@2.0.1
npm WARN notsup Unsupported engine for @npmcli/fs@2.1.2: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: @npmcli/fs@2.1.2
npm WARN notsup Unsupported engine for unique-slug@3.0.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: unique-slug@3.0.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.15.6 postinstall: `install-purescript --purs-ver=0.15.6`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.15.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-05T12_57_07_129Z-debug.log
"""
 
## PureScript version
"""bash
[root@VM-12-13-centos stack]# npm -v
6.14.10
[root@VM-12-13-centos stack]# node -v
v10.23.1
[root@VM-12-13-centos stack]# uname -a
Linux VM-12-13-centos 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
"""

**Comment by garyb** [comment]
That's due to the version of node being used - it's really old! The v10.x series was EOL'd in 2016. v16 is the current LTS version, and v18 the current standard version.

**Comment by JordanMartinez** [comment]
Should this be closed then?

**Comment by rhendric** [comment]
Yeah, let's.
