### ISSUE TITLE
Emojis cannot be used as a record label in type signatures

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4430]
## Description

Using an emoji as a record label in a type signature produces a compiler error. :smile: 

## To Reproduce

[Try PS](https://try.purescript.org/?code=FAWw9gJgrgNgpgAgLIEMCWA7BB3AFnAJzmGDRAAcwCAXBABSJigmNIqtoFEAzbuAY1oAKHn0EBKEtioBrAM4IAXIoQBlagUwBzYNILyEAXgQBvBACJAvBuAwPfNKLANxRM4dgL4A6K7ZKY%2BBOQAxTERlBAB9Ugx-IJCjUwsbOxVzJxd3BEys7JzMkwBaBBIAdTQYCH4UAggEagBPckQWbkw0ajQwLFwUBWp8BD9CIhr6xpJss29klXVNDB1st1zlldW1rPy3EjhwACs0AGk4OoA1ZyhQlUmkpRS0i-dgHbB9o9PzxGNr23tUj4z1hN8sBMgBhMCwGoYMC0EAoaj8XAIGSYCDjLKqOogABGYBg6OwbSRKIwaJBWQAKg1WLpcGVEIiBCStLVurRRoghIkfmE-ulyYD1pJMt0FCSagAlMDYBBUsZ4ekDaJDbSsxDihBgbgJKa3Rz-AWCwFbTAIe5NAQwKrwjpYZ6vY5nFyCzYkOGmsKiAS0ACqGDaoHQWGM5CgRAQUH91CAA)

```purs

module Main where

import Prelude

import Effect (Effect)

works :: String
works = { "😆" : "value" }."😆"

infersFine :: _
infersFine = { "😆" : "value" }                 {- 

Wildcard type definition has the inferred type

    { "😆" :: String
    }                                           -}

emojiKeyValue :: { "😆" :: "value" }
emojiKeyValue = { "😆" : "value" }                {-
  Could not match kind

    Symbol

  with kind

    Type


while checking that type ( "😆" :: "value"
                         )
  has kind Row Type
while inferring the kind of { "😆" :: "value"
                            }
in value declaration emojiKeyValue             -}

main :: Effect Unit
main = pure unit
```

## Expected behavior

This should compile.

## PureScript version

`0.15.7`

**Comment by rhendric** [comment]
Once you replace `"value"` with `String` in the signature it works fine.

**Comment by JordanMartinez** [comment]
:man_facepalming:
