### ISSUE TITLE
AMD module support

### ISSUE THREAD

**Issue by epost** [purescript/purescript#444]
AMD module support would make it possible to use PureScript with [RequireJS](http://requirejs.org/), for example.

*jonesfh* on AMD module support on purescript's irc channel:
> i can't see it being too hard
> looks like you'd need to add another constructor and handle it here:https://github.com/purescript/purescript-in-purescript/blob/8f13199b6f45cd3c34619841b13153931e094bc8/src/Language/PureScript/CodeGen/JS.purs#L38-L64
> then give a frontend to it like Make
> i think it could be another option for psc-make maybe

There's also a suggestion from *paf31* in this [reddit discussion](http://www.reddit.com/r/purescript/comments/250c58/amd_modules_and_purescript/)

**Comment by AppShipIt** [comment]
Close as working and AMD seems to be eclipsed by [EcmaScript modules](http://www.2ality.com/2013/07/es6-modules.html)?

**Comment by garyb** [comment]
Yeah, I don't think AMD is ever going to happen now :)
