### ISSUE TITLE
Broken PolyKinds for typeclass instances

### ISSUE THREAD

**Issue by SeungheonOh** [purescript/purescript#4440]
## Description
Typeclass does not allow polykinds

## To Reproduce

```purs
class Test :: forall k. k -> Constraint
class Test a where
  test :: Proxy a -> String

instance (IsSymbol a) => Test a where
  test _ = "hello"

else instance Test a where
  test _ = "world"
```

```purs
test (Proxy :: Proxy "hello") -- => "hello"
test (Proxy :: Proxy Int) 
{-
  Could not match kind
          
    Symbol
          
  with kind
        
    Type
...
-}
```

## Expected behavior

```purs
test (Proxy :: Proxy "hello") -- => "hello"
test (Proxy :: Proxy Int) -- => "world"
```

## Additional context
In Haskell,
```hs
import Data.Proxy
import GHC.TypeLits

class Test a where
  test :: Proxy a -> String

instance (KnownSymbol a) => Test a where
  test = symbolVal

instance Test Int where test _ = "Int"
```

```hs
test (Proxy @"hello") -- => "hello"
test (Proxy @Int) -- => "Int"
```

## PureScript version

0.14.9

**Comment by garyb** [comment]
I think this is more to do with the instance chain - it won't choose an instance based on constraints, only types.

There perhaps should be some kind of warning or error about the fact that it's going to happen though due to the overlap.

**Comment by SeungheonOh** [comment]
Shouldn't is check the next instance if the constraint fails. As haskell does it?

**Comment by rhendric** [comment]
No, the (working) equivalent of the Haskell snippet you posted is:

```purs
instance Test Int where
  test _ = "Int"

else instance (IsSymbol a) => Test a where
  test = reflectSymbol
```

Neither PureScript nor Haskell use the constraints to choose the instance.

**Comment by garyb** [comment]
I wasn't sure if I was remembering correctly, but seems we do indeed have an issue about the feature: https://github.com/purescript/purescript/issues/3120

**Comment by SeungheonOh** [comment]
> No, the (working) equivalent of the Haskell snippet you posted is:
> 
> ```purescript
> instance Test Int where
>   test _ = "Int"
> 
> else instance (IsSymbol a) => Test a where
>   test = reflectSymbol
> ```
> 
> Neither PureScript nor Haskell use the constraints to choose the instance.

Thank you. 

Besides, is there a way to add a chain instance from other modules?

**Comment by rhendric** [comment]
While you can't, as you've discovered, spread instance chains across multiple modules, and you also can't control instance selection through constraints, those may not be necessary to get what you want.

For example, another way of handling the case you posted is by parameterizing your class on kind as well as type. If you do this, the example doesn't need instance chains, and you might be able to get away with isolated instances in multiple modules.

```purs
class Test :: forall k. Type -> k -> Constraint
class Test k a where
  test' :: Proxy k -> Proxy a -> String

-- The compiler is now explicitly comparing `Symbol` versus `Type` to determine
-- which instance to select, so chains aren't needed.
instance IsSymbol s => Test Symbol s where
  test' _ = reflectSymbol

instance Test Type a where
  test' _ _ = "world"

test :: forall k (a :: k). Test k a => Proxy a -> String
test = test' (Proxy :: _ k)

test (Proxy :: Proxy "hello") -- => "hello"
test (Proxy :: Proxy Int) -- => "world"
```

Whether this particular trick is enough depends on your full application, but the general advice that this is an instance of is to give classes more parameters to match on and make those parameters types that the compiler can easily determine, possibly via helper functions or auxiliary classes.

**Comment by SeungheonOh** [comment]
Thank you for suggestion. Actually, I need instances like this:
```purs
else instance (Test k a, Test l b) => Test k (a b) where
  test' _ _ =
    test' (Proxy :: Proxy k) (Proxy :: Proxy a)
    <> "#"
    <> test' (Proxy :: Proxy l) (Proxy :: Proxy b)
```

which I don't think will do the trick. I settled with having `SProxy :: Symbol -> Type` for this, though it looks bat.

**Comment by rhendric** [comment]
From just that snippet, it's hard for me to guess what exactly you're going for, but the trick can indeed be generalized to compound types with a little extra infrastructure:

```purs
instance (Test (k -> k1 -> k2) a, Test k b) => Test (k1 -> k2) (a ((b) :: k)) where
  test' _ _ =
    test' (Proxy :: _ (k -> k1 -> k2)) (Proxy :: _ a)
    <> "#"
    <> test' (Proxy :: _ k) (Proxy :: _ b)

instance (Test (k -> Type) a, Test k b) => Test Type (a ((b) :: k)) where
  test' _ _ =
    test' (Proxy :: _ (k -> Type)) (Proxy :: _ a)
    <> "#"
    <> test' (Proxy :: _ k) (Proxy :: _ b)
else instance Test Type a where
  test' _ _ = "world"

instance IsSymbol s => Test Symbol s where
  test' _ = reflectSymbol
  
instance Test (Type -> Type) Array where
  test' _ _ = "Array"

test :: forall k (a :: k). Test k a => Proxy a -> String
test = test' (Proxy :: _ k)



foreign import data Mystery :: forall k. k -> Type

instance Test (k -> Type) Mystery where
  test' _ _ = "Mystery"

foreign import data DeepMystery :: forall k. k -> k -> k -> Type

instance Test (k -> k -> k -> Type) DeepMystery where
  test' _ _ = "DeepMystery"


main :: Effect Unit
main = do
  log $ test (Proxy :: Proxy "hello")
  log $ test (Proxy :: Proxy Int)
  log $ test (Proxy :: Proxy (Array Int))
  log $ test (Proxy :: Proxy (Mystery Int))
  log $ test (Proxy :: Proxy (Mystery "nonsense"))
  log $ test (Proxy :: Proxy (DeepMystery "absurd" "stuff" "nonsense"))
```

If you're still having trouble, maybe link to something a little more complete?

**Comment by SeungheonOh** [comment]
It's for interfacing type annotation for a block chain scripts.

check https://github.com/mlabs-haskell/ply and https://github.com/mlabs-haskell/ply-ctl

Because number of type argument can be vary, I feel more comfortable with `SProxy` method, which can take arbitrary arguments.
