### ISSUE TITLE
Enable more keywords as record labels.

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4446]
## Description

Keywords like `type` and `class` aren't useable as record puns. The below code produces a parser error:
```purs
foo { class, bar } = { class }
```

## To Reproduce

Ideally, this file should compile fine rather than failing with a parser error:

<details>
<summary>The file</summary>

```purs
module Main where

import Prelude

import Effect.Console (log)

type KeywordRow =
  -- ( ado :: String -- parser error
  ( "ado" :: String -- ok
  , as :: String
  -- , case :: String -- parser error
  , "case" :: String -- ok
  , class :: String
  , data :: String
  , derive :: String
  -- , do :: String -- parser error
  , "do" :: String -- ok
  , else :: String
  , false :: String
  -- , forall :: String -- parser error
  -- , "forall" :: String -- ok
  , foreign :: String
  , hiding :: String
  , import :: String
  -- , if :: String -- parser error
  , "if" :: String -- ok
  , in :: String
  , infix :: String
  , infixl :: String
  , infixr :: String
  , instance :: String
  -- , let :: String
  , "let" :: String
  , module :: String
  , newtype :: String
  , nominal :: String
  , of :: String
  , phantom :: String
  , representational :: String
  , role :: String
  , then :: String
  , true :: String
  , type :: String
  -- , where :: String -- parser error
  , "where" :: String -- ok
  )

type KeywordRecord =
  -- { ado :: String -- I assume cannot use
  { "ado" :: String -- ok
  , as :: String
  -- , case :: String -- I assume we cannot use
  , "case" :: String -- ok
  , class :: String
  , data :: String
  , derive :: String
  -- , do :: String -- I assume we cannot use
  , "do" :: String -- ok
  , else :: String
  , false :: String
  -- , forall :: String -- I assume we cannot use
  -- , "forall" :: String -- ok
  , foreign :: String
  , hiding :: String
  , import :: String
  -- , if :: String -- I assume we cannot use
  , "if" :: String -- ok
  , in :: String
  , infix :: String
  , infixl :: String
  , infixr :: String
  , instance :: String
  -- , let :: String
  , "let" :: String
  , module :: String
  , newtype :: String
  , nominal :: String
  , of :: String
  , phantom :: String
  , representational :: String
  , role :: String
  , then :: String
  , true :: String
  , type :: String
  -- , where :: String -- I assume we cannot use
  , "where" :: String -- ok
  }

keywordUsage :: KeywordRecord -> KeywordRecord
keywordUsage
  -- { ado
  r@
  { as
  , class
  , data
  , derive
  , forall
  , foreign
  , hiding
  , import
  , infix
  , infixl
  , infixr
  , instance
  , module
  , newtype
  , nominal
  , phantom
  , representational
  , role
  , type
  } =
  { "ado": r.ado
  , as: as
  , case: r.case
  , class: class
  , data: data
  , derive: derive
  , "do": r.do
  , else: r.else
  , false: r.false
  , forall: r.forall
  , foreign: r.foreign
  , hiding: r.hiding
  , import: r.import
  , if: r.if
  , in: r.in
  , infix: r.infix
  , infixl: infixl
  , infixr: infixr
  , instance: instance
  , let: r.let
  , module: module
  , newtype: newtype
  , nominal: nominal
  , of: r.of
  , phantom: phantom
  , representational: representational
  , role: role
  , then: r.then
  , true: r.true
  , type: type
  , where: r.where
  }

keywordUpdate :: KeywordRecord -> KeywordRecord
keywordUpdate r = r
  { ado: r.ado <> "foo"
  , as: r.as <> "foo"
  , case: r.case <> "foo"
  , class: r.class <> "foo"
  , data: r.data <> "foo"
  , derive: r.derive <> "foo"
  , do: r.do <> "foo"
  , else: r.else <> "foo"
  , false: r.false <> "foo"
  , forall: r.forall <> "foo"
  , foreign: r.foreign <> "foo"
  , hiding: r.hiding <> "foo"
  , import: r.import <> "foo"
  , if: r.if <> "foo"
  , in: r.in <> "foo"
  , infix: r.infix <> "foo"
  , infixl: r.infixl <> "foo"
  , infixr: r.infixr <> "foo"
  , instance: r.instance <> "foo"
  , let: r.let <> "foo"
  , module: r.module <> "foo"
  , newtype: r.newtype <> "foo"
  , nominal: r.nominal <> "foo"
  , of: r.of <> "foo"
  , phantom: r.phantom <> "foo"
  , representational: r.representational <> "foo"
  , role: r.role <> "foo"
  , then: r.then <> "foo"
  , true: r.true <> "foo"
  , type: r.type <> "foo"
  , where: r.where <> "foo"
  }

main = log "Done"
```

</details>

## PureScript version

0.15.7

**Comment by JordanMartinez** [comment]
I had time today to look at this, and got this far in my analysis of the issue.

## The initial problem

Tracking down the initial issue led me to this code (or things like it) in `Parser.y`
```
  label {% fmap RecordPun . toName Ident $ lblTok $1 }
```

A `label` is first parsed (via `toLabel`), but then the `Label`'s token is extracted and re-parsed into an `Ident` using `toName`. The similarities below show why keywords fail to work:

```haskell
-- All labels are accepted
toLabel :: SourceToken -> Label
toLabel tok = case tokValue tok of
  TokLowerName [] a -> Label tok $ mkString a
  TokString _ a     -> Label tok a
  TokRawString a    -> Label tok $ mkString a
  TokForall ASCII   -> Label tok $ mkString "forall"
  _                 -> internalError $ "Invalid label: " <> show tok

-- Actually... only non-reserved names are accepted
toName :: (Text -> a) -> SourceToken -> Parser (Name a)
toName k tok = case tokValue tok of
  TokLowerName [] a
    | not (Set.member a reservedNames) -> pure $ Name tok (k a)

    -- Reserved names produce the ErrKeywordVar parser error
    | otherwise -> addFailure [tok] ErrKeywordVar $> Name tok (k "<unexpected>")

  TokString _ _ -> parseFail tok ErrQuotedPun
  TokRawString _ -> parseFail tok ErrQuotedPun
  TokUpperName [] a  -> pure $ Name tok (k a)
  TokSymbolName [] a -> pure $ Name tok (k a)
  TokOperator [] a   -> pure $ Name tok (k a)
  TokHole a          -> pure $ Name tok (k a)
  _                  -> internalError $ "Invalid name: " <> show tok

-- D'oh!
reservedNames :: Set Text
reservedNames = Set.fromList
  [ "ado"
  , "case"
  , "class"
  , "data"
  , "derive"
  , "do"
  , "else"
  , "false"
  , "forall"
  , "foreign"
  , "import"
  , "if"
  , "in"
  , "infix"
  , "infixl"
  , "infixr"
  , "instance"
  , "let"
  , "module"
  , "newtype"
  , "of"
  , "true"
  , "type"
  , "where"
  ]
```

## Attempt 1 at a solution

I thought the fix would be easy. Just reimplement `toName` but for include more keywords here. (I assumed that record puns for things like `ado` and other constructs that start an expression block would be problematic. I also don't use `ado` as a field name, so I'm not personally bothered by this limitation). Voila!

```diff
-label {% fmap RecordPun . toName Ident $ lblTok $1 }
+label {% fmap RecordPun . toLabelName Ident $ lblTok $1 }
```

```diff
{- unchanged -}
toLabel :: SourceToken -> Label
toLabel tok = case tokValue tok of
  TokLowerName [] a -> Label tok $ mkString a
  TokString _ a     -> Label tok a
  TokRawString a    -> Label tok $ mkString a
  TokForall ASCII   -> Label tok $ mkString "forall"
  _                 -> internalError $ "Invalid label: " <> show tok

{- Since `toLabel` only succeeds on the 4 tokens above,
   that's all we need to care about here. 
   `toName` still exists separate from `toLabelName`.
   Below, I'm just showing the changes I made to `toName`. -}
-toName :: (Text -> a) -> SourceToken -> Parser (Name a)
-toName k tok = case tokValue tok of
+toLabelName :: (Text -> a) -> SourceToken -> Parser (Name a)
+toLabelName k tok@(SourceToken{..}) = case tokValue of
  TokLowerName [] a
    | not (Set.member a reservedNames) -> pure $ Name tok (k a)
    | otherwise -> addFailure [tok] ErrKeywordVar $> Name tok (k "<unexpected>")
  TokString _ _ -> parseFail tok ErrQuotedPun
  TokRawString _ -> parseFail tok ErrQuotedPun
+  TokForall ASCII -> pure $ Name (SourceToken tokAnn $ TokLowerName [] "forall") (k "forall")
-  TokUpperName [] a  -> pure $ Name tok (k a)
-  TokSymbolName [] a -> pure $ Name tok (k a)
-  TokOperator [] a   -> pure $ Name tok (k a)
-  TokHole a          -> pure $ Name tok (k a)
  _                  -> internalError $ "Invalid name: " <> show tok

{- Since some keywords start expression blocks, I don't think it
   makes sense to allow record puns in those cases (e.g. ado, let, etc.)
   while others that can only appear in top-level contexts should be fine
   (e.g. data, class, derive, etc). -}
reservedLabelNames :: Set Text
reservedLabelNames = Set.fromList
  [ "ado"
  , "case"
-  , "class"
-  , "data"
-  , "derive"
  , "do"
  , "else"
  , "false"
-  , "forall"
-  , "foreign"
-  , "import"
  , "if"
  , "in"
-  , "infix"
-  , "infixl"
-  , "infixr"
-  , "instance"
  , "let"
-  , "module"
-  , "newtype"
  , "of"
  , "true"
-  , "type"
  , "where"
  ]
```

## Problem 2

Did it work? Nope! Instead, I get the below error:

```
Error found:
  at tests/purs/passing/KeywordsAsRecordLabels.purs:116:12 - 116:17 (line 116, column 12 - line 116, column 17)
  
    Unable to parse module:
    Unexpected token 'class'
  
  See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
  or to contribute content related to this error.
```

`Unexpected token 'X'` is printed via `basicTokenError` via `basicError`. `basicError` is used when either `ErrToken` or `ErrLexeme` is the error type. I added a String arg to see which of these errors called `basicError`. It is `ErrToken`. 

I searched for what triggered ErrToken...
- `checkNoForalls`
- `parserError`

I added more code to see which of these caused the issue:
- `checkNoForalls`
- `parserError` via `classHead` rule in `Parser.y`
- `parserError` via `token` in `Monad.hs`

Unfortunately, none of the above caused the issue. Another round of searching later and I realized that `parserError` is called whenever the parser itself fails: 
```
-- Parser.y
%error { parseError }
```

At this point, I'm not sure what's actually causing the error.

**Comment by rhendric** [comment]
I haven't looked into your specific problem, but remember that parsing is downstream of layout, and the layout algorithm detects several of these keywords and inserts layout tokens around them, which will confuse the parser.

**Comment by natefaubion** [comment]
I think this is intentional. You can’t use any keywords as bare identifiers. You can use them unquoted with . And in a record constructor context. However a pun results in a bare identifier which isn’t allowed.

**Comment by JordanMartinez** [comment]
I can see this for some constructs like `case` or `let`. But why `type` or `module`? 

For example, `module` only shows up in our syntax as the first keyword in a file to define a module. I can see `module` not being allowed as an identifier for top-level declarations. But why prevent it within expressions? Is it because this opens a can of worms in the parser where in some contexts the keyword is ok but not in others?

**Comment by natefaubion** [comment]
I guess you can ask the inverse. Why would you want a series of identifier rules dependent on their enclosing syntactic context? What advantage does this give you? Would it be easier for tooling and users to have a consistent rule that is not context dependent?

**Comment by rhendric** [comment]
(Also, maybe it's unfair to use my pet fantasy feature as a counterargument against someone else's, but [I'll be sad](https://github.com/purescript/purescript/pull/3897) if `type` becomes a valid identifier. Maybe this is illustrative of a general benefit of not further diverging the syntax between top-level and local contexts.)

**Comment by JordanMartinez** [comment]
> Why would you want a series of identifier rules dependent on their enclosing syntactic context? What advantage does this give you? Would it be easier for tooling and users to have a consistent rule that is not context dependent?

Fair point. But why then are `as` and `hiding` allowed as record puns? `hiding` likely doesn't matter because of how infrequently it is used. `as` could easily be typed by someone who is distinguishing between an element, `a`, and a list of element, `as`.

> maybe it's unfair to use my pet fantasy feature as a counterargument against someone else

I think that's a valid point. I'm assuming that a keyword that only appears in one particular context (topl-level declarations) today won't ever appear in other contexts in the future. Local type synonyms are one feature that could be implemented. Perhaps we'd implement other such local features (e.g. local modules, local infix notation, potentially local data declarations? etc.). Sacrificing all of that possibility just so I can write `{ type } = { type }` rather than `r = { type: r.type }` seems premature to me.

At the end of the day, I just wanted record puns for `type` and `module` because of how frequently it's used for `purescript-cst-parser`/`purescript-tidy-codegen`-related things. But having had this discussion, I agree that this isn't worth the complexity or confusion.
