### ISSUE TITLE
CI issue: `stack` not found in self-hosted Linux ARM runner

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4457]
## Description

See https://github.com/purescript/purescript/actions/runs/4506918233/jobs/7934206928#step:9:67

**Comment by f-f** [comment]
Feel free to tag me for things related to self-hosted runners, so I can see them immediately.
Having a look now..

**Comment by f-f** [comment]
This is now fixed - the runner somehow crashed. I'll close this one, and investigate more tomorrow morning how to make it more resilient.
