### ISSUE TITLE
`NewType` record field access

### ISSUE THREAD

**Issue by kylixalex** [purescript/purescript#4459]
## Summary

Change `NewType`d types encapsulating records' field access to be simpler. Instead of forcing a person trying to access the wrapped record fields to write `(unwrap wrappedRecord).field`, make it be `wrappedRecord.field`.

## Motivation

In codebases like the ones I work on, we often use wrapped record types where to access fields we're forced to use the `unwrap` notation presented above. When doing this once, twice or even three times it makes for okay code but anything more than this makes the code very "dirty".

## Proposal

For fields that are meant to be publicly accessible anyway, have the compiler make field access functions for each of the record fields in a wrapped record type.

## Examples

```
newtype WrappedRecord = WrappedRecord
  { field1 :: Int
  , field2 :: String
  }

derive instance Newtype WrappedRecord _

getField1 :: WrappedRecord -> Int
getField1 wrappedRecord = wrappedRecord.field1
```

instead of

```
newtype WrappedRecord = WrappedRecord
  { field1 :: Int
  , field2 :: String
  }

derive instance Newtype WrappedRecord _

getField1 :: WrappedRecord -> Int
getField1 wrappedRecord = (unwrap wrappedRecord).field1
```

**Comment by natefaubion** [comment]
This is a common request. The primary problem here is, what are the inferred types of these expression:

```purescript
foo a = a.wat
bar a = a { wat = 42 }
```

Currently, these have a principal type. No matter the context, the same thing is always inferred. If we want this to work with nominal types, we'd need to decide how to handle this. In my mind, there are a few options

* Define an typeclass that can let arbitrary types opt-in to record syntax. This would be similar to what recent GHC is doing for overloaded record fields (eg. `HasField`). The inferred types here would potentially be much more complicated and could be much less approachable for newcomers. Updates especially.
* Allow this to typecheck with anything that can `Coerce` to a record. Limited, but the type signature would at least be a little more straightforward than constraints for each field, though I think still more obtuse than existing signatures.
* Continue to infer the existing type, but support a coercion during checking/subsumption when we know that it's a newtype. This essentially means we give up on principal types for records. Is this a significant downside? It certainly makes explaining the rules for the syntax a little more tricky, but maybe it's worth the convenience. The level of convenience also depends on how good we are at propagating as much checking information as possible.

**Comment by kylixalex** [comment]
> This is a common request. The primary problem here is, what are the inferred types of these expression:
> 
> ```purescript
> foo a = a.wat
> bar a = a { wat = 42 }
> ```
> 
> Currently, these have a principal type. No matter the context, the same thing is always inferred. If we want this to work with nominal types, we'd need to decide how to handle this. In my mind, there are a few options:
> 
> * Define a typeclass that can let arbitrary types opt-in to record syntax. This would be similar to what recent GHC is doing for overloaded record fields (eg. `HasField`). The inferred types here would potentially be much more complicated and could be much less approachable for newcomers. Updates especially.
> * Allow this to typecheck with anything that can `Coerce` to a record. Limited, but the type signature would at least be a little more straightforward than constraints for each field, though I think still more obtuse than existing signatures.
> * Continue to infer the existing type, but support a coercion during checking/subsumption when we know that it's a newtype. This essentially means we give up on principal types for record syntax. Is this a significant downside? It certainly makes explaining the rules for the syntax a little more tricky, but maybe it's worth the convenience. The level of convenience also depends on how good we are at propagating as much checking information as possible.
> 
> I don't think any of these are slam dunks, unfortunately.

I understand, it's not as simple as it seems... Either way, I wouldn't give up on the first or last option as much as they have downsides of their own.
