### ISSUE TITLE
v0.15.9-x macos executables refer to v0.15.8-x

### ISSUE THREAD

**Issue by vapaj** [purescript/purescript#4460]
## Description

The macos executables of version 0.15.9 preview releases refer to version 0.15.8.

## To Reproduce

Download the macos binary from e.g. https://github.com/purescript/purescript/releases/tag/v0.15.9-3 and run

```
./purs --version
0.15.8-3
```

## PureScript version

Preview releases of 0.15.9

**Comment by rhendric** [comment]
:flush: Thanks for the report!

*grumbles something about differences between GNU sed and FreeBSD sed*
