### ISSUE TITLE
Failure to pattern match at runtime 

### ISSUE THREAD

**Issue by mshenton75** [purescript/purescript#4466]
## Description

```purescript
data Sound = Moo | Quack | Bark

type Animal = { sound :: Sound }

animalFunc ∷ Array Animal -> Unit
animalFunc animals
  | Just { sound } <- animals # Array.find \{ sound: Moo } -> true = unit
  | otherwise = unit
```
The above example compiles successfully, but throws an unhandled exception at runtime if you call the function with one of the `Sound` enum values not pattern matched in `animalFunc` (such as `Quack` or `Bark`).

## To Reproduce

Build and run the above example.

## Expected behavior

The build should fail because not all enum values are explicitly handled. 

## Additional context

Similar examples we found that also compiled successfully:

```purescript
animalFunc ∷ Animal -> Boolean
animalFunc animal
  | (\{ sound: Moo } -> true) $ animal = true
  | otherwise = false
```
```purescript
animalFunc ∷ Animal -> Boolean
animalFunc animal
  | (let { sound: Moo } = animal in true) = true
  | otherwise = false
````

## PureScript version

0.15.7

**Comment by purefunctor** [comment]
On its own, the expression:
```hs
\{ sound: Moo } -> true
```
infers to have a `Partial` constraint, which should bubble up to `animalFunc`. An alternative definition like this shows this expected behavior:
```hs
animalFunc' :: Partial => Array { sound :: Sound } -> Unit
animalFunc' animals =
  case animals # Array.find \{ sound: Moo } -> true of
    Just { sound } -> unit
    _ -> unit
```
