### ISSUE TITLE
Allow instance with Fail constraint without where

### ISSUE THREAD

**Issue by yaitskov** [purescript/purescript#4483]
## Summary

Allow class instance with Fail constraint without following `where` part.

## Motivation

Method of a class instance constrained with `Prim.TypeError.Fail` class could not be evaluated and software engineer need to write dead code. Defining stub return value for an unreachable method might be complicated. 

## Proposal

Make section `where` optional if Fail constraint is applied.

## Examples

```
import Prelude
import Prim.TypeError

class Foo t where
  foo :: t -> String

instance fooInt :: Fail (Text "") => Foo Int

```

**Comment by rhendric** [comment]
GHC's new `Unsatisfiable` built-in class, which performs roughly the same role, is [specified](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0433-unsatisfiable.rst#21treatment-of-unsatisfiable-constraints) to enable empty bodies as well (I haven't tested this on a recent build; just going by what the spec says).

**Comment by rhendric** [comment]
`Fail` is a compiler-handled class and thus already a special case; we're just haggling over the price now.

In this case:
* the special-casing is cheap (I'd estimate < 10 LOC, probably just in src/Language/PureScript/Sugar/TypeClasses.hs)
* the improvement in ergonomics of allowing an empty declaration over even adding a superclass to `Fail` (which would also be a change to the compiler) is pretty dramatic, I think
* the surprise factor to users for introducing a somewhat non-uniform behavior is probably low, given that the idea has come up repeatedly both here and in GHC

So I'd support it.
