### ISSUE TITLE
Auto-delete pre-existing binary and sha file on GH release page before uploading new file

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4486]
## Description

When we make a new production release, sometimes CI fails and must be restarted. Before failing, CI may create a `.sha` file on the GH release page. Similarly, a placeholder for a binary file may also be created (at least, AFAICT). When CI is restarted and builds the binary and succeeds, uploading the new `.sha` file and binary file to the release page will fail because these files already exist. To fix this now, we have to manually edit the GH release to delete these files before the restarted CI attempts to upload those files.

Ideally, CI would first check for these files and delete them if they are there before uploading the new `.sha` and binary files.

**Comment by rhendric** [comment]
I wonder if we should just switch to using the `gh` CLI tool to upload assets, with [the `--clobber` option](https://cli.github.com/manual/gh_release_upload).

The GH docs say that `gh` is installed on all GitHub-hosted runners; is it on our self-hosted runners?

**Comment by f-f** [comment]
It's not on the self hosted ones but we can add it easily.

**Comment by JordanMartinez** [comment]
@f-f Can you add `gh` to the self-hosted ones?

**Comment by f-f** [comment]
@JordanMartinez done!

**Comment by JordanMartinez** [comment]
Looks like our custom Ubuntu runner doesn't have `gh` installed: https://github.com/purescript/purescript/actions/runs/6352732000/job/17256145106#step:16:10

**Comment by JordanMartinez** [comment]
I've built and uploaded the binary locally by following the same steps in `ci.yml`.
