### ISSUE TITLE
0.15.10 doesn't allow class methods without class type variables in signature

### ISSUE THREAD

**Issue by fsoikin** [purescript/purescript#4487]
## Description

Take something like [`reflectSymbol`](https://pursuit.purescript.org/packages/purescript-prelude/6.0.1/docs/Data.Symbol#v:reflectSymbol). Prior to 0.15.10 there was no choice but to give it a `Proxy` parameter:

```
s = reflectSymbol (Proxy :: _ "whatever")
```

After 0.15.10, however, one would expect to be able to do better:

```
s = reflectSymbol @"whatever"
```

But this is impossible, because the compiler will return an `UnusableDeclaration` error when checking such class.

## To Reproduce

```
class C a where x :: String
instance C Int where x = "works!"

y = x @Int
```

This doesn't compile, returning an `UnusableDeclaration` error.
Technically the class declaration alone is sufficient for repro, I just added instance and use site for better illustration.

## Expected behavior

The code should compile and `y` should be equal to `"works!"`

## PureScript version

0.15.10

**Comment by purefunctor** [comment]
This ultimately stems from type variables in class heads being available for application by default, which should have made it so that `UnusableDeclaration` isn't ever thrown. I do think down the line, they should be opt-in as well, though; I think that would also be a breaking change?

**Comment by purefunctor** [comment]
IIRC, the old implementation (#4235) did handle this specific case, since it had opt-in class head variables. I guess the underlying question here is: do we remove `UnusableDeclaration` checks or do we make class head variables opt-in, such that they're subject to this check?

**Comment by natefaubion** [comment]
If there is a good error at the call-site for how to procede with calling it, I'm personally 👍 for removing `UnsuableDeclaration`.

**Comment by JordanMartinez** [comment]
In one of our tests where [`UnusableDeclaration` is thrown](https://github.com/purescript/purescript/blob/master/tests/purs/failing/UnusableTypeClassMethodConflictingIdent.purs#L4-L6)...

```purs
class C a where
  -- type doesn't contain the type class var `a`
  c :: forall a. a
```
If we remove `UnusbleDeclaration`, will there be any naming conflicts between the type variable `a` in the class head and the type variable `a` in the `forall`? And if so, should there at least be some sort of warning here about the conflicts?

**Comment by fsoikin** [comment]
But this declaration is indeed unusable: the method cannot be called, because `a` can be neither inferred nor VTAed.

I guess the question still stands if you change it to:

```
class C a where
  c :: forall @a. a
```

**Comment by JordanMartinez** [comment]
> But this declaration is indeed unusable: the method cannot be called, because `a` can be neither inferred nor VTAed.
> 
> I guess the question still stands if you change it to:
> 
> ```
> class C a where
>   c :: forall @a. a
> ```

Here's a better example then:
```purs
class C a where
  c :: forall a. a -> Int
```
The point is still about whether a naming conflict will occur here and whether we should warn the user. Because, AFAICT, the full type signature of `c` is:
```purs
c :: forall @a a. a -> Int
-- or, if we renamed the first 'a' to something else...
c :: forall @tyClassHead a. a -> Int
```

**Comment by natefaubion** [comment]
Should that not have a shadowed warning?

**Comment by natefaubion** [comment]
I personally don't see that as a problem. It's still callable, and any given error will still be correct. The compiler doesn't prevent you from writing instances with confusing names, and I don't see this as being any different.

**Comment by fsoikin** [comment]
It does get a shadow warning here:

``` haskell
f :: forall a. a -> Unit
f _ = g 42
  where
    g :: forall a. a -> Unit
    g _ = unit
```

So I think it's totally reasonable to return a shadow warning in the situation with class too.

**Comment by JordanMartinez** [comment]
<details>
<summary>Using this test</summary>

```purs
module Main where

import Prelude
import Effect (Effect)
import Effect.Console (log)
import Unsafe.Coerce (unsafeCoerce)

class C a where
  c :: forall a. a -> Int

instance C Int where c _ = 1

main = do
  when (1 == (c @Int unit)) do
    log "Done"
```

</details>

<details>
<summary>I get this compiler error:</summary>

```
No type class instance was found for
                      
           Main.C Unit
                      
       
       while applying a function c
         of type C @Type t0 => t0 -> Int
         to argument unit
       while checking that expression (c) unit
         has type Int
       in value declaration main
       
       where t0 is an unknown type
</details>

**Comment by natefaubion** [comment]
That looks like a separate bug to me, probably due to unhygienic substitution of type variables.

**Comment by JordanMartinez** [comment]
> That looks like a separate bug to me, probably due to unhygienic substitution of type variables.

<details>
<summary>Using this as an example</summary>

```purs
module Main where

import Prelude
import Data.Maybe (Maybe(..))
import Effect (Effect)
import Effect.Console (log)

class ConflictingIdent :: Type -> Constraint
class ConflictingIdent a where
  -- The `a` in the type below should refer to the `a`
  -- introduced by the `forall`, not the class head.
  conflictingIdent :: forall a. a -> Int

instance ConflictingIdent String where
  conflictingIdent _ = 1

conflictingIdentWorks :: Effect (Maybe String)
conflictingIdentWorks = do
  pure if (1 == conflictingIdent @String 4) then Nothing else Just "ConflictingIdent failed"

main :: Effect Unit
main = do
  mbR <- conflictingIdentWorks
  log $ show mbR
```

</details>

<details>
<summary>I get the following debug output for <a href="https://github.com/purescript/purescript/blob/master/src/Language/PureScript/TypeChecker/Types.hs#L470-L481">this code</a> here:</summary>

```
infer' VTA valFn tyArg

valFn = conflictingIdent
tyArg = String
valFn' = conflictingIdent
tyArg' = String
valFn'' = conflictingIdent
ValTy' = forall (@a :: t18) (@a :: Type). ConflictingIdent a => a -> Int
tyArg'' = String
resTy = forall (@a :: Type). ConflictingIdent a => a -> Int
valFn''' = conflictingIdent
resTy' = forall (@a :: Type). ConflictingIdent a => a -> Int
```

</details>

Do we have a util for renaming the type variables to something else?

**Comment by natefaubion** [comment]
I believe there is a function somewhere that floats our foralls in typeclass methods. Naively, the signature of this method would be:
```
conflictingIdent :: forall @a. ConflictingIdent a => forall a. a -> Int
```
But the compiler is "helpfully floating the inner forall out to make the signature look more expected, but it is doing so in an unsafe way.
```
conflictingIdent :: forall @a a. ConflictingIdent a => a -> Int
```
Transforming the former into the latter is an incorrect translation, as it does not obey the scoping of the original signature. I suspect this has always been broken.

**Comment by rhendric** [comment]
Those debug outputs suggest that something during or prior to the floating is adding a visibility marker on the inner `a`, which is also incorrect.

**Comment by JordanMartinez** [comment]
> Those debug outputs suggest that something during or prior to the floating is adding a visibility marker on the inner `a`, which is also incorrect.

There's a function called [`addVisibility`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Types.hs#L553-L562) that works by looking up a ty var from a list and adding the respective visibility for it. I wonder if that's what's duplicating the visibility. In other words, I wonder if that function looks up the ty var for the second one, finds a visibility for the first one, and then duplicates the first one's visibility into the second one. If so, then fixing the floating would also fix this issue.

Looking at [`addVisibility`'s usage](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/TypeClasses.hs#L308), I see that [`moveQuantifiersToFront`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Types.hs#L600-L604). Could that cause the floating issue described here?

**Comment by natefaubion** [comment]
Yes, that's correct. `moveQuantifiersToFront` makes no effort to check if it's doing a valid transformation per scope. It just collects everything and folds it up.

**Comment by JordanMartinez** [comment]
`moveQuantifiersToFront` was introduced here: https://github.com/purescript/purescript/commit/807426adf330f86a9be7c4fca88dc91b1544f8b6. Seems like this has been there since `purs@0.5.5`. When I removed `moveQuantifiersToFront` entirely and ran `stack test --fast` all the tests passed aside from [`1310.purs`](https://github.com/purescript/purescript/blob/master/tests/purs/failing/1310.purs), which I should compile now due to VTAs.

So, is this still needed?

**Comment by JordanMartinez** [comment]
Ok, nevermind. If I remove `moveQuantifiersToFront`, 1310 still fails to compile due to this error:
```
Error found:
in module [33mIssue1310[0m
at tests/purs/failing/1310.purs:18:8 - 18:31 (line 18, column 8 - line 18, column 31)

  No type class instance was found for
  [33m                         [0m
  [33m  Issue1310.Inject Oops  [0m
  [33m                   Effect[0m
  [33m                         [0m

while applying a function [33minj[0m
  of type [33mInject @t0 t1 t2 => (forall (a :: t0). t1 a -> t2 a)[0m
  to argument [33mOops (log "Oops")[0m
while checking that expression [33minj (Oops (log "Oops"))[0m
  has type [33mEffect Unit[0m
in value declaration [33mmain[0m

where [33mt0[0m is an unknown type
      [33mt1[0m is an unknown type
      [33mt2[0m is an unknown type

See https://github.com/purescript/documentation/blob/master/errors/NoInstanceFound.md for more information,
or to contribute content related to this error.
```

**Comment by natefaubion** [comment]
I think it's probably best to move that discussion to a new issue.

**Comment by JordanMartinez** [comment]
> I think it's probably best to move that discussion to a new issue.

Opened here: https://github.com/purescript/purescript/issues/4495

**Comment by JordanMartinez** [comment]
Another implication of dropping `UnusableDeclaration` is the following. Should this compile? 
```purs
module Main where

class Zero where
  useZero :: Int

instance Zero where
  useZero = 0

zero :: Int
zero = useZero
```
To me, it seems pointless to write this as there is only one possible instance; so this is just a function with needless type class dictionary overhead. 

Should an `UnusableDeclaration` still be thrown here? Or should some other potential new error be thrown instead?

**Comment by rhendric** [comment]
I just tried that example on try.purescript.org and it works; is it simplified from something else?

**Comment by JordanMartinez** [comment]
I'm not sure how to answer that question.

**Comment by rhendric** [comment]
You asked:

> Should an `UnusableDeclaration` still be thrown here?

But an `UnusableDeclaration` doesn't seem to be thrown with that example currently, so I'm confused and trying to figure out what you mean.

**Comment by fsoikin** [comment]
Even if it should be prohibited, the error definitely shouldn't be `UnusableDeclaration`, since declaration is quite usable.

**Comment by JordanMartinez** [comment]
> You asked:
> 
> > Should an `UnusableDeclaration` still be thrown here?
> 
> But an `UnusableDeclaration` doesn't seem to be thrown with that example currently, so I'm confused and trying to figure out what you mean.

Ah, sorry! When I posted that example, I assumed it would not compile. I also assumed that, if it did not compile, it would be due to the `UnusableDeclaration` check that I was removing. So, if we wanted to make it not compile, we could throw that error still or choose a different one. If we did want to make it compile (as I didn't know it was already compileable), then the discussion would go elsewhere.

**Comment by rhendric** [comment]
Gotcha. Without thinking a lot harder about whether there are legitimate use cases for this pattern I think we should let what compiles continue to compile, then.

**Comment by JordanMartinez** [comment]
> Gotcha. Without thinking a lot harder about whether there are legitimate use cases for this pattern I think we should let what compiles continue to compile, then.

I guess letting it continue to compile also avoids a possible breaking change if someone somewhere was using this.

**Comment by JordanMartinez** [comment]
Coming back to this issue, providing a useful error message is difficult for the following reasons:
1. When `Coercible`/`coerce` is involved, [things get complicated](https://github.com/purescript/purescript/pull/4494#discussion_r1282247010)
2. We can make a design choice to fill in the user-supplied VTA arg if the user did provide one. However, doing so can be misleading per [Case 2](https://github.com/purescript/purescript/pull/4494#issuecomment-1668526160). But ignoring that means we may have a less useful error message.
3. The order of the displayed VTAs may not reflect the user's expectation. See [Case 3](https://github.com/purescript/purescript/pull/4494#issuecomment-1668526160). 

While one of the constraints of this issue was to provide a clear error message, the underlying issue is some code that isn't otherwise problematic cannot compile right now due to the `UnusedDeclaration` check. Moreover, it blocks further ecosystem updates (e.g. changing `IsSymbol`/`Reflectable` type classes to drop the `Proxy` arg).

So, would simply reporting that VTAs may help and showing what that would look like be a good enough error given these problems?

So, given code like:
```purs
module MyModule where

class MyClass a b c d 
  | a b -> c -- via FDs, only a, b, and d need to be determined
  , d -> a b -- via FDs, only d and c need to be determined
  where
    foo :: a -> b -> c -> d
```
the error would be
```
  No type class instance was found for

    MyModule.MyClass a b c d

  The instance head contains unknown type variables. Using visible type application(s)
  may resolve the unknowns:
  
    foo @a @b @_ @d
    foo @_ @_ @c @d
  
```
