### ISSUE TITLE
Typeinference fails where I wouldn't expect

### ISSUE THREAD

**Issue by FredTheDino** [purescript/purescript#4498]
## Description
Compiling:
```hs
module Main where

example =
  let
    -- Does not compile
    f x = x
  in
  f [ f 1 ]
```
https://try.purescript.org/?code=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJgA8lgAHWOAXkLjlgBcHG4BaDuAERBgDOcNCGZwAxiCopYbRgDM4pOkrbo2igNpxFARjgBdIA

causes the error:
```
  Could not match type

    Array Int

  with type

    Int


while checking that expression [ f 1
                               ]
  has type t0
while applying a function f
  of type t0 -> t0
  to argument [ f 1
              ]
in value declaration example

where t0 is an unknown type
```

But adding a typesignature to `f` - makes the code compile:
```hs
module Main where

example =
  let
    -- Compiles fine!
    f :: forall x. x -> x
    f x = x
  in
  f [ f 1 ]
  ```

## To Reproduce

Compile
```hs
module Main where

example =
  let
    -- Does not compile
    f x = x
  in
  f [ f 1 ]
```

## Expected behavior
I would expect the typeinference to infer the type `f :: forall x. x -> x` and happily compile the first code.

## Additional context
I find this error confusing - since larger pieces of code might lead you down stray roads. I would expect new developers to also find this frustrating.

## PureScript version

PureScript version:
[v0.15.10](https://github.com/purescript/purescript/releases/tag/v0.15.10)

**Comment by rhendric** [comment]
Following Haskell and the [Let Should not be Generalized](https://www.cs.tufts.edu/~nr/cs257/archive/simon-peyton-jones/let-not-generalized.pdf) paper, we don't infer polymorphic types except at the top level. The paper explains why this choice is best out of the various alternatives, and we agree with its reasoning, even though there are some cases where inferring polymorphic types would be convenient.
