### ISSUE TITLE
0.15.0 won't completely infer types using VTA inside a record

### ISSUE THREAD

**Issue by jterbraak** [purescript/purescript#4500]
## Description

When using a value inside a record for which type depends on a type provided using the new VTA feature the compiler won't infer the type inside the record and instead leaves a `forall`. This then prevents other typeclasses like `RowToList` or `Nub` from working.

## To Reproduce

```
module Example where

import Prelude

import Data.Reflectable (class Reflectable, reflectType)
import Type.Proxy (Proxy(..))

reflect :: forall @t v . Reflectable t v => v
reflect =
    reflectType ( Proxy @t )

use :: String
use =
    show { asdf : reflect @"asdf" }
```

## Expected behavior

The code should compile and the value of use should be `{ asdf: "asdf" }`

## Additional context

The issue disappears when adding any other argument:

```
reflect :: forall @t v . Reflectable t v => Unit -> v
reflect _ =
    reflectType ( Proxy @t )

use :: String
use =
    show { asdf : reflect @"asdf" unit }
```

## PureScript version

0.15.10

**Comment by JordanMartinez** [comment]
Posting the above code in Try PS: https://try.purescript.org/?code=FAWw9gJgrgNgpgAgLIEMCWA7BB3AFnAJzmGDRAAcwCAXBABSJigmNIqtoBEVqUA6AEpwAZvADGvAEbwEACjEwUAZyUIhouBJTS4AGgRENEgCoBPcnACUbSjQRmLfBmAAepuc7ey%2BfS9eCG4rQAXMEIwlQoMDAIAAK0AG4IfGoiQdoyiQgAvAB8CAkBaZq02cAIFQbFJuaIsvQEru7xCP5QSoihCADK1ASYAObA7YhllQhKuGDYCADeCMoQwghhgSVxAESLwhsIAL4kQA

Error is:
```
No type class instance was found for

    Prim.Row.Nub ( asdf :: forall v. Reflectable "asdf" v => v
                 )
                 ( asdf :: forall v. Reflectable "asdf" v => v
                 )


while solving type class constraint

  Data.Show.Show { asdf :: forall (v :: Type). Reflectable @Symbol "asdf" v => v
                 }

while applying a function show
  of type Show t0 => t0 -> String
  to argument { asdf: reflect
              }
while checking that expression show { asdf: reflect
                                    }
  has type String
in value declaration use

where t0 is an unknown type
```

**Comment by purefunctor** [comment]
#4376 introduced a typing rule for inferring property values inside of records: https://github.com/purescript/purescript/blob/4afea2fbefeebd5e89c67d5a951efee870bcf2f2/src/Language/PureScript/TypeChecker/Types.hs#L549-L573

The `propertyShouldInstantiate` function has been used for a while now but I don't exactly recall why it's there. Adding a special case for `VisibleTypeApp` should do the trick provided that the term being applied satisfies `propertyShouldInstantiate` too.

**Comment by JordanMartinez** [comment]
That fixes it. PR incoming.
