### ISSUE TITLE
Name collision with `top`

### ISSUE THREAD

**Issue by Soupstraw** [purescript/purescript#4503]
## Description
My Purescript program compiles, but I get an error at runtime:
```
Uncaught TypeError: top is not a function
```

It looks like there is a name collision between [top](https://developer.mozilla.org/en-US/docs/Web/API/Window/top) in Javascript and `top` in the `Bounded` instance of `Int`.

## To Reproduce

TODO

## Expected behavior

I expect the program to not throw a runtime error like this. The compiler should probably generate a fresh name for the `top` function in the `Bounded` class.

## Additional context

`prelude` version `6.0.1`

## PureScript version

0.15.10

**Comment by Soupstraw** [comment]
Right now the workaround is
```
sed -i 's/top\([:(]\|\( =\)\)/top$top\1/g' main.js
```

**Comment by rhendric** [comment]
I can't reproduce this error on try.purescript.org, in Firefox or Chromium. In what browser are you seeing this?

**Comment by Soupstraw** [comment]
I tried both and got the same result

**Comment by Soupstraw** [comment]
This is the project I'm working on:
https://github.com/Soupstraw/orders-of-magnitude

**Comment by rhendric** [comment]
Okay, so loading your project with [this link](https://try.purescript.org/?github=Soupstraw/orders-of-magnitude/master/src/Main.purs) (good thing it's a single module), and then replacing the localhost JSON URL with `https://raw.githubusercontent.com/Soupstraw/orders-of-magnitude/master/data/output.json`, I see an application with some hearts and colored text boxes and no errors. You see something different?

**Comment by Soupstraw** [comment]
Huh, that's odd, seems to work in the online editor for me as well

**Comment by rhendric** [comment]
Not a compiler bug, then. If you're just using the vanilla purs-nix setup for your dev environment, maybe raise this issue with them; this is the sort of issue I'd expect to see if there was an issue with the bundling step, or if a clever dev server was trying to ship code to your browser in pieces but screwing it up somehow.

**Comment by Soupstraw** [comment]
Not a compiler bug
