### ISSUE TITLE
Core dump for Linux Arm64 release with ArchlinuxARM

### ISSUE THREAD

**Issue by MarcusE1W** [purescript/purescript#4518]
## Description

After the download of release v0.15.13-1 `linux-arm64.tar.gz` the command ./purs creates a segmentation fault and core dump.

## To Reproduce

1. download `linux-arm64.tar.gz`
2. tar xvzf linux-arm64.tar.gz
3. ./purs

## Expected behavior

It runs

## Additional context

I have several distros on the same laptop and OS  in distrobox. In the Debian and  openSuse distro the exact same binary works fine (so far). So I guess it must be something about Archlinux.

## PureScript version

v0.15.13-1
ManjaroARM (ArchlinuxARM)
Pinebook Pro (aarch64)

**Comment by rhendric** [comment]
Is this specific to v0.15.13-1, or do you get the same error with other versions?

**Comment by MarcusE1W** [comment]
It crashed with the latest stable version as well

**Comment by MarcusE1W** [comment]
Let me know if I can execute or test something to narrow it down.

**Comment by rhendric** [comment]
It'd be helpful if you could find the latest version that doesn't crash for you, assuming there is one.

**Comment by MarcusE1W** [comment]
So, I solved it. It turns out it was a fault with my system.
I learned interesting things on the way.
Turns out there is a systemd service for coredumps. You can look in the relevant folder but also you can use `coredumpctl list`to get a list of the recent coredumps `coredump info <PID>`gives you then the stack trace.
In my case it turned out that my system was trying to use the wrong libc.so.6 that was first in path from one of my previous programming language experiments. That sorted it works now on Archlinux.
Sorry for the trouble and thanks for providing arm64 packages in the first place.
