### ISSUE TITLE
Problem typing a let expression

### ISSUE THREAD

**Issue by desfreng** [purescript/purescript#4527]
## Description

Hi ! I've been playing around with PureScript's typing system and I've come across an example where the compiler's behaviour doesn't seem consistent.

In my experiments and as mentioned in ticket #4498, PureScript does not generalise let expressions. So why is the following code accepted by the compiler? The reasons why I think this code should not be accepted are in the comments to the following code.

```purescript
module Main where

import Prelude (class Show, Unit, discard, show, (<>))
import Effect (Effect)
import Effect.Console (log)

data List a = Nil | Cons a (List a)

instance (Show a) => Show (List a) where
  show (Nil) = "Nil"
  show (Cons hd tl) = "(Cons " <> show hd <> " " <> show tl <> ")"

main :: Effect Unit
main = let x = Nil in -- x :: List τ, with τ unknown at this point
  do
    (let y = Cons "a" x in log (show y)) -- Here we find that τ = String, so x :: List String
    (let z = Cons true x in log (show z)) -- Boolean /= String, so why no error is repported here ?
```

The error is correctly emitted when the arity of the `List` type is modified :
```purescript
module Main where

import Prelude (class Show, Unit, discard, show, (<>))
import Effect (Effect)
import Effect.Console (log)

data List a b = Nil a | Cons b (List a b)

instance (Show a, Show b) => Show (List a b) where
  show (Nil x) = "(Nil " <> show x <> ")"
  show (Cons hd tl) = "(Cons " <> show hd <> " " <> show tl <> ")"

main :: Effect Unit
main = let x = Nil 1 in -- x :: List Int τ, with τ unknown at this point
  do
    (let y = Cons "a" x in log (show y)) -- Here we find that τ = String, so x :: List Int String
    (let z = Cons true x in log (show z)) -- Boolean /= String, so we GET an error repported here.
```

## To Reproduce

To reproduce this problem, simply copy-paste each of the examples into the `Main.purs` file generated by `spago init`, then call `spago build`.
You can also use [try.purescript.org](https://try.purescript.org) :
- [Code snippet 1](https://try.purescript.org/?code=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJWAAcQ8AXOABQKgjHgAoBjKJAZy7gGVsITABo4AVTQoqosCi5skeMKK6CRcFgB4AfAEpdJcpRoBRAGZmYbGi3OXrB0hWpw7VqgDoAwiDRcQsBpQIADmBoRgSFRIcAAycjQxALxwAHIoUHAAPnA%2BfnAxLPFcieHoJUhobKwCQgW6cEna-GoaxaVYuASEcHCqdSzpUA0pAERDoz19rSx5vNhgcFTDjXCjs768o3A603ULO83b27v9mEuZu6O6k4TAqBgAXI%2BuFu7iklR3D6uwNAAeqyGcHQcAAtGC4IDnnEEnBACPAokwUmwCLgEDQAGs0EIMFEltg5HAKOgvr0wCApr0WH84ABPVZzNZIbaA0HBEIaM70-TgyEACXw8Ew8DM6EWVGw%2BPhqz4VDw6BCKhAULgMPa-HliqpQRgNAAXozNks8BB4GyMByua19byIXAAEIgAIwSpwAD0KTlCrQSr6KpwDJxcHweEoIN4BDIzioMEWXXgAH4gA) (without the expected error)
- [Code snippet 2](https://try.purescript.org/?code=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJWAAcQ8AXOABQKgjHgAoBjKJAZy7gGVsITABo4AVTQoqosCi5skeMKK6CRcFgB4AfAEpdJcpRoBRAGZmYbGi3OXrB0hWpw7VqgDoAwiDRcQsBpQIADmBoRgSFRIcAAycjQxAEZwALxwAHIoUHAxAD5wPn5wKSzxXIkl4egVSGhsrAJCuaJNmFVp2vxqGuWVSbpYuASEcHCqzSxZOQAeg%2BkARFPZcAtwOuM9M%2BtdC7oLo5uTRbzYYHBUUPOrLCerO0ftZw9raxsT7Zcv%2B8TAqBgALgBrgs7nEkiohD%2B6DScFgNG26WmcAAjHAYQBaDFwbZAuIJOAASTQNEAI8CiTBSbBwUlwCBoADWaCEGCiF2wcjgFHQkLGYBAhzGLHhcAAnrC7gskGttjDgiENB8xfo4Fi4AAJfDwTDwMzoc5UbBs2npPhUPDoEIqEA4uB4vpEkn8c2WwVBGA0ABeEt8vHNEHgsow8sVPU9KrVACEQAEYHU4AB6U0utBW8Y2nVwADiJgAKrkMPg8JQ4AQyM4qDBzsMYB4gA) (with the correct error)

## Expected behavior

I expected the compiler to behave consistently, regardless of the arity of the `List` type introduced. That is, an error would be returned at the point explained in the comments in the first code snippet. 

## PureScript version

[v0.15.13](https://github.com/purescript/purescript/releases/tag/v0.15.13) (with [try.purescript.org](https://try.purescript.org)) and [v0.15.12](https://github.com/purescript/purescript/releases/tag/v0.15.12) (on my computer).

**Comment by natefaubion** [comment]
Probably https://github.com/purescript/purescript/issues/3874 I don't know if it's generalization so much as `Nil` is an identifier with a known type so it just accepts it's type as-is (lazy instantiation).
