### ISSUE TITLE
Allow local foreign declarations

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#460]
Having any foreign declarations currently forces me to explicitly define exports because I cannot put a foreign declaration in a `let` or `where`.

**Comment by paf31** [comment]
Closing, see discussion above.

**Comment by michaelficarra** [comment]
😕 I don't think a library that uses eval is an acceptable alternative.

**Comment by paf31** [comment]
I was referring to the compiler plugin idea specifically, but I just don't see the benefit of local foreign declarations. Avoiding explicit exports shouldn't be the motivation IMO, since writing explicit exports are a good habit to have anyway.

**Comment by michaelficarra** [comment]
Alright, I'm convinced. Thank you.
