### ISSUE TITLE
Uncurry optimization 

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#479]
I made this jsPerf as a test http://jsperf.com/curry-cost

The automatic currying of functions is an awesome part of this language and functional in general. But in javascript it comes at a serious cost (particularly if your paradigm is to use shit tons of function application). 

Some languages (Fay and Elm) flatten out curries at compile time if they are not used. So

```
  add3 x y z = x + y + z
  trace 1 2 3
```

instead of becoming:

```
   var add3 = function(x){
         return function(y){
               return function(z){
                      return x + y + z;
               };
         };
   };
   trace(add3(1)(2)(3));
```

becomes:

```
 var add3 = function(x,y,z){
       return x + y + z;
 };
 trace(add3(1,2,3));
```

are there any plans to add optimization around currying? I believe this could be done without breaking changes.

**Comment by mgmeier** [comment]
Something progress has been made on this end: We've implemented an "uncurry" optimization in ```psc-bundle```, which seems a more suitable place for it than the compiler itself.

If you're interested in the topic, here's the read-up: http://symbolian.net/2016/04/07/513
and this is the branch to check out: https://github.com/jutaro/purescript/tree/BundleAndOptimize

Please do confirm if the optimization works for you, or share figures showing that it doesn't.
Our interest is to get this as an option marked experimental into the mainline bundle tool some time soon, if the community agrees it's the right way to go.

**Comment by paf31** [comment]
I think it makes a _lot_ more sense to implement this inside `psc-bundle`. If we can gain confidence that it works as intended (the JS AST is a bit unstructured, after all), then I think we would be interested to merge it into `master`.

**Comment by Fresheyeball** [comment]
Oh my god yes!!! Make PureScript perform!!! This is HUGE!

**Comment by filib** [comment]
For anyone else following along, the new PR is at https://github.com/purescript/purescript/pull/2219.

**Comment by Pauan** [comment]
If anybody is still interested in this, [`rollup-plugin-purs`](https://github.com/Pauan/rollup-plugin-purs) now does both uncurrying and inlining. It can't uncurry every function, but it can uncurry most functions.

**Comment by jamesdbrock** [comment]
> Something progress has been made on this end: We've implemented an "uncurry" optimization in `psc-bundle`, which seems a more suitable place for it than the compiler itself.
> 
> If you're interested in the topic, here's the read-up: http://symbolian.net/2016/04/07/513
> and this is the branch to check out: https://github.com/jutaro/purescript/tree/BundleAndOptimize
> 
> Please do confirm if the optimization works for you, or share figures showing that it doesn't.
> Our interest is to get this as an option marked experimental into the mainline bundle tool some time soon, if the community agrees it's the right way to go.

It seems that @mgmeier 's Symbolian read-up on uncurrying has move to here: [Optimizing Purescript´s Runtime Performance](http://www.symbolian.net/blog/optimizing-purescripts-runtime-performance)

**Comment by JordanMartinez** [comment]
I have to agree that having an option that optimizes all functions to be uncurried as much as possible would be nice. During development, that likely wouldn't be desirable because debugging the outputted JS would be easier. However, if one is going to minify the outputted JS anyway in production, then performance and not readability is generally their concern. Also, if this is an option, then even those outputting code in production may choose not to use it whereas those where it's a fundamental business concern can use it.

At the very least, I think this is something that should be further discussed.

**Comment by rhendric** [comment]
Given that functions using the primitives from `Data.Function.Uncurried` are currently optimized in this way, I have the impression that the best way forward would be to finish #4092 and then anyone can implement this as an external, whole-program CoreFn transformation that inserts the appropriate `mkFn*`/`runFn*` calls.

(This plan has the downside that, I think, we don't yet know what the pitfalls are in managing an ecosystem of external CoreFn transformations. I think we all expect that it'd be easier than managing a collection of built-in compiler options/extensions, but from a distance the two approaches have enough similarity that I could imagine they might share some of the same problems.)
