### ISSUE TITLE
Newtype Deriving

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#514]
Since the representation of newtypes is the same as the underlying type, we should be able to "derive" instances by just using the existing instance directly.

Suggested syntax:

```
newtype Trace a = Trace (Eff (trace :: Trace) a) deriving (functorEff, applyEff, applicativeEff, bindEff, monadEff)
```

Note this would allow us to apply optimizations like "magic do" to monads derived from `Eff`.

**Comment by davidpelaez** [comment]
Just to confirm (since I'm a total purescript newbie), this would mean that I have to manually write the instances, e.g:

```haskell
newtype Context = Context String
instance showContext :: Show Context where
  show (Context x) = x
```

Would this be the correct approach in the meantime?

**Comment by garyb** [comment]
Yep, that's right, although the "deriving equivalent" would be:
``` haskell
newtype Context = Context String
instance showContext :: Show Context where
  show (Context x) = show x
```

**Comment by davidpelaez** [comment]
Thanks for the correction @garyb +1

**Comment by hdgarrood** [comment]
Why not use the same syntax that Haskell does?

```
newtype Trace a = Trace (Eff (trace :: Trace) a) deriving (Functor, Apply, Applicative, Bind, Monad)
```

**Comment by Fresheyeball** [comment]
:100: :100: :100:

**Comment by hdgarrood** [comment]
Now that orphan instances are disallowed, this would be very useful if you are trying to use something like `purescript-quickcheck-laws`. Currently, if you had a type `X` and you wanted to check that it obeyed type class laws, you'd probably have to use a newtype wrapper (since libraries won't want to depend on quickcheck in most cases) and you'd have to write out every instance you want to check, which is a lot of boilerplate.

**Comment by gbaz** [comment]
Now that we have a new syntax for deriving, can we use that for newtype deriving too?

i.e. if we say `derive instance Foo a` where Foo is anything but generic, it tries to newtype derive instead?

I'm open to tackling the issue proper if we agree on syntax first :-)

**Comment by paf31** [comment]
Yes I think so. Maybe

```purescript
derive newtype instance fooBar :: Foo Bar
``` 

?

We could use `unsafeCoerce` under the hood I think, or the equivalent in the typechecker without bringing in the `unsafe-coerce` library.

**Comment by garyb** [comment]
Yep, I don't think you need to, the implementation is just "do nothing" so I doubt we need to rely on that library for a dodgy typed identity function :wink:

You probably don't need to do that at all, could just use a `TypedValue True _` to state that it is so, no?

**Comment by paf31** [comment]
Yes exactly.

**Comment by garyb** [comment]
Does this give us the same power as `GeneralizedNewtypeDeriving`, or would that need some additional work? I think it does?

**Comment by AppShipIt** [comment]
Partially resolved by #1870?

**Comment by spicydonuts** [comment]
What's the reasoning for the new deriving syntax?  Couldn't the FFI-friendly names just go in parens like this:
```haskell
newtype Trace a = Trace (Eff (trace :: Trace) a)
  deriving ( functorTrace :: Functor
           , applyTrace :: Apply
           , applicativeTrace :: Applicative
           , bindTrace :: Bind
           , monadTrace :: Monad
           )
```
?

Using the new syntax you have to retype a lot of words:
```purescript
newtype Trace a = Trace (Eff (trace :: Trace) a)

derive newtype instance functorTrace :: Functor Trace
derive newtype instance applyTrace :: Apply Trace
derive newtype instance applicativeTrace :: Applicative Trace
derive newtype instance bindTrace :: Bind Trace
derive newtype instance monadTrace :: Monad Trace
```

Or better yet, make the FFI names optional and infer them using the convention most people are using.  A custom name can be specified if necessary to avoid a conflict.  That would make @hdgarrood's original example exactly the same as the one I have above:
```haskell
newtype Trace a = Trace (Eff (trace :: Trace) a) deriving (Functor, Apply, Applicative, Bind, Monad)
```

**Comment by AppShipIt** [comment]
Are all instance names solely for FFI? Because it seems like our convention is universal if they were generated by default.

**Comment by spicydonuts** [comment]
Especially if it used the same convention as the foreign module in compiled code: `$foreign`.  If someone really cares about the way it shows up in JS they can add `module.exports.monadFoo = $monadFoo`.  I'd make all the deriving and instances look just like Haskell, and supporting the custom name override using the current syntax would make it a non-breaking change.

**Comment by hdgarrood** [comment]
The convention is mostly universal for single parameter type classes, but multi parameter type classes (such as MonadError) make it quite a lot more complicated. See #952 and #1078. Also, let's please not go over this again in this issue. If you have new ideas to bring to the instance naming discussion, I think the mailing list is probably a better place.

**Comment by garyb** [comment]
@AppShipIt they are for the FFI / generated code currently, but depending on what happens with modules, implicits, etc. they may play a bigger role.

**Comment by AppShipIt** [comment]
Thanks! It's been a lingering question in my mind. I told @spicydonuts I thought the reason was <q>wisdom from above</q> :raised_hands:

**Comment by lexi-lambda** [comment]
Just a random bikeshedding comment that came to mind re: syntax: while I think the concision of the Haskell `deriving` clause is one of the reasons GND is so nice to use in Haskell, it is not actually completely without problems. GHC has the ability to derive lots of different classes, especially when paired with extensions like `DeriveFunctor`, and it’s not always clear which extension takes priority. This gets *especially* bad when paired with `DeriveAnyClass`, which overloads the `deriving` keyword so much that it actually becomes a little bit useless.

I think `DeriveAnyClass` is an extremely useful extension to have, so it would be nice if a PureScript implementation of any of Haskell’s deriving extensions sidestepped this issue. Personally, I wouldn’t mind the addition of a separate keyword, such as `inheriting`, to make the distinction explicit, but better resolution rules for how the various extensions interact with the optional ability to explicitly choose one particular sort of deriving would be fine, too.

**Comment by garyb** [comment]
@paf31 Another one we can close?
