### ISSUE TITLE
Optimizer prevents dead code elimination

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#539]
Like these:

```js
    function Nothing() {

    };
    Nothing.value = new Nothing();
    function Just(value0) {
        this.value0 = value0;
    };
    Just.create = function (value0) {
        return new Just(value0);
    };
```

This feature was added in https://github.com/purescript/purescript/pull/476. When they are unused, these methods *are* dead, right?

**Comment by paf31** [comment]
Is this still an issue now that DCE happens on the JS AST?

**Comment by paf31** [comment]
I did a quick test, and data types which aren't used transitively get removed, so I'll close this.
