### ISSUE TITLE
Upgrade to transformers/mtl 0.4.*

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#553]
Relax the bounds on `mtl` and `transformers`.

**Comment by hdgarrood** [comment]
On second thoughts it seems prudent to address this now rather than to add more code based on `ErrorT` (in pursuit-server). I'm happy to take a stab at it. Do you still want to move to `optparse-applicative`?

**Comment by paf31** [comment]
The `optparse-applicative` move is done. If you want to take a stab at this, I'd be very grateful. The major issue seems to be the change to `MonadPlus`, since we use `guard` in a few places, but we can probably use `guardWith` in those places.

**Comment by hdgarrood** [comment]
Ok - I'll let you know how I get on.
