### ISSUE TITLE
Package compiler dependencies

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#561]
It would be great to be able to have a package depend on a particular version of the compiler.

One simple way to do this would be to include a .psc config file in the package directory. It could contain something as simple as this:

```
{ "pscMinVersion": "0.5.4"
, "pscMaxVersion": "0.5.4.1"
}
```

or even

```
PSCConfig { pscMinVersion: Just "0.5.4", pscMaxVersion: Just "0.5.4.1" }
```

so that we can use `read`.

Both the min and max versions are optional. `psc` and `pscMake` would read the file and bail out early if the version was wrong.

Another option (simpler) is to just make these into command line options.

The biggest problem is that individual files need to indicate their required `psc` version, not just the top-level package. I'm not sure how to get around this. Maybe a pragma, or the `.psc` file could be read from every directory containing an input file.

Any ideas?

**Comment by flq** [comment]
Scanning around the "easy" tag. Is this one still alive? It carries 0.6.0 milestone. Since 0.7 is current, this is either done, obsolete or stale ;)

If it is still alive, would details be discussed @ freenode?

Talking of chat, have you people tried gitter.im ? There are chatrooms tied to a github project, and the UI is fairly decent...

**Comment by paf31** [comment]
It's still alive :) It's in the Ideas milestone, which means we might want to do it, but we haven't decided yet, and it hasn't been prioritized. That said, if you implemented it, I think a lot of people would be happy, and it might allow us to remove some deprecation warnings.

**Comment by paf31** [comment]
And yes, Freenode is the place to chat about things. I haven't tried Gitter, but I've heard of it. Does it get logged?

**Comment by flq** [comment]
With logged do you mean, does it keep history? Yes, it does. It is also searchable. You can have a look, since it's a no-brainer to log in with your github account. tbh, I don't know much about the freenode client, I guess I'd have to learn the IRC DSL.

**Comment by 2016rshah** [comment]
I'm looking to contribute to the project (#Hacktoberfest!) so I was looking through the easy tag. I would be happy to look into implementing it, but a few different options have been presented (command line args, a config file, etc.) so which one should I go for?

**Comment by paf31** [comment]
@2016rshah This probably shouldn't have the easy tag, actually. I thought it was easy at first, but it might need to be built into a package manager.

**Comment by 2016rshah** [comment]
@paf31 oh, too bad. Any ideas on other things I might be able to work on to contribute?

**Comment by paf31** [comment]
@2016rshah Definitely. The current focus is on performance and improving error messages. Any work on error messages would be very useful, if you felt inclined to work on that area. I can help on IRC if necessary.

**Comment by paf31** [comment]
Closing since this is covered by #631.
