### ISSUE TITLE
Exponentiation operator

### ISSUE THREAD

**Issue by Gabriella439** [purescript/purescript#591]
Does the purescript standard library have an exponentiation operator analogous to `(^)` in Haskell?  `(^)` in purescript is xor.

**Comment by thkoch2001** [comment]
@Gabriel439 was so kind to publish his experimental purescript to python compiler: [Purescript-to-Python](https://github.com/Gabriel439/Purescript-to-Python)

**Comment by Gabriel439** [comment]
My compiler is not much.  It barely translates anything.

**Comment by epost** [comment]
Updated link to `pow` docs: https://pursuit.purescript.org/search?q=pow
