### ISSUE TITLE
Implement array destructuring in terms of "Unconsable"

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#607]
This topic came up a few times in discussions at Strange Loop this year, so I wanted to start a discussion here on the issue tracker. Instead of specialising the array destructuring syntax `f (x:xs) = ...` to arrays, we can instead allow it to destructure any of data structures that can be split into a "head" and "tail" component, for example lists or heaps. Here's a really quick and dirty example of implementing this type class for arrays:

```hs
module Main where

import Data.Maybe (Nothing, Just)
import Data.Tuple (Tuple)
import Data.Array (null, drop)
import Prelude.Unsafe (unsafeIndex)

class (Functor f) <= Unconsable f where
  uncons :: forall a. f a -> Maybe (Tuple a (f a))

instance unconsableArray :: Unconsable [a] where
  uncons [] = Nothing
  uncons xs = Just $ Tuple (unsafeIndex xs 0) $ drop 1 xs
```

I obviously had to avoid using the destructuring syntax in its implementation. This limitation is the only downside I can see.

**Comment by michaelficarra** [comment]
FYI, I ran into more motivation for this today. An excerpt from the #purescript IRC channel:

```
9:06:51	michaelficarra	hey, #purescript, how can I destructure a fixed-length string?
9:07:26	michaelficarra	I've tried both `f (a : b : c : []) = …` and `f (a : b : c : "") = …`, but those don't work :-(
9:10:59	Bodil           michaelficarra: I guess you'd have to go via Data.String.toCharArray?
9:11:44	michaelficarra	:-( we probably need https://github.com/purescript/purescript/issues/607, don't we?
9:12:21	michaelficarra	I've been hoping to get around to that before we cut the next version
9:12:26	Bodil           I've been agreeing with that for a while. :)
9:13:31	michaelficarra	okay, for now I guess I'll just check the length and unsafe index into it
9:13:32	michaelficarra	thanks
```

**Comment by andyarvanitis** [comment]
:+1: if this is still up for discussion. I'd assume `[]` as `cons` sugar would/could be part of this too -- getting something like GHC's `OverloadedLists` extension.

**Comment by joneshf** [comment]
`OverloadedLists` would be awesome! Might need constraint inference though to make it less cumbersome to use.

**Comment by hdgarrood** [comment]
Because this was just brought up on the [mailing list](https://groups.google.com/forum/#!msg/purescript/_352c3581IE/06o6ar5FAwAJ) - sorry, but for the same reasons we removed cons patterns, my vote is :-1:.

I think view patterns are the way to go, like @jdegoes suggested in #1075. I think they would solve the issue here, and they're much more generally useful. They also make it obvious that the pattern might not be O(1).

**Comment by paf31** [comment]
I think we've settled on using `List` instead at this point. Can this be closed?

**Comment by garyb** [comment]
I think so. In the future, with pattern synonyms/guards/extractor type things we can probably regain the general behaviour here too, as those could also be aliased the way we currently do with data constructors.
