### ISSUE TITLE
compile purescript to PHP, PHP backend 

### ISSUE THREAD

**Issue by thkoch2001** [purescript/purescript#612]
Since people are already working on backends for Lua (https://github.com/purescript/purescript/issues/339) and Python (https://github.com/purescript/purescript/issues/591) it might not be too hard to add a fourth backend for PHP.
This would allow a very smooth migration path for PHP projects towards haskell.

**Comment by paf31** [comment]
The compiler solution for this will probably be to dump the functional core out to a file before/instead of codegen. I'll close this, since it almost certainly won't be implemented in this repo.

**Comment by 0x000000000000000000001** [comment]
Currently doing [the experiment](https://github.com/0x000000000000000000001/phpurs).

Included PHP in [this benchmark](https://github.com/0x000000000000000000001/altbak.pub).
