### ISSUE TITLE
Add PureScript support to pygments

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#617]
Github uses pygments for syntax highlighting code samples in issues. It'd be really nice if we didn't have to rely on the Haskell highlighting for minimal support. Repo is on bitbucket: https://bitbucket.org/birkenfeld/pygments-main

**Comment by hdgarrood** [comment]
I had a go at this a while ago, see:

* https://github.com/purescript/pursuit/issues/115
* https://github.com/github/linguist/pull/2506

GitHub has moved away from pygments and now uses TextMate lexer files for highlighting. Also, GitHub now uses the lexer file in https://github.com/freebroccolo/atom-language-purescript, which is better than the Haskell one but still has some room for improvement.

**Comment by paf31** [comment]
This can be closed now, right?

**Comment by hdgarrood** [comment]
Yes, I think so.
