### ISSUE TITLE
"Transducers" based collection functions for Prelude

### ISSUE THREAD

**Issue by philipnilsson** [purescript/purescript#625]
Clojure is introducing a "transducers" abstraction in their standard library. One of the main points is to be able to run map/filter/group and friends over strict collections (such as JS arrays) without creating intermediate collections, and allowing for explicit fusions.

It seems like this could be a natural approach to defining collections functions in Purescript's prelude, since it would allow us to define these functions without a new data type such as lazy lists, and instead be able to work on any Foldable datatype, including standard JS arrays, while maintaining the modularity benefits of lazy programming, e.g. being able to define the composition `all f = fold (&&) True . map f` in such a way that `all` is short-circuiting.

I'd suggest using something like Edward Kmett's `Data.Fold` representation:

```
data Fold a b =
  forall r. Fold (r -> b) (a -> r -> r) r
```

This data type admits an Applicative instance such that fused folds can be written as

```
mean = (/) <$> sum <*> length
```
where e.g. `sum = Fold id (+) 0`.

It also allows for a `Category` instance for the normal composition
```
foo = take 2 <<< filter p <<< map f
```

Thoughts? I've played around with this for a short amount of time but got stuck on some typing issues with the existential quantification in the `Fold` type.

**Comment by AppShipIt** [comment]
Revisited in purescript/purescript-foldable-traversable#44 and decided `Foldl.Handler` would be the best inspiration which works for optics out of the box confirming @joneshf's intuition. Close and remember as a good idea when one of us gets around to it.

**Comment by paf31** [comment]
I think this should be tracked elsewhere, it's not compiler-related.
