### ISSUE TITLE
Allow rows in instance contexts

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#642]
Currently we disallow rows in constraints, but really all we need to do is restrict instance heads, not instance contexts. We are currently disallowing seemingly valid things like 

```
foo :: (MonadState { field :: Type } m) => m Type
```

As long as every instance doesn't mention any non-empty rows, we should be fine.

**Comment by a3gis** [comment]
Could we get this merged please? :)

**Comment by paf31** [comment]
I'd really like to merge this, but I see some issues that I think could be fixed by consolidating the `unifiesWith` and `typeHeadsAreEqual` functions.

For example, suppose we need to unify `{ foo :: a }` and `{ foo :: Number }`, right now I don't think the constraint `a = Number` is made available. I'm not sure if this creates an issue or not, but it would be nice to know that we handle these cases properly.
