### ISSUE TITLE
typeclass deriving for Eq, Ord, Show

### ISSUE THREAD

**Issue by jfilip** [purescript/purescript#647]
as per Haskell

**Comment by gbaz** [comment]
This is fully developed in my branch of 0.6.9.5: https://github.com/gbaz/purescript/tree/deriving-generic

The code needs to be accompanied by a library module Generics.hs as given in this gist: https://gist.github.com/gbaz/a2c867b6c07731a403eb

I'd like to get this reviewed and merged -- not sure what branch to request a pull into, etc.

It would also be nice to develop more examples besides the show and the toFrom -- to/from json, eq, ord, etc. I'm fairly confident that the API is expressive enough for all the typical generics examples, but working a few more out would be nice.

**Comment by paf31** [comment]
See Generic Deriving in 0.7.3.
