### ISSUE TITLE
Rewrite rules

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#660]
A slightly different idea for how to implement rewrite rules, which would be more flexible:
- Provide a PureScript library which contains a type for the core AST, and some simple functions for generic traversals in the style of `syb`.
- Developers have the option of including a `.rewrites.purs` file for each module, which contains a top level value `rewrites :: [Tuple Priority (AST -> AST)]`, which is compiled and interpreted using Node during compilation.
- `psc` is responsible for interacting with the Node process, and passing the core AST back and forth during optimization.

This way, we don't need any special syntax for rewrites in the source code itself. We could even support the optimizations for `runST`!

**Comment by alexchandel** [comment]
Wouldn't rewriting be more effective if it all took place on the AST, before anything is translated to JS?

**Comment by garyb** [comment]
That's the plan, hence #971. We haven't exactly figured out where rewriting will take place, potentially at both `CoreFn` and `CoreImp` levels, although `CoreImp` would be the immediate priority as then we can remove a good part of the current JS optimiser that is specific to stuff in the `Prelude`.

**Comment by alexchandel** [comment]
Ah cool. It's too bad there isn't a JS equivalent to LLVM, otherwise PureScript could just target that. I haven't looked into it much, but the [Closure Compiler](https://developers.google.com/closure/compiler/) seems to do some optimizations beyond mere compression.

**Comment by joneshf** [comment]
You can go from LLVM to js though with things like: https://github.com/kripken/llvm.js. So an LLVM target is still a good idea.
