### ISSUE TITLE
Suggestion: Built-in tuples as arrays/multi-argument functions

### ISSUE THREAD

**Issue by dylex** [purescript/purescript#668]
Here's a crazy idea: Tuples could be added with an underlying array(-like) representation, but which, when applied to functions, expand to multiple arguments. Does this seem like a reasonable addition to the language? It may be more transparent than `FnN`, but requires adding more to the language. It would also be incompatible with #556. It's also rather javascripty.

The only major hurdle I see is polymorphism. Here's the idea for implementation: Assume (for simplicity) we have a type class `Tuple (t :: *)` that all tuples are instances of.  I'll call a "tuple type" any type for which we know there is a `Tuple` constraint.  A "non-tuple type" is any other type (including an uncontrained type variable).  A "tuple function" is any function taking a tuple type as argument, conforming to `forall t a. Tuple t => t -> a`.

When a tuple function is applied to a `Tuple` expression, call it with the arguments of the Tuple.  When a tuple function is applied to anything else (tuple or non-tuple type), call it as `f.apply(null, a)`.  When a tuple function is used as non-tuple function (i.e., generalized), wrap it in an additional `function (a) { f.apply(null, a) }` layer. (In a sense, a tuple function is like a boxed type in ghc, which needs unboxing occasionally.) When a tuple function binds its argument without a tuple pattern, use `arguments`.

**Comment by paf31** [comment]
It's not clear to me that there is a safe, modular way to implement this. Closing, but I'd be interested to hear a more complete proposal.
