### ISSUE TITLE
Make --single-line-mode the default behavior in psci

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript#709]
There are some decisions that the `psc*` (mostly just `psci`) binaries are making that I don't agree with. And, rather than change everything for everyone irreversibly, we should start looking at and using options. I don't mean command line options that you have to constantly pass to a binary, I mean global options in the `.purescript` directory.

Some things I'd like finer control over--and would like to discuss:

* Toggle cached compilation in `psci` (default off). I think this should default to off because polluting people's directories with `.psci_modules` directories doesn't seem nice. I personally don't like going about cleaning up after `psci`. Plus if it caches a bad compilation (happens more often than not when building a library), you have to then diag why it's failing and nuke it anyway.
* Toggle multiline in `psci` (default off). I think most of the definitions people write in `psci` are single lined, and repls seem to be single line by default so I feel it's more expected to have singleline be the norm, and multiline the exception.

I'll add more here as they come, but I wanted to get some opinions before I started working on this stuff.

**Comment by paulyoung** [comment]
These would be great. I only just discovered `--single-line-mode` and was also battling an issue where a file was not being recompiled.

**Comment by paf31** [comment]
Related: https://github.com/purescript/purescript/pull/882

As for cached compilation, I think the recent changes address most of the issues (0.6.7), but let me know if not.

I can make a separate issue for parsing a `.psci` file in the home directory.
