### ISSUE TITLE
Use an explicit type for type errors

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#745]
This is a first step toward moving to `transformers-0.4.*` and `ExceptT`. We need to:

- add a type (not `String`) for errors
- replace calls to `strMsg` with the appropriate constructor everywhere.
- update `monad-unify` to provide an appropriate error type, and handle that error type in `TypeChecker.Monad`.

**Comment by mjgpy3** [comment]
A few questions:
 - Should this new type be an instance of `Control.Monad.Error`?
 - Do you mean to ammend `monad-unify` so that it includes this type, or update the cabal reference?

Sorry if the questions are trivial.

**Comment by paf31** [comment]
I think we have two options:

- Move `monad-unify` back into the PureScript repo. It's going to need some changes anyway, to support some new features, so that probably isn't a bad option.
- Add a generic error type to `monad-unify`, something like `data UnifyError t e = OccursCheckFailed Unknown t | Other e`.

I'm leaning more in the direction of the first option lately, to support things like row constraints and better instance inference.
