### ISSUE TITLE
Instances for private classes and types still appear in psc-docs output

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#747]
Probably need to make a check while elaborating exports in name desugaring.

**Comment by paf31** [comment]
The environment gets passed to `psc-docs`. Maybe we could treat this like we treat data constructors?

**Comment by garyb** [comment]
Yeah, it looks like we'll have to do something with the environment anyway - instances aren't included in the elaborated exports list after all, so they must be coming through the environment after typechecking or something.

**Comment by paf31** [comment]
Sorry, I don't know what I was referring to there. The environment isn't involved in `psc-docs`, just the exports list (not elaborated). In `psc-pages`, the `isExported` check seemed to work fine. What's an example of this issue?

**Comment by hdgarrood** [comment]
Here's one: https://github.com/hdgarrood/purescript-sequences/blob/master/docs/Data.Sequence.md

`Size` and `Elem` are defined in `Data.Sequence` and not exported, but all of their instances appear in the docs.

**Comment by garyb** [comment]
Thanks, that'll make a handy test case.
