### ISSUE TITLE
Vision for getting started etc.

### ISSUE THREAD

**Issue by jasonkuhrt** [purescript/purescript#749]
I was chatting with @joneshf on IRC about this and he suggested I bring it up with the project.

The getting started story for `psc` is not ideal. It at least requires:

1. install haskell
2. install purescript
3. install node
4. install grunt
5. install grunt utils
6. understand the interop between `grunt` and `psc`, `psc-make`, etc.

It seems like it should be more along these lines:

```
$ brew install purescript && psc dev
```

Maybe it would help if the `ps` community defined an ideal *vision* and then worked backwards from there to accomplish the engineering feats required. I think `Meteor` and `Elm` are exemplary in regards to their workflow stories. Maybe `Clojure`/`Clojurescript` too, I don't know. It does seem that right now the biggest challenge to working with `ps` is the space between:

1. Wanting to try building a project with it
2. Building/deploying/running a a project with it

Ideally, the gap should be almost invisible to the user.

If `ps` is not approachable then it really does not matter how good it is. People do not want to consult a reference on how to build a project, buffer that knowledge, then flush it at once, and repeat. They want short trial-and-error cycles with really quick and useful feedback.

**Comment by AKST** [comment]
Hey so, @garyb suggested I mentioned some issues I've ran into with my first 24 hours in Purescript over here. First off I realise the language is still being actively developed so some of the stuff I guess should be expected.

I got past installing the compiler, but I already had cabal installed & I knew how to use sandboxes, and all that node stuff. Anyways the main struggle I had was getting libraries to work, the most confusing one for me was `purescript-virtual-dom`. It was using some require statements here and there, and I tried to replace the require statements with expressions pointing to the exact parts of the `virtual-dom` library, but I ended up posting an [issue](https://github.com/purescript-contrib/purescript-virtual-dom/issues/10#issuecomment-76529119) on the repo (I now have an answer)

What would have gone along way for me to build this project would have being told to use something like `pulp` off the bat (like before I even started installing libraries), but also providing a simple build script with the library example.

I also tried a bunch of different libraries each with their own struggles
- `purescript-jquery`, the api was confusing at times for some things, and didn't actually give much feedback when I did certain things wrong (but that's jquery I guess), I'll report an issue for this in a bit, I also found some of the types kind of opaque but whatever (again jquery I guess).
- `purescript-simple-dom`, doesn't actually have a method for creating `dom` elements, I posted [a question](https://github.com/aktowns/purescript-simple-dom/issues/24) about this on the repo, but I found that surprising
- `purescript-react`, I had a hard time trying to get the nightly version of `react` to install through `bower`, maybe an example in the readme would help? 

I really just wanted to build a UI of some sorts, so I tried a bunch of different libraries for it and still don't really know if there's a go to suggested library for this kind of thing.

**Comment by paf31** [comment]
You might like to look at `purescript-thermite`, which is another set of bindings to React. Where `purescript-react` is low level, `thermite` is high-level, simpler (in my opinion) and more functionally-oriented, but at the expense of some features.

**Comment by AKST** [comment]
Thanks I'll be sure to check that out

**Comment by garyb** [comment]
@paf31 do you think it might be worth revising the book to use `pulp` for the exercises? It would certainly be a much quicker path to getting started. Could just mention as a side note that plugins for Gulp, Grunt, etc. are also available when the need arises for more complex builds.

Also the point in there about only making binaries for major versions isn't quite true anymore either, certainly not since the 0.6.x release cycle.

**Comment by jasonkuhrt** [comment]
Echo's my feelings a bit http://blog.jenkster.com/2015/02/a-brief-and-partial-review-of-haskell-in-the-browser.html

>  There are a few downsides for me that eventually stacked up too high. Tooling's a bit of a pain. (You'll need Node. And Grunt. And Bower. Wait, are we actually building a JavaScript project?)
...
> Bonus Tip: If you're playing with PureScript, Take a look at Bodil Stokke's Pulp for your building needs. That worked well for me.

**Comment by alexchandel** [comment]
I went with `brew install purescript` and haven't looked back. Cabal is better suited for build management, not package management.

@garyb [purescript.org's download page](http://www.purescript.org/download/) should have a Package Manager section below Binaries, for `brew install purescript` and Linux variants (if any). Being installable via Homebrew is a major win for OS X development.

**Comment by joneshf** [comment]
> Cabal is better suited for build management, not package management.

Totally agree, it's even their mantra. 

> @garyb purescript.org's download page should have a Package Manager section below Binaries, for brew install purescript and Linux variants (if any). Being installable via Homebrew is a major win for OS X development.

You should submit a PR around here: https://github.com/purescript/purescript.github.io/blob/master/download/index.html#L41 

There are two packages in the AUR that i'm aware of: https://aur.archlinux.org/packages/?O=0&K=purescript. 

Nix has it. You can search for it here: https://nixos.org/nixos/packages.html. 

I don't really follow the other distros though.

**Comment by alexchandel** [comment]
purescript/purescript.github.io#18 merged. A maintainer should upload the Windows binary to [chocolatey](https://chocolatey.org).

As for a getting started vision, purescript.org probably needs a Packages tab with text similar to purescript/purescript.github.io#17 and a link to [Pursuit](http://pursuit.purescript.org/)

**Comment by paf31** [comment]
I think `npm install purescript` and `npm install pulp` are simple enough that I can close this now.

**Comment by GetContented** [comment]
One way to "solve" this might be to do what elm does... that is, make "elm" just a catchall command for all sub-commands,... and if bower is just an alias - ie the subcommand for "ps-package", all good :)
