### ISSUE TITLE
Inlcude markdown from code comments in generated docs

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#757]
The doc generation is awesome, but I also like to have badges (build passing, ect..) and sometimes other description. It would be nice to store this information in another markdown file and have the docgen insert that markdown file at the top of the generated markdown.

Perhaps:
```
myProject |
                 | - DocHeader.md
                 | - DocFooter.md
                 | - README.md
```
where `README.md`is the generated doc.

**Comment by hdgarrood** [comment]
I think we now have this (i.e. comments at the top of a module). See:

* https://github.com/purescript/purescript-control/blob/master/src/Control/Functor.purs
* https://github.com/purescript/purescript-control/blob/master/docs/Control.Functor.md

**Comment by paf31** [comment]
Yes, thanks.
