### ISSUE TITLE
Pattern matching in let and where clauses

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript#764]
This is what I miss most currently as bloody beginner (beside more precise parser and type checker error messages). Don't know if it is in the issue list so far but can't find it. e.g:

```
let (X a) = X b
in a
```

currently is not working, right? As far as I see the same applies to all other patterns.
I can write something like this instead, but it can make the code less clear (not in this example):

```
case X b of
  X a -> a
```

**Comment by nrolland** [comment]
wouldn't a version where the ordering has to be linearly specified, no topo sort, be useful ?  

I think in many of the cases I use it with only one case or parallel destructors anyway. 
having to introduce extraneous binders is strange after being too spoiled. I guess it makes the generated code closer to input code but in most case i think that's moot

**Comment by user471** [comment]
:+1:

**Comment by AndrasKovacs** [comment]
:+1:

**Comment by libscott** [comment]
+1

**Comment by jdegoes** [comment]
I'd definitely use this.

**Comment by felixSchl** [comment]
So would I, this would be great to have. :+1:

**Comment by vstastny** [comment]
I would also vote for having this.

**Comment by zhangchiqing** [comment]
Any update on this feature? 

I just ran into this:
```purescript
  inst <- liftEff now
  let (Milliseconds n) = unInstant inst
```
psc 0.10.1 will throw this error
```
  Unable to parse module:
  unexpected (
  expecting local declaration
```

**Comment by paf31** [comment]
No update, but it's on the Approved list, so if someone wants to work on it, we can give advice on the design/implementation.

**Comment by noraesae** [comment]
I would like to work on this. @paf31, can you give me hints on how to implement this? Maybe with desugaring into case expression as mentioned above?

**Comment by paf31** [comment]
@noraesae Great! This will definitely be implemented as a desugaring pass, but the details need to be worked out:

- What changes we need in the parser, and how we can minimize backtracking
- How this fits into the desugaring process, taking into account the need to look at binding groups

**Comment by noraesae** [comment]
Thanks for your comment. This is my first contribution on PureScript and can take a while to be accustomed to its code base.

As you suggested, I will start from looking into the parser, and see what kind of change is needed. I will update the process as frequently as possible, as I may not be sure if I am doing it right :smile:

**Comment by noraesae** [comment]
Working on the parser. I have created an example too.

- Add an example: https://github.com/noraesae/purescript/commit/cdec7991d96d91e40ef7e257a98048c9a9014553
- Modify the parser: https://github.com/noraesae/purescript/commit/12cb1b872a3a564b8c68c3f3518494e6ed0457d3

I am thinking about working on desugaring from now on. Review or further direction is super-welcomed.

**Comment by noraesae** [comment]
I have implemented desugaring of let-in expression. After this, I will implement desugaring for let statement in do expression.

For the content, please refer to the following commit. I really appreciate early reviews, as it helps me to do the job later in the right way.

- https://github.com/noraesae/purescript/commit/e6007cc96bb53dca3773a37647b70a642fc5a1bc

**Comment by paf31** [comment]
@noraesae `let` in do notation just desugars to regular `let`, so you shouldn't need to do any additional work there. Thanks!

**Comment by noraesae** [comment]
@paf31 Great to know! I may then reorder the desugaring passes and test.

**Comment by paf31** [comment]
@noraesae You might not be able to just reorder them - the order can be important - but try it and see :)

**Comment by noraesae** [comment]
As you said, I placed `desugarLetPatternModule` after `desugarDoModule` to use the desugared version of `let` in do notation. Everything seems like working now. :tada:

- Desugaring: https://github.com/noraesae/purescript/blob/let-pattern-matching/src/Language/PureScript/Sugar/LetPattern.hs
- Example: https://github.com/noraesae/purescript/blob/let-pattern-matching/examples/passing/LetPattern.purs

I will clean up the code and commits, rebase with #2611, test again, and then upload a PR.

Thank you very much for your directions. It helped me a lot.

**Comment by noraesae** [comment]
This issue can be closed?

**Comment by paf31** [comment]
Yes, thanks!

**Comment by noraesae** [comment]
Thank you very much for your help too! :tada: :tada:
