### ISSUE TITLE
Represent typeclasses as data constructors in functional core

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#781]
Currently during desugaring "class constructor functions" are created, instead we should reuse `Constructor` for this, and then use pattern matches to extract fields from the constructed typeclass dictionaries rather than assuming the typeclass dictionary is always a record.

This will remove the current strong tie between desugaring and codegen, and remove all special cases that are currently present for typeclass dictionary values.

To do this, we'll also want to be able to specify the names of fields within a `Constructor` for preserving readability in the generated code.

**Comment by garyb** [comment]
I've been looking at this a bit, and I'm not so sure it's possible to do this in the `CoreFn` desugaring phase, as the problem is class member accessors are desugared into functions that read from records much earlier on: https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/TypeClasses.hs#L213-L220

It would seem we have to desguar classes into data constructors before typechecking, but that has all kinds of problems of its own (like making externs generation difficult/impossible).

The least bad option I've come up with so far would be to make the member accessors opaque values in the AST (but with the correct `TypedValue` wrapping them), so they can be matched on in `CoreFn` desugaring and then the proper implementation provided there (we do something similar with `TypeClassDictionaryConstructorApp` which was introduced to avoid providing the constructor implementations "too early" also). How do you feel about that?

**Comment by jdegoes** [comment]
> It would seem we have to desguar classes into data constructors before typechecking, but that has all kinds of problems of its own (like making externs generation difficult/impossible).

Can you explain that a bit for my own understanding?

**Comment by garyb** [comment]
Sure thing - at the moment we produce the externs files from the AST that comes out of the typechecker, so if we desugar class declarations into data constructors before typechecking we won't have that information in class form anymore. We could perhaps use `Environment` to produce the externs instead, but that doesn't have information about the exports from each module, so we'd have to do something in combination with the AST.

**Comment by paf31** [comment]
So I generally like using `Environment` for these sorts of things, since it ties the typechecker to one particular type of context, and I have plans to change the context in the long term.

The externs file is really just a representation of the types of whatever is in the source material - just enough to compile without it - so I think it makes sense to create it as close to the source material as possible. Is there any transformation which needs to take place before generating it?

**Comment by garyb** [comment]
You like using `Environment` for that, or dislike?

We need to infer untyped definitions for the externs, but there are no transformations that we'd actually want in there that I can think of, except import desugaring so instances are pulled through. Perhaps we can just take the original parsed AST, replace the imports, and lookup the types for members that didn't have an explicit type.

**Comment by paf31** [comment]
Sorry, s/like/dislike.

**Comment by paf31** [comment]
@garyb Do you think it's possible / makes sense to do this in 0.11?

**Comment by garyb** [comment]
Assuming my hack to work around https://github.com/purescript/purescript/pull/2205#issuecomment-238035902 will work (the hack being to generate code with a `case` rather than a basic lambda) then yeah, should be able to :)

**Comment by paf31** [comment]
@garyb Sorry, I do mean to come back and take a look at that issue soon.

**Comment by JordanMartinez** [comment]
I think this was closed by #4125...

**Comment by rhendric** [comment]
I guess that depends on whether anyone (and by ‘anyone’ I think I mean just @garyb) plans on doing anything further on this.

**Comment by garyb** [comment]
Yeah, I'm fine with closing it now :+1:. We might need to revisit in the future if we add optimisations that would benefit a non-record representation, but mainly I'm glad we're now reusing machinery that already existed rather than having a bunch of special stuff that ended up equivalent to a record at the end.
