### ISSUE TITLE
Commit to types of let-bound names in psci

### ISSUE THREAD

**Issue by vkorablin** [purescript/purescript#782]
tl;dr -- interactive evaluation in PSCI can sometimes clobber types of unrelated values

Minimal test case:
```
module Bug where
    newtype Const a b = Const a
    instance functorConst :: Functor (Const a) where
                    (<$>) fn (Const x) = (Const x)

    a = Const 1
    b = (&&) false <$> a
```

Load this file into PSCI:

```
> :m Bug.purs
> :i Bug
Compiling Prelude
Compiling Prelude.Unsafe
Compiling Data.Function
Compiling Data.Eq
Compiling Control.Monad.Eff
Compiling Control.Monad.Eff.Unsafe
Compiling Control.Monad.ST
Compiling Debug.Trace
Compiling Bug
> :t a
forall t21. Bug.Const Prim.Number t21
> :t b
Bug.Const Prim.Number Prim.Boolean
> let b = (&&) false <$> a
> :t a
forall t21. Bug.Const Prim.Number t21
```

So far so good. If, however, we assign `a` and then `b` *interactively*:

```
> let a = Const 1
> :t a
forall t19. Bug.Const Prim.Number t19
> let b = (&&) false <$> a
> :t a
Bug.Const Prim.Number Prim.Boolean <-- !!!
```

Oops! `a`'s type has changed after we evaluated something completely different! And they said Purescript didn't have uncontrolled side effects. :)

This happens only in PSCI; ahead-of-time compilation is ok, as can be seen in the first part of the transcript.

**Comment by paf31** [comment]
I've changed the title to reflect the fix that I think this issue needs. We should type check the let bound name, and commit to the chosen type by artificially adding a type annotation.
