### ISSUE TITLE
Specify package bounds for all dependencies

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#783]

**Comment by aspidites** [comment]
Are we talking about the purescript.cabal file here? Are you expecting that whoever does this manually fiddle with version numbers until they find the lowest/highest numbers that don't break?

**Comment by paf31** [comment]
Yes, that was the plan. We should try to add conservative bounds which are known to work. About 50% of dependencies have bounds at this point, I think. `cabal freeze` would be one solution, but that's too restrictive.

**Comment by aspidites** [comment]
Ok. I'll mess with this in between homework assignments when I need a change of scenery.

**Comment by paf31** [comment]
I think Stackage solves this now. Closing.
