### ISSUE TITLE
Type wildcards don't work in record or row extension.

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript#788]
Simple example:

```purescript
module Wild where

  type Foo = { | _}
```

Gives:

```
➜  purs  psc wild.purs
Error at wild.purs line 3, column 3 - line 4, column 1: 
Error in type synonym Foo
Type variable _ is undefined
```

**Comment by paf31** [comment]
Fixed by https://github.com/purescript/purescript/commit/f7685450f21f5e91406ddf0ef7aeea4ffc567ff7

**Comment by joneshf** [comment]
Cool. Any ideas when we might get a new version? There's been a whole bunch of changes.

**Comment by paf31** [comment]
Good point, I'll try to make a release soon.
