### ISSUE TITLE
Pass node flags to psci

### ISSUE THREAD

**Issue by MichaelXavier** [purescript/purescript#793]
Since psci starts up a node process, there should be a way to delegate flags to the node process by invoking psci. I can see 2 ways of doing this:

1. Any unknown flags can just go to the node executable.
2. Any flags after a `--` go to the node executable.

I personally vote for option 2, as it is a more deliberate action from the user.

**Comment by MichaelXavier** [comment]
So I've got a prototype of this implemented here:
https://github.com/MichaelXavier/purescript/compare/psci-node-flags?expand=1

 A couple notes:

1. Because of the way optparse-applicative works, I have to take the rest of the arguments list as files and sort them out as files vs node arguments later, so the auto-generated cli docs don't mention this new feature. We could add it in long form, add it to some corner of the wiki. We could also add it as the metavar name, i.e. FILE_OR_NODE_FLAG but that seemed really clumsy for a feature you usually won't need.
2. I didn't add tests here. I couldn't find any test infrastructure for this sort of thing.

**Comment by paf31** [comment]
Cool :)

The `--` trick seems like a bit of a hack though. What about just specifying an option like `--node-opts`?

**Comment by MichaelXavier** [comment]
Would you specify them as an argument? `--node-opts="--foo --bar"? I could go for that.

**Comment by paf31** [comment]
Yes, I think so.

**Comment by MichaelXavier** [comment]
Ok. Please have a look now and let me know what you think.

**Comment by paf31** [comment]
Sorry, I completely missed this. It looks good - could you make a PR?

Also, could you please remove the call to `traceShow`.

One thing I'm wondering - as we add these configuration options, it probably makes sense to break out a `Config` type and use `ReaderT`, or even `RWS`.
