### ISSUE TITLE
Difficulties with the type checker on a specific issue.

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript#795]
I can't get https://github.com/jutaro/purescript-webgl to compile examples/Main.purs. 

What I try is to refactor the working examples/Example7.purs code, so that I don't
repeat the bindings declarations in data State, but instead use one bindings field in the State datatype.
I can't get this to compile. 

It should be noted that the withShaders function adds the webGLProgram field to the bindings:
withShaders :: forall bindings eff a. Shaders (Object bindings) -> (String -> EffWebGL eff a) ->
                ({webGLProgram :: WebGLProg | bindings} -> EffWebGL eff a) -> EffWebGL eff a

The commit is 0a4b3ef from Jan 5, 2015

**Comment by jutaro** [comment]
As I reported in the chat, I tried again with the new compiler version. After commenting out some lines of code I get this error message: Cannot unify ( | Main.MyBindings<>) with ( | Main.MyBindings<>).
So it really smells like a bug and not like an error on my side. It's a problem with compiling the "examples/Main" file. It should be as simple as calling grunt, to get to the error.

**Comment by paf31** [comment]
Is there any chance you could provide some code, here in the issue, as a self-contained test case?

**Comment by jutaro** [comment]
Ok, I will try.

**Comment by jutaro** [comment]
Ok, here is a rather useless code snippet, but it produces the same typechecker error:

~~~
module Main where

import Control.Monad.Eff
import Control.Monad.ST

type State bindings =
  {
    bindings :: {addition :: Number | bindings},
    other :: String
  }

type MyBindings = (test :: Number)

data Shadow bindings = Shadow String

shadows :: Shadow (Object MyBindings)
shadows = Shadow "uhh"

main :: Eff () Unit
main = withIt
          shadows
            \ bindings -> do
                let state =
                  {
                      bindings : bindings,
                      other : "Test"
                  }
                runST do
                  stRef <- newSTRef state
                  handleKeyD stRef
                  return unit


withIt :: forall bindings eff a. Shadow (Object bindings) ->
                ({addition :: Number | bindings} -> Eff eff a) -> Eff eff a
withIt (Shadow str) success = do
  b <- withBindings
  success (b{addition : 1})

foreign import withBindings
"""
        function withBindings() {}
""" :: forall eff bindings. Eff eff bindings

handleKeyD :: forall h eff. STRef h (State MyBindings) -> Eff (st :: ST h | eff) Unit
handleKeyD state = return unit
~~~

**Comment by paf31** [comment]
Thanks. Do you mind if I use this code as a test case?

**Comment by jutaro** [comment]
Of course, please use it if it helps.
