### ISSUE TITLE
In-memory modules in psci prevent out-of-date code from being rebuilt

### ISSUE THREAD

**Issue by fosskers** [purescript/purescript#796]
New to Purescript.

I'm following the book, and have an okay workflow. However, when I write a new function in a module that's also loaded in psci and give it an `:r`, then call `FooModule.barFunc` psci will:

* Tab-complete on the name of the function, but;
* Die with:
```
Error at  line 1, column 1 - line 2, column 1: 
Error in module $PSCI
Unknown value 'FooModule.barFunc'
```
Occasionally after much `grunt`'ing and `:r`'ing, it might actually run the new function, but any other new ones I write will be invisible yet visible to psci as described above.

What am I doing wrong?

**Comment by joneshf** [comment]
Are you loading the module first, either by passing the path to psci or with `:m <path>`? Can you provide an example?

**Comment by fosskers** [comment]
Well the book/tutorial implies that by having the proper code in one's grunt file:

```javascript
// stuff above
dotPsci: ["<%=srcFiles%>"],
// more settings in between
grunt.registerTask("default", ["psc:all", "dotPsci"]);
```
that `psci` will "know what to do" with your module so you don't have to reload it all the time. I can confirm this works because by opening `psci` in the top project directory all the functions are visible.

Just now I did some testing, and the bottom-most function was visible yet uncallable like above. Then I added a new one, `grunt`'d, reopened `psci` and both are visible and callable now. Then without closing `psci`, I added another function, `:r`'d, and that one is visible/callable too. Meaning the problem went away spontaneously...

**Comment by joneshf** [comment]
Oh, it was probably a cache issue.

**Comment by paf31** [comment]
Is this fixed?

**Comment by fosskers** [comment]
I'll be doing more testing tonight. I'll let you know.

**Comment by fosskers** [comment]
No it doesn't seem to be. For the record, I'm testing with the following function:
```haskell
fact :: Number -> Number
fact 0 = 1
fact 1 = 1
fact n = fact (n-1) + fact (n-2)
```
I have three windows open: an editor, a terminal for grunting, and psci. Running `fact 5` produces 8 as it should. Then I change the case `fact 1` to equal some large number. If I save and grunt again, then run `fact 5`, the output is huge as it should be. Now, if I change the value back, save, grunt, and try again, the output is still huge, even if I change input values. Furthermore, in my tests just now, leaving psci, regrunting and reopening psci still results in huge output.

Any ideas?

**Comment by fosskers** [comment]
We discussed this on IRC. What we're seeing:

* Changes are made in the `.purs` file, psci claims to be recompiling, by the "compiled" `.js` in `.psci_modules` doesn't reflect the change.
* (Seemingly) randomly a recompile will succeed in updating to the new value.
* Relaunching `psci` doesn't change anything (and it wouldn't, considering the compiled `.js` isn't changing).

**Comment by paf31** [comment]
IRC notes so I don't forget:

```
if you write the file, then do a ':r', then rerun your command, it should work
the issue is this:
the parsed modules are kept in memory
and what's in memory is not necessarily what's on disk
so we can get into a state where the js file is more recent than the purs file, but we compiled from the older source which was in memory
```

**Comment by paf31** [comment]
Maybe the answer is to just reparse from disk each time, instead of keeping modules in memory.

**Comment by fosskers** [comment]
This occured to me in a fevor dream last night: would reparsing on `:r` not work just as well? That would put it in line with `ghci`.

**Comment by paf31** [comment]
Potentially, but it would require some bigger changes, since `psci` uses the same approach as `psc-make`, just comparing timestamps.
