### ISSUE TITLE
Cannot import unknown module 'Math'

### ISSUE THREAD

**Issue by ltfschoen** [purescript/purescript#797]
I have been thoroughly applying the code examples in the [PureScript By Example Functional Programming for the Web By Phil Freeman](https://leanpub.com/purescript) book to my GitHub Public Repo [here](https://github.com/ltfschoen/PureScriptByExample). I am only up to Page 13 in the book.

I have extended the code by applying a combination of not just ```psc```, but also ```pscMake```, with separate source files for the LSHello (i.e. simply outputs Hello World!) and the LSMath modules.

To run my code, the user simply needs to clone my repo, then run:
```
npm install
bower update
grunt
node dist/Main.js
```

Currently the LSHello (Hello World!) module works when I build it with ```grunt``` and execute it with ```node dist/Main.js``` in isolation, but when I instead try to build the LSMath module (whether in isolation, or together with LSHello) I get the following error (see screenshot below):
![screen shot 2015-01-07 at 8 18 49 am](https://cloud.githubusercontent.com/assets/6226175/5636403/e493a02a-9645-11e4-8067-52a0c44713a4.png)

The error appears similar to the problem encountered in Issue #626, however I am already using ```bower update``` to use Bower to install the dependency ```"purescript-math": "0.1.0"``` [here](https://github.com/ltfschoen/PureScriptByExample/blob/master/bower.json#L11) contained in my bower.json file, which causes the library to be installed in the directory bower_components/purescript-math (noting that if I change this line of code to ```"purescript-math": "*"```, it will do the same thing and install version 0.1.0 too, so i'm just being explicit in requesting this version).

To try and see if I could import other libraries similar to purescript-math other than the Prelude (i.e. Data.Trace) without encountering this error, I tried adding the purescript-geom Library, which is recommended at [PureScript Recommended Libraries](https://github.com/purescript/purescript/wiki/Recommended-Libraries) to my bower.json file. purescript-geom is created by Bodil who showcased [PureScript (Maybe This Time We Get JavaScript Right)](https://www.youtube.com/watch?v=yIlDBPiMb0o)). After adding it to my bower.json file I performed ```bower update``` (noting that purescript-geom uses purescript-math as a dependency), and then attempted to import it into the LSMath module with ```import Geom``` and ```import Data.Geom```, but doing this also gave me errors ```Cannot import unknown module 'Geom'``` and  ```Cannot import unknown module 'Data.Geom'``` respectively (perhaps I am not providing the correct library name to importing this library without an error though...)

I've run out of ideas, any help would be greatly appreciated!!

**Comment by paf31** [comment]
In `Gruntfile.js`, your `psc` target only references `srcFiles`, but you need to include the Bower dependencies as well. These currently only appear in `libFiles`.

**Comment by paf31** [comment]
Also, thank you for the effort on the GitHub repo. That looks like the sort of thing that would help beginners to get started quickly.

**Comment by ltfschoen** [comment]
Thanks @paf31 for your help so far, I incorporated your suggestions in this [commit](https://github.com/ltfschoen/PureScriptByExample/commit/fe9d1bc586e8e08341f67c868c03b4e9552ca270) and it's solved most of my problem. Now when I run ```grunt``` the Main.js file is correctly converting the PureScript source and library files (i.e. standard Prelude, Math, Debug_Trace, LSHello, LSMath) into namespaces of equivalent JS functions (see extract below with the contents of the namespace blocks removed for brevity). 

**Extract of Main.js**
```var PS = PS || {};
PS.Prelude = (function () {
...
})();
var PS = PS || {};
PS.Math = (function () {
...
})();
var PS = PS || {};
PS.Debug_Trace = (function () {
...
})();
var PS = PS || {};
PS.PureScriptbyExample_Chapter2_LSHello = (function () {
...
})();
var PS = PS || {};
PS.PureScriptbyExample_Chapter2_LSMath = (function () {
...
})();
PS.PureScriptbyExample_Chapter2_LSHello.main();
```

However, the bottom of the Main.js file that is generated only contains a single call to ```PS.PureScriptbyExample_Chapter2_LSHello.main();```, so with this, when run ```node dist/Main.js``` it executes only the Module named "PureScriptbyExample_Chapter2_LSHello", which outputs to console ```Hello, world!```. In order to run both of the Modules sequentially, I need to manually append an additional line at the bottom of Main.js ```PS.PureScriptbyExample_Chapter2_LSMath.main();```, so when I then run ```node dist/Main.js``` it outputs to console:
```
Hello, world!
5
```
Is there a way to automatically generate calls to all the JS namespaces that represent each of the custom Modules that are defined within the Gruntfile.js section grunt.initConfig > psc > options > modules)?

Also, what is an example of an approach used to perform a call to execute one of the other PureScript "module" files (since we can define an array of them) from the "main" PureScript Module file?

**Comment by paf31** [comment]
I think the simplest way, without Grunt trickery, would be to just write a `Main` module which calls all the top-level functions you want to call, and then to use that module as the entry point.

**Comment by ltfschoen** [comment]
Thanks for your help and advice @paf31, I'm enjoying your book and I'll try that approach soon.
