### ISSUE TITLE
Parse markdown in embedded documentation

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#802]
Doc strings will be indicated in comments by a pipe at the start of each line. The pipe character will be used to disambiguate indentation in mixed-mode comments. Content to the right of the pipe will be markdown, to be inserted into generated documentation in `psc-docs`.

```
-- | Create a copy of the array without its first element.
-- |
-- | Running time: `O(n)`, where `n` is the length of the array.
-- |
-- | This function is partial. Specifically, `tail []` is undefined.
tail :: forall a. [a] -> [a]
```

**Comment by jdegoes** [comment]
:cupid:

**Comment by joneshf** [comment]
i assume this extends to block comments? Do they have to be indented to the same level or how does that work?

**Comment by garyb** [comment]
I proposed it this way just working for single line comments, but I guess it could work for blocks too. The idea is the first `|` on a line denotes the start of the line for markdown purposes, as it has significant whitespace for code blocks and the like.

**Comment by paf31** [comment]
Yep, just to clarify my intentions, `|` would be used in both block comments and line comments. Right now, all comments just get crushed into a single string, so we could split into lines, and look for `|` markers.

**Comment by paf31** [comment]
I think `cheapskate` might be a good library to use, since we would be able to generate something using its AST, which would make composition of documents simpler, and therefore improve the formatting of things like comments.

**Comment by paf31** [comment]
Huh, `cheapskate` doesn't have a pretty printer (only HTML support), so maybe this doesn't work.

**Comment by paf31** [comment]
What about changing `psc-docs` to generate HTML documentation? We could even generate one page per module and one detail page per function/type/whatever with links. Markdown autolinks could be used for references between pages.

**Comment by michaelficarra** [comment]
But I prefer including the generated output as a markdown file in github so that it is rendered inline in the repo. HTML would not have that same benefit.

**Comment by garyb** [comment]
HTML output would be nice, but I'd tend to agree having Markdown rendering is more beneficial given that we're hosting everything on Github.

Is there not an alternative markdown library we can use?

**Comment by paf31** [comment]
Yes, that is a definite disadvantage. The alternative could be to configure the repo to serve HTML under `gh-pages` though..

**Comment by paf31** [comment]
If someone can find a Markdown library in Haskell which will parse _and_ pretty print, then let's use it. 

Pursuit only needs to parse and render as HTML, so it's a bit simpler.

**Comment by garyb** [comment]
I guess depending on pandoc is a tad heavyweight? ;)

**Comment by paf31** [comment]
Heavyweight, but also it is GPL-licensed which might make things tricky.

**Comment by paf31** [comment]
Unless we want to move to GPL of course.

**Comment by garyb** [comment]
Ah good point. I think I'd rather stick with MIT/BSD style, personally.

**Comment by paf31** [comment]
Agreed.

**Comment by paf31** [comment]
One option for `psc-docs` is that we just paste the text right of the pipes directly into the generated markdown. Pursuit can do something more involved using e.g. `cheapskate`, to render nicely formatted HTML. 

Ideally I would like to do things like tidy up the header levels, but it's not the end of the world. 

I might work on a separate HTML documentation generator.

**Comment by jdegoes** [comment]
Pursuit could also use purescript-markdown to render Markdown on the client-side. :)

**Comment by paf31** [comment]
I considered that too :)

I'm thinking that Pursuit should start serving static content though (for the newer features, not the search page).
