### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#803]
The type checker monad only supports errors, not warnings. Use `WriterT` to add a warnings capability.

**Comment by hdgarrood** [comment]
Refs #33?

**Comment by garyb** [comment]
I think #33 should raise errors rather than warnings actually.

**Comment by nicodelpiano** [comment]
Hello, is it correct to think that the solution will be something alike?
```
newtype Check a = Check { unCheck :: StateT CheckState (WriterT MultipleWarnings (Either MultipleErrors)) a }
```
where MultipleWarnings depends on creating a new environment for warnings as errors have.
As WriterT is a monad transformer, this attachment to the type checker monad will give warning capability.

**Comment by paf31** [comment]
Yes, but we might want to put `WriterT` inside `ErrorT` so that we still get warnings in the case when an error occurs (I _think_ that's the right way round).

If you're interested in working on this, you could pick one or two very simple warnings to begin with, so that we at least have a place to add new ones as we think of them. Some ideas:

- Name in binder shadows existing name
- Type variable got shadowed
- Unused name in binder
- Unused type variable

**Comment by garyb** [comment]
> (I think that's the right way round)

I'm glad it's not just me :) always takes me a bit of trial and error to work out which way to layer transformers.

**Comment by paf31** [comment]
I think of it this way: `ErrorT` of `m` just replaces the result type `a` inside `m` with `Either e a`, so wherever you would previously return a result, you can now instead return an error. 

Similarly, `WriterT` replaces `a` with `(a, w)`.

So if you put `WriterT` on the outside and fail, you don't get the warnings you accumulated, but if `ErrorT` wraps `WriterT`, you essentially replace `a` in `(a, w)` and get `(Either e a, w)`.

**Comment by nicodelpiano** [comment]
You are right, but `WriterT` needs a monad as a second parameter which will be transformed to add the desired capability.
The signature of `WriterT` is `WriterT w m a`, where `w` is the type of the data we want to accumulate, and `m` is the monad which will be wrapped.
I can't figure out what is the base stack monad (`m`) which we may refer here (I thought it was `ErrorT`)

Also I've been working in a new module to handle warnings. It's basically the same as errors have. I'll make a pull request.

**Comment by paf31** [comment]
@nicodelpiano What I'm suggesting is

```purescript
newtype Check a = Check { unCheck :: StateT CheckState (ErrorT MultipleErrors (Writer MultipleWarnings) a } deriving ...
```

**Comment by paf31** [comment]
Here is a good candidate for a warning to implement:

- Cons patterns are deprecated
