### ISSUE TITLE
@ as an operator no longer works in 0.6.3

### ISSUE THREAD

**Issue by fluffynukeit** [purescript/purescript#815]
I'm writing a library that uses the @ symbol as an operator.  This worked in 0.6.1.  I just upgraded to 0.6.3 and get the following error.  It appeared at export, and when I removed the export of @, it appeared at the declaration, then at the infixl line; just went down the file complaining any time @ was used in an operator context.
```
unexpected @
expecting symbol
```
I can work around it by changing the operator to something else, but I'd like to know if this is a bug in 0.6.3 or desired behavior moving forward in releases.  Thanks.

**Comment by paf31** [comment]
I think we can handle this in the same way that we handle `:` as an operator.
