### ISSUE TITLE
Module defined multiple times?

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#818]
This was working fine with previous PSC builds, but the latest one throws the following error:

```
Module 'Context' has been defined more than once
```

I am fairly sure that `Context` is not defined multiple times. Because the only thing that changed here was the compiler version, it seems most likely a compiler bug (either unintended behavior or an incorrect error message).

https://travis-ci.org/Fresheyeball/purescript-context

**Comment by paf31** [comment]
This is because you have a cyclic dependency. `purescript-context` is in `bower_components`.

**Comment by Fresheyeball** [comment]
Oh snaps! I see it now! My testing libs depend on the lib I'm testing. Thanks @paf31!
