### ISSUE TITLE
Division where denominator is a parenthesized product yields wrong value

### ISSUE THREAD

**Issue by Garciat** [purescript/purescript#819]
> 1 / (2 * 2)
    
    1

psci 0.6.3

**Comment by paf31** [comment]
Another operator precedence issue. Could you please try master?

**Comment by Garciat** [comment]
Just tried master and the bug is not there. Should've tried master from the beginning, sorry!

**Comment by paf31** [comment]
No, thanks very much. This only got fixed a few days ago.

**Comment by michaelficarra** [comment]
https://github.com/purescript/purescript/pull/804
