### ISSUE TITLE
Existential Types

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#82]
Syntax: `exists a. ...`

**Comment by paf31** [comment]
If we implement polykinds, the `purescript-exists` solution is as general as we need, and we should close this. 

If not, we need to implement some sort of syntactic instruction to the type checker to unpack an existentially-typed package, since expressions like `e.x e.y` don't get well typed when `e` has type `exists a. { x :: a -> b, y :: a }`, for example, since we need to skolemize twice, once for each subexpression. Instead, we can check something like `unpack e as e' in e'.x e'.y` easily, since we only have to skolemize once.

**Comment by garyb** [comment]
I'd be totally happy with having polykinded `Exists` as a solution to this, personally.

**Comment by paf31** [comment]
Polykinded exists seems like a better solution for the reason given above. Closing.
