### ISSUE TITLE
First class labels

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#823]
I'd like to implement something like http://research.microsoft.com/pubs/64501/fclabels.pdf

There's lots to be done first though, most importantly improving the constraint solver.

**Comment by jdegoes** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Fresheyeball** [comment]
So the idea here is that labels are now a type and can be passed as an argument? Or that labels can have different types?

**Comment by paf31** [comment]
Well, there would be a _kind_ of labels, let's call it `L`, and a type constructor `Label :: L -> *` which can be used to represent labels as values (pass them to functions, etc.) At runtime, they would probably be strings.

**Comment by desmond-dsouza** [comment]
:+1: Just wondering if this is any closer on the planning horizon?

**Comment by paf31** [comment]
I've been thinking about it a bit lately, but I don't have a clear path in mind yet. This will probably happen sometime after the new type checker is implemented.

**Comment by LiamGoodacre** [comment]
:+1: :+1: very cool
