### ISSUE TITLE
Variable named 'undefined' disappears in generated code

### ISSUE THREAD

**Issue by philopon** [purescript/purescript#824]
Hi!

this Reproducing code

```.purs
module Test where

import Control.Monad.Eff

foreign import valid     :: forall a. a

foreign import undefined :: forall a. a
foreign import null      :: forall a. a

testValid :: Eff _ _
testValid = return valid

testUndef :: Eff _ _
testUndef = return undefined

testNull :: Eff _ _
testNull = return null
```

generates

```.js
...
    var testValid = Prelude["return"](Control_Monad_Eff.monadEff)(valid);
    var testUndef = Prelude["return"](Control_Monad_Eff.monadEff)();
    var testNull = Prelude["return"](Control_Monad_Eff.monadEff)($$null);
...
```

I think case of `undefined` and `null` isn't prospective behavior. I think it should generate

```.js
    var testUndef = Prelude["return"](Control_Monad_Eff.monadEff)(undefined);
    var testNull = Prelude["return"](Control_Monad_Eff.monadEff)(null);
```

or report compile time error.

Regards

**Comment by paf31** [comment]
What error would these report? `null` and `undefined` are keywords, so they get escaped.

**Comment by paf31** [comment]
Oh, but `undefined` disappearing definitely _is_ a bug.

**Comment by garyb** [comment]
That's an optimisation that came about when we got rid of applying `{}` in all the typeclass code.

**Comment by philopon** [comment]
> null and undefined are keywords

Yes, I understand it. but, I think

* `foreign import null :: forall a. a` seems like importing javascript null keyword.
* escaped `foreign import null` is useless(I must know mangling rule to use it).

so, I reported `null` case.

**Comment by paf31** [comment]
@garyb But undefined should be escaped here, and then not removed.

**Comment by garyb** [comment]
Ah yep, I'm not saying it's not a bug, just explaining how it's happening.

**Comment by garyb** [comment]
This is no longer an issue, I think we fixed it quite a while back actually - the FFI changes would have done it.

**Comment by paf31** [comment]
The generated code is now

```purescript
exports["null"] = $foreign["null"];
exports["undefined"] = $foreign.undefined;
```

which works when run, but seems a bit ... dodgy. Should we escape `undefined` like `null` here?

**Comment by garyb** [comment]
It's ok if we're assuming ES5, and in fact we don't have to escape a bunch of stuff that we do now if we assume ES5 - I can put a fix in if we'd prefer to escape it though? (I did that before even checking what the output was doing, so the branch is ready to go :wink:)

**Comment by paf31** [comment]
I think we should probably be consistent between `null` and `undefined`, that's all. And if we can only assume ES3, that's nice too.

**Comment by michaelficarra** [comment]
There's no need to escape `undefined`, even in ES3. `null` has always been a reserved word, and `undefined` has always been a regular old identifier. All browsers have supported this, as far back as anyone cares.

@garyb: don't forget about https://github.com/purescript/purescript/pull/855/files#r24418039.
