### ISSUE TITLE
utf8-string IO Wrappers deprecated

### ISSUE THREAD

**Issue by aspidites** [purescript/purescript#825]
Since GHC supports UTF-8, System.IO.UTF8 no longer exists. The quick fix would be to put an upper bound on utf8-string. The better fix is to update code so that it doesn't use these wrappers anymore. 

See [here](https://github.com/glguy/utf8-string/commit/31969fdecdab5b0d3732f15937886df2d3d7522e) for more details.

**Comment by paf31** [comment]
Thank you very much for pointing this out.

**Comment by aspidites** [comment]
No problem. removed comment about me working on it as I can't seem to get psc to function properly at the moment. Running `psc` by itself simply spits out javascript. `psc --help` seems to work, though.
