### ISSUE TITLE
Add <**> as flipped <*> to Prelude

### ISSUE THREAD

**Issue by reuben364** [purescript/purescript#830]
Currently in the prelude the application related operators $ and <$> have flipped operators # and <#>. In order to maintain this pattern, should <*> not have a flipped operator too?

**Comment by paf31** [comment]
Possibly. Is there a good use case for this?

**Comment by reuben364** [comment]
Just like in cases where it is more readable to have backwards function application such as

    b # a # f

someone might find it more readable to have their applicatives backwards too

    b <**> a <#> f

though I admit it is a stretch considering you'll only use the <**> when you are using two arguments in backwards order.
Like all operators of the sort, someone will eventually find some black magic to perform with it.

**Comment by michaelficarra** [comment]
`#` is less often used infix. It is partially applied and passed to other higher order functions. I don't see the same happening with this operator very often.

**Comment by paf31** [comment]
I think I'd prefer to wait until someone needs this before we add it, especially to the Prelude.

**Comment by michaelficarra** [comment]
Move to https://github.com/purescript/purescript-prelude?

**Comment by paf31** [comment]
@michaelficarra I think so.
