### ISSUE TITLE
Add a note about Ubuntu's `node` package issue ghosting `nodejs`.

### ISSUE THREAD

**Issue by spearsem** [purescript/purescript#832]
E.g.: < http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04 >

Since there is an Ubuntu package called `node`, `nodejs` installs to the executable name `nodejs`. You have to manually uninstall `node` and then symlink `nodejs` to `node` (and possibly also run `hash -r` to ensure it is picked up by `sbin` as well).

When working through the PureScript tutorial on Ubuntu 14.04, this created problems for me. Installing `grunt` appeared to work, but because it was calling the other package's `node` executable, nothing seemed to work when I actually needed to run `grunt` to follow along in the tutorial.

This is fixed by uninstalling `node` and then symlinking as the link above suggests.

It would be very helpful to add a note or link about this somewhere in the tutorial documentation around the portion where installing `nodejs` is described.

**Comment by joneshf** [comment]
It'd also be nice to have a quick link somewhere in the wiki, which I believe you can create without needing special privileges.

**Comment by paf31** [comment]
This code should handle both names:

https://github.com/purescript/purescript/blob/master/psci/Main.hs#L114

Is it not working?
