### ISSUE TITLE
Extended infix expressions

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#839]
Another wacky idea. There isn't a reason that I can think of why we limit infix expressions to simple names. Why not allow things like:

```purescript
john `comparing height` jack
```

or

```purescript
list1 `zipWith f` list2
```

This seems useful when you have functions of > 2 arguments which read naturally when written infix.

**Comment by michaelficarra** [comment]
:+1:

**Comment by garyb** [comment]
That's pretty interesting. Backticks could be used to infix any expression then? Like:

```purescript
list1 `zipWith (f true)` list2
```

I guess that would still play fine with operator sections too, although it might get a bit weird if misused:

```purescript
xs `(`f (g true)` ys)` zs
```

**Comment by paf31** [comment]
There's a definite possibility of abuse :)

**Comment by garyb** [comment]
I guess one "problem" with this is the inability to specify fixity for arbitrary expressions. We currently can't declare fixity for named functions anyway, unlike Haskell, but assuming we could there would be a few things to figure out here (like in the applied-`zipWith` example, would it take the fixity from `zipWith`, if so, how about `f` in the silly example?)

**Comment by paf31** [comment]
Another option is to only allow fixities for names, and to default to `infixr 5` or whatever we have now for everything else.

**Comment by aspidites** [comment]
This reminds me of Bash. Didn't they eventually deprecate backtick syntax for `$()`? Not knocking the idea, just noting historical precedence as a point of concern.

**Comment by jdegoes** [comment]
I like using backticks to "infix" any suitable expression. It just feels more consistent.

**Comment by paf31** [comment]
I'm going to implement this. We can label it as "experimental", see how people like it, and if it gets abused and remove it if necessary.

**Comment by AppShipIt** [comment]
> ```xs `(`f (g true)` ys)` zs```

I just tried the recursive version and doesn't appear implemented. (Thankfully?) Even non-recursive seems like it could encourage avoiding `let`/`where`. Has anyone been used this?

**Comment by natefaubion** [comment]
I use it in psa to do an adhoc ZipArray Applicative. https://github.com/natefaubion/purescript-psa/blob/master/src/Psa/Printer/Default.purs

**Comment by AppShipIt** [comment]
@natefaubion That particular case actually seems like a helpful place to have `where invokeArray = zipWith ($)`. Have you liked it? When I consider syntax I tend to imagine approaching someone's code I have stylistic differences with (hello consulting).

**Comment by natefaubion** [comment]
Eh, sometimes things aren't really worth naming. As far as the syntax, I could take it or leave it.

**Comment by garyb** [comment]
I'd say it's been pretty succesful. I've not seen any abuse anyway, it's mostly used for the `zipWith` kind of case, and I think that it's a win there.

I wouldn't use a `let` or a `where` without this option either, I'd just write it as `zipWith ($) x y` as I agree it's not worth naming / tricky to name clearly, more so than reading the definition.

**Comment by AppShipIt** [comment]
In that case I'll add it to documentation soon.
