### ISSUE TITLE
MacOS Package

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#840]
Unashamedly cribbed from the Idris repo:

```
cabal configure --prefix=/usr/local
cabal build
cabal copy --destdir=/tmp/purescript/
pkgbuild --id org.purescript --root /tmp/purescript/ purescript.pkg 
```

will build a package which will give a nice installer wizard on MacOS. Not sure how version-dependent the installer is though.

**Comment by joneshf** [comment]
Is `pkgbuild` an osx command?

**Comment by garyb** [comment]
Yeah, it comes with Xcode.

**Comment by paf31** [comment]
I tried this and ran into versioning errors. With Homebrew being supported now, I think I can close this.
