### ISSUE TITLE
psc main flag no longer works

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#849]
`psc` has a `--main` flag, but when I try to use it, the argument is being treated as a file. I believe this is due to #736. A current workaround is renaming my main module to `Main`.

**Comment by paf31** [comment]
The usage has changed to

`psc --main=MyModule`

as of (I think) 0.6.3. Note the `=`.

**Comment by michaelficarra** [comment]
Okay, then the `--help` text should change. It currently contains `--main ARG`. But I really prefer the old usage.

**Comment by paf31** [comment]
Interesting. This seems like an `optparse-applicative` bug then unless I'm missing something.

**Comment by paf31** [comment]
Closing since this seems to be a library issue.

**Comment by michaelficarra** [comment]
Why close it then? It's still a bug. Either we track an open downstream issue or we fix it on our end somehow. But closing is the wrong move.

**Comment by paf31** [comment]
Yes, let's please track it downstream.

**Comment by michaelficarra** [comment]
This is no longer an issue as of 0.7.
