### ISSUE TITLE
Document all Prelude functions

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#852]
The generated markdown docs now contain code comments, so we should start documenting all public functions in the core libraries. The Prelude would be a good place to start.

This involves a bit of work, but would be a fantastic contribution for any beginners.

**Comment by michaelficarra** [comment]
Weren't we trying to reduce the Prelude as much as possible? If I was to take this on, I would want to know what the plans were for the Prelude first.

**Comment by paf31** [comment]
Well, anything removed from Prelude would move into a core library anyway, and I would like to document those too eventually. The "Prelude" module itself is unlikely to go anywhere though.

**Comment by cschneid** [comment]
Can you point to some example documentation? How do I format the docs, provide examples, links, etc.

**Comment by paf31** [comment]
The plan is to parse comments as markdown if they are indented past a pipe:

```purescript
-- | Map a function over an array
-- |
-- | For example: `map (+ 1) [1, 2, 3]`
map :: forall a b. (a -> b) -> [a] -> [b]
```
