### ISSUE TITLE
Add --no-comments option

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#859]
To squash comments in generated JS.

**Comment by michaelficarra** [comment]
Wouldn't it be a `--comments` option that can be disabled with `--no-comments`?

**Comment by paf31** [comment]
Well, comments are currently on by default, but that could change.

**Comment by berewt** [comment]
What is your preferred option:
- remove them during the generation
- remove them during the pretty printing
- consider comment removal as a JS Optimizer

Although it's not really a code optimization, JS optimizer looks like the better place to implement it.

**Comment by paf31** [comment]
I think I would like to put the changes into the code generator.

**Comment by berewt** [comment]
Ok, I would have to check how to "carry" the no-comments option to the generator then.

**Comment by paf31** [comment]
Just pass the `Options` object along to this function:

https://github.com/purescript/purescript/blob/d683d32aa8ed1cea30354d337bff7d9fac4bb3d6/src/Language/PureScript/CodeGen/JS.hs#L89
