### ISSUE TITLE
Operator sections with identical types type-check differently

### ISSUE THREAD

**Issue by reuben364** [purescript/purescript#862]
According to the REPL the type of both `(+1)` and `(1+)` are `Number->Number`.
The expression `((1+) <$> (1+)) 1` checks out but `((+1) <$> (+1)) 1` does not.

EDIT: I just realized I'm an idiot because
```
let x = (+1)
    y = (+1)
(x <$> y) 1
```
works.
So this is some parsing bug, I think.
Or it's not correctly inferring the Functor instance for (+1)

**Comment by garyb** [comment]
Interesting, as the type of `(+1)` should be `Number -> Number` too...

**Comment by vendethiel** [comment]
should it? I didn't really follow, but is the ambiguity supposed to be determined on the whitespacing (between `+` and `1` ?)

**Comment by garyb** [comment]
Ah, I see you've updated your message!

You could be right about the inference not working out, does `((+1) <$> (+1)) 1` work in `psc` or `psc-make`?

**Comment by reuben364** [comment]
I've found out that directly inputting the lambdas doesn't work either
(\a -> a) <$> (\b -> b)

Error for `(\a->a)<$>(\b->b)`
>Error in declaration it
>Error in expression \b -> b:
>Expr does not have type u1 u2

Error for `((+1) <$> (+1)) 1`
>Error in declaration it
>Error in expression \_1 -> Prelude.(+)(_1)(1):
>Expr does not have type u1 Prim.Number

It doesn't work in psc or psci, and has the same errors in both. At this point I think it is certain that this is the Functor instance not being inferred for lambdas correctly.

**Comment by garyb** [comment]
Thanks, this might well be a typechecker problem then (or current restriction at least), it might be the lack of constraint inference issue again. @paf31 will know better.

**Comment by paf31** [comment]
Yes, the issue is in the type checker. See here https://github.com/purescript/purescript/blob/master/src/Language/PureScript/TypeChecker/Types.hs#L476
It looks easily fixable if someone wants to take a look at it.

**Comment by paf31** [comment]
To clarify, the fix I propose is to replace the check against `p a b` with a check against `f b` where `f` is fresh and gets unified with `p a`. This is not a trivial change though, and needs to be tested well.

**Comment by davidchambers** [comment]
GitHub tip: Rather than link to a specific line of a file in master, press <kbd>y</kbd> while viewing the file to get a permalink which includes the commit hash.

**Comment by paf31** [comment]
:cool: Thanks!

**Comment by reuben364** [comment]
Okay, I tried
```
check' (Abs (Left arg) ret) (TypeApp f retTy) = do
  argTy <- fresh
  f' <- fresh
  f' =?= (TypeApp tyFunction argTy)
  f =?= f'
  let ty = (TypeApp f' retTy)
  Just moduleName <- checkCurrentModule <$> get
  ret' <- makeBindingGroupVisible $ bindLocalVariables moduleName [(arg, argTy, Defined)] $ check ret retTy
  return $ TypedValue True (Abs (Left arg) ret') ty
```

And the inference then works, but Rank2Types are then broken. :-(
But I didn't expect it to be that simple anyway.

**Comment by paf31** [comment]
Try replacing 

```
f' <- fresh
f' =?= (TypeApp tyFunction argTy)
f =?= f'
```

with just

```
f =?= (TypeApp tyFunction argTy)
```

**Comment by reuben364** [comment]
Could tell me what the issue is?

**Comment by paf31** [comment]
The issue is that we need all the information that the type checker has about the function argument type. Simply creating a type fresh and unifying it is not enough if it is polymorphic, we need to know the type annotation that the user provided.
