### ISSUE TITLE
Improvements to record update codegen (use ES5 features)

### ISSUE THREAD

**Issue by fluffynukeit** [purescript/purescript#864]
Similar topic discussed as #234.

In this issue, I'd like to open discussion for two suggested changes to the codegen for record updates.

First, as shown in these [jsperf](http://jsperf.com/object-keys-vs-for-in-and-hasownproperty/7) tests, the current method of for/in with `hasOwnProperty` is consistently the slowest way to copy an object's properties.  Using `Object.keys` in conjunction with a numeric for loop is consistently the fastest or near fastest, sometimes by an enormous margin depending on browser version.  According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) the `Object.keys` method only returns the objects 'own, enumerable properties', so I believe there aren't any problems with using it for the record update implementation instead of the slower implementation now.  The performance improvement might be noticeable when performing many record updates, such as in lens operations.

Secondly, I occasionally look at the generated JS for debugging and understanding PS codegen.  The inlined for loops contribute significant line noise with almost no variation.  I wonder if we can functionize this op to clean up the JS.

**Comment by fluffynukeit** [comment]
With regard to point 2, instead of functionizing the copy, we could still inline it but put the entire implementation on 1 line instead of 6.

**Comment by michaelficarra** [comment]
One thing to consider is that `Object.keys` was added in ES5, but for-in loops are supported by ES3. Is there anywhere else PureScript uses an ES5 feature?

**Comment by garyb** [comment]
The compiler currently generates ES3 code for everything. I guess we could make ES5 the default and add an option for ES3 perhaps.

**Comment by paf31** [comment]
An `--es5` option could be neat. 

Is there any way we can polyfill things for ES3 instead? I know `for...in` isn't likely, but `Object.keys` should be simple enough, right?

If we target ES5, and can consistently recommend polyfills for older environments, I would be happy with that.

**Comment by davidchambers** [comment]
[es-shims/es5-shim][1] might be appropriate.


[1]: https://github.com/es-shims/es5-shim

**Comment by paf31** [comment]
See #916

**Comment by kRITZCREEK** [comment]
Could we close this issue in favor of #916? We could copy over the specifics about record updates being slow into that issue.

**Comment by paf31** [comment]
Yep, thanks.
