### ISSUE TITLE
Revise Num class

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#868]
This could become a huge discussion, but I'll say up front - I don't want to do anything drastic to `Num` all at once.

A very refined type class hierarchy _is_ possible, but I think would be better contained in libraries.

That said, I'm pretty sure `Number` is the only instance of `Num` right now (no `Int` yet, etc.) and I don't think any code uses `Num` in the abstract, so we can change a few things, if we're careful not to break the optimizer.

Here is the current proposal (by @jdegoes):

```purescript
-- addition and multiplication
class Semiring a where 
  (+)   :: a -> a -> a
  zero  :: a
  (*)   :: a -> a -> a
  one   :: a

-- addition, multiplication, and subtraction
class (Semiring a) <= Ring a where
  (-) :: a -> a -> a

negate :: forall a. (Ring a) => a -> a
negate a = zero - a

-- ring with division (possibly non-commutative field)
class (Ring a) <= DivisionRing a where
  (/) :: a -> a -> a

-- definitely commutative field
class (DivisionRing a) <= Num a
```

and in `purescript-monoids`:

```purescript
-- additive monoid
newtype Additive a = Additive a

-- multiplicative monoid
newtype Multiplicative a = Multiplicative a

instance additiveSemiRing :: (SemiRing a) => Semigroup (Additive a) where 
  (<>) (Additive a) (Additive b) = Additive (a + b)

instance additiveMonoid :: (SemiRing a) => Monoid (Additive a) where
  mempty = Additive zero

-- todo: Additive functor, applicative, etc.

instance multiplicativeSemiRing :: (SemiRing a) => Semigroup (Multiplicative a) where 
  (<>) (Multiplicative a) (Multiplicative b) = Multiplicative (a + b)

instance multiplicativeMonoid :: (SemiRing a) => Monoid (Multiplicative a) where
  mempty = Multiplicative one

-- todo: Multiplicative functor, applicative, etc. 
```

**Comment by jdegoes** [comment]
`/` could come from [DivisionRing](http://en.wikipedia.org/wiki/Division_ring), I don't know about `%`. But excepting '%`, this would make `Num` a `Field`, which supports addition, subtraction, multiplication, and division.

**Comment by paf31** [comment]
So the question is, are there any useful `DivisionRing`s which are not `Field`s. If we can find a practical example or two, then sure, otherwise I'm not sure it's worth the complexity. Not that it adds much complexity, but I'm trying to keep things simple, and we can always refine things in libraries.

**Comment by paf31** [comment]
Quaternions?

**Comment by jdegoes** [comment]
Quaternions are very useful in game programming, which is a hot spot of activity for Purescript. :)

**Comment by jdegoes** [comment]
Also, keep in mind that using type classes frees up the operators for other data types that permit operations which share the same algebraic laws.

**Comment by paf31** [comment]
Quaternions is a good enough use case for me.

This seems like a nice split. I'll modify the issue.

**Comment by garyb** [comment]
:+1:

**Comment by Fresheyeball** [comment]
![](http://www.evacohenmedia.com/wp-content/uploads/2013/01/514_230x230_NoPeel.jpg)

**Comment by jdegoes** [comment]
Btw, a field should also support creation of an additive inverse (`neg`), which leads to `-` defined on fields. Albeit there may be some other abstraction that could be used for that, which `Num` could extend.

**Comment by paf31** [comment]
That's `negate` though, right? It would be in `Additive`.

**Comment by jdegoes** [comment]
The problem is semirings do not have additive inverses. An example is a `Positive` newtype, which can implement `+` and `*` with the correct properties, but not `-`.

I have other work to do now but will write up a tiny little hierarchy proposal tonight or tomorrow morning.

**Comment by joneshf** [comment]
What happens to `Semigroup` and friends with this proposal? Are they just additional type classes? It seems a bit off to duplicate the effort of `Semigroup` and `Monoid` in `Additive` and `Multiplicative`

**Comment by paf31** [comment]
Well, an alternative is `Semigroup < Monoid < Group < Ring < Field` but then we lose `Semiring`.

**Comment by Fresheyeball** [comment]
I would prefer that `negate` be alone. I'm starting to think that all type classes representing magma type things should have a single member. If that was so we could make a additional distinction between classes like semigroup that define an operator, and classes like monoid that define a value (even though monoid depends on semigroup).

**Comment by garyb** [comment]
What do you mean? Perhaps I'm misunderstanding but a monoid by definition is semigroup with identity. Also "`zero`-type" classes (like if `Monoid` just had the `mempty` member and no implication) have no laws which is another reason we've avoided them so far.

**Comment by NightRa** [comment]
Also `negate` by itself has no laws. It's the combination of negate with an operation which is meaningful. 
A solution could be creating a `Negate` typeclass which can be only used as a superclass with no direct instances.

**Comment by paf31** [comment]
Well it's idempotent. That's a law :)

**Comment by paf31** [comment]
`negate` definitely belongs in some sort of group type class. Whether we want to break that out of `AdditiveMonoid`, I don't know.

@joneshf As for `Monoid` vs `AdditiveMonoid`, I don't see a good solution since `Number` has at least two monoids on it (that's the whole point, right)? Just like in your algebra package, I think we need to split them. Is there a nice alternative?

**Comment by NightRa** [comment]
Typeclasses with multiple instances is feels very the wrong solution to the problem. Is there some research that tackles this?
As both (+,0) and (*,1) are monoids over Z, and it feels somewhat wrong to not classify them as such in the type system. ()

**Comment by jdegoes** [comment]
Oops, sorry, forgot about this. Here's my proposal:

**Comment by paf31** [comment]
Maybe something like

```
newtype Additive a = Additive a
newtype Multiplicative a = Multiplicative a
class (Monoid a) <= Group a
class (Group (Additive a), Monoid (Multiplicative a)) <= Ring a
class (Ring a) <= Field a
```

?

**Comment by NightRa** [comment]
@paf31 It would make (+) and (*) very hard to use - having to wrap and unwrap around every use of those functions.

**Comment by paf31** [comment]
No, `(+)` and `(*)` have the types I wrote - no unwrapping necessary. Rewrite rules would inline these to regular old `+` and `*`.

**Comment by jdegoes** [comment]
Possibly with typos and bugs:

```purescript
-- addition and multiplication
class SemiRing a where 
  (+)   :: a -> a -> a
  zero  :: a
  (*)   :: a -> a -> a
  one   :: a

-- addition, multiplication, and subtraction
class (SemiRing a) <= Ring a where
  (-) :: a -> a -> a
  
-- ring with division (possibly non-commutative field)
class (Ring a) <= DivisionRing a where
  (/) :: a -> a -> a

-- definitely commutative field
class (DivisionRing a) <= Num a

-- additive monoid
newtype Additive a = Additive a

-- multiplicative monoid
newtype Multiplicative a = Multiplicative a

negate :: forall a. (Ring a) => a -> a
negate a = zero - a

instance additiveSemiRing :: (SemiRing a) => Semigroup (Additive a) where 
  (<>) (Additive a) (Additive b) = Additive (a + b)
  
instance additiveMonoid :: (SemiRing a) => Monoid (Additive a) where
  mempty = Additive zero
  
-- todo: Additive functor, applicative, etc.
  
instance multiplicativeSemiRing :: (SemiRing a) => Semigroup (Multiplicative a) where 
  (<>) (Multiplicative a) (Multiplicative b) = Multiplicative (a + b)
  
instance multiplicativeMonoid :: (SemiRing a) => Monoid (Multiplicative a) where
  mempty = Multiplicative one
  
-- todo: Multiplicative functor, applicative, etc.  
```

**Comment by paf31** [comment]
@jdegoes I like it. Then `Num = Field => DivisionRing`, right?

**Comment by jdegoes** [comment]
The above proposal allows us to, e.g., define `SemiRing`s for things like `PositiveInt`, which permit addition and multiplication but not subtraction, while the splitting out of non-commutative fields in `DivisionRing` permits instances for quaternions (among other things).

Yes, `Num` = commutative `Field` (commonly called a field).

**Comment by NightRa** [comment]
@paf31 Seems like a nice solution to the (+) vs (*) problem!
@jdegoes Right, it makes sense to talk about (+) vs (*) when only both exist.

**Comment by garyb** [comment]
Both of the above would also mean promoting `Monoid` to the `Prelude`, as we only have `Semigroup` there at the moment.

**Comment by jdegoes** [comment]
@garyb Seems like a small price to pay for a useful numeric hierarchy, especially since Prelude will go away at some point (probably before 1.0).

**Comment by garyb** [comment]
Oh sure, I have no problem with it, was just an observation. :)

**Comment by jdegoes** [comment]
Yeah, it will be especially tricky since the compiler is not yet versioned as a dependency in libraries... which means code may break if it uses the new prelude (with monoid) and old Data.Monoid.

**Comment by paf31** [comment]
Well only `Additive` etc. need `Monoid`, and those instances can go in `purescript-monoids`, right?

**Comment by paf31** [comment]
It's just like `Sum` and `Product` now, but more generic.

**Comment by jdegoes** [comment]
True.

**Comment by garyb** [comment]
Ah yep, that should work. Good job too, as otherwise we'd have to make new releases for:

```
purescript-angular
purescript-arb-instances
purescript-argonaut
purescript-arrows
purescript-base
purescript-bifunctors
purescript-channels
purescript-const
purescript-coproducts
purescript-datetime
purescript-distributive
purescript-drawing
purescript-enums
purescript-foldable-traversable
purescript-foreign
purescript-free
purescript-generics
purescript-graphs
purescript-handlebars
purescript-identity
purescript-inject
purescript-jquery
purescript-lazy
purescript-lens
purescript-lists
purescript-machines
purescript-maps
purescript-mongodbf
purescript-node-fs
purescript-oo-ffi
purescript-parsing
purescript-pattern-arrows
purescript-profunctors
purescript-quickcheck
purescript-sammy
purescript-sets
purescript-streams
purescript-string-parsers
purescript-strongcheck
purescript-task
purescript-transformers
purescript-tuples
purescript-unfoldable
purescript-yaml
purescript-yargs
```

**Comment by paf31** [comment]
:scream:

**Comment by paf31** [comment]
This sounds good to me. I'll update the issue to include @jdegoes ' proposal. As far as I'm concerned, if anyone wants to work on this, and doesn't mind digging into the optimizer a bit, I'll merge the changes into 0.7.0.

**Comment by paf31** [comment]
@jdegoes I just changed `SemiRing` to `Semiring` (lower case R).

**Comment by garyb** [comment]
I'll have a stab at it. :ok_hand:

**Comment by garyb** [comment]
Did we have a plan for `(%)`?

**Comment by jdegoes** [comment]
Copied from the PR:

-------------------


Ah, forgot about modulo.

I'd be interested in feedback on this slight tweak to the hierarchy:

```purescript
-- definition: a / b * b + (a % b) = a
class (Ring a) <= ModuloRing a where
  (%) :: a -> a -> a
  (/) :: a -> a -> a

-- definition: a % b = zero
class (ModuloRing a) <= DivisionRing a
```

The idea here is that some types support modulo ring but not division ring: for example, `Int`, and `Polynomial`. Whereas, because division rings are capable of producing true multiplicative inverses for every value, the quantity `a / b * b` is definitionally equal to `a`, so `a % b` is `zero` for all `b`.

**Comment by paf31** [comment]
What laws would `ModuloRing` have?

I think the idea is good, but here's the issue: `%` on `Number` doesn't follow any sensible set of laws, and it's the only candidate we have right now, since we don't have a type for polynomial rings or anything.

For that reason, I think the best option for now is to make `%` monomorphic. When we have an `Int` type,  we can make a class and `Int` instance for `ModuloRing`.

Thoughts?

**Comment by jdegoes** [comment]
I put the laws in the comments but will restate:

1. '%': Forall `a` and nonzero `b`: `a / b * b + (a % b) = a` (this holds for `Int`, `Polynomial`, etc.).
2. For any division ring, `a % b = zero` for all `b`. This is coherent for `Number` and implied by the above law for `%`.

**Comment by paf31** [comment]
So `%` for `Number` isn't `%` from JavaScript - it's `const (const 0)`?

**Comment by jdegoes** [comment]
That's correct, but purescript-int would define it using the JS operator for the upcoming Int data type.

**Comment by paf31** [comment]
So I think ultimately that is the right approach, but we potentially have to break code in the meantime.

As an alternative, `%` can be given type `Number -> Number -> Number` until 0.8.0, at which point we can break lots more things.

**Comment by jdegoes** [comment]
Another option is using the above hierarchy, but giving a wrong implementation for % (for Number), which we can fix in 0.8. That wouldn't break anything. Also, I can search to see if any code actually uses % -- we might be pleasantly surprised.

**Comment by paf31** [comment]
A few small games maybe, nothing major.

**Comment by paf31** [comment]
I don't think we gain anything by adding a broken instance.

With the hierarchy above, we can't write a `DivisionRing` instance for `Number`, because there is no valid `ModuloRing` instance.

I honestly think the simplest way is to just keep `%` as primitive (monomorphic). We can always add `ModuloRing => Ring` in a library later. Removing `%` from the namespace isn't so bad, since `ModuloRing` could define `mod` instead, and be consistent with Haskell.

**Comment by jdegoes** [comment]
`Number` does indeed have a valid `ModuloRing` instance, based on the above definition; `%` is remainder after division, such that `a / b * b + (a % b) = a`. In the case of `Number`, `a % b = 0` for all `a` and nonzero `b`.

In any case, I think it's fine to use `mod` for the above operation, and use `%` as the Javascript analogue.  This makes it consistent with Haskell and Javascript, to the extent possible, and ensures we don't needlessly break compatibility.

:+1:

**Comment by Fresheyeball** [comment]
I'm learning a ton from this thread, thank you. Is there a way to get these kinds of separations in Haskell as well?

**Comment by jdegoes** [comment]
Define it yourself? :smile: Haskell's numeric hierarchy is a legendary example of how *not* to do a numeric hierarchy. :wink:

**Comment by jdegoes** [comment]
Btw @Fresheyeball, these changes will make it very easy to define `Positive`, `Negative`, and variations on them.

**Comment by paf31** [comment]
@Fresheyeball You might like GHC's `RebindableSyntax` extension.

**Comment by michaelficarra** [comment]
@paf31 it should be called `rem`, as the result of JavaScript's `%` has the sign of the dividend, not the divisor. JavaScript does not have a true modulo operator. CoffeeScript added a `%%` operator for this, and we may want a separate `mod` derived from `rem`.

**Comment by garyb** [comment]
Should `Num` have a `ModuloRing` implication after this, or still `DivisionRing`?

**Comment by paf31** [comment]
I think `Num => DivisionRing => ModuloRing`.

**Comment by garyb** [comment]
```a `mod` b = zero``` for every commutative field then? This is a little beyond my GCSE maths ;)

**Comment by paf31** [comment]
Yes, for a field, every non-zero element has a multiplicative inverse, so

```
a / b * b + (a % b) = a
{ a / b = a * inv(b) }
==> a * inv (b) * b + a % b = a
{ inv (b) * b = 1 }
==> a + a % b = a
{ subtract a }
==> a % b = 0
```

**Comment by garyb** [comment]
Ah yep, got it, thanks :+1:

**Comment by jdegoes** [comment]
Yes, `Num => DivisionRing => ModuloRing`, since division ring is a guarantee the remainder is zero (i.e. there exists a multiplicative inverse).
