### ISSUE TITLE
--dump-imperative-core

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#876]
This would write the imperative core to a JSON file, just like `--dump-corefn` dumps the functional core.

**Comment by garyb** [comment]
Might be useful for editor support also, as the annotations could help with completions, etc.

**Comment by paf31** [comment]
Moving to 0.9, I think this will be really useful when we start focussing properly on alternative backends.

**Comment by paf31** [comment]
Duplicate of #711

**Comment by metaleap** [comment]
#3094
