### ISSUE TITLE
Linker errors when building psc on Mac OS X Yosemite

### ISSUE THREAD

**Issue by timjstewart** [purescript/purescript#878]
Purescript installed great on my Ubuntu Linux laptop but I'm having problems on my Mac OS X Yosemite MacBook Pro...

My Environment: 

$ cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.4 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

$ clang --version
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

I cloned this repo as of commit: d844d14709ef064ba7f16c6d694a23450d7601cb

When I tried to cabal install purescript into a cabal sandbox I got this error:

    "file was built for archive which is not the architecture being linked (x86_64)"

More Output from "cabal build":

In-place registering purescript-0.6.7.1...
Preprocessing executable 'psc' for purescript-0.6.7.1...
[1 of 2] Compiling Paths_purescript ( dist/build/autogen/Paths_purescript.hs, dist/build/psc/psc-tmp/Paths_purescript.o )
[2 of 2] Compiling Main             ( psc/Main.hs, dist/build/psc/psc-tmp/Main.o )
Linking dist/build/psc/psc ...
ld: warning: ld: warning: ignoring file /Users/stewtj3/tmp/purescript/dist/build/libHSpurescript-0.6.7.1.a, file was built for archive which is not the architecture being linked (x86_64): /Users/stewtj3/tmp/purescript/dist/build/libHSpurescript-0.6.7.1.aignoring file /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/pattern-arrows-0.0.2/libHSpattern-arrows-0.0.2.a, file was built for archive which is not the architecture being linked (x86_64): /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/pattern-arrows-0.0.2/libHSpattern-arrows-0.0.2.a

ld: warning: ignoring file /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/monad-unify-0.2.2/libHSmonad-unify-0.2.2.a, file was built for archive which is not the architecture being linked (x86_64): /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/monad-unify-0.2.2/libHSmonad-unify-0.2.2.a
ld: warning: ignoring file /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/file-embed-0.0.7.1/libHSfile-embed-0.0.7.1.a, file was built for archive which is not the architecture being linked (x86_64): /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/file-embed-0.0.7.1/libHSfile-embed-0.0.7.1.a
ld: warning: ignoring file /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/optparse-applicative-0.11.0.2/libHSoptparse-applicative-0.11.0.2.a, file was built for archive which is not the architecture being linked (x86_64): /Users/stewtj3/tmp/purescript/.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/optparse-applicative-0.11.0.2/libHSoptparse-applicative-0.11.0.2.a
Undefined symbols for architecture x86_64:
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilder_abortOption3_closure", referenced from:
      _Main_browserNamespace13_closure in Main.o
      _Main_dceModule6_closure in Main.o
      _Main_codeGenModule6_closure in Main.o
      _Main_outputFile8_closure in Main.o
      _Main_runMain12_closure in Main.o
      _Main_externsFile10_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilder_abortOptionzuvar_closure", referenced from:
      _Main_browserNamespace6_closure in Main.o
      _Main_dceModule3_closure in Main.o
      _Main_codeGenModule3_closure in Main.o
      _Main_outputFile5_closure in Main.o
      _Main_runMain6_closure in Main.o
      _Main_externsFile7_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilder_info1_closure", referenced from:
      _Main_main2_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilder_prefs1_closure", referenced from:
      _cbZZ_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilder_zdwabortOption_closure", referenced from:
      _SbcF_srt in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilder_zdwabortOption_info", referenced from:
      _Main_main12_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilderziInternal_DefaultProp_static_info", referenced from:
      _Main_main16_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziBuilderziInternal_OptionFields_con_info", referenced from:
      _cbW9_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziExtra_execParserPure_closure", referenced from:
      _SbcF_srt in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziExtra_execParserPure_info", referenced from:
      _cbZZ_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziExtra_helper_closure", referenced from:
      _Main_main11_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziHelpziChunk_paragraphzugo_closure", referenced from:
      _SbcF_srt in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziHelpziChunk_paragraphzugo_info", referenced from:
      _Main_inputFilezulvl2_info in Main.o
      _Main_browserNamespacezulvl2_info in Main.o
      _Main_dceModulezulvl2_info in Main.o
      _Main_codeGenModulezulvl2_info in Main.o
      _Main_outputFilezulvl2_info in Main.o
      _Main_runMain7_info in Main.o
      _Main_externsFilezulvl2_info in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziHelpziTypes_renderHelp_closure", referenced from:
      _SbcF_srt in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziHelpziTypes_renderHelp_info", referenced from:
      _sbbm_info in Main.o
      _sbbs_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_AltP_con_info", referenced from:
      _cbXO_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_AltP_static_info", referenced from:
      _Main_inputFile_closure in Main.o
      _Main_browserNamespace_closure in Main.o
      _Main_dceModule_closure in Main.o
      _Main_codeGenModule_closure in Main.o
      _Main_outputFile2_closure in Main.o
      _Main_outputFile_closure in Main.o
      _Main_runMain15_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_ArgReader_static_info", referenced from:
      _Main_inputFile6_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_CReader_static_info", referenced from:
      _Main_browserNamespace14_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_FlagReader_con_info", referenced from:
      _cbCt_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_FlagReader_static_info", referenced from:
      _Main_useStdIn7_closure in Main.o
      _Main_comments9_closure in Main.o
      _Main_noPrelude7_closure in Main.o
      _Main_noTco7_closure in Main.o
      _Main_noMagicDo7_closure in Main.o
      _Main_noOpts7_closure in Main.o
      _Main_verboseErrors7_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_Hidden_closure", referenced from:
      _cbWU_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_InfoMsg_static_info", referenced from:
      _Main_main18_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_Internal_closure", referenced from:
      _cbWU_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_MultP_static_info", referenced from:
      _Main_options11_closure in Main.o
      _Main_options10_closure in Main.o
      _Main_options9_closure in Main.o
      _Main_options8_closure in Main.o
      _Main_options7_closure in Main.o
      _Main_options6_closure in Main.o
      _Main_options3_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_NilP_static_info", referenced from:
      _Main_browserNamespace1_closure in Main.o
      _Main_externsFile1_closure in Main.o
      _Main_comments1_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_OptLong_con_info", referenced from:
      _cbuO_info in Main.o
      _cbwV_info in Main.o
      _cbyq_info in Main.o
      _cbzR_info in Main.o
      _cbBY_info in Main.o
      _cbEQ_info in Main.o
      _cbGC_info in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_OptP_static_info", referenced from:
      _Main_inputFile1_closure in Main.o
      _Main_browserNamespace4_closure in Main.o
      _Main_dceModule1_closure in Main.o
      _Main_codeGenModule1_closure in Main.o
      _Main_outputFile3_closure in Main.o
      _Main_runMain16_closure in Main.o
      _Main_runMain4_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_OptProperties_con_info", referenced from:
      _cbWL_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_OptProperties_static_info", referenced from:
      _Main_inputFile3_closure in Main.o
      _Main_browserNamespace6_closure in Main.o
      _Main_dceModule3_closure in Main.o
      _Main_codeGenModule3_closure in Main.o
      _Main_outputFile5_closure in Main.o
      _Main_runMain18_closure in Main.o
      _Main_runMain6_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_OptReader_static_info", referenced from:
      _Main_browserNamespace13_closure in Main.o
      _Main_dceModule6_closure in Main.o
      _Main_codeGenModule6_closure in Main.o
      _Main_outputFile8_closure in Main.o
      _Main_runMain12_closure in Main.o
      _Main_externsFile10_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_OptShort_static_info", referenced from:
      _Main_dceModulezun_closure in Main.o
      _Main_outputFilezun_closure in Main.o
      _Main_externsFilezun_closure in Main.o
      _Main_useStdInzun_closure in Main.o
      _Main_commentszun_closure in Main.o
      _Main_verboseErrorszun_closure in Main.o
      _Main_noPrefixzun_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_Option_static_info", referenced from:
      _Main_inputFile2_closure in Main.o
      _Main_browserNamespace5_closure in Main.o
      _Main_dceModule2_closure in Main.o
      _Main_codeGenModule2_closure in Main.o
      _Main_outputFile4_closure in Main.o
      _Main_runMain17_closure in Main.o
      _Main_runMain5_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_ParserInfo_static_info", referenced from:
      _Main_main2_closure in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_Visible_closure", referenced from:
      _Main_inputFile3_closure in Main.o
      _Main_browserNamespace6_closure in Main.o
      _Main_dceModule3_closure in Main.o
      _Main_codeGenModule3_closure in Main.o
      _Main_outputFile5_closure in Main.o
      _Main_runMain18_closure in Main.o
      _Main_runMain6_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_manyM_info", referenced from:
      _Main_options4_info in Main.o
      _Main_options2_info in Main.o
      _Main_pscOptions7_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_zdfAlternativeParserzuzdcempty_closure", referenced from:
      _Main_inputFile_closure in Main.o
      _Main_dceModule_closure in Main.o
      _Main_codeGenModule_closure in Main.o
      _Main_outputFile2_closure in Main.o
      _Main_runMain15_closure in Main.o
      _Main_runMain3_closure in Main.o
      _Main_externsFile4_closure in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_zdfAlternativeParserzuzdcpure_closure", referenced from:
      _Main_options4_info in Main.o
      _Main_options2_info in Main.o
      _Main_pscOptions7_info in Main.o
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_zdfApplicativeParserzuzdcfmap_info", referenced from:
      _Main_outputFile1_info in Main.o
      _Main_runMain1_info in Main.o
      _Main_externsFile3_info in Main.o
      _Main_options12_info in Main.o
      _Main_options5_info in Main.o
      _Main_pscOptions6_info in Main.o
      _Main_pscOptions1_info in Main.o
      ...
  "_optparsezmapplicativezm0zi11zi0zi2_OptionsziApplicativeziTypes_zdfMonoidCompleter4_closure", referenced from:
      _Main_browserNamespace14_closure in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScript_prelude_closure", referenced from:
      _Main_readInput2_closure in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScript_zdwcompilezq_closure", referenced from:
      _SbcF_srt in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScript_zdwcompilezq_info", referenced from:
      _rb6Y_info in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScriptziEnvironment_initEnvironment_closure", referenced from:
      _cbqg_info in Main.o
      _SbcF_srt in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScriptziOptions_Options_closure", referenced from:
      _Main_options12_info in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScriptziOptions_zdWCompileOptions_closure", referenced from:
      _Main_options5_info in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScriptziParserziDeclarations_parseModulesFromFiles_closure", referenced from:
      _SbcF_srt in Main.o
  "_purescriptzm0zi6zi7zi1_LanguageziPureScriptziParserziDeclarations_parseModulesFromFiles_info", referenced from:
      _cbqd_info in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by garyb** [comment]
I have a similar setup, just a slightly newer cabal and it seems okay:

```
$ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

$ clang --version
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

Seems odd that cabal would affect the linker though?

**Comment by timjstewart** [comment]
I'll upgrade cabal and try again.  Thanks for your encouraging reply!

**Comment by timjstewart** [comment]
Haskell Platform
============
I'm using the 2014.2.0.0 version of the Haskell Platform for Mac (https://www.haskell.org/platform/mac.html) and when I update cabal (cabal install cabal-install) cabal stops working (I get a "zsh: killed" response from running cabal).

Homebrew
========
I then uninstalled haskell platform (sudo uninstall-hs) and then installed the Homebrew ghc and cabal-install packages.  This gave me version 1.22.0.0 of cabal but when I try to run "cabal install purescript" in a sandbox, I get:

   ansi-terminal-0.6.2.1 failed during the configure step. The exception was:
   ExitFailure (-9)
   This may be due to an out-of-memory condition.

and other similar errors.

**Comment by timjstewart** [comment]
looks like the process killing is due to taskgated.

**Comment by timjstewart** [comment]
Could this be the problem?

From: https://github.com/tpoechtrager/osxcross/issues/11

You must use the correct ar (archiver), e.g.:

make CXX=o64-clang++ AR=x86_64-apple-darwin1X-ar

Otherwises it uses the system ar and won't work.
