### ISSUE TITLE
Improve error message for class member implementations that are not contiguous

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#881]
This:
``` purescript
instance eqMaybe :: (Eq a) => Eq (Maybe a) where
  (==) Nothing   Nothing   = true
  (==) (Just a1) (Just a2) = a1 == a2
  (/=) a b = not (a == b)
  (==) _ _ = false -- <------------- oops, out of sequence
```
Raises this error:
```
>> Compiling Data.Maybe
>> Error at src/Data/Maybe.purs line 65, column 1 - line 71, column 1:
>> Error in declaration eqMaybe
>> Duplicate property names
```

Which is caught in `ensureNoDuplicateProperties` during type checking instead of somewhere more sensible.

**Comment by paf31** [comment]
The idea of grouped cases already exists [here](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/CaseDeclarations.hs#L86), and by good fortune, the type classes code actually calls this function.

Maybe we could handle it there?
