### ISSUE TITLE
Discussion: What to do about the FFI?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#887]
I don't really like the current PureScript FFI. Its number one selling point is its simplicity, but it is, in my opinion, too simple. It allows way too many things.

My main objection is that the current FFI does not allow us to write new backends easily. Embedding huge chunks of JavaScript in our code is not an elegant solution, and it isn't portable.

It seems we have two main use cases for the FFI:

- Defining foreign data types and their functions
- Integrating with third party libraries

Any proposal should be able to handle both of these use cases across different backends. Please give me your suggestions. Here is one:

### Disallow string literals in foreign imports

The type system provides a way to talk about specifications. Backends would choose their own runtime representations for the core types (as long as they are consistent), and bindings would get implemented in the target language (or not, if the library is not appropriate for the given backend).

This would involve splitting all our libraries into a PureScript FFI part and a JavaScript wrapper library. 

#### Pros

- The JavaScript components of the libraries become useful libraries in their own right.
- Requires relatively few changes to the compiler.
- There is a very clear story for how to implement a minimal backend, or how to port a library to a backend.

#### Cons

- Extra work involved when writing FFI declarations.

**Comment by natefaubion** [comment]
I like the idea of putting FFI code in separate, language specific files. That way you could provide FFI implementations for multiple backends at once. What if `foreign import` was like any other import statement, except you provide type signatures on the bindings?

```purescript
module Foo where

foreign import Foo.Bindings
  ( idImpl :: forall a. a -> a
  , constImpl :: forall a b. a -> b -> a
  )
```

The specific backends would do the job of resolving `Foo.Bindings`, and doing any encapsulation/copying/inlining to get them into scope.

**Comment by michaelficarra** [comment]
I was just thinking about this as we've been introducing these new functional and imperative intermediate representations. I think the inline FFI code should be any string that may be compiled to one of our IRs. This would make the PureScript IR the integration point, and supporting a new backend would only involve compiling one of the PureScript IRs to that target. We would, of course, provide the JavaScript to imperative IR function (which would be implicitly used for back-compat purposes).

```purescript
myLangCompiler :: String -> PureScript.Meta.ImperativeIR
myLangCompiler stringOfMyLangCode = ...

foreign import bindingName using myLangCompiler "code" :: Type
```

Then we need some integration between the PureScript.Meta.ImperativeIR value and the PureScript compiler. It would be a lot of work, but what do you think?

**Comment by andyarvanitis** [comment]
+ 1 for being able to put backend-specific parts in separate files. Otherwise, I've been finding the simplicity and flexibility of the FFI to work pretty well, even with a language that's fairly dissimilar to JS (I've been quietly working on an experimental C++11 backend).

**Comment by photex** [comment]
@andyarvanitis can't wait to hear more about that project!

I'm very new to purescript but inline js in foreign imports struck me as a shaky idea. +1 for separating wrappers from purs source.

**Comment by garyb** [comment]
The idea of separating the FFI code out into a separate module definitely seems like a good idea to me. I think this came up back in the discussion of the Lua version as a potential solution too.

@natefaubion I quite like this change also, I guess it could still work for foreign types, effects, and instances too:

``` purescript
foreign import Foo.Bindings
  ( idImpl :: forall a. a -> a
  , constImpl :: forall a b. a -> b -> a
  , SomeType :: * -> *
  , SomeEff :: !
  , instance functorSomeType :: Functor SomeType
  )
```

The only problem I can see with this is at the moment the `.externs` files use foreign declarations to provide the interface for modules, but I'm sure there's a way it can still work.

@michaelficarra I like this in theory too, but I'm not sure it quite works, as the current `CoreImp` has no representation of "native things", it leaves the implementation of these up to the backend to further desugar. It's not just a case of native functions being unspecified, we also don't dictate what exactly a data constructor is, how object updates are implemented, etc.

**Comment by natefaubion** [comment]
@garyb I think you could just keep `foreign import data` and `foreign import instance` around since they only introduce things into the type system. This would only be to introduce foreign implementations.

@michaelficarra I agree with @garyb. I think you'd get into trouble pretty quick anytime you'd need to represent anything idiomatically, like importing native modules. If you had separate files for foreign implementations, you could work completely natively, with export conventions dictated by the backend.

**Comment by joneshf** [comment]
Speaking of `foreign import data` does it have a purpose now that we can specify kind signatures in data type declarations?

```purescript
foreign import data Eff :: # ! -> * -> *
-- vs
data Eff (effects :: # !) (value :: *)
```

**Comment by garyb** [comment]
Excellent point, probably not.

**Comment by paf31** [comment]
`foreign import data` is only needed when you're introducing a type with kind `!` or `# !` etc.

**Comment by paf31** [comment]
@natefaubion I like that idea, but wouldn't you have to put the same imports in every module that used them? Seems like that could become a bit of a maintenance headache.

**Comment by jdegoes** [comment]
Many libraries are almost entirely pure, with a small FFI component. In light of that, I would like to request the following:

*That whatever proposal is accepted, it be possible to have a library with an FFI component simultaneously support multiple backends with the same code base (excluding the FFI parts).*

This automatically rules out a huge range of proposals, or at least requires modifications to many.

I spent some time in the haxe ecosystem before Purescript. haxe allows one to do this [using a simple preprocessor](http://old.haxe.org/ref/conditionals). I hate preprocessors, but the point is the feature is *very widely used* to allow multiple backends to benefit from "mostly pure" libraries, as well as allow the creation of cross-platform abstractions for things like graphics, physics, UI, etc.

**Comment by jdegoes** [comment]
Btw will comment more on specific proposals when I get a chance, just wanted to throw the above out there since I think it's very important that libraries be able to target multiple backends simultaneously without using third-party crap (like cpp!).

**Comment by natefaubion** [comment]
@paf31 You'd want to consolidate your foreign imports, likely. I realize this introduces a certain amount of boilerplate in comparison to the inline string approach, but I think consolidation would make it easier to work with multiple backends at once.

I really dislike the idea of having actual code for multiple languages in one file. I'd like to be able to use native tools where possible like linters and such when working with other dynamic langs. Having all FFI variations globbed together in a purs file makes that difficult.

**Comment by paf31** [comment]
@jdegoes Could you clarify your requirement a little? Does my proposal satisfy it? I figure a backend may or may not support a given FFI spec. Take `EasyFFI` for example - it requires something like `eval` be provided by the backend, so it's great for JS, but probably not possible to support in a Java backend. The FFI types still provide the spec that we work against though, _if_ the backend can provide an implementation.

**Comment by fixplz** [comment]
So far for me the majority of uses of foreign literal includes has been for writing small JS functions that circumvent the type system, such as casts (where the implementation is id), wrapping and unwrapping Eff, and the odd property access or method call.

This gave me the thought that Purescript should provide the ability to write untyped expression blocks that would nonetheless be loaded as ASTs that the compiler would know how to generate output code for.

Untyped expression blocks should have the ability to access native definitions by name and invoke native operations (+, &&, obj[prop], new, if, while).

Example:

    foreign import castSmth
      """function castSmth(obj) { return obj }"""
      :: forall x y. Smth x -> Smth y

becomes

    castSmth :: forall x y. Smth x -> Smth y
    castSmth = untyped id

I believe this would supersede a majority of foreign includes in all Purescript code I have seen so far.

We should then observe what uses of foreign includes remain in the community and revisit the topic of disallowing literal includes later.

**Comment by paf31** [comment]
@fixplz I had the same thought. I considered adding a `cast` primitive to the `Prim` module for such cases, which new backends would be required to implement in the appropriate way. This would allow us to implement a lot of existing data type libraries without the FFI: `exists`, `reflection`, `nullable`, etc.

**Comment by natefaubion** [comment]
Something that isn't even touched by the current FFI is how to import foreign modules for languages other than JS. Some PS libraries rely on globals, some rely on `foreign import foo "var foo = require('foo')"`. This is a really terrible situation in my opinion, and won't scale to other languages (It doesn't really even scale now). Having native FFI files as suggested could fix that.

**Comment by fixplz** [comment]
@natefaubion 
At present the conventional way to invoke the compiler is `psc-make bower_components/purescript-*/src/**/*.purs src/**/*.purs`, which has the semantics of processing all provided files. The compiler does not read any additional files by itself.

How would we proceed from this to include backend-specific files?

**Comment by joneshf** [comment]
> foreign import data is only needed when you're introducing a type with kind ! or # ! etc.

Ah. Makes sense.

I think writing untyped blocks directly in ps as though it's regular stuff is a bad idea. If you make it super simple to circumvent the type system things can go to hell real quick. Does it really need to be this easy to write unsafe code? I strongly feel that the answer is no. We lose so much reasoning ability if any function can just use untyped code and do whatever it wants.

Look at haskell, it has a powerful C ffi, but it's a bit cumbersome to use. Most haskell libraries nowadays, have very little ffi stuff in them. Partly because of the way you use the ffi, partly because of the 20 some odd years of compiler improvements. If we don't move away from making writing ffi stuff easy, I feel like we're going to always carry around this ffi stuff through to higher level libraries rather than relegating it to a handful of primitive modules.

If that seems dystopian, look no further than this thread. Many people are weighing in on this because the ffi affects everyone. Hell, we all write `Eff` code by hand in the ffi. Any changes to the ffi will break vast amounts of code simply because it's already too easy to use it. So making it easier to use is not a good idea in my opinion.

If we want to make it easier to interface with the runtime (whatever that may be), then we should focus on providing primitives for that (like `whileE` and friends) rather than making the ffi easier to use.

**Comment by paf31** [comment]
@joneshf I agree, but we do need a way to implement things like `purescript-exists` in a cross-backend way. Maybe sticking `unsafeCoerce` in `Prelude.Unsafe` would be better. I still think an `Unsafe` type class would be a good think, incidentally.

**Comment by natefaubion** [comment]
@fixplz I'm talking about if you were say writing bindings for the ACE code editor, and you needed to reference that foreign module. You have to import it somehow. The only way to import it now is to rely on leaked globals, or use dynamic require. PureScript has no way to express that.

With backend specific files, the backend would receive the imported name, with the declared bindings and types. It would have to resolve that and include it in whatever way makes sense for the backend. It may be inlining, or it may be copying it somewhere and including it in a class path. Additionally, this could let you experiment with writing a new backend, and providing shims for core modules. Say I'm writing a COBOL backend, and I really want to use `purescript-lazy`. `purescript-lazy` may have a `foreign import Data.Lazy.Impl (...)` declaration for a primitive thunk, but obviously @paf31 isn't going to take a COBOL patch for an experiment. You could resolve that yourself to something included with your backend.

**Comment by paf31** [comment]
This is definitely an issue with my proposal, and the solution needs to be fleshed out. On the one hand, removing inline JS is a simple way to solve the issue, and providing native FFI implementations in the target language seems like a simple path to new backends. On the other, we lose the nice property that we get a bundle of JS and compiled PS out of `psc`.

At a minimum, I think we'd need a way to tie a particular FFI implementation to a backend/module pair. This could be via something like pragmas (I don't like this option), a convention (`psc-make` assumes CommonJS modules are defined in `ModuleName.js` or whatever - I like this more), or via command line options and build tools (I like this option).

**Comment by jdegoes** [comment]
If the foreign primitives are well-thought out with respect to multiple backends (e.g. C, Javascript, and JVM, for example, which are pretty representative), then I think I'd be on board with that.

But there's a detail here which is being overlooked, which is: a cross-platform Purescript function will need to invoke *different functions*, with possibly *different arguments*. If the solution is *perform the unification in the native code*, then there's a bit of a problem:

Say I am adding support for the JVM to the `purescript-timers` library. I look at the JS code, and then I determine I cannot actually write a JVM function with the same signature. So now, in order to make `purescript-timers` compatible with the JVM, I have to update both the JS code, and the Java code, to find the lowest common denominator. In the worst possible case, if a library supports N backends, and I wish to add support for N+1, then I potentially have to be familiar with all N languages, and update all of them, to provide a uniform native API which can be called from Purescript.

I'm not saying this is a fatal problem, or anything, just something that should be given consideration. The alternative is if, in Purescript, I can delegate to different native functions on different backends, which have completely different signatures. I'm not sure what this would look like, but perhaps compiler-defined nullary classes could be interesting here (?), without having to add new syntax or semantics.

**Comment by paf31** [comment]
I think of it like this: we identify a spec for timers in the form of a type:

```
foreign import data Timer :: *

setTimeout :: forall a eff. Number -> Eff eff a -> Eff eff Timer
clearTimeout :: forall a eff. Timer -> Eff eff Unit
```

or whatever. This seems like a pretty reasonable spec.

Each backend first needs to define the runtime representation for every primitive involved (`->`, `Number`, `Eff`). A core of these things will define what it means to be a backend in the first place - basically supporting the built-in types.

Next, you support a particular FFI binding if you can pick runtime representations for its foreign data types and choose implementations of its functions which are consistent with those representations.

We know what the interpretation here is for JS. On the JVM, we might use an `ExecutorService` or something, I don't know. But whatever it is, it's either possible to implement the spec or not. If is is, great. If not, one of two things is true:

- The spec isn't general enough. In this case, using our best judgement, we try to refine the spec without it turning into something ridiculous.
- The spec can't be implemented reasonably in the target backend. I don't expect this to happen very often. In this case, we say "oh well" and move on. We can always implement `purescript-timers-jvm` or something and use type classes to capture the abstract behavior if necessary.

**Comment by jdegoes** [comment]
This seems reasonable to me. We need a way (maybe in build tools as opposed to psc itself) to bundle in the foreign assets into the overall compiled package so there's a single distributable.

**Comment by garyb** [comment]
I think we can close this now :smile:
