### ISSUE TITLE
A tool for sharing data types between Haskell and PureScript

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#891]
This would auto-generate `IsForeign` instances on the PureScript side, and `ToJSON` instances on the Haskell side.

We could implement it as a quasiquoter in Haskell, or as a separate tool entirely.

This is the number one complaint I hear from Haskell users in the context of PureScript, so it would be nice to have a standard answer, however simple.

**Comment by hdgarrood** [comment]
Have you seen this? https://github.com/philopon/haskell-purescript-binding

**Comment by hdgarrood** [comment]
Also, presumably, we'd want to be able to send values the other way, too? As in, we'd want a PureScript function or type class instance for converting values to JSON, and a `FromJSON` instance in Haskell. It looks like `haskell-purescript-binding` allows this, alongside `purescript-json`.

**Comment by paf31** [comment]
I did, but I was thinking more of a pair of libraries for serializing and deserializing data with an agreed schema.

**Comment by hdgarrood** [comment]
Could you go into a little more detail about how this might work, please? I'm having difficulty visualising it

**Comment by paf31** [comment]
Sure, you'd have a schema language which supported basic things like numbers, strings, booleans, records, arrays, etc. Then you'd have Haskell and PureScript tools (I'm thinking a template haskell quasiquoter, and a gulp plugin) which would generate types and functions on both sides.

**Comment by hdgarrood** [comment]
Potentially relevant: https://www.reddit.com/comments/359oba

**Comment by FrigoEU** [comment]
I've been thinking about this a bit and wondering about ADT's. It would be amazing if this would be supported, but I'm not sure if anything like that is feasible...

**Comment by paf31** [comment]
See `purescript-foreign-generic` or `servant-purescript`.

**Comment by eallik** [comment]
@paf31 since you closed the issue, is there a "conclusion" of this matter in your head? perhaps you could serialize that conclusion in the form of a comment? :)
