### ISSUE TITLE
Update wiki: "No multiple guard clauses" in "Differences from Haskell"

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#894]
... since they're supported now.

https://github.com/purescript/purescript/wiki/Differences-from-Haskell

And anything else that might have changed...

**Comment by paf31** [comment]
Yep, feel free to remove it. Feel free to modify the wiki in any way you think is helpful.

**Comment by andyarvanitis** [comment]
Ok, cool, I'll do it right now then.
