### ISSUE TITLE
Discussion: Improve the Show type class?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#895]
Here's another thing in the category of "things I don't like".

The current `Show` class makes it difficult to write decent instances. In short: we don't have `showsPrec`.

The problem is that we have to insert too many parens in order to make things unambiguous:

```purescript
instance showMaybe :: (Show a) => Show (Maybe a) where
  show Nothing = Nothing
  show (Just a) = "Just (" ++ show a ++ ")"

> show (Just (Just 1))
"Just (Just (1))"
```

I have taken to writing `Show` instances in "sexpr-style":

```purescript
instance showMaybe :: (Show a) => Show (Maybe a) where
  show Nothing = Nothing
  show (Just a) = "(Just " ++ show a ++ ")"

> show (Just (Just 1))
"(Just (Just 1))"
```

This has the benefit that you always have just enough parens, and it is simple to write these instances mechanically:

- Atomic things like `Number`s and `String`s get rendered as usual.
- Data structures containing other things get wrapped in parens, and arguments separated by spaces.

However, a nice informal law of `Show` says that it should be possible to paste the result of `show x` into a REPL and get `x` back. These instances break that law.

I suggest that we either move to sexpr-style across the board, or modify `Show` to redefine it in terms of `showsPrec` which is a much bigger change.

Thoughts?

**Comment by joneshf** [comment]
I think this is good to finally discuss.

I think `showsPrec` is the best way to handle this, but it might make sense to hold off until we either have defaults, or deriving. I know for sure I don't want to write `showsPrec` implementations for more complex data. Nor do I want to little `Show` instances with `show = showsPrec 0` or whatever.

**Comment by Fresheyeball** [comment]
This may not be the right place to post this, but I experience frustration with implementations of the `Show` typeclass in the form of non-typey outputs. For example in purescript-argonaut `show myJCursor` does not become `JField "foo" (JIndex 0 (JCursorTop))` but rather `foo[0]`. The second representation is handy, but as `show` it makes the type harder to reason about. I'd almost like to see a second typeclass `AsString` to house the `foo[0]` version, while `Show` can remain a 'repl copy paste-able' representation.

**Comment by garyb** [comment]
Another option aside from sexpr style would be to make a `showInner :: forall a. (Show a) -> a -> String` (or something, not a great name), which applies `show` to a value, and if the resulting string contains a space, wrap it in parens. I think that's the only rule required to determine whether parens are needed right?

**Comment by paf31** [comment]
_Almost_: I think `showInner "Foo Bar"` should be `"Foo Bar"` not `("Foo Bar")` for example.

But I hadn't thought about that. That's a neat idea :)

**Comment by garyb** [comment]
Ah yeah, that's true... could test if it starts with a `"` and if so skip the whitespace check then.

I'm sure it's not perfect, but worth a try perhaps?

**Comment by paf31** [comment]
Worth a try definitely. Some other cases which I can think of:

- Records (wrapped in `{...}`)
- Arrays of strings or records

You could probably get away with turning the precedence level into a `Boolean`, which would basically mean "wrap yourself in parens" if `true`. Things like records and arrays would ignore it, and more complex things would add the parens if necessary.

`showInner` would make a neat little library in any case.

**Comment by alexchandel** [comment]
`showsPrec` is a rather ugly name, I hope that doesn't replace `show` entirely, since the sexpr-style works there, and isn't visually unappealing.

As for `Show` vs. some potential `AsString`, Rust spent some getting its [fmt traits](http://static.rust-lang.org/doc/master/std/fmt/index.html) right. Although they renamed their `Show` trait to `Debug` and their primary `AsString` trait to `Display`, the functionality is the same. `Display` isn't called "AsString" because it's one of 9 "AsString" traits, each reflecting a different way to format a value (e.g. `Binary`, `LowerExp`, `LowerHex`, `Octal`, `Pointer`, `UpperExp`, `UpperHex`, and good old `Debug`/`Show`).

**Comment by paf31** [comment]
Duplicate of https://github.com/purescript/purescript-prelude/issues/46
