### ISSUE TITLE
Revise `BoolLike`

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#907]
#900

**Comment by paf31** [comment]
I'm in favour of this, but as with `Num`, I don't want to overdo it. Something like `Ord < Lattice < DistributiveLattice < Boolean` is probably enough IMO, with `newtype`s connecting `Lattice` to the `Ring` hierarchy in some library, a la `Additive`. Thoughts?

**Comment by jdegoes** [comment]
I think only a tiny number of classes will be necessary to do this right (like for `Num`), and that Boolean or some super class would extend `Semiring` directly.

My goals would be having "bool like things", e.g. bits, boolean signals (e.g. `Signal a` for `BoolLike a`), three-valued logic, etc.

**Comment by paf31** [comment]
This seems like a useful resource http://en.wikipedia.org/wiki/Boolean_algebra#Laws

It might be handy to separate the laws out for each class. I'd also like to discuss how the partial ordering factors into the equation : `(Ord a, Semiring a) <= Lattice a`?

**Comment by Fresheyeball** [comment]
If you are willing. I'd like to understand what are the laws of a lattice, and what would a complete isolated lattice class look like?

**Comment by garyb** [comment]
I'm not suggesting this as a hierarchy, but I think this is about right @Fresheyeball:

``` purescript
-- | Associative:
-- |     a ∨ (b ∨ c) = (a ∨ b) ∨ c
-- |     a ∧ (b ∧ c) = (a ∧ b) ∧ c
-- | Commutative:
-- |     a ∨ b = b ∨ a
-- |     a ∧ b = b ∧ a
-- | Absorption:
-- |     a ∨ (a ∧ b) = a
-- |     a ∧ (a ∨ b) = a
-- | Idempotent:
-- |     a ∨ a = a
-- |     a ∧ a = a
class (Ord a) <= Lattice a where
  (\/) :: a -> a -> a
  (/\) :: a -> a -> a

-- | Identity:
-- |     a ∨ ⊥ = a
-- |     a ∧ ⊤ = a
class (Lattice a) <= BoundedLattice a where
  top :: a
  bottom :: a

-- | Complemented:
-- |     a ∨ ¬a = ⊤
-- |     a ∧ ¬a = ⊥
class (BoundedLattice a) <= ComplementedLattice a where
  not :: a -> a -> a

-- | Distributive:
-- |     x ∧ (y ∨ z) = (x ∧ y) ∨ (x ∧ z)
class (Lattice a) <= DistributiveLattice a where

class (DistributiveLattice a, ComplementedLattice a) <= BooleanAlgebra a where
```

**Comment by paf31** [comment]
On the Backlog for now, but we can bump this up to 0.7 if we can find a way to implement it without breaking too many things.

**Comment by Fresheyeball** [comment]
Wow! So Booleans are definitely a Lattice! So does this mean that `BoolLike` basically goes away and gets replaced with `Lattice` classes describing conjunction and disjunction?

**Comment by paf31** [comment]
In fact, `Boolean` has at least two lattice structures by De Morgan's laws. Just flip `&&` and `||`.

Alternatively, just turn the Hasse diagram upside down: http://en.wikipedia.org/wiki/Duality_(order_theory)

:)

**Comment by Fresheyeball** [comment]
Ok. So... is there a name for that? 
```haskell
-- channels from Monoid to Semiring
newtype Additive
newtype Multiplicative 

-- channels from Lattice to Semiring
newtype Conjunctive
newtype Disjunctive

-- channels from BooleanAlgebra to Lattice
newtype ??
newtype ??
```

**Comment by Fresheyeball** [comment]
Actually, does that mean `Number` is 2 `Semiring`s? You could flip `(+)` and `(*)` as well. What if instead we had types that represent duality? Is such a thing possible? (warning type jibberish follows)

```
newtype Additive a = Additive a
newtype Multiplicative a = Multiplicative a

newtype Hot a = Hot a
newtype Cold a = Cold a

instance (Semiring a) => Monoid (Additive a) where
   mappend (Additive a) (Additive b) = Additive (a + b)
   mempty = zero

instance (BoundedLattice a) => Semiring (Hot a) where
   (+) = (&&)
   zero = top
   (*) = (||)
   one = bottom

instance (BoundedLattice a) => Semiring (Cold a) where
   (+) = (||)
   zero = bottom
   (*) = (&&)
   one = top

mconcatBooleans :: [Multiplicative Boolean] -> Multiplicative Boolean
-- this can now be switched from the outside like so:

mconcatBooleans $ Cold <$> myMultiplicativeBooleanList
```

**Comment by paf31** [comment]
No, `*, 1

**Comment by Fresheyeball** [comment]
I think I meant `Number` is 2 `BoundedLattice`s. 

```
class Lattice Number where
  (*) :: a -> a -> a
  (+) :: a -> a -> a

class BoundedLattice Number where
  top :: 1
  bottom :: 0

-- vs

class Lattice Number where
  (+) :: a -> a -> a
  (*) :: a -> a -> a

class BoundedLattice Number where
  top :: 0
  bottom :: 1
```

**Comment by paf31** [comment]
Well every lattice has a dual, but the obvious ones on `Number` are `(-Infinity, Infinity, min, max)` and its dual.

**Comment by Fresheyeball** [comment]
so I wrote this https://github.com/Fresheyeball/purescript/blob/boolike_semiring/prelude/prelude.purs its a cheap and greasy way of getting BoolLike and Semiring to work together. Let me know what you think.

**Comment by tslawler** [comment]
I'm a bit late to the party, but re: @garyb, if I understand correctly, Lattice shouldn't be a subclass of Ord, because not all lattices are totally ordered. In theory one could go the other way, having `(/\) = min` and `(\/) = max`, but this is probably more trouble than it's worth.

For an example where something that should be a Lattice couldn't be an instance of Ord, consider:
```purescript
instance (Lattice l) => Lattice (a -> l) where
  (/\) = liftA2 (/\)
  (\/) = liftA2 (\/)
```

(Incidentally, and completely off-topic, it would be nice to have something like `instance (Apply f, BoolLike b) => BoolLike (f b)` available in the prelude at some point)

**Comment by garyb** [comment]
@tslawler thanks for the input! `Ord` is just for posets though, so I think it's still correct.

I think that `BoolLike (f b)` instance would cause problems unfortunately, as we'd end up with overlaps.
