### ISSUE TITLE
Compile to ES5

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#916]
Another rather important question - should we assume ES5 as the baseline feature set required by the compiler and use shims for older browsers?

Right now we assume ES3 but this causes poor performance on newer runtimes.

**Comment by jdegoes** [comment]
http://kangax.github.io/compat-table/es5/

:+1: Assume ES5.

**Comment by garyb** [comment]
I was about preserving ES3 compatibility at one point, but I doubt there are many people that this actually affects, and the gaps can be filled with polyfills anyway. Let's do it. :+1:

**Comment by AppShipIt** [comment]
Agreed there's no reason Pulp couldn't handle ES3 generation when needed.

**Comment by paf31** [comment]
Closing, since this is tracked by #2207.
