### ISSUE TITLE
GSOC Projects

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#917]
I'm thinking of submitting some ideas for PureScript projects to GSOC under the Haskell organization.

We have no shortage of projects, but we need to choose things at the right difficulty level and find mentors (I'm willing to mentor someone on typechecker or codegen related things, or on new tools).

Here are some ideas. Does anyone have any others? Please link to existing issues if you can.

- Implement a new backend, or ideally, get the core representation to the point where implementing backends becomes easy. (#612, #339, #466, others)
- An IDL and tool for sharing data between Haskell and Haskell-like-but-not-Haskell languages (PureScript, Elm, etc.) (#891)
- Improve the optimizer (various)
- Row constraints (#469)
- Further work on Pursuit
- An online PureScript IDE

**Comment by paf31** [comment]
- A "PureScript Notebook" application with live code sections via the Try PureScript API.

**Comment by TrevorBasinger** [comment]
+1 For implement a new backend. I would love to be able to potentially write PS everywhere.

**Comment by jdegoes** [comment]
> A "PureScript Workbook" application with live code sections via the Try PureScript API.

This would be more useful than an IDE. Developers want to use their own development tools for building apps. But for playing around / learning, a notebook app would be very useful. Built on SlamData 2.0 of course. :)

**Comment by jdegoes** [comment]
* JVM backend
 * Supercompiler using Functional Core
 * Singleton types
 * First-class labels
 * Template PureScript

I / SlamData would mentor for any of the above.

**Comment by garyb** [comment]
- Constraint inference?

**Comment by paf31** [comment]
:+1: to all of the above.

Also

- Improve rewrite rules

since if I get anything at all done pre-GSOC, it'll probably be very simple.

@jdegoes Are "singleton types" synonymous with `DataKinds`? Because that would be neat, but probably not a whole summer's work.

**Comment by ryanartecona** [comment]
+1 for backend agnosticism
+1 for Template PureScript (& typeclass deriving) #140

**Comment by jdegoes** [comment]
@paf31 They are definitely related (maybe DataKinds subsumes them?). With [singleton types](http://stackoverflow.com/questions/16017294/singleton-types-in-haskell), any value literal becomes a valid type, and there is only one inhabitant to that type, namely, the value literal (or something which can, at compile-time, be reduced to it). For example, I could write: `foo :: "baz" -> Int` (with that or some other syntax, as necessary for eliminating ambiguity).

**Comment by paf31** [comment]
@jdegoes I'll create an issue for it, because I have some ideas of my own in that area.

**Comment by jdegoes** [comment]
@paf31 Also I think singleton types (or something which subsumes it) would make trivial work of "first class labels".

**Comment by paf31** [comment]
@jdegoes https://github.com/purescript/purescript/issues/919

What do you mean about the relationship to first class labels? I mean, I know we can encode things a la `HList`, but it's not really the same thing, right? Proper first-class labels would give us entirely new types of JS interop.

**Comment by paf31** [comment]
Also, remember we have to narrow this down to 2 or 3 possible candidates.

**Comment by michaelficarra** [comment]
Constraint inference would be great, but probably not enough for a full GSOC project. :+1: for refactoring to allow implementing multiple backends.

**Comment by jdegoes** [comment]
Well, records become extensible maps whose keys are singleton types. Among other things, this lets you define a lens which is fully polymorphic: the label, the type of the label, and the type of the record.

**Comment by paf31** [comment]
@michaelficarra I don't know - full simplification of constraint contexts could become a big project. And there's a whole bunch of related stuff which we could pad that out with to become a full project.

**Comment by jdegoes** [comment]
If I can only vote for 3 things, it would be the 3 most likely to be "game changers":

1. Supercompiler
2. JVM backend (it's a mistake to focus on something generic like "easier to make backends", I don't think that would be accepted because it has no concrete goals)
3. Unification of Template PureScript / Typeclass Deriving

**Comment by paf31** [comment]
Whatever we pick, I'll create a wiki page with alternatives.

**Comment by thkoch2001** [comment]
+1 for (PHP) backend

**Comment by garyb** [comment]
I'm still hacking away at the `CoreImp` AST version we discussed in the other issue, I'll commit some stuff soon for discussion, etc.

**Comment by robotlolita** [comment]
JVM backend and Template PureScript would be really nice.

**Comment by Fresheyeball** [comment]
can't you already run [purescript on the jvm?](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Download_Rhino) ;)

**Comment by paf31** [comment]
I'm going to close this and copy the material to the wiki. The plan is to link to the wiki from the Haskell trac card I create. Please feel free to expand on any projects I write up there.

**Comment by paf31** [comment]
Here we go: https://github.com/purescript/purescript/wiki/GSOC-2015-Projects
