### ISSUE TITLE
User-defined Kinds

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#919]
## Simple Version

The simplest version of this allows the user to write

```
kind Nat
```

and then things like

```
foreign import data Zero :: Nat
foreign import data Succ :: Nat -> Nat
```
## Possible Extensions
- Allow sorts other than `BOX`: `kind List :: BOX -> BOX`
- Full-blown `DataKinds`.
- Singleton types including numbers (a little hairy until we have `Int`) and strings, and type-level computation for those (addition, etc.)

**Comment by michaelficarra** [comment]
DataKinds with rows will be so powerful! I was longing for this a few weeks ago.

**Comment by natefaubion** [comment]
If you get DataKinds, I think you'd pretty quickly want either GADTs or type families. How far can you get with DataKinds alone?

**Comment by paf31** [comment]
@michaelficarra Neat :)

We could also do some neat stuff like defining an actual kind for memory regions when using `ST`:

```purescript
runST :: forall a. (forall r. ST (r :: Region) a) -> a
```

**Comment by michaelficarra** [comment]
Exactly. This would be so great.

**Comment by LiamGoodacre** [comment]
Here's some info about data type promotion in Haskell [8.0-latest#datatype-promotion](https://downloads.haskell.org/~ghc/8.0-latest/docs/html/users_guide/glasgow_exts.html#datatype-promotion)

Things we should discuss: (basically, should we do it in the same way)

### Syntax of promoted constructors
Haskell uses an optional single-quote prefix. For example: `'True`.  Note [this section](https://downloads.haskell.org/~ghc/8.0-latest/docs/html/users_guide/glasgow_exts.html#distinguishing-between-types-and-constructors):
> ...our experience has shown that the quote mark helps to make code more readable and less error-prone...

Perhaps we should always require the prefix.

### Restrictions on promotion
Only promote data with kinds of the form `* -> ... -> * -> *`

### Auto promotion
Should all data types be promoted (where possible) or should it require enabling per data type.

**Comment by rvion** [comment]
IMO, the `'` character is not the best one:
  - overloaded meaning with `'c'` char notation
  - need to fight against automatic `'` paring in ide
  - many syntax coloring tools will be buggy

if a mandatory prefix is choosen, I'll be happer it it is an other one

**Comment by jdegoes** [comment]
How about just:

```scala
kind Foo = Bar | Baz
```

& the like? If you want a type & value constructors of the same name, you can just define them separately via `data`. Seems more orthogonal that way.

**Comment by LiamGoodacre** [comment]
I currently don't like `kind Foo = Bar | Baz`; it'll be a pain to define all our useful data types twice.  It makes more sense to me to say that `data` defines a data type which can be used as values at runtime and in types at compile time where possible.  That is, I'm favouring auto-promotion.

I think primitives with literal syntax should keep the same syntax, in the same way that symbols reuse the syntax for strings.  However to support promoted boolean literals we'd have to disallow the use of type variables called `true` and `false` - similar to how you can't bind `true` and `false` in a `case`.

For the syntax of `data` types/constructors, I agree that the single-quote prefix isn't great.  Perhaps a caret `^Bar`?

**Comment by paf31** [comment]
The simplest thing we could do to start would be to allow `foreign import kind` declarations. That would let us build out the machinery needed and then decide if we still want/need promotion. Data type promotion could be built on top, and this way we avoid having to think about syntax and namespacing right now, so I prefer that option.

**Comment by LiamGoodacre** [comment]
How about importing kinds?

```purescript
import Type.Foo (kind Foo)
```

**Comment by LiamGoodacre** [comment]
Btw I'm having a go at implementing `foreign import kind`.  Works in a single module, just trying to get import/export working.

**Comment by paf31** [comment]
I'll close this in light of #2486 being merged, and we can open separate issues for any possible extensions.
