### ISSUE TITLE
Nullary function with guard breaks with where-bound helper function

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#920]
I'll fill this in when I can reproduce the weird error I just saw in a simple test case. This is just here as a reminder for me.

**Comment by paf31** [comment]
I can't remember what this was. I'll close it and maybe I'll run into it again.

**Comment by garyb** [comment]
Wasn't it talking about something like:

```
where
value
  | fn x = true
  | otherwise = false
```

Or do you mean you can't reproduce the error now?

**Comment by paf31** [comment]
I thought it was more like

```
f | x = 1
  where
  x = blah...
```

but I can't reproduce it.

**Comment by garyb** [comment]
Ah right, yeah that matches the description better.
