### ISSUE TITLE
Object property punning

### ISSUE THREAD

**Issue by dvdsgl** [purescript/purescript#921]
When creating or matching objects, I'd really love to be able to write `{ x }` as shorthand for `{ x: x }`:

```purescript
data Person = Person { name :: String, age :: Number }

instance showPerson :: Show Person where
  show (Person { name, age }) = name <> ", who is " <> show age <> " years old"

mkPerson name age = Person { name, age }
```

**Comment by Fresheyeball** [comment]
:+1: I miss this one from the dark dark coffeescript world from whence I came.

**Comment by garyb** [comment]
That's a little bit what worries me about it... I definitely like it for destructuring, but the "implicit assignment" part always bothered me. I guess ES6 has it too so it'll be attractive to JS devs in general, but yeah...

Thoughts @paf31? I think you already suggested this when I was working on the placeholders stuff, so I guess you'd be for it too?

**Comment by paf31** [comment]
I tend to use `RecordWildCards` quite a lot, and I like this style for destructuring too. For construction, I don't really feel strongly either way.

**Comment by dvdsgl** [comment]
I agree that the case for destructuring is much more forceful than for construction, but I urge you to consider both for the sake of symmetry.

**Comment by balajirrao** [comment]
I'm looking for an 'easy' bug to fix! Can I take this one ?

**Comment by paf31** [comment]
I'm still undecided on this one. I think I'd quite like `{x}` to mean `{ x: x }` but then you can't do the same for updates without running into ambiguous syntax.

**Comment by paf31** [comment]
But we have plenty of simple items @balajirrao. Check out the `easy` label in the issues list.

**Comment by balajirrao** [comment]
Thanks! Will ask on IRC.

**Comment by garyb** [comment]
@paf31: `obj { x }` or `_ { x }` should be distinguishable from `{ x }`, they don't use the same rules in the parser - I think it's a little confusing to read for updates, but it shouldn't be syntactically ambiguous?

**Comment by jdegoes** [comment]
Does `obj { x }` mean to form the object `{ x : x }` and pass it to the function `obj`, or does it mean to update the object `obj` with `{ x = x }`?

**Comment by garyb** [comment]
Ah! :bulb: 

Yeah, that's definitely ambiguous. It didn't occur to me when writing the example for some reason, even though I exactly illustrated the problem!

**Comment by paf31** [comment]
@balajirrao Here's something which would make a good first bug: improving how types and values appear in error messages. There are lots of opportunities there, from just renaming unification variables, to new formatting rules. I can describe more on IRC if you're still interested.

**Comment by dvdsgl** [comment]
Goodness! I did mean for `{x}` to mean `{x: x}` -- not `{x = x}`. That is very confusing!

**Comment by paf31** [comment]
Moving this to the current milestone.
