### ISSUE TITLE
Detect ambiguous type variables in contexts

### ISSUE THREAD

**Issue by pseudonom** [purescript/purescript#927]
``` purescript
module Foo where

class Foo a b where
  x :: a

--1

instance fooNumNum :: Foo Number Number where
  x = 1

--2

y :: Number
y = x
```

As far as I understand things, purescript should be able to tell there's a problem from just the code up through `--1`. However, it compiles that portion without complaint. It also compiles up through `--2`. It only throws the error:

```
Error in declaration y
No instance found for Foo.Foo Prim.Number u8
```

when all of the above code is included.

(However, I just checked and GHC exhibits the same behavior. Pretty minor peccadillo either way.)

**Comment by paf31** [comment]
What error do you think it should give at `--2`?

**Comment by pseudonom** [comment]
Hm. It doesn't seem like there's standard language around this. Something to the effect of `Invalid type signature for x; any use-site will be underconstrained`.

**Comment by paf31** [comment]
But a use-site can become constrained using a type signature, or if we ever introduce functional dependencies.

**Comment by pseudonom** [comment]
I'm not sure I follow. What type signature would ever make a use of `y` valid? Won't the type variable `b` in the class declaration always remain unconstrained?

And yes, functional dependencies would change the situation. So I think the problem is really in the class declaration (by `--1`), not the instance declaration (by `--2`).

**Comment by paf31** [comment]
Oh I see, sorry. Then I suggest this error message:

> Type variable `b` in instance head is not mentioned in the type of `y`.

**Comment by pseudonom** [comment]
Sounds good to me.

**Comment by pseudonom** [comment]
Though, if/when fundeps get added, 

> Type variable b in instance head is not mentioned in the type of x

isn't necessarily problematic. Maybe:

> Type variable b in instance head is ambiguous in the type of x

**Comment by paf31** [comment]
:+1:

**Comment by LiamGoodacre** [comment]
Closing as we've had a check for type class member usability for a while now.

This means that the declaration:

```purescript
class Foo a b where
  x :: a
```

Will fail to compile because `x` can't possibly be used.

Please reopen if there are further concerns here.
