### ISSUE TITLE
Inconsistent Syntax for Records

### ISSUE THREAD

**Issue by archaeron** [purescript/purescript#930]
I hope I'm not doing anything wrong, but it looks to me like if the update and the create syntax for a record are inconsistent.

Example:

```haskell
type Language = { country :: String, language :: String }
a = { country: "Switzerland", language: "Italian"}
b = a { language = "French" }
```

notice the `:` when creating a new record vs. the `=` when modifying an existing record.

**Comment by paf31** [comment]
Yes, this is by design. It's consistent with Haskell's syntax. Otherwise, you wouldn't be able to disambiguate function application from updates without typechecking first.

**Comment by archaeron** [comment]
yes, sorry. I just read https://github.com/purescript/purescript/issues/760
my mistake

**Comment by archaeron** [comment]
It still seems a bit confusing. Something like the F# `with`syntax is a lot easyer wo parse I think:

```fsharp
type MyRecord =
    { 
        field1 : int 
        field2 : int
    }

let defaultRecord1 = { field1 = 0; field2 = 0 }

// Use the with keyword to populate only a few chosen fields
// and leave the rest with default values.
let rr3 = { defaultRecord1 with field2 = 42 }
```

or Elms syntax:

```elm
{ defaultRecord1 | field2 <- 42 }
```
