### ISSUE TITLE
Switch between single/multi line mode at runtime

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#934]
In psci, it would be nice to switch between the two modes at runtime.

@paf31 prefers something like `:set multiline` to ghci's `:{ :}`, and I agree.

**Comment by hdgarrood** [comment]
I think we should copy scala's `:paste`, which enables multiline mode for the next command only.
So an example interaction could be:
```
> :paste
-- Entering paste mode. Press Ctrl-D to finish

if true
  then 1
  else 0
^D
-- Exiting paste mode
1
> 1 + 2
3
```
See http://alvinalexander.com/scala/how-to-enter-paste-multiline-commands-statements-into-scala-repl

**Comment by michaelficarra** [comment]
The CoffeeScript REPL allows toggling of single-/multi-line mode at any time using <kbd>Ctrl</kbd>+<kbd>v</kbd>. They are visually distinguished by changing the prompt. Functionally, the only difference between them is that commands are accepted in single-line mode through <kbd>Return</kbd>, and multi-line mode through <kbd>Ctrl</kbd>+<kbd>d</kbd>. This interface works really well, and I enjoy using it *much* more than psci.

Alternatively, node's REPL automatically goes into multi-line mode when the first line entered is a syntax error. This would work for a language where there's no ambiguity between an expression/declaration that has been finished and one that may continue, but even JavaScript does not conform to this, so this ends up being a pretty poor interface. But it's something to consider.

**Comment by joneshf** [comment]
Definitely agree on the cs repl!

**Comment by hdgarrood** [comment]
I didn't know about the CoffeeScript REPL, that does sound better. I just had a play with it and it seems like a command in multi-line mode is terminated with Ctrl-V, not Ctrl-D, though? Ctrl-D seems to exit the REPL.

Maybe we could copy CoffeeScript's approach in psci, except use Ctrl-D to terminate a command in multi-line mode instead of Ctrl-V, since psci already uses Ctrl-D to terminate multi line commands.

**Comment by paf31** [comment]
Sounds good, but I don't know how to handle `^V` in `haskeline`.

While we're at it, adding an interrupt handler for `^C` would be nice. I often mistakenly use it to try to kill long running `node` processes, but it just ends up killing `psci` instead. Something like `node` where you have to press `^C` twice to quite might be nice, and if evaluation in process, `^C` once to cancel it would be nice too.

**Comment by ecl3ctic** [comment]
This would be really nice to have. In GHCi a semicolon will let you write a multiline statement, but if PureScript isn't going to support that, a keyboard shortcut to switch modes would be a godsend.

**Comment by paf31** [comment]
I don't think we want the magic semicolon approach, but I'd be fine with switching modes, if we can make Haskeline do it.
