### ISSUE TITLE
Object.freeze records?

### ISSUE THREAD

**Issue by jimmydivvy** [purescript/purescript#940]
Purescript provides compile-time mutation guarantees, however this goes out the window as soon as you pass a record to external Javascript code - you cannot guarantee that a record isn't modified once outside Purescript. 

Is it possible for the purescript compiler to automatically wrap data constructors with `Object.freeze`? Any external modifications would then result in a runtime error instead of silently mutating an "immutable" object.

I'll attempt a pull-request for this functionality myself if there's interest, I just want to make sure this isn't something purescript is intentionally not doing or something already under way.

**Comment by michaelficarra** [comment]
When you give the PureScript compiler a signature for a foreign (JavaScript) value, you are making a promise to the compiler that the value is indeed of that type. If you have lied to the compiler, and told it a function has no effects when it does, all of its assumptions are broken. The behaviour at that point is undefined.

:-1:

**Comment by jimmydivvy** [comment]
This makes sense if you're working with a mostly purescript codebase and are simply calling a few JS functions that can easily be verified. In a mixed codebase it's not always as easy to provide that guarantee.

Obviously the goal would be to ensure correctness of external code as much as possible and purescript shouldn't have to handle impure external code behaving incorrectly - but since Object.freeze should be fairly easy to add to the compiler and would have minimal or no downsides, it seems reasonable to use it by default?

**Comment by michaelficarra** [comment]
If you don't trust the JavaScript code you're passing values to, you can always just `Object.freeze` them yourself. The compiler doesn't have to do this for you.

Also, `Object.freeze` is shallow, and only prevents writing new values to existing properties. You would also need to use `Object.seal` to ensure no other properties are added. Again, though, it is a shallow operation.

**Comment by garyb** [comment]
Does `Object.freeze` even work on "class" values (as in, non-anonymous objects)?

**Comment by michaelficarra** [comment]
It works on all objects. Objects are objects.

**Comment by Fresheyeball** [comment]
Are you saying that external javascript may modify the `Object` and screw up PureScript code?

**Comment by paf31** [comment]
Yes, @michaelficarra is right. The documentation is a little hard to find, but the book goes over what it means for an FFI declaration to have a particular type, and objects should not be modified by JS functions. If that's not guaranteed to be the case, you should wrap the function, copying/freezing the object as necessary.
