### ISSUE TITLE
1 < 0 == not (1 < 0)

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#957]
The above expression evaluates to true, somewhat surprisingly, as @Javran pointed out recently on IRC.

A module demonstrating the bug:

```purescript
module Main where

import Debug.Trace

main = do
  trace (show (not (1 < 0)))
```

And it compiles to:

```javascript
PS.Main = (function () {
    "use strict";
    var Debug_Trace = PS.Debug_Trace;
    var Prelude = PS.Prelude;
    var main = Debug_Trace.trace(Prelude.show(Prelude.showBoolean)(!1 < 0));
    return {
        main: main
    };
})();
```

Looks like it needs extra parens around `1 < 0`?

**Comment by garyb** [comment]
Looks like a precedence issue in the JS prettyprinter.

**Comment by hdgarrood** [comment]
I get the exact same output with `psc` version 0.6.0.2, so I guess this bug has been around a while
