### ISSUE TITLE
Should refEq be in Prelude.Unsafe?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#966]
Generally, I would expect that `a == b` implies `f a == f b` for any a, b, f, as long as you're not using the FFI.

But if we have:
```purescript
data Thing = Thing Number
instance eqThing :: Eq Thing where
  (==) (Thing x) (Thing y) = x == y
  (/=) x y = not (x == y)

a = Thing 0
b = Thing 0
f x = if x `refEq` a then true else false
```

then `a == b` but `f a /= f b`, and information about how `a` and `b` are laid out in memory is leaking into the program... I'm not sure if this is really a problem. It feels a bit like a subversion of the type system though. Just a thought.

**Comment by garyb** [comment]
They are definitely unsafe, but we can't move them into a module, as `Prelude` can't import other modules without ending up with a circular relationship.

I don't think `refEq` and `refIneq` need to be exported actually. I think perhaps `Data.Eq.Ref` used them (when we had that) but that was removed for the same reason that `refEq` and `refIneq` shouldn't be exported.

**Comment by paf31** [comment]
Just a thought:

```
refEq :: forall h a eff. STRef h a -> STRef h a -> Eff (st :: ST h | eff) Bool
```

i.e. `refEq` can be used to compare `ST` references inside a local block, but knowledge of the equality (or rather, its meaning - the particular references) can't escape the block.
