### ISSUE TITLE
Markdown docs for core libraries

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#972]
This will be a lot of work, but we should probably parallelize the work and get it out of the way. Quite a few are done already, but many of the large ones still need to be done.

## Short

- [x] `random`
- [x] `refs`
- [x] `globals`
- [x] `exceptions`
- [x] `validation`
- [x] `math`
- [x] `inject`
- [x] `coproducts`

## Medium 

- [x] `bifunctors`
- [x] `profunctor`
- [x] `graphs`
- [x] `lazy`

## Long

- [x] `transformers`
- [x] `free`
- [x] `maps`
- [x] `sets`
- [x] `quickcheck`
- [x] `tuples`
- [x] `foldable-traversable`
- [x] `strings`
- [x] `foreign`

## Needs Discussion (Laws etc.)

- [x] `control`
- [x] `distributive`

## Guidelines

- Try to document laws in type classes. If laws are not obvious or documented elsewhere, ask on IRC or here.
- Document functions, not type class instances. Laws on classes should be enough, unless there is something odd about a particular instance.
- Try to document asymptotics where appropriate.
- Try to give an example where possible.
- Use simple Markdown - no images, large nested lists, etc.
- For writing style, see the Prelude documentation.

Some are easy, some are not. If you'd like to help, please claim a library below, and send a PR.

Thanks!

**Comment by jdegoes** [comment]
Worth posting on the mailing list.

**Comment by paf31** [comment]
Done, good idea, thanks.

**Comment by paf31** [comment]
I'll take `bifunctors`.

**Comment by brainrape** [comment]
got math: https://github.com/purescript/purescript-math/pull/2
i'll take tuples next

**Comment by brainrape** [comment]
Tuples: https://github.com/purescript/purescript-tuples/pull/11
I'll go for strings next. Get the easy ones out of the way.

**Comment by paf31** [comment]
I'll take `profunctors`.

**Comment by paf31** [comment]
`graphs`

**Comment by paf31** [comment]
`lazy`

**Comment by paf31** [comment]
I'm just going to forego my usual "PR for everything" rule, and start checking in some docs to get this done. We can always go back and change them - this won't break anything.

`free`.

**Comment by hdgarrood** [comment]
I'll take `random`

**Comment by jasonzoladz** [comment]
Just submitted a PR for sets

**Comment by paf31** [comment]
Just for the record, I'm generating docs and putting them [here](http://functorial.com/psc-pages/docs/) as these changes get merged.

**Comment by paf31** [comment]
`foldable-traversable`

**Comment by paf31** [comment]
`refs`

**Comment by paf31** [comment]
`quickcheck`

**Comment by paf31** [comment]
`foreign`

**Comment by paf31** [comment]
`exceptions`

**Comment by paf31** [comment]
`inject`

**Comment by paf31** [comment]
`coproducts`

**Comment by paf31** [comment]
`validation`

**Comment by paf31** [comment]
`distributive`

**Comment by paf31** [comment]
Just the big 2 left: `transformers` and `control` :)

**Comment by brainrape** [comment]
strings and math should be good to merge

**Comment by paf31** [comment]
I'll take a stab at `transformers`, but I might need someone else to work on the comonad transformers docs. I think some examples would really help a lot there.

**Comment by paf31** [comment]
I'm just waiting on `transformers`, so I'll close this.
