### ISSUE TITLE
Generated Documentation should have a table of contents.

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript#983]
For example, the PureScript Prelude [documentation](https://github.com/purescript/purescript/tree/master/prelude) is almost a 1000 lines of text, and it's rather difficult to get a bird's-eye view of it.

This could be ameliorated by adding the Prelude.png image in some sort of file-level documentation comment, but the issue still remains for others. And for many projects, the generated docs are their only detailed documentation.

While hierarchical and thus beyond the scope of markdown docs, I think the [Rust docs](http://doc.rust-lang.org/std/vec/) provide a good example of easily navigable docs.

As an first step, a list of types, type classes, instances, and functions in each module could be printed at the top of the generated markdown.

**Comment by paf31** [comment]
This is what I hope Pursuit and `psc-pages` will solve.

**Comment by alexchandel** [comment]
Cool, pages? On a related note, it seems strange to me that the top header of generated docs says `Module Documentation`, when in fact the document may hold several modules' worth of documentation.

**Comment by paf31** [comment]
True :) Feel free to remove that, I won't be sad to see it removed.

**Comment by paf31** [comment]
`psc-pages` demo: functorial.com/psc-pages/docs/

**Comment by paf31** [comment]
Solved by Pursuit.
