### ISSUE TITLE
Invalid JS for self-referencing class instance.

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#984]
In an instance declaration, if we refer to a different member of the instance, semantically invalid JavaScript is generated.

I managed to reproduce this issue with the following code:

~~~purescript
module Main where

class C a where
  foo :: a
  bar :: a

instance p :: C Unit where
  foo = unit
  bar = foo
~~~

The following is generated:

~~~javascript
var PS = PS || {};
PS.Prelude = (function () {
    "use strict";
    return {
        unit: unit
    };
})();
var PS = PS || {};
PS.Main = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    function C(bar, foo) {
        this.bar = bar;
        this.foo = foo;
    };
    var foo = function (dict) { return dict.foo; };
    var bar = function (dict) { return dict.bar; };
    var p = new C(Prelude.unit, bar(p));
    return { C: C, bar: bar, foo: foo, p: p };
})();
~~~

The important line is that which introduces `p`:

~~~javascript
var p = new C(Prelude.unit, bar(p));
~~~

It refers to itself before it has been initialized!

---

I generated this on the [Try PureScript](http://try.purescript.org/compile/html) webpage - I don't know how up to date that is or if this is still an active bug.

**Comment by paf31** [comment]
Yes, this is a known bug sadly. I was going to mark as a duplicate but I can't find the original.

Thanks!

**Comment by pseudonom** [comment]
> I can't find the original

It's the same as these, right? 
https://github.com/purescript/purescript/issues/941
https://github.com/purescript/purescript/issues/365

**Comment by paf31** [comment]
Yes, thanks!
