### ISSUE TITLE
Docgen should use purescript as default language for code blocks in docstrings

### ISSUE THREAD

**Issue by brainrape** [purescript/purescript#988]
Long code blocks in docstrings have to specify the code blocks' language (almost always `purescript`) to get syntax highlighting. The documentation generator should automatically set the blocks' language to purescript if no language is specified.

**Comment by garyb** [comment]
I'm not sure, I see two kind of problems with that:

1. Currently we don't parse the markdown comments, just pipe them through as-is so can't really safely make that transformation
2. Doing this would make it impossible to make a "just text" monospaced block wouldn't it?

**Comment by brainrape** [comment]
Valid concerns, maybe another approach would work, like a separate comment character for purescript code blocks?
```
-- | comment
-- |>  purescript code block
```

**Comment by paf31** [comment]
If the goal is just to include the word `purescript`, then I'm not sure it's worth the complexity, since we only have to do it once per code sample.

**Comment by garyb** [comment]
Actually thinking about it, on point 2, probably just using `text` after the opening backticks would work.

**Comment by brainrape** [comment]
Leaving the problem of having to parse the markdown, although 
```
s/^```$/```purescript/ 
```
should be all that's needed for the opening tag.

**Comment by garyb** [comment]
That'd catch the closing tag too, no?

**Comment by brainrape** [comment]
Meh, would still need parsing. Hey, at least we can write `purescript` while we're writing PureScript.
