### ISSUE TITLE
Typeclass Resolution Seems Off

### ISSUE THREAD

**Issue by cabrera** [purescript/purescript#995]
I ran into this error today:

```purescript
> [1] ++ [2]
Error in module $PSCI:
Error in value declaration it:
No instance found for Prelude.Semigroup [Prim.Number]
See https://github.com/purescript/purescript/wiki/Error-Code-NoInstanceFound for more information, or to contribute content related to this error.
```

I'm running version 0.6.9.3:

```purescript
alejandro@parametric:~:$ psci --version
0.6.9.3
```

My expectation was that `(<>)` and `(++)` would be able to unify for `[a]` for any `a`. Am I misunderstanding something somewhere?

Thanks!

**Comment by garyb** [comment]
I think the `Semigroup` instance for `Array` is only defined in `Data.Array` from `purescript-arrays`, have you imported that?

**Comment by cabrera** [comment]
Ah! There we go. Yeah, that was me breaking things. :)

Thanks for the quick reply!
