### ISSUE TITLE
Generic math functions in Prelude

### ISSUE THREAD

**Issue by reuben364** [purescript/purescript#997]
Some math functions can be implemented generically

    abs, sign :: forall a. (Ord a, Ring a) => a -> a
    gcd, lcm :: (Eq a, ModuloSemiring a) => a -> a -> Maybe a
    
should any of these be in Prelude?

**Comment by garyb** [comment]
I think they still belong in `Math` or something like that. We're moving towards eliminating the `Prelude`, so adding more stuff in would be a step backwards at this point.

**Comment by reuben364** [comment]
Currently Math is purely an interface to the Math object in JavaScript. If it is added to Math, then should all math functions with a more generic version be replaced, or should there be a specific submodule for generic functions.

**Comment by garyb** [comment]
If anything it should probably be the other way around - `Math` containing generic functions and then a submodule for the monomorphic/JS specific functions.

To take full advantage I guess ideally we'd want to do some kind of `Math` class instead (or collection of classes) so the functions could be specialised based on implementation. That's a much bigger project of course, but our current `Math` implementation is going to need an overhaul at some point to accommodate changes coming in the FFI in 0.8, and as you've noticed is already less than ideal now we have a decent numeric class hierarchy.

**Comment by garyb** [comment]
I'm sure @paf31 / @joneshf / @jdegoes will have thoughts on this too.

**Comment by paf31** [comment]
I'm happy to keep `Math` the module as a low level wrapper, but now that we're getting more interesting abstractions in the form of classes, we could add new functions to go with them. Whether they go in `Math` the package or elsewhere, I don't mind, but `Math` should probably stay relatively dependency-free IMO.

**Comment by reuben364** [comment]
Math can always be segmented into different packages
Math.Foreign with no outside dependencies and
Math.Abstract that allows for the most *complete* hierarchy to be used.

**Comment by jdegoes** [comment]
On principle, I prefer abstract versions. That said, I think this library is trying to be the PureScript version of Javascript's `Math` object, i.e. it should be 100% FFI. 

Then we need something like Spire for PureScript that contains "everything else", well abstracted and using a lot of PureScript code and some FFI code like this library.

**Comment by michaelficarra** [comment]
I don't see any value in a pure-FFI library for the `Math` object. Expose useful maths functions. If a function happens to be implemented as direct FFI to the `Math` object, great. Most functions won't, though, and that is okay.

**Comment by natefaubion** [comment]
Perhaps if we are doing 100% FFI libraries, we should namespace them under their respective languages.

**Comment by garyb** [comment]
Agreed, maybe there is room for a 100% JS FFI `Math` library, but I not sure something named `purescript-math` should be it.

**Comment by paf31** [comment]
I see the point of a FFI module, especially if we plan to move to multiple backends. It would become the spec for the math functions we want to support across other backends, but it should be minimal enough that every backend should be able to support them.

@natefaubion Naming by language is certainly one option, but I think I'd prefer to move the JS out and just keep the type signatures, so that the same module can be used across backends.

**Comment by natefaubion** [comment]
@paf31, oh sure, if you want a common interface that's supported by FFI. I was thinking more if the interface was tied to a particular language (like `Math` in JS).

**Comment by jdegoes** [comment]
FFI libraries have their place. If `purescript-math` were more than FFI, then it would have to form an *opinion* on what a proper math library looks like; and others would disagree with this. So multiple libraries would end up writing their own FFI code.

The point of FFI libraries is to have a non-opinionated way to access raw functionality, which other more opinionated libraries can build on. I'll grant it's a problem in a cross-backend PureScript world, though.

**Comment by paf31** [comment]
This belongs on the Project Ideas section of the wiki, or in the `purescript-math` issues list. I think some generalized functions would be nice to have, but in a library.
